# stardustdescends_ep02.gd - 星尘降临篇第2话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep02_script()

func play_script():
	pass

func stardustdescends_ep02_script():
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_VillaHall.png")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("이, 이백만！？", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("갑자기 “서민 소녀가 귀족 학교에서 골동 꽃병을 부숴”같은 화면이 머릿속을 스친다.")
	novel_interface.show_character("ren_full","sob")
	await novel_interface.show_dialog("（펴, 평생 아르바이트해서 갚아야 하는 건 아니겠지！！）", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("이 의자를 배상하려면 메이드 카페에서 얼마나 일해야 하는지 몰래 계산하고 있을 때, 닉스 선배가 내 턱을 든다.")
	novel_interface.show_character("ren_full","sob")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_full","normal1",0.25)
	await novel_interface.show_dialog("학교에서 널 봤을 때 순진해 보였는데……", "닉스")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("그녀가 고개를 틀어 내 귀에 걸려있던 기계를 발견한 후 미소를 짓는다.")
	novel_interface.show_character("ren_full","sob")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("이렇게 귀여운데, 예쁘게 화장해야지~", "닉스")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("뭐, 뭘 하려는 거지！？")
	await novel_interface.show_text_only("이때，검은 양복을 입은 건장한 보디가드가 날 향해 걸어온다.")
	novel_interface.show_character("ren_full","sob")
	await novel_interface.show_dialog("（망했다……）", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("모두 물거품이 됐다. 방금 나의 자연스러운 행동들이 꽤 멋있다고 생각했었는데, 완전히 들켜버렸어!")
	novel_interface.show_character("nyx_full","smile")
	await novel_interface.show_dialog("방금 놀라지 않았지──?", "닉스")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("선배가 갑자기 말투를 바꾸고 덤덤한 표정으로 내 귀에서 빼낸 이어폰을 손에 쥐어준다.")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("엣?", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("그녀가 일부러 다정하게 나의 머리를 쓰다듬으며 등 뒤에 있는 보디가드에게 차갑게 말한다.")
	novel_interface.show_character("ren_full","panic")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_full","sad",0.25)
	await novel_interface.show_dialog("이 아이는 사쿠라가와 후배예요. 우연히 만났을 뿐이에요.", "닉스")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("그 중 한 사람이 휴대폰으로 날 스캔한 후 스크린 결과를 보고 고개를 끄덕인다. ")
	await novel_interface.show_text_only("다른 한 사람은 바닥에 쓰러진 교수 옆으로 걸어가 의자를 살펴본다.")
	await novel_interface.show_text_only("닉스가 갑자기 내 뒷목을 잡고 서로의 체온을 확인하는 것처럼 서로의 이마를 붙인다──")
	novel_interface.show_character("ren_full","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","mock",0.25)
	await novel_interface.show_dialog("정신차려.", "닉스")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("선배의 명령 같은 말투에 긴박함이 묻어나있다. 그녀의 호흡이 나의 얼굴에 닿는다.")
	novel_interface.show_character("ren_full","awkward")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("nyx_full","mock",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（얼굴이……너무 가까워！）", "렌")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("제자리에 굳어 당황하고 있을 때 머릿속에 한가지 의문이 스쳐지나간다──")
	await novel_interface.show_text_only("선배가 왜 여기 있지？도박장의 손님인가? 정보를 거래하러 온 건가? 타겟이 그녀와 관련 있을까?")
	await novel_interface.show_text_only("의자의 역사와 가격을 알고 있는 걸 보니 이곳에 익숙해 보인다. 설마 이 장원의 주인일까?")
	await novel_interface.show_text_only("그런데 저 보디가드들은 어떻게 된 거지？\n그리고 이 이상한 분위기는……")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_text_only("선배의 눈을 바라보니 심장이 점점 더 빨리 뛴다. 그 옅은 붉은 눈에 빨려 들어갈 것 같다.")
	novel_interface.change_expression("sad")
	await novel_interface.show_text_only("그녀가 곁눈질로 보디가드를 관찰하다 갑자기 날 쳐다본다. 눈이 마주치자 무의식적으로 시선을 피했다──")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("잠깐, 이 각도에서 아래를 쳐다보면……")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("선배가 입은 드레스의 가슴 부분은 이런 디자인이구나……")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_text_only("보일듯 말듯한 레이스를 쳐다보니 심장이 격렬하게 뛰기 시작한다. 열기가 갑자기 대뇌를 펌프질 하는 것 같다.")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("귀가 빨개지고 눈 앞이 흐려진다……")
	novel_interface.show_character("nyx_full","sad")
	await novel_interface.show_dialog("렌……？", "닉스")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_dialog("왜 그래?", "닉스")
	await novel_interface.show_dialog("뭘 멍하니 서있어요? 빨리 도와줘요！", "닉스")
	await novel_interface.show_dialog("우선 방으로 옮기죠……", "닉스")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("…………")
	novel_interface.change_music("res://assets/audio/music/Noise.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Spot.png")
	await novel_interface.show_text_only("…")
	await novel_interface.show_text_only("저기~")
	await novel_interface.show_text_only("아직 기억해?")
	await novel_interface.show_text_only("누구지?")
	await novel_interface.show_text_only("끝없는 어둠 속에 갑자기 금색 빛이 나타나 주위를 환하게 비춘다.")
	await novel_interface.show_text_only("기억하다니……무엇을？")
	await novel_interface.show_text_only("널 기다리고 있어……")
	await novel_interface.show_text_only("약속한 곳에서")
	await novel_interface.show_text_only("약속한……")
	await novel_interface.show_text_only("곳？")
	await novel_interface.show_text_only("잠깐, 너는──")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("──！！")
	await novel_interface.show_text_only("…")
	await novel_interface.show_text_only("이봐!")
	await novel_interface.show_text_only("이봐──！！")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_NoxRoom.png")
	await novel_interface.show_dialog("정말 곤히 자는구나……침까지 흘리면서.", "닉스")
	novel_interface.show_character("ren_full","wry_smile")
	await novel_interface.show_dialog("하……?", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("느릿느릿 눈을 뜨니 크고 부드러운 침대 위에 누워있다.")
	await novel_interface.show_text_only("보라색 침대 틀, 검은색 실크 소재의 침대 가구에 고급스런 광택이 흐른다. ")
	await novel_interface.show_text_only("선배가 침대 옆에 앉아 작은 동물을 쳐다보는 눈빛으로 날 내려다보고 있다.")
	await novel_interface.show_text_only("베개가 침에 젖어있다. 더 중요한 것은 두 다리를 벌어져있고, 치마가 허리까지 말려 올라갔다는 것이다.")
	await novel_interface.show_text_only("아, 선배의 침대에서 잠들었구나…")
	novel_interface.show_character("ren_full","wail")
	await novel_interface.show_dialog("（잠깐, 선배의……침대！？）", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("아까까지 그 별장에 있었는데？！그리고 그 건장한 보디가드 두 명도 있었어……")
	await novel_interface.show_text_only("급히 다리를 오므리고 치마를 내린 후 무릎을 감싸고 침대 끄트머리에 숨어 닉스를 경계하며 쳐다봤다.")
	await novel_interface.show_text_only("방 안에 다른 사람은 없었다. 한쪽 벽은 두꺼운 보라색 커튼이 빛을 차단하고 있다.")
	await novel_interface.show_text_only("전등 장식, 벽지, 가구가 방금 그 복고풍 장원과 완전히 다르다. 바닥에 튼튼한 회색 카펫이 깔려있다.")
	novel_interface.show_character("ren_full","shy")
	await novel_interface.show_dialog("（내가 쓰러졌나？도대체 얼마나 누워있었지！）", "렌")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("여긴 어디예요？나, 날 어떻게 한 거예요！", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("선배가 떠는 날 보며 웃으며 몸을 일으킨다.")
	novel_interface.show_character("nyx_full","mock")
	await novel_interface.show_dialog("오호?", "닉스")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("그녀가 한쪽 무릎을 침대 위에 놓고 몸을 날 향해 기울인다.")
	novel_interface.show_character("nyx_full","mock")
	await novel_interface.show_dialog("네 생각에……내가 방금 어떻게 했을 것 같아?", "닉스")
	await novel_interface.show_dialog("렌 후배님──", "닉스")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","perspire1")
	await novel_interface.show_dialog("바, 방금？！", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("얼굴이 달아오른 나는 이불을 침대 머리까지 끌어당겼다. 바, 방금 나한테 뭘 한 거야!")
	await novel_interface.show_dialog("그만 놀려~", "마리루")
	await novel_interface.show_text_only("가슴에서 갑자기 울리는 목소리가 나와 선배를 놀래켰다.")
	await novel_interface.show_dialog("그럼, 방금 말한 것처럼──", "마리루")
	await novel_interface.show_dialog("준비가 끝나면 언제든지 움직여도 좋아.", "마리루")
	await novel_interface.show_text_only("닉스가 더 다가오지 않고 침대에 앉아 나의 가슴을 응시하며 천천히 고개를 끄덕인다.")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("（움직여？）", "렌")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("잠깐, 두 사람, 뭘 말했다는 거야？", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("왜 또 속은 느낌이지!")
	novel_interface.show_character("ren_full","panic")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("네가 쓰러진 척 하는 줄 알았는데, 정말 잠들었을 거라곤 생각도 못했어……", "닉스")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("선배가 자세를 풀고, 나도 천천히 이불을 놓았다. ")
	novel_interface.show_character("ren_full","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("렌 같은 어린애가 SID에 가입했을 줄은 몰랐어~", "닉스")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("실수로 이상한 조직에 가입한 거라구요.")
	novel_interface.show_character("ren_full","upset")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("잠깐, 내가 쓰러졌어？", "렌")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("기억 속 마지막 장면을 떠올려봤다. 설마 그걸 봐서──")
	novel_interface.show_character("ren_full","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（그, 그렇게 민망한 정도는 아니잖아?）", "렌")
	await novel_interface.show_dialog("（평소에 샤워할 때도 자주 보는데 뭐……）", "렌")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("안심해. 여긴 내 방이야. 우린 아직 장원 안에 있어.", "닉스")
	await novel_interface.show_dialog("넌 한 시간 동안 잠들었었어.", "닉스")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("소리를 지르려고 하자 선배가 내 입을 막는다. ")
	novel_interface.show_character("ren_full","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","sad",0.25)
	await novel_interface.show_dialog("쉿── 조용히. 방음은 괜찮지만 이 방에서 소리가 절대 새지 않는 건 아니고, 그 두 명이 아직 문 앞에 서 있어.", "닉스")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("나는 뒷말을 급히 목 뒤로 삼키고 얌전히 고개를 끄덕였다.")
	novel_interface.show_character("ren_full","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("흔들어도 일어나지 않았어. 마리루가 네 신체 지수가 정상이라고 얘기해주지 않았다면 구급차를 불렀을 거야.", "닉스")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("선배……마리루를 알아요?", "렌")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("방금 알게 됐어──", "닉스")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("닉스가 웃으며 귀에서 골전도 이어폰을 꺼낸다.")
	await novel_interface.show_dialog("내가 다시 설명하는 것보단 네가 알려주는 게 좋겠어.", "마리루")
	await novel_interface.show_text_only("선배가 잠시 머뭇거린 후 결심을 내린 듯 고개를 들어 내 눈을 바라본다. ")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_dialog("난 어렸을 때 어머니가 돌아가셔서 어머니에 대한 기억이 별로 없어. 아버지가 줄곧 날 키우셨어", "닉스")
	await novel_interface.show_dialog("아버지는 크리스토퍼 스트로치, 제6학원도시의……아니, 당시엔 아직 레보나 아일랜드였지──", "닉스")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("선배가 잠시 말을 멈추고 적당한 단어를 생각한다.")
	novel_interface.show_character("nyx_full","smile")
	await novel_interface.show_dialog("원로원 수석 정권 같은 역할이야. ", "닉스")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","happy")
	await novel_interface.show_dialog("네──？", "렌")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("어, 엄청 대단하잖아요!", "렌")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_LiberNa.png")
	await novel_interface.show_text_only("제6학원도시──레보나 아일랜드.")
	await novel_interface.show_text_only("15년 전 이물질 폭발로 안다만 해 동쪽 육지가 몇십일 안에 수천개 크고 작은 섬으로 갈라졌다.")
	await novel_interface.show_text_only("변이가 멈추기 전에 주변 국가들이 그 섬의 소속권을 두고 분쟁하기 시작했다.")
	await novel_interface.show_text_only("각국의 해군이 자주 마찰이 있긴 했지만 민감한 시기에 강제로 섬을 점령하는 것은 전쟁을 선포하는 것이나 다름없었다.")
	await novel_interface.show_text_only("그 결과 누구도 이 구역을 제어하지 못했다──이곳은 국제 무역의 필수 항로가 있는 섬으로 주인 없는 섬이 됐다.")
	await novel_interface.show_text_only("구분되지 않은 육지는 범죄인을 인도하지 않아 각국의 지명수배 범죄자와 탈영병이 가장 먼저 이곳에 왔다.")
	await novel_interface.show_text_only("이곳은 레보나（LiberNa）, 자유의 국가（LiberNation）라는 의념으로 사람들에게 각인됐다. ")
	await novel_interface.show_text_only("훗날 정부 세력이 없는 조직과 세력 단체들이 줄지어 이곳에 왔고, 번화한 해상 무역으로 이익을 나눴다.")
	await novel_interface.show_text_only("지금까지 레보나는 여러 조직이 돌아가며 관리하고 있다.")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_NoxRoom.png")
	await novel_interface.show_text_only("그 말은 즉……")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("（선배의 부친은 교부 같은 역할인가？！）", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("nyx_full","sad")
	await novel_interface.show_dialog("아버지는 혼란스런 레보나 아일랜드에 규칙과 질서를 세워 민물조차 찾을 수 없는 섬을 번화한 도시로 만들었어.", "닉스")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("선배가 단호한 말투로 애기했지만 목소리가 조금 떨린다. 무언가 회상하는 듯 벽지 위 금색 무늬를 바라본다.")
	novel_interface.show_character("nyx_full","sad")
	await novel_interface.show_dialog("그리고 아버지는 전쟁 시기에 사고에 휘말려 실종됐어.", "닉스")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("……", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("그 말을 뱉은 선배가 평소보다 침착해 보인다. 하지만 난 이런 상황에 아주 익숙하다.")
	await novel_interface.show_text_only("전쟁 기간의 “실종”은 백분의 백, 사망이라고 볼 수 있다──")
	await novel_interface.show_text_only("자신의 가족이 살아있다고 믿는 사람들은 계속해서 단호하고 침착한 말투로 자신에게 말한다.")
	await novel_interface.show_text_only("그들은 죽지 않았어. 실종된 것 뿐이야……")
	await novel_interface.show_text_only("설령 모든 파일에“사망 추측”이라고 적혀있어도.")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_dialog("뒷 이야기는 모두 뻔하다──", "닉스")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("선배가 이어서 말한다. ")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_dialog("다른 몇몇 조직들이 권력이 비어있는 틈을 타 우리 가문의 재산과 권력을 뺏으려 했어.", "닉스")
	await novel_interface.show_dialog("아버지가 안 계셔도 여전히 많은 사람들이 스트로치 가문에 충성하길 원했지.", "닉스")
	novel_interface.change_expression("sad")
	await novel_interface.show_dialog("하지만 당시 그 사람들의 충성은 날 더 위험하게 만들었어.", "닉스")
	await novel_interface.show_dialog("난 가문의 사업에 관여할 생각이 없다는 걸 증명하기 위해 레보나 아일랜드를 떠나 신토요스에 온 거야.", "닉스")
	await novel_interface.show_dialog("하지만 그들은 여전히 안심할 수 없었어──", "닉스")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("닉스가 대문을 바라보며 말한다. 그 보디가드 두명은 선배를 감시하고 있었던 거구나.")
	novel_interface.show_character("nyx_full","sad")
	await novel_interface.show_dialog("나는 학교 근처 작은 구역 안에서만 자유롭게 움직일 수 있었어. 다른 곳에서는 모두 감시를 당했거든.", "닉스")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("3년 전, 아버지의 인맥으로 천천히 스트로치 가문의 유럽과 서아시아의 지하 거래망을 회복시켰어.", "닉스")
	await novel_interface.show_dialog("그리고 현재 레보나를 책임지고 있는 홍선생에게 연락해 거래를 제안했지──", "닉스")
	await novel_interface.show_dialog("난 지하 거래망으로 그의 유럽 사업을 돕고 그는 내가 장원에 사는 것을 허락했어─물론, 홍선생의 감시 아래서.", "닉스")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("이곳은 원래 아버지의 것이긴 하지만……", "닉스")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("잠깐만요. 조금 혼란스러워요.", "렌")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("그러니까, 선배 아버지가 사들인 이 장원이 지금은 제6학원도시 정부 소유라고요?", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("레보나와 원로원의 “비밀 조약”이라 볼 수 있지……", "마리루")
	await novel_interface.show_dialog("이 세계는 전쟁에서 회복된 지 얼마 되지 않아 공개할 수 없는 거래들이 상당히 많이 존재해.", "마리루")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("지하 암시장 같은 거?", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("수요가 있으면 시장이 생기고, 시장이 생기면 돈을 벌 수 있는 거야.", "마리루")
	await novel_interface.show_text_only("어쩐지 이곳을 사들이려고 하더니! ")
	await novel_interface.show_text_only("주위를 둘러보니, 방 안에 고급 가구들이 배치돼있다. 하지만 아무도 머문 적이 없는 객실 같다.")
	await novel_interface.show_text_only("1년 내내 감시와 염탐을 당하는 건 이런 기분일까……")
	novel_interface.show_character("nyx_full","smile")
	await novel_interface.show_dialog("너희들이 오늘 정보를 캐내려던 그 사람은 화운궁 대학의 역사학 교수 시온이야.", "닉스")
	await novel_interface.show_dialog("뭔가 낌새를 느꼈는지 매수자가 약속을 여겼어. 10분 전 그도 화를 내며 떠났어.", "닉스")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("그 녀석이 장원을 떠나고 첫번째 길에서 우리에게 회수됐어. 지금은 마취 중이야.", "마리루")
	novel_interface.show_character("ren_full","stare")
	await novel_interface.show_dialog("미리 알았으면 헛수고할 필요 없었을텐데……", "렌")
	await novel_interface.show_dialog("（몇시간 동안 태도 수업을 듣게 하다니, 그 누나들의 조롱을 받으며 어제 꿈에서도 허리를 꼿꼿히 세우고 있었다구……）", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("아직 분석 중이긴 하지만 만약 시교수의 정보가 정확하다면 스트로치 가문의 유럽과 서아시아 자원을 사용할 수 있어.", "마리루")
	await novel_interface.show_text_only("그러니까, 내가 잠든 사이에 선배와 아이디어를 나눴다고?")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("이해가 안되는 게 두가지 있어요──", "렌")
	await novel_interface.show_dialog("만약 그들이 선배를 믿지 못한다면 어째서……", "렌")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("어째서 날 죽이지 않냐고?", "닉스")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("닉스가 표정을 풀고 나의 질문을 보충한다.")
	novel_interface.show_character("ren_full","upset")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("아버지가 재정한 《레보나 금령》에 따라 어떤 조직도 다른 조직의 수령과 가족을 해칠 수 없어.", "닉스")
	await novel_interface.show_dialog("그래서 최대한 날 가둬놓고 공동으로 돈을 지불해 나의 생활을 보장하는 거야. ", "닉스")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("그렇게 규칙을 잘 지킨다고요！？", "렌")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("공무원보다 복지가 더 좋잖아！")
	await novel_interface.show_dialog("상당히 똑똑한 설계야──폭력 단체 간의 투쟁을 피할 수 없지만 최소한 한계선을 설정했어.", "마리루")
	await novel_interface.show_dialog("한계선이 세워지면 누구도 그 규칙을 깨지 않으려고 하지. 스스로의 최종 보험과 면죄부를 위해.", "마리루")
	await novel_interface.show_dialog("입헌, 법치, 다당제의 교대, 정기 선거, 그리고 최소한의 선을 지키는 것……", "마리루")
	await novel_interface.show_dialog("많은 나라들이 정치 체제 개혁에 실패했는데, 법 밖의 자들이 자발적으로 해냈다는 게 참 아이러니해.", "마리루")
	novel_interface.show_character("ren_full","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("렌이 레보나 아일랜드에 대해 오해한 모양이야~", "닉스")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("여러 조직이 공동으로 관리하고 곳곳이 암시장, 도박장 같은 장소가 널린 나라겠지……")
	novel_interface.show_character("ren_full","uneasy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（나라 전체가 18세 이하 출임 금지 같은 느낌이랄까……）", "렌")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("사실 레보나 아일랜드의 범죄율은 6개 학원도시 중에 가장 낮아~", "닉스")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("아?", "렌")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("폭력 조직들의 존재 전제가 바로 준법 환경이야──", "닉스")
	await novel_interface.show_dialog("법률과 변호사의 보호가 없고 증거가 없는 상황에서 정부가 눈에 거슬리는 개인과 조직을 처리할 수 있어.", "닉스")
	await novel_interface.hide_all_characters()
	await novel_interface.show_dialog("그래서 그 조직원들도 국가의 주인이 된 후 가혹한 형법과 법률을 강요하지.", "마리루")
	await novel_interface.show_dialog("이런 이념 덕분에 레보나가 오늘의 번영을 얻게 된 거야.", "마리루")
	await novel_interface.show_text_only("마리루의 설명을 듣고 아는 듯 모르는 듯 고개를 끄덕였다. ")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("그리고 마지막 질문이 있어요……", "렌")
	await novel_interface.show_dialog("SID와 협력해서 선배가 얻고자 하는 게 뭐죠？", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("닉스가 진지하게 날 쳐다보며 말한다──")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_dialog("자유.", "닉스")

	print("=== 星尘降临篇第2话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
