# stardustdescends_ep15.gd - 星尘降临篇第15话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep15_script()

func play_script():
	pass

func stardustdescends_ep15_script():
	novel_interface.change_music("res://assets/audio/music/Wind.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_StarrySky.png")
	await novel_interface.show_text_only("Возьми мою любовь, возьми мою землю")
	await novel_interface.show_text_only("Возьми меня туда, где я не могу стоять")
	await novel_interface.show_text_only("Мне все равно, я все еще свободен")
	await novel_interface.show_text_only("Ты не можешь отобрать у меня небо")
	await novel_interface.show_text_only("Выведи меня в черноту")
	await novel_interface.show_text_only("Скажи им, что я не вернусь")
	await novel_interface.show_text_only("Сожгите землю и вскипятите море")
	await novel_interface.show_text_only("Ты не сможешь отобрать у меня небо...")
	await novel_interface.show_text_only("— Музыкальная тема из «Светлячка»")
	await novel_interface.stop_music()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("Рядом с шоссе за пределами Масады.")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Sways.png")
	await novel_interface.show_text_only("После захода солнца пустыня быстро потемнела, и мы выбрались на уединенную дорогу за городом.")
	await novel_interface.show_text_only("Вера поменяла номерной знак грузовика, а я помог Эмили закрыть грузовую платформу сеткой для подавления массовых беспорядков с маркировкой Сил национальной обороны.")
	await novel_interface.show_text_only("Очевидно, что с неразорвавшимися боеприпасами, минами и другими опасными предметами часто приходится обращаться за пределами города, поэтому люди стараются держаться подальше от военных грузовиков, покрытых такими защитными сетками.")
	await novel_interface.show_text_only("Режим автономного вождения грузовика был настроен следовать за нами. Через некоторое время он догонит наш БТР в город.")
	await novel_interface.show_text_only("Возможно, потому, что в тот день мы вместе пережили околосмертный опыт, отношения между похитителем и заложником постепенно превращались в соучастников.")
	await novel_interface.show_text_only("По дороге сюда мы праздно болтали. Я рассказал им о студенческой жизни и разнообразной еде в Нью-Тойосу, а они рассказали мне много забавных историй из военной школы.")
	await novel_interface.show_text_only("Оказалось, что Вера и Эмили были не намного старше меня. Вы могли бы назвать нас сверстниками, но мы прожили совершенно разные жизни...")
	await novel_interface.show_text_only("Во время Семилетней войны Масаде не хватало рабочей силы, и он начал отбирать студентов прямо из средней школы для обучения в более финансируемых военных академиях.")
	await novel_interface.show_text_only("В двенадцать лет Эмили самостоятельно поступила в военное училище с полным пансионом, просто чтобы сбежать из душного дома.")
	await novel_interface.show_text_only("Тем временем Веру в раннем возрасте отправили в Академию штабов Кэмберли, потому что ее отец был высокопоставленным чиновником ВВС.")
	await novel_interface.show_text_only("После тридцати месяцев академических курсов и военной подготовки они оба в одном и том же году подали документы в самую элитную военную академию Масады «Башня».")
	novel_interface.show_character("ren_medical","perspire1")
	await novel_interface.show_dialog("«Башня» — это тот фильм, у которого процент одобрения ниже одного процента...?", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("Да. Вера даже сменила фамилию, когда подала заявку, просто чтобы доказать, что она может поступить без семейных связей. Это бесконечно разозлило ее отца.", "Эмили")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("«Даян» — не такая уж и редкая фамилия, но ей просто пришлось переименовать себя во что-нибудь столь же раздутое, как «Валькирия»…", "Эмили")
	await novel_interface.show_dialog("Когда список кандидатов, вошедших в шорт-лист, был опубликован, ученики и родители спрашивали, кем должна была быть эта девочка-Валькирия.", "Эмили")
	await novel_interface.show_dialog("Она стояла прямо в толпе, опустив голову, ярко краснея. Честно говоря, это было немного жалко~", "Эмили")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ах, я понял! Такая мучительная публичная казнь чуни!")
	await novel_interface.show_text_only("Подождите, а почему я это понимаю...?")
	novel_interface.show_character("valkyrja","shy")
	await novel_interface.show_dialog("Хватит говорить!!!\nЯ поменяю его обратно после окончания школы...", "Вера")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("Ни за что, мне это нравится...", "Эмили")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","blush")
	await novel_interface.show_dialog("А?", "Вера")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("Во время этого экзамена по рукопашному бою все, что мне нужно было сделать, это кричать «Леди Валькирия» на ринге, и Вера мгновенно теряла самообладание.", "Эмили")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","shy")
	await novel_interface.show_dialog("Заткнись!!\nНе называй меня так...", "Вера")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("Лиан, помоги натянуть сюда противовзрывную сеть!", "Вера")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","smile")
	await novel_interface.show_dialog("Да, леди Валькирия. Нет проблем, леди Валькирия.", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","shy")
	await novel_interface.show_dialog("Эй!!", "Вера")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("Пффф-хахахахахахахахахахахахаха~", "Эмили")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","shy")
	await novel_interface.show_dialog("Почему вы продолжаете учить детей таким вещам?!", "Вера")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("К тому времени, как под смех и подшучивание мы закончили приготовления, уже совсем наступила ночь.")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_SlumArea.png")
	await novel_interface.show_text_only("БТР вошел в город через старую промышленную зону на восточной стороне и медленно направился к месту недалеко от изоляционной стены на северо-восточной стороне центральной части города.")
	await novel_interface.show_text_only("Этот район казался трущобами. Здания вокруг нас были низкими и ветхими, и лишь несколько уличных фонарей во всем квартале еще работали.")
	await novel_interface.show_text_only("На темной улице почти не было пешеходов, а вдоль обочин висели таблички, написанные на четырех местных языках.")
	await novel_interface.show_text_only("Слабое сияние, исходившее из ветхих жилых домов, было более тусклым, чем свет, лившийся из-за далекой изолирующей стены.")
	await novel_interface.show_text_only("Только звезды над головой на этой улице казались исключительно ясными.")
	novel_interface.show_character("ren_medical","happy")
	await novel_interface.show_dialog("Ух ты--\nЗвезды такие яркие.", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("Это место~", "Эмили")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Эмили открыла ржавые металлические ворота на улице, открыв небольшой двор, окруженный многоквартирными домами.")
	await novel_interface.show_text_only("Вера осторожно вывела грузовик задним ходом во двор, а затем припарковала БТР внутри.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Мы вошли в темный жилой дом через вход во двор. Как только мы добрались до второго этажа, мы увидели огромную металлическую дверь, похожую на вход в бомбоубежище.")
	await novel_interface.show_text_only("Эмили позвонила и тихо сказала: «Это я», и женщина лет сорока открыла дверь и приветствовала нас внутри.")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_ShelterCorridor.png")
	await novel_interface.show_text_only("Первое, что я увидел, был длинный коридор, и в воздухе стоял слабый аромат розового ладана.")
	await novel_interface.show_text_only("Голая лампочка на потолке открыто свисала с подвешенной на проводах розетки, и хотя ковер был старый, за ним явно хорошо ухаживали.")
	await novel_interface.show_text_only("Стены и двери коридора были выкрашены в элегантный ультрамарин, а стены были покрыты яркими детскими рисунками.")
	await novel_interface.show_text_only("Маленькая девочка внезапно высунула голову из комнаты дальше по коридору, прижалась к дверному косяку и с любопытством посмотрела на нас, а затем быстро нырнула обратно.")
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("(Это детский сад?)", "Лиан")
	await novel_interface.show_dialog("(Нет, это больше похоже на детский дом...)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Глядя на эти детские рисунки на стене, я понял, что некоторые из них изображают жестокие сцены, увиденные глазами ребенка...")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("Тётя Хайфа~", "Эмили")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("(Тётя?)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Уже так поздно, а ты все равно проделал этот путь. Вера тоже здесь?\nИ это...?", "Хайфа")
	novel_interface.show_character("ren_medical","happy")
	await novel_interface.show_dialog("Здравствуйте, мэм. Меня зовут Лиан.", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("О боже, какая хорошенькая девушка. Кстати, ты еще не ел?\nЯ принесу тебе что-нибудь из кухни...", "Хайфа")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("Нет необходимости. Разве мы не говорили в прошлый раз, что привезем сюда кое-какие припасы для местного населения, от которых военные планировали избавиться?", "Эмили")
	await novel_interface.show_dialog("Силы обороны в последнее время сокращаются, и Вера уговаривала отца доставить нам часть припасов из списанных подразделений.", "Эмили")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ты всегда беспокоишь своего отца. Ты уже несколько раз привозил вещи... Нам действительно придется когда-нибудь поблагодарить его лично.", "Хайфа")
	novel_interface.show_character("ren_medical","speechless")
	await novel_interface.show_dialog("(Сколько раз вы уже это делали? Неудивительно, что вы так натренированы...)", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","panic")
	await novel_interface.show_dialog("Нет, нет, мой отец слишком занят!", "Вера")
	novel_interface.change_expression("wink")
	await novel_interface.show_dialog("Когда армия отступит, вероятно, будет дороже привезти часть этих вещей домой, чем в любом случае покупать их снова с нуля.", "Вера")
	await novel_interface.show_dialog("Процедуры утилизации этих вещей не совсем честны, поэтому мы привезли их ночью... Просто скажи всем, чтобы не говорили об этом, ладно?", "Вера")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("О, хорошо, хорошо. Тогда я помогу тебе их нести?", "Хайфа")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("Я привез ребятам военный паек и планшетные компьютеры. Если бы вы могли просто освободить для меня немного места в кладовой, этого было бы достаточно.", "Эмили")
	await novel_interface.show_dialog("Большая часть остального — это то, что может использовать станция помощи доктора Хади. Я передам это ему через некоторое время...", "Эмили")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Это старшая сестра Эмили!", "Ребёнок A")
	await novel_interface.show_dialog("Старшая сестра Эмми...", "Ребёнок B")
	await novel_interface.show_dialog("Леди Валькирия тоже здесь~~", "Ребёнок C")
	await novel_interface.show_text_only("Вера закрыла лицо рукой, выражение ее лица было покрыто черными линиями.")
	await novel_interface.show_text_only("Вскоре из двух больших спален один за другим выбежали более дюжины детей и окружили нас.")
	await novel_interface.show_text_only("Эмили явно была здесь знаменитостью. Дети изо всех сил пытались столпиться вокруг нее, и все выглядели довольными.")
	await novel_interface.show_dialog("Старшая сестренка, старшая сестренка, я уже могу читать уроки для второго класса!", "Ребёнок A")
	await novel_interface.show_text_only("Маленькая девочка с гордостью сказала это, держа в руках планшет с электронными чернилами. Модель выглядела достаточно древней, примерно того же возраста, что и я.")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("Римма, это потрясающе. На этот раз мы принесли вам новые планшеты~", "Эмили")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Старшая сестра Эмили, теперь я могу жонглировать мячом двадцать раз!", "Ребёнок B")
	await novel_interface.show_text_only("Маленький мальчик в футболке под номером 10, такой огромной, что она соскользнула с плеча, отчаянно поднял руку.")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("Так держать, Омар! Когда-нибудь именно ты разгромишь национальную команду Хуаюньгун.", "Эмили")
	await novel_interface.hide_character() 
	await novel_interface.show_dialog("А еще, смотри, смотри, что я нарисовал...", "Ребёнок C")
	await novel_interface.show_text_only("Ребенок, который еще немного невнятно говорил, указал на самую большую картину на стене.")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("Хасан, это очень хорошо...", "Эмили")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Честно говоря, я уже примерно догадался, чего они добиваются, когда ранее увидел манифест поставок. Я просто не знал, что такое место существует...")
	await novel_interface.show_text_only("Объявления внизу, написанные на разных местных языках, ясно давали понять, что это район, где проживают этнические общины иммигрантов Масады.")
	await novel_interface.show_text_only("Этот район явно страдал от серьезного недостатка инфраструктуры, и, судя по массивной металлической двери, преступность здесь, вероятно, была довольно высокой.")
	await novel_interface.show_text_only("Глядя на улыбки детей, я вдруг почувствовал, что беспокоюсь об этом маленьком мальчишке...")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("Эмили, эм... мой телефон...", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Она достала из кармана мой телефон, затем, немного подумав, сняла и рацию и повернулась, чтобы передать мне обе.")
	novel_interface.show_character("emilio","normal")
	await novel_interface.show_dialog("Мы с Верой собираемся вниз перевезти припасы. Вы держитесь за радио. Сотовая связь здесь приходит и уходит...", "Эмили")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Церемония подписания соглашения о прекращении огня состоится завтра на рассвете, поэтому маршруты в центр города уже закрыты.", "Эмили")
	await novel_interface.show_dialog("Завтра утром мы вернем тебя до песчаной бури~", "Эмили")
	await novel_interface.hide_character()
	await novel_interface.stop_music()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("............")
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("Офис детского дома.")
	novel_interface.change_music("res://assets/audio/music/Sunset.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_ShelterOffice.png")
	await novel_interface.show_text_only("Я забилась в угол стены, где мне наконец удалось поймать сигнал, сжимая в руках телефон и безостановочно кивая, извиняясь.")
	await novel_interface.show_dialog("Ты только сейчас вспомнил, чтобы попросить у них свой телефон?\nТы хоть представляешь, который сейчас час?!", "Мариру")
	await novel_interface.show_dialog("Вы, идиоты, слишком усердно играете!", "Мариру")
	novel_interface.show_character("ren_medical","wail")
	await novel_interface.show_dialog("Ик--!\nS-Извините...", "Лиан")
	await novel_interface.show_dialog("Итак...\nМне сегодня придется переночевать в дальнем городе, но я вернусь завтра первым делом...", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Тоже на ночь?!", "Мариру")
	novel_interface.show_character("ren_medical","wail")
	await novel_interface.show_dialog("Эмили сказала, что все маршруты в центр города сейчас перекрыты, вероятно, из-за соглашения о прекращении огня.", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("\"Эмили\", да...? Кажется, вы с ней очень близки.", "Мариру")
	novel_interface.show_character("ren_medical","sob")
	await novel_interface.show_dialog("Н-нет!!", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Такой дурак, как ты, может быть похоронен в пустыне и даже не осознает этого.", "Мариру")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("Ах, эти две ракеты сегодня... это ты их перехватил, да?\nСпасибо, спасибо!!", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Тч--\nНу, я не могу сказать, что сегодня был полный проигрыш.", "Мариру")
	await novel_interface.show_dialog("Отец Веры является директором оперативного отдела Генерального штаба Масады, одним из сторонников жесткой линии в Силах обороны.", "Мариру")
	await novel_interface.show_dialog("Они семья военных. Имя прадеда Веры, Моше Даяна, в Масаде практически нарицательное.", "Мариру")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("А? Он такой впечатляющий...?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Интересно то, что он также был археологом-любителем. Предположительно, он единственный масадан, который когда-либо проводил археологические раскопки в пещере Махпела...", "Мариру")
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("Пещера Махпела... это то место, где произошел тот инцидент два дня назад, верно?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("После Шестидневной войны 1967 года Масада получила контроль над Хевроном.", "Мариру")
	await novel_interface.show_dialog("Моше Даян, который в то время был министром обороны, заставил стройную двенадцатилетнюю девочку пролезть в пещеру Махпела через щель снаружи.", "Мариру")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("(Почему это звучит так безрассудно...?)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Но одержимому коллекционеру не удалось добыть из него ни одной реликвии. Позже по религиозным соображениям людей внутрь уже не пускали...", "Мариру")
	await novel_interface.show_dialog("В любом случае, этот вспыльчивый характер и инициативность, похоже, заложены в семье. Ее отец тоже был бесстрашным пилотом.", "Мариру")
	await novel_interface.show_dialog("Ему было настолько неловко, что Вера настояла на том, чтобы подать заявление в Башню, академию технических специалистов. Если бы люди узнали, что сегодня сделала его дочь...", "Мариру")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("Ч-что ты собираешься делать?", "Лиан")
	await novel_interface.show_dialog("Эти двое на самом деле хорошие люди, так что не надо...", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Идиот. Если вас двоих поймают по дороге, мне нужно заранее подготовить кое-какие козыри.", "Мариру")
	await novel_interface.show_dialog("Подростки в бунтарской фазе – это такая боль…", "Мариру")
	novel_interface.show_character("ren_medical","uneasy")
	await novel_interface.show_dialog("Хе-хе, не волнуйся, я в порядке. Как Энни и малышка Stardust?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("После того, как тебя похитили, я отправил их обоих в посольство из соображений безопасности.", "Мариру")
	await novel_interface.show_dialog("Эх, теперь мне снова придется все объяснять этим старикам в Сенате...", "Мариру")
	novel_interface.show_character("ren_medical","smile")
	await novel_interface.show_dialog("Тогда хорошо~~ Завтра я успею в посольство вовремя!", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("О, верно. Если ты проведешь там ночь...", "Мариру")
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("Хм?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Будьте осторожны и не позволяйте мужчинам видеть вас, пока вы купаетесь. По обычаям некоторых этнических групп, вам, возможно, придется жениться на них~", "Мариру")
	novel_interface.show_character("ren_medical","wail")
	await novel_interface.show_dialog("Ха!?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Мариру резко положила трубку, как только закончила говорить.")
	await novel_interface.show_text_only("Обдумывая ее последние слова, я не мог сдержать дрожь.")
	novel_interface.show_character("ren_medical","sob")
	await novel_interface.show_dialog("(Какой придурок!)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ты закончил свой звонок?\nПриходи выпить гранатового сока, Лиан. Это все свежевыжатое.", "Хайфа")
	await novel_interface.show_text_only("Вошла тетя Хайфа с подносом, ее голос был особенно теплым и нежным.")
	await novel_interface.show_text_only("Она поставила на стол тарелку с фисташками и стеклянную бутылку без этикетки, наполненную красной жидкостью...")
	novel_interface.show_character("ren_medical","gratified")
	await novel_interface.show_dialog("Ах, Эмили вчера дала мне бутылку. Она получила это от тебя?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ха-ха, эта девочка любила это с самого детства, как и ее мать.", "Хайфа")
	novel_interface.show_character("ren_medical","gratified")
	await novel_interface.show_dialog("Я слышал, как она называла тебя тетей. Значит, ее мать - твоя...", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Эх, это была моя старшая сестра.", "Хайфа")
	await novel_interface.show_text_only("Тетя Хайфа вздохнула и осторожно села в кресло с печальным выражением лица.")
	await novel_interface.show_dialog("В нашей семье было три дочери. Моя старшая сестра умерла, а позже мы потеряли известия и о второй...", "Хайфа")
	await novel_interface.show_dialog("Когда Эмили была маленькой, старейшины поселения отправили ее в дом отца, чтобы она могла пойти в школу, но она все равно продолжала убегать.", "Хайфа")
	await novel_interface.show_dialog("Последние два года она присматривала за нами, хотя она еще совсем ребенок...", "Хайфа")
	await novel_interface.show_text_only("На столе я заметил старую фотографию в рамке: снимок трех человек на рынке. Все три девушки в нем были прекрасны.")
	await novel_interface.show_text_only("По бровям и глазам я мог сказать, что девочка с короткими волосами в крайнем левом углу была тетей Хайфой, когда она была моложе. Она была одета в школьную форму и выглядела лет на двенадцать или тринадцать.")
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("Эмили рассказала мне, что оба ее родителя погибли в дороге во время переезда.", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("...Это то, что она тебе сказала?", "Хайфа")
	novel_interface.show_character("ren_medical","gratified")
	await novel_interface.show_dialog("Да. Почему?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Тогда у нее все время была высокая температура. Сомневаюсь, что она многое помнит. Все, что произошло потом, ей рассказали старейшины...", "Хайфа")
	await novel_interface.show_dialog("Это правда, что много людей погибло на пути к переселению. Вздох...", "Хайфа")
	await novel_interface.show_dialog("Возможно, это и к лучшему. Возможно, это и к лучшему...", "Хайфа")
	await novel_interface.show_text_only("Тётя Хайфа больше ничего не сказала. Я осторожно взял рамку и увидел две строчки крошечной надписи в правом нижнем углу фотографии:")
	await novel_interface.show_text_only("\"Эмир, Лина и Хайфа\"\n\"Алеппо 2010\"")

	print("=== 星尘降临篇第15话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
