# stardustdescends_ep21.gd - 星尘降临篇第21话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep21_script()

func play_script():
	pass

func stardustdescends_ep21_script():
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("사건이 벌어진 지 2주 후, 제5학원도시 외곽.")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_VillaHall.png")
	await novel_interface.show_text_only("닉스는 이어폰으로 통화하며 우아하게 계단을 내려왔다.")
	novel_interface.show_character("nyx_normal","normal1")
	await novel_interface.show_dialog("그 사건은 전후 최악이자 가장 악질적인 테러 공격으로 규정되었다.", "닉스")
	await novel_interface.show_dialog("연합의회는 전면 조사를 벌이고 있으며, 연루가 의심되는 자는 누구든 절대 용서하지 않겠다고 밝혔다.", "닉스")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("그러니까--", "닉스")
	await novel_interface.show_dialog("'무샤르가 그 위성을 당신 경로로 샀다'는 정보는 대체 얼마쯤 할까요... 홍 선생님?", "닉스")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("아마도... 요즘 제가 전자화폐 역추적에 아주 능한 친구들을 좀 사귀었기 때문이겠죠~", "닉스")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("닉스의 입가에 옅은 미소가 떠올랐다.")
	novel_interface.show_character("nyx_normal","smile")
	await novel_interface.show_dialog("그럼 이 저택은 아버지를 대신해 제가 회수하겠습니다--", "닉스")
	await novel_interface.show_dialog("물론 이곳이 그동안 해 오던 장사는 계속하셔도 됩니다. 전 임대료로 수익의 10퍼센트만 받으면 돼요.", "닉스")
	await novel_interface.show_dialog("저도 당신이 하몬과 같은 꼴이 되는 건 바라지 않거든요.", "닉스")
	await novel_interface.show_dialog("대신 제 신변 안전만 확실히 책임져 주세요...", "닉스")
	await novel_interface.show_dialog("무샤르에게서 영감을 받아, 저도 생명 반응을 감지하는 장치를 하나 이식했답니다.", "닉스")
	novel_interface.change_expression("sad")
	await novel_interface.show_dialog("만약 제 생명 활동이 멈추면, 그 비밀들은 자동으로 인터넷에 공개될 거예요...", "닉스")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("아, 밀러 대주교와 라이보나의 관계는 비밀로 해 드릴게요~", "닉스")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("NASA 도난 자료까지 아주 후하게 넘겨주셨으니까요.", "닉스")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("닉스는 책상 위 태블릿을 집어 들어 그 암호화 파일을 열었다.")
	novel_interface.show_character("nyx_normal","normal1")
	await novel_interface.show_dialog("...프로젝트 '0812' 위성의 이름이 'STARDUST'라고?", "닉스")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("참... 하나도 놀랍지 않네~", "닉스")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("다음 날, SID 지휘실.")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_research","shock")
	await novel_interface.show_dialog("그러니까... 정말 아무것도 기억 안 나는 거야?", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("전혀 기억이 안 나...", "렌")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("위성 충돌 때 충격파 때문에 장갑차 안에서 머리를 부딪쳐 기절한 것 같아.", "렌")
	await novel_interface.show_dialog("그리고 눈을 떴을 땐 병원 침대에 누워 링거를 맞고 있었고...", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("국방군이 보낸 영상에 따르면, 네가 장갑차에서 나올 때는 무표정한 데다 한마디도 하지 않았고, 몸 주위엔 기묘한 코발트블루 광륜까지 감겨 있었다더라.", "마리루")
	await novel_interface.show_dialog("마치 모든 계획을 이미 알고 있는 사람처럼, 사람들의 시선을 받으며 그대로 컨벤션센터 옥상으로 걸어 올라갔대.", "마리루")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("앤의 보고에 따르면, 거의 같은 시각 대사관에서 의식불명이던 스타더스트 몸에서도 비슷한 빛이 났다더라...", "마리루")
	await novel_interface.show_dialog("에밀리오 말로는, 옥상에서 네가 자기 손을 잡았을 때 형언할 수 없을 정도로 거대한 힘이 몸 안으로 밀려들어 왔다고 해.", "마리루")
	await novel_interface.show_dialog("전에 너희가 벌집과 마주쳤을 때보다 수백 배는 강해서, 당장이라도 몸이 녹아 버릴 것 같았대.", "마리루")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("그런데 그 일격이 나간 직후 네 몸의 광륜은 사라졌고, 넌 그대로 그녀 품에 축 늘어지면서 얼굴을 가슴에 파묻으려고 필사적으로 버둥댔다더라.", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("...하?
그, 그랬어?", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("젠장, 전혀 기억이 안 나!")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("그래도 사건 요약을 읽고 나니까 아직 이해가 안 되는 부분이 있어...", "렌")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("무샤르가 2년 전에 그 위성의 제어 키를 샀다면서?", "렌")
	await novel_interface.show_dialog("그때는 아직 마사다가 자동 반격 시스템을 발표하지도 않았는데, 어떻게 대응책을 미리 준비할 수 있었지?", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("그 위성을 육지에 그대로 들이박아도 위력은 엄청났을 거야. 정면전 전황까지 뒤집을 수 있었을지도 몰라.", "마리루")
	await novel_interface.show_dialog("뛰어난 전략가는 어떤 말도 함부로 버리지 않아. 언제 쓰일지 누가 알겠어...", "마리루")
	await novel_interface.hide_character()
	
	
	await novel_interface.show_text_only("나는 알아듣는 척 연신 고개를 끄덕였고, 마리루는 그런 나를 의미심장하게 바라봤다.")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("닉스가 어제 암시장에서 NASA 도난 문서 하나를 찾아냈어.", "마리루")
	await novel_interface.show_dialog("사해로 추락한 그 위성은 400광년 떨어진 플레이아데스 성단의 어떤 구역에서 지구 방향으로 송신되는 신호를 수신하고 저장하기 위한 것이었어.", "마리루")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("신호 데이터량은 엄청나서 초당 테라바이트 단위로 저장됐고, 특정 궤도 위치에서만 수신이 가능했지--", "마리루")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("그래서 데이터는 위성 내부 하드디스크에 저장할 수밖에 없었고, 언젠가 다 차면 위성을 지구로 다시 떨어뜨려 물리적으로 회수하는 방식이었던 거야.", "마리루")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("말하자면 우주의 데이터센터였지.", "마리루")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("아이는 그 데이터가 스타더스트가 잃어버린 기억과 관련이 있을 가능성이 높다고 보고 있어.", "마리루")
	await novel_interface.show_dialog("하지만 그 위성은 이미 산산조각 나서 수심 400미터가 넘는 사해 바닥에 흩어져 버렸어...", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("그럼 스타더스트 기억은 못 찾는 거야?", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("누가 알겠어... 어쨌든 그 머나먼 우주에서 오던 신호는 사라졌으니까.", "마리루")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("어쩌면 어떤 의미에선 이미 자기 목적을 이룬 걸지도 모르지?", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("그럼 스타더스트는 지금 어때...", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("돌아왔을 때는 너처럼 계속 잠들어 있었어. 아이가 하리마 뇌연구소로 데려갔지...", "마리루")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("그런데 너희 둘은 무슨 텔레파시라도 있는 것처럼, 어제 거의 같은 시간에 깨어났더라.", "마리루")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("그래도 그 애도 하나도 아는 게 없었대. 아이는 무척 실망해서, 그 애 머리도 너처럼 텅 비었다고 하더라.", "마리루")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("누가 머리가 텅 비었다는 거야!?")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("아, 맞다! 아이가 스타더스트한테 친연 검사를 하기도 했어...", "마리루")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","perspire1",0.25)
	await novel_interface.show_dialog("?", "렌")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("걱정 마. 너희 둘은 진짜 혈연관계가 아니야~", "마리루")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wail")
	await novel_interface.show_dialog("애초에 그럴 리가 없잖아!!", "렌")
	novel_interface.character_light(0.35,"speak")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("그 꼬마는 깨어난 뒤로 계속 널 만나겠다고 보챘어. 지금 앤이 본부로 데려오고 있어.", "마리루")
	await novel_interface.show_dialog("후후후... 애들은 정말 활기차구나~", "마리루")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("왜 갑자기 할머니 같은 말투야...",)
	novel_interface.show_character("liliu_research","happy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_battle","wail",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("그 아이가 기어코 네게 들러붙겠다면, 늘 책임에서 도망치려는 네 성격도 겸사겸사 고쳐 주면 좋겠다고 생각했어.", "마리루")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("무, 무슨 뜻이야...?
(설마 내가 생각하는 그 뜻은 아니겠지!!)", "렌")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("마리루는 보온병을 집어 들고 이상한 식물이 우러난 허브차를 한 모금 마셨다. 얼굴엔 자애로운 미소까지 번졌다.")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("그보다, 그... 에밀리오랑 베라는 괜찮아?", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("몰랐어? 걔들은 지금 아주 잘 지내고 있어~", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("뭐?", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("그때 근처 주택 꼭대기에 있던 기자 하나가 컨벤션센터 옥상을 찍었거든.", "마리루")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("그래서 전 세계가 에밀리오가 마치 하늘에서 내려온 신처럼 모래폭풍을 두 동강 내는 걸 봤지--", "마리루")
	await novel_interface.show_dialog("물론 국방군은 나중에 그게 단 한 번만 발사할 수 있는 소모형 이질물 무기라고 설명했지만.", "마리루")
	await novel_interface.show_dialog("하지만 모든 아브라함계 종교에서 '바다를 갈라 사람들을 구하는' 일은 모세 같은 선택받은 자만 할 수 있잖아?", "마리루")
	await novel_interface.show_dialog("밑바닥 신도들의 반응도 격렬했고, 본인은 혼혈인데다 종교도 없으니--", "마리루")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("마사다의 대랍비와 이맘들이 전례 없이 뜻을 모아서, 서로 자기가 먼저 그녀를 신의 사자라고 떠들기 시작했어.", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("정말... 상황이 복잡한 나라네.", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("슈나이더만 총리는 그 흐름을 타고 그녀를 종교교육부 수석고문으로 앉혔어.", "마리루")
	await novel_interface.show_dialog("명예직에 불과하지만, 에밀리오는 자기 보좌관으로 베라를 데려갔고.", "마리루")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("며칠 전에는 마사다 의회가 원래 정전 협정의 일부 조항을 계속 추진하기로 결정했고, 에밀리오가 민족 문제를 조정하게 됐어.", "마리루")
	await novel_interface.show_dialog("이러면 국방군 내분이 어떻게 흘러가든, 앞으로 선거 결과가 어떻게 나오든, 두 사람까지 휘말리진 않을 거야.", "마리루")
	await novel_interface.hide_character()
	
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("어쨌든 둘이 무사하면 됐어...", "렌")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("그럼 '팬텀 포스'에 대해서는...", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("내가 끝까지 말하기도 전에 마리루가 말을 끊었다.")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("이건 엄중히 비밀로 해. 앤한테도 말하면 안 돼.", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("어?", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("마리루는 멍청한 짓을 하는 작은 동물을 보듯 미소 지으며 나를 바라봤다.")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("설마 네가 팬텀 포스의 비밀을 맞혔기 때문에 하몬이 에밀리오를 살려 줬다고 생각하는 건 아니겠지?", "마리루")
	await novel_interface.show_dialog("네가 송신 버튼을 누른 순간부터 국방군과 모노라는 네 위치를 추적하고 있었어. 그 장갑차는 이미 포위당한 상태였지.", "마리루")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("내가 제때 대화에 끼어들어 신분을 밝히지 않았다면, 너도 에밀리오도 살아남지 못했어.", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("어엉??", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("잊었어? 반격 시스템의 핵심인 팬텀 포스는 오래전에 봉인됐어.", "마리루")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("네 추리가 전부 맞았다 해도, 증거는 단 하나도 없었다고.", "마리루")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("20년도 더 전에 슐로모 샌더라는 마사다 역사학 교수가 똑같은 이론을 내놓았어.", "마리루")
	await novel_interface.show_dialog("그 사람도 확실한 증거를 내놓지 못해서, 반역자니 학살 수정주의자니 나치의 동조자니 하는 소리만 들었지.", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("그럼 마리루도...", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("내가 개입한 건 두 가지 메시지를 전달한 거야--", "마리루")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("첫째, SID가 네 안전을 아주 중시하고 있으니 주관이 직접 나섰다는 것.", "마리루")
	await novel_interface.show_dialog("둘째, 네게 무슨 일이라도 생기면 SID는 그 정보를 써서 마사다에 주저 없이 보복할 거라는 것.", "마리루")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("모노라는 SID가 대형 국제 언론사의 실권자들을 압박할 수 있는 정보를 많이 쥐고 있다는 걸 알고 있어.", "마리루")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("언론업계에 그런 말이 있지. 목소리만 충분히 크면 무슨 빌어먹을 증거 따윈 필요 없다고.", "마리루")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("그 뉴스가 사방으로 퍼져 수많은 민족주의 감정을 자극한다면, 서아시아는 앞으로 최소 30년은 더 대테러 전쟁을 치르게 될 거야.", "마리루")
	await novel_interface.show_dialog("그때 에밀리오도 그 말을 들었지만, 그녀도 베라에게 이 일을 말하지 않을 거야. 너도 마찬가지고--", "마리루")
	await novel_interface.show_dialog("그리고 비밀은 한 번 공개되는 순간 이용 가치가 사라져.", "마리루")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("알. 아. 들. 었. 지?", "마리루")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("마리루는 미소 지으며 손가락 마디를 뚝뚝 꺾었다.")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("알겠어!
죽어도 말 안 할게!!", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("죽는 건 그렇게 쉬운 일이 아니야--", "마리루")
	await novel_interface.show_dialog("마사다 빈민가의 어느 고아원에 얼마 전 거액의 기부금이 들어갔다던데...", "마리루")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("그 라이보나 황금 칩, 내가 잊었다고 생각한 건 아니겠지?", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("어?
그그그그그건...", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("그 일은 나도 완전히 잊고 있었어!")
	await novel_interface.show_text_only("그때는 아래층으로 내려가 에밀리오 일행을 찾고 싶었는데, 무슨 사고라도 날까 봐...")
	await novel_interface.show_text_only("그래서 하이파 아주머니가 불을 끌 때 그 칩을 쪽지에 끼워 책상 액자 앞에 두고 왔어.")
	await novel_interface.show_text_only("혹시 내가 일주일 안에 돌아오지 않으면 그걸 아이들 기부금으로 써 달라고 적어 놨고.")
	await novel_interface.show_text_only("그땐 스스로 진짜 멋지다고 생각했는데, 설마 침대에서 2주나 자게 될 줄은 몰랐지...")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("그 일의 전말은 이미 파악했으니까, 이제부터는...", "마리루")
	await novel_interface.hide_character()
	
	
	await novel_interface.show_text_only("왠지 마리루는 조금 들뜬 것처럼 보였다.")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("넌 돈 벌어서 빚 갚을 생각만 하면 돼~", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("이렇게 많은 돈은 나를 몇 번을 팔아도 모자랄걸...", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("그렇게까지 자기비하할 필요 없어~
내가 이미 광고 몇 개를 따 왔으니까.", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("뭐어?!", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("그 기자가 올린 영상에 너도 찍혔지만, 다들 에밀리오가 덤으로 구해 준 의무요원 정도로 생각하고 있어.", "마리루")
	await novel_interface.show_dialog("이미 얼굴이 노출됐으니, 다른 정보기관들이 멋대로 추측하게 두느니 차라리 흐름을 이용하는 게 낫지...", "마리루")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("마사다가 새로 내놓은 고에너지 배터리 이미지 광고 계약은 내가 이미 따 놨어--", "마리루")
	await novel_interface.show_dialog("제조사 쪽도 기존 배터리 광고에 나오던 장난감 토끼를 '구조된 소녀'로 바꾸자는 아이디어가 정말 절묘하다고 하더라~", "마리루")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("토끼라는 단어에 좋은 요소가 하나도 없잖아!!")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("...매니저라는 게 이렇게 재밌는 일이었구나~", "마리루")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("마리루는 내가 얼굴이 새빨개지고 머리에서 김이 날 지경이 되자 흡족해하며, 앤 일행을 맞으러 나가라고 했다.")
	await novel_interface.show_text_only("...")
	novel_interface.change_music("res://assets/audio/music/unkown/UI_Main_Funk.mp3")
	novel_interface.change_background("res://assets/images/bg/other/BG_City_street3.png")
	await novel_interface.show_text_only("엘리베이터에서 나오자 앤과 스타더스트는 이미 거리에서 한참을 기다리고 있었다.")
	novel_interface.show_character("stardust_small","tear")
	await novel_interface.show_dialog("레에에엔 아우우우우우~~~~~", "스타더스트")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("꼬마는 나를 보자마자 괴상한 끌어올린 음으로 외치며 달려들더니, 그대로 코알라처럼 내 다리에 달라붙었다.")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("야야야--
(머리를 내 치마 아래로 들이밀지 마!)", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("콧물 눈물 범벅이 된 채 필사적으로 응석 부리는 모습을 보자 곧장 마음이 약해졌고, 나는 그녀 머리를 살살 쓰다듬으며 달랬다.")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("알았어, 알았어...", "렌")
	await novel_interface.show_dialog("너도 오래 자다가 어제 겨우 깼잖아...", "렌")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("stardust_small","tear",0.25)
	await novel_interface.show_dialog("아우... 아우... 배고파...", "스타더스트")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("아직도 내게 매달리고 싶은지, 얼굴로 내 허벅지를 비비며 이상한 음절을 중얼거렸다. 마따타비 안은 고양이처럼 몹시 만족스러워 보였다.")
	novel_interface.show_character("ren_battle","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("stardust_small","konata_eye",0.25)
	await novel_interface.show_dialog("배고파...", "스타더스트")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("배에서 꾸르륵 소리가 나자 칭얼거림도 단순해졌다. 얼른 뜻을 알아차리라는 눈치였다.")
	novel_interface.show_character("ren_battle","happy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("stardust_small","konata_eye",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("뭐 먹고 싶은 거야?", "렌")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("응!", "스타더스트")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("뭐 먹고 싶어?", "렌")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("그 순간 머리 위 고양이 귀 같은 헤드셋이 두 번 반짝이더니, 그녀는 즉시 대답했다.")
	novel_interface.show_character("stardust_small","smile")
	await novel_interface.show_dialog("Le Souffle의 스타프루트 수플레.", "스타더스트")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_normal","smile",0.25)
	await novel_interface.show_dialog("어머, 취향 좋네~", "앤")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("앤은 의기양양한 스타더스트를 놀랍다는 듯 바라봤다.")
	novel_interface.show_character("anne_normal","happy")
	await novel_interface.show_dialog("렌이 사는 거라면--", "앤")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("하하하하...
(지금 내가 얼마를 빚졌는지 너는 절대 못 믿을걸.)", "렌")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("너, 수플레가 뭔지는 알아?", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("stardust_small","smile")
	await novel_interface.show_dialog("몰라아~", "스타더스트")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("그렇게 당당하게 웃지는 말아 줄래...")
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("(이 스마트 스피커, 식당 검색도 되는구나...)", "렌")
	await novel_interface.hide_character()
	
	
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("그럼 가자! 나도 배고파. 점심도 못 먹고 이 꼬마 데리러 하리마 뇌연구소까지 뛰어갔단 말이야...", "앤")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("앤이 스타더스트의 손을 잡는 순간, 나는 그녀 손목에 아주 익숙한 물건이 채워져 있는 걸 발견했다--")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("잠깐, 그건...?", "렌")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_normal","normal1",0.25)
	await novel_interface.show_dialog("응? 이거 아직도 차고 있었네? 빨리 떼어내자~", "앤")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("앤은 스타더스트 손목의 구겨진 분홍색 종이 팔찌를 능숙하게 벗겨 냈고, 나는 얼른 그걸 받아들었다.")
	await novel_interface.show_text_only("그 팔찌에는 삐뚤빼뚤한 글씨로 스타더스트의 이름이 적혀 있었다--")
	novel_interface.show_character("ren_battle","solemn")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_normal","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("이, 이 팔찌...", "렌")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("도박선에서, 스타더스트가 아직 실체화되기 전 내가 이미 벗겨 냈던 그 물건이잖아.")
	novel_interface.show_character("ren_battle","solemn")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_normal","worry",0.25)
	await novel_interface.show_dialog("잊었어? 에밀리오가 이 애가 출입국 바코드를 안 차고 있는 걸 보고 종이 띠로 임시 ID를 만들어 준 거잖아~", "앤")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("...어?", "렌")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("그거 하얀 종이 띠 아니었어?!
게다가 바코드는 어디 갔어...")
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("36시간이 훨씬 넘었으니까 잉크가 자동으로 사라진 거겠지~", "앤")
	await novel_interface.show_dialog("그날 밤 이 녀석이 호텔 볼펜으로 침대 위에 낙서하다가 팔찌에 자기 이름도 적어 놨고--", "앤")
	await novel_interface.show_dialog("그러다 석류주스를 엎질러서 종이 띠가 이 색으로 물든 거야.", "앤")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("머리가 순간 웅 하고 울렸다.")
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("괜찮아?
눈빛이 멍한데...", "앤")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("stardust_small","konata_eye",0.25)
	await novel_interface.show_dialog("응응?
왜 그래아~", "스타더스트")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("스타더스트는 내 팔을 흔들며 촉촉한 눈으로 천진하게 나를 올려다봤다.")
	novel_interface.stop_music()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_VaultStardust.png")
	await novel_interface.show_text_only("이거...")
	await novel_interface.show_text_only("처음 내가 이 아이를 봤을 때, 손목에 차고 있던 그 팔찌랑 똑같잖아...")
	await novel_interface.hide_background()
	novel_interface.change_music("res://assets/audio/music/Everything's gonna be Okay.mp3")
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("한편, 신토요스 오스미 기념병원.")
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Baizhu_Sickroom_Evening.png")
	await novel_interface.show_text_only("아이는 창가에 서서 저녁노을에 물든 제5학원도시를 바라보고 있었다.")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("시 교수가 방금 동면 캡슐에 들어갔는데, 정말 그를 실험체로 쓸 생각이야?", "아이")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("하인리히는 늘 그 물질이 뇌에 어떤 작용을 하는지 연구해 보고 싶어 했잖아... 어차피 우리 아니었으면 진작 죽었을 사람이고~", "마리루")
	await novel_interface.show_dialog("게다가 그의 딸도 어쩌면 꽤 가치가 있을지 몰라...", "마리루")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("그러고 보니 나도 요즘 그 교수 딸이 말한 사고실험을 계속 생각하고 있었어.", "아이")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("우린 이렇게 많은 정보 자원을 쥐고도 마지막 순간이 되어서야 겨우 무샤르 계획의 윤곽을 이해할 수 있었잖아.", "아이")
	await novel_interface.show_dialog("그런데 렌은 마사다에서 이틀 보고 들은 것만으로 팬텀 포스의 비밀을 알아내고, 거의 완벽했던 공격을 막아 냈어.", "아이")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("...정말 신기하지 않아?", "아이")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("그럴지도.", "마리루")
	await novel_interface.show_dialog("대학 시절 읽은 인류학 책에서 비슷한 이론을 본 적이 있어. 초승달 비옥지대 이론이라고--", "마리루")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_FertileCrescent.png")
	await novel_interface.show_dialog("그 책은 인류가 오늘날의 문명을 갖게 된 큰 이유 중 하나가, 아프리카와 지리적으로 이어진 곳이 서아시아의 메소포타미아였기 때문이라고 봤어.", "마리루")
	await novel_interface.show_dialog("그 초승달 비옥지대에는 마사다인들이 말하는 '약속의 땅'까지 포함돼 있지.", "마리루")
	await novel_interface.show_dialog("인류에게 가장 큰 영향을 준 다섯 종의 대형 가축은 양, 염소, 소, 돼지, 말인데 초승달 비옥지대에는 그중 네 종이 있었어.", "마리루")
	await novel_interface.show_dialog("초기 농경에 가장 중요했던 세 가지 식물인 보리, 밀, 콩류도 거기엔 전부 있었고.", "마리루")
	await novel_interface.show_dialog("인류의 조상들이 아프리카를 떠나 초승달 비옥지대로 왔다는 건, 마치 게임에 처음부터 세팅된 초보자용 자원 지대를 만난 것과 같았겠지.", "마리루")
	await novel_interface.show_dialog("그것도 똑같이 신기하지 않아?", "마리루")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("그러니까 말이야...", "아이")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Memory.png")
	await novel_interface.show_text_only("위험한 임무를 시작하는데, 애초에 자신을 살려 줄 장비를 전부 갖춘 채 시작하는 것 같잖아...")
	await novel_interface.show_text_only("그런 경험은 도대체 몇 번이나 죽고 다시 시작해야 얻을 수 있는 걸까.")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("정말 완전히... 불가능한 이야기 같네~", "아이")

	print("=== 星尘降临篇第21话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
