# stardustdescends_ep01.gd - 星尘降临篇第1话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep01_script()

func play_script():
	pass

func stardustdescends_ep01_script():
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Prisoner.png")
	await novel_interface.show_text_only("Наверняка вы уже слышали эту классическую историю...")
	await novel_interface.show_text_only("У богатого человека украли ценности. Полиция нашла украденное в комнате, которую делили двое подозреваемых, но доказательств не хватало, чтобы осудить кого-либо из них.")
	await novel_interface.show_text_only("Поэтому полиция разделила двух подозреваемых и предложила им такой выбор:")
	await novel_interface.show_text_only("Если один признается, а другой будет молчать, первый выйдет на свободу, а второй получит десять лет тюрьмы.")
	await novel_interface.show_text_only("Если оба промолчат, каждый получит по шесть месяцев. Но если признаются оба, каждый получит по пять лет.")
	await novel_interface.show_text_only("Для двух людей в этой истории исход, который был бы выгоднее всего им обоим, навсегда остается недосягаемым.")
	await novel_interface.show_text_only("Потому что, будет ли другая сторона молчать или признается, признаться самому всегда выгоднее. Признание становится доминирующей стратегией.")
	novel_interface.hide_background()
	await novel_interface.show_text_only("Некоторые экономисты считают, что в реальной жизни повторяющиеся игры могут научить обе стороны тому, что сотрудничество и есть лучшая стратегия.")
	novel_interface.show_background("res://assets/images/bg/Shot/storyBGWar.png")
	await novel_interface.show_text_only("Но некоторые игры не оставляют места для второго раунда.")
	await novel_interface.show_text_only("Если обе стороны попадают во взаимные подозрения, им уже никогда не избежать этой «дилеммы узника»…")
	novel_interface.hide_background()
	await novel_interface.show_text_only("<Окраина, New Opulentia>")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Manorgate.png")
	await novel_interface.show_text_only("У входа в поместье останавливается удлиненный лимузин. Красиво одетая девушка неловко вылезает с заднего сиденья.")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("Т-такое место--!", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Передо мной стояло роскошное поместье в европейском стиле: медные ворота, изысканные скульптуры, даже идеально подстриженный газон и кусты.")
	await novel_interface.show_text_only("Я понятия не имел, что такое место существует в New Opulentia. Осматривая прекрасный пейзаж, я слышу в наушнике строгий голос Мариру.")
	await novel_interface.show_dialog("Хватит глазеть. У тебя практически пускают слюни.", "Мариру")
	novel_interface.show_character("ren_full","shy")
	await novel_interface.show_dialog("Ладно, ладно...", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я собираюсь с силами и делаю шаг вперед, тут же спотыкаясь о туфли.")
	novel_interface.show_character("ren_full","shy")
	await novel_interface.show_dialog("Эти каблуки слишком высокие... И почему юбка-платье такая короткая?!", "Лиан")
	novel_interface.change_expression("shy_right")
	await novel_interface.show_dialog("(И еще в талии тесновато. Не слишком ли много я ем в последнее время...?)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Поднимите подбородок, не сутультесь. Ты похож на лобстера.", "Мариру")
	await novel_interface.show_dialog("Ты уже не первый день как девочка!", "Мариру")
	await novel_interface.show_text_only("Так раздражает--!!")
	await novel_interface.show_text_only("Когда я подхожу к входу в виллу, швейцар открывает ворота и кланяется мне.")
	await novel_interface.show_text_only("Я выдавливаю улыбку и усердно молюсь, чтобы больше не споткнуться на лестнице.")
	novel_interface.hide_background()
	await novel_interface.show_text_only("Соблюдая осторожность, я вхожу на виллу и прохожу серию сложных проверок безопасности. Виден интерьер здания – и он великолепен.")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_VillaHall.png")
	await novel_interface.show_text_only("Вестибюль, хоть и небольшой, но явно спроектирован человеком со вкусом. Даже лампа в углу светится так, как может только антиквариат.")
	await novel_interface.show_text_only("Мысленно повторяю то, что выучил вчера в этикете 101. Грудь вперед, живот втянут, шея прямая, улыбка, лицо вперед...")
	novel_interface.show_character("ren_full","uneasy")
	await novel_interface.show_dialog("(И ничего не сломайте!)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("В тот момент, когда я вхожу в вестибюль, гости, все одетые в пух и прах и перешептывающиеся по двое и по трое, поворачиваются и смотрят как один.")
	await novel_interface.show_dialog("Ух ты, Лиан, ты сегодня прекрасно выглядишь!", "Энни")
	await novel_interface.show_text_only("Наблюдая за каждым моим движением через камеру наблюдения, Энни звучит взволнованно, хотя и не забывает говорить потише.")
	novel_interface.show_character("ren_full","blush")
	await novel_interface.show_dialog("(Ну, это платье выглядит очень красиво, это правда...)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Но я парень! Фу!")
	await novel_interface.show_dialog("Гости здесь — все известные элиты из различных Академгородов. На первый взгляд, это место управляет казино только для членов клуба по специальной лицензии Сената.", "Мариру")
	await novel_interface.show_dialog("Но настоящий бизнес поместья — контрабанда и торговля разведывательной информацией. Это также крупнейший подпольный гарант во всем New Opulentia.", "Мариру")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("Итак, вы пытаетесь собрать улики, чтобы совершить набег на это место...?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("— шепчу я, все время улыбаясь и кивая окружающим.")
	await novel_interface.show_dialog("Я действительно кажусь вам таким бестактным?\nКроме того, если бы я захотел совершить набег на какое-то место, мне потребовались бы доказательства?", "Мариру")
	await novel_interface.show_text_only("Мариру отвечает. Могу поспорить, что она закатывает глаза, пока мы говорим.")
	await novel_interface.show_dialog("Сначала вам нужно привлечь внимание цели. Энни поможет.", "Мариру")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("Кажется, всем здесь лет сорок-пятьдесят. Я, очевидно, старшеклассник... разве это не было бы подозрительно?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Служба безопасности уже просканировала вас и проверила ваши записи, как только вы вошли в ворота.", "Мариру")
	await novel_interface.show_dialog("И не волнуйтесь, в системе вы отобразитесь как обычный старшеклассник, который подрабатывает в горничной.", "Мариру")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("А?\n(Почему кому-то вроде этого допущено на такое собрание?)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я замираю, нервничаю и неловко съеживаюсь под взглядами других гостей.")
	await novel_interface.show_dialog("Такие люди, как вы, сюда время от времени приходят. Некоторые гости очень любят подобные вещи.", "Мариру")
	await novel_interface.show_text_only("Что значит «такие люди, как я»?!!")
	await novel_interface.show_dialog("Цель сидит недалеко от угла, у лестницы. Выглядит немного нервным.", "Энни")
	await novel_interface.show_text_only("Я подхожу к месту, где могу наблюдать за целью и украдкой оглядываться...")
	novel_interface.show_character("shi","angry")
	await novel_interface.show_dialog("Черт возьми! Черт возьми! Черт возьми!", "???")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Цель — мужчина средних лет, обнимающий сумку. Его волосы в беспорядке, волосы на лице неопрятны. Совсем не похож на других гостей.")
	await novel_interface.show_text_only("Старое пальто, белая рубашка под свитером горчичного цвета и даже зеленый шарф...")
	novel_interface.show_character("ren_full","wail")
	await novel_interface.show_dialog("Это профессор Ши?\n(Он невероятно безвкусный!)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Да, думаю, так...", "Энни")
	novel_interface.show_character("ren_full","smile")
	await novel_interface.show_dialog("Хорошо.", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("По какой-то причине я чувствовал странную уверенность в том, как я выгляжу сегодня.")
	await novel_interface.show_text_only("Я подхожу к нему и делаю вид, что любуюсь витражами наверху, покачивая бедрами, расхаживая взад и вперед. Парень все еще не смотрит на меня должным образом.")
	await novel_interface.show_text_only("Немного не желая сдаваться, я тайно дергаю подкладки на груди и подхожу ближе, делая вид, что рассматриваю голову оленя, висящую на стене.")
	await novel_interface.show_text_only("Он даже отвернулся с отвращением!")
	novel_interface.show_character("ren_full","wail")
	await novel_interface.show_dialog("(Чувак, давай!)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Эм... простите, мисс...", "Гость-мужчина")
	await novel_interface.show_text_only("Рядом со мной появляется мужчина средних лет в смокинге и галстуке-бабочке.")
	await novel_interface.show_dialog("Я руковожу медиа-компанией в Newmoridas... Не могли бы вы немного пообщаться?", "Гость-мужчина")
	await novel_interface.show_text_only("Потирая руки, мужчина радостно сияет.")
	novel_interface.show_character("ren_full","perspire1")
	await novel_interface.show_dialog("П-извини, извини...", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я держусь за живот, как будто у меня внезапно закружилась голова, и крадусь в угол, где посылаю в камеру наблюдения взгляд отчаяния.")
	await novel_interface.show_text_only("Цель вообще не отреагировала. В итоге я только привлек какого-то чудака.")
	novel_interface.show_character("ren_full","sob")
	await novel_interface.show_dialog("Кажется, я вообще не могу привлечь внимание этого парня...", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Лиан, ты слишком жесткий...", "Энни")
	await novel_interface.show_dialog("Он тоже, кажется, кого-то ждет. И что бы ни было в этой сумке, выглядит подозрительно.", "Энни")
	await novel_interface.show_dialog("В твоей сумочке есть устройство формирования изображения. Мы только что просканировали его сумку — внутри никакой электроники, только двадцать или тридцать страниц бумажных документов.", "Мариру")
	await novel_interface.show_dialog("Он действительно старое ископаемое...", "Энни")
	novel_interface.show_character("ren_full","normal2")
	await novel_interface.show_dialog("Разве Ая не говорил, что эта штука может фотографировать содержимое множества бумажных документов, преодолевая препятствия?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я поднимаю удивительно тяжелую сумочку. Под тщательно прошитой лаковой кожей он набит маленькими гаджетами от SRD.")
	await novel_interface.show_text_only("Самое удивительное, что благодаря специально обработанной подкладке он каким-то образом прошел проверку безопасности на входе.")
	await novel_interface.show_dialog("Чтобы сфотографировать несколько листов одновременно, металлический порошок должен быть равномерно распределен по пространству, чтобы лучи, проходящие через каждую страницу, имели разные уровни интенсивности.", "Мариру")
	await novel_interface.show_dialog("У тебя в сумке дистанционно взорванная капсула с металлическим порохом, но это много страниц. Вам нужно будет сильно встряхнуть, чтобы порошок распределился равномерно.", "Мариру")
	await novel_interface.show_dialog("Не будет ли капсула издавать звук, когда лопнет? И он обнимал эту сумку, как будто это сокровище...", "Энни")
	await novel_interface.show_dialog("У вас нет заряда-липучки, способного взорвать дверной замок?", "Мариру")
	await novel_interface.show_dialog("Это еще громче!\nА если она привлечет внимание в этом наряде и это заметят не те люди...", "Энни")
	await novel_interface.show_text_only("Дрожь пробегает по мне, когда я вспоминаю, как этот ублюдок из медиа-компании продолжал смотреть на мою грудь.")
	novel_interface.show_character("ren_full","normal2")
	await novel_interface.show_dialog("Теперь, когда я думаю об этом...", "Лиан")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Вестибюль кажется нашим лучшим выбором.", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Там нет окон. Даже цветное стекло не пропускает свет, вероятно, для обеспечения конфиденциальности.")
	novel_interface.show_character("ren_full","gratified")
	await novel_interface.show_dialog("Можете ли вы двое отключить электричество в этой комнате?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Похоже, ты задумал что-то смелое, малыш...", "Мариру")
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("Я возвращаюсь в вестибюль и прохожу мимо профессора, пытаясь вести себя естественно.")
	await novel_interface.show_text_only("Внезапно лампочка с другой стороны лестницы вспыхивает, а затем с хлопком разбивается.")
	await novel_interface.show_text_only("Как только все, включая профессора, поворачивают головы, я просовываю серебряную капсулу в отверстие на его сумке.")
	await novel_interface.show_text_only("Затем я приседаю, словно поправляя каблуки, и быстро прижимаю заряд клея к ножке его стула.")
	novel_interface.show_character("ren_full","uneasy")
	await novel_interface.show_dialog("(Идеально!)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я показываю знак «ОК» камере наблюдения и отхожу на несколько шагов.")
	novel_interface.hide_background()
	await novel_interface.show_text_only("С потолка раздается стук, и в одно мгновение весь свет в комнате гаснет. Профессор кричит.")
	await novel_interface.show_text_only("Прежде чем кто-либо успевает среагировать, одна ножка стула ломается, и Профессор падает на пол.")
	await novel_interface.show_text_only("В кромешной темноте я направляю сумку сканирующей стороной к файлам и украдкой молюсь, чтобы устройство работало так, как должно.")
	await novel_interface.show_text_only("Гости впадают в смятение. Дворецкий врывается, чтобы всех успокоить, и говорит, что электричество скоро вернется.")
	await novel_interface.show_dialog("Это работает.", "Мариру")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_VillaHall.png")
	await novel_interface.show_text_only("Я выдыхаю с облегчением. Как только я опускаю сумку, свет снова загорается.")
	novel_interface.show_character("ren_full","uneasy")
	await novel_interface.show_dialog("Да!", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Все готово!")
	await novel_interface.show_dialog("Хех, вы двое...", "???")
	await novel_interface.show_text_only("Женский голос... позади меня.")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_dialog("Я наблюдал сверху. Что ты здесь делаешь, пытаешься соблазнить людей?", "Никс")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("... Никс?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Старшая девочка пристально смотрит на Профессора, который сидит рядом с нами и потирает задницу.")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_dialog("Этому стулу не менее ста тридцати лет. Эксперты говорят, что оно стоит более двух миллионов.", "Никс")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("А...?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Никс оборачивается и кладет руку мне на щеку.")
	novel_interface.show_character("nyx_full","smile")
	await novel_interface.show_dialog("Ты сегодня очень красиво одета, дорогая.", "Никс")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ее холодный палец проводит линию вдоль моего лица, достигает моего наушника с костной проводимостью, который она достает с холодной улыбкой.")
	novel_interface.show_character("nyx_full","mock")
	await novel_interface.show_dialog("... Так как же вы планируете за это платить?", "Никс")

	print("=== 星尘降临篇第1话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
