# stardustdescends_ep02.gd - 星尘降临篇第2话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep02_script()

func play_script():
	pass

func stardustdescends_ep02_script():
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_VillaHall.png")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("Two million?", "Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("A whole string of awful scenes flashes through my head--the kind where a commoner girl breaks an antique vase at some elite academy.")
	novel_interface.show_character("ren_full","sob")
	await novel_interface.show_dialog("(D-Don't tell me I'll spend the rest of my life working part-time to pay it off!!)", "Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("While I'm calculating exactly how long it'll take for me to repay all that money with my part-time job at the maid cafe, Nix puts a finger under my chin and tilts it up, forcing me to face her.")
	novel_interface.show_character("ren_full","sob")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_full","normal1",0.25)
	await novel_interface.show_dialog("At school you always seem so absent-minded...", "Nix")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("She leans closer and notes my clip-on earrings. She smiles knowingly at that.")
	novel_interface.show_character("ren_full","sob")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("With a little proper makeup, you're actually this cute...", "Nix")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("W-What are you trying to do!?")
	await novel_interface.show_text_only("That's when two buff bodyguards in black suits show up behind her and make their way towards me.")
	novel_interface.show_character("ren_full","sob")
	await novel_interface.show_dialog("(Dang it, I'm in trouble...)", "Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I thought I did fairly well in completing my mission. But now... I'm so dead!")
	novel_interface.show_character("nyx_full","smile")
	await novel_interface.show_dialog("I didn't scare you too badly just now, did I--", "Nix")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Her tone suddenly shifts, and without missing a beat she hides the earpiece she pulled from my ear in her palm.")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("Huh?", "Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Feigning concern, she touches my forehead and coldly addresses the bodyguards behind her without even turning around:")
	novel_interface.show_character("ren_full","panic")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_full","sad",0.25)
	await novel_interface.show_dialog("She's a junior of mine from Miyazakigawa. We just happened to run into each other.", "Nix")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("A bodyguard takes out a phone and scans my face, nodding understandingly at the results.")
	await novel_interface.show_text_only("The other one still seems suspicious. He walks over to the Professor, who's still on the ground looking dazed. Seems that he intends to check the chair.")
	await novel_interface.show_text_only("Seeing this, Nix suddenly hooks an arm around the back of my neck and presses her forehead to mine, as if checking my temperature--")
	novel_interface.show_character("ren_full","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","mock",0.25)
	await novel_interface.show_dialog("Get it together.", "Nix")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("There was urgency in her commanding tone, and her breath brushed directly across my face.")
	novel_interface.show_character("ren_full","awkward")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("nyx_full","mock",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("(Her face... is way too close!)", "Ren")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("I freeze in place, not sure what to say in reply. Countless questions are running through my brain--")
	await novel_interface.show_text_only("Why is Senpai here? As a guest of the casino, or to trade information? Is the target connected to her?")
	await novel_interface.show_text_only("She knew the history and price of that chair. She seems awfully familiar with this place... Could she actually be the owner of the estate?")
	await novel_interface.show_text_only("And what's with those two bodyguard-looking guys?\nAnd this bizarre atmosphere...?")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_text_only("I stare into Senpai's eyes, my heart pounding faster and faster, as if those pale crimson irises might swallow me whole.")
	novel_interface.change_expression("sad")
	await novel_interface.show_text_only("She surveys our surroundings, carefully observing the actions of the bodyguards. Suddenly, she trains her eyes back on me and I reflexively look away, redirecting my gaze downwards--")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Wait, if I look down from this angle--")
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("So that's how the neckline of Senpai's evening dress is designed...")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_text_only("As I stare at the lace trim peeking in and out of view, my heart races wildly. It feels as if a rush of heat is being pumped straight into my brain.")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("My ears turn red, and dizziness overtakes me...")
	novel_interface.show_character("nyx_full","sad")
	await novel_interface.show_dialog("Ren...?", "Nix")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_dialog("What's wrong with you?", "Nix")
	await novel_interface.show_dialog("What are you two standing around for? Hurry up and help!", "Nix")
	await novel_interface.show_dialog("Take her to my room first...", "Nix")
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("...")
	novel_interface.change_music("res://assets/audio/music/Noise.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Spot.png")
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("Hey...")
	await novel_interface.show_text_only("Do you remember?")
	await novel_interface.show_text_only("Who's there?")
	await novel_interface.show_text_only("A golden speck of light appears suddenly in the dark void, glowing in all colors of the rainbow.")
	await novel_interface.show_text_only("Do I remember what?")
	await novel_interface.show_text_only("I'm waiting for you...")
	await novel_interface.show_text_only("At the place in our promises.")
	await novel_interface.show_text_only("The place...")
	await novel_interface.show_text_only("In our promises?")
	await novel_interface.show_text_only("Wait, who are you?")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("...!")
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("Hey!")
	await novel_interface.show_text_only("Hey!")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_NoxRoom.png")
	await novel_interface.show_dialog("Hello? Did you really fall asleep just like that? You're drooling.", "Nix")
	novel_interface.show_character("ren_full","wry_smile")
	await novel_interface.show_dialog("Huh?", "Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I groggily open my eyes to find myself on a soft, king-sized bed.")
	await novel_interface.show_text_only("Purple bed frame. Black silk bedding. Looks awfully expensive.")
	await novel_interface.show_text_only("Nix is sitting on the edge of the bed, glaring at me with the eyes of a scientist looking at a lab rat.")
	await novel_interface.show_text_only("That's when I notice the wet patch of drool on what is probably a very expensive pillow--and that my legs are spread wide open, my skirt hiked all the way up to my waist.")
	await novel_interface.show_text_only("So I fell asleep on Nix's bed...")
	novel_interface.show_character("ren_full","wail")
	await novel_interface.show_dialog("(Wait... Nix? Bed?)", "Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Wasn't I supposed to be in the villa? And what happened to those bodyguards?")
	await novel_interface.show_text_only("I quickly pull my legs back together and pat down my gown, rolling over to the other side of the bed, curled up and staring at Nix defensively.")
	await novel_interface.show_text_only("Heavy velvet curtains cover the walls, shutting out every trace of daylight.")
	await novel_interface.show_text_only("The lights, the wallpaper and furniture are of a completely different style from the vintage chic in the villa. Same with the thick gray carpet on the ground.")
	novel_interface.show_character("ren_full","shy")
	await novel_interface.show_dialog("(I fainted...? Just how long had I been out?)", "Ren")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("Where is this? What did you do to me?", "Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Nix smirks and stands up, looking delighted at my reaction.")
	novel_interface.show_character("nyx_full","mock")
	await novel_interface.show_dialog("Oh?", "Nix")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She drops to her knees on the bed and starts crawling toward me.")
	novel_interface.show_character("nyx_full","mock")
	await novel_interface.show_dialog("What do you think I did to you...", "Nix")
	await novel_interface.show_dialog("Dearest Ren?", "Nix")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","perspire1")
	await novel_interface.show_dialog("W-what?", "Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Cheeks flaming, I shirk backward to the best of my ability, trying to hide my body with the blanket.")
	await novel_interface.show_dialog("Ah, stop teasing her.", "Mariru")
	await novel_interface.show_text_only("Mariru's voice suddenly booms from my chest, startling both of us so badly we nearly jump a foot into the air.")
	await novel_interface.show_dialog("Well, like we just discussed...", "Mariru")
	await novel_interface.show_dialog("You two may act whenever you're ready.", "Mariru")
	await novel_interface.show_text_only("Nix remains in her spot, peering at my chest curiously, and finally nods.")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("(Act? Act how?)", "Ren")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("Wait, what exactly did you two discuss when I was out cold?", "Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Why do I feel like I've been forced into something without my permission again?")
	novel_interface.show_character("ren_full","panic")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("I thought you were just acting when you pretended to faint. Turns out you really did black out.", "Nix")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Nix shrugs, looking slightly less creepy now, and I hesitantly put down the blanket I was clutching at like a lifeline.")
	novel_interface.show_character("ren_full","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("I didn't expect someone like you to join SID...", "Nix")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Not like I asked to become part of that weird organization myself!")
	novel_interface.show_character("ren_full","upset")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("W-wait, I... fainted?", "Ren")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("I try to recall the last thing I saw before falling unconscious. Did I really faint just because I saw--")
	novel_interface.show_character("ren_full","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("(Come on, who does that? That would have been too embarrassing!)", "Ren")
	await novel_interface.show_dialog("(It's not like I don't have breasts of my own, okay? I see them every time I bathe!)", "Ren")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Don't worry, we're still in the villa. This is my room.", "Nix")
	await novel_interface.show_dialog("You've been out for almost an hour.", "Nix")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("I'm about to exclaim in surprise when Nix covers my mouth with a hand.")
	novel_interface.show_character("ren_full","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","sad",0.25)
	await novel_interface.show_dialog("Shh, keep it down. The walls are soundproof, but those two guys are still guarding the door.", "Nix")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("I quickly swallow my words and nod like a docile lamb.")
	novel_interface.show_character("ren_full","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("I couldn't get you to wake. If Mariru hadn't claimed that your vitals were fine, I might have called an ambulance.", "Nix")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Y-you know Mariru?", "Ren")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("We became acquainted just now.", "Nix")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Nix smiles, pulling out the bone conduction earpiece from inside her ear.")
	await novel_interface.show_dialog("Just tell her everything so I won't have to.", "Mariru")
	await novel_interface.show_text_only("Nix hesitates, and finally meets my eyes, gaze steady.")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_dialog("I lost my mother when I was very young, so I barely remember her. As far as I know, it's always just been me and my father.", "Nix")
	await novel_interface.show_dialog("My father, Kristoff Strozzi, used to work in the Sixth Academy City--or rather, the place that used to be called the Lebona Archipelago...", "Nix")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She pauses, as if seeking for the right word.")
	novel_interface.show_character("nyx_full","smile")
	await novel_interface.show_dialog("You could say he was something like the head of the Senate.", "Nix")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","happy")
	await novel_interface.show_dialog("Wow!", "Ren")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("That's so cool!", "Ren")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_LiberNa.png")
	await novel_interface.show_text_only("The Sixth Academy City--back then, people called it the Lebona Archipelago.")
	await novel_interface.show_text_only("A Substance H explosion fifteen years ago had split the land to the east of the Andaman Sea into thousands of islands of different shapes and sizes over the course of a few dozen days.")
	await novel_interface.show_text_only("New islands were still forming when the surrounding nations began feuding over which island belonged to whom.")
	await novel_interface.show_text_only("Though there had never been peace between the navy of the nations, none of them dared to claim any island as their own during the period, because that would mean starting war with multiple nations at once.")
	await novel_interface.show_text_only("In the end, no nation was able to claim the area as their own territory. These islands, situated in an important location on the international trade sailing course, remained owner-less for the time being.")
	await novel_interface.show_text_only("Because the Extradition Act didn't apply to land that belonged to no country, wanted criminals and deserters from all over soon fled there.")
	await novel_interface.show_text_only("At first they called it Liber-Na--short for Liberty Nation. Over time, that name gradually became the Lebona we know today.")
	await novel_interface.show_text_only("Soon, mafias and other factions of the same type without a governmental background showed up at the islands too in hopes of making it big by doing trade on the oceans.")
	await novel_interface.show_text_only("Even now, the leaders of the Lebona Archipelago are chosen by election from among the region's biggest gangs.")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_NoxRoom.png")
	await novel_interface.show_text_only("So...")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("(So Nix's dad was basically a godfather? Whoa...)", "Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("nyx_full","sad")
	await novel_interface.show_dialog("Dad brought rules and order to that lawless patchwork of islands. Under his leadership, even those barren scraps of land without a single freshwater source developed into a prosperous city.", "Nix")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Nix speaks on, determined, yet her voice trembles. She gazes wistfully at the golden pattern of the wallpaper, as if pained by her memories.")
	novel_interface.show_character("nyx_full","sad")
	await novel_interface.show_dialog("And then the war began, and dad got involved in an incident and disappeared.", "Nix")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("...", "Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She sounds surprisingly calm, but I know all too well what situations of this kind entail.")
	await novel_interface.show_text_only("People who go \"missing\" during wars--they're most likely dead. We all know that.")
	await novel_interface.show_text_only("But the family they leave behind would simply tell themselves repeatedly:")
	await novel_interface.show_text_only("They're not dead, just missing.")
	await novel_interface.show_text_only("Even if they've been missing for so long it's unlikely they'll ever come back.")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_dialog("As for what happened later... you know the drill.", "Nix")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She continues without much of a pause.")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_dialog("Without my dad around, the other gangs took over and my family soon lost most of our assets and power.", "Nix")
	await novel_interface.show_dialog("Still, even when my dad was absent, a lot of his men remained loyal to us.", "Nix")
	novel_interface.change_expression("sad")
	await novel_interface.show_dialog("But their loyalty, in fact, put me in danger.", "Nix")
	await novel_interface.show_dialog("So, to show the other factions I wasn't interested in taking over my dad's business, I left the Lebona Islands and came to study in New Opulentia.", "Nix")
	await novel_interface.show_dialog("But, obviously, dad's enemies are still \"worried\"...", "Nix")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She glances at the door. So the two bodyguards are, in fact, there to monitor instead of protect.")
	novel_interface.show_character("nyx_full","sad")
	await novel_interface.show_dialog("I'm only allowed freedom in a very limited area around the school. No matter where else I go, those guys will be right behind me, breathing down my neck.", "Nix")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Three years ago, I managed to recover the underground trade network my family had in Europe and West Asia bit by bit, with the help of my dad's old friends.", "Nix")
	await novel_interface.show_dialog("I contacted Mr. Hong, the current head of Lebona, and offered him a deal.", "Nix")
	await novel_interface.show_dialog("I'll use my underground trade network to help promote his business in Europe, while he'll allow me to stay in his villa--of course, this means that his men will be watching over me.", "Nix")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("Even though this villa should've belonged to my dad in the first place...", "Nix")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("Wait, that's a lot to take in.", "Ren")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("So, you mean... your dad used to own this villa, but now it belongs to the Sixth Academy City?", "Ren")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("It's like an unspoken agreement between Lebona and the Senate.", "Mariru")
	await novel_interface.show_dialog("Our world is still recovering from the wars. There are lots of transactions going on, ones where the government would love to play a part in, but can't do so publicly.", "Mariru")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("So that's why there's an underground market?", "Ren")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Where there's a need, a market grows. And where there's a market, there's profit.", "Mariru")
	await novel_interface.show_text_only("No wonder you don't want to shut this place down!")
	await novel_interface.show_text_only("I survey my surroundings. The room is lavishly decorated, but it doesn't look lived-in--feels like a guest room of sorts.")
	await novel_interface.show_text_only("I guess Nix knows very well how it's like, to be under scrutinizing eyes every single second of her life...")
	novel_interface.show_character("nyx_full","smile")
	await novel_interface.show_dialog("I did some snooping. So that man you're targeting today is Yuzhe Shih, History professor from Hovering Palace University, huh?", "Nix")
	await novel_interface.show_dialog("The buyer he's meeting today didn't show up, might have gotten suspicious or something. The prof himself left too some ten minutes ago.", "Nix")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("We \"retrieved\" him soon after he left the villa. He's still knocked out, poor guy.", "Mariru")
	novel_interface.show_character("ren_full","stare")
	await novel_interface.show_dialog("Wait, what was all my hard work for, then?", "Ren")
	await novel_interface.show_dialog("(I went to etiquette 101... was teased relentlessly... to the point I had nightmares about it...)", "Ren")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("We're still analyzing what we got, but if the information on Shih's files is correct, the resources the Strozzi family has in Europe and West Asia should be useful for us.", "Mariru")
	await novel_interface.show_text_only("So you started a business partnership with Nix when I was sleeping, just like that?")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("I'm still a bit confused about two things...", "Ren")
	await novel_interface.show_dialog("If the people watching over you really distrust you that much, why not--", "Ren")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("Why not kill me, huh?", "Nix")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Nix easily finishes my sentence.")
	novel_interface.show_character("ren_full","upset")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("According to the Creed of Lebona, enacted by my dad himself, no member of an organization that is part of the pact may hurt the leader of another organization or his family members.", "Nix")
	await novel_interface.show_dialog("So they kinda just keep me on a short leash, while having to also provide funds to support my lifestyle.", "Nix")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Wow, they really respect the rules!", "Ren")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("And she's living a better life than most government workers!")
	await novel_interface.show_dialog("A clever design indeed. As disputes are unavoidable between violent factions, there should at least be a standard where they draw the line.", "Mariru")
	await novel_interface.show_dialog("And with that standard determined, no one will dare to break any rules. After all, the rules keep them safe as well. If they violate the standards, who knows who else will come after them, right?", "Mariru")
	await novel_interface.show_dialog("Constitutionalism, rule of law, multi-party rotation, periodic elections, and a clear bottom line...", "Mariru")
	await novel_interface.show_dialog("So many countries failed to reform their political systems, yet a bunch of outlaws managed to pull it off on their own. The irony.", "Mariru")
	novel_interface.show_character("ren_full","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("You probably see the Lebona Islands as this really unruly place, full of criminals, huh?", "Nix")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Like, a country run by thugs... full of black markets, casinos, stuff like that...")
	novel_interface.show_character("ren_full","uneasy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("(Not a place I'd want to raise my kids in...)", "Ren")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("In fact, the crime rate in Lebona is the lowest out of the six Academy Cities.", "Nix")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Huh?", "Ren")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("For gangs to exist, laws must first be established.", "Nix")
	await novel_interface.show_dialog("Without laws and lawyers, the government would be able to destroy all organizations and persons that annoy them, without needing evidence. Gangs would all be eliminated in no time.", "Nix")
	await novel_interface.hide_all_characters()
	await novel_interface.show_dialog("That's why now that the mafia's taken over the country, they place heavy emphasis on a rigorous set of laws.", "Mariru")
	await novel_interface.show_dialog("It's also what made Lebona so prosperous today.", "Mariru")
	await novel_interface.show_text_only("I nod, somewhat more convinced.")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("And, one last question...", "Ren")
	await novel_interface.show_dialog("Why do you want to work with the SID?", "Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Nix looks into my eyes, face serious:")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_dialog("Freedom.", "Nix")

	print("=== 星尘降临篇第2话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
