# stardustdescends_ep12.gd - 星尘降临篇第12话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep12_script()

func play_script():
	pass

func stardustdescends_ep12_script():
	novel_interface.change_music("res://assets/audio/music/unkown/UI_Draw.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_AncientHumanEH.png")
	novel_interface.show_character("stardust_big","normal")
	await novel_interface.show_dialog("Salut.", "Fille")
	await novel_interface.show_text_only("La fille devant moi avait la peau douce d’un bébé, des yeux dorés scintillant de lumière des étoiles et semblait enveloppée dans une sorte de halo.")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","blush")
	await novel_interface.show_dialog("(S-Elle est si jolie !)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("J'étais tellement fasciné par son visage qu'il m'a fallu un certain temps pour me rappeler que j'étais censé lui dire bonjour.")
	novel_interface.show_character("ren_medical","awkward")
	await novel_interface.show_dialog("Ah--ahh !!\nH-salut ! Euh, ça...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("J'ai bondi sur mes pieds, paniqué, laissant presque échapper \"S'il vous plaît, asseyez-vous\" sur le banc.")
	await novel_interface.show_text_only("Me voyant trébucher sur mes mots comme un idiot, la jeune fille laissa échapper un doux rire.")
	await novel_interface.show_text_only("Elle se dirigea vers la vitrine centrale avec les spécimens squelettiques et brossa doucement le cadre en noyer comme si elle était perdue dans ses pensées...")
	novel_interface.show_character("stardust_big","normal")
	await novel_interface.show_dialog("Cette salle est toujours aussi calme...\nÊtes-vous intéressé par la paléoanthropologie ?", "Fille")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("J'ai hoché la tête par réflexe...")
	novel_interface.show_character("ren_medical","uneasy")
	await novel_interface.show_dialog("(je peux être intéressé !)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elle m'a fait un sourire chaleureux qui pourrait faire fondre une personne, puis s'est tournée vers le squelette fossilisé dans la boîte et a dit :")
	novel_interface.show_character("stardust_big","normal")
	await novel_interface.show_dialog("Son nom est \"Lucy\". Elle vivait il y a environ 3,2 millions d'années.", "Fille")
	await novel_interface.show_dialog("Lorsqu’une expédition l’a découverte en Afrique en 1974, elle a été considérée comme le fossile d’ancêtre humain le plus ancien et le plus complet découvert à l’époque.", "Fille")
	await novel_interface.show_dialog("Plus tard, des fossiles d'hominidés plus anciens ont été découverts, mais le titre de Lucy en tant que « grand-mère de l'humanité » perdure jusqu'à ce jour.", "Fille")
	novel_interface.change_expression("smile2")
	await novel_interface.show_dialog("Et quant au nom \"Lucy\"...", "Fille")
	await novel_interface.show_dialog("Ils disent que lorsqu'elle a été découverte, le magnétophone du site de fouille jouait \"Lucy in the Sky with Diamonds\" des Beatles.", "Fille")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sa voix était douce et pure, comme si elle décrivait le ciel nocturne rempli d’étoiles au-dessus du continent africain il y a plus de trois millions d’années.")
	novel_interface.show_character("ren_medical","perspire1")
	await novel_interface.show_dialog("\"Grand-mère de l'humanité\" signifie-t-elle...\nqu'elle est l'ancêtre de beaucoup de gens ?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("stardust_big","normal")
	await novel_interface.show_dialog("Pas nécessairement~", "Fille")
	await novel_interface.show_dialog("Lucy a été l’une des premières humaines à marcher debout, mais elle n’était qu’un membre de cette population.", "Fille")
	await novel_interface.show_dialog("Certains scientifiques affirment même que, comme la taille du cerveau humain n'avait pas encore commencé à augmenter à ce stade, on ne peut pas juger le sexe par la taille de l'ouverture pelvienne.", "Fille")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Souriante, elle se pencha près de mon oreille et murmura.")
	novel_interface.show_character("stardust_big","smile1")
	await novel_interface.show_dialog("Alors...\nLucy n'était peut-être pas une fille non plus~", "Fille")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","awkward")
	await novel_interface.show_dialog("--Hein ?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Un frisson me parcourut et je reculai précipitamment de quelques pas.")
	await novel_interface.show_text_only("W-Pourquoi me dirait-elle ça ?? Se pourrait-elle qu'elle me soupçonne... ?")
	novel_interface.show_character("ren_medical","shy_right")
	await novel_interface.show_dialog("(Et arrête de respirer dans mon oreille ~~~ !!)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elle eut l'air plutôt satisfaite de ma réaction troublée, puis changea de sujet et continua :")
	novel_interface.show_character("stardust_big","normal")
	await novel_interface.show_dialog("Tant de temps s'est écoulé qu'il est impossible de récupérer l'ADN de Lucy et de le vérifier maintenant.", "Fille")
	await novel_interface.show_dialog("Mais si un corps était resté scellé et préservé, la dernière technologie d'analyse génétique de Samonton pourrait encore tester la parenté.", "Fille")
	await novel_interface.show_dialog("Il y a quelques années, ils ont extrait l'ADN d'une momie âgée de six mille ans et l'ont comparé à une base de données génétiques moderne, et ils ont effectivement trouvé des descendants encore vivants aujourd'hui.", "Fille")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","perspire1")
	await novel_interface.show_dialog("C'est incroyable--?!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Cette fille est-elle une étudiante en médecine venant de quelque part à proximité ? Mais à en juger par son apparence et ses vêtements, elle ne semble pas locale...")
	novel_interface.show_character("stardust_big","smile1")
	await novel_interface.show_dialog("En fait, je ne l'ai appris que la dernière fois...", "Fille")
	novel_interface.change_expression("close_eye")
	await novel_interface.show_dialog("Mais les ancêtres humains sont vraiment incroyables...", "Fille")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elle parla en contournant la vitrine, quittant progressivement mon champ de vision.")
	await novel_interface.show_dialog("Ils sont partis d’Afrique, ont traversé le Croissant Fertile et se sont frayés un chemin à travers le monde entier.", "Fille")
	await novel_interface.show_dialog("Ils ont atteint les endroits les plus froids de la planète et les plus chauds, des endroits où la moitié de l'année est le jour et l'autre moitié la nuit...", "Fille")
	await novel_interface.show_dialog("Ils traversèrent même les mers et atteignirent la rive opposée...", "Fille")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Ah, c'était... ?")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Mother.png")
	await novel_interface.show_text_only("C'est tiré d'un livre que ma mère m'a lu quand j'étais petite...")
	await novel_interface.show_text_only("Ce passage m’a laissé une impression particulièrement profonde…")
	await novel_interface.show_text_only("Mais après, je n’ai jamais pu comprendre comment s’appelait ce livre.")
	await novel_interface.hide_background()
	novel_interface.show_character("ren_medical","normal2")
	await novel_interface.show_dialog("Attends, où as-tu vu ça... ?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Soudain, j’ai remarqué que l’espace derrière la vitrine était plongé dans l’obscurité et qu’une lumière bleu cobalt vacillait d’où venait sa voix.")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Stardust.png")
	await novel_interface.show_text_only("Je l'ai immédiatement poursuivi et j'ai trouvé la jeune fille debout dans une lueur brumeuse, tandis que l'espace autour d'elle devenait flou et sombre.")
	await novel_interface.show_dialog("Cela devrait faire passer le message maintenant...", "Fille")
	await novel_interface.show_dialog("--Comme nous l'avions promis.", "Fille")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Promis... nous... ?")
	await novel_interface.show_text_only("Dans le vide, sa dernière voix m'a atteint...")
	await novel_interface.show_dialog("Tu es aussi belle avec les cheveux longs...", "Fille")
	await novel_interface.show_text_only("Avant que je puisse la presser, sa silhouette s’estompa progressivement, se dissolvant comme si elle n’avait jamais appartenu à ce plan.")
	await novel_interface.show_text_only("Mes yeux devinrent humides et, pour une raison ou une autre, une vague de chagrin monta en moi...")
	await novel_interface.show_text_only("Quoi... attends...")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("Hé............")
	await novel_interface.show_text_only("Hé, hé--!!!")
	await novel_interface.show_text_only("Puis le monde a tourné et j’ai eu l’impression que quelqu’un secouait mon corps.")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_AncientHumanEH.png")
	novel_interface.show_character("emilio","stare")
	await novel_interface.show_dialog("Hé, Lian ?", "Emily")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("Hein...?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("emilio","speechless",0.25)
	await novel_interface.show_dialog("Alors c'est bien toi...\nTu t'es endormi ici ? N'avez-vous pas peur d'attraper froid ?", "Emily")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("...Émilie ?", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Était-ce... un rêve à l'instant ?")
	await novel_interface.show_text_only("Je me suis frotté le visage, j'ai essuyé mes larmes et j'ai essayé de me débarrasser de ce sentiment aussi vite que possible.")
	novel_interface.show_character("ren_medical","normal2")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("emilio","speechless",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Pourquoi es-tu ici...", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("J'ai apporté ici pour évaluation des objets confisqués soupçonnés d'être des artefacts, puis je vous ai vu endormi sur le banc.", "Emily")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Pendant que je me coiffais, j'ai sorti mon téléphone, pensant toujours à ce que cette fille avait dit...")
	novel_interface.show_character("ren_medical","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("emilio","normal",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ah !! Comment est-il arrivé si tard ?!", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("J'avais l'impression d'avoir dormi moins de dix minutes, mais une heure et demie s'était déjà écoulée.")
	await novel_interface.show_text_only("La visite obligatoire du musée, qui durait trois heures, était terminée depuis quinze minutes.")
	await novel_interface.show_text_only("Je me suis levé, j'ai tiré sur la robe nuisette qui était collée à mes fesses après être resté assis trop longtemps et j'ai dit à Emily un peu gêné.")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("Heureusement que tu m'as réveillé. J'aurais failli être en retard...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Le plan était qu'après la visite, Mariru demanderait au personnel de l'ambassade de m'emmener, moi et le petit Stardust, au bureau de l'immigration pour gérer les formalités administratives.")
	await novel_interface.show_text_only("Leur voiture devrait déjà avoir atteint l'entrée du musée...")
	novel_interface.show_character("ren_medical","sob")
	await novel_interface.show_dialog("Ah~", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Soudain, j'ai senti une légère piqûre à la nuque...")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Avant que je puisse me retourner, ma vision s'est brouillée, mes membres sont devenus mous et je suis tombé en arrière...")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("............")
	await novel_interface.show_text_only("Peu de temps après, SID salle de commandement.")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_uniform1","angry")
	await novel_interface.show_dialog("--Elle a disparu !?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru feuilleta immédiatement le rapport : le chauffeur de l'ambassade déclara que personne ne s'était présenté et que les appels sur le téléphone de Lian n'étaient retournés que hors service.")
	await novel_interface.show_text_only("Le traceur de Lian a perdu le signal dans l'enceinte du musée.")
	await novel_interface.show_text_only("Étant donné que la surveillance publique du musée, ainsi que celle de tout le centre-ville de Massada, devait passer par les serveurs de Monola, il n'était pas possible de l'infiltrer rapidement.")
	await novel_interface.show_text_only("Cette idiote se perdait de temps en temps, mais cette fois, c'était clairement au-delà des attentes de Mariru.")
	await novel_interface.show_text_only("Devant le grand écran, Aya a fait tourner rapidement un crayon dans sa main gauche tout en faisant glisser la chronologie avec sa droite, regardant attentivement plusieurs séries d'images satellites.")
	await novel_interface.show_text_only("--C'était son habitude chaque fois que son cerveau tournait à plein régime.")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("Je pense que c'est celui-là...", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru regarda l'image indiquée par Aya : peu de temps après la disparition du signal de Lian, un véhicule blindé sortit du garage souterrain du musée.")
	await novel_interface.show_text_only("Comme l'image ne provenait pas d'un satellite espion en orbite basse, ni l'angle ni la résolution n'étaient suffisants pour distinguer le numéro de plaque.")
	await novel_interface.show_text_only("Après avoir quitté le musée, le véhicule est rapidement entré dans un labyrinthe de tunnels souterrains dotés de nombreuses sorties et a complètement disparu.")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("Il s’agissait d’un véhicule blindé de transport de troupes F-950 SWAT TRUCK. Son corps peut réellement bloquer les ondes électromagnétiques, et il peut même résister à une certaine quantité de rayonnement nucléaire.", "Aya")
	await novel_interface.show_dialog("Massada a déployé plus d'une centaine de ces véhicules dotés d'un blindage spécial en matériaux hétérogènes, en partie pour se défendre contre les voitures piégées et les attaques de guérilla.", "Aya")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("Pensez-vous que Monola l'a fait ?\nJe me souviens que l'administrateur d'Elluka a déjà combattu Lian et les autres...", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru secoua sombrement la tête.")
	novel_interface.show_character("ai","think")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform1","serious",0.25)
	await novel_interface.show_dialog("Très peu probable. Cette personne ne comprend pas la vraie valeur de Lian, donc cela ne vaudrait pas la peine de prendre un risque aujourd'hui.", "Mariru")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("...À cause de l'accord de cessez-le-feu ?", "Aya")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Les cinq autres villes universitaires ont toutes des postes de renseignement à Massada, mais en ce moment sensible, elles se sont toutes tacitement retenues.", "Mariru")
	await novel_interface.show_dialog("Même Samonton et New Moridas, qui sont habituellement en désaccord avec Massada, ont été inhabituellement calmes ces derniers jours...", "Mariru")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("Après tout, personne ne veut provoquer un affrontement en ce moment et assumer la responsabilité de la destruction du processus de paix mondial...", "Mariru")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Alors c'est probablement quelqu'un au sein des Forces de Défense...", "Aya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Aya a affiché un fichier sur l'écran.")
	novel_interface.show_character("ai","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_uniform1","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ce véhicule blindé coûte cher et les Forces de défense l’ont équipé d’un cryptage comparable à celui de l’avion d’attaque sans pilote Yellow Sparrow.", "Aya")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("Si ce cryptage avait été brisé, le système de défense IA de Massada serait fondamentalement sans défense. Le pays tout entier serait déjà en émoi.", "Aya")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Le téléphone de Lian est configuré pour commencer à enregistrer automatiquement dès qu'il perd le contact satellite...", "Mariru")
	await novel_interface.show_dialog("Dès que le signal revient, l'alimentation de secours renvoie immédiatement le fichier audio et les données de localisation.", "Mariru")
	novel_interface.change_2nd_expression("sigh")
	await novel_interface.show_dialog("Pour l'instant, tout ce que nous pouvons faire, c'est attendre et voir...", "Mariru")
	await novel_interface.stop_music()
	await novel_interface.hide_all_characters()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("............")
	await novel_interface.show_text_only("J'ai mal à la tête.")
	await novel_interface.show_text_only("Ce même mal de tête intense, à nouveau, comme si je l'avais déjà ressenti.")
	await novel_interface.show_text_only("C'était comme si quelqu'un avait jeté plusieurs sacs de ciment dans mon crâne et les remuait lentement...")
	await novel_interface.show_text_only("Ma tête bourdonnait, accompagnée de brusques bourdonnements dans mes oreilles.")
	await novel_interface.show_text_only("Où suis-je...?")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_MasadAPC.png")
	await novel_interface.show_text_only("J'ai ouvert les yeux groggy et mes pupilles se sont lentement adaptées à la lumière autour de moi.")
	novel_interface.show_character("emilio","normal")
	await novel_interface.show_dialog("Tu es réveillé ?", "Emily")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Vu à quel point tu es maigre, c'est une bonne chose que j'ai ajusté le dosage...", "Emily")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elle a parlé avec inquiétude dans sa voix et m'a tendu un paquet de mouchoirs.")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("Essuyez. Tu bave ~", "Emily")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","normal2")
	await novel_interface.show_dialog("Ugh...\nW-Où est-ce... ?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("J'ai réalisé que j'étais à l'intérieur d'un APC. J'avais déjà vu ce modèle dans une vidéo réalisée par un nouveau riche parlant un anglais de style russe avec un fort accent.")
	await novel_interface.show_text_only("Ces véhicules au blindage renforcé en matériaux hétérogènes coûtent une fortune. Je n'aurais jamais pensé pouvoir monter à bord moi-même...")
	await novel_interface.show_text_only("Non, attends ! Pourquoi suis-je dans un véhicule blindé ?!")
	await novel_interface.show_text_only("Dès que j'ai ouvert les yeux, Emily a scanné mon visage avec un appareil portable et l'écran a affiché « Vérification réussie ».")
	await novel_interface.show_text_only("Je me suis réveillé complètement et j'ai senti tout mon corps. Je ne semblais pas être blessé, mais mon téléphone avait disparu.")
	await novel_interface.show_text_only("En touchant l'endroit de mon cou qui m'avait piqué, j'ai finalement réalisé...")
	novel_interface.show_character("ren_medical","serious")
	await novel_interface.show_dialog("(Attends, est-ce que ça veut dire...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ai-je été kidnappé ?!")
	await novel_interface.show_text_only("J'ai regardé Emily assise à côté de moi. Elle vérifiait la boîte de munitions d'une mitrailleuse. Vous n'avez pas besoin d'armes lourdes juste pour me kidnapper, n'est-ce pas ?")
	novel_interface.show_character("ren_medical","serious")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("emilio","mock",0.25)
	await novel_interface.show_dialog("Hé, au fait...", "Emily")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Emily se pencha et dit avec un sourire.")
	novel_interface.show_character("ren_medical","serious")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("emilio","mock",0.25)
	await novel_interface.show_dialog("Vous venez de New Toyosu, n'est-ce pas ? Le sénat?", "Emily")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Hein...?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("SID ?", "Emily")
	novel_interface.character_light(0.35,"wail")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Euh!", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("Mm-hm. Il s'agit donc bien de SID.", "Emily")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Comment diable a-t-elle compris ça ?!")
	await novel_interface.show_text_only("Emily, cependant, n'avait pas fini et a continué...")
	novel_interface.show_character("emilio","normal")
	await novel_interface.show_dialog("Vous n'avez aucun muscle, donc vous ne pouvez pas être du personnel de terrain...", "Emily")
	await novel_interface.show_dialog("Le code-barres sur le bracelet que j'ai donné à cet enfant hier mène, une fois scanné, à un site Web déguisé en intranet des Forces de Défense.", "Emily")
	await novel_interface.show_dialog("Mais il n'y a toujours pas eu de journaux d'accès, ce qui signifie que vous n'êtes probablement pas non plus du personnel technique...", "Emily")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("Sinon tu serais bien trop incompétent...", "Emily")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elle a passé un bras autour de moi et a volontairement baissé la voix.")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("Le processus de sélection de SID est censé être assez strict, n'est-ce pas...", "Emily")
	await novel_interface.show_dialog("Vous êtes entré par la porte arrière, n'est-ce pas ?\nUn contrat de népotisme ?", "Emily")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Dans un certain sens, tout à fait exact !!")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("Alors j'avais raison ?\nPas étonnant que cette carte d'identité ait une autorisation si élevée...", "Emily")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("J'avais l'impression qu'elle verrait clair en moi même si je ne disais pas un mot. Si cela continuait, tous mes secrets me seraient arrachés !")
	await novel_interface.show_text_only("Je me suis instinctivement recroquevillé en boule comme un animal effrayé, essayant d'enfouir ma tête et de faire comme si de rien n'était.")
	await novel_interface.show_text_only("Toujours souriante gentiment, elle me tapota le dos pour me réconforter.")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("N'ayez pas peur. Nous empruntons simplement votre identité de couverture pour récupérer des fournitures. Nous reviendrons avant la nuit et nous ne vous ferons pas de mal.", "Emily")
	await novel_interface.show_dialog("Une fois que nous aurons terminé, nous vous laisserons partir et veillerons à ce que vous quittiez le pays en toute sécurité. Si vous le souhaitez, nous pouvons même vous aider à emmener cet enfant d'hier avec vous, alors...", "Emily")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("Nous allons garder votre téléphone pour l'instant, d'accord ?", "Emily")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Pas de problème ! S'il vous plaît, gardez-le en sécurité !!")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("Super ~", "Emily")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Je n'avais pas du tout ouvert la bouche. Cette fille est médium ou quoi ?")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("En fait, je le suis ~", "Emily")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sérieusement, tu l'es ?!\nAaaah, ne pense à rien, ne pense à rien...")
	await novel_interface.show_text_only("Je rentrai à nouveau la tête.")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("Et ça ? Vous pouvez me poser deux questions et je vous promets de répondre honnêtement.", "Emily")
	await novel_interface.show_dialog("Est-ce que cela vous permettrait de vous sentir un peu plus en sécurité ?", "Emily")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elle m'a regardé sincèrement, comme si elle ne voulait vraiment aucun mal, et mon corps a cessé d'être aussi tendu.")
	await novel_interface.show_text_only("Très bien... comment as-tu su que j'étais un agent...")
	novel_interface.show_character("emilio","speechless")
	await novel_interface.show_dialog("............?", "Emily")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elle éclata soudain de rire.")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("Hahahaha, tu es adorable...", "Emily")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Ne me dis pas que tu pensais vraiment que j'avais de la télépathie ou quelque chose comme ça, alors tu as posé une question dans ta tête ?", "Emily")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","wail")
	await novel_interface.show_dialog("... Hein ?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("Je peux lire des micro-expressions et des petits mouvements en un instant. Vous n'avez certainement jamais suivi de formation anti-interrogatoire, n'est-ce pas ?", "Emily")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Désolé, j'ai eu beaucoup d'interrogatoires, mais pas d'anti-interrogatoire !")
	novel_interface.show_character("ren_medical","shy")
	await novel_interface.show_dialog("H-Comment m'as-tu découvert...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mon visage est devenu rouge vif, mais j'avais l'impression que je devais absolument poser cette question.")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("Dès que je t'ai vu pour la première fois sur le bateau-casino, j'ai pu dire que tu essayais désespérément de cacher quelque chose ~", "Emily")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Alors j'ai agi avec désinvolture et je t'ai laissé t'exposer.", "Emily")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Je pensais que c'était une bonne personne... Je suis tellement idiote !")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("Mais quand tu as sorti cette carte d'identité, je n'ai toujours pas pu m'empêcher de rire...", "Emily")
	await novel_interface.show_dialog("Allez, tu es bien trop amateur. Habituellement, une opération comme celle-ci préparerait plusieurs fausses identités...", "Emily")
	await novel_interface.show_dialog("Au minimum, quiconque pourrait entrer dans le coffre-fort souterrain serait un VIP du casino. Comment alliez-vous relier cela à une infirmière stagiaire ?", "Emily")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Heureusement, j'ai réagi rapidement et j'ai trouvé une raison qui vous ferait penser que votre couverture n'avait pas été dévoilée...", "Emily")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Vault.png")
	await novel_interface.show_dialog("À en juger par la façon dont vous êtes habillée, quelle jeune femme riche a subi un lavage de cerveau par une vidéo promotionnelle d'une ONG ?", "Emily")
	await novel_interface.show_dialog("...Ou essayiez-vous de compléter votre CV pour obtenir des crédits universitaires ?", "Emily")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_MasadAPC.png")
	await novel_interface.show_text_only("Alors c'était ça !?\nJe pensais vraiment m'en être tiré !")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("Alors toi...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","normal")
	await novel_interface.show_dialog("Toi aussi tu as eu de la chance. L'équipe de récupération n'a trouvé aucun élément hétérogène, donc Monola a probablement acheté de fausses informations, tout comme vous.", "Emily")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ce sarcophage noir a-t-il perdu ses propriétés hétérogènes simplement parce que je l'ai touché ?")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("Alors à ce moment-là, j'ai pensé que je pourrais peut-être utiliser votre chance pour gérer quelques affaires personnelles.", "Emily")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Vos \"affaires personnelles\" ont l'air plutôt dangereuses...")
	await novel_interface.show_text_only("L’intérieur du véhicule était rempli d’équipements sous couverture militaire NBC, ainsi que de toutes sortes d’armes lourdes.")
	await novel_interface.show_text_only("L'écran de projection à l'intérieur de l'APC affichait le flux en direct de la caméra montée sur le dessus. Nous avions déjà atteint la zone proche du mur d’isolement.")

	print("=== 星尘降临篇第12话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
