# stardustdescends_ep09.gd - 星尘降临篇第9话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep09_script()

func play_script():
	pass

func stardustdescends_ep09_script():
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Ordovician.png")
	await novel_interface.show_text_only("People always love to speculate: if a powerful alien civilization exists, is it benevolent or malicious?")
	await novel_interface.show_text_only("A likelier answer is──it is indifferent.")
	await novel_interface.show_text_only("One day 449 million years ago, a beam of high-energy gamma rays from 6,000 light-years away pierced the atmosphere and struck Earth.")
	await novel_interface.show_text_only("In an instant, the radiation destroyed a third of the ozone layer, allowing ultraviolet light from the sun to pass directly through the atmosphere.")
	await novel_interface.show_text_only("Huge amounts of plankton died, shattering the foundation of the marine food chain, and famine began to spread.")
	await novel_interface.show_text_only("Several decades after the disaster, shattered atmospheric molecules recombined, forming vast amounts of toxic nitrogen dioxide.")
	await novel_interface.show_text_only("The nitrogen dioxide blotted out the sky, blocking 50% of sunlight. Deprived of sunlight, Earth began to cool rapidly.")
	await novel_interface.show_text_only("Ocean temperatures dropped from 25 degrees to 10, and the further death of plankton accelerated the collapse of the food chain.")
	await novel_interface.show_text_only("Five hundred years after the catastrophe, a third of all life on Earth had vanished, and what remained struggled through hunger and cold.")
	await novel_interface.show_text_only("With sunlight diminished, huge amounts of seawater froze worldwide. Glaciers spread at unimaginable speed, and sea levels fell by 100 meters.")
	await novel_interface.show_text_only("One hundred and fifty thousand years after the disaster, the global average temperature dropped to 5 degrees. Most of the surface was covered in ice, and over half of all species perished in the cold.")
	await novel_interface.show_text_only("The careless misstep of a distant star collapsing somewhere in the galaxy plunged ancient life on Earth into endless despair.")
	await novel_interface.show_text_only("──That accident is known to history as the Late Ordovician mass extinction.")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("The Fifth School City.")
	await novel_interface.show_text_only("As a gentle melody played in the background, the man sprawled on the sofa slowly woke up...")
	novel_interface.change_music("res://assets/audio/music/Sunset.mp3")
	novel_interface.show_background("res://assets/images/bg/Fabiola/BAR.png")
	await novel_interface.show_text_only("With stubble on his face and hair in disarray, he struggled upright using the sofa back for support.")
	await novel_interface.show_text_only("A glass of water sat on the table before him. His throat felt as dry as if he had just walked out of the desert, so he snatched it up and drained it in one gulp.")
	await novel_interface.show_text_only("Then a splitting headache hit him. He clutched his head and groaned for a while, then suddenly stood up as though looking for something.")
	await novel_interface.show_text_only("Once he found his briefcase beside the sofa and confirmed the documents inside were intact, he felt slightly reassured and sat down again.")
	novel_interface.show_character("shi","normal")
	await novel_interface.show_dialog("This is...
Where am I...?", "Professor Shih")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Professor Shih looked around. The place resembled an upscale bar, with soft music drifting through the room and neon lights flickering on the buildings outside.")
	await novel_interface.show_dialog("You're awake?", "Female Voice")
	await novel_interface.show_text_only("Following the voice, Professor Shih saw a red-haired woman in a white coat approaching slowly with a pale yellow drink in her hand.")
	await novel_interface.show_text_only("She set the drink before him and took the sofa opposite.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("It's electrolyte water. It'll help with the headache.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("shi","normal")
	await novel_interface.show_dialog("You are...?", "Professor Shih")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Professor Shih stared suspiciously at her face, as though he had some vague memory of her.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("You should know me──", "Mariru")
	await novel_interface.show_dialog("I am Mariru von Braun. Last year, when you came to New Toyosu Academy of Sciences as a visiting scholar, you attended my lecture on crystalline heteromorphic objects.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru paused, then smiled and continued.")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("Also, I'm the head of SID.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Professor Shih jolted, instinctively wanting to run, but quickly abandoned that childish thought──")
	await novel_interface.show_text_only("Mariru handed him a tablet and said soothingly,")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Don't be afraid. It's very safe here──", "Mariru")
	await novel_interface.show_dialog("And if it weren't for us, you'd already be dead.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Professor Shih took the tablet suspiciously. It was showing street surveillance footage.")
	await novel_interface.show_text_only("He suddenly remembered waiting in that villa for a long time without seeing the buyer he had arranged to meet. When he left, he called a taxi.")
	await novel_interface.show_text_only("While waiting by the roadside, he felt a sharp pain in his neck, and then everything went black...")
	novel_interface.show_character("shi","normal")
	await novel_interface.show_dialog("This is...", "Professor Shih")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("In the footage, Professor Shih was standing by the road waiting for the taxi. As an unremarkable middle-aged woman passed behind him, she suddenly pulled out a syringe──")
	await novel_interface.show_text_only("With clean, efficient motion, she drove the needle into his neck, then swiftly caught his collapsing body from behind.")
	await novel_interface.show_text_only("About three seconds later, a black van with its side door open pulled up to the curb, and two people inside hauled him into the vehicle.")
	await novel_interface.show_text_only("Then the van sped away. In under ten seconds, he had vanished as if he had evaporated from the world.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("These people were killers hired online by an anonymous client for a high price. Luckily, we stopped the van at the first intersection...", "Mariru")
	await novel_interface.show_dialog("At the time they were just about to inject you with a neurotoxin. One step later and you'd be brain-dead right now.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Professor Shih sucked in a cold breath and stiffened.")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Which is why...", "Mariru")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("Just who did you offend?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("shi","angry")
	await novel_interface.show_dialog("Offend...?
H-How could that be!", "Professor Shih")
	await novel_interface.show_dialog("I'm just a scholar. Who could I possibly have offended...", "Professor Shih")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("That villa has always had a solid reputation as an \"underground brokerage.\" Whether it was arms deals, classified documents, or heteromorphic objects──", "Mariru")
	await novel_interface.show_dialog("Under the guarantee of the organization called \"Seven Commandments,\" no matter how vile the buyer or seller, no one dared cross the line.", "Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("But this time, the buyer you contacted was willing to take such a risk to eliminate a worthless novice like you. Why?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Professor Shih defensively pulled in his coat collar and glanced at his old leather bag.")
	novel_interface.show_character("shi","normal")
	await novel_interface.show_dialog("You've already seen it, right? This is a \"top secret\" file from the First School City. Could it be the Formless Gate...", "Professor Shih")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru leaned back against the sofa and laughed dismissively──")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("If even someone like you can take it abroad, then it can't be that secret.", "Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Three identical documents have already shown up on the market, and Masada's intelligence department got one too.", "Mariru")
	await novel_interface.show_dialog("It can even be inferred that Huayungong deliberately allowed this document to leak──", "Mariru")
	await novel_interface.show_dialog("And as far as I know, the other sellers who traded this information all completed their deals without incident.", "Mariru")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("Compared to them, what is so special about you that they had to risk silencing you?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Professor Shih stared vacantly for a long while, unable to say a word.")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("My guess is that the price you quoted to your previous buyer wasn't just money, was it...", "Mariru")
	await novel_interface.show_dialog("Perhaps what you asked for was precisely what nearly got you killed?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("The man opposite Mariru let out a long sigh, relaxed, and leaned back against the sofa.")
	novel_interface.show_character("shi","eyeclose")
	await novel_interface.show_dialog("People like you... are terrifying.", "Professor Shih")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("I'm flattered~", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("The corners of Mariru's mouth rose slightly.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Since you understand the situation you're in now──", "Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Then let's talk about our deal.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.stop_music()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("The Third School City, Masada Port customs.")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_MasadaCustoms.png")
	novel_interface.show_character("ren_medical","stare")
	await novel_interface.show_dialog("Can something that looks like a tattoo really biodegrade on its own...?", "Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I rubbed the barcode on the back of my hand. Apparently the ink uses some kind of heteromorphic processing and disappears automatically at a preset time.")
	await novel_interface.show_text_only("This barcode is Masada customs' entry permit and the only legal ID foreigners have while staying in the country.")
	await novel_interface.show_text_only("The moment the permitted stay expires, the ink is supposed to evaporate on its own.")
	await novel_interface.show_text_only("Without this barcode, any soldier or inspection officer in Masada has the right to arrest me on the spot.")
	novel_interface.show_character("ren_medical","uneasy")
	await novel_interface.show_dialog("(Hmm... it won't rub off when I shower, right?)", "Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("stardust_small","disgust")
	await novel_interface.show_dialog("So slow...", "Stardust")
	novel_interface.change_expression("wordless")
	await novel_interface.show_dialog("Waaah waaah aaawoo~~", "Stardust")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tired of waiting, Stardust mumbled nonsensical syllables under her breath as she wriggled over to the corridor window and clung to the pillar to look outside.")
	await novel_interface.show_text_only("I brought her through the special passage for the International Medical Relief Organization, but Annie had to queue up through the regular security lane for ordinary visitors.")
	await novel_interface.show_text_only("Masada's security is famous worldwide for being brutally strict; even in the port lobby, soldiers with live ammunition patrol everywhere.")
	await novel_interface.show_text_only("I walked up behind Stardust and looked east through the window. There I could see the calm blue Dead Sea and the Elijah Dam standing at the end of the Grand Canal.")
	await novel_interface.show_text_only("Near the outflow on the southern side of the Dead Sea dam, the water was marbled with uneven turquoise and pale blue, and the farther north you looked, the deeper the water's color became.")
	await novel_interface.show_text_only("According to Genesis, the two sinful cities destroyed by God—Sodom and Gomorrah—lie sunken beneath the southern Dead Sea.")
	await novel_interface.show_text_only("I wondered whether the sea still held wandering spirits nursing resentment toward \"that great one.\"")
	await novel_interface.show_text_only("At that moment, on the northeastern horizon, the dark red haze born of the sandstorm was beginning to stir.")
	await novel_interface.show_text_only("But what struck me most as strange was that this little girl had been the one to tell me about the sandstorm──")
	novel_interface.show_character("stardust_small","konata_eye")
	await novel_interface.show_dialog("Mm?", "Stardust")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","smile")
	await novel_interface.show_dialog("Hey~ do you know Masada's history?", "Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She blinked at me with a \"What are you even talking about?\" expression, while the cat-ear-like headphones on her head flashed twice quickly.")
	novel_interface.show_character("ren_medical","smile")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("stardust_small","normal1",0.25)
	await novel_interface.show_dialog("In Aramaic, Masada means \"fortress.\" It was originally a palace built atop a hill, and also a powerful defensive fortification──", "Stardust")
	await novel_interface.show_dialog("In the year 72, with only a thousand defenders, Masada Fortress held out for two years under siege by the Roman legions. When the city finally fell, the defenders committed mass suicide.", "Stardust")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Just like earlier in the restaurant, she mechanically recited the standard encyclopedia answer as though reading from a book.")
	novel_interface.show_character("ren_medical","wry_smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("stardust_small","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("...Do you actually understand what you just said means?", "Ren")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"konata_eye")
	await novel_interface.show_dialog("Nope~!", "Stardust")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("She gave me a carefree smile.")
	await novel_interface.show_text_only("Are you a smart speaker or something!?")
	await novel_interface.show_text_only("The especially dumb kind, at that...")
	await novel_interface.show_text_only("I don't know much about history. I only know Masada's had it rough for thousands of years, and during the Seven-Year War even their original holy-capital city was destroyed.")
	novel_interface.show_character("ren_medical","upset")
	await novel_interface.show_dialog("Man... those people really have had a rough road.", "Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Thinking that, I could kind of understand the feeling behind the slogan on the immigration hall beam: \"Masada Shall Never Fall.\"")
	novel_interface.show_character("ren_medical","upset")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("stardust_small","happy",0.25)
	await novel_interface.show_dialog("Ah! Annie──", "Stardust")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Stardust pointed toward the security exit and called out. Annie was pulling her suitcase and walking toward us from there.")
	await novel_interface.stop_music()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("Harima Neuroscience Research Center, Experimental Medical Division.")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Dementium.png")
	await novel_interface.show_text_only("Sitting on the bed of the mind-diving device, Mariru rubbed her temples wearily──")
	await novel_interface.show_text_only("Aya walked in and handed her a bottle of electrolyte water.")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("How was it? Get anything out of the interrogation?", "Aya")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Yeah... we got some interesting intel.", "Mariru")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("How's Professor Shih doing now?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("Well... he's still in a deep coma. His brainstem reflexes are weak, and his life has to be maintained by machines──", "Aya")
	await novel_interface.show_dialog("The chelating agent cleared most of the neurotoxins out of his body, but we can't tell how much damage was already done, or whether he'll ever wake up.", "Aya")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("This setup is the only way we have right now to get information out of him~", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru unscrewed the cap and took a big swig before speaking.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("He said he stole and sold the documents in order to find his daughter.", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","wink",0.25)
	await novel_interface.show_dialog("Huh? I thought that old fossil was single~", "Aya")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("His daughter graduated from Berkeley's astronomy department six years ago and was recruited into a classified NASA project before the federal government dissolved.", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"think")
	await novel_interface.show_dialog("NASA? That's a name I haven't heard in a while...", "Aya")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("Was it some military space-weapon project?", "Aya")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("It was an astronomical observation project──", "Mariru")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("NASA supposedly received a flickering high-frequency signal in a specific band while observing a certain coordinate in the Pleiades cluster.", "Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("The signal was clearly directional and could only be received from a specific orbital position──", "Mariru")
	await novel_interface.show_dialog("Like a laser fired at the solar system from 400 light-years away, observable only if you happened to be standing in its narrow path.", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Aya's cheeks immediately flushed with excitement as she asked,")
	novel_interface.show_character("liliu_research","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ai","dizzy",0.25)
	await novel_interface.show_dialog("Like... a message transmitted directionally through optical fiber?", "Aya")
	novel_interface.change_2nd_expression("blush_dizzy")
	await novel_interface.show_dialog("D-Does that mean──?!", "Aya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru nodded slightly.")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_CrabNebula.png")
	await novel_interface.show_text_only("In 1967, astronomers first observed a set of regular pulse signals.")
	await novel_interface.show_text_only("At first they thought the signal came from extraterrestrial life and nicknamed it \"Little Green Men.\"")
	await novel_interface.show_text_only("Later it was identified as a pulsar rather than something made by intelligent life, but humanity never stopped listening for extrasolar signals.")
	await novel_interface.show_text_only("Countless astronomers and hobbyists have spent their whole lives hoping to receive a transmission from outer space.")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Dementium.png")
	novel_interface.show_character("liliu_research","angry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ai","blush_dizzy",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("This project began more than a decade ago, but after the Black Christmas incident, NASA itself fell into paralysis.", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("Black Christmas...", "Aya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("On December 24, 2033, a gigantic spherical \"Black Zone\" appeared without warning over the sea near New Moridas.")
	await novel_interface.show_text_only("In an instant, the Black Zone swallowed most of the federal government's seaborne combat forces and put a pitch-black period on the Seven-Year War.")
	novel_interface.show_character("liliu_research","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ai","normal",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Back then, Professor Shih received an email from his daughter containing the Shannon entropy signature value of that project.", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"think")
	await novel_interface.show_dialog("I remember. It's like the fingerprint of an electromagnetic signal, right?", "Aya")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Exactly. After that, his daughter vanished without a trace. Everything else he learned was pieced together through his own investigation over the last several years.", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare") 
	await novel_interface.show_dialog("That old guy's more capable than he looks...", "Aya")
	novel_interface.character_light(0.35,"speak")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("The interesting part is that when that black sarcophagus-like EX-class heteromorphic object is activated, it emits electromagnetic waves with the exact same signature value──", "Mariru")
	await novel_interface.show_dialog("Only vastly stronger. The worst activation destroyed one of Huayungong's containment facilities.", "Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Once he learned that, he immediately applied to return home and voluntarily joined the research team studying the sarcophagus.", "Mariru")
	await novel_interface.show_dialog("However, after the last International Peace Forum, the whole project team was abruptly dissolved.", "Mariru")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Huayungong's upper management apparently intends to hand the sarcophagus to the Church for permanent sealing.", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"think") 
	await novel_interface.show_dialog("Then the last clue to his daughter would be cut off too, so...", "Aya")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("So he stole this classified file and tried to use dark-web brokers to trade for information.", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("Ah, I get it. What he wanted was NASA's──?", "Aya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru smiled as if she'd just obtained the toy she'd been wanting.")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Exactly.", "Mariru")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("The reason someone came after his life was that he asked a dark-web broker for the internal materials of NASA's \"Project 0812.\"", "Mariru")

	print("=== 星尘降临篇第9话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
