# stardustdescends_ep07.gd - 星尘降临篇第7话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep07_script()

func play_script():
	pass

func stardustdescends_ep07_script():
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Vault.png")
	await novel_interface.show_text_only("An diesem Punkt möchte ich einfach so schnell wie möglich hier raus. Ich gebe Stardust ein Zeichen und gehe dann zum Aufzug.")
	await novel_interface.show_text_only("Sie versteht sofort meine Absicht und holt mich schnell ein.")
	await novel_interface.show_text_only("Das kleine Mädchen scheint meine Angst zu spüren, also reibt sie sanft mein Handgelenk.")
	novel_interface.show_character("stardust_small","normal2")
	await novel_interface.show_dialog("(flüstern) Mach dir keine Sorgen.", "Stardust")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich spüre ihre weiche Hand und ihre Temperatur, beruhige mich allmählich und halte dann ihre Hand.")
	novel_interface.show_character("stardust_small","normal2")
	await novel_interface.show_text_only("Wir scheinen eine besondere Bindung zwischen uns aufgebaut zu haben. Sie beginnt zu lächeln.")
	await novel_interface.show_text_only("Es ist unheimlich – schließlich haben wir uns gerade erst kennengelernt.")
	await novel_interface.show_text_only("Und wie kam es, dass sowohl der Kellner als auch die Soldaten sie völlig ignorierten?")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Im Aufzug kneife ich in ihr weiches Gesicht, während ich versuche, die ganze Sache herauszufinden. Es gefällt ihr nicht.")
	novel_interface.show_character("ren_full","gratified")
	await novel_interface.show_dialog("(Ihre Haut beruhigt mich irgendwie...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Vielleicht ist sie wie Beatrice? Sie haben beide eine besondere Kraft, die ihnen selbst nicht einmal bewusst ist?")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Gambling_Boat3.png")
	await novel_interface.show_text_only("Während ich versuche, alle Möglichkeiten zu klären, bringt uns der Aufzug zurück in den VIP-Raum.")
	await novel_interface.show_text_only("Sobald sich die Tür öffnet, wird mir klar, wie ernst die Dinge geworden sind.")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Gambling_Boat.png")
	await novel_interface.show_text_only("Dutzende Gäste und Besatzungsmitglieder werden bereits von Masadan-Soldaten festgehalten. Sie wurden in vier Gruppen aufgeteilt und warten in der Schlange auf die Sicherheitskontrolle.")
	await novel_interface.show_text_only("Ein Angestellter nutzt ein militärisches Tablet, um trotz ihrer Einwände Fotos von allen Gästen zu machen.")
	await novel_interface.show_text_only("Um zu verhindern, dass die Gäste telefonieren und Strippen ziehen, wurde im Raum ein Störsender installiert.")
	await novel_interface.show_text_only("Auch mein Telefon und mein Ohrhörer können keine Signale empfangen. Stardust hat Angst vor dem, was sie sieht und versteckt sich hinter mir.")
	await novel_interface.show_text_only("Am Ausgang der Lobby verkündet ein Beamter über einen Lautsprecher die Regeln für die Sicherheitskontrolle.")
	novel_interface.show_character("valkyrja","normal")
	await novel_interface.show_dialog("Entfernen Sie Ihre Uhren, Ihren Schmuck und alle anderen Metallgegenstände.", "Offizier")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("Kleben Sie einen Identifikationscode auf alle Ihre Taschen und Koffer und bringen Sie diese dann zum Scannen hierher.", "Offizier")
	await novel_interface.show_dialog("Wenn alles klappt, bekommst du ein blaues Armband. Nur wer das Bändchen hat, kann hier raus.", "Offizier")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("Diese Sicherheitskontrolle ist kein Scherz...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich überprüfe, ob ich mein Armband noch habe.")
	novel_interface.show_character("ren_full","worry")
	await novel_interface.show_dialog("(Dieses Armband hier bedeutet, dass ich jetzt im Klaren bin?)", "Lian")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("(Ich werde abwarten und sehen, nur um sicherzugehen.)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich schaue mich um. Von allen Soldaten auf dieser Etage ist nur der Offizier mit dem Lautsprecher ein Mädchen. Und genau wie Emily ist auch sie sehr jung.")
	await novel_interface.show_text_only("Alle anderen Soldaten scheinen sie jedoch wirklich zu respektieren.")
	novel_interface.show_character("ren_full","bored")
	await novel_interface.show_dialog("(Sie sieht aus wie eine Oberschülerin...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Plötzlich befreit sich ein kräftiger Mann und eilt zum Ausgang. Er schreit die Beamtin an.")
	novel_interface.show_character("miller")
	await novel_interface.show_dialog("Ich bin Erzbischof Miller von der Anglikanischen Kirche Südindiens. Sie haben nicht das Recht, Diener Gottes zu befragen!", "Miller")
	await novel_interface.show_dialog("Außerdem ist deine Uniform... das ist überhaupt keine Uniform der Masada Defence Force!", "Miller")
	await novel_interface.show_dialog("Wer bist du wirklich? Wer hat diese Operation autorisiert?", "Miller")
	await novel_interface.show_dialog("Ich verlange das Gespräch mit Ihrem Vorgesetzten!", "Miller")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Wie ein kleiner Berg steht der aggressive Erzbischof vor dem jungen Mädchen.")
	novel_interface.show_character("valkyrja","normal2")
	await novel_interface.show_dialog("Oh, ich habe nie gesagt, dass es sich um eine Uniform der Masada Defence Force handelt. Ich bin Warrant Officer Vera Valkyrie, die kommandierende Offizierin auf Zeit.", "Offizier")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("Wer bist du nochmal? Jemand aus Südindien?\nSind Sie eine Art Steuerinspektor?", "Vera")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Vera scheint etwas erkannt zu haben.")
	novel_interface.show_character("valkyrja","speechless")
	await novel_interface.show_dialog("Kein Wunder, dass Sie groß sind ... Das hängt wohl mit dem Territorium Ihres Jobs zusammen.", "Vera")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("Als ich jedoch das letzte Mal nachgesehen habe, befand sich in dieser Region Krieg. Zahlen die Menschen im Krieg noch ihre Steuern?", "Vera")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sie ignoriert völlig das rote Gesicht des Erzbischofs, als sie das Tablet aufhebt, das ihr ein Angestellter reicht.")
	novel_interface.show_character("valkyrja","happy")
	await novel_interface.show_dialog("Naja, na ja... Wer hätte das gedacht. Sie besitzen ein Visum für religiöse Arbeit.", "Vera")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Vera lacht verächtlich und blickt dann auf den Roulettetisch.")
	novel_interface.show_character("valkyrja","happy")
	await novel_interface.show_dialog("Ein Diener Gottes. Ich verstehe ... Jemand wie Sie hat die Zeit und die Mittel, all das köstliche Essen zu essen. Hatten Sie Spaß im Casino?", "Vera")
	novel_interface.change_expression("wink")
	await novel_interface.show_dialog("Und hier dachte ich: „Gott würfelt nicht.“", "Vera")
	await novel_interface.hide_character()
	novel_interface.show_character("miller")
	await novel_interface.show_dialog("Das ist Blasphemie!", "Miller")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Der Erzbischof kann es nicht mehr ertragen. Er beginnt zu schreien, als er sich Vera nähert und bereit ist, körperlich anzugreifen. Doch bevor er Vera erreichen kann, packt sie ihn am Kragen.")
	await novel_interface.show_text_only("Ich bin schockiert über das, was ich sehe.")
	await novel_interface.show_text_only("Mit nur einer Hand hebt Vera den schweren Erzbischof in die Luft.")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("(Welche Stärke!)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","speechless")
	await novel_interface.show_dialog("Falls Sie mich beim ersten Mal nicht gehört haben ...", "Vera")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("Ich bin kein Soldat. Ich bin ein Kadett des „Talpiot-Programms“, der in letzter Minute hierher versetzt wurde.", "Vera")
	await novel_interface.show_dialog("Ich will nichts davon, aber die Leute im Ausschuss für Streitkräfte glauben, sie könnten uns herumkommandieren.", "Vera")
	await novel_interface.show_dialog("Und sie können! Ich war in letzter Zeit sauer darüber. Wenn du mir noch einmal in die Quere kommst, werfe ich dich ins Meer und verfüttere dich an Haie!", "Vera")
	await novel_interface.show_dialog("Sind wir klar?!", "Vera")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Das Gesicht des Erzbischofs ist lila geworden. Da er nicht in der Lage ist zu sprechen, nickt er hastig.")
	novel_interface.show_character("valkyrja","angry")
	await novel_interface.show_dialog("Komm zurück in deine Schlange!", "Vera")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sobald er losgelassen wird, eilt der Erzbischof zu seiner Linie zurück, während er wieder zu Atem kommt.")
	novel_interface.show_character("ren_full","wry_smile")
	await novel_interface.show_dialog("Äh, entschuldigen Sie...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich gehe vorsichtig näher und zeige ihr mein Armband.")
	novel_interface.show_character("ren_full","wry_smile")
	await novel_interface.show_dialog("Ich habe mein Armband bereits. Kann ich jetzt gehen?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Vera ist ein wenig überrascht. Sie scannt den Barcode auf meinem Armband und lächelt dann.")
	novel_interface.show_character("valkyrja","wink")
	await novel_interface.show_dialog("Ja, du kannst gehen.", "Vera")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich fühle mich erleichtert. Ich bin auch froh, dass auf dieser Etage auch niemand Stardust sehen kann.")
	await novel_interface.show_text_only("Sobald ich den Raum verlasse, kommt ein Casino-Mitarbeiter auf mich zu, um sich zu entschuldigen.")
	await novel_interface.show_text_only("Ihm zufolge wird Lebona mit Masada verhandeln, um sicherzustellen, dass keine Kundeninformationen durchsickern.")
	await novel_interface.show_text_only("Die Signale in der gesamten Kabine sind gestört. Er sagt mir, wenn ich telefonieren muss, kann ich den Festnetzanschluss nutzen oder aufs Achterdeck gehen.")
	novel_interface.change_music("res://assets/audio/music/unkown/UI_Main_Funk.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/Vessel.png")
	await novel_interface.show_text_only("Ich ziehe Stardust und gehe bis zum Deck.")
	await novel_interface.show_text_only("Neben dem Glücksspielschiff liegt ein Patrouillenboot vom Typ Super Dvora Mk, an dem die blau-weiße Nationalflagge hängt.")
	novel_interface.show_character("ren_full","smile")
	await novel_interface.show_dialog("Endlich etwas frische Luft!", "Lian")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("(Schließlich sind alle Fenster im Casino geschlossen.)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich strecke meine Arme aus, während ich auf die Brücke über den Kanal blicke.")
	novel_interface.show_character("ren_full","gratified")
	await novel_interface.show_dialog("Ist das der Suezkanal?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("stardust_small","happy",0.25)
	await novel_interface.show_dialog("Wow!", "Stardust")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Stardust ist aufgeregter als ich. Sie hüpft bis zum Schiffszaun.")
	novel_interface.show_character("ren_full","worry")
	await novel_interface.show_dialog("(Ist es nur ein Zufall? Stardust steuert auf das Heck des Schiffes zu.)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Plötzlich klingelt mein Telefon – eine vertraute Stimme erwartet mich.")
	await novel_interface.show_dialog("Lian? Geht es dir gut?", "Annie")
	await novel_interface.show_dialog("Es geht ihr gut. Sie macht Dehnübungen mit Blick auf den Ozean.", "Mariru")
	await novel_interface.show_dialog("Ah, der süße Duft der Jugend! Ist das Ihre Art, ein noch größeres Paar zu bekommen?", "Aya")
	await novel_interface.show_text_only("Es stellt sich heraus, dass es sich um eine Telefonkonferenz handelt – Mariru und einige andere sind ebenfalls am Telefon ...")
	novel_interface.show_character("ren_full","awkward")
	await novel_interface.show_dialog("Sie spionieren mich aus?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich schaue mich um und entdecke kein Überwachungsgerät. Dann wird mir klar, dass es wahrscheinlich von weit oben kommt.")
	novel_interface.show_character("ren_full","shy")
	await novel_interface.show_dialog("(Es fühlt sich komisch an zu wissen, dass ein Augenpaar jede meiner Bewegungen beobachtet ...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Kommen wir zum Punkt: Was ist vorher passiert?", "Mariru")
	novel_interface.show_character("ren_full","shy_left")
	await novel_interface.show_dialog("Wo fange ich an?...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich räuspere mich und erzähle ihnen dann alles, was passiert ist. Ich weise ausdrücklich darauf hin, dass niemand Stardust sehen kann.")
	await novel_interface.show_dialog("Sie ist direkt neben dir? Nach allem, was wir gesehen haben, sind Sie allein aus der Lobby gegangen ...", "Annie")
	await novel_interface.show_dialog("Ich habe mich gefragt, wie Sie die Sicherheitskontrolle so schnell bestanden haben – Sie waren die erste Person, die rauskam!", "Annie")
	novel_interface.show_character("ren_full","gratified")
	await novel_interface.show_dialog("Es ist der Leutnant, den ich im Tresor getroffen habe. Sie scannte meinen gefälschten Ausweis und gab mir dann mein Armband.", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Masadan-Soldaten hätten nicht so nachlässig sein dürfen ...", "Mariru")
	novel_interface.show_character("ren_full","worry")
	await novel_interface.show_dialog("Oh, noch etwas. Sowohl der kommandierende Offizier in der Lobby als auch der Leutnant im Tresorraum sind junge Mädchen, nicht älter als 20.", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Was? Ich weiß, dass auch Frauen in Masada der Wehrpflicht unterliegen, aber in diesem Alter schon?", "Annie")
	novel_interface.show_character("ren_full","normal1")
	await novel_interface.show_dialog("Der Beamte in der Lobby erwähnte, sie sei eine Kadettin des „Talpiot-Programms“. Sie wurde in letzter Minute hierher versetzt.", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Das erklärt es...", "Mariru")
	await novel_interface.show_dialog("Talpiot war jahrzehntelang eine Elite-Militärakademie, die direkt dem Generalstab von Masada unterstand.", "Mariru")
	await novel_interface.show_dialog("Später erweiterte das Masadan-Militär es zum „Talpiot-Programm“. Es lädt nur das oberste Prozent der gewöhnlichen Mittelschüler und Militärschüler zum Ausprobieren ein.", "Mariru")
	await novel_interface.show_dialog("Jedes Jahr bestehen nur ein paar Dutzend Kandidaten die anstrengende geistige, körperliche und IQ-Prüfung.", "Mariru")
	await novel_interface.show_dialog("Es handelt sich um eine Pipeline für die Ausbildung künftiger militärischer Eliten, und auf dem Lehrplan stehen sogar kleine Feldeinsätze.", "Mariru")
	await novel_interface.show_dialog("Monola hat viele Absolventen aus dem „Talpiot-Programm“ rekrutiert. Sie sind für ihre Professionalität und Loyalität bekannt.", "Mariru")
	novel_interface.show_character("ren_full","worry")
	await novel_interface.show_dialog("Eine Elite-Militärschule, ja?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ich glaube nicht, dass Lian und ich reinkommen könnten...", "Annie")
	await novel_interface.show_dialog("Armer Lian...", "Aya")
	await novel_interface.show_text_only("Aya zögert, ihren Satz zu beenden.")
	await novel_interface.show_dialog("Das Mädchen, von dem du gesprochen hast. Ist sie gerade bei dir auf dem Deck?", "Aya")
	novel_interface.show_character("ren_full","worry")
	await novel_interface.show_dialog("Ja. Warum?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Aber selbst der Temperatursensor zeigt an, dass Sie allein auf dem Deck sind ...", "Aya")
	await novel_interface.show_text_only("Jetzt weiß nicht einmal ich sicher, aber da ist sie, sie hockt vor dem Zaun und starrt in eine Richtung.")
	await novel_interface.show_text_only("Plötzlich steht sie auf und zeigt mir die Richtung, in die sie geschaut hat.")
	novel_interface.show_character("stardust_small","happy")
	await novel_interface.show_dialog("Wir... werden dorthin gehen!", "Stardust")
	novel_interface.change_expression("pleased")
	await novel_interface.show_dialog("Ich kann mich nicht erinnern, warum, aber irgendetwas sagt mir, dass wir dorthin gehen.", "Stardust")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("Sonst... Sonst gibt es eine Katastrophe...", "Stardust")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("Bitte! Wir gehen bitte zusammen!", "Stardust")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Stardust packt meinen Kopf und starrt mich mit ihren großen Augen an, nur ein kleines Kind, das seine Mutter um Spielzeug bettelt.")
	novel_interface.show_character("ren_full","wry_smile")
	await novel_interface.show_dialog("Hast du... gehört, was sie gerade zu mir gesagt hat?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ich habe dich nur gehört...", "Annie")
	await novel_interface.show_dialog("Der Ton wird durch Stimmlippenvibration erzeugt. Wenn es keinen physischen Körper gibt, kann es keinen Ton geben.", "Aya")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("Aber... Aber ich kann sie sehen, berühren und ihre Körpertemperatur spüren...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Basierend auf dem, was Sie beschrieben haben, wurde Ihr Gehirn wahrscheinlich durch etwas beeinträchtigt. Und danach sendet es Ihnen neuronales Feedback, das nur Sie wahrnehmen können.", "Aya")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("Aber ich kann sogar ihren Schatten sehen!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich versuche zu argumentieren und kann ihre Erklärung nicht akzeptieren.")
	await novel_interface.show_dialog("... Versuchen Sie es mit der Kamera Ihres Telefons.", "Mariru")
	await novel_interface.show_text_only("Das ist eine gute Idee! Aber wenn ich meine Kamera auf sie richte...")
	await novel_interface.show_text_only("Es ist niemand im Kamerabild!")
	await novel_interface.show_text_only("Sobald ich jedoch mein Telefon wegbewege, sehe ich sie wieder, wie sie mich immer noch bettelt.")
	novel_interface.show_character("ren_full","panic")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("stardust_small","happy",0.25)
	await novel_interface.show_dialog("Bitte!", "Stardust")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Ich glaube immer noch nicht, dass das Mädchen nur eine Illusion ist. Ich durchsuche ihre Handtasche und finde den rosa Zettel mit ihrem Namen darauf.")
	await novel_interface.show_text_only("Immer noch das Gleiche – ich kann die Notiz in meinem Kamerarahmen nicht sehen.")
	await novel_interface.show_text_only("Und dieses Mal ist die Notiz verschwunden, nachdem ich mein Telefon weggenommen habe!")
	await novel_interface.show_text_only("Ich strecke meine zitternde Hand aus und platziere mein Telefon über Stardust.")
	await novel_interface.show_text_only("!!! Mein Handy fällt direkt auf den Boden!")
	novel_interface.show_character("stardust_small","konata_eye")
	await novel_interface.show_dialog("?", "Stardust")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Meine Ohren klingeln, meine Gliedmaßen werden plötzlich schwer.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Nach einer Weile höre ich Ayas Stimme am Telefon.")
	novel_interface.show_background("res://assets/images/bg/Stardust/Vessel.png")
	await novel_interface.show_dialog("Ich habe eine Theorie – eigentlich eher eine Vermutung.", "Aya")
	novel_interface.show_character("ren_full","sob")
	await novel_interface.show_dialog("Sag es mir.", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Denken Sie an all die Hexen, die Sie zuvor beschworen haben. Sie waren keine „Geister“ wie dieser, und sie hatten alle ihr vollständiges Gedächtnis.", "Aya")
	await novel_interface.show_dialog("Ihren Angaben zufolge leidet sie unter Gedächtnisverlust und ist nicht zu sehen. Vielleicht sind die Voraussetzungen für ihre Beschwörung nicht vollständig erfüllt?", "Aya")
	await novel_interface.show_dialog("Hat sie um etwas gebeten? Oder gibt es dir überhaupt einen Hinweis?", "Aya")
	novel_interface.show_character("ren_full","happy")
	await novel_interface.show_dialog("Darüber... Ja!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich finde plötzlich Hoffnung. Ich zeige in die Richtung, in die Stardust gehen möchte.")
	novel_interface.show_character("ren_full","happy")
	await novel_interface.show_dialog("Sie will dorthin. Nicht der genaue Ort, aber irgendwo da drüben.", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich höre das Geräusch einer Tastatur über das Telefon.")
	await novel_interface.show_dialog("318 Meilen in diese Richtung...", "Mariru")
	await novel_interface.show_dialog("Es ist die Festung Masada!", "Annie")

	print("=== 星尘降临篇第7话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
