# stardustdescends_ep4.gd - 星尘降临篇第4话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep4_script()

func play_script():
	pass

func stardustdescends_ep4_script():
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Hospital_Passage.png")
	await novel_interface.show_text_only("Quelques heures plus tard – Harima Tech Research Center")
	await novel_interface.show_text_only("Une petite fille vérifie paresseusement sa tablette tout en parlant dans son écouteur.")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("Ne vous inquiétez pas. Les deux gardes font un doux rêve au moment où nous parlons.", "Aya")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("Ne sous-estimez pas le cerveau humain : il est disposé et capable de rationaliser les situations dans lesquelles il se trouve.", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Aya jette à nouveau un coup d'œil autour de la pièce. Deux hommes en costume noir sont allongés sur une paire d'appareils Mind Diving.")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("Après tout, les gens sont plus susceptibles de croire aux mensonges qu’ils fabriquent eux-mêmes…", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Soudain, quelque chose sur la tablette d'Aya attire son attention. Elle fait défiler rapidement plusieurs pages, puis revient aux données intéressantes.")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("C'est...", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Qu'est-ce que c'est ?", "Mariru")
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("Le capteur Boltzmann a dépassé sa valeur maximale au moment où les fronts de Lian et Nix se sont touchés.", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Un dysfonctionnement ? Je pensais que vous aviez déjà fixé le plafond théorique à sa valeur la plus élevée possible.", "Mariru")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("Presque la valeur la plus élevée possible. Si le volume de données atteignait la limite de Bekenstein, ce serait une autre affaire.", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Êtes-vous en train de dire qu’à ce moment-là, le volume de données a atteint le niveau le plus élevé qu’une substance puisse transporter ?", "Mariru")
	await novel_interface.show_text_only("Aya fait quelques calculs rapidement sur sa tablette.")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("Si l'on met de côté cette seule anomalie, les paramètres de Nix sont très proches de ceux d'une sorcière. Elle ne s’en est probablement même pas rendu compte elle-même.", "Aya")
	await novel_interface.show_dialog("Alors, quelque chose comme Raphilia ?\nSi seulement Sonya n'était pas partie pour une autre mission...", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Aya allume la vidéo de surveillance pendant qu'elle se plaint.")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("Ce n'est pas un dysfonctionnement. Toutes les lectures sont rapidement revenues à la normale. Depuis, le capteur fonctionne également très bien.", "Aya")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("Plus important encore, seul Lian a perdu connaissance alors que tous les autres allaient bien...", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Aya exclut rapidement toute possibilité. Au final, il semble n'y avoir qu'une seule explication...")
	novel_interface.show_character("ai","blush_dizzy")
	await novel_interface.show_dialog("Lian - et seulement Lian - a absorbé 2,5 Yo de données en moins d'une seconde...", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Aya a du mal à croire sa propre conclusion.")
	await novel_interface.show_dialog("...Rappelez-moi encore quelle est la taille d'une unité YB ?", "Mariru")
	novel_interface.show_character("ai","blush_dizzy")
	await novel_interface.show_dialog("Un yottaoctet équivaut à 10 puissance 24 octets, soit plus que toutes les données réunies sur Internet d'avant-guerre...", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La voix d'Aya tremble d'excitation.")
	novel_interface.show_character("ai","blush_dizzy")
	await novel_interface.show_dialog("Et je pensais que son cerveau n'était bon que pour les jeux...", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Yottaoctet. Je pense l'avoir vu dans le rapport du professeur Shih !", "Mariru")
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("Cet ancien météore du Hovering Palace !", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Aya sort rapidement ce rapport.")
	novel_interface.show_character("ai","blush_wink")
	await novel_interface.show_dialog("J'ai peur que nous devions compter sur Lian maintenant.", "Aya")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("Cinq jours plus tard, à bord du navire-casino de Lebona, le Liberty Star.")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Gambling_Boat.png")
	await novel_interface.show_dialog("Euh... mademoiselle ?", "Croupier")
	await novel_interface.show_dialog("Mademoiselle ?", "Croupier")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("C'est mon tour ?", "Lian")
	await novel_interface.show_dialog("Pliage en F...", "Lian")
	novel_interface.change_expression("perspire1")
	await novel_interface.show_dialog("Désolé, mais je dois m'asseoir un tour.", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La jeune fille quitte la table et se dirige vers un endroit calme dans un coin de l'allée.")
	novel_interface.show_character("ren_full","wry_smile")
	await novel_interface.show_dialog("J'ai eu une rougeur ! Pourquoi m'as-tu dit de me coucher ?!", "Lian")
	await novel_interface.show_dialog("(baisse la voix). Surtout après avoir déjà parié autant d'argent...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La voix basse de Lian ne peut cacher sa déception.")
	await novel_interface.show_dialog("Sortez votre téléphone et faites comme si vous étiez en communication, Lian. En ce moment, pour tout le monde, on dirait que vous marmonnez pour vous-même.", "Annie")
	await novel_interface.show_dialog("Il y a trois salles de contrôle sur ce navire. J'en ai déjà fait un raid...", "Annie")
	novel_interface.show_character("ren_full","wail")
	await novel_interface.show_dialog("(R- Raid ?!...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Les caméras sont partout sur ce navire. Si quelqu'un remarque votre micro-écouteur, vous serez jeté aux requins.", "Nix")
	await novel_interface.show_text_only("Je ressens des frissons dans le dos. Je sors précipitamment mon téléphone.")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("J'ai déjà perdu 20% de ce que j'avais apporté. N'as-tu pas dit que je devais doubler mon argent avant de pouvoir accéder à la salle VIP ?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Je regarde le numéro sur le bracelet émis par le casino et je me répète encore et encore : ce n'est pas de l'argent.")
	novel_interface.show_character("ren_full","sob")
	await novel_interface.show_dialog("(Mais c'est toujours de l'argent durement gagné par les contribuables de New Opulentia !)", "Lian")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Dispatched_Ship_Aisle.png")
	await novel_interface.show_text_only("A trente mille mètres d'altitude, à bord d'un SID transport lourd à grande vitesse, Nix regarde l'écran de projection avec une tasse de thé à la main.")
	novel_interface.show_character("nyx_normal","normal1")
	await novel_interface.show_dialog("Vous n’aviez que le 2 et le 6 de carreau. À en juger par son comportement, il y avait de fortes chances qu'il ait également une couleur, et ses cartes étaient presque certainement plus élevées que les vôtres.", "Nix")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Sérieusement ?!\nJ'étais sur le point de faire tapis...", "Lian")
	novel_interface.show_character("nyx_normal","speak")
	await novel_interface.show_dialog("*soupir*", "Nix")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elle ne sait pas comment l'expliquer clairement à Lian, la même fille qui s'est endormie en bavant sur un tas de chips d'une valeur de cinquante millions la nuit dernière.")
	novel_interface.show_character("nyx_normal","normal2")
	await novel_interface.show_dialog("L'erreur la plus courante qu'un débutant commet : chaque fois qu'il a une bonne main, il veut miser gros, voire faire tapis.", "Nix")
	await novel_interface.show_dialog("Comme si la bonne main les privait de toute capacité de réflexion analytique.", "Nix")
	await novel_interface.show_dialog("L'ignorance mène à la peur ; la peur mène à l’insouciance. En fin de compte, les débutants peuvent faire tapis pour mettre fin à leur peur.", "Nix")
	novel_interface.change_expression("sad")
	await novel_interface.show_dialog("Ils ne se sentiront libres qu’après avoir parié tout ce qu’ils ont.", "Nix")
	await novel_interface.show_dialog("Le résultat est que son adversaire peut facilement prédire sa décision à partir de son comportement.", "Nix")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("En un mot, vous ne gagnerez pas beaucoup d'argent lorsque vous aurez une bonne main, et vous perdrez tout lorsque votre adversaire aura une meilleure main.", "Nix")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("Quiconque joue tout ce qu’il possède est ce genre d’imbécile.", "Nix")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("C'est dur !", "Lian")
	await novel_interface.show_text_only("Lian frissonne de manière incontrôlable.")
	await novel_interface.show_text_only("Nix prend une gorgée de son thé, puis continue.")
	novel_interface.show_character("nyx_normal","mock")
	await novel_interface.show_dialog("Écoutez, Texas Hold'em est un jeu au tour par tour.", "Nix")
	await novel_interface.show_dialog("Ce qui compte le plus, ce ne sont pas vos cartes, mais plutôt vos adversaires.", "Nix")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Choice.png")
	await novel_interface.show_dialog("Après que vous ayez effectué une action, vos adversaires n'auront que trois options : se coucher, suivre ou relancer.", "Nix")
	await novel_interface.show_dialog("Vous devez donc agir en vous basant sur un principe : empêcher vos adversaires de trouver des raisons de soutenir l'une ou l'autre de leurs trois options.", "Nix")
	await novel_interface.show_dialog("Le meilleur coup est celui qui donne à vos adversaires le sentiment que tout choix qu'ils font peut être bon mais peut aussi être mauvais en même temps.", "Nix")
	await novel_interface.show_dialog("Cela a du sens...", "Lian")
	await novel_interface.show_dialog("Lorsqu’ils se retrouvent dans une situation comme celle-là, ils paniquent, voire souffrent.", "Nix")
	await novel_interface.show_dialog("Et ce sera à leur tour de vouloir se libérer.", "Nix")
	await novel_interface.show_dialog("Ensuite, le jeu est à vous, le moment idéal pour les nettoyer.", "Nix")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("Nettoyez-les...", "Lian")
	await novel_interface.show_text_only("Je hoche la tête en réfléchissant aux paroles de Nix.")
	await novel_interface.show_dialog("(Où Nix a-t-il appris tout ça ?...)", "Lian")
	await novel_interface.show_dialog("(De toute façon, je ne joue jamais au poker avec elle !)", "Lian")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Gambling_Boat.png")
	await novel_interface.show_text_only("Je retourne à la table de poker. Avec l'aide de Nix, je double mes jetons en moins d'une heure.")
	await novel_interface.show_text_only("Dans la main où j'ai gagné le plus d'argent, au moment où j'ai mis tous mes jetons, j'ai entendu Nix et Aya commencer à parler de à quoi je ressemble quand je dors.")
	await novel_interface.show_text_only("Ils ont même échangé des photos ! J'étais tellement gêné que mon visage est devenu rouge.")
	await novel_interface.show_text_only("Mes adversaires ne savaient pas ce qui se passait, ils pensaient que je bluffais... Alors ils sont tombés dans le piège.")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("J'ai toujours l'impression qu'ils sont allés trop loin même s'ils m'ont aidé à gagner.", "Lian")
	await novel_interface.show_dialog("Je ne veux plus y penser !", "Lian")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Gambling_Boat3.png")
	await novel_interface.show_text_only("Maintenant, je suis le serveur du casino pour entrer dans la salle VIP.")
	await novel_interface.show_text_only("L’ambiance de cette pièce n’a rien à voir avec celle du hall. Décorations, tables, chaises... Tout est beaucoup plus chic.")
	await novel_interface.show_text_only("Trois hommes en costumes coûteux sont assis près d'une table, déjà un peu éméchés. Plusieurs filles sexy discutent sur le canapé.")
	await novel_interface.show_text_only("\"Liberty Star\" est un petit navire-casino réservé aux gros joueurs. Enveloppé d’une armure grise, il garde un profil très bas.")
	await novel_interface.show_text_only("Monter à bord de ce navire nécessite d'acheter au moins 20 millions de jetons, et il n'y a même pas quelques dizaines d'invités à bord.")
	await novel_interface.show_text_only("Quant au room VIP, il vous faudra gagner plus de 50 millions...")
	await novel_interface.show_text_only("Suivant les instructions de Mariru, j'ai échangé 100 millions en espèces contre un seul jeton en or gravé d'un exquis blason Lebona.")
	novel_interface.show_character("ren_full","worry")
	await novel_interface.show_dialog("Peut-être que les rumeurs étaient vraies...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Puces fabriquées à partir de substance H qui peuvent résister à de forts impacts, à des champs magnétiques et à des températures élevées ; ils peuvent être encaissés dans des centaines de casinos partout dans le monde.")
	await novel_interface.show_text_only("Il s’agit sans doute de l’obligation au porteur la plus valorisée.")
	await novel_interface.show_dialog("Nous avons détourné toutes leurs caméras de surveillance. C'est parti dès que vous êtes prêt ! ", "Annie")
	await novel_interface.show_text_only("Enfin une bonne nouvelle !")

	print("=== 星尘降临篇第4话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
