# stardustdescends_ep05.gd - 星尘降临篇第5话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep05_script()

func play_script():
	pass

func stardustdescends_ep05_script():
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Vault.png")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("นี่คือห้องนิรภัยบนเรือ \"ลิเบอร์ตี้สตาร์\"...", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ฉันมองไปรอบๆด้วยความประหลาดใจ เพดาน พื้น และผนังทั้งสองข้างล้วนหุ้มด้วยแผ่นโลหะสีสว่างเหมือนกระจกซึ่งทำจากวัสดุพิเศษบางชนิด")
	await novel_interface.show_text_only("ฉันเปรียบเทียบแผงโลหะกับเศษทองในมือ สีจะคล้ายกัน แต่ผนังจะออกเงาสีเทาอมเขียวจางๆ")
	await novel_interface.show_text_only("แขกวีไอพีบางรายเท่านั้นที่ได้รับอนุญาตให้ใช้ตู้เซฟในห้องเก็บสัมภาระ และฉันเพิ่งได้รับสิทธิ์นั้นเท่านั้น")
	await novel_interface.show_text_only("ทางเข้าออกทางเดียวคือลิฟต์ในบริเวณวีไอพีและประตูด้านล่างหนาเท่ากับผนัง")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("(ไม่มีสัญญาณตรงนี้...เป็นไปตามคาด)", "เหลียน")
	await novel_interface.show_text_only("ฉันทำการสื่อสารหายทันทีที่เข้าไปในลิฟต์ ตอนนี้ ฉันต้องทำทุกอย่างเหมือนที่เคยทำในระหว่างการฝึกซ้อม และจะไม่มีวันผิดพลาดแม้แต่ก้าวเดียว")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Vault.png")
	novel_interface.show_character("ren_full","solemn")
	await novel_interface.show_dialog("(ขั้นตอนที่หนึ่ง: ยืนยันว่าระบบ Surveillance ล่ม... ตกลง)", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ฉันสังเกตเห็นกล้องหลายตัวภายในห้องนิรภัยกะพริบพร้อมกัน จากนั้นทั้งหมดก็มืดลง")
	await novel_interface.show_dialog("คุณครับ ตู้เซฟของคุณคือหมายเลข 1212 ทุกครั้งที่เปิด ต้องใส่ทั้งกุญแจของคุณและของเรา...", "พนักงานเสิร์ฟ")
	await novel_interface.show_text_only("พนักงานเสิร์ฟหันมายื่นกุญแจให้ฉันอย่างสุภาพ แต่กลับพบว่าขวด \"น้ำหอม\" ชี้ตรงไปที่หน้าเขา--")
	novel_interface.show_character("ren_full","wry_smile")
	await novel_interface.show_dialog("ฉันขอโทษ!", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("หลังจากฉีดสเปรย์ไปที่ใบหน้าครั้งหนึ่ง ดวงตาของเขาก็หมองคล้ำทันที ดูเหมือนเขาอยากจะพูดอะไรบางอย่าง แต่หลังจากอ้าปากไปสองสามครั้งก็ไม่มีเสียงออกมา")
	await novel_interface.show_text_only("สเปรย์ระงับความรู้สึกนี้เป็นผลิตภัณฑ์ SRD ใหม่ อายะยังเพิ่มยาที่ช่วยขจัดการควบคุมการยับยั้งของสมองอีกด้วย")
	await novel_interface.show_text_only("ใครก็ตามที่ถูกสเปรย์ฉีดจะเข้าสู่สภาวะเหมือนถูกสะกดจิต และเปิดรับข้อเสนอแนะอย่างมาก")
	novel_interface.show_character("ren_full","smile")
	await novel_interface.show_dialog("มายืนตรงนี้..", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ฉันค่อยๆ นำบริกรที่มึนงงไปยังจุดที่หันหน้าไปทางประตูลิฟต์โดยตรง และยื่นชิปสีแดงเข้าไปในมือของเขา")
	novel_interface.show_character("ren_full","solemn")
	await novel_interface.show_dialog("เอิ่ม...", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("เมื่อนึกถึงบทที่ฉันได้รับคำสั่งให้ซ้อมซ้ำแล้วซ้ำอีก ฉันพูดกับเขาด้วยน้ำเสียงหนักแน่น--")
	novel_interface.show_character("ren_full","normal1")
	await novel_interface.show_dialog("คุณพาฉันมาที่ห้องนิรภัยเมื่อกี้นี้ ทุกอย่างเป็นเรื่องปกติ", "เหลียน")
	await novel_interface.show_dialog("หลังจากเก็บสิ่งของของฉันแล้ว ฉันให้ชิปแก่คุณเป็นทิป", "เหลียน")
	novel_interface.change_expression("solemn")
	await novel_interface.show_dialog("ทันทีที่คุณได้ยินเสียงดีดนิ้วหรือเห็นประตูลิฟต์เปิด คุณจะตื่นขึ้นมาและ \"จดจำ\" ทุกรายละเอียด", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("พนักงานเสิร์ฟไม่สามารถพูดอะไรได้ เขาแค่จ้องมองที่ประตูลิฟต์ ฉันเดินจากไปอย่างระมัดระวัง")
	novel_interface.show_character("ren_full","stare")
	await novel_interface.show_dialog("(แค่นี้พอเหรอ?...)", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("มาริรุกล่าวว่าสมองของมนุษย์เก่งในการกรอกรายละเอียดจากคำแนะนำและคำแนะนำง่ายๆ เพียงไม่กี่ข้อ...แต่มันยังรู้สึกง่ายเกินไปใช่ไหม!")
	novel_interface.show_character("ren_full","stare")
	await novel_interface.show_dialog("เขาจะจำอะไรได้บ้าง?", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ฉันยังคงพึมพำกับตัวเอง และเดินไปที่กลางห้องนิรภัย ถอดรองเท้าส้นสูงออกอย่างรวดเร็ว และวางไว้บนพื้นอย่างเรียบร้อย")
	await novel_interface.show_text_only("จากนั้นฉันก็ยัดหูฟังและวัตถุที่เป็นโลหะอื่นๆ ลงในกระเป๋าถือและวางไว้ข้างส้นเท้า")
	await novel_interface.show_text_only("ห้องนิรภัยนี้เป็นห้องป้องกันไฟฟ้าสถิตย์ยิ่งยวดขนาดใหญ่ ซึ่งสามารถปิดกั้นรังสีและสนามแม่เหล็กส่วนใหญ่ได้")
	await novel_interface.show_text_only("เลโบน่าไม่มีเทคโนโลยีแบบนี้ ตามข้อมูลของศาสตราจารย์ Shih ห้องป้องกันนี้ได้รับมอบหมายจากผู้ผลิตทางทหารใน Hovering Palace")
	await novel_interface.show_text_only("ฉันพบคอนเทนเนอร์เป้าหมาย ระหว่างรูกุญแจทั้งสองรูที่ประตูแต่ละบานมีลวดลายเมฆแกะสลักด้วยเลเซอร์จาง ๆ")
	novel_interface.show_character("ren_full","normal1")
	await novel_interface.show_dialog("ตู้คอนเทนเนอร์หมายเลข 0812...", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ฉันใส่คีย์หลักแบบเซรามิกสองอันเข้าไปในตัวล็อคทั้งสองพร้อมกันและเปิดใช้งานสวิตช์ที่ปลายทั้งสองตัว")
	await novel_interface.show_text_only("ฟาเบลลาเคยกล่าวไว้ว่ากุญแจสำหรับตู้เซฟส่วนตัวในธนาคารและสถาบันที่คล้ายกันนั้นมีความปลอดภัยต่ำมาก--")
	await novel_interface.show_text_only("เหตุผลส่วนหนึ่งก็คือสถาบันเหล่านั้นมีความมั่นใจอย่างยิ่งในการรักษาความปลอดภัยที่ปกป้องห้องนิรภัยเอง")
	await novel_interface.show_text_only("ที่สำคัญกว่านั้น กุญแจช่วยให้ลูกค้าเกิดภาพลวงตาว่ามีเพียงพวกเขาเท่านั้นที่สามารถเปิดตู้เซฟได้ ซึ่งทำให้การชำระค่าบริการรู้สึกง่ายขึ้นมาก")
	novel_interface.show_character("ren_full","stare")
	await novel_interface.show_dialog("(ดังนั้นห้องนิรภัยและระบบรักษาความปลอดภัยจึงให้ \"ความปลอดภัย\" ในขณะที่กุญแจให้ \"ความอุ่นใจ\"...?)", "เหลียน")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("(ทำไมมันฟังดูเหมือนมาริรุพูดจังเลยล่ะ? ฉันเกลียดมัน...)", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("คลิก ตู้เซฟเปิดแล้ว!")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("ภายในภาชนะมีอุกกาบาตสีดำยาวกว่า 1.5 เมตรวางอยู่--")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("EX ระดับสาร H?!", "เหลียน")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("ใช่แล้ว ระดับ EX!", "มาริรุ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("แต่ฉันจำได้ว่าคุณบอกว่าระดับ EX เชื่อมโยงกับศาสนา", "เหลียน")
	await novel_interface.show_dialog("เนื่องจากเป็นสิ่งพิเศษสำหรับสาวกทางศาสนาจึงสามารถรวบรวมสารระดับ EX H ได้ แต่ห้ามการวิจัย", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("สาร H บางชนิดกล่าวในตำนานทางศาสนาว่ามีพลังในการฆ่าเทพเจ้าได้")
	await novel_interface.show_text_only("เมื่อเปิดใช้งานแล้ว อาจก่อให้เกิดหายนะระดับโลกาวินาศได้ ดังนั้นการวิจัยทุกรูปแบบจึงถูกห้ามโดยเด็ดขาด")
	novel_interface.change_background("res://assets/images/bg/Shot/boySP_news.png")
	await novel_interface.show_text_only("และใช่...")
	await novel_interface.show_text_only("เหตุผลที่ผมจำเรื่องทั้งหมดได้ชัดเจนมาก...")
	await novel_interface.show_text_only("เป็นเพราะ Destiny Spear ที่เธอขโมยมานั้นเป็น Substance H เกรด EX เช่นกัน!")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("(เธอกำลังพูดถึงฉันอยู่ใช่ไหม?)", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ฉันเงยหน้าขึ้นและตรวจสอบตัวเองในกระจก")
	await novel_interface.show_text_only("มันเหมือนกับที่ฉันมองไปในความฝันทั้งหมดที่ฉันมีเมื่อเร็วๆ นี้")
	novel_interface.show_character("liliu_uniform2","speak")
	await novel_interface.show_dialog("สาร H ระดับ EX เชื่อมโยงกับมากกว่าศาสนา", "มาริรุ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("เสียงของมาริรุทำให้ฉันกลับมาสู่ความเป็นจริง")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("การทดสอบของเราแสดงให้เห็นว่าอุกกาบาตตกลงสู่โลกเมื่อกว่า 4,000 ปีก่อน มันถูกขุดขึ้นมาโดยนักโบราณคดีชาวอียิปต์ก่อนสงคราม", "มาริรุ")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_TheMeteorite.png")
	await novel_interface.show_dialog("เนื่องจากมุมปกติและหน้าแบน จึงสรุปได้ว่าอุกกาบาตไม่สามารถก่อตัวตามธรรมชาติได้", "มาริรุ")
	await novel_interface.show_dialog("ในตอนแรกผู้คนคิดว่ามันเป็นโลงศพชนิดหนึ่งจากอียิปต์โบราณ แต่อุกกาบาตนั้นทั้งตัวไม่มีแม้แต่รอยแตกแม้แต่น้อย", "มาริรุ")
	await novel_interface.show_dialog("หลายปีต่อมา เมื่อปัญหาเกี่ยวกับสาร H ทวีความรุนแรงขึ้น อุกกาบาตก็ถูกย้ายไปยังพิพิธภัณฑ์ Hovering Palace", "มาริรุ")
	await novel_interface.show_dialog("ศาสตราจารย์ Shih เป็นหนึ่งในนักวิจัยชั้นนำที่ทำการศึกษาเรื่องนี้ เมื่อ Hovering Palace ได้รับอุกกาบาตเป็นครั้งแรก พวกเขาคิดว่าจะถูกแจ็กพอตแล้ว", "มาริรุ")
	await novel_interface.show_dialog("แต่ในไม่ช้าพวกเขาก็ค้นพบว่าอุกกาบาตปฏิเสธการสำรวจและการบุกรุกทุกรูปแบบ", "มาริรุ")
	await novel_interface.show_dialog("ประการแรก สนามแม่เหล็กของมันเองจะผันผวนเป็นระยะ ๆ เกือบจะเหมือนกับการหายใจ และเมื่อถึงจุดสูงสุด สนามแม่เหล็กก็เกือบจะแรงเท่ากับสนามแม่เหล็กนีโอไดเมียม", "มาริรุ")
	await novel_interface.show_dialog("ทันทีที่ตรวจพบรังสี สนามแม่เหล็กจะพุ่งสูงขึ้นอย่างรวดเร็ว จนมีความเข้มสูงเกินกว่าจะวัดได้", "มาริรุ")
	await novel_interface.show_dialog("การทดลองไม่เพียงแต่ล้มเหลว แต่ยังทำให้สถานีวิจัยระเบิดเกือบทั้งหมด", "มาริรุ")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	novel_interface.show_character("anne_normal","happy")
	await novel_interface.show_dialog("...จะเป็นอย่างไรถ้าฉันลองตัดมันออกล่ะ?", "แอนนี่")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("แม้ว่าอุกกาบาตจะไม่ได้แข็งเป็นพิเศษ แต่ความพยายามใดๆ ที่จะทำลายโครงสร้างของมัน จะทำให้อุกกาบาตปล่อยความร้อนและการแผ่รังสีที่รุนแรงออกมา", "มาริรุ")
	await novel_interface.show_dialog("ตามการคำนวณของเรา ถ้ามีคนบังคับเปิดมันออก พลังงานที่ปล่อยออกมาก็จะเพียงพอที่จะกวาดล้างโลกไปครึ่งหนึ่ง", "มาริรุ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("ไม่น่าแปลกใจที่การวิจัยจะถูกห้าม...", "เหลียน")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("นอกจากนี้ยังไม่เสถียรอย่างยิ่งอีกด้วย ซึ่งเป็นระเบิดที่ไม่มีใครรู้ว่าจะดับลงเมื่อใด", "มาริรุ")
	await novel_interface.show_dialog("Hovering Palace พยายามทุกวิถีทางที่จะคิดเพื่อกำจัดอุกกาบาต ในท้ายที่สุด คริสตจักรก็ตกลงที่จะรับช่วงต่อ และ Samonton ก็อนุญาต", "มาริรุ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("พูดถึงคริสตจักร. Sonya ส่งอีเมลถึงฉันเมื่อบ่ายวันนี้ สิ่งที่แนบมาด้วยคือภาพของเธอในเวิร์คช็อปเรือนจำ")
	await novel_interface.show_text_only("หลังจากเหตุการณ์ครั้งสุดท้าย Sonya กลับมาที่โบสถ์ เธอบอกว่าเธอจำเป็นต้องตรวจสอบบางสิ่งบางอย่างและอัพเกรด \"เครื่องมือ\" บางอย่าง")
	await novel_interface.show_text_only("ห้องในรูปของเธอเต็มไปด้วยอุปกรณ์ราคาแพง ฉันเกือบเข้าใจผิดว่าเป็นโรงงาน SRD")
	await novel_interface.show_text_only("ถ้าซอนยาไม่สวมชุดแม่ชีของเธอ คงไม่มีอะไรในภาพนั้นที่จะทำให้ผู้คนเชื่อมโยงสถานที่นี้เข้ากับศาสนา")
	novel_interface.show_character("ren_battle","speechless")
	await novel_interface.show_dialog("(ดูเหมือนว่าคริสตจักรจะรับใครก็ได้จริงๆ ตราบใดที่ราคาเหมาะสม...)", "เหลียน")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("ดาวตกไม่สามารถขนส่งโดยเครื่องบินได้เนื่องจากมีแม่เหล็กแรงสูง วิธีเดียวที่ปลอดภัยคือทางเรือ", "มาริรุ")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("ซึ่งนำไปสู่ปัญหาอีกประการหนึ่ง คือ เมื่อเรือแล่นผ่านคลองสุเอซแล้ว อาจลงเอยด้วยการละเมิดอนุสัญญาระหว่างประเทศทั้งชุด...", "มาริรุ")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_normal","normal1",0.25)
	await novel_interface.show_dialog("และนั่นคือสิ่งที่เลโบน่าเข้ามา?", "แอนนี่")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("เป๊ะ! พระราชวังโฮเวอร์ริ่งยังจัดหาสาร H เพื่อสร้างห้องนิรภัยบนเรือเพื่อป้องกันรังสีและสนามแม่เหล็ก", "มาริรุ")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"panic")
	await novel_interface.show_dialog("และด้วยการที่ข้อมูลทั้งหมดนี้รั่วไหลมาให้เรา...", "แอนนี่")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("มาริรุพยักหน้าขณะที่เธอยืนยันทฤษฎีของแอนนี่")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("คุณเคยสัมผัสกับบางสิ่งที่คล้ายกับอุกกาบาตนี้มาก่อน", "มาริรุ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("โอ้?", "เหลียน")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_TheLastJudgement.png")
	await novel_interface.show_text_only("ขณะตอบเธอ ฉันรู้สึกเสียสมาธิกับรูปถ่ายในอีเมล เป็นภาพ The Last Judgement ซึ่งเป็นภาพปูนเปียก Sonya ที่ถ่ายในโบสถ์ซิสทีน")
	await novel_interface.show_text_only("รู้สึกโล่งใจที่เห็นว่า Sonya ยังสามารถเดินไปรอบๆ โบสถ์ได้อย่างอิสระ ฉันจึงเริ่มค้นหาข้อมูลเกี่ยวกับจิตรกรรมฝาผนัง")
	await novel_interface.show_dialog("(Michelangelo... เขามาจากยุคเดียวกับ Henriette)", "เหลียน")
	await novel_interface.show_dialog("รู้สึกเหมือนอัจฉริยะในยุคนั้นทุกคนหมกมุ่นอยู่กับร่างเปลือย...", "เหลียน")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("\"เสา Tesheim Lapis\" ของ Henriette", "มาริรุ")
	await novel_interface.show_dialog("อุณหภูมิพื้นผิวของเสาก็ผันผวนเช่นเดียวกับการหายใจ", "มาริรุ")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_normal","stare")
	await novel_interface.show_dialog("ดังนั้น...", "แอนนี่")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ทั้งมาริรุและแอนนี่หันมามองมาที่ฉัน จู่ๆ ห้องก็เงียบลง")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("เอิ่ม...", "มาริรุ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","speechless")
	await novel_interface.show_dialog("?", "เหลียน")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("หือ??", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("...")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Vault.png")
	await novel_interface.show_text_only("เพื่อหลีกเลี่ยงไม่ให้เหตุการณ์ \"ประตูสวรรค์\" เกิดขึ้นอีก มาริรุ จึงเปลี่ยนโปรโตคอล SID")
	await novel_interface.show_text_only("จำเป็นต้องติดตามข้อมูลทั้งหมดที่เกี่ยวข้องกับสารระดับ EX สาร H")
	await novel_interface.show_text_only("\"คุณไม่สามารถกอบกู้โลกทั้งโลกด้วยการอยู่ภายใน New Opulentia เรายังต้องการกุญแจสู่สภายูไนเต็ดด้วย\"")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("(ก็จริงแต่...)", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ชายในชุดต่อสู้พิเศษสีดำเหล่านั้นเข้ามาในใจฉัน เช่นเดียวกับความกลัวของฉัน")
	novel_interface.show_character("ren_full","uneasy")
	await novel_interface.show_dialog("(ฉันแค่หวังว่ากุญแจของฉันจะไม่ล็อคเข้าล็อค...)", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ฉันเปิดตู้เซฟหมายเลข 0812 อย่างไม่เต็มใจและมองดูดาวตกสีดำที่เก็บไว้ข้างใน")
	await novel_interface.show_text_only("จากคำบอกเล่าของอายะ ห้องที่ฉันยืนอยู่ควรจะสามารถต้านทานเวทมนตร์ที่แข็งแกร่งที่สุดได้")
	await novel_interface.show_text_only("ยิ่งไปกว่านั้น ยังมีหน่วยตอบสนองทางยุทธวิธีบนเรือคาสิโนลำนี้ ซึ่งพร้อมที่จะรับมือกับเหตุฉุกเฉินทุกประเภท")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("เลยต้องสัมผัสมันสักครั้ง?", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ประหม่าหรือกลัว? ฉันไม่แน่ใจ. แต่ฉันเกือบจะรู้สึกได้ว่าเลือดของฉันไหลผ่านเส้นเลือดของฉัน")
	await novel_interface.show_text_only("ฉันเอื้อมมือไปทางดาวตกอย่างช้าๆ แล้วหลับตาลง")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("รู้สึก...นุ่มนวล?")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Vault.png")
	await novel_interface.show_text_only("ฉันเปิดตาของฉันอีกครั้ง ฝ่ามือของฉันวางอยู่บนอุกกาบาตแล้ว มันแข็งและชื้นเล็กน้อย")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("(นั่นเป็นเพียงจินตนาการของฉันเหรอ? ฉันสาบานได้เลยว่าฉันสัมผัสบางสิ่งที่นุ่มนวล...)", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ฉันสัมผัสดาวตกอีกครั้ง มันยากและแบนจริงๆ")
	await novel_interface.show_text_only("ตามแผนเดิม ฉันควรจะสัมผัสดาวตกเพียงครั้งเดียว")
	await novel_interface.show_text_only("ด้วยความสับสน ฉันจึงปิดตู้เซฟแล้วล็อคกลับเข้าที่ จากนั้นฉันก็ยืนอยู่ที่นั่นอย่างเงียบๆ ต่อหน้ามัน โดยยังคงพยายามคิดว่าฉันรู้สึกอย่างไรในครั้งแรก")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("(นั่นคืออะไร...?)", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ทันใดนั้นก็มีเสียงแปลก ๆ ดังมาจากข้างหลังฉัน เหมือนปุ่มตกลงบนพื้น")
	await novel_interface.show_text_only("ในห้องเล็กๆ ที่ปิดสนิทนี้ เสียงของวัตถุที่กลิ้งไปทั่วพื้นฟังดูชัดเจนอย่างผิดธรรมชาติ")
	novel_interface.show_character("ren_full","normal1")
	await novel_interface.show_dialog("?", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ฉันหันกลับไป--มันเป็นสิ่งเล็กๆ สีเหลือง ฉันเดินไปหยิบมันขึ้นมา")
	await novel_interface.show_text_only("มันเป็นวัตถุทรงกลมเล็กๆ ที่มีปุ่มเล็กๆ แปดปุ่มบนพื้นผิว")
	novel_interface.show_character("ren_full","wry_smile")
	await novel_interface.show_dialog("... มันหลุดจากชุดฉันเหรอ?", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("แต่ดูเหมือนขนมคมเปโตที่ฉันเคยกินตอนเด็กๆ วินาทีนั้นฉันแทบจะอยากจะเลียมัน")
	await novel_interface.show_dialog("ฮะ?", "???")
	await novel_interface.show_text_only("นั่นเสียงสาวน้อย!")
	novel_interface.show_character("stardust_small","smile")
	await novel_interface.show_dialog("ฮะ? ฉันควรจะมองหาอะไร?", "Stardust")

	print("=== 星尘降临篇第5话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
