# stardustdescends_ep18.gd - 星尘降临篇第18话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep18_script()

func play_script():
	pass

func stardustdescends_ep18_script():
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Psychology.png")
	await novel_interface.show_text_only("Todo mundo já experimentou uma dor interior – algo tão real, tão pesado, tão agonizante, tão difícil de suportar.")
	await novel_interface.show_text_only("No entanto, poucas pessoas sabem que a maior parte do sofrimento psicológico é aprendida após o nascimento.")
	await novel_interface.show_text_only("Uma criança que consegue ficar feliz o dia todo com nada além de uma coxinha de frango não consegue entender a dor de ser excluída e isolada pelos colegas nas redes sociais.")
	await novel_interface.show_text_only("Seja porque você sofre porque não consegue se encaixar em um grupo, porque as pessoas ao seu redor não o aceitam, ou porque você não consegue se tornar a pessoa que imagina...")
	await novel_interface.show_text_only("Toda essa dor é construída sobre conceitos complexos, nada mais do que um subproduto de significados acumulados aprendidos após o fato.")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Camus.png")
	await novel_interface.show_text_only("Camus disse que o absurdo da humanidade reside na busca incessante por significado em um universo sem sentido.")
	await novel_interface.show_text_only("Sob as algemas do significado, ninguém pode obter a verdadeira liberdade.")
	await novel_interface.show_text_only("A civilização humana não pode existir sem significado; é a base dos sistemas sociais em todas as épocas.")
	await novel_interface.show_text_only("O significado do clã, o significado da nação, o significado do senhor, o significado da religião, até mesmo da identidade étnica, da ideologia e da cultura pop...")
	await novel_interface.show_text_only("Uma vez que um sistema de significado é instilado em você, todos os tipos de ideias se formam naturalmente e uma escada de valores é construída em sua mente.")
	await novel_interface.show_text_only("o que merece elogio e promoção, o que merece desprezo e condenação, o que conta como felicidade e honra, o que deveria trazer dor e vergonha...")
	await novel_interface.show_text_only("Algumas pessoas são levadas ao suicídio por mudanças dinásticas, outras pelo casamento de seu ídolo; não há distinção verdadeira ou falsa entre sua dor.")
	await novel_interface.show_text_only("Mas se sua mente for suficientemente perspicaz, talvez você possa ocasionalmente se libertar das algemas e sair sozinho para tomar um pouco de ar.")
	await novel_interface.show_text_only("Aí você volta para o grupo, fica fingindo que usa as correntes, elogiando o que todo mundo elogia e desprezando o que todo mundo despreza.")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Prisoner.png")
	await novel_interface.show_text_only("Porque se você for inteligente, já deve perceber isto: a humanidade não é apenas prisioneira do significado, mas torna-se voluntariamente sua carcereira.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("................")
	await novel_interface.show_text_only("...")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_ConventionCentre.png")
	await novel_interface.show_text_only("Centro Internacional de Convenções de Masada, antes da cerimônia de assinatura.")
	await novel_interface.show_text_only("No salão já estavam presentes repórteres de mais de uma centena de veículos de comunicação, com flashes e câmeras prontas para registrar esse momento histórico.")
	await novel_interface.show_text_only("Atrás do pódio, uma pesada cortina azul isolava completamente o barulhento salão dos bastidores.")
	await novel_interface.show_text_only("Fileiras de novos equipamentos de iluminação profissional nas armações do teto estavam todos em modo de espera de baixo brilho.")
	await novel_interface.show_text_only("Os painéis acústicos embutidos nas paredes e o revestimento à prova de som da cortina deixavam o lugar assustadoramente silencioso.")
	await novel_interface.show_text_only("Quando o oficial camuflado do deserto viu o homem de terno cinza se aproximando pela passagem atrás da cortina, ele imediatamente se endireitou e fez uma saudação.")
	await novel_interface.show_text_only("A insígnia na gola camuflada e a estrela dourada de seis pontas mostravam que ele era major das Forças de Defesa.")
	await novel_interface.show_text_only("E o homem que ele estava prestes a informar era o representante signatário de Masadan: o major-general Hamon do Comando Norte das Forças de Defesa.")
	await novel_interface.show_dialog("Relatório, senhor. Estou aqui para informá-lo sobre o ataque agora há pouco.", "Major")
	await novel_interface.show_text_only("O major-general havia ganhado algum peso, mas seu cabelo ainda estava penteado com perfeita precisão e seu olhar mantinha a agudeza característica de um soldado.")
	await novel_interface.show_text_only("Enquanto caminhava, ele afrouxou impacientemente a gravata e prendeu-a com o bloco de couro preto na mão.")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("Nunca consigo me acostumar a usar essa coisa...", "Hamon")
	await novel_interface.show_dialog("Vá em frente.", "Hamon")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("É o relatório da investigação sobre a explosão a sudoeste do centro de convenções há trinta minutos.", "Major")
	await novel_interface.show_dialog("Com base nos vestígios no local, a equipe de eliminação de bombas concluiu que se tratava de um IED feito principalmente com açúcar.", "Major")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("...Uma bomba caseira feita de açúcar?", "Hamon")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Sim, mas a intensidade da explosão não foi alta e não causou vítimas. O explosivo parece ter incluído aditivos que realçaram a fumaça.", "Major")
	await novel_interface.show_dialog("Apagamos a fumaça imediatamente. O regimento de guarda já isolou a área circundante e nenhum meio de comunicação relatou o incidente até agora.", "Major")
	await novel_interface.show_dialog("A vigilância nas ruas próximas ainda não encontrou nenhum suspeito. Estamos expandindo a área de pesquisa agora. Relatório concluído.", "Major")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("...É isso?", "Hamon")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Hamon olhou nos olhos do major e não disse nada por um longo momento. O major não ousou falar e só conseguiu ficar rigidamente no lugar.")
	await novel_interface.show_text_only("Hamon bufou e, insatisfeito, bateu o tablet que tinha na mão no peito do major.")
	novel_interface.show_character("hamon","speak")
	await novel_interface.show_dialog("Veja você mesmo!", "Hamon")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Cambaleando para trás com o golpe, o major rapidamente estabilizou o tablet. Na tela estava o icônico logotipo do candelabro de sete braços de Monola.")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("Eles enviaram isso há alguns minutos.", "Hamon")
	await novel_interface.show_dialog("Monola avistou três indivíduos suspeitos que se misturaram ao estacionamento subterrâneo.", "Hamon")
	await novel_interface.show_dialog("Dois deles entraram no poço do elevador com a intenção de sabotar o sistema de supressão de incêndio do prédio.", "Hamon")
	await novel_interface.show_dialog("Felizmente, os seus agentes intervieram a tempo. Eles capturaram um, mas os outros dois escaparam; um deles foi atingido de raspão por uma bala enquanto fugia.", "Hamon")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("...O poço do elevador!?\nS-Alguém se infiltrou no local?", "Major")
	await novel_interface.show_text_only("O major folheou rapidamente o relatório e sua cabeça imediatamente começou a zumbir—")
	await novel_interface.show_text_only("Aquela explosão foi apenas uma diversão...?")
	await novel_interface.show_text_only("Como o estacionamento de superfície estava ocupado por forças de segurança e veículos militares, todas as vans de equipamentos de mídia ficaram estacionadas no subsolo do centro de convenções.")
	await novel_interface.show_text_only("Então o estacionamento subterrâneo era realmente a área mais fácil de se infiltrar.")
	await novel_interface.show_text_only("Embora a Inteligência Militar tivesse instalado sistemas de segurança rígidos em todos os cantos do edifício, a parte inferior da cabine do elevador era um ponto cego de vigilância.")
	await novel_interface.show_text_only("Percebendo que a linha defensiva que ele havia organizado havia sido violada com tanta facilidade, o suor imediatamente escorreu pela testa do major.")
	novel_interface.show_character("hamon","speak")
	await novel_interface.show_dialog("A Inteligência Militar não me garantiu que a segurança do local era hermética?", "Hamon")
	novel_interface.change_expression("shout")
	await novel_interface.show_dialog("Eu deliberadamente afastei o pessoal de Monola e os mandei para o perímetro externo, e é assim que você me faz parecer?!", "Hamon")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lembrando que o salão além da cortina estava lotado de repórteres, Hamon baixou deliberadamente a voz ao repreendê-lo.")
	await novel_interface.show_dialog("Isso...\nE-foi meu fracasso!", "Major")
	await novel_interface.show_dialog("Mas os agentes de Monola não estavam todos estacionados do lado de fora do centro de convenções?\nComo eles poderiam estar dentro do prédio...?", "Major")
	await novel_interface.show_text_only("Hamon balançou levemente a cabeça e deu um tapinha no ombro do major.")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("Entre os repórteres que estão por aí, quem sabe quantos são deles...", "Hamon")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ele entendeu perfeitamente que o Departamento de Inteligência Militar que ele cultivou dentro do sistema militar nos últimos anos não poderia se comparar a um monstro como Monola.")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Speech.png")
	await novel_interface.show_text_only("“Eles são o sistema nervoso deste país, capazes de reagir a qualquer perigo com a maior velocidade”.")
	await novel_interface.show_text_only("\"Se alguém atirar uma flecha em você e você precisar que seu cérebro pense antes de se esquivar, você só morrerá com uma flecha no corpo.\"")
	await novel_interface.show_text_only("O tio de Hamon, o primeiro-ministro Schneiderman, certa vez explicou ao parlamento desta forma por que Monola detinha a autoridade operacional suprema sem restrições.")
	await novel_interface.show_text_only("Mas Hamon não podia tolerar que toda a informação fosse mantida por uma organização que ele não podia controlar.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Informação é poder. Essa foi a experiência de combate que acumulou ao longo de décadas, seja em guerras internas ou externas.")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_ConventionCentre.png")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("E além disso--", "Hamon")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ele lançou ao oficial à sua frente, um homem que ele havia promovido pessoalmente, um olhar significativo.")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("A mulher que capturaram é tenente do Batalhão Caracal.", "Hamon")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("--Um dos nossos?!", "Major")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("E um cadete da Torre, ainda por cima...", "Hamon")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Hamon disse palavra por palavra.")
	await novel_interface.show_text_only("Percebendo as repercussões políticas que isso poderia causar, o major não pôde deixar de prender a respiração...")
	await novel_interface.show_text_only("Sempre houve muitas vozes dentro das Forças de Defesa que se opunham a este acordo, especialmente entre os jovens incendiários ansiosos por se distinguirem.")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("Mais estranho ainda, as impressões digitais recolhidas no local mostram que entre os que actuaram com ela estava um estrangeiro que se tinha registado na imigração há poucos dias.", "Hamon")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Um espião estrangeiro?", "Major")
	await novel_interface.show_text_only("As sobrancelhas de Hamon se uniram enquanto ele ponderava por um momento.")
	novel_interface.show_character("hamon","speak")
	await novel_interface.show_dialog("Isso é possível. De qualquer forma, pedi a Monola que compartilhasse todas as informações primeiro, mas você não pode esperar que eles sejam muito cooperativos...", "Hamon")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("O regimento da guarda prendeu aquele tenente. Ela está agora na sala segura no andar de cima e também está sob sua responsabilidade.", "Hamon")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Sim, senhor!", "Major")
	await novel_interface.show_text_only("Hamon se virou, ajustou o colarinho e colocou a gravata novamente.")
	novel_interface.show_character("hamon","speak")
	await novel_interface.show_dialog("A cerimônia está prestes a começar...\nNão crie mais problemas para mim!", "Hamon")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Sim! Você tem minha palavra, senhor!", "Major")
	await novel_interface.show_text_only("Hamon fez uma pausa e disse sombriamente, de costas para o major:")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("Não estou usando uniforme hoje. Não me trate pela minha posição.", "Hamon")
	await novel_interface.show_dialog("O povo não quer mais soldados liderando o governo... entendeu?", "Hamon")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ah... entendi!", "Major")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("...\nMasada International Convention Center, estacionamento externo.")
	await novel_interface.show_text_only("Dentro de um veículo blindado de transporte de pessoal.")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_MasadAPCRS.png")
	await novel_interface.show_dialog("Seu idiota--!!!\nVocê caiu direto na armadilha deles??!", "Mariru")
	await novel_interface.show_text_only("Se esses fones de ouvido não pudessem ajustar o volume dinamicamente, meus tímpanos provavelmente teriam morrido antes de mim.")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("Uau...", "Lian")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("I-Isso...", "Lian")
	await novel_interface.show_dialog("B-Porque não consegui falar com ninguém...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Eu mexi nos controles por muito tempo antes de finalmente desativar o modo de blindagem deste veículo e falar com Mariru.")
	await novel_interface.show_text_only("Um baque forte veio do fone de ouvido e eu a imaginei destruindo a mesa com um soco.")
	await novel_interface.show_dialog("Então... você saiu sozinho, não foi?", "Mariru")
	await novel_interface.show_dialog("Já faz tanto tempo desde que eu fiz você passar por exercícios que você está coçando sem eles...?", "Mariru")
	await novel_interface.show_text_only("Mariru parou de gritar e mudou para um tom baixo e ameaçador.")
	await novel_interface.show_text_only("Como um vulcão prestes a entrar em erupção, foi ainda mais assustador do que antes!!")
	await novel_interface.show_dialog("Ei, ei...\nNão fique tão bravo~", "Aya")
	await novel_interface.show_text_only("Aya tentou acalmar as coisas para mim com seu habitual tom preguiçoso.")
	await novel_interface.show_dialog("Mesmo que Lian tenha obtido todas as notas D em todos os testes físicos, o fato de ela ter se voluntariado para esse tipo de trabalho de infiltração de campo ainda diz algo sobre sua coragem~", "Aya")
	await novel_interface.show_text_only("Ela está tentando acalmar as coisas ou atiçar as chamas!?")
	await novel_interface.show_text_only("Eu não tive escolha. Eu só pude cerrar os dentes e me explicar.")
	novel_interface.show_character("ren_medical","sob")
	await novel_interface.show_dialog("B-Por causa das estrelas--", "Lian")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_SlumArea.png")
	await novel_interface.show_dialog("Lembro que a noite passada estava clara e havia poucas luzes na favela, então as estrelas eram fáceis de ver.", "Lian")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_SlumArea1.png")
	await novel_interface.show_dialog("Mas quando essas pessoas passaram pela favela mais tarde, nem uma única estrela era visível.", "Lian")
	await novel_interface.show_dialog("E ainda por cima, todos os dispositivos de comunicação perderam sinal...", "Lian")
	await novel_interface.show_dialog("Eu senti que não era uma jam comum--", "Lian")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("...O que você quer dizer?", "Mariru")
	await novel_interface.show_dialog("Parecia exatamente a situação em torno da igreja na noite em que capturamos Elgana...", "Lian")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Church.png")
	await novel_interface.show_text_only("Naquela noite, quando minha ligação com Mariru foi interrompida de repente, a atmosfera ao meu redor também ficou estranha...")
	await novel_interface.show_text_only("Os edifícios à distância ficaram borrados e distorcidos, e o céu noturno claro escureceu instantaneamente.")
	await novel_interface.show_dialog("Lembro-me claramente: todas as estrelas do céu desapareceram de uma vez.", "Lian")
	await novel_interface.show_dialog("Então aqueles soldados com uniformes pretos de operações especiais vieram logo depois disso...", "Lian")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_MasadAPCRS.png")
	await novel_interface.show_text_only("Mariru ficou em silêncio por um longo tempo. Como uma criança que quebrou um vaso, mal ousei respirar enquanto esperava pela resposta dos adultos.")
	await novel_interface.show_dialog("...Então você tolamente concordou com eles?", "Mariru")
	await novel_interface.show_text_only("Ao ouvir a mistura de reprovação e resignação na voz de Mariru, meu corpo tenso relaxou um pouco.")
	await novel_interface.show_dialog("São apenas cadetes que ainda nem se formaram na escola militar. Eles não sabem que esse é o tipo de coisa que os profissionais deveriam cuidar?", "Mariru")
	novel_interface.show_character("ren_medical","upset")
	await novel_interface.show_dialog("Na verdade, depois que saímos da favela, Emily denunciou o fato aos militares, à polícia e à inteligência, e até ligou para a linha direta antiterrorista...", "Lian")
	await novel_interface.show_dialog("Mas todos deram respostas grandiosas e estereotipadas, dizendo que iriam verificar a favela o mais rápido possível e agradeceram pela dica e assim por diante...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Emily disse que a reação deles não foi surpreendente, porque tiroteios entre gangues acontecem o tempo todo na favela e é comum ver pessoas armadas à noite.")
	await novel_interface.show_text_only("E aos olhos dos cidadãos comuns de Masadan, todos nas ruas à noite parecem terroristas...")
	novel_interface.show_character("ren_medical","upset")
	await novel_interface.show_dialog("Emily também julgou que com o sistema de defesa da cidade de Massada, essas pessoas nunca conseguiriam sair da favela.", "Lian")
	novel_interface.change_expression("perspire1")
	await novel_interface.show_dialog("Se o veículo realmente carregava uma bomba e eles escolheram detoná-la durante a cerimônia de assinatura...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("As crianças do orfanato...")
	await novel_interface.show_dialog("Como todas as agências que contataram reagiram tão lentamente, eles decidiram agitar algo e forçar o adiamento da cerimônia de assinatura?", "Mariru")
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("Hum...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Então você não teve tempo de sobra para me ligar...?", "Mariru")
	await novel_interface.show_text_only("O tom de Mariru de repente tornou-se cruel, e com cada batida deliberada de suas palavras, o som de nós dos dedos estalando veio através do fone de ouvido.")
	novel_interface.show_character("ren_medical","wail")
	await novel_interface.show_dialog("Hein?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Aaaaah, deixei escapar!!!")
	novel_interface.show_character("ren_medical","sob")
	await novel_interface.show_dialog("S-Desculpe!!!!\nEu estava errado!", "Lian")
	await novel_interface.show_dialog("Eu estava errado...", "Lian")
	await novel_interface.show_dialog("M-Mas Emily, ela...", "Lian")
	await novel_interface.show_dialog("Fui levado embora~~~!!!!", "Lian")
	await novel_interface.show_dialog("Soluço, soluço, soluço, soluço, soluço...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tensão, ansiedade, arrependimento, mágoa... todas essas emoções surgiram ao mesmo tempo, e as lágrimas não paravam de escorrer dos meus olhos.")
	await novel_interface.show_dialog("Que idiota...", "Mariru")
	await novel_interface.show_text_only("Mariru suspirou e mudou para uma voz firme e firme.")
	await novel_interface.show_dialog("Emily está com a Força de Defesa. Ela também é uma excelente aluna da Torre e, além disso, não causou nenhum dano substancial.", "Mariru")
	await novel_interface.show_dialog("Cada agência tem a gravação de sua chamada de emergência na noite passada, provando seus motivos, e seu avô não vai ficar sentado sem fazer nada, nem que seja para salvar a reputação da família.", "Mariru")
	await novel_interface.show_dialog("O mais importante agora é que você não seja pego, ou a natureza do que eles fizeram se tornará diferente.", "Mariru")
	novel_interface.show_character("ren_medical","sob")
	await novel_interface.show_dialog("Hum...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Quando Mariru fala naquele tom frio, ela sempre vai direto ao ponto e não deixa espaço para discussão.")
	await novel_interface.show_dialog("Mais alguma coisa?", "Mariru")
	novel_interface.show_character("ren_medical","shy")
	await novel_interface.show_dialog("Você não pode ser um pouco mais gentil quando está confortando alguém...?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Não. Você entendeu o que acabei de dizer?", "Mariru")
	await novel_interface.show_text_only("Balancei a cabeça, querendo enxugar as lágrimas do meu rosto rapidamente, mas meu nariz continuava fungando inutilmente.")
	await novel_interface.show_dialog("A tempestade de areia chegará em breve. Encontrarei uma chance de tirar você de lá, então fique no veículo e não corra por aí.", "Mariru")
	novel_interface.show_character("ren_medical","upset")
	await novel_interface.show_dialog("Este veículo foi atribuído a eles, certo? Não será rastreado...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Se pudesse estar ligado a esses dois, eles não o teriam usado para sequestrar suprimentos.", "Mariru")
	await novel_interface.show_dialog("Mandarei alguém investigar o ataque, mas mesmo que alguém realmente planeje encenar um ataque durante a cerimônia de assinatura, a área ao redor do centro de convenções é segura.", "Mariru")
	await novel_interface.show_dialog("Preciso mudar para outros canais e fazer arranjos agora. Vou manter esta linha aberta, então se você falar, eu ouvirei você.", "Mariru")
	novel_interface.show_character("ren_medical","upset")
	await novel_interface.show_dialog("Ok...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Depois que ela silenciou a voz, respirei fundo várias vezes e tentei me acalmar o mais rápido possível.")
	novel_interface.show_character("ren_medical","upset")
	await novel_interface.show_dialog("(Uma tempestade de areia, hein...)\n(Só os vi em jogos e filmes...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Descansei uma mão no console e alternei entre diferentes feeds de vídeo.")
	await novel_interface.show_text_only("A julgar pelas câmeras externas do veículo, a área ao redor do centro de convenções ainda estava banhada pela fraca luz rosa única do início da manhã.")
	await novel_interface.show_text_only("No entanto, quando mudei para o noticiário matinal local, a imagem ao vivo da costa leste do Mar Morto já não passava de areia amarela, com visibilidade inferior a um metro.")
	await novel_interface.show_text_only("Em pouco tempo, a costa oeste também ficaria assim...")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("Nova cidade de Toyosu, sede SID.")
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("Depois que Mariru cortou o canal de voz, apenas a imagem da comunicação ao vivo de Akiko permaneceu na tela grande.")
	await novel_interface.show_dialog("Você realmente parou no meio de um interrogatório...", "Akiko")
	await novel_interface.show_text_only("Akiko parecia um tanto incrédula.")
	novel_interface.show_character("liliu_uniform1","jest")
	await novel_interface.show_dialog("Ela já não confessou?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ela confessou?", "Akiko")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("Lian foi quem propôs ir com os outros dois. Aquela idiota imaginou que se algo perigoso acontecesse, ela poderia usar sua constituição para ajudá-los a escapar.", "Mariru")
	await novel_interface.show_dialog("Mas ela sabia que eu nunca aprovaria, então deliberadamente não denunciou.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("Essa não foi exatamente a confissão dela, foi...? Ei--", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru cortou a cabeça de Aya com o lado da mão, depois pegou casualmente a pequena garrafa de bebida energética em sua mesa e inclinou metade dela para trás de uma só vez.")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("Não há como aquele idiota descrever sua própria psicologia com tanta precisão.", "Mariru")
	novel_interface.change_expression("sigh")
	await novel_interface.show_dialog("Quantas horas de sono você dormiu antes de acordar novamente?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("Essa questão heterogênea que Lambert penhorou para você da última vez tem um efeito que comprime a duração do sono. Tenho guardado no escritório.", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Aquela coisa não foi reprovada na avaliação de segurança?\nTenha cuidado ou você perderá a cabeça--", "Akiko")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("Isso não faria muita diferença para ela de qualquer maneira...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru esvaziou o resto da garrafa de um só gole.")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("Se a descrição de Lian estava correta, então a organização por trás do Conselho Unido também se envolveu?", "Aya")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("Difícil dizer...", "Mariru")
	await novel_interface.show_dialog("Essa arma que utiliza matéria heterogénea para perturbar ondas electromagnéticas de todas as frequências sobre uma determinada área apareceu pela primeira vez no campo de batalha da Ásia Ocidental.", "Mariru")
	await novel_interface.show_dialog("Massada nunca reconheceu publicamente a existência desse tipo de arma, mas há demasiadas armas que eles se recusam a reconhecer.", "Mariru")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("De acordo com Lambert o princípio de funcionamento dessa arma é completamente diferente dos dispositivos eletrônicos comuns de interferência.", "Mariru")
	await novel_interface.show_dialog("Dentro do seu alcance efetivo, quanto mais longe uma fonte eletromagnética estiver, mais severamente ela será distorcida, podendo obstruir completamente as imagens de satélite.", "Mariru")
	await novel_interface.show_dialog("As estrelas no céu também não desaparecem. Eles são esticados em longas linhas finas e, como seu brilho está espalhado, tornam-se impossíveis de observar.", "Mariru")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Durante o Fórum Internacional da Paz da última vez, aquela equipe de ataque vestida de preto que tentou apreender a réplica do Portão do Céu também tinha esse tipo de equipamento.", "Mariru")
	await novel_interface.show_dialog("Sempre pensei que fosse uma arma desenvolvida pelos militares de Masada e partilhada com o Conselho Unido através de algum acordo.", "Mariru")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("Mas há outra possibilidade -", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("Hein?", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru colocou a garrafa vazia na cabeça de Aya e, como uma treinadora de animais, gesticulou para que ela a mantivesse equilibrada.")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("A arma veio do outro lado do campo de batalha da Ásia Ocidental.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Você quer dizer...?", "Akiko")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("E se a resistência o desenvolvesse e o entregasse ao Conselho Unido como uma espécie de moeda de troca?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("A sala de comando ficou em silêncio. Pela primeira vez, a geralmente barulhenta Aya equilibrou obedientemente a garrafa vazia na cabeça sem dizer uma palavra.")
	await novel_interface.show_dialog("Esse palpite é um pouco demais...", "Akiko")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("Você não acha estranho?", "Mariru")
	await novel_interface.show_dialog("O Conselho Unido pode facilmente subjugar os senhores da guerra das várias facções da América do Sul, mas não fez absolutamente nada em relação à resistência, à organização terrorista que ele próprio designou.", "Mariru")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("Se este fosse o desígnio daquele homem...", "Mariru")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Mouchard.png")
	await novel_interface.show_text_only("No console, Mariru abriu o dossiê de Walid Mushar.")
	await novel_interface.show_dialog("A suposição externa mais comum sobre como a resistência continuou a sobreviver apesar de uma enorme desvantagem de equipamento é que Masada está deliberadamente mantendo o inimigo por perto para se justificar.", "Mariru")
	await novel_interface.show_dialog("Muitas pessoas até acreditam que se as Forças de Defesa não se importassem com o clamor público sobre as baixas civis, poderiam acabar completamente com a resistência dentro de uma semana.", "Mariru")
	await novel_interface.show_dialog("SID sempre teve lamentavelmente pouca informação sobre este líder da resistência, e a maior parte é apenas informação pública de quando ele era um estudioso antes de sua esposa e filha serem mortas.", "Mariru")
	await novel_interface.show_dialog("Colegas e professores que trabalharam com ele na universidade disseram que ele era excepcionalmente inteligente e amava profundamente sua família.", "Mariru")
	await novel_interface.show_dialog("É difícil imaginar um gênio com um ódio tão profundo por Masada se tornando um fantoche das Forças de Defesa.", "Mariru")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("Mas veja por outro ângulo...", "Mariru")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Kidnap.png")
	await novel_interface.show_dialog("O incidente do sequestro em New Moridas há dois anos...", "Mariru")
	await novel_interface.show_dialog("Durante o segundo Fórum Internacional para a Paz, a resistência planeou raptar a filha de um membro do conselho.", "Mariru")
	await novel_interface.show_dialog("Como os sequestradores utilizaram helicópteros armados não tripulados que vazaram de Massada para a cidade, o conselho foi pressionado a cancelar a emissão de títulos de guerra.", "Mariru")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("Depois que o financiamento da Segunda Cidade Acadêmica foi cortado, a redução de seu exército em Massada tornou-se apenas uma questão de tempo.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Financeiramente falando, sim...", "Akiko")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("Foi também a partir desse momento que começaram a surgir notícias de divisões faccionais dentro da resistência, fazendo com que a organização parecesse que poderia desmoronar a qualquer momento.", "Mariru")
	await novel_interface.show_dialog("Nos últimos dois anos, as Forças de Defesa de Masada continuaram a acumular vitórias e a eliminar um líder menor após o outro, mas quanto mais lutam, mais estas facções ramificadas parecem multiplicar-se.", "Mariru")
	await novel_interface.show_dialog("O facto de estarem a disfarçar até mesmo postos militares como instalações de ajuda civil mostra que cada vez mais já não podem suportar esta guerra...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Akiko observou Mariru juntar uma série de pistas em apenas alguns minutos a partir de uma única hipótese ousada e chegar a uma conclusão surpreendente.")
	await novel_interface.show_text_only("Ela não pôde deixar de se lembrar de como Mariru parecia radiante na escola quando discutiu com um professor sem palavras enquanto a defendia, e um rubor se espalhou por seu rosto.")
	await novel_interface.show_text_only("Enquanto isso, a idiota que tremia dentro do veículo blindado parecia não precisar mais de resgate.")
	await novel_interface.show_text_only("Olhando distraidamente para a foto na tela, Mariru murmurou para si mesma.")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("Ele não se importa em ganhar ou perder no momento, e não se importa com a vida de seu próprio povo...", "Mariru")
	await novel_interface.show_dialog("Vingança realizada através do cálculo exato e da razão pura.", "Mariru")
	novel_interface.change_expression("sigh")
	await novel_interface.show_dialog("Percebendo que está sendo encurralado por um oponente como esse, o primeiro-ministro Schneiderman não vai apenas sentar e esperar pela morte...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("--Então é por isso que ele projetou o “sistema de retaliação automática”!?", "Akiko")
	await novel_interface.show_text_only("Akiko de repente entendeu e Mariru assentiu levemente.")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("Mesmo que você ganhe todas as trocas, você nunca poderá dar o xeque-mate.", "Mariru")
	await novel_interface.show_dialog("Agora, no momento em que a resistência mostra qualquer intenção de atacar a Fortaleza de Massada, ela se torna um inimigo do mundo inteiro...", "Mariru")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("E quando isso acontecer, o Conselho Unido não se importará com quaisquer promessas que tenha feito~", "Mariru")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("Enquanto Massada proteger a sua capital e preservar a elite deste país, terá espaço suficiente para levar a cabo reformas e transições.", "Mariru")
	await novel_interface.show_dialog("Diante dessa reversão de Schneiderman, a resposta que Mushar escolheu foi...", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("Hum, hum--", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Aya ainda tinha a garrafa equilibrada na cabeça enquanto obedientemente levantava a mão para falar.")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("Não deveríamos discutir primeiro o plano de resgate de Lian?", "Aya")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","jest")
	await novel_interface.show_dialog("Não há necessidade ~", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Para surpresa de Aya, Akiko deu quase a mesma resposta quase ao mesmo tempo.")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("... Hein?", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Qualquer resgate traz riscos, especialmente sob o nariz de Monola.", "Akiko")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("Contar com uma tempestade de areia para salvá-la não é realista. Eles definitivamente têm contingências para um clima como esse quando a previsão é tão longa.", "Mariru")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("Então deixamos Lian ser pega obedientemente e depois a compramos de volta~", "Mariru")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("SID tem muita inteligência e autoridade que Monola desejaria em troca.", "Mariru")
	await novel_interface.show_dialog("Mesmo que eles entendam algo sobre as habilidades de Lian, não importa. Masada está desesperada para vender seus produtos agora e está cheia de pontos fracos.", "Mariru")
	await novel_interface.show_dialog("Diante da pressão direta de SID e Lambert, eles não farão uma escolha irracional.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("Eu vejo...", "Aya")
	await novel_interface.show_dialog("Aquela garota super forte chamada Vera foi salvar alguém. E ela?", "Aya")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("Vera provavelmente foi procurar a sala segura.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("A criação de salas seguras em grandes locais de reunião é o protocolo de segurança padrão das Forças de Defesa, a experiência de resposta que Masada pagou através de repetidos ataques terroristas.")
	await novel_interface.show_text_only("Numa emergência, quando é impossível confirmar se uma saída é segura, uma sala segura pode proteger temporariamente VIPs ou deter detidos importantes.")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("Passe essa informação para o pai de Vera.", "Mariru")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("Ele é alto o suficiente no Estado-Maior para não apenas ver sua própria filha cair em uma armadilha ~", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("Você é realmente mau...", "Aya")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("Então agora o principal é...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru pressionou uma das mãos contra a parte inferior do abdômen e exibiu o noticiário ao vivo da cerimônia de assinatura na tela grande.")
	await novel_interface.show_text_only("Na tela, o ligeiramente rechonchudo Hamon e o de barba branca Mushar estavam presos em um prolongado aperto de mão, o sorriso do primeiro quase congelado em seu rosto.")
	novel_interface.show_character("liliu_uniform1","angry")
	await novel_interface.show_dialog("Desta vez, Mushar entregou-se até a si mesmo. Isso significa que ele deve ter planejado um ataque capaz de acabar com tudo de uma só vez...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Mariru... algo parece errado?", "Akiko")
	await novel_interface.show_text_only("O estômago de Mariru soltou um longo ronco e então ela saiu correndo da sala de comando sem dizer nada.")
	await novel_interface.show_dialog("........................", "Akiko")
	novel_interface.show_character("ai","blush_dizzy")
	await novel_interface.show_dialog("Ah, querido...", "Aya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Aya gentilmente tirou o frasco da cabeça, colocou-o em um saco lacrado marcado com um símbolo de risco biológico e selou-o cuidadosamente.")
	await novel_interface.show_dialog("Aquela não era uma bebida energética comum, era...?", "Akiko")
	novel_interface.show_character("ai","blush_think")
	await novel_interface.show_dialog("Tinha... uma coisinha adicionada.", "Aya")
	await novel_interface.show_dialog("Eu estava planejando testar em mim mesmo e beber em lotes durante 24 horas...\n...", "Aya")
	novel_interface.change_expression("blush_stare")
	await novel_interface.show_dialog("Quem diria que ela engoliria em dois goles ~", "Aya")

	print("=== 星尘降临篇第18话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
