# stardustdescends_ep08.gd - 星尘降临篇第8话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep08_script()

func play_script():
	pass

func stardustdescends_ep08_script():
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Masada0.png")
	await novel_interface.show_text_only("제3학원도시──마사다부르크.")
	await novel_interface.show_text_only("사막에 세워진 군사 요새 도시. 특산품은 사해 진흙, 모래폭풍, 그리고 테러 공격이다.")
	await novel_interface.show_text_only("대다수 사람들의 기억 속에서 마사다부르크 관련 뉴스는 군사 충돌 아니면 인도주의적 참사뿐이다.")
	await novel_interface.show_text_only("피와 모래, 원유와 흰 연기가 그려내는 죽음의 곡선이 오래전부터 이 고대의 땅 위를 뒤덮고 있다...")
	await novel_interface.show_text_only("그곳 사람들의 삶은 어떤 모습일까?
나는 전혀 상상할 수 없었다...")
	await novel_interface.show_text_only("그런데도 왠지 모르게 익숙한 느낌이 든다. 마치 내가 직접 겪어본 것처럼...")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("하아──", "렌")
	novel_interface.change_music("res://assets/audio/music/unkown/UI_Main_Funk.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/Vessel.png")
	await novel_interface.show_text_only("나는 갑판 난간에 등을 기대고 있었고, 스타더스트는 코알라처럼 꼭 달라붙은 채 눈가에 눈물을 머금고 있었다.")
	novel_interface.show_character("ren_full","wry_smile")
	await novel_interface.show_dialog("알았어, 알았어. 아까 건 그냥 장난이었어──", "렌")
	novel_interface.change_expression("wail")
	await novel_interface.show_dialog("야, 조금만 힘 빼. 손톱이 살에 박히겠어...", "렌")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("stardust_small","tear",0.25)
	await novel_interface.show_dialog("훌쩍...", "스타더스트")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("내 옷에 코 닦지 마!!!", "렌")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("나는 난처하게 한숨을 쉬며 달래듯 그녀의 머리를 쓰다듬었다.")
	await novel_interface.show_text_only("아까 아이는 스타더스트가 가리킨 방향이 마사다부르크일 거라고 추정했지만, 막상 물어보니 그녀는 그 지명에 전혀 기억이 없었다.")
	await novel_interface.show_text_only("아니, 애초에 '학원도시'라는 개념 자체를 모르고 있었다...")
	await novel_interface.show_text_only("마리루는 정보를 먼저 정리해 보겠다며, 내가 갑판에서 대기하다가 잠시 후 다시 연락받으라고 했다.")
	await novel_interface.show_text_only("난 여전히 이 녀석이 나에게만 보이는 환영이라는 사실을 받아들일 수 없어서, 틈을 타 몇 가지 시험을 더 해 보기로 했다──")
	await novel_interface.show_text_only("우선 휴대전화를 바닥에 내려놓고, 그녀에게 주워 달라고 했다.")
	await novel_interface.show_text_only("하지만 그녀는 예의 바른 미소만 지은 채 고개를 갸웃거리며 '너 바보야?'라는 표정을 지었다.")
	await novel_interface.show_text_only("대치한 지 대략 30초쯤 지나서야 나는 민망하게 직접 휴대전화를 주워 들었고, 이어서 더 멍청한 생각이 떠올랐다──")
	await novel_interface.show_text_only("\"실체가 없다면, 벽도 통과할 수 있는 거 아냐?\"")
	await novel_interface.show_text_only("그래서 그녀가 지켜보는 가운데 선실로 돌아가 갑판으로 통하는 문을 잠그고, 그녀의 시야에서 벗어난 곳에 숨었다.")
	await novel_interface.show_text_only("2분쯤 지나자 문 반대편에서 흐느끼는 소리가 희미하게 들렸다. 불길한 예감에 서둘러 문을 열었더니, 그녀는 내 허벅지를 와락 끌어안고 놓지 않았다.")
	await novel_interface.show_text_only("선실 안을 가끔 지나다니는 웨이터들을 피하려고, 나는 그녀를 질질 끌며 힘겹게 난간 옆으로 옮겼다.")
	novel_interface.show_character("ren_full","wail")
	await novel_interface.show_dialog("(이런 다리 장식 달고는 걷지도 못하겠는데...)", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("아이를 데리고 다니는 게 원래 이렇게 힘든 거야!?")
	await novel_interface.show_text_only("더 골치 아픈 건 다른 사람들 눈엔 그녀가 보이지 않는다는 점이다. 지금의 나는 분명 혼잣말을 하며 몸짓도 이상한 정신나간 사람처럼 보이겠지.")
	await novel_interface.show_text_only("달라붙는 걸 떼어낼 방법이 없어서, 나는 그저 살살 달래는 수밖에 없었다.")
	novel_interface.show_character("ren_full","wry_smile")
	await novel_interface.show_dialog("착하지, 이제 안 두고 갈게~", "렌")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("아까는 내가 잘못했어. 사과할게, 응?", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("그러면서 나는 그녀에게 바보 같은 익살표정을 지어 보였다.")
	await novel_interface.show_text_only("누가 내가 허공을 향해 표정 연기를 하는 걸 보면, 당장 갑판 틈새라도 파고들고 싶을 거다.")
	await novel_interface.show_text_only("스타더스트는 조금 진정된 듯 나를 안은 채 고개를 들었다. 큰 눈을 깜빡이고, 머리 위 귀 장식도 반짝였다.")
	novel_interface.show_character("stardust_small","tear")
	await novel_interface.show_dialog("그럼 나랑 저쪽으로 가겠다고 약속해 줄래...?", "스타더스트")
	await novel_interface.show_dialog("정말, 정말 중요한 일이야...", "스타더스트")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("너 아까 운 척한 거 아니지?")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("(역시 아이들은 다루기 힘들어...)", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("마리루가 이런 위험한 곳에 이 꼬맹이를 데리고 가는 걸 허락해 줄지 전혀 알 수 없었다.")
	await novel_interface.show_text_only("그때 갑자기 이어폰에서 전류 잡음이 들리더니, 마리루가 다시 연결됐다.")
	await novel_interface.show_dialog("렌, 애니. 너희 둘은 마사다부르크에 대해 얼마나 알고 있지?", "마리루")
	novel_interface.show_character("ren_full","worry")
	await novel_interface.show_dialog("음...", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("대충은...", "앤")
	await novel_interface.show_text_only("나는 애써 기억을 더듬어 봤지만, SID 요원 교육 과정에서도 마사다에 관한 정보는 무척 파편적이었다.")
	await novel_interface.show_dialog("제3학원도시, 서아시아 내륙에 있는 요새 도시. 내성과 외성 구역은 수십 미터 높이의 격리벽으로 나뉘어 있다.", "앤")
	novel_interface.show_character("ren_full","bored")
	await novel_interface.show_dialog("아마 민족 문제인지 종교 문제인지 그런 갈등 때문이었던가?", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("아무튼 마사다부르크 외성 구역은 굉장히 위험해 보인다. 매달 한두 번씩은 폭탄 테러가 일어난다던데!")
	await novel_interface.show_dialog("그들의 정보기관인 '마사다 부흥사명국'은 군부가 직접 통제하고 있고, 대담하고 과격한 성향으로 유명하지.", "앤")
	novel_interface.show_character("ren_full","happy")
	await novel_interface.show_dialog("아, 그건 알아. 그 기관을 '모놀라'라고도 부르잖아?", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("영화나 게임에 자주 나오는 이름이지. 다만 주역 세력인 경우는 드물지만.")
	novel_interface.show_character("ren_full","smile")
	await novel_interface.show_dialog("맞아. 게다가 그들 무기는 엄청 발전했잖아. 게임에서도 마사다는 플레이어에게 원격 조종 전차나 드론을 제공하는 쪽으로 자주 나오고...", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("좋아, 그쯤 해 두지──", "마리루")
	await novel_interface.show_dialog("그 지역의 지정학적 환경은 원래부터 무척 복잡했고, 저항군과 분리주의 조직까지 얽히면 더 혼란스러워질 수밖에 없다.", "마리루")
	await novel_interface.show_dialog("하지만 마사다 '내성 구역'만 놓고 보면 안전성은 신토요스 못지않아. 그러니──", "마리루")
	novel_interface.show_character("ren_full","perspire1")
	await novel_interface.show_dialog("뭐? 설마...
허락한 거야?", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("여전히 내 허벅지에 매달린 스타더스트가 기쁜 듯 몸을 꿈틀거렸다.")
	await novel_interface.show_dialog("우리 둘만으로... 괜찮을까?", "앤")
	await novel_interface.show_text_only("셋이야! 셋!!
여기 짐짝 하나 더 있거든!!")
	await novel_interface.show_dialog("이건 첩보 작전이 아니야. 지금은 어디로 가야 할지조차 정확히 모르는 상태다. 너희가 선 넘는 짓만 안 하면 된다.", "마리루")
	await novel_interface.show_dialog("게다가 배를 갈아탈 필요도 없어. 이 도박선은 내일 아침 바로 마사다 항에 정박할 거야~", "아이")
	await novel_interface.show_dialog("...무슨 일이야? 원래는 사몬턴으로 가는 거 아니었어?", "앤")
	await novel_interface.show_dialog("마사다는 3일 후 저항 조직과 정전 협정을 체결할 예정이라, 서명식이 끝나기 전까지 수에즈 운하를 전면 봉쇄한대.", "마리루")
	await novel_interface.show_dialog("카지노 측은 승객의 안전을 고려해, 방금 마사다 군의 '강력한 권고'를 따르기로 하고 에일라트 쪽으로 되돌아가기로 했어.", "마리루")
	await novel_interface.show_dialog("이 배는 홍해-사해 대운하를 따라 북상해 마사다 항에 정박한 뒤, 수에즈 운하 봉쇄가 풀릴 때까지 거기서 머물게 된다.", "마리루")
	await novel_interface.show_dialog("애니의 위장 신분은 신토요스 예술 교류 프로젝트 학생이야. 절차는 이미 끝냈지.", "마리루")
	await novel_interface.show_dialog("그리고 렌──네 위장 신분은 이미 마사다 해안 방위대에 등록됐을 가능성이 크니, 계속 꼬마 간호사 노릇이나 해라~", "마리루")
	await novel_interface.show_text_only("마리루의 말에는 어쩐지 불길한 웃음기가 섞여 있었다.")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("엥??!", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("어쨌든 협정 서명이 끝나기 전까지는 움직일 수 없으니, 이틀 동안은 시내 관광이나 해~", "아이")
	await novel_interface.show_dialog("그 아이가 가고 싶어 하는 곳이 시가지 바깥이라면, 사흘 뒤에 그쪽 정보 거점 사람들을 붙여 줄게.", "마리루")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("수에즈 운하까지 봉쇄하다니...", "렌")
	await novel_interface.show_dialog("협정 하나 맺는 것뿐인데... 그렇게까지 심각하게 굴 필요가 있어?", "렌")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_dialog("그건 말이지...", "아이")
	await novel_interface.show_dialog("이미 사태가 엄청 심각해졌거든──", "아이")
	await novel_interface.show_dialog("너희는 이틀 내내 배 안에 있었으니까 아직 모르는 모양이네?", "마리루")
	await novel_interface.show_dialog("무, 무슨 일이야...?", "앤")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("십수 시간 전, 마사다 영토 내 헤브론 시의 이브라 모스크 인근에서 공업 화학물질 폭발 사고가 발생했어.", "마리루")
	await novel_interface.show_dialog("폭발 충격파로 주변 건물이 일부 붕괴했고, 전력·상수도·가스 시스템도 파괴됐다.", "마리루")
	await novel_interface.show_dialog("공식 발표에 따르면 현재 그 일대 주민들은 전부 안전 구역으로 대피한 상태래.", "마리루")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("또 테러 공격이야?", "렌")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("이브라 모스크 아래 있는 막벨라 동굴은, 전설상 마사다인의 선조가 묻힌 무덤이야.", "아이")
	await novel_interface.show_dialog("그들이 지난 세기에 그 도시를 접수한 뒤로는 한 번도 고고학 발굴을 한 적이 없지만...", "아이")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("이상한 건, 공식 사상자 보고는 그럴듯한데 정보 봉쇄가 지나치게 철저하다는 거야...", "아이")
	await novel_interface.show_dialog("인터넷엔 근처 주민이 찍은 영상 하나 없고, 관련 뉴스 페이지는 전부 마사다 정부가 제공한 사진과 영상뿐이야.", "아이")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("동시에 헤브론 시내 몇몇 대형 병원의 전산 시스템도 모두 고장 나서, 응급 기록이 대량으로 사라졌어.", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("사고 직후 마사다 측은 세계문화유산 기구가 막벨라 동굴 유적 복구를 돕겠다는 제안을 거의 즉시 거절했지.", "마리루")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("이렇게 노골적인 정보 통제는 확실히 '모놀라'다운 방식이네... 그런데 왜 정보를 막으려는 거지?", "앤")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("아마 사태가 더 복잡해지는 걸 바라지 않아서겠지──", "마리루")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("위성 사진 분석으로 보면, 소형 로켓탄이 원인인 폭발일 가능성이 높아.", "마리루")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("저항군 짓이야?
근데 곧 정전 협정을 맺는 거 아니었어...?", "렌")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("저항군 지도자는 즉시 SNS 계정에서 이번 사건과 자신들은 무관하다고 밝히고, 유감과 규탄의 뜻도 표했어.", "아이")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("현재 정보팀은 이번 습격이 저항군 내부의 어떤 분파 세력이 벌인 일일 가능성을 보고 있어. 그 자식들은 원래부터 한 덩어리가 아니었거든~", "아이")
	await novel_interface.show_dialog("지도부는 정전을 원해도, 내부의 극단파는 그 협정이 성사되길 바라지 않는 거겠지?", "아이")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("그럴 수도 있겠지만 아직은 전부 추측일 뿐이야. 다만 분명한 건, 앞으로 사흘이 제3학원도시에게 가장 민감한 시기라는 거지──", "마리루")
	await novel_interface.show_dialog("그에 맞춰 마사다의 경계 등급도 최고치까지 올라갔어. 너희는 공해상에 있는 것보다 내성 구역에 있는 편이 훨씬 안전해.", "마리루")
	novel_interface.change_expression("sigh")
	await novel_interface.show_dialog("오늘 밤은 푹 쉬어. 내일 항구에 도착하면 다시 연락하마.", "마리루")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("알겠어요!", "렌")
	await novel_interface.show_dialog("알겠어~", "앤")
	await novel_interface.show_text_only("그렇게 말한 뒤 마리루는 배 위의 두 사람과의 통신을 끊고, 대형 화면에 떠 있는 붉은 옷차림의 여성 영상으로 시선을 돌렸다.")
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("...너도 이상하다고 생각하지?", "아키코")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("그래. 이 협정은 발표된 시점부터 너무 갑작스러웠어──", "마리루")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("지난주 마사다 정부 대변인이 갑자기, 열흘 안에 저항군과 정전 협정을 체결하겠다고 발표했지.", "마리루")
	await novel_interface.show_dialog("각국 정부와 언론은 한목소리로 찬양했고, 군축과 정전이 대세인 것도 사실이야.", "마리루")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("──하지만 이 협정은 아무래도 너무 성급해.", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("그래. 신중하게 계산한 뒤 움직이던 샤인네만 총리의 스타일과는 전혀 다르지.", "아키코")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("그의 병세가 예상보다 더 악화된 탓일까...?", "아이")
	await novel_interface.show_dialog("지난 평화 포럼 이후 지금까지 샤인네만 총리는 공개 석상에 한 번도 모습을 드러내지 않았잖아~", "아이")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("어쩌면 그게 전부는 아닐지도──", "마리루")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("마사다 국방군 내부의 모순은 이제 봉합이 불가능한 수준까지 갔을지도 몰라.", "마리루")
	await novel_interface.show_dialog("인원과 예산이 크게 줄어드는 상황에선, 전공파 장교들과 기술파가 완전히 갈라서는 것도 시간문제겠지.", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("국방군 내부에서 학원 계통 출신인 기술파와, 전선에서 싸워 공을 세운 전공파의 다툼인가...", "아키코")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("마리루는 살짝 고개를 끄덕였다.")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("그리고 마사다는 지금까지도, 이 역사적인 협정에 누가 대표로 서명할지 정하지 못했어──", "마리루")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("전 세계의 주목 속에서 이 불세출의 공을 손에 넣는 사람이, 이후 선거에서 이길 가능성도 아주 크겠지?", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("당연히...", "아키코")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("아키코는 문득 뭔가를 깨달은 듯 가볍게 \"아\" 하고 소리를 냈다.")
	novel_interface.show_character("akiko","shock")
	await novel_interface.show_dialog("마사다는 이번 습격이 서명식에 영향을 주지 않게 하려고, 화학물질 폭발 사고라고 주장하는 건가...?", "아키코")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("쯧쯧, 동요하는 네 모습은 여전히 귀엽네~", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","shy")
	await novel_interface.show_dialog("(작게) ...변태.", "아키코")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("아키코는 살짝 붉어진 뺨으로 가볍게 두 번 헛기침했다.")
	novel_interface.show_character("akiko","shy")
	await novel_interface.show_dialog("그래서, 찾았어?", "아키코")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("──지난번에 말했던 적절한 '인선'을.", "아키코")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("마리루는 고개를 저었다.")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("그게 그렇게 쉽게 찾아질 문제였으면, 샤인네만 영감님도 지금까지 버티면서 은퇴를 미루지 않았겠지...", "마리루")
	await novel_interface.hide_character()
	await novel_interface.stop_music()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("...")
	await novel_interface.show_text_only("다음 날 오전 8시 40분.")
	await novel_interface.show_text_only("'리버티 스타' 호 도박선, VIP 레스토랑.")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Gambling_Boat4.png")
	await novel_interface.show_text_only("귀빈 레스토랑은 선실 최상층에 있었다. 규모는 크지 않았지만 전망만큼은 훌륭했다.")
	await novel_interface.show_text_only("창밖은 먹구름으로 뒤덮여 있었고, 깊고 어두운 바다는 어딘가 불길한 재앙을 품고 있는 듯했다.")
	await novel_interface.show_text_only("아마 어젯밤 카지노의 무제한 무료 주류에 다들 뻗어버린 건지, 지금 레스토랑에는 우리 테이블 말고는 손님이 없었다.")
	await novel_interface.show_text_only("나는 멍하니 창밖을 바라봤다. 저 짙푸른 바다는 홍해와 사해를 잇는 마사다 운하였다.")
	await novel_interface.show_text_only("이 운하는 이질물 기술을 활용해 제1·제3학원도시가 공동 건설한 것으로, 총 길이는 180킬로미터, 양끝의 해발 고도 차는 430미터에 달한다.")
	await novel_interface.show_text_only("아카바만 북단의 에일라트 항에서 출발해 사해 남서안의 마사다부르크까지 이어진다.")
	await novel_interface.show_text_only("마사다의 생명선인 이 운하는 계획 단계부터 주변 여러 소국과의 충돌과 분쟁을 동반해 왔다.")
	novel_interface.show_character("anne_uniform","normal1")
	await novel_interface.show_dialog("저 앞이 마지막 갑문이지?
엄청난 공사였네...", "앤")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("애니는 휴대전화로 이 운하에 관한 다큐멘터리를 찾아 나와 같이 보자고 했다.")
	novel_interface.show_character("ren_medical","gratified")
	await novel_interface.show_dialog("응. 매니저 말로는 어젯밤에 이미 낙차가 100미터가 넘는 대형 갑문 세 곳을 통과했다더라... 정오 전엔 도착한대.", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("나는 국제 의료구호 조직에서 지급한, 지나치게 큰 외투 자락을 잡아당겼다.")
	novel_interface.show_character("ren_medical","shy")
	await novel_interface.show_dialog("(설마 프리사이즈야...? 여성용은 없는 거야!?)", "렌")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","smile",0.25)
	await novel_interface.show_dialog("너 안에는 왜 슬립 원피스랑 레깅스만 입고 있어?", "앤")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("애니가 조금 짓궂은 눈길로 나를 훑어봤다.")
	novel_interface.show_character("ren_medical","shy_left")
	await novel_interface.show_dialog("옷을 그렇게 많이 가져온 게 아니라고!", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("일정이 갑자기 바뀔 줄 누가 알았겠어. 그래도 편의점에 속옷이랑 그거...는 팔아서 다행이었지.")
	await novel_interface.show_text_only("나는 조금 민망해서 슬립 원피스 자락을 끌어내렸다. 원래는 비상용 잠옷으로 가져온 옷이었는데.")
	novel_interface.show_character("ren_medical","shy_right")
	await novel_interface.show_dialog("(치맛단엔 연한 레이스까지 달려 있고, 진짜 창피해 죽겠어!)", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("stardust_small","happy")
	await novel_interface.show_dialog("있지 있지...", "스타더스트")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("스타더스트가 달려와 내 팔을 흔들며 말했다.")
	novel_interface.show_character("stardust_small","smile")
	await novel_interface.show_dialog("이 편 다 봤어. 다음 편으로 바꿔 줘~", "스타더스트")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("나는 냅킨으로 만든 임시 거치대에서 휴대전화를 집어 들어 몇 번 눌러 준 뒤, 그녀의 자리 앞 탁자에 다시 내려놓았다.")
	await novel_interface.show_text_only("그러자 그녀는 얌전히 엎드린 채 흥미진진하게 만화를 보기 시작했다.")
	novel_interface.show_character("anne_uniform","relieve")
	await novel_interface.show_dialog("이 아이도 얌전할 때는 꽤 귀엽네...", "앤")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("애니는 손에 든 금평당 같은 작은 알갱이를 살펴보다가 시선을 스타더스트에게 옮겼다.")
	await novel_interface.show_text_only("어젯밤 우리는 도박선 금고에서 찾아낸 이 금빛 알갱이를 한 번만 만져도 스타더스트가 보인다는 사실을 알게 됐다.")
	await novel_interface.show_text_only("하지만 애니는 나처럼 그녀를 만질 수 없었다. 전체적인 감각은 입체 홀로그램을 보는 것과 비슷하다고 했다.")
	novel_interface.show_character("anne_uniform","normal1")
	await novel_interface.show_dialog("네가 그걸 거기 숨겨서 금고에서 들고 나올 생각을 했다니, 대단하네.", "앤")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("난 아마 못 했을 것 같아...", "앤")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("애니가 살며시 자기 가슴팍을 만졌다.")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("그, 그건 그 드레스가 좀 꽉 끼어서 그랬을 뿐이야...", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("애니는 억지 미소를 지으며, 내가 위로해 준 척했다.")
	await novel_interface.show_text_only("어젯밤 이 사실을 보고했을 때, 아이는 스타더스트가 어떤 특별한 형태로 존재하는 정보 집합체일 거라고 추측했다.")
	await novel_interface.show_text_only("그리고 저 금평당처럼 생긴 물건엔 아마 스타더스트의 인격 정보가 저장돼 있을 거야──")
	await novel_interface.show_text_only("비유하자면 인간의 '영혼' 같은 거지.")
	await novel_interface.show_text_only("하지만 그 영혼은 기억을 잃어버렸어. 세월이 너무 오래 흘러서인지, 다른 이유 때문인지는 아이도 확신하지 못했다.")
	await novel_interface.show_text_only("나는 탁자 위에 엎드려 수십 년 전의 개그 애니메이션을 흥미진진하게 보고 있는 그 꼬마를 바라봤다.")
	await novel_interface.show_text_only("그 애니는 나도 어릴 때 본 적이 있어서 제법 인상 깊었다──")
	await novel_interface.show_text_only("줄거리는 주인공이 좀 무책임한 엄마와 함께 열대우림에서 살다가, 어느 날 이상한 여자아이가 갑자기 나타나는 이야기였지...")
	novel_interface.show_character("ren_medical","bored")
	await novel_interface.show_dialog("(어라? 이 줄거리 왠지 좀 비슷한데...)", "렌")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","normal1",0.25)
	await novel_interface.show_dialog("렌, 금고에 있던 그 운석은 4천 년 전에 지구에 떨어진 거 맞지?", "앤")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("애니의 말에 내 생각이 끊겼다.")
	novel_interface.show_character("ren_medical","normal1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("아, 맞아. 4천 년 전이라 했지...", "렌")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("조몬 시대였나 뭐였나... 하, 역사 교과서 내용은 시험 끝나면 다 까먹는 게 당연하잖아.")
	novel_interface.show_character("ren_medical","wry_smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("이 녀석, 설마 외계인인 건 아니겠지...?", "렌")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("애니메이션의 어떤 장면이 웃겼는지 스타더스트는 갑자기 아무 걱정도 없이 웃기 시작했고, 머리의 불빛도 번쩍번쩍했다.")
	novel_interface.show_character("ren_medical","wry_smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","relieve",0.25)
	await novel_interface.show_dialog("아마 아닐걸. 저 애가 만화 보면서 실실 웃는 모습, 너랑 완전 똑같거든──", "앤")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("나, 나랑 닮았어?")
	novel_interface.show_character("ren_medical","wry_smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","unhappy",0.25)
	await novel_interface.show_dialog("있잖아, 렌... 너 예전엔 남자애였지?", "앤")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("응?", "렌")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("그전에... 혹시... 그러니까...", "앤")
	novel_interface.change_2nd_expression("shy")
	await novel_interface.show_dialog("여자애한테 무책임한 짓을 한 적은 없어?", "앤")
	await novel_interface.show_dialog("저 아이가 너한테 이렇게까지 들러붙는 거 보면, 혹시 네가 예전에 밖에서...", "앤")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("말, 말도 안 되는 소리 하지 마!", "렌")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("내가 남자였을 때도 첫키스조차 못 해봤거든!!")
	novel_interface.show_character("ren_medical","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","relieve",0.25)
	await novel_interface.show_dialog("오~? 정말?", "앤")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("렌, 의외로 순정파였네~", "앤")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("애니는 얼굴을 들이밀며 의심스러운 눈으로 나를 바라봤고, 나는 황급히 화제를 돌렸다.")
	novel_interface.show_character("ren_medical","shy_left")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","happy",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("저, 저기 봐! 바깥, 저쪽 지평선을...", "렌")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("통유리창 너머로 멀리 보이는 동쪽 지평선에는 기묘한 암적색 구름 덩어리가 떠 있었다.")
	novel_interface.show_character("ren_medical","shy_left")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","panic",0.25)
	await novel_interface.show_dialog("저건...", "렌")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("뭐지...", "렌")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("나와 애니는 멀리의 이상 현상을 보며 서로 얼굴만 마주봤고, 스타더스트는 고개도 들지 않은 채 말했다──")
	await novel_interface.show_dialog("모래폭풍.", "스타더스트")

	print("=== 星尘降临篇第8话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
