# bathophobia_ep20.gd - 深海恐惧症篇第20话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep20_script()

func play_script():
	pass

func bathophobia_ep20_script():
	novel_interface.change_music("res://assets/audio/music/Barrier Maze.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Snedronningen_Exhibition_Room.png")
	await novel_interface.show_text_only("Der Trupp weicht weiterhin den Angriffen der wütenden, nicht identifizierbaren Feinde aus und sendet einen Notruf nach dem anderen.")
	await novel_interface.show_text_only("Weitere Feinde strömen durch den Basiseingang herein. Die Truppe gratuliert sich selbst, dass sie sich nicht in den tobenden Schneesturm zurückgezogen hat.")
	await novel_interface.show_text_only("Sie können mit diesen außergewöhnlich flinken Feinden draußen im Schnee ganz sicher nicht fertig werden, ohne Hindernisse, hinter denen sie sich verstecken können.")
	await novel_interface.show_text_only("Dies lässt ihnen jedoch auch keine andere Wahl, als tiefer in die Basis vorzudringen und eine strategisch vorteilhafte Position zu suchen, von der aus sie Unterstützung anfordern können.")
	await novel_interface.show_text_only("Sie werden immer weiter nach innen gezwungen, aus dem Ausstellungsraum heraus, in einen Korridor.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Corridor.png")
	await novel_interface.show_dialog("Mist. Hier gibt es kein Signal.","Kadermitglied C")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("Leute, geht zuerst in den Kommunikationsraum. Möglicherweise finden Sie dort einige funktionierende Übertragungsgeräte.","Milch")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Verstanden!","Kadermitglied C")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("Ich habe die 3D-Layoutkarte dieses Ortes überprüft. Unsere derzeit beste Vorgehensweise besteht darin,... \\n... nach unten zu bewegen, Richtung 8 Uhr.","Milch")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Alle Truppmitglieder sind unterschiedlich schwer verwundet. Aber sie machen weiter und bieten sich gegenseitig Deckung in Form von zwei Gruppen, einer an der Spitze und einer im Nachhinein.")
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("(Diese Typen... sie heilen so schnell. Es scheint einfach nicht richtig... )","Beth")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("milk_battle","shock",0.25)
	await novel_interface.show_dialog("Achtung!","Milch")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Beth schaltet sich für den Bruchteil einer Sekunde aus, und dann drehen die Feinde, die sie von hinten verfolgen, plötzlich ihre Gelenke und riesige Klingen schneiden in einem bizarren Winkel durch die Luft.")
	await novel_interface.show_text_only("Überrascht schiebt Milk Beth hinter sich in den Archivraum.")
	await novel_interface.show_text_only("Sie entkommen der schwingenden Klinge erfolgreich, obwohl sie immer noch einen riesigen Riss auf den Bodenfliesen hinterlässt.")
	await novel_interface.show_text_only("Der Spalt ist nicht zu breit, aber immer noch breit genug, um die beiden Gruppen zu trennen. Might as well be a bottomless canyon.")
	await novel_interface.show_dialog("Ahh!","Squad-Mitglied D")
	await novel_interface.show_text_only("Ein Truppmitglied mit dem Codenamen Mute steht zufällig am nächsten beim Feind und schwingt die riesige Klinge. In ihrer Verzweiflung, ihre Glieder zu beschützen, bewegt sie sich vorwärts und lässt die Klinge ihren Körper immer wieder durchbohren.")
	novel_interface.show_character("milk_battle","shock")
	await novel_interface.show_dialog("... Stumm!","Milch")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mute, der immer so fröhlich ist, der Hawaiihemden liebt. Jedes Mal, wenn Milk einen ihrer Wettpools startet, ist Mute der Idiot, der am Ende Geld verliert.")
	await novel_interface.show_text_only("Es ist lange her, dass Milk sich daran erinnert, Mute das letzte Mal bei ihrem Codenamen genannt zu haben. She never expected it to be in such a situation.")
	await novel_interface.show_text_only("Ihr frisch vergossenes Blut färbt die Wände des Korridors rot.")
	await novel_interface.show_text_only("Mutes modifizierter MP5K fällt zu Boden, rutscht ein wenig und bleibt schließlich neben Milks Füßen stehen.")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("... Verdammt!","Milch")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Milks modifizierte Maschinenpistole hat einen verringerten Rückstoß, sodass sie sie halten und mit nur einer Hand einen ganzen Kugelhagel abfeuern kann.")
	await novel_interface.show_text_only("Sie holt einen Dolch heraus und nagelt ihr Ziel, dessen Körper von Einschusslöchern übersät und mit einer groben grünen Flüssigkeit bedeckt ist, am Hals an der Wand fest.")
	await novel_interface.show_text_only("Während andere Truppmitglieder mit ihren Schutzschilden einspringen, um die Feinde abzuwehren, richtet Milk ihre Aufmerksamkeit auf ihre gefallene Teamkollegin und drückt auf die Wunde an ihrem Hals.")
	await novel_interface.show_text_only("Die Temperatur ist hier so niedrig, dass das Blut, das aus Mutes Aorta sprudelt, wie kochendes Wasser sprudelt.")
	novel_interface.show_character("baizhu_break","angry")
	await novel_interface.show_dialog("Wo ist das Erste-Hilfe-Set? Holen Sie sich das Blutstoppspray!","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Haah...  hah...","Squad-Mitglied D")
	await novel_interface.show_text_only("Tief in ihrem Inneren wissen sie, dass sie wahrscheinlich nicht mehr zu retten ist. Aber sie versuchen es trotzdem.")
	await novel_interface.show_text_only("Das blutstillende Spray vermischte sich mit Blut, färbte die blutstillende Watte an der Wunde schnell rot und glitt an Milks Hand entlang auf den Boden.")
	await novel_interface.show_text_only("Mittlerweile versammeln sich immer mehr Feinde draußen im Flur, angelockt von der Aufregung.")
	await novel_interface.show_text_only("Die Schutzschilde, die sie zurückhalten, wurden so oft eingeschlagen, dass sie bereits brechen.")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("Ugh...","Milch")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Drei Truppmitglieder kreisen umher, um zu helfen, und eröffnen das Feuer, um Deckung zu bieten, während Milk versucht, ihre gefallene Teamkollegin in den Archivraum an der Ecke weiter vorne zu zerren.")
	await novel_interface.show_text_only("Dabei hinterlassen sie eine lange Blutspur auf dem kalten, glänzenden Flurboden.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Reference_Room_Dark.png")
	await novel_interface.show_text_only("Nachdem sie Mute endlich ins Zimmer gebracht hat, überprüft Milk ihren Puls mit ihren Fingern.") #换行问题
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("Wir brauchen hier etwas Adrenalin!","Milch")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beth eilt herbei, reißt Mutes blutgetränktes Hemd auf, schätzt die beste Position auf der linken Seite ihrer Brust und sticht mit einer schnellen Bewegung den Adrenalinstift hinein.")
	await novel_interface.show_text_only("Die rechtzeitige Aufnahme bringt Erleichterung und einen Hauch von Farbe in Mutes Gesicht zurück – allerdings nur für ein paar Sekunden.")
	await novel_interface.show_dialog("*hustet*\\n*keucht*","Squad-Mitglied D")
	await novel_interface.show_text_only("Allerdings liegt die Blutverlustrate bereits nach wenigen Sekunden weit über der vom Körper erträglichen Grenze.")
	await novel_interface.show_text_only("Die Farbe verlässt Mutes Gesicht erneut. Ihre Pupillen weiten sich.")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("…","Milch")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tränen steigen in Milks Augen auf.")
	await novel_interface.show_text_only("Beth legt eine Hand auf die von Milk, die immer noch fest auf die Wunde ihrer Teamkollegin drückt. Sie tauschen einen stummen Blick aus, der viele Worte sagt.")
	await novel_interface.show_dialog("We can’t hold them off any longer! Wir müssen uns zurückziehen!","Kadermitglied C")
	novel_interface.show_character("baizhu_break","speechless")
	await novel_interface.show_dialog("Milch!","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Milk biss die Zähne zusammen und hebt die Probenschachtel auf, für die Mute im Archivraum ihr Leben riskiert hatte.")
	await novel_interface.show_text_only("Der Kader ist ohnehin schon in Unterzahl. Wenn einer ausfällt, steckt der Rest in noch größeren Schwierigkeiten.")
	await novel_interface.show_text_only("Niemand will es zugeben, aber das ist die Realität, mit der sie jetzt konfrontiert sind.")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("We’ll take that passage over there. Rückzug!","Milch")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ich übernehme die Nachhut.","Squad-Mitglied B")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BTB.png")
	await novel_interface.show_text_only("Die Mädchen stehen Rücken an Rücken, den Blick wachsam.")
	await novel_interface.show_text_only("Milk hält ihre Waffe fest umklammert und versucht ihr Bestes, um den Rest ihrer Truppe in Deckung zu halten.")
	await novel_interface.show_dialog("(Wie... ist das passiert... ?)","Beth")
	await novel_interface.show_text_only("Beths Ermittlungen zufolge hatte „Ningen“ lediglich ein gewöhnliches Erkundungsteam in die Antarktis geschickt.")
	await novel_interface.show_text_only("Allerdings sind die Feinde, die sie sehen, kein gewöhnliches Erkundungsteam.")
	await novel_interface.show_dialog("(War es meine Schuld, dass ich das nicht vorhergesehen habe?)","Beth")
	await novel_interface.show_dialog("(Aber ich habe damit gerechnet. Oder?)","Beth")
	await novel_interface.show_dialog("(Ich wusste die ganze Zeit... )\\n(Ich wusste die ganze Zeit, dass ich sie nur benutze, und es ist gefährlich... )","Beth")
	await novel_interface.show_dialog("(Yet I still let this happen... )","Beth")
	await novel_interface.show_text_only("Als Milk Beths Zögern bemerkt, lehnt sie sich gegen sie.")
	await novel_interface.show_text_only("Die Milch ist in dicken Schichten gebündelt, so dass sie die Körperwärme des anderen nicht spüren können. Doch irgendwie fühlt sich Beth immer noch getröstet.")
	await novel_interface.show_dialog("Es wird alles gut.","Milch")
	await novel_interface.show_dialog("…","Beth")
	await novel_interface.show_dialog("Ich bin genau hier.","Milch")
	await novel_interface.show_text_only("... „Es wird alles gut. Ich bin hier.“")
	await novel_interface.show_text_only("Als Beth in die Realität zurückkehrt, fällt ihr Blick auf den Rest ihrer Truppmitglieder.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Corridor.png")
	await novel_interface.show_text_only("Diejenigen, die die Schutzschilde tragen, werfen ihr kaum einen zweiten Blick zu, während die Feinde weiter auf sie drängen. Sie gestikulieren ihr kurz: Geh, geh.")
	await novel_interface.show_text_only("Wissen diese tapferen Krieger überhaupt, womit sie es genau zu tun haben?")
	await novel_interface.show_text_only("Wissen sie überhaupt, was diejenigen tun, die ihnen Befehle erteilen?")
	novel_interface.show_character("baizhu_break","sad")
	await novel_interface.show_dialog("Es tut mir leid. Es war meine Schuld... Ich habe die Situation falsch eingeschätzt...","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Dies ist nicht die Zeit, sich zu entschuldigen.","Squad-Mitglied B")
	await novel_interface.show_text_only("Die andere Partei zwinkerte Bai Zhu zu, dass er verstand.")
	await novel_interface.show_dialog("Sobald wir aus diesem Höllenloch herauskommen, gönnen Sie mir besser Tequila im Wert von zehn Jahren.","Kadermitglied C")
	await novel_interface.show_text_only("Beth kann kaum glauben, dass ihre Teamkollegen auch in einer solchen Situation immer noch versuchen, sie zu trösten.")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("– Achtung!","Milch")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Milk drängt Beths linke Schulter hinunter und blockt eine ankommende Sichel mit einer ohnehin schon munitionslosen Maschinenpistole ab.")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("Diese Jungs sind unmöglich!","Milch")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Die Feinde durchqueren wie eine gerade freigelassene Leopardenhorde problemlos die von den Schutzschildträgern geräumte Pufferzone.")
	novel_interface.show_character("baizhu_break","puzzled")
	await novel_interface.show_dialog("Das liegt daran, dass sie Ningen... sind, das bedeutet auf Japanisch „Mensch“.","Beth")
	await novel_interface.hide_character()
	novel_interface.show_character("witch_third")
	await novel_interface.show_dialog("Nin... gen... heeheehee... \\nStirb! Sterben! Sterben!","???")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Es ist, als ob das Wort Ningen sie amüsiert. Der Anführer der Feinde grinst mit einem gesichtszerreißenden Lächeln über beide Ohren.")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("Sie sind verrückt... \\nWir können diese Monster auf keinen Fall besiegen...","Milch")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Beth, nimm die anderen und geh! Wir werden sie aufhalten!","Truppführer")
	await novel_interface.show_text_only("Bevor das schildhaltende Truppmitglied seinen Satz überhaupt beenden kann, wird ihr Schild von einem Sense haltenden Feind durch die Luft geschleudert. Nachdem sie ihre Deckung verloren haben, eröffnen die Truppmitglieder sofort das Feuer und weichen den Angriffen so gut sie können aus.")
	await novel_interface.show_text_only("Plötzlich, aus dem Nichts –")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BaizhuBattle.png")
	await novel_interface.show_text_only("Plötzlich blockierte eine seltsam geformte Schwertklinge fest die Sichel, die Milk angriff.")
	await novel_interface.show_text_only("Beth beschwört Dutzende silberner Lichtkleckse herauf, die auf die Feinde zurasen und auf ihren Körpern weiße Flecken hinterlassen, die an Erfrierungen erinnern.")
	await novel_interface.show_text_only("Der grüne Schleim, der aus den Körpern der Feinde strömt, kann ihre Wunden heilen – aber er hat keine Wirkung auf diese weißen Flecken. Sobald sie von Granatsplittern getroffen werden, zersplittern ihre Körper in Stücke.")
	await novel_interface.show_text_only("Dann blinzelt Beth neben Milk ins Blickfeld. Sie fliegt in die Luft und feuert im Handumdrehen Dutzende Kugeln auf die umstehenden Feinde ab.")
	await novel_interface.show_dialog("Uh...  Bethy... ?","Milch")
	await novel_interface.show_text_only("In Milkys fassungslosen Augen spiegelte sich die seltsame weiße Lichtgruppe, die auf die Waffe seines Freundes schlug.")
	await novel_interface.show_text_only("Schneller, als ihre Kugeln überhaupt fliegen können, schwingt Beth das Großschwert in ihrer linken Hand. Auf seiner Oberfläche erscheinen komplizierte, spiralförmige Muster.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Dann beginnt der Kontinent erneut zu beben.")
	await novel_interface.show_text_only("Doch die Truppmitglieder, die zu sehr mit dem Kämpfen beschäftigt sind, bemerken... kaum")
	
	print("=== 深海恐惧症篇第20话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
