# bathophobia_ep19.gd - 深海恐惧症篇第19话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep19_script()

func play_script():
	pass

func bathophobia_ep19_script():
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Snedronningen_Exhibition_Room.png")
	await novel_interface.show_text_only("下へと続く階段を伝って、ゆっくりと室内に\\n入った。")
	await novel_interface.show_text_only("意外なことに電力設備と換気システムは作動して\\nおり、空気はそれほど淀んでいない。")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("こんなに広い建物なのに、人影が1つも\\n見当たらないなんて。", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("それなのにシステムは作動している……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("遠くから換気扇の音。\\n\\n室内では展示台のようなものが薄い光を放ち、\\n整然と並んでいる。")
	await novel_interface.show_text_only("こんな薄暗い環境の中だと、何か未知なる危険が\\n俺達を覗いているような気がしてくる……")
	await novel_interface.show_text_only("俺達は用心深く周囲の様子を観察して、\\nそこから展示品に着目した。")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("これは……標本なのか？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ガラスの展示ケースの中には、何かの海洋生物\\nのような展示品がアクリル樹脂のスタンドにより\\n支えられている。")
	await novel_interface.show_text_only("その生物の外殻は白く半透明で艶やかだった。\\n\\nすべすべした尻尾もあり、\\nなんとなく奇妙な深海生物の類を思い出す。")
	await novel_interface.show_text_only("こんな背中が透明でつるつるの生き物なんて、\\n正面から見たらどんなだろうと気になるが……")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("──────────ッ！！", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("俺は展示台の向こう側に回ると、\\n思わず狼狽えてしまう。")
	await novel_interface.show_text_only("生物の正面には、8本の太くて醜い爪が生え、\\nそれぞれが人の指みたいな関節をしている。")
	await novel_interface.show_text_only("8本の爪の中心には、縦に裂けた口器があった。\\n\\n筋肉のような赤い組織が目立ち、\\n口の中は細かい牙で隙間なく覆われている。")
	await novel_interface.show_text_only("思わず有名なホラー映画の中に出てくる\\n人の顔にくっ付いて離れない宇宙生物を、\\n連想してしまった。")
	novel_interface.show_character("ren_battle","wail")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","perspire",0.25)
	await novel_interface.show_dialog("本当、悪趣味な芸術品ね……", "ラファエル")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("え――――っ？\\nこ、これって映画のセットみたいな作り物なの？", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("いいえ、それは本物の生物標本……", "ラファエル")
	await novel_interface.show_dialog("戦争時に行われた、遺伝子改造技術の失敗作よ。\\n私が幼い頃、サモントンの研究所で良く見たわ。", "ラファエル")
	await novel_interface.show_dialog("後に価値のない物と判断されて、\\nある時期に大規模な廃棄が実行されたはず。", "ラファエル")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_dialog("しかし、このようなモノは生体廃棄物として\\n処理するのが一般的だけど……", "ラファエル")
	await novel_interface.show_dialog("こんな芸術品みたいに堂々と展示するとはね……", "ラファエル")
	novel_interface.change_2nd_expression("jeer")
	await novel_interface.show_dialog("ここの持ち主、あんたよりレベルの高い変態ね。", "ラファエル")
	novel_interface.character_light(0.35,"wail")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("──俺は変態じゃないって！", "小憐")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("ただこの展示品は……確かにちょっと……")
	novel_interface.show_character("heinrich_battle","worry")
	await novel_interface.show_dialog("ここには誰もいませんわね……", "ハインリッヒ")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("そのようね。基地全体がもぬけの殻だわ。\\n長年メンテをしてない形跡が所々確認できるし。", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","shout")
	await novel_interface.show_dialog("足元にお気を付けを！", "ハインリッヒ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("えっ！？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("薬莢を踏み付けた滑った俺は、\\n展示ケースの方へ転びそうになってしまう。\\n頭が展示ケースの角にあたる寸前──")
	await novel_interface.show_text_only("ラファエルが駆け寄って、タイミング良く俺を\\n支えてくれた。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("まったく、世話が焼けるわね……", "ラファエル")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","wail",0.25)
	await novel_interface.show_dialog("──あ、危なかったっ！", "小憐")
	novel_interface.change_2nd_expression("wry_smile")
	await novel_interface.show_dialog("ありがとう……ラファエル。", "小憐")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("社交ダンスのような姿勢で俺を抱きしめている\\nラファエル。\\nその動作は男の俺でも格好良かったと認めざるを\\n得ない。")
	await novel_interface.show_text_only("ラファエルは胸に抱いた俺を放してから、\\n少し恥ずかしそうに咳払いをした。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Corridor.png")
	await novel_interface.show_text_only("先ほどの部屋を出て、金属甲板で覆われている\\n長い廊下に着く。")
	await novel_interface.show_text_only("ここの照明は先ほどの部屋よりは明るいが、\\n並び立つ扉と静かな雰囲気も相まって、\\n不気味さが増している。")
	await novel_interface.show_text_only("だが、深々と響く機械駆動のホワイトノイズは\\n1点の事実を説明している──")
	await novel_interface.show_text_only("……この基地は、完全な眠りにはついていない。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("もし誰かがシステムを維持しているのであれば、\\nなんで俺達をずっと放置しているんだ？", "小憐")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","smile",0.25)
	await novel_interface.show_dialog("そいつが敵意を持っているとすれば、\\nとっくに手を下しているでしょうね……", "ラファエル")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("突然、暗闇の中で光点が動いていることに気づきました。よく見てみると、遠くないところにある監視カメラがこちらに向けられていることがわかりました。")
	await novel_interface.show_text_only("俺はカメラに向かって手を振った。")
	novel_interface.show_character("ren_battle","smile")
	await novel_interface.show_dialog("すみません──あの、少し聞きたいんですが……", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("乙女かあんたは。\\n挨拶と振る舞いが女々しい。", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ラファエルが急に口を挟んできた。")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("ちょっとそこで隠れているあんた達、\\nいつまでコソコソしてるつもりよッ！", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("いえ……これは、覗かれてる感じがしません……", "ハインリッヒ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("（ただの音に反応する監視装置かな？）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("この手の音声認識の装置って\\n小型の超音波発生器だけで壊せるから、\\nもう何年も前に淘汰されたはずなんだけど……")
	await novel_interface.show_text_only("監視装置は動作しているが、その背後に『人間』\\nらしい気配がまったく感じられない。")
	await novel_interface.show_text_only("つまりは誰もいない状況に変わりはなく、\\n俺はがっかりした。\\nラファエルがまだ困惑中だったので、ついでに\\nわざとらしい口調でオドロオドロしく喋る──")
	novel_interface.show_character("ren_battle","uneasy")
	await novel_interface.show_dialog("率直に言うと……笑われるかもしれないけど……", "小憐")
	await novel_interface.show_dialog("でも俺は感じてしまったよ……\\nきっとここには……恐らく人間以外の何かが……", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("──ゆゆゆ、ゆ、幽霊がいるとでも言いたいのか\\nあんたはッ！？ ", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ラファエルは異常に高いトーンで俺の話を遮る。")
	await novel_interface.show_text_only("俺がわざと怖がらせようとしている事に気付き\\nラファエルは血相を変えて駆け寄って来て、\\n容赦なく俺の頭を叩こうとした。")
	await novel_interface.show_text_only("彼女の一撃を避けようとした最中、\\n持っていた暖玉をポケットから落としてしまう。")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("ち、違うってラファエル。そういう意味で\\n言ったわけじゃ──は──はっくしょんッ！\\nラファエルがそこまで幽霊が苦手なんて、\\n知らなかったんだ……", "小憐")
	await novel_interface.show_dialog("さ、寒！！！", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("ふんっ。", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("暖玉の加護を失い凍え縮み上がった俺の様子を\\n見て、やっとラファエルの怒りが収まった。")
	await novel_interface.show_text_only("それよりも基地の奥まで入っているはずなのに、\\nどうしてまだこんなに寒いいいいい……")
	await novel_interface.show_text_only("俺は慌てて暖玉を拾い上げた。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("おかしくないか？こんな寒さで基地内の人は\\nどうやって暮らしているんだよ？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("よく観察してみると、壁の隅っこはすでに凍っているところが多かった…。")
	await novel_interface.show_text_only("氷と雪の中でサバイバルするゲームをなんとなく思い出します...")
	await novel_interface.show_text_only("技術革新に力を入れ、生産を促し、人々を導き、\\n自分の統率力で滅亡を防いでいく………\\nゲームのラストはわけ分かんなかったけど。")
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("（おかしい）", "ハインリッヒ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ハインリッヒは手のひらを壁に当てた。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("ま、また人の家のモノを壊したりしないでね──", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("彼女が壁を触ると、そのまま支柱とかを丸ごと\\n取り外しそうで怖い……")
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("違いますわ。", "ハインリッヒ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金髪の錬金術士は真剣な顔つきだ。")
	await novel_interface.show_text_only("彼女が手のひらを当てた場所から壁に沿って\\n周囲へ波紋のような気流が広がる。")
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("…………", "ハインリッヒ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("どうしたの？", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("……わたくし達、閉じ込められましたわ。", "ハインリッヒ")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("何だと？", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("慌てて廊下の突き当りまで走って確認したが、\\nさっきの部屋はロックされていなかった。")
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("驚かさないでくれよ……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ホッと溜め息を吐きつつ元の場所へ戻り、\\n先ほど扉が開いている事を\\n確認していたプレートに「資料室」と\\n貼ってあった部屋へと向かった。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Reference_Room.png")
	await novel_interface.show_text_only("資料室の雰囲気は廊下よりもずっと良い。")
	await novel_interface.show_text_only("周囲を見渡していたら、床のヒビ割れに気付かず\\nまた少し転びそうになる。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("あんたねぇ、気を付けなさいよ……", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ラファエルは資料室の外で俺を見つつも、\\n\\n廊下の壁の事に対して考えを巡らせている\\nハインリッヒの方にも視線を向けている。")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("ん？　待って、\\nこの資料室……風が吹いている？", "小憐")
	novel_interface.change_expression("solemn")
	await novel_interface.show_dialog("もしかして……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("俺は試しに暖玉を前の机に置き、室内の温度を\\n感じてみた。")
	await novel_interface.show_text_only("やっぱり、ここは廊下と全然違う……\\n\\n暖房が十分に効いていて、今南極にいるって事を\\n忘れてしまいそうだ。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("あれっ……？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("でもさっき……扉が開いてるのを確認するため、\\n部屋の様子を見た時は……\\n本棚の配列が、こんなんじゃなかったような？")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("（…………俺の記憶違いか…？）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("俺は頭をかいて、部屋の外へ出ようとした。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("足元注意よ。", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","smile")
	await novel_interface.show_dialog("分かってる分かってる。まったく、床がこんなに\\n割れているのに誰も修理しないなんて……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("そう言いながらも、床を注視する──")
	await novel_interface.show_text_only("床には、破損も亀裂もない。")
	await novel_interface.show_text_only("鏡のようにピカピカな大理石の床が、\\n俺の縞パンを映す……")
	await novel_interface.show_text_only("とりあえず、まずは両足を閉じて考える。")
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("…………", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("……やっぱりおかしい。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("……どうされましたか、マスター？", "ハインリッヒ")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("そこでぼーっと何をしてるのよ？", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("さっきまでにここにあったヒビが……消えた？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("さっきヒビにつまずいて、転びそうになった事を\\nはっきりと覚えている。")
	await novel_interface.show_text_only("亀裂があったはずの地面。")
	await novel_interface.show_text_only("唯一暖房が作動している資料室。")
	await novel_interface.show_text_only("変化した本棚の配列。")
	await novel_interface.show_text_only("心臓の音が加速する。")
	await novel_interface.show_text_only("俺は慎重に一歩を、前へと踏み出した。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("ねえ、隙間でつながるってどういう意味？まだ手伝ってほしいですか...", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ラファエルの態度が俺を錯覚させる。")
	await novel_interface.show_text_only("だけど身体は嘘を吐かない──\\n今踏んでいるのは、平坦な地面だ。")
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("…………", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("…………", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("……どうやら、それぞれ違う物をわたくし達は\\n見ているようですね。", "ハインリッヒ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("どうしてこんな事が……")
	await novel_interface.show_text_only("俺は無線機でアニーとマリルに連絡をして、\\n不安な気持ちを取り除こうとした。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("──もしもし、アニー、アニー？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("無線機から何の返事もない。\\n地下だから電波が届かないのかもしれない。")
	await novel_interface.show_text_only("俺の妙な表情に気付き、\\nラファエルとハインリッヒも部屋に入ってきた。")
	await novel_interface.show_text_only("───違和感で埋め尽くされた、謎の資料室に。")
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("…………", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("俺の気のせいじゃない……", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","worry")
	await novel_interface.show_dialog("……ここは、先ほどとは別の部屋ですわね。", "ハインリッヒ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突然、廊下からケラケラと奇妙な声がした。")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("──何者だ？！", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/xiaolianContact.png")
	await novel_interface.show_text_only("ラファエルとハインリッヒはすぐに迎撃準備に\\n入った。")
	await novel_interface.show_text_only("俺が振り向いた瞬間、RPGとかで登場しそうな\\n武器を装備した不気味な連中が飛び出してくる。")
	await novel_interface.show_text_only("相手の虚ろな目から見えるのは、\\n単純な敵意。")
	await novel_interface.show_text_only("俺は手に持つバットを強く握った……")
	print("=== 深海恐惧症篇第19话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
