# bathophobia_ep07.gd - 深海恐惧篇第7话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep07_script()

func play_script():
	pass

func bathophobia_ep07_script():
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_entrance.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("從莉琉的紅色Coupe跑車下來時，我只覺得頭暈目眩，雙腳好像踩在棉花上。")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("莉琉……嘔……！ \\n妳的開車方式……嘔……也太誇張了吧！ ！！", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("週末清晨，正當我像蘑菇一樣縮在溫暖被窩裡，安妮突然衝進我的房間硬把我拎了起來。")
	await novel_interface.show_text_only("半夢半醒的我被塞進這輛跑車時，內心還對安妮的暴力行徑耿耿於懷。")
	await novel_interface.show_text_only("但體驗了莉琉驚天動地的駕駛技術後，我腦子裡只剩下「活著真好」的念頭了……")
	await novel_interface.show_text_only("雖然今天是進行「方舟實驗」的日子，但我真的真的超想請病假。")
	await novel_interface.show_text_only("肚子痛了好幾天了，可惡。")
	await novel_interface.show_text_only("到現在還是很想吐……嘔！")
	novel_interface.show_character("anne_battle","perspire")
	await novel_interface.show_dialog("沒事吧，小憐？", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我朝安妮揮了揮手。")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("還好，就是有點噁心，還有全身發抖……", "小憐")
	await novel_interface.show_dialog("回去的時候，我們別坐這輛車可以嗎……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我的聲音虛弱，用祈求的可憐眼神看向安妮。")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("妳這傢伙，竟然發自內心演繹著柔弱少女的設定嗎？", "拉斐爾")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我扶著牆緩慢回血的時候，身後傳來了一個熟悉聲音。 不會吧，拜託饒了我吧……")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("拉斐爾？ 妳怎麼……", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("莉琉沒告訴妳嗎？", "拉斐爾")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("如果我事先跟她說，她應該就更不想來了～", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉一邊像寵物商人看著商品一樣看著我，一邊輕描淡寫的說道。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("等一下小憐就要拜託妳囉～\\n「薩蒙頓執行代表」──拉斐爾·戴克斯小姐。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("哎？ ！拜託她？ ！", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉笑了笑，帶我們來到了「方舟基地」的入口。")
	novel_interface.show_character("anne_battle","worry")
	await novel_interface.show_dialog("就是……這裡？", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("郊外的路邊，混凝土結構的地下室入口，上面是僅允許單人通過的小門。")
	await novel_interface.show_text_only("周圍一公里內沒有任何建築物，若不是刻著SID的標誌，要說裡面可能住著奇怪大叔都不會有人懷疑。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("呵呵，進來就知道了──", "莉琉")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_elevator_overlook.png")
	await novel_interface.show_text_only("進門之後經過一條向下延伸的樓梯，我們進入了一台大型工業電梯。")
	await novel_interface.show_text_only("似乎是為了保證在極端環境下也能正常工作，電梯靠四個厚重的金屬絞輪驅動，結構異常堅固。")
	await novel_interface.show_text_only("電梯穩定下降，四周和底部都能聽到齒輪轉動的聲音。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_elevator.png")
	await novel_interface.show_text_only("昏暗燈光，排氣孔、金屬網和鉚釘，處處透露著老式工業風格。")
	novel_interface.show_character("raphael","worry")
	await novel_interface.show_dialog("這樣極致追求穩定性的設計……之前在紐摩利達斯中央銀行的地下金庫裡也見過。", "拉斐爾")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("那種地方妳也去過嗎？ ！", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("這裡可是戰前世界聞名的超級工程之一，修復起來可費了不少功夫。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉得意地說著。")
	await novel_interface.show_text_only("確實，雖然電梯在運行中，但就像踩在大鐵塊上一樣穩定，感覺就算在上面蹦跳也不會有任何震動。")
	await novel_interface.show_text_only("從暈車狀態恢復過來的我正想跳跳看，卻發現拉斐爾瞪了我一眼。")
	await novel_interface.show_text_only("我突然意識到自己看起可能有點傻，便立刻收斂並露出抱歉的表情，她卻不屑地轉頭看向觀察窗。")
	await novel_interface.show_text_only("……外頭一片漆黑，是能看到什麼……")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("妳幹嘛一直看著我？", "拉斐爾")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("欸？ 居然惡人先告狀！")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("呃……沒想到薩蒙頓會派妳來。", "小憐")
	await novel_interface.show_dialog("這次實驗不是危險性蠻高的嗎？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("更重要的是，就我所知，這次實驗有兩套劇本。")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("（我不知道妳拿到的是哪一本啊，大小姐！ ）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我無助地望向莉琉。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("表面上看來，這是新豐洲和薩蒙頓兩個學園都市的合作研究專案。", "莉琉")
	await novel_interface.show_dialog("目標是研究「空間異變」的成因並尋求解決方案。", "莉琉")
	await novel_interface.show_dialog("雙方都需要派出一個身分能力都合適，且值得信任的人作為實驗樣本。", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("新豐洲的人選當然是因為在天空酒店的一系列愚蠢行為而暴露了身分的妳──", "莉琉")
	novel_interface.character_dark()
	await novel_interface.show_text_only("莉琉用餘光掃向我，一股巨大的威嚴感讓我直冒冷汗。")
	await novel_interface.show_text_only("幹嘛這樣，我不是已經接受過懲罰了嘛……")
	novel_interface.character_light()
	await novel_interface.show_dialog("而貴族出身，現就讀於御櫻川的「普通人」拉斐爾則是自願代表薩蒙頓參加實驗的。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("……自願參加！ ？", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("哼，「青金石柱」是薩蒙頓重要的歷史文物，我可不想讓妳這個廢柴把實驗搞砸了。", "拉斐爾")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("拉斐爾擁有加速細胞自癒的能力，這一點愛衣已經驗證過了。", "莉琉")
	await novel_interface.show_dialog("不過按照貝阿特麗切的說法，想讓這種能力發揮到極大值，最好的媒介就是小憐。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我想起上次在天空酒店地下停車場，拉斐爾瞬間就治好了安妮的傷勢。")
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("所以說，拉斐爾是友軍囉！", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("哼，「啊～糟糕，撐不住了快幫我加血！ 」這種沒骨氣的話，確實跟妳很搭呢。", "拉斐爾")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("妳好像很期待看到這一幕似的！ ！", "小憐")
	novel_interface.change_expression("perspire1")
	await novel_interface.show_dialog("等等，這不是機密實驗嗎？ \\n拉斐爾為什麼……", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("當然是我向戴克斯博士提出的。", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("由於見證了你復活貝阿特利切的情景，他老人家覺得先前與元老院的合作的方向是錯誤的。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","bored")
	await novel_interface.show_dialog("是因為宗教？", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("應該沒這麼簡單──不過薩蒙頓暫時是傾向SID的，只要我們能確保拉斐爾的安全。", "莉琉")
	await novel_interface.show_dialog("而元老院並不清楚小憐和拉斐爾的真正能力，這是我們目前的優勢。", "莉琉")
	await novel_interface.show_dialog("已經成為「魔女」的人接觸其他魔導器就不會有任何效果，這也是我們的方案可以成立的前提。", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("還真是感謝雙方高層的配合了～", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("……妳確定我爺爺那個異想天開的傢伙，不是被妳刻意引導嗎？", "拉斐爾")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("拉斐爾，妳最好不要把妳爺爺想得太簡單了，他可不是隨便挑選這件文物的。", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("這樣安排也是為了讓「真正的實驗」能夠順利進行。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("嘖，要不是爺爺的命令……", "拉斐爾")
	novel_interface.character_dark()
	await novel_interface.show_text_only("拉斐爾含糊地嘟嚷了一句，眼神輕飄飄地掠過我。")
	novel_interface.character_light()
	await novel_interface.show_dialog("我才不要和這個女裝癖演戲呢！", "拉斐爾")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("可是戴克斯博士總說，家裡最不聽話的就是妳呀～", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("哼──", "拉斐爾")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("這麼看來，薩蒙頓其實是對青金石柱的原主人──海因里希感興趣？", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","smile")
	await novel_interface.show_dialog("加油啊，小憐！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("元老院想瞞著SID繼續和薩蒙頓進行人造魔女的研究，這次也想測試我作為「穩定器」的可能性。")
	await novel_interface.show_text_only("而薩蒙頓又瞞著元老院與莉琉達成了交易。")
	await novel_interface.show_text_only("然後，莉琉則是向元老院隱瞞了我和拉斐爾的狀況。")
	await novel_interface.show_text_only("這關係光想就頭痛……")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("（真的能好好配合嗎……）", "小憐")
	novel_interface.character_dark()
	await novel_interface.show_text_only("我偷偷看著這位面色不善的大小姐。")
	novel_interface.character_light()
	await novel_interface.show_dialog("（拉斐爾轉入御櫻川這件事……）\\n（難道也早就被設計好了？ ）", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("（看她這副蠢樣，又在想些有的沒的了吧。 ）", "拉斐爾")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("隨著咣噹一聲鎖定音響起，電梯終於停穩，\\n我們面前出現了一道高十公尺左右的金屬大門。")
	await novel_interface.show_text_only("一道紅色的掃描光從上而下掠過我的身體。 \\n門內發出了確認的響聲。")
	await novel_interface.show_text_only("莉琉接著上前，進行了二次虹膜識別。")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("雖然是很老派的保全措施，但好嚴格啊……", "小憐")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_corridor.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("隨著掃描結束，大門緩緩降下，露出門後讓人震撼的空間。")
	await novel_interface.show_text_only("色調冷冽的巨大地下空間中，兩排高達數十公尺的立柱延伸到遠處。")
	await novel_interface.show_text_only("每個混凝土立柱的底部都整齊貼著大量雙向反射式裝甲片。")
	await novel_interface.show_text_only("對外可以讓建築抵禦火箭筒級的火力，朝內部啟動的話，則能瞬間摧毀它們所包裹的結構。")
	await novel_interface.show_text_only("這種裝甲，在七年戰爭期間廣泛地用於需要封鎖或自毀的堡壘式建築中……")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("這裡似乎挺潮濕的……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("地上還有未乾的水漬，空中交錯排列著幾十條嶄新的管線，傳來液體流動的聲音。")
	await novel_interface.show_text_only("看來莉琉為了改造這裡，下了不少功夫啊……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我們一路走到通道的盡頭，看到一個完全由金屬甲板包裹的空間……")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_cistern.png")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("到了。", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("——歡迎來到「方舟基地」。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("居然──改造得這麼徹底！")
	await novel_interface.show_text_only("我們面前是一個幾十公尺寬的蓄水池，池中水光閃爍，感覺就像身處碼頭一樣。")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("——好好看著吧，「登船梯」第一次正式對接。", "莉琉")

	print("=== 深海恐惧篇第7话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
