# bathophobia_ep04.gd - 深海恐惧篇第04话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep04_script()

func play_script():
	pass

func bathophobia_ep04_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_lawn.png")
	await novel_interface.show_text_only("午後，我半躺在樹蔭下的草坪上，有些惆悵地看著天空。")
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("唉──", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一道陰影遮住了我的視線。")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("怎麼啦？ 小憐，唉聲嘆氣的。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","gratified")
	await novel_interface.show_dialog("是安妮啊……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮順勢在我旁邊坐了下來，手裡的紙袋放在膝蓋上。")
	novel_interface.show_character("ren_uniform","timid")
	await novel_interface.show_dialog("──好甜的香味！", "小憐")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","happy",0.25)
	await novel_interface.show_dialog("鏘鏘～～是新出爐的楓糖奶油餅乾唷～\\n要嚐嚐嗎？", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("雖然這麼問，但是已經動手拆開包裝的安妮並沒有等我回答，就直接將一塊餅乾塞進我嘴裡。")
	novel_interface.show_character("ren_uniform","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","happy",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("唔……（嚼）\\n還不錯嘛！", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("對吧！ 剛才路過家政教室的時候，聞到了超——香的味道，我就偷偷找人要了一袋～", "安妮")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("真好啊……安妮已經完全融入這裡了。", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("嗯？", "安妮")
	await novel_interface.show_dialog("小憐也很受歡迎啊～\\n不少同學都和我打聽妳的情況呢……", "安妮")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("哎？ 是這樣嗎？")
	await novel_interface.show_text_only("跟過去比起來，現在的我還真是桃花朵朵開耶……但這種時候根本高興不起來啊！")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("乖啦，因為莉琉小姐禁止我們透露個人資料……所以我什麼都沒講哦！", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮一邊咬著餅乾，一邊關心地看著我。")
	novel_interface.show_character("ren_uniform","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","smile",0.25)
	await novel_interface.show_dialog("……", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("心情不好嗎？", "安妮")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("總覺得自己無法安心地面對這種平靜的日常……", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("平靜不好嗎？", "安妮")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("好像有什麼重要的事，又不知從何開始，\\n這樣無所事事又覺得忐忑不安……", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("重要的事……？", "安妮")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("比如說，未來會怎樣……之類的。 \\n我現在這樣的身體又會變成怎樣──", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("噗嗤～", "安妮")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("唔啊——！ \\n妳居然笑我！ ！！")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_text_only("啊啊啊啊！我居然真的說出來了，好丟臉啊！！")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("因、因為班上的女生，都毫無顧忌地跟我聊各種話題……這樣很不好意思啊。", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("哦～所以妳才一個人躺在這裡？", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮的表情似乎很輕鬆。")
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("……有時候，我會不自覺地玩起自己的頭髮或調整內衣。", "小憐")
	await novel_interface.show_dialog("在執行任務的時候，也能很自然地換上短裙和高跟鞋……", "小憐")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("可是有時候會突然意識到，我怎麼會變成這樣呢？ ！", "小憐")
	await novel_interface.show_dialog("我、我可是男孩子啊……", "小憐")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","relieve",0.25)
	await novel_interface.show_dialog("男孩子也沒有問題啊！", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮語氣變得一本正經。")
	novel_interface.show_character("ren_uniform","perspire1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","relieve",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("什麼？", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("高跟鞋啊，最初就是路易十四發明的唷～", "安妮")
	await novel_interface.show_dialog("17世紀時，女性會開始穿上高跟鞋，是為了讓自己看起來更陽剛喔。", "安妮")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("穿上高跟鞋是為了……變得陽剛？", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("嗯～而且，蘇格蘭地區的男性可是會在正式場合穿短裙的！", "安妮")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("這個倒是有聽說過……", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("是啊，據說還不用穿內褲！", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我忍不住摸了摸自己的裙子。")
	await novel_interface.show_text_only("還好還好，我不是蘇格蘭人！")
	novel_interface.show_character("ren_uniform","perspire1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","normal1",0.25)
	await novel_interface.show_dialog("所以啦，小憐的打扮，明明就很有男子氣概！", "安妮")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("是、是這樣的嗎？", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("唔……至於內衣嘛……", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮的視線落在我胸口。")
	novel_interface.show_character("ren_uniform","shy_left")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("這種東西總不會有男子氣概了吧！")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("……我覺得挺像運動時的負重訓練用具。", "安妮")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("──啊？", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("是啊～只要把增加的重量當作掛在胸前的沙袋不就好了嗎？", "安妮")
	novel_interface.change_2nd_expression("shy")
	await novel_interface.show_dialog("雖然我是沒有這種煩惱啦……", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮有點失落地摸了摸自己。")
	novel_interface.show_character("ren_uniform","uneasy")
	await novel_interface.show_dialog("這樣，好像……也說得通。", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("才沒有啦！！")
	await novel_interface.show_text_only("妳以為我會被這種亂七八糟的話說服嗎？！")
	novel_interface.show_character("ren_uniform","uneasy")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","happy",0.25)
	await novel_interface.show_dialog("不管怎麼說，在我心中，小憐就是很棒的男孩子呢～", "安妮")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"shy")
	await novel_interface.show_text_only("我突然感覺臉頰一陣發燙。")
	await novel_interface.show_dialog("是、是嗎？？", "小憐")
	await novel_interface.show_dialog("（雖然感覺有點道理，但同時也覺得自己被唬弄了……）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看著安妮天真友善的笑容，我……還是相信她吧。")
	await novel_interface.show_dialog("真是無憂無慮啊，青春真好呢～", "莉琉")
	await novel_interface.show_text_only("莉琉的聲音突然從我的胸部傳出。")
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_dialog("呀──", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我嚇了一跳，趕緊左右張望後捂住胸口，深怕被發現。")
	await novel_interface.show_text_only("雖然愛衣安慰我說，時間久了就習慣了，但這種麻麻癢癢的感覺絕對沒有辦法習慣！！")
	await novel_interface.show_text_only("我從天空酒店回來後，好幾次要求把這塊奇怪的晶片取出來。")
	await novel_interface.show_text_only("直到莉琉威脅我，再吵就在課堂上當著全班同學用我的胸部播放下課鈴聲。")
	await novel_interface.show_text_only("這個惡魔！！嗚嗚嗚嗚……")
	await novel_interface.show_dialog("我可是為了妳們，好一陣子沒休息了。", "莉琉")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("難怪最近都沒有什麼任務呢～", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("哈、哈哈……\\n安妮還真是積極……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("要不是因為元老院那邊太難搞，老早就應該搞定的……", "莉琉")
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("哎？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉的聲音有些興奮。")
	await novel_interface.show_dialog("很快妳就會知道──", "莉琉")
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("搞什麼呀？ 神神祕祕的……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("先不說這個，馬上就到訓練時間了，妳們兩個還在這裡悠閒地談情說愛啊？", "莉琉")
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("不是還有半小時嗎……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("沒收到郵件通知嗎？ \\n最近妳的體能訓練課程增加了。", "莉琉")
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("什麼？妳又要折磨我了？！", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("可以預想之後無數個精疲力竭癱瘓在床的夜晚了……")
	await novel_interface.show_dialog("嘖，什麼折磨啊？", "莉琉")
	await novel_interface.show_dialog("妳的身體，早就屬於我了哦。", "莉琉")
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_text_only("不要說這種會讓人誤會的話啦！！！")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/spConferenceRoom.png")
	await novel_interface.show_text_only("莉琉面帶笑意地中斷了通訊。")
	await novel_interface.show_text_only("面對著冷冰冰的螢幕，她站姿挺拔。")
	await novel_interface.show_text_only("手持平板中的數據已傳送到螢幕背後的幾人面前。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("關於專案預算……", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("已經向市政部門申請徵用新東北地區G-cans周圍四十公里的無人區，統一由SID管理。", "莉琉")
	await novel_interface.show_dialog("相關預算為14.9億。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("……", "眾人")
	novel_interface.show_character("liliu_uniform2","speak")
	await novel_interface.show_dialog("重設管線、配置交通及保全設施，均採用V級軍事掩體標準。", "莉琉")
	await novel_interface.show_dialog("相關預算為6.2億。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("…………", "眾人")
	novel_interface.show_character("liliu_uniform2","speak")
	await novel_interface.show_dialog("並列改造地下洩洪口、全區屏蔽電磁波，還有特製的自律武器系統。", "莉琉")
	await novel_interface.show_dialog("相關預算為5.32億。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("………………", "眾人")
	novel_interface.show_character("liliu_uniform2","speak")
	await novel_interface.show_dialog("改造工期約為58天。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("元老院對這部分企劃沒有異議的話，SID就會立刻開始執行。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_taki")
	await novel_interface.show_dialog("……有點……太貴了……吧……", "華音瀧")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("這是三份開發報告中性價比最好的選擇。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("……", "基爾斯")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("我不介意終止這項計劃。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("不過，諸位的意見是……？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("……", "眾人")
	await novel_interface.show_text_only("眾人的沉默並不意味著否定。")
	await novel_interface.show_text_only("電磁噪音充斥著這個安靜的房間。")
	await novel_interface.show_text_only("——螢幕上逐步顯示出「確認」的字樣。")
	await novel_interface.show_text_only("直到所有人的影像下方都出現了「確認」。")
	await novel_interface.show_text_only("莉琉滿意地勾起嘴角。")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("那麼──「方舟計劃」啟動！", "莉琉")

	print("=== 深海恐惧篇第04话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
