# bathophobia_ep21.gd - 深海恐惧症篇第21话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep21_script()

func play_script():
	pass

func bathophobia_ep21_script():
	novel_interface.change_music("res://assets/audio/music/Barrier Maze.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Corridor.png")
	await novel_interface.show_text_only("Les silhouettes étranges qui surgissent soudain dans le couloir se dirigent droit vers nous.")
	await novel_interface.show_text_only("Ils sont totalement silencieux, à part le bruit des tissus bruissants et les bruits de pas. Ont-ils même besoin de respirer ?")
	await novel_interface.show_text_only("Je serre fermement mon arme, me préparant mentalement. C’est alors que de puissants faisceaux de lumière jaillissent de la combinaison de combat d’Henriette. Elle disparaît de la vue en un éclair, ne laissant derrière elle qu'un pouf de fumée brillante.")
	await novel_interface.show_text_only("Alors que j'étais encore abasourdi, Heinrich avait déjà esquivé devant une personne et frappé l'une des femmes sur le plastron avec le dos de son épée en lapis-lazuli.")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("Ouah, elle a des mouvements !","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Le bruit fort et étouffé de son arme frappant sa cible résonne sur les murs du couloir. Je jure que j'ai mal à la poitrine rien qu'en l'entendant.")
	await novel_interface.show_text_only("Sa cible tombe au sol comme une marionnette en bois et roule au loin.")
	await novel_interface.show_text_only("N'importe quel humain aurait instinctivement réagi pour se protéger d'autres blessures, mais cette marionnette ne fait rien de tel.")
	await novel_interface.show_text_only("Une fois qu'elle arrête de rouler, elle bondit simplement, la poitrine bosselée et tout, et revient sur nous.")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("…!","Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Comprenant qu'il ne s'agit pas d'ennemis ordinaires, Henriette se retourne et transperce les talons de trois d'entre eux à la vitesse de l'éclair.")
	await novel_interface.show_text_only("Les trois, les tendons coupés, s'effondrent sur le sol, mais ils continuent de ramper vers nous dans des mouvements étrangement silencieux et spasmodiques.")
	await novel_interface.show_text_only("Ils n’ont pas l’air si effrayants à première vue, mais le fait qu’ils présentent des caractéristiques distinctement non humaines est pour le moins très troublant.")
	await novel_interface.show_text_only("Ils ont l'air humains. Ils n’agissent pas comme des humains. C'est effrayant comme l'enfer.")
	await novel_interface.show_text_only("Après avoir confirmé que les ennemis ne constitueront plus une menace, Rapha?l avance pour tenter de voir quel est leur problème.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Soudain, le sol se remet à trembler.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Second_Earthquake.png")
	await novel_interface.show_dialog("Un autre tremblement de terre ?","Henriette")
	await novel_interface.show_text_only("Cette fois, le séisme est plus intense et dure beaucoup plus longtemps.")
	await novel_interface.show_text_only("Parallèlement aux tremblements, les lumières du couloir clignotent, suivant ce qui ressemble à des cris stridents – ou peut-être à un coup sec sur du métal.")
	await novel_interface.show_text_only("Les ennemis au sol semblent se transformer en liquide transparent... ? Mousse? Juste sous nos yeux.") #换行问题
	await novel_interface.show_text_only("Le liquide commence alors à bouillir et à bouillonner, comme s'il se trouvait sur une planche de teppanyaki. En quelques secondes, ce qui était autrefois des figures de forme humaine s’était évaporé dans le néant.")
	await novel_interface.show_text_only("Ils ne laissent aucune trace sur les lames froides du parquet. C’est comme si ces filles bizarres n’avaient jamais existé.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Reference_Room_Old.png")
	await novel_interface.show_text_only("Notre environnement semble également avoir changé après le tremblement de terre.")
	await novel_interface.show_text_only("Les ornements en bois de la salle des archives se sont effondrés, n’étant plus que de la sciure de bois flottant dans l’air. La peinture des murs s’est également écaillée.")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("... Hein ?","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("C'est toujours la même salle d'archives...")
	await novel_interface.show_text_only("Mais les lumières sont éteintes. Les carreaux au sol ne brillent plus. Et les articles sur l’étagère – disposés complètement différemment.")
	await novel_interface.show_text_only("Derrière les épaisses poutres en acier d’aspect industriel, une autre caméra de surveillance à détection sonore pointait vers nous sa lentille sombre.")
	await novel_interface.show_text_only("Au mur se trouve une carte topographique détaillée de l’Antarctique et sur le bureau un carnet enregistrant les changements dans les données atmosphériques.")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("Qu'est-ce que... qu'est-ce que c'est ?","Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","perspire")
	await novel_interface.show_dialog("Ce que nous venons de voir... était-il une illusion ?","Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("Ces filles fantoches aussi ?","Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Henriette regarde son arme – pas tachée de sang, même si elle devrait l'être. Elle lève ensuite les yeux vers l'endroit où nos agresseurs soudains se sont apparemment évaporés.")
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("Peut-être que ce dans lequel nous étions... n’était pas le monde réel.","Henriette")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Heinrich fut soudainement interrompu par la voix de Li Tong.")
	await novel_interface.show_dialog("Enfin ! Une connexion!","Mariru")
	await novel_interface.show_text_only("La voix de Mariru résonne depuis... dans ma poitrine ?")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("Hé, Mariru ! Qu'est-ce qui se passe avec le signal ?","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru fredonne, semblant épuisé. Pendant ce temps, Henriette regarde ma poitrine avec horreur, ne sachant pas pourquoi la voix de Mariru vient de là.")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("(Hé, c'est un malentendu, je le jure !)","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("En voyant mon expression, Henriette hoche la tête, comme si elle comprenait, et commence également à palper ses propres seins.")
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("(chuchotant) Est-ce que Maître... a modifié mon corps de cette façon aussi ?","Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_text_only("Bien sûr que non ! Et pourquoi aviez-vous l’air d’être enthousiasmé par cela ?")
	await novel_interface.show_dialog("Hé, au fait, pourquoi ne nous avez-vous pas contacté avec le talkie-walkie ?\\nEst-ce que Annie est d'accord ?","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Le satellite de communication est désormais en position. Annie collecte des informations sur les sources des fuites de méthane. Comment ça se passe là-bas ?","Mariru")
	await novel_interface.show_text_only("Je fais de mon mieux pour mettre de l’ordre dans mes pensées et rapporter tout ce que nous avons rencontré après être entré dans la base de la manière la plus concise possible.")
	await novel_interface.show_dialog("... \\n(Pas le monde réel, hein... )","Mariru")
	await novel_interface.show_dialog("Attends une seconde, laisse-moi vérifier l'heure.","Mariru")
	await novel_interface.show_dialog("Huit minutes se sont écoulées depuis votre dernier contact avec Annie à la porte de la base.","Mariru")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("... Juste huit minutes ?","Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","perspire",0.25)
	await novel_interface.show_dialog("Cela n’aurait-il pas dû durer au moins quarante minutes ?","Raphael")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Comme s'il réalisait quelque chose, Mariru commence à taper.")
	await novel_interface.show_dialog("Un destroyer de classe Lebona patrouillant dans l'océan Antarctique vient de recevoir une sorte de signal basse fréquence.","Mariru")
	await novel_interface.show_dialog("Je pensais que c'était à cause d'une réplique, mais vu la situation actuelle...","Mariru")
	await novel_interface.show_text_only("Mariru appelle son système EEG et réexécute une analyse de modèle.")
	await novel_interface.show_dialog("Exactement comme je m'y attendais...","Mariru")
	await novel_interface.show_dialog("Ce signal... a le même schéma que les ondes cérébrales pendant le sommeil paradoxal humain...","Mariru")
	await novel_interface.show_dialog("... Mais soixante-deux fois plus intense.","Mariru")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("... Vous plaisantez ?","Raphael")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("Tu veux dire que nous étions en train de rêver à l'instant ?","Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("Le temps ralentit quand on rêve, c'est vrai...","Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("heinrich_battle","normal",0.25)
	await novel_interface.show_dialog("Les rêves reflètent des souvenirs. Et ce qui vient de se passer..., cela ressemblait en effet à une recombinaison de différents fragments de mémoire.","Henriette")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Si c'était un rêve, alors c'était définitivement un cauchemar...","Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Je me souviens soudain de ce film que j’ai regardé, où les personnages utilisaient des totems pour dire s’ils étaient en rêve ou non. J'aurais aimé en avoir un.")
	await novel_interface.show_dialog("... Peut-être que ce n'était pas vous qui rêviez. Vous avez peut-être été dans le rêve de quelqu’un d’autre.","Mariru")
	novel_interface.show_character("ren_battle","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("heinrich_battle","serious",0.25)
	await novel_interface.show_dialog("Le rêve de quelqu'un d'autre... ?","Henriette")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Bien sûr, tout cela ne sont que des spéculations qui ne font que m’énerver encore plus. Je remarque que c'est un peu bruyant du côté de Mariru – on dirait que beaucoup de gens sont occupés à travailler autour d'elle.")
	novel_interface.show_character("ren_battle","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("heinrich_battle","serious",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Au fait, à quoi ressemble... là-bas ?","Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru reste silencieuse pendant un moment, comme si elle essayait de décider ce qu'elle veut révéler.")
	await novel_interface.show_dialog("C'est un peu plus... compliqué que prévu.","Mariru")
	await novel_interface.show_dialog("Le Congrès américain discute actuellement de la manière de résoudre le problème des fuites de méthane. Mais vous savez à quoi ressemblent leurs gens. Impossible qu’ils soient capables de faire face à un événement de niveau apocalypse comme celui-ci.","Mariru")
	await novel_interface.show_dialog("Le Dr Deckers de Salmonton a proposé un plan pour utiliser les archées méthanophiles...","Mariru")
	await novel_interface.show_dialog("Mais il n’y en a pas beaucoup actuellement en stock, surtout pas ceux qui peuvent survivre au froid. Et il est trop tard pour cultiver davantage à partir de zéro.","Mariru")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("De plus, les bactéries anaérobies ne peuvent pas vraiment faire grand-chose dans notre atmosphère car l’oxygène les tue.","Raphael")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Donc même grand-père est perplexe, hein...","Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","bored")
	await novel_interface.show_dialog("(Je n'ai aucune idée de ce dont ils parlent...)","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Actuellement, la plupart des stations de recherche de moyenne et petite taille sont en cours d'évacuation, même si une équipe d'urgence temporaire a déjà été mise en place par les trois principales bases antarctiques.","Mariru")
	await novel_interface.show_dialog("Jusqu’à présent, quarante-deux sources de fuites de méthane ont été identifiées dans le cercle Antarctique. Six d’entre eux sont déjà incendiés, et les photos de ces sites se répandent actuellement comme une traînée de poudre sur Internet.","Mariru")
	await novel_interface.show_dialog("Et sur les chaînes d’information aussi. Tous les téléviseurs du monde diffusent probablement désormais en boucle des images de flammes crachant des fissures dans les plaines de glace polaires, s'élevant à des dizaines de mètres de haut.","Mariru")
	await novel_interface.show_dialog("Il n’y a aucun moyen pour eux de garder cela secret plus longtemps. Le monde le sait, et ils paniquent clairement – ​​certains organisent déjà des célébrations : un dernier hourra avant la fin du monde.","Mariru")
	await novel_interface.show_text_only("Les mots de Mariru sont cyniques, son ton impuissant.")
	await novel_interface.show_dialog("Les sites de fuites sont concentrés à proximité de plusieurs lacs libres de glace et dans la région du mont Erebus, sur l'île de Ross.","Mariru")
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("... Mont Erebus ? C'est un volcan.","Henriette")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Quant à la station de recherche Princess Elisabeth Antarctica proche de chez vous, deux petits incendies se sont déjà déclarés à cause des fuites de méthane.","Mariru")
	await novel_interface.show_dialog("Il y a aussi un incendie allumé par un groupe de membres riches et sans cervelle du groupe touristique de Mt. Grove qui jouaient avec des lance-flammes. Des idiots.","Mariru")
	await novel_interface.show_dialog("Au moins, la base de Snedronningen ne court aucun danger immédiat pour le moment.","Mariru")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("Ouf…","Lian")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("(Bien. Au moins, nous ne risquons pas encore d'être frits....)","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("... Cependant, la station McMurdo a détecté une activité de coulée de lave à grande échelle sous les fissures.","Mariru")
	await novel_interface.show_dialog("La fissure près de la base de Snedronningen est la plus importante, et les calottes glaciaires qui l'entourent deviennent de plus en plus instables à une vitesse alarmante.","Mariru")
	await novel_interface.show_text_only("Je ne peux m’empêcher de regarder les planches métalliques sous mes pieds.")
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("(Donc on va quand même se faire frire, hein...)","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Un bruit soudain et aigu déchira l’air. Ma poitrine vibre, et l’instant d’après, nous sommes déconnectés.") #换行问题
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("Flammes jaillissant du sol, lave qui coule, suie volcanique mortelle...","Henriette")
	await novel_interface.show_dialog("C'est trop similaire à ce qui s'est passé il y a environ quatre cents ans...","Henriette")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("Ce sont tous des précurseurs de l'effondrement de la « substance primordiale ».","Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("Vous voulez dire ce qui s'est passé en 1600 ?","Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("C’était dans la Septième Particule, la Terre d’Abondance : le District du Gouverneur du Pérou.","Henriette")
	await novel_interface.show_dialog("Je n'oublierai jamais la mer de feu, l'odeur âcre du soufre dans l'air...","Henriette")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Henriette s'en souvient, l'air amer, et je ne peux m'empêcher d'être affecté, car j'ai vécu une expérience très similaire aussi.")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("Alors... est-ce que tout cela a à voir avec ce mec « The One » dont vous avez parlé ?","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Henriette hoche la tête.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Ampthitheatre.png")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	await novel_interface.show_dialog("À l’époque, mes amis du Rosenkreuzer et moi collectionnions trois livres mystiques : le Livre du Chariot, le Livre de la Création et le Livre de la Lumière.","Henriette")
	await novel_interface.show_dialog("En suivant les instructions des livres, nous avons réalisé la plus grande réussite jamais réalisée en alchimie : créer un « portail » qui pourrait nous amener dans le royaume karmique.","Henriette")
	await novel_interface.show_dialog("Étant naïfs, nous croyions honnêtement que le portail nous mènerait à un suzerain bienveillant et omnivoyant, qui nous montrerait toutes les vérités du monde.","Henriette")
	await novel_interface.show_dialog("... Mais il y a en fait une raison pour laquelle les règles « ne passent pas par le portail » et « ne recherchent pas la vérité » existent...","Henriette")
	await novel_interface.show_dialog("Car une fois que vous aurez franchi le portail, vous ne trouverez jamais la sortie.\\nEt une fois que vous aurez découvert la vérité, elle restera gravée à jamais dans votre esprit.","Henriette")
	await novel_interface.show_dialog("Les humains ne sont capables que de comprendre le langage.","Henriette")
	await novel_interface.show_dialog("Tout ce qui ne peut être décrit par le langage nous dépasse.","Henriette")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Reference_Room_Old.png")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("C’est une philosophie inventée par quelqu’un au 20e siècle.","Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("Ah ? Quelqu'un est arrivé à cette conclusion simplement en philosophant... ?","Henriette")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("Cette personne a donc dû souffrir beaucoup.","Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("Bien sûr. Toute sa famille était considérée comme des fous.","Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("Ouais. Il devait être un homme sage. Sauf que ce genre de sagesse sert simplement à ronger votre ego jusqu’à ce que vous en deveniez partie intégrante, si craintif, si désespéré.","Henriette")
	await novel_interface.show_dialog("Moi aussi, j’ai fait partie de ce processus à une époque. Et c'est à ce moment-là que The One est apparu devant moi...","Henriette")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("Sans dire un mot, il m'a fait choisir.","Henriette")
	await novel_interface.show_dialog("Est-ce que je veux disparaître, comme une goutte dans l’océan ?","Henriette")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("Ou devenir une simple goutte dans une bouteille, préservée pour l’éternité, existant en tant que gardienne de l’Arbre de Vie ?","Henriette")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Reference_Room_Old.png")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("…","Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("Ils vous ont ciblé quand vous étiez le plus faible...","Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("Et le soi-disant Arbre de Vie, ce n’est pas ce qu’on prétend, n’est-ce pas ?","Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Henriette sourit, un peu triste.")
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("... C'est une sorte de sceau.","Henriette")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Les dix Sephiroth de l'Arbre de Vie agissent comme un sceau qui maintient à distance un être indescriptible – redouté même par The One.","Henriette")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("Cependant, je ne sais pas ce qu’est exactement cet être.","Henriette")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Peut-être que je devrais être soulagé de ne pas le faire.","Henriette")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Henriette fait une pause.")
	novel_interface.character_light(0.35,"bored")
	await novel_interface.show_dialog("(Dans le cratère d'Enaptina, qui semble sur le point de tout brûler) \\n (J'y ai goûté une fois...)","Henriette")
	await novel_interface.show_dialog("L'Un n'a jamais dit explicitement ce qu'il voulait, mais il n'est pas difficile de dire de quoi il s'agit d'après la façon dont notre terre a changé...","Henriette")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elle rit, sans humour.")
	await novel_interface.show_text_only("Un silence inquiet s’installe sur nous aux paroles d’Henriette.")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("... Attendez !","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Je sors le chromatographe en phase gazeuse et montre les chiffres dessus.")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("Même si nous sommes actuellement dans un « rêve », la « réalité » ici n’est-elle pas encore différente de celle d’autres endroits ?","Lian")
	await novel_interface.show_dialog("Vous voyez, le niveau de méthane près de la fissure à l’extérieur de la base monte en flèche, déjà supérieur à 25 %. Mais ici-bas, le niveau de méthane est encore bien inférieur à cela...","Lian")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("N'est-ce pas contradictoire ? Et nous ne l’avons même pas remarqué !","Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("Attends, qu'est-ce que tu veux dire ?","Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("Vous l’avez sûrement tous entendu depuis notre entrée dans la base. Le—","Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","perspire")
	await novel_interface.show_dialog("Le système de ventilation ?","Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("Ouais. Quelque chose dans la base doit l'héberger, empêchant le méthane de se répandre ici.","Lian")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Oh, c'est vrai, Mariru ne nous a-t-il pas envoyé un plan de la base avant de partir ?","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Rapha?l déplie immédiatement la carte et la pose sur le bureau.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("…")
	novel_interface.show_background("res://assets/images/bg/Baizhu/Snowstorm.png")
	await novel_interface.show_text_only("Il y a une heure, il n'y avait que de la neige, silencieuse, belle. Et maintenant, il y a du vent. Perçants, hurlants, comme des lames brillantes.")
	await novel_interface.show_text_only("Le continent de glace, autrefois enveloppé de ténèbres, est désormais une terre d’un blanc impitoyable.")
	await novel_interface.show_text_only("Le blizzard est arrivé.")
	
	print("=== 深海恐惧症篇第21话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
