# bathophobia_ep22.gd - 潜渊症篇第22话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep22_script()

func play_script():
	pass

func bathophobia_ep22_script():
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Reference_Room_Old.png")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("... Nessun segnale qui. Affatto.","Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("Questo significa che siamo di nuovo in quel “sogno”?","Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("In ogni caso, il sistema di ventilazione funziona ancora a pieno regime. Possiamo sentire il rumore dei ventilatori anche dal condotto di aerazione nella stanza dell'archivio.")
	await novel_interface.show_text_only("Secondo la mappa, questa base, nonostante sia stata costruita molto tempo fa, è stata costruita rigorosamente in conformità con gli standard delle organizzazioni top-secret.")
	await novel_interface.show_text_only("L'accesso tra le sezioni è rigidamente limitato. E ci sono innumerevoli unità indipendenti, separate da barriere in lega rinforzata.")
	novel_interface.show_character("heinrich_battle","worry")
	await novel_interface.show_dialog("La mappa non dice cosa fa la maggior parte di queste stanze. Dovremmo cercarli tutti?","Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("Questo è... così complesso...","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ci vorrebbero ore per setacciare l'intero posto. Comodini, non abbiamo nemmeno idea di cosa stiamo cercando.")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("E potrebbero esserci altri folli nemici in agguato dietro gli angoli.","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Quelle strane pupazzette in cui ci siamo appena imbattuti... solo a pensarci mi vengono le palpitazioni al cuore.")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("Beh, io per primo mi rifiuto di essere solo un bersaglio facile!","Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphael sbatte il pugno sulla scrivania, sollevando una nuvola di polvere.")
	await novel_interface.show_text_only("La telecamera di sorveglianza con rilevamento del suono dietro la trave metallica regola leggermente la sua angolazione in caso di rumore improvviso.")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("…","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Forse è il momento giusto per porre la domanda che mi perseguitava da quando ero alla stazione di rifornimento.")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("Ehi, tu... riesci a percepire di che materiale è fatto qualcosa?","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La ragazza bionda sorride alla mia domanda.")
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("Naturalmente. È un'abilità di base per tutti gli alchimisti di Rosenkreuzer.","Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("Quindi se... ci fosse un filo metallico isolato davvero molto lungo, saresti in grado di seguirlo fino in fondo e trovare dove porta?","Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("Se posso toccarlo, dovrei essere in grado di farlo.","Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("Vuoi dire...","Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Faccio un cenno a Raphael. Insieme, ci voltiamo e fissiamo l'angolo buio della stanza...")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Red_Dot.png")
	await novel_interface.show_text_only("Dove il punto rosso di luce lampeggia ritmicamente dentro e fuori dalla vista, come se avesse un battito.")
	await novel_interface.show_text_only("La telecamera di sorveglianza con rilevamento del suono.")
	await novel_interface.show_text_only("Nella vasta base sotterranea dovrebbero esserci un sacco di questi dispositivi.")
	await novel_interface.show_text_only("Il che dovrebbe portare tutto a un unico posto:")
	await novel_interface.show_dialog("La sala di controllo.","Lian")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Dispatched_Ship_Aisle.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("... La bufera di neve ha interrotto il segnale?","Mariru")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Il chip GPS di Ren non trasmette più.")
	novel_interface.character_light()
	await novel_interface.show_dialog("Se le comunicazioni venissero perse in questa misura, anche le missioni in aree coperte da particelle cariche ad alta energia ne risentirebbero, giusto?","Mariru")
	novel_interface.change_expression("sigh")
	await novel_interface.show_dialog("Voi ragazzi dell'SRD dovete migliorare il vostro gioco.","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru alza gli occhi al cielo verso Aya, che tira fuori la lingua.")
	novel_interface.show_character("liliu_uniform1","sigh")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","blush_wink",0.25)
	await novel_interface.show_dialog("Beh, dopotutto siamo al Polo Sud. Naturalmente qui le condizioni sono diverse.","Ai")
	novel_interface.change_2nd_expression("blush_stare")
	await novel_interface.show_dialog("Tuttavia, perdere il segnale in quel momento... non è assolutamente possibile che i nostri dispositivi siano così inutili.","Ai")
	novel_interface.character_light(0.35,"serious")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Vuoi dire che ci sono... altri motivi che causano la disconnessione?","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"blush_dizzy")
	await novel_interface.show_dialog("Sì. Non so cosa sia, ma deve essere potente... \\nSono sicuro che invidio chiunque ci sia dietro questo...","Ai")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru fissa pensieroso il dispositivo che ha in mano e la parola lampeggiante, DISCONNESSO, sullo schermo.")
	await novel_interface.show_text_only("Nel frattempo, Aya osserva il volto di Mariru.")
	novel_interface.show_character("liliu_uniform1","serious")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ai","think",0.25)
	await novel_interface.show_dialog("Sembri il proprietario di un animale domestico preoccupato per il suo gattino in fuga.","Ai")
	novel_interface.character_light(0.35,"sigh")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ad ogni modo, non possiamo fare altro che aspettare.","Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Aya espira, girandosi verso la finestra.")
	novel_interface.show_character("liliu_uniform1","sigh")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ai","normal",0.25)
	await novel_interface.show_dialog("Altitudine 37.000 metri sul livello del mare. È come se fossimo già nello spazio.","Ai")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Se andiamo ancora più in alto, il nostro radar e le comunicazioni smetteranno di funzionare.","Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru lancia un'occhiata alla postazione di lavoro della loro macchina, dove oltre trenta operatori dell'intelligence sono impegnati a smistare i dati che arrivano da tutti gli angoli del mondo.")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("Questa nave da trasporto pesante ad alta velocità... \\nCi tieni agli occhi da un po', eh?","Ai")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("Ah. Il Senato ha sicuramente delle cose interessanti nascoste.","Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("Altre tre ore prima di raggiungere l'Antartide...","Ai")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("Se una qualsiasi parte del corpo di Ren si rompesse, saremmo in grossi guai.","Ai")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Notando Aya che si mordeva le unghie con ansia, Mariru le batte le nocche dietro la testa.")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("Ehi.","Mariru")
	await novel_interface.show_dialog("Chi pensavi che avesse addestrato quei ragazzi?","Mariru")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Tunneling.png")
	await novel_interface.show_text_only("<Base di Snedronningen>")
	await novel_interface.show_text_only("Seguendo le indicazioni di Henriette, tracciamo il cavo collegato al dispositivo di sorveglianza fino alle profondità della base.")
	await novel_interface.show_text_only("Qui i corridoi sono sempre più stretti. Le pareti sono spoglie, come se la costruzione non fosse ancora completata.")
	await novel_interface.show_text_only("I nostri passi risuonano sulle pareti del tunnel. Strisciante. Troppo inquietante. Posso sentire il cuore che mi martella nel petto.")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("…","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Questo non è il momento adatto per questo, ma...")
	await novel_interface.show_text_only("Ma più mi innervosisco, più diventa difficile trattenerlo...")
	await novel_interface.show_text_only("Mi fermo di colpo, alzo una mano.")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("Ehi…","Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","stare",0.25)
	await novel_interface.show_dialog("E adesso?","Raphael")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Posso...","Lian")
	await novel_interface.show_dialog("Vai al... bagno?","Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Eccomi qui, in un tunnel apparentemente infinito senza porte o biforcazioni, con due ragazze. E sto chiedendo di andare in bagno. Voglio saltare da un dirupo.")
	novel_interface.show_character("ren_battle","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("raphael","perspire",0.25)
	await novel_interface.show_dialog("…","Raphael")
	novel_interface.change_2nd_expression("subtle")
	await novel_interface.show_dialog("Ti rendi almeno conto della gravità della situazione?","Raphael")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Sono... Mi dispiace! Non posso farci niente, ok?","Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Stringo ancora di più le cosce, cercando di guardare ovunque tranne che verso il volto chiaramente disgustato di Raphael.")
	novel_interface.show_character("ren_battle","shy_left")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("raphael","subtle",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("(Più divento nervoso, più mi dico di non pensarci, peggio mi sento... )","Lian")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Sono così vicino a pisciarmela addosso...")
	novel_interface.character_light(0.35,"sob")
	await novel_interface.show_dialog("(Cosa ho fatto per meritarmi questo?)","Lian")
	await novel_interface.show_dialog("Uh, se uno di voi due avesse una bottiglia di plastica o qualcosa del genere, potrei...","Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("... Eh?","Raphael")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Uffa, di cosa sto parlando?")
	await novel_interface.show_text_only("Raphael mi vedeva come un pervertito, ma ora... probabilmente mi vede come spazzatura.")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("Vuoi qualcosa per trattenere la pipì, eh, Maestro? Beh, potrei provare a forgiare dei materiali...","Henriette")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Henriette sembra divertirsi un po' troppo.")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("Andiamo! Sai che non è quello che intendo!","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Vedendo la disperazione nei miei occhi, l'alchimista finalmente ha pietà di me e fa un buco della giusta misura nelle pareti del tunnel.")
	await novel_interface.show_text_only("Dietro il muro c'è quello che sembra un alloggio per i lavoratori: buio, ammuffito e, soprattutto, dotato di bagno.")
	await novel_interface.show_text_only("Viva l'alchimia!")
	await novel_interface.show_text_only("Mi infilo subito nel buco, non voglio più restare sotto gli occhi scrutatori di Raphael.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("La temperatura sembra essere più bassa qui. C'è un sottile strato di ghiaccio sulle pareti e posso vedere i miei respiri uscire in sbuffi bianchi.")
	await novel_interface.show_text_only("Con la luce proveniente dai tunnel riesco a leggere il termometro a mercurio sul muro. Dice meno trentadue gradi.")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("(Ehi, in tal caso, la mia pipì sarà congelata non appena uscirà?)","Lian")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("(Probabilmente non... giusto?)","Lian")
	await novel_interface.show_dialog("(ma...)","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("…")
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Base_Tunneling.png")
	await novel_interface.show_text_only("Finalmente torno nel tunnel, arrossendo furiosamente.")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("Perché ci hai messo così tanto tempo?","Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("Hai la faccia tutta rossa.","Henriette")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Tutto il potere della tua Fire Jade è stato consumato? Ne hai bisogno di uno nuovo?","Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("No, no, va bene!","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mi spiace, Henriette... \\nQuesta Fire Jade... non lascerò assolutamente che qualcuno la tenga adesso!")
	await novel_interface.show_text_only("La vescica non mi uccide più, seguo felicemente Henriette e Raphael mentre continuiamo a camminare lungo la direzione dei cavi.")
	await novel_interface.show_text_only("Cerco di ricordare quello che ho appena visto negli alloggi dei lavoratori. Su un tavolo c'era mezza bottiglia di Vodka e sulle pareti del ghiaccio scuro.")
	await novel_interface.show_text_only("Mi sembrava di aver preso a calci un oggetto metallico mentre camminavo nel buio... \\nSono bossoli di proiettile?")
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("No, no. Deve essere stata la mia immaginazione.","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Osservo ciò che mi circonda. Le pareti del tunnel di cemento sono per lo più nude, ad eccezione di un paio di piastrelle.")
	await novel_interface.show_text_only("Attendi... riquadri? Se questo posto fosse stato in costruzione come pensavo, le piastrelle non sarebbero state posizionate in modo così casuale.")
	await novel_interface.show_text_only("Ma quale forza ha staccato l’intera parete interna del tunnel? ?")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_text_only("(Ecco... cosa è successo esattamente.)")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Finalmente raggiungemmo la porta della sala di monitoraggio. Sembrava che la maniglia della porta inceppata non fosse stata girata da molto tempo.")
	await novel_interface.show_text_only("Ciò non scoraggia Henriette. Quel mostro rompe semplicemente la maniglia, la serratura e tutto il resto.")
	await novel_interface.show_text_only("La porta della sala di monitoraggio si apre cigolando...")
	novel_interface.show_character("heinrich_battle","shout")
	await novel_interface.show_dialog("—Attento!","Henriette")
	
	print("=== 潜渊症篇第22话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
