# bathophobia_ep04.gd - 深海恐惧篇第04话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep04_script()

func play_script():
	pass

func bathophobia_ep04_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_lawn.png")
	await novel_interface.show_text_only("On the grass in the shade, I stare up at the afternoon sky in a gloomy daze.")
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("Ugh—", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("A shadow suddenly blocks my view.")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("What's wrong, Ren? What's bothering you?", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","gratified")
	await novel_interface.show_dialog("Hi, Annie…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Annie sits down beside me and sets a paper bag on her knees.")
	novel_interface.show_character("ren_uniform","timid")
	await novel_interface.show_dialog("—It smells so sweet!", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","happy",0.25)
	await novel_interface.show_dialog("Ta-dah! Freshly baked maple cream cookies! \\nWanna have one?", "Annie")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Having asked me, she doesn't seem to expect any rejection and pushes a cookie into my mouth.")
	novel_interface.show_character("ren_uniform","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","happy",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Umm… (Chewing) \\nYummy!", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("I know, right? I passed by a home economics class and it smelled amazing, so I asked someone to sneak me a bag.", "Annie")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("It's nice... seeing you really become part of school life, Annie.", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("Hmm?", "Annie")
	await novel_interface.show_dialog("Ren, you are very popular, too. \\nMany classmates have asked me about you…", "Annie")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("Really?")
	await novel_interface.show_text_only("My luck with romance is way better than when I was a boy!")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("But Ms. Mariru doesn't allow us to leak our personal information… So I never told anyone about you!", "Annie")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Annie looks at me attentively while eating the cookies.")
	novel_interface.show_character("ren_uniform","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","smile",0.25)
	await novel_interface.show_dialog("…", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("You don't feel good?", "Annie")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Such a peaceful life kind of makes me uneasy…", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("Isn't it good for you?", "Annie")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("It's like I have something important to do but don't know where  to start. \\nThe fact that we have nothing to do now makes me jittery…", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("Something important?", "Annie")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Let's say, what the future would be like… Things like that. \\nAnd my body—", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("Haha—", "Annie")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("Hmm—! \\nYou think this is funny!!")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_text_only("It's so embarrassing to say this!!!")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("A... a lot of girls in class talk to me openly about all this girl stuff... and I just feel awkward.", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("I see. So that’s why you are here alone?", "Annie")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Annie looks at ease.")
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("Yes. Sometimes I would unconsciously fiddle with my hair, or adjust my underwear.", "Lian")
	await novel_interface.show_dialog("And when heading out for a mission, I would naturally put on a skirt and high heels…", "Lian")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("But the moment I realized what I have done, I would be like: “Gosh, how could I do this?\"", "Lian")
	await novel_interface.show_dialog("I… I'm a boy…", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","relieve",0.25)
	await novel_interface.show_dialog("Boys can do that too.", "Annie")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Annie suddenly sounds serious.")
	novel_interface.show_character("ren_uniform","perspire1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","relieve",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("What?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("High heels were invented by Louis XIV.", "Annie")
	await novel_interface.show_dialog("And in the 17th century, women started to wear high heels to make themselves look masculine.", "Annie")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("High heels were meant for… masculinity?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("And Scottish men wear kilts on formal occasions!", "Annie")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("I've heard that one...", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("Uh-huh… It's said they don't even wear underpants!", "Annie")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Without thinking, I patted my skirt.")
	await novel_interface.show_text_only("Thank goodness I'm not a Scot!")
	novel_interface.show_character("ren_uniform","perspire1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","normal1",0.25)
	await novel_interface.show_dialog("So, Ren, you look very manly!", "Annie")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Do… do I?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Hmm… And the underwear…", "Annie")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Annie's eyes turn to my chest.")
	novel_interface.show_character("ren_uniform","shy_left")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("S… see! These two are in no way manly!")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("… I think they are similar to weight training equipment.", "Annie")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("—Huh?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("Exactly! Just think of them as sandbags.", "Annie")
	novel_interface.change_2nd_expression("shy")
	await novel_interface.show_dialog("I wish I could have these sweet burdens…", "Annie")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Annie sadly touches her chest.")
	novel_interface.show_character("ren_uniform","uneasy")
	await novel_interface.show_dialog("That... actually sounds kind of reasonable.", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("—No way!")
	await novel_interface.show_text_only("You think I'll buy this?")
	novel_interface.show_character("ren_uniform","uneasy")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","happy",0.25)
	await novel_interface.show_dialog("Anyway, Ren, I think you're a very good boy!", "Annie")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"shy")
	await novel_interface.show_text_only("My face is burning.")
	await novel_interface.show_dialog("Y-You do?", "Lian")
	await novel_interface.show_dialog("(She sounds sensible, but I still feel tricked…)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Annie looks innocent and sincere, so… I choose to trust her.")
	await novel_interface.show_dialog("Youth really is carefree.", "Mariru")
	await novel_interface.show_text_only("Mariru's voice suddenly came out of my chest.")
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_dialog("Aah—", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Startled, I immediately cupped my chest, afraid to be caught by other students.")
	await novel_interface.show_text_only("Aya said I would get used to the speaker, but I think I'll never accept this weird numbness!!")
	await novel_interface.show_text_only("After the Sky Hotel operation, I had been requesting them to remove the stupid chip.")
	await novel_interface.show_text_only("Until Mariru threatened to ring the school bell through the chip in front of my whole class.")
	await novel_interface.show_text_only("What a devil!! Waaah…")
	await novel_interface.show_dialog("I have been working nonstop for you guys these days.", "Mariru")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("No wonder we don't receive any mission!", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("Ha… haha… \\nSounds like you can’t wait to work, Annie…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("If not for the headstrong Senators, I would've got everything settled…", "Mariru")
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("Eh?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru sounds excited.")
	await novel_interface.show_dialog("Soon you'll know—", "Mariru")
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("What?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Never mind. But it's almost time for training, and you two are still hanging around the campus. For what? Dating?", "Mariru")
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("We still have half an hour…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Haven't you got my email? \\nYour physical training has been increased.", "Mariru")
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("Torture again…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I can already picture countless nights of collapsing onto my bed, dead tired...")
	await novel_interface.show_dialog("Torture? Humph—", "Mariru")
	await novel_interface.show_dialog("Don’t forget, your body has long been mine.", "Mariru")
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_text_only("Hey, stop that. This doesn’t sound right!!!")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/spConferenceRoom.png")
	await novel_interface.show_text_only("Mariru cuts off the call with a smile.")
	await novel_interface.show_text_only("She is standing upright in front of a bleak screen.")
	await novel_interface.show_text_only("The data from her tablet is being fed to the people behind the screen.")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("Regarding the budget…", "Mariru")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("I've requested the municipal authorities to give SID the mandate to take over the uninhabited land within 25 miles of G-cans in the New Northeast region.", "Mariru")
	await novel_interface.show_dialog("The budget is 1.49 billion.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("…", "Crowd")
	novel_interface.show_character("liliu_uniform2","speak")
	await novel_interface.show_dialog("We'll rebuild the pipes and supporting transportation and security infrastructure, all in line with V-class military bunker standard.", "Mariru")
	await novel_interface.show_dialog("The budget is 620 million.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("…", "Crowd")
	novel_interface.show_character("liliu_uniform2","speak")
	await novel_interface.show_dialog("The underground flood control ports will be renovated to connect in parallel. Electromagnetic shields will be put in place across the area. A customized autonomous weapon system will be deployed.", "Mariru")
	await novel_interface.show_dialog("The budget is 532 million.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("…", "Crowd")
	novel_interface.show_character("liliu_uniform2","speak")
	await novel_interface.show_dialog("The project is expected to take 58 days.", "Mariru")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("Senators, if you have no questions about this, SID will start the project right away.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_taki")
	await novel_interface.show_dialog("That's… very… pricey…", "Eloise")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("This is the most cost-effective option among the three development plans.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("…", "Kirs")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("Well, I don't mind calling an end to this project.", "Mariru")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("Either way, the final call is yours...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("…", "Crowd")
	await novel_interface.show_text_only("The silence doesn't mean no.")
	await novel_interface.show_text_only("Only static buzzing noise can be heard in the room.")
	await novel_interface.show_text_only("— The word \"Approved\" shows up one after another on the screen.")
	await novel_interface.show_text_only("It appears beneath every video feed.")
	await novel_interface.show_text_only("Mariru beams with satisfaction.")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("So—I announce the start of \"Project Ark\"!", "Mariru")

	print("=== 深海恐惧篇第04话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
