# bathophobia_ep24.gd - 深海恐惧症篇第24话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep24_script()

func play_script():
	pass

func bathophobia_ep24_script():
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Control_Room.png")
	await novel_interface.show_text_only("Milk kehrt in den Kontrollraum zurück und blockiert die Haupttür mit einem Stuhl.")
	await novel_interface.show_text_only("Die nächste Gruppe von Feinden wird in wenigen Minuten eintreffen. Die andere Gruppe wird bald auch im Ostflügel auf Milks Trupp stoßen.")
	novel_interface.show_character("milk_battle","gratified")
	await novel_interface.show_dialog("Hmm. Daran hätte ich früher denken sollen...","Milch")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Wenn ich meine eigene Truppe extrem agiler Soldaten mit scharfem Gehör und unglaublichen Selbstheilungsfähigkeiten hätte...")
	await novel_interface.show_text_only("Warum sie mit Klingen und nicht mit Schusswaffen ausrüsten?")
	await novel_interface.show_text_only("Diese Feinde bewegen sich in Gruppen und haben keine nennenswerte Strategie, obwohl sie alle wahnsinnig effektive Kämpfer sind.")
	novel_interface.show_character("milk_battle","normal")
	await novel_interface.show_dialog("Sie können nicht länger als Menschen betrachtet werden, diese Mädchen...","Milch")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Milk wirft einen Blick auf die Gerätereihe links vom Hauptkontrollpult. Darauf liegt die Probenschachtel, die Beth zurückgelassen hat.")
	novel_interface.show_character("milk_battle","normal")
	await novel_interface.show_dialog("Die Mission... spielt keine Rolle mehr.","Milch")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("Ich vermute, dass die hier eingesetzten strategischen Offensivverteidigungsmaßnahmen gar nicht so schlecht sind...","Milch")
	await novel_interface.show_dialog("Ich hoffe, der Lautsprecher funktioniert noch...","Milch")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sie holt tief Luft, stabilisiert sich, bevor sie eine Reihe von Befehlen in das Bedienfeld eingibt...")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Storehouse.png")
	await novel_interface.show_text_only("Währenddessen flattert Beth im dunklen Lagerhaus durch den Raum und sucht verzweifelt nach etwas, das vielleicht gar nicht da ist.")
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("Das Passwort... \\nWie lautet das Passwort?","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mit zitternden Fingern hat sie kaum noch eine Ahnung, welche Tasten sie am Schlosspaneel drückt.")
	await novel_interface.show_text_only("Wenn sie das richtige Passwort hat, kann sie das Lagerhaus verlassen und an der Seite ihrer Freundin kämpfen.")
	await novel_interface.show_text_only("Aber Milk auf der anderen Seite der Mauer hinterließ keine Hinweise darauf, wie das Passwort lauten könnte.")
	await novel_interface.show_text_only("Vielleicht hinterlässt sie ihr nie wieder einen Hinweis...")
	novel_interface.show_character("baizhu_break","angry")
	await novel_interface.show_dialog("Nein! Nein!\\nDas kann ich nicht akzeptieren! Ich werde das nicht akzeptieren!","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Voller Raserei hämmert Beth weiter mit den Fäusten gegen die Tür, doch ihre Ausbruchsversuche sind erfolglos.")
	await novel_interface.show_text_only("Sie kann sich nur vorstellen, was als nächstes auf der anderen Seite der Mauer passieren wird, ganz allein in dem dunklen, stillen, engen Raum.")
	novel_interface.show_character("baizhu_break","puzzled")
	await novel_interface.show_dialog("Bitte keine...","Beth")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_dialog("(Ich bin nutzlos... )","Beth")
	await novel_interface.show_dialog("(Kann niemanden retten... )","Beth")
	await novel_interface.show_dialog("(Nicht Vater..., nicht Milch... )","Beth")
	await novel_interface.show_dialog("(Wie... ist das passiert... ?)","Beth")
	await novel_interface.show_dialog("(Warum bin ich so schwach... ?)","Beth")
	await novel_interface.show_dialog("(So hilflos... )","Beth")
	await novel_interface.show_dialog("(... Und egoistisch.)","Beth")
	await novel_interface.show_dialog("(Warum?)","Beth")
	novel_interface.show_character("baizhu_break","sad")
	await novel_interface.show_text_only("Ich möchte nur nicht einsam und nicht kalt sein...")
	await novel_interface.show_text_only("Ich verlange nicht zu viel, oder?")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Das Mädchen sitzt allein im Dunkeln, die Schultern zittern vor Schluchzen.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Storehouse.png")
	novel_interface.change_music("res://assets/audio/music/Wind.mp3")
	await novel_interface.show_text_only("Sie merkt kaum, dass der andauernde intensive Kampf ihren Körper bis ins Mark erschöpft hat.")
	await novel_interface.show_text_only("Die Dekompressionskrankheit bringt ihr Gehirn durcheinander.")
	await novel_interface.show_text_only("Es ist, als würde Wasser in ihrem Kopf brodeln und ihr Bewusstsein Stück für Stück durcheinander bringen.")
	await novel_interface.show_text_only("Vielleicht hat sie das im dunklen, tiefen Ozean doch nicht gesehen...")
	novel_interface.change_background("res://assets/images/bg/Baizhu/white_bg.png")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("Sie kommt sich vor, als wäre sie auf einem Gletscher – nein, in einem. Das Eis, scharf und dicht, durchdringt ihr Herz, ihre Seele.")
	await novel_interface.show_text_only("Ihr geschmeidiger Körper gefriert nach und nach und ihr Blut beginnt zu gefrieren.") #换行问题
	await novel_interface.show_text_only("Unzählige reine Lichtgruppen umgaben sie, bis sie ihre Existenz vollständig verdeckten.")
	await novel_interface.show_text_only("Es gibt keinen Schmerz mehr, keine Einsamkeit mehr.")
	await novel_interface.show_text_only("Nicht mehr.")
	novel_interface.change_music("res://assets/audio/music/Everything's gonna be Okay.mp3")
	await novel_interface.show_text_only("In dieser Welt aus reinem Weiß hört sie eine vertraute Melodie.")
	await novel_interface.show_dialog("... Milch?","Beth")
	await novel_interface.show_text_only("Das ist ihr Lieblingslied. Ihr Lied.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Tunneling2.png")
	await novel_interface.show_text_only("In einem explosiven Ausbruch fliegen Hunderte leuchtender Kugeln aus Beths Körper.")
	await novel_interface.show_text_only("Das Mädchen blinzelt und öffnet die Augen. Das blendend weiße Licht hat mit ohrenbetäubendem Knall die gesamte Wand weggeblasen.")
	await novel_interface.show_text_only("Der Lautsprecher im Kontrollraum spielt ihr Lied, das den ganzen Tunnel hinunter hallt. Milk muss die Audiodatei verwendet haben, die sie in ihrer Uhr gespeichert hat.")
	await novel_interface.show_text_only("Dutzende Feinde haben sich versammelt, angelockt vom Geräusch. So viele davon, weit mehr, als sie auf dem Bildschirm gezählt hatten.")
	await novel_interface.show_text_only("Die Feinde haben den Eingang des Kontrollraums umzingelt.")
	await novel_interface.show_text_only("Beth ist jetzt nur noch dreißig Meter vom Kontrollraum entfernt.")
	novel_interface.show_character("baizhu_break","cry")
	await novel_interface.show_dialog("(Ich brauche nur zehn Sekunden... nein, fünf... )","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fünf Sekunden, um ihre idiotische beste Freundin zu erreichen und sie davon abzuhalten, das zu tun, was sie tun wird.")
	await novel_interface.show_text_only("Eine große Gruppe parasitärer Soldaten schwärmte sofort auf Bai Zhu zu und plötzlich griffen mehrere scharfe Klingen hinter ihr an.")
	await novel_interface.show_text_only("Sie dreht sich um und feuert mehrere Schüsse in Form heller Lichtstrahlen ab, die ihre Ziele an der Wand in Stücke sprengen.")
	await novel_interface.show_text_only("Sie rennt weiter in Richtung Kontrollraum, ihr Körper erstrahlt in einem Licht, heller als je zuvor.")
	await novel_interface.show_text_only("Die von ihrem Körper ausgehenden Energiewellen reißen die Innenwände des Tunnels ab. Sie leuchtet blendend wie ein Requiem vom Himmel.")
	await novel_interface.show_text_only("Niemand kann sie jetzt aufhalten.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Snedronningen_Light.png")
	await novel_interface.show_text_only("Unzählige grelle weiße Strahlen schießen von der Snedronningen-Basis aus und erhellen den Sternenhimmel, als ob die Morgendämmerung über den schlummernden Kontinent hereingebrochen wäre.")
	await novel_interface.show_text_only("Fast wie ein Begrüßungsritual für eine Gottheit.")
	await novel_interface.show_text_only("Plötzlich beginnt der ganze Kontinent zu beben...")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Tunneling2.png")
	await novel_interface.show_text_only("In nur wenigen Sekunden hat Beth Dutzende Feinde auf einmal getötet. Sie fällt zurück, ihre Sicht wird durch das flackernde Licht getrübt.")
	await novel_interface.show_text_only("Die Kraft, die aus ihrem Körper strömt, ist kurz davor, sie ganz zu verschlingen.")
	await novel_interface.show_text_only("Als sie mit der Klinge in ihrer rechten Hand einen Feind aus dem Weg wirft...")
	await novel_interface.show_text_only("Ein Dutzend Feinde brechen durch die verstopfte Tür des Kontrollraums und stürmen hinein.")
	novel_interface.show_character("baizhu_break","angry")
	await novel_interface.show_dialog("Warte auf mich... Idiot...","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("„Ich komme...“")
	await novel_interface.show_text_only("Boom!")
	await novel_interface.show_text_only("Aus dem Kontrollraum schießt ein gigantischer Lichtbogen. Dann kommen die Explosionen, unzählige Flammenexplosionen in einer Sekunde, direkt vor Beths Augen.")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("Es ist, als ob die Zeit stehen geblieben wäre.")
	await novel_interface.show_text_only("Sie bleibt abrupt stehen und fällt auf die Knie, nur wenige Meter vom Kontrollraum entfernt.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Tunneling3.png")
	await novel_interface.show_text_only("Dann öffnet dieser eisige Kontinent, rücksichtslos und kalt, endlich seine Augen aus seinem nie endenden Schlaf.")
	await novel_interface.show_text_only("In der Dunkelheit bricht ein goldener Schatten aus den unterirdischen Eisschichten hervor, reißt sich durch den Boden des Tunnels und durchdringt lautlos den Oberkörper des Mädchens.")
	await novel_interface.show_text_only("Es ist ein Speer, der schlicht aussieht, wären da nicht die komplizierten Goldmuster, die um die Speerspitze herumwirbeln.")
	await novel_interface.show_dialog("…","Beth")
	await novel_interface.show_text_only("Ein warmer Hitzestrahl strömte über die Spitze der Waffe, folgte dem Waffenkörper und verschmolz mit dem Blut.")
	await novel_interface.show_text_only("Ihre Arme fallen schlaff zur Seite. Auch wenn sich ihre Pupillen weiten, starrt sie sie an, als wäre sie noch nicht bereit aufzugeben.")
	await novel_interface.show_text_only("Auf dem Boden purpurrotes Blut.")
	await novel_interface.show_text_only("Tropfen. Tropfen. Tropfen.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Das helle Licht, das den Kontinent umhüllt, verblasst.")
	
	print("=== 深海恐惧症篇第24话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
