# bathophobia_ep23.gd - 深海恐惧症篇第23话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep23_script()

func play_script():
	pass

func bathophobia_ep23_script():
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Control_Room.png")
	novel_interface.show_character("milk_battle","normal")
	await novel_interface.show_dialog("Yêu cầu quyền truy cập... được rồi, xong. Chúng tôi đang ở trong.","Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Bíp—\\nCánh cửa phòng điều khiển mở ra.")
	await novel_interface.show_text_only("Máy điều khiển âm thanh trong nhà được bật cùng lúc, Nến Trắng và Sữa bước vào phòng, hỗ trợ lẫn nhau.")
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("*Ho*","Beth")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_battle","normal")
	await novel_interface.show_dialog("*Thở hổn hển*","Milk")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","smile")
	await novel_interface.show_dialog("Hiện tại chúng ta sẽ an toàn ở đây....","Beth")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_battle","serious")
	await novel_interface.show_dialog("Vâng. Tôi sẽ kiểm tra hệ thống.","Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Milk bước tới bảng điều khiển và kiểm tra các tin nhắn trên màn hình. Họ không nói về con voi trong phòng – những kỹ năng mà Beth vừa bộc lộ. Rõ ràng không phải là con người.")
	novel_interface.show_character("milk_battle","pleased")
	await novel_interface.show_dialog("Ồ, họ đang sử dụng Chính hãng cho hệ thống bảo mật của mình. Đẹp.","Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Milk thích khoe khoang về khả năng hack của mình với Beth. Hệ thống Chính hãng—miếng bánh dành cho cô ấy. Cô ấy đã làm việc chăm chỉ hơn nhiều.")
	novel_interface.show_character("milk_battle","pleased")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("baizhu_break","think",0.25)
	await novel_interface.show_dialog("Sữa, tôi...","Beth")
	novel_interface.character_light(0.35,"laugh")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Suỵt, không sao đâu, tôi hiểu rồi.","Milk")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Milk dùng một tay vuốt ve cô gái trẻ đang lắc lư trên đầu một cách trìu mến.")
	await novel_interface.show_text_only("Cô ấy thực sự hiểu được nó. Không phải là bạn của cô ấy cố tình che giấu kỹ năng của mình để chọc tức cô ấy.")
	await novel_interface.show_text_only("Rốt cuộc, nếu Boss phát hiện ra, ông ta sẽ rất vui mừng khi tận dụng tối đa “tài nguyên chiến thuật” này.")
	await novel_interface.show_text_only("Khi vuốt ve đầu cô ấy, Milk gỡ chiếc kẹp tóc bằng kim loại màu đen ra khỏi tóc của Beth. Beth nhìn chằm chằm, bối rối.")
	await novel_interface.show_text_only("Milk nhăn mặt với cô và nhanh chóng cúi xuống, biến mất dưới bàn điều khiển.")
	await novel_interface.show_dialog("Nếu tôi sử dụng một vật kim loại để làm chập mạch hệ thống, nó sẽ kích hoạt cơ chế bảo vệ quá tải tự động.","Milk")
	await novel_interface.show_text_only("Sau một tiếng xèo xèo nhỏ, hai hàng đèn báo trên bảng điều khiển đồng loạt tắt. Màn hình trung tâm bây giờ hoàn toàn tĩnh.")
	await novel_interface.show_text_only("Leo ra khỏi gầm bàn, Milk rút ra một sợi cáp dữ liệu từ bên trong đồng hồ và cắm nó vào ổ cắm trên máy tính để bàn.")
	await novel_interface.show_text_only("Vài giây sau, đèn báo lại nhấp nháy và quạt cũng bắt đầu quay lại.")
	novel_interface.show_character("milk_battle","serious")
	await novel_interface.show_dialog("Chỉ cần tôi thêm bộ nhớ flash vào hàng đợi tự kiểm tra trước khi hệ thống khởi động lại, chúng tôi sẽ có thể nhập mã.","Milk")
	novel_interface.change_expression("pleased")
	await novel_interface.show_dialog("Thấy không? Rốt cuộc thì hệ thống bảo mật này... không an toàn lắm.","Milk")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","mock")
	await novel_interface.show_dialog("Vì vậy, cho dù phần mềm được thiết kế liền mạch đến đâu thì vẫn có cách để đột nhập vào phần cứng... ?","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Milk đã phàn nàn với Beth về những chuyện như thế này khi họ cùng nhau ăn trưa tại quán trà yêu thích. Tất nhiên là Beth không hiểu một từ nào cả.")
	await novel_interface.show_text_only("Milk tiếp tục nhìn chằm chằm vào màn hình, gõ lệnh nhanh bằng tay trái, gửi cho Beth một trái tim bằng ngón tay bằng tay phải.")
	await novel_interface.show_text_only("Một trái tim bằng ngón tay—thật lạc lõng trong hoàn cảnh như thế này, nhưng đối với Beth, nó mang lại cảm giác ấm áp, nhẹ nhõm, như ở nhà.")
	await novel_interface.show_text_only("Rốt cuộc thì không cần phải giải thích kỹ năng của cô ấy với Milk. Họ là... bạn tâm giao, phải không?")
	await novel_interface.show_text_only("Milk đã ghi đè hệ thống và hiện đang chạy một trong những phần mềm của riêng mình, dần dần giành được quyền kiểm soát tất cả các thiết bị giám sát trong căn cứ.")
	await novel_interface.show_text_only("Beth đứng đó, quan sát các thiết bị khác trong phòng. Bên cạnh bảng điều khiển chính có một dãy thiết bị nhưng cô không biết chúng dùng để làm gì. Cô cũng không có thời gian để tìm hiểu.")
	await novel_interface.show_text_only("Trên màn hình lớn trước mặt Milk, cảnh quay của camera giám sát bắt đầu hiện lên.")
	await novel_interface.show_text_only("Ở giữa màn hình, những kẻ địch bị đồng đội bắn ngã xuống đất đang dần đứng dậy, tứ chi vẫn còn méo mó.")
	await novel_interface.show_text_only("Họ đang di chuyển chậm rãi, nhưng vết thương của họ đang dần lành lại.")
	await novel_interface.show_text_only("Sữa phóng to. Có một sinh vật giống dây leo màu xanh lá cây bám vào vết thương như một loại lưới.")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("(Tôi đã từng thấy điều tương tự trước đây trong một báo cáo... )","Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Đó là một loại cây giống cây thường xuân đã được biến đổi gen để bám vào con người, đánh cắp ý thức của họ và biến chúng thành những cỗ máy giết người giống như thây ma.")
	await novel_interface.show_text_only("Milk biết quá rõ loại kỹ thuật này có thể mang lại thiệt hại gì trên chiến trường.")
	novel_interface.show_character("milk_battle","shock")
	await novel_interface.show_dialog("... Chúng ta đang gặp rắc rối.","Milk")
	await novel_interface.hide_character() 
	await novel_interface.show_text_only("Theo dõi Milk's Gaze, Beth quay sang màn hình bên trái.")
	await novel_interface.show_text_only("Theo đoạn phim giám sát, ngoài những người đã tham gia trận chiến, còn có ít nhất hai nhóm kẻ thù khác hiện đang ở trong căn cứ.")
	await novel_interface.show_text_only("Một trong số họ, cả hai vừa mới thoát khỏi ba phút trước. Nhóm còn lại gồm bảy, tám thành viên, hiện đang di chuyển với tốc độ chóng mặt về phía cánh phía đông.")
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("(Nếu điều này tiếp tục, nhóm kẻ thù gần nhất sẽ tấn công chúng ta trong vòng ba phút.)","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beth chuyển hướng sang một loạt cảnh quay khác, nơi cô tìm thấy những hình ảnh mờ ảo của những thành viên còn lại trong đội đã bị tách khỏi họ cách đây không lâu.")
	await novel_interface.show_text_only("Thành viên cầm khiên đã bị mất nửa chân và hiện đang nằm trên cáng, được hai người khác khiêng về phía bệnh xá.")
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("(Có vẻ như họ không còn nhiều đạn nữa. Nếu tiếp tục dọc theo cánh phía đông như thế này, họ sẽ gặp một nhóm kẻ thù khác trong vòng năm phút.)","Beth")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("Đó có phải là...","Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Milk nhận thấy một bóng người trên một trong những cửa sổ nhỏ.")
	await novel_interface.show_text_only("Nó là kẻ thù nhanh nhất của nhóm. Bây giờ cô ấy đang đi lang thang dọc hành lang, vung chiếc ủng dính máu của một trong những thành viên trong đội.")
	await novel_interface.show_text_only("Như thể cảm nhận được ánh mắt của Beth, cô ấy nghiêng mặt về phía máy ảnh và mỉm cười—một nụ cười không răng đáng sợ.")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("Chết tiệt!","Milk")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("baizhu_break","normal",0.25)
	await novel_interface.show_dialog("Hãy bình tĩnh, bình tĩnh.","Beth")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Beth vỗ vai Milk an ủi, rồi bắt đầu quét nhanh hàng chục màn hình giám sát trong phòng.")
	await novel_interface.show_text_only("Cô nhanh chóng tập hợp bản đồ bố cục 3D của căn cứ trong đầu và so sánh nó với các cảnh quay nhằm cố gắng đưa ra phương án tối ưu nhất có thể.")
	await novel_interface.show_text_only("Milk có thể biết rằng Beth đang ở trong một trong những chế độ tính toán đó chỉ bằng cách liếc nhìn khuôn mặt cô ấy. Khi cô ấy gặp một trong những tình tiết đó, không có cách nào có thể khiến cô ấy thoát khỏi nó.")
	await novel_interface.show_text_only("Nhưng xét đến tình hình, thực sự không đời nào cô ấy có thể nghĩ ra một kế hoạch khả thi... phải không?")
	novel_interface.show_character("milk_battle","gratified")
	await novel_interface.show_dialog("Ừm. Bethy giỏi việc này...","Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Giọng Milk nhỏ dần thành tiếng thì thầm.")
	await novel_interface.show_text_only("Cô nhận thấy trên màn hình rằng nhóm kẻ thù đang tiến qua cánh phía đông bằng cách nào đó đã bỏ qua việc kiểm tra hàng rào hợp kim.")
	novel_interface.show_character("milk_battle","normal")
	await novel_interface.show_dialog("…","Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Milk nhắm mắt lại, ngẫm nghĩ rồi quyết định.")
	await novel_interface.show_text_only("Trong nháy mắt, cô ấy gõ một loạt lệnh trên bàn phím và gửi chúng.")
	await novel_interface.show_text_only("Một trung tâm dữ liệu quân sự dưới lòng đất, nằm trên những ngọn đồi ở đâu đó ở châu Á, sẽ nhận được tin nhắn trong vòng mười giây.")
	await novel_interface.show_text_only("Không phải là một lời cầu cứu mà là một thông điệp thông báo cho họ về sự sụp đổ của đội.")
	novel_interface.show_character("milk_battle","gratified")
	await novel_interface.show_dialog("(... Tôi xin lỗi.)","Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Milk mỉm cười buồn bã với Beth, người vẫn đang chìm đắm trong suy nghĩ.")
	await novel_interface.show_text_only("Cô gái tóc đen dường như đang phát ra một màu bạc nhạt.")
	await novel_interface.show_dialog("... Bethy...","Milk")
	await novel_interface.show_dialog("Bạn có nhớ lần đầu chúng ta gặp nhau không?","Milk")
	novel_interface.show_character("baizhu_break","shock")
	await novel_interface.show_dialog("Ừm?","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beth, vẫn đang đắm chìm trong kế hoạch của mình, hầu như không nhận ra Milk đang làm gì.")
	await novel_interface.show_dialog("Hồi đó tôi đã trộm một báo cáo nghiên cứu ngay trước mặt bạn. Bạn có nhớ điều đó không?","Milk")
	novel_interface.show_character("baizhu_break","smile")
	await novel_interface.show_dialog("Tại sao đột nhiên nhắc tới chuyện này?","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Bạn chưa bao giờ hỏi tôi tại sao tôi làm điều đó và tôi làm điều đó vì ai.","Milk")
	await novel_interface.show_text_only("Beth quay lại, cuối cùng cũng nhận ra những cảm xúc kỳ lạ trong giọng nói của Milk.")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	novel_interface.show_character("milk_aim","normal")
	await novel_interface.show_text_only("Cô ấy nhìn lên và bắt gặp ánh mắt của người lãnh đạo của mình, người đang chỉ vào cô ấy với một khẩu súng lục ổ quay trên một tay.")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("Bạn luôn như thế này...","Milk")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","normal")
	await novel_interface.show_dialog("…","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beth kiên quyết phớt lờ hành vi kỳ lạ của Milk.")
	await novel_interface.show_text_only("Cô ấy liếc nhìn lại màn hình và đẩy mõm ra một cách thiếu kiên nhẫn.")
	novel_interface.show_character("baizhu_break","speechless")
	await novel_interface.show_dialog("Đừng đùa nữa. Chúng ta có chưa đầy một phút. Những kẻ đó sẽ sớm tìm thấy chúng ta.","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Milk cười tự giễu.")
	novel_interface.show_character("milk_aim","gratified")
	await novel_interface.show_dialog("Thấy không? Tôi đang chĩa súng vào bạn. Và bạn vẫn tin tưởng tôi...","Milk")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","smile")
	await novel_interface.show_dialog("Tôi biết bạn sẽ không bao giờ làm tổn thương tôi.","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Milk nuốt khan những lời đó, biết rằng bạn mình đã nhìn thấu mình.")
	await novel_interface.show_text_only("Cô nạp khẩu súng lục của mình, tháo chốt an toàn, đặt ngón tay lên cò súng và chĩa thẳng vào Beth.")
	novel_interface.show_character("milk_aim","gratified")
	await novel_interface.show_dialog("Đứng lại.","Milk")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("…","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beth đột nhiên hiểu ra một cách mơ hồ về chính xác người lãnh đạo của cô đang lên kế hoạch gì.")
	novel_interface.show_character("milk_aim","solemn")
	await novel_interface.show_dialog("– Lùi lại!","Milk")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("…","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beth lùi lại cho đến khi lưng cô chạm vào cửa sau của phòng điều khiển.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Tunneling.png")
	await novel_interface.show_text_only("Cánh cửa mở ra, để lộ một lối đi dốc.")
	await novel_interface.show_text_only("Beth tiếp tục lùi lại, họng súng của Milk vẫn chĩa vào giữa hai mắt cô.")
	novel_interface.show_character("milk_aim","gratified")
	await novel_interface.show_dialog("Này, bạn còn nhớ câu hỏi đó không?","Milk")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("Đừng đùa nữa, Sữa...","Beth")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_aim","gratified")
	await novel_interface.show_dialog("Có một chuyến tàu không thể dừng lại được. Có hai cách nó có thể đi. Một cách, nó đè bẹp đồng đội của bạn. Một cái khác, nó nghiền nát bạn.","Milk")
	await novel_interface.show_dialog("Bạn cứu ai?","Milk")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","angry")
	await novel_interface.show_dialog("—Sữa!","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Vẻ đau buồn hiện rõ trên khuôn mặt Milk, thật bi thảm.")
	novel_interface.show_character("milk_aim","mock")
	await novel_interface.show_dialog("Tôi chọn cứu... người tôi yêu...","Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Với nụ cười ranh mãnh, Milk lao về phía trước, ép Beth vào một cửa sập trên tường đường hầm.")
	await novel_interface.show_dialog("Ủa... ?","Beth")
	await novel_interface.show_text_only("Trước khi Beth kịp phản ứng, cô ấy đã lăn xuống cầu thang vào một trong những nhà kho bí mật duy nhất trong căn cứ, được bảo vệ bởi hàng rào hợp kim.")
	await novel_interface.show_text_only("Một rào cản chỉ có thể mở được từ bên ngoài.")
	novel_interface.show_character("milk_aim","mock")
	await novel_interface.show_dialog("Bethy...","Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Giọng nói kỹ thuật số đều đều.\\n\"Hệ thống an ninh đã khóa. Rào chắn đã đóng.\"")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Locking.png")
	await novel_interface.show_text_only("Trước mắt Beth, Milk đang mỉm cười rạng rỡ hơn bao giờ hết.\\nCánh cổng rào chắn bắt đầu đóng lại.")
	await novel_interface.show_text_only("Quá nhanh.")
	await novel_interface.show_dialog("“Ba... ”","System")
	await novel_interface.show_dialog("Hãy cùng nhau đón Giáng sinh tới. Bạn nói gì?","Milk")
	await novel_interface.show_dialog("“Hai... ”","System")
	await novel_interface.show_text_only("Beth tuyệt vọng đưa tay ra, cố gắng ôm lấy Milk, nhưng Milk lùi lại và gửi cho cô một nụ hôn gió.")
	await novel_interface.show_dialog("“Một... ”","System")
	await novel_interface.show_text_only("Beth nhìn chằm chằm với vẻ hoài nghi.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Locking2.png")
	await novel_interface.show_text_only("Còn lại một giây. Khuôn mặt của Beth méo mó, hàng nghìn cảm xúc cùng lúc trào dâng.")
	await novel_interface.show_dialog("Hãy mỉm cười đi! Hãy cười lên cho tôi!","Milk")
	await novel_interface.show_text_only("Đó là điều cuối cùng Beth nghe thấy trước khi cánh cổng rào đóng sầm lại, tàn nhẫn, vô cảm.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Âm thanh Beth đập mạnh vào tường vang vọng khắp đường hầm.")
	await novel_interface.show_text_only("Nghe có vẻ nặng nề làm sao, trên nhiều lớp bảng hợp kim Ti-451...")
	
	print("=== 深海恐惧症篇第23话结束 ===")
	
	await novel_interface.end_story_episode(0.5)
