# bathophobia_ep29.gd - 深海恐惧症篇第29话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep29_script()

func play_script():
	pass

func bathophobia_ep29_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Baizhu_Sickroom_Evening.png")
	await novel_interface.show_text_only("ナースさんが病室の扉をノックした。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("うん？","小憐")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("すみませんバイジュウさん。\\nそろそろリハビリのお時間です。","ナース")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("あっ、もうこんな時間か。","小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ナースさんは申し訳なさそうに微笑んだ。")
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("それじゃまた明日──","小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("話の途中、胸元が2回震える。")
	await novel_interface.show_text_only("おっと、忘れるところだった。明日も来るなんて\\nマリルが絶対許してくれないよな……")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("（今回のお見舞いも何十回と申請した挙句……）\\n\\n（やっと許可がもらえたんだし……）","小憐")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("じゃあ……俺達、今日の所は帰るから。","小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("はい、お気を付けて。","バイジュウ")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("簡単な別れの挨拶を交わし、少し名残惜しそうな\\nラファエルの肩を押して\\nアニーと一緒に病室を離れた。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("うあっ！　今度はこっちを忘れてたっ！","小憐")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Baizhu_Sickroom_Evening.png")
	await novel_interface.show_text_only("廊下にいる2人に頭を下げ、\\n慌てて1人でバイジュウの病室へ戻った。")
	novel_interface.show_character("baizhu_normal","shock")
	await novel_interface.show_dialog("どうしましたか？","バイジュウ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("え、えっと……\\n（なんか恥ずかしいな……）","小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("俺は深呼吸をして、勇気を振り絞り前へ出る──")
	await novel_interface.show_text_only("直接バイジュウの手を引いた。\\n\\nそして色付きのリップクリームで、\\n彼女の手のひらに数字の文字列を書く。")
	novel_interface.show_character("ren_battle","shy_left")
	await novel_interface.show_dialog("こ、これ、俺の番号っ！\\n\\nもしよかったら、あの……俺に連絡くださいっ！","小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("うわあああぁ――っ！！！\\nこれ超恥ずかしい事をした気がするっ！！！")
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("……ゴホン。","小憐")
	await novel_interface.show_dialog("（考えてみると……）\\n\\n（色付きリップを持ち歩いている事も……）\\n\\n（女の子の手に字を書くのも、変だよな……）","小憐")
	novel_interface.change_expression("perspire1")
	await novel_interface.show_dialog("べ、別にやましい事を考えてるとかではなくて、\\nその……","小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_normal","shock")
	await novel_interface.show_dialog("…………","バイジュウ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("バイジュウの表情は少し驚いてるように見える。")
	await novel_interface.show_text_only("そりゃ驚くよね！\\nさっき俺の行動はデリカシーがないし！")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("（あ、あんな事をやらなければ良かったかも…）","小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("「男性向けロマンチックでファンタジーな\\n　シチュエーション、ベスト10！」\\nという去年の街頭アンケート結果の1個なのに…")
	await novel_interface.show_text_only("あ、待てよ……あれって……\\n\\n「入院中にお見舞いに来た美少女が、自分の\\n　手のひらに電話番号を書いてくれた」だっけ…")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("（なんか致命的に間違えていた気がする……）","小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("俺は番号が書かれたバイジュウの手を握りつつ、\\n少し狼狽えていた。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("ああっ――これ、あの……\\n汚しちゃって………ごめん！","小憐")
	await novel_interface.show_dialog("拭かせてくださいッ！！\\n（そして何も無かった事にしますッ！！）","小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("俺は急いで自分が書いた数字をかき消した。")
	novel_interface.show_character("baizhu_normal","shock")
	await novel_interface.show_dialog("…………","バイジュウ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("さらに彼女を驚かせてしまったか……")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("失礼ですが、その……\\nレンさんは男の子なんでしょうか？","バイジュウ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("はぇッ！？","小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("どどどどどどどしてバレたッ！？！？")
	await novel_interface.show_text_only("俺は動揺しすぎて、ティッシュを取ろうとする\\n動きすらガチガチになり、\\n続けざま3枚も引き抜いてしまった。")
	await novel_interface.show_text_only("絶対に自分の情報を漏らさないようにと、すでに\\nマリルから厳重注意されている。さもないと……")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("何でしょうか。\\n\\n直感ですかね……？","バイジュウ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("バイジュウは少し止まってから、\\n追い打ちをかける。")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("こんな事をするのは、\\nなんだか不器用な男の子みたいです……","バイジュウ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("は、あはは……\\n\\n多分俺が図太い神経をしているタイプだから\\nじゃないかな……","小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ようやくバイジュウの手を拭き終えた俺は、\\n病室の出口に向かって素早く逃亡しようとした。")
	await novel_interface.show_dialog("レンちゃん──","バイジュウ")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("な、な、なんでしょうか……？","小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("処刑宣告までの時間が少しでも遅くなるように、\\n俺は硬直気味にゆっくりと振り返る。")
	await novel_interface.show_text_only("まさか本当に見抜かれてはいないよね！?")
	await novel_interface.show_text_only("そう思いながら振り向いたが俺の予想とは\\n若干違い、バイジュウは俺に対して\\n楽しそうな笑みを浮かべていた。")
	novel_interface.show_character("ren_battle","sob")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("baizhu_normal","mock",0.25)
	await novel_interface.show_dialog("あなたの番号、もう覚えちゃいました。","バイジュウ")
	novel_interface.character_light(0.35,"timid")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("あ、あ……？","小憐")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("俺は少し戸惑って、その場で呆然としてしまう。")
	novel_interface.show_character("ren_battle","timid")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("baizhu_normal","smile",0.25)
	await novel_interface.show_dialog("それから……","バイジュウ")
	await novel_interface.show_dialog("実は目を覚ましてから、マリルさんに頼んで\\n調べてもらった事があります。","バイジュウ")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("少女の笑顔が突然、影を落とした。")
	novel_interface.show_character("ren_battle","timid")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("baizhu_normal","sad",0.25)
	await novel_interface.show_dialog("信じたくはないのですが、どうやらお父さんは\\nずっと……\\n……私に色んな事を隠していたみたいなのです。","バイジュウ")
	await novel_interface.show_dialog("もしあなたでしたら……どうしますか？","バイジュウ")
	await novel_interface.hide_all_characters()
	await novel_interface.show_dialog("あのーー？　おーじょーさーんーー？","ナース")
	await novel_interface.show_text_only("ナースのお姉さんが、露骨に立ち去るよう\\n催促してきた。")
	novel_interface.show_character("anne_normal","happy")
	await novel_interface.show_dialog("レンちゃ～～ん！　そろそろ行かないと～～！","アニー")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("アニーは入り口から顔を出した。")
	novel_interface.show_character("ren_battle","smile")
	await novel_interface.show_dialog("あぁっ！　すぐ行くよっ！","小憐")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("あの、さっきの話……","小憐")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("baizhu_normal","smile",0.25)
	await novel_interface.show_dialog("いいえ、大丈夫です。\\n何も聞かなかった事にしてください。","バイジュウ")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（そんなわけには……）","小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("それより、早く行かないとでは？\\n\\nそうだ、抱き枕ありがとうございます。\\nすごく気に入りました。","バイジュウ")
	novel_interface.character_light(0.35,"gratified")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("うん……","小憐")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("バイジュウの姿はまだ弱っているように見える。")
	novel_interface.show_character("ren_battle","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("baizhu_normal","smile",0.25)
	await novel_interface.show_dialog("安心してください、ちゃんと連絡しますから。","バイジュウ")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("バイジュウは俺に向かって再度、手を振った。")
	novel_interface.show_character("ren_battle","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("baizhu_normal","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("あ、ああ……それじゃあ、またねっ！","小憐")
	await novel_interface.hide_all_characters()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("ワイワイと賑やかな人達が離れた後、\\nバイジュウは自分の手をぼんやり見つめていた。")
	await novel_interface.show_text_only("手を握られて番号を書かれた感触が、\\nまだ少し残っている。")
	await novel_interface.show_text_only("手のひらに暖かさを感じながら、\\nバイジュウは微かに笑みを浮かべた。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Baizhu_Cabin.png")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("──────飛行機の客室内")
	await novel_interface.show_text_only("滑走路の上でゆっくり移動し始めた飛行機は、\\n南米を離れるために最後の準備をしている。")
	await novel_interface.show_text_only("バイジュウは視線を窓の外に向けながら、\\nイヤホンから馴染みのある声を聞いていた。")
	await novel_interface.show_text_only("彼女はマリルから聞いた。\\n\\n過去にスノークイーン基地に起きた事や、\\nレンやハインリッヒが見た映像に関しての事。")
	await novel_interface.show_text_only("記憶が抜け落ちた19年間────\\n\\n戦争と異質物によって様変わりした世界に対し、\\n少女は戸惑いを隠せない。")
	await novel_interface.show_text_only("何か彼女を安心させるものがあるとしたら──")
	novel_interface.change_music("res://assets/audio/music/Everything's gonna be Okay.mp3")
	await novel_interface.show_dialog("「バ～イジュ～ウちゃ～ん♪」","Recordミルク")
	novel_interface.show_character("baizhu_normal","mock")
	await novel_interface.show_text_only("少女は手のひらにあるプレイヤーを握りしめた。")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("SIDのエージェントはミルクウォッチのデータを回収した後、その記録と情報の一部をプレーヤーにコピーし、白百珠に届けた。")
	await novel_interface.show_text_only("彼女は親友が出発前に録音した\\nボイスメッセージを繰り返し聞いている。")
	await novel_interface.show_dialog("「あと4ヶ月でクリスマスだよっ！」\\n\\n「私へのプレゼントはもう考えてるのかな？」","Recordミルク")
	await novel_interface.show_dialog("「えっへっへ～～」\\n\\n「この時期にクリスマスプレゼントの催促は\\n　ちょっと意地悪だったかも……」","Recordミルク")
	await novel_interface.show_dialog("「でもね、私すごく楽しみにしてるよっ！」","Recordミルク")
	await novel_interface.show_dialog("「……おかしいな。」\\n「出会ってからまだ1年しか経ってないのに」\\n「バイジュウちゃんとは何世紀も前から知り\\n　合っていたような感じでさ」","Recordミルク")
	await novel_interface.show_dialog("「おっとっ！　あんた今、大げさですねって」\\n\\n「照れながら言ってるでしょっ？」","Recordミルク")
	await novel_interface.show_dialog("「だって私の前では、バイジュウちゃんは…」\\n\\n「隠し事なんてできないからねっ！」","Recordミルク")
	await novel_interface.show_dialog("「……ねぇ、覚えてる？」\\n「私達が初めて出会った時。」\\n「バイジュウちゃんあの教授の金庫の暗証番号を\\n　私に教えちゃうんだもん。親和数ですよって」","Recordミルク")
	await novel_interface.show_dialog("「220、284。今でも覚えてる」","Recordミルク")
	await novel_interface.show_dialog("「そんな暗証番号の構成方式、初めて知ったよ」","Recordミルク")
	await novel_interface.show_dialog("「でもあんたアレは無神経過ぎじゃない！？」","Recordミルク")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Baizhu_Cafe.png")
	await novel_interface.show_dialog("「私が偽装した捜査員って分かっていたのに」\\n\\n「簡単に教授の秘密を暴露しちゃうなんて！」","Recordミルク")
	await novel_interface.show_dialog("「しかもその後……」\\n\\n「私からのお茶の誘いも、全然っ断らないし！」","Recordミルク")
	await novel_interface.show_dialog("「普通の人なら断るでしょ？」","Recordミルク")
	await novel_interface.show_dialog("…………","Recordミルク")
	await novel_interface.show_dialog("「まぁ、バイジュウちゃんらしいというべきか」","Recordミルク")
	await novel_interface.show_dialog("「もしくは、これが私達の日常……」","Recordミルク")
	await novel_interface.show_dialog("「いいんじゃない？」","Recordミルク")
	await novel_interface.show_dialog("「時々ね、思うんだ。」\\n\\n「私達の出会いは運命だったんだって」","Recordミルク")
	await novel_interface.show_dialog("「あんたと私の魂は……親和数みたいに………」\\n「あっあああいやいやいやっ！」　\\n「ヤバいこれ恥ずかしいっ！」　\\n「ダメだ削除削除っ！　やり直しっ！」","Recordミルク")
	await novel_interface.show_dialog("「──バイジュウちゃん」","Recordミルク")
	await novel_interface.show_dialog("「ごめんね。私あの時、あんたを利用した……」","Recordミルク")
	await novel_interface.show_dialog("「だからね、あんたも私を利用して」\\n\\n「それで、おあいこっ！」","Recordミルク")
	await novel_interface.show_dialog("「今年のクリスマスは、どこにいるのかなぁ？」","Recordミルク")
	await novel_interface.show_dialog("「どうせ任務が終わったら、半年ちょっとは、\\n　訓練の日々に戻るだろうしね……」","Recordミルク")
	await novel_interface.show_dialog("「もう嫌だーーっ！」\\n「Bossったら全然休みくれないもんっ！」","Recordミルク")
	await novel_interface.show_dialog("「だがしかぁしっ！　私には予感があるっ！」\\n\\n「来年のクリスマスなら──」","Recordミルク")
	await novel_interface.show_dialog("「まぁ……」\\n\\n「バイジュウちゃんは期待していなさいなっ！」","Recordミルク")
	await novel_interface.show_dialog("「と言うか私……」\\n\\n「なんで録音しようと思ったんだっけ……？」","Recordミルク")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("親友の声が、そこで止まった。")
	await novel_interface.show_text_only("バイジュウはリプレイボタンを押す。\\nイヤホンから再び馴染みのある声が聞こえた。")
	await novel_interface.show_dialog("「バ～イジュ～ウちゃ～ん♪」","Recordミルク")
	await novel_interface.show_text_only("…………")
	novel_interface.show_character("baizhu_normal","cry")
	await novel_interface.show_text_only("涙を浮かべながら、少女は小さい声で笑った。")
	novel_interface.change_expression("tear")
	await novel_interface.show_dialog("……バカ。","バイジュウ")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Sonar.mp3")
	await novel_interface.show_text_only("『魂』とは何か？")
	await novel_interface.show_text_only("意識を記録した、ある種のエネルギーか。\\nそれとも観測できない量子状態的な存在か？")
	await novel_interface.show_text_only("あるいは『魂』とは単なる概念の1つに過ぎないのかもしれない。")
	await novel_interface.show_text_only("物理学における『時間』の概念と同じく──")
	await novel_interface.show_text_only("ただの幻覚……夢。")
	await novel_interface.show_text_only("ならば唯一の問題は──")
	novel_interface.show_background("res://assets/images/bg/Baizhu/Baizhu_Niunai.png")
	await novel_interface.show_text_only("夢を見ているのは──誰なのか？")

	print("=== 潜渊症篇第29话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
