# bathophobia_ep13.gd - 深海恐惧症篇第13话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep13_script()

func play_script():
	pass

func bathophobia_ep13_script():
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Submarine_centralControlRoom.png")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	await novel_interface.show_text_only("中央制御室の中で座っているバイジュウは、\\n船室外にあるリアルタイム監視映像に\\n映される氷山を見つめていた。")
	await novel_interface.show_text_only("潜水艦の浮上と共に南極の夜空の下、\\n淡い紫色の光が部屋全体を覆った。")
	novel_interface.show_character("milk_normal","laugh")
	await novel_interface.show_dialog("バイ～～ジュウ～～ちゃん～～♪", "ミルク")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("部屋の扉が突然押し開かれ、活発な性格の\\nポニーテール少女が飛びかかってきた。")
	await novel_interface.show_text_only("深慮から現実に引き戻されたバイジュウは、\\n致し方なく溜め息を吐いた。")
	novel_interface.show_character("milk_normal","pleased")
	await novel_interface.show_dialog("ねぇ～私に会いたかったでしょ～～？", "ミルク")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("さっきのパスコードはアホどもの悪戯だから、\\n気にしないでいいんだよ！", "ミルク")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ミルクはそう言いながら、\\n先程の「戦利品」である札束を見せつける。")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("悪趣味です。", "バイジュウ")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_normal","laugh")
	await novel_interface.show_dialog("いつも私の期待に答えてくれるバイジュウちゃん\\nやっぱ最高～～それに超可愛いっ！", "ミルク")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("バイジュウは自分にくっ付いてくる生物を\\n引き剥がそうとするが、\\n相手は剥がされてもまたすぐ飛びかかってくる。")
	novel_interface.show_character("milk_normal","mock")
	await novel_interface.show_dialog("へっへっへ～～と、まあ。\\nそれより……さっきの報告している時、\\nちょっと様子がおかしかったよ？", "ミルク")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_normal","think")
	await novel_interface.show_dialog("…………そう？", "バイジュウ")
	await novel_interface.hide_character()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("バイジュウがソファーに座ると、ミルクは彼女の\\n膝の上に乗って彼女の頬を両手で包む。")
	novel_interface.change_music("res://assets/audio/music/Sunset.mp3")
	await novel_interface.show_text_only("少し動揺したバイジュウは、視線を避けた。")
	novel_interface.show_character("baizhu_normal","think")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("milk_normal","gratified",0.25)
	await novel_interface.show_dialog("…………", "ミルク")
	await novel_interface.show_dialog("認めないの？", "ミルク")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("しばらくの沈黙の後、ミルクは優しく微笑んだ。")
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("実はね、今回の任務、\\n実はこれぽっちも参加したくなかったんだ……", "ミルク")
	await novel_interface.show_dialog("超常現象や人外生物とか、私の趣味じゃないし。", "ミルク")
	await novel_interface.show_dialog("「南極上空に異常な類似生物の電波を検知」って\\n情報だけで「目標」を見つけ出すなんて、\\n普通は無理じゃん……", "ミルク")
	novel_interface.change_2nd_expression("laugh")
	await novel_interface.show_dialog("手ぶらで帰ったとしても、何の問題もない～～\\n\\n南極観光旅行っていう休暇になるかな～～って。", "ミルク")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("バイジュウは相手の言葉の真意が分かった。")
	novel_interface.show_character("baizhu_normal","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light(0)
	novel_interface.show_2nd_character("milk_normal","laugh",0.25)
	novel_interface.character_2nd_dark(0)
	await novel_interface.show_dialog("……全て、分かったのですか？", "バイジュウ")
	novel_interface.character_dark()
	await novel_interface.show_text_only("ボニーテールの少女は真剣な表情に変わった。")
	novel_interface.character_2nd_light(0.35,"solemn")
	await novel_interface.show_dialog("ええ。\\nあんたの潜水艦のログを調べた。", "ミルク")
	await novel_interface.show_dialog("あんた……『アレ』を目視したの？", "ミルク")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("バイジュウは机の上に広げられた\\n軍事作戦用の南極詳細地図を見た。")
	await novel_interface.show_text_only("支給された地図の上には、\\n黒影の印がはっきりとマークされている──")
	await novel_interface.show_text_only("南極大陸東部の海洋中、その区域に正体不明の\\n大型物体が発見されたとして。")
	novel_interface.show_character("baizhu_normal","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("milk_normal","pleased",0.25)
	await novel_interface.show_dialog("──まぁ、安心してよね。", "ミルク")
	novel_interface.change_2nd_expression("sprite")
	await novel_interface.show_dialog("任務中に潜水艦をわざと制御不能にさせてから\\n深海6000mまで沈下した後、\\n自動的に復旧するよう設定した操作ログ。\\n私が全部編集しといたからさ～", "ミルク")
	await novel_interface.show_dialog("あんたってさ、機械類は得意だけど、\\nああいう隠しコードは良く見落とすよね……", "ミルク")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("あなたが助けてくれると信じていましたから。", "バイジュウ")
	novel_interface.character_dark()
	await novel_interface.show_text_only("バイジュウは少しずるい笑みを浮かべた。")
	novel_interface.character_2nd_light(0.35,"shock")
	await novel_interface.show_dialog("だけどね？　さっきの報告で、南極大陸の\\n奥地へ行きたいって意図。\\nあれは少し分かりやす過ぎたと思うよ！", "ミルク")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("ミルクはバイジュウの頭を軽く叩いた。")
	novel_interface.show_character("baizhu_normal","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("milk_normal","normal",0.25)
	await novel_interface.show_dialog("そもそもサンプル収容箱が数時間の深海環境しか\\n維持できないとしても、\\nそれが原因でサンプルが活性を失うとは\\n限らないのでしょ？", "ミルク")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("はい……", "バイジュウ")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"sprite")
	await novel_interface.show_dialog("ねぇねぇ、『アレ』って綺麗だった？", "ミルク")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("バイジュウは怯えたまなざしで、首を横に振る。")
	novel_interface.character_2nd_light(0.35,"gratified")
	await novel_interface.show_dialog("ああ～～やっぱそうよね。", "ミルク")
	await novel_interface.show_dialog("……でも、なぜ自分が『アレ』の追加情報を\\n知っている事、隠しちゃうの？", "ミルク")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("バイジュウは黙った。")
	await novel_interface.show_text_only("ミルクはバイジュウの隣に座り、\\n視線を窓の外へ向ける。")
	novel_interface.show_character("baizhu_normal","think")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("milk_normal","normal",0.25)
	await novel_interface.show_dialog("最初、バイジュウちゃんの目的はウスアイア号か\\nと思った。", "ミルク")
	await novel_interface.show_dialog("だけど「砕氷船の上に実験室を設置する」って\\n聞くだけで不安要素だらけだよね……", "ミルク")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("ですから、必ず不安要素が「想定外」を生み\\nあの案は却下となるでしょう。", "バイジュウ")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("そうなると、サンプルの解析が可能な場所は\\n極地区域内にある常駐施設の実験室しかない。", "ミルク")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("2時間以内の範囲、かつ規格を満たす実験室を\\n所有している施設ですと\\n『スノークイーン』及び『ニュルンベルク』\\n南極圏内ではこの2つの基地だけです。", "バイジュウ")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("残りは設備が古いか、権力関係が複雑だし、\\n駐屯軍がいるところなんて論外。", "ミルク")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("地理的な観点では、ニュルンベルク基地の方が\\nエメリー棚氷の近くです。", "バイジュウ")
	await novel_interface.show_dialog("ですが──", "バイジュウ")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"sprite")
	await novel_interface.show_dialog("だけどあいにく、ニュルンベルク基地は先月から\\n民間の武装部隊が駐屯を始めた。\\nつまり「独立機関」に売却されたって事だね。", "ミルク")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("2人は目を合わせ、バイジュウが瞬きした。")
	novel_interface.show_character("baizhu_normal","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light(0)
	novel_interface.show_2nd_character("milk_normal","sprite",0.25)
	novel_interface.character_2nd_dark(0)
	await novel_interface.show_dialog("正直な話、あなたのBossがプライベート企業と\\n協力する意思表明さえしてくれるのでしたら……", "バイジュウ")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("いやいや。\\n政府のトップ達はメンツが一番大事だからさ。", "ミルク")
	novel_interface.character_light(0.35,"shock")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("近隣海域の海賊と、独裁者を買収したとしても\\nでしょうか？", "バイジュウ")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"pleased")
	await novel_interface.show_dialog("ねえっ！　バイジュウちゃん知り過ぎっ！", "ミルク")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("と、とにかく、砕氷船とニュルンベルク基地の\\n選択肢がなくなったとすると、\\n私達に向かわせたい本当の目的地は――", "ミルク")
	await novel_interface.show_dialog("東経76-55-22、南緯68-24-59…「スネドロニンゲン」 - ホワイトクイーンベース。", "ミルク")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……もう。", "バイジュウ")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"gratified")
	await novel_interface.show_dialog("おっ、ようやく認めた？", "ミルク")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("私の考えを、あなたは全て知っているくせに……", "バイジュウ")
	novel_interface.character_dark()
	await novel_interface.show_text_only("ミルクは推理力を得意げにするのではなく、\\n親友に心配する表情を見せる。")
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("手がかりは……あそこを指してたの？", "ミルク")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("…………", "バイジュウ")
	novel_interface.character_dark()
	await novel_interface.show_text_only("バイジュウは黙って頷いた。")
	novel_interface.character_2nd_light(0.35,"laugh")
	await novel_interface.show_dialog("そっか……手配するから、安心なさいな！", "ミルク")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("私が何か隠し事をしていても、\\nあなたはいつも見抜いてしまいますね。", "バイジュウ")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"sprite")
	await novel_interface.show_dialog("バイジュウちゃんの事に関して、\\n私を甘く見ちゃダメだよ～～！", "ミルク")
	await novel_interface.show_dialog("だから隠し事はしないでね？\\n計画を知らないと助ける事ができないから。", "ミルク")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("でも……", "バイジュウ")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("それとも、私を信用できないかな？", "ミルク")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("いいえ、そんな……\\nただ──", "バイジュウ")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("どのように否定すれば良いかと思考していると、\\n少女はいつの間にか\\n暖かい両腕によって抱きしめられていた。")
	novel_interface.show_character("baizhu_normal","think")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("milk_normal","gratified",0.25)
	await novel_interface.show_dialog("もう……分かってるよ……", "ミルク")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("…………", "バイジュウ")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("巻き込みたくないんでしょ？\\nああいう事に……", "ミルク")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("少女は俯いた。")
	novel_interface.character_light(0.35,"sad")
	await novel_interface.show_dialog("お父さんの事は、複雑過ぎますから……", "バイジュウ")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("ミルクはさらに強くバイジュウを抱きしめた。")
	await novel_interface.show_text_only("黒髪少女は頬を真っ赤にした。\\n\\n最初は小恥ずかしくなり押しのけようとしたが、\\n諦めてゆっくりと両手をおいた。")
	await novel_interface.show_text_only("言葉では表現できないような安らぎと\\n暖かい感覚が……徐々に彼女の心を満たす。")
	novel_interface.show_character("baizhu_normal","sad")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("milk_normal","gratified",0.25)
	await novel_interface.show_dialog("あんたはね、氷みたいに冷たい人間に見えるけど\\n本当はとっても情に脆いのよ。", "ミルク")
	await novel_interface.show_dialog("この艦艇で出会って間もないバカ達も\\n巻き込みたくないと思っている。", "ミルク")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("私は別に……", "バイジュウ")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"laugh")
	await novel_interface.show_dialog("ふふ、じゃあなんでさっきは\\n「諦めるのなら、今ならまだ間に合う」\\nってさ、あんな事を言ったの？", "ミルク")
	await novel_interface.show_dialog("あいつらを早く安全な所に帰したいからとしか、\\n考えられないけどな～～", "ミルク")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……大体、当たってます……", "バイジュウ")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("バイジュウはミルクの胸の中で、淡い微笑みを\\n浮かべた。\\nそして自分を抱いている女性を仰向けに見ると、\\nその目には光があった。")
	novel_interface.show_character("baizhu_normal","think")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("milk_normal","laugh",0.25)
	await novel_interface.show_dialog("隠し事はもうしないで。\\nバイジュウちゃんは真っ直ぐなんだから、\\n人を騙すなんてできないんだしさ。", "ミルク")
	novel_interface.change_2nd_expression("gratified")
	await novel_interface.show_dialog("私を信じて、本当の事を教えて……？", "ミルク")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("バイジュウは沈黙してしまう。")
	novel_interface.show_character("baizhu_normal","think")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("milk_normal","sprite",0.25)
	await novel_interface.show_dialog("まあ言わなくても、大体分かるんだけどね。\\n\\n私はバイジュウちゃんの心を見抜く、\\n超能力を持っているんだから！", "ミルク")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("そうですね……あなたは、聡明だから。", "バイジュウ")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("でもあんたの意図を推測すればするほど、\\n私は心配になっちゃうなぁ……", "ミルク")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("ごめんなさい……", "バイジュウ")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"sprite")
	await novel_interface.show_dialog("謝るより、行動で示せ～～っ！", "ミルク")
	novel_interface.character_light(0.35,"shock")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("…………", "バイジュウ")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("ミルクはバイジュウのおでこを突いた。")
	novel_interface.show_character("baizhu_normal","shock")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("milk_normal","laugh",0.25)
	await novel_interface.show_dialog("抱きしめてくれないの？", "ミルク")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……もう。", "バイジュウ")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("何か吹っ切れたのかバイジュウは手を伸ばし、\\nミルクの腰に手を回した。")
	novel_interface.show_character("baizhu_normal","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("milk_normal","laugh",0.25)
	await novel_interface.show_dialog("ほら笑って？\\nこんなにも可愛い……女の子なんだから。", "ミルク")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("水面に浮上した潜水艦は、冷たい海流の中を\\n静かに通り抜けていく。")
	await novel_interface.show_text_only("時間的には真夜中なのだが、空は依然として\\n夕焼けのような色が夜の色と混ざり合っている。")
	await novel_interface.show_text_only("しかしその鮮やかさも、今のミルクには\\n負けてしまうだろう。\\n暖かくて明るい、朝日のようないつもの笑顔。")
	await novel_interface.show_text_only("バイジュウにとって船外の景色の美しさよりも、\\nそれは印象的な一幕であった。")
	novel_interface.show_character("baizhu_normal","shy")
	await novel_interface.show_dialog("（つぶやき）…君の方が可愛いよ。", "バイジュウ")

	print("=== 深海恐惧症篇第13话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
