# bathophobia_ep09.gd - 深海恐惧篇第9话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep09_script()

func play_script():
	pass

func bathophobia_ep09_script():
	novel_interface.change_background("res://assets/images/bg/Baizhu/liliu_observation.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("Stando alla stazione di controllo in cima alla banca di fronte alla piattaforma, Mariru può vederci al primo piano e nella sala di osservazione dei Senatori.")
	await novel_interface.show_text_only("Dalla sala provengono tre avvertimenti profondi e bassi, che indicano che Mariru è pronto.")
	await novel_interface.show_text_only("Raphael saluta al Mariru. Annie e io stiamo vigili accanto a lei.")
	await novel_interface.show_dialog("Progetto Arca, esperimento numero uno.", "Mariru")
	await novel_interface.show_dialog("Lo scudo verrà disattivato tra dieci secondi.", "Mariru")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_awaitOrders.png")
	await novel_interface.show_text_only("Sulla base del tavolo operativo appare un conto alla rovescia con numeri rossi.")
	await novel_interface.show_text_only("La chiusa è chiusa e i gradini si ritraggono nel muro.")
	await novel_interface.show_text_only("Il rumore dello stridore degli ingranaggi proviene dall'alto della sala, e le armi automatiche nascoste nel soffitto sono puntate verso la scrivania, pronte a sparare in qualsiasi momento.")
	await novel_interface.show_text_only("Io, come un pesce nelle profondità dell'oceano, sto in mezzo all'oscurità.")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("Mi sento un criminale condannato...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Con così tante armi puntate contro di me, mi sento estremamente teso.")
	novel_interface.show_character("anne_battle","smile")
	await novel_interface.show_dialog("Rilassati, Ren. Ti proteggerò!", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Anche Annie sembra nervoso... Le sue dita premono sulla mazza da baseball così forte che le unghie diventano pallide, ma mi continua a confortare.")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("Uff, codardo.", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Nel momento in cui il timer arriva a zero, Raphael tira rapidamente la leva.")
	await novel_interface.show_text_only("Lo scudo trasparente che circonda la piattaforma si restringe rapidamente verso il basso prima di scomparire.")
	await novel_interface.show_text_only("Mentre il Pilastro di Lapislazzuli viene leggermente sollevato, mi colpisce una sensazione più forte.")
	await novel_interface.show_text_only("Mi sento come se il sangue iniziasse a ribollire e all'improvviso ho un impulso inspiegabile.")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("(Ahi… mi fa più male la pancia…)", "Lian")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("(Se chiedo una pausa per il bagno, probabilmente vorranno uccidermi…)", "Lian")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/bedstand.png")
	await novel_interface.show_text_only("Lo spazio sopra di noi improvvisamente trema e un raggio di luce passa rapidamente sopra le nostre teste e corre fino alla fine del corridoio.")
	await novel_interface.show_text_only("Poi, due brevi ronzii mi colpiscono il petto, segnalando che il sistema finto è avviato.")
	await novel_interface.show_text_only("Lo strato di mimetizzazione ottica in alto nella sala e il vetro appositamente trattato della sala di osservazione assicurano che nessun suono venga diffuso ai senatori.")
	await novel_interface.show_text_only("Ai loro occhi, Raphael, Annie e io dovremmo sparire all'istante insieme al Pilastro di Lapislazzuli.")
	await novel_interface.show_text_only("Dopodiché vedranno le immagini che abbiamo falsificato.")
	await novel_interface.show_text_only("Lo spettacolo è in corso. Proprio al centro del palco, non ho altra via d'uscita.")
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("Devo sfidarlo...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Faccio un passo avanti e tendo con cautela la mano.")
	await novel_interface.show_text_only("Mentre la mia mano si avvicina al pilastro, chiudo nervosamente gli occhi e trattengo il respiro\\nFino a quando le mie dita toccano il pilastro.") #换行问题
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_awaitOrders.png")
	await novel_interface.show_text_only("…")
	await novel_interface.show_text_only("…?")
	await novel_interface.show_text_only("Apro lentamente gli occhi.")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("Sembra che... non sia successo niente.", "Lian")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Appoggio tutto il palmo della mano sul pilastro. Sembra marmo.")
	novel_interface.character_light(0.35,"upset")
	await novel_interface.show_dialog("Mhm...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Provo un'altra angolazione e gli do una spinta forte.\\nIl pilastro, che pesa più di quindicimila libbre, rimane immobile.")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("Tsk!", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphael mi disprezza.")
	await novel_interface.show_text_only("Che non accada nulla è stato il risultato che desidero di più tra tutte le ipotesi che abbiamo fatto durante la riunione preparatoria:")
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("(Ma perché… mi sento un po’ in imbarazzo…)", "Lian")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Mentre la mia mano è ancora sul pilastro, l’atmosfera è imbarazzante. Proprio mentre sto pensando di premere più forte, il mio cuore improvvisamente si contrae bruscamente.")
	await novel_interface.show_text_only("Quasi nello stesso tempo il pilastro trema.")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Poi, il pilastro si stacca dalla mia mano, lasciando un piccolo spazio che si sta lentamente allargando.")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("—Eh?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("L'alta piattaforma e la base del pilastro scricchiolano, producendo rumori profondi e sommessi...")
	await novel_interface.show_text_only("Il tesoro nazionale di Salmonton, un manufatto che simboleggia l'illuminazione degli esseri umani durante il Rinascimento: il pilastro di lapislazzuli di Tesheim...")
	await novel_interface.show_text_only("… sta lentamente crollando nella direzione in cui sto premendo…")
	await novel_interface.show_text_only("E sta cadendo sempre più velocemente.")
	await novel_interface.show_text_only("Bum——!!!")
	await novel_interface.show_text_only("L'enorme scoppio avviene quando il pilastro si scontra con la piattaforma metallica e si rompe in due pezzi. Il pezzo più lontano scivola anche qualche centimetro in avanti.") #缩减符号
	await novel_interface.show_text_only("Piccoli frammenti si sparpagliano e il pezzo più lontano rotola addirittura nella pozza di fronte.")
	await novel_interface.show_text_only("C'è un lungo silenzio...")
	await novel_interface.show_text_only("Da un po' di tempo, anche Raphael ha perso la sua solita arroganza, apparendo estremamente scioccata.")
	await novel_interface.show_text_only("Poi si gira lentamente verso di me.")
	await novel_interface.show_text_only("Posso vedere il fuoco che arde nei suoi occhi.")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("No, io... io non...", "Lian")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_flare.png")
	await novel_interface.show_text_only("Quando faccio fatica a pensare a come salvarmi il sedere, il suono di un campanello a vento arriva dal nulla.")
	await novel_interface.show_text_only("I frammenti che giacciono sul pavimento si dividono in pezzi ancora più piccoli e cominciano a fluttuare come fogli di carta portati via da una folata di vento.")
	await novel_interface.show_text_only("Riflettendo archi colorati di luce, i frammenti del pilastro formano diversi anelli e fluttuano verso l'alto.")
	await novel_interface.show_text_only("Alla fine, tutti i pezzi rotti si dissipano nell'aria, lasciando numerosi anelli di luce fluttuanti che illuminano l'intera sala.")
	novel_interface.show_character("anne_battle","happy")
	await novel_interface.show_dialog("Ehi...", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Non posso fare a meno di toccare un anello formato da piccoli frammenti—")
	await novel_interface.show_text_only("L'anello si rompe immediatamente in punti di luce dorati.")
	await novel_interface.show_text_only("I punti fluttuanti si disperdono come polvere.")
	await novel_interface.show_text_only("Poi si concentrano e creano una luce sempre più abbagliante...")
	await novel_interface.show_text_only("Dalla luminosità che fa male agli occhi, davanti a me appare un'adolescente dai capelli dorati.")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("…!!!", "Lian")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	await novel_interface.show_text_only("Con le braccia spalancate, sta tranquillamente di fronte a me... Ma non riesco proprio a distogliere lo sguardo da questa scena affascinante.")
	await novel_interface.show_text_only("C'è un vago profumo di fiori d'arancio e viola nell'aria.")
	await novel_interface.show_text_only("La ragazza apre lentamente gli occhi.")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("Che \"risultato\" intrigante e favoloso...", "Ragazza bionda")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Si guarda intorno.")
	novel_interface.character_light()
	await novel_interface.show_dialog("Siamo… tempi moderni!?", "Ragazza bionda")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Ai suoi occhi, una crescente eccitazione sta sostituendo la vuota confusione.")
	novel_interface.character_light()
	await novel_interface.show_dialog("Acqua e carbonio, cloruro di sodio e zolfo, silicio e ferro…", "Ragazza bionda")
	await novel_interface.show_dialog("Hanno creato un posto così bello...", "Ragazza bionda")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Guarda incredula le sue mani tremanti.")
	novel_interface.character_light()
	await novel_interface.show_dialog("Il tocco del corpo…", "Ragazza bionda")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La ragazza sente lentamente il suo corpo da cima a fondo.")
	await novel_interface.show_text_only("All'improvviso mi rendo conto che non dovrei guardare, quindi mi giro immediatamente dall'altra parte.")
	await novel_interface.show_text_only("Ma non posso fare a meno di lanciarle uno sguardo...")
	await novel_interface.show_text_only("Lei... la sta addirittura toccando... lei...!!")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("…", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","perspire")
	await novel_interface.show_dialog("…", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("Anche questo... viene ricreato?", "Ragazza bionda")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("…La luce era così forte che non vedevo nulla!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Abbiamo tutti i tipi di piani di emergenza, ma per un po' nessuno di noi tre sa cosa fare dopo.")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("Quindi...", "Ragazza bionda")
	novel_interface.character_dark()
	await novel_interface.show_text_only("La ragazza bionda guardò Anne e Raphael, che erano ancora tesi, e il suo sguardo cadde su di me, che avevo un'aria spenta.")
	novel_interface.character_light()
	await novel_interface.show_dialog("Sei stato tu a realizzare questo miracolo?", "Ragazza bionda")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La ragazza atterra lentamente sul pavimento e fa rispettosamente un passo indietro.")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("…Eh? \\n(Non so dove guardare!!)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("Oppure hai realizzato tu questo contenitore per la mia anima?", "Ragazza bionda")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("Ah... forse... sì?", "Lian")
	await novel_interface.show_text_only("Scusa, ho appena dato una piccolissima spinta al pilastro!")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La ragazza si mette una mano sul petto e si inchina leggermente verso di me.")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("Quindi, se vuoi...", "Ragazza bionda")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Mi guarda negli occhi. \\nLeggo un forte desiderio nei suoi occhi azzurri.")
	novel_interface.character_light()
	await novel_interface.show_dialog("Per favore, concedimi tutta la tua essenza...", "Ragazza bionda")
	await novel_interface.show_dialog("Maestro.", "Ragazza bionda")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Maestro?", "Raphael & Annie")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("Eeeeeessenza?!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fermare-!")
	await novel_interface.show_text_only("Ferma la strana immaginazione!!!")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("“Alchimia, la ricerca della saggezza degli elementi e della vita.”", "Ragazza bionda")
	await novel_interface.show_dialog("L'uomo in grado di ricostruire un corpo ed evocare un'anima deve possedere la verità che non possiedo.", "Ragazza bionda")
	await novel_interface.show_dialog("Io… Henriette Kunhardt, sono pronta ad essere una serva della verità…", "Ragazza bionda")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Heinrich si ferma improvvisamente e guarda solennemente uno spazio aperto nell'atrio.")
	await novel_interface.show_text_only("Seguendo il suo sguardo non vedo altro che pilastri.")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("(Aspetta. Ha detto qualcosa riguardo s...servo?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La ragazza sospira.")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("Trovato così in fretta.", "Henriette")
	await novel_interface.show_dialog("Anche con un nuovo corpo, sono ancora vincolato dal contratto...", "Henriette")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ha appena finito di parlare quando all'improvviso la sala inizia a distorcersi pesantemente.")
	await novel_interface.show_text_only("I sensori nella custodia schermata inviano allarmi di soglia tutti in una volta e gli indicatori di stato diventano immediatamente rossi.")
	await novel_interface.show_text_only("Dall'alto arriva un rumore assordante di vetri che si infrangono.")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("Spara... Un flusso spaziotemporale...", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Dietro Heinrich appare uno specchio che ruota in senso antiorario, assomigliando a delle onde.")
	await novel_interface.show_text_only("La ragazza cade all'indietro e gradualmente si immerge nel vuoto.")
	novel_interface.show_character("anne_battle","perspire")
	await novel_interface.show_dialog("Ren, corri!", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ma è troppo tardi—")
	novel_interface.change_background("res://assets/images/bg/Baizhu/spaceTransfer.png")
	await novel_interface.show_text_only("Lo spazio che ci circonda è distorto e ruota lungo numerose superfici specchianti.")
	await novel_interface.show_text_only("—Poi sono sopraffatto dalla sensazione di assenza di gravità.")
	await novel_interface.show_text_only("Quando finalmente torno in me, mi rendo conto che stiamo cadendo.")
	await novel_interface.show_dialog("Aaaah—!!", "Lian")
	await novel_interface.show_text_only("L'unica cosa che ricordo prima di svenire è...")
	await novel_interface.show_text_only("Il mio sedere è freddo nel vento e mi fa ancora più male lo stomaco!")
	await novel_interface.show_text_only("Questo è…")
	await novel_interface.show_text_only("Il giorno peggiore di sempre!!!")
	
	print("=== 深海恐惧篇第9话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
