# bathophobia_ep09.gd - 深海恐惧篇第9话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep09_script()

func play_script():
	pass

func bathophobia_ep09_script():
	novel_interface.change_background("res://assets/images/bg/Baizhu/liliu_observation.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("マリルは対岸の高所にある制御台に立っている。\\n\\nあの場所は、1階にいる俺達と元老院がいる\\nモニタールームが同時に見える場所だ。")
	await novel_interface.show_text_only("広々としたホール内に、低い警報音が連続で\\n3回鳴った。\\nマリルによる準備完了の合図だ。")
	await novel_interface.show_text_only("ラファエルはマリルに軽く手を振り、\\n俺とアニーは始まるのを待ち構えている。")
	await novel_interface.show_dialog("──『方舟計画』　第一次実験開始。", "マリル")
	await novel_interface.show_dialog("10秒後に防壁を解除する！", "マリル")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_awaitOrders.png")
	await novel_interface.show_text_only("コンソールの台座に、赤いカウントダウンが\\n出現した。")
	await novel_interface.show_text_only("入口のゲートが重々しく閉まり、可変通路の橋も\\n壁の中に収納される。")
	await novel_interface.show_text_only("ホールの天井から歯車の噛み合う音が聞こえ\\n天井に隠蔽されていた自動銃器の隊列が、\\nコンソールに照準を合わせて待機状態に入る。")
	await novel_interface.show_text_only("光の照らされていない場所で立っている俺は、\\n\\nまるで深海魚みたいに、\\n黒い深海に浮いているかのようだった。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("気分は重罪人だな……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("多くの武器を向けられて、全身が落ち着かない。")
	novel_interface.show_character("anne_battle","smile")
	await novel_interface.show_dialog("大丈夫、私がレンちゃんを守るから！", "アニー")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("アニーも緊張しているのだろう……\\n\\nバットを強く握る彼女の手の爪に血の気がない。\\nそれにも関わらず、俺を慰めようとしてくれる。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("ふん、怯えている場合？", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("カウントダウンがゼロになったと同時に、\\nラファエルが迷いなくレバーを倒した。")
	await novel_interface.show_text_only("台座の周囲の透明な防壁が素早く底に消える。")
	await novel_interface.show_text_only("そして青金石柱の本体が微かに上昇し、\\n落ち着かない感覚がさらに強烈になる。")
	await novel_interface.show_text_only("体内の血液が騒ぎ出し、心の底から不可解な\\n衝動が昇ってきた。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("（うっ……お腹がもっと痛くなった……）", "小憐")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("（今トイレに行きたいと言ったら……）\\n\\n（きっと袋叩きにされちゃうよね……）", "小憐")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/bedstand.png")
	await novel_interface.show_text_only("突然、上方の空間が震える。\\n\\n一筋の閃光が俺達の頭上を通り抜けると、\\nその筋はホールの果てまで伸びていった。")
	await novel_interface.show_text_only("──胸元から短い振動が2回。\\nこれは偽装システムが起動した合図だ。")
	await novel_interface.show_text_only("ホール上空の光学迷彩とモニタールームの\\nガラスの仕切りは、二重の保険で音声も遮断。")
	await novel_interface.show_text_only("彼らの視界では俺達3人、そして青金石柱も\\n今の一瞬で消えたはずだ。")
	await novel_interface.show_text_only("代わりとして見せるのは、事前に用意した\\n偽造の画面。")
	await novel_interface.show_text_only("すでに大芝居は始まっている。\\n舞台の真ん中の俺に、もう逃げ場はない。")
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("やるしかない……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("俺は腹を括って前に出て、慎重に手を伸ばした。")
	await novel_interface.show_text_only("手を少しずつ前へと伸ばす。\\n\\n緊張して目を瞑り、俺は息を止めて……\\nそして指先が柱に触れるまで……") #换行问题
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_awaitOrders.png")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("…………？")
	await novel_interface.show_text_only("ゆっくりと目を開いてみる。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("特に変化がない……みたい。", "小憐")
	novel_interface.character_dark()
	await novel_interface.show_text_only("試しに手のひらを全部くっ付けてみた。\\n大理石のような感触だ。")
	novel_interface.character_light(0.35,"upset")
	await novel_interface.show_dialog("うっ……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("今度は角度を変えて、力強く押してみた。\\n\\n 7トンにもなる石柱は山の如く微動だにしない。")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("ははっ――", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("後ろから、ラファエルの呆れた声が聞こえた。")
	await novel_interface.show_text_only("事前の作戦会議で様々な対応策は用意したけど、何も起こらないのが俺の一番望ましい結果。")
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("（だけどなぜか……ちょっと情けない……）", "小憐")
	novel_interface.character_dark()
	await novel_interface.show_text_only("俺の手はまだ石柱に触れたままであるが、\\n雰囲気は少し気まずい。\\nもう少し力を入れようと思った瞬間──\\n心臓が急に激しく脈打った。")
	await novel_interface.show_text_only("ほぼ同時に、石柱が振動し始める。")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("そして、石柱が徐々に俺の手から離れ、\\n目の前から遠ざかっていく光景を目にした。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("────えっ？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("上昇した台座と石柱が接触する部分から、\\n嫌な予感を連想させる低い摩擦音が聞こえる……")
	await novel_interface.show_text_only("ルネサンス時代の人類啓蒙と覚醒を象徴する\\n偉大なる芸術品──\\nそして現在サモントンの国宝級文化財でもある\\n『トスハイム青金石柱』──")
	await novel_interface.show_text_only("そんな物が押した方向へゆっくり倒れていく……")
	await novel_interface.show_text_only("しかも倒れるスピードがますます速くなる。")
	await novel_interface.show_text_only("昸——！ ！ ！")
	await novel_interface.show_text_only("……………………大きな音がした。\\n\\n青金石柱が思いっきり金属製の台座に倒れ、\\nそのまま真っ二つに砕け散った。\\n砕けた先端が、前方へ何センチか滑っていく。") #缩减符号
	await novel_interface.show_text_only("割れた場所から、たくさんの破片が散らばり\\n一番遠くの物はそのまま前方の池に落ちる。")
	await novel_interface.show_text_only("…………………………………………………………\\n…………………………………………………………\\n…………………………そして長い沈黙。")
	await novel_interface.show_text_only("それまで傲慢な態度だったラファエルも、\\n唖然とした顔で立ち尽くしている。")
	await novel_interface.show_text_only("そして彼女はゆっくりと俺の方を向いた。")
	await novel_interface.show_text_only("目から鋼鉄板を寸断できそうな、\\n怒りの火炎を射出しているように見える。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("ち、ち、違う、お、俺じゃない……", "小憐")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_flare.png")
	await novel_interface.show_text_only("どうすれば命が助かるかを考えている最中、\\n虚空の中から風鈴のような音が聞こえてきた。")
	await novel_interface.show_text_only("地面に散らばった破片が音に合わせて、\\nさらに小さな破片に分裂していく……\\nそして、風に吹かれた紙片のように舞い始めた。")
	await novel_interface.show_text_only("破片は多彩な光を屈折させ、次第に空中に複数の\\n円環を形成すると、上へ上へと昇っていく。")
	await novel_interface.show_text_only("砕けた石柱が、完全に風化して空中に散るまで\\n無数の流動的な光の破片に照らされる。\\nホール内は色彩豊かな輝きに包まれた。")
	novel_interface.show_character("anne_battle","happy")
	await novel_interface.show_dialog("うわぁ……", "アニー")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("俺は思わず指先で、破片の円環の1つに触れた。")
	await novel_interface.show_text_only("触れると円環は砕け、金色の光の砂に変わる。")
	await novel_interface.show_text_only("流れる光が埃のように散っていく。")
	await novel_interface.show_text_only("そして光は中心へと集まり、\\nますます明るくなって……")
	await novel_interface.show_text_only("眩しい光の中から──────\\n\\n長い金髪の少女が俺の前に現れた。")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("……ッ！？！？！？", "小憐")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	await novel_interface.show_text_only("少女は両腕を広げ平然と俺の前に立っている……\\n\\n眼前に広がる不思議で絢爛とした景色から、\\n俺は目を離せなかった。")
	await novel_interface.show_text_only("──薄いオレンジの花とストックの香りがする。")
	await novel_interface.show_text_only("少女はゆっくりと目を開けた。")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("奇妙で華麗なる『錬成』……", "金髪の少女")
	novel_interface.character_dark()
	await novel_interface.show_text_only("彼女は辺りを見渡した。")
	novel_interface.character_light()
	await novel_interface.show_dialog("ここは……現世ッ！？", "金髪の少女")
	novel_interface.character_dark()
	await novel_interface.show_text_only("少女の目の色は一瞬で、茫然から興奮へ転じた。")
	novel_interface.character_light()
	await novel_interface.show_dialog("水と炭素、塩と硫黄、ケイ素と鉄……", "金髪の少女")
	await novel_interface.show_dialog("これほど完璧なまでに成し遂げるとは……", "金髪の少女")
	novel_interface.character_dark()
	await novel_interface.show_text_only("彼女は未だに信じられないように、\\n震える自らの手を見つめた。")
	novel_interface.character_light()
	await novel_interface.show_dialog("この肉体の感触は……", "金髪の少女")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女は上から下までゆっくりと自分の身体を\\n舐めるように撫でる。")
	await novel_interface.show_text_only("俺はマズいと思い、慌てて顔を背けた。")
	await novel_interface.show_text_only("そして尻目遣いに、少女を見る……")
	await novel_interface.show_text_only("その手、手が、触れているところは……！！")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("……", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","perspire")
	await novel_interface.show_dialog("……", "アニー")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("まさかここも……復元されたのかしら？", "金髪の少女")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("……眩しい謎の光で、全然見えないッ！！", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("いくつもの対応策は事前に用意していたが、\\nこの状況に俺達3人は戸惑いを隠せない。")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("では……", "金髪の少女")
	novel_interface.character_dark()
	await novel_interface.show_text_only("金髪の少女は緊張したままのアンとラファエルをちらっと見て、元気のない表情の私に視線を落とした。")
	novel_interface.character_light()
	await novel_interface.show_dialog("貴方が……貴方が、\\nこの奇跡を成し遂げた方でいらっしゃいますか？", "金髪の少女")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ゆっくりと降りてきた金髪の少女の足先が\\n地面に触れ、俺に向かって恭しく一歩退いた。")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("……えっ？\\n（俺は目線をどっちに向ければいいの！？）\\n（全然分からないのだけどっ！？）", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("あるいは貴方が、わたくしの魂のために\\n器を創造して下さったのでしょうか？ ", "金髪の少女")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("はあ……まぁ……そうなるの？", "小憐")
	await novel_interface.show_text_only("ごめんなさい。ただ軽く押しただけなんです！")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金髪の少女は片手を胸元に置き、\\n俺に向かって軽くお辞儀をする。")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("では、よろしければ……", "金髪の少女")
	novel_interface.character_dark()
	await novel_interface.show_text_only("金髪の少女は顔を上げ、真っ直ぐ俺を見つめた。\\n紺碧の瞳の中に無限の渇望を潜めるかの如く。")
	novel_interface.character_light()
	await novel_interface.show_dialog("どうか、貴方の精気をわたくしに\\n授けてください……", "金髪の少女")
	await novel_interface.show_dialog("『マスター』", "金髪の少女")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("マスター？", "ラファエルとアニー")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("精、精、精、精気ッッ？！？！？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("待て待て、落ち着け――ッ！！")
	await novel_interface.show_text_only("変な想像をしちゃダメだッ！！")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("「錬金術、元素と生命の理を求める知恵」", "金髪の少女")
	await novel_interface.show_dialog("肉体を再構成し、彷徨う魂を呼び戻せる者は、\\n\\n必然的にわたくしの及ばぬ真理を把握している\\nお方に違いありません。", "金髪の少女")
	await novel_interface.show_dialog("そしてわたくし……\\nハインリッヒ・クンラートは真理の奴隷……", "金髪の少女")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ハインリッヒと名乗った少女は、\\n全ての言葉を終えない内に止まった。\\n急に立ち上がり、ホールの広々としている方角を\\n真剣に見つめている。")
	await novel_interface.show_text_only("俺も彼女の視線を追ったが、柱以外は何もない。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("（それより彼女さっき「奴隷」って言ったよね）\\n\\n（……ど……何？）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("──金髪の少女が溜め息を吐いた。")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("こんなに早くも見つかってしまいましたか。", "ハインリッヒ")
	await novel_interface.show_dialog("たとえ新しい肉体になっても、\\nあの『契約』からは逃れられないのですね……", "ハインリッヒ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ハインリッヒの声がまだ終らない内に、\\nホールの空間が突然大きく歪み始めた。")
	await novel_interface.show_text_only("隔離ボックス内のセンサーが臨界警報を発し、\\n検測状態のランプが一瞬で赤色に切り替わる。")
	await novel_interface.show_text_only("上空から巨大な音……ガラスの割れる音がする。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("まずい……これは時空波動……", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ハインリッヒの背後に現れたのは、\\n波紋のような反時計回りの鏡面。")
	await novel_interface.show_text_only("少女は後ろへと倒れ、ゆっくりと虚空に\\n溶け込んでいく。")
	novel_interface.show_character("anne_battle","perspire")
	await novel_interface.show_dialog("レンちゃん、離れてッ！！！", "アニー")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("だが、遅かった────")
	novel_interface.change_background("res://assets/images/bg/Baizhu/spaceTransfer.png")
	await novel_interface.show_text_only("周りの空間は無数の鏡面と共に歪み、\\n既に回転を始めている。")
	await novel_interface.show_text_only("──そして訪れたのは、全身を襲う無重力感。")
	await novel_interface.show_text_only("気が付いた時には、俺達はすでに落下していた。")
	await novel_interface.show_dialog("うああああぁぁぁぁ――――ッ！！？", "小憐")
	await novel_interface.show_text_only("気を失う前に最後に覚えていた事は……")
	await novel_interface.show_text_only("お尻が風で冷やされて、更にお腹が痛くなった！")
	await novel_interface.show_text_only("今日は本当に……………………")
	await novel_interface.show_text_only("めちゃくちゃだッッ！！！")

	print("=== 深海恐惧篇第9话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
