# bathophobia_ep29.gd - 深海恐惧症篇第29话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep29_script()

func play_script():
	pass

func bathophobia_ep29_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Baizhu_Sickroom_Evening.png")
	await novel_interface.show_text_only("A enfermeira bate na porta.")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("Hum?","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("É hora da fisioterapia da Sra. Beth.","Enfermeira")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("Ah. Já está na hora?","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("A enfermeira sorri desculpando-se.")
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("Voltaremos amanhã—","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Antes que eu possa terminar a frase, meu peito vibra duas vezes.")
	await novel_interface.show_text_only("Ah, certo. Mariru não permitirá que eu visite novamente tão cedo...")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("(Tive que implorar inúmeras vezes antes de poder visitá-la hoje.)","Lian")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("Então... iremos embora agora, eu acho?","Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("Sim. Tomar cuidado.","Beth")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Depois de me despedir de Beth, arrasto Raphael e Annie relutantes para fora da enfermaria comigo.")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("Ah, esqueci uma coisa...","Lian")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Baizhu_Sickroom_Evening.png")
	await novel_interface.show_text_only("Volto correndo para o quarto de Beth, deixando as duas no corredor.")
	novel_interface.show_character("baizhu_normal","shock")
	await novel_interface.show_dialog("Você está de volta. E aí?","Beth")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("Hum... eu... \\n(Ah, isso é tão embaraçoso... )","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Respiro fundo e me preparo antes de subir.")
	await novel_interface.show_text_only("Pego a mão de Beth e escrevo uma série de números nela com meu protetor labial.")
	novel_interface.show_character("ren_battle","shy_left")
	await novel_interface.show_dialog("Meu número. Se precisar de algo, você pode... \\nVocê sempre pode entrar em contato comigo!","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ahhhh!\\nIsso foi tão embaraçoso!")
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("*Tosse*","Lian")
	await novel_interface.show_dialog("(Ainda assim... pensando nisso... carregando um protetor labial colorido em mim... )\\n(E escrever meu número na mão de uma garota... ambos são tão estranhos... )","Lian")
	novel_interface.change_expression("perspire1")
	await novel_interface.show_dialog("Uh, quero dizer... eu só queria...","Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_normal","shock")
	await novel_interface.show_dialog("…","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beth parece um pouco surpresa.")
	await novel_interface.show_text_only("É claro que ela ficaria surpresa!\\nO que eu estava fazendo?")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("(Eu não deveria ter voltado afinal...)","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Por que estou me estranhando? Apenas trocando números com uma garota, nada mais.\\nEm uma pesquisa de rua no ano passado, ficou entre os dez cenários mais românticos para homens...")
	await novel_interface.show_text_only("Ainda assim, quando estavam pensando em “trocar números com uma garota”, provavelmente não queriam dizer “escrever seu número na mão de uma garota em uma enfermaria de hospital com um protetor labial”.")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("(Acho que errei, hein...)","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Olho para a mão de Beth, com meu número rabiscado às pressas, sem saber como proceder.")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("Uh... Se isso deixa você desconfortável... \\nSinto muito!","Lian")
	await novel_interface.show_dialog("Vou limpar para você!\\n(E então aja como se nada tivesse acontecido!)","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Rapidamente tento borrar os números com os dedos.")
	novel_interface.show_character("baizhu_normal","shock")
	await novel_interface.show_dialog("…","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Eu a assustei...?")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("Hum, me desculpe se isso é um pouco direto, mas... \\nVocê é um menino, Ren?","Beth")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("Eh?","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Como ela poderia saber?")
	await novel_interface.show_text_only("Estou tão surpreso que congelo no meio de pegar um lenço de papel e acabo rasgando três lenços de uma vez.")
	await novel_interface.show_text_only("Mariru me avisou que eu não deveria deixar ninguém saber que na verdade sou... homem. Ou então...")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("Não tenho certeza, apenas minha intuição.","Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beth faz uma pausa e acrescenta:")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("Escrever seu número na minha mão e ficar tão nervoso com isso... nenhuma garota agiria assim.","Beth")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("Haha... \\nAcho que só... não sou muito feminina?","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Depois de finalmente tirar meu número das mãos de Beth, rio timidamente e corro em direção à porta.")
	await novel_interface.show_dialog("Ren—","Beth")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("O quê?","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Eu me viro, com o corpo rígido, rezando para que Beth esteja apenas brincando.")
	await novel_interface.show_text_only("Não posso deixá-la saber sobre minha verdadeira identidade!")
	await novel_interface.show_text_only("Para minha surpresa, Beth está sorrindo para mim da cama, com os olhos divertidos.")
	novel_interface.show_character("ren_battle","sob")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("baizhu_normal","mock",0.25)
	await novel_interface.show_dialog("Eu memorizei seu número.","Beth")
	novel_interface.character_light(0.35,"timid")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Uh __ELIPSIS__","Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Fico congelado no lugar, sem saber o que fazer.")
	novel_interface.show_character("ren_battle","timid")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("baizhu_normal","smile",0.25)
	await novel_interface.show_dialog("Também...","Beth")
	await novel_interface.show_dialog("Pedi a Mariru para investigar algo para mim depois que acordei.","Beth")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("O sorriso da garota parece desaparecer um pouco.")
	novel_interface.show_character("ren_battle","timid")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("baizhu_normal","sad",0.25)
	await novel_interface.show_dialog("Por mais que eu não queira acreditar, parece que meu pai deve ter... \\nescondido muitas coisas de mim.","Beth")
	await novel_interface.show_dialog("Se fosse você, o que faria nessa situação?","Beth")
	await novel_interface.hide_all_characters()
	await novel_interface.show_dialog("Com licença, senhorita...","Enfermeira")
	await novel_interface.show_text_only("A enfermeira está ficando impaciente.")
	novel_interface.show_character("anne_normal","happy")
	await novel_interface.show_dialog("Hora de ir, Ren!","Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Annie diz, enfiando a cabeça de fora.")
	novel_interface.show_character("ren_battle","smile")
	await novel_interface.show_dialog("Indo, vindo!","Lian")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("Uh, você estava dizendo...","Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("baizhu_normal","smile",0.25)
	await novel_interface.show_dialog("Está tudo bem. Não foi nada.","Beth")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("(Com certeza não me pareceu nada!)","Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("É melhor você ir agora.\\nAh, certo, adorei a almofada. Obrigado!","Beth")
	novel_interface.character_light(0.35,"gratified")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Bem…","Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Beth ainda parece um pouco fraca fisicamente.")
	novel_interface.show_character("ren_battle","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("baizhu_normal","smile",0.25)
	await novel_interface.show_dialog("Não se preocupe. Entrarei em contato com você.","Beth")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Beth acena para mim mais uma vez.")
	novel_interface.show_character("ren_battle","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("baizhu_normal","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Uh, ok... tchau!","Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Depois que as garotas desordeiras finalmente saem do quarto, Beth se senta sozinha na cama, olhando para sua mão.")
	await novel_interface.show_text_only("Ela ainda podia sentir o calor dos dedos macios de Ren nos seus.")
	await novel_interface.show_text_only("O calor parece vazar pela palma da mão dela. Ela sorri suavemente.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Baizhu_Cabin.png")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("<Cabine de avião>")
	await novel_interface.show_text_only("A aeronave está planando, pronta para partir da América do Sul.")
	await novel_interface.show_text_only("Beth fica sentada olhando pela janela, ouvindo a voz familiar vinda de seus fones de ouvido.")
	await novel_interface.show_text_only("Mariru contou a ela tudo sobre o que aconteceu na Base Snedronningen e o relato de Ren e Henriette sobre as imagens de vigilância.")
	await novel_interface.show_text_only("Este mundo é tão diferente do que ela lembrava de dezenove anos atrás. Wars e Substance H mudaram tudo o que ela conhecia, e ela não tem certeza de como lidar com isso.")
	await novel_interface.show_text_only("A única coisa que ela sente em casa neste mundo desconhecido é...")
	novel_interface.change_music("res://assets/audio/music/Everything's gonna be Okay.mp3")
	await novel_interface.show_dialog("“Bethy!”","Record Milk")
	novel_interface.show_character("baizhu_normal","mock")
	await novel_interface.show_text_only("A garota sorri fracamente, segurando o player com mais força.")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Depois que os agentes do SID recuperaram os dados do monitoramento do leite, eles copiaram a gravação e parte das informações para um jogador e as entregaram a Bai Baizhu.")
	await novel_interface.show_text_only("E agora, ela está reproduzindo a mensagem que Milk gravou antes de partirem para sua última missão juntos.")
	await novel_interface.show_dialog("O Natal é daqui a quatro meses. Já escolheu um presente para mim, Bethy?","Record Milk")
	await novel_interface.show_dialog("Ha, talvez eu esteja planejando muito à frente, hein?","Record Milk")
	await novel_interface.show_dialog("Mesmo assim, estou muito animado com as férias!","Record Milk")
	await novel_interface.show_dialog("... Não é estranho? Nós nos conhecemos há apenas um ano... mas parece que se passaram séculos.","Record Milk")
	await novel_interface.show_dialog("Isso não é exagero? Você provavelmente diria quando ouvir isso.","Record Milk")
	await novel_interface.show_dialog("Eu te conheço muito bem, Bethy!","Record Milk")
	await novel_interface.show_dialog("Ah. Lembra da primeira vez que nos conhecemos? Você me disse que a senha do cofre do professor era um par de números amigáveis.","Record Milk")
	await novel_interface.show_dialog("220 e 284. Ainda me lembro, até agora.","Record Milk")
	await novel_interface.show_dialog("Essa foi a primeira vez que percebi que algumas pessoas realmente usavam conceitos matemáticos para senhas seguras...","Record Milk")
	await novel_interface.show_dialog("Enfim, você com certeza confia com muita facilidade!","Record Milk")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Baizhu_Cafe.png")
	await novel_interface.show_dialog("Você poderia dizer que eu era um agente disfarçado, mas mesmo assim você vazou o segredo do professor.","Record Milk")
	await novel_interface.show_dialog("E depois disso, quando te convidei para um café... \\nVocê nem disse não!","Record Milk")
	await novel_interface.show_dialog("Qualquer pessoa com bom senso teria recusado!","Record Milk")
	await novel_interface.show_dialog("…","Record Milk")
	await novel_interface.show_dialog("Mas é isso que o torna especial aos meus olhos.","Record Milk")
	await novel_interface.show_dialog("Talvez o que os outros acham estranho seja normal para nós, né?","Record Milk")
	await novel_interface.show_dialog("E não há nada de errado com isso, certo?","Record Milk")
	await novel_interface.show_dialog("Às vezes, sinto que estamos fadados a nos encontrar.","Record Milk")
	await novel_interface.show_dialog("Você e eu... somos como um par de números amigáveis. Nós vamos tão bem juntos - ok, isso foi brega. Esqueça isso. Finja que não aconteceu.","Record Milk")
	await novel_interface.show_dialog("Bethy__ELIPSIS__","Record Milk")
	await novel_interface.show_dialog("Me desculpe por ter usado você naquela época...","Record Milk")
	await novel_interface.show_dialog("Se você quiser, deixo você me “usar” também, para que possamos ficar empatados.","Record Milk")
	await novel_interface.show_dialog("Gostaria de saber onde passaremos o Natal este ano?","Record Milk")
	await novel_interface.show_dialog("Aposto que depois que a missão terminar, eles vão nos trancar dentro de casa para treinar por meses novamente...","Record Milk")
	await novel_interface.show_dialog("Ugh, nosso chefe nunca nos dá descanso!","Record Milk")
	await novel_interface.show_dialog("Mas ouça, no próximo Natal...","Record Milk")
	await novel_interface.show_dialog("Ah, não vou te contar ainda. Ansiosa por isso, sim, Bethy?","Record Milk")
	await novel_interface.show_dialog("Haha, isso parece ridículo.","Record Milk")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("A gravação termina aí abruptamente.")
	await novel_interface.show_text_only("Beth pressiona o replay novamente.\\nDeixe a voz familiar encher seus ouvidos novamente.")
	await novel_interface.show_dialog("“Bethy!”","Record Milk")
	await novel_interface.show_text_only("…")
	novel_interface.show_character("baizhu_normal","cry")
	await novel_interface.show_text_only("A garota ri, embora soe mais como um gemido choroso.")
	novel_interface.change_expression("tear")
	await novel_interface.show_dialog("Manequim...","Beth")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Sonar.mp3")
	await novel_interface.show_text_only("O que é a Alma?")
	await novel_interface.show_text_only("Algum tipo de energia que contém o espírito? Algum tipo de existência quântica que não pode ser medida e observada?")
	await novel_interface.show_text_only("Ou apenas um conceito…")
	await novel_interface.show_text_only("Assim como o conceito de tempo na física—")
	await novel_interface.show_text_only("Talvez seja apenas uma ilusão... um sonho.")
	await novel_interface.show_text_only("Agora, a única questão é:")
	novel_interface.show_background("res://assets/images/bg/Baizhu/Baizhu_Niunai.png")
	await novel_interface.show_text_only("Quem é o sonhador?")
	
	print("=== 潜渊症篇第29话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
