# bathophobia_ep11.gd - 深海恐惧篇第11话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep11_script()

func play_script():
	pass

func bathophobia_ep11_script():
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("「現實」是什麼？")
	novel_interface.change_background("res://assets/images/bg/Baizhu/game.png")
	await novel_interface.show_text_only("我們所認為的現實，或許只是個線上遊戲。")
	await novel_interface.show_text_only("角色在登入時醒來、登出時沉睡、帳號刪除時死亡，")
	await novel_interface.show_text_only("卻漸漸產生了自己擁有「靈魂」的錯覺。")
	await novel_interface.show_text_only("理所當然地覺得那些被控制做出的種種行為，完全是出於自己的「自由意志」。")
	await novel_interface.show_text_only("公式、定律、語法、守則……在獲得自由之前，每個角色都要被灌輸這些不知由誰制訂的遊戲規則。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/unknowm.png")
	await novel_interface.show_text_only("即使某天，天空中出現了因渲染故障而撕裂的巨大馬賽克像素色塊──")
	await novel_interface.show_text_only("角色們也不會承認那是「未知」，而是編造各種神話或信仰來解釋。")
	await novel_interface.show_text_only("因為，承認「未知」意味著無法否定那最讓人擔憂的可能──")
	await novel_interface.show_text_only("所謂的「現實」，只是一種幻覺。")
	await novel_interface.show_text_only("一場夢。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/CauseAndEffect.png")
	await novel_interface.show_text_only("我慢慢睜開雙眼，發現自己身處一片朦朧之中。")
	await novel_interface.show_text_only("霧氣繚繞中，一串串水珠詭異地懸浮在半空。")
	await novel_interface.show_text_only("我伸手觸碰，那些「水珠」立刻消散於無形。")
	await novel_interface.show_dialog("這裡是……", "小憐")
	await novel_interface.show_text_only("我正站在某個平面上，能感到重力，低頭卻看不到地面，視覺上有一種奇妙的下墜感……")
	await novel_interface.show_text_only("背景的噪音摻雜著某種特殊異響，但在沒有參照座標的空間卻無法判斷方位。")
	await novel_interface.show_text_only("我抬頭，看到上空漂浮著一個樹狀的鏤空圖騰。")
	await novel_interface.show_text_only("圖騰在天空中像毯子一樣展開，發著微微的亮光。")
	await novel_interface.show_text_only("圖騰上的10個圓環緩慢轉動著，其中一個圓環散發出淡紅色。")
	await novel_interface.show_text_only("隨後，我的腳下也展開了由巨大的線條和銘文構成的圖形，構成了概念上的「地面」。")
	await novel_interface.show_text_only("仔細觀察，地面與天空都是一樣的圖騰，只是比從遠處看起來大得多。")
	await novel_interface.show_text_only("被以某種規則連接起來的圓環，每一個直徑都超過5公尺，圖騰中穿插著不知年代的銘文。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("（我是在……做夢嗎？ ）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("之前的訓練裡有學過判斷幻覺或夢境的方法。")
	await novel_interface.show_text_only("那個重要的「問題」是什麼來著……")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("──我，是怎麼來到這裡的？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("記憶慢慢開始浮現，剛才我們還在方舟基地，然後似乎突然開始墜落，然後……")
	await novel_interface.show_text_only("這裡，不是夢境。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("（和剛才出現的那個女生有關嗎？ ）", "小憐")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（一出現就叫我「主人」，而且還……）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("啊──\\n不對！ 現在才不是回味那種畫面的時候！")
	await novel_interface.show_text_only("安妮呢？ 拉斐爾呢？ ！")
	await novel_interface.show_text_only("她們兩個……應該和我一起被捲進來了！")
	await novel_interface.show_text_only("我在霧氣中緊張地四處張望，忽然一個溫暖的身體從身後抱住了我。")
	await novel_interface.show_dialog("不要緊張，主人──", "金髮少女")
	await novel_interface.show_text_only("出、出現了！ \\n那個一絲不掛的傢伙正從後面摟著我的腰！")
	await novel_interface.show_text_only("我很想質問她，又不知該不該回頭……")
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("（而且「主人」這個稱呼……）\\n（讓我想起動畫裡很多奇怪的角色啊！ ）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她似乎在摸索著什麼，手掌劃過我的腰，最後停留在我那不管如何訓練都長不出肌肉的小腹。")
	await novel_interface.show_text_only("一片寂靜中，只有她的呼吸輕拂著我的頭髮，我的心跳不斷加快……")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("（她、她要幹什麼？ ）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("哦～？","金髮少女")
	await novel_interface.show_text_only("她好像發現了什麼有趣的事情，手掌輕輕一按，我的肚子立刻不爭氣的發出「咕—」的一聲。")
	await novel_interface.show_text_only("在本安靜的環境中，這個聲音格外明顯。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("（欸？ ？為什麼……）", "小憐")
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("（感覺……好丟人啊啊啊啊！ ！！ ）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我撥開她的手，少女卻步伐輕巧地繞到我面前，用好奇的眼神打量著我。")
	await novel_interface.show_dialog("原來主人的身體也被改造過？ \\n……真是完美的煉金產物啊！","金髮少女")
	await novel_interface.show_text_only("我正想捂住眼睛，卻發現她已經穿好了衣服。")
	await novel_interface.show_text_only("等等，她剛說我也被改造過？ ！\\n而且，她這身裝扮……")
	await novel_interface.show_text_only("就算只用肉眼觀察，也能看出海因里希的服裝是以非常先進的材料製作的。")
	await novel_interface.show_text_only("無論質感還是設計，都不是16世紀的工藝可以達到的……不，就算是現在也不一定能做到。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("（難道莉琉的情報有誤？ ）\\n（還有，她是如何得知我身體的事情？ ）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("在我思考要先問哪個問題的時候，連衣帽突然被人用力向後扯。")
	await novel_interface.show_text_only("拉斐爾把我拉到身後，擋在我和金髮少女之間。")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("妳到底是誰？ ！", "拉斐爾")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("──哦？", "金髮少女")
	novel_interface.character_dark()
	await novel_interface.show_text_only("金髮少女看著拉斐爾，露出輕蔑的微笑。")
	novel_interface.character_light()
	await novel_interface.show_dialog("妳是問名字嗎？ \\n那種東西我用過上百個～", "金髮少女")
	await novel_interface.show_dialog("不過告訴妳也無妨，海因里希·昆哈特──這就是我的「契約」之名。", "金髮少女")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("別開玩笑了！", "拉斐爾")
	await novel_interface.show_dialog("姑且不說所有歷史記錄中，海因里希都是男性──", "拉斐爾")
	await novel_interface.show_dialog("就妳這身輕浮的打扮……\\n還有，妳是誤解了內衣的定義嗎？", "拉斐爾")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("海因里希是有名的煉金術士，絕不是妳這種不知羞恥、隨意叫別人主人、還……還說什麼精華……", "拉斐爾")
	novel_interface.character_dark()
	await novel_interface.show_text_only("拉斐爾的臉可疑地紅了一下。")
	novel_interface.character_light()
	await novel_interface.show_dialog("……妳到底是什麼人！", "拉斐爾")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她們對峙時，我忍不住從拉斐爾的背後偷偷觀察海因里希。")
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("（她上半身的衣服到底是什麼材質……）\\n（好驚人的包覆性！ 還能同時向不同方向抖嗎？ ）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突然間，海因里希與我目光相接，我低下頭滿臉通紅地拉著裙角，不敢再看她。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("哦？ 我以為煉成了這個完美軀體的主人，並不會對自己的作品產生動搖呢。", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不不不，我（以前）可是男孩子啊……")
	await novel_interface.show_text_only("海因里希說著拉了拉自己胸口的衣服。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("似乎比以前大了一些……是主人的興趣嗎？", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐爾回頭瞪了我一眼。")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("不！ ！我不是！ 我沒有！ ！", "小憐")
	novel_interface.change_expression("shy")
	await novel_interface.show_text_only("我只是不小心打碎了薩蒙頓的國寶級文物……")
	await novel_interface.show_dialog("還有，別叫我主人啦……叫我小憐就好。", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("小憐……？ \\n沒想到如此偉大的您……居然有著這樣可愛的名字。", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("那麼妳呢？ 妳真的是那個海因里希？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金髮少女猶豫了一下，看了看手腕上的數字，有點無奈地嘆了口氣。")
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("已經過400多年了啊……", "海因里希")
	novel_interface.character_dark()
	await novel_interface.show_text_only("等等，她手腕上有電子錶或者萬年曆之類的嗎！ ？")
	novel_interface.character_light()
	await novel_interface.show_dialog("過去，無論是研究、發表論文書籍還是行醫，我確實一直都使用男性身分。", "海因里希")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("所以歷史上有那些記載也是正常的。", "海因里希")
	await novel_interface.show_dialog("因為在我那個時代，大學不招收女生，教會也不准女人行醫──", "海因里希")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("至於煉金術……哼哼，如果女性的身分去研究，很快就會被宗教法庭找上門吧？", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("……\\n", "拉斐爾")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不知為何，最近聽到這些對女性的種種壓迫，我就會感同身受、憤憤不平。")
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("雖然要處理掉那些「教廷的警犬」易如反掌，但凡夫俗子不值得我浪費寶貴的時間。", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("好、好像……很厲害的樣子……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐爾的表情也有些動搖。")
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("等等，女生真的可以偽裝成男孩子上大學嗎？ \\n", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我忽然很好奇她用了什麼方法，說不定……")
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("我只是剪短頭髮、偽造幾封推薦信，再用個假名，就混進萊比錫大學了。", "海因里希")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","smile",0.25)
	await novel_interface.show_dialog("只是剪短頭髮就可以嗎？", "小憐")
	novel_interface.change_2nd_expression("wry_smile")
	await novel_interface.show_text_only("我又看了看她的胸部，400年前的人難道真的像電視劇裡一樣瞎到看不出女扮男裝？")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("當時我剛滿10歲，大學入學考的題目太簡單了。", "海因里希")
	novel_interface.character_dark()
	await novel_interface.show_text_only("海因里希不屑地笑了笑。")
	novel_interface.character_2nd_light(0.35,"wail")
	await novel_interface.show_dialog("啊！ 失敬失敬！", "小憐")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("無論在哪個時代，學霸都令人敬畏啊！ ！")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("那妳怎麼解釋現在這身裝扮？", "拉斐爾")
	await novel_interface.show_dialog("海因里希是醫生和煉金術士，但妳的護具和武器明顯是為了戰鬥配置的。", "拉斐爾")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希微笑著退後一步。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("——哦，抱歉，這是我的疏忽。", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希右手按在胸前，隨後她服裝的表面開始浮現出裂痕。")
	await novel_interface.show_text_only("藍白色的緞帶和各色晶石環繞在她的四周，圍繞金髮少女的身體發出光芒。")
	await novel_interface.show_text_only("青金色的光芒退卻之際，海因里希的身上漸漸……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("漸漸……咦？ ？")
	await novel_interface.show_text_only("拉斐爾瞬間衝到我面前緊緊捂住我的眼睛。")
	await novel_interface.show_dialog("停！ 我明白了──", "拉斐爾")
	await novel_interface.show_dialog("妳這暴露狂，快把衣服穿回去！ ！", "拉斐爾")
	await novel_interface.show_dialog("還有女裝癖，你看什麼看！", "拉斐爾")
	await novel_interface.show_text_only("都被妳遮住了，我能看見什麼啦！")
	novel_interface.show_background("res://assets/images/bg/Baizhu/CauseAndEffect.png")
	await novel_interface.show_text_only("拉斐爾移開手掌時，海因里希已經恢復了剛才的裝扮。 唉……真可惜都沒看到")
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("這是魔法戰服，和主人身上的類似，只不過製造者是更高階的存在。", "海因里希")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("至於款式，可能是「那位」的惡趣味……", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("「那位」？", "拉斐爾")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("我曾經以煉金之法，製造了這個空間的「門」。", "海因里希")
	await novel_interface.show_dialog("但凡人窺視真理總要付出代價，因此「那位」與我的靈魂強行定下了契約……", "海因里希")
	novel_interface.character_dark()
	await novel_interface.show_text_only("海因里希的表情有些無奈。")
	novel_interface.character_light(0.35,"bored")
	await novel_interface.show_dialog("（嘟嚷）上次我明明已經把身體炸得完全粉碎，契約居然還能以新的肉體啟動……", "海因里希")
	await novel_interface.show_dialog("真是陰魂不散……", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("？", "小憐")
	novel_interface.character_dark()
	await novel_interface.show_text_only("我正因為海因里希說的話而感到疑惑，安妮顫抖的聲音突然從濃霧中傳來。")
	await novel_interface.show_dialog("小憐──", "安妮")
	novel_interface.character_light(0.35,"solemn")
	await novel_interface.show_dialog("安妮？ ！", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我們循聲跑過去，發現安妮正縮成一團蹲在地上全身不停地發抖。")
	await novel_interface.show_dialog("救、救我……", "安妮")
	await novel_interface.show_dialog("……我不要、不要……", "安妮")
	await novel_interface.show_text_only("我連忙上前安撫安妮，在我的手接觸到她身體的一剎那——")
	await novel_interface.show_text_only("一股無形但柔軟的東西迅速滑過了我的手背，帶著黏稠的熱浪迅速遠離。")
	await novel_interface.show_text_only("我環顧四周，並沒有發現什麼異常，只有海因里希一臉驚訝地注視著我。")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("沒事的，安妮！", "小憐")
	novel_interface.change_expression("solemn")
	await novel_interface.show_dialog("安妮？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("顫抖的安妮顯然很不對勁。")
	await novel_interface.show_text_only("我能夠理解對未知空間的擔憂……但是四周空曠完全沒有敵人蹤影。")
	await novel_interface.show_text_only("我只能抱緊安妮，試著給她一些安慰。")
	await novel_interface.show_text_only("拉斐爾看到安妮的狀態，轉向海因里希。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("妳剛才說的「這個空間」，是不是「因果的裂縫」？", "拉斐爾")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("這是刻印在「生命之樹」上的名字……", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("「生命之樹」？", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("擅自把我們帶到這種地方，妳到底想做什麼？", "拉斐爾")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希聳了聳肩。")
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("不是我。", "海因里希")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("事實上，妳們本來不可能出現在這裡的……", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("哎？", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("除非是「那位」……或者更高階存在的意志。", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("妳說的「那位」究竟是……", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("按照契約，我不能直呼其名，但「那位」的名字實在太多了。", "海因里希")
	await novel_interface.show_dialog("「真理」、「道路」、「門」。", "海因里希")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("從最初……到最終。", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("……？ ！！", "拉斐爾")

	print("=== 深海恐惧篇第11话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
