# bathophobia_ep15.gd - 深海恐惧篇第15话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep15_script()

func play_script():
	pass

func bathophobia_ep15_script():
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Submarine_centralControlRoom.png")
	await novel_interface.show_dialog("Ah-choo…", "Beth")
	await novel_interface.show_text_only("Resting her head on the desk, the girl could have dozed off had it not been for this sneeze.")
	await novel_interface.show_text_only("Outside the submarine window is the polar night, and she can't tell the time by the color of the sky.")
	await novel_interface.show_text_only("Beth looks at the screen and realizes it's only a few hours after her encounter with the deep-sea monster.")
	novel_interface.show_character("baizhu_normal","sad")
	await novel_interface.show_dialog("… Am I doing the right thing?", "Beth")
	await novel_interface.show_dialog("(Using her to find the truth for myself…)", "Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Without noticing, Beth takes a glance at the notebook in her hand.")
	novel_interface.show_character("baizhu_normal","sad")
	await novel_interface.show_dialog("(If father were here…)", "Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("—He would never waver because of such kind of emotions.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/baizhu_father.png")
	await novel_interface.show_text_only("Thinking of her father's strong hands, Beth slowly clenches her fist.")
	await novel_interface.show_text_only("The notebook, full of obscure texts, once belonged to her adoptive father.")
	await novel_interface.show_text_only("He was a tall, silent and devoted biologist who was strict with both Beth and himself.")
	await novel_interface.show_text_only("Because of Beth's special ability, he arranged rigorous trainings for her apart from her schoolwork.")
	await novel_interface.show_text_only("Beth remembers that she had to work extra hard every day to reach the goals set by her father.")
	await novel_interface.show_text_only("What she expected most was the occasional smile of recognition on his serious face.")
	await novel_interface.show_text_only("Without much tenderness, the reserved man had been protecting her in his own way…")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("—As if preparing her for some inescapable fate…")
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Submarine_centralControlRoom.png")
	await novel_interface.show_text_only("On her 12th birthday, Beth received an anonymous package. Inside it was this notebook—and the news of her father's death.")
	await novel_interface.show_text_only("A gas explosion killed more than 30 people, including Beth's only remaining family member in the world.")
	novel_interface.show_character("baizhu_normal","puzzled")
	await novel_interface.show_dialog("…", "Beth")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Lips trembling, Beth mouths a silent name.")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("The clues behind this name made her realize that her father's death was not an accident as officially reported.")
	await novel_interface.show_text_only("The lonely girl had to dry her tears and grow up quickly to survive the unknown dangers.")
	await novel_interface.show_text_only("—Her father said in the notebook that her special ability would expose her to danger and make her the target of the gang.")
	await novel_interface.show_text_only("The package would only be sent out when he could no longer protect her…")
	novel_interface.show_character("baizhu_normal","sad")
	await novel_interface.show_dialog("(Why would people crave for… such kind of ability…)", "Beth")
	await novel_interface.show_dialog("(Isn't this more of a curse…)", "Beth")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Beth looks at her palm. Several balls of silver lights are bouncing over her fingers.")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beth knows she is different ever since she could remember things—but not because of her special ability.")
	await novel_interface.show_text_only("She has an eidetic memory for numbers even as a child. She can do mental math much faster than others and is keenly interested in machinery.")
	await novel_interface.show_text_only("But her father asked her to keep a low profile and act as an ordinary kid so as to cover up her special ability.")
	await novel_interface.show_text_only("After he died, Beth decided not to hide herself anymore.")
	await novel_interface.show_text_only("A year later, she was admitted to a prestigious university under special permission, an exception made for the first time in years.")
	await novel_interface.show_text_only("She studied hard and read a lot, but couldn't find the answer in either books or classes.")
	novel_interface.show_character("baizhu_normal","sad")
	await novel_interface.show_dialog("(Why am I different…)", "Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She kept learning and thinking, as if trying to satisfy her long-suppressed curiosity all at once.")
	await novel_interface.show_text_only("She didn't realize that she was thus labeled as arrogant, indifferent and unapproachable.")
	await novel_interface.show_text_only("Gradually, people turned their back on her, but she didn't care.")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("(Otherwise, I wouldn't have met you…)", "Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She met Silvia in an accident.")
	await novel_interface.show_text_only("It took Beth just minutes to figure out that Silvia was an investigator disguised as a student. Her mission was to search for illegal Substance H on campus.")
	await novel_interface.show_text_only("She knew that Silvia's name and experiences could all be fake, but was still attracted by her careless and cheerful personality.")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("(She is… different.)", "Beth")
	novel_interface.character_dark()
	await novel_interface.show_text_only("She knows me better than anyone else…")
	novel_interface.character_light()
	await novel_interface.show_dialog("(Although she is used to disguising herself to others…)", "Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She has truly opened her heart to me without any reservation.")
	await novel_interface.show_text_only("But neither of them had expected that their friendship would cause the attention of the organization behind Milk.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Knowing she was the adoptive daughter of the famous biologist, Milk's boss invited her to join the Antarctic mission.")
	await novel_interface.show_dialog("(I intended to decline…)", "Beth")
	novel_interface.show_background("res://assets/images/bg/Baizhu/milkBase.png")
	await novel_interface.show_text_only("In an underground base of the Squad.")
	await novel_interface.show_text_only("What made her change her mind and decide to join was a symbol on the mission guide—")
	await novel_interface.show_text_only("A symbol that she saw in her father's notebook.")
	await novel_interface.show_text_only("A creepy black eyeball representing a secret religious organization.")
	await novel_interface.show_text_only("Her father recorded his contact with people from that organization. They had shown the intention of mobilizing people with special ability and creating a militant group.")
	await novel_interface.show_text_only("The plan was named Project Ningen.")
	await novel_interface.show_text_only("After documents from her orphanage fell into their hands, Beth had been on the top wanted list of Project Ningen.")
	await novel_interface.show_text_only("As a result, her father became a target of this dangerous organization.")
	novel_interface.show_character("baizhu_normal","stare")
	await novel_interface.show_dialog("(Ningen… the Antarctic.)", "Beth")
	await novel_interface.show_dialog("(The Snow Queen Base in the Antarctic…) \\n(It's named after a story in Andersen's Fairy Tales.)", "Beth")
	await novel_interface.show_dialog("In Danish it's Snedronningen \\nOr Snedron-Ningen", "Beth")
	await novel_interface.show_dialog("(Not a coincidence.)", "Beth")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("So your Boss and the gang are going after the same thing…", "Beth")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_normal","sprite")
	await novel_interface.show_dialog("By the look on your face… this gang seems to be tougher than others on the Blacklist…", "Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beth nods, but she doesn’t want to talk further.")
	novel_interface.show_character("baizhu_normal","sad")
	await novel_interface.show_dialog("Sorry. I joined this mission out of selfish motives.", "Beth")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_normal","sprite")
	await novel_interface.show_dialog("Well, I know that.", "Milk")
	novel_interface.change_expression("pleased")
	await novel_interface.show_dialog("But Boss just wants you to carry on your father's research on marine life.", "Milk")
	await novel_interface.show_dialog("So it's a win-win.", "Milk")
	novel_interface.change_expression("sprite")
	await novel_interface.show_dialog("As for your selfish motives… I know you're so charmed by me that you decide to stay here.", "Milk")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("Oh, that's too much pressure for me!", "Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Milk said and blew a kiss towards Bai Yan, which made Bai Zhu smile.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("What she doesn't notice is a fleeting gloom in her friend's clear eyes.")
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Submarine_centralControlRoom.png")
	await novel_interface.show_text_only("She still feels guilty when she thinks of the moment she signed the paperwork.")
	novel_interface.show_character("baizhu_normal","sad")
	await novel_interface.show_dialog("(I was… using her.)", "Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beth sits down at the desk, draws out a pen, and stares at the open notebook.")
	await novel_interface.show_text_only("Valuable are the useful ones.")
	await novel_interface.show_text_only("—She jots down her thought.")
	await novel_interface.show_text_only("You told me this… And I've always agreed with you…")
	await novel_interface.show_text_only("Use others or be used unscrupulously \\n“This is something you take for granted…\"")
	await novel_interface.show_text_only("It only depends on who has a higher value.")
	await novel_interface.show_text_only("There's no need to explain. Just focus on your goal.")
	await novel_interface.show_text_only("Only such a simple relationship can keep you safe from most people.")
	await novel_interface.show_text_only("Beth pauses.")
	await novel_interface.show_text_only("But you also told me that there are still—")
	await novel_interface.show_text_only("Someone who wants to be used by you no matter what. \\n\"And someone whom you don't want to use under any circumstances.\"")
	await novel_interface.show_text_only("Thinking of this, a faint smile tugs on her lips.")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("(Guilt? It's a feeling that must be discarded.)", "Beth")
	await novel_interface.show_dialog("(Then is it… affection?)", "Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beth closes her diary.")
	await novel_interface.show_text_only("Now she has found her answer.")
	await novel_interface.show_text_only("She looks out of the window and finds the dark blue sky grows deeper, almost merging into the infinite sea.")
	await novel_interface.show_text_only("Suddenly, an emergency alarm goes off across the vessel.")
	await novel_interface.show_text_only("Attention, all crew. Directive changed. Report to the meeting room in ten minutes.")
	await novel_interface.show_text_only("Repeat. Directive changed…")
	await novel_interface.show_text_only("Beth takes a deep breath, puts away the notebook, and hurries out of the room.")

	print("=== 深海恐惧篇第15话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
