# bathophobia_ep21.gd - 深海恐惧症篇第21话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep21_script()

func play_script():
	pass

func bathophobia_ep21_script():
	novel_interface.change_music("res://assets/audio/music/Barrier Maze.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Corridor.png")
	await novel_interface.show_text_only("The strange figures that have suddenly shown up on the corridor make a beeline for us.")
	await novel_interface.show_text_only("They’re totally silent—besides the sound of rustling fabrics and pattering footsteps. Do they even need to breathe?")
	await novel_interface.show_text_only("I grip my weapon tight, mentally preparing myself. That’s when strong beams of light shoot out of Henriette’s battle suit. She disappears from sight in a flash, leaving behind nothing but a poof of bright smoke.")
	await novel_interface.show_text_only("While I was still stunned, Heinrich had already dodged in front of one person and struck one of the women on the breastplate with the back of his lapis lazuli sword.")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("Wow, she’s got some moves!","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("The loud, muffled sound of her weapon hitting its mark echoes off the corridor walls. I swear my chest hurts just from hearing it.")
	await novel_interface.show_text_only("Her target drops to the ground like a wooden puppet and rolls a distance away.")
	await novel_interface.show_text_only("Any human would have instinctively moved to protect themselves from further injury—yet this puppet-girl does nothing of the sort.")
	await novel_interface.show_text_only("Once she stops rolling, she simply leaps up, chest dent and all, and charges back at us.")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("…!","Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Realizing that these are no ordinary enemies, Henriette turns around, pierces through the heels of three of them in lightning speed.")
	await novel_interface.show_text_only("The three, tendons severed, crumple to the ground—yet they continue crawling towards us in eerily silent, spasming movements.")
	await novel_interface.show_text_only("They don’t look that scary on first sight, but the fact that they’re showing distinctly non-human characteristics is... very disturbing, to say the least.")
	await novel_interface.show_text_only("They look human. They don’t act human. That’s creepy as hell.")
	await novel_interface.show_text_only("After confirming that the enemies will no longer pose a threat, Raphael moves forward in attempt to see what the matter is with them.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Suddenly, the ground begins trembling again.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Second_Earthquake.png")
	await novel_interface.show_dialog("Another earthquake?","Henriette")
	await novel_interface.show_text_only("This time, the quake is more intense, and lasts much longer.")
	await novel_interface.show_text_only("Along with the tremors, the lights in the corridor blink on and off, following what sounds like shrill screeching—or maybe metal being yanked on.")
	await novel_interface.show_text_only("The enemies on the ground seem to turn into... transparent liquid? Foam? Right in front of our eyes.") #换行问题
	await novel_interface.show_text_only("The liquid then begins to boil and bubble, as if it were on a teppanyaki board. Within seconds, what were formerly human-shaped figures had evaporated into nothingness.")
	await novel_interface.show_text_only("They leave no trace at all on the cold floorboards. It’s like those bizarre girls never existed.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Reference_Room_Old.png")
	await novel_interface.show_text_only("Our surroundings seem to have changed after the earthquake as well.")
	await novel_interface.show_text_only("The wooden ornaments in the archive room have crumbled away, becoming mere sawdust floating in the air. The paint on the walls, too, has peeled away.")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("... Huh?","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("It’s still the same archive room...")
	await novel_interface.show_text_only("But the lights are off. The tiles on the ground are no longer shiny. And the items on the shelf—arranged completely differently.")
	await novel_interface.show_text_only("Behind the thick, industrial-looking steel beams, another sound-sensing surveillance camera pointed its dark lens at us.")
	await novel_interface.show_text_only("On the wall is a detailed topographic map of Antarctica, and on the desk a notebook recording changes in atmospheric data.")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("What... what is this?","Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","perspire")
	await novel_interface.show_dialog("Was what we just saw... an illusion?","Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("Those puppet girls too?","Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Henriette looks down at her weapon—not bloodstained, even though it should be. She then looks up at where our sudden attackers have seemingly evaporated.")
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("Perhaps what we were in... wasn’t the real world.","Henriette")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Heinrich was suddenly interrupted by Li Tong's voice.")
	await novel_interface.show_dialog("Finally! A connection!","Mariru")
	await novel_interface.show_text_only("Mariru’s voice booms from... inside my chest?")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("Hey, Mariru! What’s up with the signal?","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru hums, sounding exhausted. Meanwhile, Henriette is staring at my chest in horror, confused as to why Mariru’s voice is coming from there.")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("(Hey, this is a misunderstanding, I swear!)","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Seeing the look on my face, Henriette nods, as if she gets it, and begins feeling around her own breasts as well.")
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("(Whispering) Did Master... modify my body that way too?","Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_text_only("Of course not! And why did you look like you were excited about it?")
	await novel_interface.show_dialog("Hey, by the way, why didn’t you contact us with the walkie-talkie instead?\\nIs Annie okay?","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("The communications satellite is in position now. Annie is collecting info on the sources of methane leaks. How’s it going over there?","Mariru")
	await novel_interface.show_text_only("I try my best to sort out my thoughts and report everything we’ve encountered after entering the base in the most concise way possible.")
	await novel_interface.show_dialog("...\\n(Not the real world, huh...)","Mariru")
	await novel_interface.show_dialog("Wait a sec, let me check the time.","Mariru")
	await novel_interface.show_dialog("Eight minutes have passed since you last contacted Annie at the gate of the base.","Mariru")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("... Just eight minutes?","Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","perspire",0.25)
	await novel_interface.show_dialog("Shouldn’t it have been at least forty minutes?","Raphael")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("As if realizing something, Mariru begins typing away.")
	await novel_interface.show_dialog("A Lebona-class Destroyer patrolling the Antarctic Ocean just received some kind of low-frequency signal.","Mariru")
	await novel_interface.show_dialog("I thought it was from an aftershock, but considering how things stand now...","Mariru")
	await novel_interface.show_text_only("Mariru calls up her EEG system and reruns a pattern analysis.")
	await novel_interface.show_dialog("Just like I expected...","Mariru")
	await novel_interface.show_dialog("This signal... it’s got the same pattern as brainwaves do during human REM sleep...","Mariru")
	await novel_interface.show_dialog("... But sixty-two times more intense.","Mariru")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("... Are you kidding me?","Raphael")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("Do you mean we were dreaming just now?","Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("Time does slow down when you dream, that’s true...","Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("heinrich_battle","normal",0.25)
	await novel_interface.show_dialog("Dreams reflect memories. And what just happened... it indeed felt like a recombination of different memory fragments.","Henriette")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("If that was a dream, then it was definitely a nightmare...","Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("I’m suddenly reminded of this movie I watched, where the characters used totems to tell whether they were in a dream or not. Wish I had one of those.")
	await novel_interface.show_dialog("... Maybe it wasn’t you guys who were dreaming. You might’ve been in someone else’s dream.","Mariru")
	novel_interface.show_character("ren_battle","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("heinrich_battle","serious",0.25)
	await novel_interface.show_dialog("Someone else’s dream...?","Henriette")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("All these are just speculations, of course, only serving to unnerve me even more. I notice that it’s kind of noisy on Mariru’s end—seems that a lot of people are busy at work around her.")
	novel_interface.show_character("ren_battle","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("heinrich_battle","serious",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("By the way, what is it like... out there?","Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru remains silent for a moment, as if trying to decide just how much she wants to reveal.")
	await novel_interface.show_dialog("It’s a bit more... complicated than we expected.","Mariru")
	await novel_interface.show_dialog("The United Congress is currently discussing how to solve the methane leak problem. But you know what their kind of people are like. No way they’ll be able to cope with an apocalypse-level event like this.","Mariru")
	await novel_interface.show_dialog("Dr. Deckers from Salmonton did propose a plan to use methanophile archaea...","Mariru")
	await novel_interface.show_dialog("But there isn’t much of that currently in stock, especially not the kind that can survive in the cold. And it’s too late to cultivate more from scratch.","Mariru")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("Besides, anaerobic bacteria can’t really do much in our atmosphere because oxygen kills them.","Raphael")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("So even Grandpa is stumped, huh...","Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","bored")
	await novel_interface.show_dialog("(I have no idea what they’re even talking about...)","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Presently, most medium and small-scale research stations are in process of evacuation, though a temporary emergency team has already been set up by the three major Antarctic bases.","Mariru")
	await novel_interface.show_dialog("So far, forty-two methane leak sources have been identified in the Antarctic Circle. Six are already ignited, and photos of those sites are spreading like wildfire on the internet right now.","Mariru")
	await novel_interface.show_dialog("And on the news channels too. All TVs in the world are probably now looping footage of flames spewing from cracks in the polar ice plains, shooting up dozens of meters high.","Mariru")
	await novel_interface.show_dialog("There’s no way they can keep this under wraps any longer. The world knows, and they’re clearly panicking—some are already throwing celebrations: one last hurrah before the world ends.","Mariru")
	await novel_interface.show_text_only("Mariru’s words are cynical, her tone helpless.")
	await novel_interface.show_dialog("The leaking sites are concentrated near several ice-free lakes, and in the Mount Erebus area on Ross Island.","Mariru")
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("... Mount Erebus? That’s a volcano.","Henriette")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("As for the Princess Elisabeth Antarctica Research Station near your location, two small fires have already started due to the methane leaks.","Mariru")
	await novel_interface.show_dialog("There’s also a fire started by a bunch of rich, brainless Mt. Grove tour group members who were playing with flamesprayers. Idiots.","Mariru")
	await novel_interface.show_dialog("At least the Snedronningen Base isn’t in any immediate danger right now.","Mariru")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("Phew…","Lian")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("(Nice. At least we’re in no danger of being fried... yet.)","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("... However, the McMurdo Station has detected large-scale lava flow activity underneath the cracks.","Mariru")
	await novel_interface.show_dialog("The crack near Snedronningen Base is the most prominent one, and the ice sheets surrounding it are becoming increasingly unsteady in an alarming speed.","Mariru")
	await novel_interface.show_text_only("I can’t help looking down at the metal boards under my feet.")
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("(So we’re still gonna get fried anyway, huh...)","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("A sudden, sharp noise rips through the air. My chest vibrates, and the next thing I know, we’re disconnected.") #换行问题
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("Flames spouting from the ground, flowing lava, deadly volcanic soot...","Henriette")
	await novel_interface.show_dialog("It’s too similar to what happened around four hundred years ago...","Henriette")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("These are all precursors to the collapse of the \"primordial substance\".","Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("You mean what happened in 1600?","Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("That was in the Seventh Particle, the Land of Abundance: the Governor’s District of Peru.","Henriette")
	await novel_interface.show_dialog("I’ll never forget the sea of fire, the pungent smell of sulfur in the air...","Henriette")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Henriette reminisces, sounding bitter, and I can’t help being affected—for I had a very similar experience as well.")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("So... does all this have to do with that “The One” dude you mentioned?","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Henriette nods.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Ampthitheatre.png")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	await novel_interface.show_dialog("Back then, my friends in the Rosenkreuzer and I collected three mystic books: Book of the Chariot, Book of Creation, and Book of Light.","Henriette")
	await novel_interface.show_dialog("Following the instructions on the books, we completed the greatest achievement ever in alchemy: creating a “portal” that could bring us into the karmic realm.","Henriette")
	await novel_interface.show_dialog("Being naive, we honestly believed that the portal would lead us to a benevolent, all-seeing Overlord, who will show us all the truths in the world.","Henriette")
	await novel_interface.show_dialog("... But there’s actually a reason why the rules “do not pass through the portal” and “do not seek the truth” exist...","Henriette")
	await novel_interface.show_dialog("For once you enter the portal, you will never find the way out.\\nAnd once you see the truth, it will be forever engraved in your mind.","Henriette")
	await novel_interface.show_dialog("Humans are only capable of understanding language.","Henriette")
	await novel_interface.show_dialog("Anything that can’t be described by language is beyond us.","Henriette")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Reference_Room_Old.png")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("That’s a philosophy someone came up with in the 20th century.","Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("Oh? Someone came up with that conclusion just by... philosophizing?","Henriette")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("That person must have been through a lot of pain, then.","Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("Sure did. His whole family was considered lunatics.","Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("Yeah. He must have been a wise man. Except that kind of wisdom simply serves to eat away at your ego until you become part of it, so fearful, so desperate.","Henriette")
	await novel_interface.show_dialog("I, too, was part of that process once upon a time. And that was when The One showed up in front of me...","Henriette")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("Without saying a word, he made me choose.","Henriette")
	await novel_interface.show_dialog("Do I want to disappear, like a drop in the ocean?","Henriette")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("Or become a single drop in a bottle, preserved for eternity, existing as the guardian of the Tree of Life?","Henriette")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Reference_Room_Old.png")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("…","Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("They targeted you when you were the weakest...","Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("And the so-called Tree of Life—it’s not what they say it is, right?","Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Henriette smiles, a bit ruefully.")
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("... It’s a kind of seal.","Henriette")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("The Ten Sephiroth of the Tree of Life act as a seal that keeps an unspeakable being—one feared even by The One—at bay.","Henriette")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("I don’t know what that being is exactly, though.","Henriette")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Maybe I should be relieved I don’t.","Henriette")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Henriette pauses.")
	novel_interface.character_light(0.35,"bored")
	await novel_interface.show_dialog("(In the crater of Enaptina, which seems to be about to burn out everything) \\n (I once had a taste of it...)","Henriette")
	await novel_interface.show_dialog("The One had never explicitly said what he wanted, but it’s not hard to tell what it is from how our earth has changed...","Henriette")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She laughs, humorlessly.")
	await novel_interface.show_text_only("An uneasy silence creeps upon us at Henriette’s words.")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("... Wait!","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I take out the gas chromatograph and point at the figures on it.")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("Even if we’re in a “dream” right now, isn’t the “reality” here still different from other places?","Lian")
	await novel_interface.show_dialog("See, the methane level near the crack outside the base is skyrocketing, over 25% already. But down here, the methane level is still far lower than that...","Lian")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("Isn’t that contradictory? And we didn’t even notice!","Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("Wait, what do you mean?","Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("Surely you’ve all heard it since we entered the base. The—","Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","perspire")
	await novel_interface.show_dialog("The ventilation system?","Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("Yeah. Something in the base must be manning it, keeping the methane from spreading here.","Lian")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Oh, right, didn’t Mariru send us a layout map of the base before we set off?","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphael immediately unfolds the map and sets it on the desk.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("…")
	novel_interface.show_background("res://assets/images/bg/Baizhu/Snowstorm.png")
	await novel_interface.show_text_only("An hour ago, there was nothing but snow, silent, beautiful. And now there is wind. Piercing, shrieking, like gleaming blades.")
	await novel_interface.show_text_only("The continent of ice, once shrouded in darkness, is now a land of ruthless white.")
	await novel_interface.show_text_only("The blizzard has come.")
	
	print("=== 深海恐惧症篇第21话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
