# bathophobia_ep16.gd - 深海恐惧症篇第16话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep16_script()

func play_script():
	pass

func bathophobia_ep16_script():
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Depot1.png")
	await novel_interface.show_text_only("ラファエルが2階で寒冷地用のディーゼル燃料を\\n数箱見つけてくれた。\\nこれでこの補給所は数日間稼働できるだろう。")
	await novel_interface.show_text_only("発電機の轟音に伴い、電力供給が回復した。\\n\\n俺はダッシュでトイレに駆け込む。")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("（真っ暗闇の中で、トイレなんてしたくない\\n　からね……）", "小憐")
	await novel_interface.show_dialog("（この場所を作った人達が洒落た感じに、\\n　トイレもガラス張りにしてたらと思うと……）", "小憐")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("勘弁してくれよ……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("お腹を押さえながらトイレを出ると、\\nアニーが少し回復したのか立ち上がっていた。")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("アニー、大丈夫か？", "小憐")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_normal","normal2",0.25)
	await novel_interface.show_dialog("大丈夫。通信室に行こう……", "アニー")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("身体を強引に起こしたアニーを支えながら、\\n2階へと向かう。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Depot2.png")
	await novel_interface.show_text_only("通信室の内部はシンプルなデザインである。\\n\\n最低限の必要設備が部屋の中に詰め込まれ、\\n奥の観測空間だけは少し広くなっている。")
	await novel_interface.show_text_only("部屋のロッカーには沢山の飲用水と缶詰、\\nそして長期保存食を見つけた。")
	await novel_interface.show_text_only("空気も悪くなく、窓から夜空に躍動する\\nオーロラが見える。")
	novel_interface.show_character("anne_normal","upset")
	await novel_interface.show_dialog("このシステム、まだ動くのかな……", "アニー")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("アニーはコンソール上で古い機器の起動を\\n試みた。\\n信頼性を前提に構成されたハードウェアは、\\n依然として作動できるようだ。")
	await novel_interface.show_text_only("SIDで訓練を受けたアニーはこのシステムも\\n知っているようだ。\\n幸いな事に補給所外部の通信アンテナに関しても\\n外気の影響をあまり受けていない様子ではある。")
	await novel_interface.show_text_only("壁を巡る換気口から、しっとりした暖かい風が\\n巡ってくる。")
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("暖房は作動しているみたいだけど？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("壁にかかった温度表示を見ると、\\n室内の温度が0℃から徐々に上がっていく。")
	await novel_interface.show_text_only("それに対して室外の温度は…… −42℃！？？")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("ハインリッヒがくれた暖玉があって助かった……", "小憐")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("（−42℃の環境の中、スカート姿で雪遊び）", "小憐")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("（なんか、達成困難な実績を解除した気がする）", "小憐")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("ああ……それより早く、\\nマリルに連絡して助けてもらおう……", "小憐")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("（そう言えば、あのチップは壊れたのか？）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("思わず胸元を触ってみた。\\n\\nまさかここからマリルの声が聞こえてくるのを、\\n望む日が来ようとは。")
	novel_interface.show_character("anne_normal","normal1")
	await novel_interface.show_dialog("衛星接続中……できた！", "アニー")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("アニーの指示に従って、俺は頭に刻み込んでいる\\n文字列をコンソールに入力した。")
	await novel_interface.show_text_only("マリルに無理矢理SIDの暗号化属性コードを\\n暗記させられててよかった。")
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("なるほど、実に興味深い──", "ハインリッヒ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("補給所に入ってからというもの、ハインリッヒは\\n材質や物品などを興味津々と観察し続けている。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("前から直に触れてみたいと思っておりました──", "ハインリッヒ")
	await novel_interface.show_dialog("砂礫、アルミニウム、カルシウム、可燃金属、\\nそして玄武岩との組み合わせ……", "ハインリッヒ")
	await novel_interface.show_dialog("それらを繊維化すれば、異なる性質のものに\\n変わるのですね。", "ハインリッヒ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","bored")
	await novel_interface.show_dialog("うん？", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("このガラスの構成方式は、わたくしが知っている\\n形成方法とは違いますわ。", "ハインリッヒ")
	await novel_interface.show_dialog("なるほど……この方法であれば、熱量の流失を\\n遮断できるのですね……実に面白い。", "ハインリッヒ")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("ですが、やはり錬金術によるエネルギー転換の\\n刻印には劣ります。", "ハインリッヒ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("刻印……\\nもう何が凄いとか比べる領域じゃない気がする。", "小憐")
	novel_interface.change_expression("wail")
	await novel_interface.show_dialog("（ガラスの作り方とか科学の授業で習ったけど、\\n　材料を聞くだけで気が狂いそうになったし！）", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("しかし、先ほどあそこで見つけたゴム製品は\\n素晴らしい作品だと思いますわ。\\n小さい袋にそれぞれが包装されていて、\\n延伸性に関してはとても驚異的でした。", "ハインリッヒ")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("それにゴムなのに果物の香りも……あれは何に\\n使うものなのでしょうか？　マスター？", "ハインリッヒ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("……し、し、知りませんッ！！", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("ただのガムよ、この変態。", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ラファエルが俺を白い目で見た。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("ううう……仕方ないだろ勘違いするって。\\nハインリッヒの奴は自分の世界に戻ってるし！")
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("一方、本部に戻ったマリルは愛衣と共に\\nレンの行方を捜索していた。")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("衛星クラスターは、まだレンちゃんのチップを\\n発見できていないよ。\\n全世界を捜査範囲として設定しているのに……", "愛衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("まさか、地球以外に転送されたか、\\nまたはタイムトラベルしたとか？", "愛衣")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","serious",0.25)
	await novel_interface.show_dialog("必要が無いのであれば\\n「必要以上に多くを仮定するべきでない」\\n──最良の基礎的状況を、優先的に考慮しろ。", "マリル")
	await novel_interface.show_dialog("いわゆる『グローバル衛星』は北緯70度から\\n南緯70度までを軌道として巡回している。", "マリル")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("つまりは──", "愛衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("突然、SIDの暗号化通信に「接続」の表示が\\nポップアップされた。")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("もしもしっ、聞こえるか──？", "マリル")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("マリル！！\\nやっと連絡が繋がった──", "小憐")
	await novel_interface.show_text_only("馴染みの声を聴くとマリルの表情も落ち着きを\\n取り戻し、いつもの状態に立ち直った。")
	await novel_interface.show_text_only("彼女は今もオフラインと表示されている\\n位置情報を見つめ、\\nすぐさま逆追跡プログラムを起動した。")
	novel_interface.show_character("liliu_uniform2","speak")
	await novel_interface.show_dialog("レン？　今どこだ？\\n他の者は一緒か？", "マリル")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("うん、補給所にいるんだ。\\nラファエルもアニーも無事だけど、ただ──", "小憐")
	await novel_interface.show_dialog("俺達今……南極にいる。", "小憐")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("…………", "マリル")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","dizzy",0.25)
	await novel_interface.show_dialog("──南極！！！？？", "愛衣")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("驚きながらもマリルの表情には少しの動揺も\\nなかった。")
	novel_interface.character_light()
	await novel_interface.show_dialog("（レンの声からすると低体温症等ではない）\\n（彼女達は今、安全な場所にいるはずだ）", "マリル")
	await novel_interface.show_dialog("（方舟基地での実験中に空間転移が起きたか？）", "マリル")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("ようやくスクリーン上に、通信先の追跡結果が\\n表示された。\\n南極にあるプリンセス・エリザベス・ランド地区\\n2番合同補給所だ。")
	novel_interface.show_character("liliu_uniform2","normal2")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light(0)
	novel_interface.show_2nd_character("ai","dizzy",0.25)
	novel_interface.character_2nd_dark(0)
	await novel_interface.show_dialog("やはりか……意図的に軌道を変えない限り、\\n一般の衛星はあのエリアをスキャンしない。", "マリル")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("極地の太陽風はデータの転送に影響するからね。", "愛衣")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("うん、やっぱり私の見落としだった……", "愛衣")
	await novel_interface.show_dialog("南極上空の衛星を起用する？", "愛衣")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("ああ。あのジジイ達に気付かれないようにな。", "マリル")
	await novel_interface.hide_all_characters()
	await novel_interface.show_dialog("とにかく、俺達もなんでここに連れてこられたか\\n分からないんだ。", "小憐")
	novel_interface.show_character("liliu_uniform2","speak")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light(0)
	novel_interface.show_2nd_character("ai","normal",0.25)
	novel_interface.character_2nd_dark(0)
	await novel_interface.show_dialog("……お前達3人以外、他に誰かいるのか？", "マリル")
	await novel_interface.hide_all_characters()
	await novel_interface.show_dialog("ハインリッヒの事か？\\n彼女なら俺の傍に──", "小憐")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Depot2.png")
	await novel_interface.show_text_only("こんな古い設備でもマリルと無事に連絡取れて、\\n精神的にはかなり安心した。")
	await novel_interface.show_text_only("現在の状況を、簡単にマリルに報告する。")
	await novel_interface.show_dialog("……大体の状況は掴めた。", "マリル")
	await novel_interface.show_dialog("聞いてくれ、\\nお前達の現在置は南極点の非常に近くだ。\\n迎えに行くのには、少し厄介事がある。", "マリル")
	await novel_interface.show_dialog("戦後の『新南極条約』によれば南極に5人以上の\\n視察隊を派遣する場合──", "マリル")
	await novel_interface.show_dialog("または飛行ツールを使って南極圏に入る場合、\\n連合議会に申請して承認を得なければならない。", "マリル")
	await novel_interface.show_dialog("そして、途中で新オーストラリアへ寄港する事を\\n加え……", "マリル")
	await novel_interface.show_dialog("1時間以内に物資を揃え、全手続きを道中で\\n申請したとしても、およそ40時間はかかる。", "マリル")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("大丈夫だ。ここの発電機能は数日間持つし、\\n食べ物も結構ある。", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("最寄りの専用ヘリポートの位置は、\\n東経76度55分、南緯68度24分の地点。\\nお前達がいる拠点から約1キロの場所だ。", "マリル")
	await novel_interface.show_dialog("私達はヘリポートへの着陸を目指すが、\\n南極の天候は複雑だ。\\nもし通信が途切れた場合には、\\nある場所を第1級合流地点としろ。", "マリル")
	await novel_interface.show_dialog("そこは規模の大きい拠点で、ほとんどの施設が\\n地下に造営されている。名前は……\\n『Snedronningen』\\n──スノークイーン基地だ。", "マリル")
	await novel_interface.show_dialog("詳細は……別途で……ガガッ……、\\nレン、今は……ザーッザーッ……", "マリル")
	await novel_interface.show_text_only("マリルの声が急にノイズで覆われた。")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("マリル！　マリルッ！？　もしもし──", "小憐")
	novel_interface.character_dark()
	await novel_interface.show_dialog("──聞……えるか？　……しもし？", "マリル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("通信センターの雑音がますます強くなった。")
	await novel_interface.show_dialog("太陽風かもしれな──記した……れば、\\n電波を確……できるか──", "マリル")
	await novel_interface.show_text_only("うわー——")
	await novel_interface.show_text_only("電流の雑音が酷くなるにつれ、マリルの声は\\n消失した。")
	await novel_interface.show_text_only("周囲は静まり返っている。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("駄目だ……応答が返ってこない……", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("40時間？　その間に何も起こらないように、\\n祈っておいた方がいいわね。", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("しかし、何やら胸騒ぎがする。")
	await novel_interface.show_text_only("電波と同時に窓の外のオーロラも消えていた。\\n外は風の音さえ止まっている。")
	await novel_interface.show_text_only("室内にはコンピューターの放熱器とエアコンの\\n送風の音のみが響く。")
	await novel_interface.show_text_only("異常なほどの静寂は、嵐の前の静けさとしか\\n思えない……")
	await novel_interface.show_text_only("目の前のコンソールが突然揺れた。")
	await novel_interface.show_text_only("いや、違う。\\n俺が、ちゃんと立てていないだけだ。")
	novel_interface.show_character("anne_normal","panic")
	await novel_interface.show_dialog("みんな、感じない……？", "アニー")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("まさかあんたも……", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("軽かった揺れが次第に強くなってくる。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("……う、嘘だろうッ！？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("俺はコンソールを支えにしながら、これから\\n起こるであろう事に対し緊張感を張り巡らせる。")
	novel_interface.show_character("heinrich_battle","perspire")
	await novel_interface.show_dialog("これは……？", "ハインリッヒ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("怒号のような大きな異音が、足元から段々と\\n伝わってきた。")
	await novel_interface.show_text_only("建物が激しく揺れ始め、\\n俺達はもはや立っている事も困難になる。")
	await novel_interface.show_text_only("テーブルの上に置かれていたもの全てが、\\n紙相撲みたいに位置を変える。")
	await novel_interface.show_text_only("遠くの氷山から轟々と崩れる音が聞こえてくる。")
	await novel_interface.show_text_only("窓の外を見てみると、やはり──")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("──地震だッッ！！？", "小憐")
	print("=== 深海恐惧症篇第16话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
