# bathophobia_ep11.gd - 深海恐惧篇第11话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep11_script()

func play_script():
	pass

func bathophobia_ep11_script():
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("What is reality?")
	novel_interface.change_background("res://assets/images/bg/Baizhu/game.png")
	await novel_interface.show_text_only("Maybe the reality as we know it is but a computer game.")
	await novel_interface.show_text_only("Log in, the characters wake up; log out and they fall asleep. When accounts are closed, they die.")
	await novel_interface.show_text_only("As time goes by, they develop the perception of the soul.")
	await novel_interface.show_text_only("They believe all those preprogrammed actions are taken out of their free will.")
	await novel_interface.show_text_only("Formulas, laws, grammar rules, codes of conduct… every character is given these rules to follow without knowing who created them… until they are finally freed.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/unknowm.png")
	await novel_interface.show_text_only("Even if a huge patch of the sky becomes pixelated due to a rendering error—")
	await novel_interface.show_text_only("They just rationalized it with fairy tales or religious beliefs, instead of admitting that it is beyond their knowledge.")
	await novel_interface.show_text_only("Because accepting the unknown means the most disturbing possibility—")
	await novel_interface.show_text_only("That the so-called reality might be nothing but an illusion.")
	await novel_interface.show_text_only("A pipe dream.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/CauseAndEffect.png")
	await novel_interface.show_text_only("I open my eyes slowly and find myself in a haze.")
	await novel_interface.show_text_only("I'm surrounded by the mist. Strangely, strings of raindrops are hanging in midair.")
	await novel_interface.show_text_only("I reach out and try to touch them, but they evaporate immediately.")
	await novel_interface.show_dialog("Where am I…", "Lian")
	await novel_interface.show_text_only("I'm standing on a solid surface, and can feel gravity. But I can't see the ground… as if my sight is absorbed into the void.")
	await novel_interface.show_text_only("There is an unusual buzz in the background. Without any frame of reference, directions are imperceptible.")
	await novel_interface.show_text_only("I look up and see the outline of a tree-like totem floating along high above me.")
	await novel_interface.show_text_only("It spreads like a glimmering blanket in the sky.")
	await novel_interface.show_text_only("Ten rings on the totem rotate slowly, one emitting a reddish ray.")
	await novel_interface.show_text_only("Then a huge pattern composed of lines and inscriptions unfolds beneath my feet, forming what can be called the ground.")
	await novel_interface.show_text_only("The totem on the ground is the same as the one in the air, but much bigger looking from short distance.")
	await novel_interface.show_text_only("The rings, each about 15 ft in diameter, are connected in a certain order. Inscriptions on them look ancient.")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("(Am I… dreaming?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I've been trained to identify hallucinations and dreams…")
	await novel_interface.show_text_only("What's that important question again…")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("—How did I come here?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Memories come back. I was in the Ark Base and everything began to fall… Then…")
	await novel_interface.show_text_only("No. This is not a dream.")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("(Does it have anything to do with that girl?)", "Lian")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("(She called me Master, and even…)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Aww— \\nNo… It's not the time for fantasy…")
	await novel_interface.show_text_only("Where is Annie? And Raphael?")
	await novel_interface.show_text_only("They must also get sucked into this place!")
	await novel_interface.show_text_only("I look around into the mist for them. Unexpectedly, a pair of warm arms of holds me from behind.")
	await novel_interface.show_dialog("Do not worry, Master—", "Blond Girl")
	await novel_interface.show_text_only("It's her! \\nThe naked girl is hugging me from the back!")
	await novel_interface.show_text_only("I have many questions for her. But I hesitate to look back…")
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("(Master… How strange!) \\n(Just like weirdos in cartoon movies!)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She seems to be groping for something. Her hands crawl along my waist, and stop at my flat belly.")
	await novel_interface.show_text_only("In the silence, I can hear my heart beating fast as her breath is tickling my hair…")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("(What… is she going to do?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Oh?","Blond Girl")
	await novel_interface.show_text_only("She seemed to have discovered something interesting. She pressed it lightly with her palm, and my stomach immediately let out an unsatisfactory \"gurgling\" sound.")
	await novel_interface.show_text_only("In this quiet environment, this sound is particularly noticeable.")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("(Eh? Why…)", "Lian")
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("(Ahhhhhhh… So embarrassing…)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I break away from her. She walks up to me and looks at me curiously.")
	await novel_interface.show_dialog("Has Master's body been modified as well? \\n… What a perfect product of alchemy!","Blond Girl")
	await novel_interface.show_text_only("I want to cover my eyes, but realized she’s already dressed.")
	await novel_interface.show_text_only("Wait, did she just say my body has been modified?! \\nAnd… what is she wearing?")
	await novel_interface.show_text_only("One look at Heinrich's costume is enough to tell its state-of-the-art material.")
	await novel_interface.show_text_only("Judging from the texture and design, it can’t be made the 16th century… No, it’s even beyond modern craftsmanship.")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("(Is Mariru's information wrong?) \\n(And how does she know about my body transformation?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("As I try to verbalize my thoughts, someone gives me a sudden pull backwards.")
	await novel_interface.show_text_only("It's Raphael. She grabs me by my hood, steps forward and stands between me and Heinrich.")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("Tell me, who are you?!", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("—Well?", "Blond Girl")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Heinrich turns to Raphael, a scornful smile on her face.")
	novel_interface.character_light()
	await novel_interface.show_dialog("Are you asking my name? \\nI have hundreds of them.", "Blond Girl")
	await novel_interface.show_dialog("But you can call me Henriette Khunrath—that's the one on the Contract.", "Blond Girl")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("That's not funny!", "Raphael")
	await novel_interface.show_dialog("Heinrich is a man in all historical records—", "Raphael")
	await novel_interface.show_dialog("And besides, look what you're wearing! \\nHave you mistaken underwear for outerwear?", "Raphael")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Don't defile Heinrich the great alchemist, you shameless girl! Stop calling people “master\" and… and taking people’s essence…", "Raphael")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Raphael blushes as she speaks.")
	novel_interface.character_light()
	await novel_interface.show_dialog("… Who on earth are you!", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("As they face off against each other, I couldn't help but peep at Heinrich from Raphael's back.")
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("(What's the material of her costume…) \\n(Amazing wrap! How could her breasts shake in different directions?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Our eyes meet and I blush at once. In a panic, I look down at my skirt, avoiding further eye contact.")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("Well? I thought Master wouldn't be struck by your own masterpiece…", "Henriette")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("No no no, I am (or, was) a boy…")
	await novel_interface.show_text_only("Heinrich points to her chest.")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("Bigger than they used to be… Is this Master's taste?", "Henriette")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphael looks back and casts me a stern look.")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("No! Not me! I didn't!!", "Lian")
	novel_interface.change_expression("shy")
	await novel_interface.show_text_only("I just broke Salmonton's national treasure by accident…")
	await novel_interface.show_dialog("And, please don't call me master… Just call me Ren.", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("Ren…? \\nI didn't expect a great person like you would have such a lovely name…", "Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("What about you? Are you really Heinrich?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She hesitates, looks at the numbers on her wrist, and sighs slightly.")
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("It’s already 400 years…", "Henriette")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Wait, is there any watch or calendar on her wrist!?")
	novel_interface.character_light()
	await novel_interface.show_dialog("I did pose as a man to do research, publish papers or practice medicine.", "Henriette")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("So I'm not surprised by the way history records me.", "Henriette")
	await novel_interface.show_dialog("In my time, universities didn't admit girls, and the church forbade women to practice medicine—", "Henriette")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("Let alone becoming an alchemist… Hmm, I don't want to get into trouble with the religious court.", "Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("… \\n", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Somehow, I start to feel indignant every time I learn about the oppression of women.")
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("It's easy to get rid of those dogs of the court, but they're not worth my time.", "Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("Wow… sounds cool…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphael looks at Heinrich thoughtfully.")
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("Wait, how did you get to enter the university as a boy? \\n", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I am suddenly curious about how she got in. Maybe…")
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("I just cut my hair short, forged several references, and got into the University of Leipzig under a pseudonym.", "Henriette")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","smile",0.25)
	await novel_interface.show_dialog("Just a haircut?", "Lian")
	novel_interface.change_2nd_expression("wry_smile")
	await novel_interface.show_text_only("I look at her chest. Are people 400 years ago all blind?")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("I was ten years old then. The university entrance exam was too easy.", "Henriette")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Heinrich smiles disdainfully.")
	novel_interface.character_2nd_light(0.35,"wail")
	await novel_interface.show_dialog("Huh? Never mind.", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("No matter how the world changes, whiz kids are always awesome!")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("Then how do you explain this costume?", "Raphael")
	await novel_interface.show_dialog("Heinrich was a doctor and alchemist, but your armor and weapon are obviously for battles.", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Heinrich takes a step back, smiling.")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("Oh, sorry, it's my fault.", "Henriette")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She presses her right hand on her chest, and the costume begins to crack.")
	await novel_interface.show_text_only("Her body, now surrounded by blue and white ribbons and colorful crystals, begins to shine.")
	await novel_interface.show_text_only("When the blue and golden light starts to fade, her body gradually…")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Gradually… Eh?")
	await novel_interface.show_text_only("Raphael rushes up and covers my eyes tightly with her hands.")
	await novel_interface.show_dialog("Enough! I see!", "Raphael")
	await novel_interface.show_dialog("Put your clothes on, exhibitionist!", "Raphael")
	await novel_interface.show_dialog("There is also cross-dressing, what are you looking at!", "Raphael")
	await novel_interface.show_text_only("I haven't seen anything!!")
	novel_interface.show_background("res://assets/images/bg/Baizhu/CauseAndEffect.png")
	await novel_interface.show_text_only("When Raphael removes her hands, Heinrich is already dressed in the same costume again. Ugh…")
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("This is a magical Battle Suit, similar to the one on Master. But mine is made by superior beings.", "Henriette")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("As for the design… I'm afraid The One has a terrible taste…", "Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("The One?", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("I made the Doorway to this space using alchemical techniques.", "Henriette")
	await novel_interface.show_dialog("Mortals are not supposed to know the truth… So I had to pay the price. The One forced me to sign a contract regarding my soul…", "Henriette")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Heinrich looks somewhat helpless.")
	novel_interface.character_light(0.35,"bored")
	await novel_interface.show_dialog("(Mumbling) Last time I had my body completely blown to pieces, but the contract could still be activated with a new body...", "Henriette")
	await novel_interface.show_dialog("Why don’t you give me a break…", "Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("?", "Lian")
	novel_interface.character_dark()
	await novel_interface.show_text_only("As I'm wondering what Heinrich is saying, Annie's quivering voice suddenly comes from the mist.")
	await novel_interface.show_dialog("Ren—", "Annie")
	novel_interface.character_light(0.35,"solemn")
	await novel_interface.show_dialog("Annie?!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("We run towards where the voice came from, and find Annie lying sprawled on the ground, trembling.")
	await novel_interface.show_dialog("H… Help…", "Annie")
	await novel_interface.show_dialog("… Don't… Please…", "Annie")
	await novel_interface.show_text_only("I quickly stepped forward to comfort Annie, and the moment my hand touched her body——")
	await novel_interface.show_text_only("A viscous and hot breeze flows through my hand and sweeps past me quickly.")
	await novel_interface.show_text_only("I look around but find nothing unusual, except that Heinrich is gazing at me in bewilderment.")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("You'll be fine, Annie!", "Lian")
	novel_interface.change_expression("solemn")
	await novel_interface.show_dialog("Annie?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("For some reason, Annie is shivering violently.")
	await novel_interface.show_text_only("I understand unknown places bring worry… But there is no sign of enemies in the vast empty space.")
	await novel_interface.show_text_only("I hold Annie close, trying to comfort her.")
	await novel_interface.show_text_only("Seeing this, Raphael turns to Heinrich again.")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("You mentioned this space… Is it the Crevice of Causality?", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("That's the name inscribed on the Tree of Life…", "Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("Tree of Life?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("Why did you take us here? What do you want from us?", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Heinrich shrugs.")
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("Not me.", "Henriette")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("In fact, you couldn't have been here…", "Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("Eh?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("… Without the intent of The One… or even from more superior beings.", "Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("Who is The One?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("I'm obliged not to call him by his name… But The One has too many titles…", "Henriette")
	await novel_interface.show_dialog("The Truth, the Way, the Doorway…", "Henriette")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("From the beginning… to the end.", "Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("…?!", "Raphael")
	
	print("=== 深海恐惧篇第11话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
