# bathophobia_ep03.gd - 深海恐惧篇第3话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep03_script()

func play_script():
	pass

func bathophobia_ep03_script():
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("Mariru เดินไปหาอายะแล้วก้มลงไปอ่านข้อมูลที่รีเฟรชบนหน้าจอ")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("รายงานทางการแพทย์ของ Beatrice?", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","dizzy",0.25)
	await novel_interface.show_dialog("เอ่อ-ฮะ-ตัวอย่างที่สมบูรณ์แบบ!", "Ai")
	novel_interface.change_2nd_expression("wink")
	await novel_interface.show_dialog("และคงจะน่าสนใจกว่านี้มากถ้าเราสามารถเปรียบเทียบกับบันทึกทางประวัติศาสตร์ได้", "Ai")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("แต่ไม่มีฐานข้อมูลใดของเราที่มีข้อมูลใด ๆ ของเธอ อาจเป็นเพราะช่องว่างข้อมูลที่เกิดจากสงคราม", "Mariru")
	await novel_interface.show_dialog("อย่างไรก็ตาม ตามคำให้การของเธอและรายงานของคุณ...", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru ดึงโปรไฟล์ของ Beatrice ขึ้นมาบนหน้าจอ")
	novel_interface.show_character("liliu_research","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ai","wink",0.25)
	await novel_interface.show_dialog("อายุ 24 ปี… \\nช่างเป็นวัยที่สำคัญจริงๆ!", "Ai")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru และอายะสบตากัน โดยรู้ว่าสังเกตเห็นสิ่งเดียวกัน จากนั้นพวกเขาก็หันกลับมาที่หน้าจอ")
	novel_interface.show_character("liliu_research","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ai","wink",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("นี่คือผลการทดสอบของเธอในคืนที่เธอปรากฏตัวออกมาเหรอ?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal")
	await novel_interface.show_dialog("แทบไม่มีธาตุกัมมันตภาพรังสีที่พบในร่างกายของเธอ แม้ว่าระดับโลหะหนักในตัวอย่างเลือดของเธอจะค่อนข้างสูงก็ตาม", "Ai")
	await novel_interface.show_dialog("มันอาจจะเกี่ยวข้องกับเครื่องใช้หรือเครื่องสำอางหยาบๆ ในยุคกลาง...", "Ai")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("คุณได้ข้อสรุปแล้วใช่ไหม?", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","stare",0.25)
	await novel_interface.show_dialog("ท้ายที่สุดแล้ว ตามบันทึกคำให้การของเธอ—", "Ai")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("อายะลากนิ้วของเธอไปบนบรรทัดข้อความบนหน้าจอ")
	await novel_interface.show_text_only("GMT+9 13:09:11 เป้าหมายอ้างว่าปี ค.ศ. 1265 เป็นปีเกิด")
	novel_interface.show_character("liliu_research","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ai","stare",0.25)
	await novel_interface.show_dialog("—นี่เป็นครั้งแรกที่ฉันเห็นตัวอย่างที่มีชีวิตตั้งแต่สมัยโบราณ", "Ai")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("อาจเป็นกรณีเดียวกันกับ Annie หรือไม่", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("ไม่นะ! \\nBeatrice บอกว่าเธอแน่ใจ 100 เปอร์เซ็นต์ว่าเธอตายแล้ว", "Ai")
	novel_interface.change_2nd_expression("think")
	await novel_interface.show_dialog("เธอบอกว่าเธอจงใจดื่มยาพิษ", "Ai")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("มีบันทึกทางประวัติศาสตร์ที่สนับสนุนสิ่งนี้... แต่ความเป็นไปได้ของการปลอมแปลงไม่สามารถตัดทิ้งได้", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("อายะคลิกเปิดรายงานการทดสอบอีกฉบับ")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("มีสารพิษหลากหลายชนิดที่บันทึกไว้ในยุคกลางเท่านั้น Hemlock, nightshade, vomic-nut และอื่น ๆ", "Ai")
	await novel_interface.show_dialog("เราพบสารอัลคาลอยด์ที่เป็นพิษตกค้าง ในตัวอย่างเลือดของเธอ ที่ถ่ายในคืนที่เธอปรากฏตัว", "Ai")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("แต่ในเลือดที่เราเจาะในวันรุ่งขึ้น แทบไม่มีร่องรอยของอัลคาลอยด์ที่เป็นพิษหรือโลหะหนักเลย", "Ai")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","happy",0.25)
	await novel_interface.show_dialog("ไม่น่าแปลกใจเลยที่คุณดูตื่นเต้นมาก...", "Mariru")
	novel_interface.character_light(0.35,"dizzy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("เดี๋ยวก่อน นี่ไม่ใช่ส่วนที่น่าตื่นเต้นที่สุด!", "Ai")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("เสียงของอายะสั่นด้วยความตื่นเต้น")
	novel_interface.show_character("ai","dizzy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("liliu_research","happy",0.25)
	await novel_interface.show_dialog("Beatrice ต่างจาก Annie ตรงที่มีระบบภูมิคุ้มกันที่พบในทารกแรกเกิด เธอมีผลตรวจ IgD เป็นลบ", "Ai")
	await novel_interface.show_dialog("และ…คุณสมบัติของไมโครไบโอมในร่างกายเธอเกือบจะเหมือนกับของเร็นเลย!!", "Ai")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("… คุณได้รับแนวคิดในการทำแบบทดสอบเหล่านี้ได้อย่างไร", "Mariru")
	novel_interface.character_light(0.35,"blush_dizzy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("สัญชาตญาณ สัญชาตญาณ. และความหลงใหลในตัวอย่างหายาก!!", "Ai")
	await novel_interface.show_dialog("ร่างกายที่สร้างขึ้นจากความว่างเปล่า... สร้าง \"คำสาป\" ที่น่าสนใจที่สุดในเรื่องนี้ขึ้นมาใหม่อย่างแม่นยำ นั่นคือความสามารถในการดึงดูดความรัก", "Ai")
	await novel_interface.show_dialog("เร็นช่าง... เหลือเชื่อ!!", "Ai")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("พูดจบอายะก็หลับตาและกอดอกกอดตัวเอง ดูค่อนข้างมึนเมากับความคิดของเธอ")
	await novel_interface.show_text_only("Mariru ม้วนรายงานออกมาและกระแทกหน้าผากของอายะอย่างแรง")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("หากวิญญาณสามารถดำรงอยู่ได้อย่างอิสระในกาลอวกาศอื่น...", "Mariru")
	await novel_interface.show_dialog("แล้วมันเลือกภาชนะยังไงล่ะ?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush")
	await novel_interface.show_dialog("มันเกี่ยวอะไรกับผีเสื้อสีทองหรือเปล่าล่ะ?", "Ai")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("ไม่ เมื่อพิจารณาจาก Annie และไม้เบสบอลของเธอ ฉันคิดว่า Beatrice มีความเชื่อมโยงกับอัญมณีสีเขียว…", "Mariru")
	await novel_interface.show_dialog("มันเหมือนกับว่าวัตถุบางอย่างสามารถเรียกวิญญาณที่ติดอยู่กับพวกมันออกมาได้", "Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("นี่เป็นเรื่องเกี่ยวกับการเดินทางในกาลอวกาศและการสร้างร่างกาย...", "Mariru")
	await novel_interface.show_dialog("(วุฒิสภาไม่ควรรู้อะไรเกี่ยวกับเรื่องนี้)", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("ดังนั้น Ren จึงสามารถดึงดูดวิญญาณได้...", "Ai")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("อายะทำลายความคิดของ Mariru")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("อืม?", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","normal",0.25)
	await novel_interface.show_dialog("การดึงวิญญาณออกมาจากที่ไหนสักแห่ง และสร้างร่างกายเพื่อรองรับวิญญาณ… ดูเหมือนการเล่นแร่แปรธาตุต้องห้าม", "Ai")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_dialog("ถ้าฉันไม่ได้อยู่ในยุคนี้ ฉันอาจจะพยายามค้าขายวิญญาณกับเทพเจ้าโดยใช้องค์ประกอบพื้นฐานเหมือนกับนักเล่นแร่แปรธาตุ", "Ai")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("เหมือนกับสิ่งที่เรียกว่า \"บุตรแห่งเทพเจ้า\" ซึ่งได้รับการส่งเสริมจากกลุ่มศาสนาเล็กๆ แต่ไม่มีตลาดสำหรับสิ่งนี้ใน New Opulentia", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"blush_think")
	await novel_interface.show_dialog("ไม่นะ ฉันชอบคำนำหน้าผู้หญิงอย่าง \"Goddess\" มากกว่า พวกเขาทำให้ฉันมีแรงกระตุ้นภายในที่จะต่อต้านการเลิกบุหรี่", "Ai")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("เอ้ย—ทำไมฉันถึงจ้างคนแบบคุณ…", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"blush")
	await novel_interface.show_dialog("เอ่อฮะ! บางทีจิตวิญญาณของเราอาจดึงดูดกัน", "Ai")
	await novel_interface.hide_all_characters()
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_heathRoom.png")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("—นี่คือทั้งหมดที่ฉันพบ", "Ai")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("ฮะ?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ในศูนย์สุขภาพ หลังจากการตรวจร่างกายเป็นประจำ ฉันคุยกับอายะเกี่ยวกับ Beatrice ขณะสวมเสื้อผ้า")
	await novel_interface.show_text_only("ความคิดเห็นของอายะเกี่ยวกับสภาพร่างกายของ Beatrice อาจจะสมเหตุสมผล...")
	await novel_interface.show_text_only("แต่ทฤษฎีวิญญาณฟังดูไร้สาระ…")
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("(โดยเฉพาะสิ่งที่เรียกว่า \"เทพธิดา\"…) \\n(แม้ว่าฉันจะเคยแสดงบทบาทประเภทนี้ในวิดีโอเกมมาก่อนก็ตาม)", "Lian")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("(แต่ฉันไม่เคยต้องการชื่อเช่นนี้สำหรับตัวเอง!)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ฉันอดไม่ได้ที่จะโอบแขนตัวเองด้วยอาการตัวสั่น")
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("ไม่ ไม่เคย!!", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","stare",0.25)
	await novel_interface.show_dialog("Ooh la la มีอะไรที่พูดไม่ออกในใจของคุณบ้างไหม?", "Ai")
	novel_interface.character_light(0.35,"bored")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("ดังนั้น… นี่คือสาเหตุที่รายการตรวจของฉันเพิ่มขึ้นเหรอ?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("เอ่อฮะ", "Ai")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("อายะเผยรอยยิ้มเจ้าเล่ห์ราวกับกำลังวางแผนบางอย่างเป็นความลับ")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("(อาจเป็นงานวิจัยอื่นที่ไม่ได้รับอนุญาต…)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("น่าเสียดายที่ฉันมีอุปกรณ์สนับสนุนไม่เพียงพอ ไม่เช่นนั้น ฉันสามารถทำการทดสอบที่ \"น่าสนใจ\" กว่านี้ได้...", "Ai")
	novel_interface.change_expression("blush_wink")
	await novel_interface.show_dialog("ยังไงก็ตาม อยากลองใช้โหมดพลังงานสูงสุดของชิปที่ฝังอยู่ในตัวคุณไหม?", "Ai")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("ไม่! ขอบคุณมาก!!", "Lian")

	print("=== 深海恐惧篇第3话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
