# bathophobia_ep09.gd - 深海恐惧篇第9话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep09_script()

func play_script():
	pass

func bathophobia_ep09_script():
	novel_interface.change_background("res://assets/images/bg/Baizhu/liliu_observation.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("Parado na estação de controle no topo da margem oposta à plataforma, Mariru pode nos ver no primeiro andar e na sala de observação dos Senadores.")
	await novel_interface.show_text_only("Três avisos profundos e baixos vêm do corredor, indicando a prontidão de Mariru.")
	await novel_interface.show_text_only("Raphael acena para Mariru. Annie e eu ficamos vigilantes ao lado dela.")
	await novel_interface.show_dialog("Projeto Ark, experimento número um.", "Mariru")
	await novel_interface.show_dialog("O escudo será desativado em dez segundos.", "Mariru")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_awaitOrders.png")
	await novel_interface.show_text_only("Na base da mesa de operações aparece uma contagem regressiva com números vermelhos.")
	await novel_interface.show_text_only("A eclusa é fechada e os degraus retraem-se na parede.")
	await novel_interface.show_text_only("Sons de engrenagens rangendo vêm do topo do corredor, e o conjunto automático de armas escondidas no teto está apontado para a mesa, pronto para atirar a qualquer momento.")
	await novel_interface.show_text_only("Eu, como um peixe nas profundezas do oceano, estou no meio da escuridão.")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("Sinto-me como um criminoso condenado...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Com tantas armas apontadas para mim, sinto-me extremamente tenso.")
	novel_interface.show_character("anne_battle","smile")
	await novel_interface.show_dialog("Relaxe, Ren. Eu vou proteger você!", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Annie também parece nervoso... Seus dedos pressionam o taco de beisebol com tanta força que as unhas ficam pálidas, mas ela ainda está me confortando.")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("Humph, covarde.", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("No momento em que o cronômetro chega a zero, Raphael puxa rapidamente a alavanca.")
	await novel_interface.show_text_only("O escudo transparente que circunda a plataforma encolhe rapidamente em direção ao fundo antes de desaparecer.")
	await novel_interface.show_text_only("À medida que o Pilar Lapis é ligeiramente levantado, um sentimento mais forte me atinge.")
	await novel_interface.show_text_only("Sinto que meu sangue começa a ferver e de repente sinto um impulso inexplicável.")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("(Ai… minha barriga dói mais…)", "Lian")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("(Se eu pedir uma pausa para ir ao banheiro, eles provavelmente vão querer me matar…)", "Lian")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/bedstand.png")
	await novel_interface.show_text_only("O espaço acima treme de repente, e um raio de luz passa rapidamente sobre nossas cabeças e corre até o final do corredor.")
	await novel_interface.show_text_only("Então, dois zumbidos curtos atingem meu peito, sinalizando que o sistema falso foi iniciado.")
	await novel_interface.show_text_only("A camada de camuflagem óptica no alto do corredor e o vidro especialmente tratado da sala de observação garantem que nenhum som vaze para os senadores.")
	await novel_interface.show_text_only("Aos olhos deles, Raphael, Annie e eu deveríamos partir instantaneamente junto com o Pilar Lapis.")
	await novel_interface.show_text_only("Depois disso, eles verão as imagens que falsificámos.")
	await novel_interface.show_text_only("O encena??o está passando. Bem no centro do palco, não tenho outra saída.")
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("Tem que enfrentar isso…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Dou um passo à frente e cuidadosamente estendo minha mão.")
	await novel_interface.show_text_only("À medida que minha mão se aproxima do pilar, fecho os olhos nervosamente e prendo a respiração \\nAté que as pontas dos dedos toquem o pilar.") #换行问题
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_awaitOrders.png")
	await novel_interface.show_text_only("…")
	await novel_interface.show_text_only("…?")
	await novel_interface.show_text_only("Abro lentamente os olhos.")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("Parece que… nada aconteceu.", "Lian")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Coloco toda a palma da mão no pilar. Parece mármore.")
	novel_interface.character_light(0.35,"upset")
	await novel_interface.show_dialog("Hum…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tento outro ângulo e dou um empurrão forte. O pilar, pesando mais de quinze mil libras, permanece imóvel.")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("Tsk!", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphael me despreza.")
	await novel_interface.show_text_only("Que nada aconteça foi o resultado que mais desejo entre todas as suposições que fizemos durante a reunião preparatória—")
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("(Mas por que... estou me sentindo um pouco envergonhado...)", "Lian")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Enquanto minha mão ainda está no pilar, a atmosfera é estranha. No momento em que estou pensando em pressioná-lo com mais força, meu coração de repente se contrai bruscamente.")
	await novel_interface.show_text_only("Quase ao mesmo tempo, o pilar estremece.")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Então, o pilar se afasta da minha mão, deixando uma pequena lacuna que se alarga lentamente.")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("—Eh?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("A plataforma alta e a parte inferior do pilar estão rangendo, produzindo ruídos profundos e baixos…")
	await novel_interface.show_text_only("Tesouro nacional de Salmonton, um artefato que simboliza a iluminação dos seres humanos durante a Renascença - O Pilar Lapis de Tesheim…")
	await novel_interface.show_text_only("… está desmoronando lentamente na direção que estou pressionando…")
	await novel_interface.show_text_only("E está caindo cada vez mais rápido.")
	await novel_interface.show_text_only("Bum——!!!")
	await novel_interface.show_text_only("O enorme estrondo ocorre quando o pilar colide com a plataforma de metal e se quebra em dois pedaços. A peça mais distante desliza alguns centímetros para frente.") #缩减符号
	await novel_interface.show_text_only("Pequenos fragmentos se espalham, e o pedaço mais distante rola até a piscina da frente.")
	await novel_interface.show_text_only("Há um longo silêncio…")
	await novel_interface.show_text_only("Por algum tempo, até mesmo Raphael perdeu sua arrogância habitual, parecendo extremamente chocada.")
	await novel_interface.show_text_only("Ela então lentamente se vira para mim.")
	await novel_interface.show_text_only("Posso ver fogo queimando em seus olhos.")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("Não, eu... eu não...", "Lian")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_flare.png")
	await novel_interface.show_text_only("Quando me esforço para pensar em maneiras de salvar meu próprio traseiro, o som de um sino de vento vem do nada.")
	await novel_interface.show_text_only("Os fragmentos caídos no chão se dividem em pedaços ainda menores e começam a flutuar como folhas de papel levadas por uma rajada de vento.")
	await novel_interface.show_text_only("Refletindo arcos coloridos de luz, os fragmentos do pilar formam vários anéis e flutuam para cima.")
	await novel_interface.show_text_only("Finalmente, todos os pedaços quebrados se dissipam no ar, deixando numerosos anéis de luz flutuantes que iluminam todo o salão.")
	novel_interface.show_character("anne_battle","happy")
	await novel_interface.show_dialog("Uau…", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Não consigo evitar tocar em um anel formado por pequenos fragmentos—")
	await novel_interface.show_text_only("O anel imediatamente se transforma em pontos dourados de luz.")
	await novel_interface.show_text_only("Os pontos flutuantes se espalham como poeira.")
	await novel_interface.show_text_only("Depois, concentram-se e criam uma luz cada vez mais deslumbrante…")
	await novel_interface.show_text_only("Pelo brilho de machucar os olhos, uma adolescente de cabelos dourados aparece na minha frente.")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("…!!!", "Lian")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	await novel_interface.show_text_only("Com os braços bem abertos, ela fica parada calmamente na minha frente... Mas não consigo desviar os olhos dessa cena glamorosa.")
	await novel_interface.show_text_only("Há um leve aroma de flor de laranjeira e violeta no ar.")
	await novel_interface.show_text_only("A garota abre lentamente os olhos.")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("Que \"resultado\" intrigante e fabuloso…", "Garota loira")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Ela olha em volta.")
	novel_interface.character_light()
	await novel_interface.show_dialog("Isso é… tempo moderno!?", "Garota loira")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Aos seus olhos, a excitação crescente está substituindo a confusão vazia.")
	novel_interface.character_light()
	await novel_interface.show_dialog("Água e carbono, cloreto de sódio e enxofre, silício e ferro…", "Garota loira")
	await novel_interface.show_dialog("Eles criaram um lindo…", "Garota loira")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Ela olha incrédula para suas mãos trêmulas.")
	novel_interface.character_light()
	await novel_interface.show_dialog("O toque do corpo…", "Garota loira")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("A garota sente lentamente seu corpo de cima a baixo.")
	await novel_interface.show_text_only("De repente percebo que não deveria olhar, então me afasto imediatamente.")
	await novel_interface.show_text_only("Mas não posso deixar de olhar para ela...")
	await novel_interface.show_text_only("Ela… está até tocando ela… ela…!!")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("…", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","perspire")
	await novel_interface.show_dialog("…", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("Mesmo isso… é recriado?", "Garota loira")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("… A luz era tão forte que não vi nada!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Temos todos os tipos de planos de emergência, mas por um tempo nenhum de nós três sabe o que fazer a seguir.")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("Então…", "Garota loira")
	novel_interface.character_dark()
	await novel_interface.show_text_only("A loira olhou para Anne e Raphael, que ainda estavam tensos, e seus olhos pousaram em mim, que parecia sem graça.")
	novel_interface.character_light()
	await novel_interface.show_dialog("Você fez esse milagre acontecer?", "Garota loira")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("A garota cai lentamente no chão e dá um passo para trás respeitosamente.")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("…Eh? \\n(Não sei onde procurar!!)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("Ou você fez este recipiente para minha alma?", "Garota loira")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("Ha… Talvez… Sim?", "Lian")
	await novel_interface.show_text_only("Desculpe, acabei de dar um empurrãozinho no pilar!")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("A garota coloca a mão sobre o peito e se curva levemente para mim.")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("Então, se você gosta…", "Garota loira")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Ela olha nos meus olhos. \\nEu li um forte desejo em seus olhos azuis.")
	novel_interface.character_light()
	await novel_interface.show_dialog("Por favor, conceda toda a sua essência a mim...", "Garota loira")
	await novel_interface.show_dialog("Mestre.", "Garota loira")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Mestre?", "Raphael & Annie")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("Eeeessência?!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Pare—!")
	await novel_interface.show_text_only("Pare com a imaginação estranha!!!")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("“Alquimia, a busca pela sabedoria dos elementos e da vida.”", "Garota loira")
	await novel_interface.show_dialog("O homem capaz de reconstruir um corpo e invocar uma alma deve possuir a verdade que não possuo.", "Garota loira")
	await novel_interface.show_dialog("Eu… Henriette Kunhardt, estou pronta para ser uma serva da verdade…", "Garota loira")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Heinrich para de repente e olha solenemente para um espaço aberto no corredor.")
	await novel_interface.show_text_only("Seguindo seu olhar, não vejo nada além de pilares.")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("(Espere. Ela disse algo sobre serva...serva?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("A garota suspira.")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("Encontrado tão rapidamente.", "Henriette")
	await novel_interface.show_dialog("Mesmo com um novo corpo, ainda estou vinculado ao contrato…", "Henriette")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ela mal terminou de falar quando o salão de repente começa a distorcer fortemente.")
	await novel_interface.show_text_only("Os sensores na caixa blindada enviam alarmes de limite de uma só vez e os indicadores de status ficam imediatamente vermelhos.")
	await novel_interface.show_text_only("Um som ensurdecedor de vidro quebrando vem de cima.")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("Atire… Um fluxo de espaço-tempo…", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Atrás de Heinrich aparece um espelho, que gira no sentido anti-horário, parecendo ondas.")
	await novel_interface.show_text_only("A garota cai para trás e gradualmente submerge no vazio.")
	novel_interface.show_character("anne_battle","perspire")
	await novel_interface.show_dialog("Ren, corra!", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mas é tarde demais—")
	novel_interface.change_background("res://assets/images/bg/Baizhu/spaceTransfer.png")
	await novel_interface.show_text_only("O espaço que nos rodeia é distorcido e gira ao longo de inúmeras superfícies espelhadas.")
	await novel_interface.show_text_only("—Então fico impressionado com a sensação de leveza.")
	await novel_interface.show_text_only("Quando finalmente volto a mim, percebo que estávamos caindo.")
	await novel_interface.show_dialog("Aaaah-!!", "Lian")
	await novel_interface.show_text_only("A única coisa que me lembro antes de desmaiar é...")
	await novel_interface.show_text_only("Minha bunda fica gelada com o vento e meu estômago dói mais!")
	await novel_interface.show_text_only("Isto é…")
	await novel_interface.show_text_only("O pior dia de todos!!!")
	
	print("=== 深海恐惧篇第9话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
