# bathophobia_ep23.gd - 深海恐惧症篇第23话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep23_script()

func play_script():
	pass

func bathophobia_ep23_script():
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Control_Room.png")
	novel_interface.show_character("milk_battle","normal")
	await novel_interface.show_dialog("Запросить доступ... окей, готово. Мы внутри.","Молоко")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Звуковой сигнал —\\nДверь в диспетчерскую распахивается.")
	await novel_interface.show_text_only("В то же время включился внутренний звуковой монитор, и Белая Свеча и Молоко вошли в комнату, поддерживая друг друга.")
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("*Кашель*","Бет")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_battle","normal")
	await novel_interface.show_dialog("*Тяжёлое дыхание*","Молоко")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","smile")
	await novel_interface.show_dialog("Сейчас мы должны быть здесь в безопасности....","Бет")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_battle","serious")
	await novel_interface.show_dialog("Да. Я проверю систему.","Молоко")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Милк подходит к панели управления и проверяет сообщения на экране. Они не говорят о слоне в комнате — о навыках, которые Бет только что раскрыла. Явно не человек.")
	novel_interface.show_character("milk_battle","pleased")
	await novel_interface.show_dialog("Ох, они используют Genuine в своей системе безопасности. Хороший.","Молоко")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Милк любит хвастаться перед Бет своим хакерским опытом. Подлинная система для нее — пустяк. Она справилась гораздо сложнее.")
	novel_interface.show_character("milk_battle","pleased")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("baizhu_break","think",0.25)
	await novel_interface.show_dialog("Молоко, я...","Бет")
	novel_interface.character_light(0.35,"laugh")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Тсс, все в порядке, я понимаю.","Молоко")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Молоко нежно гладит потрясенную девушку по голове одной рукой.")
	await novel_interface.show_text_only("Она действительно это понимает. Не то чтобы ее подруга специально скрывала свои навыки, чтобы назло ей.")
	await novel_interface.show_text_only("В конце концов, если бы Босс узнал об этом, он был бы слишком рад использовать этот «тактический ресурс» по максимуму.")
	await novel_interface.show_text_only("Гладя свою голову, Милк снимает с волос Бет черную металлическую заколку. Бет смотрит в замешательстве.")
	await novel_interface.show_text_only("Милк корчит ей рожу и быстро приседает, исчезая под столом с панелью управления.")
	await novel_interface.show_dialog("Если я использую металлический предмет для короткого замыкания системы, это срабатывает автоматическая защита от перегрузки.","Молоко")
	await novel_interface.show_text_only("После тихого шипящего звука два ряда индикаторов на панели одновременно гаснут. Центральный экран теперь полностью статичен.")
	await novel_interface.show_text_only("Выбираясь из-под стола, Милк вытаскивает из часов кабель для передачи данных и подключает его к разъему настольного компьютера.")
	await novel_interface.show_text_only("Через несколько секунд индикаторы снова загорятся, и вентиляторы снова начнут жужжать.")
	novel_interface.show_character("milk_battle","serious")
	await novel_interface.show_dialog("Если я добавлю флэш-память в очередь самотестирования до перезагрузки системы, мы сможем ввести код.","Молоко")
	novel_interface.change_expression("pleased")
	await novel_interface.show_dialog("Видишь? В конце концов, эта система безопасности... не такая уж и безопасная.","Молоко")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","mock")
	await novel_interface.show_dialog("Таким образом, независимо от того, насколько гладко спроектировано программное обеспечение, все же есть способ взломать аппаратное обеспечение... ?","Бет")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Милк говорил Бет о подобных вещах, когда они вместе обедали в своей любимой чайхане. Бет, конечно, не поняла ни слова.")
	await novel_interface.show_text_only("Милк продолжает пристально смотреть на экран, набирая быстрые команды левой рукой и посылая Бет сердечко правой рукой.")
	await novel_interface.show_text_only("Сердце из пальца — так неуместно в такой ситуации, но для Бет оно кажется теплом, облегчением, домом.")
	await novel_interface.show_text_only("В конце концов, нет нужды объяснять Милку ее навыки. Они... родственные души, верно?")
	await novel_interface.show_text_only("Милк обогнала систему и теперь использует одно из своих собственных программ, постепенно получая контроль над всеми устройствами мониторинга на базе.")
	await novel_interface.show_text_only("Бет стоит и наблюдает за другими устройствами в комнате. Рядом с главной панелью управления находится ряд оборудования, но она понятия не имеет, для чего оно используется. И у нее нет времени, чтобы это выяснить.")
	await novel_interface.show_text_only("На большом экране перед Милком начинают появляться кадры с камеры наблюдения.")
	await novel_interface.show_text_only("В центре экрана враги, поваленные отрядом на землю, медленно встают на ноги, конечности все еще искривлены.")
	await novel_interface.show_text_only("Они двигаются медленно, но их раны постепенно заживают.")
	await novel_interface.show_text_only("Молоко приближается. Зеленый, похожий на виноградную лозу организм прикрепляется к ранам, как своего рода сеть.")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("(Нечто подобное я уже видел в отчете... )","Молоко")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Это своего рода растение, похожее на плющ, которое было генетически модифицировано, чтобы цепляться за людей, красть их сознание и превращать их в машины для убийства в стиле зомби.")
	await novel_interface.show_text_only("Милк слишком хорошо знает, какой ущерб может нанести такая техника на поле боя.")
	novel_interface.show_character("milk_battle","shock")
	await novel_interface.show_dialog("... У нас проблемы.","Молоко")
	await novel_interface.hide_character() 
	await novel_interface.show_text_only("Следуя за взглядом Милка, Бет поворачивается к монитору слева.")
	await novel_interface.show_text_only("Судя по записям камер наблюдения, помимо тех, кто вступил в бой с отрядом, в настоящее время на базе находятся еще как минимум две группы противников.")
	await novel_interface.show_text_only("Один из них, эти двое отделались всего три минуты назад. Другая группа, состоящая из семи-восьми человек, в настоящее время движется с головокружительной скоростью к восточному крылу.")
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("(Если так будет продолжаться, ближайшая группа врагов нападет на нас в течение трех минут.)","Бет")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Бет поворачивается к другому набору кадров, где находит размытые изображения остальных членов отряда, которые не так давно от них отделились.")
	await novel_interface.show_text_only("Участник, держащий щит, потерял половину ноги и в настоящее время находится на носилках, которые двое других несут в лазарет.")
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("(Кажется, у них осталось не так много боеприпасов. Если они продолжат идти по восточному крылу вот так, через пять минут они столкнутся с еще одной группой врагов.)","Бет")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("Это __ЭЛЛИПСИС__","Молоко")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Милк замечает фигуру в одном из маленьких окон.")
	await novel_interface.show_text_only("Это самый быстрый враг группы. Она сейчас просто бродит по коридору, размахивая окровавленным ботинком, принадлежавшим одному из членов отряда.")
	await novel_interface.show_text_only("Словно почувствовав взгляд Бет, она наклоняет лицо к камере и улыбается — ужасающей беззубой ухмылкой.")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("Черт возьми!","Молоко")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("baizhu_break","normal",0.25)
	await novel_interface.show_dialog("Сохраняйте спокойствие, сохраняйте спокойствие.","Бет")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Бет успокаивающе похлопывает Милка по плечу, а затем начинает быстро просматривать десятки экранов наблюдения в комнате.")
	await novel_interface.show_text_only("Она быстро составляет в голове трехмерную карту расположения базы и сравнивает ее с отснятым материалом, пытаясь придумать наиболее оптимальный план.")
	await novel_interface.show_text_only("Милк может сказать, что Бет находится в одном из этих расчетливых режимов, просто взглянув на ее лицо. Когда у нее случается один из таких эпизодов, ее невозможно вывести из этого.")
	await novel_interface.show_text_only("Но, учитывая ситуацию, у нее действительно нет возможности придумать работоспособный план __ЭЛЛИПСИС__, верно?")
	novel_interface.show_character("milk_battle","gratified")
	await novel_interface.show_dialog("Мм. У Бети хорошо получается...","Молоко")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Голос Милка переходит в шепот.")
	await novel_interface.show_text_only("Она замечает на экране, что группа врагов, прочесывающая восточное крыло, каким-то образом не проверила барьер из сплава.")
	novel_interface.show_character("milk_battle","normal")
	await novel_interface.show_dialog("…","Молоко")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Милк закрывает глаза, размышляет, затем принимает решение.")
	await novel_interface.show_text_only("В мгновение ока она набирает на клавиатуре серию команд и отправляет их.")
	await novel_interface.show_text_only("Подземный военный центр обработки данных, расположенный на холмах где-то в Азии, получит сообщение в течение десяти секунд.")
	await novel_interface.show_text_only("Не мольба о помощи, а сообщение, информирующее о гибели отряда.")
	novel_interface.show_character("milk_battle","gratified")
	await novel_interface.show_dialog("(... Извините.)","Молоко")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Милк грустно улыбается Бет, которая все еще глубоко задумалась.")
	await novel_interface.show_text_only("Темноволосая девушка, кажется, светится слабым серебристым светом.")
	await novel_interface.show_dialog("... Бети...","Молоко")
	await novel_interface.show_dialog("Помнишь, когда мы впервые встретились?","Молоко")
	novel_interface.show_character("baizhu_break","shock")
	await novel_interface.show_dialog("Хм?","Бет")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Бет, все еще погруженная в планирование, почти не замечает, что делает Милк.")
	await novel_interface.show_dialog("Тогда я украл отчет об исследовании прямо на твоих глазах. Помните это?","Молоко")
	novel_interface.show_character("baizhu_break","smile")
	await novel_interface.show_dialog("Зачем вдруг об этом упоминать?","Бет")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Вы никогда не спрашивали меня, почему я это сделал и для кого я это сделал.","Молоко")
	await novel_interface.show_text_only("Бет оборачивается, наконец уловив странные эмоции в голосе Милка.")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	novel_interface.show_character("milk_aim","normal")
	await novel_interface.show_text_only("Она поднимает взгляд и встречается взглядом со своим лидером, который указывает на нее с револьвером в одной руке.")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("Ты всегда был таким...","Молоко")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","normal")
	await novel_interface.show_dialog("…","Бет")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Бет решительно игнорирует странное поведение Милка.")
	await novel_interface.show_text_only("Она оглядывается на экраны и нетерпеливо отталкивает дуло.")
	novel_interface.show_character("baizhu_break","speechless")
	await novel_interface.show_dialog("Перестаньте шутить. У нас меньше минуты. Эти ребята скоро нас найдут.","Бет")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Милк самоуничижительно смеется.")
	novel_interface.show_character("milk_aim","gratified")
	await novel_interface.show_dialog("Видишь? Я направляю на тебя пистолет. И все же ты мне доверяешь...","Молоко")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","smile")
	await novel_interface.show_dialog("Я знаю, что ты никогда не причинишь мне вреда.","Бет")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Милк сглатывает эти слова, зная, что подруга видит ее насквозь.")
	await novel_interface.show_text_only("Она заряжает пистолет, снимает предохранитель, кладет палец на спусковой крючок и направляет его обратно на Бет.")
	novel_interface.show_character("milk_aim","gratified")
	await novel_interface.show_dialog("Отойдите.","Молоко")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("…","Бет")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Бет внезапно получает смутное представление о том, что именно планирует ее лидер.")
	novel_interface.show_character("milk_aim","solemn")
	await novel_interface.show_dialog("— Отойди!","Молоко")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("…","Бет")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Бет пятится назад, пока не оказывается спиной к задней двери диспетчерской.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Tunneling.png")
	await novel_interface.show_text_only("Дверь распахивается, открывая наклонный проход.")
	await novel_interface.show_text_only("Бет продолжает пятиться назад, дуло пистолета Милка все еще направлено ей между глаз.")
	novel_interface.show_character("milk_aim","gratified")
	await novel_interface.show_dialog("Эй, ты помнишь этот вопрос?","Молоко")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("Хватит шутить, Милк...","Бет")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_aim","gratified")
	await novel_interface.show_dialog("Есть поезд, который просто не может остановиться. Есть два пути развития событий. С одной стороны, это сокрушает ваших товарищей по команде. Во-вторых, это тебя сокрушает.","Молоко")
	await novel_interface.show_dialog("Кого ты спасаешь?","Молоко")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","angry")
	await novel_interface.show_dialog("— Молоко!","Бет")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Горе на лице Милка очевидно, и это прискорбно.")
	novel_interface.show_character("milk_aim","mock")
	await novel_interface.show_dialog("Я решил спасти... того, кого люблю...","Молоко")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("С проницательной улыбкой Милк бросается вперед, заставляя Бет попасть в люк на стене туннеля.")
	await novel_interface.show_dialog("А, __ЭЛЛИПСИС__ ?","Бет")
	await novel_interface.show_text_only("Прежде чем Бет успевает среагировать, она скатывается по лестнице в один из единственных секретных складов на базе, защищенный барьером из сплава.")
	await novel_interface.show_text_only("Барьер, который можно открыть только снаружи.")
	novel_interface.show_character("milk_aim","mock")
	await novel_interface.show_dialog("Бети...","Молоко")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Цифровой голос говорит монотонно.\\n\"Система безопасности заблокирована. Шлагбаум закрывается\".")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Locking.png")
	await novel_interface.show_text_only("Перед глазами Бет Милк улыбается ярче, чем когда-либо.\\nВорота барьера начинают закрываться.")
	await novel_interface.show_text_only("Слишком быстро.")
	await novel_interface.show_dialog("«Три __ЭЛЛИПСИС__»","System")
	await novel_interface.show_dialog("Давайте отпразднуем следующее Рождество вместе. Что ты говоришь?","Молоко")
	await novel_interface.show_dialog("«Два __ЭЛЛИПСИС__»","System")
	await novel_interface.show_text_only("Бет отчаянно тянется, пытаясь схватить Милка, но тот отшатывается и посылает ей летящий поцелуй.")
	await novel_interface.show_dialog("«Один __ЭЛЛИПСИС__»","System")
	await novel_interface.show_text_only("Бет смотрит с недоверием.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Locking2.png")
	await novel_interface.show_text_only("Осталась одна секунда. Лицо Бет искажается, на поверхность сразу всплывают тысячи эмоций.")
	await novel_interface.show_dialog("Давай, улыбнись! Улыбнись мне!","Молоко")
	await novel_interface.show_text_only("Это последнее, что слышит Бет перед тем, как ворота барьера захлопнутся, беспощадно и бесчувственно.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Звук ударов Бет по стене эхом разносится по туннелю.")
	await novel_interface.show_text_only("Как это тяжело звучит на многослойных платах из сплава Ti-451...")
	
	print("=== 深海恐惧症篇第23话结束 ===")
	
	await novel_interface.end_story_episode(0.5)
