# bathophobia_ep12.gd - 深海恐惧篇第12话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep12_script()

func play_script():
	pass

func bathophobia_ep12_script():
	novel_interface.change_background("res://assets/images/bg/Baizhu/CauseAndEffect.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("Thành thật mà nói, tôi không chắc chắn về danh tính thực sự của The One, bởi vì ngay cả khi anh ta có nói dối tôi, tôi cũng không thể biết được.", "Henriette")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Và tôi luôn tự hỏi, ngay cả khi tất cả đều là sự thật…", "Henriette")
	await novel_interface.show_dialog("Anh ta phải là một sinh vật vượt trội hơn nhiều so với con người. Vậy tại sao anh ấy lại bận tâm quan tâm đến chúng tôi?", "Henriette")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("Hãy nghĩ về nó. Có lẽ The One không hơn gì một đứa trẻ nghịch ngợm, thích dùng kính lúp để đốt kiến.", "Henriette")
	await novel_interface.show_dialog("Tuy nhiên, lũ kiến không biết chuyện gì đang xảy ra. Họ coi đó như một sự trừng phạt từ thần linh và phủ phục trước cái bóng đằng sau ánh sáng chói lóa.", "Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("Ha-haha…", "Raphael")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Raphael bật cười bối rối.")
	novel_interface.character_light(0.35,"mock")
	await novel_interface.show_dialog("Tôi sẽ không đồng ý.", "Raphael")
	await novel_interface.show_dialog("Mọi người cúi đầu và cầu nguyện trước đối tượng của lời cầu nguyện... Điều răn thứ nhất bướng bỉnh như một đứa trẻ.", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("Ý định của anh ta vẫn chưa được biết, nhưng xét theo tất cả những việc làm xấu xa của The One, có thể anh ta đã cố tình lôi kéo các cô gái vào cuộc.", "Henriette")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Khi cô ấy trả lời Raphael, Heinrich hướng mắt về Annie và tôi.")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("Ý bạn là… chúng tôi?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("Annie đã từng đến đây và trong khoảng thời gian cô ấy mất tích, có lẽ cô ấy đã bị mắc kẹt trong không gian này…", "Raphael")
	await novel_interface.show_dialog("Danh tính của Annie được Rose Cross phát hiện ngay sau sự cố Sky Hotel. Tuy nhiên, họ cho rằng cô ấy chỉ là một bản sao.", "Raphael")
	await novel_interface.show_dialog("Họ chỉ có thể xác nhận danh tính của cô ấy sau khi kiểm tra chéo với SID… Cô ấy đã mất tích được bảy năm.", "Raphael")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("heinrich_battle","speechless",0.25)
	await novel_interface.show_dialog("Rose Cross… Ý bạn là Rosenkreutz?", "Henriette")
	await novel_interface.show_dialog("Hội bí mật mà tôi thành lập để trao đổi học thuật giữa các nhà giả kim nữ? Bây giờ nó đã trở thành một cơ quan tình báo?", "Henriette")
	novel_interface.change_2nd_expression("mock")
	await novel_interface.show_dialog("Vì vậy, có vẻ như tôi đã để lại một “di sản” thú vị nào đó.", "Henriette")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Heinrich nở một nụ cười rạng rỡ và Raphael dường như đã linh cảm được điều gì đó.")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("Bây giờ tất cả đều có ý nghĩa… Lời chào của Rosenkreutz, khá phổ biến ngày nay, thực sự là một sự báng bổ vào thời điểm đó.", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("Cầu mong những bông hồng nở trên thập tự giá của bạn.", "Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("Hoa hồng ám chỉ các nhà giả kim nữ… Không, không chính xác. Hoa hồng tượng trưng cho tất cả phụ nữ, phải không?", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("Tôi không hiểu lắm, nhưng nó có vẻ cực kỳ tuyệt vời…", "Lian")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Dù sao đi nữa, Người mà bạn đang nói tới… Anh ấy thực sự là một kẻ xấu, phải không?", "Lian")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Nhìn thấy Annie hoàn toàn hoảng sợ, tôi cảm thấy một cơn thịnh nộ dâng trào trong mình.")
	novel_interface.character_light(0.35,"solemn")
	await novel_interface.show_dialog("Làm sao anh ta có thể ép ai đó ký hợp đồng và đưa chúng tôi đến nơi xa lạ này?", "Lian")
	await novel_interface.show_dialog("Và chắc chắn anh ta đã làm điều gì đó còn khủng khiếp hơn với Annie…", "Lian")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("Nếu tôi gặp trực tiếp anh ta, tôi sẽ đá anh ta một trận!", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("…", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","worry")
	await novel_interface.show_dialog("…", "Henriette")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Đột nhiên, một sự im lặng bao trùm giữa họ và tất cả họ đều nhìn tôi như thể tôi là một thằng ngốc.")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("Cái gì? Tại sao bạn nhìn chằm chằm vào tôi?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("… Không có gì. Bạn chỉ nghe như một thằng ngốc.", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("Nếu ngài nói vậy, thưa Thầy.", "Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("Hmm… Bây giờ, làm thế nào chúng ta có thể quay lại?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","worry")
	await novel_interface.show_dialog("Tôi sợ chúng tôi không thể. Có thể bạn không cảm thấy gì trong không gian này, nhưng chúng tôi hiện đang được chuyển đến địa điểm phân công.", "Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("Loại nhiệm vụ gì? Tôi có thể bỏ cuộc được không?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("Nói một cách đơn giản, tôi có nghĩa vụ bảo vệ mười khu vực được chỉ định trên thế giới theo hợp đồng.", "Henriette")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("Dù đó không phải là lựa chọn của tôi nhưng tôi phải thừa nhận rằng… nếu không có ai làm thì sẽ bị tàn phá.", "Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("Mười khu vực—chúng có tương ứng với mười vòng tròn trên “Cây sự sống” không?", "Raphael")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Raphael nhìn lên vật tổ hình cây trên bầu trời. Trong số tất cả các vòng tròn, có một vòng sáng màu đỏ.")
	novel_interface.character_light(0.35,"normal2")
	await novel_interface.show_dialog("Vị trí đó là… Yesod. Nó tượng trưng cho nguồn gốc của muôn loài và sức mạnh sáng tạo của thần thánh. Nó có thể được coi là “Nguồn gốc của sự sống”.", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("Tôi chưa bao giờ đến đó trước đây. Nhưng một khi chúng ta bước vào không gian này, đích đến của chúng ta là không thể thương lượng được.", "Henriette")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tôi đoán là không còn cách nào để bỏ cuộc, điều này đột nhiên làm tôi nhớ đến người bạn cũ của chúng tôi…")
	await novel_interface.show_text_only("Tôi cảm thấy ngực mình dành cho người nói.")
	novel_interface.show_character("ren_battle","speechless")
	await novel_interface.show_dialog("(Kỳ lạ. Đã lâu lắm rồi Mariru mới liên lạc với tôi…)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Nghe những gì chúng tôi đã nói, Annie bây giờ có vẻ lo lắng hơn.")
	novel_interface.show_character("anne_normal","upset")
	await novel_interface.show_dialog("Không… Không, chúng ta không thể ở lại đây…", "Annie")
	await novel_interface.show_dialog("Kẻ đó sẽ nuốt chửng tất cả chúng ta…", "Annie")
	await novel_interface.show_dialog("Chúng ta sẽ không bao giờ có cơ hội trốn thoát…", "Annie")
	await novel_interface.show_dialog("Không… Đừng!", "Annie")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Annie ôm chặt tôi trong tuyệt vọng, nhưng tôi không biết phải làm gì.")
	novel_interface.character_light()
	await novel_interface.show_dialog("Đừng bỏ tôi một mình…", "Annie")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","upset",0.25)
	await novel_interface.show_dialog("(Chúng ta không thể tiếp tục như thế này…)", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Annie đang hành động như một bệnh nhân mắc chứng PTSD. Tôi đã từng thấy những triệu chứng này trước đây ở những người lính nhập viện từng canh gác biên giới Ageis.")
	await novel_interface.show_text_only("Đợi đã… Bệnh viện… \\nTôi đã… nhập viện?")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("(Đừng bận tâm. Bây giờ tôi không có thời gian cho việc này…)", "Lian")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Có lối thoát nào không?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Heinrich lắc đầu với lòng bàn tay giơ lên.")
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("Không. Ở một mức độ nào đó, con người không hơn gì nô lệ của The One.", "Henriette")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Đưa tôi ra khỏi đây… Ren!", "Annie")
	await novel_interface.show_text_only("Annie khóc và túm chặt lấy quần áo của tôi. Khuôn mặt cô ấy đã đẫm nước mắt rồi.")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("Chúng ta phải rời khỏi đây ngay bây giờ!!!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Khi tôi gầm lên giận dữ, vật tổ bằng vàng xung quanh chúng tôi bắt đầu nứt ra.")
	await novel_interface.show_text_only("Krrr… Krrr… Krrr…")
	await novel_interface.show_text_only("Nghe như tiếng kính vỡ trong khoảng không.")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("Cái gì?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","perspire")
	await novel_interface.show_dialog("??", "Henriette")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/CauseAndEffect_collapse.png")
	await novel_interface.show_text_only("Trong con mắt của Heinrich, những mảnh vật tổ liên tục rơi xuống, giống như những quân domino rơi xuống bốn cô gái đang đứng trong khoảng không.")
	await novel_interface.show_text_only("Tất cả các mảnh vỡ đều bốc hơi khi chúng chạm tới cô gái tóc đen.")
	await novel_interface.show_text_only("Không gian xung quanh bắt đầu xoắn lại thành những hình chữ nhật đẹp đẽ, rồi lại tách ra thành các sọc không gian ba chiều.")
	await novel_interface.show_text_only("Trong chớp mắt, sự tĩnh lặng tuyệt đối tràn ngập những hình khối hình học và “mặt đất” duy nhất dưới chân mọi người rung chuyển như thể có một cơn gió mạnh thổi qua.")
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("Cái gì…", "Henriette")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Fabiola/white_bg.png")
	await novel_interface.show_text_only("Trước khi Heinrich kết thúc, mảnh vật tổ cuối cùng bắt đầu nứt.")
	await novel_interface.show_text_only("Tất cả các cô gái đều rơi vào vực sâu của khoảng không.")
	await novel_interface.show_text_only("Cú ngã bất ngờ rõ ràng đã khiến cô gái tóc vàng giật mình. Trong con ngươi giãn ra của cô ấy có một màu kỳ lạ—màu trắng.")
	await novel_interface.show_text_only("Ánh sáng trắng tinh khiết.")
	novel_interface.change_background("res://assets/images/bg/SID/spConferenceRoom.png")
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	await novel_interface.show_text_only("Vào thời điểm các cô gái biến mất, những vết nứt xuất hiện trên tấm kính chống đạn toàn năng phía trước phòng giám sát. Nó được cho là có thể ngăn chặn các cuộc tấn công bằng súng bắn tỉa điện từ.")
	await novel_interface.show_text_only("Theo giao thức bảo mật, nhóm SWAT ngay lập tức hỗ trợ các thành viên Thượng viện sơ tán khỏi khu vực khỏi lối đi dự phòng mà họ đã chuẩn bị trước.")
	await novel_interface.show_text_only("Mariru, người vẫn ở lại C?n c? Ark, đang bị Thượng viện thẩm vấn trước màn hình kỹ thuật số.")
	novel_interface.show_character("senate_taki")
	await novel_interface.show_dialog("Di tích và các đối tượng con người đều đã mất tích…", "Eloise")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("Chà, điều đó có làm bạn ngạc nhiên không?", "Mariru")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Mariru bình tĩnh nói qua bộ thu phát.")
	novel_interface.character_light(0.35,"normal2")
	await novel_interface.show_dialog("Khả năng này được đề cập trong phần ba của Báo cáo mô phỏng dòng chảy không thời gian.", "Mariru")
	await novel_interface.show_dialog("Nếu Substance H sụp đổ, nó có khả năng hút mọi thứ trong bán kính một trăm feet vào khu vực từ thông.", "Mariru")
	await novel_interface.show_dialog("Và tài năng đặc biệt của Ren đã làm tăng khả năng Raphael và Annie được đưa vào khu vực thay đổi.", "Mariru")
	await novel_interface.show_dialog("Mặc dù khu vực thí nghiệm được trang bị tấm chắn cách nhiệt…", "Mariru")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Hóa ra ngay cả những vật liệu tiên tiến nhất cũng không thể chịu được lực hấp dẫn mạnh như vậy.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Một sự im lặng ngắn ngủi quét qua phòng giám sát.")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("Haha… Một cuộc náo động ngoại giao đang đến gần, em yêu. Làm thế nào bạn có thể giữ bình tĩnh như vậy?", "Bright")
	await novel_interface.show_dialog("Nếu Tiến sĩ Dekkers biết rằng chiếc bánh dễ thương của ông ấy đã mất tích, bạn nghĩ sẽ mất bao lâu trước khi ông ấy trả thù chúng ta?", "Bright")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("Đừng lo lắng.", "Mariru")
	await novel_interface.show_dialog("Đây không phải là lần đầu tiên Ren bước vào khu vực thông lượng, và tất cả hồ sơ đều chỉ ra rằng…", "Mariru")
	await novel_interface.show_dialog("Nếu không có gì sai sót, chúng sẽ thoát khỏi vùng thay đổi trong vòng 24 giờ và xuất hiện ở một vị trí ngẫu nhiên nào đó trong New Opulentia.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("Ha… tôi thực sự hy vọng như vậy.", "Bright")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("…", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_taki")
	await novel_interface.show_dialog("Nhưng sau đó dữ liệu thử nghiệm có thể bị ô nhiễm…", "Eloise")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("Họ mang theo thiết bị ghi âm. Mọi thứ xảy ra trong khu vực thông lượng đó sẽ được ghi lại.", "Mariru")
	await novel_interface.show_dialog("Đó là cách chúng tôi sử dụng để lấy thông tin về các vùng thông lượng.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("Còn dữ liệu về kích hoạt Substance H thì sao?", "Kirs")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Bộ thu phát phát ra tiếng ồn nhỏ.")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("Nó đã được xử lý.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Khi dữ liệu trên màn hình kỹ thuật số bắt đầu được làm mới, các thành viên Thượng viện dần dần nới lỏng, ngoại trừ Tiến sĩ #C.")
	await novel_interface.show_text_only("Anh đứng đó, không nói nên lời.")
	await novel_interface.show_text_only("Thay vì cùng những người khác sơ tán căn cứ, Tiến sĩ #C chọn ở lại. Đằng sau cánh cửa sổ nứt toác, anh ấy nhìn Mariru, đứng đó ở trung tâm của bục thí nghiệm.")
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("Điều gì sẽ xảy ra nếu những chú mèo con bị lạc và rơi vào tay người khác…", "#C")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("Nếu điều đó thực sự xảy ra, chúng ta có thể dùng chúng để kiểm tra Ilyanthos.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("Whoa, whoa, whoa… Tôi tưởng bạn rất tử tế với bạn bè của mình. Tôi đoán là tôi đã sai rồi.", "#C")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("Bíp–")
	await novel_interface.show_text_only("Đang đợi trước màn hình, Aya nhấc máy ngay khi bộ đàm phát ra tiếng bíp.")
	await novel_interface.show_dialog("Aya, bạn có thể theo dõi vị trí con chip của Ren không?", "Mariru")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("Chết tiệt! Chúng tôi đã mất tín hiệu vài phút trước.", "Ai")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Aya cắn bút và tỏ ra thất vọng tsk.")
	novel_interface.character_light(0.35,"stare")
	await novel_interface.show_dialog("Điều đó thật kỳ lạ. Con chip được trang bị RBM, có thể giúp chúng tôi truy xuất vị trí thô của Ren ngay cả trong khu vực thông lượng. Và chúng tôi chưa bao giờ mất tín hiệu trước đây…", "Ai")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("Việc cụm vệ tinh bị mất tín hiệu đột ngột là điều không thể. Phải chăng cô bé đã bị nhiệt độ cao bốc hơi ngay lập tức…", "Ai")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("… Nó không buồn cười chút nào!", "Mariru")
	await novel_interface.show_text_only("Ở bên kia đầu dây, Mariru cất giọng với vẻ lo lắng hiếm thấy.")
	await novel_interface.show_dialog("Chúng tôi gặp chút rắc rối ở đây… Từ camera đặt ở dưới đó, điều cuối cùng chúng tôi nhìn thấy là Trụ Lapis bị Ren xé nát.", "Mariru")
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("Thật là một ngón tay bơ…", "Ai")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Sau đó, đột nhiên, tất cả các thiết bị chụp ảnh quang học, nhiệt và vi sóng đều đồng loạt bị hỏng.", "Mariru")
	await novel_interface.show_dialog("Khi tín hiệu quay lại thì các cô gái đã đi hết.", "Mariru")
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("Chắc chắn đã có chuyện gì đó khủng khiếp xảy ra… Chết tiệt! Không có dữ liệu nào cả!!", "Ai")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Theo kế hoạch của chúng tôi, Ren phải đưa bất cứ ai cô ấy mang về từ khu vực thông lượng đến lối ra trước khi lớp ngụy trang quang học biến mất.", "Mariru")
	await novel_interface.show_dialog("(Đó là cách duy nhất để làm sai lệch dữ liệu của khu vực thông lượng. Chỉ khi đó chúng ta mới có thể khiến Thượng viện không biết về khả năng thực sự của Ren và Raphael.)", "Mariru")
	await novel_interface.show_dialog("Chúng tôi đã thu thập hai bộ dữ liệu trong quá trình thử nghiệm và một trong số chúng có vẻ rất giống với những gì chúng tôi thu thập được khi Beatrice hoạt động trở lại.", "Mariru")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("Vậy… Điều đó có nghĩa là thí nghiệm đã thành công?", "Ai")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru giọng đột ngột trở nên lạnh lùng.")
	await novel_interface.show_dialog("Mặc dù đối với bộ khác… Chúng tôi không thể tìm thấy một kết quả phù hợp nào.", "Mariru")
	await novel_interface.show_dialog("Người ta tin rằng tất cả bọn họ, kể cả người họ mang về, đều đã bị hút vào một khu vực không xác định.", "Mariru")
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("Hoan hô!", "Ai")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Aya kêu lên vui sướng.")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("… Thông tin chi tiết đã được truyền tới SID thông qua các kênh được mã hóa.", "Mariru")
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("Ren không bao giờ hết làm tôi ngạc nhiên!", "Ai")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Theo dõi cô ấy.", "Mariru")
	await novel_interface.show_dialog("Tôi cần một báo cáo phân tích trong 30 phút.", "Mariru")
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("Roger đó.", "Ai")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Trên màn hình lớn trước mặt Aya, một vài chữ cái màu đỏ xuất hiện bên cạnh nơi đánh dấu vị trí của cô được nhìn thấy lần cuối–")
	await novel_interface.show_text_only("Ngoại tuyến–")
	
	print("=== 深海恐惧篇第12话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
