# bathophobia_ep07.gd - 深海恐惧篇第7话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep07_script()

func play_script():
	pass

func bathophobia_ep07_script():
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_entrance.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("Вылезая из красного купе Mariru, я чувствую, как весь мир кружится, и едва могу стоять прямо.")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("Mariru… Блин… \\nКак ты водишь!! Это безумие!!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Сегодня утром я, как обычно, свернулся калачиком под уютным одеялом. Внезапно в комнату ворвался Annie и вытащил меня из кровати.")
	await novel_interface.show_text_only("Еще полусонного меня затолкали в машину. В тот момент я все еще протестовал по поводу ее агрессивного поведения.")
	await novel_interface.show_text_only("Но после этой ужасной поездки единственное, что осталось у меня в голове: «Слава богу, я еще жив»…")
	await novel_interface.show_text_only("Проект «Арк» стартует сегодня, но мне очень хочется заболеть.")
	await novel_interface.show_text_only("У меня уже несколько дней болит живот. Блин!")
	await novel_interface.show_text_only("И меня всегда тошнит… Блин!")
	novel_interface.show_character("anne_battle","perspire")
	await novel_interface.show_dialog("С тобой все в порядке, Рен?", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я пренебрежительно машу Annie.")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("Я в порядке, просто немного приболел. И я не могу перестать дрожать прямо сейчас…", "Lian")
	await novel_interface.show_dialog("Могу ли я взять другую машину, когда мы вернемся?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("— спрашиваю я слабым голосом, умоляюще глядя на Annie.")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("Посмотри на себя. Ты так привык изображать мисс Невинность, не так ли?", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Когда я прислонился к стене в поисках поддержки, сзади раздался знакомый голос. Господи! Просто отпусти меня…")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("Рафилия? Почему ты…", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("Разве Mariru не говорил тебе, что я буду здесь?", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("Она бы не появилась, если бы я это сделал.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Глядя на меня так, будто я ее питомец, выставленный на продажу, Mariru игнорирует вопрос Рафилии.")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("Я оставляю Рена вам, \\nМисс Dekkers, нашему дорогому исполнительному представителю Salmonton.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("Подожди! Оставить меня ей?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru улыбается и ведет нас ко входу на базу «Ковчег».")
	novel_interface.show_character("anne_battle","worry")
	await novel_interface.show_dialog("Ты уверен, что это... вход?", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Перед нами вход в бетонный подвал, выходящий на эту дорогу на окраине города. Дверь пропускает только одного человека.")
	await novel_interface.show_text_only("В радиусе полумили вообще нет построек. Если бы не логотип SID, выгравированный на стене, я, должно быть, воспринял бы это как жуткое убежище для какого-то извращенца.")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("Хи-хи, пойдем со мной.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_elevator_overlook.png")
	await novel_interface.show_text_only("Мы спустились по лестнице за дверью, ведущей к большому грузовому лифту.")
	await novel_interface.show_text_only("Кажется, лифт создан для экстремальных условий. Четыре толстых металлических шкива обеспечивают безопасную и стабильную работу.")
	await novel_interface.show_text_only("Когда лифт плавно опускается, звук вращающихся шестерен доносится со всех сторон.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_elevator.png")
	await novel_interface.show_text_only("Вентиляционные отверстия, металлические сетки, заклепки и тусклый свет… Винтажные индустриальные элементы повсюду.")
	novel_interface.show_character("raphael","worry")
	await novel_interface.show_dialog("Надежность превыше всего… Я видел подобные конструкции в золотом хранилище Центрального банка Ньюморидаса.", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("Вау, ты был там?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("До Семилетней войны это была одна из крупнейших в мире строек, и нам потребовалось немало усилий, чтобы восстановить это место.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru с гордостью представляет это подземное сооружение.")
	await novel_interface.show_text_only("Рафилия права. Лифт, хотя и работает, но стабилен, как огромный кусок твердой стали. Мне приходит в голову, что даже прыжки не вызовут ни малейшего тряски лифта.")
	await novel_interface.show_text_only("Только что оправившись от укачивания, мне не терпится попробовать, но я обнаруживаю, что Рафилия пристально смотрит на меня.")
	await novel_interface.show_text_only("Поняв, что, возможно, я веду себя глупо, я тут же смущенно отмахиваюсь от этого. Но она презрительно повернула лицо к смотровому окну.")
	await novel_interface.show_text_only("Что же она может увидеть в темноте?")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("Почему ты смотришь на меня?", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Вор плачет, вор, да?")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("Ух… Никогда не ожидал, что Salmonton отправит тебя сюда.", "Lian")
	await novel_interface.show_dialog("Ведь эксперимент сегодня довольно опасен.", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Что еще более важно, я знаю, что этот эксперимент представляет собой шоу с двумя сценариями.")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("(Вы действительно понимаете, во что ввязались, миледи?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я беспомощно поворачиваюсь к Mariru.")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("На первый взгляд, это совместный исследовательский проект New Opulentia и Salmonton.", "Mariru")
	await novel_interface.show_dialog("Цель состоит в том, чтобы определить причины потока пространства-времени и меры противодействия.", "Mariru")
	await novel_interface.show_dialog("Обе стороны должны послать квалифицированного и заслуживающего доверия человека в качестве человеческого субъекта.", "Mariru")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("Теперь, когда ваша абсурдность в отеле Sky Hotel той ночью раскрыла вашу личность, вы определенно лучший выбор для New Opulentia.", "Mariru")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Mariru бросает на меня взгляд, от которого у меня по спине пробежал холодок.")
	await novel_interface.show_text_only("Да ладно, я усвоил урок…")
	novel_interface.character_light()
	await novel_interface.show_dialog("Что касается Рафилии, нашей «высокорожденной, ставшей простолюдинкой» в Госакурагаве, она вызвалась присоединиться к эксперименту от имени Salmonton.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("Волонтерство?!", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("Хм, Лазуритовый Столп очень важен для Salmonton. Я бы никогда не позволил тебе, неудачнику, облажаться.", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("Рафилия способна ускорять самоисцеление на клеточном уровне. Это подтвердила Ая.", "Mariru")
	await novel_interface.show_dialog("Но, по мнению Beatrice, Рафилии лучше работать с Реном, чтобы полностью раскрыть свой талант.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Мне внезапно пришло в голову, что на стоянке отеля Sky Hotel Рафилия исцелила Annie в мгновение ока.")
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("Значит, Рафилия на нашей стороне, верно?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("Пфф, я могу представить твой жалкий взгляд, когда ты борешься за свою жизнь. «Оууу… Я умираю… Исцели меня сейчас…»", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("Похоже, ты не можешь дождаться, когда это произойдет?!", "Lian")
	novel_interface.change_expression("perspire1")
	await novel_interface.show_dialog("Подождите, я думал, это секретный эксперимент. \\nОткуда она узнала?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("Я все объяснил доктору Dekkers.", "Mariru")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("Поскольку он стал свидетелем того, как вы воскресили Беатрис, он почувствовал, что его предыдущее сотрудничество с Сенатом было в неправильном направлении.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","bored")
	await novel_interface.show_dialog("Это как-то связано с религией?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("Вероятно, это не так просто... Но теперь Salmonton готов работать с SID, пока Рафилия находится с нами в безопасности.", "Mariru")
	await novel_interface.show_dialog("Сенат не знает о ваших настоящих способностях. Это сила, которую мы должны использовать в полной мере.", "Mariru")
	await novel_interface.show_dialog("Ведьма ничего не активирует, когда касается Осколка Ведьмы. Вот почему наш план может сработать.", "Mariru")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("Итак, я действительно хочу поблагодарить лидеров обеих сторон за то, что это произошло.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("Ты уверен, что моего капризного дедушку не обманули?", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("Твой дедушка не такой уж наивный, дорогая. Реликвия здесь ни в коем случае не является его случайным выбором.", "Mariru")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("Мы сделали все это, чтобы убедиться, что «настоящий эксперимент» может быть проведен успешно.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("Хм, если бы не приказ дедушки…", "Raphael")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Рафаэль что-то неопределенно пробормотал, его взгляд мимолетно скользнул по мне.")
	novel_interface.character_light()
	await novel_interface.show_dialog("Я бы никогда не согласился сотрудничать с этим переодетым извращенцем!", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("Но доктор Dekkers всегда говорит, что ты никогда не слушаешь.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("Хм…", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("Дайте угадаю… Salmonton действительно интересуется Генрихом, первоначальным владельцем Ляписовой колонны?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","smile")
	await novel_interface.show_dialog("Удачи, Рен!", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Сенат планирует работать с Salmonton над созданием новых ведьм за спиной SID. И на этот раз они хотят проверить целесообразность использования меня в качестве Стабилизатора.")
	await novel_interface.show_text_only("Однако Salmonton заключил секретную сделку с Mariru.")
	await novel_interface.show_text_only("Что касается Mariru, она держала Сенат в неведении относительно наших реальных способностей.")
	await novel_interface.show_text_only("Все становится сложнее. Это убивает меня…")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("(Можем ли мы действительно сражаться бок о бок?)", "Lian")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Я украдкой смотрю на властную даму передо мной.")
	novel_interface.character_light()
	await novel_interface.show_dialog("(Передача Рафилии Госакурагаве…) \\n(это тоже часть их плана?)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("(Посмотрите на это глупое лицо. Должно быть, она снова думает о чем-то глупом.)", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("…")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Лифт наконец останавливается со стуком. \\nПеред нами вырисовываются металлические ворота высотой 35 футов.")
	await novel_interface.show_text_only("Красный лазерный луч пронесся по моему телу с головы до ног. \\nВскоре из ворот раздается подтверждающий звуковой сигнал.")
	await novel_interface.show_text_only("Mariru переходит к следующему сканированию радужной оболочки.")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("Пусть они и старомодны, но меры безопасности здесь довольно жесткие…", "Lian")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_corridor.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("Когда мы закончили сканирование, гигантские ворота медленно опускаются, оставляя нас пораженными поразительным пространством за дверью.")
	await novel_interface.show_text_only("Огромное подземное пространство поддерживается двумя рядами величественных бетонных колонн.")
	await novel_interface.show_text_only("Основание каждой колонны покрыто грудами осколков брони, которые можно использовать в обоих направлениях.")
	await novel_interface.show_text_only("Вывернутые наружу эти осколки могут защитить строение от разрушительных ракетных атак. Но если использовать их в противоположном направлении, они способны разрушить все столбы сразу.")
	await novel_interface.show_text_only("Во время Семилетней войны эти осколки брони широко использовались в крепостях, которые нужно было либо блокировать, либо разрушать.")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("Здесь довольно сыро…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Пол весь в пятнах от воды. Высоко над потолком смонтированы десятки новых труб, издающих звуки протекающей жидкости.")
	await novel_interface.show_text_only("Mariru, должно быть, приложил массу усилий, чтобы преобразить это место.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Ближе к концу прохода мы оказываемся перед пространством, огороженным металлическими плитами.")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_cistern.png")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("Дамы.", "Mariru")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("Добро пожаловать на базу Арк.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я просто... Я просто не могу поверить своим глазам!")
	await novel_interface.show_text_only("Перед нами находится резервуар. Глядя на туман, поднимающийся от сверкающей воды, такое ощущение, будто я стою на пристани.")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("Просто смотрите: посадочная лестница уже на пути к нам.", "Mariru")
	
	print("=== 深海恐惧篇第7话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
