# bathophobia_ep22.gd - 潜渊症篇第22话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep22_script()

func play_script():
	pass

func bathophobia_ep22_script():
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Reference_Room_Old.png")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("... Ở đây không có tín hiệu. Không có gì cả.","Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("Phải chăng điều này có nghĩa là chúng ta lại đang ở trong “giấc mơ” đó?","Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Dù thế nào đi nữa, hệ thống thông gió vẫn hoạt động hết công suất. Chúng tôi có thể nghe thấy tiếng quạt quay thậm chí từ lỗ thông hơi trong phòng lưu trữ.")
	await novel_interface.show_text_only("Theo bản đồ, căn cứ này tuy được xây dựng từ lâu nhưng được xây dựng theo đúng tiêu chuẩn dành cho các tổ chức tuyệt mật.")
	await novel_interface.show_text_only("Truy cập giữa các phần bị hạn chế cứng nhắc. Và có vô số đơn vị độc lập, được ngăn cách bởi các rào chắn làm bằng hợp kim cường lực.")
	novel_interface.show_character("heinrich_battle","worry")
	await novel_interface.show_dialog("Bản đồ không cho biết hầu hết các phòng này làm gì. Chúng ta có nên tìm kiếm tất cả chúng?","Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("Đây là... quá phức tạp...","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sẽ phải mất hàng giờ để rà soát toàn bộ nơi này. Đầu giường, chúng tôi thậm chí không biết mình đang tìm kiếm điều gì.")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("Và có thể có những kẻ thù điên cuồng khác đang rình rập xung quanh.","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Những cô gái bù nhìn kỳ lạ mà chúng ta vừa gặp... chỉ nghĩ về họ thôi cũng khiến tim tôi đập nhanh.")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("Vâng, tôi từ chối việc chỉ là một con vịt ngồi!","Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphael đập tay xuống bàn làm tung lên một đám bụi.")
	await novel_interface.show_text_only("Camera giám sát cảm biến âm thanh phía sau thanh kim loại sẽ điều chỉnh góc của nó một chút khi có tiếng động đột ngột.")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("…","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Có lẽ đây là thời điểm tốt để hỏi câu hỏi đã ám ảnh tôi kể từ khi còn ở trạm tiếp tế.")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("Này, bạn... có thể cảm nhận được thứ gì đó được làm từ chất liệu gì không?","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Cô gái tóc vàng mỉm cười trước câu hỏi của tôi.")
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("Tất nhiên. Đó là một kỹ năng cơ bản dành cho tất cả các nhà giả kim ở Rosenkreuzer.","Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("Sau đó, nếu... có một sợi dây kim loại cách điện rất dài, liệu bạn có thể lần theo dấu vết của nó và tìm ra nơi nó dẫn đến không?","Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("Nếu tôi có thể chạm vào nó, tôi sẽ có thể làm được.","Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("Ý bạn là…","Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tôi gật đầu với Raphael. Cùng nhau, chúng tôi quay lại và nhìn chằm chằm vào góc tối của căn phòng...")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Red_Dot.png")
	await novel_interface.show_text_only("Nơi chấm sáng đỏ nhấp nháy nhịp nhàng trong tầm mắt, giống như có nhịp đập.")
	await novel_interface.show_text_only("Camera giám sát cảm biến âm thanh.")
	await novel_interface.show_text_only("Trong căn cứ ngầm rộng lớn chắc chắn phải có hàng đống những thiết bị này.")
	await novel_interface.show_text_only("Tất cả sẽ dẫn đến một nơi:")
	await novel_interface.show_dialog("Phòng điều khiển.","Lian")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Dispatched_Ship_Aisle.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("... Bão tuyết có làm mất tín hiệu không?","Mariru")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Chip GPS của Ren không còn truyền tín hiệu nữa.")
	novel_interface.character_light()
	await novel_interface.show_dialog("Nếu liên lạc bị mất ở mức độ này, các nhiệm vụ trong khu vực được bao phủ bởi các hạt tích điện năng lượng cao cũng sẽ bị ảnh hưởng, phải không?","Mariru")
	novel_interface.change_expression("sigh")
	await novel_interface.show_dialog("Các bạn ở SRD phải cố gắng lên.","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru trợn mắt nhìn Aya, người đang lè lưỡi.")
	novel_interface.show_character("liliu_uniform1","sigh")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","blush_wink",0.25)
	await novel_interface.show_dialog("Chà, rốt cuộc chúng ta đang ở Nam Cực. Tất nhiên các điều kiện ở đây khác nhau.","Ai")
	novel_interface.change_2nd_expression("blush_stare")
	await novel_interface.show_dialog("Tuy nhiên, việc mất tín hiệu như vậy... không thể nào thiết bị của chúng tôi lại vô dụng đến thế.","Ai")
	novel_interface.character_light(0.35,"serious")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ý bạn là có... lý do khác gây ra tình trạng ngắt kết nối?","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"blush_dizzy")
	await novel_interface.show_dialog("Đúng. Tôi không biết nó là gì, nhưng nó chắc hẳn rất mạnh mẽ... \\nTôi chắc chắn ghen tị với bất cứ ai đứng đằng sau điều này...","Ai")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru trầm ngâm nhìn chằm chằm vào thiết bị trên tay và dòng chữ DISCONNECTED nhấp nháy trên màn hình.")
	await novel_interface.show_text_only("Trong khi đó, Aya quan sát khuôn mặt của Mariru.")
	novel_interface.show_character("liliu_uniform1","serious")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ai","think",0.25)
	await novel_interface.show_dialog("Bạn trông giống như một người nuôi thú cưng đang lo lắng về chú mèo con bỏ trốn của mình.","Ai")
	novel_interface.character_light(0.35,"sigh")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Dù sao thì chúng ta cũng chẳng thể làm gì ngoài việc chờ đợi.","Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Aya thở ra, quay mặt về phía cửa sổ.")
	novel_interface.show_character("liliu_uniform1","sigh")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ai","normal",0.25)
	await novel_interface.show_dialog("Độ cao 37.000 mét so với mực nước biển. Giống như chúng ta đang ở ngoài không gian vậy.","Ai")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Nếu chúng ta lên cao hơn nữa, radar và hệ thống liên lạc của chúng ta sẽ ngừng hoạt động.","Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru liếc nhìn trạm làm việc trên tàu tuần dương của họ, nơi hơn ba mươi nhân viên tình báo đang bận rộn phân loại dữ liệu đến từ mọi nơi trên thế giới.")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("Tàu sân bay hạng nặng tốc độ cao này... \\nBạn đã để mắt tới nó được một thời gian rồi phải không?","Ai")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("Hà. Chắc chắn Thượng viện có một số thứ hay ho được cất giấu.","Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("Ba giờ nữa là chúng ta tới Nam Cực...","Ai")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("Nếu bất kỳ bộ phận nào trên cơ thể Ren bị gãy, chúng tôi sẽ gặp rắc rối lớn.","Ai")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Nhận thấy Aya đang cắn móng tay một cách lo lắng, Mariru gõ vào gáy cô ấy.")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("Này.","Mariru")
	await novel_interface.show_dialog("Bạn nghĩ ai đã huấn luyện những kẻ đó?","Mariru")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Tunneling.png")
	await novel_interface.show_text_only("<Căn cứ Snedronningen>")
	await novel_interface.show_text_only("Theo chỉ dẫn của Henriette, chúng tôi lần theo sợi cáp kết nối với thiết bị giám sát đến tận độ sâu của căn cứ.")
	await novel_interface.show_text_only("Các hành lang ở đây ngày càng hẹp. Những bức tường trống trơn, như thể việc xây dựng vẫn chưa hoàn thành.")
	await novel_interface.show_text_only("Tiếng bước chân của chúng tôi vọng lại từ những bức tường đường hầm. Rùng mình. Quá đáng sợ. Tôi có thể cảm thấy tim mình đang đập thình thịch trong lồng ngực.")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("…","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Đây không phải là thời điểm thích hợp cho việc này, nhưng...")
	await novel_interface.show_text_only("Nhưng tôi càng lo lắng thì càng khó kiềm chế...")
	await novel_interface.show_text_only("Tôi dừng bước, giơ một tay lên.")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("Này…","Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","stare",0.25)
	await novel_interface.show_dialog("Bây giờ thì sao?","Raphael")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Tôi có thể...","Lian")
	await novel_interface.show_dialog("Đi tới... nhà vệ sinh?","Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Tôi đang ở đây, trong một đường hầm dường như vô tận không có cửa hay lối đi rẽ nhánh, cùng với hai cô gái. Và tôi đang yêu cầu đi vệ sinh. Tôi muốn nhảy ra khỏi vách đá.")
	novel_interface.show_character("ren_battle","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("raphael","perspire",0.25)
	await novel_interface.show_dialog("…","Raphael")
	novel_interface.change_2nd_expression("subtle")
	await novel_interface.show_dialog("Bạn thậm chí có nhận ra mức độ nghiêm trọng của tình hình?","Raphael")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Tôi là... Tôi xin lỗi! Tôi không thể giúp được, được chứ?","Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Tôi khép chặt hai đùi lại, cố gắng nhìn đi chỗ khác ngoại trừ khuôn mặt chán ghét rõ ràng của Raphael.")
	novel_interface.show_character("ren_battle","shy_left")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("raphael","subtle",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("(Càng lo lắng, tôi càng tự nhủ đừng nghĩ về điều đó, cảm giác càng tệ hơn... )","Lian")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Tôi sắp tè ra quần rồi...")
	novel_interface.character_light(0.35,"sob")
	await novel_interface.show_dialog("(Tôi đã làm gì để đáng phải chịu điều này?)","Lian")
	await novel_interface.show_dialog("Uh, nếu một trong hai bạn có chai nhựa hay thứ gì đó, tôi có thể...","Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("... Hả?","Raphael")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Ặc, tôi đang nói về cái gì thế này?")
	await novel_interface.show_text_only("Raphael từng coi tôi là kẻ hư hỏng, nhưng bây giờ... có lẽ cô ấy coi tôi như rác rưởi.")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("Ngài muốn thứ gì đó để cầm nước tiểu phải không, thưa Chủ nhân? Chà, tôi có thể thử rèn một số vật liệu...","Henriette")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Henriette có vẻ thích thú chuyện này hơi quá.")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("Cố lên! Bạn biết đó không phải là ý tôi mà!","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Nhìn thấy sự tuyệt vọng trong mắt tôi, nhà giả kim cuối cùng cũng thương hại tôi và khoét một cái lỗ có kích thước vừa phải trên tường đường hầm.")
	await novel_interface.show_text_only("Phía sau bức tường là nơi trông giống như khu ở của công nhân - tối tăm, mốc meo và quan trọng nhất là có nhà vệ sinh.")
	await novel_interface.show_text_only("Thuật giả kim Viva!")
	await novel_interface.show_text_only("Tôi chui qua cái lỗ ngay lập tức, không muốn đứng dưới ánh mắt dò xét của Raphael nữa.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Nhiệt độ ở đây có vẻ thấp hơn. Có một lớp băng mỏng phủ trên tường và tôi có thể thấy hơi thở của mình phả ra thành những làn khói trắng.")
	await novel_interface.show_text_only("Với ánh sáng phát ra từ các đường hầm, tôi có thể đọc được nhiệt kế thủy ngân trên tường. Nó báo là âm ba mươi hai độ.")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("(Chà, trong trường hợp đó, nước tiểu của tôi có bị đóng băng ngay khi nó chảy ra không?)","Lian")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("(Có lẽ không... phải không?)","Lian")
	await novel_interface.show_dialog("(nhưng...)","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("…")
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Base_Tunneling.png")
	await novel_interface.show_text_only("Cuối cùng tôi cũng quay trở lại đường hầm, đỏ mặt giận dữ.")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("Điều gì khiến bạn mất nhiều thời gian thế?","Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("Mặt bạn đỏ hết rồi.","Henriette")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Toàn bộ sức mạnh trong Hỏa Ngọc của bạn đã bị tiêu hao hết chưa? Cần một cái mới?","Henriette")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("Không, không, ổn thôi!","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Xin lỗi, Henriette... \\nNgọc lửa này... không đời nào tôi cho phép bất cứ ai giữ nó bây giờ!")
	await novel_interface.show_text_only("Bàng quang không còn giết chết tôi nữa, tôi vui vẻ đi theo Henriette và Raphael khi chúng tôi tiếp tục đi dọc theo hướng dây cáp.")
	await novel_interface.show_text_only("Tôi cố nhớ lại những gì tôi vừa nhìn thấy ở khu công nhân. Trên bàn có nửa chai Vodka, còn trên tường là những tảng băng sẫm màu.")
	await novel_interface.show_text_only("Có vẻ như tôi đã đá vào một vật kim loại khi đi loanh quanh trong bóng tối... \\nChúng có phải là vỏ đạn không?")
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("Không, không. Đó chắc hẳn là trí tưởng tượng của tôi.","Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tôi quan sát xung quanh mình. Các bức tường đường hầm xi măng hầu hết để trống, chỉ có vài viên gạch.")
	await novel_interface.show_text_only("Chờ đã... gạch? Nếu nơi này đang được xây dựng như tôi nghĩ thì gạch sẽ không được đặt bừa bãi như thế này.")
	await novel_interface.show_text_only("Nhưng lực nào đã bóc tách toàn bộ bức tường bên trong của đường hầm? ?")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_text_only("(Đây...chính xác thì chuyện gì đã xảy ra.)")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Cuối cùng chúng tôi cũng đến được cửa phòng giám sát. Tay nắm cửa bị kẹt dường như đã lâu không được vặn.")
	await novel_interface.show_text_only("Điều đó không ngăn cản Henriette. Con quái vật đó chỉ đơn giản là bẻ gãy núm, ổ khóa và tất cả.")
	await novel_interface.show_text_only("Cánh cửa phòng giám sát cọt kẹt mở...")
	novel_interface.show_character("heinrich_battle","shout")
	await novel_interface.show_dialog("—Coi chừng!","Henriette")
	
	print("=== 潜渊症篇第22话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
