# bathophobia_ep11.gd - 深海恐惧篇第11话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep11_script()

func play_script():
	pass

func bathophobia_ep11_script():
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("『現実』とは何だ？")
	novel_interface.change_background("res://assets/images/bg/Baizhu/game.png")
	await novel_interface.show_text_only("私達が普段感じている『現実』とは、\\nただのゲーム中での出来事なのかもしれない。")
	await novel_interface.show_text_only("キャラクター達はログイン時に目覚め、\\nログアウト時に眠り、デリート時に死亡する。")
	await novel_interface.show_text_only("そうしている内にキャラクターは\\n自分が『魂』を持っていると錯覚し始めた。")
	await novel_interface.show_text_only("『自由意志』から生まれたものだと、\\n当たり前のように思ってしまう。\\n本当は自分の行為がコントロールされている\\nとしても。")
	await novel_interface.show_text_only("公式、定律、文法、法則……自由を得る前に\\nキャラクター全員は注ぎ込まれていく。\\n誰が創ったかも分からないゲームのルールを。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/unknowm.png")
	await novel_interface.show_text_only("仮にある日。\\n\\nレンダリングのミスにより、引き裂かれた\\n巨大なモザイクが上空に現れたとしても───")
	await novel_interface.show_text_only("キャラクター達はそれを『未知』だと認めず、\\n神話や信仰だと捻じ曲げて説明しようとする。")
	await novel_interface.show_text_only("なぜなら『未知』を認めるという事は、\\n最も畏れている可能性を否定できなくなるから。")
	await novel_interface.show_text_only("もしも、いわゆる『現実』というものが、\\nただの幻だったら。")
	await novel_interface.show_text_only("ただの夢だったら──")
	novel_interface.change_background("res://assets/images/bg/Baizhu/CauseAndEffect.png")
	await novel_interface.show_text_only("ゆっくり目を開くと、自分が朦朧とした世界に\\n存在している事に気が付いた。")
	await novel_interface.show_text_only("霧の中、ゆらゆらと水玉が不気味に宙を\\n漂っている。")
	await novel_interface.show_text_only("手を伸ばし触れようとすると、「水玉」は\\nすぐさま形を無くして消えていった。")
	await novel_interface.show_dialog("ここは……", "小憐")
	await novel_interface.show_text_only("平面な場所に立ってはいるようで重力は感じる。\\n\\nだが、下を見ても地面は見えず、\\n視覚は奇妙な墜落感を常に感じさせてくる。")
	await novel_interface.show_text_only("周囲の環境音は何かの特殊な音が混ざっている。\\n\\nしかし、判断材料のない空間では\\nどこから聞こえてくるのかさえ判別が付かない。")
	await novel_interface.show_text_only("空を見上げると、上空には透かし彫りにされた\\n模様のような樹状の紋章が浮いていた。")
	await novel_interface.show_text_only("紋章は絨毯のように空中に広がっていて、\\n微かに光を放っている。")
	await novel_interface.show_text_only("その紋章の上をなぞるようゆっくりと回るのは、\\n10個の輪。\\nその中の1つは薄く赤い色をしていた。")
	await novel_interface.show_text_only("しばらくすると、俺の足元に巨大な線と刻銘で\\n構成された図形が展開され、\\n概念上、足元は『地面』となった。")
	await novel_interface.show_text_only("よく見ると地面の図形は空の紋章と同一だ。\\nただ、遠くから見るよりも明らかに大きい。")
	await novel_interface.show_text_only("ある種の規則性が存在していそうな円環は、\\n全て直径5メートルを超えていそうだ。\\n紋章の刻銘は──意味も年代も一切が不詳。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("（俺は……夢でも見ているのか？）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("以前の訓練で、幻覚や夢を識別する方法を\\n学んだ事がある。")
	await novel_interface.show_text_only("たしか『質問』を自分へ投げかけるのだけれど、\\n何だっけ……")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("──俺、どうやってここにたどり着いたんだ？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("記憶がだんだんと蘇る。\\nさっきまで俺達は方舟基地にいて……\\nそれから急に落下して……それから……")
	await novel_interface.show_text_only("これは、夢なんかじゃない。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("（さっき現れた女の子と関係があるのか？）", "小憐")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（いきなり『マスター』とか呼んでくるし……）\\n\\n（おまけに……）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ぬあ──ッ！！　違うっ！\\nあんな映像を振り返ってる場合じゃない！")
	await novel_interface.show_text_only("アニーは！？　それにラファエルは！！？")
	await novel_interface.show_text_only("あの2人も、俺と一緒にここに落下したはず！")
	await novel_interface.show_text_only("緊張感を持ちつつ、俺は霧の中をあちらこちらと\\n見回す。\\nすると急に、背後から暖かい何かによって\\n抱きしめられた。")
	await novel_interface.show_dialog("どうか緊張なさらないで、マスター。", "金髪の少女")
	await novel_interface.show_text_only("で、で、で、出やがったな！\\n\\nあの一糸も纏ってない奴が、\\n背後から俺の腰を抱きしめている！")
	await novel_interface.show_text_only("彼女に色々と質問したいけれど、\\n振り向いていいかどうかさえ分からない……")
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("（それにあの『マスター』って呼び方……）\\n\\n（アニメとかマンガの色々なキャラ達が……）\\n\\n（いっぱい思い浮かんでくる！！）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("彼女は何かを手探りしているようだ。\\n\\n手のひらを俺の腰に軽く当てたかと思うと、\\n今度はどう鍛えても割れない俺の腹筋に触れる。")
	await novel_interface.show_text_only("静寂の中、彼女の呼吸が優しく俺の髪を撫で\\n俺の心拍数はどんどん加速していく……")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("（な、な、何する気なんだ？）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("おや？","金髪の少女")
	await novel_interface.show_text_only("彼女は何か面白いものを発見したようだった。彼女が手のひらで軽く押すと、すぐに私のお腹から「ゴロゴロ」という物足りない音が出ました。")
	await novel_interface.show_text_only("この静かな環境では、この音は特に目立ちます。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("（え？？　なんだか……）", "小憐")
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("（これ……めっちゃ恥ずかしいじゃんッ！！？）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("思わず手を払いのけた。\\n\\n彼女は軽やかに俺の目の前に回り込み、\\n好奇の目で俺を見つめる。")
	await novel_interface.show_dialog("マスターも身体を改造なされたのですね？\\n\\n……何と素晴らしい、錬金術の成果ですわ！","金髪の少女")
	await novel_interface.show_text_only("俺は自分で目を塞ごうと思ったけど、\\n彼女はすでに服を着ていた。")
	await novel_interface.show_text_only("待って、彼女はさっき俺の身体が改造された\\nって言ったよなっ？！\\n\\nそれに彼女のこの格好……")
	await novel_interface.show_text_only("ハインリッヒの服装は肉眼で見ただけでも、\\n非常に先進的な材質で構成されてるのが分かる。")
	await novel_interface.show_text_only("質感もデザインも、16世紀の工芸技術で\\n生み出せるような物じゃない……\\nいや、現代においても不可能かもしれない。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("（まさかマリルの情報が間違っている？）\\n\\n（後、彼女にはどうして身体の事がばれたの？）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("どの質問を先に聞こうか考えている最中、\\n急に服のフードを誰かに引っ張られた。")
	await novel_interface.show_text_only("ラファエルが俺を後ろに引っ張る。\\n\\n俺と金髪の少女の間を割って、立ちはだかった。")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("あんたは、いったい誰なんだッ！！？", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("──あら？", "金髪の少女")
	novel_interface.character_dark()
	await novel_interface.show_text_only("金髪の少女は、ラファエルを見ながら\\n軽蔑な笑みを浮かべた。")
	novel_interface.character_light()
	await novel_interface.show_dialog("名前を尋ねているのでしょうか？\\nわたくしは以前、そういったモノを100通りほど\\n持っておりましたが……", "金髪の少女")
	await novel_interface.show_dialog("教えてあげても構いません。\\nハインリッヒ・クンラート──\\nそれがわたくしの『契約』の名前。", "金髪の少女")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("ふざけるな！", "ラファエル")
	await novel_interface.show_dialog("あらゆる歴史文献において、ハインリッヒが\\n男性である事はさておいても──", "ラファエル")
	await novel_interface.show_dialog("あんたのような浮付いた格好……\\n\\nあんた下着の穿き方を知らないのかしらッ？", "ラファエル")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("ハインリッヒは有名な錬金術士よ。\\n\\n決してあんたみたいに破廉恥で、\\n勝手にこいつをマスターとか呼んだりしないわ！\\nそれに……精気とかなんて……ッ!", "ラファエル")
	novel_interface.character_dark()
	await novel_interface.show_text_only("ラファエル\\n自分で言いながら顔が赤くなってきてるけど。")
	novel_interface.character_light()
	await novel_interface.show_dialog("……あんたは一体何者よッ！", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("俺はラファエルに庇ってもらいながらも\\n隙間から、ハインリッヒの事を観察する。")
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("（彼女の上の服……一体どんな材質なんだ……）\\n（な、何という締め付け感！）\\n（なんだと…同時に違う方向に揺れるのか…！）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突然、ハインリッヒと目が合った。\\n\\n顔が真っ赤になってスカートの裾を弄りつつも、\\nこれ以上は彼女を直視できない。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("おや？　この肉体を完璧に錬成したのは、\\nマスター自身でありますよね？\\nご自身の作品に動揺される事はないのでは……", "ハインリッヒ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("いやいやいや、俺は男だぞ……（だったぞ……）")
	await novel_interface.show_text_only("ハインリッヒはそう言いつつ自分の服の胸元を\\n引っ張った。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("以前より大きくなっているようですが……\\nこれはマスターの趣味でしょうか？", "ハインリッヒ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ラファエルが振り返って俺を睨んだ。")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("いやッ！！　違うッ！　俺じゃない！！", "小憐")
	novel_interface.change_expression("shy")
	await novel_interface.show_text_only("俺はただ不注意で、サモントンの国宝級文化財を\\n壊しちゃっただけで……")
	await novel_interface.show_dialog("そっちの君も俺をマスターって呼ばないで……\\nレンでいいよ。", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("レン……さん……？\\n\\n偉大なる貴方様が……そのような可愛らしい\\nお名前でいらっしゃるとは。", "ハインリッヒ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("それで君は？　本当にあのハインリッヒなのか？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金髪の少女は少し躊躇ったが、手首にある数字を\\n確認して、仕方なしとばかりに溜め息を吐いた。")
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("もう400年以上も過ぎていましたか……", "ハインリッヒ")
	novel_interface.character_dark()
	await novel_interface.show_text_only("ちょっと待って、腕にデジタル時計とか\\nカレンダーでもついているのか！？")
	novel_interface.character_light()
	await novel_interface.show_dialog("以前は研究や論文の発表にしても、\\n医者として活動するにしても、\\n確かにわたくしは男性の身分を使用して\\nいました。", "ハインリッヒ")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("なので後の歴史の記録に、そう記載されていても\\n別に不自然ではありません。", "ハインリッヒ")
	await novel_interface.show_dialog("なぜなら、わたくしが生きた時代\\n女性は大学へ招かれませんでしたし──\\n教会も女性が医者となる事を\\n許してはくれませんでした──", "ハインリッヒ")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("錬金術に関しても……\\n\\nふふ、女性の身分がバレてしまっていたら、\\nすぐ宗教裁判所の者が尋ねてきた事でしょうね。", "ハインリッヒ")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("……\\n", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("なぜか最近、こういった女性に対しての様々な\\n暴挙を聞く度に、他人事ではない怒りを感じる。")
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("「教皇庁の番犬」を処理するのは簡単でしたが、\\n\\nそういった凡人にわたくしの『貴重な時間』を\\n費やす価値はございませんでした。", "ハインリッヒ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("なんか……すごいな……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ラファエルも表情から少し動揺がうかがえる。")
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("ちょっと待って、\\nどうやって男を装って大学へ行けていたんだ？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("彼女が一体どんな方法を使ったのか、\\nすごく気になってきた。もしかしたら……")
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("わたくしはただ髪の毛を短く切り、\\nいくつかの推薦状を偽造して、\\n仮名でライプツィヒ大学に紛れ込んだだけ\\nですわ。", "ハインリッヒ")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","smile",0.25)
	await novel_interface.show_dialog("髪の毛を……切るだけでいいのか？", "小憐")
	novel_interface.change_2nd_expression("wry_smile")
	await novel_interface.show_text_only("彼女の胸を改めて注視する。\\n\\n400年前の人達は、本当にドラマの中みたいに\\n男装が分からないほど目が節穴だったのか？")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("当時、わたくしは10歳になったばかりでしたが\\n大学の入試問題なんてとても簡単でして。", "ハインリッヒ")
	novel_interface.character_dark()
	await novel_interface.show_text_only("ハインリッヒは舐めるような笑みを浮かべた。")
	novel_interface.character_2nd_light(0.35,"wail")
	await novel_interface.show_dialog("失礼しましたっ！", "小憐")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("どの時代でも、秀才って怖いなッ！！")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("じゃあ今現在のあんたの格好については、\\nどう説明するのかしら？", "ラファエル")
	await novel_interface.show_dialog("ハインリッヒは医者であり、\\n錬金術士だったと語られているけど、\\nあんたの防具と武器は明らかに戦闘のための\\nものよね？", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ハインリッヒは微笑みながら、1歩下がった。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("──ああ、申し訳ございません。\\nこれはわたくしの不注意なのです。", "ハインリッヒ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ハインリッヒは右手で胸元を押さえると、\\n彼女の服の表面から破片が浮かび上がった。")
	await novel_interface.show_text_only("藍白色のリボンと多種多彩な晶石が彼女を囲み\\n金髪の少女の身体を包んで輝く。")
	await novel_interface.show_text_only("青金石のような綺麗な色をした光が、\\n消えていくにつれ……\\nハインリッヒの身体がだんだん……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("だんだん……だんだん……\\n\\n……え？")
	await novel_interface.show_text_only("ラファエルは即座に駆け寄ってきてしっかりと\\n俺の目を覆った。")
	await novel_interface.show_dialog("もういいッ！　分かったから──", "ラファエル")
	await novel_interface.show_dialog("この露出狂、早く服を着なさい！！", "ラファエル")
	await novel_interface.show_dialog("女装もあるけど何見てるの！", "ラファエル")
	await novel_interface.show_text_only("俺、何も見てないのに！！")
	novel_interface.show_background("res://assets/images/bg/Baizhu/CauseAndEffect.png")
	await novel_interface.show_text_only("ラファエルが手を放すと、すでにハインリッヒはさっきの格好に戻っていた。\\n……はぁ。")
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("これは魔術による戦闘服です。\\n\\nマスターが着ているものと似てはいますが、\\n製造者はもっと上位の存在です。", "ハインリッヒ")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("このデザインについては『あの方』の\\n悪趣味かもしれませんが……", "ハインリッヒ")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("『あの方』？", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("かつてわたくしは錬金術で、この空間の『扉』を\\n創り出しました。", "ハインリッヒ")
	await novel_interface.show_dialog("しかしながら、凡才が真理を覗くには代価を\\n払わなければなりませんわ。\\nだから『あの方』は強引にわたくしと魂の契約を\\n結びました。", "ハインリッヒ")
	novel_interface.character_dark()
	await novel_interface.show_text_only("ハインリッヒは達観したような表情を見せる。")
	novel_interface.character_light(0.35,"bored")
	await novel_interface.show_dialog("（ブツブツ） 前回は体が吹き飛ばされてしまいましたが、新たな体でも契約は発動できるのですね…。", "ハインリッヒ")
	await novel_interface.show_dialog("本当に永々無窮と付きまとうのですね……", "ハインリッヒ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("────？", "小憐")
	novel_interface.character_dark()
	await novel_interface.show_text_only("ハインリッヒが何を言っているのかを\\n不思議に思っている時、\\nアニーの震えた声が急に濃霧の中から\\n伝わってきた。")
	await novel_interface.show_dialog("レンちゃん……", "アニー")
	novel_interface.character_light(0.35,"solemn")
	await novel_interface.show_dialog("アニーッ！？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("俺達は声の方に走っていく。すると\\n地面にうずくまり震えているアニーを見つけた。")
	await novel_interface.show_dialog("た、助けて……", "アニー")
	await novel_interface.show_dialog("いや……やだよ……", "アニー")
	await novel_interface.show_text_only("アニーを慰めようと急いで前に出たその時、私の手がアニーの体に触れた瞬間――")
	await novel_interface.show_text_only("形のない柔らかなモノが手の甲を素早く滑り、\\n粘り気のある熱波を帯びながら、遠くに離れた。")
	await novel_interface.show_text_only("周りを見回したが、特に異常はない。\\n\\nただハインリッヒは少し驚いている様子で、\\n俺を見つめている。")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("大丈夫だよ、アニーっ！", "小憐")
	novel_interface.change_expression("solemn")
	await novel_interface.show_dialog("……アニー？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("震えているアニーの様子が、明らかにおかしい。")
	await novel_interface.show_text_only("未知の空間への恐怖は分かるが……\\nこの広々とした空間に、敵の気配は全くない。")
	await novel_interface.show_text_only("俺は最大限に彼女を落ち着かせようと、\\nアニーを抱きしめた。")
	await novel_interface.show_text_only("ラファエルはアニーの様子を見てから、\\n改めてハインリッヒの方を向く。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("さっきあんたが言っていた「この空間」って\\n『因果の狭間』の事か？", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("それは『セフィロトの樹』に刻まれた名前……", "ハインリッヒ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("『セフィロトの樹』？", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("勝手に私達をこんな場所に連れてきて、\\nあんたは一体どういうつもり？", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ハインリッヒは肩をすくめた。")
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("原因はわたくしではありませんわ。", "ハインリッヒ")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("本来なら、貴方達はここにたどり着けるはずが\\nないのです……", "ハインリッヒ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("うぇ？", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("『あの方』……もしくはさらなる上位に存在する\\n意志でもない限り。", "ハインリッヒ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("さっきから君が言う『あの方』って一体……", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("契約により、わたくしは名前を口にする事が\\nできません。\\nですが『あの方』には多くの呼び名があります。", "ハインリッヒ")
	await novel_interface.show_dialog("『真理』　『道』　『扉』", "ハインリッヒ")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("全ては始まりから……終わりまで。", "ハインリッヒ")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("……！！？", "ラファエル")

	print("=== 深海恐惧篇第11话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
