# bathophobia_ep03.gd - 深海恐惧篇第3话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep03_script()

func play_script():
	pass

func bathophobia_ep03_script():
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("Mariru подходит к Ае и наклоняется, чтобы прочитать освежающие данные на экране.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Медицинское заключение Beatrice?", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","dizzy",0.25)
	await novel_interface.show_dialog("Угу, идеальный образец!", "Ai")
	novel_interface.change_2nd_expression("wink")
	await novel_interface.show_dialog("И было бы гораздо интереснее, если бы мы могли сравнить это с историческими записями.", "Ai")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Но ни одна из наших баз данных не содержит никакой ее информации. Возможно, это связано с пробелом в данных, вызванным войной.", "Mariru")
	await novel_interface.show_dialog("Тем не менее, согласно ее заявлениям и вашему отчету…", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru выводит на экран профиль Beatrice.")
	novel_interface.show_character("liliu_research","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ai","wink",0.25)
	await novel_interface.show_dialog("24 года… \\nКакой прекрасный возраст!", "Ai")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru и Ая переглядываются, зная, что заметили то же самое. Затем они снова поворачиваются к экрану.")
	novel_interface.show_character("liliu_research","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ai","wink",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Это результат ее анализов в ту ночь, когда она появилась на свет?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal")
	await novel_interface.show_dialog("В ее организме практически не обнаружено радиоактивных элементов. Хотя уровень тяжелых металлов в ее пробах крови относительно высок.", "Ai")
	await novel_interface.show_dialog("Возможно, это как-то связано с посудой или грубой косметикой Средневековья…", "Ai")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Итак, вы уже сделали вывод?", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","stare",0.25)
	await novel_interface.show_dialog("Ведь согласно записям ее заявлений...", "Ai")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Ая проводит пальцем по строке текста на экране.")
	await novel_interface.show_text_only("GMT+9 13:09:11 Цель утверждает, что годом рождения является 1265 год нашей эры.")
	novel_interface.show_character("liliu_research","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ai","stare",0.25)
	await novel_interface.show_dialog("— Впервые вижу живой образец из древних времен.", "Ai")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Может ли быть то же самое с Annie?", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Нет! \\nBeatrice сказала, что она на 100 процентов уверена, что она мертва.", "Ai")
	novel_interface.change_2nd_expression("think")
	await novel_interface.show_dialog("Она заявила, что намеренно выпила яд.", "Ai")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Есть исторические данные, подтверждающие это... Но нельзя исключать возможность фальсификации.", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Ая открывает еще один отчет о тестировании.")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("В средние века зарегистрировано лишь ограниченное количество ядов. Болиголов, паслен, рвотный орех и т. д.", "Ai")
	await novel_interface.show_dialog("Мы обнаружили остатки токсичного алкалоида в образцах ее крови, взятых в ночь, когда она появилась на свет.", "Ai")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Но в крови, которую мы взяли на следующий день, почти нет следов каких-либо токсичных алкалоидов или тяжелых металлов.", "Ai")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","happy",0.25)
	await novel_interface.show_dialog("Неудивительно, что ты выглядишь таким взволнованным…", "Mariru")
	novel_interface.character_light(0.35,"dizzy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Подождите, это еще не самое интересное!", "Ai")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Голос Аи дрожит от волнения.")
	novel_interface.show_character("ai","dizzy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("liliu_research","happy",0.25)
	await novel_interface.show_dialog("В отличие от Annie, Beatrice имеет иммунную систему, обнаруженную у новорожденных. У нее отрицательный результат на IgD.", "Ai")
	await novel_interface.show_dialog("И… свойства микробиома в ее организме почти такие же, как у Рена!!", "Ai")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("… Как вам вообще пришла в голову идея пройти эти тесты?", "Mariru")
	novel_interface.character_light(0.35,"blush_dizzy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Интуиция. Инстинкт. И страсть к редким образцам!!", "Ai")
	await novel_interface.show_dialog("Тело, созданное из ничего… точно воспроизводящее самое интересное «проклятие» на эту тему – способность привлекать любовь.", "Ai")
	await novel_interface.show_dialog("Рен просто… невероятен!!", "Ai")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Сказав это, Ая закрывает глаза и скрещивает руки, чтобы обнять себя, выглядя совершенно опьяненной своими мыслями.")
	await novel_interface.show_text_only("Mariru достает пачку отчетов и сильно стучит Аю по лбу.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Если душа может самостоятельно существовать в другом Пространстве-времени…", "Mariru")
	await novel_interface.show_dialog("Тогда как он выбирает контейнер?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush")
	await novel_interface.show_dialog("Может ли это иметь какое-то отношение к золотой бабочке?", "Ai")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("Нет, учитывая Annie и ее бейсбольную биту, я думаю, что Beatrice каким-то образом связана с зеленым камнем…", "Mariru")
	await novel_interface.show_dialog("Как будто некоторые предметы могут призывать прикрепленные к ним души.", "Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Речь идет о путешествиях в пространстве-времени и создании тел…", "Mariru")
	await novel_interface.show_dialog("(Сенат никогда не должен ничего знать об этом.)", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("Значит, Рен даже может привлечь душу…", "Ai")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ая прерывает ход мыслей Mariru.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Хм?", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","normal",0.25)
	await novel_interface.show_dialog("Получить определённую душу из ниоткуда и создать тело для неё… Это звучит как запретная алхимия.", "Ai")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_dialog("Если бы я не жил в эту эпоху, я, возможно, попытался бы торговать душами с богами, используя основные элементы, как алхимики.", "Ai")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Подобно так называемому «Сыну Богов», продвигаемому небольшими религиозными группами. Но в New Opulentia для этого нет рынка.", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"blush_think")
	await novel_interface.show_dialog("Нет, я предпочитаю женские титулы, такие как «Богиня». Они дают мне внутреннее желание бросить вызов воздержанию.", "Ai")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Черт возьми, с какой стати я нанял такого человека, как ты…", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"blush")
	await novel_interface.show_dialog("Угу! Возможно, наши души просто притягиваются друг к другу.", "Ai")
	await novel_interface.hide_all_characters()
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_heathRoom.png")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("— Итак, это все, что я нашел.", "Ai")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("А?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("В медицинском центре, после регулярного медицинского осмотра, я разговариваю с Аей о Beatrice, пока одеваюсь.")
	await novel_interface.show_text_only("Комментарий Аи о физическом состоянии Beatrice может иметь смысл…")
	await novel_interface.show_text_only("Но теория души звучит как полная чушь…")
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("(Особенно так называемая «Богиня»…) \\n(Хотя я когда-то снимал такие роли в видеоиграх)", "Lian")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("(Но я бы никогда не хотел себе такого титула!)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я не могу удержаться от дрожи, обхватив себя руками.")
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("Нет, никогда!!", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","stare",0.25)
	await novel_interface.show_dialog("Ох-ля-ля, у тебя на уме есть что-нибудь невыразимое?", "Ai")
	novel_interface.character_light(0.35,"bored")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Итак... Вот почему количество моих контрольных предметов увеличилось?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Угу.", "Ai")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Ая показывает лисью улыбку, словно что-то тайно планирует.")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("(Может быть, это очередное несанкционированное исследование…)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("Жаль, что у меня недостаточно вспомогательного оборудования; в противном случае я мог бы провести более «интересные» тесты…", "Ai")
	novel_interface.change_expression("blush_wink")
	await novel_interface.show_dialog("Кстати, хочешь опробовать режим максимальной мощности встроенного в тебя чипа?", "Ai")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("Нет! Большое спасибо!!", "Lian")

	print("=== 深海恐惧篇第3话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
