# bathophobia_ep17.gd - 深海恐惧症篇第17话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep17_script()

func play_script():
	pass

func bathophobia_ep17_script():
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Snedronningen.png")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	await novel_interface.show_text_only("Una interminable extensión de tierra desolada, teñida de un verde místico por la impresionante aurora australis.")
	await novel_interface.show_text_only("Una hilera de faros atraviesa la gélida y silenciosa penumbra.")
	await novel_interface.show_text_only("Pertenecen a una flota de motos de nieve. Los scooters pasan por las llanuras de hielo envueltas en la oscuridad, pasan por el helipuerto y finalmente se estacionan en la entrada de la extensa base.")
	await novel_interface.show_text_only("Frente a ellos hay un monumento con forma de capullo. Una caja de muestras de alta resistencia, utilizada anteriormente para contener meteoros del Monte Grove, está incrustada en su superficie rocosa.")
	await novel_interface.show_text_only("La palabra \"Snedronningen\" está pintada innumerables veces alrededor de la caja, brillando en plata bajo un foco.")
	await novel_interface.show_text_only("Snedronningen: la Reina Blanca. El nombre de la base que buscan los ciclistas.")
	await novel_interface.show_text_only("Un miembro del escuadrón fuertemente armado, que va al frente, le arranca la visera.")
	novel_interface.show_character("milk_battle","normal")
	await novel_interface.show_dialog("—¡Aaa y aquí estamos!", "Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Siguiendo su ejemplo, los cinco jinetes restantes apagan sus motores y desmontan, cada uno recogiendo sus respectivos suministros.")
	await novel_interface.show_text_only("Este es un equipo de investigación científica, uno en el que todos los miembros han recibido entrenamiento de combate estándar.")
	await novel_interface.show_text_only("Los informes de ondas de radio generadas por Substance H detectadas en la Antártida hace dos meses han atraído a muchas facciones curiosas a la zona. La mayoría de ellos vinieron armados.")
	await novel_interface.show_text_only("Para el equipo, es aconsejable ser cauteloso para mantener a salvo a los ejemplares.")
	await novel_interface.show_text_only("Han tenido suerte hasta ahora. El viaje a la base de investigación mencionada en el plan de respaldo se desarrolló sin problemas.")
	await novel_interface.show_dialog("Muy bien. Todo lo que tenemos que hacer es entregar las cosas.", "Miembro del equipo D")
	novel_interface.show_character("baizhu_battle","normal")
	await novel_interface.show_dialog("Sí.", "Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("A diferencia de los demás, que van envueltos en capas gruesas y cálidas, Beth viste un atuendo informal, que claramente no se ve afectado por la temperatura extrema.")
	await novel_interface.show_text_only("Sus armas mejoradas también se destacan entre la multitud.")
	await novel_interface.show_text_only("Su viaje había transcurrido exactamente como ella esperaba...")
	await novel_interface.show_text_only("Beth se había sumergido en las profundidades del océano hacía apenas unas horas y había logrado recuperar muestras vivas que había recogido del cuerpo de una criatura no identificada.")
	await novel_interface.show_text_only("Para concluir el proyecto de investigación, el supervisor de Milk envió el Rompehielos Ushuaia para ayudar al escuadrón de operaciones especiales.")
	await novel_interface.show_text_only("Cuando la caja de muestras estaba siendo trasladada al Ushuaia, el biolaboratorio del barco sufrió “accidentalmente” un corte de energía.")
	await novel_interface.show_text_only("Al mismo tiempo, la base de Snedronningen, a aproximadamente una hora de viaje, ofreció dejar que el equipo almacenara temporalmente las muestras en su laboratorio, que cumple con todas las especificaciones.")
	await novel_interface.show_text_only("El equipo pronto recibió permiso para entrar en las instalaciones y se le encomendó la tarea de llevar los especímenes a la base de Snedronningen en un plazo de noventa minutos.")
	novel_interface.show_character("baizhu_battle","normal")
	await novel_interface.show_dialog("(Hemos llegado hasta aquí...)", "Beth")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("¿Aparecerán esos cabrones?", "Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beth aprieta el puño.")
	await novel_interface.show_text_only("Lo que le molesta aún más es que algo en la caja de muestras parece haber desencadenado una especie de respuesta en su cuerpo.")
	novel_interface.show_character("baizhu_battle","sad")
	await novel_interface.show_dialog("... \\n(Esto le resulta familiar por alguna razón... )", "Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Antes de que pueda seguir contemplando esto, el mundo comienza a temblar violentamente.")
	novel_interface.show_character("baizhu_battle","speechless")
	await novel_interface.show_dialog("(¿Estoy simplemente mareado por la inmersión?)", "Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("No, eso no es todo.")
	await novel_interface.show_text_only("—Toda esta tierra está temblando.")
	await novel_interface.show_text_only("Se puede escuchar un estruendo profundo desde la distancia.")
	await novel_interface.show_text_only("Incluso los veteranos más curtidos parecen conmocionados.")
	await novel_interface.show_text_only("El temblor que sacude este continente blanco dura menos de treinta segundos.")
	novel_interface.show_character("milk_battle","shock")
	await novel_interface.show_dialog("La Antártida no está en la zona de terremotos... ¿verdad?", "Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("El terremoto no fue demasiado fuerte. Sin embargo, dejó a todos un poco mareados.")
	await novel_interface.show_dialog("(Murmurando) Es mucho peor que el tsunami...", "Miembro del equipo B")
	await novel_interface.show_dialog("La plataforma de hielo bajo nuestros pies parece bastante resistente. Si el mismo terremoto hubiera ocurrido en una ciudad tropical densamente poblada, habría causado muchos más daños.", "Líder de escuadrón")
	await novel_interface.show_text_only("Los miembros del escuadrón ignoran este terremoto de pequeña escala y continúan con su trabajo.")
	novel_interface.show_character("baizhu_battle","normal")
	await novel_interface.show_dialog("Está bien, vámonos.", "Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Con la caja de muestras asegurada en sus brazos, Beth salta del asiento trasero de la moto de nieve de Milk.")
	await novel_interface.show_dialog("Estoy agotado. No puedo esperar a llegar a casa, a mi cama y tomar un chocolate caliente.", "Miembro del equipo B")
	await novel_interface.show_text_only("Mientras los miembros del escuadrón ya están bajando la guardia, el líder permanece alerta y envía miradas significativas en el camino de Beth.")
	await novel_interface.show_text_only("Si no fuera por esta chica, habrían fracasado en esta misión, tal como lo hicieron todas las demás facciones.")
	await novel_interface.show_text_only("Tuvo que sumergirse en las profundidades del océano, correr el riesgo de sufrir una enfermedad por descompresión y enfrentarse a criaturas no identificadas...")
	await novel_interface.show_text_only("Hay demasiado en juego. Ni siquiera la propia Milk podría haber garantizado el éxito en tales circunstancias.")
	await novel_interface.show_dialog("Entonces todo lo que tenemos que hacer es entregarle el material a los científicos aquí, ¿verdad?", "Miembro del equipo D")
	await novel_interface.show_dialog("Beth, déjanos invitarte a una cerveza cuando regresemos a Buenos Aires, ¿eh?", "Miembro del equipo C")
	novel_interface.show_character("milk_battle","sprite")
	await novel_interface.show_dialog("¡De ninguna manera! ¡Nuestra Bethy no bebe alcohol!", "Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tomando a Beth en sus brazos, declara Milk.")
	await novel_interface.show_text_only("Bai Zhu apretó los labios, reprimiendo deliberadamente su inquietud.")
	await novel_interface.show_text_only("Milk envía múltiples solicitudes de entrada a la puerta de la base, pero no recibe respuesta.")
	novel_interface.show_character("milk_battle","shock")
	await novel_interface.show_dialog("Que extraño...", "Milk")
	await novel_interface.show_dialog("¿El terremoto arruinó la conexión o algo así?\\nTodavía estaban en contacto justo antes de que atracáramos.", "Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Aún así, aunque los picos en la puerta principal que restringen la entrada de vehículos permanecen en pie, el escuadrón técnicamente puede ingresar de todos modos; después de todo, han recibido el código de acceso por adelantado.")
	await novel_interface.show_text_only("Entonces se dirigen hacia la barrera brillantemente iluminada al costado de la base.")
	await novel_interface.show_text_only("Beth se detiene de repente y le entrega la caja de especímenes a uno de sus compañeros de escuadrón.")
	await novel_interface.show_text_only("Con sus manos libres, agarra con fuerza sus armas.")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("... ¿Qué pasa?", "Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Al darse cuenta de las acciones de Beth, Milk también saca sus armas, con los ojos alerta.")
	await novel_interface.show_text_only("Los otros miembros también se tensan y entran en modo batalla, avanzando en una formación en forma de abanico, mirándose las espaldas unos a otros.")
	await novel_interface.show_dialog("... ¿Qué diablos?", "Miembro del equipo D")
	await novel_interface.show_dialog("Shh, mantenlo bajo.", "Líder de escuadrón")
	await novel_interface.show_text_only("Lo único que se oye en el silencio ensordecedor son los chirridos de las botas de nieve sobre la superficie del hielo y la respiración tranquila de los miembros del escuadrón.")
	await novel_interface.show_text_only("Milk se acerca a la puerta e introduce el código en la cerradura de seguridad.")
	await novel_interface.show_text_only("El sistema acepta el código y la palabra ENTER parpadea en verde en la pantalla.")
	novel_interface.show_character("milk_battle","normal")
	await novel_interface.show_dialog("Vaya... esto debería ser seguro, ¿verdad?", "Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Pero Beth todavía no puede reprimir la inquietante sensación en sus entrañas...")
	novel_interface.change_background("res://assets/images/bg/Baizhu/baizhuBase.png")
	await novel_interface.show_text_only("La barrera que conduce a la base de Snedronningen finalmente se abre, junto con sonidos de engranajes chirriando y cuerdas tensas.")
	await novel_interface.show_text_only("Detrás de la puerta hay un tramo de escaleras que desciende directamente hacia el nivel inferior con poca luz.")
	await novel_interface.show_dialog("¿Alguien?", "Milk")
	await novel_interface.show_text_only("Su pregunta resuena por el estrecho pasillo.")
	await novel_interface.show_dialog("Entiendo que la mayoría de las instalaciones aquí están bajo tierra, pero ¿no podrían haber enviado a alguien arriba para darnos la bienvenida?", "Milk")
	await novel_interface.show_dialog("Al menos uno de esos investigadores debería venir y revisar las muestras...", "Miembro del equipo B")
	await novel_interface.show_dialog("¡En posición de batalla!", "Beth")
	await novel_interface.show_text_only("Con los ojos fijos en el otro extremo de las escaleras, Beth grita su orden.")
	await novel_interface.show_dialog("Alguien nos está mirando.", "Beth")
	await novel_interface.show_dialog("Cuanto más encubierta sea la opción, más fácil será llamar la atención, supongo...", "Milk")
	await novel_interface.show_dialog("(¿Son nuestros enemigos los que te preocupan?)", "Milk")
	await novel_interface.show_text_only("Una serie de seguros de armas que saltan rompen el terrible silencio.")
	await novel_interface.show_text_only("Los miembros del escuadrón, todos soldados entrenados por derecho propio, miran a la chica que ocupa el puesto de comandante temporal, esperando sus órdenes.")
	await novel_interface.show_dialog("Estamos en un lugar muy expuesto en este momento. Estaremos en peligro si tienen una emboscada. Podemos retirarnos afuera de...", "Miembro del equipo D")
	await novel_interface.show_dialog("No puedo. Recibimos una advertencia, decía que habrá una tormenta de nieve en una hora.", "Beth")
	await novel_interface.show_dialog("Todos en alerta máxima. Sigue moviéndote.", "Beth")
	await novel_interface.show_dialog("(Todos) ¡Sí, señor!", "Miembro del equipo")
	await novel_interface.show_text_only("Los miembros del escuadrón avanzan de puntillas, manteniendo la respiración baja.")
	await novel_interface.hide_background()
	novel_interface.change_music("res://assets/audio/music/Hand-to-hand combat.mp3")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("¡Cuidado!", "Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("El sonido de una hoja afilada cortando el aire rompió el momento de silencio.")
	await novel_interface.show_text_only("Una criatura que empuña un arma pesada con forma de guadaña salta de las sombras y corta el costado derecho de Beth.")
	await novel_interface.show_text_only("La advertencia de Milk llegó justo a tiempo, lo que le permitió a Beth esquivar el ataque.")
	novel_interface.show_character("baizhu_battle","stare")
	await novel_interface.show_dialog("¡¿Qué?!!", "Beth")
	await novel_interface.hide_character()
	novel_interface.show_character("witch_third")
	await novel_interface.show_dialog("Jajaja... jajajajaja...", "???")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("El atacante es una niña: ojos hundidos, postura distorsionada. Se inclina hacia delante y sus articulaciones hacen ruido, ruidoso y desorientador.")
	await novel_interface.show_text_only("Varios otros, con rostros frescos y expresiones de locura, surgen a través de la entrada del pasillo previamente vacía.") 
	await novel_interface.show_text_only("Los miembros del escuadrón inmediatamente se ponen en su formación triangular estándar, mientras continúan disparando a los atacantes.")
	await novel_interface.show_text_only("Siguiendo el ejemplo de Beth, rodean al miembro que sostiene la caja de muestras, protegiéndola por todos lados.")
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Snedronningen_Exhibition_Room.png")
	await novel_interface.show_text_only("El equipo mantiene un ritmo de disparo constante mientras busca cobertura. Pronto llegan a un espacio que parece ser una sala de exposiciones.")
	await novel_interface.show_text_only("Aquí las luces son tenues y las exhibiciones son en su mayoría especímenes de animales.")
	await novel_interface.show_text_only("El líder ordena al equipo que forme una línea de defensa en la entrada de la sala, mientras el resto del escuadrón discute las cualidades anormales que han notado en estos enemigos.")
	await novel_interface.show_text_only("Cuando son golpeados, no sangran. Ni siquiera parecen sentir dolor.")
	await novel_interface.show_text_only("El grupo despliega sus escudos antidisturbios de fibra de Kevler, que bloquean un poco los ataques.")
	await novel_interface.show_text_only("Los enemigos que se precipitan desde el otro lado, con grandes espadas en mano, son retenidos en la esquina por miembros del escuadrón que sostienen aún más escudos antidisturbios.")
	await novel_interface.show_text_only("Mientras tanto, detrás de los portaescudos, siguen lloviendo balas de 9 mm sobre los enemigos y el olor a pólvora flota en el aire.")
	await novel_interface.show_dialog("¡Recarga!", "Miembro del equipo C")
	await novel_interface.show_text_only("Los disparos no hacen nada para disuadir a los extraños enemigos. Incluso cuando las balas les atraviesan la cara, estas espantosas chicas siguen sonriendo.")
	await novel_interface.show_text_only("Hasta que una de las chicas salta sobre un escudo y se cuelga boca abajo, como un murciélago, en el techo del pasillo.")
	novel_interface.show_character("milk_battle","shock")
	await novel_interface.show_dialog("Uh... ¿Es ella siquiera... humana?", "Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("De las heridas de bala de la niña sale un líquido verde tinta. Su cuello, casi partido por la mitad por la fuerza de las balas, ahora está teñido de un inquietante color púrpura verdoso.")
	await novel_interface.show_dialog("¡Cuidado!", "Miembro del equipo B")
	await novel_interface.show_text_only("Más enemigos vienen cargando desde el final del corredor.")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("¡Retirada! ¡Retiro!", "Milk")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Los miembros del escuadrón no tienen más remedio que dividirse en dos direcciones y buscar otros puntos de ataque adecuados, que afortunadamente encuentran pronto.")
	await novel_interface.show_text_only("No han estado luchando por mucho tiempo todavía, pero para todos es obvio que los enemigos, sean los que sean, son tan poderosos como los suyos.")
	await novel_interface.show_text_only("Y también cien por cien más loco.")
	novel_interface.show_character("baizhu_battle","angry")
	await novel_interface.show_dialog("... ¿Qué son...?", "Beth")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("milk_battle","solemn",0.25)
	await novel_interface.show_dialog("¿Qué diablos?\\n¡No pueden ser humanos!", "Milk")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Para Beth, es obvio que estas jóvenes que empuñan espadas son como ella...")
	await novel_interface.show_text_only("No, no del todo.")
	novel_interface.show_character("baizhu_battle","stare")
	await novel_interface.show_dialog("(Se parecen más a lo que su padre describió...)\\n(Estilo de \\\"Ningen\\\")", "Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Son resistentes, se recuperan rápidamente y tienen articulaciones extremadamente flexibles que los hacen menos humanos y más parecidos a ágiles marionetas. Demasiado poderoso.")
	await novel_interface.show_text_only("Y claramente se han vuelto locos. Como máquinas de matar activadas por programas.")
	novel_interface.show_character("witch_third")
	await novel_interface.show_dialog("Jajajaja... Jajajajajaja...", "Pitonisa irregular")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Su balbuceo sin sentido suena como una especie de canto demoníaco. Definitivamente no es humano.")
	await novel_interface.show_text_only("De repente, el miembro del escuadrón que sostiene la caja de muestras es alcanzado por una flecha. Mientras cae al suelo, la caja se le escapa de los brazos.")
	await novel_interface.show_text_only("Pero los enemigos no parecen tener prisa por recogerlo.")
	await novel_interface.show_dialog("¡Beth!", "Miembro del equipo D")
	await novel_interface.show_text_only("Los miembros del escuadrón, obligados a llegar hasta las profundidades de la sala de exposición por el avance de los enemigos, gritan a su comandante para que les dé más instrucciones.")
	await novel_interface.show_text_only("Esta es una situación en la que no se aplica ningún protocolo normal. Lo único en lo que Beth puede confiar ahora es en sus propios sentidos y juicio.")
	novel_interface.show_character("baizhu_battle","stare")
	await novel_interface.show_dialog("(¿Entonces no están aquí por los especímenes?)", "Beth")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("¡Maldita sea!", "Milk")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_battle","stare")
	await novel_interface.show_dialog("(Entonces su objetivo debe ser—)", "Beth")
	novel_interface.change_expression("angry")
	await novel_interface.show_text_only("—para aniquilarnos a todos.")
	await novel_interface.show_dialog("... \\n(Así que son ustedes, de hecho,...)", "Beth")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La mirada de Beth se posa en el símbolo bordado en el parche del ojo de una de esas marionetas.")
	await novel_interface.show_text_only("Ha visto ese símbolo innumerables veces mientras investigaba la muerte de su padre.")
	await novel_interface.show_text_only("Es un ojo solitario y espeluznante, un ojo con extremidades.")
	print("=== 深海恐惧症篇第17话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
