# chapter3_ep04.gd - 第三章第4话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep04_script()

func play_script():
	pass

func chapter3_ep04_script():
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	await novel_interface.show_text_only("Han pasado unos días desde que se publicó el anuncio de búsqueda.")
	await novel_interface.show_text_only("Tal como predijo Mariru, el incidente no parece tener ningún efecto en la vida diaria de las personas.")
	await novel_interface.show_text_only("Tampoco hay apenas rastros de la ingeniería de distracción de Mariru.")
	await novel_interface.show_text_only("Parece nada más que una pesadilla.")
	novel_interface.show_character("iluka_normal","smile")
	await novel_interface.show_dialog("Buenos días, hermana Lian.", "Elluka")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Como bruja con habilidades especiales, Elluka es vigilada de cerca por SID.")
	await novel_interface.show_text_only("Pero el niño parece apegado a mí. Mariru me la envía todos los días, alegando que simplemente está siendo amable.")
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("Buenos días, Elluka. \\n¿Quieres comer algo entre comidas?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","smile")
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("¡Oye! ¡No les dé a los niños demasiados bocadillos!", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_normal","worry")
	await novel_interface.show_dialog("Boohoo...", "Elluka")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","happy")
	await novel_interface.show_dialog("Está bien. No son demasiados.", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","stare",0.25)
	await novel_interface.show_dialog("Vamos, siempre dices eso.", "Annie")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_dialog("¿Y está bien que se quede con nosotros todo el día?", "Annie")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("¿Eh?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("Los niños de su edad deberían ir a la escuela. \\n¿No es así?", "Annie")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("… Umm, supongo que no es sólo una niña.", "Lian")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"upset")
	await novel_interface.show_dialog("Claro, pero todavía estoy un poco preocupado...", "Annie")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_dialog("Todo es culpa tuya. ¡Sigue alimentándola, estoy empezando a preocuparme por su peso!", "Annie")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("iluka_normal","unhappy")
	await novel_interface.show_dialog("Annie, malo.", "Elluka")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elluka mira fijamente a Annie con una mirada herida. Y Annie pone cara de tristeza.")
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("Ahora sé lo que se siente ser una madre estricta...", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("Muy bien. No seas tan duro.", "Lian")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("Toma, Elluka, un último trozo de chocolate hoy. No más. \\nA continuación, te llevaré a mi escuela.", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elluka solo puede moverse libremente entre nuestro apartamento y la escuela, según lo exige Mariru.")
	novel_interface.show_character("iluka_normal","normal")
	await novel_interface.show_dialog("Ah...", "Elluka")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_centreSpace1.png")
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("… Aún así, triste.", "Elluka")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Le doy unas palmaditas en la cabeza y la llevo a la escuela junto con Annie.")
	await novel_interface.show_text_only("Mmmm, que lindo día. Ni demasiado caliente ni demasiado frío.")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("ren_uniform","smile",0.25)
	await novel_interface.show_dialog("No te sientas mal, cariño.", "Lian")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("Elluka de repente levanta la cabeza y me mira a los ojos, con chocolate en los labios.")
	novel_interface.character_light(0.35,"gourmet")
	await novel_interface.show_dialog("Hermana Lian ...", "Elluka")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"shy_left")
	await novel_interface.show_dialog("(¡Oh por favor, no me mires así!)", "Lian")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("Elluka se pone de puntillas para agarrar mi mano y se la pone en la cabeza.")
	novel_interface.character_light()
	await novel_interface.show_dialog("De nuevo.", "Elluka")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"awkward")
	await novel_interface.show_text_only("¿¡Es esto una ofensiva de encanto!? \\n¡Oh, no, eso es algo que ningún hombre podría resistir!")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("Tut-tut, te gusta Lolita, ¿eh?", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("nyx_normal","mock")
	await novel_interface.show_dialog("Jeje, eso creo.", "Nix")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Escucho la voz de Nix detrás de mí.")
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("Nix?!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("¿Cómo podría acercarse a nosotros sin hacer ningún ruido?")
	novel_interface.show_character("ren_uniform","perspire1")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_normal","smile",0.25)
	await novel_interface.show_dialog("Lo siento, ¿te asusté?", "Nix")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("No, sólo... \\nEstá bien.", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Me da vergüenza pensar que me pillarán mirando estúpidamente a Elluka.")
	await novel_interface.show_text_only("Y me alivia que Nix no continúe con este tema. ¡Es tan simpática y elegante!")
	novel_interface.show_character("nyx_normal","smile")
	await novel_interface.show_dialog("Tu nombre es Elluka, ¿verdad?", "Nix")
	await novel_interface.show_dialog("Si te gusta el postre, la próxima vez te compraré un bizcocho, ¿vale?", "Nix")
	await novel_interface.show_dialog("Conozco una panadería increíble en Theatre Street. Sirven jarabe de arce realmente bueno, sabe casi a caramelo.", "Nix")
	await novel_interface.show_dialog("Y te encantará su exclusiva crema de chocolate dentro del pastel.", "Nix")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elluka piensa por un momento y asiente porque no logra resistir la tentación de la comida.")
	novel_interface.show_character("anne_uniform","stare")
	await novel_interface.show_dialog("Elluka, ¡no aceptas comida de extraños!", "Annie")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","smile",0.25)
	await novel_interface.show_dialog("Está bien. Nix es nuestro mayor de todos modos.", "Lian")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"worry")
	await novel_interface.show_dialog("Sí, pero…", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("¿Soy solo yo?")
	await novel_interface.show_text_only("Parece que Annie ha desconfiado de Nix desde la primera vez que se conocieron.")
	novel_interface.show_character("nyx_normal","smile")
	await novel_interface.show_dialog("Entonces es un trato, Elluka.", "Nix")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_normal","smile")
	await novel_interface.show_dialog("¡Trato!", "Elluka")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mi teléfono suena de repente. \\nEs Mariru.")
	novel_interface.show_character("ren_uniform","normal1")
	await novel_interface.show_dialog("… Hola?", "Lian")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("(¡Uf, no otra misión otra vez!) \\n(Honestamente, ¡no todos los días elimino Elluka!)", "Lian")

	print("=== 第三章第4话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
