# chapter3_ep16.gd - 第三章第16话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep16_script()

func play_script():
	pass

func chapter3_ep16_script():
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	await novel_interface.show_text_only("È passata una settimana da quando i flussi spaziotemporali sono stati rilevati allo Sky Hotel.")
	await novel_interface.show_text_only("La dottoressa Aya ha realizzato Beatrice un delicato braccialetto con il Substance H metallo utilizzato nel guscio interno della valigia.")
	await novel_interface.show_text_only("Grazie al braccialetto ora può accendere o spegnere liberamente la sua magia che attrae gli uomini.")
	await novel_interface.show_text_only("In cambio, Beatrice si è unito a SID come agente, proprio come Annie.")
	await novel_interface.show_text_only("Mariru la colloca nella stanza degli ospiti in questo lussuoso appartamento.")
	await novel_interface.show_text_only("All'inizio temevo che i soldati della sicurezza ci identificassero dalle riprese delle telecamere a circuito chiuso del piano esecutivo.")
	await novel_interface.show_text_only("Ma sorprendentemente, nessuno di noi è stato ripreso dalla telecamera. Nemmeno Jacob e i suoi compagni.")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("Mariru, quanta potenza ha realmente SID?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","normal",0.25)
	await novel_interface.show_dialog("Eh? Perché me lo chiedi?", "Mariru")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Dato che questa volta è stata coinvolta più di una Città Accademica, ho pensato che sarebbe stato un brutto lavoro rimettere a posto il caos.", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Sono felice che tu abbia così tanta fiducia in SID…", "Mariru")
	novel_interface.change_2nd_expression("speak")
	await novel_interface.show_dialog("Ma tu e Annie non sareste mai riusciti a fuggire da quel posto tutti interi se non fosse stato per il Senato. Come sapete, il Senato ha una grande voce in capitolo nel Congresso Unito.", "Mariru")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("Il dottor Kirs, il vecchio con la faccia da poker, gioca sempre le sue carte al sicuro. Quindi non so cosa abbia fatto esattamente.", "Mariru")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("(Faccia da poker... vecchio mio?) \\nPensavo che il Senato avrebbe condiviso le sue informazioni con SID...", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("Sei troppo ingenuo...", "Mariru")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("Nessuna agenzia di intelligence condividerebbe tutta la sua intelligence con i capi di stato o di governo.", "Mariru")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Eh? Perché?!", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("Come si suol dire, conoscere è possedere.", "Mariru")
	await novel_interface.show_dialog("Il Senato è la massima autorità in New Opulentia. Quindi, naturalmente, SID deve funzionare con esso. In altre parole, SID e il Senato sono partner.", "Mariru")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("Se fossi tu il capo, forniresti gratuitamente tutte le informazioni riservate al tuo partner?", "Mariru")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Mhm... certo che no...", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("E se il tuo partner avesse delle preziose informazioni riservate che desideri davvero, cosa faresti?", "Mariru")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Fammi vedere... \\nForse comprerò qualche custode.", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("Ragazza intelligente. Finché l’agenzia è abbastanza grande, può sempre essere violata dall’interno, non importa quanto rigido sia il suo protocollo di sicurezza.", "Mariru")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Se... se è così, abbiamo nei anche in SID?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("Puoi scommetterci. Ci sono migliaia di dipendenti nel SID e alcuni di loro devono essere spie, provenienti dal Senato, da agenzie di intelligence straniere o da altre organizzazioni.", "Mariru")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("Ecco perché dobbiamo tenere aggiornato solo un piccolo gruppo di persone quando si tratta di informazioni chiave.", "Mariru")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("E che dire della Sala d'Avorio...", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("Non è qualcosa di cui dovresti preoccuparti. Ragazze ingenue come te non potranno mai infiltrarsi al Senato.", "Mariru")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("Tutti i membri del Senato sono esperti nel campo del Substance H con un grado minimo di livello SS.", "Mariru")
	await novel_interface.show_dialog("Questi esperti hanno un sacco di elementi Substance H da sperimentare. Se ti intrufoli lì dentro, potresti subire il lavaggio del cervello prima che tu te ne accorga.", "Mariru")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ma... ci sono ancora molti punti discutibili in questo caso.", "Lian")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Ad esempio, perché la delegazione Salmonton ha contrabbandato la farfalla d'oro a New Opulentia?", "Lian")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("E quella collana di Raphael, che è piuttosto antiquata, chiaramente non è la sua tazza di tè. Di solito lo infila sotto il colletto.", "Lian")
	await novel_interface.show_dialog("In realtà, Raphael che io sappia... non indosserebbe mai tali ornamenti...", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Hai ragione. La farfalla dorata ha proprietà simili a quelle del meme infettivo Substance H. La protezione dello scudo che usiamo per un oggetto così pericoloso è solitamente grande quanto un camion.", "Mariru")
	novel_interface.change_2nd_expression("angry")
	await novel_interface.show_dialog("Ma l'hanno semplicemente messo in una valigia. L'energia che fuoriesce da quella valigia può essere rilevata anche dai satelliti.", "Mariru")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("Se davvero volevano introdurlo di nascosto, perché dovevano convincere quei funzionari governativi a farlo? Perché dovrebbero correre un rischio politico così grande?", "Mariru")
	novel_interface.character_light(0.35,"solemn")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Forse non c'è alcun rischio. Forse è un ordine di qualcuno più in alto che ha dato loro la garanzia...", "Lian")
	await novel_interface.show_dialog("I membri della delegazione non sono tenuti a dichiarare il bagaglio a mano ai controlli di sicurezza. E hanno scelto deliberatamente un albergo fuori dalla nostra giurisdizione.", "Lian")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("Stai dicendo...", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("Finalmente capito?", "Mariru")
	novel_interface.character_light(0.35,"solemn")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Il Senato glielo ha ordinato? Solo per tenere SID all'oscuro?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("Jacob è un addetto militare di Salmonton e i dati di Elluka mostrano che studiano le streghe da un po'.", "Mariru")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("La farfalla d'oro appartiene a una strega e Jacob è apparsa all'improvviso e si è unita alla lotta. \\nPensaci...", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("La corsa per il controllo del potere soprannaturale ha gettato il mondo nel caos della Guerra dei Sette Anni. Succederà di nuovo?")
	novel_interface.show_character("ren_battle","normal1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_research","normal",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Verranno prodotte più streghe allora?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("È ora di prepararsi per questa battaglia sottobanco.", "Mariru")
	await novel_interface.hide_all_characters()
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_centreSpace1.png")
	await novel_interface.show_text_only("Alcune settimane dopo")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("Nnngh ... Riesco a malapena a tenere gli occhi aperti ... \\nSono rimasto sveglio tutta la notte a giocare ...", "Lian")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Ehi, maniaco del travestitismo.")
	novel_interface.character_light(0.35,"wry_smile")
	await novel_interface.show_dialog("???", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La voce familiare...")
	await novel_interface.show_text_only("Il luogo familiare…")
	await novel_interface.show_text_only("E il saluto familiare…")
	await novel_interface.show_text_only("La ragazza in piedi di fronte a me… È ancora lei!")
	await novel_interface.show_text_only("Questo piantagrane dalla lingua tagliente Raphael!")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("Ra-Raphael? \\nPerché sei qui?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","stare",0.25)
	await novel_interface.show_dialog("Non ti hanno insegnato le buone maniere in questa scuola, vero?", "Raphael")
	novel_interface.change_2nd_expression("mock")
	await novel_interface.show_dialog("Sono il tuo senior. Mostra un po' di rispetto!", "Raphael")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Eh?!", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Non l'avevo notato fino ad ora... \\nCon la cartella a portata di mano, indossa l'uniforme e le scarpe da studentessa del secondo anno.")
	novel_interface.show_character("ren_uniform","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("raphael","mock",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Pensavo che odiassi questa scuola...", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("Non avevo altra scelta. \\nTutte le scuole in New Opulentia fanno schifo.", "Raphael")
	novel_interface.change_2nd_expression("mock")
	await novel_interface.show_dialog("Essendo una strega, questa scuola potrebbe essere la scelta migliore per me.", "Raphael")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("Sembra che Raphael abbia fatto tutte le ricerche e abbia preso la sua decisione in così poco tempo. Che genio.")
	novel_interface.character_light(0.35,"upset")
	await novel_interface.show_dialog("La tua famiglia... hai detto loro che sei una strega?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("Perché preoccuparsi? Non porterebbe loro altro che preoccupazioni.", "Raphael")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("Ehi, diventare una strega non è come entrare in un club doposcuola!")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Riesci a immaginare che mi abbiano mandato all'estero solo per lasciarmi riposare dopo quella stupida intervista?", "Raphael")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_dialog("Se lo venissero a sapere, probabilmente andrebbero fuori di testa, come quando hanno saputo che mi ero fatto un tatuaggio.", "Raphael")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("No, no, no. È solo un gioco da ragazzi rispetto a trasformarsi in una strega! \\nBeh, se hai davvero qualche tatuaggio, mostramelo, per favore...")
	novel_interface.change_expression("perspire1")
	await novel_interface.show_dialog("A proposito... cosa diavolo hai detto nell'intervista?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Vieni dall'età della pietra o cosa? Quel video avrebbe dovuto già girare su Internet.", "Raphael")
	novel_interface.character_light(0.35,"uneasy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("A proposito, sono piuttosto popolare anche su Internet. \\nDopo tutto, sono un criminale ricercato in tutto il mondo...")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Ad essere onesti, devo essermi perso alcune grandi novità perché sono stato completamente risucchiato dal gioco di Legend of Zelda.")
	novel_interface.character_light(0.35,"stare")
	await novel_interface.show_dialog("Smettila di guardarmi in quel modo...", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Prendo il telefono per leggere le ultime notizie. Raphael non sta mentendo. Il suo nome ha fatto notizia in tutto il mondo.")
	await novel_interface.show_text_only("Riproduco uno di quei video e presto esce la voce di Raphael.")
	await novel_interface.show_dialog("Perché credono che tutti i peccatori possano essere redenti purché preghino gli dei? La preghiera non porta loro altro che un patetico conforto.", "Raphael")
	await novel_interface.show_dialog("…Quei rifiuti sono inutili ovunque vadano. Perché il nostro governo dovrebbe salvarsi il sedere? Lasciali semplicemente marcire.", "Raphael")
	await novel_interface.show_text_only("Non posso credere che questi commenti controversi siano stati fatti da Raphael, la nipote del governatore di Salmonton. Non c’è da stupirsi che abbia causato un tale tumulto.")
	novel_interface.show_character("ren_uniform","speechless")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("raphael","worry",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ricordo che Salmonton è uno stato di welfare religioso… \\nHai davvero il coraggio di fare quei commenti provocatori.", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("Tanti stati hanno dichiarato guerre in nome degli dei. Quindi, perché non posso dire quello che ho in mente?", "Raphael")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Guerra? Intendi... la Guerra dei Sette Anni?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("No, idiota. Naturalmente le guerre imminenti!", "Raphael")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_dialog("A Salmonton incoraggiamo le persone ad avere la propria religione, indipendentemente dal dio in cui credono.", "Raphael")
	await novel_interface.show_dialog("Come risultato delle massicce migrazioni seguite alla Guerra dei Sette Anni, innumerevoli rifiuti si riversarono in questi gruppi inutili, e la loro avarizia non conosceva confini.", "Raphael")
	novel_interface.change_2nd_expression("angry")
	await novel_interface.show_dialog("Il nonno è troppo indulgente con loro. Quei fannulloni dovrebbero finire nei macelli…", "Raphael")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Fermare! Sta diventando inquietante adesso...", "Lian")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"stare")
	await novel_interface.show_dialog("Ora sei al centro di questa massiccia transizione. Semplicemente non ti interessa, o sì?", "Raphael")
	novel_interface.change_2nd_expression("thinking")
	await novel_interface.show_dialog("Forse nessuno tranne gli idioti come te può vivere una vita così ottimistica.", "Raphael")

	print("=== 第三章第16话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
