# chapter3_ep14.gd - 第3章第14话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep14_script()

func play_script():
	pass

func chapter3_ep14_script():
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.change_background("res://assets/images/bg/SkyHotel/guestRoomInner.png")
	novel_interface.show_character("anne_uniform","stare")
	await novel_interface.show_dialog("Jacob Golpea al administrador de \\nElluka...", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Detrás de él veo a varios soldados de seguridad tirados en el suelo.")
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("Simplemente se desmayaron. Matar en la zona desmilitarizada no está en mi plan.", "Jacob")
	await novel_interface.show_dialog("Tenía la intención de recuperar páginas del clásico de culto El Libro de los Siete Filósofos, y no esperaba tal bonificación...", "Jacob")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","angry")
	await novel_interface.show_dialog("…", "Beatrice")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","solemn")
	await novel_interface.show_dialog("(Libro de los Siete Filósofos…) \\n(¿Es este el Grimorio vinculado a la Mariposa Dorada?)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","stare")
	await novel_interface.show_dialog("Ren... Encontré muchas heridas viejas en el cuerpo de Elluka cuando la ayudé a lavarse.", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","wry_smile")
	await novel_interface.show_dialog("(¿Lavaste Elluka?) \\n(¿¡Cuándo!?)", "Lian")
	novel_interface.change_expression("solemn")
	await novel_interface.show_dialog("(No, ese no es el punto.) \\n(Viejas heridas... ¡Eso significa...!)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","serious")
	await novel_interface.show_dialog("¡Ningún niño normal podría soportar una experiencia tan traumática!", "Annie")
	await novel_interface.show_dialog("¡¡Tiene que ser este tipo ... este es el indicado!!", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("Oh... \\nParece que esa cosa aún no se ha roto.", "Jacob")
	await novel_interface.show_dialog("Tut-tut, supongo que SID ya realizó ingeniería inversa... \\nLa tecnología que usé en él.", "Jacob")
	await novel_interface.show_dialog("Si hubiera sabido que causaría tantos problemas, le habría instalado un dispositivo de autodestrucción.", "Jacob")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","shout")
	await novel_interface.show_dialog("¡Tú—!", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","serious")
	await novel_interface.show_dialog("— ¡Pendejo!", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lo siguiente que sé es que Annie salta furiosamente e intenta patear a Jacob en la cara.")
	novel_interface.show_background("res://assets/images/bg/Baizhu/white_bg.png")
	await novel_interface.show_text_only("Chirrido—")
	await novel_interface.show_text_only("Con un grito, la habitación se ilumina con un enorme arco eléctrico. Por un momento, estoy cegado.")
	await novel_interface.show_text_only("El resplandor tarda unos segundos en desaparecer. Un dolor punzante persiste en mis ojos.")
	novel_interface.show_background("res://assets/images/bg/SkyHotel/guestRoomInner.png")
	novel_interface.show_character("ren_maid","shout")
	await novel_interface.show_dialog("Annie…!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Annie pierde el conocimiento y cae al suelo. Una franja de marcas de quemaduras en forma de ramas aparece en su piel.")
	await novel_interface.show_text_only("El soldado al lado de Jacob sostiene una pistola humeante… ¿Es esa el arma que usaron hace un momento?")
	await novel_interface.show_text_only("El soldado descarga rápidamente una bala parecida a una batería del tamaño de un bote.")
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("Sabemos cómo sacar lo mejor de las brujas...", "Jacob")
	await novel_interface.show_dialog("Prefiero atraparlos vivos. Pero la perra SID llegará pronto…", "Jacob")
	await novel_interface.show_dialog("Ahora que se nos acaba el tiempo...", "Jacob")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Jacob saca un trozo de metal con forma de pastel. El caparazón de color verde grisáceo emite un resplandor azul claro familiar.")
	novel_interface.show_character("ren_maid","solemn")
	await novel_interface.show_dialog("¿Es eso... un arma Substance H?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","angry")
	await novel_interface.show_dialog("Siento… el flujo de poder mágico…", "Beatrice")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("¿Qué diablos estás haciendo? ¡Esta es una zona desmilitarizada!", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("(Ren)", "Mariru")
	await novel_interface.show_text_only("La voz de Mariru de repente sale de los auriculares.")
	await novel_interface.show_dialog("(Esa es una trampa explosiva hecha de fibras autoadhesivas). \\n(Es un arma Substance H no letal).", "Mariru")
	await novel_interface.show_dialog("(Explota tres segundos después de la detonación). \\n(Y las fibras se esparcirán por todo el lugar. Es imposible escapar).", "Mariru")
	novel_interface.show_character("ren_maid","solemn")
	await novel_interface.show_dialog("—!?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("(Así que guarda tus fuerzas por el momento.) \\n(Ya descubriré cómo sacarte...)", "Mariru")
	await novel_interface.show_text_only("Jacob levanta lentamente la trampa explosiva en su mano derecha. Aparecen líneas doradas en su palma, como si estuviera listo para pelear.")
	novel_interface.show_character("ren_maid","solemn")
	await novel_interface.show_dialog("Su mano… ¿es esa inscripción mágica?", "Lian")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("(Finalmente… Mi turno de experimentar el arma Substance H…)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("Perdón por esto…", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beatrice de repente me agarra con una mano y le arrebata el collar a Raphael con la otra.")
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("¿Qué?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("De repente, el colgante de esmeralda emite un rayo deslumbrante y se convierte en una poderosa espada con inscripciones en la hoja.")
	novel_interface.show_character("beatrice_battle","smile1")
	await novel_interface.show_dialog("Mire estas almas miserables implorando que se limpie su pecado.", "Beatrice")
	await novel_interface.hide_character()
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("¿Qué…?", "Jacob")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","angry")
	await novel_interface.show_dialog("¡Cállate!", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beatrice empuja fuertemente la espada contra el suelo.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Jacob abre la boca, pero no sale nada. \\nLa habitación se llena de un silencio mortal.")
	await novel_interface.show_text_only("El suelo debajo de Jacob se agrieta, revelando nada más que una completa oscuridad.")
	await novel_interface.show_text_only("Se escucha un sonido espeluznante desde las profundidades de la oscuridad, como si millones de personas estuvieran de luto y aullando desde el infierno.")
	await novel_interface.show_text_only("Un humo oscuro sale de la grieta y se apodera de todos los rincones de la habitación, ahora envuelta en una oscuridad infernal en poco tiempo.")
	await novel_interface.show_text_only("Golpeado por un escalofrío en mis huesos y una profunda sensación de terror, se me erizan los pelos y no puedo moverme...")
	novel_interface.show_background("res://assets/images/bg/SkyHotel/guestRoomInner.png")
	await novel_interface.show_text_only("Pero apenas unos segundos después, la oscuridad se disipa. \\nY la grieta no se encuentra por ninguna parte.")
	await novel_interface.show_text_only("Como si sufriera un ataque de pánico, Jacob cae al suelo y se rasca el cuello con tanta fuerza que sangra.")
	await novel_interface.show_text_only("Su cara se pone roja mientras lucha por respirar. Pero sus pulmones parecen estar vacíos de aire, dejándolo jadear ruidosamente en vano.")
	await novel_interface.show_text_only("Pasa un rato antes de que recupere el aliento.")
	await novel_interface.show_text_only("El hombre alto y fornido se acurruca en la alfombra, temblando, con los brazos cruzados sobre el pecho.")
	await novel_interface.show_text_only("Sus ojos inyectados en sangre están llenos de miedo. Las lágrimas salen como resultado de la descompresión.")
	await novel_interface.show_text_only("Las líneas de su mano han desaparecido por completo y la trampa explosiva caída sobre la alfombra también ha perdido su brillo.")
	await novel_interface.show_text_only("Los soldados enmascarados están todos quietos, temblando.")
	await novel_interface.show_text_only("Desde sus rostros inexpresivos, parecen embargados por el horror de ver una realidad más allá de cualquier descripción.")
	await novel_interface.show_text_only("Si miras largamente un abismo, el abismo también te mira a ti...")
	await novel_interface.show_text_only("Ante el horror real, incluso respirar…")
	await novel_interface.show_text_only("Te hace sentir expuesto a una desesperación indescriptible.")
	novel_interface.show_character("beatrice_battle","angry")
	await novel_interface.show_dialog("¡Vamos!", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("…")
	await novel_interface.show_dialog("(¡Ren, sal de ahí!)", "Mariru")
	await novel_interface.show_text_only("Hasta ahora no he vuelto en sí. Asintiendo con la cabeza a Beatrice, salgo de la habitación con Annie en mis brazos.")
	await novel_interface.show_text_only("Beatrice arrastra a Raphael, que todavía está aturdido. Corrimos hacia el ascensor...")

	print("=== 第3章第14话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
