# chapter3_ep05.gd - 第三章第5话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep05_script()

func play_script():
	pass

func chapter3_ep05_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("Mariru отправляет Annie и Elluka, когда мы возвращаемся в штаб-квартиру.")
	await novel_interface.show_text_only("Теперь я расстроен. Не знаю, буду ли меня снова допрашивать со странными вопросами…")
	novel_interface.show_character("ren_uniform","sprite")
	await novel_interface.show_dialog("Что случилось?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal1",0.25)
	await novel_interface.show_dialog("Что, если ничего не произойдет? Ты собираешься продолжать ухмыляться Elluka, как извращенец?", "Mariru")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Вы... Вы, должно быть, наблюдали за мной через камеру наблюдения!", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak2")
	await novel_interface.show_dialog("Хе-хе, это все, что ты можешь придумать?", "Mariru")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Что еще это может быть…", "Lian")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal2")
	await novel_interface.show_dialog("Например:", "Mariru")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("Mariru злобно смотрит на меня с головы до пят.")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("Исследовательский отдел разработал пластину, которая может даже решать, когда вы пойдете в туалет!", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","perspire1",0.25)
	await novel_interface.show_dialog("Что… ванная? \\nУх, звучит отвратительно!", "Lian")
	await novel_interface.show_dialog("Должно быть, это придумал Ая! \\nПодожди, только не говори мне, что ты тайно вживил его в мое тело!", "Lian")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Я просто пошутил.", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("То, как вы это говорите, не похоже на шутку!")
	novel_interface.show_character("liliu_uniform2","speak2")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_uniform","perspire1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Или… Есть ли что-то странное, что приходит вам в голову?", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"shy")
	await novel_interface.show_dialog("Ух, блин…", "Lian")
	await novel_interface.show_dialog("(В прошлый раз я бегал во время школьного собрания…) \\n(Значит ли это…?)", "Lian")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ха-ха-ха! Не воспринимайте это всерьез!", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru громко смеется, с силой потирая мне голову.")
	novel_interface.show_character("liliu_uniform2","normal2")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_uniform","shy",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ая сделал только прототип, прежде чем я свернул проект. \\nЗачем нам использовать его на таком никем, как ты!", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"shy_right")
	await novel_interface.show_dialog("О, мне стоит сказать спасибо?", "Lian")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Хаха, у тебя грязь на уме, да?", "Mariru")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Ааа… Слава богу, нет машины, читающей мысли! Подумайте только, как это было бы стыдно!")
	novel_interface.character_light(0.35,"speak2")
	await novel_interface.show_dialog("Эй, не облажайся. Так весело наблюдать, как ты сопротивляешься.", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_text_only("Извините, что подвёл вас.")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Хм… Интересно, как такой простак, как ты, мог добывать информацию о ключевых объектах?", "Mariru")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Mariru вытирает слезы от смеха и делает свое обычное высокомерное лицо.")
	novel_interface.character_2nd_light(0.35,"upset")
	await novel_interface.show_dialog("Ключевые цели… Звучит более значимо, чем просто обслуживание вас… Но зачем мистеру Бигу разговаривать со старшеклассником!", "Lian")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("На этот раз вы приблизитесь к своей цели как студент. Цель…", "Mariru")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Raphael Dekkers, внучка мэра Salmonton. Она приедет с делегацией Salmonton.", "Mariru")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("Она настоящая знатная девушка. Взволнованный?", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("Почему я должен волноваться?", "Lian")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Тьфу-тьфу, тебе нравятся только маленькие девочки, да?", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wry_smile")
	await novel_interface.show_dialog("Эй, хватит называть меня преступником!", "Lian")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_dialog("… Кхм. \\nИ вообще, что ты хочешь, чтобы я получил от этой знатной девушки?", "Lian")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ух, ты не очень разговорчивый... \\nНадеюсь, ты продержишься хотя бы один день.", "Mariru")
	await novel_interface.show_dialog("Ладно, серьезно, что ты знаешь о Salmonton?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal2")
	await novel_interface.show_dialog("Хм... Я думаю, это крупнейший экспортер продуктов питания?", "Lian")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("Говоря о Salmonton… что мне приходит на ум, так это десятки высотных теплиц вдоль Рейна.")
	await novel_interface.show_text_only("Зеленые сады за теплицами… \\nВсегда делайте идеальные обои.")
	novel_interface.show_character("ren_uniform","normal1")
	await novel_interface.show_dialog("И церквей очень много. Все граждане имеют религиозные убеждения. Они даже сформировали Священный Альянс…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Это все, что я могу вспомнить. Я не силен в географии. Слишком много запоминания случайных фактов.")
	novel_interface.show_character("ren_uniform","normal1")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("Экономическая и политическая власть Salmonton во многом зависит от его контроля над генами сельскохозяйственных культур.", "Mariru")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("Но инциденты после исчезновения Кубка Росса создали для них серьезную угрозу.", "Mariru")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Под угрозами вы имеете в виду… Поток пространства-времени?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("Это верно. По моим сведениям, он пострадал от многочисленных флюсов. Но ущерб пока неизвестен.", "Mariru")
	await novel_interface.show_dialog("Судя по недавней волатильности цен на зерновые фьючерсы, влияние кажется довольно значительным… Возможно, будут возникать спорадические голодоморы.", "Mariru")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Это серьезно!", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Я ничего не знаю о фьючерсном рынке. Я думал, что воздействие ограничилось небольшой областью.")
	novel_interface.show_character("ren_uniform","upset")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("Да… Неурожай не причинит немедленного вреда. В любом случае у стран есть резервы риска.", "Mariru")
	await novel_interface.show_dialog("Кажется, Salmonton рухнул первым среди всех Академгородов.", "Mariru")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("Он направил делегацию на New Opulentia, которая уже в пути.", "Mariru")
	await novel_interface.show_dialog("Как их главный импортер продуктов питания, мы не можем сказать «нет».", "Mariru")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Будут ли они… подозревать Annie и меня?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak2")
	await novel_interface.show_dialog("Вот что вы собираетесь сделать.", "Mariru")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Что?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("Хотя это происходит под лозунгом программы «культурного обмена», делегация находится под жесткой охраной Королевской службы безопасности.", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Королевская служба безопасности… Разведывательное агентство Salmonton, также известное как Розенкрейц.")
	await novel_interface.show_text_only("Для разведывательной службы она слишком известна благодаря фильмам «Агент № 7».")
	novel_interface.show_character("ren_uniform","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Вызовет ли это какие-то проблемы?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Конечно. SID даже испытывает трудности со сбором исходной информации.", "Mariru")
	await novel_interface.show_dialog("На данный момент для вас важно то, что девочка будет посещать среднюю школу для девочек Госакурагава.", "Mariru")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Моя школа?!", "Lian")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal1")
	await novel_interface.show_dialog("Этого и следовало ожидать. Она примерно возраста старшеклассницы.", "Mariru")
	await novel_interface.show_dialog("Так что вам нужно выяснить настоящую цель их визита.", "Mariru")
	novel_interface.change_2nd_expression("normal2")
	await novel_interface.show_dialog("Спецслужбы подготовили буклет о Salmonton и семье Dekkers. А теперь иди и прочитай это.", "Mariru")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("Упс, снова задание на запоминание... \\nЯ об этом позабочусь!", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("Кстати, остерегайтесь извращенца по дороге домой.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_dialog("Ч-Что!?", "Lian")

	print("=== 第三章第5话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
