# chapter3_ep03.gd - 第三章第3话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep03_script()

func play_script():
	pass

func chapter3_ep03_script():
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("Você quer dizer… Eliminar todas as informações de terceiros sobre aquele cara?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("Não. Pelo contrário, acrescentarei mais informações.", "Mariru")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("O que?!", "Lian")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Um sorriso arrepiante surge no rosto de Mariru.")
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Agora, a única informação sobre o ladrão são apenas imagens de baixa resolução.", "Mariru")
	await novel_interface.show_dialog("Imagine quantas pessoas em todo o mundo têm rostos tão simples.", "Mariru")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("Espere, você acabou de dizer, claro? Isso dói.")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("E mesmo que alguém se pareça com “eu”, ainda assim seria fácil descobrir.", "Lian")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Câmeras de segurança registram tudo o que ele fez naquele dia!", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("Claro, não é difícil destacar uma pessoa real.", "Mariru")
	novel_interface.change_2nd_expression("speak2")
	await novel_interface.show_dialog("Mas e se… essa pessoa não existir?", "Mariru")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Você quer dizer…", "Lian")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0)
	await novel_interface.show_dialog("Se inserirmos algumas identidades forjadas com características faciais semelhantes às do suspeito, será quase impossível descobrir.", "Mariru")
	novel_interface.change_2nd_expression("normal2")
	await novel_interface.show_dialog("E para todos, exceto nós, essas pessoas não são diferentes de "+GameConfig.player_name+" — apenas mais desaparecidos de forma misteriosa.", "Mariru")
	novel_interface.change_2nd_expression("speak2")
	await novel_interface.show_dialog("Então como é possível descobrir o verdadeiro alvo?", "Mariru")
	await novel_interface.show_dialog("Para esconder um grão de arroz, você pode retirá-lo ou polvilhar um saco inteiro de arroz para cobri-lo.", "Mariru")
	novel_interface.character_2nd_move_left(-0.25)
	novel_interface.show_character("ren_battle","upset",0.25)
	await novel_interface.show_dialog("Parece um grande projeto…", "Lian")
	novel_interface.character_2nd_light()
	novel_interface.character_dark()
	await novel_interface.show_dialog("Apenas um pouco mais de complexidade para um problema simples, para que os contribuintes fiquem satisfeitos com a forma como o seu dinheiro é gasto. Ver? Dois coelhos com uma cajadada só.", "Mariru")
	novel_interface.character_2nd_dark()
	novel_interface.character_light(0.35,"stare")
	await novel_interface.show_dialog("Cada vez que você faz comentários tão inapropriados, quero chamar a polícia.", "Lian")
	novel_interface.character_2nd_light(0.35,"normal1")
	novel_interface.character_dark()
	await novel_interface.show_dialog("A propósito, encontrei algumas contradições nas suas informações de identidade.", "Mariru")
	novel_interface.character_2nd_dark()
	novel_interface.character_light(0.35,"normal2")
	await novel_interface.show_dialog("Hein? Qual parte?", "Lian")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal2")
	await novel_interface.show_dialog("Sobre seus pais.", "Mariru")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("Meu coração aperta ao ouvir a palavra “pais”.")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("Você me disse que sua mãe morreu cedo e que seu pai estava desaparecido.", "Mariru")
	await novel_interface.show_dialog("Eu sei que você não quer falar sobre isso. Mas é importante. Eu tenho que verificar com você.", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","upset",0.25)
	await novel_interface.show_dialog("Tudo bem…", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru recupera os dados dos quais ela fez backup.")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("Aqui diz que sua mãe desapareceu em 25 de julho de 2026, dada como morta. \\nEssa foi a Grande Tribulação.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("…", "Lian")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Shot/seabed.png")
	await novel_interface.show_text_only("Antes daquele dia, as ruínas subaquáticas no Noroeste New Opulentia eram uma cidade movimentada.")
	await novel_interface.show_text_only("Tenho apenas uma vaga lembrança disso...")
	await novel_interface.show_text_only("No momento em que a cidade foi destruída pelas armas Devine Touch, Aegis gerou um campo de proteção. New Opulentia estava bem no limite.")
	await novel_interface.show_text_only("E… Isso marcou o início da Guerra dos Sete Anos.")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("Pai, desaparecido desde dezembro de 2026. Presumido…", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("Pare… por favor!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Eu odeio essa frase fria – Presumido… morto.")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("Eu sempre digo a mim mesmo… \\nTalvez… papai ainda esteja vivo…", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("… Bem, seu pai deve estar feliz. Seu menino cresceu e se tornou uma linda menina!", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Eu rio de suas palavras. \\nDroga, eu sei que ela está me provocando!")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("Bem, olhe para isso.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ela clica nos perfis dos meus pais. Dois códigos aparecem.")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("De acordo com o perfil—", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mãe, codifique offline. \\nPai, codifique off-line.")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("… Alguma coisa errada?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("Aegis não teria atribuído um código à sua mãe se ela tivesse morrido antes do campo de proteção ser ativado ou em algum lugar fora de seu alcance.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("Ei...?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru olha para mim pensativo.")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("Você também não tem ideia? \\nOs arquivos não mentiriam. Vou tomar cuidado com isso…", "Mariru")

	print("=== 第三章第3话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
