# chapter3_ep02.gd - 第三章第2话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep02_script()

func play_script():
	pass

func chapter3_ep02_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("SID의 기록에 따르면, 알카트라즈 수용 기지는 실험과 연구가 금지된 EX급 『이물질』을 수용하고 있다.")
	await novel_interface.show_text_only("그곳의 지하는 아직 등급 책정이 끝나지 않아 출입이 금지된 고대 유적 『채터 동굴』과 연결되어 있다.")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("그 EX급 『이물질』……특별히 위험한 물건이야?", "샤오롄")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal1",0.25)
	await novel_interface.show_dialog("대부분은 종교와 관련된 『성물』이지. 신도들에게는 특별한 의미가 있기 때문에, 연구도 허락되지 않아.", "마리루")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("뭔가 눈 가리고 아웅하는 느낌인데.", "샤오롄")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("하하하. 나도 그렇게 생각해.──\\n하지만 그들의 도리도 있으니까.", "마리루")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("종교 전승 속에는 신마저 죽일 힘을 지녔거나 종말의 심판을 열 수 있는 물건도 있어.", "마리루")
	await novel_interface.show_dialog("일단 발동되면 세계 종말급 재앙을 일으킬 수도 있지.", "마리루")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("그럼 확실히……심상치 않네.", "샤오롄")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("다른 종교 이야기 속 신성한 물건은 실험 후 미미한 효과만 발견된 것도 있어…", "마리루")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("우스운 효과?", "샤오롄")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak2")
	await novel_interface.show_dialog("어느 “성인”의 신발에 키스하면 억제할 수 없는 스트리킹 충동을 불러 일으키지.", "마리루")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("그런 악취미가 있는 물건도 있구나.\\n그럼 그들이 이번에 잃어버린 건 어떤 건데?", "샤오롄")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"serious")
	await novel_interface.show_dialog("…이번에 도둑맞은 것은 모든 학원도시가 공동 감시하는 EX 『이물질』인 『천명의 창』이야.", "마리루")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"smile")
	await novel_interface.show_dialog("오오!\\n그렇구나. 대단하다!", "샤오롄")
	await novel_interface.show_dialog("그럼 『천명의 창』은 뭐야?", "샤오롄")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("…………", "마리루")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("네 지금 얼굴, 완전 바보 같아.", "마리루")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","sob",0.25)
	await novel_interface.show_dialog("모르니까 그렇지!\\n난 평범한 고등학생일 뿐이라고……", "샤오롄")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("마리루가 어쩔 수 없다는 듯 날 쳐다본다. 이 문제를 이해하려면 보충 수업이 필요하다고 생각하나 보다.")
	novel_interface.character_light()
	await novel_interface.show_dialog("전체적으로 말하면 첫번째 유형에 속해. 전설 속 신을 죽이는 능력을 가진 이물질.", "마리루")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("공개 문헌에 기록된 내용은 『고온에서 용해되지 않음』,『휘두르면 무거워짐』 이 두 개뿐이야.", "마리루")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("그게 끝이야…?", "샤오롄")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("만약 이 두 가지 설명 중 하나라도 깊이 연구한다면 XK급 『이물질』이 될 거야.", "마리루")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("만약 아직 발견 못 한 다른 특질이 있다면 더 위험해져. 그래서 최대한 미디어에 노출되는 걸 피해야 해.", "마리루")
	novel_interface.character_dark()
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("나는 침을 삼켰다. XK급 『이물질』은 어린아이도 다 알고 있는──")
	await novel_interface.show_text_only("세계 멸망급 재앙이나 동급 위력을 발휘할 수 있는 『이물질』. 현재 알려진 건 6개뿐이다. ")
	await novel_interface.show_text_only("각 학원도시에 퍼져 있다. 달리 말하면 XK급 『이물질』을 보유해야 연합회의의 인정을 받을 수 있다.")
	novel_interface.character_2nd_light(0.35,"perspire1")
	await novel_interface.show_dialog("……엣?\\n그, 그렇다면……?", "샤오롄")
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("이제 \"네가\" 저지른 죄가 얼마나 심각한 건지 알겠지?", "마리루")
	novel_interface.character_dark()
	await novel_interface.show_text_only("너무 놀라 실감이 나지 않는다. ")
	novel_interface.character_2nd_light(0.35,"sob")
	await novel_interface.show_dialog("……미안\\n아니!내가 왜 사과하는 거야!내가 훔친 게 아니잖아!!", "샤오롄")
	await novel_interface.show_dialog("(젠장, 그 녀석 엄청 위험하잖아?)", "샤오롄")
	novel_interface.change_2nd_expression("uneasy")
	await novel_interface.show_dialog("하, 하지만 뉴스를 내린 것도 불행 중 다행이야……", "샤오롄")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("바보, 뉴스를 내린 건 공포를 확산시키지 않기 위해서야.\\n수배는 비밀리에 진행되고 있어.", "마리루")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("보안을 위해 수배령이 방위청까지 내려가진 않을 테지만,\\nSID를 포함한 각국의 정보 기관은 이미 통보를 받았어. ", "마리루")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("그러니까 아직 안도의 한숨을 쉬긴 일러~", "마리루")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"upset")
	await novel_interface.show_dialog("역시……내 원래 모습은 위험한 거겠지?", "샤오롄")
	novel_interface.change_2nd_expression("perspire1")
	await novel_interface.show_dialog("만일……만일!\\n누군가 수배령의 사진으로 내 원래 모습을 찾는다면……", "샤오롄")
	await novel_interface.show_dialog("지금은 여자라고 해도 관련 인물로 취조를 받을 수 있잖아?", "샤오롄")
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("네가 드디어 문제를 파악했구나~", "마리루")
	await novel_interface.show_dialog("정보부가 감시 영상을 확보해서 네 얼굴을 한 녀석을 찾아냈어. 최근에 변이 구역에 나타났더군.", "마리루")
	await novel_interface.show_dialog("우린 제3자의 데이터를 통해 찾아냈지만, 다른 기관도 아마 이 정보를 파악했을 거야.", "마리루")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"panic")
	await novel_interface.show_dialog("상습범인가?\\n어째 내 앞길이 이미 어두워진 것 같아……", "샤오롄")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("순간 수많은 고문을 당하는 화면이 머리속을 스친다……")
	await novel_interface.show_text_only("언제든지 끌려가서 반인류 어쩌고 하는 죄명을 뒤집어 쓰고……")
	await novel_interface.show_text_only("가장 엄격한 감옥에 갇히고,2백 년 이상의 형을 선고 받겠지.")
	await novel_interface.show_text_only("무서운 감방 동기라도 만난다면……")
	await novel_interface.show_text_only("흐아～그만!!!\\n그만 생각하자!!!")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("하하하, 겁먹어서 얼굴이 창백해졌네……?", "마리루")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("걱정 마. 신토요스 안에서는 내가 너의 안전을 98% 보호할 수 있어.", "마리루")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","panic",0.25)
	await novel_interface.show_dialog("그 말은 2%는 어떻게 될지 모른다는 거잖아?!", "샤오롄")
	await novel_interface.show_dialog("(100초마다 2초의 사고가 일어날 수 있잖아!?)\\n(전혀 안도감이 없다고!!)", "샤오롄")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("연합회의가 역사 상 이렇게 빨리 의견 일치를 본 적이 없어…어쩌면 배후에 내가 모르는 힘이 있을지도 몰라.", "마리루")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("그리고 이게 바로……그 2%의 확신할 수 없는 요인이야.", "마리루")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"upset")
	await novel_interface.show_dialog("이 사건이 그들을 얼마나 흔들었을지 상상도 못하겠어…", "샤오롄")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("다른 학원도시의 정보부도 대량의 인원을 투입해서 전력으로 그 자를 찾고 있을 거야.", "마리루")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("그, 그럼 난 어떡해?", "샤오롄")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"speak2")
	await novel_interface.show_dialog("눈에 보이는 적을 상대하는 건 쉽지. 그런 전문 작업은 SID에게 맡겨. ", "마리루")

	print("=== 第三章第2话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
