# chapter3_ep05.gd - 第三章第5话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep05_script()

func play_script():
	pass

func chapter3_ep05_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("Mariru gửi Annie và Elluka đi ngay khi chúng tôi quay trở lại Trụ sở chính.")
	await novel_interface.show_text_only("Bây giờ tôi đang buồn. Tôi không biết liệu mình có bị thẩm vấn bằng những câu hỏi kỳ lạ nữa không…")
	novel_interface.show_character("ren_uniform","sprite")
	await novel_interface.show_dialog("Chuyện gì đã xảy ra vậy?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal1",0.25)
	await novel_interface.show_dialog("Nếu không có gì xảy ra thì sao? Bạn định tiếp tục cười nhạo Elluka như một kẻ hư hỏng à?", "Mariru")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Bạn… Chắc chắn bạn đã theo dõi tôi qua camera giám sát!", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak2")
	await novel_interface.show_dialog("Hehe, đó là tất cả những gì bạn có thể nghĩ đến à?", "Mariru")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Còn có thể là gì nữa…", "Lian")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal2")
	await novel_interface.show_dialog("Ví dụ—", "Mariru")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("Mariru nhìn tôi ác độc từ đầu đến chân.")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("Phòng Nghiên cứu đã phát triển một loại bánh xốp thậm chí có thể quyết định thời điểm bạn đi vệ sinh!", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","perspire1",0.25)
	await novel_interface.show_dialog("Cái gì… phòng tắm? \\nUgh, nghe ghê quá!", "Lian")
	await novel_interface.show_dialog("Nó chắc chắn là do Aya phát minh ra! \\nĐợi đã, đừng nói với tôi là bạn đã bí mật cấy nó vào cơ thể tôi nhé!", "Lian")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Tôi chỉ đùa thôi.", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Cách bạn nói không có gì giống như một trò đùa!")
	novel_interface.show_character("liliu_uniform2","speak2")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_uniform","perspire1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Hoặc… Có điều gì đó kỳ lạ lướt qua tâm trí bạn không?", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"shy")
	await novel_interface.show_dialog("Ặc, chết tiệt…", "Lian")
	await novel_interface.show_dialog("(Lần trước tôi đã chạy trong buổi họp ở trường…) \\n(Điều đó có nghĩa là…?)", "Lian")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Hahahaha! Đừng coi trọng nó!", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru cười lớn, xoa đầu tôi thật mạnh.")
	novel_interface.show_character("liliu_uniform2","normal2")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_uniform","shy",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Aya chỉ làm một nguyên mẫu trước khi tôi hủy bỏ dự án. \\nTại sao chúng tôi lại sử dụng nó cho một người không giống bạn!", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"shy_right")
	await novel_interface.show_dialog("Ồ, tôi có nên nói lời cảm ơn không?", "Lian")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Haha, đầu óc bạn đang có chuyện bẩn thỉu phải không?", "Mariru")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Ahh… Ơn trời là không có máy đọc suy nghĩ! Hãy nghĩ xem điều đó sẽ đáng xấu hổ biết bao!")
	novel_interface.character_light(0.35,"speak2")
	await novel_interface.show_dialog("Này, đừng có mút nó. Thật vui khi thấy bạn chiến đấu trở lại.", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_text_only("Xin lỗi vì đã làm bạn thất vọng.")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Hmm… Tôi tự hỏi làm sao một kẻ ngu ngốc như cậu lại có thể moi được thông tin từ những mục tiêu quan trọng.", "Mariru")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Mariru lau nước mắt cười và trưng ra bộ mặt kiêu ngạo thường ngày.")
	novel_interface.character_2nd_light(0.35,"upset")
	await novel_interface.show_dialog("Các mục tiêu chính… Nghe có vẻ có ý nghĩa hơn là phục vụ bạn… Nhưng tại sao Mr. Big lại nói chuyện với một học sinh cấp ba!", "Lian")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Lần này bạn sẽ tiếp cận mục tiêu của mình khi còn là sinh viên. Mục tiêu…", "Mariru")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Raphael Dekkers, cháu gái của thị trưởng Salmonton. Cô ấy sẽ đến cùng với Phái đoàn Salmonton.", "Mariru")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("Cô ấy đúng là một cô gái quý tộc. Hào hứng?", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("Tại sao tôi phải phấn khích?", "Lian")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Tut-tut, bạn chỉ thích con gái nhỏ thôi à?", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wry_smile")
	await novel_interface.show_dialog("Này, đừng miêu tả tôi như một tên tội phạm nữa!", "Lian")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_dialog("… Ừm. \\nDù sao thì bạn muốn tôi nhận được gì từ cô gái quý tộc này?", "Lian")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ugh, bạn không phải là người nói nhiều… \\nHy vọng bạn có thể vượt qua được ít nhất một ngày.", "Mariru")
	await novel_interface.show_dialog("Được rồi, nghiêm túc mà nói, bạn biết gì về Salmonton?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal2")
	await novel_interface.show_dialog("Umm… tôi đoán đó là nước xuất khẩu thực phẩm lớn nhất?", "Lian")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("Nhắc đến Salmonton… điều tôi nghĩ đến là hàng chục nhà kính cao tầng dọc theo sông Rhine.")
	await novel_interface.show_text_only("Những khu vườn xanh tươi phía sau nhà kính… \\nLuôn tạo nên những hình nền hoàn hảo.")
	novel_interface.show_character("ren_uniform","normal1")
	await novel_interface.show_dialog("Và có rất nhiều nhà thờ. Mọi công dân đều có niềm tin tôn giáo. Họ thậm chí còn thành lập một Liên minh thiêng liêng…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Đó là tất cả những gì tôi có thể nhớ được. Tôi không giỏi môn địa lý. Ghi nhớ quá nhiều sự kiện ngẫu nhiên.")
	novel_interface.show_character("ren_uniform","normal1")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("Quyền lực kinh tế và chính trị của Salmonton phần lớn phụ thuộc vào khả năng kiểm soát gen cây trồng của nó.", "Mariru")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("Nhưng những sự cố sau khi Ross Goblet biến mất đã gây ra những mối đe dọa nghiêm trọng cho họ.", "Mariru")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Khi nói đến sự đe dọa, ý bạn là… Dòng chảy Không thời gian?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("Đúng vậy. Theo thông tin của tôi, nó đã trải qua nhiều biến động. Nhưng thiệt hại vẫn chưa rõ.", "Mariru")
	await novel_interface.show_dialog("Đánh giá từ sự biến động gần đây của giá ngũ cốc kỳ hạn, tác động có vẻ khá lớn… Có thể nạn đói lẻ tẻ sẽ xảy ra.", "Mariru")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Thật nghiêm trọng!", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Tôi không biết gì về thị trường kỳ hạn. Tôi nghĩ tác động chỉ giới hạn ở một khu vực nhỏ.")
	novel_interface.show_character("ren_uniform","upset")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("Vâng… Mất mùa sẽ không gây hại ngay lập tức. Dù sao thì các nước cũng có dự trữ rủi ro.", "Mariru")
	await novel_interface.show_dialog("Có vẻ như Salmonton là thành phố đầu tiên sụp đổ trong số tất cả các Thành phố Học viện.", "Mariru")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("Nó đã cử một phái đoàn tới New Opulentia, vốn đang trên đường tới.", "Mariru")
	await novel_interface.show_dialog("Với tư cách là nhà nhập khẩu thực phẩm lớn của họ, chúng tôi không thể nói không.", "Mariru")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Liệu họ… có nghi ngờ Annie và tôi không?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak2")
	await novel_interface.show_dialog("Đó là những gì bạn sẽ làm.", "Mariru")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Cái gì?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("Mặc dù mang biểu ngữ chương trình \"trao đổi văn hóa\", phái đoàn đã được Cơ quan An ninh Hoàng gia bảo vệ chặt chẽ.", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Cơ quan An ninh Hoàng gia… Cơ quan tình báo của Salmonton, còn được gọi là Rosenkreutz.")
	await novel_interface.show_text_only("Đối với một ngành tình báo thì quá nổi tiếng nhờ phim Đặc vụ số 7.")
	novel_interface.show_character("ren_uniform","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Nó sẽ gây ra một số rắc rối?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Tất nhiên. SID thậm chí còn gặp khó khăn trong việc thu thập thông tin cơ bản.", "Mariru")
	await novel_interface.show_dialog("Cho đến nay, điều liên quan đến bạn là cô gái sẽ đến thăm trường trung học nữ sinh Gosakuragawa.", "Mariru")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Trường học của tôi?!", "Lian")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal1")
	await novel_interface.show_dialog("Đó là điều được mong đợi. Cô ấy đang ở độ tuổi của một học sinh trung học.", "Mariru")
	await novel_interface.show_dialog("Vì vậy điều bạn cần làm là tìm hiểu mục đích thực sự chuyến viếng thăm của họ.", "Mariru")
	novel_interface.change_2nd_expression("normal2")
	await novel_interface.show_dialog("Cơ quan tình báo đã làm một cuốn sách nhỏ về Salmonton và gia đình Dekkers. Bây giờ bạn đi và đọc nó qua.", "Mariru")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("Rất tiếc, lại phải làm bài tập ghi nhớ… \\nTôi sẽ lo việc đó!", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("Nhân tiện, hãy coi chừng kẻ biến thái trên đường về nhà.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_dialog("C-Cái gì!?", "Lian")

	print("=== 第三章第5话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
