# chapter3_ep14.gd - 第3章第14话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep14_script()

func play_script():
	pass

func chapter3_ep14_script():
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.change_background("res://assets/images/bg/SkyHotel/guestRoomInner.png")
	novel_interface.show_character("anne_uniform","stare")
	await novel_interface.show_dialog("Jacob Trừng phạt \\nElluka Quản trị viên của…", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Phía sau anh ta, tôi thấy vài người lính an ninh nằm trên sàn.")
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("Họ vừa mới ngất đi. Giết chóc ở khu phi quân sự không nằm trong kế hoạch của tôi.", "Jacob")
	await novel_interface.show_dialog("Tôi định lấy lại những trang của cuốn sách kinh điển đình đám Book of Seven Philosophers, và không ngờ phần thưởng như vậy…", "Jacob")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","angry")
	await novel_interface.show_dialog("…", "Beatrice")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","solemn")
	await novel_interface.show_dialog("(Sách Bảy Nhà Triết Học…) \\n(Đây có phải là cuốn Grimoire có liên quan đến Bướm Vàng không?)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","stare")
	await novel_interface.show_dialog("Ren… Tôi tìm thấy rất nhiều vết thương cũ trên cơ thể Elluka khi tôi giúp cô ấy tắm rửa.", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","wry_smile")
	await novel_interface.show_dialog("(Bạn đã giặt Elluka?) \\n(Khi nào!?)", "Lian")
	novel_interface.change_expression("solemn")
	await novel_interface.show_dialog("(Không, vấn đề không phải ở chỗ đó.) \\n(Vết thương cũ… Nghĩa là…!)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","serious")
	await novel_interface.show_dialog("Không một đứa trẻ bình thường nào có thể chịu đựng được trải nghiệm đau thương như vậy!", "Annie")
	await novel_interface.show_dialog("Chắc chắn phải là anh chàng này ... đây chính là anh chàng này!!", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("Ồ— \\nCó vẻ như thứ đó vẫn chưa hỏng.", "Jacob")
	await novel_interface.show_dialog("Tut-tut, tôi đoán SID đã được thiết kế ngược rồi… \\nCông nghệ tôi đã sử dụng trên đó.", "Jacob")
	await novel_interface.show_dialog("Nếu biết nó sẽ gây ra nhiều rắc rối như vậy thì tôi đã lắp thiết bị tự hủy vào đó rồi.", "Jacob")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","shout")
	await novel_interface.show_dialog("Bạn—!", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","serious")
	await novel_interface.show_dialog("- Đồ khốn!", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Điều tiếp theo tôi biết, Annie bật dậy giận dữ và cố đá vào mặt Jacob.")
	novel_interface.show_background("res://assets/images/bg/Baizhu/white_bg.png")
	await novel_interface.show_text_only("Kẹt—")
	await novel_interface.show_text_only("Với một tiếng rít, căn phòng được chiếu sáng bởi một luồng điện khổng lồ. Trong một khoảnh khắc, tôi như bị mù.")
	await novel_interface.show_text_only("Phải mất vài giây để ánh sáng chói biến mất. Một nỗi đau nhức nhối đọng lại trong mắt tôi.")
	novel_interface.show_background("res://assets/images/bg/SkyHotel/guestRoomInner.png")
	novel_interface.show_character("ren_maid","shout")
	await novel_interface.show_dialog("Annie…!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Annie bất tỉnh và ngã xuống đất. Trên da cô xuất hiện một dải vết cháy hình cành cây.")
	await novel_interface.show_text_only("Người lính bên cạnh Jacob đang cầm một khẩu súng bốc khói… Đó có phải là vũ khí họ vừa sử dụng không?")
	await novel_interface.show_text_only("Người lính nhanh chóng tháo một viên đạn giống như cục pin có kích thước bằng một cái hộp.")
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("Chúng tôi biết cách tận dụng tối đa sức mạnh của phù thủy…", "Jacob")
	await novel_interface.show_dialog("Tôi thích bắt sống chúng hơn. Nhưng con khốn SID sắp xuất hiện…", "Jacob")
	await novel_interface.show_dialog("Bây giờ chúng ta sắp hết thời gian…", "Jacob")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Jacob lấy ra một miếng kim loại hình chiếc bánh. Lớp vỏ màu xanh xám tỏa ra ánh sáng xanh nhạt quen thuộc.")
	novel_interface.show_character("ren_maid","solemn")
	await novel_interface.show_dialog("Đó có phải là… vũ khí Substance H không?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","angry")
	await novel_interface.show_dialog("Tôi cảm thấy… dòng sức mạnh ma thuật…", "Beatrice")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("Bạn đang làm cái quái gì vậy? Đây là khu phi quân sự!", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("(Ren)", "Mariru")
	await novel_interface.show_text_only("Giọng của Mariru đột nhiên vang lên từ tai nghe.")
	await novel_interface.show_dialog("(Đó là một cái bẫy làm bằng sợi tự liên kết.) \\n(Đó là vũ khí Substance H không gây chết người.)", "Mariru")
	await novel_interface.show_dialog("(Nó phát nổ ba giây sau khi phát nổ.) \\n(Và các sợi sẽ lan ra khắp nơi. Không thể thoát ra được.)", "Mariru")
	novel_interface.show_character("ren_maid","solemn")
	await novel_interface.show_dialog("—!?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("(Vì vậy, hãy dành sức lực của bạn vào lúc này.) \\n(Tôi sẽ tìm cách đưa bạn ra ngoài…)", "Mariru")
	await novel_interface.show_text_only("Jacob từ từ nâng bẫy bẫy trong tay phải lên. Những đường màu vàng xuất hiện trên lòng bàn tay anh, như thể đã sẵn sàng chiến đấu.")
	novel_interface.show_character("ren_maid","solemn")
	await novel_interface.show_dialog("Bàn tay của anh ấy… đó có phải là dòng chữ ma thuật không?", "Lian")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("(Cuối cùng… Đến lượt mình trải nghiệm vũ khí Substance H…)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("Xin lỗi vì điều này…", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beatrice bất ngờ nắm lấy tôi bằng một tay và giật chiếc vòng cổ từ Raphael bằng tay kia.")
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("Cái gì?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Đột nhiên, mặt dây chuyền ngọc lục bảo phát ra một tia sáng chói và biến thành một thanh kiếm uy lực có khắc chữ trên lưỡi.")
	novel_interface.show_character("beatrice_battle","smile1")
	await novel_interface.show_dialog("Hãy nhìn những linh hồn khốn khổ này đang cầu xin để rửa sạch tội lỗi của họ—", "Beatrice")
	await novel_interface.hide_character()
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("Cái gì…", "Jacob")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","angry")
	await novel_interface.show_dialog("Im đi!", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beatrice đẩy mạnh thanh kiếm xuống sàn.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Jacob mở miệng nhưng chẳng có gì thốt ra được. \\nCăn phòng tràn ngập sự im lặng chết chóc.")
	await novel_interface.show_text_only("Sàn bên dưới Jacob nứt ra, chẳng để lộ gì ngoài bóng tối dày đặc.")
	await novel_interface.show_text_only("Từ sâu trong bóng tối truyền đến một âm thanh rùng rợn, như thể hàng triệu người đang than khóc và hú hét từ địa ngục.")
	await novel_interface.show_text_only("Khói đen phun ra từ vết nứt và bao trùm mọi ngóc ngách của căn phòng, giờ đây nhanh chóng bị bao phủ trong bóng tối địa ngục.")
	await novel_interface.show_text_only("Bị ớn lạnh tận xương tủy và cảm giác kinh hoàng sâu sắc, tóc tôi dựng đứng và tôi không thể cử động…")
	novel_interface.show_background("res://assets/images/bg/SkyHotel/guestRoomInner.png")
	await novel_interface.show_text_only("Nhưng chỉ vài giây sau, bóng tối tan biến. \\nVà không tìm thấy vết nứt ở đâu cả.")
	await novel_interface.show_text_only("Như thể đang bị hoảng loạn, Jacob ngã xuống sàn và điên cuồng gãi cổ mạnh đến mức chảy máu.")
	await novel_interface.show_text_only("Mặt anh đỏ bừng khi anh khó thở. Nhưng phổi của anh ấy dường như bị hút hết không khí, khiến anh ấy thở hổn hển một cách vô ích.")
	await novel_interface.show_text_only("Phải mất một lúc lâu anh mới lấy lại được hơi thở yếu ớt.")
	await novel_interface.show_text_only("Người đàn ông cao lớn, rắn chắc cuộn tròn trên thảm, run rẩy, hai tay khoanh trước ngực.")
	await novel_interface.show_text_only("Đôi mắt đỏ ngầu của anh ta đầy sợ hãi. Nước mắt chảy ra do sự giải nén.")
	await novel_interface.show_text_only("Những đường nét trên tay anh đã hoàn toàn biến mất, chiếc bẫy bẫy rơi trên thảm cũng mất đi vẻ sáng bóng.")
	await novel_interface.show_text_only("Những người lính đeo mặt nạ đều đứng yên, run rẩy.")
	await novel_interface.show_text_only("Từ khuôn mặt trống rỗng của họ, họ dường như bị nỗi kinh hoàng khi nhìn thấy một thực tế vượt xa mọi mô tả.")
	await novel_interface.show_text_only("Nếu bạn nhìn chăm chú vào vực thẳm, vực thẳm cũng nhìn chằm chằm vào bạn…")
	await novel_interface.show_text_only("Đối mặt với nỗi kinh hoàng thực sự, ngay cả hơi thở…")
	await novel_interface.show_text_only("Khiến bạn cảm thấy tuyệt vọng không thể diễn tả được.")
	novel_interface.show_character("beatrice_battle","angry")
	await novel_interface.show_dialog("Đi thôi!", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("…")
	await novel_interface.show_dialog("(Ren, ra khỏi đó đi!)", "Mariru")
	await novel_interface.show_text_only("Mãi đến bây giờ tôi mới tỉnh táo lại. Gật đầu với Beatrice, tôi rời khỏi phòng với Annie trên tay.")
	await novel_interface.show_text_only("Beatrice kéo Raphael, người vẫn còn choáng váng. Chúng tôi lao tới thang máy…")

	print("=== 第3章第14话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
