# chapter3_ep08.gd - 第3章第8话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep08_script()

func play_script():
	pass

func chapter3_ep08_script():
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_centreSpace1.png")
	await novel_interface.show_text_only("나는 안절부절 못하며 라파엘을 데리고 학교를 참관하고 있다.")
	await novel_interface.show_text_only("임무 타겟에게 접근하는 것이 이렇게 순조롭게 진행될 줄은 몰랐다.")
	await novel_interface.show_text_only("애써 환영회를 준비했다가 바람을 맞은 교감이 우리 뒤에서 손수건을 뜯고 있다.")
	await novel_interface.show_text_only("그리고 이 아가씨는 아직 만족한 것 같지는 않지만 아까보다 기분이 좋아진 듯 하다.")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("이게 끝이야?", "라파엘")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("응?참관 내용 말인가요?", "샤오롄")
	await novel_interface.show_dialog("저쪽으로 더 가면 캠퍼스 밖 상업구가 나와요……", "샤오롄")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("건물 디자인이 전쟁 전 유명한 건축물과 비슷해. 문화 소양을 높이려는 의도겠지.", "라파엘")
	await novel_interface.show_dialog("학교 면적이 너무 작아서 여러 스타일의 건물들이 충돌하는 느낌이야. ", "라파엘")
	await novel_interface.show_dialog("이런 곳에 있으면 답답하지 않아? ", "라파엘")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("신토요스는 폐허 위에 세운 도시라서 남아있는 역사 건물이 많이 없다. ")
	await novel_interface.show_text_only("게다가 방호 역장 안 금싸라기 땅에 이런 면적을 차지하고 있는 것도 상당한 사치다. ")
	await novel_interface.show_text_only("갑자기 그렇게 얘기하니까, 기분이 불쾌한 걸……")
	novel_interface.show_character("ren_uniform","normal2")
	await novel_interface.show_dialog("음……", "샤오롄")
	await novel_interface.show_dialog("당신은 제4학원도시에서 오신 라파엘 덱스 아가씨죠?", "샤오롄")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("여기가 그렇게나 마음에 안 들면서 왜 참관하러 온 거예요? ", "샤오롄")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","jeer")
	await novel_interface.show_dialog("오?내가 누군지 알고 있구나?", "라파엘")
	await novel_interface.show_dialog("흥, 할아버지는 날 다른 학원도시로 유학이나 보내려고 해서……", "라파엘")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("이렇게 모방이나 하고 깊이가 없는 곳은 한 발짝도 들이고 싶지 않아!", "라파엘")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("……", "샤오롄")
	await novel_interface.show_dialog("(집안에서 시킨 것 때문에 화풀이를 하고 있군……)\\n(그런 일은 대화로 해결하면 되잖아!?)", "샤오롄")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("이런. 그녀의 말을 들으니, 나까지 학교의 건물 스타일이 갑자기 자연스럽지 않아 보인다. ")
	await novel_interface.show_text_only("정말 해로운 평가다. 빨리 잊어버리자! !")
	novel_interface.show_character("nyx_normal","normal1")
	await novel_interface.show_dialog("집안의 계획이 그렇게나 마음에 안 든다면", "닉스")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("왜 자신의 생각을 직접 말하지 않는 거죠?", "닉스")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("닉스 선배가 우아한 자태로 천천히 걸어온다. ")
	await novel_interface.show_text_only("선배와 라파엘의 눈이 마주치는 순간, 고압 전기가 튀는 소리를 들은 것 같다.")
	await novel_interface.show_text_only("……착각이겠지?")
	novel_interface.show_character("raphael","worry")
	await novel_interface.show_dialog("넌 또 누구야?", "라파엘")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_normal","smile",0.25)
	await novel_interface.show_dialog("전 이 학교의 평범한 학생이죠.", "닉스")
	novel_interface.change_2nd_expression("mock")
	await novel_interface.show_dialog("귀족 아가씨께서 아까부터 우리 학교에 불만이 많으신 것 같길래.", "닉스")
	await novel_interface.show_dialog("귀하신 분께서 누추한 여기까지 뭐하러 오셨죠? 가문의 압력 때문에? ", "닉스")
	novel_interface.character_light(0.35,"angry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("나와 내 가족의 일을 네가 함부로 떠들 필요는 없을 텐데? ", "라파엘")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("당신은 부모의 명령을 거역하지 못하는 제멋대로인 어린아이일 뿐이에요──", "닉스")
	novel_interface.change_2nd_expression("sad")
	await novel_interface.show_dialog("뭐가 그리 잘나서 무료로 가이드까지 해주는 사람의 학교를 비난하는 거죠?", "닉스")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"subtle")
	await novel_interface.show_dialog("하?!내가 언제 잘났다고 그랬어?", "라파엘")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("이봐, 여장 변태, 내가 그랬어?", "라파엘")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("그건 아니지만……", "샤오롄")
	await novel_interface.show_text_only("젠장, 누가 여장 변태라는 거야!")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("봐봐, 내가 언제 그랬다고 그래?", "라파엘")
	await novel_interface.show_dialog("그리고, 네 목에 차고 있는 그거……", "라파엘")
	novel_interface.change_expression("jeer")
	await novel_interface.show_dialog("학교에서 그런 걸 차고 있어도 정말 괜찮은 거야?", "라파엘")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("사실 우리 학교는 악세서리 착용 금지 규정이 없어요……", "샤오롄")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("게다가 선배의 목걸이는 아주 귀엽다고!")
	novel_interface.show_character("raphael","jeer")
	await novel_interface.show_dialog("일부러 저반광 소재를 쓴 걸 보니……전쟁 전 궁정에서 유출되어 세 조각이 난 『오를로프 블랙다이아』군.", "라파엘")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("이곳의 강의동 몇 채와 맞바꿀 수 있는 가격이라지?", "라파엘")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("──뭐!!?", "샤오롄")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("평민을 대변하는 것처럼 굴지 마. 이 여장 바보가 널 같은 편이라고 여길 거라고 생각하는 거야?", "라파엘")
	await novel_interface.hide_character()
	novel_interface.show_character("nyx_normal","normal2")
	await novel_interface.show_dialog("……", "닉스")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("누가 여장 바보라는 거야!!")
	await novel_interface.show_text_only("닉스 선배는 왜 갑자기 도둑이 제 발 저리는 모습을 하는 거야?!")
	novel_interface.show_character("nyx_normal","normal2")
	await novel_interface.show_dialog("난 그저 나와 잘 어울리는 악세서리를 한 것뿐이에요.", "닉스")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("자유롭고 독립적이고 싶어하면서 가문의 그늘에서 거만하고 우쭐대는 당신이야말로 정말 가소롭군요. ", "닉스")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","mock",0.25)
	await novel_interface.show_dialog("블랙다이아는 마피아 대부의 손에 넘어갔다고 들었는데, 검은 돈으로 산 블랙 다이아라니, 정말 당신과 잘 어울리는군.", "라파엘")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("당신의 가문이 식량 무역을 독점해서 재물과 귀족 지위를 얻은 것과는 다르죠.  옷 하나도 이렇게 화려하다니.", "닉스")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("그러게 누가 우리 작물만이 『흑사병』을 예방하라 그랬나. 속까지 새까만 너와는 다르지.", "라파엘")
	novel_interface.character_light(0.35,"mock")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("기아로 전세계를 위협하면서, 신앙을 잃어서는 안 된다고 선전하던데, 스스로의 영혼은 탐구하지 않나 봐요?", "닉스")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"jeer")
	await novel_interface.show_dialog("내 영혼은 너 같은 사람의 탐구는 필요 없어. 분명 인생의 오점이 될 거야. ", "라파엘")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0)
	await novel_interface.show_dialog("어머, 잘 됐네요. 저도 쓰레기통에 있는 폐기물의 실체는 연구하고 싶진 않아서.", "닉스")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("오후의 햇볕이 우리 세 사람을 따스하게 비춘다.")
	await novel_interface.show_text_only("나는 가운데 서서, 두 아가씨의 대단한 말싸움을 바라보았다. 어떻게 말려야 할지 전혀 모르겠다.")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("(두 사람, 진짜 처음 만난 것 맞아?)", "샤오롄")
	await novel_interface.show_dialog("(어렸을 때부터 원수 사이가 아니고?)", "샤오롄")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("멀리서 지켜보던 교감은 이미 쓰러져서 실려나갔다.")
	await novel_interface.show_text_only("됐어, 마리루가 알아보라고 한 정보를 손에 얻었으니까.")
	await novel_interface.show_text_only("……이제 신경쓰지 않아도 되겠지?")

	print("=== 第3章第8话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
