# chapter3_ep02.gd - 第三章第2话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep02_script()

func play_script():
	pass

func chapter3_ep02_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("根據SID的記錄顯示，阿卡特拉茲收容基地收容著被聯合議會禁止測試和研究的EX級「異質物」。")
	await novel_interface.show_text_only("收容基地的地下，還連接著嚴禁入內以至於連評級都無法完成的古代遺跡「夏特洞窟」。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("那個EX級的「異質物」……是什麼特別危險的東西嗎？", "小憐")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal1",0.25)
	await novel_interface.show_dialog("大多是某些宗教相關的「聖物」，因為對教徒有特別的意義，所以只許收容，不許研究。", "莉琉")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("感覺有點自欺欺人啊。", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("呵呵呵，雖然我也是這麼想的──\\n不過也有他們的道理哦。", "莉琉")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("有些物品在宗教傳說中擁有弒神的能力，或能開啟末日審判，", "莉琉")
	await novel_interface.show_dialog("一旦激發，可能會引發世界末日級的災難。", "莉琉")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那確實……有些不妙。", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("而另一些在宗教故事中特別神聖的物品，可能在測試後發現只有很弱甚至尷尬的效果……", "莉琉")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("搞笑的效果？", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak2")
	await novel_interface.show_dialog("比如有位「聖人」的鞋子，親吻鞋尖就會產生無法克制的裸奔衝動，這也太讓教宗拉不下臉了。", "莉琉")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……還有這麼惡搞的東西啊！ \\n那他們這次弄丟的是哪一類？", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"serious")
	await novel_interface.show_dialog("…這次失竊的，是由所有學園都市共同監視和保護的EX「異質物」——「天命之矛」。", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"smile")
	await novel_interface.show_dialog("哦哦！ \\n原來如此，好厲害！", "小憐")
	await novel_interface.show_dialog("那，「天命之矛」是什麼呀？", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("…………", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("妳現在的樣子，真是一臉白痴。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","sob",0.25)
	await novel_interface.show_dialog("不知道就是不知道啊！ \\n我只是普通的高中生而已……", "小憐")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("莉琉無奈的看著我，盤算著我要理解這個問題需要補充多少知識。")
	novel_interface.character_light()
	await novel_interface.show_dialog("總歸一句，「天命之矛」是屬於第一類，傳說中有弒神能力的異質物。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("在公開文獻中，對天命之矛只有兩段非常簡單的異常描述：「高溫不會熔化」和「揮舞時會變重」。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("就……這麼簡單？", "小憐")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("如果深入研究，這兩條中任何一條的延伸都可能成為XK級「異質物」了。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("如果還有其他未表現的特質就更危險，所以一般這種東西會盡量避免在媒體面前曝光。", "莉琉")
	novel_interface.character_dark()
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("我不禁吞了口口水，XK級「異質物」的危險性可是連小孩子都知道的──")
	await novel_interface.show_text_only("能夠造成世界毀滅級災難或形成同等威懾力的「異質物」，目前世界上已知的只有六個。")
	await novel_interface.show_text_only("分別屬於六個學園都市，或者說，擁有XK級「異質物」，才會被聯合議會所承認。")
	novel_interface.character_2nd_light(0.35,"perspire1")
	await novel_interface.show_dialog("……哎？ \\n也、也就是說……？", "小憐")
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("現在知道「你」犯下的罪有多重了嗎？", "莉琉")
	novel_interface.character_dark()
	await novel_interface.show_text_only("因為太過震驚，我反而覺得不真實。")
	novel_interface.character_2nd_light(0.35,"sob")
	await novel_interface.show_dialog("……對不起！ \\n不對！ 道什麼歉！ 並不是我偷的啊！ ！", "小憐")
	await novel_interface.show_dialog("（可惡，那個傢伙豈不是超級危險！ ）", "小憐")
	novel_interface.change_2nd_expression("uneasy")
	await novel_interface.show_dialog("不、不過，新聞能被撤下也算不幸中的萬幸……", "小憐")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("笨蛋，新聞撤下是為了避免引起恐慌。 \\n通緝令還是會祕密執行的。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("為了保密，通緝令不會下發到防衛廳，但各國的情報機構，包括SID在內應該都收到了通報。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("所以妳想鬆一口氣還早呢～", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"upset")
	await novel_interface.show_dialog("果然……我原來的樣子還是很危險吧？", "小憐")
	novel_interface.change_2nd_expression("perspire1")
	await novel_interface.show_dialog("萬一……我是說萬一！ \\n有人根據通緝令的照片查到了原來的我身上……", "小憐")
	await novel_interface.show_dialog("就算我現在是女生，也很有可能被當作相關人員審問吧？", "小憐")
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不錯，妳終於意識到問題了呢～", "莉琉")
	await novel_interface.show_dialog("情報部調閱了所有能查到的監視影片，發現那個頂著你過去的臉的傢伙，最近還出現在幾個異變區內。", "莉琉")
	await novel_interface.show_dialog("而且既然我們能從第三方數據中查到，其他機構也差不多也應該掌握這個消息了。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"panic")
	await novel_interface.show_dialog("居然是個慣犯了嗎？ \\n怎麼感覺，我的前途已經一片黑暗了……", "小憐")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("我的腦海中瞬間劃過無數嚴刑拷打的畫面……")
	await novel_interface.show_text_only("總感覺隨時會被人帶走，然後背上反人類什麼的罪名……")
	await novel_interface.show_text_only("被關進最嚴格的監獄，判處兩百年以上的刑期。")
	await novel_interface.show_text_only("說不定遇到超恐怖的獄友，偶爾還會……")
	await novel_interface.show_text_only("嗚哇～夠了！ ！！ \\n不要想了！ ！！")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("哈哈哈居然害怕到臉色發白啊……", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("安心，在新豐洲境內，我可以保證妳的安全指數高達98%。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","panic",0.25)
	await novel_interface.show_dialog("也就是說，還有2%的可能會出現意外？ ！", "小憐")
	await novel_interface.show_dialog("（每100秒會有2秒出現意外嗎！ ？）\\n（這樣一點安全感也沒有啊！ ！）", "小憐")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("能讓聯合議會的老烏龜們史無前例地這麼快達成共識……說不定，背後有我不知道的力量在運作著。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("而這……就是那2%的不確定因素了。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"upset")
	await novel_interface.show_dialog("已經不敢想像這件事在那群大人物中引發了多大的騷動了……", "小憐")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("所以，其他學園都市的情報部門現在也一定投入了大量的人力物力，全力搜捕畫面中這個人。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("那、那我該怎麼辦才好？", "小憐")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"speak2")
	await novel_interface.show_dialog("看得到的敵人都好對付，那些專業工作就交給SID吧。", "莉琉")

	print("=== 第三章第2话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
