# chapter3_ep16.gd - 第三章第16话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep16_script()

func play_script():
	pass

func chapter3_ep16_script():
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	await novel_interface.show_text_only("Já se passou uma semana desde que os Fluxos do Espaço-Tempo foram detectados no Sky Hotel.")
	await novel_interface.show_text_only("Aya fez para Beatrice uma pulseira delicada com o metal Substance H usado no interior da mala.")
	await novel_interface.show_text_only("Graças à pulseira, agora ela pode ligar ou desligar livremente a magia que atrai os homens.")
	await novel_interface.show_text_only("Em troca, Beatrice juntou-se a SID como agente, assim como Annie.")
	await novel_interface.show_text_only("Mariru a coloca em um quarto de hóspedes neste luxuoso apartamento.")
	await novel_interface.show_text_only("No início, fiquei preocupado que os soldados de segurança nos identificassem pelas imagens de CCTV do andar executivo.")
	await novel_interface.show_text_only("Mas, surpreendentemente, nenhum de nós foi capturado pela câmera. Nem Jacob e seus companheiros.")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("Mariru, quanto poder SID realmente tem?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","normal",0.25)
	await novel_interface.show_dialog("Hein? Por que você pergunta?", "Mariru")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Como desta vez mais de uma Cidade Acadêmica se envolveu, pensei que seria um trabalho desagradável limpar a bagunça.", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Estou muito feliz que você tenha tanta fé em SID…", "Mariru")
	novel_interface.change_2nd_expression("speak")
	await novel_interface.show_dialog("Mas você e Annie nunca poderiam ter escapado daquele lugar inteiros se não fosse pelo Senado. Como você sabe, o Senado tem uma grande influência no Congresso Unido.", "Mariru")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("Dr. Kirs, o velho com cara de pôquer, sempre joga suas cartas perto do peito. Então, não sei exatamente o que ele fez.", "Mariru")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("(Cara de pôquer… velho?) \\nAchei que o Senado compartilharia sua inteligência com SID…", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("Você é muito ingênuo...", "Mariru")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("Nenhuma agência de inteligência partilharia toda a sua inteligência com os chefes de estado ou de governo.", "Mariru")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Hein? Por que?!", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("Como diz o ditado, conhecer é possuir.", "Mariru")
	await novel_interface.show_dialog("O Senado é a autoridade máxima em New Opulentia. Então, naturalmente, SID tem que trabalhar com isso. Em outras palavras, SID e o Senado são parceiros.", "Mariru")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("Se você fosse o chefe, forneceria gratuitamente todas as informações confidenciais ao seu parceiro?", "Mariru")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Hm… Claro que não…", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("E se o seu parceiro tivesse alguma informação confidencial valiosa que você realmente deseja, o que você faria?", "Mariru")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Deixe-me ver... \\nTalvez eu compre algum zelador.", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("Garota inteligente. Desde que a agência seja grande o suficiente, ela sempre poderá ser quebrada por dentro, não importa quão rígido seja seu protocolo de segurança.", "Mariru")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Se... se for esse o caso, também temos informantes em SID?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("Você aposta. Existem milhares de funcionários em SID e alguns deles devem ser espiões, sejam do Senado, de agências de inteligência estrangeiras ou de outras organizações.", "Mariru")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("É por isso que precisamos manter apenas um pequeno grupo de pessoas informadas quando se trata de informações importantes.", "Mariru")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Então, e o Salão do Marfim…", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("Isso não é algo com que você deva se preocupar. Garotas ingênuas como você nunca poderão se infiltrar no Senado.", "Mariru")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("Todos os membros do Senado são especialistas na área de Substance H com classificação mínima de nível SS.", "Mariru")
	await novel_interface.show_dialog("Esses especialistas têm muitos itens Substance H para experimentar. Se você entrar furtivamente lá, poderá sofrer uma lavagem cerebral antes que perceba.", "Mariru")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Mas… ainda há muitos pontos questionáveis neste caso.", "Lian")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Por exemplo, por que a delegação Salmonton contrabandeou a Borboleta Dourada para New Opulentia?", "Lian")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("E aquele colar de Raphael, que é bastante antiquado, claramente não é sua preferência. Ela geralmente coloca embaixo da gola.", "Lian")
	await novel_interface.show_dialog("Na verdade, Raphael que eu conheço… nunca usaria tais enfeites…", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Você tem razão. A Borboleta Dourada tem propriedades semelhantes às do meme infeccioso Substance H. O escudo que usamos para um item tão perigoso é geralmente do tamanho de um caminhão.", "Mariru")
	novel_interface.change_2nd_expression("angry")
	await novel_interface.show_dialog("Mas eles apenas colocaram em uma mala. A energia que vaza dessa mala pode até ser detectada por satélites.", "Mariru")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("Se eles realmente queriam contrabandear, por que tiveram que convencer os funcionários do governo a fazer isso? Por que eles correriam um risco político tão grande?", "Mariru")
	novel_interface.character_light(0.35,"solemn")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Talvez não haja risco algum. Talvez seja uma ordem de alguém superior que lhes deu a garantia…", "Lian")
	await novel_interface.show_dialog("Os membros da delegação não precisam declarar a bagagem de mão no controle de segurança. E escolheram deliberadamente um hotel fora da nossa jurisdição.", "Lian")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("Você está dizendo…", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("Finalmente conseguindo?", "Mariru")
	novel_interface.character_light(0.35,"solemn")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("O Senado ordenou que o fizessem? Apenas para manter SID no escuro?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("Jacob é adido militar de Salmonton e os dados de Elluka mostram que eles estudam bruxas há algum tempo.", "Mariru")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("A Borboleta Dourada pertence a uma bruxa e Jacob apareceu de repente e se juntou à luta. \\nPense nisso…", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("A corrida pelo controle do poder sobrenatural lançou o mundo no caos da Guerra dos Sete Anos. Isso vai acontecer de novo?")
	novel_interface.show_character("ren_battle","normal1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_research","normal",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Haverá mais bruxas produzidas então?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("É hora de se preparar para essa luta por baixo da mesa.", "Mariru")
	await novel_interface.hide_all_characters()
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_centreSpace1.png")
	await novel_interface.show_text_only("Algumas semanas depois")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("Nnngh ... Mal consigo manter os olhos abertos ... \\nFiquei acordado a noite toda jogando um jogo ...", "Lian")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Ei, aberração travesti.")
	novel_interface.character_light(0.35,"wry_smile")
	await novel_interface.show_dialog("???", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("A voz familiar…")
	await novel_interface.show_text_only("O lugar familiar…")
	await novel_interface.show_text_only("E a saudação familiar…")
	await novel_interface.show_text_only("A garota que está na minha frente… É ela de novo!")
	await novel_interface.show_text_only("Este encrenqueiro de língua afiada Raphael!")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("Ra-Raphael? \\nPor que você está aqui?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","stare",0.25)
	await novel_interface.show_dialog("Você não aprende boas maneiras básicas nesta escola, não é?", "Raphael")
	novel_interface.change_2nd_expression("mock")
	await novel_interface.show_dialog("Eu sou seu sênior. Mostre algum respeito!", "Raphael")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Hein?!", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Eu não tinha percebido isso até agora… \\nCom uma mochila em mãos, ela veste o uniforme e os sapatos dos alunos do primeiro ano.")
	novel_interface.show_character("ren_uniform","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("raphael","mock",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Achei que você odiava essa escola...", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("Eu não tive outra escolha. \\nTodas as escolas em New Opulentia são péssimas.", "Raphael")
	novel_interface.change_2nd_expression("mock")
	await novel_interface.show_dialog("Como bruxa, esta escola pode ser a melhor escolha para mim.", "Raphael")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("Parece que Raphael fez toda a pesquisa e tomou sua decisão em tão pouco tempo. Que gênio.")
	novel_interface.character_light(0.35,"upset")
	await novel_interface.show_dialog("Sua família… Você contou a eles que é uma bruxa?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("Por que se preocupar? Isso não traria nada além de preocupações para eles.", "Raphael")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("Ei, tornar-se uma bruxa não é nada como entrar para um clube depois da escola!")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Você pode imaginar que eles me mandaram para o exterior só para me deixar ficar quieto depois daquela entrevista estúpida?", "Raphael")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_dialog("Se descobrirem isso, provavelmente vão surtar, como quando souberam que eu tinha feito uma tatuagem.", "Raphael")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("Não, não, não. Isso é apenas uma brincadeira de criança em comparação com se transformar em uma bruxa! \\nBem, se você realmente tem alguma tatuagem, mostre-a para mim, por favor…")
	novel_interface.change_expression("perspire1")
	await novel_interface.show_dialog("A propósito… o que diabos você disse na entrevista?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Você é da Idade da Pedra ou o quê? Esse vídeo já deveria estar circulando pela Internet.", "Raphael")
	novel_interface.character_light(0.35,"uneasy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("Falando nisso, também sou bastante popular na Internet. \\nAfinal, sou um criminoso procurado em todo o mundo…")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Para ser justo, devo ter perdido algumas grandes notícias porque fui completamente absorvido por jogar Legend of Zelda.")
	novel_interface.character_light(0.35,"stare")
	await novel_interface.show_dialog("Pare de me olhar desse jeito...", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Pego meu telefone para receber as últimas notícias. Raphael não está mentindo. Seu nome ganhou as manchetes em todo o mundo.")
	await novel_interface.show_text_only("Eu reproduzo um desses vídeos e logo a voz de Raphael sai.")
	await novel_interface.show_dialog("Por que eles acreditam que todos os pecadores podem ser redimidos desde que orem aos deuses? A oração não lhes traz nada além de algum conforto patético.", "Raphael")
	await novel_interface.show_dialog("… Esses lixos são inúteis onde quer que vão. Por que nosso governo deveria salvar seus traseiros? Apenas deixe-os apodrecer.", "Raphael")
	await novel_interface.show_text_only("Não acredito que esses comentários polêmicos sejam feitos por Raphael, neta do governador de Salmonton. Não admira que tenha causado tamanho alvoroço.")
	novel_interface.show_character("ren_uniform","speechless")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("raphael","worry",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Lembro que Salmonton é um estado de bem-estar religioso… \\nVocê realmente tem coragem de fazer esses comentários provocativos.", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("Muitos estados declararam guerras em nome dos deuses. Então, por que não posso dizer o que estou pensando?", "Raphael")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Guerra? Você quer dizer… a Guerra dos Sete Anos?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("Não, seu idiota. Claro, as próximas guerras!", "Raphael")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_dialog("No Salmonton, encorajamos as pessoas a terem a sua própria religião, independentemente do deus em que acreditam.", "Raphael")
	await novel_interface.show_dialog("Como resultado das migrações massivas após a Guerra dos Sete Anos, incontáveis lixos precipitaram-se sobre esses grupos inúteis, e a sua avareza não conhece fronteiras.", "Raphael")
	novel_interface.change_2nd_expression("angry")
	await novel_interface.show_dialog("O vovô é muito indulgente com eles. Esses preguiçosos deveriam acabar em matadouros…", "Raphael")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Pare! Está ficando assustador agora...", "Lian")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"stare")
	await novel_interface.show_dialog("Agora você está no centro desta transição massiva. Você simplesmente não se importa, ou não?", "Raphael")
	novel_interface.change_2nd_expression("thinking")
	await novel_interface.show_dialog("Talvez ninguém além de idiotas como você possa viver uma vida tão otimista.", "Raphael")

	print("=== 第三章第16话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
