# chapter3_ep16.gd - 第三章第16话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep16_script()

func play_script():
	pass

func chapter3_ep16_script():
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	await novel_interface.show_text_only("スカイホテルの一件から1週間が過ぎた。")
	await novel_interface.show_text_only("愛衣はあのアタッシュケースの外殻素材に\\n使用されていた異質物金属を使って、\\nベアトリーチェに特製ブレスレットを作成した。")
	await novel_interface.show_text_only("そのお陰で男性の脳に影響を与える魔法効果を\\nようやく彼女は自らの意思で、\\n自由にオンオフできるようになった。\\n…………いや、本当に、ありがたい。")
	await novel_interface.show_text_only("交換条件としてアニーと同じくベアトリーチェも\\n捜査員としてSIDに正式に加入した。")
	await novel_interface.show_text_only("そしてマリルの手配で、彼女も\\nこの豪華なペントハウスの住人となっている。")
	await novel_interface.show_text_only("事件後、保安軍が調査する際に、\\nエグゼクティブフロアの監視映像から、\\n俺達の行動が発見されないか心配だったけど……")
	await novel_interface.show_text_only("何故か俺たちやヤコブ、取り巻きも含めて、\\nなんの映像証拠も残っていないらしい。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("マリル。\\nSIDって……一体どんだけ権力を持ってるの？", "小憐")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","normal",0.25)
	await novel_interface.show_dialog("ふん……？　藪から棒にどうした？", "マリル")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("今回は学園都市をいくつも巻き込んだから、\\n後始末とか大変かなって思ってたんだけど。\\nだけど意外とあっさり終わったよね。", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("お前がSIDの情報操作能力を高く評価してくれる\\nのは嬉しいが……", "マリル")
	novel_interface.change_2nd_expression("speak")
	await novel_interface.show_dialog("今回、お前やアニーが無事でいられているのは、\\n元老院が連合議会に様々な手回しをしたお陰だ。", "マリル")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("まあ、ギアーズ博士は一貫して秘密主義者だ。\\n\\nあの顔面神経麻痺のポーカーフェイスジジイが\\n何を実際やったのか、私も完全に把握してない。", "マリル")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（ポーカーフェイス……ジジイ）\\n\\n元老院はSIDと情報共有をしないのか？", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("お前はアホの子か……", "マリル")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("情報組織というのは、自国の元首や統治者に対し\\n情報を完全に共有する事などありえない。", "マリル")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("えっ──マジで！？", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("情報とは、すなわち権利。\\nKnowing is Owningだ。", "マリル")
	await novel_interface.show_dialog("元老院は新豊洲各方面の権利の統合者だ。\\n\\nSIDと元老院は、ただ本来の立場に基づいた\\n協力関係に過ぎない。", "マリル")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("さて、ここで問題だ。\\n\\nお前は会社の機密情報をパートナーに、\\n無償で渡すか？", "マリル")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("う～ん……そりゃ……当然しないね……", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("相手が価値のある秘密情報を擁していた場合、\\nどうしてもそれを知りたいとすれば？", "マリル")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("うーん……\\n清掃員でも買収するかな？", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("その通り。\\n相手組織の人数が多ければ多いほど、\\nどれだけ厳重な安保協議も、社会工学によって\\n破る事が可能となる。", "マリル")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("でも、そ、その説明だと……\\nSIDの内部にもスパイがいるって事だよな！？", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("うちのスタッフは1万人以上いるからな。\\n潜り込まれている可能性は少なくないだろう──\\n元老院、外国情報機関や各種組織も含めてな。", "マリル")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("だから、結局は重要な情報の流通範囲を、\\nしっかりと制限しておけばいいという話なのだ。", "マリル")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("それじゃ『象牙のロビー』の中にも……", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("お前がそんな心配をしなくてもいい。\\n\\n元老院のお膝元は、お前のような甘い考えで\\n侵入できる場所ではないからな。", "マリル")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("元老院のメンバーは全員が異質物研究の権威だ。\\nSS級の科学者である事なんて、\\n基本的な条件に過ぎない。", "マリル")
	await novel_interface.show_dialog("彼らは試験的な異質物の道具をいくつも所持して\\nいる。\\nお前が潜入したところで、知らない間に\\n洗脳されるのがオチだ。", "マリル")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("しかし今回の事件って……疑問点が満載だな。", "小憐")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("例えば、なんでサモントンの視察団の人達が、\\n黄金バタフライを新豊洲に密輸したんだ？", "小憐")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("ラファエルの例のネックレスだって、\\nすごい年代物って感じでさ。\\nそれを本人も嫌がっている様子で、\\n服の中に隠していたようだし。", "小憐")
	await novel_interface.show_dialog("だけど、ラファエルの性格からすると……\\n嫌なものを、自分から着けないはずだしなぁ……", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("確かに、『黄金バタフライ』の特性は感染性の\\nミーム類異質物と酷似している。\\n普通ならトラック並みの保管装置に収容しても\\n不十分なぐらいだ。", "マリル")
	novel_interface.change_2nd_expression("angry")
	await novel_interface.show_dialog("しかし彼らはそれをアタッシュケースの中に\\n無理矢理詰め込み、\\n結果として溢れ出たエナジーは、\\n衛星でも検出できてしまうほどだった。", "マリル")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("それに、本当に密輸目的だとしたら、\\n国の公式使節による運搬なんぞ下策。\\nなぜここまで大きな政治的リスクを冒したのか？", "マリル")
	novel_interface.character_light(0.35,"solemn")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("元々そのリスクとかは存在していなくて、\\nあるいは依頼主が保証できる人間だとすると……", "小憐")
	await novel_interface.show_dialog("視察団の荷物は税関に申告する必要がない。\\n\\nそしてわざわざ、俺達が管轄権を持ってない\\nホテルを選んだ……", "小憐")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("まさか……！", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("ようやく気付いたか？", "マリル")
	novel_interface.character_light(0.35,"solemn")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("元老院がサモントンに要求したのか？\\nSIDを蚊帳の外に置くために……", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("あのヤコブという男は第三学園都市の人間だ。\\nイルカのデータから察する限り、\\n奴は長きに渡り、魔女を研究してるみたいだな。", "マリル")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("黄金バタフライも魔女と関係している。\\nそしてヤコブの横槍も入った。\\nこれらの事象を結び付ければ……", "マリル")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("七年戦争中に浮上したっていう、\\n特殊な力をコントロールしようと企む連中が、\\n再び台頭してきたというのか？")
	novel_interface.show_character("ren_battle","normal1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_research","normal",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("製造された魔女……\\n今後はさらに増えるのか……", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("どうやら私達も水面下で、力比べの準備を\\nしなければならないようだな。", "マリル")
	await novel_interface.hide_all_characters()
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_centreSpace1.png")
	await novel_interface.show_text_only("　―　数週間後　―")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("はぁあ──眠い～～……\\n\\n昨夜はバッテリーが切れるまで、\\nケンタウロス相手に周回していたからなぁ……", "小憐")
	novel_interface.character_dark()
	await novel_interface.show_text_only("ったく　相変わらずね、女装癖。")
	novel_interface.character_light(0.35,"wry_smile")
	await novel_interface.show_dialog("？？？？？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("覚えのある声……")
	await novel_interface.show_text_only("覚えのある場所……")
	await novel_interface.show_text_only("覚えのある呼称……")
	await novel_interface.show_text_only("俺の目の前に現れたのは、やはりあの……")
	await novel_interface.show_text_only("手に負えない毒舌お嬢様。ラファエル！")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("ラ、ラファエル？\\nなんで来たの？", "小憐")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","stare",0.25)
	await novel_interface.show_dialog("この学校は礼儀に対して、ここまで非礼で\\n返すように教育しているのかしら？", "ラファエル")
	novel_interface.change_2nd_expression("mock")
	await novel_interface.show_dialog("今後あんたはラファエル「先輩」と呼びなさい。", "ラファエル")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("へっ！？", "小憐")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("ラファエルに言われてから気付いたけど……\\n\\n彼女はカバンを持っているし、\\n学校指定である二年生の靴も履いている。")
	novel_interface.show_character("ren_uniform","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("raphael","mock",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("この学校、嫌いじゃなかったっけ……？", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("できればここには来たくなかったわよ。\\n\\nただ、あんたの国だと、ここよりマシなところが\\nないだけ。", "ラファエル")
	novel_interface.change_2nd_expression("mock")
	await novel_interface.show_dialog("それに私が魔女である以上、ここが最も今の私に\\n適しているのよ。", "ラファエル")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("さすがラファエル。こんな短い間で調べ上げ、\\nしかも平然と受け入れている。")
	novel_interface.character_light(0.35,"upset")
	await novel_interface.show_dialog("家族は……魔女の事を知っているのか？", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("そんな些細な事で家族を悩ませる必要はないわ。", "ラファエル")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("魔女になった事を、スーパーの会員になった\\nぐらいみたいに言うなよ！")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("……その家族はたった1回のつまらない\\nインタビュー如きで私を国から出国させた挙句、\\nしばらく世論から身を隠して欲しいみたいね。", "ラファエル")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_dialog("この上、魔女の事を教えようものなら、\\n多分私がタトゥーでも入れたかのように、\\n慌てた挙句、気絶するんじゃないかしら？", "ラファエル")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("イヤイヤイヤ、全然同じレベルじゃないだろ！！\\n\\nでも本当にタトゥーを入れたら、\\nそれはそれでちょっと見たいけどねッ！！")
	novel_interface.change_expression("perspire1")
	await novel_interface.show_dialog("ラファエル……そのインタビューで一体どんな\\n強烈な話をしたの？", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("あんたは原始人なの？\\n\\nあの取材の内容ならすでに暇人達の手によって、\\nネット上で拡散されているんじゃないかしら？", "ラファエル")
	novel_interface.character_light(0.35,"uneasy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("その点だったら俺も負けてないぞ──\\n\\n何せ、世界的な指名手配者だからな……")
	novel_interface.character_dark()
	await novel_interface.show_text_only("とはいえ最近はとあるゲーム機でリリースされた\\n《緑服の勇者》に夢中だったため、\\nニュース自体をあまり見ていない。")
	novel_interface.character_light(0.35,"stare")
	await novel_interface.show_dialog("やめて……、そんな目で見るなよ……", "小憐")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("携帯で検索すると、ニュースランキングで\\nラファエルの名前がトップに載っていた。")
	await novel_interface.show_text_only("再生ボタンを押すとラファエルの声が聞こえる。")
	await novel_interface.show_dialog("なぜ人は、「神に祈れば救われる」と\\n皆、思っているのかしら？\\nそれは尻尾を振りながら哀れみを求め、\\n自己の慰めを望んでいるだけに過ぎないわ。", "ラファエル")
	await novel_interface.show_dialog("……「ろくでなし」は、どこへ行こうと\\nただの「ろくでなし」よ。\\nなんでこの国はこんな連中を飼ってるのかしら？\\n泥中で腐らせて肥料にすれば、まだマシなのに。", "ラファエル")
	await novel_interface.show_text_only("サモントン総督の孫娘として、\\n随分インパクトのある発言だなおいッッ！！")
	novel_interface.show_character("ren_uniform","speechless")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("raphael","worry",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("サモントンってたしか、\\n全国民が宗教を信仰している宗教国家だよな……\\nこんな事をストレートに言うなんて、\\n勇気が有り余ってるのかラファエルお嬢様。", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("多くの人々が神の名の元に戦争を起こしている。\\n\\n私にそれを言っちゃいけない理由なんて、\\n一体どこにあるのかしら？", "ラファエル")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("戦争？　七年戦争……の事？", "小憐")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("もちろん新しい戦争の事よッ！", "ラファエル")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_dialog("元々サモントンの主張は、人に必要なのは\\n信仰だけであるというものよ。\\nあらゆる信仰にも包容的な態度を取っている。", "ラファエル")
	await novel_interface.show_dialog("だけど戦後の大移民のせいで、廃棄物の寄せ集め\\nみたいな愚かな団体が徐々に貪欲となったわ。\\n彼らは今でも果てのない利益と権利を\\n要求し続けている。", "ラファエル")
	novel_interface.change_2nd_expression("angry")
	await novel_interface.show_dialog("お爺様は彼らに寛容すぎるわ。\\n\\nああいう役立たずのゴミどもは全部屠殺所に\\n送ればいいのに……", "ラファエル")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("サラッと怖い事を言うなよ……", "小憐")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"stare")
	await novel_interface.show_dialog("……逆に、\\n\\nあんたはこの異変の中心にいるというのに\\nそういうのは全く気にならないのかしら？", "ラファエル")
	novel_interface.change_2nd_expression("thinking")
	await novel_interface.show_dialog("多分あんたみたいなバカだけが、\\n幸せに暮らせるのでしょうね。", "ラファエル")

	print("=== 第三章第16话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
