# chapter3_ep14.gd - 第3章第14话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep14_script()

func play_script():
	pass

func chapter3_ep14_script():
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.change_background("res://assets/images/bg/SkyHotel/guestRoomInner.png")
	novel_interface.show_character("anne_uniform","stare")
	await novel_interface.show_dialog("ヤコブ・シュミット\\nイルカの管理人……", "アニー")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ヤコブの後ろには、保安軍の制服を着た人達が\\n倒れている。")
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("彼らはただ、気絶しているだけですよ。\\n\\n流石の私も連合議会の管理範囲内で、\\n殺傷事件を起こすつもりはありません。", "ヤコブ")
	await novel_interface.show_dialog("元々はあの邪悪な経典──『七賢者の書』の\\nページを回収するつもりだけでしたが。\\nこれはこれは、意外な収穫ですね……", "ヤコブ")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","angry")
	await novel_interface.show_dialog("…………", "ベアトリーチェ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","solemn")
	await novel_interface.show_dialog("（『七賢者の書』……）\\n\\n（それが『金色の蝶』と対の魔導書なのか？）", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","stare")
	await novel_interface.show_dialog("レンちゃん……\\n\\n私ね、イルカのお風呂を手伝った時に、\\nイルカの身体に傷跡が沢山あったのを見たの。", "アニー")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","wry_smile")
	await novel_interface.show_dialog("（イルカのお風呂を手伝ったって！？）\\n（一体いつ！？）", "小憐")
	novel_interface.change_expression("solemn")
	await novel_interface.show_dialog("（って違う違う、そんな事はどうでもいいっ）\\n（古い傷って事は……っ！！）", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","serious")
	await novel_interface.show_dialog("あんなに酷い傷……普通の子供なら身体も心も、\\nとっくに壊れていたはずよ。", "アニー")
	await novel_interface.show_dialog("きっとこいつだ……こいつに違いない！！", "アニー")
	await novel_interface.hide_character()
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("ほう──\\n\\n貴方たちの話から察するに『あれ』は、\\nまだ壊れていないのですか？", "ヤコブ")
	await novel_interface.show_dialog("だとすると……『あれ』に使われていた技術が、\\nSIDの解析で既に筒抜けとなったのは明白。", "ヤコブ")
	await novel_interface.show_dialog("ですが、これは我々のミスですね。\\n\\n最初から『あれ』に自爆装置を備えておけば、\\nこのような面倒にはならなかったのでしょうに。", "ヤコブ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","shout")
	await novel_interface.show_dialog("この野郎！", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","serious")
	await novel_interface.show_dialog("──コイツ！！！", "アニー")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("俺が反応するよりも早く、アニーが先に\\n飛びかかっていた。\\nヤコブの顔面に向けて彼女は飛び蹴りを放つ。")
	novel_interface.show_background("res://assets/images/bg/Baizhu/white_bg.png")
	await novel_interface.show_text_only("カッ──！！")
	await novel_interface.show_text_only("甲高い音と共に、巨大な放電が部屋全体を\\n白く染めた。\\n俺の目の前も瞬時に真っ白くなった。")
	await novel_interface.show_text_only("数秒後、強烈な光は散っていき視界が元に戻る。\\nまだ目に刺されるような痛みを感じつつも、\\n目の前を確認すると──")
	novel_interface.show_background("res://assets/images/bg/SkyHotel/guestRoomInner.png")
	novel_interface.show_character("ren_maid","shout")
	await novel_interface.show_dialog("アッ、アニ───ッッ！！", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("──アニーがカーペットに重々しく転げ落ちる。\\n\\n……身体に大きな樹状の焼け跡を負いながら。")
	await novel_interface.show_text_only("ヤコブの近くにいた兵士の銃口より、\\n煙が吐かれている……\\nあの武器から発射されたのか……？")
	await novel_interface.show_text_only("その兵士は慣れた手付きで次弾を込める。\\n\\n銃の片側から、散弾銃のショットシェルサイズの\\n電池のような物体が飛び出した。")
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("確かに使用方法さえ改めれば、魔女の技術も\\n十分に役に立ちますね。", "ヤコブ")
	await novel_interface.show_dialog("……できれば生け捕りにしたかったですが、\\nそろそろSIDのあの女が来てしまいますからね。", "ヤコブ")
	await novel_interface.show_dialog("申し訳ないですが、コチラには時間がない──", "ヤコブ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ヤコブが手のひらサイズの、金属製の餅みたいな\\n物体を取り出した。\\n灰緑色の金属ケースから、よく見知った\\n薄青い光が放たれている。")
	novel_interface.show_character("ren_maid","solemn")
	await novel_interface.show_dialog("あれはまさか……異質物武器！？", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","angry")
	await novel_interface.show_dialog("感じるわ、魔力の流れを……", "ベアトリーチェ")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("中立エリアでそんなモノを使うなんて、\\n一体どういうつもりだッ！", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("（……レン）", "マリル")
	await novel_interface.show_text_only("突然、イヤホンの方からマリルの声が聞こえる。")
	await novel_interface.show_dialog("（奴が持っているのは『自縛繊維』で作られた\\n　誘導捕獲爆弾）\\n（非致死性『異質物武器』だ）", "マリル")
	await novel_interface.show_dialog("（起動後、約3秒で爆発する）\\n\\n（爆発すれば、繊維がフロア全体に散らばって、\\n　お前達は逃げられなくなるだろう）", "マリル")
	novel_interface.show_character("ren_maid","solemn")
	await novel_interface.show_dialog("――！？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("（今は無駄な抵抗はしなくていい）\\n\\n（後で何とかしてやる……）", "マリル")
	await novel_interface.show_text_only("ヤコブは捕獲爆弾を持つ右手をゆっくり掲げた。\\nすると、金色に光る線が数本浮かび上がる。\\nどうやら起爆準備はもう完了しているようだ。")
	novel_interface.show_character("ren_maid","solemn")
	await novel_interface.show_dialog("あの手は……魔法刻印？", "小憐")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("（とうとう異質物武器の威力を体験する時が\\n　来てしまったのか……）", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("ごめんね……", "ベアトリーチェ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ベアトリーチェが突然俺の手を掴み、\\n\\nもう片方の手でラファエルが持っていた\\nエメラルドのペンダントを素早く奪った。")
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("──えっ？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("瞬時にペンダントが強烈な光を放ち──\\n\\nベアトリーチェの手の中に、銘文が刻まれた\\n大剣が生成される。")
	novel_interface.show_character("beatrice_battle","smile1")
	await novel_interface.show_dialog("──踠き\\n──弁明を企む\\n────罪悪の魂よ", "ベアトリーチェ")
	await novel_interface.hide_character()
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("なっ……", "ヤコブ")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","angry")
	await novel_interface.show_dialog("黙りなさい！！！", "ベアトリーチェ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ベアトリーチェは大剣の鋭い切っ先を、\\n深々と床へと刺しこんだ。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("ヤコブは口を開こうとしたが、その声は何かに\\n呑み込まれたかのように消えた。\\n部屋に残されたのは、息を呑む静寂のみ。")
	await novel_interface.show_text_only("ヤコブの足元に亀裂が走る。亀裂から覗くのは、\\nフロアの床でも建材でもなく……\\n────真なる闇だった。")
	await novel_interface.show_text_only("深淵より、甚大な悲痛が叫ばれる。\\n数百万人の咆哮めいたモノが聞こえ、\\nまるでそこは切り裂かれた地獄の一角の如く。")
	await novel_interface.show_text_only("厄災の具現が地面の裂け目から噴き出す。\\n\\n闇は刹那も許さず、見渡す限りを染め上げる。")
	await novel_interface.show_text_only("骨まで響く冷たさと形容し難い恐怖に包まれる。\\n\\n全身の毛が逆立ち、その場から動けなくなった。")
	novel_interface.show_background("res://assets/images/bg/SkyHotel/guestRoomInner.png")
	await novel_interface.show_text_only("────そして闇は素早く消えていった。\\n全ては僅か数秒での出来事ごとで、\\n先ほどの亀裂など、\\nまるで最初から存在などしなかったかのようだ。")
	await novel_interface.show_text_only("ヤコブはパニック発作を起こしたかのように\\n狂ったように地面に倒れこんだ。\\n自分の首を爪で掻きむしり、\\n幾筋もの血の跡を作りあげている。")
	await novel_interface.show_text_only("顔を真っ赤にして懸命に息をするが、\\n彼の肺は一瞬で真空にでもなったかのようで、\\n鼻腔から呼吸音を必死に発している。")
	await novel_interface.show_text_only("しばらくして、微弱ながらもやっと彼の呼吸が\\n回復した事を音から判断した。")
	await novel_interface.show_text_only("地面のカーペットを巻き込み、\\n大柄な身体を丸く縮こまらせ、\\n両手で胸元を抑えても、止まらない震えに\\n今も苛まれている。")
	await novel_interface.show_text_only("恐怖に満ちた溢れた目は赤く充血し、\\n体内機能の失圧の為か、\\n分泌された液体が涙腺より溢れ落ちていた。")
	await novel_interface.show_text_only("この時、すでに彼の手に浮かんでいた模様は\\n完全に消えていた。\\nヤコブの掲げていた誘導捕獲爆弾も\\nカーペットに転がり既に光沢を失っている。")
	await novel_interface.show_text_only("部屋中にいる覆面兵士は、全員その場で\\n呆然としている。\\n──震えを止めずに。")
	await novel_interface.show_text_only("倒れないように懸命に立とうとしている様子から\\n先ほど巻き起こった意識の構築を超える恐怖に、\\n未だ彼らが浸ったままであるという事が分かる。")
	await novel_interface.show_text_only("あなたが深淵を覗いている時に……\\n\\n深淵もまたあなたを覗いている……")
	await novel_interface.show_text_only("本当の恐怖を目の当たりにした時は、\\nたとえ呼吸をするだけでも……")
	await novel_interface.show_text_only("形容が不可能な程の絶望的存在の前に、\\n晒されていると、理解できてしまう……")
	novel_interface.show_character("beatrice_battle","angry")
	await novel_interface.show_dialog("早く、行きなさい！", "ベアトリーチェ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("…………")
	await novel_interface.show_dialog("（レンッ！　早く！）", "マリル")
	await novel_interface.show_text_only("やっと正気に戻った俺は、ベアトリーチェに頷き\\nアニーを抱き上げ素早く部屋を離れた。")
	await novel_interface.show_text_only("未だ呆然としているラファエルを、\\nベアトリーチェが引っ張る。\\n俺たちはエレベーターに向かって素早く走った。")

	print("=== 第3章第14话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
