# chapter3_ep10.gd - 第3章第10话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep10_script()

func play_script():
	pass

func chapter3_ep10_script():
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	novel_interface.change_background("res://assets/images/bg/SkyHotel/diningRoom2.png")
	await novel_interface.show_text_only("Gracias a Skurd, parece que Fabella decide dejarme ir.")
	await novel_interface.show_text_only("Justo cuando Skurd se da vuelta, varios invitados bien vestidos se acercan y hablan con ella.")
	await novel_interface.show_text_only("La niña tiene aproximadamente la misma edad que Elluka, pero brilla en una ocasión social tan elegante...")
	novel_interface.show_character("ren_maid","worry")
	await novel_interface.show_dialog("(Skuld… ¿Es ella de una familia noble?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mientras Fabella dirige su atención a su maestro, me escabullo al otro lado del salón de banquetes.")
	novel_interface.show_character("ren_maid","wry_smile")
	await novel_interface.show_dialog("Esto me está asustando... \\nLa pequeña maestra y su doncella, ¿no?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Parece que la criada no me va a pillar. \\n¿Ella sólo quería engañarme?")
	novel_interface.show_character("anne_uniform","normal1")
	await novel_interface.show_dialog("¡Ren, estás aquí!", "Annie")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("¡Podría haberme topado con una pista importante!", "Annie")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_maid","normal2",0.25)
	await novel_interface.show_dialog("¿Eh?", "Lian")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Justo ahora, seguí a la delegación en secreto hasta el piso ejecutivo, y allí vi al séquito de Raphael cargando una maleta especial.", "Annie")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire1")
	await novel_interface.show_dialog("Una maleta… ¿Qué hay dentro?", "Lian")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("No sé. ¡Pero recuerdo que en la capacitación SID se mencionaba el material utilizado en la maleta!", "Annie")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("Es un metal verde grisáceo con un peculiar resplandor azul claro.", "Annie")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"solemn")
	await novel_interface.show_dialog("Resplandor azul claro... \\n¡Qué! ¿No es así…?", "Lian")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("Recuerdo una aleación que reduce o elimina los efectos de los psicoactivos y memes Substance H…")
	await novel_interface.show_text_only("Los contenedores Substance H fabricados con esta aleación pueden eludir la mayoría de los escaneos de tonos.")
	await novel_interface.show_text_only("La aleación en sí es un Substance H: el 98% son metales conocidos y el 2% restante son sustancias desconocidas.")
	await novel_interface.show_text_only("Debido a su escasez, su precio en el mercado negro se ha disparado.")
	await novel_interface.show_text_only("Estoy casi seguro de que cualquier cosa que haya en esa maleta tiene algo que ver con Substance H.")
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("¡Santa mierda! \\n¿Ha informado de esto a Mariru?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La delegación Salmonton no ha informado al Senado que traerían ningún Substance H con ellos.")
	await novel_interface.show_text_only("Cualquier Substance H destructivo introducido de contrabando en el campo de fuerza protectora puede provocar una catástrofe en New Opulentia.")
	novel_interface.show_character("anne_uniform","relieve")
	await novel_interface.show_dialog("Le dije inmediatamente. Debe estar solicitando una orden de registro del Senado ahora mismo.", "Annie")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Pero lo vi de un vistazo y no tomé ninguna foto. \\nNo creo que puedan entrar en la habitación sin más pruebas...", "Annie")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Es por eso que Mariru acaba de actualizar nuestra misión a \"Proteger y cargar evidencia lo antes posible\".", "Annie")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_maid","solemn",0.25)
	await novel_interface.show_dialog("Si es así, la única posibilidad es colarse en sus habitaciones…", "Lian")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Sí… la habitación de las chicas. No es una tarea fácil.", "Annie")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"stare")
	await novel_interface.show_dialog("Hmm… Tendremos que tocarlo de oído ahora.", "Lian")
	await novel_interface.hide_2nd_character()
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	novel_interface.change_background("res://assets/images/bg/SkyHotel/guestRoomPassage.png")
	await novel_interface.show_text_only("El piso ejecutivo está reservado para la delegación. Llegamos allí a través del ascensor de servicio.")
	await novel_interface.show_text_only("Empujo el carrito de servicio \"prestado\" hacia el pasillo fuertemente vigilado. Annie se esconde debajo...")
	await novel_interface.show_dialog("¡Oye! ¿No se supone que deberías estar en el banquete de abajo? \\nNo estás permitido aquí. Vete ahora.", "Seguridad")
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("(Tantos guardias de seguridad, efectivamente…)", "Lian")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("¿Eh? ¡Pero un huésped de la Suite Real acaba de pedir foie gras al servicio de habitaciones con whisky en llamas!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("El líder no parece impresionado en absoluto.")
	await novel_interface.show_text_only("Claramente lo he subestimado. Tengo que encontrar otra manera...")
	novel_interface.show_character("ren_maid","wry_smile")
	await novel_interface.show_dialog("Uh... Quizás el servicio de habitaciones cometió un error. Mis disculpas, señor...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Apenas termino de hablar cuando Annie sale corriendo y le golpea el cuello con el bate de béisbol.")
	await novel_interface.show_text_only("Luego se da vuelta y lanza una pelota de béisbol directamente a la cara de otro guardia a 10 metros de distancia.")
	await novel_interface.show_text_only("El guardia restante queda estupefacto por el ataque. Antes de que pudiera alcanzar su transceptor, Annie le da una patada en la barbilla.")
	await novel_interface.show_text_only("Tres hombres se desploman casi todos a la vez. El murciélago rebota en el suelo y vuelve a la mano de Annie.")
	novel_interface.show_character("ren_maid","wry_smile")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","happy",0.25)
	await novel_interface.show_dialog("¡Claro!", "Annie")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"perspire1")
	await novel_interface.show_dialog("¿Qué… qué hiciste?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("Nada. Simplemente dejándolos reposar un rato.", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("Jaja, eso es tan Annie… \\n(Gracias a Dios, estoy con ella…)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("¡Y ni siquiera usó magia! \\n¿Qué tipo de entrenamiento está recibiendo...?")
	await novel_interface.show_text_only("Después de quitar a los guardias del camino, Annie me lleva a la suite de doble puerta al final del pasillo.")
	novel_interface.show_character("anne_uniform","normal1")
	await novel_interface.show_dialog("Aquí.", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Intercambiamos una mirada. \\nJusto cuando estamos a punto de presionar la puerta con los oídos...")
	await novel_interface.show_text_only("De repente se abre desde dentro. Nos pillan con la guardia baja y caemos al suelo dentro de la habitación.")
	await novel_interface.hide_background()
	novel_interface.show_character("ren_maid","sob")
	await novel_interface.show_dialog("Owww…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Al levantar la vista, veo un rostro familiar y arrogante.")
	novel_interface.change_background("res://assets/images/bg/SkyHotel/guestRoomInner.png")
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("… Raphael?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphael está rodeada por varios guardaespaldas y su séquito, con una expresión de desprecio en su rostro.")
	await novel_interface.show_text_only("¡Vaya, cuántas mujeres maduras y guapas!")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("¿Mmm? ¿No eres ese monstruo travesti de ese basurero que es una escuela? ¿Qué estás haciendo aquí?", "Raphael")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("¡Con trajes de sirvienta francesa! ¿No te sientes lo suficientemente pervertido?", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","wail")
	await novel_interface.show_dialog("¡Q… qué coincidencia! \\nSolo estoy trabajando a tiempo parcial aquí con mi compañero de clase...", "Lian")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Ah, y… el salón de banquetes de abajo, ¿verdad? \\nEs posible que hayamos venido al lugar equivocado.", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lo siento, Annie, ¡soy un desastre mintiendo!")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("Eso es raro. ¿No te detuvieron los guardias de seguridad?", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Confundido, Raphael mira hacia el pasillo.")
	await novel_interface.show_text_only("Raphael se horroriza cuando encuentra a los guardias de seguridad, todos inconscientes en el suelo.")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("—¡Atrápenlos!", "Raphael")

	print("=== 第3章第10话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
