# chapter3_ep15.gd - 第3章第15话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep15_script()

func play_script():
	pass

func chapter3_ep15_script():
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	novel_interface.change_background("res://assets/images/bg/SkyHotel/parkingLot_night.png")
	await novel_interface.show_text_only("마리루의 안내에 따라 우리는 지하 주차장의 지정 위치에 왔다.")
	novel_interface.show_character("ren_maid","gratified")
	await novel_interface.show_dialog("그 사람들은 우릴 쫓아오지 않고 다른 통로에서 철수했다고 한다. ", "샤오롄")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","normal2")
	await novel_interface.show_dialog("상처를 보여줘……응급치료를 배운 적 있어.", "라파엘")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("라파엘이 앤을 난간 위에 눕히라고 한 뒤 맥박과 호흡을 살핀다.")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("다행히 심실세동 증상은 없지만, 호흡이 약하고 화상이 많아서, 내장의 손상 정도가 어떨지 알 수 없어……", "라파엘")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("그 미친 녀석들! 여자아이에게 이런 짓을 하다니!", "라파엘")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("이봐요, 아가씨──", "베아트리체")
	await novel_interface.show_dialog("아가씨 옆에 작은 동물이 자주 나타나나요?\\n예를 들면──", "베아트리체")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("베아트리체가 가리킨 방향으로 돌아보니, 비둘기 두 마리가 우리 주위를 맴돌고 있다.")
	await novel_interface.show_dialog("구구구", "비둘기")
	novel_interface.show_character("raphael","worry")
	await novel_interface.show_dialog("그게 뭐가 어때서. 어딜 가나 이런 동물은 있잖아?", "라파엘")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","wail")
	await novel_interface.show_dialog("아니, 여긴 지하 3층 주차장인데……", "샤오롄")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("그래서?\\n흔한 일이야~", "라파엘")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("구구구구", "비둘기")
	novel_interface.show_character("ren_maid","wry_smile")
	await novel_interface.show_dialog("(…설마 이 아가씨는 이런 쪽에 상식이 없는 건가?)", "샤오롄")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("치유계열 마법은 작은 동물을 끌어들이죠. 만약 본인이 자각하지 못했다면……", "베아트리체")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("베아트리체가 나를 라파엘 옆으로 끌어당긴 후, 각각 우리 두 사람의 손목을 잡는다.")
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("자, 시도해보죠──", "베아트리체")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","upset")
	await novel_interface.show_dialog("응?", "샤오롄")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("베아트리체가 나와 라파엘의 손을 모으고 자신의 손바닥으로 감싼다.")
	novel_interface.show_character("ren_maid","upset")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","normal1",0.25)
	await novel_interface.show_dialog("뭐하는 거야──?", "라파엘")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("이 아가씨, 손이 의외로 부드럽다.\\n게다가 따뜻해……")
	await novel_interface.show_text_only("아니, 잠깐!\\n우리 지금──")
	novel_interface.show_character("ren_maid","perspire1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("raphael","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("손을 잡고 있어……", "샤오롄")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("놀람과 분노가 섞인 표정의 라파엘이 눈에서 레이저를 쏘듯 날 노려본다.")
	await novel_interface.show_text_only("그녀가 날 변태라고 욕하며 흠씬 두드려 패는 장면이 머릿속을 스친다. ")
	await novel_interface.show_text_only("라파엘이 뭔가를 느낀 듯 베아트리체를 바라보자 그녀가 라파엘을 향해 고개를 끄떡인다.")
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("?", "샤오롄")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("라파엘이 진지하게 눈을 감고, 베아트리체가 우리 둘의 손을 잡은 손을 천천히 놓는다. ")
	novel_interface.show_character("ren_maid","stare")
	await novel_interface.show_dialog("(엣?설마 내 손이 잡아당기기 좋은 손인가?)", "샤오롄")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("갑자기 따뜻한 빛이 온 몸을 감싸는 것처럼 몸이 가벼워진다.")
	await novel_interface.show_text_only("후──\\n지하 주차장의 공기도 이렇게 맑을 수 있다는 걸 처음 알았어~")
	await novel_interface.show_text_only("왠지 모르겠지만 방금 그 공포스러운 장면이 마음 속에서 연기처럼 사라졌다.")
	await novel_interface.show_dialog("콜록, 콜록──", "앤")
	novel_interface.show_character("ren_maid","happy")
	await novel_interface.show_dialog("앤?", "샤오롄")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("앤의 몸 위에 있떤 화상이 불가사의한 속도로 옅어지더니 완전히 사라졌다.")
	await novel_interface.show_text_only("따스한 느낌이 점점 사라지고 라파엘이 긴 숨을 쉰 후 눈을 뜨고 우리를 바라본다.")
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("렌, 여긴 어디야……?", "앤")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("앤이 마치 방금 잠에서 깬 것처럼 몽롱한 눈빛으로 날 쳐다본다.")
	novel_interface.show_character("ren_maid","gratified")
	await novel_interface.show_dialog("안전하게 빠져나왔어. 지금 마리루를 기다리고 있는 중이야.", "샤오롄")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("……", "라파엘")
	await novel_interface.show_dialog("왜……", "라파엘")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","worry")
	await novel_interface.show_dialog("모르셨군요?", "베아트리체")
	novel_interface.change_expression("smile2")
	await novel_interface.show_dialog("이토록 아름다운 치유 능력을 보유한 마녀 아가씨는\\n정말 절 설레게 한다니까요~", "베아트리체")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","happy")
	await novel_interface.show_dialog("정말이야. 라파엘, 나도 느꼈어!", "샤오롄")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("…마녀라니……너희들 무슨 헛소리를 하는 거야!", "라파엘")
	novel_interface.character_dark()
	await novel_interface.show_text_only("라파엘이 미간을 찌푸린다.")
	novel_interface.character_light()
	await novel_interface.show_dialog("방금 나한테 무슨 짓을 한 거야?\\n앤의 상처가 어떻게 갑자기 회복됐지?", "라파엘")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("이 귀족 아가씨의 세계관이 거대한 충격을 받은 것 같다. 어떻게 설명하지…?")
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("그리고 보안군을 공격한 놈들은 누구지?\\n감히 이런 곳에서 이물질 무기를 사용하다니…", "라파엘")
	await novel_interface.show_dialog("몇 백 년 전에 죽은 사람이 갑자기 살아나고, 난 아직도 그녀의 유물을 착용하고 있어.", "라파엘")
	await novel_interface.show_dialog("게다가 그런 것까지 보다니……", "라파엘")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("방금 화면이 생각났는지 라파엘의 목소리가 조금 떨린다. ")
	await novel_interface.show_text_only("다시 베아트리체의 얼굴을 쳐다보니, 티 없이 정교한 얼굴에 침착하고 여유로운 미소가 떠오른다.")
	await novel_interface.show_text_only("에메랄드는 다시 원래 모습으로 돌아왔고, 베아트리체는 그것을 라파엘에게 돌려주었다.")
	await novel_interface.show_text_only("마치 방금 전의 끔찍한 장면이 그녀와는 아무 상관도 없었던 것처럼 보였다.")
	novel_interface.show_character("beatrice_battle","smile1")
	await novel_interface.show_dialog("《칠현자의 서》의 마법은 사람의 마음에 영향을 미치죠…\\n처음 보았을 땐 무서울 수 있어요.", "베아트리체")
	novel_interface.change_expression("smile2")
	await novel_interface.show_dialog("공포는 인간의 가장 중요한 감정이에요. 자신의 약점을 알아야 위기에서 살아남을 수 있어요.", "베아트리체")
	await novel_interface.show_dialog("정말 무서운 것은 공포에 마음을 지배당한 사람들이에요……", "베아트리체")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("베아트리체가 과거 일을 회상하는 듯 아주 슬픈 눈빛을 한다.")
	novel_interface.show_character("beatrice_battle","smile1")
	await novel_interface.show_dialog("전 여전히 제가 그 책을 열지 않았길, 그 소원을 빌지 않았길 소망한답니다.", "베아트리체")
	await novel_interface.show_dialog("그 저주 같은 능력을 얻지 않았다면……", "베아트리체")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","normal1")
	await novel_interface.show_dialog("저주?", "샤오롄")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("마도서는 내게……\\n스스로도 제어할 수 없는『이성 유혹』 마법을 줬어요.", "베아트리체")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("(어쩐지……!)", "앤")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("베아트리체가 날 바라보며  집게손가락 끝을 내 목에 갖다 댄다. ")
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("하나만 물어봐도 돼요?", "베아트리체")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("네… 말씀하세요!", "샤오롄")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("beatrice_battle","smile2",0.25)
	await novel_interface.show_dialog("렌, 맞죠?\\n정말 특별하군요……", "베아트리체")
	await novel_interface.show_dialog("여자는 이 마법의 영향을 받지 않는데, 어째서 당신은.... 날 몰래 쳐다보고 있죠?", "베아트리체")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("들켰다!\\n아아아아아, 얘기하지 마!!!")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("하지만……당신은 그 남자들처럼 완전히 이성을 잃지는 않는군요.", "베아트리체")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("(마법 때문일까……?)\\n(아니, 나도 방금 이성을 잃었는 걸!!)", "샤오롄")
	novel_interface.character_dark()
	await novel_interface.show_text_only("베아트리체가 손가락으로 내 턱을 들어올리고 코 끝을 누른다. ")
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("싫지 않아요……아니, 사랑스럽다고 해야겠죠~", "베아트리체")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,false)
	await novel_interface.show_text_only("나는 반사적으로 침을 꼴딱 삼켰다.")
	await novel_interface.show_text_only("정말……마법 때문일까?!")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("빠른 속도로 주차장에 들어온 검은색 SUV리무진이 우리 앞에 멈춘다.")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("렌, 앤, 어서 타!", "마리루")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("당신이 베아트리체지? 우리와 함께 가줬으면 좋겠어.", "마리루")
	await novel_interface.show_dialog("당시 알던 사람들의 이력이 궁금하다면, 우리가 이미 모든 자료를 준비해놨어.", "마리루")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("당신을 짝사랑했던 그 시인의 시가 지금까지 전해져 오고 있어.", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile1")
	await novel_interface.show_dialog("좋아요. 당신들의 이 귀여운 생명체에도 관심이 있으니까요.", "베아트리체")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("베아트리체와 눈이 마주친 내 얼굴이 순식간에 붉어졌다……")
	await novel_interface.show_text_only("지, 진짜 단순히 마법 때문일까?!!")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("라파엘은 호텔로 돌아가는 게 좋겠어. 그 녀석들이 모두 철수했으니 이제 안전할 거야.", "마리루")
	await novel_interface.show_dialog("게다가 시찰단이 네가 실종된 걸 알고 난리가 났으니까.", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","normal2")
	await novel_interface.show_dialog("우리가 금지물품을 들고 와서.... 이렇게 큰 소란을 피웠군.", "라파엘")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("라파엘이 베아트리체를 쳐다본다.\\n그 금지물품이 미녀로 변했으니, 아주 기쁜 일이지.")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("이렇게 날 놔주는 거야?", "라파엘")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal1",0.25)
	await novel_interface.show_dialog("덱스 박사와 앞으로 1년간 살몬톤의 농산품을 내가 정한 거래상에게 우선 공급하기로 거래를 했어.", "마리루")
	novel_interface.change_2nd_expression("speak2")
	await novel_interface.show_dialog("내가 제2학원도시의 선물거래소에 한 행동도 대충 눈감아 주기로 했지. ", "마리루")
	await novel_interface.show_dialog("관련 협의서는 내 사무실 책상에 모셔놨어. SID는 밑지는 장사는 하지 않으니 걱정 마~", "마리루")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("잠깐!우릴 위험에 빠트린 게 돈을 벌기 위해서였어!?")
	novel_interface.character_light(0.35,"thinking")
	await novel_interface.show_dialog("흥──", "라파엘")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("좋아. 내가 이 일을 파악하기 전까지 오늘 일을 아무에게도 알리지 않는다고 약속할게.", "라파엘")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("덱스가의 사람들과 거래하는 건 정말 즐겁다니까~", "마리루")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"stare")
	await novel_interface.show_dialog("렌, 난 살몬톤에 돌아가서 마력에 관한 일을 모두 조사할 거야.", "라파엘")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","happy")
	await novel_interface.show_dialog("응! 라파엘이 멋진 힘을 가지고 있는 게 느껴져~", "샤오롄")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("라파엘이 몸을 돌리려다 갑자기 멈춘다.\\n그녀가 에메랄드 펜던트를 꺼내 내게 던진다.")
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("이건 네 가문의 소장품이잖아? 어떻게……", "샤오롄")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","normal2")
	await novel_interface.show_dialog("이젠 네 거야.", "라파엘")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("정말 박력 있는 아가씨군요. 나중에 멋있는 여인이 되겠어요~", "베아트리체")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("흥, 너의 내막도 철저히 조사할 거야.", "라파엘")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("그럼 다들, 안녕.", "라파엘")

	print("=== 第3章第15话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
