# chapter3_ep08.gd - 第3章第8话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep08_script()

func play_script():
	pass

func chapter3_ep08_script():
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_centreSpace1.png")
	await novel_interface.show_text_only("Tôi cảm thấy bồn chồn khi tham quan Raphael quanh khuôn viên trường.")
	await novel_interface.show_text_only("Tôi chưa bao giờ nghĩ mình có thể tiếp cận mục tiêu dễ dàng đến vậy.")
	await novel_interface.show_text_only("Thầy hiệu phó, chứng kiến buổi lễ chào mừng đã chuẩn bị từ lâu của mình bị hủy hoại, liền cắn một chiếc khăn tay với vẻ oán giận ở đâu đó phía sau chúng tôi.")
	await novel_interface.show_text_only("Tuy nhiên, cô gái trẻ có vẻ không hài lòng với chuyến tham quan nho nhỏ của chúng tôi, mặc dù bây giờ cô ấy đang có tâm trạng tốt hơn nhiều.")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("Có phải vậy không?", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("Ừm, nếu ý bạn là chuyến tham quan.", "Lian")
	await novel_interface.show_dialog("Nếu bạn tiếp tục đi theo hướng đó, bạn sẽ đến khu thương mại.", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("Rất nhiều tòa nhà ở đây bắt chước phong cách kiến trúc trước chiến tranh, cố gắng mang lại cảm giác văn hóa.", "Raphael")
	await novel_interface.show_dialog("Tuy nhiên, khuôn viên này quá nhỏ nên không có khoảng đệm giữa các tòa nhà có phong cách tương phản.", "Raphael")
	await novel_interface.show_dialog("Điều này làm cho mọi thứ ở đây quá ngột ngạt, bạn có nghĩ vậy không?", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("New Opulentia là một thành phố được xây dựng lại trên đống đổ nát. Hầu hết các di tích lịch sử của nó đã bị đốt cháy.")
	await novel_interface.show_text_only("Thực sự khá xa xỉ khi có một dải đất như vậy trong lá chắn bảo vệ nơi đất đai khan hiếm.")
	await novel_interface.show_text_only("Tôi phần nào cảm thấy bị xúc phạm bởi lời nói của cô ấy…")
	novel_interface.show_character("ren_uniform","normal2")
	await novel_interface.show_dialog("Ừm…", "Lian")
	await novel_interface.show_dialog("Bạn phải Raphael Dekkers đến từ Thành phố học thuật thứ tư.", "Lian")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("Vậy tại sao bạn lại đến thăm trường nếu bạn không thích nó ở đây?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","jeer")
	await novel_interface.show_dialog("Ồ, bạn biết tôi là ai không?", "Raphael")
	await novel_interface.show_dialog("Hừm… Tất cả là do ông nội tôi. Anh ấy muốn tôi học ở một Thành phố Học thuật khác…", "Raphael")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("Nhưng ngôi trường bắt chước này không có lịch sử gì cả… Tôi sẽ không bao giờ đặt chân đến nó nữa.", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("…", "Lian")
	await novel_interface.show_dialog("(Vậy là cô ấy chỉ đơn giản là không hài lòng về kế hoạch của ông nội mình…) \\n(Tại sao cô ấy không lên tiếng?!)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tệ thật! Lời nói của cô ấy phần nào đó đã ảnh hưởng đến tôi. Tất cả các tòa nhà trong trường đột nhiên trông kỳ lạ.")
	await novel_interface.show_text_only("Chết tiệt! Hãy quên những bình luận đó đi! Hiện nay!")
	novel_interface.show_character("nyx_normal","normal1")
	await novel_interface.show_dialog("Wow, vì bạn quá thất vọng…", "Nix")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("Tại sao bạn không nói với ông của bạn những gì bạn nghĩ?", "Nix")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Nix bước đến chỗ chúng tôi, thanh lịch như mọi khi.")
	await novel_interface.show_text_only("Khi mắt họ gặp nhau, tôi nghĩ mình nghe thấy tiếng nổ lách tách của dòng điện cao thế.")
	await novel_interface.show_text_only("Chắc hẳn là… ảo giác, phải không?")
	novel_interface.show_character("raphael","worry")
	await novel_interface.show_dialog("Bạn là ai?", "Raphael")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_normal","smile",0.25)
	await novel_interface.show_dialog("Chà, tôi chỉ là một kẻ vô dụng ở trường này.", "Nix")
	novel_interface.change_2nd_expression("mock")
	await novel_interface.show_dialog("Tôi chỉ đang tự hỏi điều gì đã đưa cô đến đây, thưa cô?", "Nix")
	await novel_interface.show_dialog("Tại sao ngay từ đầu bạn lại đồng ý đến đây? Có phải do áp lực của gia đình?", "Nix")
	novel_interface.character_light(0.35,"angry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Chuyện gia đình tôi không liên quan đến anh.", "Raphael")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Hãy để tôi đoán. Một đứa trẻ luôn coi mình là trung tâm và không bao giờ làm trái ý muốn của cha mẹ.", "Nix")
	novel_interface.change_2nd_expression("sad")
	await novel_interface.show_dialog("Tại sao bạn lại coi mình cao hơn? Ai cho bạn quyền đánh giá một trường học? Rốt cuộc, cô ấy đã tình nguyện dẫn bạn đi tham quan xung quanh.", "Nix")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"subtle")
	await novel_interface.show_dialog("Xin lỗi?! Khi nào tôi coi mình là ưu việt?", "Raphael")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Này, đồ biến thái. Có bao giờ tôi kiêu ngạo đến thế không?", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("Không hẳn…", "Lian")
	await novel_interface.show_text_only("Đợi đã, tôi không phải kẻ biến thái!")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("Thấy không? Tôi không nói điều đó.", "Raphael")
	await novel_interface.show_dialog("Nhân tiện, thứ quanh cổ cậu…", "Raphael")
	novel_interface.change_expression("jeer")
	await novel_interface.show_dialog("Trường này có cho phép đeo đồ trang sức không?", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("Trên thực tế, chúng tôi không có bất kỳ hạn chế nào trong việc đeo đồ trang sức…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Và chiếc vòng cổ của Nix thật dễ thương!")
	novel_interface.show_character("raphael","jeer")
	await novel_interface.show_dialog("Dây đeo có thể đơn giản nhưng chắc chắn không phải là viên ngọc quý trên đó—Kim cương đen Orlov. Viên ngọc hoàng gia này đã vỡ thành ba mảnh và bị thất lạc trong thời kỳ hỗn loạn trước khi chiến tranh nổ ra.", "Raphael")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("Bạn có thể có thể mua một vài tòa nhà ở đây chỉ với một mảnh.", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("Cái gì?!", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("Đóng giả là một học sinh bình thường và lên tiếng thay họ… Bạn muốn gì? Để đánh lừa kẻ biến thái mặc đồ khác giới này rằng bạn đứng về phía cô ấy?", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("nyx_normal","normal2")
	await novel_interface.show_dialog("…", "Nix")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Đừng gọi tôi là kẻ biến thái nữa!")
	await novel_interface.show_text_only("Và tại sao Nix lại có vẻ ngoài tinh tế và đáng tiếc như thế này?")
	novel_interface.show_character("nyx_normal","normal2")
	await novel_interface.show_dialog("Tôi chỉ đang mặc thứ gì đó phù hợp với mình thôi.", "Nix")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("Còn bạn thì sao? Bạn cố tỏ ra độc lập nhưng lại tự hào khi được hưởng sự giàu có của gia đình mình. Điều đó thật buồn cười.", "Nix")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","mock",0.25)
	await novel_interface.show_dialog("Tôi nhớ cả ba mảnh đều rơi vào tay một tên trùm mafia. Một viên Kim cương đen được mua bằng tiền bất chính—nó rất hợp với bạn.", "Raphael")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Vâng, tôi phải thừa nhận rằng gia đình tôi kém may mắn hơn. Suy cho cùng, không phải ai cũng có thể kiếm được tài sản và danh hiệu cao quý nhờ độc quyền về ngũ cốc.", "Nix")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("Đó là bởi vì chỉ có cây trồng của chúng ta mới có thể giúp con người ngăn chặn được Bệnh dịch hạch đen. Họ xứng đáng được sống. Không như anh, mục nát từ trong ra ngoài.", "Raphael")
	novel_interface.character_light(0.35,"mock")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Bạn nhất quyết giữ vững niềm tin trong khi đe dọa thế giới bằng nạn đói. Tại sao bạn không suy ngẫm về tâm hồn của chính mình trước tiên?", "Nix")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"jeer")
	await novel_interface.show_dialog("Tôi không cần phải làm điều đó với những người như bạn. Nó sẽ chỉ mang lại cho tôi sự xấu hổ.", "Raphael")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0)
	await novel_interface.show_dialog("Ồ, điều đó nghe có vẻ quen thuộc. Tôi cũng không muốn biết về những kẻ thua cuộc như các bạn.", "Nix")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("…")
	await novel_interface.show_text_only("Nắng chiều chiếu nhẹ lên chúng tôi.")
	await novel_interface.show_text_only("Đứng giữa hai người, tôi không biết phải giải quyết cuộc chiến này như thế nào.")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("(Bạn có chắc là mình chưa từng gặp nhau trước đây không?)", "Lian")
	await novel_interface.show_dialog("(Bạn thực sự không phải là kẻ thù truyền kiếp?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Hiệu phó ở xa đã hoảng sợ đưa đi cấp cứu.")
	await novel_interface.show_text_only("Đừng bận tâm. Tôi có tất cả thông tin mà Mariru muốn.")
	await novel_interface.show_text_only("Dù sao thì đó cũng không phải việc của tôi.")

	print("=== 第3章第8话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
