# chapter1_ep6.gd - Chapter 1 Episode 6
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter1_ep6_script()

func play_script():
	pass

func chapter1_ep6_script():
	novel_interface.change_music("res://assets/audio/music/Black Market.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_outside.png")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("...Hah, hah... non ho ben capito cosa sia successo,\nma possiamo dire di aver vinto...?",GameConfig.player_name)
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_battle","normal",0.25)
	await novel_interface.show_dialog("...Direi di sì.","Annie")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("T-tu chi saresti!?\nDa dove sei sbucata!?",GameConfig.player_name)
	await novel_interface.show_dialog("Che razza di cose erano quelle che mi hanno aggredita!?\nE cos'è questa mazza!?",GameConfig.player_name)
	await novel_interface.show_dialog("Che diavolo sta succedendo qui?!",GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("Calmati!\nPer quanto ne so, risponderò a tutte le tue domande, una per una.", "Annie")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_dialog("Però anch'io, proprio come te, non capisco bene la situazione.\nAnzi, sarei io a voler sapere chi sei tu...", "Annie")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Scusa. Mi sono fatta prendere dal panico...",GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("Tranquilla.\nA proposito, non ci siamo ancora presentate per bene.", "Annie")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("Mi chiamo Annie Bass.\nChiamami pure Annie~", "Annie")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("...Io mi chiamo "+GameConfig.player_name+". Piacere.",GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog(GameConfig.player_name+"... piacere mio.", "Annie")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("Il tuo nome sembra da ragazzo. Ha un gran bel suono~", "Annie")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("！？", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("Che c'è, perché sei così sorpresa?","Annie")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ah, già... io adesso...\nsono una ragazza...",GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Eh? Ma tu sei una ragazza, no?\nGuarda quanto ti stanno bene i vestiti che ho trasformato per te.", "Annie")
	novel_interface.change_2nd_expression("uneasy")
	await novel_interface.show_dialog("Sei carinissima, davvero...\nQuesta 『tenuta da battaglia』 considerala pure il mio regalo di benvenuto~", "Annie")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("...Tenuta da battaglia?",GameConfig.player_name)
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("No, aspetta— aaaaaahhhhh!!!!",GameConfig.player_name)
	await novel_interface.hide_all_characters()
	novel_interface.change_background("res://assets/images/bg/Shot/BG_Shot_girlchar_battleWearingShy.png")
	await novel_interface.show_text_only("Solo allora me ne resi conto:\nindossavo davvero dei vestiti da ragazza!!")
	await novel_interface.show_text_only("Una divisa alla marinara...\ne una gonna talmente corta da mettermi in imbarazzo...!")
	await novel_interface.show_text_only("Così si sentono le calze sulla pelle delle gambe...? Che sensazione stranissima...")
	await novel_interface.show_dialog("E quella stretta che sento sul petto non sarà mica... (tocca)",GameConfig.player_name)
	await novel_interface.show_dialog("Aaaaaahhhh!!!",GameConfig.player_name)
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_outside.png")
	novel_interface.show_character("anne_battle","normal")
	await novel_interface.show_dialog("Anche la giacca si abbina benissimo al colore dei tuoi capelli~\nÈ perfetta per muoversi.", "Annie")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Mmh...? Che c'è~~?", "Annie")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","shy",0.25)
	await novel_interface.show_dialog("Perché...\nperché...",GameConfig.player_name)

	print("=== Chapter 1 Episode 6 End ===")

	# episode end
	await novel_interface.end_story_episode(0.5)
