# chapter1_ep6.gd - Chapter 1 Episode 6
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter1_ep6_script()

func play_script():
	pass

func chapter1_ep6_script():
	novel_interface.change_music("res://assets/audio/music/Black Market.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_outside.png")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("… Phew, hah… I don't know what's going on. \nBut, did we just win?",GameConfig.player_name)
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_battle","normal",0.25)
	await novel_interface.show_dialog("… Looks like so.","Annie")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Who… who are you? \nWhere are you from?",GameConfig.player_name)
	await novel_interface.show_dialog("Who are those guys attacking me? \nWhat is this bat? \nAnd what's going on here?",GameConfig.player_name)
	await novel_interface.show_dialog("What happened here?!",GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("Take it easy! \nI'll answer your questions one by one, as much as I know.", "Annie")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_dialog("But I'm just as clueless as you are.\nIf anything, I want to know who you are...", "Annie")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Sorry, I panicked…",GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("Never mind. \nAnd we haven’t introduced ourselves yet.", "Annie")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("My name is Annie Bass. \nJust call me Annie.", "Annie")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("... My name is "+GameConfig.player_name+". Nice to meet you.",GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog(GameConfig.player_name+"... Likewise.", "Annie")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("Your name sounds like a boy's name. So cool!", "Annie")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("?!", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("What? Why do you look terrified?","Annie")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ahh, I'm now… \nA girl…",GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Er? You're a girl! \nLook at the costume I created for you! It suits you, right?", "Annie")
	novel_interface.change_2nd_expression("uneasy")
	await novel_interface.show_dialog("It's so cute… \nTake this Battle Suit as a gift from me!", "Annie")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("… Battle Suit?",GameConfig.player_name)
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("Oh my—Aaaah!!",GameConfig.player_name)
	await novel_interface.hide_all_characters()
	novel_interface.change_background("res://assets/images/bg/Shot/BG_Shot_girlchar_battleWearingShy.png")
	await novel_interface.show_text_only("I just notice that\nI've been wearing girl's clothes!!")
	await novel_interface.show_text_only("A sailor dress… \nAnd the skirt is awkwardly short!")
	await novel_interface.show_text_only("The stockings… feel so strange!")
	await novel_interface.show_dialog("And the feel of tightness around my chest… No way…(Touching)",GameConfig.player_name)
	await novel_interface.show_dialog("Aaaah!",GameConfig.player_name)
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_outside.png")
	novel_interface.show_character("anne_battle","normal")
	await novel_interface.show_dialog("The suit is a perfect match for your hair-tone. \nAnd it's ideal for workouts.", "Annie")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Huh? Something wrong?", "Annie")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","shy",0.25)
	await novel_interface.show_dialog("It's… \nIt's just…",GameConfig.player_name)

	print("=== Chapter 1 Episode 6 End ===")

	# Call episode end function
	await novel_interface.end_story_episode(0.5)
