# chapter1_ep3.gd - 第1章第3話
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter1_ep3_script()

func play_script():
	pass

func chapter1_ep3_script():
	novel_interface.change_music("res://assets/audio/music/Hand-to-hand combat.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_stairway.png")
	novel_interface.show_character("soldier_2")
	await novel_interface.show_dialog("そっちの見張りから返事がない。お前、向こうを見てこい——", "男性の声A")
	await novel_interface.hide_character()
	novel_interface.show_character("soldier_1")
	await novel_interface.show_dialog("了解ッ！", "男性の声B")
	await novel_interface.hide_character()
	novel_interface.show_character("soldier_2")
	await novel_interface.show_dialog("俺は心拍検知器を取ってくる。しっかり見張ってろ！", "男性の声A")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_male","worry")
	await novel_interface.show_dialog("まずい、ここじゃやり過ごせない……",GameConfig.player_name)
	await novel_interface.show_dialog("視線に死角がなくて抜けられない。二手に分かれた瞬間に、どちらか一人を不意打ちするしかない。",GameConfig.player_name)
	await novel_interface.show_dialog("たぶん……いけるはずだ。\nあの女の人が素手で相手を倒せたくらいなんだから……",GameConfig.player_name)
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("武器になる物を探さないと……",GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("廊下の壁に金属バットが掛けられていた。下の銘板の小さな文字には『レイボナ　自由光……』と書かれていた。")
	novel_interface.show_character("ren_male","happy")
	await novel_interface.show_dialog("たぶん展示品だよな……\nでも今だけ借りるだけだ、うん、今だけ……",GameConfig.player_name)
	await novel_interface.show_dialog("…………",GameConfig.player_name)
	novel_interface.change_expression("shout")
	await novel_interface.show_dialog("よし……行くぞ！\nはああ——っ！",GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.play_background_flash_effect(Color.WHITE,3,0.15,1.0,[Color.RED,Color.BLACK],true)
	await novel_interface.show_text_only("ドンッ！！！")
	await novel_interface.show_text_only("渾身の一撃を覆面の後頭部に叩き込む。ものすごい音が響いた。えっ……こんなに音が大きいのか？")
	await novel_interface.show_background("res://assets/images/bg/Shot/BG_RC_stairway.png")
	await novel_interface.show_text_only("だが、相手は期待したように倒れず、怒りのこもった目でこちらを振り向いた。")
	novel_interface.show_character("ren_male","shock")
	await novel_interface.show_dialog("ゲームの中と全然違うじゃねえか！！",GameConfig.player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("soldier_2")
	await novel_interface.show_dialog("何者だ！", "覆面A")
	await novel_interface.hide_character()
	await novel_interface.play_background_flash_effect(Color.RED,3,0.15,0.6,[],false)
	await novel_interface.show_text_only("覆面男は素早く銃床を振りかぶって襲いかかってくる。俺は慌ててバットを握り直し、必死に受け止めた。")
	novel_interface.show_character("ren_male","shock")
	await novel_interface.show_dialog("しまった——",GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.play_background_flash_effect(Color.BLACK,1,1.0,1.0,[],false)
	await novel_interface.show_text_only("圧倒的な力がバット越しに両手と肩へ叩き込まれる。歯を食いしばって耐えていたその瞬間、覆面男の鋭い蹴りが飛んできた。")
	await novel_interface.play_background_flash_effect(Color.BLACK,1,0.15,1.0,[Color.RED],true)  
	await novel_interface.show_text_only("ブーツの先が、無防備な俺の腹へ容赦なくめり込んだ。")
	await novel_interface.play_background_flash_effect(Color.WHITE,1,0.15,1.0,[],false)
	novel_interface.show_background("res://assets/images/bg/Baizhu/white_bg.png")
	await novel_interface.show_text_only("蹴り飛ばされた俺はそのまま手すりをへし折り、真っ逆さまに下の階へ落ちた。")
	await novel_interface.play_background_flash_effect(Color.RED,1,0.15,1.0,[Color.BLACK],true)
	await novel_interface.show_text_only("あああああっ！！！！！！")
	novel_interface.show_character("soldier_2")
	await novel_interface.show_dialog("くそっ、さっき不意打ちしてきたガキが下へ落ちやがった。\n俺が仕留めてくる！", "覆面A")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_male","hurt")
	await novel_interface.show_dialog("……早く逃げないと……\n……あの展示物の影に……隠れないと……",GameConfig.player_name)
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Shot/BG_RC_stairway.png")
	novel_interface.show_character("soldier_1")
	await novel_interface.show_dialog("待て……今、隊長から連絡が来た。自爆式の防盗装置の解除に成功したそうだ。", "覆面B")
	await novel_interface.show_dialog("ぐずぐずするな。すぐ会議室に集合しろ！\nあいつが目を覚ます頃には、俺達はもう撤収してる。", "覆面B")
	await novel_interface.hide_character()
	novel_interface.show_character("soldier_2")
	await novel_interface.show_dialog("了解ッ！", "覆面A")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	novel_interface.show_character("ren_male","hurt")
	await novel_interface.show_dialog("意識が……だんだん……遠のく……\nマリル……",GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("その頃、会議室では——")
	novel_interface.change_music("res://assets/audio/music/Barrier Maze.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_Shot_liliu_instConfRoomWatching.png")
	await novel_interface.show_dialog("どうやらあいつらは光学偽装で\\n紛れ込んだようだが……","マリル")
	await novel_interface.show_dialog("収容施設の光学探知設備が一部点検中だった隙を突いたわね。内部から情報が漏れていたみたい。","マリル")
	await novel_interface.show_dialog("相手の正体はまだ不明……ここは機会を待つしかないわね。","マリル")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_conferenceRoom.png")
	novel_interface.show_character("soldier_leader")
	await novel_interface.show_dialog("ふふふ……ははは——","覆面リーダー")
	await novel_interface.show_dialog("ついに取り戻したぞ……！", "覆面リーダー")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Shot/BG_Shot_liliu_instConfRoomWatching.png")
	await novel_interface.show_dialog("あれは——『ロス・ゴールド』！？","マリル")
	novel_interface.change_background("res://assets/images/bg/Shot/losgrail.png")
	await novel_interface.show_text_only("突如太平洋中部に現れたロス諸島で、調査団が発見した『異質物』。杯の外側には四つの宝石が埋め込まれている。")
	await novel_interface.show_text_only("杯の中には赤い液体のようなものが入っているが、それは注ぐことも触れることもできず、まるで幻のように実体がない……")
	await novel_interface.show_text_only("研究所の老人共は、ありとあらゆる方法を試したのに、それが何なのか結局解明できなかった……")
	await novel_interface.show_text_only("しばらくして、アレの脅威レベルが『SAFE』に\\n下げられ公開研究の許可が下ったが……")
	await novel_interface.show_dialog("ちっ、宝石だけは無価値じゃないだろう。","マリル")
	await novel_interface.show_dialog("しかも宝石と杯本体は分子レベルで一体化している……","マリル")
	novel_interface.show_character("soldier_leader")
	await novel_interface.show_dialog("ならば私が分離してやろう、この穢れた代物を！！", "覆面リーダー")
	novel_interface.character_dark()
	await novel_interface.show_dialog("──引き離す？　どうやって───","マリル")

	print("=== 第1章第3話終了 ===")

	# エピソード終了処理
	await novel_interface.end_story_episode(0.5)
