# chapter1_ep2.gd - Chapter 1 Episode 2
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter1_ep2_script()

func play_script():
	pass

func chapter1_ep2_script():
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/AEGIS.png")
	await novel_interface.show_dialog("Đăng nhập thành công!","Hệ thống")
	await novel_interface.show_dialog("ID của bạn: 2519G1911\nTên: "+GameConfig.player_name,"Hệ thống")
	await novel_interface.show_dialog("Tuổi: 15\nGiới tính: nam","Hệ thống")
	await novel_interface.show_dialog("Chào mừng đến với Trung tâm Nghiên cứu Giam giữ Stilmont thuộc Thành Phố Học Viện Thứ Năm. Cơ sở giam giữ và nghiên cứu 『Vật dị chất』 lớn nhất khu Tân Phong Châu.","Hệ thống")
	await novel_interface.show_dialog("『Vật dị chất』, còn được gọi là 『Thần tích』, là tên gọi chung của các đạo cụ và công cụ có thể gây ra hiện tượng vật lý siêu thường trong những điều kiện nhất định.","Hệ thống")
	await novel_interface.show_dialog("Hôm nay là ngày mở cửa học viện của trung tâm nghiên cứu.\nTrung tâm mở cửa cho cư dân và các đoàn khảo sát tới từ những Thành Phố Học Viện khác.","Hệ thống")
	await novel_interface.show_dialog("Là một phần quan trọng trong hoạt động giáo dục công chúng\nmột số 『Thần tích』 và thành quả nghiên cứu sẽ được đem ra trưng bày……","Hệ thống")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_passageNight.png")
	novel_interface.show_character("ren_male","normal")
	await novel_interface.show_dialog("May quá!~ Cuối cùng cũng kịp trước giờ đóng cửa!",GameConfig.player_name)
	await novel_interface.show_dialog("Mấy cái thang máy ở sảnh thế mà đều ngừng hoạt động cả, may mà mình phát hiện ra chiếc thang hàng dự phòng vẫn còn chạy.",GameConfig.player_name)
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("Tóm lại, chỉ cần vào nghe một buổi thuyết trình rồi xin dấu xác nhận là có tín chỉ đúng không?",GameConfig.player_name)
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Nhưng mà…… sao tầng này lại chẳng thấy ai hết vậy?",GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tôi vừa đi dọc hành lang tầng hai vừa đảo mắt nhìn khắp nơi.")
	await novel_interface.show_text_only("Tuy nơi thế này bình thường vốn đã ít người, nhưng giờ lại chẳng thấy nổi lấy một bóng người.")
	await novel_interface.show_text_only("Hơn nữa trong không khí còn phảng phất mùi thuốc sát trùng của bệnh viện, khiến tôi bất giác liên tưởng đến những nhân viên vệ sinh dọn dẹp sau giờ đóng cửa.")
	novel_interface.show_character("ren_male","speechless")
	await novel_interface.show_dialog("Buổi thuyết trình chẳng lẽ đã kết thúc mất rồi?",GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Vừa tìm 『phòng hội nghị』 nơi diễn ra buổi thuyết trình, tôi vừa rẽ tới bên cạnh một cầu thang xoắn.")
	novel_interface.show_character("ren_male","worry")
	await novel_interface.show_dialog("Chết thật, quả nhiên mình không nên chơi cái game đó……",GameConfig.player_name)
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("Cái kiểu nút 『lượt tiếp theo』 đúng là có độc——aa a a ưm\n!!!?",GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Đột nhiên cổ tôi bị thứ gì đó móc lấy rồi giật mạnh về phía sau!")
	await novel_interface.show_text_only("Ngay lúc cơ thể sắp mất thăng bằng, tôi cảm thấy sau đầu mình tựa lên một vật vừa mềm mại vừa vững chắc.")
	await novel_interface.show_text_only("Khi hoàn hồn lại, tôi đã bị kéo vào một lối đi hẹp ở góc cầu thang, xung quanh tối hơn hẳn.")
	await novel_interface.show_dialog("Ư——!!\nƯm——!!!",GameConfig.player_name)
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/liliu_instPassageHiding.png")
	await novel_interface.show_text_only("Chưa kịp kêu thành tiếng, miệng tôi đã bị một bàn tay bịt chặt. Qua khóe mắt, tôi chỉ lờ mờ thấy được một người phụ nữ mặc áo blouse trắng——")
	await novel_interface.show_text_only("Lúc này cô ấy đang dựa lưng vào tường, một tay bịt miệng tôi")
	await novel_interface.show_text_only("Mà một bên má của tôi lại bị ép chặt vào trước ngực cô ấy…… hương thơm nồng nàn cứ thế xộc thẳng vào mũi.")
	await novel_interface.show_dialog("(Ơ?? To, to quá!!!! Mặt mình lún vào mất rồi!!)",GameConfig.player_name)
	await novel_interface.show_dialog("(Tình huống gì vậy!! Người này là ai!?)",GameConfig.player_name)
	await novel_interface.show_dialog("Suỵt——! Đừng lên tiếng!", "Người phụ nữ áo blouse trắng")
	await novel_interface.show_text_only("Người phụ nữ phía sau tuy cố tình hạ thấp giọng, nhưng lời nói lại toát ra uy thế không cho phép bất kỳ nghi ngờ nào.")
	await novel_interface.show_text_only("Đầu óc tôi rối tung lên, cảm giác như sắp nghẹt thở.\nTôi chỉ có thể khẽ gật đầu ra hiệu mình đã hiểu……")
	await novel_interface.show_text_only("Dù miệng tôi vẫn còn bị bịt, nhưng áp lực trên cổ đã nhẹ đi\nmột chút.")
	await novel_interface.show_text_only("Tôi nhìn kỹ hơn, lờ mờ thấy trên bảng tên cài trước ngực áo blouse trắng của cô ấy có một dòng chữ nhỏ: Nhà khoa học trưởng……")
	await novel_interface.show_dialog("(Nhà khoa học…… cô ấy là nhân viên viện nghiên cứu sao?)",GameConfig.player_name)
	await novel_interface.show_text_only("Lúc này tôi mới nhận ra cô ấy hoàn toàn không nhìn tôi, mà quay đầu sang phía\nkhác, chăm chú nhìn về phía hành lang.")
	await novel_interface.show_text_only("Từ cuối hành lang vọng lại tiếng bước chân dồn dập và nặng nề.")
	await novel_interface.show_dialog("Báo cáo, bên này không có ai.", "Giọng nam A")
	await novel_interface.show_dialog("Nhưng đúng là có một thang máy chở hàng độc lập, tôi qua đó tắt thủ công nó.", "Giọng nam A")
	await novel_interface.show_dialog("(Người vừa chạy qua ban nãy hình như còn bịt mặt, trên tay lại còn cầm…… súng?)",GameConfig.player_name)
	await novel_interface.show_dialog("Nơi này đang bị xâm nhập. Không muốn chết thì đừng nhúc nhích.", "Người phụ nữ áo blouse trắng")
	await novel_interface.show_dialog("(Xâm, xâm nhập? Rốt cuộc là chuyện gì……)",GameConfig.player_name)
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_stairway.png")
	await novel_interface.show_text_only("Trong lúc tôi còn đang ngây ra, người phụ nữ đã lách người xông ra ngoài")
	await novel_interface.show_text_only("Vài giây sau truyền đến một tiếng nện đục cùng âm thanh như xương bị bẻ gãy.")
	await novel_interface.show_text_only("Không hề có tiếng ngã xuống như tôi tưởng. Cô ấy thuận tay đỡ lấy tên bịt mặt\nrồi kéo hắn trở lại lối đi, đồng thời tháo lấy một khẩu súng lục.")
	await novel_interface.show_dialog("Hắn là……?!",GameConfig.player_name)
	await novel_interface.show_text_only("Người phụ nữ không hề để ý tới tôi, mà thuần thục mở cửa phòng điện bên tường\nrồi nhấc gót giày cao gót đá một cú, hất gã to xác mềm nhũn toàn thân vào trong.")
	await novel_interface.show_text_only("Dù mặc sơ mi trắng và váy ngắn ôm sát, động tác của cô ấy vẫn liền mạch gọn gàng đến kỳ lạ.")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("Hừm~ tạm thời chắc sẽ không có ai tới đây đâu.", "Liliu")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Cô ấy vỗ vỗ tay, như thể vừa xử lý xong một đống rác cỡ lớn, rồi quay đầu lại nhìn tôi đầy ung dung.")
	await novel_interface.show_text_only("Bộ não tôi đã không thể xử lý nổi những chuyện vừa xảy ra, chỉ biết ngây người nhìn cô ấy.")
	novel_interface.show_character("ren_male","shy")
	await novel_interface.show_dialog("(Nhìn kỹ lại thì chị này đẹp thật đấy!)\n(Với lại vóc dáng y như người mẫu nữa……)",GameConfig.player_name)
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("(Nhưng trên bảng tên trước ngực cô ấy rõ ràng lại ghi là 'nhà khoa học')",GameConfig.player_name)
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("(Vậy nên chuyện vừa rồi chắc chắn chỉ là ảo giác thôi!)",GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Đúng vậy, hiện giờ trong phòng điện hoàn toàn không có một gã đàn ông to con bịt mặt nào cả.")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_Shot_liliu_leg1.png")
	await novel_interface.show_text_only("Tôi thản nhiên đi tới kết luận ấy, rồi dời tầm mắt xuống đôi chân của cô ấy……")
	await novel_interface.show_text_only("(Được làm việc cùng một chị đẹp thế này thì tuyệt thật……)\n(Nhà nghiên cứu 『Vật dị chất』 cũng là một nghề không tệ nhỉ)")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_stairway.png")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("Này? Nhóc con, mắt cậu đang nhìn đi đâu thế?", "Người phụ nữ áo blouse trắng")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Cô ấy vừa nói vừa tháo băng đạn khẩu súng lục ra kiểm tra đạn.")
	novel_interface.show_character("ren_male","sob")
	await novel_interface.show_dialog("(Mình không thể tiếp tục tự lừa mình nữa rồi!!!)",GameConfig.player_name)
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Xin, xin chào\nbạn là……?",GameConfig.player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Mà…… cứ gọi tôi là Liliu đi\nHôm nay vốn dĩ tôi phải đứng ra làm một buổi diễn thuyết chán ngắt", "Liliu")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Cô ấy thuần thục lắp lại khẩu súng, rồi nhét nó vào túi áo blouse trắng.")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("Nhưng vừa rồi đám kia đã khống chế hội trường.\nNhờ phúc của bọn chúng mà buổi thuyết trình bị hủy luôn~", "Liliu")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_male","shock",0.25)
	await novel_interface.show_dialog("Liliu…… Liliu von Braun?!",GameConfig.player_name)
	await novel_interface.show_dialog("Chị, chị chẳng phải chính là diễn giả của buổi thuyết trình em cần xin dấu xác nhận sao!\nCòn là nhà khoa học cấp SS do Viện Nguyên lão công nhận nữa!",GameConfig.player_name)
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Hừ, lừa mấy lão già đó dễ lắm~", "Liliu")
	await novel_interface.show_dialog("Nhưng nhìn bộ dạng cậu thì là tới đây để kiếm tín chỉ cho đủ đúng không?", "Liliu")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("Ưm…… thật sự xin lỗi!!",GameConfig.player_name)
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"speak")
	await novel_interface.show_dialog("Không biết nên nói cậu là xui xẻo hay ngốc nữa. Giữa lúc nơi này bị phong tỏa mà cậu vẫn tìm được thang máy để lên đây.", "Liliu")
	await novel_interface.show_dialog("Nếu mặc kệ cậu, e là cậu đã ngơ ngác bước thẳng vào hiện trường hội trường bị khống chế rồi.", "Liliu")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Phong tỏa……?\nTôi lấy điện thoại ra, quả nhiên không còn chút tín hiệu nào.")
	await novel_interface.show_text_only("Cuối cùng tôi cũng hiểu vì sao mấy cái thang máy chính ở sảnh đều ngừng chạy…… hóa ra không phải do đã đóng cửa rồi!")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Giờ cả chiếc thang máy cậu đi lên cũng bị phong kín rồi, ngoan ngoãn ở đây chờ Cục Phòng vệ tới cứu đi.", "Liliu")
	await novel_interface.show_dialog("Tôi phải tới hội trường xem tình hình. Nếu có ai tới thì cậu trốn đi.", "Liliu")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_male","shock")
	await novel_interface.show_dialog("Nh, nhưng mà…… chị chỉ có một mình……",GameConfig.player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("Nghe rõ chưa!", "Liliu")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_male","shock")
	await novel_interface.show_dialog("Rõ!!",GameConfig.player_name)

	print("=== Chapter 1 Episode 2 End ===")

	# episode end
	await novel_interface.end_story_episode(0.5)
