# chapter1_ep2.gd - Chapter 1 Episode 2
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter1_ep2_script()

func play_script():
	pass

func chapter1_ep2_script():
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/AEGIS.png")
	await novel_interface.show_dialog("Autenticação concluída com sucesso.","Sistema")
	await novel_interface.show_dialog("Seu ID: 2519G1911\nNome: "+GameConfig.player_name,"Sistema")
	await novel_interface.show_dialog("Idade: 15 anos\nSexo: masculino","Sistema")
	await novel_interface.show_dialog("Bem-vindo ao Centro de Contenção e Pesquisa Steele Monte da Quinta Academy City, a maior instituição de contenção e pesquisa de 『Objetos Heterogêneos』 em Nova Opulentia.","Sistema")
	await novel_interface.show_dialog("『Objetos Heterogêneos』, também conhecidos como 『milagres』, designam o conjunto de artefatos e ferramentas capazes de provocar fenômenos físicos sobrenaturais em circunstâncias específicas.","Sistema")
	await novel_interface.show_dialog("Hoje é o dia de visita pública do centro de pesquisa.\nA instituição está aberta aos cidadãos e às delegações de outras Academy Cities.","Sistema")
	await novel_interface.show_dialog("Como parte importante da educação pública,\nalguns 『milagres』 e resultados de pesquisa estão em exibição...","Sistema")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_passageNight.png")
	novel_interface.show_character("ren_male","normal")
	await novel_interface.show_dialog("Que sorte! Consegui chegar antes de fechar!",GameConfig.player_name)
	await novel_interface.show_dialog("Os elevadores do saguão estão todos fora de serviço; ainda bem que achei um elevador de carga reserva que continua funcionando.",GameConfig.player_name)
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("Enfim, basta ouvir uma palestra e pegar um carimbo para conseguir os créditos, né?",GameConfig.player_name)
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Mas... por que não tem ninguém neste andar?",GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Caminhei pelo corredor do segundo andar olhando em volta.")
	await novel_interface.show_text_only("Mesmo que esse tipo de lugar normalmente já não tenha muita gente, agora não se via sequer uma pessoa.")
	await novel_interface.show_text_only("E o ar tinha um cheiro de desinfetante de hospital, o que me fez pensar nos faxineiros que limpam tudo depois do fechamento.")
	novel_interface.show_character("ren_male","speechless")
	await novel_interface.show_dialog("A palestra já acabou, por acaso?",GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Enquanto procurava o 『auditório』 da palestra, virei na direção de uma escada em espiral.")
	novel_interface.show_character("ren_male","worry")
	await novel_interface.show_dialog("Droga, droga... eu realmente não devia ter jogado aquele jogo...",GameConfig.player_name)
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("Esse botão de 『Próxima rodada』 é mesmo um perigo— aaah, ngh\n！！！？",GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("De repente, algo enganchou meu pescoço e me puxou com força para trás!")
	await novel_interface.show_text_only("Quando estava prestes a perder o equilíbrio, senti a parte de trás da cabeça encostar em algo macio, mas firme.")
	await novel_interface.show_text_only("Quando voltei a mim, já tinha sido arrastado para uma passagem estreita no canto da escada, onde a iluminação era bem mais fraca.")
	await novel_interface.show_dialog("Ugh—!!\nMmm—!!!",GameConfig.player_name)
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/liliu_instPassageHiding.png")
	await novel_interface.show_text_only("Antes que eu pudesse gritar, uma mão tampou minha boca com força, e tudo o que consegui ver de relance foi uma mulher de jaleco branco—")
	await novel_interface.show_text_only("Naquele momento, ela estava encostada na parede, com uma das mãos cobrindo minha boca.")
	await novel_interface.show_text_only("E uma das minhas bochechas estava pressionada contra seu peito... um perfume intenso e envolvente entrava sem parar pelo meu nariz.")
	await novel_interface.show_dialog("(Hã?? É-é enorme!!!! Meu rosto afundou aí!!)",GameConfig.player_name)
	await novel_interface.show_dialog("(O que está acontecendo!? Quem é essa pessoa!?)",GameConfig.player_name)
	await novel_interface.show_dialog("Psiu—! Não faça barulho!", "Mulher de jaleco branco")
	await novel_interface.show_text_only("Embora ela falasse de propósito em voz baixa, havia em suas palavras uma autoridade que não admitia contestação.")
	await novel_interface.show_text_only("Minha cabeça estava um caos, eu sentia que ia sufocar\ne só consegui assentir levemente em sinal de obediência...")
	await novel_interface.show_text_only("Embora minha boca ainda estivesse coberta, a pressão no meu pescoço diminuiu um\npouco.")
	await novel_interface.show_text_only("Forcei o olhar para o que estava mais perto e consegui distinguir, no crachá preso ao jaleco branco sobre o peito dela, uma linha de letras pequenas: cientista-chefe...")
	await novel_interface.show_dialog("(Cientista... ela é funcionária do instituto?)",GameConfig.player_name)
	await novel_interface.show_text_only("Só então percebi que ela não estava olhando para mim; tinha virado a cabeça para o outro\nlado, observando o corredor com total atenção.")
	await novel_interface.show_text_only("Ao longe, pelo corredor, vieram passos apressados e firmes.")
	await novel_interface.show_dialog("Relatório, não há ninguém aqui.", "Voz masculina A")
	await novel_interface.show_dialog("Mas realmente existe um elevador de carga independente. Vou desligá-lo manualmente.", "Voz masculina A")
	await novel_interface.show_dialog("(E a pessoa que passou correndo agora há pouco parecia estar mascarada e segurava uma... arma?)",GameConfig.player_name)
	await novel_interface.show_dialog("Este lugar foi invadido. Se não quiser morrer, não se mexa.", "Mulher de jaleco branco")
	await novel_interface.show_dialog("(In-invadido? O que está acontecendo...)",GameConfig.player_name)
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_stairway.png")
	await novel_interface.show_text_only("No tempo em que fiquei parado em choque, a mulher já tinha saído num salto atrás deles.")
	await novel_interface.show_text_only("Poucos segundos depois, ouvi um baque surdo e um som parecido com ossos se quebrando.")
	await novel_interface.show_text_only("Não houve o som de queda que eu esperava; ela o segurou por trás, arrastou o homem\nmascarado de volta para a passagem e tirou dele uma pistola.")
	await novel_interface.show_dialog("Esse cara é...?!",GameConfig.player_name)
	await novel_interface.show_text_only("A mulher nem me deu atenção; abriu com destreza a porta da sala elétrica ao lado da parede e, erguendo o salto alto, chutou para dentro o brutamontes completamente sem forças.")
	await novel_interface.show_text_only("Mesmo usando camisa branca e saia justa, seus movimentos foram fluidos e incrivelmente precisos.")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("Hm~ Por enquanto, ninguém deve vir por aqui.", "Mulher de jaleco branco")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ela bateu as mãos uma na outra, como se tivesse acabado de se livrar de um lixo grande, e então se virou para mim com tranquilidade.")
	await novel_interface.show_text_only("Meu cérebro já não conseguia processar o que acabara de acontecer; só me restava encará-la, atônito.")
	novel_interface.show_character("ren_male","shy")
	await novel_interface.show_dialog("(Olhando bem, essa moça é linda!)\n(E ainda tem um corpo de modelo...)",GameConfig.player_name)
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("(Mas no crachá preso ao peito dela está escrito claramente: 『cientista』)",GameConfig.player_name)
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("(Então o que aconteceu agora há pouco só pode ter sido uma alucinação, né!)",GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Isso mesmo: naquele instante, não existia nenhum brutamontes mascarado dentro da sala elétrica.")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_Shot_liliu_leg1.png")
	await novel_interface.show_text_only("Convenientemente, tirei essa conclusão e desviei o olhar para as pernas dela...")
	await novel_interface.show_text_only("(Trabalhar com uma mulher dessas deve ser incrível...)\n(Ser pesquisador de Objetos Heterogêneos também parece uma boa carreira.)")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_stairway.png")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("Ei, garoto, onde você acha que está olhando?", "Mulher de jaleco branco")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Enquanto falava, ela retirou o carregador da pistola e conferiu as balas.")
	novel_interface.show_character("ren_male","sob")
	await novel_interface.show_dialog("(Chega de mentir para mim mesmo!!!)",GameConfig.player_name)
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("O-olá\nvocê é...?",GameConfig.player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Bom... pode me chamar de Liliu.\nHoje eu deveria dar uma palestra bem chata", "Liliu")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ela montou a arma de novo com habilidade e a enfiou de volta no bolso do jaleco branco.")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("Mas aquele grupo acabou de tomar o auditório.\nGraças a eles, a palestra foi cancelada~", "Liliu")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_male","shock",0.25)
	await novel_interface.show_dialog("Liliu... Liliu von Braun?!",GameConfig.player_name)
	await novel_interface.show_dialog("V-você não é a palestrante da conferência em que eu precisava pegar o carimbo?!\nE ainda por cima, uma cientista de Classe SS reconhecida pelo Senado!",GameConfig.player_name)
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Hm, aqueles velhotes são fáceis de enganar~", "Liliu")
	await novel_interface.show_dialog("Mas, olhando para você, veio só atrás de créditos, não foi?", "Liliu")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("Ugh... me desculpe mesmo!!",GameConfig.player_name)
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"speak")
	await novel_interface.show_dialog("Não sei se te chamo de azarado ou de idiota: conseguiu achar justamente o elevador que ainda subia durante o bloqueio.", "Liliu")
	await novel_interface.show_dialog("Se eu te deixasse por conta própria, você provavelmente pisaria direto no local do sequestro no auditório.", "Liliu")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Estado de bloqueio...?\nTirei o celular do bolso e, como imaginei, não havia sinal nenhum.")
	await novel_interface.show_text_only("Finalmente entendi por que todos os elevadores do saguão principal estavam parados... então não era que o prédio tivesse fechado!")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Agora até o elevador que você usou já foi bloqueado. Fique quietinho aqui e espere o resgate do Ministério da Defesa.", "Liliu")
	await novel_interface.show_dialog("Eu preciso ir ao auditório ver a situação. Se alguém aparecer, esconda-se.", "Liliu")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_male","shock")
	await novel_interface.show_dialog("M-mas... você vai sozinha...?",GameConfig.player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("Entendeu?!", "Liliu")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_male","shock")
	await novel_interface.show_dialog("Entendi!!",GameConfig.player_name)

	print("=== Chapter 1 Episode 2 End ===")

	# episode end
	await novel_interface.end_story_episode(0.5)
