# chapter1_ep3.gd - 第一章第3話
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter1_ep3_script()

func play_script():
	pass

func chapter1_ep3_script():
	novel_interface.change_music("res://assets/audio/music/Hand-to-hand combat.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_stairway.png")
	novel_interface.show_character("soldier_2")
	await novel_interface.show_dialog("這邊的哨點一直沒有回應，你去那邊檢查一下——", "男性的聲音A")
	await novel_interface.hide_character()
	novel_interface.show_character("soldier_1")
	await novel_interface.show_dialog("是！", "男性的聲音B")
	await novel_interface.hide_character()
	novel_interface.show_character("soldier_2")
	await novel_interface.show_dialog("我去拿心跳檢測儀來，你盯著點！", "男性的聲音A")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_male","worry")
	await novel_interface.show_dialog("糟了，在這裡躲不過的……",GameConfig.player_name)
	await novel_interface.show_dialog("他們的視線沒有死角，根本溜不掉。唯一的機會，就是趁他們分開時先偷襲其中一個。",GameConfig.player_name)
	await novel_interface.show_dialog("大概沒問題吧……\n既然那個女人赤手空拳都能撂倒對方……",GameConfig.player_name)
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("得找個東西作為武器……",GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("走廊的牆壁上掛著一根金屬球棒，底下銘牌的小字上寫著「萊博娜 自由光……」。")
	novel_interface.show_character("ren_male","happy")
	await novel_interface.show_dialog("應該是展品吧……\n只是臨時借用，嗯嗯，臨時借用……",GameConfig.player_name)
	await novel_interface.show_dialog("……\n……",GameConfig.player_name)
	novel_interface.change_expression("shout")
	await novel_interface.show_dialog("那麼……要上了！\n哈——！",GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.play_background_flash_effect(Color.WHITE,3,0.15,1.0,[Color.RED,Color.BLACK],true)
	await novel_interface.show_text_only("咚！！！")
	await novel_interface.show_text_only("我使出全力，一球棒砸向蒙面人的後腦勺，頓時爆出一聲巨響。欸……聲音有這麼大嗎？")
	await novel_interface.show_background("res://assets/images/bg/Shot/BG_RC_stairway.png")
	await novel_interface.show_text_only("但是對方並沒有如我期待的那樣倒下，而是眼中冒著怒火轉過了身。")
	novel_interface.show_character("ren_male","shock")
	await novel_interface.show_dialog("這和遊戲裡不一樣啊！！",GameConfig.player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("soldier_2")
	await novel_interface.show_dialog("什麼人！", "蒙面人A")
	await novel_interface.hide_character()
	await novel_interface.play_background_flash_effect(Color.RED,3,0.15,0.6,[],false)
	await novel_interface.show_text_only("蒙面人猛地揮起槍托朝我撲來，我連忙握緊球棒硬擋了下來。")
	novel_interface.show_character("ren_male","shock")
	await novel_interface.show_dialog("不好——",GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.play_background_flash_effect(Color.BLACK,1,1.0,1.0,[],false)
	await novel_interface.show_text_only("對方壓倒性的力量沿著球棒直衝雙手與肩膀。我還咬牙死撐著，蒙面人卻突然補上一記踢擊。")
	await novel_interface.play_background_flash_effect(Color.BLACK,1,0.15,1.0,[Color.RED],true)  
	await novel_interface.show_text_only("腳狠狠踢在了我毫無防備的腹部。")
	await novel_interface.play_background_flash_effect(Color.WHITE,1,0.15,1.0,[],false)
	novel_interface.show_background("res://assets/images/bg/Baizhu/white_bg.png")
	await novel_interface.show_text_only("被踢中的我飛出並撞斷了護欄，徑直摔到了下一\n層。")
	await novel_interface.play_background_flash_effect(Color.RED,1,0.15,1.0,[Color.BLACK],true)
	await novel_interface.show_text_only("啊！！！！！！")
	novel_interface.show_character("soldier_2")
	await novel_interface.show_dialog("媽的，那個偷襲我的小鬼摔到樓下去了。\n我去宰了他！", "蒙面人A")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_male","hurt")
	await novel_interface.show_dialog("……我得快逃……\n……得藏到…那個展品的…陰影裡去……",GameConfig.player_name)
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Shot/BG_RC_stairway.png")
	novel_interface.show_character("soldier_1")
	await novel_interface.show_dialog("等等……隊長剛傳來消息，自爆式防盜裝置解除成功了。", "蒙面人B")
	await novel_interface.show_dialog("別浪費時間，馬上去會議廳集合！\n等他醒來咱們早就撤了。", "蒙面人B")
	await novel_interface.hide_character()
	novel_interface.show_character("soldier_2")
	await novel_interface.show_dialog("是！", "蒙面人A")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	novel_interface.show_character("ren_male","hurt")
	await novel_interface.show_dialog("意識……漸漸……模糊了\n莉琉……",GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("與此同時，會議廳裡——")
	novel_interface.change_music("res://assets/audio/music/Barrier Maze.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_Shot_liliu_instConfRoomWatching.png")
	await novel_interface.show_dialog("看來這群人是靠光學偽裝混進來的……","莉琉")
	await novel_interface.show_dialog("竟然利用了收容設施部分反光學偵測裝置檢修的空檔……看來內部有人走漏了消息。","莉琉")
	await novel_interface.show_dialog("還不清楚他們到底是什麼來頭……只能先等機會了。","莉琉")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_conferenceRoom.png")
	novel_interface.show_character("soldier_leader")
	await novel_interface.show_dialog("哼哼哼哈哈——","蒙面人首領")
	await novel_interface.show_dialog("我們終於把它取回來了……！", "蒙面人首領")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Shot/BG_Shot_liliu_instConfRoomWatching.png")
	await novel_interface.show_dialog("那是——『洛斯金盃』！？","莉琉")
	novel_interface.change_background("res://assets/images/bg/Shot/losgrail.png")
	await novel_interface.show_text_only("這是考察團在突然出現在太平洋中部的洛斯群島上發現的『異質物』，杯身外側鑲著四顆寶石。")
	await novel_interface.show_text_only("杯中盛著紅色液體狀的物質，但那東西既無法倒出，也無法觸碰，就像幻影一樣，似乎並不存在實體……")
	await novel_interface.show_text_only("研究所那幫老頭子想盡了各種辦法，卻始終搞不明白那到底是什麼東西……")
	await novel_interface.show_text_only("一段時間後就將它的威脅等級降到了『Safe』\n允許進行公開研究了……")
	await novel_interface.show_dialog("嘖，看來也就那幾顆寶石還值點錢了。","莉琉")
	await novel_interface.show_dialog("不過，寶石和杯身在分子層面上早就融為一體了……","莉琉")
	novel_interface.show_character("soldier_leader")
	await novel_interface.show_dialog("那就由我來把它分離開吧——這污穢之物！！", "蒙面人首領")
	novel_interface.character_dark()
	await novel_interface.show_dialog("分離？那種事怎麼可能辦得到——","莉琉")

	print("=== 第一章第3話結束 ===")

	# 調用劇情結束函數
	await novel_interface.end_story_episode(0.5)


