# apocalypse_ep18.gd - 天启篇第18话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第18话剧本
	apocalypse_ep18_script()

func play_script():
	pass

# 天启篇第18话 - 正式剧本
func apocalypse_ep18_script():
	# Scene 1 - 开始
	novel_interface.show_background("res://assets/images/bg/Soya/Parade.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("Мы выходим из здания и обнаруживаем, что наш автомобиль припаркован у входа. Толстяк-водитель протягивает нам два наушника с микрокостной проводимостью.")
	await novel_interface.show_dialog("Босс сказал мне передать это тебе.", "Водитель")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("Би-босс?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Мы с Соней надеваем наушники и слышим, как на другом конце провода говорит Ая.")
	await novel_interface.show_dialog("В толпе слишком шумно. Возможно, ты меня плохо услышишь, если мы поговорим по телефону.", "Ай")
	await novel_interface.show_dialog("Я только что проверил. Из всей согласованной демилитаризованной зоны только в семи районах, где произошли беспорядки, есть желтые уличные фонари.", "Ай")
	await novel_interface.show_dialog("Все это оживленные районы с множеством рекламных щитов и других источников света, поэтому даже те, кто просматривает аэрофотоснимки, не заметят разницы.", "Ай")
	await novel_interface.show_dialog("Мы отправили нашу поисковую команду, но, думаю, мне не удастся убедить вас остаться. Просто береги Рена.", "Ай")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("Остаться в стороне? Хм? Держитесь подальше от чего?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Соня просто кивает на преследующий нас дрон и тащит меня в толпу.")
	
	# Scene 2 - 切换场景
	await novel_interface.hide_background()
	await novel_interface.show_text_only("…")
	novel_interface.show_background("res://assets/images/bg/Soya/Parade.png")
	await novel_interface.show_text_only("Мы приходим под желтый уличный фонарь, который, к счастью, окружен не слишком большим количеством людей. Фонарный столб поднимается почти на двадцать пять футов.")
	await novel_interface.show_text_only("Вернувшись на курсы подготовки в SID, я потерпел полную неудачу в упражнениях по скалолазанию.")
	novel_interface.show_character("ren_fishnet","uneasy")
	await novel_interface.show_dialog("(Получил двойку за все.)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Обычно мне приходилось хвататься за шест в прыжке, чтобы набрать высоту, но в итоге я все равно соскальзывал вниз.")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("Хе-хе...", "Соя")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Соня вытаскивает из сумочки провисшую металлическую коробочку. Он на удивление большой, со сторонами размером со среднюю бумагу для заметок и толщиной около трех дюймов.")
	await novel_interface.show_text_only("По поверхности коробки проходит блестящая серебряная линия, обозначающая вращающийся компонент. А сбоку розовая металлическая полоса.")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("Угадай, что у меня здесь!", "Соя")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("— гордо восклицает Соня, показывая мне коробку.")
	await novel_interface.show_text_only("Хм. Судя по размеру, мастерству изготовления, большому веерообразному вращающемуся компоненту и блестящей металлической полосе…")
	novel_interface.show_character("ren_fishnet","smile")
	await novel_interface.show_dialog("Э-э, какая-то неоправданно огромная видеокарта?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Соня просто тянет защелку на ручке, и розовая полосатая сторона коробки раскрывается, как гармошка.")
	await novel_interface.show_text_only("А изнутри выскакивает ряд черных механических компонентов вместе с длинной «доской». Сложите их все вместе, и он выдвинется почти на сорок дюймов.")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("Какого черта?", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Это оружие эксклюзивно для Рыцарей Правосудия. Работает на веществе H!", "Соя")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Пенитенциарное учреждение сделало это для меня согласно моему желанию.", "Соя")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Соня поворачивает ручку, и вдоль края длинной доски появляется ряд блестящих зубьев пилы.")
	await novel_interface.show_text_only("Ряд зубцов доходит до дуги на конце доски и, наконец, доходит до коробки.")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("Бензопила?", "Лиан")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","normal",0.25)
	await novel_interface.show_dialog("Что-то в этом роде. Однако он не питается от электричества. Это мое любимое оружие!", "Соя")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Соня усмехается и включает «бензопилу». Зубы начинают вращаться с поразительной скоростью, но на удивление бесшумно.")
	
	novel_interface.show_character("ren_fishnet","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("soya_uniform","normal",0.25)
	novel_interface.character_2nd_dark()
	
	await novel_interface.show_dialog("Ты собираешься...", "Лиан")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Не колеблясь, Соня начинает прорезать металлический фонарный столб. Повсюду летят искры, и серебряный столб протестующе визжит.")#多字问题
	await novel_interface.show_text_only("Шум привлекает целую публику. Несколько мужчин средних лет, не имея ни малейшего представления о том, что происходит, начинают кричать и аплодировать.")
	await novel_interface.show_text_only("Очень скоро изнутри столба раздаются два взрыва, и Соня спокойно достает бензопилу.")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Она смотрит на уличный фонарь, который больше не светит. Колонна диаметром около восьми дюймов почти разрезана насквозь.")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("Т...", "Лиан")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("Древесина!", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("Это больше похоже на это!", "Соя")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Соня ухмыляется, ударяя шестом в сторону, противоположную толпе.")
	await novel_interface.show_text_only("И шест наконец поддается, опрокидываясь с оглушительным воплем.")
	await novel_interface.show_text_only("Бум! Фонарный столб врезается в землю, раскалывая смолу и разбрасывая обломки.")
	await novel_interface.show_text_only("Окружающая толпа несколько секунд ошеломлена, затем разражаются бурные аплодисменты.")
	await novel_interface.show_dialog("К свободе!\nК миру!", "Толпа")
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_dialog("Какое это имеет отношение к свободе и темпу?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Мы бежим к тому, что когда-то было верхушкой уличного фонаря. Соня стремительно отсекает часть со светом, а преследующий нас дрон приземляется возле зрелища.")
	await novel_interface.show_dialog("Отсюда я мало что вижу. Избавьтесь от абажура и поднесите лампочку поближе к дрону. Хочу посмотреть светодиодную модель.", "Ай")
	await novel_interface.show_text_only("Чтобы избежать возбужденной толпы, я беру лампочку и мчусь в сторону нашего внедорожника.")#换行问题
	await novel_interface.show_text_only("Как только мы приедем, Соня все это разбирает по указанию Аи. Находим микрокамеру, батарейки, нить накала и электрический балласт.")
	await novel_interface.show_dialog("Серийные номера этих компонентов и светодиодов кажутся в порядке и откровенными.", "Ай")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("Эй...", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я подношу абажур к источнику света, находящемуся где-то снаружи автомобиля.")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Если абажур желтый, лампа не сможет излучать белый свет, верно?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Желтая фактура, покрывающая абажур, кажется сложной, с детальным тиснением. Должно быть, пришлось много потрудиться.")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("Может быть, на этом абажуре спрятано послание? Хотя я не могу сказать...", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Соня тоже поднимает абажур против внешнего света и отрицательно качает головой.")
	await novel_interface.show_dialog("В фургоне есть устройство 3D-сканирования. Поместите абажур внутрь и пришлите мне результаты.", "Ай")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("Ого, у нас на машине есть что-то подобное?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Конечно! Все машины СИД оснащены полным набором автоматизированного вооружения.", "Ай")
	novel_interface.show_character("soya_uniform","yell")
	await novel_interface.show_dialog("Берегись!", "Соя")
	await novel_interface.hide_character()
	
	# Scene 4 - 被攻击场景
	await novel_interface.hide_background()
	novel_interface.change_music("res://assets/audio/music/Hand-to-hand combat.mp3")
	await novel_interface.show_text_only("Зинг!")
	novel_interface.show_background("res://assets/images/bg/Soya/Beingshot.png")
	await novel_interface.show_text_only("Внезапная ослепительная вспышка белого света вырывается из угла и врезается прямо мне в грудь.")
	await novel_interface.show_text_only("На секунду я слышу только резкий визг электричества. Моё сердце перестало биться? Такое ощущение, что так оно и есть.")
	await novel_interface.show_text_only("Когда я падаю назад, кто-то подхватывает меня — вероятно, водитель. С помощью Сони он перетаскивает меня на другую сторону, за фургон.")
	await novel_interface.show_text_only("Семь буйволов в черных специальных боевых костюмах бросаются на нас с автоматами...")
	await novel_interface.show_text_only("Все вокруг словно окутано дымкой, как будто кто-то надел ужасный фильтр. Но мой мозг остается бдительным, почти необычайно. Как будто я вижу, что происходит в замедленной съемке.")
	await novel_interface.show_text_only("Вот Соня и Ая выкрикивают мое имя. Но я не слышу их отчетливо. Между нами будто стена...")
	await novel_interface.show_text_only("Водитель ловко вытаскивает из багажника дробовик, одной рукой заряжает его и начинает стрелять по нашим нападавшим, прикрываясь пуленепробиваемой дверью машины.")
	await novel_interface.show_text_only("Так что этот пухлый чувак на самом деле настоящий задира, да...")
	await novel_interface.show_text_only("Жаль, что у них численное преимущество и они хорошо обучены. У них отличное оружие, и по тому, как они атакуют, очевидно, что они не планируют позволить нам уйти живыми. Даже не Соня, маленькая девочка...")
	await novel_interface.show_text_only("Последнее, что я помню перед тем, как мое сознание исчезло, — это как Соня сжала мою руку, а затем подняла бензопилу…")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Далее следует серия испуганных животных криков умирающих людей.")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…")
	
	# Scene 5 - 瑟蕾莎场景
	novel_interface.change_background("res://assets/images/bg/Soya/Backstreet.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("<Примерно в тысяче футов от Первой авеню>")
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("Тск...", "Тереза")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Тереза ловко вырезает черный кусок ткани из экипировки мертвого солдата на земле, одновременно лениво говоря в гарнитуру.")
	novel_interface.show_character("cereza","normal")
	await novel_interface.show_dialog("Неужели эти ребята действительно просто резервная команда?\nКонечно, они потратили много денег на свое оборудование.", "Тереза")
	await novel_interface.show_dialog("А? Оставить их в живых?", "Тереза")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("... Упс!", "Тереза")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Тереза хлопает себя по голове.")
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("Я забыл, что должен был оставить их в живых...", "Тереза")
	await novel_interface.show_dialog("Да ладно, это не моя вина! Их мозги внезапно взорвались. Меня застали врасплох, и я убил их всех.", "Тереза")
	novel_interface.change_expression("boring")
	await novel_interface.show_dialog("К тому же, даже если я верну их живыми, вряд ли мы сможем узнать от этих чуваков что-то интересное, верно?", "Тереза")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Сжигать все отпечатки пальцев... динамитные имплантаты в зубах... как только они оказываются на грани смерти, срабатывает механизм и взрывается все лицо...", "Тереза")
	novel_interface.change_expression("blink")
	await novel_interface.show_dialog("... Да! Видеть? Это не моя вина!", "Тереза")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Соня жалуется кому бы то ни было на другом конце разговора.")
	novel_interface.show_character("cereza","speek")
	await novel_interface.show_dialog("Я собирался оставить этих парней в живых! Я просто ударил их своим клинком... Я хотел дать им возможность оценить мои крутые приемы...", "Тереза")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("А потом они просто взорвались!", "Тереза")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Она вздыхает, очищая лезвие отрезанной тканью, затем бросает грязную тряпку на лицо трупа — если его вообще можно назвать лицом.")
	novel_interface.show_character("cereza","wordless")
	await novel_interface.show_dialog("Куча неудачников.", "Тереза")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Тереза кладет свою блестящую катану обратно в ножны.")
	novel_interface.show_character("cereza","normal")
	await novel_interface.show_dialog("Откуда-то из переулка появились две бригады скорой помощи. Нет номерного знака. Их было больше дюжины, так что я не смог взять их всех сразу...", "Тереза")
	await novel_interface.show_dialog("Но им троим удалось уйти от нападавших, да? Этот водитель должен быть опытным.", "Тереза")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("Подожди, что?", "Тереза")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Тереза прижимает наушник ближе к уху, как будто это изменит то, что она услышала.")
	novel_interface.show_character("cereza","uneasy")
	await novel_interface.show_dialog("Нападавшие... все уничтожены?", "Тереза")
	await novel_interface.show_dialog("И их кровь брызнула так высоко, что достигла пятого этажа соседнего офисного здания?", "Тереза")#多符号
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Было ли это...", "Тереза")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Тереза ​​делает паузу, ожидая подтверждения с другой стороны.")
	novel_interface.show_character("cereza","normal")
	await novel_interface.show_dialog("Ах да, я знал, что это она сделала! Когда я встретил ее сегодня, я тоже это почувствовал.", "Тереза")
	novel_interface.change_expression("blink")
	await novel_interface.show_dialog("Ха-ха-ха...", "Тереза")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Тереза сонно зевает.")
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("Ты должен перестать меня постоянно будить так рано. Я просто хочу вернуться в свою кровать.", "Тереза")
	await novel_interface.show_dialog("В любом случае, у вас есть вся необходимая информация, верно?", "Тереза")
	await novel_interface.hide_character()
	
	# Scene 6 - 莉琉与伦伯特对话
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("С другой стороны доносится уверенный женский голос.")
	await novel_interface.show_dialog("Да, у меня есть все, что мне нужно для победы в этих переговорах.", "Женский голос")
	novel_interface.show_background("res://assets/images/bg/Soya/Underground_Hall.png")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("У Сони браслет на щиколотке прослушивается. Я слышал все, что она сказала Рену. И это, плюс то, что вы нашли...", "Мариру")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Мариру смотрит на выцветшую фотографию в своей руке, расхаживая по закрытому подвалу.")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("Молодец, Тереза.", "Мариру")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("Или лучше сказать... Мачида Ринко?", "Мариру")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Тереза лишь криво смеется и кладет трубку.")
	await novel_interface.show_text_only("Спустя несколько секунд открывается одна из двух черных дверей лифта, ведущих в подвал. Выходит мужчина в безупречном костюме.")
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("Какой впечатляющий дизайн...", "Ламберт")
	novel_interface.change_expression("sedation")
	await novel_interface.show_dialog("Два лифта, расположенные на разных улицах, в двух зданиях впритык. Однако они ведут в один и тот же потайной подвал.", "Ламберт")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("Привет, сэр Ламберт.\nВидишь ли, обе наши личности... деликатны, поэтому нам приходится встречаться тайно.", "Мариру")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Разве вы не говорили два дня назад по телевидению, что хотите поговорить со мной публично?", "Мариру")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("Думаю, в этом больше нет необходимости.", "Ламберт")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ламберт указывает на выцветшую фотографию в руке Мариру.")
	novel_interface.show_character("lambert","smile")
	await novel_interface.show_dialog("Теперь скажи мне. Как много ты знаешь?", "Ламберт")
	await novel_interface.hide_character()
	
	# Scene 7 - 小怜醒来
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("Я не могу сказать, сколько времени прошло, пока я медленно восстанавливаю чувствительность конечностей. Я слышу грохот автомобиля... я на машине?")
	await novel_interface.show_text_only("Чья-то рука нежно гладит меня по лбу. Чувствуешь себя как дома.")
	await novel_interface.show_dialog("Рен...", "Соя")
	novel_interface.show_background("res://assets/images/bg/Soya/Wakingup.png")
	await novel_interface.show_text_only("Я заставляю себя открыть глаза, хотя все по-прежнему размыто.")
	await novel_interface.show_dialog("Рен—", "Соя")
	await novel_interface.show_dialog("Ты проснулся?", "Соя")
	await novel_interface.show_text_only("Соня кажется взволнованной. Это те слезы, которые я вижу в ее глазах?")
	await novel_interface.show_dialog("Что случилось...?", "Лиан")
	await novel_interface.show_dialog("Урх...", "Лиан")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Я чувствую что-то твердое во рту. Что-то, чего там не должно быть. Я рефлекторно выплевываю это.")
	novel_interface.show_background("res://assets/images/bg/Soya/Backseat.png")
	await novel_interface.show_text_only("Я протираю глаза и оказываюсь на заднем сиденье нашего внедорожника. Что я только что выплюнул? Я смотрю на свою руку.")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Что…", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Это прозрачный драгоценный камень размером с мрамор. Выглядит точно так же, как тот, который дала мне Рафилия, только цвет потускнел.")
	await novel_interface.show_dialog("Вау! Уже встал?", "Водитель")
	await novel_interface.show_dialog("Оставайся на месте, не двигайся! Мы действительно думали, что потеряли тебя там. Понятия не имею, как мы собираемся сказать боссу.", "Водитель")
	await novel_interface.show_dialog("И не волнуйся, мы скоро доберемся до больницы.", "Водитель")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Больница?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я изо всех сил стараюсь вспомнить, что именно произошло. На нас напали, не так ли? И тогда...")
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("Ты в порядке? Болит ли где-нибудь?", "Соя")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("— спрашивает Соня, крепко хватая меня за руку. Ее голос звучит необычно обеспокоенно.")
	await novel_interface.show_text_only("Она щелкает пальцами по моим ушам, чтобы убедиться, что я все еще слышу, затем просит меня сосредоточиться на ее пальце, который затем рисует круг, чтобы проверить работу моих глаз.")
	await novel_interface.show_text_only("Я ощупываю себя и решаю, что на самом деле нигде особо не болит.")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Меня... ударила молния?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ух, это было электрическое оружие. Это было удачей. Я так волновалась.", "Ай")
	await novel_interface.show_text_only("Я слышу выдох Аи из наушника.")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("Счастливчик?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("О, ты не знаешь?", "Ай")
	await novel_interface.show_dialog("Весь наряд, который вы носите сегодня... платье, чулки и туфли... они сделаны из композитных материалов с проводящим углеродным волокном.", "Ай")
	await novel_interface.show_dialog("Это было сделано для того, чтобы ты не был случайно шокирован этим браслетом…", "Ай")
	await novel_interface.show_text_only("Подождите, так эти чулки в сеточку, которые постоянно падают, на самом деле действительно ценны?")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("(Разве они не могли сделать это так, чтобы оно выглядело менее смущающе?)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Когда вы попали под эту дугу, ваше оборудование само сформировало клетку Фарадея и отвело большую часть энергии от вас.", "Ай")
	await novel_interface.show_dialog("Тем не менее, это оружие было довольно мощным, и снаряжение не могло поглотить его целиком. Вот почему тебя все равно нокаутировали.", "Ай")
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("Вот так и следует использовать драгоценный камень Рафилии... к счастью, я не заставил тебя его проглотить.", "Соя")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("П-подожди, что ты сделал со мной, когда я был без сознания?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я понятия не имею, что такое клетка Фарадея, но... спасибо, Фарадей, брат мой!")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("Кто вообще были эти парни?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я смотрю на заднее стекло и замечаю, что оно забрызгано кровью.")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("Что, черт возьми, происходит?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Неловкое молчание. Затем водитель наконец заговорил.")
	await novel_interface.show_dialog("С тобой все в порядке, это главное.", "Водитель")
	await novel_interface.show_dialog("Ах да. Разве результаты сканирования уже не известны?", "Водитель")
	await novel_interface.show_dialog("Я уже отправил их на телефон Рена. Однако требуется дополнительный анализ.", "Ай")
	novel_interface.change_background("res://assets/images/bg/Soya/Ripple.png")
	await novel_interface.show_text_only("Я тут же разблокирую телефон и вижу странное изображение...")
	await novel_interface.show_dialog("Что…", "Лиан")
	await novel_interface.show_text_only("В трехмерном пространстве бесчисленные крошечные кубики сплетены в перекрученные формы. Кажется, они несут в себе огромное количество информации...")
	await novel_interface.show_text_only("Соня тоже наклоняется, чтобы посмотреть.")
	await novel_interface.show_dialog("Похоже на 3D картину.", "Соя")
	novel_interface.change_background("res://assets/images/bg/Soya/Backseat.png")
	await novel_interface.show_dialog("Картина...", "Ай")
	await novel_interface.show_dialog("Ах! Я должен был знать!", "Ай")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Я пытался проанализировать эти кривые с помощью математики...", "Ай")
	await novel_interface.show_dialog("Но что, если вместо этого я буду рассматривать каждый куб как пиксель...?", "Ай")
	await novel_interface.show_text_only("После шквала движений со стороны Аи мы вскоре получаем другое изображение.")
	novel_interface.change_background("res://assets/images/bg/Soya/Solomon2.png")
	await novel_interface.show_dialog("Что это?", "Лиан")
	await novel_interface.show_text_only("Царь Соломон и царица Савская. Точно так же, как резьба, которую я видел на церковной двери...")
	await novel_interface.show_dialog("Итак... Эльгана...", "Лиан")
	await novel_interface.show_text_only("Мы с Соней переглядываемся и одновременно киваем.")
	print("=== 天启篇第18话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
