# apocalypse_ep15.gd - 天启篇第15话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第15话剧本
	apocalypse_ep15_script()

func play_script():
	pass

# 天启篇第15话 - 正式剧本
func apocalypse_ep15_script():
	# 开场设置
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N_Door.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("ああ、マザー……", "ソヤ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ソヤはエルガノを見た途端に大人しくなって、\n俺の服を掴んでいた両手をサッと引き戻した。")
	novel_interface.show_character("el","normal")
	await novel_interface.show_dialog("エンジェルス、先ほど郵便物が届いていました。\n西院のあなたのお部屋に置いてあります。", "エルガナ")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("はい～～", "ソヤ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("エルガノの威厳がこもっている言葉に対し、\nソヤはわざと語尾を伸ばして返事をする。")
	await novel_interface.show_text_only("担任の先生の前でわざと良い子のフリをする\n小学生のようだ。")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("……マザー？", "レン")
	await novel_interface.hide_character()
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("その呼び方、レンさんには馴染みがありません\nでしょうか？\nでしたらエルガノとお呼びいただいて結構です。", "エルガナ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("は、初めまして……エルガノさん。", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ヨーロッパの古い映画を思い出した。\n\n修道院のマザーは先生や寮の監督官みたいな\n役割なのだろう。")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("腰を痛めたとお聞きしましたが。", "エルガナ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("はい、うっかりして……", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("うっかり体重100キロの子供にやられて\nしまいました。")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("どうぞ、中へお入りください。\nすぐお薬を用意いたしますわね。", "エルガナ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("エルガノは慈愛に満ち溢れた笑みを俺に向けた。\n\nさっきソヤと話していた時の雰囲気と全然違う。")
	novel_interface.show_character("ren_fishnet","uneasy")
	await novel_interface.show_dialog("（ソヤの奴、小さい頃からトラブルメーカー\n　だったんだろうか……）", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("エルガノは教会の分厚い扉を押し開き、\n俺は後ろに付いて行く。")
	novel_interface.show_character("ren_fishnet","happy")
	await novel_interface.show_dialog("すっごく凝ってる彫刻ですね──", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("近くで見ると、扉の左右には四角い金属製の\nレリーフが5つずつ象られている事が分かった。\nそれぞれが1つの物語を表しているようだ。")
	novel_interface.show_character("el","normal")
	await novel_interface.show_dialog("これはギベルティのレリーフの複製品ですわ。\n\nオリジナルは戦争中に破壊されてしまいまして、\nもう見る事は叶いませんが……", "エルガナ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("エルガノの表情は少し悲しそうだった。\n彼女の好きな芸術家の作品だったのだろうか。")
	novel_interface.change_background("res://assets/images/bg/Soya/Solomon.png")
	await novel_interface.show_text_only("ギベルティが何者かなんて知らないけど、\nその彫刻の1つに俺は見惚れていた。")
	await novel_interface.show_dialog("こちらのレリーフはシバの女王とソロモン王の\n伝説を体現しておりますわ。", "エルガナ")
	await novel_interface.show_dialog("先代の教皇様は新築した教会の全てに、\n歴史的な芸術作品の要素を追加するようにと、\nそう仰っておりました。", "エルガナ")
	await novel_interface.show_dialog("輝かしき人類の文明を、我々の戦争によって\n抹殺してはならないと……\n人々に忠告したかったのかもしれません。", "エルガナ")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N_Door.png")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("……素晴らしい人、だったんですね。", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("マリルによると、その先代の教皇様がソヤに\n『審判騎士』の資格を与えたらしい。")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("んっ？　ソヤは来ないのか？", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ソヤは足を進めず、俺達が中へ入るのを静かに\n見送ろうとしている。")
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("わたくしは結構です……", "ソヤ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("柔らかい光が立ち尽くすソヤの顔を照らす。\n\n初めて会った時みたいな落ち着いた表情を\n彼女はしていた。")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("──？", "レン")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("とにかく、ちゃんと治療を受けてくださいまし。\nそんなに時間はかからないはずですの──\n先に裏庭に行って待ってますわね？", "ソヤ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ソヤはそう告げると、教会西側の廊下に向かって\n急いで駆けて行った。")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("（そんな事を言って……）\n\n（本当は早く郵便物を開けたいだけじゃ……？）", "レン")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("とりあえずソヤの妙な動きは後回しにして、\n俺はエルガノと教会の中へと入る。")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_L.png")
	novel_interface.show_character("ren_fishnet","happy")
	await novel_interface.show_dialog("広ぉッ――――！！", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("両側には雄大な石柱、迫力のあるドーム天井、\n生まれて初めての教会に俺は驚きが止まらない。")
	await novel_interface.show_text_only("天井は宗教壁画で埋め尽くされ、遠くにある\nステンドグラスは光で神々しく映っている。")
	await novel_interface.show_text_only("後ろのベンチに木製の薬箱が置いてあった。\nわざわざ用意してくれたのだろう。")
	novel_interface.show_character("ren_fishnet","happy")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("el","smile",0.25)
	await novel_interface.show_dialog("では、拝見させていただきます。", "エルガナ")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("それを聞いた矢先、1つの問題に気付いた──")
	novel_interface.show_character("ren_fishnet","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("el","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（今着ているこのワンピース、腰の後ろを\n　見せるには……）", "レン")
	await novel_interface.show_dialog("（後ろから丸々めくり上げるしかない！？）", "レン")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("あ、じ、実は、大した怪我でもなくて～～", "レン")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("腰の怪我は油断なりません。\n\n適切な処置をせず、病根となってしまってから\nでは遅いのです。", "エルガナ")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("う…………", "レン")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("こら！\nいい子なんですから、言う事をお聞きになって！", "エルガナ")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("エルガノは親のように不満と心配を露にして、\n問答無用で抵抗を封じてきた。\nマットを敷いたベンチに俺は押さえ付けられる。")
	await novel_interface.show_text_only("俺はおずおずとうつ伏せになった。\n\n上半身を腕で支えずに持ち上げようとすると、\n腰が非常に痛む事に気付いた。")
	await novel_interface.show_text_only("彼女が俺のワンピースをめくるので、\n手で網タイツの下のパンツを隠そうと試みる。")
	await novel_interface.show_dialog("恥ずかしがる事はございませんわ。\nうさぎの模様が可愛いらしいですわね？", "エルガナ")
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("あああ、こいつはただのゲームのグッズです！！\nグッズ！！！", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("失敗した──\n\nとあるFPSゲームで、機動装甲を操縦する\n自爆が特徴的なキャラクターのパンツを、\n今日は穿いているって事をすっかり忘れていた。")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("（お尻が……お尻がひんやりするよぉ……）", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("暴れてはいけませんよ。\n……ええと、ここでしょうか？", "エルガナ")
	await novel_interface.show_text_only("エルガノは患部をすぐに見つけて押さえる。\n激しい痛みが全ての羞恥心を塗りつぶした。")
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_dialog("あいたたたたたた――――ッ！！", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("彼女は薬箱から瓶を取り出す。\n\n薬草の匂いを放つ、どろどろとした軟膏を\n俺の背中に塗って軽くマッサージをしてくれた。")
	await novel_interface.show_text_only("スーっと痺れた感覚が腰から伝わってくる。")
	await novel_interface.show_dialog("もうすぐ終わりますから、\n動かないでくださいねーー……", "エルガナ")
	await novel_interface.show_text_only("俺は猫のように大人しく寝そべって、\n微動だにしないようしている。")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("ソヤから聞いたんですけど、エルガノさんが\n自ら調合した薬なんですよね？", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("わたくしの故郷にある薬草で、調合は小さい頃に\n母から教わりましたの。", "エルガナ")
	await novel_interface.show_dialog("どうでしょうか？ 少しは楽になりましたか？", "エルガナ")
	await novel_interface.show_text_only("彼女の声は柔らかく、まるで子守唄のようだ。")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("はい……", "レン")
	await novel_interface.show_dialog("ここはエルガノさんが1人で管理して\nいるんですか？", "レン")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("el","smile",0.25)
	await novel_interface.show_dialog("神父様がいらっしゃるはずだったのですが、\n神職に勤める方々の不足によって、\n先んじてわたくしだけが転任いたしました。", "エルガナ")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("しかし、1人でも大丈夫でございます……", "エルガナ")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("数年前の苦難が続いた時期──\n\n修道院を維持するため東奔西走、説法などをして\n皆様からお布施をいただいておりました……\nあの時期に比べますと、今の環境はとても\n恵まれておりますから。", "エルガナ")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("優しい声ながらも、どんな困難にも立ち向かう\nという意思が見え、何だか安心感を覚えた。")
	novel_interface.show_character("ren_fishnet","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_dark(0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("el","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("ソヤは小さい頃、エルガノさんの修道院に\nいたんですよね……？", "レン")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("ソヤの名前を聞くと、彼女は軽く溜め息を\n吐いた──")
	novel_interface.show_character("ren_fishnet","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_dark()
	novel_interface.show_2nd_character("el","normal",0.25)
	novel_interface.character_2nd_dark(0)
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("あの子がポトシから送られてきた時は、\nまだ3歳にも満たなかったのに……\n誰1人として家族はいませんでした……", "エルガナ")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("しかし彼女は聡明で、何に対しても好奇心を\n持っておりましてね。\n修道院の子供の中では一番のいたずらっ子\nでしたの。", "エルガナ")
	await novel_interface.show_dialog("授業の時、他のシスターに変な質問を色々と\n聞いて困らせておりましたわ。\nそのたびにわたくしはシスター達を慰めなければ\nならなくて……まったく……", "エルガナ")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("思い出を語るエルガノの声には、\n確かな愛おしさが宿っている。")
	novel_interface.show_character("ren_fishnet","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_dark(0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("el","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("でも彼女は、少しエルガノさんを恐れていた\nような……", "レン")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("エルガノはしばらく沈黙すると、俺に質問を\n投げかけてきた。")
	novel_interface.show_character("ren_fishnet","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_dark()
	novel_interface.show_2nd_character("el","normal",0.25)
	novel_interface.character_2nd_dark(0)
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("レンさんは、全ての人が物事に対して\n全く同じ事を感じていると思いますか？", "エルガナ")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……それは違います……よね。", "レン")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("きっと、あの子の好奇心は特別なのでしょうね。\n\n興味を感じた物に対して陶酔し、根掘り葉掘り\nどこまでも聞いてしまう……", "エルガナ")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("ベンチにうつ伏せのままで俺は静かに頷いた。\nまったく同感だ。")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("あの子は普通の人と、見ている世界が違うのかも\nしれません……", "エルガナ")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("かつて子供でさえ自らの身を守らなければ\nならなかった激動の情勢。\nそんな中でもあの子は、両手を広げて未知なる\n物事を迎え入れていました。", "エルガナ")
	await novel_interface.show_dialog("その性格がため、特別な生徒として早くから\n信理部に監視され育てられましてね……", "エルガナ")
	await novel_interface.show_dialog("好奇心のせいか、あの子は危険な事を\nたくさん試しました。\n自分がいくら傷つこうが一切構わずに……", "エルガナ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("エルガノの言葉から俺は不穏な空気を感じ取る。")
	novel_interface.show_character("ren_fishnet","normal1")
	await novel_interface.show_dialog("彼女に……何が起きたんですか？", "レン")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.show_character("el","sad")
	await novel_interface.show_dialog("数年前、非常に重要かつ危険な任務が\nございました。", "エルガナ")
	await novel_interface.show_dialog("当時の詳細は分かりませんが、黒衣の修道士は\n誰1人として引き受けようとしなかったのに、\n彼女は自ら名乗り出たと……", "エルガナ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","normal1")
	await novel_interface.show_dialog("（まさか、マリルが言っていたヤツか……）", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("エルガノの声は少し震えていた。")
	novel_interface.show_character("el","sad")
	await novel_interface.show_dialog("その任務は完遂したのですが……\n\n得体の知れない異質物に、彼女の身体は\n侵されてしまったのです……", "エルガナ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","serious")
	await novel_interface.show_dialog("なんだって！？", "レン")
	await novel_interface.hide_character()
	novel_interface.show_character("el","normal")
	await novel_interface.show_dialog("そうですか。\nあの子はあなたに伝えていませんでしたか……", "エルガナ")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Toxin.png")
	await novel_interface.show_dialog("あの黒い物質は科学成分として測定不能であり、\nガン細胞のように身体を少しずつ蝕んでいます。", "エルガナ")
	await novel_interface.show_dialog("先代の教皇様があの子に対して、あんなにも早く\n真理の印を授けたのも、\nあらゆるお医者様が成人まで生き延びる事が\nできないと判断を下したから……", "エルガナ")
	await novel_interface.show_dialog("さらに彼女は教会や修道院などの神聖な場所に\n身体を晒してしまうと、\n全身に激痛が走るようにもなってしまいました。", "エルガナ")
	await novel_interface.show_dialog("異質物と言うより1種の『悪意』のような\n存在なのです。\nそれはまるで神が咎を背負わせるが如く……", "エルガナ")
	await novel_interface.show_dialog("……結果、あの子は「神に見放された子」と\nなりました。", "エルガナ")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_L.png")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("…………", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("結構です……と言ったソヤの寂しそうな顔を\n思い出すと、言葉が見つからない。")
	await novel_interface.show_text_only("彼女は修道院に引き取られた孤児だ。\n\nだったら……第2の故郷すらも追い出された\nようなもんじゃないか……")
	await novel_interface.show_text_only("だから証拠は自分の身体の中にあるって\nマリルに言ってたのか……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("それにあんな事も言っていた──")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("ですが、もう少しレンさんと遊びたいですの。", "ソヤ")
	await novel_interface.show_dialog("明日のお昼12時までには、レンさんと一緒に\n帰還しますわ。", "ソヤ")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_dialog("あのバカ……ッ！", "レン")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_L.png")
	await novel_interface.show_text_only("俺は身を翻してベンチから起き上がった。\n痛みは和らいでいるが、完治したわけではない。")
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_dialog("痛っーー！", "レン")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("el","smile",0.25)
	await novel_interface.show_dialog("痛むのですね？ まだ動かれては……", "エルガナ")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("俺は歯を食いしばって服を着て、\n教会西側の廊下に繋がる扉に向かって走った。")
	await novel_interface.hide_background()
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("暗号化回線の通話で、マリルは現在唯一連絡が\n可能な元老院メンバーへと繋げた。")
	novel_interface.show_background("res://assets/images/bg/SID/spConferenceRoom.png")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("──マリル？ 私に何か用事か？\n彼らはまだ閉鎖会議の途中だが……", "ブライト")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("呼び出されると思ってなかった様子のブライトは\n喋りながら何かを咀嚼しているようだ。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("（このゴリラ……）", "マリル")
	await novel_interface.show_dialog("ゴホン──ブライト博士。\n\n今、中央通りで起きている暴動が制御不能に\nなりそうな事をご存知ですか？", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("大丈夫だ。\nパランティアの傭兵がいるではないか。\n\n暴動なんぞ毎年の恒例行事で、今回もせいぜい\n何人かが死ぬ程度だろう。", "ブライト")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("このような結果が明白な事柄に対して、\n彼は興味を示さない。")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("いや待て、君が連絡してくるという事は……\nもしや『ミーム』による影響を発見したのか？", "ブライト")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("まだ直接の証拠はありませんがミーム類異質物に\n関して伺いたい事が幾つかあります。", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("なんだ、まだ見つかっていないのか。\nでは後にしてくれないか？ \nまだいくつか残っている会議があってな……", "ブライト")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("ブライト博士！！", "マリル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("マリルはブライドのいつも通りの態度に\n苛立っている。\nしかし彼がミーム類異質物における研究分野で、\n高い見識を持っている事は認めざるを得ない。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("『キャベンディッシュバナナ』を\n少し手に入れました──", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("ほう？ どうやって？\nとうの昔に絶滅したものだと思っていたが。", "ブライト")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("サモントンの無菌温室で新しく育種した\n果実のサンプルです。\n1つの質問に答えていただければ、\nすぐにお宅に届けるよう手配いたしましょう。", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("フハハ、いいだろう……何を聞きたいのだ？", "ブライト")
	await novel_interface.show_dialog("だが、私が答える質問は1つだけだ。\n良く考えてから話したまえよ。", "ブライト")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("彼がそういうと思って、用意していた質問を\nマリルは単刀直入に投げかけた。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("ミーム類異質物は「異常を引き起こす情報」と\n通常は定義・周知されております。", "マリル")
	await novel_interface.show_dialog("この観点に対し、あなたは公の場で幾度も\n軽蔑的な態度を示しております。\nしかし反証する論文はというと、\n一度も発表していません。", "マリル")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("反証する理論を…是非とも説明していただければ\n幸いです。", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("真っ当に情報収集をしているようだな。\n\n君はあのようなくだらない学術会議なぞに\n関心は持っていないと思っていたが……", "ブライト")
	await novel_interface.show_dialog("語りうるものは全て明晰に語り、語りえぬものに\nついては沈黙しなければならない。", "ブライト")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("ウィトゲンシュタインの名言ですか……\n\n言語を超えた場所に答えはあると言いたい\nのでしょうか？\n……それでは回答になっておりませんが。", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("『ミーム』はこの世界の基礎的メカニズムを\n変える事ができる。\n切り詰めて上位の存在を表現するなら「言語」", "ブライト")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Meme.png")
	await novel_interface.show_dialog("別に異質物の特性を持たない『ミーム』でも──\n\n我々の言語や文化、基礎的な認知すら簡単に\n変えられる事を、君も知っているはずだ。", "ブライト")
	await novel_interface.show_dialog("最初はネットで流行した断片に過ぎないが、\n拡散されるにつれて、\n本来含まない意味までもが付属されてしまう。", "ブライト")
	await novel_interface.show_dialog("最終的に新しい意味が本来の意味を完全に\n上書きして、新たな基礎的メカニズムとなる。", "ブライト")
	await novel_interface.show_dialog("ミームは我々が情報を解釈するインタプリタさえ\n簡単に歪ませる事ができると言うのだ。\n単なる「異常を引き起こす情報」と\n結論を出してしまうのは、おかしくはないかね？", "ブライト")#多字问题
	novel_interface.change_background("res://assets/images/bg/SID/spConferenceRoom.png")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("それだけであれば、変えられた概念を受け入れる\nだけで済む話です。\n言語は現在に至るまでそのように進化して来た\nではありませんか？", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("異質物は常識を超えた物理現象を引き起こせるが\nつまりは物理現象に過ぎない。\nでなければ科学の枠組みで研究などは\n不可能だろう。", "ブライト")
	await novel_interface.show_dialog("ミーム類異質物はな、その物理的要因と同様の\n原理で概念の入れ替えを行う事ができるのだ。\n通常のミームでは困難な事柄でも然り、\nしかも人間の脳に作用するだけに留まらない。", "ブライト")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("それはもちろん承知しています。\n『イージス』もミーム類異質物の一種ですから。\nコンピューターのプログラムを作動するだけで\n絶対的な物理防壁を生み出せるなどは本来……", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("あれは質量やベクトル、エネルギーなどの\n物理概念を入れ替えた結果だ。", "ブライト")
	await novel_interface.show_dialog("例えば強大なミームが1つ、世界中の「赤色」と\n「緑色」の概念を入れ替えたとしたら？", "ブライト")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("呼び方だけを入れ替えても、本質自体が\n変わらなければ、\nそれほど影響は起きないと思いますが……", "マリル")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("……待ってください。例えば「0」と「1」の\n概念が入れ替わったとしたら、\n一瞬で全世界のコンピューター設備は麻痺する\n結果に……", "マリル")
	await novel_interface.show_dialog("それは……\n世界の終末のような災いにも繋がる──", "マリル")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("そうだ、ミームの拡散において情報は単なる形に\n過ぎない。\n情報の概念ではなく、最終的に概念そのものを\n入れ替えられるのさ。", "ブライト")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ブライトは溜め息を吐いた。")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("歴史上で異質物の存在を隠す事に尽力した\n機関があったな。\nそうしなければ、人類という脆弱な種族を\n守る事ができないと彼らは考えていた。", "ブライト")
	await novel_interface.show_dialog("何千年も紆余曲折を経て人類が手に入れた\n理性と秩序が、\n不条理な存在に揺るがされるわけには\nいかないとな。", "ブライト")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Spy1.png")
	await novel_interface.show_dialog("さらにミーム類異質物の拡散を制御するための\nエリートチームまで設立された。", "ブライト")
	await novel_interface.show_dialog("今の連合議会にも担当する部門があるはずです。\n\nこの前あなたに頭を下げていましたね……\n主任になって欲しいと。", "マリル")
	await novel_interface.show_dialog("ふっはっは……あの馬鹿どもはミーム類異質物が\n世界に浸透して、\n約3%の基礎的メカニズムを変えただけと\n思っているからな。", "ブライト")
	await novel_interface.show_dialog("では……実際はどうなんでしょうか？", "マリル")
	await novel_interface.show_dialog("言うにも容易いッ！\n\nとっくに我々の世界は完膚なきまで侵されて\nいるのだよ！\nミーム類異質物によってな！！", "ブライト")
	await novel_interface.show_dialog("あの連中が言う「エリート」達が\n多大なる犠牲を払って最終的に出した結論は、\n完全に機関全体を崩壊させた！", "ブライト")#换行问题
	await novel_interface.hide_background()
	await novel_interface.show_text_only("そう叫ぶとブライドが少しの沈黙を挟む。\n\nここまでの話を聞きマリルも、さすがに動揺を\n隠せない。")
	novel_interface.show_background("res://assets/images/bg/Soya/Spy2.png")
	await novel_interface.show_dialog("ミーム類異質物の浸透率はすでに──\n\n「2000%」を超えている。", "ブライト")
	await novel_interface.show_dialog("──ッ！！", "マリル")
	await novel_interface.show_dialog("……まるで細菌だ。\n\nより強いミームがかつての勝者を上書きして、\nさらに強いミームが上書き、その繰り返し……", "ブライト")
	await novel_interface.show_dialog("世界を最初の状態に戻すのは、とうの昔より\n不可能なのだよ。", "ブライト")
	novel_interface.change_background("res://assets/images/bg/SID/spConferenceRoom.png")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("光、音、文字、画像、コード、全てがミーム類\n異質物の拡散ルートになる可能性がある。", "ブライト")
	await novel_interface.show_dialog("あの連合議会の機関など取り繕った見せかけさ。\n実際は彼ら自身もミームを使っている。", "ブライト")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("何だと！？", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("『新回転ドア計画』において……\n\n学園都市の呼称をこんなにも早く、全世界に\n受け入れさせた方法を君は説明できるか？", "ブライト")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("──マリルは身震いする。")
	await novel_interface.show_text_only("これは恐怖なのか？\n\n否、それ以上にあるのは興奮だ。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("なるほど、分かりました……", "マリル")
	await novel_interface.show_dialog("ミーム類異質物に感染した人間が、感覚を酷く\n歪められたとしても、本人は異常を感じない。", "マリル")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("自己判断で説明できない事を容認し兼ねるが、\n受動的な状況においては合理化を図ってしまう。", "マリル")
	await novel_interface.show_dialog("……私の言葉は、間違っていますか？", "マリル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("マリルは口角が上がるのを抑えきれなくなった。")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("──新豊洲記念教会西院。")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N_Backyard.png")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("あのバカ……", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("教会の脇のドアから飛び出した瞬間、\n急に息が苦しくなった。")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("（さっきの治療の副作用か？）\n\n（いや違う、この感覚は……）", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("数秒間の時が止まったかのような、空間の揺れを\n微かに感じると、徐々に息苦しさが消えていく。")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("どうなってる！？！？", "レン")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("待てよ……", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ソヤはこっちにはいない、教会前の広場にいる。")
	await novel_interface.show_text_only("なぜか分からないが、そんな気がする。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("…………")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("やっぱり……", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("広場に来るとソヤは噴水の傍に座って\n水遊びをしていた。")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("レンさん、来てくれましたわね……♡", "ソヤ")
	await novel_interface.show_text_only("ストキングを脱いだ彼女は噴水に足を延ばし、\n指先を髪に絡めて弄んでいる。")
	await novel_interface.show_text_only("朧げな灯りに照らされた彼女は、酩酊しているか\nのように頬を赤く染め、俺の方を見た。")
	await novel_interface.show_text_only("俺の心臓は激しく鼓動を打つ──")
	await novel_interface.hide_character()
	
	print("=== 天启篇第15话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
