# apocalypse_ep16.gd - 天启篇第16话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第16话剧本
	apocalypse_ep16_script()

func play_script():
	pass

# 天启篇第16话 - 正式剧本
func apocalypse_ep16_script():
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	await novel_interface.show_text_only("Il viso di Sonya è arrossato sotto la fioca luce gialla. Le gocce d'acqua scendono lungo i suoi polpacci magri e nudi, lasciando una pozzanghera sul terreno.")
	await novel_interface.show_text_only("Si siede appollaiata sul bordo di marmo della fontana come un animale indifeso. Lei mi guarda, occhi innocenti eppure così ipnotizzanti...")
	await novel_interface.show_text_only("Il mio cuore fa un balzo e sento il mio viso riscaldarsi.")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Sonya...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ero rimasto inorridito quando ho sentito il suo retroscena, non volevo altro per trovarla e confortarla immediatamente. Ma ora... il mio cervello è completamente vuoto.")
	await novel_interface.show_text_only("Un po' come quegli idioti maldestri che vedi nei manga: vanno incontro alla loro cotta per confessare in un'esplosione di finta spavalderia, per poi dimenticare tutto ciò che avevano provato nel momento in cui vedono la cotta.")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("(Cervello, fai qualcosa! Cavolo!)", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","smile",0.25)
	await novel_interface.show_dialog("Ehi...", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Sonya si lecca le labbra e sorride dolcemente.")
	novel_interface.show_character("ren_fishnet","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("soya_uniform","normal",0.25)
	await novel_interface.show_dialog("Hai un odore... interessante...", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Striscia verso di me sul gradino di marmo. Vedo il motivo ad alveare sulla sua cavigliera riflesso dalla luce.")
	await novel_interface.show_text_only("È una cavigliera prodotta dal nostro SRD con materiali per armature di Sostanza H. Sembra fragile, ma in realtà è estremamente robusto.")
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("Proprio come mi aspettavo...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya mi prende la mano, preme il naso contro la mia pancia e inspira avidamente.")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("Ren è davvero il migliore!", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("C-cosa?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Faccio qualche passo indietro, confuso. Cosa le è successo nei minuti in cui ero via?")
	await novel_interface.show_text_only("Sonya si siede pigramente sul gradino di marmo e si liscia i capelli.")
	novel_interface.show_character("ren_fishnet","awkward")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","smile",0.25)
	await novel_interface.show_dialog("Elgana te l'ha detto, eh?", "Soya")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Il tuo corpo... semplicemente... cosa ti è successo?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Non volevo che tu lo sapessi.", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Sonya si allontana, la voce diminuisce di volume.")
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("Tutti quelli che conoscono il mio segreto finiscono per prendere le distanze da me...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Non posso fare a meno di ricordare il modo in cui Elgana ha parlato con Sonya qualche tempo fa.")
	await novel_interface.show_text_only("Sa che Sonya non vivrà a lungo e probabilmente ha pensato che sarebbe stato meglio starle lontano. Farebbe meno male quando accade l’inevitabile, giusto?")
	await novel_interface.show_text_only("Inoltre, Elgana è religiosa. La giovane, a cui è vietato entrare negli edifici sacri, potrebbe sembrarle di cattivo auspicio.")
	await novel_interface.show_text_only("La carta d'identità che rappresenta il suo titolo di Cavaliere del Giudizio, invece di garantirle la massima immunità, agisce in realtà come una sorta di ordine di esilio...")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Ma va bene. So che non sarai come loro...", "Soya")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Giusto?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("chiede Sonya, con cautela, con gli occhi puntati su di me. Le mie labbra tremano leggermente e mi avvicino per accarezzarle la testa.")
	await novel_interface.show_text_only("Sonya sorride, chiude gli occhi e mi dà una gomitata sul palmo.")
	await novel_interface.show_text_only("Poi si stiracchia e guarda il murale vicino alla cima della chiesa, così glorioso sotto il cielo notturno.")
	await novel_interface.show_dialog("Probabilmente mi odia adesso...", "Soya")
	await novel_interface.show_dialog("Anche se immagino che comunque non mi abbia mai amato.", "Soya")
	await novel_interface.show_text_only("Sto per chiederle chi è \"lui\", quando Sonya lancia un'occhiata al mio vestito e sorride.")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("Beh, anche tu hai molti segreti, vero?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("Cosa?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mi avvolge con le braccia prima che possa reagire.")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Sai perché non ho chiesto a Mariru la tua identità qualche tempo fa?", "Soya")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("È stato perché voglio trovare io stesso la risposta a questo affascinante enigma!", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("Ehi!", "Lian")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("D-non—", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Il mio telefono squilla all'improvviso. Beatrice. Sonya è ancora avvolta attorno a me anche mentre rispondo alla chiamata.")
	await novel_interface.show_text_only("Devo tenere il telefono con una mano e spingere Sonya con l'altra nel futile tentativo di tenere le sue mani lontane da me. Il mio palmo si posa sul suo naso e sulla sua bocca.")
	await novel_interface.show_dialog("Mmmff! Mmff!", "Soya")
	await novel_interface.show_dialog("Ren? Sono all'ospedale.", "Beatrice")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("Beatrice! Come sta John?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya balza in piedi e mi strappa via il telefono, accendendolo in trasmissione.")
	await novel_interface.show_dialog("L'hanno agganciato a una macchina... hanno bisogno di dargli dei fluidi. La sua vita non è in pericolo. Sta dormendo adesso, gli hanno iniettato degli antidolorifici.", "Beatrice")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("...Oh, quindi sente dolore?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Sì. L'infermiera dice che si è trattato di una perdita temporanea della capacità di percepire il dolore. Lo sa perché è il quarto paziente stasera che si trova in una situazione del genere.", "Beatrice")
	await novel_interface.show_dialog("C'era un uomo di mezza età che salì a piedi nudi sul cofano rovente di un'auto durante una rivolta in Electronics Street per avere una visuale migliore.", "Beatrice")
	await novel_interface.show_dialog("Le persone attorno a lui sentivano odore di bruciato e se ne accorse solo allora. La cosa strana era che anche i suoi capelli erano bruciati...", "Beatrice")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("(Forse è lo stesso ragazzo che Elluka ha scioccato?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Un altro paziente era un giornalista di Newmoridas. Si è fatta strada davanti ai manifestanti solo per scoprire che non riusciva a premere l'otturatore. Si è scoperto che si è rotta un dito lungo la strada.", "Beatrice")
	await novel_interface.show_dialog("C'era anche un riparatore dell'Hovering Palace. Mentre stava lavorando, ha avuto una scossa elettrica e ha iniziato a sanguinare internamente. Eppure non ne aveva idea! Ha continuato a chiacchierare con il suo collega al telefono per mezz'ora...", "Beatrice")
	await novel_interface.show_dialog("Si rese conto che qualcosa non andava solo quando non riuscì più a vedere in uno dei suoi occhi perché era iniettato di sangue.", "Beatrice")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("…", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sento un brivido corrermi lungo la schiena.")
	await novel_interface.show_text_only("Quattro persone completamente scollegate. Età, sesso, nazionalità, carriere diverse. Eppure mostrano segni dello stesso, e molto raro, disturbo.")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Mariru ha detto che le rivolte di stasera potrebbero avere qualcosa a che fare con la sostanza H...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Potrebbe essere.", "Beatrice")
	await novel_interface.show_dialog("Aya è già entrata nei dati di sorveglianza dei soldati della sicurezza. Hai accesso temporaneo anche sul tuo telefono, giusto?", "Beatrice")
	await novel_interface.show_dialog("Ripercorrendo i registri delle attività di queste quattro persone, abbiamo scoperto che sono state tutte in almeno una delle sette aree degli scontri questo pomeriggio.", "Beatrice")
	await novel_interface.show_dialog("Quel riparatore era in realtà il capo dell'ispezione di sicurezza della Johnson Heavy Industries!", "Beatrice")
	await novel_interface.show_dialog("Ha parlato per cinque minuti con un uomo in giacca a vento intorno alle sei di stasera, all'incrocio vicino a Electronics Street.", "Beatrice")
	await novel_interface.show_dialog("Sembrava che quell'uomo avesse deliberatamente evitato tutte le zone dotate di telecamere di sorveglianza. Ma abbiamo ancora la sua faccia quando è passato in un vicolo...", "Beatrice")
	await novel_interface.show_text_only("Beatrice inizia a parlare più lentamente, ponendo l'accento su ogni parola.")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("È l'uomo che ci ha aggredito allo Sky Hotel.", "Beatrice")
	novel_interface.show_background("res://assets/images/bg/Soya/Monitor_Y.png")
	await novel_interface.show_text_only("Mi invia lo screenshot che ha ricevuto.")
	await novel_interface.show_dialog("Giacobbe?", "Lian")
	await novel_interface.show_text_only("Jacob Schmidt... specialista in armi del Congresso Unito, rappresentante di Masada Ford, la Terza Città Accademia.")
	await novel_interface.show_text_only("Quel ragazzo che trattava Elluka come un'arma e un semplice strumento...")
	await novel_interface.show_text_only("Successivamente, ha guidato un gruppo di lacchè ad attaccare me, Beatrice, Annie e Raphilia allo Sky Hotel. Ha usato anche armi a base di sostanza H.")
	await novel_interface.show_text_only("Annie è stata gravemente ferita da una delle loro armi elettriche. Per fortuna c'era Raphilia...")
	await novel_interface.show_text_only("Nemmeno Mariru è riuscita a trovare dati su quell'uomo. Possiamo solo dedurre che lavorasse per Menorah, l'agenzia di intelligence della Terza Città Accademia.")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("Aspetta, Johnson Heavy Industries... intendi Johnson Substation?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fu lì che io e Annie incontrammo per la prima volta Elluka e Igor. Non saremmo sopravvissuti vivi senza il tempestivo aiuto di Mariru.")
	await novel_interface.show_dialog("Ho interrogato un po’ il riparatore, ma tutto quello che sapeva era che Igor era un rappresentante di un collaboratore della loro azienda.", "Beatrice")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("Perché Johnson dovrebbe collaborare con Igor...?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Il Congresso Unito ha deciso solo due settimane fa di potenziare completamente il sistema di sorveglianza della città prima dell'inizio del Forum di Pace.", "Beatrice")
	await novel_interface.show_dialog("La maggior parte delle telecamere erano già posizionate, ma l’alimentazione per l’illuminazione era fornita in modo indipendente e non c’era abbastanza tempo per espandere la copertura del circuito alla maggior parte dei blocchi.", "Beatrice")
	await novel_interface.show_dialog("Quindi hanno dovuto chiedere a un collaboratore di fornire le batterie come misura temporanea.", "Beatrice")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("Batterie?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Sai, un vaso trasparente delle dimensioni di un pollice. Elettrodi su entrambe le estremità. Liquido appiccicoso luminoso all'interno. Ho sentito che potrebbe far funzionare i dispositivi di sorveglianza per venti giorni.", "Beatrice")
	await novel_interface.show_dialog("Ho già inviato un campione alla sede centrale.", "Beatrice")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("Sembra che il \"cibo\" che Elluka mi ha offerto la prima volta che ci siamo incontrati...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Voleva ringraziarmi per la cioccolata... immagino che non dovesse essere commestibile!")
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("Ehi, quell'Igor di cui parli... è quel ragazzo che possedevi totalmente?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("chiede Sonya, con gli occhi spalancati come una bambina curiosa.")
	await novel_interface.show_dialog("Ren...", "Beatrice")
	await novel_interface.show_dialog("Voi due siete piuttosto \"vicini\", ma sembra che le abbiate lasciato trapelare un po' troppo, vero?", "Beatrice")
	await novel_interface.show_text_only("Assolutamente no! Non siamo \"vicini\"!")
	await novel_interface.show_dialog("Non hai paura che Mariru ti punisca?", "Beatrice")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("Non ho fatto trapelare...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Mmph... mmmm!", "Lian")
	await novel_interface.show_text_only("Sonya mi mette una mano sul viso, sollevando il telefono in alto con una mano.")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("Ren mi ha detto tutto, in realtà!", "Soya")
	await novel_interface.show_dialog("Sei davvero la stessa bellezza del capolavoro di Dante?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Sentendoci giocare a litigare, Beatrice scoppia a ridacchiare.")
	novel_interface.change_background("res://assets/images/bg/Soya/University_Hospital.png")
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("Lo sai anche tu? Immagino che Mariru abbia permesso a Ren di dirtelo allora.", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Allora? Sei?", "Soya")
	await novel_interface.show_text_only("Sonya insiste, come un grosso cane che scodinzola.")
	novel_interface.show_character("beatrice_regular","smile3")
	await novel_interface.show_dialog("Sì. Sono davvero la Beatrice di cui parli. Mio padre era Folco Portinari.", "Beatrice")#文字错误
	novel_interface.change_expression("smile2")
	await novel_interface.show_dialog("A dire il vero ho visto Dante solo una volta. Era durante una riunione di famiglia il Primo Maggio. Allora ero davvero giovane, però. Anche più giovane di Elluka.", "Beatrice")
	novel_interface.change_expression("grieved")
	await novel_interface.show_dialog("Scoprii solo più tardi che quel bicchiere di veleno lo avevo bevuto per più di una dozzina d'anni quando scrisse la Divina Commedia.", "Beatrice")
	await novel_interface.show_dialog("Da parte sua si trattava semplicemente di un'attrazione unilaterale.", "Beatrice")
	novel_interface.change_expression("smile2")
	await novel_interface.show_dialog("Tuttavia, devo ammettere che le sue opere sono impressionanti.", "Beatrice")
	await novel_interface.show_dialog("Ha osato deridere il papa nel suo lavoro e ha persino descritto me che lo aspettavo alle porte del paradiso e lo guidavo attraverso i livelli dell'inferno.", "Beatrice")
	novel_interface.change_expression("smile1")
	await novel_interface.show_dialog("Probabilmente per lui era la realizzazione di un desiderio. Magari anche una sorta di vendetta.", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Vendetta?", "Lian")
	novel_interface.show_character("beatrice_regular","smile2")
	await novel_interface.show_dialog("Bene, quel segreto spetta a me mantenerlo.", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beatrice guarda in alto verso il cielo stellato.")
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("Lo sapevi...", "Beatrice")
	await novel_interface.show_dialog("Uno degli asteroidi che ruotano attorno al sistema solare porta il mio nome. Lo scopritore si ispirò alla mia immagine nell’opera di Dante.", "Beatrice")
	await novel_interface.show_dialog("Se solo potessi scrivere la mia risposta alla sua poesia...", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_text_only("Beatrice finalmente riattacca dopo aver detto che chiamerà Mariru.")
	await novel_interface.show_text_only("Sonya si siede sul bordo della fontana e continua a giocare con il mio telefono, ignorando le mie richieste di restituirmelo.")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("Tch... hai anche chiuso a chiave il tuo album fotografico? È come ammettere che dentro c'è qualcosa di incriminante...", "Soya")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_fishnet","stare",0.25)
	await novel_interface.show_dialog("Almeno è meglio che affrontarlo...", "Lian")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Comunque, prima controlliamo i filmati della sorveglianza. Spiare le persone con i droni è davvero un’ottima idea!", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Faresti meglio a non fare niente del genere!")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Uhm—", "Soya")
	await novel_interface.show_dialog("Dove sono…", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mi avvicino per vedere il filmato di sorveglianza in tempo reale del drone che abbiamo posizionato davanti al Congresso Unito sulla First Avenue.")
	novel_interface.change_background("res://assets/images/bg/Soya/Cordon.png")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("I soldati della sicurezza hanno allestito una rigida linea di difesa davanti all'edificio.")
	await novel_interface.show_text_only("Su entrambi i lati della lunga fila di scudi antisommossa, la tensione tra i soldati armati e i manifestanti agitati è palpabile.")
	await novel_interface.show_text_only("Diversi manifestanti continuano a cercare di sbattere contro il muro di scudi, mentre alcuni lanciano oggetti da lontano contro i soldati.")
	await novel_interface.show_text_only("Ciò include una bomba Molotov rozzamente realizzata, che atterra oltre la linea di difesa, creando un arco stranamente bello nell'aria.")
	await novel_interface.show_text_only("Diversi soldati si affrettano a spegnere l'incendio con gli estintori, mentre i feriti vengono trascinati sul retro per essere curati. Sembrano avere abbastanza esperienza nell'affrontare cose come questa.")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("soya_uniform","wordless")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_fishnet","upset",0.25)
	await novel_interface.show_dialog("Sembra un disastro laggiù...", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Se invece quella cosa fosse caduta tra la folla in protesta...")
	await novel_interface.show_text_only("Sonya non sembra infastidita dalle mie preoccupazioni. Passa semplicemente a un altro schermo, visualizzando le riprese di un altro drone, e si acciglia.")
	await novel_interface.show_text_only("Quindi inizia a confrontare le riprese di diversi droni e a tracciare le posizioni corrispondenti su una grande mappa.")
	await novel_interface.show_text_only("Le sette aree in cui si sono verificati i disordini formano un esagramma perfetto: sei punti rappresentano le punte acuminate della stella e i rimanenti il centro.")
	novel_interface.show_character("soya_uniform","trance")
	await novel_interface.show_dialog("E' questo...", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("Hai trovato qualcosa?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Ren, devo andare subito in questo posto.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Indica un punto nella sezione centrale della First Avenue, con espressione solenne.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Non preoccuparti, non mi precipiterò tra la folla o altro. Puoi fare quello che vuoi purché non sia a più di 200 metri da me.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Che cosa hai intenzione di...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("Oh, devo tornare indietro per qualcosa. Aspettami qui!", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Prima che possa finire la domanda, Sonya si è rimessa le scarpe ed è corsa in camera sua.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("…")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	await novel_interface.show_text_only("Riappare con una borsa nera a tracolla. Qualunque cosa ci sia dentro sembra piuttosto ingombrante.")
	await novel_interface.show_text_only("Mi prende la mano come se fosse la cosa più naturale che ci sia e ci guida verso il SUV nero che ci aspetta all’ingresso.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Alla Prima Avenue.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ma la gente non protesta lì?", "Autista")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Possiamo semplicemente andare in giro tra la folla. Indicherò la strada.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("Non è ancora mezzanotte, ma le strade sono sorprendentemente sgombre. L'autista grassottello urla.")
	await novel_interface.show_dialog("Di solito il traffico è frenetico su questa strada, ma oggi è davvero fluido. Immagino che la maggior parte delle persone che sanno cosa è bene per se stesse siano già tornate a casa.", "Autista")
	await novel_interface.show_text_only("Immagino che ciò significhi che siamo quelli che non sanno cosa è bene per se stessi!")
	novel_interface.show_background("res://assets/images/bg/Soya/Parade.png")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("Provo a contattare Mariru e Beatrice in macchina, ma non risponde nessuno.")
	await novel_interface.show_text_only("Nel giro di dieci minuti arriviamo su una strada più piccola a est della sezione centrale della First Avenue.")
	await novel_interface.show_text_only("L’autista ci dice che ci aspetterà lì e avverte anche noi “due signorine” di stare attenti là fuori di notte.")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("Ahah... ah...", "Lian")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("(Quindi anime innocenti e ben intenzionate come questa esistono anche nel SID, eh?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Dall’altra parte della strada vediamo orde di manifestanti che sventolano striscioni e scandiscono slogan disordinati.")
	await novel_interface.show_text_only("La First Avenue è piena di gente, gente e ancora gente. La folla sembra avanzare, verso un punto finale che non raggiungerà mai.")
	novel_interface.show_character("ren_fishnet","speechless")
	await novel_interface.show_dialog("Se continuassero così, quando arriveranno al palazzo del congresso probabilmente le diecimila persone più avanti rimarranno schiacciate...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Non pensi che queste persone si comportino in modo un po’ strano?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ho visto molte manifestazioni a New Opulentia, ma nessuna di così grande portata. Nemmeno vicino.")
	await novel_interface.show_text_only("In contrasto con l’atmosfera tesa lassù sulla linea di difesa, la folla intorno a noi sembra meno violenta. Alcuni cantano ad alta voce, è vero...")
	await novel_interface.show_text_only("Ma molti altri sembrano essere qui semplicemente per godersi l'atmosfera. Alcuni addirittura si scattano selfie sotto cartelloni pubblicitari lampeggianti, caffè e cibo spazzatura in mano.")
	await novel_interface.show_text_only("Guardo un uomo di mezza età, dopo aver posato per la macchina fotografica, applicare un filtro e condividere la foto sul suo account di social media.")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("Sembrano... piuttosto tranquilli?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Non ci sono soldati della sicurezza in giro. Probabilmente sono troppo occupati a trattare con quelli più avanti per preoccuparsi di questi civili pacifici.")
	novel_interface.show_character("ren_fishnet","stare")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","wordless",0.25)
	await novel_interface.show_dialog("In realtà, le dimostrazioni su larga scala di solito sono così. Ci sarebbero quelli violenti e quelli pacifici. Ma non pensi che il confine tra queste due sezioni sia un po’ troppo definito?", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Solo allora mi rendo conto che le persone sembrano davvero aderire a certi “confini”. La maggior parte della folla, infatti, è raccolta dall’altra parte della strada rispetto a noi, anche se c’è molto spazio per stare dalla nostra parte.")
	novel_interface.show_character("ren_fishnet","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("soya_uniform","wordless",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("È questo quello che chiamano comportamento da gregge?", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mimetizzarsi tra la folla per sentirsi al sicuro... come i pinguini che tendono a viaggiare in gruppo. È naturale che in tali situazioni si formino dei “confini”.")
	novel_interface.show_character("ren_fishnet","speechless")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light(0)
	novel_interface.show_2nd_character("soya_uniform","wordless",0.25)
	novel_interface.character_2nd_dark(0)
	await novel_interface.show_dialog("Comunque, cosa hai detto che volevi fare qui comunque?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speechless")
	await novel_interface.show_dialog("Eh, andiamo di sopra prima.", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Sonya mi trascina in un edificio per uffici lungo la strada. Fa fuoriuscire la sicurezza con facilità, afferra la tessera d'ingresso che lui porta al collo e la scannerizza nell'ascensore. Ci porta direttamente sul tetto.")
	novel_interface.change_background("res://assets/images/bg/Soya/First_Avenue.png")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	novel_interface.show_character("ren_fishnet","serious")
	await novel_interface.show_dialog("Wow, sono un sacco di persone!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Dal nostro punto di vista, posso vedere fin troppo chiaramente quanto sia affollato laggiù.")
	await novel_interface.show_text_only("Non sono più grandi delle formiche dal mio punto di vista, ma nemmeno le formiche sarebbero così vicine l'una all'altra, vero?")
	await novel_interface.show_text_only("Sonya recupera un piccolo binocolo dalla borsa e scruta la folla sottostante.")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Hmm, non laggiù...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Prende il mio telefono e ricomincia a passare da un filmato di sorveglianza all'altro.")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Nemmeno lì...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Alla fine si siede e tira un sospiro, come se fosse sollevata.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Quindi è solo una coincidenza, eh...", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("Andiamo, cosa stai cercando esattamente?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Una porta...", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("Porta?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya continua a guardare in silenzio il mare di gente, ignorando la mia domanda.")
	await novel_interface.show_text_only("Decido di non assillarla ulteriormente dato che comunque finora sembra tutto a posto. Invece mi siedo accanto a lei e mi godo il panorama.")
	await novel_interface.show_text_only("Tutto sembra così banale in qualche modo, quando siamo così in alto.")
	await novel_interface.show_dialog("Ci devono essere più di diecimila persone laggiù...", "Soya")
	await novel_interface.show_dialog("Probabilmente...", "Lian")
	await novel_interface.show_dialog("Quando li guardi così, ti senti come se fossi uno di loro?", "Soya")
	await novel_interface.show_text_only("Delicatamente, scuoto la testa.")
	await novel_interface.show_text_only("Le folle disordinate laggiù sembrano essere diventate di per sé una forma di vita nuova di zecca: un essere vivente e respirante che si muove come fanno gli umani che lo compongono.")
	await novel_interface.show_text_only("Mi fa venire i brividi. Certamente non vorrei essere uno di loro.")
	await novel_interface.show_dialog("Ehi...", "Soya")
	await novel_interface.show_dialog("Ehm?", "Lian")
	await novel_interface.show_dialog("Ho visto questo documentario quando ero piccolo, nell'abbazia.", "Soya")
	await novel_interface.show_dialog("Era ambientato al Polo Sud. Tutto è bianco lì. Nessun punto di riferimento come riferimento.", "Soya")
	await novel_interface.show_dialog("L'unico modo in cui i pinguini possono orientarsi è il loro istinto. E devono migrare in massa due volte ogni anno per riprodursi.", "Soya")
	await novel_interface.show_dialog("I pinguini appena nati devono imparare a seguire il loro gruppo subito dopo la nascita, così da poter raggiungere l’oceano dove c’è il cibo.", "Soya")
	await novel_interface.show_dialog("A volte ci sono più di duecentomila pinguini che si muovono contemporaneamente sulla piattaforma di ghiaccio del Polo Sud. Il loro corteo è ordinato, tutti vanno nella stessa direzione.", "Soya")
	novel_interface.change_background("res://assets/images/bg/Soya/Penguin.png")
	await novel_interface.show_dialog("Ma ogni anno, per qualche motivo, alcuni pinguini appena nati vogliono prendere un’altra strada.", "Soya")
	await novel_interface.show_dialog("Anche se i pinguini adulti cercano di correggerli, anche se sono completamente soli, anche se c’è una bufera di neve, insistono ad allontanarsi dall’oceano.", "Soya")
	await novel_interface.show_dialog("Ma il Polo Sud è un continente disabitato e isolato. L'ambiente non è mai benevolo nei confronti di questi piccoli pinguini.", "Soya")
	await novel_interface.show_dialog("Tuttavia, se il clima cambia, cambia drasticamente per la prima volta in un milione di anni, forse i piccoli pinguini che vanno nella direzione opposta saranno gli unici sopravvissuti.", "Soya")
	await novel_interface.show_dialog("—In un certo senso, sono una sorta di meccanismo assicurativo per la specie. Possono salvare la loro specie dall'istinto.", "Soya")
	novel_interface.change_background("res://assets/images/bg/Soya/First_Avenue.png")
	await novel_interface.show_text_only("Sonya tace dopo aver finito di raccontare ciò che aveva visto.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Quando ero piccola, pensavo sempre... che ci fossero tantissime cose affascinanti là fuori nel mondo, che aspettavano che io le scoprissi.", "Soya")
	await novel_interface.show_dialog("E voglio vederli tutti, sperimentarli tutti.", "Soya")
	novel_interface.change_expression("wordless")
	await novel_interface.show_dialog("Ma la curiosità ha un prezzo...", "Soya")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("I sintomi appena descritti da Beatrice e l'ubicazione delle sette aree in cui ci furono rivolte... mi ricordano entrambi quella missione di tre anni fa...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Deglutisco sorpreso. Quindi ha già riscontrato sintomi del genere prima?")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Allora ci fu un’enorme calamità da qualche parte in Sud America. Così enorme che probabilmente avrebbe portato a un'apocalisse di classe XK.", "Soya")
	await novel_interface.show_dialog("Il primo gruppo di monaci vestiti di nero inviati dalla CDF morirono tutti. Gli altri monaci rimasero inorriditi e si rifiutarono di andare.", "Soya")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Ma mi sono offerto volontario. Ero quel piccolo pinguino...", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","serious")
	await novel_interface.show_dialog("Cosa è successo esattamente lì?", "Lian")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/BlackGate.png")
	await novel_interface.show_dialog("Un paio di cancelli di puro nero apparvero dal nulla sui muri di una piccola chiesa. E dietro le porte semiaperte non c'è altro che una luce dorata, brillante e accecante...", "Soya")
	await novel_interface.show_dialog("In un raggio di due miglia con il cancello come punto centrale, tutta l'elettronica ha smesso di funzionare. Nessuno di coloro che sono entrati nella zona è rimasto vivo.", "Soya")
	await novel_interface.show_dialog("Questo era tutto ciò che sapevamo allora.", "Soya")
	await novel_interface.show_dialog("Secondo il Papa è stato come se si fossero aperte le porte perlate del Paradiso.", "Soya")
	novel_interface.change_background("res://assets/images/bg/Soya/First_Avenue.png")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("E la mia missione era richiudere i cancelli.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mi accorgo a malapena che sto trattenendo il respiro mentre Sonya racconta la sua storia.")
	novel_interface.show_character("soya_uniform","speechless")
	await novel_interface.show_dialog("Paradiso, lo chiamavano. Ah.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lei scuote la testa con uno sbuffo.")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Sono arrivato e ho scoperto che, con la chiesa come punto centrale, che si estendeva in sei direzioni simmetriche, c'erano sei \"linee\" su cui giacevano decine di migliaia di corpi contorti.", "Soya")
	await novel_interface.show_dialog("Maschi, femmine, anziani o giovani: tutte quelle persone sono morte combattendo tra loro. Lo si capiva dalle ferite.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("(Sembra qualcosa che farebbero quelle streghe contaminate...)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("Immagino che, se l'Inferno esiste... sarebbe così.", "Soya")
	await novel_interface.show_dialog("L'unico motivo per cui sono arrivato vivo alla porta è stato probabilmente perché ero l'unico nella zona. Nessuno con cui combattere.", "Soya")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/BlackGate.png")
	await novel_interface.show_dialog("Non trovavo la luce troppo forte quando ero lì, davanti a quella porta. Sembrava... caldo, rilassante. Come se volesse risucchiarmi dentro.", "Soya")
	await novel_interface.show_dialog("Potevo percepire una sorta di spirito, uno con una presenza impossibile da ignorare, che cercava di convincermi ad spalancare il cancello o semplicemente ad entrare.", "Soya")
	await novel_interface.show_dialog("Non lo diceva a parole, ma era quello che sentivo.", "Soya")
	await novel_interface.show_dialog("Se entrassi nel portale, diventerei tutt’uno con la luce dorata.", "Soya")
	await novel_interface.show_dialog("Se aprissi completamente il cancello, tutti nel mondo diventerebbero tutt’uno con la luce dorata.", "Soya")
	novel_interface.change_background("res://assets/images/bg/Soya/First_Avenue.png")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Sfortunatamente, non ero affatto interessato a “diventare tutt’uno” con nulla…", "Soya")
	await novel_interface.show_dialog("Quindi ho semplicemente chiuso il cancello mentre lo spirito mi urlava parolacce.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("Ahahahah...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Nel momento in cui i nostri occhi si incontrano, scoppiamo a ridere.")
	await novel_interface.show_text_only("Laggiù, innumerevoli persone stanno marciando. Ed eccoci qui, sul tetto, a più di cento metri sopra di loro, a ridere a crepapelle.")
	await novel_interface.show_dialog("Uffa—", "Soya")
	await novel_interface.show_text_only("Sonya inspira profondamente, cercando di calmarsi. Aveva riso così forte che era praticamente in lacrime.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Dopo aver chiuso il cancello, tutto è semplicemente scomparso. Il muro nudo era tutto ciò che restava.", "Soya")
	await novel_interface.show_dialog("Dopo quell’incidente, il Congresso Unito cominciò a sostenere la nostra chiesa.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Quindi è per questo che la chiesa riusciva a malapena a sopravvivere, ma ora può costruire giganteschi edifici religiosi, eh?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Tuttavia dovevo toccare la superficie nera e pura della porta per chiuderla.", "Soya")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("E le sostanze nere gradualmente hanno invaso il mio corpo. Immagino che sia il prezzo che devo pagare...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya abbassa lo sguardo, un po' malinconica.")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Sonya.", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Metto le mani sulle sue fragili spalle e la guardo profondamente negli occhi.")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("I piccoli pinguini che vanno nella direzione opposta lo fanno di propria volontà, non per una sorta di meccanismo assicurativo per la sopravvivenza della specie.", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Sono solo davvero curiosi di sapere cosa c’è dall’altra parte.", "Lian")
	await novel_interface.show_dialog("Anche alcuni dei nostri antenati erano come quei pinguini. Seguendo i propri desideri, partirono dall'Africa e alla fine popolarono il mondo intero.", "Lian")
	await novel_interface.show_dialog("Gli esseri umani sono ovunque ormai. Nei luoghi più freddi e caldi del mondo, in luoghi bui per metà dell'anno e luminosi per l'altra metà, anche al di là del mare!", "Lian")
	await novel_interface.show_dialog("Non sei una sorta di meccanismo. Tu sei...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("Sono...?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Ehi.", "Lian")#文字错误
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","wordless",0.25)
	await novel_interface.show_dialog("Ehm?", "Soya")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ehm...", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Aaaaaaah!")
	await novel_interface.show_text_only("Perché non riesco a trovare le parole giuste?")
	novel_interface.show_character("ren_fishnet","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("soya_uniform","jest",0.25)
	await novel_interface.show_dialog("Ehm?", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Sonya mi dà una gomitata nello stomaco.")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("Non eri eloquente pochi secondi fa?", "Soya")
	await novel_interface.hide_character()
	
	print("=== 天启篇第16话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
