# apocalypse_ep10.gd - 天启篇第10话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第10话剧本
	apocalypse_ep10_script()

func play_script():
	pass

# 天启篇第10话 - 正式剧本
func apocalypse_ep10_script():
	# 场景：秋叶原夜晚
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("Sonya e io torniamo verso la luminosa Electronics Street.")
	await novel_interface.show_text_only("L'enorme schermo sospeso sulla parete esterna del Nekomaru Electronics Flagship Building trasmette in loop la pubblicità di uno sponsor.")
	await novel_interface.show_text_only("Alcuni camion mobili con cartelloni pubblicitari sono parcheggiati ordinatamente in fila al centro del passaggio pedonale.")
	await novel_interface.show_text_only("Su entrambi i lati di ogni camion ci sono giganteschi annunci pubblicitari dipinti con spray. Sul tetto dei veicoli ci sono dei binari decorati, e alcuni operai si appoggiano ad essi, effettuando controlli del suono con attrezzature dall'aspetto fantasioso.")
	novel_interface.show_character("soya_uniform", "speechless")
	await novel_interface.show_dialog("Terranno una specie di evento qui?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Electronics Street è ancora più affollata di quando l'avevamo lasciata in precedenza. Continua ad affluire altra gente.")
	novel_interface.show_character("ren_fishnet", "perspire1")
	await novel_interface.show_dialog("Oh, oggi deve essere...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ricordo di aver visto qualcosa di simile online e di aver tirato fuori il telefono per eseguire una ricerca.")
	await novel_interface.show_text_only("Esatto. È il festival annuale di Electronics Street.")
	await novel_interface.show_text_only("Cinque anni fa, mentre New Opulentia si riprendeva gradualmente dalla guerra, il Senato annunciò l’abolizione di diverse leggi che regolavano le attività culturali, inclusa la Legge sull’Ordine Sociale.")
	await novel_interface.show_text_only("La mezzanotte prima che venisse presa la decisione, un'enorme folla si radunò sotto lo stesso schermo davanti alla Nekomaru Electronics e contò i secondi che portavano a questa “grande vittoria”.")
	await novel_interface.show_text_only("Successivamente, alcuni netizen hanno apportato modifiche divertenti, creando un intero cortometraggio che raccontava una storia epica di come i coraggiosi pionieri otaku si opposero al governo oppressivo e alla fine salvarono il mondo.")
	await novel_interface.show_text_only("Ciò ha ispirato molti dei cosiddetti \"pionieri\" a apportare le proprie esilaranti modifiche, aggiungendo frammenti alla storia di \"quella guerra\", come se fosse un evento realmente esistente.")
	await novel_interface.show_text_only("Alcuni hanno addirittura affermato che, dopo l’incidente, il governo ha cancellato la memoria di chiunque nel mondo, lasciando intatta la memoria solo di pochi coraggiosi “pionieri”.")
	await novel_interface.show_text_only("E il conto alla rovescia era in realtà un gruppo di sopravvissuti riuniti per commemorare quei coraggiosi “pionieri” la notte prima che i loro ricordi venissero cancellati.")
	novel_interface.show_character("ren_fishnet", "wail")
	await novel_interface.show_dialog("(Che razza di storia stupida è questa? Chi la comprerebbe comunque?)", "Lian")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("(Mi è davvero piaciuto scorrere le modifiche però...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ad ogni modo, le aziende della zona hanno colto l'occasione per trasformare la giornata in un festival annuale in cui gli acquirenti ottengono sconti pazzeschi. Ciò ha attirato anche molti sponsor.")
	novel_interface.show_character("ren_fishnet", "uneasy")
	await novel_interface.show_dialog("Non c'è da stupirsi che questo pomeriggio distribuissero merce gratuita...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Osservo con invidia il passaggio di alcuni acquirenti, con in mano le loro bandierine gialle.")
	novel_interface.show_character("soya_uniform", "wordless")
	await novel_interface.show_dialog("Se l'evento durerà fino a mezzanotte... non è un po' troppo presto perché la gente si entusiasmi così tanto?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Controllo l'orologio. Non sono ancora le otto, ma la folla per strada sembra già in fermento.")
	await novel_interface.show_text_only("Oggi il numero dei partecipanti è inaspettatamente alto. La povera polizia di sicurezza che mantiene l'ordine riesce a malapena a farsi sentire.")
	novel_interface.show_character("ren_fishnet", "upset")
	await novel_interface.show_dialog("Uh... non siamo fuggitivi?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Dò una sbirciatina ai poliziotti nelle vicinanze, chiedendomi se Sonya avrà bisogno di eliminarli anche con qualche altro gadget pazzesco.")
	novel_interface.show_character("soya_uniform", "relieve")
	await novel_interface.show_dialog("Mantieni solo un profilo basso.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya mi dà un pizzicotto e indica alcuni veicoli dall'altra parte della strada.")
	novel_interface.show_character("soya_uniform", "smile")
	await novel_interface.show_dialog("Vedi quei due camion blindati neri?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Li vedo. Sembra che trattengano i soldati della sicurezza in attesa di ordini, probabilmente dalla squadra operativa speciale di Newmoridas.")
	novel_interface.show_character("soya_uniform", "jest")
	await novel_interface.show_dialog("Se attiriamo l’attenzione di quei ragazzi, non ti proteggerò dai proiettili!", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya guarda le mie cosce morbide e senza muscoli con un sorriso sdegnoso. Probabilmente pensa che io sia un ragazzino inutile che non sa nemmeno schivare i proiettili. E non ha torto.")
	novel_interface.show_character("ren_fishnet", "upset")
	await novel_interface.show_dialog("Come troviamo Elluka tra così tante persone?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mi guardo intorno e guardo la folla che chiacchiera, sentendo una fitta al cuore mentre immagino la piccola Elluka, persa in mezzo a tutto, terrorizzata e indifesa.")
	novel_interface.show_character("soya_uniform", "jest")
	await novel_interface.show_dialog("Oh, quella ragazza? Lei è proprio lì.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "perspire1")
	await novel_interface.show_dialog("Eh?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya fa un cenno al camion con i cartelloni pubblicitari davanti a noi, decorato come una sorta di santuario. E la ragazza seduta nella posizione del dio adorato? Elluka.")
	await novel_interface.show_text_only("È difficile dire chi abbia sponsorizzato questo camion. Sulla sua testa è appesa una gigantesca lanterna, e proprio dietro di essa ci sono due uomini che suonano i tamburi taiko.")
	await novel_interface.show_text_only("Centinaia di persone sono affollate attorno al camion, indicano Elluka e tubano per la sua dolcezza.")
	await novel_interface.show_text_only("Una dozzina di ragazzi vestiti con abiti wota sono in fila, sventolano le bandiere gialle e cantano fanchant al ritmo dei tamburi.")
	await novel_interface.show_text_only("Sul tavolo delle offerte davanti a Elluka c'è un panino con crema al cioccolato, che lei divora in pochi secondi.")
	
	# 显示伊露卡，使用iluka_hide而不是iluka_uniform
	await novel_interface.show_dialog("Mwahahah…", "Elluka")
	await novel_interface.show_text_only("E poi sorride, così felice, così senza cuore.")
	await novel_interface.show_text_only("La folla esulta quando termina l'\"offerta\" e i suoi \"fan\" iniziano a cantare più forte.")
	await novel_interface.show_text_only("Con gli occhi pieni di stelle, Elluka sceglie la sua prossima “offerta”.")
	novel_interface.show_character("ren_fishnet", "wail")
	await novel_interface.show_dialog("...", "Lian")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("Che diavolo?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "laugh")
	await novel_interface.show_dialog("Sembra che si stiano divertendo tantissimo.", "Soya")
	await novel_interface.hide_character()
	
	# 场景转换
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…")
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("Ci facciamo largo tra la folla, osservando il camion da ogni angolazione.")
	await novel_interface.show_text_only("I tifosi devoti sono ammucchiati contro il camion, rendendoci impossibile avvicinarci senza ricorrere alla violenza.")
	novel_interface.show_character("ren_fishnet", "upset")
	await novel_interface.show_dialog("Ma non possiamo creare trambusto, perché arriveranno gli sbirri...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Almeno Elluka non sembra essere in pericolo. Lei è semplicemente seduta lì, a mangiare. Inutile preoccuparsi, quindi.")
	novel_interface.show_character("soya_uniform", "jest")
	await novel_interface.show_dialog("Ehi, perché pensi che quei ragazzi adorino le ragazzine carine? In Europa, troviamo che ciò sia anormale.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("mi chiede Sonya, con un sorrisetto sul volto.")
	novel_interface.show_character("ren_fishnet", "perspire1")
	await novel_interface.show_dialog("Anormale?\nNon è poi così male...", "Lian")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("Vedi, è come il modo in cui le persone trovano carini i gattini e i cuccioli, giusto? Le bambine sono semplici, un po' goffe e fanno sempre del loro meglio...", "Lian")
	await novel_interface.show_dialog("Ricorda alle persone quel pezzo di innocenza che hanno perso e vogliono proteggerlo...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Cerco di spiegare, ma più dico, più mi sembra strano.")
	novel_interface.show_character("ren_fishnet", "shy_left")
	await novel_interface.show_dialog("Inoltre, quando si tratta di essere anormali, non sei anche tu peggio?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "laugh")
	await novel_interface.show_dialog("Ebbene, per quanto mi riguarda, essere anormali non è una brutta cosa.", "Soya")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("Se “normale” è definito come lo stato medio delle persone in un determinato ambiente, allora coloro che non sono nella media saranno considerati “anormali”.", "Soya")
	await novel_interface.show_dialog("Quindi anche coloro che sono eccezionali sono “anormali”, giusto? Non è affatto una brutta cosa!", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya si mette una mano davanti al petto, con aria piuttosto orgogliosa.")
	novel_interface.show_character("soya_uniform", "relieve")
	await novel_interface.show_dialog("Essere anormali va bene, non c'è bisogno di spiegare la tua anormalità a quei comuni cittadini comuni. Puoi semplicemente ammetterlo invece di cercare di trovare scuse per questo.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya mi dà una pacca sulla spalla, come se se ne fosse appena andata con grande saggezza.")
	novel_interface.show_character("ren_fishnet", "wail")
	await novel_interface.show_dialog("(Che razza di interpretazione è questa?)\n(E questo significa che anche lei pensa che io sia anormale?)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "jest")
	await novel_interface.show_dialog("Il motivo per cui gli europei trovano anormali quelli con il complesso lolicon è probabilmente che all'europeo medio piacciono di più le donne con il seno grande. Per esempio...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya mette una mano sul mio seno e pizzica un capezzolo.")
	novel_interface.show_character("ren_fishnet", "awkward")
	await novel_interface.show_dialog("Respirare?", "Lian")
	await novel_interface.hide_character()
	
	# 贝阿特丽切出场，使用beatrice_show_hide效果
	await novel_interface.show_dialog("Non ancora molto maturo, eh.", "Voce femminile")
	await novel_interface.show_text_only("Una voce familiare arriva alle nostre spalle.")
	novel_interface.show_character("ren_fishnet", "perspire1")
	await novel_interface.show_dialog("B-Beatrice?\nCosa stai facendo qui?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("È passato un po' di tempo, tesoro!", "Beatrice")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "laugh")
	await novel_interface.show_dialog("Waah!", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya sta per fare un balzo sul petto di Beatrice, ma la tiro indietro giusto in tempo.")
	novel_interface.show_character("soya_uniform", "cry")
	await novel_interface.show_dialog("L-lasciami andare!", "Soya")
	await novel_interface.show_dialog("Ha l'odore puro di Ren, ma i suoi sono molto più grandi...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Stai zitto!")
	await novel_interface.show_text_only("Beatrice si limita a scostare elegantemente i capelli e ad aggiustarsi la camicia attillata.")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("Mariru mi ha chiesto di seguirti in segreto e di tenerti al sicuro.", "Beatrice")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("È stato piuttosto difficile restare nascosti tutto il pomeriggio! Soprattutto da quando vi siete imbattuti in quella Theresa...", "Beatrice")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "panic")
	await novel_interface.show_dialog("Seguirci? In segreto?", "Lian")
	# 显示双角色位置移动
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform", "afraid", 0.25)
	await novel_interface.show_dialog("Da quando ci segui? Non me ne sono nemmeno accorto... anche se hai un profumo così dolce!", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Sonya si avvicina a Beatrice, annusando come un cucciolo impaziente che viene trattenuto per il collare (sono io quello che tiene il collare).")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("Ti seguo da questo pomeriggio.", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beatrice sorride, tutta raffinata e di classe, e non posso fare a meno di arrossire.")
	await novel_interface.show_text_only("È vero che ho sentito che ha aiutato con alcuni \"affari speciali\" al SID.")
	await novel_interface.show_text_only("Questa adorabile signora che afferma di essere morta più di settecento anni fa è una strega che ho evocato utilizzando il ciondolo della famiglia di Raphilia nello Sky Hotel.")
	await novel_interface.show_text_only("Si dice che Beatrice sia vittima di una “maledizione” che fa innamorare di lei tutti gli esseri umani del sesso opposto.")
	await novel_interface.show_text_only("Mi sento così nervoso ogni volta che la vedo. Dev'essere a causa di quella maledizione.")
	novel_interface.show_character("ren_fishnet", "shy")
	await novel_interface.show_dialog("Aspetta... quando siamo stati trattenuti alla stazione di polizia...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular", "worry")
	await novel_interface.show_dialog("Ho contattato Mariru non appena sei stato arrestato, ma sembrava essere occupata o in qualche posto con un segnale difettoso e non ha risposto al mio messaggio.", "Beatrice")
	novel_interface.change_expression("smile2")
	await novel_interface.show_dialog("Ho deciso che voi due sareste comunque riusciti a scappare presto, dato che Sonya era lì, quindi sono rimasto qui e ho tenuto d'occhio Elluka.", "Beatrice")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "shy_right")
	await novel_interface.show_dialog("Uh... allora come ha fatto Elluka ad arrivare lassù?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Quando parlo con Beatrice, non so mai dove guardare: in qualche modo sono troppo agitato per incontrare il suo sguardo.")
	await novel_interface.show_text_only("Sonya, invece, studia le mie espressioni con molto interesse. Perché quel moccioso è così fastidioso?")
	novel_interface.show_character("beatrice_regular", "worry")
	await novel_interface.show_dialog("Mentre Sonya ti teneva contro il muro, quel bambino è scappato per seguire un ragazzo che vendeva dolci.", "Beatrice")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("Voi due...", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beatrice sospira pesantemente, come se fossimo totalmente senza speranza. Cosa che non siamo. Non ho nemmeno fatto niente di male!")
	novel_interface.show_character("beatrice_regular", "smile1")
	await novel_interface.show_dialog("Dopodiché, poiché Elluka non è riuscita a trovarvi, è andata al negozio di dolci dove avete mangiato questo pomeriggio. Il negoziante non solo le ha permesso di mangiare gratis, ma le ha anche assegnato un ruolo nell'evento promozionale di stasera.", "Beatrice")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "stare")
	await novel_interface.show_dialog("(Wow, quel negoziante calvo ha un buon occhio per i potenziali favoriti della folla!)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular", "smile1")
	await novel_interface.show_dialog("Non avevo familiarità con Elluka, quindi ho pensato che le piacessero davvero i dolci. Ma ora che la guardo, qualcosa davvero non va...", "Beatrice")
	await novel_interface.show_dialog("Puoi dirlo anche tu, vero, Sonya?", "Beatrice")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "wordless")
	await novel_interface.show_dialog("Non proprio...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya alza lo sguardo in direzione di Elluka.")
	novel_interface.show_character("soya_uniform", "speechless")
	await novel_interface.show_dialog("Non sembra che sia stata minacciata o drogata.", "Soya")
	await novel_interface.show_dialog("Non sembra ferito da nessuna parte. Agire semplicemente in base ai suoi desideri, in un modo adatto a un bambino della sua età.", "Soya")
	novel_interface.change_expression("wordless")
	await novel_interface.show_dialog("L'unica cosa insolita è che sicuramente mangia molto, ma comunque...", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular", "grieved")
	await novel_interface.show_dialog("Secondo le notizie, ci sono già stati violenti scontri tra manifestanti in sei diverse aree della Zona Demilitarizzata Concordata.", "Beatrice")
	novel_interface.change_expression("sad")
	await novel_interface.show_dialog("E questo potrebbe diventare il settimo, anche se non c’è ancora alcun conflitto, semplicemente troppe persone per essere considerate al sicuro.", "Beatrice")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "panic")
	await novel_interface.show_dialog("Non c'è da stupirsi che l'esercito sia qui.\nAllora dobbiamo partire con Elluka il più presto possibile!", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "wordless")
	await novel_interface.show_dialog("Ma come dovremmo superare i suoi fan pazzi?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("Posso aiutarli a distogliere la loro attenzione, ma ci sono così tante persone in giro, quindi probabilmente non riuscirò a tenerli occupati per più di trenta secondi.", "Beatrice")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "worry")
	await novel_interface.show_dialog("Come farai...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Prima che possa finire la domanda, Beatrice mi interrompe.")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("C'è qualcosa che tutti gli accaniti fan di Elluka hanno in comune.", "Beatrice")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "jest")
	await novel_interface.show_dialog("Sono tutti... molto emozionati?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beatrice sorride, alza il braccio destro.")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("No. Questi idioti... sono tutti uomini!", "Beatrice")
	await novel_interface.hide_character()
	
	print("=== 天启篇第10话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
