# apocalypse_ep08.gd - 天启篇第08话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第08话剧本
	apocalypse_ep08_script()

func play_script():
	pass

# 天启篇第08话 - 正式剧本
func apocalypse_ep08_script():
	# scene1 - 街上对话
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("Bem... diga-me então.\nEssa “informação” que você falou... como fazer para obtê-la?", "Soya")
	await novel_interface.show_dialog("Ren, você não cheira nem um pouco como aquelas bruxas, mas definitivamente não é uma pessoa normal, não é? Você é especial...", "Soya")
	await novel_interface.show_dialog("Você simplesmente cheira muito puro!", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya se inclina perto do meu peito e respira avidamente, com os olhos ansiosos.")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_text_only("Isso me lembra um cachorrinho, balançando o rabo furiosamente, esperando que seu dono jogue o frisbee.")
	await novel_interface.show_text_only("Como se ela estivesse dizendo \"brinque comigo! Brinque comigo! Brinque comigo!\"")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Eu... eu sou especial?")
	await novel_interface.show_text_only("Aya disse algo assim antes.")
	novel_interface.show_background("res://assets/images/bg/Fabiola/AI.png")
	await novel_interface.show_dialog("“Ren, você pode ativar a magia das bruxas com uma taxa incrivelmente eficiente...”", "Ai")
	await novel_interface.show_dialog("“Como uma superbateria em um vibrador!”", "Ai")
	await novel_interface.hide_background()
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("(Essa metáfora era necessária?)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Na verdade, também não sei muito sobre essa “informação”...", "Lian")
	await novel_interface.show_dialog("Tudo o que sei é que está gravado em um recipiente chamado Grimoire.", "Lian")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("Ah, certo, você deveria ter visto um antes, quando lutava contra bruxas, certo?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Grimório? É como uma espécie de livro?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Os olhos de Sonya se arregalaram, como se de repente ela tivesse percebido algo.")
	novel_interface.show_character("soya_uniform","trance")
	await novel_interface.show_dialog("Eu me lembro de ver pedaços de papel flutuando quando eu lidava com bruxas às vezes...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sônia relembra.")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Mas as freiras da Abadia sempre diziam que isso poderia contaminar as pessoas, e o pessoal da Penitenciária recolhia todos eles e os queimava numa pilha ao limpar o local.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("(Então eles tratam isso como poluição biológica, hein...)", "Lian")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("(Eles não estão exatamente errados, no entanto...)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("“Bum!”")
	await novel_interface.show_text_only("Há uma explosão repentina do outro lado da rua. Parece um choque elétrico de alta voltagem. Cremes agudos ressoam.")
	novel_interface.show_character("soya_uniform","yell")
	await novel_interface.show_dialog("Que diabos?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya fica sóbria. Algo está errado – ela provavelmente pode sentir o cheiro.")
	novel_interface.show_character("ren_fishnet","serious")
	await novel_interface.show_dialog("Espere, onde está Elluka?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("É quando finalmente percebo a ausência da garotinha que deveríamos cuidar.")
	await novel_interface.show_text_only("Meu cérebro fica em branco em um instante. Então é assim que é ser uma mãe que perde o filho no supermercado, né?")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("Alguém a sequestrou?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ela não é uma criança comum...")
	await novel_interface.show_text_only("Se ela não tomar cuidado...")
	await novel_interface.show_text_only("Ela pode liberar mais de um milhão de volts de eletricidade sem sequer tentar!")
	await novel_interface.show_text_only("Sonya imediatamente corre em direção ao local da comoção, eu seguindo de perto.")
	await novel_interface.show_text_only("Os policiais patrulhadores chegaram antes de nós e estão apitando, tentando dispersar a multidão.")
	await novel_interface.show_dialog("Por favor, pare de empurrar! Esta é uma área perigosa!", "Guarda de segurança A")
	await novel_interface.show_dialog("Ei! Você! Não chegue mais perto!", "Guarda de segurança B")
	await novel_interface.show_text_only("Dois policiais tentam ficar no caminho de Sonya enquanto ela corre em direção a eles.")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("D-desculpe, estamos procurando um amigo—", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Antes mesmo que eu possa terminar a frase, Sonya bate sem esforço no pescoço de um dos policiais com a mão direita.")
	await novel_interface.show_text_only("O oficial atarracado perde a voz e cai no chão, fazendo sons sufocados.")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("Respire?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Antes que o outro policial possa reagir, Sonya deita-se de costas em um piscar de olhos e dá um golpe no pescoço dele.")
	await novel_interface.show_text_only("Seus movimentos são limpos, suaves, como se tivessem sido ensaiados inúmeras vezes.")
	await novel_interface.show_text_only("Em três segundos, um policial está inconsciente no chão e o outro está de joelhos, com falta de ar. Sonya desaparece na multidão.")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Eu cuidadosamente circunavego o policial inconsciente e dou um tapinha nas costas do pobre rapaz que está tendo espasmos no chão, lutando para respirar.")
	await novel_interface.show_text_only("O homem grande avança ao meu toque, caindo com o rosto no chão com um estrondo.")
	await novel_interface.show_text_only("Todas as multidões ao redor me olham com horror. Uma senhora arrasta seu filho alguns passos para trás.")
	await novel_interface.show_text_only("Um cara com uniforme de equipe de manutenção de uma empresa de eletricidade até pega o telefone e começa a filmar.")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("Ei, não é minha culpa!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mas... com certeza parece que sim!")
	await novel_interface.show_text_only("Engulo em seco, colocando minha melhor cara impassível enquanto me espremo na multidão à frente, onde a forte explosão aconteceu.")
	await novel_interface.show_text_only("O chão está marcado por marcas de queimaduras pretas em forma de galhos. No meio está um homem de meia-idade, cabelo queimado, parecendo muito morto.")
	await novel_interface.show_text_only("Ele está vestindo uma camiseta temática de um anime que estava na moda há alguns anos. A imagem das três garotas do anime no tecido creme está meio queimada.")
	await novel_interface.show_text_only("O travesseiro corporal deitado ao seu lado e a capa do telefone em sua mão apresentam designs de lindas garotas de anime. Bem, é muito óbvio agora—")
	await novel_interface.show_text_only("Os deuses devem ter enviado um raio sobre ele para puni-lo por seu complexo de lolicon.")
	await novel_interface.show_text_only("Sonya está ajoelhada ao lado dele, a mão esquerda em seu peito, o punho direito erguido—")
	novel_interface.show_character("ren_fishnet","serious")
	await novel_interface.show_dialog("Sônia! O que você fez com aqueles oficiais?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Antes que eu possa terminar a frase, o punho de Sonya atinge com força as costas da mão esquerda. Seu poder atinge o peito do morto, o impacto é amortecido pela mão no lugar.")
	await novel_interface.show_text_only("Em poucos segundos, o homem tem um ataque e solta duas baforadas de fumaça preta. A multidão ao redor suspira em voz alta.")
	await novel_interface.show_text_only("Sonya então puxa a cabeça dele para perto dela e dá dois tapas na bochecha dele.")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Acorde! Acordar!", "Soya")
	await novel_interface.show_dialog("Você já viu uma garotinha de cabelo azul por aí? Parece um pouco com o do seu travesseiro corporal.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("O homem olha para o travesseiro corporal e começa a chorar como uma alma penada, rastejando para longe de quatro. A julgar pela mancha colorida perto da virilha, ele deve ter molhado as calças.")#文本错误
	novel_interface.show_character("ren_fishnet","speechless")
	await novel_interface.show_dialog("(O coitado deve estar traumatizado...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya se vira para me encarar.")
	novel_interface.show_character("soya_uniform","yell")
	await novel_interface.show_dialog("Então os poderes de Elluka são tão insanos?\nVocê deveria ter me contado antes de me deixar sair com ela!", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("Vamos, você não é melhor do que ela. Aqueles dois policiais—", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Tch, eles vão ficar bem.", "Soya")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("Tive que tirá-los do caminho. Ou então, se te segurassem, estaríamos separados e eu ficaria chocado com a tornozeleira.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","sprite")
	await novel_interface.show_dialog("Isso não justifica prejudicar a polícia! Se você ficar chocado, a culpa é sua!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Estou prestes a conversar com Sonya quando sinto algo me picar duas vezes nas costas.")
	novel_interface.show_character("ren_fishnet","serious")
	await novel_interface.show_dialog("Hein?", "Lian")#文本错误
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","yell")
	await novel_interface.show_dialog("Atrás de você!", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Era um Taser X46. A queimação intensa faz com que meus músculos contraiam.")
	await novel_interface.show_text_only("E então tudo fica preto...")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…")
	await novel_interface.show_text_only("…")
	await novel_interface.show_text_only("Acordo com a música do interlúdio do noticiário noturno.")
	
	# scene2 - 拘留室
	novel_interface.show_background("res://assets/images/bg/Soya/Police_Cells.png")
	novel_interface.change_music("res://assets/audio/music/Brooklyn.mp3")
	await novel_interface.show_dialog("O homem-bomba do metrô New Opulentia postou outro anúncio de seus futuros esquemas de bombardeio. As bombas anteriores descobertas foram desmanteladas. A cena está sendo limpa.", "Notícias")
	await novel_interface.show_dialog("Segundo o porta-voz da corporação de gás, sua equipe está atualmente investigando fontes de vazamento de gás na cidade. Gostaríamos de alertar todos os cidadãos para evitarem áreas próximas às fontes.", "Notícias")
	await novel_interface.show_dialog("Mais de dez mil manifestantes reuniram-se na Primeira Avenida, em frente à sede do Congresso Unido...", "Notícias")
	await novel_interface.show_dialog("A reunião fechada do Fórum Internacional da Paz ainda está em andamento. Os manifestantes estão exigindo que os líderes das nações terminem a reunião e se manifestem imediatamente...", "Notícias")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Ah, você está acordado?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Esfrego os olhos, enxugo a baba e me encontro em uma sala cheia de gente.")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Onde... estamos?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("A sala de detenção temporária na delegacia. Não muito longe da Rua Eletrônica.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("Entendo... espere, o que?", "Lian")
	await novel_interface.show_dialog("Delegacia de polícia? Detenção?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("A névoa em minha mente se dissipa imediatamente enquanto examino o que me rodeia.")
	await novel_interface.show_text_only("Dois lados da sala de detenção são paredes, o outro lado é um balcão e o restante é uma barreira feita de barras de liga leve. Nenhum dos detidos foi algemado. Todos nós podemos nos mover livremente.")
	await novel_interface.show_text_only("A sala já está cheia – não muito longe de nós, encostados na parede, há vários homens musculosos, bêbados demais. Todos eles apresentam lesões esportivas aqui e ali.")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("(Eles brigaram depois de beber? Seus rostos ainda estão sangrando...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("No canto ao lado do balcão, alguns delinquentes estão agachados. Eles ficam olhando para mim e para as três senhoras vestidas de maneira escassa sentadas perto de nós, claramente interessadas.")
	await novel_interface.show_text_only("Certas carreiras consideradas legais na Nova Opulência são restritas em território internacional. Isso não desanima aqueles que, na área da embaixada, pensam que podem comprar todos os tipos de serviços, desde que tenham dinheiro...")
	await novel_interface.show_text_only("Espere! Essas senhoras e eu... estamos todos usando meias arrastão. Quatro pares seguidos...")
	novel_interface.show_character("ren_fishnet","shy_left")
	await novel_interface.show_dialog("(Eu... eu não sou um deles!)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Já passei por muita coisa esses dias, mas é a primeira vez que chego em uma delegacia. Não consigo deixar de me sentir nervoso.")
	await novel_interface.show_text_only("Começo a me imaginar em uma cela de prisão. E se meu colega de cela for um canalha que usa cueca por fora? Ou um homem musculoso que não para de sorrir como um pervertido...")
	await novel_interface.show_text_only("Um arrepio percorre minha espinha.")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("(Ah, espere, não serei colega de cela de homens musculosos... já que, em vez disso, eles vão me colocar em uma prisão feminina!)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("... De jeito nenhum!")
	await novel_interface.show_text_only("Mesmo assim, ainda não recebi mais pedidos de Mariru. Isso significa que o objetivo que ela tem em mente para mim continua o mesmo:")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Elluka! Onde está Elluka?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sônia dá de ombros.")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Os policiais parecem muito ocupados hoje, mas até agora não houve notícias de outras pessoas levando choques elétricos.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Já que o noticiário noturno está passando... devo ter dormido por mais de uma hora...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Acabei de me levantar também. Provavelmente espalharam algum tipo de droga tranquilizante nas agulhas do seu novo modelo de taser.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya aproxima a cabeça da minha e sussurra.")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("Você está se sentindo melhor agora? É hora de irmos.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("Ir? Ir como?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya arranca um botão de sua capa, revelando uma pequena agulha com menos de 2 mm de comprimento.")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("Falando em drogas tranquilizantes...", "Soya")
	await novel_interface.hide_character()

	print("=== 天启篇第08话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
