# apocalypse_ep16.gd - 天启篇第16话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第16话剧本
	apocalypse_ep16_script()

func play_script():
	pass

# 天启篇第16话 - 正式剧本
func apocalypse_ep16_script():
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	await novel_interface.show_text_only("Sonya’s face is flushed under the dim yellow light. The water droplets course down her slim, bare calves, leaving a puddle on the ground.")
	await novel_interface.show_text_only("She sits perched on the fountain’s marble edge like a helpless animal. She gazes at me, eyes innocent yet so mesmerizing—")
	await novel_interface.show_text_only("My heart leaps, and I can feel my face heating up.")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Sonya...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I had been horrified when I heard her backstory, wanting nothing more to find her and comfort her immediately. But now—my brain is completely blank.")
	await novel_interface.show_text_only("Kind of like those bumbling idiots you see in manga—striding to their crush to confess in a burst of fake bravado, then forgetting everything they had rehearsed the second they see the crush.")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("(Brain, do something! Geez!)", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","smile",0.25)
	await novel_interface.show_dialog("Hey...", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Sonya licks her lips and smiles softly.")
	novel_interface.show_character("ren_fishnet","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("soya_uniform","normal",0.25)
	await novel_interface.show_dialog("You smell... interesting...", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("She crawls over in my direction on the marble step. I can see the beehive pattern on her anklet reflecting off the light.")
	await novel_interface.show_text_only("It’s an anklet manufactured by our SRD with Substance H armor materials. Looks flimsy, but is actually extremely sturdy.")
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("Just like I expected...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya grabs my hand, presses her nose close to my belly, and inhales greedily.")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("Ren is the best indeed!", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("W-what?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I take a few steps back, confused. What happened to her the minutes I was gone?")
	await novel_interface.show_text_only("Sonya sits up lazily on the marble step and smooths her hair.")
	novel_interface.show_character("ren_fishnet","awkward")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","smile",0.25)
	await novel_interface.show_dialog("Elgana told you, huh?", "Soya")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Your body... just... what happened to you?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("I didn’t want you to know.", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Sonya turns away, voice diminishing in volume.")
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("Everyone who knows my secret ends up distancing themselves from me...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I can’t help recalling the way Elgana spoke to Sonya a while ago.")
	await novel_interface.show_text_only("She knows that Sonya won’t live long, and probably thought it’d be better to stay away. It’d hurt less when the inevitable happens, right?")
	await novel_interface.show_text_only("Besides, Elgana is religious. The young girl, forbidden to enter holy buildings, might seem like a bad omen to her.")
	await novel_interface.show_text_only("The ID card representing her Judgment Knight title, instead of granting her the highest immunity, actually acts as a sort of exiling order...")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("But it’s fine. I know you won’t be like them...", "Soya")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Right?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya asks, cautiously, eyes trained on me. My lips tremble a little, and I move close to pat her head.")
	await novel_interface.show_text_only("Sonya smiles, closes her eyes, and nudges into my palm.")
	await novel_interface.show_text_only("She then stretches and looks up at the mural near the top of the church, ever so glorious under the night sky.")
	await novel_interface.show_dialog("He probably hates me now...", "Soya")
	await novel_interface.show_dialog("Though I guess he never loved me anyway.", "Soya")
	await novel_interface.show_text_only("I’m about to ask her who “he” is, when Sonya glances at my dress and smirks.")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("Well, you have a lot of secrets of your own, don’t you?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("What?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She wraps her arms around me before I can react.")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("You know why I didn’t ask Mariru about your identity a while ago?", "Soya")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("It was because I wanna find out the answer to this fascinating puzzle myself!", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("Hey!", "Lian")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("D-don’t—", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("My phone rings all of a sudden. Beatrice. Sonya is still wrapped around me even as I take the call.")
	await novel_interface.show_text_only("I have to hold the phone with one hand and shove at Sonya with another in a futile attempt to keep her hands off me. My palm lands on her nose and mouth.")
	await novel_interface.show_dialog("Mmmff! Mmff!", "Soya")
	await novel_interface.show_dialog("Ren? I’m at the hospital.", "Beatrice")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("Beatrice! How’s John?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya leaps up and snatches my phone away, turning it on broadcast.")
	await novel_interface.show_dialog("They have him hooked to a machine... need to get some fluids into him. His life is not in danger. He’s asleep right now, they injected him with some painkillers.", "Beatrice")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("... Oh, so he does feel pain?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Yeah. The nurse says it was a temporary loss of the ability to sense pain. She knows because he’s the fourth patient tonight that has come in with such a situation.", "Beatrice")
	await novel_interface.show_dialog("There was a middle-aged man who stepped barefoot on the searing hot engine cover of a car during a riot on Electronics Street for a better view.", "Beatrice")
	await novel_interface.show_dialog("The people around him smelled something burning and he only realized then. What was weird was that his hair was burnt too...", "Beatrice")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("(Maybe it’s the same guy whom Elluka shocked?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Another patient was a reporter from Newmoridas. She shoved her way to the front of the protestors only to find that she couldn’t press the shutter. Turned out she broke a finger along the way.", "Beatrice")
	await novel_interface.show_dialog("There was a repairman from the Hovering Palace too. When he was working, there was an electric shock and he began bleeding internally. Yet he had no idea! Continued chatting with his colleague on the phone for half an hour...", "Beatrice")
	await novel_interface.show_dialog("He only realized something was off when he could no longer see in one of his eyes due to it being bloodshot.", "Beatrice")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("…", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I feel a chill run down my spine.")
	await novel_interface.show_text_only("Four completely unconnected people. Different ages, genders, nationalities, careers. Yet they show signs of the same—and very uncommon—disorder.")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Mariru said that the riots tonight might have something to do with Substance H...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Could be.", "Beatrice")
	await novel_interface.show_dialog("Aya’s already hacked into the surveillance data of the security soldiers. You have temporary access on your phone too, right?", "Beatrice")
	await novel_interface.show_dialog("When retracing the activity records of these four people, we found that they’ve all been to at least one of the seven rioting areas this afternoon.", "Beatrice")
	await novel_interface.show_dialog("That repairman was actually the safety inspection head of Johnson Heavy Industries!", "Beatrice")
	await novel_interface.show_dialog("He spoke to a man in a windbreaker for five minutes at around six tonight, on the crossroads near Electronics Street.", "Beatrice")
	await novel_interface.show_dialog("That man seemed to have deliberately avoided all areas with surveillance cameras. But we still got his face when he passed by an alley...", "Beatrice")
	await novel_interface.show_text_only("Beatrice begins to speak slower, placing emphasis on every word.")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("It’s the man who attacked us at Sky Hotel.", "Beatrice")
	novel_interface.show_background("res://assets/images/bg/Soya/Monitor_Y.png")
	await novel_interface.show_text_only("She sends the screenshot she got to me.")
	await novel_interface.show_dialog("Jacob?", "Lian")
	await novel_interface.show_text_only("Jacob Schmidt... weaponry specialist in the United Congress, representative of Masada Ford, the Third Academy City.")
	await novel_interface.show_text_only("That guy who treated Elluka as a weapon and a mere tool...")
	await novel_interface.show_text_only("Afterwards, he led a group of lackeys to attack me, Beatrice, Annie and Raphilia in Sky Hotel. Even used Substance H weapons.")
	await novel_interface.show_text_only("Annie was heavily injured by one of their electric weapons. Luckily Raphilia was there...")
	await novel_interface.show_text_only("Not even Mariru was able to find data on that man. We could only deduce that he worked under Menorah, intelligence agency of the Third Academy City.")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("Wait, Johnson Heavy Industries... you mean Johnson Substation?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("That was where Annie and I first met Elluka and Igor. We wouldn’t have made it out alive without Mariru’s timely aid.")
	await novel_interface.show_dialog("I interrogated the repairman a bit, but all he knew was that Igor was a representative of one of their company’s collaborators.", "Beatrice")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("Why would Johnson collaborate with Igor...?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("The United Congress decided only two weeks ago to fully upgrade the surveillance system in the city before the Forum of Peace began.", "Beatrice")
	await novel_interface.show_dialog("The cameras were mostly in position already, but the power supply for the lighting was independently provided and there wasn’t enough time to expand the circuit coverage to most blocks.", "Beatrice")
	await novel_interface.show_dialog("So they had to ask a collaborator to provide batteries as a temporary measure.", "Beatrice")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("Batteries?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("You know, a transparent vessel the size of a thumb. Electrodes on both ends. Glowing sticky liquid on the inside. Heard it could keep the surveillance devices running for twenty days.", "Beatrice")
	await novel_interface.show_dialog("I already sent a sample to the headquarters.", "Beatrice")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("Sounds like the “food” Elluka offered me when we first met...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She wanted to thank me for the chocolate... guess that wasn’t supposed to be edible!")
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("Hey, that Igor you're talking about... is it that guy whom you totally owned?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya asks, eyes wide like a curious child.")
	await novel_interface.show_dialog("Ren...", "Beatrice")
	await novel_interface.show_dialog("You two are pretty \"close\", but seems that you've leaked a bit too much to her, haven't you?", "Beatrice")
	await novel_interface.show_text_only("No way! We're not \"close\"!")
	await novel_interface.show_dialog("Aren't you worried that Mariru would punish you?", "Beatrice")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("I didn't leak—", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Mmph... mmmm!", "Lian")
	await novel_interface.show_text_only("Sonya places a hand over my face, raising the phone high in one hand.")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("Ren told me everything, actually!", "Soya")
	await novel_interface.show_dialog("Are you really the same beauty in Dante's masterpiece?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Hearing us play-fighting, Beatrice bursts out giggling.")
	novel_interface.change_background("res://assets/images/bg/Soya/University_Hospital.png")
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("You know about this, too? Guess Mariru's permitted Ren to tell you then.", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("So? Are you?", "Soya")
	await novel_interface.show_text_only("Sonya persists, like a big dog wagging her tail.")
	novel_interface.show_character("beatrice_regular","smile3")
	await novel_interface.show_dialog("Yes. I am indeed the Beatrice you speak of. My father was Folco Portinari.", "Beatrice")#文字错误
	novel_interface.change_expression("smile2")
	await novel_interface.show_dialog("I've only seen Dante once, actually. It was on a family gathering on May Day. I was really young then, though. Even younger than Elluka.", "Beatrice")
	novel_interface.change_expression("grieved")
	await novel_interface.show_dialog("I found out only later that I'd drunken that glass of poison for over a dozen years when he wrote the Divine Comedy.", "Beatrice")
	await novel_interface.show_dialog("It was simply one-sided attraction on his part.", "Beatrice")
	novel_interface.change_expression("smile2")
	await novel_interface.show_dialog("Still, I have to admit that his works are impressive.", "Beatrice")
	await novel_interface.show_dialog("He dared to mock the pope in his work, and even described me waiting for him at the gates of heaven and guiding him through the levels of hell.", "Beatrice")
	novel_interface.change_expression("smile1")
	await novel_interface.show_dialog("It was probably wish-fulfillment for him. Maybe also a sort of revenge.", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Revenge?", "Lian")
	novel_interface.show_character("beatrice_regular","smile2")
	await novel_interface.show_dialog("Well, that secret is mine to keep.", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beatrice gazes upward at the starry skies.")
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("Did you know...", "Beatrice")
	await novel_interface.show_dialog("One of the asteroids that rotate around the solar system was named after me. The discoverer was inspired by my image in Dante’s work.", "Beatrice")
	await novel_interface.show_dialog("If only I could write my own response to his poem...", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_text_only("Beatrice finally hangs up after saying she's going to call Mariru.")
	await novel_interface.show_text_only("Sonya sits on the fountain edge and continues playing with my phone, ignoring my requests for her to return it.")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("Tch... you even locked up your photo album? It's like admitting there's something incriminating inside...", "Soya")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_fishnet","stare",0.25)
	await novel_interface.show_dialog("At least it's better than you going through it...", "Lian")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Anyway, let's check the surveillance footage first. Spying on people with drones really is a great idea!", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("You'd better not do anything like that!")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Umm—", "Soya")
	await novel_interface.show_dialog("Where am I…", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I move closer to see the real-time surveillance footage from the drone we posted in front of the United Congress on First Avenue.")
	novel_interface.change_background("res://assets/images/bg/Soya/Cordon.png")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("The security soldiers have set up a strict defense line in front of the building.")
	await novel_interface.show_text_only("On either side of the long row of riot shields, the tension between the armed soldiers and the antsy protesters is palpable.")
	await novel_interface.show_text_only("Several protesters keep trying to ram themselves into the wall of shields, while some are throwing things at the soldiers from afar.")
	await novel_interface.show_text_only("This includes a crudely-made Molotov cocktail, which lands beyond the defense line, making an eerily beautiful arc in the air.")
	await novel_interface.show_text_only("Several soldiers hurry over to put out the fire with extinguishers, while the injured ones are dragged to the back to be treated. They seem to be quite experienced in dealing with things like this.")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("soya_uniform","wordless")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_fishnet","upset",0.25)
	await novel_interface.show_dialog("Looks like a mess over there...", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("If that thing had fallen into the protesting crowds instead...")
	await novel_interface.show_text_only("Sonya doesn’t seem bothered by my concerns. She simply switches to another screen, displaying footage from another drone, and scowls.")
	await novel_interface.show_text_only("She then begins comparing the footage from different drones and marking out the corresponding locations on a big map.")
	await novel_interface.show_text_only("The seven areas where riots happened form a perfect hexagram—with six of the dots being the sharp points of the star and the remaining as the center.")
	novel_interface.show_character("soya_uniform","trance")
	await novel_interface.show_dialog("Is this...", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("You found something?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Ren, I need to head over to this place right away.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She points at a spot in the middle section of First Avenue, face solemn.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Don’t worry, I’m not going to rush into the crowds or anything. You can do whatever you want as long as you’re not more than 650 feet away from me.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Just what are you planning to—", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("Oh, I need to go back for something. Wait here for me!", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Before I can finish my question, Sonya has put her shoes back on and sprinted off to her room.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("…")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	await novel_interface.show_text_only("She reappears with a black bag slung over her shoulder. Whatever is inside seems quite cumbersome.")
	await novel_interface.show_text_only("She takes my hand like it’s the most natural thing ever, and steers us towards the black SUV waiting for us at the entrance.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("To First Avenue.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("But aren’t people protesting there?", "Driver")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("We can just go around the crowds. I’ll point the way.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("It’s not even midnight yet, but the roads are surprisingly clear. The plump driver tuts.")
	await novel_interface.show_dialog("Traffic is usually nuts on this road, but it’s real smooth today. Guess most people who know what’s good for themselves went home already.", "Driver")
	await novel_interface.show_text_only("I guess that means we’re the ones who don’t know what’s good for themselves!")
	novel_interface.show_background("res://assets/images/bg/Soya/Parade.png")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("I attempt to contact Mariru and Beatrice on the car, but no one picks up.")
	await novel_interface.show_text_only("Within ten minutes, we arrive on a smaller road to the east of the middle section of First Avenue.")
	await novel_interface.show_text_only("The driver tells us that he’ll wait there for us and even warns us “two young ladies” to be careful out there at night.")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("Haha... ha...", "Lian")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("(So innocent, well-meaning souls like this exist in the SID too, huh?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Across the street, we see hordes of marchers, holding up banners and messily chanting slogans.")
	await novel_interface.show_text_only("First Avenue is filled with people, people and more people. The crowds seem to be advancing—towards a finishing point they’ll never reach.")
	novel_interface.show_character("ren_fishnet","speechless")
	await novel_interface.show_dialog("If they keep on going like this, when they reach the congress building the ten thousand people up ahead would probably be crushed...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Don’t you think these people are acting a bit weird?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I’ve seen lots of demonstrations in New Opulentia, but none of such an impressive scale. Not even close.")
	await novel_interface.show_text_only("In contrast to the tense atmosphere up there at the defense line, the crowds around us seem less violent. Some are chanting loudly, that’s true—")
	await novel_interface.show_text_only("But a lot of others seem to be simply here to enjoy the atmosphere. Some are even taking selfies under flashing billboards, coffee and junk food in hand.")
	await novel_interface.show_text_only("I watch as a middle-aged man, after posing for the camera, slaps on a filter and shares the pic on his social media account.")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("They seem... pretty chill?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("There aren’t any security soldiers around. They’re probably too busy dealing with the ones up ahead to bother with these peaceful civilians.")
	novel_interface.show_character("ren_fishnet","stare")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","wordless",0.25)
	await novel_interface.show_dialog("Large-scale demonstrations are usually like this, actually. There’d be violent ones and peaceful ones. But don’t you think the line between these two sections is a bit too well-defined?", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Only then do I realize that the people really do seem to be adhering to certain “borders”. Most of the crowd, in fact, is gathered across the street from us, even though there’s plenty of space for them to stand on our side.")
	novel_interface.show_character("ren_fishnet","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("soya_uniform","wordless",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Is this what they call herd behavior?", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Blending in to the crowds to feel safe... like penguins that tend to travel in huddles. It’s natural for “borders” to form in such situations.")
	novel_interface.show_character("ren_fishnet","speechless")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light(0)
	novel_interface.show_2nd_character("soya_uniform","wordless",0.25)
	novel_interface.character_2nd_dark(0)
	await novel_interface.show_dialog("Still, what did you say you wanted to do here anyway?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speechless")
	await novel_interface.show_dialog("Eh, let’s go upstairs first.", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Sonya drags me into an office building by the road. She knocks out the security with practiced ease, snatches the entry card he’s wearing on the neck, and scans it in the elevator. It takes us straight up to the roof.")
	novel_interface.change_background("res://assets/images/bg/Soya/First_Avenue.png")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	novel_interface.show_character("ren_fishnet","serious")
	await novel_interface.show_dialog("Wow, that’s a lot of people!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("From our vantage point, I can see only too clearly just how crowded it is down there.")
	await novel_interface.show_text_only("They’re no bigger than ants from my point of view, but not even ants would be packed so tightly together, would they?")
	await novel_interface.show_text_only("Sonya retrieves a pair of small binoculars from her bag and scans the crowd underneath.")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Hmm, not over there...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She grabs my phone and begins switching between surveillance footages again.")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Not there either...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She finally sits down and heaves a sigh, as if relieved.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("So it’s just a coincidence, huh...", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("Come on, what are you looking for exactly?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("A door...", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("Door?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya continues gazing down at the sea of people in silence, ignoring my question.")
	await novel_interface.show_text_only("I decide not to pester her further since everything seems fine so far anyway. Instead, I sit down beside her and let myself enjoy the view.")
	await novel_interface.show_text_only("Everything seems so trivial somehow, when we’re so high up.")
	await novel_interface.show_dialog("There must be more than ten thousand people down there...", "Soya")
	await novel_interface.show_dialog("Probably...", "Lian")
	await novel_interface.show_dialog("When you look at them like this, do you feel like you’re one of them?", "Soya")
	await novel_interface.show_text_only("Gently, I shake my head.")
	await novel_interface.show_text_only("The sprawling crowds down there seem to have become a brand-new life form in itself—a living, breathing being that moves as the humans who compose it do.")
	await novel_interface.show_text_only("It gives me the creeps. I certainly wouldn’t want to be one of them.")
	await novel_interface.show_dialog("Hey...", "Soya")
	await novel_interface.show_dialog("Hmm?", "Lian")
	await novel_interface.show_dialog("I saw this documentary when I was little, in the abbey.", "Soya")
	await novel_interface.show_dialog("It was set in the South Pole. Everything is white there. No landmarks for reference.", "Soya")
	await novel_interface.show_dialog("The only way penguins can tell directions is their instincts. And they have to mass-migrate twice each year in order to reproduce.", "Soya")
	await novel_interface.show_dialog("The newborn penguins have to learn to follow their group immediately after they’re born, so that they can reach the ocean where there’s food.", "Soya")
	await novel_interface.show_dialog("Sometimes there are more than two hundred thousand penguins moving all at once on the South Pole ice shelf. Their procession is orderly, everyone going in the same direction.", "Soya")
	novel_interface.change_background("res://assets/images/bg/Soya/Penguin.png")
	await novel_interface.show_dialog("But every year, for some reason, some newborn penguins want to go another way.", "Soya")
	await novel_interface.show_dialog("Even if the adult penguins try to correct them, even if they’re totally alone, even if there’s a blizzard—they insist on moving away from the ocean.", "Soya")
	await novel_interface.show_dialog("But the South Pole is an uninhabited, isolated continent. The environment there is never benevolent towards these baby penguins.", "Soya")
	await novel_interface.show_dialog("However, if the climate changes, changes drastically for the first time in a million years maybe—perhaps the baby penguins who go the other way will be the only survivors.", "Soya")
	await novel_interface.show_dialog("—In a way, they’re a sort of insurance mechanism for the species. They can save their species from going instinct.", "Soya")
	novel_interface.change_background("res://assets/images/bg/Soya/First_Avenue.png")
	await novel_interface.show_text_only("Sonya falls silent after she finishes recounting what she had seen.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("When I was little, I always thought... there must be tons of fascinating things out there in the world, waiting for me to discover them.", "Soya")
	await novel_interface.show_dialog("And I want to see them all, experience them all.", "Soya")
	novel_interface.change_expression("wordless")
	await novel_interface.show_dialog("But curiosity comes with a price...", "Soya")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("The symptoms Beatrice just described, and the locations of the seven areas where there were riots... they both remind me of that mission three years ago...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I gulp in surprise. So she’s actually come across symptoms like that before?")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("There was a huge calamity somewhere in South America back then. So huge it would have likely led to an XK-class apocalypse.", "Soya")
	await novel_interface.show_dialog("The first batch of black-robed monks dispatched by the CDF all perished. The other monks were horrified and refused to go.", "Soya")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("But I volunteered. I was that baby penguin...", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","serious")
	await novel_interface.show_dialog("What exactly happened there?", "Lian")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/BlackGate.png")
	await novel_interface.show_dialog("A pair of pure black gates appeared out of nowhere on the walls of a small church. And behind the half-open doors are nothing but bright, blinding golden light...", "Soya")
	await novel_interface.show_dialog("In a two-mile radius with the gate as the central point, all electronics stopped functioning. No one who entered the area left alive.", "Soya")
	await novel_interface.show_dialog("That was all we knew back then.", "Soya")
	await novel_interface.show_dialog("According to the Pope, it was like the pearly gates to Heaven had been opened.", "Soya")
	novel_interface.change_background("res://assets/images/bg/Soya/First_Avenue.png")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("And my mission was to close the gates back again.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I barely notice that I’m holding my breath as Sonya recounts her story.")
	novel_interface.show_character("soya_uniform","speechless")
	await novel_interface.show_dialog("Heaven, they called it. Ha.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She shakes her head with a snort.")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("I arrived to find that, with the church as central point, spreading out in six symmetrical directions, were six “lines”—on them lay tens of thousands of twisted bodies.", "Soya")
	await novel_interface.show_dialog("Male, female, elderly or young—those people all died from fighting each other. You could tell from their wounds.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("(Sounds like something those contaminated witches would do...)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("I guess, if Hell exists... that was it.", "Soya")
	await novel_interface.show_dialog("The only reason I arrived at the door alive was probably because I was the only one in the area. No one to fight.", "Soya")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/BlackGate.png")
	await novel_interface.show_dialog("I didn’t find the light too bright when I was there, in front of that door. It felt... warm, relaxing. As if it wanted to suck me right inside.", "Soya")
	await novel_interface.show_dialog("I could sense some sort of spirit—one with a presence impossible to ignore—trying to convince me to open the gate up wide, or simply enter the gates.", "Soya")
	await novel_interface.show_dialog("It didn’t say it in words, but that was what I felt.", "Soya")
	await novel_interface.show_dialog("If I entered the gateway, I’d become one with the golden light.", "Soya")
	await novel_interface.show_dialog("If I opened the gate up wide, everyone in the world would become one with the golden light.", "Soya")
	novel_interface.change_background("res://assets/images/bg/Soya/First_Avenue.png")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Unfortunately, I wasn’t interested at all in “becoming one” with anything...", "Soya")
	await novel_interface.show_dialog("So I simply closed the gate while the spirit yelled profanities at me.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("Hahahaha...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("The second our eyes meet, we burst out laughing.")
	await novel_interface.show_text_only("Down there, countless people are marching. And here we are, on the roof over three hundred feet above them, laughing our heads off.")
	await novel_interface.show_dialog("Ugh—", "Soya")
	await novel_interface.show_text_only("Sonya inhales deeply, trying to calm herself down. She had laughed so hard she was practically in tears.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("After I closed the gate, the whole thing just disappeared. The bare wall was all that remained.", "Soya")
	await novel_interface.show_dialog("After that incident, the United Congress began to support our church.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("So that was why the church used to barely get by but can now build gigantic religious buildings, huh?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Still, I had to touch the pure black surface of the door in order to close it.", "Soya")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("And the black substances gradually invaded my body. I guess that’s the price I have to pay...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya looks down, a bit melancholy.")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Sonya.", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I place my hands on her fragile shoulders and gaze deeply into her eyes.")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("The little penguins who go in the opposite direction do so out of their own will, not because of some kind of insurance mechanism for the survival of the species.", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("They’re just really curious about what’s on the other side.", "Lian")
	await novel_interface.show_dialog("Some of our ancestors were like those penguins too. Following their own desires, they set off from Africa and eventually populated the whole world.", "Lian")
	await novel_interface.show_dialog("Humans are everywhere now. In the coldest, hottest locations in the world, in places that are dark half the year and bright the other half, even all the way across the sea!", "Lian")
	await novel_interface.show_dialog("You’re not some sort of mechanism. You’re—", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("I’m...?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Uh.", "Lian")#文字错误
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","wordless",0.25)
	await novel_interface.show_dialog("Hmm?", "Soya")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Uh...", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Aaaaaaah!")
	await novel_interface.show_text_only("Why can’t I find the right words?")
	novel_interface.show_character("ren_fishnet","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("soya_uniform","jest",0.25)
	await novel_interface.show_dialog("Hm?", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Sonya elbows me in the gut.")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("Weren’t you eloquent seconds ago?", "Soya")
	await novel_interface.hide_character()
	
	print("=== 天启篇第16话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
