# apocalypse_ep12.gd - 天启篇第12话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第12话剧本
	apocalypse_ep12_script()

func play_script():
	pass

# 天启篇第12话 - 正式剧本
func apocalypse_ep12_script():
	# scene1 - 开场黑屏到秋叶原
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN.png")
	novel_interface.change_music("res://assets/audio/music/Brooklyn.mp3")
	await novel_interface.show_text_only("Beatrice nhấc một chân lên lan can và hét vào micro.")
	await novel_interface.show_text_only("Dàn âm thanh nổi bật hết cỡ sẽ truyền giọng nói của cô đến tận cuối Phố Điện Tử.")
	novel_interface.show_character("beatrice_regular", "angry")
	await novel_interface.show_dialog("Tất cả các bạn đều là rác rưởi!", "Beatrice")
	await novel_interface.show_dialog("Xuống địa ngục đi, lũ biến thái!", "Beatrice")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "wail")
	await novel_interface.show_dialog("Cái gì?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform", "jest", 0.25)
	await novel_interface.show_dialog("Ờ...", "Soya")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("(Cô ấy chỉ… nói vậy để thu hút sự chú ý thôi, đúng không? Cô ấy không có ý đó, phải không?)", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Và thu hút sự chú ý cô ấy đã làm. Mọi ánh mắt lúc này đều đổ dồn vào cô.")
	await novel_interface.show_text_only("Ngay khi họ nhìn thấy khuôn mặt của Beatrice, những người đi đường không thể rời mắt được nữa. Họ đứng đó, miệng há hốc, kinh ngạc trước đôi giày cao gót màu đỏ sáng bóng và bóng tối quyến rũ dưới chiếc váy ngắn của cô.")
	novel_interface.show_character("beatrice_regular", "bored")
	await novel_interface.show_dialog("Rác rưởi, tất cả các bạn! Lũ bọ bẩn thỉu! Bạn muốn tôi dẫm chết tất cả các bạn phải không?", "Beatrice")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("Bạn không xấu hổ sao?", "Beatrice")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "panic")
	await novel_interface.show_dialog("(Có lẽ cô ấy thực sự có ý đó...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Hầu hết mọi người trên đường lúc này đều đang nhìn chằm chằm. Ngay cả những linh vật từng nhảy múa trên nóc những chiếc xe tải khác cũng dừng màn trình diễn của mình để xem cảnh tượng này.")
	await novel_interface.show_text_only("Sonya và tôi tận dụng cơ hội để leo lên chiếc thang bên hông xe tải của Elluka.")
	await novel_interface.show_text_only("Cô gái đang ngồi trên ngai vàng của mình, vỗ nhẹ vào cái bụng căng phồng của mình một cách hài lòng. Hàng chục chiếc đĩa trống nằm trên bàn cúng trước mặt cô.")
	novel_interface.show_character("ren_fishnet", "upset")
	await novel_interface.show_dialog("Cô ấy... ăn hết chỗ này à?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tôi khảo sát khu vực, tính toán cách tốt nhất để đưa cô bé háu ăn mũm mĩm này ra khỏi mớ hỗn độn này, nhưng Elluka chỉ đơn giản lao vào tôi.")
	novel_interface.show_character("iluka_uniform", "smile")
	await novel_interface.show_dialog("Cô Ren!", "Elluka")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tôi đặt một ngón tay lên môi, ra hiệu cho cô ấy giữ nó xuống—")
	await novel_interface.show_text_only("Thế nhưng cô ấy đã nhảy lên không trung, nhắm thẳng vào mặt tôi…")

	# scene2 - 回忆场景
	novel_interface.change_background("res://assets/images/bg/Soya/Recall.png")
	await novel_interface.show_text_only("Ồ, đúng rồi. Lần đầu tiên tôi nhìn thấy Elluka, cô ấy đang chiến đấu với phù thủy trên không phải không?")
	await novel_interface.show_text_only("Tôi nhớ Aya đã nói với tôi rằng cô gái này, tính theo độ tuổi của xương, khoảng mười một đến mười hai tuổi, đã trải qua hàng chục ca phẫu thuật và được lắp vô số bộ phận máy móc vào cơ thể.")
	await novel_interface.show_text_only("Ký ức của cô đã bị xóa quá nhiều lần - cô thậm chí còn không nhớ mắt trái của mình đã được thay thế bằng mắt giả điện tử cấp quân sự từ khi nào.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Với tất cả những bộ phận máy móc đó bên trong, mặc dù cô ấy có khả năng nổi nhờ lợi dụng trường điện từ, nhưng trọng lượng thực tế của cô ấy thực tế là gấp đôi trọng lượng của tôi…")
	# scene3 - 回到秋叶原
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN.png")
	await novel_interface.show_text_only("Bụp!")
	await novel_interface.show_text_only("Elluka đáp xuống tôi, đùi ép chặt vào xương sườn tôi, cái bụng mềm mại che mặt tôi. Bàn tay mũm mĩm của cô ấy ôm chặt lấy gáy tôi.")
	await novel_interface.show_text_only("Tôi thề là tôi có thể nghe thấy tiếng xương sống của mình gãy ra vì áp lực.")
	await novel_interface.show_text_only("Em ôm trọn cơ thể vào ngực, đầu tôi, dụi má vào tóc tôi như một chú mèo rất nhiệt tình.")
	novel_interface.show_character("iluka_uniform", "smile")
	await novel_interface.show_dialog("Cô Ren là người tôi yêu thích nhất! *khụ*", "Elluka")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Từ khuôn mặt đỏ bừng vui vẻ và giọng nói líu ríu của cô ấy, người ta có thể nghĩ rằng cô ấy say rượu.")
	novel_interface.show_character("soya_uniform", "afraid")
	await novel_interface.show_dialog("Tôi nghe thấy tiếng rắc lớn... đó có phải là xương của bạn không?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "wail")
	await novel_interface.show_dialog("...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tôi đứng cứng đờ, đông cứng tại chỗ. Cảm giác như cổ tôi sẽ gãy làm đôi nếu tôi cử động dù chỉ một chút.")
	await novel_interface.show_text_only("Sự náo động dường như đã thu hút sự chú ý của những cô gái đứng gần đó. Một số thậm chí còn chỉ vào chúng tôi và hỏi \"cái gì vậy?\"")
	await novel_interface.show_text_only("Bây giờ tôi trông giống như một con quái vật đầu to trong chiếc tất lưới cá. Không có gì ngạc nhiên khi họ bối rối.")
	await novel_interface.show_text_only("Nhận thấy tình trạng khó khăn của chúng tôi, Beatrice cao giọng, như muốn cho chúng tôi thêm thời gian để sơ tán.")
	novel_interface.show_character("beatrice_regular", "angry")
	await novel_interface.show_dialog("Tất cả các bạn đều thuộc về bãi phế liệu! Không một chút lịch sự nào trong đầu bạn cả! Giòi! Leo! Heo!", "Beatrice")
	await novel_interface.show_dialog("Tất cả các bạn—", "Beatrice")
	await novel_interface.show_dialog("Chết đi!", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Hai người nói đồng thanh với dòng điện xèo xèo khi bài phát biểu đầy nhiệt huyết của Beatrice đạt đến cao trào.")
	await novel_interface.show_text_only("Và cuối cùng chúng phát nổ, cùng với những bóng đèn trên các bảng quảng cáo được chiếu sáng gần đó.")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("Cả con phố rơi vào sự im lặng đáng sợ.")
	await novel_interface.show_text_only("Đám đông vẫn đang sửng sốt nhìn chằm chằm vào người phụ nữ tóc đỏ đang đứng đầy vinh quang trên nóc xe tải.")
	await novel_interface.show_text_only("Sonya lợi dụng sự phân tâm ngắn ngủi để kéo Elluka ra khỏi tôi, sau đó đẩy cô ấy nằm ngửa.")
	await novel_interface.show_text_only("Cô gái trẻ hơn, người đã dán mình lên tôi như một miếng kẹo cao su, ngủ ngay lập tức.")
	novel_interface.show_character("soya_uniform", "afraid")
	await novel_interface.show_dialog("Ối... không ngờ con nhóc lại nặng đến thế...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tôi thở dài, cuối cùng cũng lấy lại được hơi thở, xoa bóp thắt lưng khi quan sát hiện trường. Nó vẫn im lặng đến đáng sợ.")
	novel_interface.show_character("ren_fishnet", "perspire1")
	await novel_interface.show_dialog("Những kẻ này bị hóa đá hay gì đó?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Nhưng khoảnh khắc sau, tiếng reo hò bắt đầu lan truyền khắp đám đông. Tiếng reo hò vang dội, tuyệt vời.")
	novel_interface.change_music("res://assets/audio/music/Brooklyn.mp3")
	await novel_interface.show_dialog("Aahhh! Cô ấy thật tuyệt vời! Bạn thật tuyệt vời!", "Người qua đường A")
	await novel_interface.show_dialog("Hãy bước lên tôi, nữ hoàng của tôi!", "Người qua đường B")
	novel_interface.show_character("ren_fishnet", "stare")
	await novel_interface.show_dialog("Cái gì?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Những làn sóng cổ vũ ngây ngất bùng nổ khắp đường phố.")
	await novel_interface.show_text_only("Đám đông đang náo loạn vì quá phấn khích.")
	await novel_interface.show_text_only("Từ những chiếc xe bọc thép màu đen bên kia đường, vài người lính mang vũ khí tự động nhảy xuống, bối rối quan sát tình hình náo động bất ngờ.")
	await novel_interface.show_text_only("Tôi ra hiệu về phía họ, cố gắng cảnh báo Beatrice, và đó là lúc tôi vô tình nhìn thấy khuôn mặt của cô ấy...")

	# scene4 - 被美色迷惑
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN1.png")
	novel_interface.show_character("ren_fishnet", "timid")
	await novel_interface.show_dialog("Ôi trời—", "Lian")
	novel_interface.change_expression("heart")
	await novel_interface.show_dialog("Cô ấy...đẹp quá!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Một dòng điện ngứa ran ấm áp giống như ham muốn lan truyền khắp cơ thể tôi ngay lập tức.")
	await novel_interface.show_text_only("Má tôi bỏng rát, chân tôi rã rời...")
	novel_interface.show_character("ren_fishnet", "heart")
	await novel_interface.show_dialog("(Tôi muốn cô ấy...)", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform", "speechless", 0.25)
	await novel_interface.show_dialog("... Ren?", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Đám đông đang dần mất kiểm soát. Họ lao vào chiếc xe tải của Beatrice như một, vừa đi vừa hô to, đến mức chiếc xe mỏng manh sắp bị lật nhào.")
	await novel_interface.show_text_only("Một số kẻ cố gắng leo lên chiếc xe tải từ bên cạnh, nhưng Beatrice chỉ đơn giản dẫm lên bàn tay đang túm lấy của họ và đá họ xuống.")
	novel_interface.show_character("ren_fishnet", "heart")
	await novel_interface.show_dialog("(Đúng! Thêm nữa! Giẫm lên tôi nữa! Làm ơn đi, nữ hoàng của tôi!)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beatrice mỉm cười và lắc đầu trước vẻ mặt ngu ngốc của tôi, rồi đeo lại chiếc vòng tay của mình.")
	await novel_interface.show_text_only("Sau đó, cô ấy rút ra một viên nang bạc có kích thước bằng ngón tay cái từ ngực mình và ném nó vào đám đông cuồng nhiệt dưới chân mình—")
	await novel_interface.show_text_only("Trong làn khói trắng, Beatrice xinh đẹp biến mất không dấu vết.")
	# scene5 - 逃跑
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN.png")
	await novel_interface.show_text_only("Tuy nhiên, tôi vẫn không thể quên khuôn mặt tuyệt đẹp của cô ấy - cho đến khi Sonya kéo mạnh cánh tay tôi.")
	novel_interface.show_character("ren_fishnet","heart")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform", "yell", 0.25)
	await novel_interface.show_dialog("Hãy thoát khỏi nó! Những người lính đang đến! Bên cạnh đó...", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Khi khói tan, đám đông bắt đầu lẩm bẩm bối rối và nhận ra rằng đối tượng họ tập trung không còn ở đó nữa.")
	await novel_interface.show_text_only("Sonya và tôi chỉ vừa mới rời khỏi đám đông được vài bước trước khi fanclub của Elluka nhận ra rằng thần tượng của chính họ đã biến mất.")
	await novel_interface.show_dialog("Tiểu thư Elluka đâu?", "Cận vệ hoàng gia A")
	await novel_interface.show_dialog("Ở đằng kia! Kẻ mang tất lưới cá đó đã cướp mất Quý cô Elluka của chúng ta!", "Cận vệ hoàng gia B")
	novel_interface.show_character("ren_fishnet", "wry_smile")
	await novel_interface.show_dialog("(Tất lưới cá? Quý cô Elluka?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Kẻ bắt cóc! Hãy gọi cảnh sát!", "Cận vệ hoàng gia C")
	await novel_interface.show_dialog("Đuổi theo họ!", "Cận vệ hoàng gia A")
	await novel_interface.show_text_only("Một nhóm người hung hãn đi thẳng về phía chúng tôi, theo sau là một vài cảnh sát an ninh.")
	await novel_interface.show_text_only("Thôi nào, kẻ bắt cóc nào lại đi tất lưới cá?")
	novel_interface.show_character("ren_fishnet", "perspire1")
	await novel_interface.show_dialog("Chạy đi!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Nhưng thật khó để chúng tôi rũ bỏ đám đông, đặc biệt là khi Sonya đang bế Elluka bụ bẫm, và thắt lưng của tôi vẫn đang nhói đau.")
	await novel_interface.show_text_only("Tệ hơn nữa, có một số cảnh sát đang tuần tra phía trước...")
	await novel_interface.show_text_only("Chúng tôi không thể chiến đấu. Chúng tôi không thể chạy. Thật vô vọng.")
	await novel_interface.show_text_only("Đột nhiên, từ phía sau chúng tôi vang lên tiếng kính vỡ.")
	await novel_interface.show_text_only("Một anh chàng tóc vàng mặc áo gió đen đã tông đổ một bảng quảng cáo được chiếu sáng kiểu cũ bên đường.")
	await novel_interface.show_text_only("Các mảnh vỡ của bóng đèn biển quảng cáo che phủ mặt đất. Những người đi bộ, cố gắng hết sức để tránh họ, đã làm chậm lại fanclub của Elluka một cách hiệu quả.")
	await novel_interface.show_text_only("Anh chàng tóc vàng mỉm cười với Sonya và tôi, khuôn mặt ngây thơ và ngọt ngào.")
	novel_interface.show_character("john", "smile")
	await novel_interface.show_dialog("Có một lối tắt ở phía trước. Đi với tôi nhé?", "Cậu bé đeo kính")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya và tôi liếc nhìn nhau. Tại sao điều này nghe giống như một kịch bản nào đó trong một bộ phim?")
	await novel_interface.show_text_only("Chàng trai đeo kính, với mái tóc vàng bồng bềnh, áo sơ mi kẻ sọc và đôi mắt xanh, có vẻ khá nhút nhát.")
	await novel_interface.show_text_only("Anh ấy trông gần như bối rối vì sự thiếu phản ứng của chúng tôi và vội vàng giải thích:")
	novel_interface.show_character("john", "shy")
	await novel_interface.show_dialog("Tôi... tôi làm việc bán thời gian ở một cửa hàng gần đây... Tôi vừa tan sở...", "Cậu bé đeo kính")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Anh ấy liếc nhìn chân tôi, nuốt nước bọt rồi quay đi.")
	novel_interface.show_character("ren_fishnet", "uneasy")
	await novel_interface.show_dialog("(Wow, đây thực sự không phải là cách hay để lén nhìn con gái đâu...)\n(Điều đó quá rõ ràng...)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("john", "smile")
	await novel_interface.show_dialog("Cậu... trông cậu như đang bị kẻ xấu truy đuổi, nên tôi nghĩ...", "Cậu bé đeo kính")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Vai của Sonya chùng xuống khi cô ấy hạ cảnh giác trong giây lát.")
	novel_interface.show_character("soya_uniform", "smile")
	await novel_interface.show_dialog("Đánh giá từ khí chất của anh ấy, anh ấy không muốn làm tổn thương chúng tôi.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Trên thực tế, xét trên mọi khía cạnh, CHÚNG TÔI LÀ kẻ xấu ở đây...")
	novel_interface.show_character("soya_uniform", "jest")
	await novel_interface.show_dialog("Hãy dẫn đường!", "Soya")
	await novel_interface.hide_character()
	
	print("=== 天启篇第12话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
