# apocalypse_ep06.gd - 天启篇第06话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第06话剧本
	apocalypse_ep06_script()

func play_script():
	pass

# 天启篇第06话 - 正式剧本
func apocalypse_ep06_script():
	# scene1 - SID指挥室
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("Nella sala di controllo, Mariru è accigliata e fissa il video in loop sul grande schermo.")
	await novel_interface.show_text_only("È un filmato di quando il portavoce di Masada Ford ha introdotto il “sistema di risposta passiva” nella conferenza stampa.")
	await novel_interface.show_text_only("L’uomo sullo schermo è raggiante, carismatico, come un venditore che presenta agli chef un nuovo modello di forno.")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("Sono usciti i risultati dell'analisi facciale?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("Sì. Questo è davvero l'oratore stesso. Non un doppelgänger. E non sta recitando o tentando di nascondere nulla.", "Ai")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Aya sembra un po' delusa dai risultati.")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("Quindi quest'uomo era sinceramente felice quando ha presentato alla folla questo incubo apocalittico?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("Forse è abbastanza intelligente da ingannare il programma di analisi facciale. Lo so.", "Ai")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Aya fa notare, ma Mariru la colpisce semplicemente in testa.")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("Non sei te.", "Mariru")
	await novel_interface.show_dialog("Questo portavoce di Masada Ford è un politico da quasi vent'anni. Dovrebbe sapere molto bene quale risultato porterebbe la sua azione...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru lancia un'occhiata alla fila di piccole finestre nella parte superiore dello schermo, che mostrano filmati in diretta delle proteste dei rifugiati già iniziate nelle città di Salmonton, vicino al confine con il Medio Oriente.")
	await novel_interface.show_text_only("E sotto la fila delle riprese dal vivo c’è una mappa di distribuzione di New Opulentia, con le aree evidenziate che indicano i punti caldi per ancora più manifestazioni.")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("Come va a far tacere i media?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("In realtà non abbiamo il diritto di vietare loro di parlare o altro, ma la maggior parte delle aziende ha accettato di conformarsi quando ha saputo che era coinvolto il SID.", "Ai")
	novel_interface.change_expression("wink")
	await novel_interface.show_dialog("Per quanto riguarda coloro che non si sono conformati, le loro connessioni di rete sono tutte interrotte a causa di un attacco proveniente da una “fonte sconosciuta”.", "Ai")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Aya fa una smorfia, e un angolo delle labbra di Mariru si curva leggermente verso l'alto.")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("Tuttavia, non possiamo controllare tutti i canali mediatici del mondo...", "Ai")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("L'Hovering Palace è l'unico luogo in cui le trasmissioni di notizie sono state limitate. Per quanto riguarda il resto dei paesi... beh, il gatto è fuori dal sacco.", "Ai")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("Non è un nostro problema.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_dizzy")
	await novel_interface.show_dialog("Allora dovremmo attaccare anche la rete della Zona Demilitarizzata Concordata –", "Ai")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru scuote la testa.")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("No. Il Congresso Unito è estremamente sensibile in questi giorni quando si tratta di attacchi di qualsiasi tipo, quindi restate fuori dai guai.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru continua a guardare la mappa dei punti caldi della protesta, aggiornata automaticamente ogni secondo, riflettendo su come far cooperare i funzionari dell'Ufficio della Difesa e dei Dipartimenti dell'Amministrazione.")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("Uffa. Quei ragazzi del Senato stanno tenendo una riunione a porte chiuse, e ora non abbiamo nessuno su cui contare oltre a stupidi gorilla che non sanno come fare niente...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Seleziona alcune fermate del tram sul suo dispositivo portatile, quindi compone il numero di un agente di fiducia.")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("Dobbiamo evacuare la folla nei focolai della protesta. Manda un avviso di bomba all'Ufficio Traffico, digli di vietare il parcheggio vicino alle stazioni nel caso in cui qualche veicolo che trasporta bombe decida di aggirarsi in queste aree.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("Roger quello.", "Agente SID")
	novel_interface.show_character("agent")
	novel_interface.show_character("liliu_uniform1","jest")
	await novel_interface.show_dialog("Oh, manda anche l'unità artificieri. Mostra loro che facciamo sul serio.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("Roger, quello!", "Agente SID")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("Manda i tuoi uomini a monitorare queste cinque aree chiave del centro. Sembrano essere più affollati del solito oggi.", "Mariru")
	await novel_interface.show_dialog("Rimani vigile e ascoltalo a orecchio. Se qualcosa va storto, indossa un vestito ignifugo e spruzza anidride solforosa sulle strade o qualcosa del genere, e fai finta che ci sia stata una fuga di gas.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("Sì, capo.", "Agente SID")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru riattacca per incontrare gli occhi eccitati di Aya.")
	novel_interface.show_character("liliu_uniform1","jest")
	await novel_interface.show_dialog("Spara con due cannoni allo ioduro d'argento verso nord-ovest. Quando inizierà a piovere la gente tornerà a casa.", "Mariru")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("Ricordatevi di tenere in considerazione la direzione del vento e di non influenzare la zona demilitarizzata concordata, altrimenti saremo nei guai per aver violato l’accordo internazionale.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("Naturalmente. Lascia fare tutto a me!", "Ai")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…")
	
	# scene2 - 美术馆与瑟蕾莎
	novel_interface.show_background("res://assets/images/bg/Soya/Galleries.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.show_character("cereza","wordless")
	await novel_interface.show_text_only("Lancio uno sguardo furtivo alla signora che mi ha salvato dallo schiantarmi la faccia al suolo.")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","timid")
	await novel_interface.show_dialog("(Wow, sono piuttosto... considerevoli!)\n(Sembra che potrebbero rimbalzare mentre lei si allena...)", "Lian")
	# removed legacy empty placeholder comment
	await novel_interface.hide_character()
	await novel_interface.show_text_only("…")
	await novel_interface.show_text_only("La signora tira l'imbracatura che lega i suoi seni voluttuosi e sorride in modo seducente.")
	novel_interface.show_character("cereza","jest")
	await novel_interface.show_dialog("Non rimbalzeranno, ho queste belle cinture!", "Donna dai capelli neri")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("Aspetta, cosa...?\n(Mi ha appena letto nel pensiero?)", "Lian")
	# removed legacy empty placeholder comment
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("(E smettila di tirare l'imbracatura! Non farebbe male?)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_text_only("…")
	await novel_interface.show_dialog("Ah, Theresa, cosa ci fai qui?", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphilia interviene. Non molto dietro di lei c'è Sonya, con il fumo che le esce ancora dalla testa, che marcia verso di me con Elluka al seguito.")
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("Tutta colpa di Buhler. Mi ha chiamato tipo dieci volte, quella vecchia strega. Sono così stanco...", "Teresa")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Theresa sbadiglia ancora una volta e allunga le braccia, facendone scivolare facilmente una attorno al mio collo.")
	novel_interface.show_character("cereza","jest")
	await novel_interface.show_dialog("Ehi, questa è la ragazza \"Ren\" di cui ha parlato Mariru, giusto?\nQuello che ha fatto un'operazione con te?", "Teresa")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("(Lei sa dell'operazione congiunta?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphilia pronuncia un piccolo \"ah\" e si volta, evitando lo sguardo di Theresa.")
	await novel_interface.show_text_only("Quest'ultimo si muove semplicemente dietro di me, pizzicandomi le spalle con entrambe le mani.")
	novel_interface.show_character("cereza","smile")
	await novel_interface.show_dialog("Hm, il suo fisico va bene, ma ha bisogno di più allenamento.", "Teresa")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mi dispiace, non sono abbastanza muscoloso per i tuoi gusti...")
	await novel_interface.show_text_only("Poi arriccia gli indici e con le articolazioni delle dita mi traccia due linee lungo entrambi i lati della spina dorsale. Quando raggiunge le mie fossette sulla schiena, preme forte...")
	await novel_interface.show_text_only("Una sensazione calda e indistinta mi scorre nelle vene. Non posso fare a meno di gemere.")
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("Ah!", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("…", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("Ah?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphilia non sembra nemmeno interessata: sembra piuttosto abituata agli imbrogli di Theresa. Nel frattempo, Sonya si avvicina, incuriosita dal mio gemito.")
	await novel_interface.show_text_only("Le mani di Theresa sono estremamente abili. Presto mi rendo conto che non c'è modo di reagire, il mio corpo si scioglie come mastice tra le sue mani.")
	await novel_interface.show_dialog("Shh, chiudi gli occhi...", "Teresa")
	await novel_interface.show_text_only("Theresa mi sussurra all'orecchio.")
	await novel_interface.show_dialog("Immagina che il tuo braccio destro stia per scattare in avanti, ma non puoi farlo perché le tue dita lo tengono in posizione. Invece, è semplicemente lì, ad accumulare energia come una corda tesa.", "Teresa")
	await novel_interface.show_text_only("Seguo le istruzioni di Theresa e alzo il braccio destro, posizionando le dita della mano destra sulla spalla sinistra.")
	await novel_interface.show_dialog("Fai un respiro profondo...", "Teresa")
	await novel_interface.show_dialog("E lascia andare!", "Teresa")
	await novel_interface.show_text_only("Non appena lascio andare le dita, il mio braccio rimbalza in avanti come una freccia scoccata. Nell'aria, le mie dita sembrano aver tagliato qualcosa...")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","trance")
	await novel_interface.show_text_only("Una ciocca della frangia argentata di Sonya è stata tagliata di netto dalla mia unghia. Lei sta lì a un braccio di distanza da me, fissandomi con orrore.")
	novel_interface.change_expression("afraid")
	await novel_interface.show_dialog("Respirare?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ci scambiamo sguardi mentre guardiamo la ciocca di capelli argentati scivolare lentamente a terra...")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("S-scusa!\nTi ho ferito?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","shy")
	await novel_interface.show_dialog("Uuuu...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya geme, proprio come un piccolo animale ferito.")
	novel_interface.show_character("soya_uniform","shy")
	await novel_interface.show_dialog("La tua aura... mi ha penetrato..", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("mormora Sonya, con il viso rosso vivo. Sembra che... si stia divertendo?")#换行问题
	novel_interface.show_character("cereza","jest")
	await novel_interface.show_dialog("Interessante. Non c'è da stupirsi che Miss Raphilia preferisca restare a New Opulentia.", "Teresa")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("Stai zitto. Comunque perché sei qui?", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","jest")
	await novel_interface.show_dialog("Per accompagnarti all'ambasciata, ovviamente.", "Teresa")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Sei...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","smile")
	await novel_interface.show_dialog("Ah, non mi sono ancora presentato.", "Teresa")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Theresa si aggiusta attentamente il seno.")
	novel_interface.show_character("cereza","smile")
	await novel_interface.show_dialog("Theresa, allenatrice di combattimento Rosenkreuzer, al tuo servizio.", "Teresa")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("Fondamentalmente, il mio lavoro è insegnare alle persone a combattere, anche se le lezioni di solito consistono nel picchiare gli altri.", "Teresa")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Quando la signorina Raphilia si mette nei guai, a volte faccio anche la guardia del corpo.", "Teresa")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Theresa sorride raggiante a Raphilia, che semplicemente alza gli occhi al cielo.")
	novel_interface.show_character("cereza","smile")
	await novel_interface.show_dialog("Suo nonno mi ha addirittura premiato con una medaglia!", "Teresa")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("Comunque, cosa è successo esattamente?", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("Beh... mi sono appena alzata anch'io, ma la vecchia strega ha detto...", "Teresa")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("Il portavoce di Masada Ford... si è sparato nella sua suite d'albergo.", "Teresa")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("Cosa?", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("Che diavolo?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("Questo è tutto quello che so. Lo conosci?", "Teresa")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("Ah!", "Teresa")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Theresa urla all'improvviso, dandosi una pacca sulla testa.")
	novel_interface.show_character("cereza","boring")
	await novel_interface.show_dialog("Doveva essere un segreto!", "Teresa")
	novel_interface.change_expression("blink")
	await novel_interface.show_dialog("Ah... qualunque cosa...", "Teresa")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("Qualunque cosa? Hai appena svelato un enorme segreto e questa è la tua reazione?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","normal")
	await novel_interface.show_dialog("Il SID probabilmente lo sa già comunque. Anche gli addetti alla sicurezza sono in massima allerta.", "Teresa")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Theresa si schiarisce la gola e si irrigidisce, sollevando la katana che ha in mano.")
	novel_interface.show_character("cereza","normal")
	await novel_interface.show_dialog("E quindi, visto che la nazione è in massima allerta... sono qui per scortare Miss Raphilia all'Ambasciata.", "Teresa")#换行问题
	await novel_interface.hide_character()

	print("=== 天启篇第06话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
