# apocalypse_ep19.gd - 天启篇第19话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第19话剧本
	apocalypse_ep19_script()

func play_script():
	pass

# 天启篇第19话 - 正式剧本
func apocalypse_ep19_script():
	# Scene 1 - 神曲开场
	novel_interface.show_background("res://assets/images/bg/Soya/DivinaCommedia.png")
	await novel_interface.show_text_only("Und während das Glühen über der Welle am rötlichsten brennt,\nDarauf wartet das aufsteigende Gespann, der Phaëton\nIch wusste zu leiten, und auf jedem Teil war das Licht")
	await novel_interface.show_text_only("Vermindert verblasst, am intensivsten in der Mitte;\nSo brannte die friedliche Flamme und ließ nach\nAuf jeder Seite verfiel die lebendige Flamme.")
	await novel_interface.show_text_only("Und mittendrin wehten ihre sportlichen Wimpel\nTausende Engel; in jeder Pracht")
	await novel_interface.show_text_only("Deutliche und urige Verzierung...")
	await novel_interface.show_text_only("–Canto XXXI, Paradiso, Die Göttliche Komödie")
	
	# Scene 2 - 地下密室对话
	novel_interface.change_background("res://assets/images/bg/Soya/Underground_Hall.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("Mariru steht da, spielt mit dem Foto in ihren Händen und beobachtet aufmerksam den grauhaarigen Mann vor ihr.")
	await novel_interface.show_text_only("Es gibt nicht viele Informationen über diesen Mann. Niemand weiß, ob Lumbert sein richtiger Name ist, geschweige denn, wie sein Nachname ist.")
	await novel_interface.show_text_only("Dennoch ist es eine Tatsache, dass er aufgrund seines „herausragenden Beitrags zum Weltfrieden“ unter diesem Namen zum Ritter geschlagen wurde.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("(Akiko hat bereits bestätigt, dass es sicher ist, mit ihm zu verhandeln.)", "Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Die meisten Menschen glauben, dass der Vereinigte Kongress die größte Macht über unseren Planeten hat, weil dort Staatsoberhäupter aus der ganzen Welt versammelt sind.", "Mariru")
	await novel_interface.show_dialog("Es stimmt, diese Art von Organisation gab es in der Geschichte schon einmal. Aber die Struktur war schwach und die Mitglieder konnten nie aufhören zu streiten. Der Vorsitzende verhielt sich eher wie ein Friedensstifter und Bettler.", "Mariru")
	await novel_interface.show_dialog("Aber der Vereinigte Kongress, den wir jetzt haben, ist überhaupt nicht so. Viel einflussreicher. Und viel reicher.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru steckt das Foto mit ausdruckslosem Gesicht wieder in die Tasche.")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("Aus Interesse entsteht Vertrauen. Aus Vertrauen entsteht Macht. Und Macht erzeugt durch die Anordnung und Verteilung von Ressourcen noch mehr Interesse ...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lumbert zieht eine Augenbraue hoch.")
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("Das ist Walkers grundlegendes Gesellschaftsmodell.", "Lumbert")
	await novel_interface.show_dialog("Politiker werden von Interessengruppen als Agenten ausgewählt, die das Vertrauen der Öffentlichkeit genießen.", "Lumbert")
	novel_interface.change_expression("relax")
	await novel_interface.show_dialog("Wenn diese Agenten nicht in der Lage sind, größere Interessen aufrechtzuerhalten oder zu schaffen, werden ihnen ihre Befugnisse entzogen und jemand anderes wird an ihre Stelle treten.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Das stimmt in der Makrogeschichte, aber die Öffentlichkeit war nie vernünftig. Wie Le Bon einmal sagte...", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","smile")
	await novel_interface.show_dialog("Die Massen haben nie nach Wahrheit gedurstet. Wer sie mit Illusionen versorgen kann, ist leicht ihr Herr; Wer versucht, ihre Illusionen zu zerstören, ist immer ihr Opfer.", "Lumbert")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lumbert murmelt und beendet das Zitat für sie. Mariru lächelt und nickt.")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("Es gibt zu viele Möglichkeiten, den Interessenteil zu überspringen und direkt das Vertrauen der Öffentlichkeit zu gewinnen.", "Mariru")
	await novel_interface.show_dialog("Führungskräfte dieser Art haben keine Angst davor, große Opfer zu bringen, solange sie am Ende erfolgreich sind.", "Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Doch nach dem Siebenjährigen Krieg beginnen diejenigen, die das Leben der Massen schützen und die Nationen am Laufen halten, die ganze Situation zu überdenken.", "Mariru")
	await novel_interface.show_dialog("Und so gründeten sie den Vereinigten Kongress. Eine Organisation, die direkt mit Interessengruppen zusammenarbeitet und verhandelt.", "Mariru")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("Es ist also eigentlich umgekehrt. Der Vereinigte Kongress ist nicht mächtig, weil er aus nationalen Führern besteht. Tatsächlich ist die Wahrheit so, dass nur diejenigen im Kongress qualifiziert sind, nationale Führer zu werden.", "Mariru")
	await novel_interface.show_dialog("Diese Organisation hat vor drei Jahren ihren ersten Schritt gemacht ...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru macht eine Pause. Lumbert starrt sie an und hält den Atem an.")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Vor drei Jahren arbeiteten der Vereinigte Kongress und die Kirche zusammen, um eine Art EX-Klasse-Substanz H in Südamerika zu testen. Sie setzten die Mafia-Warlords dort unter Druck, mit ihnen zusammenzuarbeiten.", "Mariru")
	await novel_interface.show_dialog("Das Experiment geriet jedoch außer Kontrolle. Über 46.000 Einheimische kamen ums Leben.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Bernadotte.png")
	await novel_interface.show_dialog("Sie bestachen jeden, der die Wahrheit kannte, um sie zum Schweigen zu bringen, und brandmarkten die ganze Sache als Massaker am Fluss Churun und schoben die Schuld auf Carlos Branco, den einzigen Kriegsherrn, der sich weigerte zu kooperieren.", "Mariru")
	await novel_interface.show_dialog("Die Nachricht von dem Vorfall ging viral. Die Medien waren begeistert. Die Öffentlichkeit hasste ihn und zeigte in großem Umfang ihre Abscheu und ihren Hass gegenüber dem Krieg.", "Mariru")
	await novel_interface.show_dialog("Und der Vereinigte Kongress wurde weithin als die Organisation geschätzt, die an einer gemeinsamen Militäroperation zur Tötung von Branco beteiligt war. Niemand hat sich auch nur die Mühe gemacht zu hinterfragen, ob die Existenz dieser Organisation überhaupt legal war.", "Mariru")
	novel_interface.change_background("res://assets/images/bg/Soya/Underground_Hall.png")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("Aber ist es nicht zu unnatürlich? Tausende von Körpern, in einer reihenartigen Formation angeordnet, mit der Kirche als Mittelpunkt ...", "Mariru")
	await novel_interface.show_dialog("Ich glaube, dass der Kongress dort eine Substanz-H-Waffe abgefeuert hat, die in der Lage ist, die Radiowellen in einem Umkreis von zwei Meilen zu stören, um die Wahrheit zu verbergen.", "Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Eine ähnliche Anomalie ereignete sich auch auf dem Schlachtfeld in Westasien. Deshalb waren die Bilder, die die Satelliten dort aufgenommen hatten, alle verzerrt – schließlich war auch Licht eine Art Welle.", "Mariru")
	await novel_interface.show_dialog("Aus diesem Grund blieben die Funkwellenstörungen in der Gegend auch nach der Schließung des „Tores“ wochenlang bestehen.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru legt großen Wert auf die Worte „das Tor“. Lumbert schließt resigniert die Augen.")
	novel_interface.change_background("res://assets/images/bg/Soya/Churun.png")
	await novel_interface.show_text_only("Mariru studiert das Foto in ihrer Hand.")
	await novel_interface.show_dialog("Die Beseitigung all dieser Leichen erforderte viele Arbeiter. Es muss schwierig gewesen sein, sicherzustellen, dass keiner von ihnen etwas durchsickern ließ.", "Mariru")
	await novel_interface.show_dialog("Ich wette, Sie hätten nie erwartet, dass jemand dieses Foto der Szene mit einer alten mechanischen Kamera und einer Rolle verrotteten Films macht.", "Mariru")
	await novel_interface.show_dialog("Der Hintergrund des Bildes war verschwommen. Das lag an den Lichtverzerrungseigenschaften der von Ihren Leuten verwendeten Substanz-H-Waffe.", "Mariru")
	novel_interface.change_background("res://assets/images/bg/Soya/Underground_Hall.png")
	novel_interface.show_character("lambert","usually")
	await novel_interface.show_dialog("Interessant. Aber warum sind Sie so überzeugt, dass ich beteiligt war?", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Einen Monat vor dem Vorfall wurden Sie zum Generalsekretär der Organisation zum Verbot von Substanz-H-Waffenexperimenten ernannt.", "Mariru")
	await novel_interface.show_dialog("Oberflächlich betrachtet besteht der Zweck dieser Organisation darin, Experimente mit Stoff-H-Waffen zu verbieten. Es handelt sich um eine leistungsstarke Einrichtung mit vielen verfügbaren Ressourcen und hervorragenden Möglichkeiten zur Informationsbeschaffung.", "Mariru")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("Es ist unmöglich, dass Sie nichts von einem Vorfall dieser Größenordnung wissen. Der Grund, warum Sie sich entschieden haben, nichts zu sagen, war, dass Sie in Wirklichkeit derjenige waren, der alles geplant hat.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lumbert versucht nicht zu protestieren und Mariru wertet sein Schweigen als Zeichen dafür, dass es sicher ist, weiterzumachen.")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("Am Ende schickte die Kirche einige von ihnen los, um die Substanz H zu bergen, die den ganzen Ärger verursachte. Danach erhielten sie ungewöhnlich viele Gelder und Privilegien vom Vereinigten Rat.", "Mariru")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("Bei der Substanz H handelt es sich um eine halboffene schwarze Tür. Dahinter ist blendendes goldenes Licht –", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","frown")
	await novel_interface.show_dialog("Genug! Ich verstehe es!", "Lumbert")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lumbert unterbricht ihn und hebt beide Arme in einem Akt der Kapitulation.")
	await novel_interface.show_text_only("Er zupft am Kragen seines Anzugs und räuspert sich.")
	novel_interface.show_character("lambert","frown")
	await novel_interface.show_dialog("Tatsächlich besteht die Mission unserer Organisation darin, sicherzustellen, dass die Öffentlichkeit keinen einfachen Zugang zu Stoff-H-Waffen hat, geschweige denn, sie in Experimenten einzusetzen.", "Lumbert")
	await novel_interface.show_dialog("Substanz H ist einfach zu gefährlich. Wenn wir nicht aufpassen, könnte es unsere Zivilisation zerstören. Aber das Experiment, das wir durchgeführt haben... es war unvermeidlich. Jemand musste es tun, das könnten genauso gut wir sein.", "Lumbert")
	await novel_interface.show_dialog("Jemand ... etwas ... klopfte von innen an die Tür. Immer dringlicher. Wir hatten keine Wahl...", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Klopfen...?", "Mariru")
	await novel_interface.hide_character()
	
	# Scene 3 - 天堂之门
	novel_interface.change_background("res://assets/images/bg/Soya/BlackGate.png")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	await novel_interface.show_dialog("Ich klopfe an die Tür des Himmels, ja.", "Lumbert")
	await novel_interface.show_dialog("Der Himmel existiert in allen Religionen und Mythologiesystemen in unterschiedlichen Formen. Die Definitionen können in jedem Glaubenssystem unterschiedlich sein, aber vielleicht stammen sie alle aus derselben Quelle.", "Lumbert")
	await novel_interface.show_dialog("In historischen Aufzeichnungen heißt es, dass kurz bevor die Tür geöffnet wurde, dreimal hintereinander an die Tür geklopft wurde.", "Lumbert")
	await novel_interface.show_dialog("Tiefes, hallendes Klopfen. Als würde es an die Seele des Zuhörers klopfen ...", "Lumbert")
	await novel_interface.show_dialog("Nachdem das Klopfen zum ersten Mal zu hören ist, herrscht eine Woche lang Stille und das Klopfen beginnt erneut. Die Abstände zwischen den Klopfen werden allmählich kürzer...", "Lumbert")
	await novel_interface.show_dialog("Wenn zwischen jedem Klopfen nicht mehr als neunzig Sekunden vergehen, wissen wir, dass die Himmelstür bereit ist, sich zu öffnen.", "Lumbert")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("Sie können das „Wesen“ hinter der Tür nach Belieben definieren, aber Tatsache ist, dass es über Kräfte verfügt, die eine Katastrophe vom Ausmaß einer Apokalypse herbeiführen können.", "Lumbert")
	await novel_interface.show_dialog("Eine gewaltige Überschwemmung zum Beispiel, hm...", "Mariru")
	await novel_interface.show_dialog("Den Manuskripten der Kirche zufolge besteht die einzige Möglichkeit, die Tür geschlossen zu halten, darin, etwa zehntausend Menschen auf dem Gelände zu versammeln und die Tür zu umgeben ...", "Lumbert")
	await novel_interface.show_dialog("Eine Art Opfer, oder?", "Mariru")
	await novel_interface.show_text_only("Lumbert ignoriert Marirus Bemerkung und fährt fort.")
	await novel_interface.show_dialog("So etwas passierte alle paar hundert Jahre. Immer wurden die Leichen in einer strahlenförmigen Anordnung angeordnet, wobei die Tür den Mittelpunkt bildete.", "Lumbert")
	await novel_interface.show_dialog("Diese Art von Ritual wurde normalerweise im Geheimen durchgeführt. Da zwischen einem Ritual und dem nächsten jedoch immer Hunderte von Jahren lagen, nutzten bestimmte Menschen aus bestimmten Epochen sie zu ihrem eigenen Vorteil ...", "Lumbert")
	await novel_interface.show_dialog("Zum Beispiel das Massaker am St. Bartholomäus-Tag in Paris im Jahr 1572.", "Lumbert")
	await novel_interface.show_dialog("In der Nacht vor dem St.-Bartholomäus-Tag in diesem Jahr kam es zu einem schrecklichen religiösen Massaker, dem schlimmsten seit Jahrhunderten, mit über siebzigtausend Toten.", "Lumbert")
	await novel_interface.show_dialog("Paris, hm...", "Mariru")
	novel_interface.show_background("res://assets/images/bg/Soya/Paris.png")
	await novel_interface.show_dialog("Moment, eine radiale Anordnung mit einer Tür als Mittelpunkt?", "Mariru")
	await novel_interface.show_text_only("Mariru wird sofort an die Art und Weise erinnert, wie die Straßen in der Stadt der Romantik angelegt sind.")
	await novel_interface.show_dialog("Ironisch, nicht wahr...", "Lumbert")
	await novel_interface.show_text_only("Lumbert lacht humorlos.")
	novel_interface.change_background("res://assets/images/bg/Soya/Underground_Hall.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("Dennoch kann man nicht an eine Tür klopfen, es sei denn, sie hat eine konkrete Form. Warum zerstört man es nicht einfach oder deponiert es irgendwo im Weltraum?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("Die Tür zum Himmel ist nur ein Konzept. Anfangs tauchte die Tür nie zweimal an derselben Stelle auf.", "Lumbert")
	await novel_interface.show_dialog("Es tauchte sogar an Stellen auf, an denen es eigentlich keine Tür geben sollte. Zum Beispiel auf der Oberfläche antiker Stadtmauern.", "Lumbert")
	await novel_interface.show_dialog("Sie brachten immer Unheil mit sich, waren aber auch gewissermaßen göttliche Relikte, ein Beweis dafür, dass es eine Existenz jenseits unseres Verständnisses gab.", "Lumbert")
	await novel_interface.show_dialog("Religiöse Fraktionen in der Geschichte hatten nie aufgehört, über dieses Konzept zu streiten und es für sich zu beanspruchen.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("Wie beansprucht man ein Konzept genau?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("Aus historischen Aufzeichnungen geht hervor, dass die Hagia Sofia über einen längsten Zeitraum der offizielle „Eigentümer“ der Himmelstür war.", "Lumbert")
	await novel_interface.show_dialog("Dann, im fünfzehnten Jahrhundert, beanspruchte der Bildhauer Lorenzo Ghiberti aus Florenz mit einem Kunstwerk, an dem er sein ganzes Leben lang gearbeitet hatte, den Besitz des Konzepts.", "Lumbert")
	await novel_interface.show_dialog("Dieses Kunstwerk diente nach seiner Fertigstellung im Jahr 1452 als Haupteingang der Kathedrale von Florenz. Die Welt war sich einig, dass es von da an als „Himmelspforte“ bekannt sein sollte.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Ich verstehe.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Die älteste Methode, mit der Menschen Anspruch auf ein Konzept erhoben, bestand darin, ihren eigenen Wert durch die Schaffung majestätischer, extravaganter Kunstwerke unter Beweis zu stellen.")
	await novel_interface.show_text_only("Pyramiden, Tempel, Paläste, Kronen, Throne...")
	await novel_interface.show_text_only("Alles Möglichkeiten, um zu beweisen, dass der Schöpfer der wahre, würdige Eigentümer eines Konzepts ist.")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Moment... wurde Konstantinopel, wo sich die Hagia Sofia befindet, nicht ein Jahr nach der Fertigstellung von Ghibertis Kunstwerk überfallen und besetzt? Lag es daran, dass...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lumbert schüttelt den Kopf.")
	novel_interface.show_character("lambert","frown")
	await novel_interface.show_dialog("Wir wissen es nicht. In diesem Zeitraum konnten keine direkten Beweise gefunden werden.", "Lumbert")
	await novel_interface.show_dialog("Wir KÖNNEN sicher sein, dass Ghibertis Werk im Siebenjährigen Krieg zerstört wurde.", "Lumbert")
	await novel_interface.show_dialog("Um also zu bestimmen, wann die „Tür“ das nächste Mal erscheint, und um sicherzustellen, dass sie sich in einem ausreichend entfernten Bereich befindet, um beim nächsten Öffnen nur minimalen Schaden anzurichten ...", "Lumbert")
	novel_interface.change_expression("relax")
	await novel_interface.show_dialog("Wir mussten mit der Kirche zusammenarbeiten, um eine Art Kopie zu erstellen.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("Doch bei dem Experiment ging etwas schief. Wir konnten die Tore nicht so schließen, wie wir sollten. Deshalb musste die Kirche solche Anstrengungen unternehmen ...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Das erklärt alles. Für Mariru fühlt es sich an, als würde sie endlich die Hinweise zusammensetzen und das ganze Puzzle so sehen, wie es ist.")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Also... Sie haben hinterher alles mit einer genialen Lüge, der Hilfe der Medien und dem perfekten Sündenbock vertuscht...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lumbert kichert grimmig über Marirus Worte.")
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("Danke für das Kompliment, schätze ich.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Nein. Kein Kompliment. Wenn die Menschheit eines Tages keine andere Wahl haben wird, als sich einer Macht solch überwältigenden Ausmaßes zu stellen ...", "Mariru")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("Ich würde es für dumm halten, alles mit einer Lüge zu vertuschen und unter dem Deckmantel der Hoffnung Unwissenheit zu verbreiten.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","serious")
	await novel_interface.show_dialog("Aber siehst du das nicht? Der Mensch ist so schwach. Wir geben lieber unsere Sicherheit für ein Gefühl der Sicherheit auf.", "Lumbert")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru grinst und erhebt ihre Stimme.")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("Deshalb ist „Ethik“ in gewisser Weise wertvoll.", "Mariru")
	await novel_interface.show_dialog("Es ist Teil Ihrer Aufgabe, die Wahrheit dieses Experiments zu vertuschen. Und die Wahrheit liegt jetzt in meinen Händen ...", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","serious")
	await novel_interface.show_dialog("Du hast recht. Benennen Sie also Ihre Begriffe.", "Lumbert")
	await novel_interface.show_dialog("Aber denken Sie daran, dass ich selbst nur ein Repräsentant bin und keinen Einfluss auf die Entscheidungen des Vereinigten Kongresses habe. Ich weiß nicht einmal, wer die Entscheidungen trifft.", "Lumbert")
	await novel_interface.hide_character()
	
	# Scene 4 - 交易谈判
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("Keine Sorge, ich werde nichts benennen, was außerhalb Ihrer Macht liegt.", "Mariru")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("Meine Bedingung ist: Der Nachfolger von Scheinermann, Ministerpräsident der Dritten Akademiestadt, kann kein Militär sein.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lumbert sieht angesichts der Bitte verblüfft aus.")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Oberflächlich betrachtet, zumindest finanziell, müssen sie sich nie Sorgen machen, dass ihre Waffenhersteller pleitegehen, solange der Vereinigte Kongress Masada zum Verkauf von Waffen ermächtigt.", "Mariru")
	await novel_interface.show_dialog("Allerdings geht es in der Politik nicht nur um Geld. Auch Menschen sehnen sich nach Macht...", "Mariru")
	await novel_interface.show_dialog("Sobald die Öffentlichkeit der sinnlosen Kriege überdrüssig wird, wird es kein solides Fundament mehr geben, auf dem ein groß angelegtes Militär aufbauen könnte.", "Mariru")
	await novel_interface.show_dialog("Ist Ihnen nicht aufgefallen, dass in letzter Zeit immer mehr Medienkanäle aus Masada ihre eigene Hauptstadt als „Academy City“ statt als „Masada Ford“ bezeichnen?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lumbert antwortet nicht.")
	await novel_interface.show_text_only("Plötzlich klingelt der schwarze Aufzug auf der linken Seite. Eine bebrillte Frau kommt mit einer kleinen Aktentasche in der Hand aus der Tür.")
	novel_interface.show_character("lambert","surprise")
	await novel_interface.show_dialog("Akiko?", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("Du hast das alte Warzenschwein am Nachmittag getroffen, ohne mich zu benachrichtigen. Ich lasse dich dieses Mal vom Haken –", "Akiko")
	await novel_interface.show_dialog("Aber hättest du mir nicht wenigstens sagen sollen, dass du Mariru triffst? Vor allem, weil ich derjenige war, der euch einander vorgestellt hat!", "Akiko")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lumbert dreht sich um und wirft Mariru einen ungläubigen Blick zu, doch Mariru zuckt mit den Schultern.")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("Sie stellte viele Fragen. Ich musste es ihr sagen.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("Ugh...", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("Alter Fuchs.", "Akiko")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Akiko öffnet ihre Aktentasche und bringt ein Dutzend Batterien zum Vorschein, die ordentlich mit Schaumgummi befestigt sind.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Ich bin mir sicher, dass Sie bereits alles über die Parameter dieser kleinen Kerle wissen.", "Mariru")
	await novel_interface.show_dialog("Masada hatte tagelang ununterbrochen daran gearbeitet, der Welt während des Friedensforums seine hochdichten Stromspeicherprodukte zu zeigen.", "Mariru")
	await novel_interface.show_dialog("So ähnlich wie auf der Pariser Weltausstellung 1900 elektrisch betriebene Lampen ausgestellt wurden, um der Welt zu zeigen, wie militärische Technologien für die breite Öffentlichkeit genutzt werden können.", "Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Schließlich war es Ministerpräsident Scheinermann selbst, der dieses Projekt erstmals ins Leben gerufen und vorangetrieben hat.", "Mariru")
	await novel_interface.show_dialog("Und unseren Erkenntnissen zufolge wird Scheinermann mit seinem aktuellen Gesundheitszustand nicht bis zum nächsten Pessachfest durchhalten.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lumberts Gesichtsausdruck wird dabei grimmig.")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Was die ungehinderte Kanalbeförderung betrifft ...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru tritt einen Schritt näher und starrt Lumbert direkt in die Augen.")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("Sollte es nicht das Beste sein, wenn „beide Nutznießer“ sich gemeinsam um den Haushalt kümmern?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","usually")
	await novel_interface.show_dialog("Gut...", "Lumbert")
	await novel_interface.show_dialog("Aber welchen Nutzen hat das für Sie?", "Lumbert")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru antwortet nicht. Stattdessen holt sie einfach eine Batterie aus dem Gehäuse und schnüffelt daran, als wäre es eine Zigarre.")
	novel_interface.show_character("akiko","perspire")
	await novel_interface.show_dialog("Kriechen.", "Akiko")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru streckt ihre Hand aus und fährt, immer noch die Batterie haltend, durch Akikos Haare. Die Dame schnaubt und wendet sich ab.")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("Oh, Sie tragen immer noch diese nicht verschreibungspflichtige Brille?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","frown")
	await novel_interface.show_dialog("Brillen ohne Sehstärke?", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Wie auch immer, auch Sie werden von der Zusammenarbeit mit uns viel profitieren. Wenn Masadas Pläne in die Tat umgesetzt werden, benötigen sie eine Menge Geld von Newmoridas.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","frown")
	await novel_interface.show_dialog("… Ich verstehe.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Was den perfekten Kandidaten betrifft, haben wir noch Zeit, uns zu entscheiden.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru legt die Batterie zurück in das Gehäuse und streckt ihre rechte Hand in Richtung Lumbert aus.")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("Also, Deal?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lumbert ergreift fest Marirus Hand, um den Deal anzunehmen, merkt dann aber nach ein paar Sekunden, dass sie keinerlei Anzeichen dafür zeigt, dass sie loslassen will.")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Nun, kommen wir zum nächsten Thema ...", "Mariru")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("Der Testversuch, den Sie heute durchführen ...", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","frown")
	await novel_interface.show_dialog("…", "Lumbert")
	novel_interface.change_expression("usually")
	await novel_interface.show_dialog("Ach? Wie konntest du das erkennen?", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Der Sprecher von Masada Ford verlor vor einigen Jahren seine Frau und seine Tochter bei einem Autounfall. Danach hatte er mehrmals versucht, sich das Leben zu nehmen.", "Mariru")
	await novel_interface.show_dialog("Aber er hat immer im letzten Moment gekniffen – und doch hat er es heute getan ... einfach so. Verdächtig, oder?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mit einem freudlosen Lächeln holt Lumbert langsam seine Hand zurück.")
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("Guter Punkt. Aber Sie haben keinen Beweis dafür, dass es kein Selbstmord war.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Heutzutage gibt es einen Zustrom von Patienten, die ihr Schmerzempfinden verloren haben ...", "Mariru")
	await novel_interface.show_dialog("Ich vermute, dass die Wirkung der Substanz H, die Sie dieses Mal testen, vorübergehend alle negativen Gefühle beim Menschen blockieren kann, und dazu gehört auch der Schmerz. Habe ich recht?", "Mariru")
	await novel_interface.hide_character()
	
	# Scene 5 - 切回小怜视角
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("An der leeren Kreuzung macht unser schwarzer SUV plötzlich eine Kehrtwende.")
	novel_interface.show_background("res://assets/images/bg/Soya/Backseat.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("Nachdem wir das im Lampenschirm verborgene Geheimnis entdeckt haben, entscheiden wir uns für einen Abstecher zur New Opulentia Memorial Church.")
	await novel_interface.show_dialog("Dieser Lampenschirm lenkt scheinbar einen kleinen Teil des Lichts um. Dennoch stimmt etwas nicht...", "Ai")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("Was meinst du?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Erstens ist der Bereich dieses Lampenschirms, der das Licht tatsächlich umlenken kann, äußerst gering. Dieses Bild ist nur aus einem ganz bestimmten Winkel sichtbar – tatsächlich einem eingeschlossenen Winkel von etwa einem Grad.", "Ai")
	await novel_interface.show_dialog("Wenn man es aus einem anderen Blickwinkel betrachtet, sieht man nur einfaches, altgelbes Licht.", "Ai")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Aber wenn es in wirklich überfüllten Bereichen platziert wird, könnte dieser Winkel von einem Grad immer noch viele Menschen beeinträchtigen, oder?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Und das ist das Merkwürdigste daran.", "Ai")
	await novel_interface.show_dialog("Bei der Umlenkung des Lichts transformiert der Lampenschirm die Wellenlänge des sichtbaren Lichts, sodass es für das bloße menschliche Auge unsichtbar wird.", "Ai")
	await novel_interface.show_dialog("Daher hätten die Fußgänger in der Menge nicht beeinträchtigt werden dürfen, selbst wenn sie sich in einem bestimmten Abstand aufhielten.", "Ai")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("... Wie?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Welchen Sinn haben diese Lampenschirme dann?")
	await novel_interface.show_dialog("Das Bergungsteam überprüfte vor Ort nach über dreißig zufällig ausgewählten Personen, die sich zufällig in der Reichweite befanden. Es stellte sich heraus, dass keiner von ihnen überhaupt betroffen war.", "Ai")
	await novel_interface.show_text_only("Im Inneren des Lieferwagens herrscht Stille.")
	await novel_interface.show_text_only("Wir sind also wieder bei Null, oder?")
	await novel_interface.show_text_only("Im Moment liegen uns nur die Daten der vier Patienten vor.")
	await novel_interface.show_text_only("Dieser Typ mit dem Lolicon-Komplex, der von Elluka, dem Reporter aus Newmoridas, dem Mechaniker des Elektrizitätsunternehmens und John schockiert wurde ...")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Ich schließe die Augen und versuche mein Bestes, um zwischen diesen vieren etwas Gemeinsames zu finden.")
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN.png")
	await novel_interface.show_text_only("Der Lolicon-Komplex-Typ mit Bildern von süßen Mädchen auf seinem Körperkissen und seiner Handyhülle ...")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Night_Park.png")
	await novel_interface.show_text_only("John, der uns erzählte, dass er Beatrice heimlich dabei gefilmt hatte, wie sie auf dem Dach des Lastwagens schreit …")
	novel_interface.change_background("res://assets/images/bg/Soya/Cordon.png")
	await novel_interface.show_text_only("Die Reporterin, die sich nach vorne drängte, aber den Kameraauslöser nicht drücken konnte ...")
	novel_interface.change_background("res://assets/images/bg/Soya/AkihabaraNN.png")
	await novel_interface.show_text_only("Und oh, als ich diesen armen Polizisten zu Boden stieß, wurde ich da nicht von einem Mechaniker in der Uniform eines Elektrizitätsunternehmens gefilmt?")
	novel_interface.change_background("res://assets/images/bg/Soya/Parade.png")
	await novel_interface.show_text_only("Was alle vier gemeinsam hatten...")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("Sie hatten ihre Telefone raus...", "Lian")
	novel_interface.show_background("res://assets/images/bg/Soya/Backseat.png")
	await novel_interface.show_dialog("Hmm?", "Ai")
	novel_interface.show_character("ren_fishnet","normal1")
	await novel_interface.show_dialog("Die Patienten... nutzten sie nicht alle ihre Telefone oder andere digitale Geräte in der Nähe der Straßenlaternen?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Oh, du meinst...", "Ai")
	await novel_interface.show_text_only("Aya schnappt nach Luft, als hätte sie das fehlende Puzzleteil gefunden.")
	novel_interface.change_background("res://assets/images/bg/Soya/infrared.png")
	await novel_interface.show_dialog("Es stimmt, dass bestimmte Digitalkameras unsichtbares Licht in sichtbares Licht umwandeln können.", "Ai")
	await novel_interface.show_dialog("Es ist so, als ob Sie einen wirklich hellen Lichtstrahl auf Ihrem Foto einfangen würden, wenn Sie die Linse mehrerer Mobiltelefone auf den Sender einer Infrarot-Fernbedienung richten und dann die Taste der Fernbedienung drücken.", "Ai")
	await novel_interface.show_dialog("Wenn diese vier also zufällig ein Foto oder Video aufgenommen haben, auf dem die Straßenlaterne in einem bestimmten Winkel zu sehen ist, werden sie „es“ sehen.", "Ai")
	novel_interface.change_background("res://assets/images/bg/Soya/Backseat.png")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("Wenn ich mein Telefon also genauso nutzen würde wie sie, wäre ich dann auch betroffen?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ihr Telefon ist ein speziell von SID angepasstes Telefon. Über die Linse ist eine transparente Folie geklebt, die unsichtbares Licht herausfiltert.", "Ai")
	await novel_interface.show_dialog("Dies ist jedoch normalerweise nur bei High-End-Fotoausrüstung zu finden. Und manche Leute meiden bewusst Kameramodelle mit solchen Filtern, weil sie denken, dass ihre Fotos dadurch unrealistisch werden.", "Ai")
	await novel_interface.show_dialog("Das ist so aufregend! Ich werde mir sofort ein paar D-Klasse-Mitarbeiter als Testobjekte besorgen!", "Ai")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("Hey, warte!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Aya ignoriert meine Proteste und trennt sich vom Gespräch, wahrscheinlich bereit, erneut Chaos anzurichten.")
	await novel_interface.show_text_only("Haha, mir tun ihre nächsten Opfer so leid.")
	await novel_interface.show_text_only("Ich drehe mich zu Sonya um, die schweigend aus dem Fenster gestarrt hat.")
	await novel_interface.show_text_only("Sie wurde praktisch von Elgana erzogen, nicht wahr?")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("(Sie sieht in Elgana wahrscheinlich die Mutter, die sie nie hatte ...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich klopfe Sonya auf die Schulter und sie dreht sich mit einem wehmütigen Lächeln zu mir um.")
	await novel_interface.show_text_only("Vielleicht neigen Menschen auch dazu, die Welt durch Kamerafilter zu sehen. Sie sehen nur das, was sie sehen wollen, und glauben, dass die reale Welt genauso aussieht, als ob sie hinter den Filtern wäre ...")
	await novel_interface.show_text_only("Aber tatsächlich ist die Welt nicht so rein, wie sie glauben.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Ich frage mich, wie die Welt aus Sonyas Augen aussieht.")
	
	# Scene 6 - 教堂场景
	novel_interface.change_background( "res://assets/images/bg/Soya/Church_N.png")
	await novel_interface.show_text_only("Als wir wieder bei der Kirche ankommen, finden wir sie von Dutzenden schwer bewaffneten Sicherheitssoldaten umzingelt vor.")
	await novel_interface.show_text_only("Wir steigen in der Nähe des Eingangs aus und Elgana steht direkt vor den goldenen Toren, würdevoll und aufrecht, als hätte sie auf uns gewartet.")
	await novel_interface.show_text_only("Mehrere SID-Agenten haben sie bereits festgehalten. Einige andere bringen ihre persönlichen Gegenstände Box für Box auf den Boden vor dem Eingang.")
	await novel_interface.show_text_only("Mit Erlaubnis der Agenten nähern wir uns Elgana.")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N_Door.png")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("Du bist ziemlich abrupt gegangen, Ren. Wie geht es deiner Taille?", "Elgana")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Als Antwort starre ich nur wütend an. Elgana blickt auf die Kisten auf dem Boden, die von den Agenten mit Beweisetiketten versiegelt wurden. Das heitere Lächeln verschwindet aus ihrem Gesicht.")
	novel_interface.show_character("el","normal")
	await novel_interface.show_dialog("Sonya, warst du es, der die geheime Kiste geöffnet hat, die das Gefängnis versiegelt hat?", "Elgana")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("…", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sie seufzt.")
	novel_interface.show_character("el","normal")
	await novel_interface.show_dialog("Du warst schon immer neugierig, nicht wahr?", "Elgana")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Als Elgana bemerkt, dass ich sie mit äußerst misstrauischen Augen anstarre, öffnet sie erneut den Mund, als wolle sie es erklären.")
	novel_interface.show_character("el","normal")
	await novel_interface.show_dialog("Dieses Kirchentor... es ist ein Meisterwerk von mir. Ich habe all die Jahre damit verbracht, damit zu experimentieren und es zu verbessern. Es ist eine Nachahmung der authentischen Heaven’s Door.", "Elgana")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("Ich kann jetzt den Prozess der Aufhebung der Funktion eines kleinen Teils des Unterdrückungssystems im menschlichen Gehirn präzise auslösen.", "Elgana")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sie klingt ziemlich stolz – als ob sie glaubt, dass sie eine Auszeichnung dafür verdient hätte, dass sie heute Abend die Märsche und Unruhen verursacht hat!")
	novel_interface.show_character("el","normal")
	await novel_interface.show_dialog("Jeder hat seine eigenen Gedanken und Wünsche, die er aus unterschiedlichen Gründen unterdrückt.", "Elgana")
	await novel_interface.show_dialog("Jeder hat Dinge, die er gerne tun würde, aber nicht kann ...", "Elgana")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("Ich wurde von der „Tür“ inspiriert, jedem zu helfen, seine unterdrückten Wünsche loszulassen, indem ich die Kräfte der Tür nutzte.", "Elgana")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Ist es nicht der beste Weg für uns alle, Erlösung zu erlangen?", "Elgana")
	await novel_interface.show_dialog("Ich habe es gut gemacht, oder?", "Elgana")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elganas Stimme zittert, obwohl ihre Haltung anmutig bleibt.")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("Ah, vielleicht ist es zu tiefgründig, als dass Sie es verstehen könnten.", "Elgana")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sie hebt den Kopf, als würde sie in Erinnerungen schwelgen...")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("Das Dorf, in dem ich geboren wurde, war klein und hatte nur etwas mehr als hundert Einwohner. Vor mehr als zehn Jahren brach eine Räuberbande während des Sonntagsgottesdienstes in unsere Kirche ein ...", "Elgana")
	await novel_interface.show_dialog("Von den vier Räubern hatten nur zwei Waffen. Sie haben es trotzdem geschafft, uns alles wegzunehmen.", "Elgana")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Sie wurden von einem militärischen Deserteur angeführt, der sagte, er wolle zehn Dorfbewohner auslosen, die getötet werden sollten, und damit dem System folgen, das sie in der Armee zur Bestrafung von Deserteuren hatten.", "Elgana")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ein Schauer läuft mir über den Rücken. Ich wusste, dass es in vielen Ländern bereits lange vor Ausbruch des Siebenjährigen Krieges anhaltende Konflikte zwischen den Gebieten gab.")
	await novel_interface.show_text_only("Um so viele Mitglieder wie möglich einzuziehen, wandte das Militär einige recht brutale Bestrafungsmethoden an.")
	novel_interface.show_character("el","sad")
	await novel_interface.show_dialog("Ich wurde damals mit dem Schaft einer Waffe bewusstlos geschlagen, als ich versuchte, meine Tochter zu beschützen ...", "Elgana")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Tochter...?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("el","sad")
	await novel_interface.show_dialog("Alle einhundert von uns mussten sitzen und zusehen, wie die Räuber die zehn Dorfbewohner ausweideten, die mit ihren Messern den Kürzeren gezogen hatten. Ob alt oder jung, sie haben sie alle getötet.", "Elgana")
	await novel_interface.show_dialog("Keiner der Dorfbewohner wagte es, für jemand anderen einzustehen. Sie saßen nur da und beteten, dass sie nicht ausgewählt würden.", "Elgana")
	await novel_interface.show_dialog("Als die Männer der Armee, die hinter den Deserteuren her waren, endlich eintrafen und die vier Räuber gefangen nahmen, stellten sie fest, dass die Jungs tatsächlich nur zwei Kugeln unter ihnen hatten. Zwei!", "Elgana")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elgana bricht plötzlich in Kichern aus, obwohl sie Tränen in den Augenwinkeln hat.")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("Nur zwei Kugeln...", "Elgana")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Zwei Kugeln, die ihre ganze Welt zerstörten. Ich beobachte sie schweigend und versuche mir vorzustellen, wie sie sich gefühlt haben muss, als sie aufwachte und erfuhr, dass niemand ihre kleine Tochter verteidigt hatte, als sie getötet wurde.")
	await novel_interface.show_text_only("Ohne Johns Hilfe heute wären Sonya und ich vielleicht auch in große Schwierigkeiten geraten.")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("(Warten Sie ... Elluka hat eine militärische elektronische Augenprothese. Vielleicht war sie auch vom Lampenschirm betroffen und hat deshalb so viel gegessen?)", "Lian")
	await novel_interface.show_dialog("Unterdrückte Wünsche loslassen?", "Lian")
	await novel_interface.show_dialog("Diese Räuber waren doch diejenigen, die ihrem unterdrückten Hass gegenüber der Armee freien Lauf ließen, nicht wahr? Und was hat das denn gebracht?", "Lian")
	await novel_interface.show_dialog("Die Tür, die du benutzt hast ... ist dir nicht klar, wie viel Geld Sonya dafür bezahlt hat, sie zu schließen?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("el","surprised")
	await novel_interface.show_dialog("Schließen?", "Elgana")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elgana erhebt ihre Stimme, hoch, scharf, angespannt.")
	novel_interface.show_character("el","surprised")
	await novel_interface.show_dialog("Warum es schließen? Wenn wir alle Einschränkungen loswerden und eins werden könnten ... wäre das nicht das Ideal für den Menschen?", "Elgana")
	novel_interface.change_expression("shout")
	await novel_interface.show_dialog("Sonya war die erste Person, die Gott durch die Tür lud. Doch sie lehnte das Angebot ab!", "Elgana")
	await novel_interface.show_dialog("Es ist ihre eigene Schuld. Es ist kein Opfer! Alle Kinder in der Abtei werden ohnehin dazu erzogen, eins mit Gott zu werden.", "Elgana")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elgana deutet auf Sonya.")
	novel_interface.show_character("el","shout")
	await novel_interface.show_dialog("Sie hätte es von Anfang an wissen müssen!", "Elgana")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Da ich meine Wut nicht länger zurückhalten kann, gehe ich einen Schritt näher und schlage Elgana ins Gesicht, was sogar die Agenten in der Nähe überrascht.")
	await novel_interface.show_text_only("Elgana greift nach oben, berührt ihre flammende Wange und senkt schweigend den Kopf.")
	await novel_interface.show_text_only("Ich bin selbst ziemlich überrascht von dem, was ich getan habe. Schwer atmend schaffe ich es wieder, mit kaltem Ton zu sprechen.")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("Sie haben Experimente mit der Substanz H auf internationalem Territorium durchgeführt und werden mit Sicherheit vom Vereinigten Kongress vor Gericht gebracht. Ich habe dir nichts zu sagen. Auf Wiedersehen.", "Lian")
	await novel_interface.hide_character()
	
	# Scene 7 - 切回地下密室
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("<Inzwischen im Keller>")
	novel_interface.change_background("res://assets/images/bg/Soya/Underground_Hall.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("Lumbert hört aufmerksam zu, während Mariru die Einzelheiten des Experiments erzählt.")
	novel_interface.show_character("lambert","frown")
	await novel_interface.show_dialog("Wir werden die Statistiken sowieso später brauchen, also können wir Sie auch gleich fragen. Sind alle Patienten, die Sie aufgenommen haben, bereits genesen?", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Ja. Einige von ihnen erlangten ihre Fähigkeit, Schmerzen zu empfinden, noch bevor sie das Krankenhaus erreichten. Sie schrien wie verrückt im Krankenwagen.", "Mariru")
	await novel_interface.show_dialog("Und übrigens, Ihr Einsatzkommando war meinen Männern gegenüber ziemlich gewalttätig, oder?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Als er das bösartige Glitzern in Marirus Augen sieht, hebt Lumbert kapitulierend beide Hände, tritt zwei Schritte zurück, zuckt mit den Schultern und lächelt beruhigend.")
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("Richtig, aber...", "Lumbert")
	await novel_interface.show_dialog("Ich schwöre, ich weiß nichts über dieses Experiment. Und ich habe kein Einsatzkommando geschickt.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("Was?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("Ich habe dir das nur erlaubt, mir das alles zu erzählen, weil ich diese Informationen sowieso brauche. Ich kann es mir doch nicht verübeln, dass ich neugierig bin, oder?", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("Ich habe dir gesagt, dieser Typ ist ein alter Fuchs.", "Akiko")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Akiko schließt ihre Aktentasche und verdreht die Augen zu Lumbert.")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("Warten Sie, wenn selbst SIE nichts darüber wissen ...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru zückt ihr Handy, ihr Gehirn schmiedet bereits auf Hochtouren Theorien.")
	await novel_interface.show_text_only("Sie wählt Theresas Nummer. Es klingelt eine Weile, bevor Theresa endlich abhebt und sich halb schlafend anhört.")
	await novel_interface.show_dialog("Hallo? Ich bin endlich im Bett... warum musstest du mich wecken?", "Theresa")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("Beantworten Sie einfach diese eine Frage ...", "Mariru")
	await novel_interface.show_dialog("Bevor Dr. Deckers zu der nichtöffentlichen Sitzung ging, bat er Sie, Raphilia eine Nachricht zu überbringen. Was war es?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Hä? Er machte sich nur Sorgen um seine Enkelin und wollte sie früher nach Hause bringen ...", "Theresa")
	await novel_interface.show_dialog("Er stimmte zu, das Voynich-Manuskript für sie zu beschaffen ...", "Theresa")
	await novel_interface.show_dialog("Unter der Bedingung, dass sie nach Hause kommt, sobald während der zwei Tage, an denen er bei dem Treffen ist, die Straßenlaternen angehen.", "Theresa")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("... Der alte Fuchs weiß also definitiv etwas!", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru ruft Ren direkt nach dem Auflegen an.")
	
	# Scene 8 - 最终场景
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Marirus Stimme dröhnt aus dem Nichts aus dem Ohrhörer und ich gehe ein paar Schritte zur Seite, um sie besser hören zu können.")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("ren_fishnet","normal1")
	await novel_interface.show_dialog("Mariru?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ren, verschwinde sofort von dort. Das Auto steht am Tor!", "Mariru")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("W-was ist los?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich werfe einen Blick auf die beschäftigten SID-Agenten und Sonya, die immer noch schweigend dasteht. Alles scheint in Ordnung zu sein. Warum ist Mariru plötzlich so nervös?")
	await novel_interface.show_dialog("Unsere sechs Bergungsteams wurden von den Sicherheitskräften abgefangen, und auch der vorübergehende Überwachungszugang, den sie dem SID gewährt hatten, wurde gerade widerrufen.", "Mariru")
	await novel_interface.show_text_only("Ich bemerke, wie die Sicherheitskräfte am Kircheneingang vor Aufregung summen, als hätten sie gerade eine neue Anweisung erhalten.")
	await novel_interface.show_dialog("Wie dem auch sei, verschwinde jetzt da! Die einzigen, die das alles auf einmal schaffen könnten, sind –", "Mariru")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Bevor Mariru zu Ende sprechen kann, ertönt ein Rauschen und die Verbindung bricht ab.")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N3.png")
	await novel_interface.show_text_only("Ich schaue mich um – irgendetwas scheint sich in der Atmosphäre verändert zu haben.")
	await novel_interface.show_text_only("Die Gebäude in der Ferne sind nicht mehr sichtbar und hinterlassen nur noch eine verzerrte Unschärfe. Auch der Himmel hat sich verdunkelt.")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("Alle Sterne sind weg...?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Zwei schwarze gepanzerte Lastwagen ohne Nummernschild rasen in die Kirche. Ein schwarzer Hubschrauber senkt sich langsam vom Himmel.")
	await novel_interface.show_text_only("Die Sicherheitssoldaten und die Neuankömmlinge stürmen auf den Platz und deaktivieren schnell die Waffen der Agenten, die Kisten transportierten.")
	await novel_interface.show_text_only("Elgana kommt auf mich zu, lächelt eisig, fast unheimlich.")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("... Was ist los?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elgana hebt ihre Hand. Ich dachte, sie würde mich gleich zurückschlagen, aber sie tätschelt einfach meine Wange.")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("... Vor Gericht gebracht, nicht wahr? Von wem, oder?", "Elgana")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("Wer, glauben Sie, unterstützt meine Forschung?", "Elgana")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elgana dreht sich um und blickt zu dem herrlichen Wandgemälde an der Wand des Kirchengebäudes hinauf.")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("Wer hat die Macht, eine solch riesige Kirche in der vereinbarten entmilitarisierten Zone zu bauen?", "Elgana")
	await novel_interface.show_dialog("Wer hat die Macht, in so kurzer Zeit alle Straßenlaternen in der Stadt auszutauschen?", "Elgana")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sie dreht sich um und schätzt meine Reaktion ab.")
	novel_interface.show_character("el","mock")
	await novel_interface.show_dialog("Und wer hat die Macht, die Fußgängerbeschränkung auf der Electronics Street vorzeitig aufzuheben?", "Elgana")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("In meinem Gehirn schrillen die Alarmglocken. Mein Blut wird kalt.")
	await novel_interface.show_text_only("Die Soldaten, die aus den gepanzerten Lastwagen und dem Hubschrauber strömen, tragen alle schwarze Kampfanzüge für Spezialeinheiten, mit denen ich viel zu vertraut bin ...")
	await novel_interface.show_text_only("Sie ignorieren die Agenten und mich und machen sich auf den Weg zum Kirchentor.")
	novel_interface.show_character("el","mock")
	await novel_interface.show_dialog("Dieses Experiment ist der Beweis dafür, dass ich endlich eine sichere und reversible Methode gefunden habe, um den Geist von Menschen zu beeinflussen.", "Elgana")
	await novel_interface.show_dialog("Ist Ihnen bewusst, was für eine große Leistung das ist?", "Elgana")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N1.png")
	await novel_interface.show_text_only("Bald sind die Soldaten in Schwarz damit fertig, das Kirchentor in einer großen Holzkiste zu verschließen und sie in den Hubschrauber zu schleppen.")
	await novel_interface.show_text_only("Elgana streichelt meinen Kopf, als ich bemerke, dass Sonya auf uns zukommt.")
	novel_interface.show_character("el","mock")
	await novel_interface.show_dialog("Ihr habt euch gerade erst kennengelernt. Glaubst du wirklich, dass du sie schon so gut kennst?", "Elgana")
	await novel_interface.show_dialog("Glaubst du wirklich, dass sie ohne meine Forschungen zu Substanz H und die Medizin, die ich gebraut habe, so lange überlebt hätte?", "Elgana")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…")
	
	# Scene 9 - 地下密室终场
	await novel_interface.show_text_only("<Versteckter Raum, Keller>")
	novel_interface.show_background("res://assets/images/bg/Soya/Underground_Hall.png")
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("Wenn das stimmt, was Sie gesagt haben, ist das Ding viel zu viel wert ...", "Lumbert")
	await novel_interface.show_dialog("Denken Sie einfach darüber nach. Nur wenige flüchtige Bilder in einem Video könnten Millionen Menschen auf der ganzen Welt beeinflussen.", "Lumbert")
	await novel_interface.show_dialog("Mit Inhalten, die bei Menschen Wünsche und Impulse auslösen, lässt sich die breite Öffentlichkeit leicht dazu bewegen, bestimmte Produkte zu kaufen, einer Sekte beizutreten oder sich der Armee anzuschließen.", "Lumbert")
	novel_interface.change_expression("usually")
	await novel_interface.show_dialog("Es gibt keinen schnelleren Weg, an Macht zu gelangen als diesen.", "Lumbert")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru verstummt und starrt auf ihr jetzt empfangsloses Telefon.")
	novel_interface.show_character("lambert","usually")
	await novel_interface.show_dialog("Ganz gleich, wer hinter diesem Experiment steckt, sie sollten wissen, dass sie meine Unterstützung nicht haben werden.", "Lumbert")
	await novel_interface.show_dialog("Aber wie kamen Sie darauf, dass es Dr. Deckers ist?", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Eliminierungsprozess.", "Mariru")
	await novel_interface.show_dialog("Wenn es tatsächlich eine solche Organisation hinter dem Vereinigten Kongress gäbe, würde das bedeuten, dass alle sechs Akademiestädte beteiligt wären.", "Mariru")
	await novel_interface.show_dialog("Aber das ist unmöglich, denn jede Nation hat ihre eigenen Bräuche und Probleme, die sich aus der Vergangenheit angesammelt haben ...", "Mariru")
	await novel_interface.show_dialog("Die Kabinettsmitglieder des Schwebenden Palastes streiten sich ständig. Die siebzehn Herren im Newmoridas-Komitee haben jeweils ihre eigenen Ziele.", "Mariru")
	await novel_interface.show_dialog("Das Militär und die breite Öffentlichkeit in Masada haben sich nie verstanden. Und das Militär selbst besteht aus mehreren widersprüchlichen Fraktionen.", "Mariru")
	await novel_interface.show_dialog("Die Senatsmitglieder von New Opulentia werden aufgrund ihres akademischen Beitrags ausgewählt. Diese alten Kerle können kaum mit der Zeit gehen.", "Mariru")
	await novel_interface.show_dialog("Die drei wichtigsten Mafia-Fraktionen auf den Lebona-Inseln befinden sich ständig im Krieg. Sie wechseln sich im Moment ab und führen die Nation an, das ist der einzige Grund, warum es hier einigermaßen friedlich ist.", "Mariru")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("Salmonton ist die einzige der sechs Akademiestädte, in der kein Chaos herrscht. Egal, ob es um Technologie, Wirtschaft oder Politik geht, keine der anderen Nationen kann Dr. Deckers das Wasser reichen.", "Mariru")
	await novel_interface.show_dialog("Diese sogenannten „Aristokraten“ sind nichts weiter als Kleinaktionäre, die Schutz bei Deckers‘ Wirtschaftsgesellschaft suchen.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","frown")
	await novel_interface.show_dialog("Tatsächlich…", "Lumbert")
	await novel_interface.show_dialog("Er förderte das Projekt, Flüchtlinge in der Stadt willkommen zu heißen, ganz allein. Keine einzelne Person könnte in einer anderen Akademiestadt so einflussreich sein.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Wenn es also wirklich eine Organisation gäbe, die über den Führern aller Nationen steht, wäre Dr. Deckers definitiv Mitglied.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_dialog("Keine Ahnung, welche Rolle dieser schlaue alte Mann dort spielt ...", "Mariru")
	
	# Scene 10 - 最终告别
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N1.png")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	await novel_interface.show_text_only("Sonya kommt auf uns zu und zieht mich zur Seite.")
	await novel_interface.show_text_only("Elgana stapft einfach davon, mit herablassendem Blick, während sie die Soldaten daran erinnert, auch ihre Kisten mit „Beweisen“ in den Hubschrauber zu bringen.")
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("Ren...", "Soya")
	await novel_interface.show_dialog("Es tut mir so leid, dass ich es dir nicht früher gesagt habe ... Ich wusste einfach nicht, wie ich es ausdrücken soll.", "Soya")
	await novel_interface.show_dialog("Aber bitte glauben Sie mir, ich habe erst heute herausgefunden, dass Mutter auch über solche Dinge recherchiert hat ...", "Soya")
	await novel_interface.show_dialog("Ich darf in alle Länder frei ein- und ausreisen, aber ich würde sterben, wenn ich zu weit von ihr entfernt wäre.", "Soya")
	await novel_interface.show_dialog("Deshalb bin ich jetzt eigentlich in New Opulentia ... weil sie hier ist.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya hält den Kopf gesenkt, die Stimme leise und hilflos.")
	novel_interface.show_character("soya_uniform","snivel")
	await novel_interface.show_dialog("Und sie hat recht...", "Soya")
	await novel_interface.show_dialog("Die von der Abtei aufgenommenen Waisenkinder sind schließlich dazu bestimmt, schwarzgekleidete Mönche zu werden.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich lege meine Arme um das zitternde Mädchen.")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Sie müssen sich für nichts entschuldigen.", "Lian")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	await novel_interface.show_text_only("In meiner Umarmung flüstert Sonya:")
	await novel_interface.show_dialog("Hey...", "Soya")
	await novel_interface.show_dialog("Weißt du was? Wenn ich deine Hand halte... habe ich das Gefühl, von einer Kugel aus warmem, leuchtendem Licht umhüllt zu sein. Ich habe das Gefühl, ich könnte alles tun.", "Soya")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("(Huh? Meine Hand?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elgana steht neben dem Hubschrauber und bedeutet Sonya, sich ihr anzuschließen. Aber das Mädchen wirft einfach ihre Arme um mich, wie ein Kind, das es nicht erträgt, sich von seiner Mutter zu trennen.")
	await novel_interface.show_text_only("Sie schluchzt ihre letzten Worte.")
	await novel_interface.show_dialog("Es tut mir so leid... wenn wir nur mehr Zeit gehabt hätten... wie echte Freunde...", "Soya")
	await novel_interface.show_text_only("Etwas brennt an der Außenseite meines Oberschenkels. Seltsam. Ich bin gerade dabei, nach unten zu schauen und nachzusehen, als mir klar wird, dass ich mich nicht mehr bewegen kann.")
	await novel_interface.show_text_only("Kann auch keinen Ton von sich geben. Ich bin völlig unbeweglich.")
	await novel_interface.show_dialog("(...Ist das das Kugelfischgift?)", "Lian")
	await novel_interface.show_dialog("(Sonja...)", "Lian")
	await novel_interface.show_text_only("Meine Muskeln sind gelähmt, mein Gesicht ist erstarrt.")
	await novel_interface.show_text_only("Sonya setzt mich sanft auf den Boden, sodass ich an den Marmorrand des Brunnens lehne.")
	await novel_interface.show_text_only("Sie ist auch so nett, etwas hinter meinen Rücken zu legen, damit meine Taille weniger schmerzt.")
	await novel_interface.show_text_only("Die Soldaten in Schwarz scheinen ihre Arbeit bereits erledigt zu haben und evakuieren alle mit ihren Militärfahrzeugen.")
	await novel_interface.show_text_only("Sonya wirft mir einen letzten Blick zu, bevor sie sich umdreht und zum Helikopter sprintet.")
	await novel_interface.show_text_only("Bald höre ich, wie der Hubschrauber abhebt. Auch die Sicherheitskräfte ziehen gruppenweise ab.")
	await novel_interface.show_text_only("Ich versuche verzweifelt, meinen Kopf zu heben, um Sonya ein letztes Mal zu sehen, aber ich kann mich keinen Zentimeter bewegen.")
	await novel_interface.show_text_only("Als die Geräusche des Helikopters verklingen und das Signal wiederhergestellt ist, höre ich Mariru in meinen Ohrhörer bellen.")
	await novel_interface.show_dialog("Hallo? Ren? Was ist da los?", "Mariru")
	await novel_interface.show_dialog("Der Fahrer erzählte mir, er habe gerade herausgefunden, dass die Batterie in der Straßenlaterne, die ihr abgesägt habt, leer ist!", "Mariru")
	await novel_interface.show_dialog("Aya sagt, wenn eine Spannung von mehr als 32 V angelegt wird, und sei es auch nur für eine Millisekunde, explodiert es!", "Mariru")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Moment ... der längste zulässige Abstand zwischen meinem Elektroschock-Fußkettchen und dem von Sonya beträgt –")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N2.png")
	await novel_interface.show_text_only("Plötzlich ist in der Ferne ein scharfer, ohrenbetäubender Knall zu hören. Der Nachthimmel erleuchtet – so hell, als wäre es Mittag.")
	await novel_interface.show_text_only("Der Hubschrauber ist explodiert.")
	print("=== 天启篇第19话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
