# apocalypse_ep14.gd - 天启篇第14话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第14话剧本
	apocalypse_ep14_script()

func play_script():
	pass

# 天启篇第14话 - 正式剧本
func apocalypse_ep14_script():
	# 开场设置
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("Guardo l'auto che riporta Elluka al quartier generale della SID allontanarsi, scomparendo alla fine della strada. Il mio cervello è ancora pieno di immagini del ragazzo privo di sensi e di tutto quel sangue...")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("John dovrebbe stare bene, vero?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya risponde, abbassando lo sguardo sul frammento di vetro insanguinato che ha in mano:")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Ha colpito alcuni dei suoi muscoli ma non ha colpito nessuna delle arterie principali. Dovrebbe stare bene se lo curano in tempo.", "Soya")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("Eppure è pazzesco come abbia camminato per più di venti minuti con quel tipo di ferita. Qualsiasi persona normale probabilmente sarebbe già svenuta.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("... Forse ha il CIPA o qualcosa del genere?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("È un disturbo che ricordo di aver visto in TV. Molti personaggi ce l'hanno negli anime e nei drammi.")
	await novel_interface.show_text_only("Non riescono a sentire dolore, quindi anche l'appendicite può ucciderli: potrebbero anche non notare che qualcosa non va finché non c'è un buco nello stomaco o qualcosa del genere.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Probabilmente dovrebbe avere ancora i sensi tattili in quel caso.", "Soya")
	await novel_interface.show_dialog("Avrebbe dovuto essere in grado almeno di sentire tutta quella macchia di sangue rappreso sui pantaloni. Eppure non sembrava averlo notato affatto. È davvero...", "Soya")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("Affascinante!", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("Cosa?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("Dovremmo andare a controllarlo in ospedale. Guarda che tipo di stimoli gli faranno reagire.", "Soya")
	await novel_interface.show_dialog("O forse era troppo concentrato su Ren per notare il dolore?", "Soya")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("In tal caso, dovremo utilizzare anche Ren come parte dell'esperimento. Devo prenderla in prestito da quella femmina di gorilla...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mentre Sonya continua a divagare, il mio petto vibra dal nulla.")
	await novel_interface.show_dialog("Chi stavi chiamando una femmina di gorilla, eh?", "Mariru")
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("M-Mariru?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya agita i capelli inorridita ma non vede Mariru da nessuna parte. Ci sono solo io, una mano sul mio petto ronzante.")
	await novel_interface.show_dialog("Ti manco ancora, Ren?", "Mariru")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("Non puoi semplicemente chiamarmi sul mio telefono?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","laugh",0.25)
	await novel_interface.show_dialog("Ehi...", "Soya")
	await novel_interface.show_text_only("Scoprendo finalmente la fonte della voce, Sonya si avvicina a me con gli occhi che brillano di curiosità.")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Salta verso il mio seno, proprio come un golden retriever con la coda scodinzolante...")
	await novel_interface.show_text_only("Dalla sua caviglia appare un improvviso arco luminoso. Sonya sbatte a terra.")
	await novel_interface.show_text_only("Il suo braccio e la sua gamba destra hanno due spasmi e riesce ad arrampicarsi, semiparalizzata.")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("(Sembra che si stia riprendendo più velocemente dalle scosse elettriche ora...?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Con gli occhi colmi di lacrime, la ragazza si siede, massaggiandosi il braccio sinistro dolorante, e alza la testa verso il cielo in un silenzioso lamento.")
	novel_interface.show_character("soya_uniform","cry")
	await novel_interface.show_dialog("Cavolo, puoi anche controllare a distanza questa cosa?", "Soya")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/UAV.png")
	await novel_interface.show_text_only("Seguo lo sguardo di Sonya e vedo un minuscolo punto rosso sospeso nell'aria.")
	await novel_interface.show_dialog("Un drone?", "Lian")
	await novel_interface.show_dialog("I droni non sono vietati in quest’area?", "Lian")
	await novel_interface.show_text_only("I divieti non hanno mai ostacolato il SID, ovviamente, ma Mariru stessa non ha detto un paio di giorni fa che dobbiamo peccare per eccesso di cautela durante il Forum Internazionale di Pace?")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("ren_fishnet","uneasy")
	await novel_interface.show_dialog("(Beh, immagino che nemmeno attaccare i poliziotti, evadere il carcere e scatenare rivolte non contenga errori di prudenza...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("La situazione oggi è particolare. Sono già più di cinquantamila le persone radunate sulla Prima Avenue, che marciano per chissà cosa.", "Mariru")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("Così tanti?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ci sono già state rivolte in sette aree. Il quartier generale dei soldati della sicurezza è un disastro in questo momento.", "Mariru")
	await novel_interface.show_dialog("Ho detto al loro comandante che se non affrontano queste rivolte in modo appropriato, New Opulentia potrebbe essere nei guai...", "Mariru")
	await novel_interface.show_dialog("E in un certo senso gli ho fatto un po' pressione parlando della sua famiglia. Il poveretto ha accettato di permettere subito al SID di aggirare alcune restrizioni.", "Mariru")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("(\"Un po'\" sotto pressione?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Hanno fatto davvero di tutto per il Forum quest'anno. Anche rimontati con nuovi modelli tutti i lampioni della Zona Demilitarizzata Convenzionata.", "Mariru")
	await novel_interface.show_dialog("Ogni lampione ora funge anche da telecamera di sorveglianza. Sono state installate anche le reti e le unità corrispondenti.", "Mariru")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Non è un piano molto intelligente. Sicuramente ci sono luoghi senza lampioni. Altrimenti perché dovresti usare i droni, giusto?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("dice Sonya in tono beffardo, ma Mariru semplicemente canticchia d'accordo.")
	await novel_interface.show_dialog("Sì, non è affatto un piano intelligente. Costa molto e non dà molti risultati. Inoltre, c’è anche un enorme fattore di rischio politico…", "Mariru")
	await novel_interface.show_dialog("Se i media scoprissero che ci sono telecamere di sorveglianza ovunque, tirerebbero sicuramente fuori i classici romanzi distopici. George Orwell e cose del genere. Il Congresso Unito sarebbe sotto tiro.", "Mariru")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_dialog("Comunque ho scoperto quello che dovevo sapere.", "Mariru")
	novel_interface.change_background("res://assets/images/bg/Soya/Club.png")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("È ormai confermato che tutto quello che devo fare è mettere un po’ di pressione su alcune persone per convincere anche le organizzazioni più influenti del mondo a prendere decisioni palesemente stupide.", "Mariru")
	await novel_interface.show_dialog("Ora, tutto ciò che dobbiamo sapere è chi prendere di mira...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru esegue la scansione delle migliaia di profili che sono appena stati importati nel suo dispositivo portatile. Profili che contengono identità, conti bancari, importo dei fondi e altri dettagli correlati.")
	await novel_interface.show_dialog("Cosa intendi con...?", "Lian")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("Ad esempio, il Senato è l’organizzazione che detiene il maggior potere sulla Federazione New Opulentia. In tal caso, quello che mi piacerebbe sapere è quanto potere detiene esattamente il Senato. Tutti devono seguire i loro ordini?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Tu non lo fai, per esempio...", "Lian")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("In poche parole, ogni nazione è composta da un sistema di potere a più livelli. Il potere detenuto dalle diverse organizzazioni è influenzato da molti fattori: l’economia, l’esercito, la storia, le culture, le religioni e altro ancora.", "Mariru")
	await novel_interface.show_dialog("Per quanto riguarda il leader di una nazione, è semplicemente un rappresentante scelto per mantenere l’equilibrio nella complicata lotta per il potere tra le diverse fazioni.", "Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Fin dall’inizio della storia, non importa in quale sistema politico – democratico, dittatura, repubblica, accademico – non c’è mai stato un vero “Re” che decidesse tutto.", "Mariru")
	await novel_interface.show_dialog("Tutto quello che c'era era qualcuno che doveva negoziare la propria strada attraverso innumerevoli situazioni contrastanti, fare scelte impossibili per tutti e prendersi la colpa per tutte le cose di cui non era colpa loro.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru fa una pausa, guardando un gruppo di membri della squadra di recupero, che stanno evacuando le masse in tute ignifughe.")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("Quella persona che ha tutta questa responsabilità... può sembrare forte, ma in realtà i suoi corpi portano più cicatrici di quante possano contarne.", "Mariru")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("…", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya rimane in silenzio, con una mano sul petto, mentre io la guardo confusa.")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("Non sono sicuro di aver capito...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Non sei destinato a farlo comunque, idiota.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya si sforza di calmare il respiro e infine chiede, in tono serio:")
	novel_interface.show_character("soya_uniform","speechless")
	await novel_interface.show_dialog("Vedo che sei qui per contrattare, ma manca ancora il pezzo finale del puzzle, quello più cruciale. Quindi sei disposto a darmi qualcosa in cambio delle mie informazioni, eh?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Sì.", "Mariru")
	await novel_interface.show_text_only("Mariru risponde, facilmente.")
	await novel_interface.show_dialog("Per quanto ne so, i Cavalieri del Giudizio sono \"monaci vestiti di nero che possiedono il Sigillo della Verità\". Meno di venti fortunati hanno ricevuto un simile onore negli ultimi cinquecento anni.", "Mariru")
	await novel_interface.show_dialog("Nella storia ci sono stati innumerevoli monaci vestiti di nero di grande talento.", "Mariru")
	await novel_interface.show_dialog("Eppure nemmeno loro hanno ricevuto il Sigillo della Verità, simbolo della massima immunità nel Regno di Dio. Solo coloro che secondo la Chiesa hanno dato un contributo importante al mondo hanno questo privilegio.", "Mariru")
	await novel_interface.show_dialog("Hai ricevuto il tuo due anni fa. Vi è stato assegnato dal defunto Papa, Sua Santità Callisto IV.", "Mariru")
	await novel_interface.show_dialog("Allora non potevi avere più di dodici anni, vero?", "Mariru")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Hm, sai davvero molto.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Bene, andrò dritto al punto.", "Mariru")
	await novel_interface.show_dialog("Cosa hai fatto esattamente tre anni fa, durante la missione di “purificazione” presso lo Scudo della Guyana?", "Mariru")
	await novel_interface.show_text_only("Sonya resta in silenzio per qualche secondo prima di alzare lo sguardo.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("So cosa vuoi da me, ma ho delle condizioni.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Certo, sono tutto orecchie.", "Mariru")
	novel_interface.show_character("soya_uniform","yell")
	await novel_interface.show_dialog("Per prima cosa, disattiva questa cavigliera, adesso!", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Non posso.", "Mariru")
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("Cosa?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("La disattivazione richiede attrezzature speciali della sede SID. Non posso farlo da remoto. Per ora, tutto ciò che possiamo fare è impostare la distanza consentita tra te e Ren al massimo, circa 200 metri.", "Mariru")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("... Bene, almeno è meglio di trenta piedi.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La spia gialla sulla cavigliera di Sonya lampeggia alcune volte.")
	await novel_interface.show_dialog("È fatto.", "Mariru")
	await novel_interface.show_text_only("Con gli occhi fissi su di me, Sonya inizia a indietreggiare con cautela, fermandosi ogni pochi passi, infine sospirando di sollievo quando è ovvio che siamo a più di 650 piedi di distanza.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Bene, in secondo luogo, voglio sapere cosa succede tra Beatrice e Ren. E voglio che Ren me lo dica con parole sue.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru riflette per un po' su questo in silenzio.")
	await novel_interface.show_dialog("...Bene. Ma devi promettere che non lo dirai a nessun altro.", "Mariru")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("C-cosa? È davvero giusto dirglielo?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beatrice era morta nel XIII secolo. Secondo Aya, il corpo attuale di Beatrice è stato creato solo nel momento stesso in cui l’ho evocata.")#换行问题
	novel_interface.show_character("ren_fishnet","uneasy")
	await novel_interface.show_dialog("(Quindi ho “creato” un corpo così straordinario? È surreale...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tuttavia, questo fatto è etichettato come top secret. Nemmeno il Senato può saperlo.")
	await novel_interface.show_text_only("Attualmente, solo otto persone in tutto il mondo conoscono la verità: io, Annie, Beatrice stessa, Raphilia, il dottor Dekkers, Mariru, Aya e Henrietta.")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("(Le informazioni che Mariru vuole da Sonya devono essere incredibilmente importanti...)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Prometto di non dirlo ad anima viva.", "Soya")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("Ma non dimenticare: se Ren mente, lo capirò a colpo d'occhio!", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("Va bene, va bene!\nSmettila di fregarlo...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Procedo raccontando la mia esperienza allo Sky Hotel, dove ho evocato Beatrice utilizzando la collana di smeraldi di Raphilia.")
	await novel_interface.show_text_only("Con il permesso di Mariru, le racconto la parte in cui Beatrice sconfigge Igor e anche la sua \"maledizione\".")
	await novel_interface.show_text_only("Sonya ascolta, con gli occhi lucidi, come un bambino che si gode una favola della buonanotte, intervenendo di tanto in tanto con sussulti eccitati.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Quindi lo smeraldo su quella collana che apparteneva alla famiglia di Raphilia... era incastonato nella spada di Beatrice secoli fa?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Sì. Aya lo ha confermato. È un'esperta.", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Beatrice Portinari... era nell'opera di Dante, raffigurata come una strega...", "Soya")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("È così affascinante!", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ehm.", "Mariru")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Ok, le prove di cui hai bisogno... sono proprio dentro di me! Quella ragazza Aya probabilmente sarà in grado di rilevarlo.", "Soya")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Ma voglio stare con Ren ancora un po'! Possiamo tornare al SID domani invece che adesso? Prometto di tornare prima di mezzogiorno!", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Bene...", "Mariru")
	await novel_interface.show_dialog("Oh, a proposito, Ren, Aya ha raccolto tutti i filmati di sorveglianza dei droni e dei soldati della sicurezza e li ha messi tutti insieme su una pagina. Anche tu hai accesso, puoi controllarlo sul tuo telefono.", "Mariru")
	await novel_interface.show_dialog("Non sappiamo ancora se il caos di stasera è causato dalla sostanza H. Promettimi che starai attento.", "Mariru")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Mariru quindi interrompe la connessione.")
	novel_interface.change_background("res://assets/images/bg/Soya/Club.png")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("Per quanto riguarda voi ragazzi...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lancia un'occhiataccia agli uomini che ha catturato all'asta, tutti legati, seminudi, con la bocca fasciata.")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("Preferiresti morire per una fuga di radiazioni...", "Mariru")
	await novel_interface.show_dialog("O collaborare con me e poi permetterci di cancellare i tuoi ricordi?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Gli uomini, contorcendosi dal terrore, emettono gemiti frenetici dietro il nastro adesivo.")
	await novel_interface.show_text_only("Mariru ne calpesta uno con forza. Sul suo viso c'è un sorriso altezzoso, da regina.")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Lo pensavo.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_dialog("Eheheh...", "Soya")
	await novel_interface.show_text_only("Non appena Mariru riattacca, Sonya mi fa un ampio sorriso.")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("C-cosa...?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("C'è una domanda che volevo farti... ma pensavo che la femmina di gorilla non te lo permettesse.", "Soya")
	await novel_interface.show_dialog("Dato che anche tu sei affetto dalla maledizione di Beatrice, devi essere maschio, eh?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("Cosa?", "Lian")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("Io... no, sono una ragazza...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Come posso rispondere a questo?")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("La tua aura mi dice che non stai dicendo tutta la verità...", "Soya")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("Ahh... Ren, sei davvero il più affascinante di tutti!", "Soya")
	await novel_interface.show_dialog("E comunque come funzionano le tue tette?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("Smettila! Andare via!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tento di fuggire verso la chiesa.")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("Ehi, aspetta... non hai contattato quella Madre Elgana per dirle che saremmo arrivati presto?\nÈ davvero giusto farla aspettare?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_dialog("Ah, tu sei Ren, vero?", "Voce femminile")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N_Door.png")
	await novel_interface.show_text_only("La voce di una donna, morbida e gentile.")
	novel_interface.show_character("el","smile")
	await novel_interface.show_text_only("Seguo il suono e vedo una suora in piedi all'ingresso della chiesa, che sorride benevolmente.")
	await novel_interface.show_text_only("Sembra essere sulla trentina, la pelle luminosa, lunghi capelli biondi che le scendono fino alla vita.")
	await novel_interface.show_dialog("Avevo paura che ti saresti perso per strada!", "Suora")
	await novel_interface.show_dialog("Sono Elgana.", "Suora")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("Madre Elgana...?", "Lian")
	await novel_interface.hide_character()
	
	print("=== 天启篇第14话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
