# apocalypse_ep10.gd - 天启篇第10话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第10话剧本
	apocalypse_ep10_script()

func play_script():
	pass

# 天启篇第10话 - 正式剧本
func apocalypse_ep10_script():
	# 场景：秋叶原夜晚
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("我和索婭趕回了燈火依舊通明的電器街。")
	await novel_interface.show_text_only("貓丸電器本店外牆三四層高的大螢幕上，正重複播放著贊助商的廣告影片。")
	await novel_interface.show_text_only("幾輛由貨車改造而成的巡迴花車，在行人徒步區中央整齊地排成一列。")
	await novel_interface.show_text_only("花車兩側都印著巨幅彩繪廣告，車頂是裝飾精緻的圍欄，一些工作人員正在測試音響設備。")
	novel_interface.show_character("soya_uniform", "speechless")
	await novel_interface.show_dialog("這是要舉辦什麼活動嗎？", "索婭")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("電器街的人比我們剛剛離開時更多了，還有遊客不斷湧入。")
	novel_interface.show_character("ren_fishnet", "perspire1")
	await novel_interface.show_dialog("啊，今天難道是……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我忽然想起曾在網路上看過類似的場景，便馬上拿出手機搜尋。")
	await novel_interface.show_text_only("果然──今晚是電器街一年一度的特殊慶典。")
	await novel_interface.show_text_only("五年前，隨著新豐洲的局勢逐漸穩定，元老院宣佈廢除了《社會秩序維護法》等多個文化管制法案。")
	await novel_interface.show_text_only("決議生效前一晚，很多人自發性地聚集在貓丸電器的大螢幕下倒數計時，慶祝這一個「偉大的勝利」。")
	await novel_interface.show_text_only("後來有人在網路上惡搞，將這事件改編成御宅族的前輩反抗暴政，奮勇抵抗最終拯救世界的故事。")
	await novel_interface.show_text_only("後續還引發了一群「老戰士」的集體創作，眾人紛紛用回憶的形式補完「那場戰爭」。")
	await novel_interface.show_text_only("還煞有介事的說，戰後政府決定對全世界進行記憶消除，只保留部分功臣的記憶……")
	await novel_interface.show_text_only("而那次倒數計時，就是記憶消除的前一夜，倖存者們一邊讀秒一邊熱淚盈眶地緬懷戰爭烈士。")
	novel_interface.show_character("ren_fishnet", "wail")
	await novel_interface.show_dialog("（蠢爆了！誰會信啊！！）", "小憐")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（虧我當年看得那麼熱血……）", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不過商家倒是把握了這個機會，將這一天打造成年度促銷慶典，還吸引了大批贊助商。")
	novel_interface.show_character("ren_fishnet", "uneasy")
	await novel_interface.show_dialog("難怪今天下午在免費發送周邊商品……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我嫉妒地看著路人手中的黃色小旗子。")
	novel_interface.show_character("soya_uniform", "wordless")
	await novel_interface.show_dialog("如果活動會持續到12點……現在的氣氛也太熱烈了吧？", "索婭")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我看了看手錶，還不到8點，街上的人群卻異常興奮。")
	await novel_interface.show_text_only("由於今年的人數遠遠超過預期，現場維持秩序的保安警察顯得力不從心。")
	novel_interface.show_character("ren_fishnet", "upset")
	await novel_interface.show_dialog("話說……我們兩個應該算逃犯吧？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我看著附近的幾個員警，不知這次他們會被索婭用什麼新花招撂倒。")
	novel_interface.show_character("soya_uniform", "relieve")
	await novel_interface.show_dialog("低調點──", "索婭")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索婭掐了我一下，指著對街。")
	novel_interface.show_character("soya_uniform", "smile")
	await novel_interface.show_dialog("看見那兩輛黑色裝甲車了嗎？", "索婭")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我朝著她手指的方向看去，那種裝甲車裡應該是待命的保安警察……搞不好是紐摩利達斯攻擊隊！")
	novel_interface.show_character("soya_uniform", "jest")
	await novel_interface.show_dialog("萬一把那群傢伙吸引過來，我可沒法幫妳擋子彈～", "索婭")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索婭看了看我毫無肌肉的大腿後露出鄙視的微笑，不會躲子彈還真抱歉啊！")
	novel_interface.show_character("ren_fishnet", "upset")
	await novel_interface.show_dialog("這裡這麼多人，不知能不能找到伊露卡……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我煩惱地環視四周熙熙攘攘的人群，一想到伊露卡在這種環境下那迷茫無助的小眼神就一陣揪心。")
	novel_interface.show_character("soya_uniform", "jest")
	await novel_interface.show_dialog("她不就在那嗎，喏～", "索婭")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "perspire1")
	await novel_interface.show_dialog("啥！？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索婭用下巴示意前方被裝飾成神龕的花車，坐在神位上的那個小蘿莉正是伊露卡。")
	await novel_interface.show_text_only("不知道是哪家贊助廠商的花車，前面掛著一個巨大的燈籠，燈籠後還有兩個人敲擊著太鼓。")
	await novel_interface.show_text_only("花車下密密麻麻的圍了上百個人，正用朝聖般的眼神注視著車上的大萌神。")
	await novel_interface.show_text_only("還有十幾個人穿著應援服站成一排，每人手中都拿著兩支黃色的小旗子，隨著太鼓的節奏打call。")
	await novel_interface.show_text_only("只見伊露卡從面前的貢品台上捧起一個巧克力奶油卷，咬幾口就吃光了。")
	
	# 显示伊露卡，使用iluka_hide而不是iluka_uniform
	await novel_interface.show_dialog("欸嘿嘿嘿……", "伊露卡")
	await novel_interface.show_text_only("──吃完後還展現出沒心沒肺的幸福笑容。")
	await novel_interface.show_text_only("眾人看她吃完，立刻一陣歡呼，應援隊也掀起一陣高潮。")
	await novel_interface.show_text_only("接著伊露卡又滿眼星星地挑選起下一件「貢品」。")
	novel_interface.show_character("ren_fishnet", "wail")
	await novel_interface.show_dialog("……", "小憐")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("這是什麼情形啊？有那麼餓嗎？！", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "laugh")
	await novel_interface.show_dialog("哦呀呀～場面相當熱絡喔。", "索婭")
	await novel_interface.hide_character()
	
	# 场景转换
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("我們繞著花車勘查了一圈。")
	await novel_interface.show_text_only("除了強行穿越那群把花車圍得密不透風的「親衛隊」以外，似乎沒有其他方法可接近依露卡了。")
	novel_interface.show_character("ren_fishnet", "upset")
	await novel_interface.show_dialog("但這樣一定會引起注意的啦……", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我們遠遠看著在花車上大快朵頤的伊露卡，既然確定她沒有危險，似乎也不用那麼著急了。")
	novel_interface.show_character("soya_uniform", "jest")
	await novel_interface.show_dialog("吶～為什麼有人對小蘿莉那麼狂熱呢？在歐洲，人們認為這種行為很變態哦──", "索婭")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索婭一臉賊賊地問我。")
	novel_interface.show_character("ren_fishnet", "perspire1")
	await novel_interface.show_dialog("變、變態？\n想太多了吧……", "小憐")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("妳看，就像有人喜歡動物的幼崽一樣──單純、認真、又有點笨拙……", "小憐")
	await novel_interface.show_dialog("那種美好、純淨，讓人不忍心傷害、想要抱緊，呃，保護……的感覺", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我試圖辯解，但似乎越描越黑了。")
	novel_interface.show_character("ren_fishnet", "shy_left")
	await novel_interface.show_dialog("說到變態，妳和他們根本不是同個等級吧！", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "laugh")
	await novel_interface.show_dialog("嘿嘿，變態有什麼不好的～", "索婭")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("如果「普通」的定義是特定環境中所有人的平均狀態，那麼與平均值相差過大的人就會被當做變態。", "索婭")
	await novel_interface.show_dialog("所以，變態本身就是與眾不同的意思，完全不需要隱藏。", "索婭")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索婭一臉自豪地將手放在自己胸前──")
	novel_interface.show_character("soya_uniform", "relieve")
	await novel_interface.show_dialog("變態就是變態，坦然承認就好，不需要用普通人的邏輯為自己辯解。", "索婭")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索婭拍了拍我的肩，用人生導師的語氣說道。")
	novel_interface.show_character("ren_fishnet", "wail")
	await novel_interface.show_dialog("（有這種不要臉的自我解讀嗎？）\n（還有，我怎麼好像被強行歸類了！）", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "jest")
	await novel_interface.show_dialog("歐洲人認為蘿莉控變態，可能只是因為他們比較喜歡豐滿的女性吧，比如──", "索婭")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索婭順勢將手移到我的胸前捏了捏。")
	novel_interface.show_character("ren_fishnet", "awkward")
	await novel_interface.show_dialog("欸？", "小憐")
	await novel_interface.hide_character()
	
	# 贝阿特丽切出场，使用beatrice_show_hide效果
	await novel_interface.show_dialog("看來還不是很成熟呢。", "女性的聲音")
	await novel_interface.show_text_only("一個熟悉的聲音從我們身後傳來。")
	novel_interface.show_character("ren_fishnet", "perspire1")
	await novel_interface.show_dialog("貝、貝阿特麗切？！\n妳怎麼會在這……", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("好久不見了，小可愛──", "貝阿特麗切")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "laugh")
	await novel_interface.show_dialog("哇──！！", "索婭")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索婭看著貝阿特麗切的胸部就要撲過去，卻被我一把抓住。")
	novel_interface.show_character("soya_uniform", "cry")
	await novel_interface.show_dialog("放、放開我！", "索婭")
	await novel_interface.show_dialog("這個人和小憐的味道一樣乾淨，但是大很多──", "索婭")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("妳夠了喔！！！")
	await novel_interface.show_text_only("貝阿特麗切優雅地整理了頭髮，順便調整了一下緊繃的襯衫。")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("因為莉琉要我暗中跟蹤並保護妳們啊。", "貝阿特麗切")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("要全程不被發現還挺困難的呢，尤其妳們還遇到了那個瑟蕾莎……", "貝阿特麗切")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "panic")
	await novel_interface.show_dialog("跟、跟蹤？", "小憐")
	# 显示双角色位置移动
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform", "afraid", 0.25)
	await novel_interface.show_dialog("從什麼時候開始的啊？我都沒發現……明明是這麼甜美的氣味！", "索婭")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("索婭被我拉著衣領，只能像小狗一樣拚命將鼻子往貝阿特麗切探去。")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("今天下午開始，我就一直都在妳們附近。", "貝阿特麗切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("貝阿特麗切嫵媚一笑，我覺得臉頰開始發燙。")
	await novel_interface.show_text_only("她最近似乎都在幫SID處理一些「特殊事務」。")
	await novel_interface.show_text_only("這位自稱死於700多年前的姐姐，是我在天空酒店透過拉斐爾家的墜飾召喚出來的魔女。")
	await novel_interface.show_text_only("據說貝阿特麗切身上帶有會讓所有異性迷戀自己的「詛咒」。")
	await novel_interface.show_text_only("一定是因為那個詛咒的關係，害我每次見到她都會慌張到不知所措……")
	novel_interface.show_character("ren_fishnet", "shy")
	await novel_interface.show_dialog("等等，那我們倆剛才被拘留──", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular", "worry")
	await novel_interface.show_dialog("妳們一被逮捕我就聯絡了莉琉，但她可能在忙別的或者收不到訊息，一直沒有回覆……", "貝阿特麗切")
	novel_interface.change_expression("smile2")
	await novel_interface.show_dialog("我想，既然有索婭在，妳們應該很快就能脫身，所以就留在這邊繼續監視伊露卡。", "貝阿特麗切")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "shy_right")
	await novel_interface.show_dialog("那……伊露卡到底是怎麼跑到那上面的？", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我和貝阿特麗切對話時總是視線飄移，實在不知該把目光放在哪裡好。")
	await novel_interface.show_text_only("而索婭已經放棄掙扎，開始興致盎然地觀察著我的表情，煩死人了！")
	novel_interface.show_character("beatrice_regular", "worry")
	await novel_interface.show_dialog("索婭把妳按在牆上的時候，那孩子就跟著一個甜點外送員跑了。", "貝阿特麗切")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("妳們兩個啊……唉。", "貝阿特麗切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("貝阿特麗切語重心長地嘆了口氣，這口氣怎麼好像我們做了什麼奇怪的事情啊！")
	novel_interface.show_character("beatrice_regular", "smile1")
	await novel_interface.show_dialog("後來伊露卡去了妳們下午去的甜點店，老闆不但請客，還介紹她來今晚的宣傳活動打工。", "貝阿特麗切")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "stare")
	await novel_interface.show_dialog("（沒想到那個微禿的老闆這麼有眼光！）", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular", "smile1")
	await novel_interface.show_dialog("因為對她不熟悉，一開始我以為只是小孩子貪吃，但現在看來確實有些不對勁……", "貝阿特麗切")
	await novel_interface.show_dialog("索婭沒有看出什麼問題？", "貝阿特麗切")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "wordless")
	await novel_interface.show_dialog("沒有耶──", "索婭")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索婭看向伊露卡。")
	novel_interface.show_character("soya_uniform", "speechless")
	await novel_interface.show_dialog("沒有被脅迫，沒有被下藥。", "索婭")
	await novel_interface.show_dialog("沒有不適或痛苦，她的行為完全符合自身的心智和慾望。", "索婭")
	novel_interface.change_expression("wordless")
	await novel_interface.show_dialog("硬要說有什麼問題的話，就是她實在吃太多了……", "索婭")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular", "grieved")
	await novel_interface.show_dialog("從剛才的新聞看來，今晚協議非武裝區裡已經有6個區域的示威遊行出現暴力衝突了。", "貝阿特麗切")
	novel_interface.change_expression("sad")
	await novel_interface.show_dialog("雖然性質不同，但這裡很可能會變成第7個。", "貝阿特麗切")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "panic")
	await novel_interface.show_dialog("難怪連軍隊都來了……\n那要趕快帶伊露卡離開了！", "小憐")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "wordless")
	await novel_interface.show_dialog("但那群傢伙把她團團包圍，把人帶走沒那麼簡單吧？", "索婭")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("我倒是能分散一下他們的注意力，但在人這麼多的場合大概只能維持30秒……", "貝阿特麗切")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "worry")
	await novel_interface.show_dialog("要怎麼──", "小憐")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我的話還沒問完，就被貝阿特麗切打斷。")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("妳們有沒有發現這裡的人有什麼共同點？", "貝阿特麗切")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "jest")
	await novel_interface.show_dialog("他們都很興奮？", "索婭")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("貝阿特麗切抬起右手，微微一笑。")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("這群笨蛋，基本上都是男人啊──", "貝阿特麗切")
	await novel_interface.hide_character()
	
	print("=== 天启篇第10话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
