# apocalypse_ep11.gd - 天启篇第11话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第11话剧本
	apocalypse_ep11_script()

func play_script():
	pass

# 天启篇第11话 - 正式剧本
func apocalypse_ep11_script():
	# scene1 - 开始
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.show_character("beatrice_regular","smile2")
	await novel_interface.show_dialog("ไม่ ไอ้โง่พวกนี้—พวกมันล้วนเป็นผู้ชาย!", "เบียทริซ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("บนแขนขวาของเบียทริซมีสร้อยข้อมือซึ่งทำจากโลหะสีเขียวมอส แวววาวเบา ๆ ในโทนสีฟ้าอ่อน")
	await novel_interface.show_text_only("สิ่งประดิษฐ์ของอายะ ทำจากโลหะผสมพิเศษที่บล็อกเอฟเฟกต์ของมีม Substance H. สามารถใช้เพื่อระงับเอฟเฟกต์ของ \"คำสาป\" ของเบียทริซ")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("เดี๋ยวก่อนคุณวางแผนอะไร—", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("ฉันจำได้ว่า Mariru บอกฉันเมื่อสองสามสัปดาห์ก่อนเกี่ยวกับ \"คำสาป\" ผู้ชายคนไหนที่เห็นเบียทริซจะตกหลุมรักเธอทันที")
	# scene2 - 回忆莉琉的解释
	novel_interface.show_background("res://assets/images/bg/Soya/FusiformGyrus.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_dialog("พูดให้ถูกก็คือใบหน้าของเธอนั่นเองที่ทำให้เกิดผลกระทบ", "มาริรุ")
	await novel_interface.show_dialog("ผ่านการทดสอบหลายชุดที่ดำเนินการโดย Aya พวกเขาค้นพบว่าการมองตรงไปที่ใบหน้าของเบียทริซช่วยกระตุ้นไจรัสรูปกระสวยและต่อมทอนซิลในสมองของผู้ชายได้อย่างมาก", "มาริรุ")
	await novel_interface.show_dialog("อย่างไรก็ตาม จะได้ผลก็ต่อเมื่อเป้าหมายมองเธอโดยตรงในรัศมี 260 ฟุต ภาพถ่าย วิดีโอ หรือภาพสะท้อนไม่มีผลกระทบดังกล่าว", "มาริรุ")
	await novel_interface.show_dialog("หลังจากการกระตุ้นนี้มีผลเป็นระยะเวลาหนึ่ง สมองของผู้ได้รับผลกระทบจะเกิดการเปลี่ยนแปลงที่ไม่สามารถรักษาให้หายได้ สิ่งนี้จะเปลี่ยนวิธีการปฏิบัติของพวกเขาโดยพื้นฐาน", "มาริรุ")
	await novel_interface.show_dialog("พวกเขาหมดหวังที่จะให้เบียทริซเป็นของพวกเขา แต่เนื่องจากทำไม่ได้ พวกเขาจึงวิตกกังวล ฉุนเฉียว และขุ่นเคือง สิ่งนี้อาจนำไปสู่การทำร้ายตัวเอง การลอบวางเพลิง หรือแนวโน้มความรุนแรง", "มาริรุ")
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("เศร้าจังเลยใช่มั้ย? รักที่ไม่สมหวัง...", "มาริรุ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("มาริรุถอนหายใจ")
	await novel_interface.show_text_only("ฉันเปิดปากถามว่าอายะทำการทดลองที่น่าสยดสยองนั้นได้อย่างไร แต่ก็ปิดอีกครั้ง จะดีกว่าถ้าฉันยังคงโง่เขลา")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("(โชคดีที่ฉันไม่ใช่หนึ่งในผู้ถูกทดสอบของเธอ...)", "เหลียน")
	await novel_interface.show_dialog("…", "เหลียน")
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("รอก่อน! ตอนที่คุณให้ฉันอธิบายเรื่องให้เบียทริซคนเดียวใน “ชุดนั้น” เมื่อวานนี้...", "เหลียน")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("นั่นเป็นการทดลองของอายะด้วยเหรอ?", "เหลียน")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","shock")
	await novel_interface.show_dialog("เพิ่งรู้ตัวตอนนี้เหรอ?", "มาริรุ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("เป็นเช่นนั้นเหรอ?")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("อืม คุณคงไม่รู้ว่าสร้อยข้อมือที่เบียทริซใส่เมื่อวานนั้นเป็นของปลอมใช่ไหม?", "มาริรุ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("มาริรุพูดติดตลก รู้สึกผิดหวังเล็กน้อยที่ฉันขาดทักษะการสังเกต")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("เหตุผลที่ฉันให้คุณสวมชุดนั้นก็เพื่อป้องกันไม่ให้ความคิดส่วนตัวของคุณรบกวนผลสอบของเรา “ความอับอาย” ที่คุณรู้สึกจะยกเลิก “ความปรารถนา” ของคุณได้อย่างมีประสิทธิภาพ", "มาริรุ")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("และ...", "มาริรุ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("เธอเอื้อมมือออกไป วางมือทั้งสองข้างบนไหล่ของฉัน บนใบหน้าของเธอมีรอยยิ้มอันละเอียดอ่อน")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("... คุณดูดีมากในชุดกระต่ายเพลย์บอย!", "มาริรุ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("อ๊าาา!\nเราไม่สามารถหยุดพูดเรื่องนั้นได้หรือ?", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ฉันใช้เวลาหนึ่งชั่วโมงอันเลวร้ายนั้นในชุดกระต่ายเพลย์บอย คนเดียวกับเบียทริซ ในห้องปิด")
	await novel_interface.show_text_only("ฉันรู้สึกประหม่ามากจนแทบจะพูดประโยคออกมาไม่หมด ฉันไม่สามารถเดินได้อย่างถูกต้อง")
	await novel_interface.show_text_only("และเบียทริซใช้เวลาหนึ่งชั่วโมงปลอบใจฉัน แม้ว่าเธอจวนจะหัวเราะคิกคัก ฉันมั่นใจ")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("อายะกล่าวว่าภาพสแกนสมอง 3 มิติของคุณนั้นเหมือนกับการแสดงดอกไม้ไฟ เธอสนุกกับมันมาก คงปล่อยให้มันดำเนินต่อไปอีกนานถ้าความดันสมองของคุณไม่สูงสักหน่อย", "มาริรุ")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("อย่างไรก็ตาม ตอนนี้เรารู้แล้วว่า แม้ว่าสมองของคุณจะตอบสนองต่อคำสาปของเบียทริซเหมือนกับผู้ชายทั่วไป แต่ก็ไม่มีบาดแผลใดๆ หลงเหลืออยู่", "มาริรุ")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("ในทางกลับกัน ผู้ชายคนอื่นๆ จะประสบกับความเสียหายทางสมองอย่างถาวรหลังจากมองหน้าเบียทริซมาระยะหนึ่งแล้ว ระยะเวลาตั้งแต่สี่สิบวินาทีถึงแปดนาที", "มาริรุ")
	await novel_interface.show_dialog("ดังนั้นคุณจึงปลอดภัย คุณไม่โล่งใจเหรอ?", "มาริรุ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("ฉันไม่โล่งใจอย่างแน่นอน!", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("…")
	await novel_interface.show_text_only("อา นั่นเป็นอีกหนึ่งความทรงจำของฉันที่ฉันอยากจะลบทิ้งไป")
	
	# scene3 - 回到现场
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("(ดังนั้น... ถ้าเธอถอดสร้อยข้อมือออกที่นี่...)", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("เบียทริซยิ้มหวานให้ฉันแล้วดึงฉันเข้าไปกอด")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("ทุกอย่างมืดลงต่อหน้าฉันขณะที่ใบหน้าของฉันถูกตบไปที่หน้าอกของเธอ")
	await novel_interface.show_dialog("ฮะ?", "เหลียน")
	await novel_interface.show_dialog("ฉันจะพูดว่า \"ไป\" หลังจากนั้นคุณมีเวลาสามสิบวินาที", "เบียทริซ")
	await novel_interface.show_dialog("หยิบ Elluka แล้วเราจะแยกกันและพบกันที่ Newell Central Park มีผู้ประท้วงน้อยลง", "เบียทริซ")
	await novel_interface.show_dialog("เข้าใจไหม?", "เบียทริซ")
	await novel_interface.show_text_only("ฉันพยักหน้า พยายามอย่างเต็มที่ที่จะไม่คิดถึงหน้าอกที่อ่อนนุ่มบนใบหน้าของฉัน")
	await novel_interface.show_dialog("เฮ้ ฉันก็อยากเลี้ยวเหมือนกัน!", "โซยา")
	await novel_interface.show_text_only("“คลิก”")
	await novel_interface.show_text_only("ตัวล็อคของสร้อยข้อมือเปิดออก คำสาปมีผลแล้ว")
	# scene4 - 索娅的视角
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN1.png")
	await novel_interface.show_text_only("ในสายตาของ Sonya ตอนนี้ Electronics Street กลายเป็นโลกแห่งสีชมพู")
	await novel_interface.show_text_only("สีชมพูแบบเดียวกับที่เธอเห็นปกคลุมหนังสือบางเล่มที่มีเนื้อหาโจ่งแจ้งเมื่อตอนช้อปปิ้งในร้านหนังสือบ่ายวันนี้")
	novel_interface.show_character("soya_uniform","shy")
	await novel_interface.show_dialog("คุณก็เป็นแม่มดเหมือนกันเหรอ?", "โซยา")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("อา. คุณบอกได้ไหม?", "เบียทริซ")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","shy")
	await novel_interface.show_dialog("แต่คุณไม่เหมือนเอลลูก้าหรือราฟิเลีย...", "โซยา")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("คุณก็มีออร่าที่บริสุทธิ์ราวกับเด็กทารกเหมือนกับเร็น!", "โซยา")
	await novel_interface.show_dialog("... นี่มันน่าหลงใหล!", "โซยา")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya อุทาน เขย่าไหล่ของฉันด้วยความตื่นเต้น")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("วะฮ่าฮ่า!\n(หยุดนะ! หายใจไม่ออก!)", "เหลียน")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular","smile2")
	await novel_interface.show_dialog("ดูเหมือนคุณจะมีน้ำหนักน้อยกว่าที่ฉันจำได้\nคุณไม่ใช่คนน่ารักเหรอ?", "เบียทริซ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("สาวนมโตกอดเร็นแน่นยิ่งขึ้น")
	await novel_interface.show_text_only("ขณะเดียวกัน Ren กำลังร้องไห้อย่างสิ้นหวังและพยายามหลบหนีจากอ้อมกอดที่หายใจไม่ออกของเธอ")
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("... ว่าแต่คุณเป็นใคร?", "โซยา")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("Oops, forgot to introduce myself.\nฉันชื่อเบียทริซ ปอร์ตินารี", "เบียทริซ")
	await novel_interface.hide_character()
	
	# scene5 - 90分钟前的场景
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("<90 นาทีที่แล้ว>")
	novel_interface.change_background("res://assets/images/bg/Soya/Club.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_text_only("<เขตปลอดทหารที่ตกลงไว้ โรงแรม New Opulentia Stork Garden>")
	await novel_interface.show_text_only("<ด้านนอกห้อง Birdsong ห้องจัดเลี้ยงชั้นบนสุด>")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("โอ้โฮ พวกเขามีสวนที่นี่บนชั้น 99 ผู้คนใน Hovering Palace เพลิดเพลินกับความหรูหราเช่นนี้ตลอดเวลาหรือไม่?", "มาริรุ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("มาริรุสำรวจหลังคากระจกและยิ้มอย่างไม่เต็มใจ")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("บางทียิ่งสวนสูงเท่าไหร่ก็ยิ่งดูหรูหรามากขึ้นเท่านั้น? หรือบางที 99 อาจเป็นเลขนำโชคของเจ้าของ?", "สกัลด์")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("เด็กสาวผมบลอนด์เกาหัวอย่างสับสน")
	novel_interface.show_character("skuld","think")
	await novel_interface.show_dialog("คุณตัดสินใจได้อย่างไรว่าการประมูลครั้งนี้คือสิ่งที่เรากำลังมองหาอยู่แล้ว?", "สกัลด์")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("มาริรุจ้องมองป้ายโฆษณาพ่นสีสเปรย์ที่ทางเข้าห้องจัดเลี้ยง")
	await novel_interface.show_text_only("อยู่ในหัวข้อ “การประมูลฤดูใบไม้ร่วงของพิพิธภัณฑ์จอห์นสัน”\nตามด้วยคำบรรยาย: ที่ซึ่งศิลปะพบกับการเงิน")
	await novel_interface.show_text_only("ข้อความสีขาวดูสั่นสะเทือนเป็นพิเศษบนพื้นหลังสีน้ำเงิน ไม่มีอะไรที่เป็นศิลปะเกี่ยวกับเรื่องนี้")
	novel_interface.show_character("skuld","perspire")
	await novel_interface.show_dialog("นี่คือการประมูลงานศิลปะจริงๆเหรอ? ดูเหมือนจะไม่ค่อยสวยงามสำหรับฉัน", "สกัลด์")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("มาริรุพยักหน้าและยิ้ม")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("แต่ที่นั่งเต็มห้าร้อยที่นั่งแล้ว จากหกสิบสามรายการ ขายไปแล้วหกสิบรายการ", "มาริรุ")
	await novel_interface.show_dialog("จัดทำไปแล้วทั้งหมด 1.5 พันล้าน", "มาริรุ")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("ขนาดนั้นเลยเหรอ? การประมูลครั้งนี้คงจะใหญ่มากแน่ๆ\nแต่ฉันไม่ได้ยินอะไรเลยเกี่ยวกับเรื่องนี้ ...", "สกัลด์")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("บัญชีที่เข้ารหัสทางอิเล็กทรอนิกส์ที่คุณแจ้งเรา...มีเงินทุนมูลค่าหลายพันล้าน", "มาริรุ")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("เยอะมาก แต่ก็เพียงพอที่จะสร้างตึกระฟ้าประเภทนี้สองแห่งเท่านั้น", "มาริรุ")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("หากต้องการใช้เงินจำนวนนี้เพื่อสร้างผลกระทบต่อกองทุนสร้างใหม่นับล้านล้านที่ United Congress เป็นเจ้าของ ควรมีทางเดียวเท่านั้น...", "มาริรุ")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","think")
	await novel_interface.show_dialog("ติดสินบน? นั่นเป็นเหตุผลที่พวกเขาเลือกสกุลเงินที่เข้ารหัส?", "สกัลด์")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("บัญชีอาจถูกเข้ารหัส แต่ทุกคนในเครือข่ายสามารถเห็นธุรกรรมใดๆ ที่เกิดขึ้นได้ และการทำธุรกรรมขนาดนี้ ไม่มีทางที่ผู้คนจะสังเกตเห็นมัน", "มาริรุ")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("นั่นเป็นเหตุผลที่พวกเขาต้องการเหตุผลที่เป็นไปได้สำหรับการทำธุรกรรม...", "สกัลด์")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("สกัลด์เอียงศีรษะไปข้างหนึ่งครุ่นคิด จากนั้นเธอก็อุทาน:")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("โอ้ นั่นเป็นเหตุผลว่าทำไมพวกเขาถึงจัดประมูล!", "สกัลด์")
	await novel_interface.show_dialog("ของเก่าที่ไม่มีการกำหนดราคาไว้ถือเป็นข้อแก้ตัวที่ดีสำหรับการทำธุรกรรมที่มีมูลค่าสูง สิ่งของต่างๆ เช่น เครื่องจีน หยก ภาพวาดเก่าๆ... ไม่มีใครสนใจถ้าเห็นคนประมูลราคาเป็นล้านๆ", "สกัลด์")
	await novel_interface.show_dialog("และธุรกรรมดังกล่าวก็จัดขึ้นในดินแดนระหว่างประเทศด้วย ทำให้หน่วยงานภาษีจากประเทศต่างๆ ไม่สามารถเก็บภาษีได้", "สกัลด์")
	await novel_interface.show_dialog("สิ่งที่พวกเขาต้องทำก็แค่ติดต่อกับทั้งสองฝ่ายและขายขยะบางส่วนภายใต้ชื่อพิพิธภัณฑ์ของเอกชนบางแห่ง", "สกัลด์")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("แต่พวกเขาไม่สามารถปล่อยให้ผู้ชื่นชอบงานศิลปะเข้ามาในสถานที่ได้ เพราะพวกเขาจะสามารถบอกเล่าเรื่องราวต่างๆ ที่เกิดขึ้นได้อย่างรวดเร็ว", "สกัลด์")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("เพราะเหตุนี้ที่นั่งจึงเต็มหมด!\nพวกเขาเต็มที่นั่งด้วยคนของพวกเขาเอง!", "สกัลด์")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("มาริรุตบหัวของสกัลด์อย่างเห็นชอบ")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("ฉลาดมาก. คุณคงเบื่อที่โรงเรียนมากใช่ไหม?", "มาริรุ")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("คุณคิดอย่างไร?", "สกัลด์")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld เงยหน้าขึ้นมอง Mariru ด้วยท่าทางภูมิใจ")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("ให้ฉันบอกคุณอย่างอื่นแล้ว", "มาริรุ")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("“กองทุนฟื้นฟูหลังสงคราม” โดยพื้นฐานแล้วเป็นการกู้ยืมจากรัฐสภาคองเกรสแห่งสหประชาชาติ รัฐบาลที่ยืมมาจากพวกเขาจะต้องจ่ายเงินคืน ไม่เช่นนั้นต้องเผชิญกับความโกรธเกรี้ยวจากหกชาติใหญ่", "มาริรุ")
	await novel_interface.show_dialog("แต่ในอดีต ไม่มีประเทศใดสามารถชำระคืนเงินกู้ขนาดนี้ได้ภายในกำหนดเวลา นั่นคือที่มาของขอบเขตการเจรจา", "มาริรุ")
	await novel_interface.show_dialog("คณะกรรมการเป็นคนรวยสกปรก สิ่งที่พวกเขาต้องการสำหรับตัวเองน่าจะเป็นภาคส่วนที่มีกำไรมากที่สุด เช่น โครงสร้างพื้นฐาน เช่น ไฟฟ้าและการสื่อสาร", "มาริรุ")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("พวกเขาสามารถยื่นข้อเสนอต่อหัวหน้ารัฐบาลที่ยืมเงินได้โดยง่ายว่าพวกเขาจะไม่ต้องจ่ายเงินที่ยืมคืนตราบเท่าที่พวกเขามอบหุ้น 30% ของหุ้นในเครือข่ายโทรคมนาคมแก่คณะกรรมการเป็นการถาวร", "มาริรุ")
	await novel_interface.show_dialog("รัฐบาลที่ไม่สามารถจ่ายคืนเงินกู้ได้มักจะเห็นด้วย ผู้นำประเทศบางคนอาจถึงกับขอส่วนลดเป็นการส่วนตัวด้วยซ้ำ", "มาริรุ")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("แล้วคณะกรรมการจะควบคุม “ภาคส่วน” ที่พวกเขาต้องการได้อย่างไร?", "สกัลด์")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("พวกเขาต้องโน้มน้าวให้รัฐสภาคองเกรสยอมให้บริษัทข้ามชาติเป็นเจ้าของเงินทุนและมีอิสระในระดับหนึ่ง...", "สกัลด์")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("นั่นเป็นเรื่องมากที่จะขอ พวกเขาจะตกลงกันจริงๆเหรอ?", "สกัลด์")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("แทนที่จะตอบ มาริรุกลับถามคำถามอื่นแทน")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("งานศิลปะที่พ่นสีสเปรย์นี้ดูเหมือนเด็กอนุบาลทำเอง นั่นบอกอะไรคุณ?", "มาริรุ")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("ใครก็ตามที่ทำสิ่งนั้นไม่ได้พยายามอย่างหนักพอที่จะปกปิดความจริงที่ว่ามันเป็นเรื่องปลอมทั้งหมด", "สกัลด์")
	await novel_interface.hide_character()
	
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("แม้ว่าจะมีเงินจำนวนมากเข้ามาเกี่ยวข้องก็ตาม พวกเขาต้องเช่าชั้นบนสุดของโรงแรมและจ้างคนหลายร้อยคน พวกเขาใช้จ่ายไปมากมายแล้ว—แล้วทำไมพวกเขาถึงไม่ใช้จ่ายไปกับกราฟิกมากนักด้วยล่ะ?", "มาริรุ")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","think")
	await novel_interface.show_dialog("ก็…", "สกัลด์")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("สกัลด์ทำหน้ามุ่ย นิ่งงันกับข้อมูลใหม่ทั้งหมด")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("เป็นเพราะนี่ไม่ใช่เรื่องใหม่สำหรับพวกเขา มันเกิดขึ้นนับครั้งไม่ถ้วนแล้ว ทั้งที่นี่และที่อื่น", "มาริรุ")
	await novel_interface.show_dialog("ไม่มีใครสงสัยหรือโทรหาพวกเขาเลย ดังนั้นพวกเขาจึงไม่ต้องปกปิดมันอีกต่อไป", "มาริรุ")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("การติดสินบนถือเป็นศิลปะในตัวเอง โดยเฉพาะอย่างยิ่งการติดสินบนประเภทนี้ พวกเขาจำเป็นต้องรวบรวมข้อมูลจำนวนมหาศาลและตรวจสอบให้แน่ใจว่าทุกคนที่เกี่ยวข้องได้รับความพึงพอใจในทุกระดับ", "มาริรุ")
	await novel_interface.show_dialog("จะต้องทำการสอบสวนจำนวนมาก ผู้คนจำนวนนับไม่ถ้วนกลายเป็นส่วนหนึ่งของปฏิบัติการ การแลกเปลี่ยนผลประโยชน์ดังที่เราเห็นในปัจจุบันนี้เกิดขึ้นหลายครั้ง", "มาริรุ")
	await novel_interface.show_dialog("พวกเขาจะต้องเจรจากับผู้คนจำนวนมาก เจ้าหน้าที่ ช่องสื่อ พันธมิตรแรงงาน องค์กรพัฒนาเอกชน แม้กระทั่งผู้ซึ่งมีตำแหน่งสูงในการก่ออาชญากรรม", "มาริรุ")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("นั่นคือวิธีที่พวกเขามีอิทธิพลต่อการตัดสินใจที่สำคัญของ United Congress", "มาริรุ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("มาริรุพยักหน้าที่ประตูที่ปิดอยู่ของห้องจัดเลี้ยง")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("นั่นคือสิ่งที่คุ้มค่าที่สุดในการประมูลครั้งนี้", "มาริรุ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld ห้อยหัวและถอนหายใจ")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("แย่จังเลย...รู้สึกไม่ซื่อสัตย์เลย...", "สกัลด์")
	novel_interface.change_expression("talk")
	await novel_interface.show_dialog("เดี๋ยวก่อนนั่นคือสิ่งที่คุณวางแผนมาตั้งแต่ต้นใช่ไหม?", "สกัลด์")
	await novel_interface.show_dialog("คุณคงไม่อยากจับกุมผู้บงการที่บงการโครงการสร้างใหม่...", "สกัลด์")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ทันใดนั้น ประตูห้องจัดเลี้ยงก็เปิดออกโดยมีรอยแตกเล็กๆ ฟาเบลลายื่นมือออกมาเพื่อส่งสัญญาณตกลง")
	await novel_interface.show_text_only("เป็นสัญญาณว่าสินค้าทั้งหมดได้ถูกขายไปแล้ว และการทำธุรกรรมระหว่างบัญชีที่เข้ารหัสทางอิเล็กทรอนิกส์กำลังจะเกิดขึ้น")
	await novel_interface.show_text_only("มาริรุหยิบวิทยุสื่อสารของเธอขึ้นมา")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("ทีมกู้ภัยปิดทางเข้าชั้น 99 ทั้งหมด รวมทั้งปล่องลิฟต์ด้วย แจ้งเตือนโรงแรมว่าตรวจพบสารกัมมันตรังสีปริมาณมากบนชั้น 98", "มาริรุ")
	await novel_interface.show_dialog("ตัดสัญญาณเครือข่ายและวิธีการสื่อสารในอาคารทั้งหมด เมื่อฉันบอกว่าไป ให้บังคับความเงียบของวิทยุ", "มาริรุ")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("ไป!", "มาริรุ")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…")
	
	# scene6 - 回到现场
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.change_music("res://assets/audio/music/Brooklyn.mp3")
	await novel_interface.show_text_only("ในที่สุดเบียทริซก็ทำให้ฉันหายใจได้ เธอกระตุ้นให้ฉันหันหลังให้หันหลังเข้าหาเธอ และกระซิบข้างหูฉัน")
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("รอจนกว่าฉันจะพูดว่า \"ไป\" และอย่ามอง!", "เบียทริซ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("จากนั้นเธอก็ผลักฉันไปทางรถบรรทุกที่ Elluka ขับอยู่ ฉันพยายามอย่างเต็มที่เพื่อฝ่าฝูงชน โดยมี Sonya เดินตามมาจากด้านหลัง")
	await novel_interface.show_text_only("ในขณะเดียวกัน เบียทริซก็เดินออกไปอย่างสงบไปยังรถบรรทุกอีกคันที่อยู่ใกล้ๆ ผลักพวกผู้ชายออกไปให้พ้นทางเหมือนราชินีผู้สูงและทรงพลัง")
	await novel_interface.show_text_only("ใครก็ตามที่หันกลับมาเพื่อกรีดร้องใส่เธอ จะสูญเสียความรู้สึกทันทีเมื่อเห็นหน้าเธอ")
	await novel_interface.show_text_only("เบียทริซปีนขึ้นไปบนรถบรรทุกที่ว่างอยู่อย่างว่องไว โดยมีคนงาน 2 คนกำลังตรวจสอบเสียงบนหลังคา")
	await novel_interface.show_text_only("เธอคว้าไมค์และเฝ้าดูจนกระทั่ง Sonya และฉันสามารถเบียดรถบรรทุกของ Elluka ได้ใกล้ที่สุดเท่าที่จะเป็นไปได้ จากนั้นจึงโบกมือให้คนงานปรับระดับเสียงไมค์ของเธอให้ดังที่สุด")
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("ไป!", "เบียทริซ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("เมื่อได้ยินคำสั่งของเธอ ฉันก็พยักหน้าให้ Sonya")#换行问题
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("ไป!", "เหลียน")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("เมื่อลำโพงเปิดระดับเสียงสูงสุด ไม่ว่าอะไรก็ตามที่เบียทริซจะพูดต่อไปจะต้องเข้าหูทุกคนบนถนนอิเล็กทรอนิกส์อย่างแน่นอน")
	await novel_interface.show_text_only("เธอยืนอย่างภูมิใจบนหลังคารถบรรทุก หายใจเข้าลึกๆ และส่งเสียงกรีดร้องใส่ไมโครโฟน ปล่อยให้เสียงของเธอพาไป")
	novel_interface.show_character("beatrice_regular","angry")
	await novel_interface.show_dialog("พวกคุณมันขยะกันทุกคน!", "เบียทริซ")
	await novel_interface.show_dialog("ไปลงนรกพวกนิสัยเสีย!", "เบียทริซ")
	await novel_interface.hide_character()
	
	print("=== 天启篇第11话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
