# apocalypse_ep05.gd - 天启篇第05话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第05话剧本
	apocalypse_ep05_script()

func play_script():
	pass

# 天启篇第05话 - 正式剧本
func apocalypse_ep05_script():
	# scene1 - 盲点序章
	novel_interface.show_background("res://assets/images/bg/Soya/Blindspot.png")
	await novel_interface.show_text_only("盲点──\n網膜上の動脈・静脈と視神経が通る場所。\nこの領域には視細胞がないため、\n視覚は発生しない。")
	await novel_interface.show_text_only("しかし、盲点の位置を自分の視界の中で\n確認するのは不可能だ。\n何故なら欠けた視界の部分を、脳が自動的に\n補完してしまうからである。")
	await novel_interface.show_text_only("私達の脳は、どんな状況でもあらゆる手を使い\n自身の状態を合理化する。")
	await novel_interface.show_text_only("その結果として多くの人々が、以下ように\n考えてしまう。\n自分が生まれながら備わっているものが、\n当然でありで正しいのだと。")
	await novel_interface.show_text_only("事実はそうでないにも関わらず──")
	await novel_interface.show_text_only("7歳になって、やっと自分の左目が失明している\n事に気付く人間がいた。")
	await novel_interface.show_text_only("生まれながらにして耳が聞こえない人間は、\n誰かに知らされない限り、\n元々世界に音声など存在しないと思ってしまう。")
	await novel_interface.show_text_only("もし何かの異常が「初期設定」であるならば、\n人は何も疑問を抱かない。")
	await novel_interface.show_text_only("ある日、その矛盾に直面せざるを得なくなった時\nそこでようやく気付くのだ。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("では考えてみよう……\n\n全人類が当たり前であると思っている物が、\nもし欠陥だった場合はどうするのか？")
	novel_interface.show_background("res://assets/images/bg/Soya/Doomsday1.png")
	await novel_interface.show_text_only("いつか──")
	await novel_interface.show_text_only("人類は避けられない矛盾に直面せざるを\n得ない時……\nようやく…………")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……………………")
	
	# scene2 - 美术馆继续
	novel_interface.show_background("res://assets/images/bg/Soya/Galleries.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("俺は未だ衝撃的であろうニュースを消化しようと\n努力している。")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("（深刻な事態だとは分かるけど、何だか思考が\n　上手くまとまらない）", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("新豊洲が最初の核攻撃を防いだとしても、\nその後の汚染、環境、食料問題は致命傷だ。")
	await novel_interface.show_text_only("「XK級の世界終末に、生存者は存在しない」")
	await novel_interface.show_text_only("当時よりこの言葉を方針に連合議会は戦争を\n終わらせ、以降は平和の維持に努めている。\nニュースで良く見るお決まりの台詞だけど……")
	novel_interface.show_character("raphael","normal2")
	await novel_interface.show_dialog("無差別反撃システム自体は別に真新しいモノでも\nないわ。\n冷戦期間中に似たような物が設計されていたし。", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("えっ？ そんなに昔からあるの！？", "レン")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("ただ、滅多にそれを言及する人はいない──", "ラファエル")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("なぜだか分かるかしら？", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("歴史が全く分からない俺は「何も知りません」の\n愛想笑いを返すと、\nラファエルの軽蔑的な目線が突き刺さった。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("各国に暗黙の了解があるからよ。\n\nこのような脅威は互いが知っていれば良い、\n「民衆」が知る必要はないと。", "ラファエル")
	await novel_interface.show_dialog("当時は全世界のメディアにおいて話す事さえ\nタブーだった。\n報道規制の厳しい国、報道の自由を提唱する国、\n……色々とあったけど、それでもね。", "ラファエル")
	await novel_interface.hide_character()
	
	# 背景切换
	novel_interface.change_background("res://assets/images/bg/Shot/storyBGPol.png")
	await novel_interface.show_text_only("連合議会が設立されて停戦を宣言した時\n「文明と未来のため」とか、\n確かに当たり障りのない理由しか\n言っていなかった。")
	await novel_interface.show_text_only("各国はXK級『異質物』に対して完全黙秘──\n\nそれ自体が戦争を終結した根本的な要因で\nあるらしいけど。")
	await novel_interface.show_text_only("そこから民衆が抱く将来の不安を解消するために\n「新回転ドア計画」という決議案も発表された。")
	await novel_interface.show_text_only("6つの常任理事国が全会一致で可決。\nその後、各自の首都に呼称を起用する。\n今や皆が知るAcademyCity……\n『学園都市』という名前を。")
	
	novel_interface.change_background("res://assets/images/bg/Soya/Guidepost.png")
	await novel_interface.show_text_only("この壮大な運動は政府の再編成、新通貨の発行、\n空港やランドマークの改名、\n果ては道路標識の交換にまで及んだ。")
	await novel_interface.show_text_only("それはただ名前を変えただけに見えたが……\n\n数ヶ月で奇跡的に各国の信用体系は回復。")
	await novel_interface.show_text_only("上場企業達も相次いで名称変更を申請した。\n\n『学園都市』と関連する名前にすれば、\nすぐに株価を上げる事ができたからである。")
	novel_interface.change_background("res://assets/images/bg/Soya/galleries.png")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("美しき未来が例え幻想であろうと、\n魅力さえあれば人々は惹かれてしまうのよ。", "ラファエル")
	await novel_interface.show_dialog("民衆に必要なのは、幻想の根拠を支える\n「シンボル」だけ──", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("まあ……男の子が魔法使いになるための\n「薄い本」みたいなものですわね？", "ソヤ")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","smile")
	await novel_interface.show_dialog("……ほん？", "イルカ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("…………", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ラファエルは丸めた紙を強く握って\n「また殴られたいのか？」という目つきをする。\nソヤは瞬間的に俺の後ろに隠れた。")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("要するに、今回行われた第三学園都市の声明は\n暗黙の了解を破ったって事だよな？\nそれも突発的なものじゃなくて計画的に。", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("暗黙の了解が通用しているのなら、こんな事は\n上層部の閉鎖会議内だけで通知すればいい。")
	await novel_interface.show_text_only("会議に参加できない小国やテロリストでも情報を\n知る術は沢山持っているし、\n脅威を誇示するだけなら民衆の不安を煽る\n必要なんてないはずだ。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("今、6ヵ国でメディア禁止令を出せる人物の\n全員が、あの部屋で閉鎖会議に興じている。", "ラファエル")
	await novel_interface.show_dialog("今頃全世界のマスコミは禁止令が下される前に、\nこの衝撃的ニュースで──\n視聴率とクリック数を稼ぎたいと思っている\nでしょうね。", "ラファエル")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("ただし、やりたい放題に焦燥と恐怖を公衆へ\n撒き散らしてしまうと……", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ラファエルは不安そうに窓の外の人混みを\n眺めている。")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("普段のこの場所って……こんなに人が多い\nモノなの？", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("街の属性からして政治的事件とは無縁のはずだが\n確かに今日の電気街は普段より人が多い。")
	novel_interface.show_background("res://assets/images/bg/Soya/Galleries.png")
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.show_character("soya_uniform","relieve")
	await novel_interface.show_dialog("まあ、心配いらないですわ！", "ソヤ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("俺達がいるロビーは2階に位置している。\n\nソヤが窓を覗き込んで辺りを見回すと、\n自信満々にそう言った。")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("あの人達の気配は怒りの色をしておりませんわ。\n\n焦りの匂いも、この程度の人混みなら\n正常の範囲内ですわよ？", "ソヤ")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("それがあんたのプロフィールに書いてあった……\n『共感覚』かしら？", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("まあ、そんなところですわ～～♪", "ソヤ")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("なら……あんたから見ると、私達はどんな気配が\nするわけ？", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ソヤの色と香りを兼ねた発言が、このお嬢様の\n好奇心をくすぐったようだ。")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("えーーっと……あなたはですね、\n少し矛盾した感じがして厄介なのですわ。", "ソヤ")
	await novel_interface.show_dialog("雨上がりの田畑のような息吹と温かい感じ。\n\n負の感情もすぐに洗い流して下さる安心感は、\nまるで母の抱擁のような暖かさ……\nなのに……なのに……", "ソヤ")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_fishnet","perspire1",0.25)
	await novel_interface.show_dialog("（……そんな優しそうな感じを出しているのに\n　ゲンコツが飛んでくるもんだから──）\n（ラファエルの攻撃を避けられなかったのか？）", "レン")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("ソヤは困惑の表情をしている。")
	novel_interface.show_character("soya_uniform","speechless")
	await novel_interface.show_dialog("普通そういう方は優しい癒し系のお姉様の\nはずですわ。\nそれがどうして、あなたみたいな性格の悪い\n暴力的なじゃじゃ馬──", "ソヤ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ソヤの話の途中、ラファエルの頭上に燃え盛る\n怒りのオーラが浮かび上がってくる。")
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("──だだ、だ、だからつまり、とても優しくて\n寛大で慈悲深くて、\n暴力などは絶対に振るうはずないですわ！", "ソヤ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ソヤは早口で切り上げ、即座に話題を変えた。")
	novel_interface.show_character("soya_uniform","relieve")
	await novel_interface.show_dialog("こほん。一方のレンさんを例にしますと、\n彼女の色は今まで見た中で一番純粋ですの。", "ソヤ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("……えっ？", "レン")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("ほほうっ？", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ラファエルの怒りの炎が瞬時に鎮火され、\n興味へと切り替わる。")#文字错误
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("例えばスイーツ店でパフェを食べた時には、\n1口食べるたびに「ん――おいしい！」という\n声が心から聞こえてきましたわ。", "ソヤ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("な、なんの事？\n（い、言わないでくれッ！！！）", "レン")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("毎回叫び終わってからやっと次の1口に移る……\nと～っても面白いですの♪", "ソヤ")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("へぇ～～流石あんたね、実に馬鹿馬鹿しいわ。", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("イルカちゃんの方はハムスターみたく楽しげに\n食べ続けていましたわ。", "ソヤ")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","smile")
	await novel_interface.show_dialog("えへへ～～", "イルカ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("イルカは褒められたかのように無邪気に笑う。")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("街中で綺麗な女の子を見かけますとレンさんから\n急に薄いピンクの気配がしますのよ。\n首は動かさず目だけを動かして覗いて\nおりましたわ。", "ソヤ")
	await novel_interface.show_dialog("他にも後ろの景色を見るフリをしつつ、\nそこから目線をそらして……\n滑稽にも見てない感じを装えば疑いが晴れると\n思っておりますのよ？", "ソヤ")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","jeer")
	await novel_interface.show_dialog("ふん、この変態。", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ラファエルが満足げに軽蔑の目を向ける。")
	novel_interface.show_character("ren_fishnet","shy_left")
	await novel_interface.show_dialog("い、いっそ殺して……", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("上手く隠せてたと思っていたのに……\n何で細かく俺を観察しているんだよ……")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("レンさんが素敵な洋服を見かけると、\n2種の矛盾した色が戦い始めるのです……\n勝つのはいつも、薄赤い方のようですわねぇ♡", "ソヤ")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("ほほうっ？", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ラファエルは振り向いて、俺を上から下まで\nじっくりと見る。")
	novel_interface.show_character("ren_fishnet","shy_right")
	await novel_interface.show_dialog("（知らないっ！ 俺は何も知らない！！）", "レン")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("それと、レンさんが急に気配を殺して人混みから\n離れようとしているのであれば、\n下着や網タイツをこっそり整えようとしている\nパターンが多いですわね！", "ソヤ")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","hungry")
	await novel_interface.show_dialog("お～～", "イルカ")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","mock",0.25)
	await novel_interface.show_dialog("ふふっ……", "ラファエル")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("イルカとラファエルは興味津々に聞いていて、\nソヤの話はますます盛り上がる。")#文字错误
	await novel_interface.show_text_only("──ダメだ。もうここにはいられない。")
	await novel_interface.show_text_only("俺は気配を消し、こっそり後ろに後退した。")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("それとそれと～～\nレンさんがトイレに行きたがる時はぁ～～……", "ソヤ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ソヤがまだ話している途中、彼女の足輪の\nランプが点滅し始める。")
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("あららっ？", "ソヤ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("「カチッ」という音と共に、一瞬だけ美術館の\nロビーの窓際が薄青い弧状の光で煌めく。")
	await novel_interface.show_text_only("銀髪の少女が綺麗に地面に倒れると、\n身体から白い煙が立ち昇った。")
	await novel_interface.show_text_only("イルカがしゃがんで、まだ少し息が残っている\nソヤをツンツンと突いた。\n無垢な瞳で「イルカがやったのじゃない」と\n言いたそうにラファエルを見つめている。")
	await novel_interface.show_text_only("ラファエルがこちらに振り向いた時、\n俺はすでに階段のところまで駆け出していた。")
	novel_interface.show_character("ren_fishnet","uneasy")
	await novel_interface.show_dialog("（ごめん、君を黙らせる方法はこれしか\n　思いつかなかった！！）", "レン")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("ぽふッ──")
	await novel_interface.show_text_only("慌てていた俺は、誰かにぶつかったようだ。")
	await novel_interface.show_text_only("しかしその人は俺に突き倒される事なく、\nむしろそのまま俺を抱いて支えてくれた。")
	novel_interface.show_character("ren_fishnet","timid")
	await novel_interface.show_dialog("（こ、この弾力……）", "レン")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Soya/Galleries.png")
	novel_interface.show_character("cereza","wordless")
	await novel_interface.show_dialog("気を付けなさいな、おチビさん……", "黒髪の女性")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("黒髪のお姉さんは、眠そうにあくびをした。")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("あ、ご、ごめんなさいっ！", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("彼女は手に日本刀を持っていた。\n\n精巧な鞘、鍔と柄、至る所から芸術品として\n傑作の息吹を感じる。")#文字错误
	novel_interface.show_character("cereza","normal")
	await novel_interface.show_dialog("君、レンって言うのね？", "黒髪の女性")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("あら、中々持って可愛いじゃないの──", "黒髪の女性")
	await novel_interface.hide_character()

	print("=== 天启篇第05话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
