# apocalypse_ep14.gd - 天启篇第14话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第14话剧本
	apocalypse_ep14_script()

func play_script():
	pass

# 天启篇第14话 - 正式剧本
func apocalypse_ep14_script():
	# 开场设置
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("I watch as the car bringing Elluka back to the SID headquarters roll away, disappearing at the end of the road. My brain is still filled with images of the unconscious guy and all that blood...")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("John should be okay, right?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya replies, gazing down at the bloody glass shard in her hand:")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("It got some of his muscles but didn’t hit any major arteries. He should be fine if they treat him in time.", "Soya")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("Still, it’s crazy how he walked for more than twenty minutes with that kind of wound. Any normal person would probably have fainted already.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("... Maybe he has CIPA or something?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("It’s a disorder I remember seeing on TV. Lots of characters have it in animes and dramas.")
	await novel_interface.show_text_only("They can’t feel pain, so even appendicitis can kill them—they might not even notice something’s wrong until there’s a hole in their stomach or something.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("He should probably still have tactile senses though in that case.", "Soya")
	await novel_interface.show_dialog("He should’ve been able to at least feel that whole patch of congealed blood on his pants. Yet he didn’t seem to have noticed at all. He’s really...", "Soya")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("Fascinating!", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("What?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("We should go check on him in the hospital. See what kind of stimuli will get a reaction out of him.", "Soya")
	await novel_interface.show_dialog("Or maybe he was too focused on Ren to notice the pain?", "Soya")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("In that case, we have to use Ren as part of the experiment too. Gotta borrow her from that female gorilla...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("As Sonya rambles on, my chest vibrates out of nowhere.")
	await novel_interface.show_dialog("Who were you calling a female gorilla, huh?", "Mariru")
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("M-Mariru?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya whips her hair around in horror but doesn’t see Mariru anywhere. There’s only me, one hand on my buzzing chest.")
	await novel_interface.show_dialog("Miss me yet, Ren?", "Mariru")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("Can’t you just call me on my phone?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","laugh",0.25)
	await novel_interface.show_dialog("Whoa...", "Soya")
	await novel_interface.show_text_only("Finally discovering the source of the voice, Sonya bounces over to me, eyes shining in curiosity.")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("She leaps up towards my breasts, much like a golden retriever with a wagging tail—")
	await novel_interface.show_text_only("From her ankle, a sudden bright arc appears. Sonya slams into the ground.")
	await novel_interface.show_text_only("Her right arm and leg spasm twice, and she manages to clamber up, half-paralyzed.")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("(She seems to be recovering to the electric shocks faster now...?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Eyes brimming with tears, the girl sits up, rubbing her aching left arm, and lifts her head towards the sky in a silent complaint.")
	novel_interface.show_character("soya_uniform","cry")
	await novel_interface.show_dialog("Geez, you can even remote-control this thing?", "Soya")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/UAV.png")
	await novel_interface.show_text_only("I follow Sonya’s gaze and spot a tiny red dot hovering in the air.")
	await novel_interface.show_dialog("A drone?", "Lian")
	await novel_interface.show_dialog("Aren’t drones banned in this area?", "Lian")
	await novel_interface.show_text_only("Bans never did hinder SID, of course, but didn’t Mariru say herself a couple days ago that we need to err on the side of caution during the International Forum of Peace?")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("ren_fishnet","uneasy")
	await novel_interface.show_dialog("(Well, I guess attacking cops, jail-breaking and starting riots don’t really count as erring on the side of caution either...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("The situation is special today. There’s already more than fifty thousand people gathered on First Avenue, marching for who knows what.", "Mariru")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("That many?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("There’s already been riots in seven areas. The headquarters of the security soldiers is a mess right now.", "Mariru")
	await novel_interface.show_dialog("I told their commander that if they don’t deal with these riots in an appropriate way, New Opulentia could be in trouble...", "Mariru")
	await novel_interface.show_dialog("And I kinda pressured him a bit by bringing up his family. Poor guy agreed to allow the SID to bypass certain restrictions right away.", "Mariru")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("(“Kinda” pressured?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("They really went all out for the Forum this year. Even refitted all the street lamps in the Agreed Demilitarized Zone with new models.", "Mariru")
	await novel_interface.show_dialog("Each street lamp doubles as a surveillance camera now. Got the corresponding networks and units installed too.", "Mariru")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("That’s not a very smart plan. Surely there are locations with no street lamps. Why else would you have to use drones, right?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya says, mockingly, but Mariru simply hums in agreement.")
	await novel_interface.show_dialog("Yeah, not a smart plan at all. Costs a lot, and doesn’t yield a lot of results. Besides, there’s a huge political risk factor too...", "Mariru")
	await novel_interface.show_dialog("If the media finds out about there being surveillance cameras everywhere, they’ll definitely bring up classic dystopian novels. George Orwell and stuff like that. The United Congress would be under fire.", "Mariru")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_dialog("Anyway, I found out what I needed to know.", "Mariru")
	novel_interface.change_background("res://assets/images/bg/Soya/Club.png")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("It’s now confirmed that all I need to do is put certain people under a bit of pressure to convince even the world’s most influential organizations to make blatantly stupid decisions.", "Mariru")
	await novel_interface.show_dialog("Now, all we need to know is who to target...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru scans the thousands of profiles that have just been imported into her handheld device. Profiles that contain identities, bank accounts, amount of funds and other related details.")
	await novel_interface.show_dialog("What do you mean...?", "Lian")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("For example, the Senate is the organization that holds the most power over the New Opulentia Federation. In that case, what I’d like to know is how much power the Senate holds exactly. Does everyone have to follow their orders?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("You don’t, for one...", "Lian")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("In a nutshell, every nation is composed of a multi-layered system of power. The power different organizations hold is affected by many factors: the economy, the military, history, cultures, religions and more.", "Mariru")
	await novel_interface.show_dialog("As for the leader of a nation, they’re merely a representative that has been chosen to keep the balance in the complicated struggle for power among different factions.", "Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Since the very beginning in history, no matter in what political system—democratic, dictatorship, republic, academic—there’s never been a real “King” who decides everything.", "Mariru")
	await novel_interface.show_dialog("All there was is someone who has to negotiate their way through countless conflicting situations, make impossible choices for everyone, and take the blame for all things that aren’t their fault.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru pauses, gazing at a group of retrieval team members, who are evacuating the masses in hazmat suits.")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("That one person who holds all this responsibility... they may look strong, but in fact their bodies bear more scars than they can count.", "Mariru")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("…", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya remains silent, a hand over her chest, while I stare, confused.")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("I’m not sure I understand...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("You’re not meant to anyway, idiot.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya forces herself to calm her breathing and finally asks, tone serious:")
	novel_interface.show_character("soya_uniform","speechless")
	await novel_interface.show_dialog("I see that you’re here to bargain—but the final puzzle piece, the most crucial one, is still missing. So you’re willing to give me something in exchange for my information, huh?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Yup.", "Mariru")
	await novel_interface.show_text_only("Mariru replies, easily.")
	await novel_interface.show_dialog("As far as I know, Judgment Knights are “black-robed monks who own the Seal of Truth”. Fewer than twenty lucky ones have received such an honor in over the past five hundred years.", "Mariru")
	await novel_interface.show_dialog("In history, there have been countless highly talented black-robed monks.", "Mariru")
	await novel_interface.show_dialog("Yet not even they received the Seal of Truth, a symbol of the highest immunity in the Kingdom of God. Only those whom the church determined to have made an important contribution to the world have the privilege.", "Mariru")
	await novel_interface.show_dialog("You received yours two years ago. It was awarded to you by the late Pope, His Holiness Callistus IV.", "Mariru")
	await novel_interface.show_dialog("You couldn’t have been more than twelve years old then, could you?", "Mariru")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Hm, you really know a lot.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Well, I’ll cut straight to the point.", "Mariru")
	await novel_interface.show_dialog("What exactly did you do three years ago, on the “purification” mission at the Guyana Shield?", "Mariru")
	await novel_interface.show_text_only("Sonya is quiet for a few seconds before looking back up.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("I know what you want from me, but I have conditions.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Sure, I’m all ears.", "Mariru")
	novel_interface.show_character("soya_uniform","yell")
	await novel_interface.show_dialog("First, deactivate this anklet, now!", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("I can’t.", "Mariru")
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("What?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Deactivating requires special equipment from the SID headquarters. I can’t do it remotely. Right now, all we can do is set the distance allowed between you and Ren to the maximum number, around 650 feet.", "Mariru")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("... Fine, at least that’s better than thirty feet.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("The yellow indicator light on Sonya’s anklet blinks a few times.")
	await novel_interface.show_dialog("It’s done.", "Mariru")
	await novel_interface.show_text_only("Eyes fixed on me, Sonya begins backing away cautiously, pausing every few steps, finally sighing in relief when it’s obvious that we’re over 650 feet apart.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Well, second, I want to know what’s up between Beatrice and Ren. And I want Ren to tell me in her own words.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru ponders this in silence for a bit.")
	await novel_interface.show_dialog("... Fine. But you must promise you won’t tell anyone else.", "Mariru")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("W-what? Is it really okay to tell her?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beatrice had died sometime in the thirteenth century. According to Aya, Beatrice’s current body had only been created the very moment I summoned her.")#换行问题
	novel_interface.show_character("ren_fishnet","uneasy")
	await novel_interface.show_dialog("(So I “created” such an amazing body? That’s surreal...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("However, this fact is labeled a top secret. Not even the Senate can know.")
	await novel_interface.show_text_only("Currently, only eight people in the whole world knows the truth: me, Annie, Beatrice herself, Raphilia, Dr. Dekkers, Mariru, Aya and Henrietta.")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("(The information Mariru wants from Sonya must be insanely important...)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("I promise not to tell a soul.", "Soya")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("But don’t forget—if Ren lies, I’ll be able to tell at a glance!", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("All right, all right!\nStop rubbing it in...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I proceed to explain my experience in Sky Hotel, where I summoned Beatrice using Raphilia’s emerald necklace.")
	await novel_interface.show_text_only("Under Mariru’s permission, I tell her the part about Beatrice defeating Igor and her “curse” as well.")
	await novel_interface.show_text_only("Sonya listens on, eyes bright, like a child enjoying a bedtime story, interjecting with excited gasps from time to time.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("So the emerald on that necklace that belonged to Raphilia’s family... it used to be embedded in Beatrice’s sword centuries ago?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Yeah. Aya confirmed that. She’s an expert.", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Beatrice Portinari... she was in Dante’s work, depicted as a witch...", "Soya")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("That’s so fascinating!", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ahem.", "Mariru")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Okay, the evidence you need... it’s right inside me! That Aya girl will probably be able to detect it.", "Soya")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("But I wanna hang out with Ren a bit longer! Can we return to SID tomorrow instead of now? I promise to be back before noon!", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Fine...", "Mariru")
	await novel_interface.show_dialog("Oh, by the way, Ren, Aya’s collected all the surveillance footage from the drones and the security soldiers and put them all together on a page. You have access too, you can check it on your phone.", "Mariru")
	await novel_interface.show_dialog("We don’t know yet if the chaos tonight is caused by Substance H. Promise me you’ll be careful.", "Mariru")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Mariru then cuts the connection.")
	novel_interface.change_background("res://assets/images/bg/Soya/Club.png")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("As for you guys...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("She glares down at the men she had captured from the auction, all tied up, half-naked, mouths taped.")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("Would you prefer to die from leaked radiation...", "Mariru")
	await novel_interface.show_dialog("Or cooperate with me and let us wipe your memories after that?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("The men, writhing in terror, let out frantic moans behind the gum tape.")
	await novel_interface.show_text_only("Mariru stomps down hard on one of them. On her face is a haughty, queen-like smile.")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Thought so.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_dialog("Hehehe...", "Soya")
	await novel_interface.show_text_only("The second Mariru hangs up, Sonya flashes a wide grin at me.")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("W-what...?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("There’s a question I wanted to ask... but I thought that female gorilla wouldn’t let you tell.", "Soya")
	await novel_interface.show_dialog("Since you’re affected by Beatrice’s curse too, you must be male, huh?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("What?", "Lian")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("I... no, I’m a girl...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("How do I even reply to this?")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("Your aura tells me that you’re not telling the full truth...", "Soya")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("Ahh... Ren, you’re indeed the most fascinating of them all!", "Soya")
	await novel_interface.show_dialog("And how do your boobs work anyway?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("Stop it! Go away!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I attempt to flee towards the church.")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("Hey, wait... didn’t you contact that Mother Elgana and tell her we’d arrive soon?\nIs it really okay to keep her waiting?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_dialog("Ah, you’re Ren, aren’t you?", "Female Voice")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N_Door.png")
	await novel_interface.show_text_only("A woman’s voice, soft and gentle.")
	novel_interface.show_character("el","smile")
	await novel_interface.show_text_only("I follow the sound and see a nun standing at the church entrance, smiling benevolently.")
	await novel_interface.show_text_only("She looks to be in her early thirties, skin glowing, long blonde hair cascading all the way down to her waist.")
	await novel_interface.show_dialog("I was worried that you might have gotten lost on the way!", "Nun")
	await novel_interface.show_dialog("I’m Elgana.", "Nun")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("Mother Elgana...?", "Lian")
	await novel_interface.hide_character()
	
	print("=== 天启篇第14话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
