# apocalypse_ep06.gd - 天启篇第06话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第06话剧本
	apocalypse_ep06_script()

func play_script():
	pass

# 天启篇第06话 - 正式剧本
func apocalypse_ep06_script():
	# scene1 - SID指挥室
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("──指令室内。\n\n眉をひそめたマリルが、映像をループ再生して\n眺めている。")
	await novel_interface.show_text_only("数時間前、例の『自動反撃システム』を\nマサダブルクの議長が発表した時の映像である。")
	await novel_interface.show_text_only("動画の中年男性は微笑を浮かべて自然体で\n語りかけてくる。\nまるで主婦に最新型オーブンを紹介する\n通販番組みたいだ。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("顔認証による分析の結果は出たか？", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("議長本人に間違いないわ。さらに嘘の感情や\n微細な表情変化も見当たらない──", "アイ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("愛衣はこの結果に対して、少しガッカリして\nいるように見える。")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("つまり、公衆向かって世界の終末を発表しながら\n本心から微笑んでいるという事か？", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("ちっ、その位なら私でもできるのに……", "アイ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("負けず嫌い？な愛衣をマリルは軽く叩いた。")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("彼はお前じゃない……", "マリル")
	await novel_interface.show_dialog("この議長は20年近くも政治の世界に身を\n置いているんだ。\n自分の行為が招く結果を充分に理解しているはず\nなのだが……", "マリル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("マリルはスクリーン上部のトップニュースを\n確認する。\nすでに難民の抗議デモが、西アジアに近い\n数箇所の都市で勃発していた。")
	await novel_interface.show_text_only("その画面の下には、新豊洲のホットスポットの\n分布図。\n色が明るく表示されている地区は、人が集まって\nいる事を意味している。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("マスコミへの規制はどうなった？", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("禁止令を配布する権利は私達にないけどねぇ……\n\n大半の企業はSIDの介入を知って大人しく\n協力してくれているわ。", "アイ")
	novel_interface.change_expression("wink")
	await novel_interface.show_dialog("残りの頑固者は「出所不明」のサイバー攻撃で\n全面的に麻痺しているみたい。", "アイ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("愛衣がおどけた顔をするとマリルの口元も\nわずかに上がった。")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("それでも、私達だけじゃ世界中のマスコミを\n抑えられない……", "アイ")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("現在は一貫して報道規制を行ってる華雲宮以外、\n他の国はもう大騒ぎだよ。", "アイ")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("それは私達が心配する事ではないな。", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_dizzy")
	await novel_interface.show_dialog("協定非武装地域のネットに対しても……？", "アイ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("マリルは「やめとけ」と言わんばかりに\n手を振った。")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("ここ数日、連合議会はあらゆる攻撃に対して\n敏感になっている。\nとりあえず、お前は面倒事を起こすな。", "マリル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("マリルは毎秒更新されるホットスポットの\n分布図を眺めながら、\n防衛庁と市政部門の官僚達をどのように大人しく\n協力させるか……その方法を考えていた。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("ちっ、元老院の連中め。\n\n閉鎖会議に引きこもるのは良いが自分本位でしか\n対応しないゴリラだけを外に残すとは……", "マリル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("マリルはタブレットからいくつかの鉄道の駅を\n選ぶと、部下の捜査員へと電話をかけた。")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("ホットスポットの人の流れを分散させる。\n\nまずは交通局へ爆発物の警告を出して、\n複数の駅を運行停止にしてもらえ。", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("了解です。", "SID捜査官")
	novel_interface.show_character("agent")
	novel_interface.show_character("liliu_uniform1","jest")
	await novel_interface.show_dialog("ああ一応、爆弾処理班を現場に行かせて、\n芝居だけは打っておこうか。", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("承知いたしました。", "SID捜査官")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("そして市街地5つの重点区域をしっかりと\nマークしろ。\n今日は普段以上に人が多く集まっている。", "マリル")
	await novel_interface.show_dialog("現場は臨機応変を心がけるように。\n\nアクシデント次第では防護服を着用して街中に\n二酸化硫黄を散布、以降はガス漏れなどを装え。", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("お任せください。", "SID捜査官")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("マリルが電話を切ると、期待に満ちた顔をして\n愛衣がこちらを見ている事に気付いた。")
	novel_interface.show_character("liliu_uniform1","jest")
	await novel_interface.show_dialog("お前は西北地区にヨウ化銀砲弾を撃ち込め。\n\n雨が降れば皆も大人しく帰宅するだろう。", "マリル")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("協定非武装地域へ影響が出ないように、\n風向きには注意しろ──\n国際条約は面倒だが、一応守らなくてはな。", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("ふへへ、ノープロブレム～～！", "アイ")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…………")
	
	# scene2 - 美术馆与瑟蕾莎
	novel_interface.show_background("res://assets/images/bg/Soya/Galleries.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.show_character("cereza","wordless")
	await novel_interface.show_text_only("俺はこっそりと目線だけを動かし、目の前の\nお姉さんの服を見ていた。")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","timid")
	await novel_interface.show_dialog("（お、大きい……）\n\n（動いたら飛び出さないのか……）", "レン")
	#await novel_interface.show_text_only("")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("俺の考えを見抜いたのか彼女は豊満な胸元を\n縛ったベルトを引っ張り、\n誘惑するかのように笑った。")
	novel_interface.show_character("cereza","jest")
	await novel_interface.show_dialog("この子達は包まれてるから、ほら見て……\n……出ないわよ？", "黒髪の女性")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("えっ……はっ？\n（考えが見透かされた？）", "レン")
	#await novel_interface.show_text_only("")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("（と言うかもう、引っ張らないでっ！ ）\n\n（食い込んで、あの、素敵な形に！！）", "レン")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("セレサ、なぜあんたがここに？", "ラファエル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("過激なやり取りの最中、ラファエルが間に入って\n彼女にそう告げた。\nその後ろでは青い煙に包まれたソヤが怒りながら\nイルカを引っ張りつつ、こちらへ迫っている。")
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("ブーラの老婆だよっ！\n\n 何度も電話してくるから、本当うるさいったら\nありゃしない……", "テレサ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("セレサは気だるそうな顔であくびをしながら、\n続けて片腕を俺の首に回してきた。")
	novel_interface.show_character("cereza","jest")
	await novel_interface.show_dialog("ねぇ、これが噂だったマリルの手下の「レン」\nよね？\n前回の共同研究であんたと一緒だったあの？", "テレサ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("（この人、前回の南極での件を知ってるのか？）\n\n （……どこまでの内容を？）", "レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ラファエルは「あっ」と声を上げると、\n顔を横に向けて視線をそらした。")
	await novel_interface.show_text_only("いつの間にか後ろに回ってきて両手で俺の肩を\n握ったセレサ……\n彼女の態度は良く分からない。")
	novel_interface.show_character("cereza","smile")
	await novel_interface.show_dialog("うーん、素質は悪くないけど鍛錬が足りて\nいないわね。", "テレサ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("筋肉がなくてすみませんでした。")
	await novel_interface.show_text_only("突然、彼女は人差し指を引っ掛け、指の関節で\n俺の脊髄の両側を支えながら下へ滑らせた。\n指が腰までたどり着くとキュッと力を\n入れてくる──")
	await novel_interface.show_text_only("すると全身に力の抜けるような暖かい感じがして\n思わず声を漏らしてしまう。")
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("あんっ……", "レン")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("…………", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("お～や～？", "ソヤ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("もう見飽きたと言わんばかりの表情をする\nラファエルと違い、\nソヤは俺の零れた嬌声に興味が傾いたようで\nより近くに迫ってくる。")
	await novel_interface.show_text_only("俺は大人しくセレサのされるがままに……\n\n軽く指でなぞられただけなのに、もう抵抗しても\n無駄だと心が思ってしまう。")
	await novel_interface.show_dialog("さっ、目を閉じて──", "テレサ")
	await novel_interface.show_text_only("セレサは俺の耳元でそっとささやく。")
	await novel_interface.show_dialog("想像してごらんなさいな？ \n君の小さい右腕が前へ飛び出そうとするの。\nでも指が引っかかって動けなくて……ゆっくりと\n前に動く力を蓄える事しかできない──", "テレサ")
	await novel_interface.show_text_only("セレサの指示通り俺は右腕を上げて、\n指を左肩に引っかけた。")
	await novel_interface.show_dialog("深呼吸…………そして……", "テレサ")
	await novel_interface.show_dialog("放つ──", "テレサ")
	await novel_interface.show_text_only("右手の指を解き放つ。\n\n腕は弓なりに弾き出されて、宙で何かを\n切ったような感触がする。")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("…………？", "レン")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","trance")
	await novel_interface.show_text_only("目の前に立っていたソヤの前髪の一部が、\n俺の爪によって鮮やかに切り裂かれていた。")
	novel_interface.change_expression("afraid")
	await novel_interface.show_dialog("はぅ！？", "ソヤ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ただただ俺達2人は立ち尽くして、その銀髪が\nゆっくりと落ちるのを見るしかできなかった……")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("ごっ、ごめん！　ケガしてない？", "レン")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","shy")
	await novel_interface.show_dialog("はふぅん……", "ソヤ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ソヤは小動物みたいな声を出す。")
	novel_interface.show_character("soya_uniform","shy")
	await novel_interface.show_dialog("さきほどの息吹……まるでわたくしの身体を\n突き抜けるかのような……", "ソヤ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ソヤは照れながら俺を見つめる……\n\nまるで何か陶酔というか、気持ち良さそうに\nしているんだけど！？")#换行问题
	novel_interface.show_character("cereza","jest")
	await novel_interface.show_dialog("はははっ、どおりで我らのお嬢様が新豊洲に\n留まるわけだ……", "テレサ")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("──余計な事はいい。\n\n私はあんたが何しに来たのかって\n聞いているのだけど？", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","jest")
	await novel_interface.show_dialog("あんたを大使館まで迎えに来たのよ。", "テレサ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("あ、あなたは一体……", "レン")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","smile")
	await novel_interface.show_dialog("あっ、ひとまず自己紹介よね～～", "テレサ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("セレサは胸の位置を正す。")
	novel_interface.show_character("cereza","smile")
	await novel_interface.show_dialog("十字薔薇の格闘総教官、セレサよ。", "テレサ")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("主に人にケンカの仕方を教えるのが仕事──\n\nまあ、大体は私が人を殴ってばかりだけどね。", "テレサ")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("お嬢様が面倒事を起こした際は、たまにだけど\nボディガードもしているわ。", "テレサ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("セレサはラファエルにウィンクをしたが、\n無慈悲にもラファエルはそっぽ向く。")
	novel_interface.show_character("cereza","smile")
	await novel_interface.show_dialog("私は彼女のお爺ちゃんからコンパニオン勲章を\nもらっているからさ～～", "テレサ")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("だから御託はいいから……\n\n迎えに来たって、何が起こったっていうのよ？", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("それがねぇ、私も目を覚ましたばかりだから……\nとにかく老婆によると──", "テレサ")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("マサダブルクの議長さん、ホテルの部屋で\n自殺したらしいのよ。", "テレサ")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("なッ！！？？", "ラファエル")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("ど、どういう事……っ！？！？", "レン")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("私が持ってる情報はこれだけよ。\nなんちゃら議長の事、あんた達は知ってるの？", "テレサ")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("あっちゃ──！", "テレサ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("セレサは頭を叩いて大声で叫ぶと、\n俺の方へ振り返った。")
	novel_interface.show_character("cereza","boring")
	await novel_interface.show_dialog("これ……機密情報だったっけ……", "テレサ")
	novel_interface.change_expression("blink")
	await novel_interface.show_dialog("まぁ、別にいいか。", "テレサ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("えっ、いいの！？", "レン")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","normal")
	await novel_interface.show_dialog("どうせSIDも知ってるでしょ？ \n保安軍も2級警戒態勢になってるし。", "テレサ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("セレサは咳払いすると、だらけた姿を瞬時に\n止めた。\nそして腰をぴんと伸ばし、刀を握りしめる。")
	novel_interface.show_character("cereza","normal")
	await novel_interface.show_dialog("というわけで──安保協議に従い、私がお嬢様を\n大使館まで護送します。", "テレサ")#换行问题
	await novel_interface.hide_character()

	print("=== 天启篇第06话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
