# apocalypse_ep03.gd - 天启篇第03话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第03话剧本
	apocalypse_ep03_script()

func play_script():
	pass

# 天启篇第03话 - 正式剧本
func apocalypse_ep03_script():
	# scene1 - 电器街下午
	novel_interface.show_background("res://assets/images/bg/Soya/Akihabara.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("<Улица Нэкомару Электроникс, 17:00>")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("Стоп! Соня! Подожди!", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я кричу на седовласую девушку, которая идет вперед пружинистым шагом, таща за собой Эллуку. Я никак не смогу догнать этих двоих, таща за собой громоздкий бумажный пакет.")
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_dialog("Разве ты не должен следовать за мной, а не я за тобой?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Мои бесполезные жалобы остаются без внимания, поглощенные гомоном толпы на улице Электроники.")
	await novel_interface.show_text_only("Во время войны Сенат принял Закон о социальном порядке, чтобы способствовать гармонии между иммигрантами из разных регионов, религий и культур.")
	await novel_interface.show_text_only("Из-за этого ранее процветавшая индустрия культуры и развлечений в этом районе понесла серьезный удар.")
	await novel_interface.show_text_only("На территории, находящейся под прикрытием Aegis, новый район посольства и окрестности являются единственными участками, на которые не распространяются ограничения закона.")
	await novel_interface.show_text_only("Таким образом, этот район стал центром магазинов, торгующих «нишевыми товарами». Например, горничное кафе, стоящее в его центре девять лет назад, является одной из самых популярных достопримечательностей в этом районе.")
	await novel_interface.show_text_only("Хотя сейчас закон уже не действует, эта улица на границе Согласованной демилитаризованной зоны стала своего рода Меккой для отаку всего мира.")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("(В любом случае, почему Мариру заставила меня надеть этот наряд...)", "Лиан")
	novel_interface.change_expression("wail")
	await novel_interface.show_dialog("(... тоже с чулками в сеточку?)", "Лиан")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("(Это первый раз, когда я ношу что-то подобное...)", "Лиан")
	await novel_interface.show_dialog("(И не слишком ли высокие эти каблуки?)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я гонюсь за Соней, отчаянно поправляя чулки свободной рукой, изо всех сил стараясь не обращать внимания на взгляды прохожих.")
	await novel_interface.show_text_only("Чего они не осознают, так это того, что и я, и седовласая девушка носим на правых лодыжках устройства мониторинга, отслеживающие расстояние между нами в режиме реального времени.")
	await novel_interface.show_text_only("Если мы когда-нибудь окажемся на расстоянии более тридцати футов друг от друга, браслет Сони, усиленный веществом H, немедленно оглушит ее током в 20 000 вольт.")
	await novel_interface.show_text_only("Конечно, еще одно из гордых изобретений Аи.")
	await novel_interface.show_text_only("Внезапно я поскальзываюсь на ступеньке за углом и теряю равновесие…")
	await novel_interface.show_text_only("Бумажный пакет вылетает из моих рук, образуя в воздухе красивую дугу.")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("Что?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Крах!")
	await novel_interface.show_text_only("Содержимое мешка выкатывается, когда он падает на землю.")
	await novel_interface.show_text_only("Я собираюсь упасть вперед во всей своей красе в чулках-сеточках, когда кто-то хватает меня сзади.")
	await novel_interface.show_text_only("Знакомый голос шепчет мне на ухо:")
	await novel_interface.show_dialog("Эй, зачем спешка?", "Женский голос")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Soya/Akihabara.png")
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("Р-Рафилия?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Это внучка губернатора Салмонтона. Она уже несколько дней отсутствует в школе, вероятно, из-за Форума Мира.")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("Ты опоздал на смену в горничную или что-то в этом роде?", "Рафаэль")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Рафилия понимающе ухмыляется моему тяжелому положению, в то время как ее свита бросается помочь мне собрать разбросанные предметы.")
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("Н-нет, это для другой миссии...", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("По какой-то причине Рафилия знала все о моей подработке в горничной. Даже обязательно посетил несколько раз.")
	
	# 回忆场景
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Представьте себе это.")
	await novel_interface.show_text_only("Я, одетый в костюм горничной с белыми подвязками с оборками, приветствую Рафилию в кафе...")
	novel_interface.show_character("ren_maid","shy")
	await novel_interface.show_dialog("С возвращением... Мастер!", "Лиан")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("Что бы ты хотел заказать сегодня, ня?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Оу...", "Рафаэль")
	await novel_interface.show_dialog("Ха-ха-ха-ха!", "Рафаэль")
	novel_interface.show_character("ren_maid","stare")
	await novel_interface.show_dialog("Мастер, вы пролили чай, ня...", "Лиан")
	await novel_interface.hide_character()
	
	# 回到现实
	novel_interface.show_background("res://assets/images/bg/Soya/Akihabara.png")
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_dialog("(Ух, я должен попросить Аю стереть ей память! И мою тоже, пока она этим занимается...)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Рафилия окидывает меня взглядом, и я быстро придергиваю платье.")# 换行问题
	await novel_interface.show_text_only("Она не перестает смотреть на мои ноги. Или, точнее, мои чулки.")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("На этот раз ваша миссия — соблазнить кого-то из высокопоставленных чиновников в правительстве?", "Рафаэль")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("Ни в коем случае!", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Свита Рафилии возвращается с моим ассортиментом вещей.")
	novel_interface.show_character("servent")
	await novel_interface.show_dialog("Мисс Рен, я все для вас нашел. Позвольте мне перечислить их всех —", "Антураж")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("Нет, нет, пожалуйста, не надо, все в порядке!", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Рафилия достает из сумки пару книг и изучает обложки.")
	novel_interface.show_character("servent")
	await novel_interface.show_dialog("Влюблена в своего похитителя, все связанные, эксклюзивное лечение...", "Антураж")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("«Рабство и боль волнуют меня и заставляют чувствовать себя такой свободной…»", "Рафаэль")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Рафилия читает вслух и имеет приличие покраснеть. Она смотрит на то, чтобы дать мне пощечину, но в итоге просто переворачивает следующую страницу.")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("…", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("…", "Рафаэль")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Неловкое молчание.")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("Нет, подожди, это не мои...", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Посмотрим, что еще... упряжь, кнут...\nО, еще квитанция с подписью мисс Рен.", "Антураж")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("Я заплатил за них, но это не значит, что я их выбрал!", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я протестую, желая просто вырыть яму в земле и умереть.")
	await novel_interface.show_text_only("Некоторые пешеходы останавливаются и смотрят.")
	await novel_interface.show_dialog("Посмотрите на этот кнут. Кажется, эта девушка мазохистка. Думаешь, у нее получится хорошая задница?", "Прохожий А")#文本错误
	await novel_interface.show_dialog("Она выглядит довольно мило...", "Прохожий Б")
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_dialog("(Я не девочка!)\n(И уж точно не дно!)", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("Ох! Действительно дно!", "Соя")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("— восклицает Соня, торжествующе показывая на надпись «удобные трусики для задорной попки» на этикетке кружевного белья в сумке.")
	await novel_interface.show_text_only("Она усмехается, проводя языком по верхней губе, как котенок.")
	await novel_interface.show_text_only("Или лучше сказать кот, который съел канарейку?")
	novel_interface.show_character("iluka_uniform","speechless")
	await novel_interface.show_dialog("Мисс Рен, что такое низ?", "Эллука")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_dialog("(Ух, убей меня сейчас!)", "Лиан")
	await novel_interface.hide_character()
	
	# scene2 - 回忆审讯室
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…")
	novel_interface.change_background("res://assets/images/bg/SID/hearingRoom.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("<Ранее, комната для допросов SID>")
	novel_interface.show_character("soya_nun","relieve")
	await novel_interface.show_dialog("Да...", "Соя")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Ведьмы, оборотни, зомби, демоны, вампиры, вся эта сволочь... Я их всех очищаю!", "Соя")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("Те термины, которые вы перечислили...", "Мариру")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_nun","smile")
	await novel_interface.show_dialog("Это просто имена, которые люди дали разным типам существ, зараженных веществом H. На мой взгляд, они все одинаковы.", "Соя")
	await novel_interface.show_dialog("Пока их аура выглядит мутной, пахнет соленой или имеет горький вкус...", "Соя")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Я убью их всех.", "Соя")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Выражение лица Мариру становится мрачным при виде невинной улыбки девушки за односторонним зеркалом.")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("Так у тебя есть синестезия, ты имеешь в виду?", "Мариру")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Синестезия — это перцепционный феномен, при котором стимуляция одного сенсорного типа автоматически трансформируется в стимуляцию другого сенсорного типа.")
	await novel_interface.show_text_only("Например, если вы всегда чувствуете определенный запах, когда видите определенную форму, или видите определенный цвет, когда слышите определенный звук, это синестезия.")
	await novel_interface.show_text_only("Лишь немногие люди обладают такой почти сверхспособностью.")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("Так вот почему ты так легко уклоняешься от атак, а?", "Мариру")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_nun","relieve")
	await novel_interface.show_dialog("Хм, может быть?", "Соя")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Недавно меня отправили в церковный округ Новая Опулентия, чтобы предотвратить потенциальные «инциденты», которые могут произойти во время Форума.", "Соя")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("Потом ты встретил по пути каких-то ведьм и просто так их уничтожил?", "Мариру")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_nun","normal")
	await novel_interface.show_dialog("Да! Я помахал им рукой, чтобы они перебрались сами.", "Соя")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("Избавил меня от необходимости гоняться за ними.", "Соя")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Соня корчит рожу и пожимает плечами.")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("…", "Мариру")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Мариру хмурится. Причудливое решение девушки сорвало операцию по слежению, которая длилась восемьдесят часов и на планирование ушли десятки дней.")#换行问题
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("Ну и следующий вопрос...", "Мариру")
	await novel_interface.show_dialog("Вы намеренно слили ключевую информацию во всех своих ответах, которые вы мне только что дали...", "Мариру")
	await novel_interface.show_dialog("Значит, ты хочешь что-то взамен, да?", "Мариру")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_nun","normal")
	await novel_interface.show_dialog("Ты действительно хорош в допросе!", "Соя")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Чего я хочу? Хм... помнишь девушку, которая недавно стояла на твоем месте?", "Соя")#文本错误
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("(Кто это был... Ая?)", "Мариру")
	await novel_interface.hide_character()
	
	# 背景切换
	novel_interface.change_background("res://assets/images/bg/Soya/AI.png")
	await novel_interface.show_text_only("Соня говорит, лицо серьезное.")
	await novel_interface.show_dialog("Она ничего не сказала, но у нее уникальная мощная аура...", "Соя")
	await novel_interface.show_dialog("Как будто она хочет поглотить, нет, сожрать все знания в мире.", "Соя")
	await novel_interface.show_dialog("…", "Соя")
	
	novel_interface.change_background("res://assets/images/bg/SID/hearingRoom.png")
	await novel_interface.show_text_only("Девушка почти незаметно дрожит, но вскоре восстанавливает самообладание.")
	novel_interface.show_character("soya_nun","smile")
	await novel_interface.show_dialog("У меня есть условие: пока ты будешь держать ее подальше от меня, я соглашусь с тобой работать.", "Соя")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("(Это точное описание Аи, но она не из тех, кто обычно причиняет вред своим подопытным...)", "Мариру")
	await novel_interface.show_dialog("(На самом деле, она искренне любит интересные экземпляры, которые ей попадаются.)", "Мариру")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("У тебя есть секрет, который ты предпочитаешь скрывать, да?", "Мариру")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Мариру ухмыляется.")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("Я вижу. Конечно, я принимаю.", "Мариру")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("<День, несколько часов спустя>")
	novel_interface.show_background("res://assets/images/bg/SID/hearingRoom.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("Когда я вхожу в комнату, я прохожу мимо нескольких уходящих агентов. По пути они посылают мне сочувствующие взгляды...")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("Ч-что происходит?", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("Расслабься. Мы просто отправляем вас на простую миссию по сопровождению.", "Мариру")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Мариру указывает на девушку в комнате для допросов, видимую по другую сторону одностороннего зеркала.")
	await novel_interface.show_text_only("Длинные серебристые локоны, нежное, бледное лицо. Она сидит молча, с пустым лицом.")
	await novel_interface.show_text_only("Элегантный, изысканный. Это мое первое впечатление о ней.")
	await novel_interface.show_text_only("А потом она поднимает взгляд. Ее глаза просверлили дыры в моей душе, как будто она могла видеть сквозь одностороннее зеркало.")
	await novel_interface.show_text_only("Она выглядит так, будто может выпустить из глаз розовые лучи и испепелить меня в любую секунду.")
	novel_interface.show_character("soya_nun","shy")
	await novel_interface.show_dialog("Этот запах...", "Соя")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Девушка встает, прижавшись щекой к стеклу передо мной.")
	await novel_interface.show_text_only("Ее нос-пуговица дергается, как у кролика, которому вручили морковку.")
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("Что?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я знаю, что она не слышит меня через стекло, но я все равно рефлекторно задерживаю дыхание.")
	await novel_interface.show_text_only("Мариру несколько раз кашляет и нажимает кнопку, чтобы разогреть стекло.")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("Знакомьтесь, Соня Анхелес.", "Мариру")
	await novel_interface.show_dialog("Соня, это Рен.", "Мариру")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_nun","laugh")
	await novel_interface.show_dialog("Ох! Привет!", "Соя")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Девочка выглядит взволнованной, как ребенок, которому только что подарили новую игрушку.")
	await novel_interface.show_text_only("Если бы у нее был хвост, завтра он бы вилял как ни в чем не бывало.")
	await novel_interface.show_text_only("Мариру еще раз нажимает кнопку, чтобы зеркало стало непрозрачным. Перед нами материализуются профиль Сони и карта Новой Опулентии.")
	await novel_interface.show_text_only("Она кратко описывает мне ситуацию Сони, затем увеличивает карту.")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("Ваша задача — привести Соню и Эллуку за покупками в этот район.", "Мариру")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","bored")
	await novel_interface.show_dialog("Разве это не рядом с горничной, в которой я работаю? Внутри согласованной демилитаризованной зоны, рядом с посольством.", "Лиан")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Но я думал, что теперь это зона ограниченного доступа?\nВсе магазины будут закрыты до окончания Форума на следующей неделе.", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("Ограничение было снято вчера вечером Объединённым Конгрессом из ниоткуда. А Сенат приказал половине персонала Бюро обороны уйти.", "Мариру")
	await novel_interface.show_dialog("Мы не уверены, что именно происходит, но сейчас эта территория является своего рода ничейной землей.", "Мариру")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","normal2")
	await novel_interface.show_dialog("Значит, мы должны патрулировать это место, притворяясь, что делаем покупки?", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("О, тебе не обязательно этого делать. У нас достаточно камер видеонаблюдения в этом районе.", "Мариру")
	await novel_interface.show_dialog("Объединенный Конгресс знает о личности и способностях Сони. Сенат, с другой стороны, смотрит на вас.", "Мариру")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("Им все равно, что вы там делаете. Тот факт, что вы будете появляться вместе, сам по себе является большой новостью.", "Мариру")#换行问题
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("А что, если Соня попытается сбежать?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я никогда не смогу победить ее...")
	await novel_interface.show_text_only("Мариру просто ухмыляется и нажимает кнопку, чтобы убрать запотевание экрана, хотя Соня по-прежнему не слышит нас изнутри. Сейчас она прислонилась к стене и выглядит скучающей.")#换行问题
	await novel_interface.show_text_only("Мариру постукивает по своему портативному устройству, и металлический браслет на седовласой девушке начинает мигать красным.")
	await novel_interface.show_text_only("Девушка пристально смотрит на Мариру и произносит: «Опять?»")
	novel_interface.show_character("ren_uniform","normal2")
	await novel_interface.show_dialog("?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("И вдруг возникает голубая вспышка электричества. Соня падает на землю в клубах бирюзового дыма.")
	novel_interface.show_character("ren_uniform","panic")
	await novel_interface.show_dialog("...", "Лиан")
	await novel_interface.show_dialog("... Она...", "Лиан")
	novel_interface.change_expression("wail")
	await novel_interface.show_dialog("... мертв?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Через несколько секунд тело маленькой монахини сводит судорогой, и она снова карабкается на ноги и подходит к стеклу, выглядя очень готовой выкрикивать ненормативную лексику…")
	await novel_interface.show_text_only("Мариру просто нажимает кнопку, и экран снова запотевает.")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("Видишь? С этим устройством она не сможет сбежать.\nКроме того, вы всегда можете сказать Эллуке использовать на ней свои силы.", "Мариру")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("Что? Это зло!", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("О?", "Мариру")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Мариру прижимает меня к стене и наклоняется к моему уху.")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("Слушай, ты важный актив, принадлежащий SID.", "Мариру")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("Если вы попробуете что-нибудь слишком рискованное...\nНам придется вас наказать!", "Мариру")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("… !!!", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Промываю до ушей.")
	novel_interface.show_character("ren_uniform","shy_left")
	await novel_interface.show_dialog("Я... я буду осторожен!", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Мариру улыбается и осторожно выталкивает меня из комнаты для допросов.")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("Я знаю, что ты это сделаешь.", "Мариру")
	await novel_interface.show_dialog("Для вашей миссии у нас есть специальное снаряжение. Попробуйте!", "Мариру")
	await novel_interface.hide_character()

	print("=== 天启篇第03话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
