# apocalypse_ep06.gd - 天启篇第06话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第06话剧本
	apocalypse_ep06_script()

func play_script():
	pass

# 天启篇第06话 - 正式剧本
func apocalypse_ep06_script():
	# scene1 - SID指挥室
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("지휘실 안. 마리루가 미간을 찌푸리고 스크린 위 재생되는 영상을 응시하고 있다.")
	await novel_interface.show_text_only("몇시간 전 마사다 의장이 발표회에서 『자동 반격 시스템』을 소개하는 영상이다──")
	await novel_interface.show_text_only("화면 속 아저씨의 자연스러운 말투가 마치 주부에게 신상 오븐을 소개하는 판매원 같다.")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("안면 분석 결과는 나왔어？", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("확실히 의장 본인이 맞아. 감정이나 표정 위장 같은 것도 발견되지 않았어──", "아이")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("아이가 결과에 조금 실망한 듯 하다.")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("그러니까 세계 멸망을 소개할 때 그 웃는 얼굴이 진심이라는 거지?", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("쳇, 나도 할 수 있다구~", "아이")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("아이가 질 수 없다는 듯 얘기한다.")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("그 사람은 네가 아니야──", "마리루")
	await novel_interface.show_dialog("마사다 의장은 정부에서 20년간 일했어. 이 행위가 불러올 결과를 잘 알고 있을 거야……", "마리루")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("마리루가 스크린 상단의 뉴스 화면을 쳐다본다. 살몬톤 주변 서아시아 도시에 난민 시위가 발생했다.")
	await novel_interface.show_text_only("그 화면들 아래 신토요스의 핫스팟 분포도가 보인다. 빛나는 지역은 항의군이 밀집했다는 뜻이다.")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("미디어 제어는 어떻게 됐어？", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("우리가 금지령을 내릴 권리는 없지만 대다수 기업이 SID가 개입했다는 걸 알고 순순히 협조하고 있어.", "아이")
	novel_interface.change_expression("wink")
	await novel_interface.show_dialog("고집을 부리던 몇몇 기업은 “출처를 알 수 없는” 네트워크 공격으로 곤란해하고 있지.", "아이")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("아이가 장난스런 표정을 짓자 마리루의 입꼬리가 작게 올라간다.")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("하지만 전세계의 미디어를 막을 수는 없어……", "아이")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("현재 화운궁만 예전처럼 언론을 제어하고 있어. 다른 나라는 이미 터져버렸고.", "아이")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("그건 우리가 걱정해야 할 것이 아니야.", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_dizzy")
	await novel_interface.show_dialog("그럼 협의 비무장지대의 네트워크도……", "아이")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("마리루가 아이를 향해 손을 젓는다.")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("요며칠 연합회의가 공격에 대해 아주 민감하니까 아무 것도 하지마.", "마리루")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("마리루가 초마다 갱신되는 도시 핫스팟 분포도를 주시하며 어떻게 방위청과 정부 관료들의 협조를 얻을지 생각한다.")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("에휴, 원로원 그 자식들이 비밀 회의를 여는 바람에 아무것도 안 하는 고릴라만 남았어……", "마리루")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("그녀가 휴대 기기의 전차역을 선택하고 요원에게 전화를 건다.")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("핫스팟 지역의 사람들을 분산시켜야해. 교통국에 폭발물 경고를 보내고 역의 통행을 금지시켜.", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("네.", "SID 요원")
	novel_interface.show_character("agent")
	novel_interface.show_character("liliu_uniform1","jest")
	await novel_interface.show_dialog("아. 폭탄 제거팀도 보내는 것 잊지 말고~", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("알겠습니다.", "SID 요원")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("파견 요원은 5개 중점 지역을 주시해야 돼. 오늘 평소보다 사람들이 더 많이 모여있어.", "마리루")
	await novel_interface.show_dialog("현장 반응을 주시하고 상황이 틀어지면 아황산가스를 뿌려서 가스가 누출된 것처럼 꾸며.", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("네!", "SID 요원")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("마리루가 전화를 끊고 기대가 가득 찬 눈빛으로 자신을 바라보는 아이를 발견한다.")
	novel_interface.show_character("liliu_uniform1","jest")
	await novel_interface.show_dialog("서북 지역에 요오드화 은 폭탄을 두발 터트리면 순순히 집으로 돌아가게 될 거야.", "마리루")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("상황을 잘 파악해야 돼. 협의 비무장지대를 건드리면──국제 공약에 문제가 생길 거야.。", "마리루")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("헤헤, 알았어~", "아이")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	
	# scene2 - 美术馆与瑟蕾莎
	novel_interface.show_background("res://assets/images/bg/Soya/Galleries.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.show_character("cereza","wordless")
	await novel_interface.show_text_only("나는 눈 앞에 있는 이 누나의 옷을 몰래 훔쳐보고 있다.")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","timid")
	await novel_interface.show_dialog("（크, 크다！）\n（운동할 때 튀어나오는 거 아닐까……）", "렌")
	#await novel_interface.show_text_only("")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("그녀가 내 생각을 간파했는지 가슴을 속박하고 있는 벨트를 잡아당기고 웃으며 말한다.")
	novel_interface.show_character("cereza","jest")
	await novel_interface.show_dialog("얘네들이 감싸고 있어서 나올 수 없어~", "흑발 여성")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("윽……네？\n（내 생각을 읽었나？）", "렌")
	#await novel_interface.show_text_only("")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("（계, 계속 당길 필요 없다고！야한 모습이 되고 있어 ！）", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("세레사──넌 왜 왔어?", "라파엘")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("라파엘이 머리에 연기가 나는 소야와 이루카를 끌고 이쪽으로 향해 걸어온다.")
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("불러 그 마녀 때문이야！나한테 어찌나 전화를 걸던지, 졸려 죽겠네……", "테레사")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("세레사가 피곤하다는 얼굴로 기지개를 켜고 팔을 내 목에 건다. ")
	novel_interface.show_character("cereza","jest")
	await novel_interface.show_dialog("~이 친구가 마리루가 거둬들인 그 “렌” 맞지？\n지난번 연합 임무에서 너와 같이 움직인?", "테레사")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("（연합 임무를 알고 있어？）", "렌")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("라파엘이 “아”하고 얼굴을 옆으로 돌리며 상대의 눈빛을 피한다.")
	await novel_interface.show_text_only("세레사가 다짜고짜 내 뒤로 와서 양손으로 내 어깨를 꽉 쥔다.")
	novel_interface.show_character("cereza","smile")
	await novel_interface.show_dialog("음, 골격은 괜찮은데 단련이 부족하네. ", "테레사")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("근육이 없어서 미안합니다~")
	await novel_interface.show_text_only("그녀가 집게손가락을 접고 관절 부분으로 척추 양쪽을 쓸어내리다 허리 부근에서 힘을 준다──")
	await novel_interface.show_text_only("저릿저릿한 느낌이 순간 온몸에 느껴져 참지 못하고 소리를 내버렸다.")
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("아~", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("……", "라파엘")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("오호？", "소야")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("라파엘이 익숙한 얼굴을 하고 있다. 소야는 나의 목소리에 들뜬 것 같다.")
	await novel_interface.show_text_only("수박 겉핥기 같은 수법에도 전혀 반항할 수 없는 나는 얌전히 그녀의 말을 따랐다.")
	await novel_interface.show_dialog("자, 눈을 감아──", "테레사")
	await novel_interface.show_text_only("세레사가 내 귓가에 조용히 얘기한다.")
	await novel_interface.show_dialog("오른손을 앞으로 뻗고 싶지만 손가락에 걸려 움직일 수 없어 천천히 힘을 모을 수 밖에 없어.", "테레사")
	await novel_interface.show_text_only("나는 세레사의 지시에 따라 오른팔을 들어 손가락을 왼쪽 어깨에 올렸다.")
	await novel_interface.show_dialog("숨을 깊게 들이마셔……………………", "테레사")
	await novel_interface.show_dialog("뻗어──", "테레사")
	await novel_interface.show_text_only("오른손 손가락을 놓자마자 팔이 팽팽히 당겨진 활처럼 공중을 가르며 튀어나갔다 ──")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("？", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","trance")
	await novel_interface.show_text_only("나의 앞에 서있던 소야의 앞머리 한가닥이 나의 손톱에 날카롭게 잘려나간다.")
	novel_interface.change_expression("afraid")
	await novel_interface.show_dialog("엣?", "소야")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("우리 두 사람은 제자리에 서서 은발 한가닥이 천천히 떨어지는 것을 쳐다봤다……")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("미, 미안！\n안 다쳤지？", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","shy")
	await novel_interface.show_dialog("으흑~", "소야")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("소야가 작은 동물 같은 목소리를 낸다.")
	novel_interface.show_character("soya_uniform","shy")
	await novel_interface.show_dialog("방금 네 기운이 내 몸을 관통한 것 같아……", "소야")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("얼굴이 잔뜩 달아오른 소야가 날 보며 얘기한다. 뭔가에 심취된 모습으로!")#换行问题
	novel_interface.show_character("cereza","jest")
	await novel_interface.show_dialog("히히, 어쩐지 우리 아가씨가 신토요스에 있어야 한다고 고집을 부리더니……", "테레사")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("시끄러워──여긴 도대체 왜 온 거야！？", "라파엘")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","jest")
	await novel_interface.show_dialog("아가씨를 대사관으로 모시려고 왔지.", "테레사")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("당신 도대체……", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","smile")
	await novel_interface.show_dialog("아, 내 소개를 깜빡했네──", "테레사")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("세레사가 가슴 부근을 정리한다.")
	novel_interface.show_character("cereza","smile")
	await novel_interface.show_dialog("나는 십자장미의 격투 교관 세레사.", "테레사")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("전문적으로 싸움을 가르치는 사람이야──내가 다른 사람을 때리긴 하지만.", "테레사")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("아가씨가 사고를 치면 가끔 보디가드를 맡기도 해. ", "테레사")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("세레사가 라파엘을 향해 윙크를 하자 라파엘이 무표정으로 흘겨본다.")
	novel_interface.show_character("cereza","smile")
	await novel_interface.show_dialog("아가씨의 할아버님께서 내게 전우 훈장을 주시기도 했지~", "테레사")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("그러니까, 도대체 무슨 일이 있는 거야?", "라파엘")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("음……나도 방금 일어나서…그치만 그 마녀의 얘기에 따르면.", "테레사")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("마사다 성 의장이…호텔 방에서 권총으로 자살했어.", "테레사")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("뭐──？！", "라파엘")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("그럴리가?!", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("내 정보는 여기까지야. 그 의장이라는 사람, 너희들도 알고 있어?", "테레사")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("아─！", "테레사")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("세레사가 가슴께를 두드리고 고개를 돌려 날 쳐다본다. ")
	novel_interface.show_character("cereza","boring")
	await novel_interface.show_dialog("이건 기밀 정보인데……", "테레사")
	novel_interface.change_expression("blink")
	await novel_interface.show_dialog("뭐……됐어~", "테레사")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("돼, 됐다고？！", "렌")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","normal")
	await novel_interface.show_dialog("어쨌든 SID도 알고 있을테니까. 보안군도 이미 2급 경계 상태가 됐거든.", "테레사")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("세레사가 목소리를 가다듬고 건들건들한 자세를 바로잡는다. 어깨를 세우고 일본도를 꺼내든다.")
	novel_interface.show_character("cereza","normal")
	await novel_interface.show_dialog("그래서──보안 협의에 따라 아가씨를 대사관으로 모시러 왔습니다.", "테레사")#换行问题
	await novel_interface.hide_character()

	print("=== 天启篇第06话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
