# apocalypse_ep16.gd - 天启篇第16话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第16话剧本
	apocalypse_ep16_script()

func play_script():
	pass

# 天启篇第16话 - 正式剧本
func apocalypse_ep16_script():
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	await novel_interface.show_text_only("Le visage de Sonya est rouge sous la faible lumière jaune. Les gouttelettes d'eau coulent le long de ses mollets minces et nus, laissant une flaque d'eau sur le sol.")
	await novel_interface.show_text_only("Elle est perchée sur le rebord de marbre de la fontaine, comme un animal sans défense. Elle me regarde, des yeux innocents mais si fascinants…")
	await novel_interface.show_text_only("Mon cœur fait un bond et je sens mon visage se réchauffer.")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Sonya...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("J'avais été horrifié lorsque j'avais entendu son histoire, ne voulant plus rien pour la retrouver et la réconforter immédiatement. Mais maintenant, mon cerveau est complètement vide.")
	await novel_interface.show_text_only("Un peu comme ces idiots maladroits que l’on voit dans les mangas – se dirigeant vers leur béguin pour se confesser dans un éclat de fausse bravade, puis oubliant tout ce qu’ils avaient répété à la seconde où ils voient le béguin.")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("(Cerveau, fais quelque chose ! Bon sang !)", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","smile",0.25)
	await novel_interface.show_dialog("Hé...", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Sonya se lèche les lèvres et sourit doucement.")
	novel_interface.show_character("ren_fishnet","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("soya_uniform","normal",0.25)
	await novel_interface.show_dialog("Tu sens... intéressant...", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Elle rampe dans ma direction sur la marche en marbre. Je peux voir le motif de ruche sur son bracelet de cheville se refléter dans la lumière.")
	await novel_interface.show_text_only("Il s’agit d’un bracelet de cheville fabriqué par notre SRD avec des matériaux d’armure Substance H. Il a l'air fragile, mais il est en réalité extrêmement solide.")
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("Exactement comme je m'y attendais...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya me prend la main, presse son nez contre mon ventre et inspire goulûment.")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("Ren est vraiment le meilleur !", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("Q-quoi ?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Je recule de quelques pas, confus. Que lui est-il arrivé pendant les minutes où j'étais parti ?")
	await novel_interface.show_text_only("Sonya s'assied paresseusement sur la marche en marbre et lisse ses cheveux.")
	novel_interface.show_character("ren_fishnet","awkward")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","smile",0.25)
	await novel_interface.show_dialog("Elgana te l'a dit, hein ?", "Soya")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Votre corps... juste... qu'est-ce qui vous est arrivé ?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Je ne voulais pas que tu le saches.", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Sonya se détourne, la voix diminuant de volume.")
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("Tous ceux qui connaissent mon secret finissent par s'éloigner de moi...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Je ne peux m'empêcher de rappeler la façon dont Elgana a parlé à Sonya il y a quelque temps.")
	await novel_interface.show_text_only("Elle sait que Sonya ne vivra pas longtemps et a probablement pensé qu’il valait mieux rester à l’écart. Cela ferait moins mal lorsque l’inévitable se produirait, n’est-ce pas ?")
	await novel_interface.show_text_only("En plus, Elgana est religieuse. La jeune fille, interdite d’accès aux édifices sacrés, pourrait lui paraître de mauvais augure.")
	await novel_interface.show_text_only("La carte d'identité représentant son titre de Judgment Knight, au lieu de lui accorder la plus haute immunité, agit en fait comme une sorte d'ordre d'exil...")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Mais ça va. Je sais que tu ne seras pas comme eux...", "Soya")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("N'est-ce pas ?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("» demande prudemment Sonya, les yeux rivés sur moi. Mes lèvres tremblent un peu et je m'approche pour lui caresser la tête.")
	await novel_interface.show_text_only("Sonya sourit, ferme les yeux et donne un coup de coude dans ma paume.")
	await novel_interface.show_text_only("Elle s'étire ensuite et lève les yeux vers la fresque murale située au sommet de l'église, toujours aussi glorieuse sous le ciel nocturne.")
	await novel_interface.show_dialog("Il me déteste probablement maintenant...", "Soya")
	await novel_interface.show_dialog("Même si je suppose qu'il ne m'a jamais aimé de toute façon.", "Soya")
	await novel_interface.show_text_only("Je suis sur le point de lui demander qui il est, quand Sonya jette un coup d'œil à ma robe et sourit.")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("Eh bien, vous avez beaucoup de secrets, n'est-ce pas ?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("Quoi ?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elle m’entoure de ses bras avant que je puisse réagir.")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Tu sais pourquoi je n'ai pas demandé à Mariru ton identité il y a quelque temps ?", "Soya")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("C'est parce que je veux découvrir moi-même la réponse à cette énigme fascinante !", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("Hé!", "Lian")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("D-ne—", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mon téléphone sonne tout d'un coup. Béatrice. Sonya est toujours enroulée autour de moi alors même que je réponds à l'appel.")
	await novel_interface.show_text_only("Je dois tenir le téléphone d'une main et pousser Sonya de l'autre dans une vaine tentative de garder ses mains loin de moi. Ma paume se pose sur son nez et sa bouche.")
	await novel_interface.show_dialog("Mmmff ! Mmff !", "Soya")
	await novel_interface.show_dialog("Ren ? Je suis à l'hôpital.", "Béatrice")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("Béatrice ! Comment va Jean ?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya se lève d'un bond et arrache mon téléphone et l'allume en mode diffusion.")
	await novel_interface.show_dialog("Ils l'ont accroché à une machine... il faut lui injecter des liquides. Sa vie n'est pas en danger. Il dort en ce moment, ils lui ont injecté des analgésiques.", "Béatrice")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("... Oh, alors il ressent de la douleur ?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ouais. L’infirmière dit qu’il s’agissait d’une perte temporaire de la capacité de ressentir la douleur. Elle le sait parce qu’il est le quatrième patient ce soir à se trouver dans une telle situation.", "Béatrice")
	await novel_interface.show_dialog("Il y avait un homme d’âge moyen qui marchait pieds nus sur le capot moteur brûlant d’une voiture lors d’une émeute sur Electronics Street pour avoir une meilleure vue.", "Béatrice")
	await novel_interface.show_dialog("Les gens autour de lui sentaient quelque chose de brûlé et il ne s'en rendit compte qu'à ce moment-là. Ce qui était bizarre, c'est que ses cheveux étaient brûlés aussi...", "Béatrice")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("(Peut-être que c'est le même gars qu'Elluka a choqué ?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Un autre patient était un journaliste de Newmoridas. Elle s’est frayée un chemin vers les manifestants pour constater qu’elle ne pouvait pas appuyer sur le déclencheur. Il s'est avéré qu'elle s'est cassé un doigt en cours de route.", "Béatrice")
	await novel_interface.show_dialog("Il y avait aussi un réparateur du Hovering Palace. Alors qu'il travaillait, il a reçu un choc électrique et il a commencé à avoir une hémorragie interne. Pourtant, il n’en avait aucune idée ! J'ai continué à discuter avec son collègue au téléphone pendant une demi-heure...", "Béatrice")
	await novel_interface.show_dialog("Il n'a réalisé que quelque chose n'allait pas lorsqu'il ne pouvait plus voir dans un de ses yeux car il était injecté de sang.", "Béatrice")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("…", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Je sens un frisson parcourir ma colonne vertébrale.")
	await novel_interface.show_text_only("Quatre personnes complètement déconnectées. Différents âges, sexes, nationalités, carrières. Pourtant, ils montrent des signes du même trouble, et très rare.")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Mariru a dit que les émeutes de ce soir pourraient avoir quelque chose à voir avec la substance H...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Peut-être.", "Béatrice")
	await novel_interface.show_dialog("Aya a déjà piraté les données de surveillance des soldats de la sécurité. Vous disposez également d'un accès temporaire sur votre téléphone, n'est-ce pas ?", "Béatrice")
	await novel_interface.show_dialog("En retraçant les activités de ces quatre personnes, nous avons constaté qu’elles se sont toutes rendues dans au moins une des sept zones d’émeutes cet après-midi.", "Béatrice")
	await novel_interface.show_dialog("Ce réparateur était en fait le responsable de l’inspection de sécurité de Johnson Heavy Industries !", "Béatrice")
	await novel_interface.show_dialog("Il a parlé à un homme en coupe-vent pendant cinq minutes vers six heures du soir, au carrefour près de Electronics Street.", "Béatrice")
	await novel_interface.show_dialog("Cet homme semblait avoir délibérément évité toutes les zones équipées de caméras de surveillance. Mais on a quand même eu son visage quand il est passé dans une ruelle...", "Béatrice")
	await novel_interface.show_text_only("Béatrice commence à parler plus lentement, en mettant l'accent sur chaque mot.")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("C’est l’homme qui nous a attaqués au Sky Hotel.", "Béatrice")
	novel_interface.show_background("res://assets/images/bg/Soya/Monitor_Y.png")
	await novel_interface.show_text_only("Elle m'envoie la capture d'écran qu'elle a reçue.")
	await novel_interface.show_dialog("Jacob ?", "Lian")
	await novel_interface.show_text_only("Jacob Schmidt... spécialiste de l'armement au Congrès uni, représentant de Masada Ford, la Troisième Ville Académie.")
	await novel_interface.show_text_only("Ce type qui traitait Elluka comme une arme et un simple outil...")
	await novel_interface.show_text_only("Ensuite, il a dirigé un groupe de laquais pour m'attaquer, moi, Béatrice, Annie et Raphilia, au Sky Hotel. J'ai même utilisé des armes de substance H.")
	await novel_interface.show_text_only("Annie a été grièvement blessée par l'une de leurs armes électriques. Heureusement que Raphilia était là...")
	await novel_interface.show_text_only("Même Mariru n’a pas pu trouver de données sur cet homme. Nous ne pouvions que déduire qu'il travaillait pour Menorah, l'agence de renseignement de la Troisième Cité Académie.")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("Attendez, Johnson Heavy Industries... vous voulez dire la sous-station Johnson ?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("C'est là qu'Annie et moi avons rencontré Elluka et Igor pour la première fois. Nous n’en serions pas sortis vivants sans l’aide opportune de Mariru.")
	await novel_interface.show_dialog("J’ai un peu interrogé le réparateur, mais tout ce qu’il savait, c’est qu’Igor était le représentant d’un des collaborateurs de leur entreprise.", "Béatrice")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("Pourquoi Johnson collaborerait-il avec Igor... ?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Le Congrès uni a décidé il y a seulement deux semaines de moderniser entièrement le système de surveillance de la ville avant le début du Forum pour la paix.", "Béatrice")
	await novel_interface.show_dialog("La plupart des caméras étaient déjà en place, mais l’alimentation électrique pour l’éclairage était assurée de manière indépendante et il n’y avait pas assez de temps pour étendre la couverture du circuit à la plupart des pâtés de maisons.", "Béatrice")
	await novel_interface.show_dialog("Ils ont donc dû demander à un collaborateur de leur fournir des batteries à titre temporaire.", "Béatrice")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("Des piles ?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("You know, a transparent vessel the size of a thumb. Électrodes aux deux extrémités. Liquide collant brillant à l'intérieur. J'ai entendu dire que les dispositifs de surveillance pouvaient fonctionner pendant vingt jours.", "Béatrice")
	await novel_interface.show_dialog("J'ai déjà envoyé un échantillon au siège.", "Béatrice")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("Cela ressemble à la « nourriture » qu’Elluka m’a offerte lors de notre première rencontre…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elle voulait me remercier pour le chocolat... je suppose que ce n'était pas censé être comestible !")
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("Hé, cet Igor dont tu parles... est-ce ce type que tu possédais entièrement ?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("» demande Sonya, les yeux écarquillés comme un enfant curieux.")
	await novel_interface.show_dialog("Ren...", "Béatrice")
	await novel_interface.show_dialog("Vous êtes plutôt « proches », mais il semble que vous lui ayez un peu trop parlé, n'est-ce pas ?", "Béatrice")
	await novel_interface.show_text_only("Pas question ! Nous ne sommes pas « proches » !")
	await novel_interface.show_dialog("N'as-tu pas peur que Mariru te punisse ?", "Béatrice")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("Je n'ai pas fui...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Mmph...mmmm !", "Lian")
	await novel_interface.show_text_only("Sonya pose une main sur mon visage et lève le téléphone dans une main.")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("Ren m'a tout dit, en fait !", "Soya")
	await novel_interface.show_dialog("Êtes-vous vraiment la même beauté dans le chef-d’œuvre de Dante ?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("En nous entendant nous battre, Béatrice éclate de rire.")
	novel_interface.change_background("res://assets/images/bg/Soya/University_Hospital.png")
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("Vous êtes également au courant ? Je suppose que Mariru a alors permis à Ren de vous le dire.", "Béatrice")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Et alors ? Es-tu?", "Soya")
	await novel_interface.show_text_only("Sonya persiste, comme un gros chien qui remue la queue.")
	novel_interface.show_character("beatrice_regular","smile3")
	await novel_interface.show_dialog("Oui. Je suis bien la Béatrice dont vous parlez. Mon père était Folco Portinari.", "Béatrice")#文字错误
	novel_interface.change_expression("smile2")
	await novel_interface.show_dialog("En fait, je n'ai vu Dante qu'une seule fois. C'était lors d'une réunion de famille le 1er mai. Mais j’étais très jeune à l’époque. Encore plus jeune qu’Elluka.", "Béatrice")
	novel_interface.change_expression("grieved")
	await novel_interface.show_dialog("J'ai découvert seulement plus tard que j'avais bu ce verre de poison pendant plus d'une douzaine d'années, lorsqu'il avait écrit la Divine Comédie.", "Béatrice")
	await novel_interface.show_dialog("C’était simplement une attirance unilatérale de sa part.", "Béatrice")
	novel_interface.change_expression("smile2")
	await novel_interface.show_dialog("Pourtant, je dois admettre que ses œuvres sont impressionnantes.", "Béatrice")
	await novel_interface.show_dialog("Il a osé se moquer du pape dans son travail et m'a même décrit l'attendant aux portes du paradis et le guidant à travers les niveaux de l'enfer.", "Béatrice")
	novel_interface.change_expression("smile1")
	await novel_interface.show_dialog("C'était probablement pour lui la réalisation d'un souhait. Peut-être aussi une sorte de vengeance.", "Béatrice")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Une vengeance ?", "Lian")
	novel_interface.show_character("beatrice_regular","smile2")
	await novel_interface.show_dialog("Eh bien, ce secret est à moi et je le garde.", "Béatrice")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Béatrice regarde le ciel étoilé.")
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("Le saviez-vous...", "Béatrice")
	await novel_interface.show_dialog("L’un des astéroïdes qui tournent autour du système solaire porte mon nom. Le découvreur s’est inspiré de mon image dans l’œuvre de Dante.", "Béatrice")
	await novel_interface.show_dialog("Si seulement je pouvais écrire ma propre réponse à son poème...", "Béatrice")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_text_only("Béatrice raccroche finalement après avoir dit qu'elle allait appeler Mariru.")
	await novel_interface.show_text_only("Sonya s'assoit au bord de la fontaine et continue de jouer avec mon téléphone, ignorant mes demandes de le rendre.")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("Tch... tu as même verrouillé ton album photo ? C'est comme admettre qu'il y a quelque chose d'incriminant à l'intérieur...", "Soya")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_fishnet","stare",0.25)
	await novel_interface.show_dialog("Au moins, c'est mieux que de vivre ça...", "Lian")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Quoi qu'il en soit, vérifions d'abord les images de surveillance. Espionner les gens avec des drones est vraiment une excellente idée !", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Tu ferais mieux de ne rien faire de pareil !")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Euh—", "Soya")
	await novel_interface.show_dialog("Où suis-je…", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Je me rapproche pour voir les images de surveillance en temps réel du drone que nous avons postées devant le Congrès uni sur la Première Avenue.")
	novel_interface.change_background("res://assets/images/bg/Soya/Cordon.png")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("Les forces de sécurité ont établi une ligne de défense stricte devant le bâtiment.")
	await novel_interface.show_text_only("De chaque côté de la longue rangée de boucliers anti-émeutes, la tension entre les soldats armés et les manifestants agités est palpable.")
	await novel_interface.show_text_only("Plusieurs manifestants continuent de tenter de s'enfoncer dans le mur de boucliers, tandis que certains lancent des objets à distance sur les soldats.")
	await novel_interface.show_text_only("Cela inclut un cocktail Molotov de fabrication grossière, qui atterrit au-delà de la ligne de défense, créant un arc d’une beauté étrange dans les airs.")
	await novel_interface.show_text_only("Plusieurs soldats se précipitent pour éteindre l'incendie avec des extincteurs, tandis que les blessés sont traînés à l'arrière pour être soignés. Ils semblent être assez expérimentés pour gérer des choses comme celle-ci.")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("soya_uniform","wordless")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_fishnet","upset",0.25)
	await novel_interface.show_dialog("On dirait que c'est le bordel là-bas...", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Si cette chose était tombée dans la foule des manifestants...")
	await novel_interface.show_text_only("Sonya ne semble pas gênée par mes inquiétudes. Elle passe simplement à un autre écran, affichant des images d’un autre drone, et lance un regard renfrogné.")
	await novel_interface.show_text_only("Elle commence ensuite à comparer les images de différents drones et à marquer les emplacements correspondants sur une grande carte.")
	await novel_interface.show_text_only("Les sept zones où des émeutes ont eu lieu forment un hexagramme parfait, six des points étant les pointes pointues de l'étoile et le reste constituant le centre.")
	novel_interface.show_character("soya_uniform","trance")
	await novel_interface.show_dialog("Est-ce...", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("Tu as trouvé quelque chose ?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Ren, je dois me rendre à cet endroit tout de suite.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elle désigne un endroit au milieu de la Première Avenue, le visage solennel.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Ne vous inquiétez pas, je ne vais pas me précipiter dans la foule ou quoi que ce soit. Tu peux faire ce que tu veux tant que tu n’es pas à plus de 200 mètres de moi.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Qu'est-ce que tu comptes faire au juste...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("Oh, je dois y retourner pour quelque chose. Attends-moi ici !", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Avant que je puisse terminer ma question, Sonya a remis ses chaussures et a couru vers sa chambre.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("…")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	await novel_interface.show_text_only("Elle réapparaît avec un sac noir en bandoulière. Ce qu'il y a à l'intérieur semble assez encombrant.")
	await novel_interface.show_text_only("Elle me prend la main comme si c’était la chose la plus naturelle qui soit et nous dirige vers le SUV noir qui nous attend à l’entrée.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Vers la Première Avenue.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Mais est-ce que les gens ne manifestent pas là-bas ?", "Chauffeur")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Nous pouvons simplement contourner la foule. Je vais montrer le chemin.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("Il n’est même pas encore minuit, mais les routes sont étonnamment claires. Le conducteur dodu fait un petit tut.")
	await novel_interface.show_dialog("La circulation est généralement folle sur cette route, mais elle est vraiment fluide aujourd'hui. Je suppose que la plupart des gens qui savent ce qui est bon pour eux sont déjà rentrés chez eux.", "Chauffeur")
	await novel_interface.show_text_only("Je suppose que cela signifie que nous sommes ceux qui ne savent pas ce qui est bon pour eux-mêmes !")
	novel_interface.show_background("res://assets/images/bg/Soya/Parade.png")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("J'essaie de contacter Mariru et Béatrice dans la voiture, mais personne ne décroche.")
	await novel_interface.show_text_only("En dix minutes, nous arrivons sur une route plus petite à l’est de la partie médiane de la Première Avenue.")
	await novel_interface.show_text_only("Le chauffeur nous annonce qu’il nous y attendra et nous prévient même « deux demoiselles » de faire attention la nuit.")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("Haha... ha...", "Lian")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("(Donc, des âmes innocentes et bien intentionnées comme celle-ci existent aussi dans le SID, hein ?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("De l’autre côté de la rue, nous voyons des hordes de manifestants brandissant des banderoles et scandant des slogans en désordre.")
	await novel_interface.show_text_only("La Première Avenue est remplie de monde, de monde et encore de monde. Les foules semblent avancer, vers un point d’arrivée qu’elles n’atteindront jamais.")
	novel_interface.show_character("ren_fishnet","speechless")
	await novel_interface.show_dialog("S'ils continuent ainsi, lorsqu'ils atteindront le bâtiment du congrès, les dix mille personnes devant eux seront probablement écrasées...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Ne trouvez-vous pas que ces gens agissent un peu bizarrement ?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("J’ai vu de nombreuses manifestations à New Opulentia, mais aucune d’une ampleur aussi impressionnante. Même pas proche.")
	await novel_interface.show_text_only("Contrairement à l'atmosphère tendue qui règne sur la ligne de défense, la foule autour de nous semble moins violente. Certains scandent fort, c’est vrai…")
	await novel_interface.show_text_only("Mais beaucoup d’autres semblent être simplement là pour profiter de l’ambiance. Certains prennent même des selfies sous des panneaux publicitaires clignotants, café et malbouffe à la main.")
	await novel_interface.show_text_only("Je regarde un homme d'âge moyen, après avoir posé pour la caméra, mettre un filtre et partager la photo sur son compte de réseau social.")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("Ils ont l'air... plutôt cool ?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Il n’y a pas de soldats de sécurité dans les parages. Ils sont probablement trop occupés à s’occuper de ceux qui les attendent pour s’occuper de ces civils pacifiques.")
	novel_interface.show_character("ren_fishnet","stare")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","wordless",0.25)
	await novel_interface.show_dialog("En fait, les manifestations à grande échelle se déroulent généralement ainsi. Il y en aurait des violents et des pacifiques. Mais ne trouvez-vous pas que la frontière entre ces deux sections est un peu trop nette ?", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Ce n’est qu’à ce moment-là que je réalise que les gens semblent réellement adhérer à certaines « frontières ». En fait, la majeure partie de la foule est rassemblée en face de nous, même s’il y a suffisamment d’espace pour qu’ils se tiennent à nos côtés.")
	novel_interface.show_character("ren_fishnet","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("soya_uniform","wordless",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Est-ce ce qu'on appelle un comportement grégaire ?", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Se fondre dans la foule pour se sentir en sécurité... comme les pingouins qui ont tendance à voyager en groupe. Il est naturel que des « frontières » se forment dans de telles situations.")
	novel_interface.show_character("ren_fishnet","speechless")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light(0)
	novel_interface.show_2nd_character("soya_uniform","wordless",0.25)
	novel_interface.character_2nd_dark(0)
	await novel_interface.show_dialog("Pourtant, qu’as-tu dit que tu voulais faire ici de toute façon ?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speechless")
	await novel_interface.show_dialog("Eh, montons d’abord.", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Sonya m'entraîne dans un immeuble de bureaux au bord de la route. Elle assomme les agents de sécurité avec une aisance experte, lui arrache la carte d'entrée qu'il porte autour du cou et la scanne dans l'ascenseur. Cela nous emmène directement sur le toit.")
	novel_interface.change_background("res://assets/images/bg/Soya/First_Avenue.png")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	novel_interface.show_character("ren_fishnet","serious")
	await novel_interface.show_dialog("Wow, ça fait beaucoup de monde !", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("De notre point d’observation, je ne vois que trop clairement à quel point il y a du monde là-bas.")
	await novel_interface.show_text_only("De mon point de vue, elles ne sont pas plus grosses que des fourmis, mais même les fourmis ne seraient pas si serrées les unes contre les autres, n’est-ce pas ?")
	await novel_interface.show_text_only("Sonya sort une paire de petites jumelles de son sac et scrute la foule en dessous.")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Hum, pas là-bas...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elle saisit mon téléphone et recommence à basculer entre les images de surveillance.")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Pas là non plus...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elle finit par s'asseoir et pousse un soupir, comme soulagée.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Alors c'est juste une coïncidence, hein...", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("Allez, qu'est-ce que tu cherches exactement ?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Une porte...", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("Porte ?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya continue de contempler la mer de gens en silence, ignorant ma question.")
	await novel_interface.show_text_only("Je décide de ne pas la harceler davantage puisque de toute façon, tout semble bien jusqu'à présent. Au lieu de cela, je m'assois à côté d'elle et me laisse profiter de la vue.")
	await novel_interface.show_text_only("D’une certaine manière, tout semble si trivial quand nous sommes si haut.")
	await novel_interface.show_dialog("Il doit y avoir plus de dix mille personnes là-bas...", "Soya")
	await novel_interface.show_dialog("Probablement...", "Lian")
	await novel_interface.show_dialog("Quand vous les regardez ainsi, avez-vous l’impression d’en faire partie ?", "Soya")
	await novel_interface.show_text_only("Doucement, je secoue la tête.")
	await novel_interface.show_text_only("Les foules tentaculaires semblent être devenues une toute nouvelle forme de vie en soi : un être vivant et respirant qui se déplace comme le font les humains qui le composent.")
	await novel_interface.show_text_only("Cela me donne la chair de poule. Je ne voudrais certainement pas en faire partie.")
	await novel_interface.show_dialog("Hé...", "Soya")
	await novel_interface.show_dialog("Hum ?", "Lian")
	await novel_interface.show_dialog("J'ai vu ce documentaire quand j'étais petite, à l'abbaye.", "Soya")
	await novel_interface.show_dialog("L'action se déroulait au pôle Sud. Tout y est blanc. Aucun repère pour référence.", "Soya")
	await novel_interface.show_dialog("La seule façon pour les manchots de déterminer leur direction est leur instinct. Et ils doivent migrer en masse deux fois par an pour se reproduire.", "Soya")
	await novel_interface.show_dialog("Les manchots nouveau-nés doivent apprendre à suivre leur groupe immédiatement après leur naissance, afin qu’ils puissent atteindre l’océan où se trouve la nourriture.", "Soya")
	await novel_interface.show_dialog("Parfois, plus de deux cent mille manchots se déplacent en même temps sur la banquise du pôle Sud. Leur cortège est ordonné, tout le monde va dans la même direction.", "Soya")
	novel_interface.change_background("res://assets/images/bg/Soya/Penguin.png")
	await novel_interface.show_dialog("Mais chaque année, pour une raison quelconque, certains manchots nouveau-nés veulent prendre un autre chemin.", "Soya")
	await novel_interface.show_dialog("Même si les manchots adultes tentent de les corriger, même s’ils sont totalement seuls, même s’il y a une tempête de neige, ils insistent pour s’éloigner de l’océan.", "Soya")
	await novel_interface.show_dialog("Mais le pôle Sud est un continent inhabité et isolé. L’environnement n’y est jamais bienveillant envers ces bébés pingouins.", "Soya")
	await novel_interface.show_dialog("Cependant, si le climat change, change radicalement pour la première fois depuis un million d'années, peut-être que les bébés manchots qui iront dans l'autre sens seront les seuls survivants.", "Soya")
	await novel_interface.show_dialog("— D’une certaine manière, c’est une sorte de mécanisme d’assurance pour l’espèce. Ils peuvent sauver leur espèce de l’instinct.", "Soya")
	novel_interface.change_background("res://assets/images/bg/Soya/First_Avenue.png")
	await novel_interface.show_text_only("Sonya se tait après avoir fini de raconter ce qu'elle a vu.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Quand j'étais petite, j'ai toujours pensé... qu'il devait y avoir des tonnes de choses fascinantes dans le monde qui n'attendaient que que je les découvre.", "Soya")
	await novel_interface.show_dialog("Et je veux tous les voir, tous les expérimenter.", "Soya")
	novel_interface.change_expression("wordless")
	await novel_interface.show_dialog("Mais la curiosité a un prix…", "Soya")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Les symptômes que Béatrice vient de décrire, et les emplacements des sept zones où il y a eu des émeutes... ils me rappellent tous deux cette mission d'il y a trois ans...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Je déglutis de surprise. Donc elle a déjà rencontré des symptômes comme celui-là ?")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Il y a eu à cette époque une énorme calamité quelque part en Amérique du Sud. Si énorme que cela aurait probablement conduit à une apocalypse de classe XK.", "Soya")
	await novel_interface.show_dialog("Le premier groupe de moines en robe noire envoyés par le CDF a tous péri. Les autres moines furent horrifiés et refusèrent de partir.", "Soya")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Mais je me suis porté volontaire. J'étais ce bébé pingouin...", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","serious")
	await novel_interface.show_dialog("Que s'est-il passé exactement là-bas ?", "Lian")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/BlackGate.png")
	await novel_interface.show_dialog("Une paire de portes d’un noir pur est apparue de nulle part sur les murs d’une petite église. Et derrière les portes entrouvertes, il n'y a rien d'autre qu'une lumière dorée, brillante et aveuglante...", "Soya")
	await novel_interface.show_dialog("Dans un rayon de trois kilomètres avec le portail comme point central, tous les appareils électroniques ont cessé de fonctionner. Personne qui est entré dans la zone n’en est sorti vivant.", "Soya")
	await novel_interface.show_dialog("C'était tout ce que nous savions à l'époque.", "Soya")
	await novel_interface.show_dialog("Selon le Pape, c’était comme si les portes nacrées du Ciel s’étaient ouvertes.", "Soya")
	novel_interface.change_background("res://assets/images/bg/Soya/First_Avenue.png")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Et ma mission était de refermer les portes.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Je remarque à peine que je retiens mon souffle pendant que Sonya raconte son histoire.")
	novel_interface.show_character("soya_uniform","speechless")
	await novel_interface.show_dialog("Le paradis, comme ils l'appelaient. Ha.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elle secoue la tête en reniflant.")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Je suis arrivé à découvrir que, avec l'église comme point central, s'étendant dans six directions symétriques, se trouvaient six « lignes » sur lesquelles reposaient des dizaines de milliers de corps tordus.", "Soya")
	await novel_interface.show_dialog("Hommes, femmes, personnes âgées ou jeunes, ces gens sont tous morts à force de se battre. Cela se voyait à leurs blessures.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("(Cela ressemble à quelque chose que feraient ces sorcières contaminées...)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("Je suppose que si l'enfer existe... c'était tout.", "Soya")
	await novel_interface.show_dialog("La seule raison pour laquelle je suis arrivé vivant à la porte était probablement parce que j’étais le seul dans le coin. Personne pour se battre.", "Soya")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/BlackGate.png")
	await novel_interface.show_dialog("Je n’ai pas trouvé la lumière trop vive quand j’étais là, devant cette porte. C'était... chaleureux, relaxant. Comme s'il voulait me sucer de l'intérieur.", "Soya")
	await novel_interface.show_dialog("Je pouvais sentir une sorte d’esprit – avec une présence impossible à ignorer – essayant de me convaincre d’ouvrir grand le portail, ou simplement d’entrer par le portail.", "Soya")
	await novel_interface.show_dialog("Cela ne l’a pas dit avec des mots, mais c’est ce que j’ai ressenti.", "Soya")
	await novel_interface.show_dialog("Si j’entrais par la porte, je ne ferais plus qu’un avec la lumière dorée.", "Soya")
	await novel_interface.show_dialog("Si j’ouvrais grand la porte, tout le monde ne ferait plus qu’un avec la lumière dorée.", "Soya")
	novel_interface.change_background("res://assets/images/bg/Soya/First_Avenue.png")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Malheureusement, je n’étais pas du tout intéressé à « ne faire qu’un » avec quoi que ce soit…", "Soya")
	await novel_interface.show_dialog("Alors j’ai simplement fermé la porte pendant que l’esprit me criait des injures.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("Hahahaha...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("À la seconde où nos regards se croisent, nous éclatons de rire.")
	await novel_interface.show_text_only("Là-bas, d’innombrables personnes défilent. Et nous voilà, sur le toit à plus de trois cents pieds au-dessus d'eux, à rire aux éclats.")
	await novel_interface.show_dialog("Pouah—", "Soya")
	await novel_interface.show_text_only("Sonya inspire profondément, essayant de se calmer. Elle avait tellement ri qu'elle était pratiquement en larmes.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Après avoir fermé le portail, tout a disparu. Il ne restait plus que le mur nu.", "Soya")
	await novel_interface.show_dialog("Après cet incident, le Congrès Uni a commencé à soutenir notre Église.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("C’est pour ça que l’église s’en sortait à peine mais qu’elle peut désormais construire de gigantesques édifices religieux, hein ?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Pourtant, j'ai dû toucher la surface noire pure de la porte pour la fermer.", "Soya")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Et les substances noires ont progressivement envahi mon corps. Je suppose que c'est le prix que je dois payer...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya baisse les yeux, un peu mélancolique.")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Sonya.", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Je pose mes mains sur ses épaules fragiles et la regarde profondément dans les yeux.")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Les petits manchots qui vont dans la direction opposée le font de leur propre gré, et non à cause d'une sorte de mécanisme d'assurance pour la survie de l'espèce.", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Ils sont vraiment curieux de savoir ce qu’il y a de l’autre côté.", "Lian")
	await novel_interface.show_dialog("Certains de nos ancêtres ressemblaient aussi à ces pingouins. Suivant leurs propres désirs, ils partirent d’Afrique et finirent par peupler le monde entier.", "Lian")
	await novel_interface.show_dialog("Les humains sont partout désormais. Dans les endroits les plus froids et les plus chauds du monde, dans des endroits sombres la moitié de l’année et lumineux l’autre moitié, même de l’autre côté de la mer !", "Lian")
	await novel_interface.show_dialog("Vous n’êtes pas une sorte de mécanisme. Vous êtes...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("Je suis... ?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Euh.", "Lian")#文字错误
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","wordless",0.25)
	await novel_interface.show_dialog("Hum ?", "Soya")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Euh...", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Aaaaaaah !")
	await novel_interface.show_text_only("Pourquoi n'arrive-t-il pas à trouver les bons mots ?")
	novel_interface.show_character("ren_fishnet","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("soya_uniform","jest",0.25)
	await novel_interface.show_dialog("Hein ?", "Soya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Sonya me donne un coup de coude dans le ventre.")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("N'étiez-vous pas éloquent il y a quelques secondes ?", "Soya")
	await novel_interface.hide_character()
	
	print("=== 天启篇第16话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
