# apocalypse_ep07.gd - 天启篇第07话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第07话剧本
	apocalypse_ep07_script()

func play_script():
	pass

# 天启篇第07话 - 正式剧本
func apocalypse_ep07_script():
	# scene1 - 继续美术馆对话
	novel_interface.show_background("res://assets/images/bg/Soya/Galleries.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("Der Sprecher von Masada Ford hat Selbstmord begangen? Aber das ist unmöglich!", "Raphael")
	await novel_interface.show_dialog("Er sah auf der Pressekonferenz so selbstgefällig aus... anstatt eine Kugel zu essen, ist es viel wahrscheinlicher, mit Champagner zu feiern. Hätte ihn nicht jemand anders erschießen können?", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("Nun, Menorahs Spezialdienstteam scheint ein fähiger Haufen zu sein …", "Theresa")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Aber nicht fähig genug, sich in die Suite einzuschleichen, auf das Ziel zu schießen und es wie Selbstmord aussehen zu lassen.", "Theresa")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("Oder wurde er vielleicht erpresst?", "Raphael")
	await novel_interface.show_dialog("Oder vielleicht war er einfach eine Schachfigur, die die Leute dort oben nicht mehr brauchten ...", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","smile")
	await novel_interface.show_dialog("Na gut, na gut, lasst uns das Rätselraten auf später verschieben. Komm jetzt mit.", "Theresa")
	await novel_interface.show_dialog("Die First Avenue – dort befindet sich das Hauptquartier des Vereinigten Kongresses – wird bereits von Demonstranten überschwemmt. Die Situation wird bald außer Kontrolle geraten.", "Theresa")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("Außerdem, hast du es deinem Großvater nicht schon versprochen?", "Theresa")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Theresa klopft Raphilia auf den Rücken und flüstert ihr etwas ins Ohr.")
	novel_interface.show_character("ren_fishnet","normal2")
	await novel_interface.show_dialog("(Theresa sieht nicht europäisch aus...)\n(Und sie trägt einfach so ein Katana in einem Einkaufsviertel? Es ist fast so, als würde sie es zur Schau stellen ...)", "Lian")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("(Es stimmt allerdings, dass Waffen dieser Art in diesem Gebiet nicht verboten sind ...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Nachdem sie ihre kleine Flüstersitzung beendet haben, nickt Raphilia Theresa zu und bedeutet allen, gemeinsam nach unten zu gehen.")
	
	# scene2 - 夜晚电器街
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("Wir verlassen die Kunstgalerie und kommen auf die Straße.")
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("Die Sonne ist gerade erst untergegangen. Die Straßenlaternen sind bereits an und erhellen die geschäftige Elektronikstraße mit ihrem warmen, gelben Schein.")#不确定
	novel_interface.show_character("iluka_uniform","speechless")
	await novel_interface.show_dialog("Wow...", "Elluka")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Das sind viele Leute...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("Findet hier irgendeine Veranstaltung statt?", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("servent")
	await novel_interface.show_dialog("Ich habe gerade online nachgeschaut. Es scheint, dass viele Geschäfte aufgrund der jüngsten Verkehrsbeschränkung vorübergehend schließen mussten ...", "Gefolge")
	await novel_interface.show_dialog("Aber die Beschränkung wurde gestern Abend aufgehoben und die für nächsten Montag geplante große Wiedereröffnungsveranstaltung wurde ebenfalls auf heute verschoben.", "Gefolge")
	await novel_interface.show_dialog("Teilnehmer der Veranstaltung erhalten kostenlose limitierte Merchandise-Artikel von einigen Animes.", "Gefolge")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("C-könnte es sein...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mir fällt auf, dass viele Fußgänger eine kleine gelbe Fahne mit der Aufschrift „Eingeschränkter Zugang“ in der Hand halten. Es ist ein Gegenstand, der heutzutage oft in einem der angesagtesten Animes zu sehen ist.")
	await novel_interface.show_text_only("Dieser Anime bestand aus bezaubernden Mädchen in Kindergartenuniformen, die mit kleinen Fähnchen in der Hand hart arbeiteten. Viele Zuschauer waren der schieren Niedlichkeit verfallen – auch ich.")
	novel_interface.show_character("ren_fishnet","smile")
	await novel_interface.show_dialog("(Oh, es ist aus dieser Show!)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich kann nicht anders, als ein bisschen aufgeregt zu sein.")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("Hmm?", "Raphael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("(Äh, nichts, nichts ...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich verstecke schnell meine Aufregung. Ich bin inzwischen so ziemlich ein Profi darin.")
	novel_interface.show_character("raphael","normal2")
	await novel_interface.show_dialog("Ich muss gehen. Ihr solltet auch besser gehen.", "Raphael")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Es fühlt sich an, als würde heute Abend etwas Verrücktes passieren.", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphilia stopft mir einen grünen Edelstein in der Größe einer Murmel in die Hand.")
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("Henriette hat das gemacht. Es könnte nützlich sein, wenn jemand verletzt wird.", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphilia weicht meinem Blick resolut aus und sieht sehr verlegen aus.")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Oh... Henriette, huh...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Es ist schon eine Weile her, seit ich das letzte Mal von diesem Alchemisten gehört habe, der darauf bestand, mich „Meister“ zu nennen.")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("(Ich frage mich, was sie denken würde, wenn sie wüsste, dass ich jetzt derjenige bin, der andere im Dienstmädchen-Outfit Meister nennen muss ...)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","worry")
	await novel_interface.show_dialog("Wie auch immer, seien Sie vorsichtig.", "Raphael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Bevor ich überhaupt antworten kann, verschwindet Raphilia zusammen mit Theresa und ihrem Gefolge.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Ich sehe zu, wie sie in der Menschenmenge auf der Electronics Street verschwinden.")
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("Hm, sie umarmt immer noch das Buch, mit dem sie mir gerade auf den Kopf geschlagen hat ...", "Soya")#换行问题
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Kein Wunder, dass sie es so eilig hat zu gehen!")
	novel_interface.show_character("ren_fishnet","smile")
	await novel_interface.show_dialog("Hey, was wäre, wenn wir uns auch dieses Event ansehen, bevor wir zurückfahren?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich würde auch gerne meine eigene kleine gelbe Flagge bekommen. Doch bevor ich meinen Satz beenden kann, knallt Sonya mich gegen eine Wand.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Es hat dir doch Spaß gemacht, oder? Du denkst, es macht total Spaß, mich mit dem Fußkettchen zu schocken, oder?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("Oh nein...\nS-tut mir leid!", "Lian")
	# removed legacy empty placeholder comment
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mir ist klar, dass ich meine Wachsamkeit vielleicht zu früh aufgegeben habe.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Ich frage mich seit heute Nachmittag...", "Soya")
	await novel_interface.show_dialog("…", "Lian")
	await novel_interface.show_dialog("Theresa, Raphilia und Elluka...", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("(Die drei? Was haben sie gemeinsam?)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Ihre Auren riechen wie Hexen, haben aber menschenähnliche Farben.", "Soya")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("Das habe ich nicht erwartet.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya streckt ihren Zeige- und Mittelfinger fest über mein Herz. Ihre Augen sind stählern, kalt, entschlossen. Eines ist klar:")
	await novel_interface.show_text_only("Wenn ich lüge, sterbe ich.")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("Du meinst... Theresa ist auch eine dieser Leute?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Einer dieser Leute?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich behalte Sonyas Gesicht im Auge, während ich versuche, die richtigen Worte zu finden.")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("Zum Beispiel Mädchen, die die „Informationen“ über Magie erhalten haben, aber immer noch bei Verstand sind.", "Lian")
	await novel_interface.show_dialog("Einige von ihnen sind nicht in der Lage, die Last des Wissens zu ertragen, verlieren ihren Verstand und werden so zu den Hexen, die man töten möchte.", "Lian")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("Es gibt einen Unterschied zwischen den beiden.", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya hält ihren Blick auf meinen gerichtet, während sie spricht:")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Wer also seinen Verstand verliert, kann sich davon erholen?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Theoretisch nein. Zumindest hat Aya das gesagt...", "Lian")
	await novel_interface.hide_character()
	
	# scene3 - 回忆场景
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("<Vor ein paar Wochen>")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Hospital_Passage.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("Harima Tech ist mit dem Scannen unserer Hexenexemplare fertig. Sie haben etwas Interessantes gefunden ...", "Ai")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","bored")
	await novel_interface.show_dialog("Exemplare? Sie meinen die, die das Militär „für einen hohen Preis“ in den nördlichen Hügeln erbeutet hat?", "Lian")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("(Zum Glück bin ich nur für Anomalien zuständig, die von Aegis abgedeckt werden ...)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("Nun, es hat einige Zeit gedauert, Bindungen herzustellen, um sie an Ort und Stelle zu halten ...\nIch werde Sie jedenfalls nicht mit den Details langweilen. Ich gehe gleich auf die Ergebnisse ein, die wir gefunden haben.", "Ai")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Erstens wird der Körper einer Hexe vom Gehirn kontrolliert. Es berücksichtigt jedoch nicht die eigenen physikalischen Grenzen.", "Ai")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Hypnosis.png")
	await novel_interface.show_dialog("Normalerweise würde ein Mensch seinem eigenen Körper zum Selbstschutz eine Art unbewusste Grenze setzen. Diese Grenze kann durch Hypnose und ähnliche Methoden vorübergehend aufgehoben werden.", "Ai")
	await novel_interface.show_dialog("Beispielsweise kann eine hypnotisierte Person still liegen wie auf einem steifen Brett, wobei nur Kopf und Füße von einem Gestell gestützt werden, während es in der Mitte nichts gibt, das sie stützt.", "Ai")
	await novel_interface.show_dialog("Und sie werden nicht einmal mit der Wimper zucken, wenn ihnen mehr als 20 Pfund Gewicht auf den Bauch gelegt werden. Ein Mensch bei vollem Bewusstsein wäre dazu nicht in der Lage.", "Ai")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Hospital_Passage.png")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("Das Gehirn einer Hexe behandelt den Körper als Verbrauchsmaterial. Aus diesem Grund können sie sich in ungewöhnlich starken Schüben bewegen, aber das kann natürlich ihren Körper schädigen.", "Ai")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("(Deshalb können sie ihre Gelenke auf gruselige Weise verdrehen, nicht wahr ...)", "Lian")#换行问题
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("Zweitens empfängt das Gehirn einer Hexe weiterhin Informationen von einer unbekannten Quelle, selbst in einer Umgebung, die durch elektromagnetische Wellen blockiert ist. Die Geschwindigkeit, mit der sie die Informationen erhalten, nimmt von Sekunde zu Sekunde zu.", "Ai")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("Es ist wie eine Festplatte, auf der Daten eingegeben und dann immer wieder gelöscht werden. Theoretisch wird die maximale Bandbreite durch die Geschwindigkeit bestimmt, mit der Informationen in ihre Gehirnzellen eingegeben und dann gelöscht werden.", "Ai")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("Dies stellt jedoch eine enorme Belastung für die Zellen dar, die dadurch absterben. Die verbleibenden Zellen müssen eine noch größere Belastung aushalten und sterben daher noch schneller ab.", "Ai")
	await novel_interface.show_dialog("Der Rest ihres Bewusstseins würde sich einfach wie ein Tropfen im Ozean auflösen.", "Ai")#换行问题
	await novel_interface.show_dialog("Alles in allem haben Hexen ihre Grenzen – der menschliche Körper kann schließlich nur eine begrenzte Menge aushalten. Ihre magischen Kräfte werden durch ihren physischen Körper und ihr Gehirn eingeschränkt.", "Ai")
	await novel_interface.show_dialog("Wir können sagen, dass der Körper und das Gehirn einer Hexe lediglich Batterien sind, die dazu bestimmt sind, geleert zu werden.", "Ai")
	await novel_interface.show_dialog("Und die Leistungsgrenze dieser Batterien wird durch die höchste Entladungsstufe bestimmt, die sie im Kurzschlusszustand ertragen können.", "Ai")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich weiß, dass Aya die vollständigen Profile dieser „Hexen“ gelesen hatte, als sie noch lebten. Sie muss auch verschiedene Wege ausprobiert haben, um sie wieder zu Bewusstsein zu bringen.")
	await novel_interface.show_text_only("Sie beschrieb sie, als wären sie Objekte ohne Persönlichkeit, aber es war wahrscheinlich ihre Art, mir zu sagen, dass es in Ordnung ist, im Kampf gegen sie alles zu geben, und dass ich mich deswegen nicht schuldig fühlen muss.")
	await novel_interface.show_text_only("Die menschliche Vernunft ist wie ein Damm – so robust er auch aussieht, in dem Moment, in dem er bricht, kann es nur ein Ergebnis geben.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Und Sonyas Aufgabe ist es, den Schaden zu minimieren, sobald der Damm bricht.")
	await novel_interface.show_text_only("Es dürfte nicht leicht für sie gewesen sein.")
	
	# scene4 - 回到现在
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("Sonya lässt mich langsam los, erleichtert, nachdem sie meine Antwort gehört hat.")
	await novel_interface.show_dialog("... Ist das so?", "Soya")
	await novel_interface.show_text_only("Ihre Stimme ist leise und zitternd.")
	await novel_interface.show_dialog("Weißt du was...? Als Theresa Sie anwies, mit Ihrem Arm „einen unsichtbaren Pfeil abzufeuern“ ...", "Soya")
	await novel_interface.show_dialog("Ich dachte, du würdest mich auf jeden Fall umbringen ...", "Soya")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("Was?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Als sie deinen Körper berührte und du anfingst, dich „aufzuladen“, konnte ich spüren, wie die Auren von euch beiden an Kraft zunahmen, mindestens um das Zehnfache, nein, um das Hundertfache des Originals.", "Soya")
	await novel_interface.show_dialog("Jeder wäre von einer solchen Macht verschlungen worden.", "Soya")
	await novel_interface.show_dialog("Aber ich sah, wie diese purpurrote Aura, die so mächtig war, dass sie das ganze Gebäude durchdrang, direkt durch mich hindurch schoss. Und trotzdem war ich überhaupt nicht verletzt...", "Soya")
	await novel_interface.show_text_only("Als Sonya ihren Kopf hebt, um mich anzusehen, sehe ich, dass sie rosa anläuft.")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("– Ich habe noch nie in meinem Leben etwas so Schönes wie diese Aura gesehen!", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("(...Was ist das für eine Reaktion?)", "Lian")
	await novel_interface.hide_character()

	print("=== 天启篇第07话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
