# apocalypse_ep07.gd - 天启篇第07话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第07话剧本
	apocalypse_ep07_script()

func play_script():
	pass

# 天启篇第07话 - 正式剧本
func apocalypse_ep07_script():
	# scene1 - 继续美术馆对话
	novel_interface.show_background("res://assets/images/bg/Soya/Galleries.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("Спикер Масады Форд покончил жизнь самоубийством? Но это невозможно!", "Рафаэль")
	await novel_interface.show_dialog("Он выглядел таким самодовольным на пресс-конференции... вместо того, чтобы съесть пулю, гораздо вероятнее отпраздновать это событие шампанским. Неужели кто-то другой не мог его застрелить?", "Рафаэль")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("Что ж, команда спецслужб Меноры выглядит весьма способной командой...", "Тереза")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Но он недостаточно способен проникнуть в номер, выстрелить в цель и представить это как самоубийство.", "Тереза")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("А может, его шантажировали?", "Рафаэль")
	await novel_interface.show_dialog("Или, возможно, он был просто шахматной фигурой, которая людям там наверху больше не была нужна...", "Рафаэль")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","smile")
	await novel_interface.show_dialog("Ладно-ладно, оставим догадки на потом. Пойдем сейчас.", "Тереза")
	await novel_interface.show_dialog("Первая авеню, где находится штаб-квартира Объединенного Конгресса, уже затоплена протестующими. Ситуация скоро выйдет из-под контроля.", "Тереза")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("Кроме того, разве ты уже не обещал дедушке?", "Тереза")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Тереза похлопывает Рафилию по спине и что-то шепчет ей на ухо.")
	novel_interface.show_character("ren_fishnet","normal2")
	await novel_interface.show_dialog("(Тереза не выглядит европейкой...)\n(И катану несет в торговом районе, вот так? Почти как будто выставляет ее напоказ...)", "Лиан")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("(Хотя правда, что оружие такого типа в этой зоне не запрещено...)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("После того, как они заканчивают свой небольшой разговор шепотом, Рафилия кивает Терезе и жестом предлагает всем вместе спуститься вниз.")
	
	# scene2 - 夜晚电器街
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("Мы покидаем художественную галерею и выходим на улицу.")
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("Солнце едва зашло. Уличные фонари уже горят, освещая шумную улицу Электроники своим теплым желтым светом.")#不确定
	novel_interface.show_character("iluka_uniform","speechless")
	await novel_interface.show_dialog("Ого...", "Эллука")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Это много людей...", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("Здесь происходит какое-то событие?", "Рафаэль")
	await novel_interface.hide_character()
	novel_interface.show_character("servent")
	await novel_interface.show_dialog("Я только что проверил онлайн. Похоже, многим магазинам пришлось временно закрыться из-за недавнего ограничения движения...", "Антураж")
	await novel_interface.show_dialog("Но вчера вечером ограничение было снято, и грандиозное мероприятие по открытию, запланированное на следующий понедельник, тоже перенесено на сегодня.", "Антураж")
	await novel_interface.show_dialog("Участники мероприятия получат бесплатный ограниченный мерч из некоторых аниме.", "Антураж")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("К-может быть...", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я заметил, что многие пешеходы держат маленький желтый флажок с надписью «Доступ ограничен». Этот предмет часто можно увидеть в одном из самых популярных аниме в наши дни.")
	await novel_interface.show_text_only("Это аниме состояло из очаровательных девочек в форме детского сада, усердно работающих с флажками в руках. Многие зрители влюбились в эту явную привлекательность, включая меня.")
	novel_interface.show_character("ren_fishnet","smile")
	await novel_interface.show_dialog("(О, это из того сериала!)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я не могу не волноваться.")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("Хм?", "Рафаэль")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("(Э-э, ничего, ничего...)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я быстро скрываю свое волнение. Теперь я в значительной степени профессионал в этом.")
	novel_interface.show_character("raphael","normal2")
	await novel_interface.show_dialog("Я должен идти. Ребята, вам тоже лучше уйти.", "Рафаэль")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Такое ощущение, что сегодня вечером произойдет что-то безумное.", "Рафаэль")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Рафилия сует мне в руку зеленый драгоценный камень размером с мрамор.")
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("Генриетта сделала это. Это может пригодиться, если кто-то пострадает.", "Рафаэль")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Рафилия решительно избегает моего взгляда, выглядя очень смущенной.")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Ох... Генриетта, да...", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Прошло много времени с тех пор, как я в последний раз слышал об этом алхимике, который настаивал на том, чтобы называть меня «Мастером».")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("(Интересно, что бы она подумала, если бы узнала, что теперь именно мне приходится называть других Мастером в костюме горничной...)", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","worry")
	await novel_interface.show_dialog("В любом случае, берегите себя.", "Рафаэль")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Прежде чем я успеваю ответить, Рафилия исчезает вместе с Терезой и ее свитой.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Я наблюдаю, как они исчезают в толпе на улице Электроники.")
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("Хм, она все еще обнимает ту книгу, которой только что ударила меня по голове...", "Соя")#换行问题
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Неудивительно, что она так торопится уйти!")
	novel_interface.show_character("ren_fishnet","smile")
	await novel_interface.show_dialog("Эй, а что, если мы тоже проверим это событие, прежде чем отправиться обратно?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я бы тоже хотел получить свой собственный маленький желтый флаг. Но прежде чем я успеваю закончить предложение, Соня швыряет меня о стену.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Тебе это нравилось, да? Думаешь, шокировать меня браслетом - это очень весело, да?", "Соя")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("О, нет...\nП-прости!", "Лиан")
	# removed legacy empty placeholder comment
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я понимаю, что, возможно, слишком рано ослабил бдительность.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Я задавался вопросом с сегодняшнего дня...", "Соя")
	await novel_interface.show_dialog("…", "Лиан")
	await novel_interface.show_dialog("Тереза, Рафилия и Эллука...", "Соя")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("(Они трое? Что у них общего?)", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Их ауры пахнут ведьмами, но имеют человеческие цвета.", "Соя")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("Это не то, чего я ожидал.", "Соя")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Соня сильно тычет указательным и средним пальцами мне в сердце. Ее глаза стальные, холодные и решительные. Ясно одно:")
	await novel_interface.show_text_only("Если я солгу, я умру.")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("Ты имеешь в виду... Тереза тоже одна из таких людей?", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Один из тех людей?", "Соя")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я не спускаю глаз с лица Сони, пытаясь подобрать нужные слова.")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("Мол, девушки, получившие «информацию» магии, но еще в здравом уме.", "Лиан")
	await novel_interface.show_dialog("Некоторые из них не могут нести бремя знаний и теряют рассудок, становясь тем самым теми ведьмами, которых хочется убить.", "Лиан")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("Между ними есть разница.", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Соня, не спуская с меня глаз, говорит:")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Итак, те, кто потерял рассудок... смогут ли они выздороветь?", "Соя")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Теоретически нет. По крайней мере, так сказала Ая...", "Лиан")
	await novel_interface.hide_character()
	
	# scene3 - 回忆场景
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("<Несколько недель назад>")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Hospital_Passage.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("Компания Harima Tech завершила сканирование наших образцов ведьм. Они нашли что-то интересное...", "Ай")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","bored")
	await novel_interface.show_dialog("Образцы? Вы имеете в виду тех, кого военные захватили с северных холмов «за огромную цену»?", "Лиан")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("(К счастью, я отвечаю только за аномалии, находящиеся под прикрытием Aegis...)", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("Ну, создание привязок, чтобы удерживать их на месте, заняло некоторое время...\nВ любом случае, не буду утомлять вас подробностями. Я перейду сразу к результатам, которые мы нашли.", "Ай")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Во-первых, телом ведьмы управляет мозг. Однако он не учитывает свои собственные физические ограничения.", "Ай")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Hypnosis.png")
	await novel_interface.show_dialog("Обычно человек устанавливает своего рода подсознательный предел для своего тела в целях самозащиты. Этот предел можно временно отменить с помощью гипноза и подобных методов.", "Ай")
	await novel_interface.show_dialog("Например, загипнотизированный человек может лежать неподвижно, как жесткая доска, и только его голова и ноги поддерживаются стойкой, в то время как посередине его ничего не поддерживает.", "Ай")
	await novel_interface.show_dialog("И они даже не вздрагивают, когда на их живот ложится более двадцати фунтов веса. Полностью сознательный человек не смог бы этого сделать.", "Ай")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Hospital_Passage.png")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("Мозг ведьмы относится к телу как к расходному материалу. Поэтому они могут двигаться аномально мощными рывками, но это, конечно, может повредить их тела.", "Ай")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("(Так вот почему они могут так жутко выкручивать суставы, а...)", "Лиан")#换行问题
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("Во-вторых, мозг ведьмы продолжает получать информацию из неизвестного источника, даже в среде, заблокированной электромагнитными волнами. Скорость, с которой они получают информацию, растет с каждой секундой.", "Ай")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("Это как жесткий диск, на который данные вводятся, а затем снова и снова удаляются. Теоретически максимальная пропускная способность определяется скоростью, с которой информация вводится, а затем удаляется из клеток мозга.", "Ай")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("Но это оказывает огромную нагрузку на клетки, которые в результате погибают. Оставшимся клеткам придется принять на себя еще большую нагрузку, поэтому они погибнут еще быстрее.", "Ай")
	await novel_interface.show_dialog("То, что останется от их сознания, просто рассеется, как капля в океане.", "Ай")#换行问题
	await novel_interface.show_dialog("В общем, у ведьм есть пределы — в конце концов, человеческое тело может выдержать не так много. Их магические силы ограничены их физическим телом и мозгом.", "Ай")
	await novel_interface.show_dialog("Мы можем сказать, что тело и мозг ведьмы — это просто батарейки, которые должны быть разряжены.", "Ай")
	await novel_interface.show_dialog("А предел производительности этих батарей определяется максимальным уровнем разряда, который они могут выдержать в состоянии короткого замыкания.", "Ай")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("…", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я знаю, что Ая прочитала полные анкеты этих «ведьм», когда они были еще живы. Должно быть, она тоже пробовала разные способы вернуть их в сознание.")
	await novel_interface.show_text_only("Она описывала их так, как будто они были объектами без индивидуальности, но, вероятно, это был ее способ сказать мне, что можно выкладываться по полной, сражаясь с ними, и мне не нужно чувствовать себя виноватым из-за этого.")
	await novel_interface.show_text_only("Человеческий разум подобен плотине: какой бы прочной она ни выглядела, в тот момент, когда она прорвется, исход может быть только один.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("А задача Сони — минимизировать ущерб, как только дамба прорвется.")
	await novel_interface.show_text_only("Должно быть, ей было нелегко.")
	
	# scene4 - 回到现在
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("Соня с облегчением медленно отпускает меня из рук, услышав мой ответ.")
	await novel_interface.show_dialog("... Так ли это?", "Соя")
	await novel_interface.show_text_only("Голос у нее тихий, дрожащий.")
	await novel_interface.show_dialog("Знаешь что...? Когда Тереза посоветовала вам «выпустить невидимую стрелу» из вашей руки…", "Соя")
	await novel_interface.show_dialog("Я думал, ты меня точно убьешь...", "Соя")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("Что?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Когда она коснулась твоего тела, и ты начал «заряжаться», я почувствовал, как ауры вас обоих увеличиваются в силе, по крайней мере, в десять… нет, в сотни раз по сравнению с оригиналом.", "Соя")
	await novel_interface.show_dialog("Любой был бы сожран такой силой.", "Соя")
	await novel_interface.show_dialog("Но я видел, как эта малиновая аура, такая мощная, что пронизала все здание, пронзила меня насквозь. И тем не менее, мне совсем не было больно...", "Соя")
	await novel_interface.show_text_only("Когда Соня поднимает голову ко мне, я вижу, что она покраснела.")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("—Я никогда в жизни не видел ничего прекраснее этой ауры!", "Соя")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("(... Что это за реакция?)", "Лиан")
	await novel_interface.hide_character()

	print("=== 天启篇第07话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
