# apocalypse_ep14.gd - 天启篇第14话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第14话剧本
	apocalypse_ep14_script()

func play_script():
	pass

# 天启篇第14话 - 正式剧本
func apocalypse_ep14_script():
	# 开场设置
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("Je regarde la voiture qui ramène Elluka au siège du SID rouler et disparaître au bout de la route. Mon cerveau est encore rempli d'images du type inconscient et de tout ce sang...")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("John devrait aller bien, non ?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya répond en regardant l'éclat de verre ensanglanté dans sa main :")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Cela a touché certains de ses muscles mais n’a touché aucune artère majeure. Il devrait aller bien s'ils le soignent à temps.", "Soya")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("C’est quand même fou comme il a marché plus de vingt minutes avec ce genre de blessure. N’importe quelle personne normale se serait probablement déjà évanouie.", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("... Peut-être qu'il a CIPA ou quelque chose comme ça ?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("C’est un trouble que je me souviens avoir vu à la télévision. De nombreux personnages l'ont dans les animes et les drames.")
	await novel_interface.show_text_only("Ils ne ressentent pas la douleur, donc même l’appendicite peut les tuer. Ils ne remarqueront peut-être même pas que quelque chose ne va pas jusqu’à ce qu’il y ait un trou dans l’estomac ou quelque chose du genre.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Il devrait probablement encore avoir des sens tactiles dans ce cas.", "Soya")
	await novel_interface.show_dialog("Il aurait dû au moins pouvoir sentir toute cette tache de sang figé sur son pantalon. Pourtant, il ne semblait pas l’avoir remarqué du tout. Il est vraiment...", "Soya")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("Fascinant !", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("Quoi ?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("On devrait aller le voir à l'hôpital. Voyez quel type de stimuli suscitera une réaction de sa part.", "Soya")
	await novel_interface.show_dialog("Ou peut-être qu'il était trop concentré sur Ren pour remarquer la douleur ?", "Soya")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("Dans ce cas, nous devons également utiliser Ren dans le cadre de l’expérience. Je dois l'emprunter à cette femelle gorille...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Alors que Sonya continue de parler, ma poitrine vibre de nulle part.")
	await novel_interface.show_dialog("Qui appelais-tu une femelle gorille, hein ?", "Mariru")
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("M-Mariru ?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya fouette ses cheveux avec horreur mais ne voit Mariru nulle part. Il n’y a que moi, une main sur ma poitrine bourdonnante.")
	await novel_interface.show_dialog("Je te manque encore, Ren ?", "Mariru")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("Tu ne peux pas m'appeler sur mon téléphone ?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","laugh",0.25)
	await novel_interface.show_dialog("Waouh...", "Soya")
	await novel_interface.show_text_only("Découvrant enfin la source de la voix, Sonya rebondit vers moi, les yeux brillants de curiosité.")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Elle bondit vers mes seins, un peu comme un golden retriever avec la queue qui remue…")
	await novel_interface.show_text_only("De sa cheville, un arc lumineux apparaît soudain. Sonya s'écrase contre le sol.")
	await novel_interface.show_text_only("Son bras droit et sa jambe droite ont des spasmes à deux reprises, et elle parvient à se relever, à moitié paralysée.")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("(Elle semble se remettre plus rapidement des chocs électriques maintenant... ?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Les yeux pleins de larmes, la jeune fille se redresse en frottant son bras gauche douloureux et lève la tête vers le ciel dans une plainte silencieuse.")
	novel_interface.show_character("soya_uniform","cry")
	await novel_interface.show_dialog("Bon sang, tu peux même contrôler cette chose à distance ?", "Soya")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/UAV.png")
	await novel_interface.show_text_only("Je suis le regard de Sonya et repère un petit point rouge planant dans les airs.")
	await novel_interface.show_dialog("Un drone ?", "Lian")
	await novel_interface.show_dialog("Les drones ne sont-ils pas interdits dans cette zone ?", "Lian")
	await novel_interface.show_text_only("Les interdictions n’ont jamais entravé le SID, bien sûr, mais Mariru n’a-t-elle pas dit elle-même il y a quelques jours que nous devions pécher par excès de prudence lors du Forum international de la paix ?")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("ren_fishnet","uneasy")
	await novel_interface.show_dialog("(Eh bien, je suppose qu’attaquer des flics, faire des évasions de prison et déclencher des émeutes ne comptent pas non plus comme une erreur de prudence...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("La situation est particulière aujourd’hui. Il y a déjà plus de cinquante mille personnes rassemblées sur la Première Avenue, marchant pour on ne sait quoi.", "Mariru")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("Autant ?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Il y a déjà eu des émeutes dans sept zones. Le quartier général des soldats de la sécurité est actuellement en désordre.", "Mariru")
	await novel_interface.show_dialog("J'ai dit à leur commandant que s'ils ne réagissaient pas à ces émeutes de manière appropriée, New Opulentia pourrait être en difficulté...", "Mariru")
	await novel_interface.show_dialog("Et je lui ai un peu mis la pression en élevant sa famille. Le pauvre type a accepté de permettre au SID de contourner immédiatement certaines restrictions.", "Mariru")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("(« Un peu » sous pression ?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ils ont vraiment tout mis en œuvre pour le Forum cette année. Nous avons même rééquipé tous les lampadaires de la zone démilitarisée agréée avec de nouveaux modèles.", "Mariru")
	await novel_interface.show_dialog("Chaque lampadaire fait désormais office de caméra de surveillance. J'ai également installé les réseaux et les unités correspondants.", "Mariru")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Ce n’est pas un plan très intelligent. Il y a sûrement des endroits sans lampadaires. Sinon, pourquoi devriez-vous utiliser des drones, n'est-ce pas ?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("» dit Sonya d'un ton moqueur, mais Mariru fredonne simplement en signe d'accord.")
	await novel_interface.show_dialog("Ouais, ce n'est pas du tout un plan intelligent. Cela coûte cher et ne donne pas beaucoup de résultats. En outre, il existe également un énorme facteur de risque politique…", "Mariru")
	await novel_interface.show_dialog("Si les médias découvrent qu’il y a des caméras de surveillance partout, ils évoqueront certainement des romans dystopiques classiques. George Orwell et des trucs comme ça. Le Congrès uni serait sous le feu des critiques.", "Mariru")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_dialog("Quoi qu'il en soit, j'ai découvert ce que j'avais besoin de savoir.", "Mariru")
	novel_interface.change_background("res://assets/images/bg/Soya/Club.png")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Il est désormais confirmé qu’il me suffit de mettre un peu de pression sur certaines personnes pour convaincre même les organisations les plus influentes du monde de prendre des décisions manifestement stupides.", "Mariru")
	await novel_interface.show_dialog("Maintenant, il ne reste plus qu'à savoir qui cibler...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru scanne les milliers de profils qui viennent d'être importés dans son appareil portable. Profils contenant des identités, des comptes bancaires, le montant des fonds et d’autres détails connexes.")
	await novel_interface.show_dialog("Que veux-tu dire... ?", "Lian")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("Par exemple, le Sénat est l’organisation qui détient le plus de pouvoir sur la Fédération Nouvelle Opulentia. Dans ce cas, ce que j’aimerais savoir, c’est quel est exactement le pouvoir du Sénat. Est-ce que tout le monde doit suivre ses ordres ?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Vous ne le faites pas, pour commencer...", "Lian")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("En un mot, chaque nation est composée d’un système de pouvoir à plusieurs niveaux. Le pouvoir détenu par les différentes organisations est affecté par de nombreux facteurs : l’économie, l’armée, l’histoire, les cultures, les religions et bien plus encore.", "Mariru")
	await novel_interface.show_dialog("Quant au leader d’une nation, il n’est qu’un représentant choisi pour maintenir l’équilibre dans la lutte complexe pour le pouvoir entre les différentes factions.", "Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Depuis le tout début de l’histoire, quel que soit le système politique – démocratique, dictature, république, universitaire – il n’y a jamais eu de véritable « roi » qui décide de tout.", "Mariru")
	await novel_interface.show_dialog("Tout ce qu’il y avait, c’était quelqu’un qui devait se frayer un chemin à travers d’innombrables situations conflictuelles, faire des choix impossibles pour tout le monde et assumer la responsabilité de tout ce qui n’était pas de sa faute.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru fait une pause, regardant un groupe de membres de l'équipe de récupération, qui évacuent les masses en combinaisons de protection contre les matières dangereuses.")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("Cette personne qui porte toute cette responsabilité... elle a peut-être l'air forte, mais en fait, son corps porte plus de cicatrices qu'on ne peut en compter.", "Mariru")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("…", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya reste silencieuse, une main sur sa poitrine, tandis que je la regarde, confuse.")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("Je ne suis pas sûr de comprendre...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("De toute façon, tu n’es pas censé le faire, idiot.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya se force à calmer sa respiration et demande finalement, d'un ton sérieux :")
	novel_interface.show_character("soya_uniform","speechless")
	await novel_interface.show_dialog("Je vois que vous êtes ici pour négocier, mais la dernière pièce du puzzle, la plus cruciale, manque toujours. Alors tu es prêt à me donner quelque chose en échange de mes informations, hein ?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ouais.", "Mariru")
	await novel_interface.show_text_only("Mariru répond facilement.")
	await novel_interface.show_dialog("Pour autant que je sache, les Chevaliers du Jugement sont des « moines en robe noire qui possèdent le Sceau de la Vérité ». Moins de vingt chanceux ont reçu un tel honneur au cours des cinq cents dernières années.", "Mariru")
	await novel_interface.show_dialog("Dans l’histoire, il y a eu d’innombrables moines en robe noire très talentueux.", "Mariru")
	await novel_interface.show_dialog("Pourtant, même eux n’ont pas reçu le Sceau de Vérité, symbole de la plus haute immunité dans le Royaume de Dieu. Seuls ceux dont l’Église a déterminé qu’ils ont apporté une contribution importante au monde ont ce privilège.", "Mariru")
	await novel_interface.show_dialog("Vous avez reçu le vôtre il y a deux ans. Il vous a été décerné par feu le Pape, Sa Sainteté Calliste IV.", "Mariru")
	await novel_interface.show_dialog("Vous ne pouviez pas avoir plus de douze ans à ce moment-là, n’est-ce pas ?", "Mariru")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Hm, tu en sais vraiment beaucoup.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Eh bien, je vais aller droit au but.", "Mariru")
	await novel_interface.show_dialog("Qu’avez-vous fait exactement il y a trois ans, sur la mission « épuration » du Bouclier Guyana ?", "Mariru")
	await novel_interface.show_text_only("Sonya reste silencieuse pendant quelques secondes avant de relever la tête.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Je sais ce que tu attends de moi, mais j'ai des conditions.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Bien sûr, je suis tout ouïe.", "Mariru")
	novel_interface.show_character("soya_uniform","yell")
	await novel_interface.show_dialog("Tout d’abord, désactivez ce bracelet de cheville, maintenant !", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Je ne peux pas.", "Mariru")
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("Quoi ?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("La désactivation nécessite un équipement spécial de la part du siège du SID. Je ne peux pas le faire à distance. Pour l’instant, tout ce que nous pouvons faire, c’est fixer la distance autorisée entre vous et Ren au nombre maximum, environ 650 pieds.", "Mariru")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("... Très bien, au moins ça fait mieux que trente pieds.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Le voyant jaune sur la cheville de Sonya clignote plusieurs fois.")
	await novel_interface.show_dialog("C’est fait.", "Mariru")
	await novel_interface.show_text_only("Les yeux fixés sur moi, Sonya commence à reculer prudemment, s'arrêtant tous les quelques pas, pour finalement soupirer de soulagement lorsqu'il est évident que nous sommes à plus de 200 mètres l'un de l'autre.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Eh bien, deuxièmement, je veux savoir ce qui se passe entre Béatrice et Ren. Et je veux que Ren me le dise avec ses propres mots.", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru réfléchit un moment en silence.")
	await novel_interface.show_dialog("... Très bien. Mais vous devez promettre de ne le dire à personne d’autre.", "Mariru")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("Q-quoi ? Est-ce vraiment bien de lui dire ?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Béatrice était décédée au XIIIe siècle. Selon Aya, le corps actuel de Béatrice n’avait été créé qu’au moment même où je l’avais invoquée.")#换行问题
	novel_interface.show_character("ren_fishnet","uneasy")
	await novel_interface.show_dialog("(Alors j’ai « créé » un corps tellement incroyable ? C’est surréaliste…)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Cependant, ce fait est qualifié de top secret. Même le Sénat ne peut pas le savoir.")
	await novel_interface.show_text_only("Actuellement, seules huit personnes dans le monde connaissent la vérité : moi, Annie, Béatrice elle-même, Raphilia, le Dr Dekkers, Mariru, Aya et Henrietta.")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("(Les informations que Mariru veut de Sonya doivent être incroyablement importantes...)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Je promets de ne le dire à personne.", "Soya")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("Mais n’oubliez pas : si Ren ment, je pourrai le savoir d’un coup d’œil !", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("Très bien, très bien !\nArrêtez de le frotter...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Je continue en expliquant mon expérience au Sky Hotel, où j'ai invoqué Béatrice en utilisant le collier d'émeraude de Raphilia.")
	await novel_interface.show_text_only("Avec la permission de Mariru, je lui raconte la partie de Béatrice battant Igor et sa « malédiction » également.")
	await novel_interface.show_text_only("Sonya écoute, les yeux brillants, comme un enfant qui apprécie une histoire au coucher, intervenant de temps en temps avec des halètements excités.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Alors l'émeraude sur ce collier qui appartenait à la famille de Raphilia... elle était incrustée dans l'épée de Béatrice il y a des siècles ?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Ouais. Aya l'a confirmé. C’est une experte.", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Béatrice Portinari... elle était dans l'œuvre de Dante, représentée comme une sorcière...", "Soya")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("C'est tellement fascinant!", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Hum.", "Mariru")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("D'accord, la preuve dont vous avez besoin... elle est juste en moi ! Cette fille Aya sera probablement capable de le détecter.", "Soya")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Mais je veux passer du temps avec Ren un peu plus longtemps ! Pouvons-nous retourner au SID demain au lieu de maintenant ? Je promets d'être de retour avant midi !", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Très bien...", "Mariru")
	await novel_interface.show_dialog("Oh, au fait, Ren, Aya a rassemblé toutes les images de surveillance des drones et des soldats de sécurité et les a toutes rassemblées sur une page. Vous y avez également accès, vous pouvez le vérifier sur votre téléphone.", "Mariru")
	await novel_interface.show_dialog("Nous ne savons pas encore si le chaos de ce soir est causé par la substance H. Promettez-moi que vous ferez attention.", "Mariru")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Mariru coupe alors la connexion.")
	novel_interface.change_background("res://assets/images/bg/Soya/Club.png")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("Quant à vous les gars...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elle regarde les hommes qu'elle a capturés lors de la vente aux enchères, tous ligotés, à moitié nus, la bouche bandée.")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("Préféreriez-vous mourir à cause d'une fuite de radiations...", "Mariru")
	await novel_interface.show_dialog("Ou coopérer avec moi et nous laisser effacer vos souvenirs après ça ?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Les hommes, se tordant de terreur, poussèrent des gémissements frénétiques derrière le ruban adhésif.")
	await novel_interface.show_text_only("Mariru piétine durement l'un d'eux. Sur son visage se dessine un sourire hautain et royal.")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Je le pensais.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_dialog("Héhéhé...", "Soya")
	await novel_interface.show_text_only("À la seconde où Mariru raccroche, Sonya me lance un large sourire.")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("W-what...?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("Il y a une question que je voulais poser... mais je pensais que cette femelle gorille ne vous le permettrait pas.", "Soya")
	await novel_interface.show_dialog("Puisque tu es aussi affecté par la malédiction de Béatrice, tu dois être un homme, hein ?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("Quoi ?", "Lian")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("Je... non, je suis une fille...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Comment puis-je répondre à cela ?")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("Votre aura me dit que vous ne dites pas toute la vérité...", "Soya")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("Ahh... Ren, tu es en effet le plus fascinant de tous !", "Soya")
	await novel_interface.show_dialog("Et d’ailleurs, comment fonctionnent tes seins ?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("Arrêtez ça ! S'en aller!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("J'essaie de fuir vers l'église.")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("Hé, attends... tu n'as pas contacté cette Mère Elgana pour lui dire que nous arriverions bientôt ?\nEst-ce vraiment acceptable de la faire attendre ?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_dialog("Ah, tu es Ren, n'est-ce pas ?", "Voix féminine")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N_Door.png")
	await novel_interface.show_text_only("Une voix de femme, douce et tendre.")
	novel_interface.show_character("el","smile")
	await novel_interface.show_text_only("Je suis le son et vois une religieuse debout à l'entrée de l'église, souriante avec bienveillance.")
	await novel_interface.show_text_only("Elle a l'air d'avoir la trentaine, la peau éclatante, de longs cheveux blonds tombant en cascade jusqu'à sa taille.")
	await novel_interface.show_dialog("J'avais peur que tu te sois perdu en chemin !", "Nonne")
	await novel_interface.show_dialog("Je m'appelle Elgana.", "Nonne")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("Mère Elgana...?", "Lian")
	await novel_interface.hide_character()
	
	print("=== 天启篇第14话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
