# apocalypse_ep04.gd - 天启篇第04话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第04话剧本
	apocalypse_ep04_script()

func play_script():
	pass

# 天启篇第04话 - 正式剧本
func apocalypse_ep04_script():
	 #scene1 - 继续电器街
	novel_interface.show_background("res://assets/images/bg/Soya/Akihabara.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_dialog("…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("…", "Rafael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mal consigo respirar de nervosismo enquanto observo Raphilia folhear o livro em suas mãos.")
	await novel_interface.show_text_only("Suas bochechas estão vermelhas, os dedos tremendo, como se hesitasse antes de virar cada página.")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("Olha! Lingerie para bumbuns empinados!", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya está gritando, exibindo a lingerie de renda preta para alguns transeuntes muito fascinados.")
	novel_interface.show_character("soya_uniform","laugh")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("iluka_uniform","speechless",0.25)
	await novel_interface.show_dialog("Ah! Fundo! Fundo!", "Elluka")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Elluka comemora ao lado, apesar de não ter a menor ideia do que é bottom.")
	novel_interface.show_character("servent")
	await novel_interface.show_dialog("Senhorita Ren, verifiquei todos os seus itens. Eles parecem estar intactos. Devo pedir a alguém para trazê-los para sua residência?", "Entourage")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphilia finalmente recupera os sentidos, pigarreia e enrola o livro, com o rosto sério.")
	await novel_interface.show_text_only("Então, com o livro enrolado, ela bate na cabeça de Sonya, com tanta violência que toda a rua consegue ouvir.")
	await novel_interface.show_text_only("O caçador de bruxas de cabelos grisalhos, incapaz de se abaixar a tempo, agacha-se de dor.")
	novel_interface.show_character("soya_uniform","cry")
	await novel_interface.show_dialog("P-para que foi isso?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ela chora, massageando a cabeça.")
	await novel_interface.show_text_only("Raphilia olha para ela com ar condescendente.")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("Você realmente acha que eu não sei quem você é?", "Rafael")
	await novel_interface.show_dialog("Sem Salmonton, a igreja não é nada. E temos os perfis de todos os agentes da CDF na nossa Embaixada.", "Rafael")
	await novel_interface.show_dialog("Sonya Angeles...", "Rafael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphilia está de frente para Sonya, mas apontando para mim com o dedo direito.")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("Essa lingerie que você está segurando...", "Rafael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphilia move o dedo ligeiramente para baixo, apontando para o meu peito.")
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("Isso realmente caberia nela?", "Rafael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("O quê?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ah...", "Transeunte A")
	await novel_interface.show_dialog("Bem…", "Transeunte B")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","hungry")
	await novel_interface.show_dialog("Ah...", "Elluka")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elluka assente compreensivamente, embora ainda não tenha ideia do que está acontecendo.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Felizmente alguém tem bom senso! As habilidades de detetive de Raphilia finalmente provaram ao mundo que a lingerie não me pertence.")
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_text_only("(Mas isso não melhora a situação!)")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Soya/Akihabara.png")
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("Tchau...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya suspira, como uma criança cuja pegadinha falhou.")
	await novel_interface.show_text_only("Ela se levanta lentamente, esfregando a cabeça, e anota o endereço da comitiva de Raphilia.")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Por favor, envie a sacola de itens para este endereço. Obrigado!", "Soya")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("servent","",0.25)
	await novel_interface.show_dialog("Entendido!", "Entourage")
	await novel_interface.hide_all_characters()
	
	# scene2 - 美术馆
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…")
	novel_interface.change_background("res://assets/images/bg/Soya/Galleries.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("Raphilia nos afasta das multidões ao redor para uma galeria de arte relativamente tranquila.")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("Então você fez compras com aqueles dois a tarde toda?", "Rafael")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_fishnet","wry_smile",0.25)
	await novel_interface.show_dialog("Sim, praticamente...", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Nós três já estávamos na área há algumas horas. Pegamos a sobremesa e jogamos alguns jogos de arcade, embora Sonya parecesse não achar isso divertido.")
	await novel_interface.show_text_only("Agora, a Rua da Eletrônica, por outro lado...")
	await novel_interface.show_text_only("Não posso acreditar que aquela garota de aparência inocente tem uma queda por aquelas lojas para adultos!")
	await novel_interface.show_text_only("E ela localizou todos os itens que queria imediatamente. Aposto que não foi a primeira vez dela aqui.")
	await novel_interface.hide_background()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Posso dizer quem tocou num livro apenas pelo cheiro.", "Soya")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Os livros com cheiro de rosa são os meus preferidos!", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Então ela geralmente usa suas habilidades em coisas assim?")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_text_only("Tive que ficar ali na entrada, segurando sacolas de compras com uma das mãos e cobrindo os olhos virgens e puros de Elluka com a outra.")
	novel_interface.change_expression("shy_right")
	await novel_interface.show_text_only("Os clientes que passavam ficavam olhando para minha roupa. Isso foi tão constrangedor...")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Soya/Galleries.png")
	await novel_interface.show_text_only("Raphilia suspira, como se achasse que sou uma idiota. E ela finalmente fala:")
	novel_interface.show_character("ren_fishnet","shy_right")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","normal2",0.25)
	await novel_interface.show_dialog("Então você não tem ideia do que aconteceu esta tarde?", "Rafael")
	await novel_interface.stop_music()
	novel_interface.character_light(0.35, "upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Eh? O que?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("A reunião fechada de 48 horas entre os líderes das Cidades Acadêmicas começou hoje ao meio-dia. Você sabe disso, certo?", "Rafael")
	novel_interface.character_light(0.35, "perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Acho que ouvi falar disso nas notícias...", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Desculpe, normalmente só mudo de canal quando aparecem notícias de política.")
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("Duas horas após o início da reunião fechada, o porta-voz oficial da Terceira Cidade Acadêmica, que não compareceu à reunião, fez um anúncio que abalou o mundo:", "Rafael")
	await novel_interface.show_dialog("A construção do sistema de resposta passiva da Masada Ford está concluída. O sistema já está oficialmente operando.", "Rafael")
	await novel_interface.show_dialog("O sistema é construído em um ambiente totalmente fechado, controlado por um módulo de IA offline que não está de forma alguma conectado ao mundo exterior.", "Rafael")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("Assim que começar a funcionar, ninguém será capaz de desligá-lo nos próximos vinte anos.", "Rafael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("Isso não parece nada exagerado...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("No entanto, ao contrário do que todos pensavam, não é um sistema controlado por IA que lançaria automaticamente um contra-ataque quando atacado.", "Rafael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("A expressão de Raphilia é indescritível – uma combinação de medo, raiva e até tristeza.")
	await novel_interface.show_text_only("Ela faz uma pausa, tentando se recompor.")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("Na verdade, o sistema tem apenas uma função: quando determinar que mais de 50% do centro de Masada Ford foi destruído ou danificado, a “Operação Apocalipse” será acionada imediatamente.", "Rafael")
	novel_interface.show_background("res://assets/images/bg/Soya/Doomsday1.png")
	await novel_interface.show_dialog("O sistema lançará então bombas nucleares indiscriminadamente em todas as principais cidades do mundo através da Substância H “Fantasy Army”.", "Rafael")
	await novel_interface.show_dialog("Basicamente, se Masada Ford for prejudicado, não importa quem, o mundo inteiro afundará com isso.", "Rafael")
	await novel_interface.show_dialog("É um mecanismo fundamental no firmware do sistema. Ninguém seria capaz de desligá-lo, nem mesmo os líderes nacionais.", "Rafael")
	await novel_interface.show_dialog("Se alguém tentar quebrar, desligar ou reescrever o sistema, a Operação Apocalipse será imediatamente acionada.", "Rafael")
	novel_interface.show_background("res://assets/images/bg/Soya/galleries.png",0.5)
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("Uh...", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("O que é isso...?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Embora não tenha certeza dos detalhes, já parece uma situação grave, a julgar pelas palavras-chave que peguei.")
	await novel_interface.show_text_only("“Fantasy Army” é um tipo de Substância H de nível militar usada na Terceira Cidade Acadêmica. É vital para a cidade da mesma forma que o Aegis é vital para a Nova Opulência.")
	await novel_interface.show_text_only("É um tipo espacial de Substância H que concede armas que existem em um determinado espaço várias vezes maior que seu poder de fogo original.")
	await novel_interface.show_text_only("Quando essas armas atingem o seu alvo na atmosfera, podem causar uma destruição centenas de vezes mais grave do que poderiam ter causado com o seu design original.")
	await novel_interface.show_text_only("O mundo exterior sabe muito pouco sobre os seus parâmetros exatos devido à estrita confidencialidade mantida por Masada Ford.")
	await novel_interface.show_text_only("Até o próprio nome “Exército de Fantasia” é simplesmente um codinome que se originou das palavras insultuosas de um general inimigo.")
	await novel_interface.show_text_only("Isso foi na época em que a linha de abastecimento da Península do Sinai foi cortada e Masada Ford estava em perigo. O general regozijou-se com o fato de Masada Ford ser um alvo fácil agora e a vitória da cidade ser apenas uma fantasia passageira.")
	await novel_interface.show_text_only("Não muito tempo depois, seu território foi completamente arrasado por um míssil antitanque “inimaginavelmente poderoso”...")
	await novel_interface.show_text_only("Nenhum estranho sabe a localização exata do Exército Fantasia. Há rumores de que todo o Masada Ford foi construído em torno dele.")
	await novel_interface.show_text_only("Masada Ford continuou a ser fortificada ao longo dos anos. Neste momento, é imune até mesmo a desastres naturais, como inundações, terramotos e tufões.")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("(Lembro que o Aegis deveria ser capaz de se defender até mesmo contra armas fortalecidas pelo Exército Fantasia... pelo menos é o que o público em geral pensa...)", "Lian")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("Ainda assim, o sistema é operado por IA e isso pode ser um problema...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Em todos os trabalhos de ficção científica que li, deixar a IA controlar armas nucleares nunca foi uma boa ideia.")
	await novel_interface.show_text_only("Me lembra um anime que assisti uma vez, com um homem nu e um cientista em uma cadeira de rodas, gargalhando por trás dos óculos escuros...")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("Os dados de teste completos de toda a IA relacionada estão anexados no anúncio publicado por Masada Ford. Afinal, eles são o primeiro país a aplicar a tecnologia de IA ao combate real.", "Rafael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphilia olha pela janela com uma leve carranca no rosto.")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("Não estou preocupado com o que a IA fará. O que me preocupa é o que os humanos farão.", "Rafael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("A Electronics Street parece estranhamente lotada hoje.")
	
	# scene3 - 大使馆
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("<Enquanto isso, Embaixada de Newmoridas, Zona Desmilitarizada Acordada>")
	await novel_interface.show_background("res://assets/images/bg/Soya/Embassy.png")
	await novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("Masada usou este sistema para selar o Exército Fantasia e renunciou aos direitos da cidade para ativá-lo.", "Lumbert")
	await novel_interface.show_dialog("Superficialmente, o sistema parece promover uma mentalidade de “nós morremos, todo mundo morre” –", "Lumbert")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Mas, essencialmente, é como uma espécie de declaração de paz forçada.", "Lumbert")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("O orador é um homem vestido com um terno elegante e personalizado. Ele coloca seu copo de uísque na mesa.")
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("Sim.", "Mulher com óculos")
	await novel_interface.show_dialog("Mas você já conhecia o sistema de antemão, não é?", "Mulher com óculos")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("Direto ao ponto, como sempre, entendo, Akiko.", "Lumbert")
	novel_interface.change_expression("sedation")
	await novel_interface.show_dialog("A notícia da construção do sistema não pode ser divulgada antes de ser concluído e oficialmente ativado. Caso contrário, o mundo inteiro tentaria intervir e impedir a sua construção.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("Raposa velha.", "Akiko")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Akiko levanta os óculos, o rosto inexpressivo.")
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("…", "Lumbert")
	await novel_interface.show_dialog("De qualquer forma, o que está feito está feito. O público pode reclamar, mas não há nada que possa fazer a não ser aceitá-lo.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("Raposa velha.", "Akiko")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("... Desculpe por ocultar informações de você.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("Hmph.", "Akiko")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lumbert limpa a garganta.")
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("Neste momento, o que Masada Ford pretende é manter a controvérsia negativa sob controlo e evitar sanções económicas dos países membros do Congresso Unido.", "Lumbert")
	await novel_interface.show_dialog("Há dois anos, quando a Newmoridas parou de conceder empréstimos a Masada, a cidade não teve outra escolha senão começar a roubar os recursos das áreas vizinhas.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("É como matar uma galinha pelos ovos.", "Akiko")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("Mas o Salmonton’s abriu as portas aos refugiados no ano passado. Por um lado, a população do país está a diminuir de qualquer maneira—", "Lumbert")
	await novel_interface.show_dialog("Por outro lado, é uma forma de garantir que Massada nunca se torne parte da Europa. Os refugiados podem funcionar como uma espécie de amortecedor.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("E agora, sem a galinha, quem vai botar os ovos?", "Akiko")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Akiko revira os olhos.")
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("Devido às intermináveis guerras em Massada, mais de 15% da sua população faz parte do exército ou é parente de alguém que esteja nele. Você pode imaginar a situação financeira do país.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("Então eles também estão usando a notícia desse sistema de resposta passiva como uma oportunidade para o desarmamento?", "Akiko")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("É simplesmente uma forma de economizar dinheiro. Mas eles também precisarão de uma maneira de ganhar mais dinheiro, que é—", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("Comércio de armas.", "Akiko")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Akiko imediatamente fornece. É óbvio. Armas de fogo são a única especialidade que Masada Ford tem a oferecer.")
	novel_interface.show_character("lambert","smile")
	await novel_interface.show_dialog("Ou, devo dizer – o comércio de “soluções de defesa nacional”?", "Lumbert")
	await novel_interface.show_dialog("A Resistência é conhecida como um grupo terrorista altamente perigoso que se esconde em algum lugar na periferia de Massada...", "Lumbert")
	novel_interface.change_expression("sedation")
	await novel_interface.show_dialog("Mas na verdade é a mídia de Masada que faz com que isso pareça.", "Lumbert")
	await novel_interface.show_dialog("A Resistência é na verdade uma organização obsoleta que tem problemas fundamentais tanto de gestão como de tecnologia. Os membros mal trabalham juntos. Definitivamente não é uma ameaça tão grande quanto a mídia faz parecer.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("Para vender segurança, eles precisam primeiro espalhar o medo...", "Akiko")
	await novel_interface.show_dialog("Tenho certeza de que todos os agentes de marketing de software de segurança de computador sabem disso muito bem.", "Akiko")#文本错误
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("De qualquer forma, vamos direto ao ponto. O que exatamente você quer?", "Akiko")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lumbert aponta para a fronteira entre a Ásia e a África no mapa espalhado sobre a mesa.")
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("Hum. Pensei assim.", "Akiko")
	await novel_interface.hide_character()

	print("=== 天启篇第04话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
