# apocalypse_ep15.gd - 天启篇第15话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第15话剧本
	apocalypse_ep15_script()

func play_script():
	pass

# 天启篇第15话 - 正式剧本
func apocalypse_ep15_script():
	# 开场设置
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N_Door.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("Мать!", "Соя")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Соня затихает, изображая кротость, как только видит Эльгану, и убирает свои цепкие руки от моей рубашки.")
	novel_interface.show_character("el","normal")
	await novel_interface.show_dialog("Анжелес, для тебя есть посылка. Я отправил его в твою комнату в западном крыле.", "Эльгана")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("Понял... это...", "Соя")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Тон Эльганы властный, но Соня по-прежнему тянет ответ, как и всякая девчонка.")
	await novel_interface.show_text_only("Это похоже на то, как ученица начальной школы язвительно относится к своему классному руководителю.")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("... Мать?", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("Ах, вы не привыкли к нашим названиям, да?\nПросто Эльгана в порядке.", "Эльгана")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Д-добрый день, Эльгана.", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я помню, как смотрел старый европейский фильм об аббатстве. Мать играет роль инструктора плюс общежитие РА, своего рода.")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("Я слышал, что ты вывихнул поясницу?", "Эльгана")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Да, это был несчастный случай...", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Несчастный случай, когда на меня упал ребенок, весивший более двухсот фунтов.")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("Тогда заходите. Я приготовила травы.", "Эльгана")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Эльгана улыбается мне, как любящая бабушка, совсем не так, как она только что разговаривала с Соней.")
	novel_interface.show_character("ren_fishnet","uneasy")
	await novel_interface.show_dialog("(Соня, должно быть, была настоящей нарушительницей спокойствия.)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Эльгана распахивает тяжелую дверь церкви, и я следую за ней, осматривая украшения.")
	novel_interface.show_character("ren_fishnet","happy")
	await novel_interface.show_dialog("Резьба такая сложная!", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я подхожу ближе и замечаю пять металлических гравюр квадратной формы по обе стороны от входа, каждая из которых рассказывает свою историю.")
	novel_interface.show_character("el","normal")
	await novel_interface.show_dialog("Это копии работ Гиберти. Оригиналы были уничтожены во время войны.", "Эльгана")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я слышу это намек на тоску? Должно быть, ей очень понравился этот художник.")
	novel_interface.change_background("res://assets/images/bg/Soya/Solomon.png")
	await novel_interface.show_text_only("Я, с другой стороны, ничего не знаю о художнике, но одна из резных фигурок до сих пор меня интригует.")
	await novel_interface.show_dialog("В нем рассказывается легенда о царице Савской и царе Соломоне.", "Эльгана")
	await novel_interface.show_dialog("Покойный Папа, Его Святейшество, постановил, что все вновь построенные церкви должны содержать исторические художественные элементы...", "Эльгана")
	await novel_interface.show_dialog("Возможно, это напоминание миру о том, что мы не должны позволять войнам уничтожать наши славные цивилизации...", "Эльгана")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N_Door.png")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Он показался мне хорошим человеком!", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Согласно тому, что я слышал от Мариру, именно покойный Папа даровал Соне титул Рыцаря Правосудия.")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("Эй, Соня, ты не придешь?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Девушка отстает, наблюдая, как мы входим в церковь, послушными оленьими глазами.")
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("Я не приду...", "Соя")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Она остается на месте. В теплом свете наружного освещения ее лицо кажется мирным и нежным. Такое выражение я видел только однажды на ее непослушном лице — и тогда я впервые увидел ее через двустороннее зеркало.")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("?", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("В любом случае, поправьте свою талию, и вам сразу станет лучше!\nЯ буду на заднем дворе!", "Соя")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Она убегает по коридору западного крыла.")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("(Наверное, спешит развернуть посылку...)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Решив пока игнорировать странные действия Сони, я следую за Эльганой в церковь.")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_L.png")
	novel_interface.show_character("ren_fishnet","happy")
	await novel_interface.show_dialog("Вау, это огромно!", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Интерьер украшен величественными мраморными колоннами и великолепной куполообразной крышей. Я едва могу сдержать вздох удивления, учитывая, что я впервые сама была в церкви.")
	await novel_interface.show_text_only("Под теплым желтым сиянием потолок, покрытый фресками, и цветное мозаичное стекло кажутся необыкновенно святыми и безмятежными.")
	await novel_interface.show_text_only("На заднем ряду скамьи стоит аптечка из орехового дерева, приготовленная, вероятно, специально для меня.")
	novel_interface.show_character("ren_fishnet","happy")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("el","smile",0.25)
	await novel_interface.show_dialog("Вот, позвольте мне увидеть вашу талию.", "Эльгана")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("И тут я осознаю проблему:")
	novel_interface.show_character("ren_fishnet","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("el","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("(Я в платье. Если я хочу показать кому-нибудь свою талию...)", "Лиан")
	await novel_interface.show_dialog("(Мне придется раскрыть все, что внизу!)", "Лиан")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("Это... на самом деле не так уж и важно...", "Лиан")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Травмы талии могут стать серьезными, если их не заметить. Если вы будете игнорировать их слишком долго, это проявится, когда вы станете старше!", "Эльгана")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Хм…", "Лиан")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("Будьте добры, это ни капельки не повредит!", "Эльгана")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Эльгана прижимает меня к коврику на скамейке, не принимая «нет» за ответ, как поступила бы обеспокоенная мать.")
	await novel_interface.show_text_only("Я принимаю свою судьбу и опускаюсь спиной к монахине. Именно тогда я замечаю, что моя талия действительно болит, особенно когда локти не выдерживают вес верхней части тела.")
	await novel_interface.show_text_only("Эльгана задирает мое платье, а я отчаянно пытаюсь прикрыть руками нижнее белье.")
	await novel_interface.show_dialog("Все в порядке! Узор в виде кролика на ваших трусах просто восхитителен!", "Эльгана")
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("Это... это просто мерч из игры!", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я, конечно, не планировал никому показывать свое нижнее белье, гордо демонстрируя персонажа из шутера, который часто отправляется на миссии камикадзе на механических роботах.")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("(Моя задница... такая холодная...)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Хватит извиваться! Вот это место, да?", "Эльгана")
	await novel_interface.show_text_only("Эльгана сразу находит поврежденную часть. В тот момент, когда она нажимает на него, я забываю о смущении.")
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_dialog("Аааа!", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Эльгана достает из аптечки баночку с мазью, пахнущей травами. Она обильно размазывает мазь по моей спине, нежно массируя ее пальцами.")
	await novel_interface.show_text_only("Это ощущение освежает. Моя кожа дрожит в ответ.")
	await novel_interface.show_dialog("Я почти закончил. Не двигайся!", "Эльгана")
	await novel_interface.show_text_only("Я остаюсь на месте, как послушный котенок.")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("Соня сказала, ты сам придумал лекарство?", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Я получил травы из моего родного города. Моя мама научила меня готовить его, когда я была маленькой.", "Эльгана")
	await novel_interface.show_dialog("Чувствуете себя лучше?", "Эльгана")
	await novel_interface.show_text_only("Голос у нее нежный, мягкий, как колыбельная.")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Ну…", "Лиан")
	await novel_interface.show_dialog("Вы единственный, кто заботится об этом месте?", "Лиан")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("el","smile",0.25)
	await novel_interface.show_dialog("Это должна была быть работа священника... но в последние несколько лет у нас не хватает рабочей силы, поэтому они прислали меня. Я буду здесь, пока они не найдут доступного священника.", "Эльгана")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("Но это нормально...", "Эльгана")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("В последние несколько лет было еще хуже. Мне приходилось повсюду ездить по сбору средств, чтобы аббатство продолжало работать. По крайней мере, сейчас условия намного лучше.", "Эльгана")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Голос Эльганы спокоен и умиротворен, как будто она способна с легкостью противостоять любому бедствию. Рядом с ней я чувствую себя в безопасности.")
	novel_interface.show_character("ren_fishnet","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_dark(0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("el","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Соня осталась в вашем аббатстве, когда была моложе, да?", "Лиан")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Дама вздыхает, когда я упоминаю имя Сони.")
	novel_interface.show_character("ren_fishnet","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_dark()
	novel_interface.show_2nd_character("el","normal",0.25)
	novel_interface.character_2nd_dark(0)
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Этот ребенок... когда ее впервые нашли в трущобах Потоси, ей не было и трех лет. Вся ее семья погибла на войне...", "Эльгана")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("Но она была очень умна. Очень любопытно. Самый непослушный из всех детей в аббатстве.", "Эльгана")
	await novel_interface.show_dialog("Всегда задавал странные вопросы на уроках. Она была огромной головной болью для всех учителей. Иногда мне приходилось успокаивать этих бедняжек после занятий.", "Эльгана")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Несмотря на свои жалобы, Эльгана сияет, как любящая мать.")
	novel_interface.show_character("ren_fishnet","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_dark(0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("el","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Она, кажется, немного в восторге от тебя...", "Лиан")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Эльгана некоторое время молчит и спрашивает:")
	novel_interface.show_character("ren_fishnet","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_dark()
	novel_interface.show_2nd_character("el","normal",0.25)
	novel_interface.character_2nd_dark(0)
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Рен, как ты думаешь, люди всегда будут относиться к одному и тому же опыту одинаково?", "Эльгана")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Э... нет, я думаю?", "Лиан")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("Эта дура... у нее было ненасытное любопытство. Когда она находила что-то увлекательное, ей отчаянно хотелось узнать об этом все, чего бы это ни стоило.", "Эльгана")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Я киваю в знак согласия, все еще лежа.")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("Может быть, это потому, что мир, который она видит, отличается от того, что видят нормальные люди...", "Эльгана")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Когда мир был в смятении, даже маленькие дети знали, что им нужно защитить себя, чтобы выжить. Соня же приняла неизведанное с распростертыми объятиями.", "Эльгана")
	await novel_interface.show_dialog("CDF заметил ее выдающуюся игру и тренировал ее с юных лет.", "Эльгана")
	await novel_interface.show_dialog("Но у ее любопытства была и обратная сторона. Она никогда не стеснялась пробовать опасные вещи, не беспокоясь о том, что поранится...", "Эльгана")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я не могу не заметить внезапный намек на сожаление в тоне Эльганы.")
	novel_interface.show_character("ren_fishnet","normal1")
	await novel_interface.show_dialog("С ней что-то случилось?", "Лиан")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.show_character("el","sad")
	await novel_interface.show_dialog("Несколько лет назад была эта миссия... очень опасная, но и очень важная.", "Эльгана")
	await novel_interface.show_dialog("Я не уверен в деталях, но ни один из монахов в черных одеждах не пожелал принять эту миссию. Поэтому она вызвалась...", "Эльгана")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","normal1")
	await novel_interface.show_dialog("(Это был тот инцидент, о котором упоминала Мариру...?)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Голос Эльганы дрожит.")
	novel_interface.show_character("el","sad")
	await novel_interface.show_dialog("Миссия была выполнена, но в тело Сони попало какое-то неопознанное вещество Н...", "Эльгана")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","serious")
	await novel_interface.show_dialog("Что?", "Лиан")
	await novel_interface.hide_character()
	novel_interface.show_character("el","normal")
	await novel_interface.show_dialog("Она тебе не сказала, да?", "Эльгана")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Toxin.png")
	await novel_interface.show_dialog("Это темное вещество, химические свойства которого невозможно определить. Оно постепенно разъедает ее тело, как рак...", "Эльгана")
	await novel_interface.show_dialog("Причина, по которой покойный Папа вручил ей Печать Истины в столь юном возрасте, заключалась в том, что все врачи установили, что она не доживет до совершеннолетия.", "Эльгана")
	await novel_interface.show_dialog("Наверное, не стоит его называть «Веществом Н». Это больше похоже на «злую волю»…", "Эльгана")
	await novel_interface.show_dialog("Потому что это имеет еще один побочный эффект. Если она войдет в священные здания, такие как церкви или аббатства, ей будет очень больно.", "Эльгана")
	await novel_interface.show_dialog("Она стала «ребёнком, презираемым Богом».", "Эльгана")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_L.png")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("…", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Теперь, когда я вспоминаю выражение лица Сони, когда она сказала, что не пойдет со мной, я понимаю, что она действительно выглядела немного задумчивой.")
	await novel_interface.show_text_only("Она была сиротой, которую взяло на воспитание аббатство. Для нее это, должно быть, похоже на то, как будто ее во второй раз выгнали из дома.")
	await novel_interface.show_text_only("Вот почему она сказала Мариру, что улики находятся внутри нее.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("И еще она сказала...")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("Но я хочу потусоваться с Реном еще немного!", "Соя")
	await novel_interface.show_dialog("Можем ли мы вернуться в SID завтра, а не сейчас?", "Соя")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_dialog("Идиот...!", "Лиан")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_L.png")
	await novel_interface.show_text_only("Я заставляю себя подняться со скамейки. Талия теперь меньше болит, но все еще немного пульсирует.")
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_dialog("Оу...", "Лиан")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("el","smile",0.25)
	await novel_interface.show_dialog("Не двигайся! Вы еще не полностью выздоровели...", "Эльгана")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Стиснув зубы, я переодеваюсь и бегу к боковой двери, ведущей в западное крыло.")
	await novel_interface.hide_background()
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("Тем временем Мариру звонит единственному члену Сената, которого она в настоящее время может найти по зашифрованному каналу.")
	novel_interface.show_background("res://assets/images/bg/SID/spConferenceRoom.png")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("Мариру, да? Нужно что-нибудь?\nОстальные все еще проводят закрытое собрание в своей маленькой комнатке!", "Брайт")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Судя по чавкающим звукам, доносившимся на другом конце трубки, Брайт не ожидал этого звонка.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("(Проклятая горилла...)", "Мариру")
	await novel_interface.show_dialog("Кхм... Доктор Брайт, вы ведь понимаете, что беспорядки на Первой авеню выходят из-под контроля?", "Мариру")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("Нет, все в порядке. Наемники из Ритналапа сделают свое дело.\nВ любом случае беспорядки случаются постоянно. Несколько десятков человек погибнут и все.", "Брайт")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Беспорядки не являются чем-то новым для Брайта. Был там, сделал это. Скучный.")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("Подожди... ты позвонил мне, потому что подозреваешь, что здесь замешаны «мемы»?", "Брайт")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("У нас пока нет конкретных доказательств, но у меня есть к вам несколько вопросов относительно мема «Вещество H».", "Мариру")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("О, еще нет доказательств? Тогда позвони мне позже. Мне еще нужно сходить на несколько встреч...", "Брайт")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("Доктор Брайт!", "Мариру")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Мариру никогда не ценила апатичную личность Брайта, но даже она должна признать, что он является экспертом среди экспертов, когда дело касается мемов «Вещество H».")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Мне удалось раздобыть несколько бананов Кавендиш…", "Мариру")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("Ух ты! Как ты это сделал?\nЯ думал они вымерли!", "Брайт")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Это недавно выращенные образцы из асептической теплицы Салмонтона. Я пришлю вам партию, если вы готовы ответить на мой вопрос.", "Мариру")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("Конечно, конечно! Огонь!", "Брайт")
	await novel_interface.show_dialog("Всего один вопрос, не более! Лучше сначала подумать!", "Брайт")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Как и ожидала Мариру. Она идет вперед и задает вопрос:")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Мем-вещество H воспринимается широкой публикой как «своего рода информация, вызывающая аномалии».", "Мариру")
	await novel_interface.show_dialog("Однако вы не раз публично выражали презрение к этой идее, ни разу не опубликовав статью, объясняющую почему именно.", "Мариру")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Я бы хотел, чтобы вы объяснили мне сейчас.", "Мариру")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("Ты очень хорошо умеешь раскапывать грязь! Думал, людям в вашем агентстве плевать на эти душные научные конференции...", "Брайт")
	await novel_interface.show_dialog("То, что вообще можно сказать, можно сказать ясно, а то, о чем мы не можем говорить, мы должны обойти молчанием.", "Брайт")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Цитата Людвига Витгенштейна. Ты имеешь в виду, что не можешь объяснить мне словами? Это неприемлемый ответ.", "Мариру")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("Я имел в виду, что «мемы» могут изменить самую фундаментальную основу этого мира, и на этой основе строится язык.", "Брайт")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Meme.png")
	await novel_interface.show_dialog("Вы сами должны прекрасно знать, что даже «мемы» без атрибутов Вещества H могут легко переписать наши языки, культуры и даже самые базовые знания в мире.", "Брайт")
	await novel_interface.show_dialog("То, что раньше было вирусными материалами в Интернете, в процессе распространения приобрело значения, которых у них не было вначале.", "Брайт")
	await novel_interface.show_dialog("Новые значения постепенно вытесняют первоначальные значения и становятся новым «фундаментальным пониманием».", "Брайт")
	await novel_interface.show_dialog("Мемы могут легко исказить даже способы, с помощью которых мы расшифровываем информацию. Как же тогда люди могут называть их «информацией, вызывающей аномалии»? Это слишком несправедливо!", "Брайт")#多字问题
	novel_interface.change_background("res://assets/images/bg/SID/spConferenceRoom.png")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Если это так, то почему люди просто не принимают новорожденные концепции? Разве не так изначально развивался язык?", "Мариру")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("Но физические явления, вызванные Веществом H, по своей сути по-прежнему являются физическими. В противном случае люди не смогли бы изучать их как форму науки.", "Брайт")
	await novel_interface.show_dialog("И по той же логике мем-вещество H способно выполнять концептуальные замены, которые не может выполнить обычный мем. И это касается не только человеческого мозга.", "Брайт")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Я знаю, конечно. Эгида сама по себе является мемом «Вещество H» — абсолютный барьер физической защиты, созданный компьютерными кодами.", "Мариру")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("Это внесло изменения в физические концепции, включая объем, векторы и энергию.", "Брайт")
	await novel_interface.show_dialog("Итак, скажите мне... а что, если действительно мощный мем способен переключать значения понятий «красный» и «зеленый» друг с другом?", "Брайт")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Если изменится только название, а не свойства самих цветов...\nНичего бы не изменилось...", "Мариру")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("Подожди... а что, если он поменяет значения нуля и единицы? Все компьютерные устройства мгновенно выйдут из строя.", "Мариру")
	await novel_interface.show_dialog("Это будет катастрофа мирового уровня!", "Мариру")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("Это верно. Видите ли, «информация» — это формат, в котором распространяются мемы. И, по сути, сами концепции действительно подменены!", "Брайт")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ярко вздыхает, покорно.")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("В истории были организации, которые очень старались сохранить существование вещества H в секрете. Они считали, что это единственный способ защитить слабый вид, которым были мы, люди.", "Брайт")
	await novel_interface.show_dialog("Они назвали Вещество H абсурдным существованием, которое только пошатнет рациональность и порядок, на установление которых людям понадобилось так много времени.", "Брайт")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Spy1.png")
	await novel_interface.show_dialog("Они даже создали элитный отряд, отвечающий за предотвращение распространения вещества H.", "Брайт")
	await novel_interface.show_dialog("Разве сейчас в Объединенном Конгрессе нет такого отдела? Они пригласили тебя стать председателем, да?", "Мариру")
	await novel_interface.show_dialog("Ха. Эти идиоты думали, что мем «Вещество H» проникло и изменило всего лишь три процента фундаментальных концепций нашего мира.", "Брайт")
	await novel_interface.show_dialog("Ну... каков тогда фактический процент?", "Мариру")
	await novel_interface.show_dialog("Оно захватило весь мир!", "Брайт")
	await novel_interface.show_dialog("Эти «элиты» заплатили огромную цену, чтобы наконец подсчитать реальный процент. И результаты привели к развалу всей организации…", "Брайт")#换行问题
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Мариру задерживает дыхание, дрожь пробегает по ее спине, когда Брайт делает паузу для драматического эффекта.")
	novel_interface.show_background("res://assets/images/bg/Soya/Spy2.png")
	await novel_interface.show_dialog("Мем-вещество H уже проникло в более чем две тысячи процентов мира.", "Брайт")
	await novel_interface.show_dialog("...!", "Мариру")
	await novel_interface.show_dialog("Это как бактерии. Более сильные мемы побеждают предыдущих чемпионов и переписывают их.", "Брайт")
	await novel_interface.show_dialog("Вернуть наш мир к тому, каким он был изначально, невозможно.", "Брайт")
	novel_interface.change_background("res://assets/images/bg/SID/spConferenceRoom.png")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("Свет, звук, текст, изображения, коды... все это методы распространения мема Вещества H.", "Брайт")
	await novel_interface.show_dialog("Этот отдел в Объединенном Конгрессе создан просто для галочки. Собственно, Конгресс сам использует мемы.", "Брайт")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("Что?!", "Мариру")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("Как еще, по вашему мнению, они с такой легкостью заставили весь мир принять титул «Академгород» с помощью «Проекта новой вращающейся двери»?", "Брайт")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Мариру начинает дрожать.")
	await novel_interface.show_text_only("Она... боится?\nНет. В основном просто взволнован.")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Я вижу...", "Мариру")
	await novel_interface.show_dialog("Те, кто заражен мем-веществом H, не видят никакой проблемы, даже если все их чувства резко извращены.", "Мариру")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Потому что человеческий мозг всегда пытается все о себе рационализировать. Он отказывается принять возможности, которые они не могут объяснить.", "Мариру")
	await novel_interface.show_dialog("Верно?", "Мариру")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Мариру самодовольно ухмыляется.")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("<Западное крыло Мемориальной церкви Новая Опулентия>")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N_Backyard.png")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("Этот идиот...", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Как только я выхожу из боковой двери церкви, я внезапно чувствую удушье.")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("(Побочный эффект от лекарства?)\n(Нет, это похоже на...)", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Кажется, что время остановилось на несколько секунд. Наконец, странное чувство уходит, когда мир вокруг меня мерцает и снова выравнивается.")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("Что это было?", "Лиан")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Подожди...", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Сони здесь нет. Она находится на площади перед церковью.")
	await novel_interface.show_text_only("Я понятия не имею, почему я это знаю — просто знаю.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("…")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("Ах, как я и ожидал.", "Лиан")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Я прихожу на площадь и вижу Соню, сидящую на краю фонтана и пинающую воду босыми ногами.")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Привет, Рен!", "Соя")
	await novel_interface.show_text_only("Ее шелковые чулки были отброшены. Она встает на мелководье, играя одной рукой с выбившейся прядью серебристых волос.")
	await novel_interface.show_text_only("Лицо у нее покраснело, как будто она пьяна. Она смотрит на меня в тусклом желтом свете…")
	await novel_interface.show_text_only("Мое сердце трепещет, как будто завтра не наступит.")
	await novel_interface.hide_character()
	
	print("=== 天启篇第15话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
