# apocalypse_ep11.gd - 天启篇第11话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第11话剧本
	apocalypse_ep11_script()

func play_script():
	pass

# 天启篇第11话 - 正式剧本
func apocalypse_ep11_script():
	# scene1 - 开始
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.show_character("beatrice_regular","smile2")
	await novel_interface.show_dialog("No. Questi idioti... sono tutti uomini!", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sul braccio destro di Beatrice c'è un braccialetto, realizzato in metallo verde muschio, che brilla dolcemente in una tonalità azzurra.")
	await novel_interface.show_text_only("Un'invenzione di Aya. Realizzato in una lega speciale che blocca gli effetti della sostanza meme H. Può essere utilizzato per sopprimere gli effetti della \"maledizione\" di Beatrice.")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("Aspetta, cosa hai intenzione di...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Ricordo che Mariru mi parlò un paio di settimane fa della \"maledizione\". Qualsiasi maschio che vede Beatrice si innamora immediatamente di lei.")
	# scene2 - 回忆莉琉的解释
	novel_interface.show_background("res://assets/images/bg/Soya/FusiformGyrus.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_dialog("Per essere precisi, è il suo viso a innescare l’effetto.", "Mariru")
	await novel_interface.show_dialog("Attraverso una serie di test condotti da Aya, hanno scoperto che guardare direttamente il viso di Beatrice stimola fortemente il giro fusiforme e l'amigdala nel cervello maschile.", "Mariru")
	await novel_interface.show_dialog("Tuttavia, è efficace solo se il bersaglio lo guarda direttamente in un raggio di 260 piedi. Foto, video o riflessi non hanno questo effetto.", "Mariru")
	await novel_interface.show_dialog("Dopo che questa stimolazione è in vigore per un periodo di tempo, il cervello della persona colpita subirà cambiamenti irreversibili. Ciò cambierà radicalmente il loro modo di agire.", "Mariru")
	await novel_interface.show_dialog("Diventano disperati nel voler fare di Beatrice la loro. Ma, poiché non possono, diventano ansiosi, irritabili, risentiti. Ciò può anche portare ad autolesionismo, incendio doloso o tendenze violente.", "Mariru")
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Che tristezza, eh? Amore non corrisposto...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru sospira.")
	await novel_interface.show_text_only("Apro la bocca per chiedere come esattamente Aya abbia condotto quell'orribile esperimento, ma la richiudo. È meglio che rimango ignorante.")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("(Fortunatamente non ero uno dei suoi soggetti di prova...)", "Lian")
	await novel_interface.show_dialog("…", "Lian")
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("Aspetta! Quando ieri mi hai fatto spiegare delle cose a Beatrice da sola con \"quel vestito\"...", "Lian")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("Anche quello era un esperimento di Aya?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","shock")
	await novel_interface.show_dialog("Te ne sei accorto solo adesso?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Quindi è stato?")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Hmm, allora probabilmente non ti sei ancora accorto che il braccialetto che Beatrice indossava ieri era falso, eh?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("scherza Mariru, sembrando leggermente delusa dalla mia mancanza di capacità di osservazione.")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Il motivo per cui ti ho fatto indossare quel vestito era per evitare che i tuoi pensieri soggettivi rovinassero i risultati dei nostri test. L’”imbarazzo” che provavi annullerebbe di fatto i tuoi “desideri”.", "Mariru")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("E…", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Si allunga e mi mette entrambe le mani sulle spalle. Sul suo viso c'è un sorriso sottile.")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("... Stavi molto bene vestito da coniglietta di Playboy!", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("Aaaaaaaaaa!\nNon possiamo semplicemente smettere di parlarne?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ho trascorso quell'ora infernale vestito da coniglietto di Playboy, da solo con Beatrice, in una stanza chiusa.")
	await novel_interface.show_text_only("Ero così nervoso che a malapena riuscivo a tirar fuori una frase intera. Non riuscivo nemmeno a camminare correttamente.")
	await novel_interface.show_text_only("E Beatrice ha passato l’ora a consolarmi, anche se era sul punto di scoppiare a ridere, ne sono sicuro.")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Aya ha detto che le immagini scansionate in 3D del tuo cervello erano come uno spettacolo pirotecnico. Le è davvero piaciuto, l'avrebbe lasciato andare avanti ancora per molto se la tua pressione cerebrale non fosse stata un po' alta.", "Mariru")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("Ad ogni modo, ora sappiamo che, anche se il tuo cervello reagisce alla maledizione di Beatrice proprio come quello di qualsiasi maschio normale, non rimarrà alcun trauma.", "Mariru")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("D’altra parte, altri uomini subiranno danni cerebrali permanenti dopo aver guardato per un periodo il volto di Beatrice. Il periodo varia da quaranta secondi a otto minuti.", "Mariru")
	await novel_interface.show_dialog("Quindi sei al sicuro. Non sei sollevato?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("Di certo non sono sollevato!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("…")
	await novel_interface.show_text_only("Ah, questo è un altro dei miei ricordi che vorrei poter cancellare.")
	
	# scene3 - 回到现场
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("(Quindi... se si toglie il braccialetto qui...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Beatrice mi sorride dolcemente, poi mi stringe in un abbraccio.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Tutto diventa scuro davanti a me mentre il mio viso è schiacciato contro il suo petto.")
	await novel_interface.show_dialog("Eh?", "Lian")
	await novel_interface.show_dialog("Dirò \"vai\". Dopodiché hai trenta secondi.", "Beatrice")
	await novel_interface.show_dialog("Prendi Elluka e ci divideremo e ci incontreremo a Newell Central Park. Meno manifestanti lì.", "Beatrice")
	await novel_interface.show_dialog("Capito?", "Beatrice")
	await novel_interface.show_text_only("Annuisco, facendo del mio meglio per non pensare al petto morbido del mio viso.")
	await novel_interface.show_dialog("Ehi, voglio un turno anch'io!", "Soya")
	await novel_interface.show_text_only("“Clicca”")
	await novel_interface.show_text_only("La chiusura del braccialetto si apre. La maledizione è ora in vigore.")
	# scene4 - 索娅的视角
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN1.png")
	await novel_interface.show_text_only("Agli occhi di Sonya, Electronics Street è ora un mondo rosa.")
	await novel_interface.show_text_only("Lo stesso tipo di rosa che aveva visto avvolgere certi libri dal contenuto esplicito quando facevano acquisti in libreria questo pomeriggio.")
	novel_interface.show_character("soya_uniform","shy")
	await novel_interface.show_dialog("Anche tu sei una strega?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("Ah. Puoi dirlo?", "Beatrice")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","shy")
	await novel_interface.show_dialog("Ma tu non sei come Elluka o Raphilia...", "Soya")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("Tu, come Ren, hai un'aura pura come quella di un bambino!", "Soya")
	await novel_interface.show_dialog("... Questo è affascinante!", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("esclama Sonya, scuotendomi le spalle per l'eccitazione.")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("Wahhhh!\n(Smettila! Non riesco a respirare!)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular","smile2")
	await novel_interface.show_dialog("Sembra che pesi meno di quanto ricordassi.\nNon sei carino?", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La tettona stringe Ren ancora più forte.")
	await novel_interface.show_text_only("Nel frattempo, Ren si dibatte disperatamente, cercando di sfuggire al suo abbraccio soffocante.")
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("... Comunque, chi sei?", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("Ops, ho dimenticato di presentarmi.\nSono Beatrice Portinari.", "Beatrice")
	await novel_interface.hide_character()
	
	# scene5 - 90分钟前的场景
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("<90 minuti fa>")
	novel_interface.change_background("res://assets/images/bg/Soya/Club.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_text_only("<Zona demilitarizzata concordata, New Opulentia Stork Garden Hotel>")
	await novel_interface.show_text_only("<Fuori dalla Sala del Canto degli Uccelli, la sala dei banchetti all'ultimo piano>")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Whoa, hanno un giardino quassù al 99esimo piano. Le persone a Hovering Palace si godono sempre lussi come questi?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru osserva i tetti di vetro, sorridendo a malincuore.")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Forse più il giardino è alto, più sembra lussuoso? O forse 99 è il numero fortunato del proprietario?", "Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La ragazza bionda si gratta la testa, confusa.")
	novel_interface.show_character("skuld","think")
	await novel_interface.show_dialog("Come hai fatto a decidere che quest'asta è ciò che stiamo cercando?", "Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru fissa lo sguardo sul cartellone pubblicitario verniciato a spruzzo all'ingresso della sala dei banchetti.")
	await novel_interface.show_text_only("Su di esso c'è il titolo \"Asta autunnale del Johnson's Museum\",\nseguito dal sottotitolo: dove l'arte incontra la finanza.")
	await novel_interface.show_text_only("Il testo bianco sembra particolarmente stridente sullo sfondo blu. Niente di artistico in questo.")
	novel_interface.show_character("skuld","perspire")
	await novel_interface.show_dialog("Si tratta davvero di un'asta di opere d'arte? Non mi sembra molto gradevole esteticamente.", "Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru annuisce e sorride.")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Ma tutti e cinquecento i posti sono occupati. Dei sessantatré articoli, sessanta sono già stati venduti.", "Mariru")
	await novel_interface.show_dialog("Sono stati realizzati complessivamente 1,5 miliardi.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("Così tanto? Quest'asta deve essere enorme, quindi.\nMa non ne ho sentito parlare...", "Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("I conti criptati elettronicamente di cui ci hai informato... contengono fondi per miliardi.", "Mariru")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("È molto, ma appena sufficiente per costruire due grattacieli di questo tipo.", "Mariru")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("Per utilizzare questa somma di denaro per creare un impatto sui trilioni di fondi per la ricostruzione posseduti dal Congresso Unito, dovrebbe esserci un solo modo...", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","think")
	await novel_interface.show_dialog("Corruzione? Ecco perché hanno scelto la valuta crittografata?", "Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("I conti possono essere crittografati, ma tutte le transazioni effettuate possono essere viste da tutti nella rete. E una transazione di queste dimensioni è impossibile che la gente non se ne accorga.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Ecco perché hanno bisogno di una ragione plausibile per la transazione...", "Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld inclina la testa di lato, pensando. Poi esclama:")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Oh, ecco perché tengono un'asta!", "Skuld")
	await novel_interface.show_dialog("Gli oggetti d'antiquariato senza prezzo fisso sono una buona scusa per transazioni di grande valore. Oggetti come porcellane, giade, vecchi dipinti... nessuno batterebbe ciglio se vedesse qualcuno offrire milioni per averli.", "Skuld")
	await novel_interface.show_dialog("E l'operazione si svolge anche su territorio internazionale. Rende impossibile per i dipartimenti fiscali di diverse nazioni riscuotere le tasse.", "Skuld")
	await novel_interface.show_dialog("Tutto ciò di cui hanno bisogno è contattare entrambe le parti del commercio e vendere un po’ di spazzatura sotto il nome di qualche museo privato.", "Skuld")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("Ma non possono far entrare veri intenditori d’arte, perché potranno capire a colpo d’occhio che cosa sta succedendo.", "Skuld")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("Ecco perché tutti i posti sono occupati!\nHanno riempito i posti con la loro stessa gente!", "Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru dà una pacca sulla testa di Skuld con approvazione.")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("Molto intelligente. Probabilmente ti annoi molto a scuola, eh?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("Cosa ne pensi?", "Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld sorride a Mariru, sembrando orgoglioso.")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("Lascia che ti dica un'altra cosa, allora.", "Mariru")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("I “fondi per la ricostruzione del dopoguerra” sono fondamentalmente prestiti forniti dal Congresso Unito. I governi che hanno preso in prestito da loro devono restituire il denaro, altrimenti affronteranno l’ira delle sei principali nazioni.", "Mariru")
	await novel_interface.show_dialog("Ma storicamente, nessuna nazione è mai stata in grado di rimborsare un prestito di questa entità entro la scadenza. È qui che entra in gioco lo spazio per la negoziazione.", "Mariru")
	await novel_interface.show_dialog("Il Comitato è schifosamente ricco. Tutto ciò che vogliono per sé è probabilmente il settore più redditizio, ad esempio le infrastrutture di base come l’energia e le comunicazioni.", "Mariru")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("Possono semplicemente fare una proposta ai capi di governo che hanno preso in prestito i soldi: non dovranno restituire l’importo preso in prestito finché cederanno permanentemente al Comitato il 30% delle azioni della loro rete di telecomunicazioni.", "Mariru")
	await novel_interface.show_dialog("I governi, incapaci di rimborsare i prestiti, di solito sono d’accordo. Alcuni leader nazionali potrebbero anche richiedere attivamente sconti in privato.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Allora come fa il Comitato ad ottenere il controllo sui “settori” che desidera?", "Skuld")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("Devono convincere il Congresso Unito a lasciare che le multinazionali possiedano fondi e abbiano un certo grado di autonomia...", "Skuld")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("È molto da chiedere. Saranno davvero d'accordo?", "Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Invece di rispondere, Mariru fa semplicemente un'altra domanda.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Questa opera d'arte dipinta a spruzzo sembra fatta da un bambino dell'asilo. Cosa ti dice?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Che chiunque sia stato non si è sforzato abbastanza di nascondere il fatto che è tutto falso.", "Skuld")
	await novel_interface.hide_character()
	
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Si tratta però di un sacco di soldi. Dovettero affittare l'ultimo piano dell'hotel e assumere centinaia di persone. Hanno già speso così tanto, quindi perché non hanno speso molto anche per la grafica?", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","think")
	await novel_interface.show_dialog("Bene…", "Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld mette il broncio, sconcertato da tutte le nuove informazioni.")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("Bene, è perché questa non è una novità per loro. È già successo innumerevoli volte. Sia qui che altrove.", "Mariru")
	await novel_interface.show_dialog("Nessuno li ha mai sospettati o denunciati. Quindi non si preoccupano più di nasconderlo.", "Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("La corruzione è un'arte in sé, soprattutto questo tipo di corruzione subdola. Devono raccogliere un'enorme quantità di informazioni e assicurarsi che tutti i soggetti coinvolti siano soddisfatti a ogni livello.", "Mariru")
	await novel_interface.show_dialog("Bisogna fare un sacco di indagini. Innumerevoli persone diventano parte dell'operazione. Gli scambi di benefici, come questo che vediamo oggi, sono avvenuti numerose volte.", "Mariru")
	await novel_interface.show_dialog("Dovranno negoziare con un sacco di persone. Funzionari, canali mediatici, alleanze dei lavoratori, organizzazioni non governative, anche quelli che occupano una posizione elevata nella criminalità organizzata.", "Mariru")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("È così che influenzano le decisioni chiave prese dal Congresso Unito.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru annuisce verso la porta chiusa della sala dei banchetti.")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("Questo è ciò che realmente vale di più in questa asta.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld abbassa la testa e sospira.")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("Fa schifo... sembra così disonesto...", "Skuld")
	novel_interface.change_expression("talk")
	await novel_interface.show_dialog("Aspetta, era quello che avevi pianificato fin dall'inizio?", "Skuld")
	await novel_interface.show_dialog("Non volevi arrestare quelle menti che manipolavano il progetto di ricostruzione...", "Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("All'improvviso, la porta della sala del banchetto si apre con una piccola fessura. Fabella tende una mano, dando loro un segno di OK.")
	await novel_interface.show_text_only("È il segnale che tutti gli articoli sono stati venduti e che la transazione tra i conti crittografati elettronicamente sta per avvenire.")
	await novel_interface.show_text_only("Mariru prende il suo walkie-talkie.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Squadra di recupero, bloccate tutti gli ingressi al 99° piano, compreso il pozzo dell'ascensore. Avvertire l'hotel che al 98esimo piano è stata rilevata una grande dose di sostanze inquinanti radioattive.", "Mariru")
	await novel_interface.show_dialog("Interrompere tutti i segnali di rete e i mezzi di comunicazione nell'edificio. Una volta che dirò di andare, impongo il silenzio radio.", "Mariru")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("Vai!", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…")
	
	# scene6 - 回到现场
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.change_music("res://assets/audio/music/Brooklyn.mp3")
	await novel_interface.show_text_only("Beatrice finalmente mi lascia respirare. Mi spinge a girarmi in modo che la mia schiena sia rivolta verso di lei e mi sussurra all'orecchio.")
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("Aspetta finché non dico \"vai\". E non sbirciare!", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Poi mi spinge verso il camion su cui si trova Elluka. Faccio del mio meglio per farmi strada tra la folla, con Sonya che mi segue da dietro.")
	await novel_interface.show_text_only("Nel frattempo, Beatrice si avvia con calma verso un altro camion nelle vicinanze, spingendo via gli uomini come una regina alta e potente.")
	await novel_interface.show_text_only("Chiunque si giri per urlarle perde immediatamente i sensi quando vede la sua faccia.")
	await novel_interface.show_text_only("Beatrice sale agilmente su un camion vuoto, dove due operai stanno effettuando un controllo del suono sul tetto.")
	await novel_interface.show_text_only("Afferra un microfono e osserva finché io e Sonya non riusciamo ad avvicinarci il più possibile al camion di Elluka, quindi fa cenno agli operai di accendere il microfono al massimo volume.")
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("Vai!", "Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sentendo i suoi ordini, annuisco a Sonya.")#换行问题
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("Vai!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Con l'altoparlante al massimo volume, qualunque cosa Beatrice dirà dopo raggiungerà sicuramente le orecchie di ogni singola persona in Electronics Street.")
	await novel_interface.show_text_only("In piedi orgogliosa sul tetto del camion, fa un respiro profondo e urla nel microfono, lasciando che la sua voce si diffonda.")
	novel_interface.show_character("beatrice_regular","angry")
	await novel_interface.show_dialog("Siete spazzatura, tutti voi!", "Beatrice")
	await novel_interface.show_dialog("Andate al diavolo, pervertiti!", "Beatrice")
	await novel_interface.hide_character()
	
	print("=== 天启篇第11话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
