# apocalypse_ep04.gd - 天启篇第04话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第04话剧本
	apocalypse_ep04_script()

func play_script():
	pass

# 天启篇第04话 - 正式剧本
func apocalypse_ep04_script():
	 #scene1 - 继续电器街
	novel_interface.show_background("res://assets/images/bg/Soya/Akihabara.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_dialog("…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("…", "Rafael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Apenas puedo respirar por el nerviosismo mientras veo a Raphilia hojear el libro que tiene en sus manos.")
	await novel_interface.show_text_only("Sus mejillas están sonrojadas, sus dedos tiemblan, como si dudaran antes de pasar cada página.")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("¡Mira! ¡Lencería para traseros alegres!", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya grita, mostrando la lencería de arnés de encaje negro a unos transeúntes muy fascinados.")
	novel_interface.show_character("soya_uniform","laugh")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("iluka_uniform","speechless",0.25)
	await novel_interface.show_dialog("¡Oh! ¡Abajo! ¡Abajo!", "Elluka")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Elluka aplaude a un lado, a pesar de no tener la menor idea de lo que es un pasivo.")
	novel_interface.show_character("servent")
	await novel_interface.show_dialog("Señorita Ren, he revisado todos sus artículos. Parecen estar intactos. ¿Debo pedirle a alguien que los traiga a su residencia?", "séquito")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphilia finalmente recupera sus sentidos, se aclara la garganta y enrolla el libro, con la cara seria.")
	await novel_interface.show_text_only("Luego, con el libro enrollado, golpea a Sonia en la cabeza con tanta fuerza que toda la calle puede oírlo.")
	await novel_interface.show_text_only("El cazador de brujas de cabello plateado, incapaz de agacharse a tiempo, se agacha de dolor.")
	novel_interface.show_character("soya_uniform","cry")
	await novel_interface.show_dialog("¿Para qué fue eso?", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ella llora, masajeándose la cabeza.")
	await novel_interface.show_text_only("Raphilia la mira condescendientemente.")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("¿De verdad crees que no sé quién eres?", "Rafael")
	await novel_interface.show_dialog("Sin Salmonton, la iglesia no es nada. Y tenemos los perfiles de todos los agentes de la CDF en nuestra Embajada.", "Rafael")
	await novel_interface.show_dialog("Sonia Ángeles...", "Rafael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphilia está frente a Sonya, pero me señala con su dedo derecho.")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("Esa lencería que tienes en la mano...", "Rafael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphilia mueve su dedo ligeramente hacia abajo para que apunte a mi pecho.")
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("¿Eso realmente le quedaría bien?", "Rafael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("¿Qué?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ah...", "Transeúnte A")
	await novel_interface.show_dialog("Bueno…", "Transeúnte B")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","hungry")
	await novel_interface.show_dialog("Ah...", "Elluka")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elluka asiente con comprensión, aunque todavía no tiene idea de lo que está pasando.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("¡Afortunadamente alguien tiene sentido común! Las habilidades detectivescas de Raphilia finalmente le han demostrado al mundo que la lencería no me pertenece.")
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_text_only("(¡Pero eso no mejora la situación!)")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Soya/Akihabara.png")
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("Tch...", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sonya suspira, como una niña cuya broma ha fracasado.")
	await novel_interface.show_text_only("Se levanta lentamente, se frota la cabeza y escribe una dirección para el séquito de Raphilia.")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("Por favor envíe la bolsa de artículos a esta dirección. ¡Gracias!", "Soya")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("servent","",0.25)
	await novel_interface.show_dialog("¡Entendido!", "séquito")
	await novel_interface.hide_all_characters()
	
	# scene2 - 美术馆
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…")
	novel_interface.change_background("res://assets/images/bg/Soya/Galleries.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("Raphilia nos aleja de las multitudes de los alrededores hacia una galería de arte relativamente tranquila.")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("¿Has estado de compras con esos dos toda la tarde?", "Rafael")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_fishnet","wry_smile",0.25)
	await novel_interface.show_dialog("Sí, más o menos...", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Los tres ya llevábamos unas horas paseando por la zona. Tomamos postre y jugamos algunos juegos de arcade, aunque Sonya no pareció encontrarlos divertidos.")
	await novel_interface.show_text_only("Ahora, la Calle de la Electrónica, en cambio...")
	await novel_interface.show_text_only("¡No puedo creer que a esa chica de aspecto inocente le gusten esas tiendas para adultos!")
	await novel_interface.show_text_only("Y localizó todos los artículos que quería de inmediato. Apuesto a que esta no era su primera vez aquí.")
	await novel_interface.hide_background()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("Puedo saber quién tocó un libro con sólo olerlo.", "Soya")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("¡Los libros que huelen a rosa son mis favoritos!", "Soya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("¿Entonces ella normalmente usa sus habilidades en cosas como esta?")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_text_only("Tuve que quedarme allí en la entrada, sosteniendo bolsas de compras con una mano y cubriendo los ojos puros y vírgenes de Elluka con la otra.")
	novel_interface.change_expression("shy_right")
	await novel_interface.show_text_only("Los clientes que pasaban seguían mirando mi atuendo. Eso fue tan vergonzoso...")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Soya/Galleries.png")
	await novel_interface.show_text_only("Raphilia suspira, como si pensara que soy una idiota. Y ella finalmente habla:")
	novel_interface.show_character("ren_fishnet","shy_right")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","normal2",0.25)
	await novel_interface.show_dialog("¿Entonces no tienes idea de lo que pasó esta tarde?", "Rafael")
	await novel_interface.stop_music()
	novel_interface.character_light(0.35, "upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("¿Eh? ¿Qué?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("La reunión a puerta cerrada de 48 horas entre los líderes de las Ciudades Academia comenzó hoy al mediodía. Lo sabes, ¿verdad?", "Rafael")
	novel_interface.character_light(0.35, "perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Creo que lo escuché en las noticias...", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Lo siento, normalmente cambio de canal cuando salen noticias de política.")
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("Dos horas después de que comenzara la reunión a puerta cerrada, el portavoz oficial de la Tercera Ciudad Academia, que no asistirá a la reunión, hizo un anuncio que sacudió al mundo:", "Rafael")
	await novel_interface.show_dialog("La construcción del sistema de respuesta pasiva de Masada Ford está completa. El sistema ya está funcionando oficialmente.", "Rafael")
	await novel_interface.show_dialog("El sistema está construido en un entorno completamente cerrado, controlado por un módulo de IA fuera de línea que de ninguna manera está conectado con el mundo exterior.", "Rafael")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("Una vez que empiece a funcionar, nadie podrá apagarlo en los próximos veinte años.", "Rafael")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("Eso no suena nada sincero...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("Sin embargo, a diferencia de lo que todos pensaban, no es un sistema controlado por IA que lanzaría automáticamente un contraataque cuando fuera atacado.", "Rafael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La expresión de Raphilia es indescriptible: una combinación de miedo, rabia e incluso tristeza.")
	await novel_interface.show_text_only("Hace una pausa, tratando de recomponerse.")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("De hecho, el sistema tiene una sola función: cuando determina que más del 50% del centro de Masada Ford ha sido destruido o dañado, se activará de inmediato la “Operación Apocalipsis”.", "Rafael")
	novel_interface.show_background("res://assets/images/bg/Soya/Doomsday1.png")
	await novel_interface.show_dialog("Luego, el sistema lanzará bombas nucleares indiscriminadamente sobre las principales ciudades del mundo a través del “Ejército de Fantasía” de Sustancia H.", "Rafael")
	await novel_interface.show_dialog("Básicamente, si Masada Ford resulta perjudicado, sin importar quién, el mundo entero se hunde con él.", "Rafael")
	await novel_interface.show_dialog("Es un mecanismo fundamental en el firmware del sistema. Nadie podría apagarlo, ni siquiera los líderes nacionales.", "Rafael")
	await novel_interface.show_dialog("Si alguien intenta romper, apagar o reescribir el sistema, la Operación Apocalipsis se activará inmediatamente.", "Rafael")
	novel_interface.show_background("res://assets/images/bg/Soya/galleries.png",0.5)
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("Eh...", "Soya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("¿Qué es esto...?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Si bien no estoy exactamente seguro de los detalles, ya parece una situación grave a juzgar por las palabras clave que capté.")
	await novel_interface.show_text_only("El “Ejército de Fantasía” es un tipo de Sustancia H de grado militar utilizada en la Tercera Ciudad Academia. Es vital para la ciudad del mismo modo que la Égida es vital para Nueva Opulentia.")
	await novel_interface.show_text_only("Es un tipo espacial de Sustancia H que otorga a las armas que existen en un espacio determinado varias veces su potencia de fuego original.")
	await novel_interface.show_text_only("Cuando dichas armas impactan su objetivo en la atmósfera, pueden causar una destrucción hasta cientos de veces más grave que la que podrían tener con su diseño original.")
	await novel_interface.show_text_only("El mundo exterior sabe muy poco sobre sus parámetros exactos debido a la estricta confidencialidad que mantiene Masada Ford.")
	await novel_interface.show_text_only("Incluso el nombre \"Fantasy Army\" en sí es simplemente un nombre en clave que se originó a partir de las palabras burlonas de un general enemigo.")
	await novel_interface.show_text_only("Eso fue cuando se cortó la línea de suministro desde la península del Sinaí y Masada Ford estaba en peligro. El general se jactaba de que Masada Ford era ahora un blanco fácil y que la victoria para la ciudad no era más que una fantasía fugaz.")
	await novel_interface.show_text_only("Poco después, su territorio fue completamente arrasado por un misil antitanque “inimaginablemente poderoso”...")
	await novel_interface.show_text_only("Ningún extraño conoce la ubicación exacta del Fantasy Army. Se rumorea que todo el Masada Ford se construyó a su alrededor.")
	await novel_interface.show_text_only("Masada Ford siguió fortaleciéndose a lo largo de los años. En este momento, es inmune incluso a desastres naturales como inundaciones, terremotos y tifones.")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("(Recuerdo que la Égida debería poder defenderse incluso contra armas reforzadas por el Ejército de Fantasía... al menos eso es lo que piensa el público en general...)", "Lian")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("Aún así, el sistema está operado por IA y eso puede ser un problema...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("En todas las obras de ciencia ficción que he leído, dejar que la IA controle las armas nucleares nunca ha sido una buena idea.")
	await novel_interface.show_text_only("Me recuerda a este anime que vi una vez, con un hombre desnudo y un científico en silla de ruedas, riéndose detrás de sus gafas de sol...")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("Los datos completos de las pruebas de toda la IA relacionada se adjuntan en el anuncio publicado por Masada Ford. Después de todo, son el primer país en aplicar la tecnología de inteligencia artificial al combate real.", "Rafael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Raphilia mira por la ventana con el ceño ligeramente fruncido.")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("No me preocupa lo que hará la IA. Lo que me preocupa es lo que harán los humanos.", "Rafael")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Electronics Street parece hoy inusualmente concurrida.")
	
	# scene3 - 大使馆
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("<Mientras tanto, Embajada de Newmoridas, Zona Desmilitarizada Acordada>")
	await novel_interface.show_background("res://assets/images/bg/Soya/Embassy.png")
	await novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("Masada ha utilizado este sistema para sellar el Fantasy Army y renunció a los derechos de la ciudad para activarlo.", "Lumbert")
	await novel_interface.show_dialog("Superficialmente, el sistema parece promover una mentalidad de “nosotros morimos, todos mueren”.", "Lumbert")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Pero, en esencia, es como una especie de declaración de paz forzada.", "Lumbert")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("El orador es un hombre vestido con un traje elegante y personalizado. Deja su vaso de whisky sobre la mesa.")
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("Sí.", "Mujer con gafas")
	await novel_interface.show_dialog("Pero ya conocías el sistema de antemano, ¿no?", "Mujer con gafas")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("Directo al grano como siempre, ya veo, Akiko.", "Lumbert")
	novel_interface.change_expression("sedation")
	await novel_interface.show_dialog("La noticia sobre la construcción del sistema no puede difundirse hasta que esté completo y activado oficialmente. De lo contrario, el mundo entero intentaría intervenir e impedir que se construyera.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("Viejo zorro.", "Akiko")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Akiko se levanta las gafas, con el rostro inexpresivo.")
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("…", "Lumbert")
	await novel_interface.show_dialog("En fin, lo hecho, hecho está. El público puede quejarse, pero no hay nada que puedan hacer excepto aceptarlo.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("Viejo zorro.", "Akiko")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("... Perdón por ocultarle información.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("Hmph.", "Akiko")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lumbert se aclara la garganta.")
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("Ahora mismo, lo que quiere Masada Ford es mantener bajo control la controversia negativa y evitar sanciones económicas por parte de los países miembros del Congreso Unido.", "Lumbert")
	await novel_interface.show_dialog("Desde hace dos años, cuando Newmoridas dejó de conceder préstamos a Masada, la ciudad no tuvo más remedio que empezar a robar sus recursos a las zonas circundantes.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("Es como matar una gallina por los huevos.", "Akiko")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("Pero Salmonton's abrió sus puertas a los refugiados el año pasado. Por un lado, la población del país está disminuyendo de todos modos.", "Lumbert")
	await novel_interface.show_dialog("Por otro, es una forma de garantizar que Masada nunca forme parte de Europa. Los refugiados pueden actuar como una especie de amortiguador.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("Y ahora, sin la gallina, ¿quién pondrá los huevos?", "Akiko")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Akiko pone los ojos en blanco.")
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("Debido a las interminables guerras en Masada, más del 15% de su población forma parte del ejército o está relacionada con alguien que está en él. Puedes imaginar la situación financiera del país.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("¿Entonces también están utilizando la noticia de este sistema de respuesta pasiva como una oportunidad para el desarme?", "Akiko")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("Es simplemente una forma de ahorrar dinero. Pero también necesitarán una forma de ganar más dinero, que es...", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("Comercio de armas.", "Akiko")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Akiko suministra inmediatamente. Es obvio. Las armas de fuego son la única especialidad que Masada Ford tiene para ofrecer.")
	novel_interface.show_character("lambert","smile")
	await novel_interface.show_dialog("¿O debería decir: el comercio de “soluciones de defensa nacional”?", "Lumbert")
	await novel_interface.show_dialog("La Resistencia es conocida como un grupo terrorista muy peligroso que acecha en algún lugar de la periferia de Masada...", "Lumbert")
	novel_interface.change_expression("sedation")
	await novel_interface.show_dialog("Pero en realidad son los medios de Masada los que lo hacen parecer así.", "Lumbert")
	await novel_interface.show_dialog("La Resistencia es en realidad una organización obsoleta que tiene problemas fundamentales tanto en gestión como en tecnología. Los miembros apenas trabajan juntos. Definitivamente no es una amenaza tan grande como los medios hacen creer.", "Lumbert")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("Para vender seguridad, primero tienen que sembrar el miedo...", "Akiko")
	await novel_interface.show_dialog("Estoy seguro de que todos los agentes de marketing de software de seguridad informática lo saben muy bien.", "Akiko")#文本错误
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("De todos modos, vayamos al grano. ¿Qué es exactamente lo que quieres?", "Akiko")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Lumbert señala la frontera entre Asia y África en el mapa extendido sobre la mesa.")
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("Mmm. Eso pensé.", "Akiko")
	await novel_interface.hide_character()

	print("=== 天启篇第04话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
