# traumareflex_ep02.gd - 创伤反射篇第02话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放创伤反射篇第02话剧本
	traumareflex_ep02_script()

func play_script():
	pass

# 创伤反射篇第02话 - 正式剧本
func traumareflex_ep02_script():
	novel_interface.change_background("res://assets/images/bg/other/BG_City_street3.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("<Cinquième Ville Académie, Campus Est Rd.>")
	await novel_interface.show_text_only("La nuit approche à grands pas dans le quartier des affaires très animé. Les étudiants vêtus des uniformes de l’académie privée du quartier se bousculent.")
	await novel_interface.show_text_only("Une jeune fille, vêtue d'une tenue de femme de chambre, se fraye un chemin à vive allure dans la foule.")
	await novel_interface.show_text_only("Comme il y a un maid café ouvert 24h/24 et 7j/7 dans la rue d'en face, sa tenue n'attire pas beaucoup l'attention.")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("Mademoiselle Skuld ! Ralentir! C'est dangereux !","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("Allez, arrête de harceler !\nLaisse-moi profiter en toute tranquillité de mes quelques secondes de liberté !","Skuld")
	novel_interface.character_dark()
	await novel_interface.show_text_only("La jeune fille blonde virevolte et tourne en souriant comme le soleil.")
	novel_interface.character_light(0.35,"normal")
	await novel_interface.show_dialog("Détendez-vous !\nC'est l'endroit le plus sûr au monde. En plus...","Skuld")
	novel_interface.change_expression("proud")
	await novel_interface.show_dialog("J'ai Fabella pour me protéger !","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella rattrape enfin sa petite maîtresse et soupire en voyant à quel point la petite fille semble énergique.")
	novel_interface.show_character("fabiola_maid","smile")
	await novel_interface.show_dialog("Quelques secondes de liberté, hein...","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Pour une petite fille souvent enfermée à l'intérieur par son père surprotecteur, New Opulentia est en effet l'endroit le plus sûr où elle puisse être. Ce n’est pas comme Newmoridas, où tous les résidents sont autorisés à porter des armes, ni comme Salmonton, avec ses rues ternes pleines de réfugiés et de clochards.")
	await novel_interface.show_text_only("Les îles Lebona abritent également désormais des gangs importants qui s'y étaient installés pendant la guerre.")
	novel_interface.change_background("res://assets/images/bg/Shot/storyBGPol.png")
	await novel_interface.show_text_only("De plus, depuis que le Forum International de la Paix se tiendra à Nouvelle Opulentia le mois prochain, la sécurité a été renforcée dans toute la ville.")
	await novel_interface.show_text_only("Fabella a enfin une chance de sortir avec sa petite maîtresse sans avoir besoin de porter une arme automatique.")
	novel_interface.change_background("res://assets/images/bg/other/BG_City_street3.png")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("Ouais, c'est sûr ici, mais tu dois quand même faire attention à la circulation ! Et ne t'éloigne pas de ma vue—","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("Compris, compris !","Skuld")
	novel_interface.character_dark()
	await novel_interface.show_text_only("La jeune fille blonde interrompt la phrase de Fabella en bondissant en avant et en blottissant son visage contre la poitrine de la servante.")
	novel_interface.character_light(0.35,"perspire")
	await novel_interface.show_dialog("Oh, toi ! Vous portez encore un gilet pare-balles maintenant ?","Skuld")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("Ce n'est pas un peu contraignant ?\nTu devrais laisser respirer tes seins !","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_maid","blush")
	await novel_interface.show_dialog("Respirer ?","Fabella")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("Très bien, arrête ça...\n(chuchotements) Ne fais pas ça en public...","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("Heehee, je savais que Fabella était la meilleure ! Merci d'avoir arrêté les gars de l'ambassade pour moi et de m'avoir aidé à m'enfuir !","Skuld")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("fabiola_maid","normal",0.25)
	await novel_interface.show_dialog("Le vieux Haggerty va tellement nous tuer à notre retour...\nPourtant, la personne que nous recherchons se présentera-t-elle vraiment dans cette zone ?","Fabella")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Je pense que oui. La dernière fois au Sky Hotel, je me souviens avoir ressenti ce sentiment très fort... \"C'est ça, c'est celui-là\".","Skuld")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Vous voulez dire cette servante maladroite ?","Fabella")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Mais celui que je recherche devrait être un garçon...","Skuld")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Eh bien...\nEn fait, les garçons peuvent aussi se déguiser en servantes, vous savez...","Fabella")
	novel_interface.character_light(0.35,"perspire")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Hein ?","Skuld")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("Vous voyez, en fait, beaucoup de garçons aiment s'habiller avec des tenues girly...","Fabella")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ouh ?","Skuld")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"laugh")
	await novel_interface.show_dialog("Ils mettent aussi de jolis accessoires et du maquillage. À quel point est-ce adorable ?","Fabella")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ouh ! Et?","Skuld")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Certains peuvent aussi parler avec des voix girly aiguës. Beaucoup d’entre eux ont d’énormes abonnés en ligne !","Fabella")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Fabella est tellement excitée que sa voix tremble pratiquement.")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Oh, je me souviens avoir déjà vu des photos dans vos favoris Instagram.","Skuld")
	novel_interface.change_expression("pleased")
	await novel_interface.show_dialog("Dans ce cas, peut-être que la servante que nous avons vue n'était pas une fille, mais un garçon habillé comme tel...","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La jeune fille blonde semble plongée dans ses pensées.")
	novel_interface.show_character("fabiola_maid","panic")
	await novel_interface.show_dialog("Euh... hé !","Fabella")
	novel_interface.change_expression("blush")
	await novel_interface.show_dialog("Miss Skuld, laissez mon téléphone tranquille !","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","stare")
	await novel_interface.show_dialog("Allez, ton téléphone a une connexion cryptée donc les gens de Père ne pourront pas y accéder. En plus, ton mot de passe est si facile à deviner !","Skuld")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Je ne t'ai jamais demandé de faire de mon anniversaire ton mot de passe !","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld fait une grimace à Fabella, puis se retourne.")
	await novel_interface.show_text_only("Elle regarde le ciel du soir, teint en rouge par le soleil couchant, d'un air lointain et légèrement déçu.")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("Quoi qu'il en soit, peu importe que ce soit un garçon ou une fille, je suppose qu'il est trop tard pour que nous puissions les retrouver aujourd'hui.","Skuld")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Au moins, nous avons pu profiter de l'air frais ici, n'est-ce pas ?","Skuld")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("fabiola_maid","normal",0.25)
	await novel_interface.show_dialog("Alors... on rentre à la maison maintenant ?","Fabella")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Il y a un autre endroit que je veux visiter. C'est près de l'ambassade. Viens avec moi?","Skuld")
	await novel_interface.show_dialog("Vous souvenez-vous du Père Anton de l'église de la Trinité ?","Skuld")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Je pense que nous ne nous sommes rencontrés qu'une seule fois... c'est celui de Newmoridas qui écoutait toujours tes confessions depuis que tu étais petite, non ?","Fabella")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ouais. Il m'a envoyé un texto hier qui disait :","Skuld")
	await novel_interface.show_dialog("« Nouvelle Église Commémorative Opulentia »","Skuld")
	novel_interface.character_light(0.35,"thought")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Je l'ai appelé avec votre téléphone, mais il n'a jamais répondu. Je suis un peu inquiet, alors j'ai pensé que je devrais visiter l'église dont il a parlé...","Skuld") #换行问题
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Hum. L’église se trouve dans la zone démilitarisée agréée et également à proximité de l’ambassade, elle est donc probablement sûre.","Fabella") #文字错误
	novel_interface.change_2nd_expression("perspire")
	await novel_interface.show_dialog("Mais bon, quand l'as-tu appelé avec mon téléphone ? Et je n'ai même pas remarqué... à quel point je manquais de professionnalisme...","Fabella")
	novel_interface.character_light(0.35,"perspire")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ha, ne sois pas si dur avec toi-même !\nTu étais occupé à cuisiner !","Skuld")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Un petit sourire narquois apparaît sur le visage de Skuld à l’idée de la cuisine de Fabella.")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Church_Dusk.png")
	novel_interface.change_music("res://assets/audio/music/Sunset.mp3")
	await novel_interface.show_text_only("Le duo arrive devant une église en pierre de couleur marron, ses murs extérieurs recouverts d'une immense fresque religieuse.")
	await novel_interface.show_text_only("Il y a une croix au sommet du toit, qui semble digne et solennelle. Plusieurs dômes aux sculptures complexes dégagent une aura grandiose et majestueuse.")
	novel_interface.show_character("fabiola_maid","normal")
	await novel_interface.show_dialog("Je ne savais pas qu’il y avait une si grande église près de l’ambassade.","Fabella")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("skuld","normal",0.25)
	await novel_interface.show_dialog("La Nouvelle Opulentia est une sorte de ville académique, voyez-vous. Tout est question de science, donc il n’y a pas beaucoup de constructions religieuses ici.","Skuld")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Fabella passe sa carte électronique en vue satellite, curieuse de connaître la structure topographique et l'architecture de la région.")
	await novel_interface.show_text_only("C’est une habitude qu’elle avait cultivée dans l’équipe des opérations spéciales.")
	novel_interface.show_character("fabiola_maid","thinking")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("skuld","normal",0.25)
	novel_interface.character_dark()
	await novel_interface.show_dialog("Bizarre. Une église si immense, et pourtant il n’y a aucun modèle sur la carte. Existe-t-il une sorte de restriction pour des bâtiments comme celui-ci sur le territoire international ?","Fabella")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("C’est probablement parce que l’église n’avait même pas été ouverte jusqu’à récemment. Il doit être construit pour le Forum du mois prochain. Voir? Les peintures murales ont encore l'air neuves.","Skuld")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Votre père sera là le mois prochain, n'est-ce pas ? En tant que membre du Comité.","Fabella")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("Je pense que oui. Quoi qu’il en soit, entrons à l’intérieur !","Skuld")
	await novel_interface.hide_all_characters()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Church.png")
	await novel_interface.show_text_only("Entrer dans l’église, c’est comme entrer dans le sanctuaire le plus ancien du monde.")
	await novel_interface.show_text_only("Les murs sont entièrement en marbre. Des colonnes colossales se dressent sombrement. Les peintures à l'huile sur le plafond en forme de dôme et les fenêtres en mosaïque colorée environnantes créent une atmosphère de sainteté et de paix.")
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("Dépêchez-vous ! Regarder! Regarder! Ce lieu est structuré à l’image de l’église de la Trinité !","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_maid","panic")
	await novel_interface.show_dialog("Attends-moi !","Fabella")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Skuld sautille partout, buvant chaque détail avec délice, tandis que Fabella reste vigilante, tenant la porte d'entrée ouverte.")
	novel_interface.character_light(0.35,"normal")
	await novel_interface.show_dialog("(Il y a encore des étagères en bois là-bas dans les escaliers...)","Fabella")
	await novel_interface.show_dialog("(Cette église doit être encore en construction.)","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella fait quelques pas en avant. L’air autour d’elle vibre, presque imperceptiblement, mais c’est là. Tous ses poils sont dressés, comme affectés par l'électricité statique.")
	await novel_interface.show_text_only("Elle a toujours été très sensible au danger, en raison de son enfance sur les champs de bataille en Amérique du Sud.")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("(Attendez... quelque chose ne va pas...)","Fabella")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("A quelques pas de Fabella, Skuld se tait soudainement. Elle reste bien ancrée sur place, les mains tombant mollement à ses côtés.")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("Bon sang ! Nous devons partir !","Fabella")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Church_Stained_Glass1.png")
	await novel_interface.show_text_only("En moins d’une milliseconde, la vision de Fabella s’assombrit. Les couleurs des vitres, représentant des histoires bibliques, semblent briller davantage, envahissant tous ses sens.")
	await novel_interface.show_text_only("Les couleurs déforment, tordent, envahissent sa vision comme un essaim d'abeilles.")
	await novel_interface.show_text_only("La lumière orange du soleil couchant à l'extérieur se tord et se déforme, se fondant progressivement dans une couleur totalement différente.")
	await novel_interface.show_text_only("Tout semble se confondre, s’infiltrant dans le nez et les oreilles de Fabella, comme un bruissement inquiétant approchant à une vitesse alarmante.")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Church.png")
	await novel_interface.show_text_only("Fabella essaie désespérément de se concentrer.")
	await novel_interface.show_text_only("Cela ne lui éclaircit pas beaucoup la tête, mais elle parvient à ouvrir les yeux de force, seulement pour voir que Skuld s'est effondré sur le tapis non loin d'elle.")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("Bon sang !","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("A la seconde où elle lève un pied, essayant d'atteindre sa petite maîtresse, ses jambes lâchent.")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("... Je ne vois pas...","Fabella")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Church_Stained_Glass2.png")
	await novel_interface.show_text_only("Les fenêtres en mosaïque s'enroulent et se convulsent, se rapprochent, comme une peinture à l'huile se fondant dans un flot éclair de couleurs.")
	await novel_interface.show_text_only("Les objets représentés dans les peintures en mosaïque semblent se réorganiser dans des positions bizarres.")
	await novel_interface.show_text_only("Le corps de la servante se balance, l’inconscience approche à grands pas – et l’invasion colorée dans son esprit continue.")
	await novel_interface.show_text_only("La lumière pénétrant par la fenêtre projette des ombres sur le sol, engloutissant pouce par pouce les derniers de ses sens.")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Church.png")
	await novel_interface.show_text_only("Fabella se recroqueville brusquement, sort un poignard de l'intérieur d'un poignard.")
	await novel_interface.show_text_only("Elle vise un endroit sans artères principales et lui enfonce le poignard dans la cuisse sans une seconde d'hésitation.")
	await novel_interface.show_text_only("Le sang frais teint en rouge la peau claire de la jeune fille, mais au moins l’éclat de douleur lui offre quelques secondes de clarté.")
	await novel_interface.show_text_only("Serrant les dents, Fabella trébuche aux côtés de Skuld et prend la petite fille dans ses bras.")
	await novel_interface.show_text_only("Elle se retourne et avance de quelques pas en chancelant.")
	await novel_interface.show_text_only("Visant l'entrée principale, où il y a encore de la lumière, elle jette Skuld à l'extérieur du bâtiment avec ce qui lui reste de volonté avant que l'obscurité ne l'emporte.")
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("Au moins, elle est en sécurité maintenant, pense Fabella. Puis ses yeux se ferment, cédant enfin à l'ombre.")

	print("=== 创伤反射篇第02话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
