# traumareflex_ep11.gd - 创伤反射篇第11话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放创伤反射篇第11话剧本
	traumareflex_ep11_script()

func play_script():
	pass

# 创伤反射篇第11话 - 正式剧本
func traumareflex_ep11_script():
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_VTOL.png")
	novel_interface.change_music("res://assets/audio/music/Hand-to-hand combat.mp3")
	await novel_interface.show_text_only("Zeisig. Ein unbemannter Militärhubschrauber.")
	await novel_interface.show_text_only("Dieses Fahrzeug mit schwerer Feuerkraft war ein Albtraum für alle Bodeneinheiten und wurde während des Siebenjährigen Krieges von Masada Ford in der Dritten Akademiestadt entwickelt.")
	await novel_interface.show_text_only("Es ist in der Lage, Kampfhandlungen auf der Grundlage eines automatisierten Algorithmus durchzuführen und kann sich leicht an militärische Umgebungen mit Funkwellenstörungen gewöhnen.")
	await novel_interface.show_text_only("Seine nicht perfekte KI-Erkennungstechnologie ist sein einziger Schwachpunkt. Es ist berüchtigt für seine häufigen Fehlzündungen, bei denen viele Zivilisten getötet oder verletzt werden.")
	await novel_interface.show_text_only("Mehrere Länder haben eine Vereinbarung zum Verbot maschinell betriebener Zerstörungsgeräte unterzeichnet. Allerdings weigert sich Masada Ford weiterhin, Teil der Vereinbarung zu werden.")
	await novel_interface.show_text_only("Und jetzt landet dieser gelb-schwarz gestreifte Albtraum langsam über dem Gebäude vor uns.")
	await novel_interface.show_text_only("Die zwölf Spike-Raketen auf beiden Seiten des Fahrzeugs können leicht den gesamten Block in nichts als Asche sprengen.")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_Fighting1.png")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("Psst, beweg dich nicht.","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella bleibt kniend, ein Knie auf dem Boden. Sie legt ihr Scharfschützengewehr langsam auf den Boden und hebt beide Arme in einer Geste der Kapitulation.")
	await novel_interface.show_text_only("Unterdessen sitze ich immer noch da und kann kaum atmen wegen der erdrückenden Wucht der Scharfschützengewehrkugel, die gerade meine Deckung weggesprengt hat.")
	await novel_interface.show_text_only("Im Schatten sehe ich eine Silhouette, die sich lautlos dem Zeisig nähert.")
	novel_interface.show_character("ren_mercenary","serious")
	await novel_interface.show_dialog("(Ein Aufklärungsflugzeug... ist das nicht eines von denen, die sich selbst zerstören können?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Der in der Luft schwebende Zeisig scannt die Umgebung und feuert plötzlich Dutzende orange leuchtende Raketen ab.")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("...!","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","wail")
	await novel_interface.show_dialog("(Oh nein!)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Die Raketen hinterlassen mehrere helle Bögen in der Luft, breiten sich um den Zeisig aus und explodieren auf einmal.")
	await novel_interface.show_text_only("Im Gebäude dahinter zersplittern mehrere Reihen Glasfenster. Auch das Aufklärungsflugzeug zerfällt zu glitzernden Scherben in der Luft.")
	await novel_interface.show_text_only("Das Licht der rot-blauen Werbetafel hinter der gesamten Szene lässt es wie ein herrliches Großfeuerwerk aussehen.")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("(Es feuert also Täuschungsraketen ab, wenn es nicht in der Lage ist, den genauen Standort einer Bedrohung zu lokalisieren ...)","Fabella")
	await novel_interface.show_dialog("(Was für eine brillante Kriegsmaschine. Ihre KI-Programmierung ist etwas ganz Besonderes.)","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Der Hubschrauber dreht sich dann langsam, dreht sich, bis er direkt auf Fabella und mich gerichtet ist.")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_VTOL.png")
	await novel_interface.show_text_only("Die Facettenaugenlinse unter seinem Körper richtet seinen roten Laserpunkt des Todes auf uns beide, die wir da mitten auf der Straße sitzen.")
	await novel_interface.show_text_only("Es ist, als ob die Zeit genau dort stehen geblieben wäre.")
	await novel_interface.show_text_only("Die wenigen Sekunden vor dem Tod sind weitaus schrecklicher als der Tod selbst.")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("(Nur... wie viel Zeit ist vergangen?)","Ren")
	await novel_interface.show_dialog("(Wenn dies Teil von Fabellas Erinnerung ist, muss es tatsächlich passiert sein.)","Ren")
	await novel_interface.show_text_only("Aber irgendetwas fühlt sich einfach nicht richtig an ...")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Street_Fighting1.png")
	await novel_interface.show_text_only("Aus dem Nichts zittert der Zeisig heftig und dann –")
	await novel_interface.show_text_only("Nach knisternder statischer Aufladung und mehreren metallischen Klirren lösen sich einige Teile des Hubschraubers.")
	novel_interface.show_character("ren_mercenary","solemn")
	await novel_interface.show_dialog("(Hat jemand... darauf geschossen?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Der gepanzerte Hubschrauber dreht sich zur Seite und beginnt zu fallen – schafft es aber bald, die Höhe zu halten.")
	await novel_interface.show_text_only("Es versucht noch einmal aufzusteigen. Das System muss die Position des Fahrzeugs entsprechend dem erlittenen Schaden anpassen.")
	await novel_interface.show_text_only("Plötzlich ertönt eine weibliche Stimme aus meinem Ohrhörer – der so lange still war, dass ich vergessen hatte, dass er existiert.")
	await novel_interface.show_dialog("Tut mir leid, dass ich euch warten ließ, meine Babys!","Weibliche Stimme")
	await novel_interface.show_dialog("Aber denken Sie daran: Der mobile elektromagnetische Beschleuniger kann nur einmal verwendet werden. Normale Kugeln können es nicht durchdringen.","Weibliche Stimme")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Rina! Wie geht es dem Alpha-Team?","Russel")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Kümmere dich zuerst um dich selbst. Du musst dich immer noch um den Helikopter kümmern!","Männliche Stimme")
	await novel_interface.show_text_only("Eine tiefe, heisere Männerstimme warnt uns.")
	novel_interface.show_character("ren_mercenary","panic")
	await novel_interface.show_dialog("Wo ist...\nFabella?","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mir wird klar, dass Fabella, die neben mir kauerte, nicht mehr da ist. Ich bin der Einzige, der noch übrig ist, und sitze wie ein Idiot mitten auf der Straße.")  #换行问题
	await novel_interface.show_text_only("Sekunden später bricht ein dunkler Schatten mit einem flammend orangefarbenen Schwanz mit einem scharfen Kreischen unter dem umgestürzten gepanzerten Lastwagen hervor.")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("Alle runter!","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Boom!")
	await novel_interface.show_text_only("Wie von Fabellas lautem Schrei zerrissen, zerplatzt der Helikopter auf einer Seite in orangefarbene und gelbe Flammen.")
	await novel_interface.show_text_only("Bald wird der Hubschrauber von wütendem Feuer verschluckt. Der Zeisig wirbelt am Himmel herum, zieht dunklen Rauch hinter sich her, stürzt schließlich zu Boden und erleidet seinen Untergang.")
	await novel_interface.show_text_only("Eine Propellerklappe zischt aus dem dichten Rauch hervor, landet genau zwischen meinen Beinen und ragt aus der Teeroberfläche der Straße hervor.")
	novel_interface.show_character("ren_mercenary","wry_smile")
	await novel_interface.show_dialog("?","Ren")
	novel_interface.change_expression("wail")
	await novel_interface.show_dialog("…","Ren")
	await novel_interface.show_dialog("Aaaaaaaah!","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich setze mich schnell auf alle Viere zurück und habe das Gefühl, als würde mir das Herz gleich aus dem Mund springen.")
	novel_interface.show_character("fabiola_battle","mock")
	await novel_interface.show_dialog("Haha, armes Mädchen. Kannst du noch stehen?","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella erscheint hinter dem gepanzerten Lastwagen und wirft eine leere Stinger-Patrone beiseite.")
	await novel_interface.show_text_only("Ich klettere hinauf und versuche, meine unordentliche Frisur zu bändigen.")
	await novel_interface.show_dialog("Gut gemacht!","Männliche Stimme")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("Pernard? Wie läuft es da drüben?","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Du wirst mir nicht zuerst danken?","Weibliche Stimme")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Gut. Danke, oh toller Mirkin!","Cassel")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Alter. Warum bist du die ganze Zeit still geblieben und hast dich nur aufgeregt, wenn du ein Mädchen siehst?","Russel")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Das „Gepäck“ ist in Ordnung. Wir haben Schwartz verloren. Azoulay ist am Boden.","Männliche Stimme")
	await novel_interface.show_text_only("Der Mann mit der heiseren Stimme erklärt die Situation mit ein paar einfachen Worten. So sachlich, so emotionslos.")
	await novel_interface.show_dialog("Die Polizei und Ritnalap haben Unterstützung geschickt, aber sie sitzen wahrscheinlich außerhalb des Gebiets fest. Es wird wahrscheinlich eine weitere Angriffswelle geben.","Männliche Stimme")
	await novel_interface.show_dialog("Diese Straße ist auf beiden Seiten verbarrikadiert. Treffen wir uns an der Straße auf der Ostseite.","Männliche Stimme")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("Verstehen Sie das.","Fabella")
	await novel_interface.show_dialog("Schnappen Sie sich die Ausrüstung und machen Sie sich bereit!","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Ja!","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Was ist mit dem Kerl im Truck?","Cassel")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","bored")
	await novel_interface.show_dialog("Lassen wir den Idioten einfach hier.","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Ja!","Cassel")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_Fighting2.png")
	await novel_interface.show_text_only("Wir machten uns auf den Weg zur Nachbarstraße, indem wir einige Fenster eines Straßenhotels einschlugen und mit dem Rest unserer Munition und Vorräte hindurchgingen.")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("Hier sind alle Lichter an. Sollte da nicht jemand in der Nähe sein?","Fabella")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("russell","",0.25)
	await novel_interface.show_dialog("Das Disease Control Center hat hier vor neunzig Minuten eine Warnung vor biologischer Gefahr der Stufe 3 herausgegeben. Es wurde jedoch jetzt abgesagt.","Russel")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("erklärt Russel, während er durch die Nachrichten auf seinem Tablet scrollt.")
	novel_interface.show_character("fabiola_battle","thinking")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("russell","",0.25)
	await novel_interface.show_dialog("Der Krieg endete erst letztes Jahr und die Zivilbevölkerung ist immer noch paranoid. Wer möchte doch schon von einer Anthrax-Gesicht getroffen werden, oder?","Russel")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Fabella fragt finster:")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("Dieser Zeisig... ist er nicht weltweit auf dem Markt verboten?","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Natürlich. Diese Jungs sind stolz auf ihr streng geheimes KI-Kontrollsystem. Sie werden es sicherlich niemandem verkaufen.","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Was wäre dann, wenn wir die Steuereinheit aus den Trümmern holen? Auf diese Weise können wir es untersuchen und die Technologie stehlen …","Cassel")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Der Chip hat sich in dem Moment, in dem der Hubschrauber abstürzte, selbst zerstört, Idiot.","Russel")
	await novel_interface.show_dialog("Ich habe gehört, dass seine Angriffs- und Verteidigungsmodule tatsächlich getrennt sind. Vor ein paar Monaten floh ein Beamter aus Masada mit einer Probe eines dieser Module aus seinem Land.","Russel")
	await novel_interface.show_dialog("Als Menorah davon erfuhr, gingen sie diesem armen Kerl nach und sprengten ihn und seinen Transporter in Stücke. Für alle Fälle haben sie sogar die Asche eingesammelt und in ihr Land zurückgeschickt.","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","wail")
	await novel_interface.show_dialog("(Ihr Geheimdienst klingt auch ziemlich verrückt ...)","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Sie sind da!","Cassel")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich folge den Schritten und sehe mehrere Soldaten, die von der Straße herüberschlendern.")
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("Du hast hier vier, hm... oh, und auch einen Neuling?","Pernard")
	await novel_interface.show_dialog("Ich brauche eine Karte der Gegend.","Pernard")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Der große, stämmige Team-Alpha-Captain, dessen Auge von einer Klappe verdeckt ist, beginnt sofort, mit Fabella die Karte zu studieren.")
	novel_interface.show_character("leena")
	await novel_interface.show_dialog("Was für eine Süße.\nIch bin Rina Mirkin. Freut mich, Sie kennenzulernen.","Rina")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_mercenary","gratified",0.25)
	await novel_interface.show_dialog("Schön, Sie kennenzulernen. Nennen Sie mich Ren.","Ren")
	await novel_interface.show_dialog("(War sie nicht diejenige, die den Schuss abgefeuert hat, der uns den Arsch gerettet hat?)","Ren")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Rina sieht mit ihrem farbenfrohen Stricktuch und dem Scharfschützengewehr wie ein eleganter Hippie aus.")
	novel_interface.show_character("leena")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_mercenary","gratified",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Hm. Dein Outfit...","Rina")
	await novel_interface.show_dialog("Ist es das, was die Jugendlichen Girly Punk nennen?","Rina")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"awkward")
	await novel_interface.show_dialog("Äh, nein...","Ren")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Meine löchrigen Seidenstrümpfe wirken allerdings... punkig.")
	await novel_interface.show_text_only("Nun ja…")
	await novel_interface.show_text_only("Plötzlich taucht hinter den breiten Schultern des Team-Alpha-Anführers eine bekannte Gestalt hervor.")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Hallo, Fräulein Ren.","Skuld")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Wir sehen uns wieder!","Skuld")

	print("=== 创伤反射篇第11话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
