# traumareflex_ep09.gd - 创伤反射篇第09话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	traumareflex_ep09_script()

func play_script():
	pass

func traumareflex_ep09_script():
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("—Was? Der Verdächtige ist tot?","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Unser Ziel hatte sein Haus in eine ganze Festung umgebaut. Und er hat wie verrückt mit schweren Waffen auf das Bergungsteam geschossen, als sie ankamen.","SID Agent")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("Sollte das Bergungsteam nicht nur mit nichttödlichen Waffen ausgerüstet sein? Warum ist das Ziel gestorben?","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Das Team hat das Ziel nicht tödlich verletzt.","SID Agent")
	await novel_interface.show_dialog("Stattdessen scheint das Ziel entweder an einer Überdosis Neuropharmaka oder an Blutverlust gestorben zu sein.","SID Agent")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("... ich verstehe. Du kannst jetzt gehen.","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ja, Boss.","SID Agent")
	await novel_interface.show_text_only("Mariru blättert in den Akten des Verdächtigen und sieht sehr genervt aus, als Aya den Kontrollraum betritt.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Ist Ren jetzt da?","Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("Ja. Alles scheint ziemlich stabil zu sein.","Aya") #文字错误
	await novel_interface.show_dialog("Sind das die... Autopsieergebnisse des Verdächtigen?","Aya")
	await novel_interface.show_dialog("Antonio Jose Urquiza ... ein Mafia-Kriegsherr, der während des Siebenjährigen Krieges in Südamerika ziemlich aktiv war. Im Moment ist er nicht mehr als ein kleiner Bandenführer.","Aya")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("Schade, dass die Drogen sein Gehirn ziemlich verbrannt haben ... sonst hätten wir versuchen können, ihn mit diesem Gerät zu verhören.","Aya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Aya murmelt, während sie ihren Aktenstapel durchblättert.")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("Südamerika... das Ziel war also wirklich Fabella, oder?","Aya")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("Wir können noch nicht sicher sein.","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru schüttelt mit düsterem Gesicht den Kopf, während sie das auf dem Bildschirm angezeigte Zielprofil studiert.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("In dem chemischen Verteilungsgerät, das wir in der Kirche gefunden haben, wurde eine kleine Anzahl radioaktiver Marker entdeckt.","Mariru")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("Und von dort aus fanden wir leicht einen anderen Ort mit den gleichen radioaktiven Markierungen ... direkt in New Opulentia.","Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","dizzy",0.25)
	await novel_interface.show_dialog("Oh? Es ist also fast so, als würde sich der Täter nicht einmal die Mühe machen, sich zu verstecken.","Aya")
	novel_interface.character_light(0.35,"angry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Deshalb finde ich das so verdächtig...","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("Antonio... hat dieser Typ ein Motiv, Fabella zu verletzen?","Aya")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ja, und was für ein Motiv...","Mariru")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Im zweiten Kriegsjahr brach die Wirtschaft in Südamerika zusammen. Als nächstes übernahmen Banden mit ihren Konflikten und kleinlichen Schlägereien die politische Szene.","Mariru")
	await novel_interface.show_dialog("Fabella, die ihre Eltern im Krieg verlor, wurde von einem Oberst adoptiert und wuchs in einem streng militärischen Umfeld auf.","Mariru")
	await novel_interface.show_dialog("Sie zeigte bald animalische Kampfinstinkte und wurde die jüngste Nationalgarde der Geschichte.","Mariru")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("Ich habe gehört, dass sie sich einmal allein in feindliches Gebiet geschlichen hat und stillschweigend den Kommandanten ermordet hat – der zufällig Antonios ältester Sohn war.","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wink")
	await novel_interface.show_dialog("Das ist tatsächlich ein Motiv.","Aya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru ruft das Porträt eines Mannes in Militärkleidung auf und deutet auf den Bildschirm.")
	novel_interface.show_character("liliu_research","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ai","wink",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Dies war der Oberst, der Fabella adoptierte: Carlos Branco.","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"think")
	await novel_interface.show_dialog("Du meinst „Schlächter vom Fluss Churun“ Branco?","Aya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Das Massaker am Fluss Churun ​​ereignete sich nicht lange nach der Gründung des Vereinigten Kongresses durch die sechs Akademiestädte.")
	await novel_interface.show_text_only("46.000 Zivilisten wurden am Fluss hingerichtet, ihr Blut färbte die Salto Ángel Falls flussabwärts rot.")
	await novel_interface.show_text_only("Es war in diesen paar Wochen überall in den Nachrichten. Die allgemeine Meinung war, dass Carlos Branco, der damals mächtigste Kriegsherr, dahinter steckte.")
	await novel_interface.show_text_only("Die grotesken Anblicke des Vorfalls lösten in der breiten Öffentlichkeit weit verbreitete Antikriegsstimmungen aus, und Branco war seitdem als der Schlächter des Churun-Flusses bekannt.")
	novel_interface.change_background("res://assets/images/bg/Shot/storyBGPol.png")
	await novel_interface.show_text_only("Bald ergriff der Vereinigte Kongress militärische Maßnahmen gegen Carlos Branco und verurteilte ihn für seine antihumanitären und rassistischen Verbrechen.")
	await novel_interface.show_text_only("Schließlich sprengte ein Lancer Penetrator die Höhle, in der sich Branco versteckte – und beendete damit die Ära der Bandenmonopolisierung in Südamerika.")
	await novel_interface.show_text_only("Dies brachte den Vereinigten Kongress in die guten Bücher der meisten Menschen. Sie wurden von der breiten Öffentlichkeit als Symbol für Frieden und Gerechtigkeit angesehen. Aufgrund ihres Erfolgs wurden die sechs Nationen im Kongress in Akademiestädte umbenannt.")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("– Zumindest ist das die offizielle Version, die in den Geschichtsbüchern steht.","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru grinst und Aya nickt verständnisvoll.")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("Danach verschwanden die sechs verbliebenen Warlords in Südamerika einfach auf einmal, als stünden sie unter einer Art Vereinbarung. Der Vereinigte Kongress übernahm bald ihr Territorium.","Aya")
	await novel_interface.show_dialog("Sie wissen, was wirklich passiert ist, nicht wahr?","Aya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("fragt Aya, lehnt sich dicht an Mariru und stupst ihre Taille mit einem Ellbogen an, wie eine neugierige Katze.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Ja. Das Massaker fand tatsächlich statt – aber die Toten kamen aus den Gebieten der sechs Kriegsherren.","Mariru")
	await novel_interface.show_dialog("Sie stimmten zu, diese Leute zum Fluss zu transportieren, und ... Sie wissen, was als nächstes geschah.","Mariru")
	await novel_interface.show_dialog("Jemand hatte sie dazu bestochen.","Mariru")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("Der einzige, der sich weigerte, das Bestechungsgeld anzunehmen, war Carlos Branco.","Mariru")
	await novel_interface.show_dialog("So erhielt er die Rolle des „notwendigen Übels“ in unserer heutigen Welt.","Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","normal",0.25)
	await novel_interface.show_dialog("Also diejenigen, die die Kriegsherren bestochen haben...","Aya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Aya starrt mit großen Augen. Die Antwort ist nur allzu klar.")
	novel_interface.show_character("liliu_research","speak")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ai","think",0.25)
	await novel_interface.show_dialog("Diese Kriegsherren, die verschwunden sind, müssen einfach woanders hingezogen sein, ihren Namen geändert und den Rest ihres Lebens damit genossen haben, das Geld, das sie erhalten haben, auszugeben.","Aya")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Was den Beweis für Brancos Schuld betrifft ... er muss vom Vereinigten Kongress selbst für die Sicherheitssoldaten gefälscht worden sein.","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("Wenn der Vereinigte Kongress erkennt, dass Antonio aus Rache zurück ist, möchte er die Sache so schnell wie möglich hinter sich bringen.","Aya")
	await novel_interface.show_dialog("Kein Wunder, dass sich diese ganze Situation so unangenehm anfühlt.","Aya")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Oh? Peinlich, wie?","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"think")
	await novel_interface.show_dialog("Die Halluzinogene, die wir im Blut des Ziels gefunden haben, sind von der gleichen Art wie die, die wir auf Fabella gefunden haben.","Aya")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Das wusste ich.","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("Und wir fanden eine Art Stimulans, die Art, die die Kriegsherren oft verwendeten, um ihre Soldaten wachsam zu halten. Das war tatsächlich der wahre Grund für Antonios Tod.","Aya")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Das steht auch im Bericht.","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"think")
	await novel_interface.show_dialog("Das Stimulans macht denjenigen, dem es injiziert wird, überempfindlich. Sie werden mehr hören und mehr fühlen.","Aya")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("…","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Es ist so viel davon in seinem Blut, dass es wahrscheinlich genauso weh tun würde, wenn er von einem Gummigeschoss getroffen würde, als wenn er mit einer Kanone beschossen würde.","Aya")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Aber während der etwa zwanzig Minuten, in denen die beiden Seiten aufeinander feuerten, wurde das Ziel mehrere Male getroffen ...","Mariru")
	await novel_interface.show_dialog("Das Ziel ist seit der fünften Minute in den Aufnahmen der Szene deutlich zu erkennen. Und er hat sich nie etwas injiziert.","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Sie fanden bei der Autopsie auch keine Läsionen in seinem Nervensystem.","Aya")
	novel_interface.change_2nd_expression("blush_dizzy")
	await novel_interface.show_dialog("D-bedeutet das, dass dieser Typ Schmerzen wirklich genießt? Wow, der ultimative Masochist...","Aya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru rollt schnell etwas Papier zusammen und schlägt Aya auf den Kopf, als ob sie das ihr ganzes Leben lang getan hätte.")
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("Oh... wie auch immer, haben sie schon herausgefunden, wer Skuld in den Park gebracht hat?","Aya")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Wer auch immer es war, hielt sich von allen Überwachungskameras fern. Ein Paradebeispiel für einen hervorragenden Entführer.","Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("Jemand, der mit den Standorten von Überwachungskameras vertraut ist ... und mit einem Mädchen auf dem Rücken durch die Stadt laufen könnte, ohne als verdächtig zu gelten ...","Aya")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Ja. Diese Hinweise sind alles, was wir haben.","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru kratzt sich nachdenklich am Kinn.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Wenn Antonio tatsächlich ein Sündenbock war, der sorgfältig ausgewählt wurde, um als „Täter“ zu fungieren ...","Mariru")
	await novel_interface.show_dialog("Dann ist derjenige, der dahinter steckt, wahrscheinlich hinter Fabella her – oder genauer gesagt, hinter ihren Hexenkräften.","Mariru")
	await novel_interface.show_dialog("Ich glaube nicht, dass sie bekommen haben, was sie wollten.","Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Aber sie ist ein ziemlich wertvolles Exemplar, also beschlossen sie, sie nicht sofort zu töten, sondern dort zu lassen, damit der Vereinigte Kongress sie einfangen kann ...","Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("Das war also der Grund, warum sie einen so wertvollen „Sündenbock“ benutzten?","Aya")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Nun, sie ist eine Hexe, die von Feuermagie besessen ist, also...\nHmm, Moment, „Informationen mit Willen“...","Mariru")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("Informationen...?","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Marirus schockierter Blick trifft auf den von Aya. Sie sind zu dem gleichen Schluss gekommen.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Wenn das, was diese Entführer tatsächlich wollten, darin bestand, die Informationen aus Fabellas Kopf zu stehlen ...","Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("Sie verwenden möglicherweise die gleiche Art von Ausrüstung, die wir auch verwenden. Harima Tech hatte diese Brain-Hacking-Geräte auf der Grundlage einiger veröffentlichter, der breiten Öffentlichkeit zugänglicher Artikel entwickelt.","Aya")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("In diesem Fall sind sie wahrscheinlich auf das gleiche Problem gestoßen wie wir.","Mariru")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/TheWall.png")
	await novel_interface.show_text_only("Die ersten vier Agenten, die versuchten, sich in Fabellas Gehirn zu hacken, stießen auf dieselbe endlose Mauer.")
	await novel_interface.show_text_only("Wie eine Firewall, die Eindringlinge fernhält.")
	await novel_interface.show_dialog("Wenn es sich um eine anstößige Art von Firewall handelt –","Aya")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("Aya, mach dich bereit, Ren aufzuwecken, sobald ich die Befehle gebe.","Mariru")

	print("=== 创伤反射篇第09话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
