# traumareflex_ep08.gd - 创伤反射篇第08话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	traumareflex_ep08_script()

func play_script():
	pass

func traumareflex_ep08_script():
	novel_interface.change_background("res://assets/images/bg/Shot/storyBGWar.png")
	await novel_interface.show_text_only("Ce monde est cruel.")
	await novel_interface.show_text_only("La guerre d'il y a dix ans nous a laissé peu de moyens de vivre.")
	await novel_interface.show_text_only("Il y avait des tonnes d'enfants comme moi à l'orphelinat, mais je pensais toujours que j'étais le moins chanceux.")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Mother.png")
	await novel_interface.show_text_only("Peut-être avais-je l’impression que ce que j’avais perdu était le plus important. Mais alors, peut-être que le fait que je les ai perdus les rendait d’autant plus importants ?")
	await novel_interface.show_text_only("Pourtant, il était difficile pour moi, réfugié protégé sous l’égide, d’imaginer…")
	await novel_interface.show_text_only("À quoi ressemblerait la vie de ceux qui devaient continuer à survivre sur le champ de bataille après avoir perdu leurs proches.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Bouf... bouf...")
	await novel_interface.show_text_only("Bouf... bouf...")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Street_Fighting1.png")
	novel_interface.change_music("res://assets/audio/music/Hand-to-hand combat.mp3")
	await novel_interface.show_text_only("Je sors de l'épaisse fumée et m'effondre derrière une voiture au bord de la route, respirant durement dans mon masque.")
	await novel_interface.show_text_only("Le sol est recouvert de gravats. Les cris et le bruit des explosions semblent provenir de toutes les directions.")
	await novel_interface.show_text_only("À travers les flammes et la fumée, je distingue encore la publicité colorée diffusée sur l'écran d'un gratte-ciel lointain.")
	await novel_interface.show_text_only("Tout cela semble tellement... surréaliste.")
	novel_interface.show_character("ren_mercenary","solemn")
	await novel_interface.show_dialog("(Je me demande combien d'expériences de ce genre existent dans les souvenirs de Fabella...)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sa vie est tellement différente de la mienne.")
	await novel_interface.show_text_only("J’ai suivi quelques formations après avoir rejoint le SID, mais c’est surtout lié à la tactique et à la manipulation de l’information.")
	await novel_interface.show_text_only("Je n’ai jamais participé à un véritable exercice avec de vraies armes et de vraies balles. Même lorsque nous nous entraînions au tir, je me tournais vers les quelques canons plus petits ayant le recul le plus faible. Mariru et Annie se moquaient toujours de moi.")
	novel_interface.show_character("ren_mercenary","sob")
	await novel_interface.show_dialog("(Si seulement Annie était là...)","Ren")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("Hum. Ce pistolet dans ma main... est-ce un KRISS ?","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Une mitraillette KRISS Vector, connue pour son recul réduit. Les balles sont subsoniques, silencieuses. Pas étonnant que Mariru appelle cela un pistolet à eau pour les femmes.")
	await novel_interface.show_text_only("... Hé, tout le monde n'aime pas porter de gros fusils comme elle, vous savez ?")
	await novel_interface.hide_background()
	novel_interface.show_character("ren_mercenary","uneasy")
	await novel_interface.show_dialog("Cette arme... pas trop mal, peut-être que je peux y arriver...","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Je regarde le chargeur étendu en bas et j'avale.")
	novel_interface.show_character("ren_mercenary","shy")
	await novel_interface.show_dialog("(Non. Mieux vaut garder la sécurité désactivée pour le moment. Je ne veux pas frapper un allié.)","Ren")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Street_Fighting1.png")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Je jette un coup d'œil, essayant d'observer la situation là-bas.")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Cassel, tout va bien là-bas ?","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Le conducteur est mort ! Attendez... qu'est-ce que c'est ?\nOh mon Dieu, le mec respire toujours !","Cassel")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("Mettez un masque à gaz sur son visage et jetez-le dans le coffre. Alors prenez votre équipement et cherchez à vous mettre à l’abri !","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Les membres de l'escouade n'hésitent pas. Fabella, portant un sac noir, saute de l’autre côté de la voiture derrière laquelle je me cache.")
	novel_interface.show_character("ren_mercenary","perspire1")
	await novel_interface.show_dialog("(Wow, je n'en crois pas mes yeux... elle bouge si vite !)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Russel place le pont supérieur qui s'est envolé lors de l'explosion près d'un tas de pierres, créant une zone aveugle qu'il peut utiliser comme couverture, et se fraye un chemin à travers la rue.")
	await novel_interface.show_text_only("Quelques secondes plus tard, un énorme sac à dos surgit de nulle part à cause de la fumée, puis Cassel passe devant et disparaît rapidement dans l'ombre au coin.")
	await novel_interface.show_text_only("Cette situation est probablement un jeu d'enfant pour les membres de l'escouade des opérations spéciales comme ces gars-là. Après tout, ils ont tous combattu en première ligne.")
	await novel_interface.show_text_only("Mais cette fois, au lieu d’une zone de guerre, ils se battent dans la Deuxième Cité Académie.")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("Faites attention aux troupes mécaniques et envoyez un drone pour explorer l'environnement.\nRussel, avez-vous déjà contacté l'équipe Alpha ?","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Il n’y a pas de réponse. Ils sont de l’autre côté de l’explosion, avec nos « bagages ».","Russel")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Je suis le regard de Russel. La rue devant nous a été réduite en miettes, tandis que nous sommes coincés quelque part vers le milieu de la route.")
	await novel_interface.show_text_only("Le goudron sur le sol brûle comme jamais demain, ce qui rend difficile de savoir ce qui se passe devant nous.")
	novel_interface.show_character("ren_mercenary","serious")
	await novel_interface.show_dialog("(Est-ce que quelqu'un a enterré les bombes ici auparavant ?)","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("Hé ! Débutant ! Tu penses vraiment qu'il est sécuritaire de s'y cacher ?","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","perspire1")
	await novel_interface.show_dialog("—Hein ?\n(Est-ce qu'elle me parle ?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Avant même que je puisse réagir, Fabella m'a attrapé par le col de ma veste et m'a traîné dans l'ombre derrière le distributeur automatique au bord de la rue.")
	novel_interface.show_character("fabiola_battle","perspire")
	await novel_interface.show_dialog("Allez, c’est beaucoup trop facile pour l’ennemi de vous y amener. Et vous ne savez pas d’où ils tireront.","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Avant que je puisse formuler une réponse, elle fait signe à Russel, qui est de l'autre côté de la rue, tandis que Russel répond avec un pouce levé.")
	await novel_interface.show_text_only("Quelques secondes plus tard, un objet volant gris en forme de disque s'élève de derrière la voiture où Russel est caché.")
	await novel_interface.show_text_only("Fabella sort une petite tablette de sa ceinture et commence à étudier la vue plongeante de la zone capturée par le drone.")
	await novel_interface.show_text_only("Les deux SUV qui mènent la troupe ne sont plus que des boules de feu fumantes.")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("Ces gardes de sécurité... probablement tous morts. Au moins la Team Alpha et les « bagages » étaient derrière nous…","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Soudain, l'écran de la tablette devient statique, suivi d'un « boum » assourdissant.")
	await novel_interface.show_text_only("Avec un bruit faible et pétillant, le drone gris s'enflamme dans le ciel.")
	await novel_interface.show_text_only("Ses petits composants pleuvent et viennent claquer sur les toits des voitures qui nous entourent avec des bruits métalliques.")
	novel_interface.show_character("ren_mercenary","serious")
	await novel_interface.show_dialog("... Un tireur d'élite ?","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("Doit être dans le bâtiment d'en face. Probablement en utilisant un dispositif d'accélération électromagnétique anti-espionnage à courte distance. Regardez où vous vous cachez. Assurez-vous que l'obstacle que vous choisissez est suffisamment épais.","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Il s’agit d’un appareil doté de balles métalliques accélérées régulièrement par l’énergie électromagnétique. Extrêmement puissant, même si l'appareil est généralement encombrant et difficile à transporter.")
	await novel_interface.show_text_only("Ces balles peuvent pénétrer des obstacles très épais. Pendant la guerre, un Premier ministre a été tué par un homme à plus de 0,5 kilomètre de distance, alors qu'il se trouvait derrière un mur de ciment d'un mètre d'épaisseur. C’est ainsi que ce type d’engin de tir complet a acquis sa renommée.")
	await novel_interface.show_text_only("Des trucs comme ça ne faisaient pas vraiment partie de mon entraînement, je le sais simplement parce que, eh bien, c'est dans l'un de mes jeux préférés. Il est également livré avec un skin exclusif, pour un prix exorbitant.")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("L'Œil est baissé ! Je le répète, l'Œil est baissé !","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Le tireur d'élite devrait être à environ 800 mètres de nous. Nous avons un autre drone avec une surface réfractive et un œil qui voit tout monté dessus. Ils ne le remarqueront probablement pas si nous envoyons celui-là.","Cassel")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","panic")
	await novel_interface.show_dialog("Attendez, l'Œil qui voit tout... le rayon de sa lentille est de 15 mm, n'est-ce pas ?","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella demande, alors qu'elle observe le bâtiment bien éclairé d'en face avec un réflecteur.")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("L'objectif peut donc toujours réfléchir la lumière. Même quand il fait nuit. Nous ne pouvons pas exactement le recouvrir d’une surface réfringente la lumière.","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Donc ils peuvent quand même repérer le drone, hein... Et on ne peut pas ouvrir le feu sur le bâtiment comme ça. C’est un immeuble commun et des innocents y vivent.","Cassel")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Pour un sniper travaillant avec un équipement encombrant et long à recharger, la priorité est de ne pas se faire repérer par l'ennemi (nous).")
	await novel_interface.show_text_only("Je me souviens avoir appris cela lors d'un entraînement tactique.")
	await novel_interface.show_text_only("Cependant, je me souviens aussi d'autre chose dans le même manuel...")
	novel_interface.show_character("ren_mercenary","normal1")
	await novel_interface.show_dialog("(Leur priorité c'est de ne pas se faire repérer, c'est vrai, mais aussi... ne devraient-ils pas aussi essayer de ne pas nous faire savoir du tout leur existence ?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tirer sur notre drone, bien sûr, signifie que nous connaîtrons leur existence.")
	await novel_interface.show_text_only("Ce qui en fera bien sûr une cible. Qui que ce soit, ce doit être soit un débutant qui ne sait pas ce qu'il fait...")
	await novel_interface.show_text_only("Ou quelqu'un qui est déjà sûr de savoir où tirer ensuite et de pouvoir évacuer immédiatement après avoir terminé le travail.")
	await novel_interface.show_text_only("Mon cœur s'emballe.")
	await novel_interface.show_text_only("Je bondis instinctivement, forçant Fabella à tomber au sol, loin du blocage derrière lequel elle se cache.")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("Que fais-tu ? Idiot—","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La seconde suivante, le blocage sur lequel elle s'appuyait explose en morceaux.")
	await novel_interface.show_text_only("Après avoir détruit la couverture, la balle pénètre dans le mur du bâtiment, créant un renflement de neuf pieds carrés dans le mur.")
	await novel_interface.show_text_only("Les panneaux près du distributeur automatique sont projetés en l'air. D’innombrables billets flottent dans le ciel, finissant par dériver vers le sol comme des flocons de neige, avec les lampadaires blancs en toile de fond.")
	await novel_interface.show_text_only("C’est comme une scène tout droit sortie d’un film noir.")
	await novel_interface.show_text_only("Je regarde, hypnotisé, mais Fabella a déjà serré ses jambes autour de ma taille, m'envoyant rouler dans l'ombre projetée par une pile de briques de ciment.")
	novel_interface.show_character("ren_mercenary","awkward")
	await novel_interface.show_dialog("(Hein ? Pourquoi me retient-elle ?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Ça va, patron ?","Cassel")
	novel_interface.show_character("fabiola_battle","mock")
	await novel_interface.show_dialog("Ah, je vais bien.\nHeureusement, notre débutant a l'esprit vif.","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella répond en me tapotant les joues. Cela aurait semblé être un geste doux si elle ne m'avait pas chevauché.")
	novel_interface.show_character("fabiola_battle","wink")
	await novel_interface.show_dialog("Et j'ai trouvé un moyen d'empêcher l'objectif de réfléchir la lumière.","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elle dit en tendant la main vers mes cuisses—")

	print("=== 创伤反射篇第08话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
