# traumareflex_ep03.gd - 创伤反射篇第03话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	traumareflex_ep03_script()

func play_script():
	pass

func traumareflex_ep03_script():
	await novel_interface.show_text_only("เฮ้ คุณเคยรู้สึกแบบนั้นบ้างไหม?")
	await novel_interface.show_text_only("คุณจำฉากหนึ่งได้... แต่ไม่รู้ว่ามันเกิดขึ้นเมื่อใด")
	await novel_interface.show_text_only("ฉันไม่ได้หมายถึงเดจาวู ทุกคนมีเวลานั้นบ้าง")
	await novel_interface.show_text_only("ฉันหมายถึง มีบางอย่างที่คุณรู้มาโดยตลอดว่าสักวันหนึ่งจะต้องเกิดขึ้น และในที่สุดมันก็เกิดขึ้น")
	await novel_interface.show_text_only("คุณรู้มาตลอดว่ามันจะเกิดขึ้น คุณเคยเห็นมันในรูปแบบของภาพย้อนหลังด้วยซ้ำ คุณไม่สามารถแน่ใจได้ว่าจะเกิดขึ้นเมื่อใด")
	await novel_interface.show_text_only("สิ่งที่เราเรียกว่าเดจาวูเป็นเพียงการยืนยันว่าลางสังหรณ์ของคุณเป็นจริง")
	await novel_interface.show_text_only("คุณรู้ว่ามันจะเกิดขึ้น คุณรู้อยู่เสมอ")
	await novel_interface.show_text_only("ใช่ไหมล่ะ?")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Night_Park.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.show_character("skuld","painful")
	await novel_interface.show_dialog("อืม…","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("เด็กสาวผมบลอนด์ลืมตาขึ้นอย่างเมามาย ลูบหน้า และพบว่าตัวเองนอนอยู่บนม้านั่ง")
	novel_interface.show_character("skuld","panic")
	await novel_interface.show_dialog("ฟาเบลล่า... เราอยู่ที่ไหน?","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("แต่ฟาเบลล่าไม่ตอบ แปลก. สาวใช้มักจะปรากฏตัวทันทีที่ชื่อของเธอถูกเรียก")
	await novel_interface.show_text_only("เด็กสาวมองไปรอบๆ เพื่อดูถนนที่ว่างเปล่า มีโคมไฟถนนเรียงรายสองข้างทาง ถนนสายนี้ดูจะดำเนินต่อไปตลอดกาลในความเงียบอันน่าขนลุก ราวกับเป็นจักรวาลคู่ขนาน")
	novel_interface.show_character("skuld","panic")
	await novel_interface.show_dialog("เราอยู่ในโบสถ์ไม่ใช่เหรอ...?","Skuld")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("อ่า... ฟาเบลล่า!","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("สกัลด์ลุกขึ้นยืน โดยมีมือนวดขมับที่ปวดของเธอ")
	await novel_interface.show_text_only("เธอจำฝันร้ายที่เธอมีได้ จำภาพบิดเบี้ยวบนหน้าต่างโมเสก แต่มันเป็นเพียงฝันร้ายจริงๆเหรอ?")
	await novel_interface.show_text_only("เธอจำฟาเบลลาได้ โดยไล่เธอออกจากโบสถ์ ปลดปล่อยเธอออกจากความมืดมิดที่อาจทำร้ายเธอ...")
	await novel_interface.show_text_only("สกัลด์ตรวจสอบข้าวของของเธอ โทรศัพท์มือถือของเธอ กระเป๋าสตางค์ของเธอ เครื่องประดับของเธอ... ทั้งหมดอยู่ที่นั่น")
	await novel_interface.show_text_only("มีสายที่ไม่ได้รับในโทรศัพท์ของเธอสามสิบสองสาย")
	await novel_interface.show_text_only("ถ้าฟาเบลลาไม่ได้ติดตั้งซอฟต์แวร์ป้องกันการติดตามบนโทรศัพท์ สถานทูตก็คงจะพบเธอแล้ว")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("สิบแปดนาฬิกา...มันสายไปแล้วเหรอ?","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("เธอหลับตาลง พยายามควบคุมการหายใจให้ดีที่สุด เพื่อจัดการกับความทรงจำที่พันกันยุ่งวุ่นวายของเธอ")
	await novel_interface.show_text_only("เธอต้องสงบสติอารมณ์ นั่นคือสิ่งที่พ่อและฟาเบลลาคงปรารถนา พวกเขามักจะบอกเธอเสมอว่ายิ่งสถานการณ์อันตรายมากเท่าไร เธอก็ยิ่งต้องรักษาสมองให้ปลอดโปร่งมากขึ้นเท่านั้น")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("โบสถ์นั้น... และข้อความจากคุณพ่อแอนตัน... ต้องเป็นกับดักแน่ๆ","Skuld")
	await novel_interface.show_dialog("ไม่ว่าใครก็ตามจะต้องมุ่งเป้าไปที่ฉัน พ่อหรือฟาเบลล่า","Skuld")
	await novel_interface.show_dialog("ฉันได้ยินเสียงรถยนต์จากถนนใกล้ๆ และแม้แต่นักแสดงข้างถนนที่เล่นเพลงที่อยู่ห่างไกลออกไป... และฉันไม่ได้ถูกมัดหรืออะไรเลย","Skuld")
	await novel_interface.show_dialog("จาก GPS ในโทรศัพท์ของฉัน ฉันอยู่ที่ Arai Central Park ไม่ไกลจากโบสถ์มากนัก","Skuld")
	await novel_interface.show_dialog("ใครก็ตามที่พาฉันมาที่นี่คงไม่ได้ทำอันตรายใดๆ","Skuld")
	await novel_interface.show_dialog("ฉันไม่รู้ว่าใครก็ตามที่วางกับดักและใครก็ตามที่พาฉันมาที่นี่ เป็นคนกลุ่มเดียวกันหรือเปล่า... ฉันกลับไปแบบนี้ไม่ได้","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("สกัลด์หมุนหมายเลขของฟาเบลลาอีกครั้ง และอีกครั้งไปที่วอยซ์เมล เธอตรวจสอบบันทึกทั้งหมดของเธอ และดูเหมือนว่าฟาเบลลาจะไม่ได้ติดต่อกับเธอเลย") #换行问题
	novel_interface.show_character("skuld","painful")
	await novel_interface.show_dialog("ฟาเบลลา...","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ในที่สุด เธอก็โทรหาพ่อของเธอโดยกำโทรศัพท์ไว้ในมือเล็ก ๆ ของเธอแน่น")
	await novel_interface.show_text_only("เขารับสายวินาทีที่ผ่านไป")
	await novel_interface.show_dialog("สกัลด์เหรอ? นั่นคือคุณเหรอ?","พ่อ")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("พ่อ...","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("คุณอยู่ที่ไหนห่า? สิบโมงกว่าแล้ว คุณอยู่ที่ไหน ทุกคนต่างกังวลใจจะตาย!","พ่อ")
	await novel_interface.show_dialog("และทั้งคุณและสาวใช้ของคุณก็ไม่รับสาย! คุณสองคนเป็นอะไรกัน? ท่านเอกอัครราชทูตแฮ็กเกอร์ตีได้ส่งทีมออกไปตามหาคุณแล้ว!","พ่อ")
	await novel_interface.show_text_only("พ่อของเธอฟังดูโกรธมาก แต่สกัลด์ก็โล่งใจที่ได้ยินเสียงของเขา")
	await novel_interface.show_text_only("อย่างน้อยก็ไม่มีใครพยายามข่มขู่เขาด้วยการใช้เธอเป็นตัวประกัน")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("ตอนนี้ฉันปลอดภัยแล้ว ไม่ต้องกังวล แต่ฟังนะ—","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ชายคนนั้นเงียบลงทันทีด้วยน้ำเสียงของลูกสาวอย่างเร่งด่วน")
	await novel_interface.show_dialog("... คุณอยู่คนเดียวเหรอ?","พ่อ")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("ใช่ แค่ฉัน.","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("รอสักครู่ ฉันจะโทรกลับพร้อมหมายเลขอื่น","พ่อ")
	await novel_interface.show_text_only("เธอวางสายและรับสายจากหมายเลขที่ไม่รู้จักทันที")
	await novel_interface.show_dialog("เอาล่ะ คุยกันได้แล้ว เกิดอะไรขึ้น","พ่อ")
	await novel_interface.show_text_only("สกัลด์หายใจเข้าลึกๆ จากสิ่งที่เธอรู้ในปัจจุบัน ควรมีความเป็นไปได้สองประการ:")
	await novel_interface.show_text_only("ถ้าคนที่วางกับดักและคนที่พาเธอมาที่นี่มาจากกลุ่มเดียวกัน เป้าหมายของพวกเขาต้องเป็นฟาเบลล่า ไม่ใช่สกัลด์เอง")
	await novel_interface.show_text_only("หากพวกเขาไม่ได้มาจากกลุ่มเดียวกัน เธอเองก็อาจเป็นเป้าหมายได้ ใครก็ตามที่ต้องการให้เธอล้มเหลว และขณะนี้จับฟาเบลลาและคุณพ่อแอนตันเป็นตัวประกัน")
	await novel_interface.show_text_only("ไม่ว่าจะเป็นอะไรก็ตาม คนที่เธอชื่นชอบที่สุดในโลกกำลังตกอยู่ในอันตราย")
	await novel_interface.show_text_only("ถึงกระนั้น หากเป็นอย่างหลัง เธอก็ไม่สามารถออกไปตามหาฟาเบลลาด้วยตัวเองได้ มันคงจะเดินตรงเข้าไปในกับดัก และเธอก็อาจจะตกเป็นตัวประกันด้วย ซึ่งผู้ลักพาตัวสามารถใช้ต่อสู้กับพ่อและคณะกรรมการได้")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("คุณช่วยทำอะไรให้ฉันก่อนได้ไหม? ฉันต้องการคนมาตรวจสอบคุณพ่อแอนตันจากโบสถ์ทรินิตี และบอกฉันว่าเขาปลอดภัยหรือไม่","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("แน่นอน ฉันจะส่งคนไปทันที\nตอนนี้ บอกฉันว่าเกิดอะไรขึ้น","พ่อ")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("ฉันกับฟาเบลลาถูกซุ่มโจมตีใกล้สถานทูตเมื่อไม่นานมานี้ พวกเขาอาจใช้ยาหลอนประสาทบางชนิดหรือยาที่ทำจากสาร H.","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("อะไร?","พ่อ")
	await novel_interface.show_text_only("การใช้อาวุธเคมีหรืออาวุธที่สร้างด้วยสาร H ในดินแดนระหว่างประเทศค่อนข้างจะเทียบเท่ากับการประกาศสงครามกับรัฐสภาคองเกรส")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("ฟาเบลลาเสี่ยงชีวิตเพื่อช่วยฉัน ฉันไม่รู้ว่าตอนนี้เธออยู่ที่ไหน...","Skuld")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("คนพวกนั้นคงส่งข้อความปลอมเป็นคุณพ่อแอนตันมาให้ฉันและล่อฉันไปที่นั่น","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("… ฉันเห็นแล้ว","พ่อ")
	await novel_interface.show_dialog("Forum of Peace กำลังจะจัดขึ้นในเดือนหน้า... ทำไมคุณต้องไปที่ New Opulentia ในเวลาอันละเอียดอ่อนเช่นนี้...?","พ่อ")
	await novel_interface.show_dialog("ใครก็ตามที่กล้าทำเช่นนี้จะต้องระมัดระวังอย่างมากเกี่ยวกับตัวตนของพวกเขา","พ่อ")
	await novel_interface.show_dialog("แม้ว่าอดีตหัวหน้าของฟาเบลลาในอเมริกาใต้จะเสียชีวิตไปแล้ว แต่เขายังคงมีศัตรูอยู่บ้าง...","พ่อ")
	await novel_interface.show_dialog("อย่างไรก็ตาม ตอนนี้คุณอยู่ที่ไหนแล้ว?\nฉันจะจัดเตรียมบางอย่างเกี่ยวกับความสัมพันธ์ระหว่างประเทศและนำคุณกลับไปที่นิวโมริดาส","พ่อ")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("คุณต้องสัญญากับฉันก่อน! สัญญากับฉันว่าจะช่วยฟาเบลล่า!","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("เสียงของ Skuld สั่น ดวงตาเต็มไปด้วยน้ำตา")
	await novel_interface.show_dialog("…","พ่อ")
	await novel_interface.show_text_only("อีกด้านหนึ่งของสาย ความเงียบ")
	await novel_interface.show_text_only("สคูลด์รู้ดีว่าพ่อของเธอเก่งมาก มีความรู้ดีอยู่เสมอ เขาสามารถวิเคราะห์สถานการณ์ได้อย่างง่ายดายและตัดสินใจเลือกแนวทางปฏิบัติที่ดีที่สุด")
	await novel_interface.show_text_only("พ่อของเธอเป็นผู้ก่อตั้งบริษัทกองทุนเฮดจ์ฟันด์ ซึ่งเจริญรุ่งเรืองในตลาดการเงินในช่วงสงครามเนื่องจากทักษะการตัดสินใจที่ยอดเยี่ยมของเขา ด้วยเหตุนี้เขาจึงได้รับตำแหน่งในคณะกรรมการสำหรับตนเอง")
	await novel_interface.show_text_only("แต่นั่นก็เป็นสาเหตุที่ทำให้เขาได้รับศัตรูจำนวนนับไม่ถ้วน การนำหุ้นลงนั้นแตกต่างอย่างมากจากการนำประเทศลง")
	await novel_interface.show_text_only("สกัลด์เติบโตขึ้นมาในสภาพแวดล้อมที่เต็มไปด้วยความเกลียดชังและอันตราย แต่พ่อของเธอยืนหยัดอย่างผิดปกติและปฏิเสธที่จะเปลี่ยนวิธีการเพื่อลูกสาวของเขา")
	await novel_interface.show_text_only("มันอาจจะเกี่ยวข้องกับแม่ของเธอที่เสียชีวิตตั้งแต่เธอยังเด็กมาก")
	await novel_interface.show_text_only("ทันใดนั้น Skuld สังเกตเห็นกรอบสีแดงเล็กๆ บนหน้าจอโทรศัพท์ของเธอ\nสิ่งนี้บ่งบอกว่าตำแหน่งของเธอถูกติดตามในระหว่างการโทร")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("...!","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("เธอก็วางสายทันที")
	novel_interface.show_character("skuld","panic")
	await novel_interface.show_dialog("พวกเขาได้ตำแหน่งของฉันแล้ว! ต้องออกไปจากที่นี่...","Skuld")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Parking_Lot.png")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("สกัลด์รีบวิ่งเข้าไปในปล่องบันไดของอาคารจอดรถในบริเวณใกล้เคียง")
	await novel_interface.show_text_only("เธอเรียกหมายเลขร้านซักรีดในรายชื่อติดต่อของเธอ ฟาเบลลาให้หมายเลขนี้แก่เธอเป็นทางเลือกสุดท้าย")
	novel_interface.show_character("skuld","panic")
	await novel_interface.show_dialog("... เดาว่าฉันไม่มีทางเลือกแล้ว!","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("หญิงสาวหมอบอยู่บนบันไดแล้วกดหมายเลข")
	await novel_interface.show_text_only("หลังจากดังไปสามครั้ง หญิงสาวผู้น่ารักก็พูดขึ้น")
	await novel_interface.show_text_only("เครื่องซักผ้าหยอดเหรียญ Rexhill ยินดีให้บริการครับ.")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("... ฉันชื่อ Skuld Axelrod หมายเลขประจำตัวระหว่างประเทศ AX1832.","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("เข้าใจแล้ว กรุณารอสักครู่...")
	await novel_interface.show_text_only("คุณแอกเซลร็อด ผ้าของคุณพร้อมแล้ว เราจะส่งไปให้คุณหรือเปล่า?")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("แน่นอน เพื่อนของฉันที่โบสถ์ New Opulentia Memorial ต้องการให้เธอไปรับผ้าซักรีด","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("เข้าใจแล้ว")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("ฉันอยู่ที่—","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("เรารู้ว่าคุณอยู่ที่ไหน กรุณาอดทน.")
	await novel_interface.show_text_only("ผู้หญิงคนนั้นวางสาย")
	await novel_interface.show_text_only("สิบนาทีต่อมา รถเอสยูวีสีดำแล่นเข้ามาในลานจอดรถ")
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("ขอให้เป็นวันดี คุณแอกเซลร็อด","SID Agent")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("คุณมาจาก... SID?","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("ใช่ เราได้เรียกเพื่อนของคุณแล้ว","SID Agent")
	await novel_interface.show_dialog("กรุณาเข้าไป","SID Agent")


	print("=== 创伤反射篇第03话结束 ===")
	await novel_interface.end_story_episode(0.5)
