# traumareflex_ep12.gd - 创伤反射篇第12话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放创伤反射篇第12话剧本
	traumareflex_ep12_script()

func play_script():
	pass

# 创伤反射篇第12话 - 正式剧本
func traumareflex_ep12_script():
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_Fighting2.png")
	novel_interface.change_music("res://assets/audio/music/War Drum.mp3")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Hola, señorita Ren.","Skuld")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("¡Nos volvemos a encontrar!","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","perspire1")
	await novel_interface.show_dialog("¿Eh? Sku—","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Me contengo justo a tiempo, tragándome mis palabras.")
	await novel_interface.show_text_only("Estos recuerdos son de hace dos años. Skuld y yo no deberíamos habernos conocido todavía en aquel entonces.")
	novel_interface.show_character("ren_mercenary","stare")
	await novel_interface.show_dialog("(¿Podría conocerme por sus habilidades proféticas especiales?)","Ren")
	await novel_interface.show_dialog("(Skuld dijo que recordaba haberme visto en sus recuerdos...)","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Y tú eres Fabella, ¿verdad?\nY Russel, Cassel...","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld se gira hacia los otros miembros del escuadrón, con cara brillante e inocente.") #换行问题
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_dialog("Oh, ¿alguien te enseñó nuestros nombres?\nLa hija de nuestro empleador es una pequeña muy inteligente.","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","wry_smile")
	await novel_interface.show_dialog("(Jaja, tal vez ella no sea tan complicada como pensaba.)","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("¡Encantado de conocerte!\nEres mucho más bonita que en la foto—","Cassel")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Russel le da un codazo a Cassel en las costillas para que se calle.")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Oh, por favor, no creas que no te pillé mirando la subasta.","Russel")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld se echa a reír ante el rostro sonrojado de Cassel. La atmósfera tensa se aligera un poco.")
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("Escuche, nuestras tropas de apoyo todavía están retenidas fuera de la zona. Tendremos que encontrar una manera de llegar nosotros mismos al punto de evacuación.","Pernard")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_dialog("Estamos fusionando equipos temporalmente. Todos sigan las órdenes del Capitán Pernard.","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella asiente hacia Pernard, le entrega varios cargadores de rifle, mientras ella misma toma una escopeta.")
	novel_interface.show_character("ren_mercenary","worry")
	await novel_interface.show_dialog("(Parece que confían el uno en el otro. ¿Han peleado mucho juntos?)","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("Es posible que pronto nos encontremos con más hostiles. Todos, hagan un inventario ahora. Vea cuánto equipo y munición tenemos e informe en cinco minutos.","Pernard")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Ya revisé mi mochila. Tiene tres cargadores, un pequeño kit de emergencia y una lata de aerogel.")
	await novel_interface.show_text_only("Es algo así como laca para el cabello. La espuma que sale del bote se expandirá inmediatamente de tamaño y se congelará tan pronto como quede expuesta al aire.")
	await novel_interface.show_text_only("Annie lo usó una vez para sellar la puerta de una habitación de invitados en el Sky Hotel.")
	await novel_interface.show_dialog("(¿Por qué está esto en mi bolso...?)","Ren")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Street_Fighting2.png")
	await novel_interface.show_text_only("Mientras todos hacen un inventario, Fabella arrastra a Pernard al otro lado de la calle.") #换行问题
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("Nuestro enemigo realmente vino preparado.","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("Sí. Parecen tener todo nuestro itinerario trazado. Incluso logró evacuar a los civiles en el momento perfecto con una advertencia falsa.","Pernard")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("Lo que significa que saben cuándo terminó la subasta.","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("¿Cuántos hostiles te has encontrado después de que volaron la carretera?","Pernard")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_dialog("Un francotirador y un jilguero. ¿Tú?","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("Tres francotiradores, cuatro drones montados con armas automatizadas.","Pernard")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ahí es cuando Fabella finalmente nota la sangre salpicada en la cazadora de Pernard. Ella pregunta nerviosamente:")
	novel_interface.show_character("fabiola_battle","panic")
	await novel_interface.show_dialog("¿Tantos de ellos? ¿Estás herido?","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("No en serio. Rina es una excelente tiradora, los eliminó a todos fácilmente.","Pernard")
	await novel_interface.show_dialog("Enviaron a los francotiradores en las posiciones perfectas incluso en un área con tantos edificios altos. Esto significa que saben que el \"equipaje\" está en el Equipo Alfa.","Pernard")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella frunce el ceño.")
	novel_interface.show_character("fabiola_battle","panic")
	await novel_interface.show_dialog("¿Pero ese mocoso mimado no decidió en qué auto ir solo después de que terminó la subasta?","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("Esto significa que... uno de nosotros podría haber filtrado la información.","Pernard")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Pernard y Fabella miran en silencio a los cuatro miembros restantes del escuadrón, bromeando y riendo, rodeando a la chica rubia.")
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("El enemigo debe estar persiguiéndola, por supuesto, pero probablemente no quieran matarla.","Pernard")
	await novel_interface.show_dialog("O sino, podrían haberlo hecho tan fácilmente en otro momento.","Pernard")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","bored")
	await novel_interface.show_dialog("... ¿Entonces la quieren secuestrar?","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("Entonces al menos envía un escuadrón terrestre o un vehículo blindado.","Pernard")
	await novel_interface.show_dialog("De todos modos, manténgase alejado de los espacios abiertos. Continúe a la sombra de los edificios.","Pernard") #原文多字
	await novel_interface.show_dialog("Cuídate.","Pernard")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_dialog("Sí, tú también.","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Al otro lado de la carretera, escucho a Skuld y los otros tres hablar sobre la subasta a la que asistieron esta noche.")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Ese manuscrito que compraste esta noche... ¿te costó 36 millones?","Cassel")
	await novel_interface.show_dialog("¿Pero no es sólo un viejo y estúpido pergamino? ¿Qué tiene de valioso? ¿Tienes todos los futuros números de lotería o algo así?","Cassel")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Ah, por favor. No sabrías el valor de las reliquias antiguas.","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","pleased")
	await novel_interface.show_dialog("Realmente tampoco sé mucho sobre reliquias. De alguna manera sentí con mucha fuerza que necesitaba comprarlo.","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("¡Ah, eso es lo que siempre siento cuando veo los juegos de disparos más nuevos!","Cassel")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Cassel asiente, comprensivamente.")
	novel_interface.show_character("ren_mercenary","wry_smile")
	await novel_interface.show_dialog("(¿Estás seguro de que realmente entendiste?)\n(Skuld probablemente compró el artículo debido a algo que vio en sus recuerdos...)","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("leena")
	await novel_interface.show_dialog("Ahora que lo pienso, muchas escrituras antiguas se perdieron después de la guerra. Escuché que alguien compró el manuscrito de Arquímedes hace algún tiempo incluso por millones de dólares.","Rina")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Entonces, ¿qué es este pergamino que compraste?","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Ya tiene miles de años según la datación por carbono 14. Creo que es una especie de receta escrita en runas antiguas. Yo tampoco puedo leerlo.","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Dice Skuld, mostrándonos el papel descolorido, que guarda en una exquisita carpeta en su bolso negro de piel de cocodrilo.")
	novel_interface.show_character("ren_mercenary","perspire1")
	await novel_interface.show_dialog("(¿Es seguro mostrárnoslo... así sin más?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La textura del papel parece parecerse a una especie de tela. En él hay innumerables runas no identificables, junto con ilustraciones muy parecidas a los brazos de un pulpo.")
	novel_interface.show_character("leena")
	await novel_interface.show_dialog("¿Es esto papiro? Pero el papiro no se habría conservado tan bien si hubiera existido durante miles de años.","Rina")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","panic")
	await novel_interface.show_dialog("¿No deberías usar guantes o algo así antes de tocarlo?","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Está bien, está cubierto con una capa de spray hermético.","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Vaya. Me pregunto qué plato puedes hacer con esta receta. Vale 36 millones...","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Será mejor que le enseñes a tu mamá a cocinarlo la próxima vez, Russ. La última vez que comí un plato que ella preparó, casi termino en el hospital.","Cassel")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("No puedo culpar a mi mamá por eso. Tuviste diarrea explosiva sólo porque comiste demasiado, no por su comida.","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Entonces... esos tipos... ¿tal vez están detrás de este pergamino?","Cassel")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Pero un jilguero ya cuesta más de 20 millones. A menos que este pergamino contenga algún mensaje oculto realmente importante, no vale la pena.","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld")
	await novel_interface.show_dialog("¿Mensaje oculto?","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld sostiene el manuscrito en el aire, estudiándolo bajo la luz del edificio de enfrente.")
	await novel_interface.show_text_only("Todos los demás se apiñan y no puedo evitar unirme a ellos también.")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Bueno…","Cassel")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Hasta donde puedo ver...","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("leena")
	await novel_interface.show_dialog("No hay nada sospechoso en ello...","Rina")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("…")
	novel_interface.show_character("ren_mercenary","worry")
	await novel_interface.show_dialog("En realidad, lo que realmente me parece sospechoso es...","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Bueno, me lo he estado preguntando desde que llegamos a esta calle por primera vez.")
	await novel_interface.show_text_only("Hay toneladas de discotecas, bares y vallas publicitarias iluminadas por aquí.")
	novel_interface.show_character("ren_mercenary","worry")
	await novel_interface.show_dialog("¿Pero por qué este foco apunta hacia nosotros, en lugar de un anuncio o la entrada de una tienda?","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("... Mmmm, cierto...","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("¡Oye!","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella, que está al otro lado de la calle, de repente nos grita.")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("¡Muévete!","Fabella")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("¡Auge!")
	await novel_interface.show_text_only("Apenas logramos dispersarnos antes de que un gigantesco objeto negro se estrelle desde el cielo, aterrizando en el lugar exacto hacia donde apunta el foco.")
	await novel_interface.show_text_only("En medio de la nube de polvo y asfalto destrozado, escuchamos el siniestro ruido de la fricción del metal y el zumbido de las juntas mecánicas.")
	await novel_interface.show_text_only("Una enorme púa sobresale del humo, brillando con una fría luz metálica azul.")
	await novel_interface.show_text_only("Adjunto a la púa hay un elegante brazo mecánico, que a su vez está conectado a:")
	await novel_interface.show_dialog("¿Q-qué diablos es eso?","Ren")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Big_Spider.png")
	await novel_interface.show_text_only("Fabella nos advirtió que el enemigo podría enviar algún tipo de ejército de robots, pero ciertamente no esperaba, bueno, esto.")
	await novel_interface.show_text_only("Tiene ocho patas ágiles, afiladas y con púas, que sostienen un cuerpo gigantesco que sigue haciendo ruidos mecánicos.")
	await novel_interface.show_text_only("... Una araña robot de aleación, de casi un metro de altura. Equipado con púas en cada pierna que pueden atravesar fácilmente el cuerpo humano.")
	await novel_interface.show_text_only("El mortal robot depredador nos estudia con ojos rojos parpadeantes en su “cabeza”.")
	await novel_interface.show_dialog("¿Estás bromeando...?","Rina")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_Fighting2.png")
	await novel_interface.show_text_only("Fabella y Pernard rápidamente levantan sus armas y abren fuego.")
	await novel_interface.show_text_only("Las balas de plomo llueven sobre la armadura de aleación, saltan chispas cuando las balas rebotan en el cuerpo de la araña.")
	await novel_interface.show_text_only("La araña en sí no parece afectada en absoluto. Se gira para mirar a Fabella y se abalanza sobre ella con un movimiento fluido.")
	await novel_interface.show_text_only("Pernard se hace a un lado, mientras Fabella se agacha y se desliza por debajo del vientre de la araña.")
	await novel_interface.show_text_only("Un fuerte estallido viene detrás de mí, sacándome de mi estado de aturdimiento. Es Rina, que también ha empezado a disparar.")
	await novel_interface.show_text_only("Las patas de la araña tiemblan, pero incluso el rifle de francotirador antimaterial de Rina deja solo una pequeña abolladura en la armadura de aleación.")
	novel_interface.show_character("ren_mercenary","panic")
	await novel_interface.show_dialog("(¿Qué debo hacer...?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("¿Usar el aerogel? De ninguna manera. Me asará vivo antes de que pueda acercarme para rociarlo con mi aerogel.")
	novel_interface.show_character("ren_mercenary","upset")
	await novel_interface.show_dialog("(Vamos, tiene que haber una manera...)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("El arácnido gigante ahora persigue a Pernard, quien rompe la ventanilla de un taxi estacionado al costado de la carretera y se sube.")
	await novel_interface.show_text_only("Antes de que pueda arrancar el motor, la araña ha desprendido la puerta del coche con una pata.")
	await novel_interface.show_text_only("Pernard aprovecha la oportunidad para salir del auto nuevamente, agarrando la puerta del auto y arrojándola sobre sí mismo antes de que la araña pueda saltar sobre él.")
	await novel_interface.show_text_only("Una de las patas con púas de la araña atraviesa la puerta y se queda atascada allí. Debajo está Pernard, que hace todo lo posible por mantener la puerta del coche en su sitio, con el rostro sonrosado por el esfuerzo.")
	novel_interface.show_character("ren_mercenary","shout")
	await novel_interface.show_dialog("¡Uf, es ahora o nunca!","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tomo mi decisión y le tiro toda mi lata de aerosol a la araña.")
	await novel_interface.show_text_only("A continuación, cambio mi metralleta KRISS Vector al modo de ráfaga y comienzo a disparar rápidamente en la dirección de la lata que acabo de lanzar al aire.")

	print("=== 创伤反射篇第12话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
