# traumareflex_ep06.gd - 创伤反射篇第06话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	traumareflex_ep06_script()

func play_script():
	pass

func traumareflex_ep06_script():
	novel_interface.change_music("res://assets/audio/music/Hand-to-hand combat.mp3")
	await novel_interface.show_text_only("—Boom!")
	await novel_interface.show_text_only("Noch ein Knaller. Der Kopf unseres Lastwagens wird abrupt angehoben und ich werde auf den Boden geschleudert.")
	await novel_interface.show_text_only("Das Äußere des Lastwagens, das mit der magischen Substanz H verstärkt ist, wird kaum beeinträchtigt, aber wir können immer noch die erdrückende Kraft von innen spüren.")
	await novel_interface.show_text_only("Als der Lastwagen auf die Seite rollt, dreht sich mein Magen um. Es fühlt sich an, als könnte ich mir ab und zu die Eingeweide auskotzen.")
	await novel_interface.show_text_only("Richtig ... die Panzerung des Lastwagens mag unbesiegbar sein, aber der Boden ist es ganz bestimmt nicht. Sprengen Sie einfach den Boden und der LKW wird unbeweglich gemacht.")
	await novel_interface.show_text_only("Was für ein dummer, sinnlos teurer Entwurf...")
	novel_interface.show_background("res://assets/images/bg/Fabiola/APC_Blur2.png")
	await novel_interface.show_text_only("…")
	await novel_interface.show_text_only("Kopfschmerzen...")
	await novel_interface.show_text_only("Meine Ohren klingeln, meine Augen können sich kaum konzentrieren.")
	await novel_interface.show_text_only("Zum Glück trage ich eine mit nicht-Newtonscher Flüssigkeit gefüllte Kampfjacke, sonst hätte ich mir bei der vorherigen Sauerei wahrscheinlich die meisten Knochen gebrochen.")
	await novel_interface.show_text_only("Ich weiß nicht, wer die Ausrüstung für mich ausgewählt hat, aber ich denke, ich sollte dankbar sein.")
	novel_interface.show_character("ren_mercenary","awkward")
	await novel_interface.show_dialog("(Mussten sie mich trotzdem dazu zwingen, Seidenstrümpfe zu tragen?)\n(Und jetzt sind Löcher darin!)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Bäm! Bumm! Bumm! Bumm! Bumm!")
	await novel_interface.show_text_only("Fabella schlägt die Abdeckung über dem Notausgangsknopf im Auto auf. Die Sprengschnüre auf dem Dach des Lastwagens explodieren nacheinander.")
	await novel_interface.show_text_only("Auf dem Dach entsteht ein klaffendes Loch, das nun zur Seite zeigt. Beißender Rauch und Flammen dringen in meine Nase und in den Innenraum des Fahrzeugs ein.")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("Verdammt... alle raus!","Fabella")
	novel_interface.change_expression("thinking")
	await novel_interface.show_dialog("*Husten* Hey, geht es dem Neuling gut?","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Noch immer kaum bei Bewusstsein, werde ich von Fabella hochgehoben und aus dem Lastwagen geworfen.")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Der Rauch brennt in meinen Augen, lässt mich unkontrolliert tränen und blockiert meine Sicht.")
	await novel_interface.show_text_only("Ich nehme zwei große Schlucke Luft, bekomme aber nur Rauch. Meine Lunge steht kurz vor dem Verbrennen...")
	await novel_interface.show_text_only("Ich beginne reflexartig zu husten und zu würgen, da ich nicht in der Lage bin, wieder zu Atem zu kommen.")
	await novel_interface.show_text_only("Mein Körper ruckelt, während ich würge, und mein Blick trifft schließlich auf die Maske, die an meinem Hals hängt. Ich drücke es schnell mit einer Hand über meine Nase und meinen Mund.")
	await novel_interface.show_text_only("Puh...")
	await novel_interface.show_text_only("…")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Hospital_Passage.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_text_only("<Abteilung für experimentelle Medikamente, Harima Tech>")
	await novel_interface.show_text_only("Nachdem Mariru und Aya mit mir die grundlegenden Details zu Fabella besprochen haben, gehen sie nach unten, um ein paar Geräte zu stimmen, und lassen mich ganz allein dort sitzen.")
	novel_interface.show_character("ren_maid","wry_smile")
	await novel_interface.show_dialog("Also sind sie einfach... gegangen? Einfach so?","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Die stillen Krankenhausflure wirken plötzlich bedrückend.")
	await novel_interface.show_text_only("Ich sitze da auf einem Stuhl an der Wand, gekleidet in ein völlig unpassendes Dienstmädchen-Outfit.")
	novel_interface.show_character("ren_maid","sob")
	await novel_interface.show_dialog("Fühlt sich an, als wäre ich in einem Zombie-Shooter-Spiel mit R-Rating …","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Nein. Zombies existieren nicht. Geister hingegen...","???")
	novel_interface.show_character("ren_maid","wry_smile")
	await novel_interface.show_dialog("Ja, haha. Zombies tun nicht –","Ren")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("Warte, wer war das?","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich springe auf, als ich plötzlich eine Stimme von der Treppe höre.")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Es tut mir leid, habe ich dich erschreckt?","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ein zierliches Mädchen schaut aus der Ecke hervor.")
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("Und wir sehen uns wieder, Miss Ren!","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Das blonde Haar des Mädchens fällt in einem zarten Zopf bis zur Taille. Sie sieht ätherisch aus, wie etwas, das nicht von dieser Welt ist. Keine Aura, die ich jemals vergessen könnte.")
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("Oh, Skurd?","Ren")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("(Hat sie mich...Fräulein genannt?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld lächelt mich schüchtern an. Sie scheint ängstlich und unruhig zu sein.")
	await novel_interface.show_text_only("Überhaupt nicht elegant und anmutig, wie damals, als wir uns im Sky Hotel trafen.")
	await novel_interface.show_text_only("Oh, richtig! Fabella ist ihre Zofe. Natürlich wird sie sich Sorgen machen...")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("Ich weiß, dass du hier bist, weil Mariru dich kommen ließ...\nAber ich hätte dich trotzdem gefragt...","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sie scheint zu zögern, zittert ein wenig und hält tapfer die Tränen zurück, während sie spricht.")
	novel_interface.show_character("skuld","painful")
	await novel_interface.show_dialog("Bitte... rette Fabella...","Skuld")
	await novel_interface.show_dialog("Es war alles meine Schuld, dass ich sie dazu gebracht habe, sich mit mir davonzuschleichen ...","Skuld")
	await novel_interface.show_dialog("Ich habe nicht damit gerechnet, dass das passiert...","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("Hey, beruhige dich!","Ren")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("(Oh nein, sie wird weinen!)\n(Was soll ich tun?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich strecke ihr fast die Hand aus, um sie zu trösten, aber es kommt mir einfach nicht richtig vor, ein kleines Mädchen zu umarmen ... auf dem Flur eines Krankenhauses um Mitternacht ... in Strumpfbändern und im Dienstmädchen-Outfit.")
	await novel_interface.show_text_only("Ich halte inne, die Arme in der Luft, und sie wirft sich in meine Brust.")
	await novel_interface.show_text_only("Ihr weiches blondes Haar fällt über meine Ellenbogen. Das Mädchen riecht ein wenig nach Milch. Mein Herzschlag beschleunigt sich, mein Gehirn brummt.")
	novel_interface.show_character("ren_maid","blush")
	await novel_interface.show_dialog("(Sie ist so winzig!)\n(Was für eine Süße!)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Hier, mit ihrem Gesicht in meiner Brust vergraben, scheint sie kleiner zu sein, als sie aussah. Ihr zerbrechlicher Körper zittert wie ein in die Enge getriebenes Tier.")
	await novel_interface.show_text_only("Hm. Hat Aya etwas über das Hacken von Gehirnen erwähnt? Kann mich nicht erinnern. Ist mir egal.")
	novel_interface.show_character("ren_maid","smile")
	await novel_interface.show_dialog("Ich helfe dir! Ich werde dir auf jeden Fall helfen!\nÜberlassen Sie alles mir!","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ren.exe funktioniert nicht mehr. Ich würde zu allem, was sie von mir verlangt, Ja sagen. Sogar die Bombardierung des Senats...")
	novel_interface.show_character("ren_maid","blush")
	await novel_interface.show_dialog("Es ist okay. Ich bin genau hier.","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich bin schrecklich darin, andere zu trösten. Was nützt es ihr überhaupt, wenn ich „hier bin“? Wer weiß, aber sagen die Leute in solchen Situationen nicht normalerweise so etwas?")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Ja.","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("In meiner Umarmung nickt Skuld sanft.")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Ich glaube an dich. Du kannst es schaffen.","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Wirklich? Ich kann?")
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("Weil... du dieser besondere Mensch bist... in meinen Erinnerungen.","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","awkward")
	await novel_interface.show_dialog("Okay... warte, was?","Ren")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("(Ich, besonders? Hat mein Dienstmädchen-Outfit einen so großen Eindruck bei ihr hinterlassen?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld beruhigt sich ein wenig, trocknet ihre Tränen und schaut mit vertrauensvollen Augen zu mir auf.")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Ich kann dir alle meine Geheimnisse verraten.","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Wie... unerwartet. Ich habe keine Ahnung, wie ich reagieren soll.")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Es fällt Ihnen vielleicht schwer, es zu glauben, aber hören Sie bitte zu.","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Das kleine, zerbrechliche Mädchen vor mir wird plötzlich nüchtern und ich kann nicht anders, als mich vorzubeugen und fühle mich ganz ernst.")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("Ich habe eine... wirklich besondere Fähigkeit.","Skuld")
	await novel_interface.show_dialog("Ich kann mich an Dinge erinnern, die noch nicht passiert sind ... oder sollte ich sagen ... es gibt einige Dinge, die noch nicht passiert sind, aber ich kann sie bereits sehen, wie Erinnerungen.","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","upset")
	await novel_interface.show_dialog("Erinnerungen... die noch nicht passiert sind?","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("Diese Fragmente existierten von Anfang an in meinen Erinnerungen, sodass ich nicht einmal sagen kann, welche Erinnerungen aus der Vergangenheit und welche aus der Zukunft stammen.","Skuld")
	await novel_interface.show_dialog("Ich muss es sehen, um sicherzugehen.","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","gratified")
	await novel_interface.show_dialog("Es ist also so etwas wie eine Prophezeiung?","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Das hört sich zwar unglaublich an, aber ich habe in diesen paar Monaten so viel Verrücktheit erlebt, dass ich mich bereits daran gewöhnt habe, vor dem Frühstück sechs unmögliche Dinge zu glauben.")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Es ist so etwas wie... eine Süßigkeit. Ein bisschen süß, ein bisschen sauer, hinterlässt beim Schmelzen einen minzigen Geschmack im Mund.","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("Hm, ich habe diese Art von Süßigkeiten schon einmal gegessen, aber ich bin mir nicht sicher, wann ...","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("Das stimmt!","Skuld")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Sie können im Detail beschreiben, wie die Süßigkeit schmeckt, aber Sie können nicht sagen, wann oder wo Sie sie probiert haben.","Skuld")
	await novel_interface.show_dialog("„Oh, das ist es“ wird einem erst dann klar, wenn man es eines Tages wirklich probieren kann.","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ich glaube, ich fange an zu verstehen. Wenn in Ihren Erinnerungen sowohl Fragmente vorhanden sind, die aus der Vergangenheit als auch aus der Zukunft stammen können, ist es schwer zu sagen, welches welches ist.")
	await novel_interface.show_text_only("Um genau zu sein geht es nicht darum, in die Zukunft zu sehen. Weil sie nicht erkennen kann, welche Erinnerungen aus der Zukunft stammen.")
	novel_interface.show_character("ren_maid","worry")
	await novel_interface.show_dialog("(Moment... aber mit ein paar Hinweisen in der Umgebung würde sie es doch sicher herausfinden können?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Es ist, als würde Skuld meine Gedanken lesen. Sie erklärt:")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Sie denken vielleicht: Es ist wahr, dass Sie vielleicht nicht sagen können, ob im nächsten Monat oder im letzten Monat etwas passiert ist, aber die Umgebung wird in zehn Jahren in der Zukunft sicherlich ganz anders aussehen als jetzt, oder?","Skuld")
	await novel_interface.show_dialog("Aber Erinnerungen... sie sind nicht wie Videoaufnahmen. Alles, was wir bekommen, sind Fragmente ...","Skuld")
	await novel_interface.show_dialog("Unser Gehirn kann die gesamte Szene einer Erinnerung nur dann wieder aufbauen, wenn wir uns sehr darauf konzentrieren, wissen Sie?","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Es macht Sinn. Ich erinnere mich an diese Zeile aus einem Film:")
	await novel_interface.show_text_only("„Erinnerungen sind Interpretationen, keine Aufzeichnungen.“")
	novel_interface.show_character("skuld","think")
	await novel_interface.show_dialog("Daher ist es eigentlich gar nicht so einfach, Fragmente in meinen Erinnerungen zu finden, die es mir ermöglichen, den Zeitrahmen genau zu bestimmen.\nAußerdem...","Skuld")
	novel_interface.change_expression("thought")
	await novel_interface.show_dialog("Normalerweise vertieft man sich nicht ohne Grund in seine Erinnerungen, oder?","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","worry")
	await novel_interface.show_dialog("Hmm?","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Du wirst dich zum Beispiel doch nicht nur zum Spaß an den Mathematikunterricht in der Grundschule erinnern und daran, was der Lehrer an die Tafel geschrieben hat, oder?","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Natürlich. Matheunterricht...Lehrer...sicherlich kein Spaß.")
	novel_interface.show_character("ren_maid","gratified")
	await novel_interface.show_dialog("Ich glaube dir, es ist einfach... wow. Das ist unglaublich.","Ren")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Warte. Also, das „Ich“ in Ihren Erinnerungen, das Sie gerade erwähnt haben ...","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld nickt.")
	novel_interface.show_character("skuld","painful")
	await novel_interface.show_dialog("Wie auch immer, es gibt nur eine Sache in meinen Erinnerungen, von der ich mir sicher bin, dass sie in der Zukunft passiert ist.","Skuld")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Shot/Soul_Sacrifice.png")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("Ich halte den Atem an. Ich habe plötzlich das Gefühl, dass ich erraten kann, was sie meint ...")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("... Es ist eine Erinnerung an den Moment, in dem die Welt untergeht.","Skuld")
	await novel_interface.show_dialog("Aber in dieser Erinnerung bist du ein Junge.","Skuld")

	print("=== 创伤反射篇第06话结束 ===")
	await novel_interface.end_story_episode(0.5)
