# traumareflex_ep02.gd - 创伤反射篇第02话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放创伤反射篇第02话剧本
	traumareflex_ep02_script()

func play_script():
	pass

# 创伤反射篇第02话 - 正式剧本
func traumareflex_ep02_script():
	novel_interface.change_background("res://assets/images/bg/other/BG_City_street3.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("<Quinta Città Accademia, Campus East Rd.>")
	await novel_interface.show_text_only("La notte si sta avvicinando rapidamente nel vivace quartiere degli affari. Si aggirano gli studenti vestiti con le uniformi dell'accademia privata della zona.")
	await novel_interface.show_text_only("Una ragazza, vestita con abiti da cameriera, si fa strada a passo spedito tra la folla.")
	await novel_interface.show_text_only("Dato che c'è un maid café aperto 24 ore su 24, 7 giorni su 7, nella strada di fronte, il suo abbigliamento non attira molta attenzione.")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("Signorina Skuld! Rallentare! È pericoloso!","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("Forza, smettila di assillare!\nLasciami godermi in tutta tranquillità i miei pochi secondi di libertà!","Skuld")
	novel_interface.character_dark()
	await novel_interface.show_text_only("La ragazza bionda volteggia su se stessa, sorridendo come il sole.")
	novel_interface.character_light(0.35,"normal")
	await novel_interface.show_dialog("Rilassati!\nQuesto è il posto più sicuro al mondo. Inoltre...","Skuld")
	novel_interface.change_expression("proud")
	await novel_interface.show_dialog("Ho Fabella a proteggermi!","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella finalmente raggiunge la sua piccola padrona e sospira vedendo quanto sembra energica la ragazzina.")
	novel_interface.show_character("fabiola_maid","smile")
	await novel_interface.show_dialog("Pochi secondi di libertà, eh...","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Per una ragazzina spesso chiusa in casa dal padre iperprotettivo, New Opulentia è davvero il posto più sicuro in cui potrebbe stare. Non è come Newmoridas, dove tutti i residenti hanno la licenza di portare armi, o Salmonton, con le sue strade squallide piene di rifugiati e vagabondi.")
	await novel_interface.show_text_only("Oggi anche le Isole Lebona ospitano bande di spicco che vi si erano trasferite durante la guerra.")
	novel_interface.change_background("res://assets/images/bg/Shot/storyBGPol.png")
	await novel_interface.show_text_only("Inoltre, poiché il prossimo mese si terrà a New Opulentia il Forum Internazionale della Pace, la sicurezza in tutta la città è stata aumentata.")
	await novel_interface.show_text_only("Fabella ha finalmente la possibilità di uscire con la sua padroncina senza bisogno di portare con sé un'arma automatica.")
	novel_interface.change_background("res://assets/images/bg/other/BG_City_street3.png")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("Sì, è sicuro qui, ma devi comunque stare attento al traffico! E non allontanarti dalla mia vista—","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("Capito, capito!","Skuld")
	novel_interface.character_dark()
	await novel_interface.show_text_only("La bionda interrompe la frase di Fabella con un balzo in avanti e strofinando il viso sul petto della cameriera.")
	novel_interface.character_light(0.35,"perspire")
	await novel_interface.show_dialog("Oh, tu! Indossi un giubbotto antiproiettile anche adesso?","Skuld")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("Non è un po' restrittivo?\nDovresti lasciare respirare le tue tette!","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_maid","blush")
	await novel_interface.show_dialog("Respirare?","Fabella")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("Va bene, smettila...\n(Sussurri) Non farlo in pubblico...","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("Heehee, sapevo che Fabella è la migliore! Grazie per avermi infastidito i ragazzi dell'ambasciata e avermi aiutato a svignarmela!","Skuld")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("fabiola_maid","normal",0.25)
	await novel_interface.show_dialog("Il vecchio Haggerty ci ucciderà quando torneremo...\nComunque, la persona che stiamo cercando apparirà davvero in questa zona?","Fabella")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Penso di sì. L'ultima volta allo Sky Hotel, ricordo di aver avuto questa sensazione davvero forte... \"Ecco, è quello\".","Skuld")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Intendi quella cameriera goffa?","Fabella")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Quello che cerco dovrebbe essere un maschio, però...","Skuld")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Beh...\nIn realtà anche i ragazzi possono vestirsi da cameriere, sai...","Fabella")
	novel_interface.character_light(0.35,"perspire")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Eh?","Skuld")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("Vedi, in realtà, a molti ragazzi piace vestirsi con abiti femminili...","Fabella")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ooh?","Skuld")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"laugh")
	await novel_interface.show_dialog("Indossano anche accessori carini e trucco. Quanto è adorabile?","Fabella")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Oh! E?","Skuld")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Alcuni possono anche parlare con voci acute e femminili. Molti di loro hanno un enorme seguito online!","Fabella")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Fabella è così emozionata che la sua voce quasi le trema.")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Oh, ricordo di aver già visto delle foto tra i tuoi preferiti di Instagram.","Skuld")
	novel_interface.change_expression("pleased")
	await novel_interface.show_dialog("In tal caso, forse la cameriera che abbiamo visto non era una ragazza, ma un ragazzo vestito come tale...","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La ragazza bionda sembra assorta nei suoi pensieri.")
	novel_interface.show_character("fabiola_maid","panic")
	await novel_interface.show_dialog("Ehm... ehi!","Fabella")
	novel_interface.change_expression("blush")
	await novel_interface.show_dialog("Signorina Skuld, lasci stare il mio telefono!","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","stare")
	await novel_interface.show_dialog("Andiamo, il tuo telefono ha una connessione crittografata, quindi la gente di papà non potrà accedervi. Inoltre, la tua password è così facile da indovinare!","Skuld")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Non ti ho mai chiesto di impostare il mio compleanno come password!","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld fa una smorfia a Fabella, poi si gira.")
	await novel_interface.show_text_only("Lei fissa il cielo serale, tinto di rosso dal sole che tramonta, con uno sguardo lontano, un po' deluso.")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("Comunque, non importa che sia un maschio o una femmina, immagino che sia troppo tardi per trovarli oggi.","Skuld")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Almeno possiamo goderci l'aria fresca qui fuori, giusto?","Skuld")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("fabiola_maid","normal",0.25)
	await novel_interface.show_dialog("Allora... andiamo a casa adesso?","Fabella")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("C'è un altro posto che voglio visitare. È vicino all'ambasciata. Venga con me?","Skuld")
	await novel_interface.show_dialog("Ricordi padre Anton della Chiesa della Trinità?","Skuld")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Credo che ci siamo incontrati solo una volta... è lui quello di Newmoridas che ascoltava sempre le tue confessioni fin da quando eri piccolo, vero?","Fabella")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Sì. Ieri mi ha mandato un messaggio che diceva:","Skuld")
	await novel_interface.show_dialog("“Chiesa commemorativa della Nuova Opulentia”","Skuld")
	novel_interface.character_light(0.35,"thought")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("L'ho chiamato con il tuo telefono, ma non ha risposto. Sono un po' preoccupato, quindi ho pensato che avrei dovuto visitare la chiesa che ha menzionato...","Skuld") #换行问题
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Uhm. La chiesa si trova nella Zona Demilitarizzata Convenzionata ed è anche vicina all’Ambasciata, quindi probabilmente è sicura.","Fabella") #文字错误
	novel_interface.change_2nd_expression("perspire")
	await novel_interface.show_dialog("Ma ehi, quando l'hai chiamato con il mio cellulare? E non ho nemmeno notato... quanto poco professionale da parte mia...","Fabella")
	novel_interface.character_light(0.35,"perspire")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ah, non essere così duro con te stesso!\nEri impegnato a cucinare!","Skuld")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Un piccolo sorriso si insinua sul volto di Skuld al pensiero della cucina di Fabella.")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Church_Dusk.png")
	novel_interface.change_music("res://assets/audio/music/Sunset.mp3")
	await novel_interface.show_text_only("I due arrivano davanti a una chiesa in pietra di colore marrone, le cui pareti esterne sono coperte da un enorme murale religioso.")
	await novel_interface.show_text_only("C'è una croce in cima al tetto, che sembra dignitosa e solenne. Diverse cupole con intagli intricati emanano un'aura grandiosa e maestosa.")
	novel_interface.show_character("fabiola_maid","normal")
	await novel_interface.show_dialog("Non sapevo che vicino all'Ambasciata ci fosse una chiesa così grande.","Fabella")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("skuld","normal",0.25)
	await novel_interface.show_dialog("New Opulentia è una specie di città accademica, vedete. È tutta una questione di scienza, quindi non ci sono molte costruzioni religiose da queste parti.","Skuld")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Fabella passa la sua mappa elettronica alla Vista Satellite, incuriosita dalla struttura topografica e dall'architettura della zona.")
	await novel_interface.show_text_only("È un'abitudine che aveva coltivato nella squadra operativa speciale.")
	novel_interface.show_character("fabiola_maid","thinking")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("skuld","normal",0.25)
	novel_interface.character_dark()
	await novel_interface.show_dialog("Strano. Una chiesa così grande, eppure non c’è nessun modello sulla mappa. Esiste una sorta di restrizione per edifici come questo in territorio internazionale?","Fabella")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("Probabilmente è perché la chiesa non era nemmeno stata aperta fino a poco tempo fa. Deve essere costruito per il Forum del mese prossimo. Vedere? I murali sembrano ancora nuovi.","Skuld")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Tuo padre sarà qui il mese prossimo, giusto? Come membro del Comitato.","Fabella")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("Penso di sì. Comunque entriamo!","Skuld")
	await novel_interface.hide_all_characters()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Church.png")
	await novel_interface.show_text_only("Entrando in chiesa è come entrare nel santuario più antico del mondo.")
	await novel_interface.show_text_only("Le pareti sono interamente di marmo. Colonne colossali si ergono cupamente. I dipinti ad olio sul soffitto a cupola e le circostanti finestre a mosaico colorate creano un'atmosfera di santità e pace.")
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("Sbrigati! Aspetto! Aspetto! Questo posto è strutturato proprio come la Chiesa della Trinità!","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_maid","panic")
	await novel_interface.show_dialog("W-aspettami!","Fabella")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Skuld saltella qua e là, bevendo con gioia ogni dettaglio, mentre Fabella rimane vigile, tenendo aperto il cancello d'ingresso.")
	novel_interface.character_light(0.35,"normal")
	await novel_interface.show_dialog("(Ci sono ancora delle rastrelliere di legno laggiù sulle scale...)","Fabella")
	await novel_interface.show_dialog("(Questa chiesa deve essere ancora in costruzione.)","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella fa qualche passo avanti. L'aria intorno a lei vibra, quasi impercettibilmente, ma c'è. Tutti i suoi capelli sono ritti, come se fossero colpiti dall'elettricità statica.")
	await novel_interface.show_text_only("È sempre stata molto sensibile al pericolo, a causa degli anni della sua infanzia sui campi di battaglia in Sud America.")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("(Aspetta... qualcosa non va...)","Fabella")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("A pochi passi da Fabella, Skuld improvvisamente tace. Lei resta radicata sul posto, con le mani che cadono inerti lungo i fianchi.")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("Maledizione! Dobbiamo andarcene!","Fabella")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Church_Stained_Glass1.png")
	await novel_interface.show_text_only("In un attimo, la vista di Fabella si offusca. I colori dei vetri delle finestre, raffiguranti storie bibliche, sembrano brillare più luminosi, invadendo tutti i suoi sensi.")
	await novel_interface.show_text_only("I colori distorcono, torcono, affollano la sua visione come uno sciame di api.")
	await novel_interface.show_text_only("La luce arancione proveniente dal sole al tramonto all'esterno si contorce e si deforma, sciogliendosi gradualmente in un colore completamente diverso.")
	await novel_interface.show_text_only("Tutto sembra fondersi insieme, penetrando nel naso e nelle orecchie di Fabella, come un fruscio sinistro che si avvicina con una velocità allarmante.")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Church.png")
	await novel_interface.show_text_only("Fabella cerca disperatamente di concentrarsi.")
	await novel_interface.show_text_only("Non le schiarisce molto le idee, ma riesce ad aprire gli occhi con forza, solo per vedere che Skuld è crollato sul tappeto non molto lontano da lei.")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("Maledizione!","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Nel momento in cui alza un piede, cercando di raggiungere la sua padroncina, le sue gambe cedono.")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("...non riesco a vedere...","Fabella")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Church_Stained_Glass2.png")
	await novel_interface.show_text_only("Le finestre a mosaico si avvolgono e si contorcono, sempre più vicine, come un dipinto ad olio che si scioglie in un lampo di colori.")
	await novel_interface.show_text_only("Gli oggetti raffigurati nei dipinti a mosaico sembrano riorganizzarsi in posizioni bizzarre.")
	await novel_interface.show_text_only("Il corpo della cameriera ondeggia, l'incoscienza si avvicina rapidamente e la colorata invasione nella sua mente continua.")
	await novel_interface.show_text_only("La luce che penetra dalla finestra proietta ombre sul terreno, inghiottendo centimetro dopo centimetro gli ultimi sensi.")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Church.png")
	await novel_interface.show_text_only("Fabella si rannicchia all'improvviso, estrae un pugnale da dentro un pugnale.")
	await novel_interface.show_text_only("Essa mira ad un punto senza arterie principali, e senza un secondo di esitazione si pianta il pugnale nella coscia.")
	await novel_interface.show_text_only("Il sangue fresco tinge di rosso la pelle chiara della ragazza, ma almeno l'esplosione di dolore le regala qualche secondo di lucidità.")
	await novel_interface.show_text_only("Stringendo i denti, Fabella inciampa al fianco di Skuld e prende in braccio la bambina.")
	await novel_interface.show_text_only("Lei si volta e fa qualche passo barcollante in avanti.")
	await novel_interface.show_text_only("Mirando all'ingresso principale, dove c'è ancora luce, lancia Skuld fuori dall'edificio con ciò che resta della sua forza di volontà prima che l'oscurità la colga.")
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("Almeno adesso è al sicuro, pensa Fabella. Poi i suoi occhi si chiudono, cedendo finalmente all'ombra.")

	print("=== 创伤反射篇第02话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
