# traumareflex_ep15.gd - 创伤反射篇第15话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放创伤反射篇第15话剧本
	traumareflex_ep15_script()

func play_script():
	pass

# 创伤反射篇第15话 - 正式剧本
func traumareflex_ep15_script():
	novel_interface.change_background("res://assets/images/bg/Fabiola/Anton's_Blindness.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("La ceguera de Antón.")
	await novel_interface.show_text_only("Una enfermedad en la que el paciente, aunque ciego, persiste en creer que todavía puede ver.")
	await novel_interface.show_text_only("Aunque el paciente puede tener pequeños hematomas en las extremidades por chocar contra cosas, aún así se le ocurrirán diferentes razones para explicarlo.")
	await novel_interface.show_text_only("Así es como funciona el cerebro. Forja nuevos recuerdos para proporcionar una explicación a cosas que no puede entender.")
	await novel_interface.show_text_only("Ésa es una especie de instinto de autoconservación que tenemos cuando nos enfrentamos a lo desconocido.")
	await novel_interface.show_text_only("¿Quizás sea porque simplemente aún no estamos preparados para enfrentar la oscuridad detrás de los cielos estrellados?")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Factory.png")
	await novel_interface.show_text_only("Mmm. Si esas arañas no fueron enviadas por la gente de Rina...")
	await novel_interface.show_text_only("Entonces ¿de dónde vinieron? Armas mecánicas, a tan gran escala, aparecen dentro de la Segunda Ciudad Academia así como así. Inaudito.")
	novel_interface.show_character("ren_mercenary","upset")
	await novel_interface.show_dialog("(¿Quizás alguien más también ha traído ciertos elementos a este recuerdo? ¿No solo yo?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("O tal vez no sea alguien, sino… algo con voluntad propia.")
	await novel_interface.show_text_only("Recuerdo, antes de que comenzara esta misión...")
	await novel_interface.show_text_only("…")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Hospital_Passage.png")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Skuld nos dijo que Fabella es una bruja de fuego. Poseído por la magia del fuego.","Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","stare")
	await novel_interface.show_dialog("¿Poseído?","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Fabella no es como Elluka, que puede controlar los campos eléctricos directamente. Su situación es más como... “cierta información poderosa” ha elegido poseerla.","Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("Estás hablando como si la información tuviera voluntad propia.","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("Lo hacen. Si una cadena de información tiene una densidad lo suficientemente alta y un valor de entropía lo suficientemente bajo, puede ganar voluntad.","Aya")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("Cuando Fabella perdió el conocimiento, la “información viva” comenzó a apoderarse de su cuerpo...","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("…")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Información viva... tomando el control...")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Factory.png")
	novel_interface.show_character("ren_mercenary","solemn")
	await novel_interface.show_dialog("¿Puede ser?","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("¿Esas arañas robot son creadas por ese “algo” que posee a Fabella?")
	await novel_interface.show_text_only("¿Y por eso tengo que presentarme, para evitar que esa “información con voluntad” tuerza los recuerdos de Fabella?")
	await novel_interface.show_text_only("Pero parece que lo he intentado muchas veces y he seguido fallando.")
	novel_interface.show_character("ren_mercenary","upset")
	await novel_interface.show_dialog("(¿Cómo debería lidiar con esos errores entonces?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Nervioso, rebusco entre mi equipo. Si cada objeto en mí tiene un propósito...")
	await novel_interface.show_text_only("El único que aún no he usado es el pequeño kit de emergencia.")
	novel_interface.show_character("ren_mercenary","sob")
	await novel_interface.show_dialog("(No puede hacer mucho excepto, ya sabes, “recuperar HP mínimo”, aunque... se considera bastante inútil en esos juegos de zombies...)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Paso mis dedos sobre la bolsa en forma de cubo suavemente empaquetada en mi mochila.")
	novel_interface.show_character("ren_mercenary","shy")
	await novel_interface.show_dialog("(Espera...)\n(Esto se siente como...)","Ren")
	await novel_interface.hide_character()

	# 战斗部分剧本
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Dispara, esos bichos están llegando.","Russel")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/War Drum.mp3")
	await novel_interface.show_text_only("Sigo los sonidos de hundimiento y veo más de una docena de arañas escalando el hueco del ascensor. Detrás de ellos vienen más.")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("¡Todos, en su lugar!","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("El escuadrón inmediatamente entra en modo batalla y comienza a disparar.")
	await novel_interface.show_text_only("Fabella carga su escopeta con una mano y agarra una daga con la otra. Utiliza su antebrazo izquierdo como soporte para el arma mientras apunta.")
	await novel_interface.show_text_only("Elimina dos arañas con dos tiros limpios, luego destroza una tercera con su daga y su pie izquierdo, abrumada por la rabia hacia aquellos monstruos que se llevaron a su amiga.")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("¡Me estoy quedando sin munición!","Cassel")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Russel le lanza una revista a Cassel.")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Este es el último. Vaya a revisar los estantes de almacenamiento y vea si hay algo utilizable.","Russel")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Cassel asiente, recarga su arma y sigue retrocediendo mientras continúa disparando, hasta que desaparece detrás de una fila de estantes de almacenamiento.")
	novel_interface.show_character("ren_mercenary","serious")
	await novel_interface.show_dialog("¡Skuld, ponte detrás de mí!","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Agarro con fuerza mi metralleta y la cambio al modo de disparo único.")
	novel_interface.show_character("ren_mercenary","solemn")
	await novel_interface.show_dialog("(Solo me quedan alrededor de una docena de balas...)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("¡Oye, Russel, adivina lo que encontré!\nUna caja entera de vodka destilado polaco, de quince años.","Cassel")
	await novel_interface.show_text_only("Cassel suena extraordinariamente emocionado.")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Idiota, ¿estás intentando hacer un cóctel molotov?","Russel")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Creo que funcionaría. Dice 96% de contenido de alcohol... seguramente no es para beber.","Cassel")
	novel_interface.show_character("ren_mercenary","solemn")
	await novel_interface.show_dialog("Rina dijo que esas arañas detectan sus objetivos al sentir el calor.","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("Los cócteles molotov no son tan sencillos de preparar.","Fabella")
	await novel_interface.show_dialog("Primero debes sellar la abertura de la botella, o probablemente te quemarás. Y necesitas algo que pueda absorber agua, como una tira de tela, para usarlo como mecha.","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella ya ha derribado alrededor de diez arañas, pero están entrando más por las puertas del ascensor.")
	await novel_interface.show_text_only("Nos estamos quedando sin munición y no tenemos más remedio que retroceder, acercándonos.")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Todos nuestros conjuntos están hechos de fibra impermeable. ¿Dónde encontramos telas que puedan absorber líquidos? ¿Tenemos que quedarnos en ropa interior o algo así?","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","perspire1")
	await novel_interface.show_dialog("¡E-oye, prueba esto!","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Le lanzo mi “pequeña mochila de emergencia” a Cassel antes de darme la vuelta y correr hacia las colinas.")
	await novel_interface.show_dialog("¿Eh? ¿Qué es esto?","Cassel")
	await novel_interface.show_dialog("Serie F... paquete de 18... alta transpirabilidad, sin agente fluorescente...","Cassel")
	novel_interface.show_character("ren_mercenary","shy")
	await novel_interface.show_dialog("¡Deja de leerlo en voz alta!","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Período de menstruación... para pieles sensibles... 250 mm de largo...\n¿Puede ser...?","Cassel")
	novel_interface.show_character("ren_mercenary","shy_left")
	await novel_interface.show_dialog("¡Vamos, idiota, no lo leas en voz alta!","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","mock")
	await novel_interface.show_dialog("Ah, ya veo lo que es. Es perfecto.","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella me envía una mirada significativa.")
	await novel_interface.show_dialog("¡Oh, esto es maravilloso!\nIncluso se hincha un poco después de absorber agua. ¡Sellará la botella a la perfección!","Cassel")
	novel_interface.show_character("ren_mercenary","sob")
	await novel_interface.show_dialog("(¿De verdad tienes que entrar en detalles? Vamos...)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("…")
	await novel_interface.show_text_only("Pronto, Cassel reaparece detrás del estante con sus cócteles Molotov recién creados.")
	await novel_interface.show_text_only("Siguiendo las órdenes de Fabella, mantenemos a Cassel cubierto mientras todos nos movemos como uno solo hacia el ascensor.")
	await novel_interface.show_text_only("Lanza algunos cócteles Molotov y la entrada del ascensor arde en llamas.")
	await novel_interface.show_text_only("Eliminamos el resto de arañas con la munición y armas cuerpo a cuerpo que nos quedan.")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Deberíamos estar bien por ahora...","Russel")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Russel tiene varios rasguños en el codo y Cassel tiene una herida en una pierna.")
	await novel_interface.show_text_only("Fabella finalmente se calma un poco después de la caótica batalla. Ella se acerca a mí y me da una palmadita en la espalda en silencio.")
	novel_interface.show_character("ren_mercenary","shy")
	await novel_interface.show_dialog("(¿Q-qué quiere decir con eso?)","Ren")
	await novel_interface.show_dialog("(¿Y por qué sonríe como si supiera algo?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Solo me quedan dos balas en mi cargador.")
	await novel_interface.show_text_only("Aunque estamos a salvo por ahora, realmente no me queda ningún elemento útil.")
	novel_interface.show_character("ren_mercenary","upset")
	await novel_interface.show_dialog("(Quizás en la, eh, última ronda, yo... ¿morí aquí?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Miro ansiosamente las llamas anaranjadas que devoran la entrada del ascensor, y me pregunto...")
	await novel_interface.show_text_only("¿Cuál es el sentido de esta situación del día de la marmota?")
	await novel_interface.show_text_only("No importa cuantas veces repita esta experiencia...cuantos gadgets nuevos traigo conmigo...")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("¿Todavía moriré una y otra vez?")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Hospital_Passage.png")
	await novel_interface.show_text_only("…")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Lo que debes hacer es encontrar información clave en los recuerdos del objetivo. No dejes ninguna piedra sin remover.","Mariru")
	await novel_interface.show_dialog("El objetivo se encuentra actualmente en lo alto de la escala de coma. No sabemos mucho sobre su pasado, por lo que no estamos seguros de en qué parte de su memoria está atrapada actualmente.","Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("Lo que significa que debes prestar atención a cada detalle... ¡incluso si tu objetivo está en la ducha!","Aya")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("Espera. ¿Cuándo ocurrió esta conversación? ¿En el hospital? ¿En la sede del SID?")
	await novel_interface.show_text_only("Mi memoria se está volviendo borrosa...")
	await novel_interface.show_text_only("¿Cuál fue esa “información clave” que mencionó Mariru?")
	await novel_interface.show_text_only("¿Mencionó siquiera este término?")
	await novel_interface.show_dialog("Señorita Ren...","Skuld")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Factory.png")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("¡Señorita Ren!","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld tirando de mi manga me devuelve a la realidad.")
	novel_interface.show_character("ren_mercenary","gratified")
	await novel_interface.show_dialog("¿Mmmm?","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Esa cosa que le diste a Cassel... ¿Qué es eso?","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Pregunta Skuld, estudiando la bolsa de forma cuadrada en sus manos con ojos puros e inocentes.")
	novel_interface.show_character("ren_mercenary","shy")
	await novel_interface.show_dialog("Eh... es...","Ren")
	await novel_interface.show_dialog("(¡Dios me ayude! ¡No me preguntes esto delante de todos!)","Ren")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Tú… no tienes edad suficiente para eso, jaja.","Ren")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("(Tampoco tengo mucha experiencia en usarlo...)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Intento torpemente cambiar de tema. Realmente no quiero explicarle algo como esto a una niña tan joven...")
	await novel_interface.show_text_only("…")
	await novel_interface.show_text_only("Espera. Una niña tan joven...")
	novel_interface.show_character("ren_mercenary","upset")
	await novel_interface.show_dialog("(La primera vez que conocí a Skuld, ella era solo un poco mayor que Elluka).","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Pero este recuerdo debería ser de hace dos años. Las niñas de esta edad suelen cambiar mucho en dos años.")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_text_only("Pero este Skuld que veo frente a mí se ve exactamente igual al que vi en el hospital.")
	await novel_interface.show_text_only("Su vestimenta, peinado, altura, rostro, incluso el leve olor a leche en su cabello... exactamente igual.")
	await novel_interface.show_text_only("¿Yo... la “construí” según mis propios recuerdos?")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella solía ser líder de escuadrón de fuerza especial bajo Ritnalap, organización de inteligencia en la Segunda Ciudad Academia.")
	await novel_interface.show_text_only("Pero más tarde se convirtió en una sirvienta-guardaespaldas de Skuld.")
	await novel_interface.show_text_only("Si esta fuera la primera vez que se conocieran.. ¿qué pasó aquí exactamente?")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("¡Oye, esos insectos están entrando a raudales desde el techo!","Russel")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Russel grita de repente, señalando el techo.")
	await novel_interface.show_text_only("Varias pequeñas arañas robot se han escabullido desde el respiradero sobre el almacén.")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("¡Uf, odio los insectos!","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Continúo mirando este “Skuld” y ni siquiera me molesto en recoger un arma cuerpo a cuerpo para nuestra última batalla.")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("(Sigo trayendo nuevos elementos que necesito a este mundo...)","Ren")
	await novel_interface.show_text_only("Pero la que realmente se encarga de mantener a raya esa “información con voluntad” es la propia Fabella.")
	await novel_interface.show_text_only("La clave para cambiar el rumbo ya había aparecido antes de que lo hiciera la primera araña robot, ¿verdad?")
	await novel_interface.show_text_only("Ese objeto... parecía estar demandando mi atención, instándome a tocarlo...")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Factory.png")
	novel_interface.show_character("ren_mercenary","solemn")
	await novel_interface.show_dialog("Skuld, déjame prestado esto por un momento.","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tomo la carpeta negra de piel de cocodrilo de Skuld y saco el antiguo manuscrito descolorido.")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("En el momento en que mi mano toca el papel, el texto y los patrones se tuercen y se transforman en algo completamente incomprensible.")
	await novel_interface.show_text_only("Si observo con atención, puedo distinguir cada runa. Pero ponlos todos juntos y no puedo entender nada.")
	novel_interface.show_character("ren_mercenary","solemn")
	await novel_interface.show_dialog("(Al igual que la primera vez que conocí a Elluka...)","Ren")
	await novel_interface.show_dialog("(Este manuscrito debe ser una página de un Grimorio...)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Las pequeñas arañas bajan saltando del techo y se arrastran hacia nosotros. Los miembros del escuadrón comienzan a golpearlos con postes de acero y palancas.")
	await novel_interface.show_text_only("Hago a Fabella a un lado en medio de todo el caos.")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("¡Oye! ¿Qué crees que estás haciendo?","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Simplemente tomo su mano y la coloco en la de Skuld.")
	novel_interface.show_character("ren_mercenary","solemn")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	await novel_interface.show_dialog("Realmente no puedo explicarlo ahora, pero lo entenderás en poco tiempo—","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Porque esto te pertenece. Es tu Grimorio.")
	await novel_interface.show_text_only("Tomaste la decisión de dejar que te poseyera hace dos años, la primera vez que conociste a Skuld.")

	# 重要的结局部分
	novel_interface.change_background("res://assets/images/bg/Fabiola/FactoryLF.png")
	await novel_interface.show_text_only("Pongo el manuscrito en la mano de Fabella. Al segundo siguiente, el papel descolorido se transforma en un rayo de luz cegadora.")
	await novel_interface.show_text_only("Una gigantesca esfera en llamas aparece en medio del almacén y lentamente desciende como una especie de aparición.")
	await novel_interface.show_text_only("La esfera disminuye gradualmente de tamaño a medida que desciende, y desaparece en el cuerpo de Fabella, convirtiéndose en parte de ella...")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Factory.png")
	await novel_interface.show_text_only("Una capa de llamas vivas envuelve el brazo de Fabella, pero no siento ningún calor, a pesar de que mi mano sostiene la de ella.")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("Fuego... magia...","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("De repente, un pequeño robot salta y se abalanza sobre Skuld.")
	await novel_interface.show_text_only("Fabella reflexivamente lo golpea directamente en el cuerpo. En menos de un segundo, la araña robot negra es devorada por una bola de llamas.")
	await novel_interface.show_text_only("Se rompe en innumerables componentes diminutos, que se reducen a cenizas incluso antes de tocar el suelo.")
	novel_interface.show_character("fabiola_battle","panic")
	await novel_interface.show_dialog("¿Qué es esto...?","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella mira las llamas en sus manos confundida. Se extendieron hacia afuera, formando una barrera a su alrededor.")
	await novel_interface.show_text_only("Cualquier araña que se atreva a acercarse a su periferia arde espontáneamente.")
	novel_interface.change_background("res://assets/images/bg/Fabiola/FactoryL.png")
	await novel_interface.show_text_only("La barrera en llamas continúa expandiéndose en alcance, como una imagen 2D quemada en un espacio 3D.")
	await novel_interface.show_text_only("Todo el espacio restante en el almacén parece brillar con una espeluznante luz blanca, como si estuviera encendido por llamas provenientes de un plano aún más alto.")
	await novel_interface.show_text_only("Ahí es cuando todas las pequeñas arañas parecen evaporarse—")
	await novel_interface.show_text_only("Y las paredes del almacén también se evaporan con ellos.")
	await novel_interface.stop_music()
	novel_interface.show_background("res://assets/images/bg/Fabiola/white_bg.png")
	await novel_interface.show_text_only("…")
	await novel_interface.show_text_only("Me duele la cabeza.")
	await novel_interface.show_text_only("Un dolor de cabeza realmente serio.")
	await novel_interface.show_text_only("Se siente como un saco de cemento en mi cerebro y alguien lo está removiendo. Se siente familiar...")
	await novel_interface.show_text_only("…")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Dementium.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_text_only("Abro los ojos y veo un objeto en forma de arco sobre mi cabeza. Lo reconozco como el dispositivo de piratería cerebral de Harima Tech.")
	novel_interface.show_character("ren_maid","upset")
	await novel_interface.show_dialog("¿Cuánto tiempo ha pasado...?","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Me froto los ojos y me levanto, bostezando mientras miro alrededor de la habitación. La ciudad sigue durmiendo fuera de la ventana.")
	await novel_interface.show_text_only("El nuevo anuncio del cuadragésimo quinto aniversario de la franquicia Becca Star es visible en lo alto de un rascacielos a lo lejos. El personaje principal rosa se eleva en el cielo azul, muy feliz y despreocupado.")
	await novel_interface.show_text_only("Giro la cabeza para mirar la cama del hospital al lado de la mía. La chica rubia duerme boca abajo, babeando sobre las sábanas.")
	await novel_interface.show_text_only("No puedo ver la expresión de Fabella ya que el equipo está en el camino, pero puedo ver su mano acariciando suavemente el suave cabello de Skuld.")
	await novel_interface.show_text_only("Intento mover un poco los brazos. Parece que he tenido un sueño realmente complicado. Mi cerebro no se siente nada bien descansado.")
	await novel_interface.show_text_only("Fabella se endereza, se lleva un dedo a los labios y me sonríe. Ella susurra:")
	novel_interface.show_character("fabiola_maid","mock")
	await novel_interface.show_dialog("Oye, tampoco te ves tan mal con medias blancas.","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","awkward")
	await novel_interface.show_dialog("... E-espera, ¿qué?","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Según el reloj en la pantalla, llevaba menos de dos horas dormido.")
	await novel_interface.show_text_only("Aya me había dicho que olvidaría todo lo que pasó durante mi sesión de piratería cerebral. Como si fuera sólo un sueño.")
	await novel_interface.show_text_only("Mariru se había asegurado de que así fuera.")
	novel_interface.show_character("ren_maid","stare")
	await novel_interface.show_dialog("(Fue solo un sueño, ¿verdad? ¡No es gran cosa!)","Ren")
	await novel_interface.hide_character()

	# 与此同时的场景
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("<Mientras tanto>")
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("<Conversación de canal cifrado, sala de control SID>")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("¿Entonces ya ha verificado a la persona real detrás de la cuenta cifrada electrónicamente? Eres rápido.","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Por supuesto. Está confirmado.","Voz Femenina")
	await novel_interface.show_dialog("Russel, Director del Departamento de Inteligencia de Ritnalap, todavía me debe una.","Voz Femenina")
	await novel_interface.show_dialog("De todos modos, ¿cómo conseguiste esta cosa?","Voz Femenina")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("Es un secreto comercial, ja.","Mariru")
	await novel_interface.show_dialog("De todos modos, estarás aquí para el Foro Internacional de Paz el próximo mes con los demás representantes del Comité, ¿verdad?","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Sí. ¿Quieres tomar una copa con tu viejo amigo?","Voz Femenina")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("¿No te preocupa emborracharte?","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Cállate.","Voz Femenina")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("Jaja. De todos modos, te veré entonces. —Akiko","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La conversación acaba de terminar y Mariru ya recibió otra invitación de videochat.")
	await novel_interface.show_text_only("Una mujer con una camisa blanca aparece en pantalla.")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("¿Cómo van las cosas?","Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("El embajador Haggerty de la Embajada de Newmoridas está feliz de seguir nuestros planes.","Beatrice")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("Entonces todo va bien allí, ya veo.","Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular","smile2")
	await novel_interface.show_dialog("Sí. Esos niños seguro que son adorables.","Beatrice")
	await novel_interface.show_dialog("Especialmente ese Capitán Cassel...\nNi siquiera me había quitado el brazalete y él ya estaba súper ansioso.","Beatrice")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("Eres muy “persuasivo”, supongo.","Mariru")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("De todos modos, gracias por el arduo trabajo.","Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("No es gran cosa. Yo mismo pedí ser parte de esto.","Beatrice")
	await novel_interface.show_dialog("Es una situación en la que todos salimos ganando.","Beatrice")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Aparece una ventana que muestra imágenes de vigilancia de una sala de hospital.")
	await novel_interface.show_text_only("Skuld está llorando en los brazos de una Fabella completamente despierta, y Aya está sosteniendo a Ren en una cama, revisando sus signos vitales.")
	await novel_interface.show_text_only("Debajo del metraje hay un mensaje: \"¡Misión exitosa! Tanto el objetivo como el agente están ilesos física y mentalmente\".")
	await novel_interface.show_text_only("Mariru sonríe, satisfecha.")
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…")

	# 几天后的场景
	await novel_interface.show_text_only("<Unos días después>")
	novel_interface.show_background("res://assets/images/bg/APT/livingRoom_daytime.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.show_character("fabiola_maid","normal")
	await novel_interface.show_dialog("Entonces, ¿vamos a visitar tu escuela en un momento?","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Sí. Déjame cepillarme los dientes primero.","Ren")
	novel_interface.show_character("iluka_uniform","normal")
	await novel_interface.show_dialog("Señorita Ren, ¿por qué tarda tanto?","Elluka")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","perspire")
	await novel_interface.show_dialog("¡Está bien, aún nos quedan 90 minutos antes de la hora programada!\nY... y deberíamos cepillarnos los dientes después de comer, ¿no?","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld intenta defenderme, aunque ella misma está temblando.")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("¿Veo que no estás satisfecho con mi comida, Ren?","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Pregunta Fabella, sin siquiera molestarse en ocultar su tono amenazador.")
	await novel_interface.show_dialog("¡No! ¡No! ¡Cien por ciento satisfecho!","Ren")
	await novel_interface.show_text_only("Para agradecernos por sacarla del coma, Fabella nos trajo hoy su “plato súper especial”.")
	await novel_interface.show_text_only("Tentáculos de pulpo, tomates, pescados de aguas profundas, puerros… todos ellos, en un mismo cuenco.")
	await novel_interface.show_text_only("Rociado con una generosa cantidad de salsa morada pegajosa y pegajosa que sigue burbujeando.")
	await novel_interface.show_text_only("Tomé solo un bocado y me sentí como si estuviera parado junto al río Styx, listo para unirme a las filas de los muertos.")
	await novel_interface.show_text_only("He estado en el baño vomitando hasta las tripas durante los últimos veinte minutos. Puede que sea sólo mi imaginación, pero ese horrible sabor todavía persiste en mi boca.") #换行问题
	await novel_interface.show_text_only("¿Quizás permanecerá conmigo por el resto de mi vida?")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("¡Ren!","Annie")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("¿Eh?","Ren")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("En el futuro, cuando tomes fotografías como esta, recuerda sostener la cámara más lejos de ti, aproximadamente a la altura del pecho.","Annie")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("¿Qué fotos?","Ren")
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_dialog("¡Annie! ¡Quita tus manos de mi teléfono!","Ren")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Stockings.png")
	await novel_interface.show_text_only("Entro corriendo a la sala de estar y encuentro a Annie descansando en el sofá, jugando con mi teléfono.")
	await novel_interface.show_text_only("Y en la pantalla está la selfie que me tomé cuando practicaba con mi disfraz de sirvienta.")
	await novel_interface.show_text_only("Lo que es peor, Skuld, Fabella y Elluka se han acercado para verlo.")
	await novel_interface.show_text_only("¿Qué hice en mi vida pasada para merecer esto?")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom_daytime.png")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("¡Tu contraseña fue demasiado fácil de adivinar!","Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Annie comenta, luciendo orgullosa de sí misma.")
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("La próxima vez toma la foto como te enseñé. Tus piernas se verán más largas de esa manera.","Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_maid","laugh")
	await novel_interface.show_dialog("Sí. Y puedes subirte la falda más arriba. De todos modos, nadie podría ver debajo desde este ángulo.","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","stare")
	await novel_interface.show_dialog("Y también puedes probar algunas aplicaciones de retoque de selfies.","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","speechless")
	await novel_interface.show_dialog("¡Oh!","Elluka")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elluka sigue asintiendo, como si estuviera fascinada por todos los consejos para selfies de las mujeres mayores.")
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("Fue solo... un... chasquido... casual...","Ren")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("¿Por qué necesito todos estos consejos para selfies de todos modos?","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","relieve")
	await novel_interface.show_dialog("Ah, cierto, ¿tus padres aceptaron dejarte quedarte en New Opulentia?","Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","think")
	await novel_interface.show_dialog("Mariru convenció a Padre muy rápidamente. Parecía tan fácil...","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","bored")
	await novel_interface.show_dialog("(Definitivamente no fue fácil para tu padre...)","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("¡Además, la señorita Ren también ayudó mucho!","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld me muestra una sonrisa tan brillante como el sol.")
	novel_interface.show_character("fabiola_maid","normal")
	await novel_interface.show_dialog("Realmente no recuerdas nada, ¿eh?","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("Uh, todo estaba borroso... espera, ¿te acuerdas?","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_maid","smile")
	await novel_interface.show_dialog("Lo único que recuerdo es que tuve un sueño que me dejó una gran impresión. Y también me encontré con algunos viejos amigos en el sueño...","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella parece un poco melancólica ante eso.")
	novel_interface.show_character("fabiola_maid","laugh")
	await novel_interface.show_dialog("De todos modos, ¡eso ya es cosa del pasado!","Fabella")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Se necesitan quince minutos para caminar hasta tu escuela, ¿verdad?\nAún tenemos algo de tiempo...","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella se acerca al balcón y contempla la ciudad en expansión que hay allí.")
	novel_interface.show_character("fabiola_maid","normal")
	await novel_interface.show_dialog("La vista es agradable aquí.","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","smile")
	await novel_interface.show_dialog("Señorita Ren, quiero jugar un videojuego.\n¡Juguemos a Becca Star!","Elluka")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","gratified")
	await novel_interface.show_dialog("Aunque nos iremos pronto...\nEstá bien, está bien, está bien. ¡Vamos a jugar!","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("…")
	await novel_interface.show_dialog("¡Aaaah!","Fabella")
	await novel_interface.show_text_only("Fabella, que está en el balcón, de repente empieza a gritar.")
	novel_interface.show_character("ren_uniform","shout")
	await novel_interface.show_dialog("¿Qué pasa?","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_maid","blush")
	await novel_interface.show_dialog("¡Una araña!","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella grita, señalando la telaraña en la esquina del balcón. Saca una pistola de la pistolera que lleva en el muslo y apunta.")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("¡Fabella! ¡Esta es la casa de alguien! ¡No puedes usar armas aquí!","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("Vaya, ¿es un P226?\n¡Es genial!","Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","speechless")
	await novel_interface.show_dialog("¡Vaya, se ve genial!","Elluka")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("Ay, dame un respiro...","Ren")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("…")
	await novel_interface.show_text_only("Mientras Ren y el resto de ellos discuten, Skuld cierra los ojos.")
	await novel_interface.show_dialog("Ren…","Skuld")
	novel_interface.show_background("res://assets/images/bg/Fabiola/YumeRen.png")
	await novel_interface.show_text_only("Recuerdo haber visto tu cara después de un destello de luz blanca.")
	await novel_interface.show_text_only("Fue solo por menos de un segundo, pero nunca recuerdo mal.")
	novel_interface.change_background("res://assets/images/bg/Fabiola/YumeRen2.png")
	await novel_interface.show_text_only("Pero te ves un poco diferente...")
	await novel_interface.show_text_only("...por como te recuerdo.")

	print("=== 创伤反射篇第15话结束 ===")
	print("=== 创伤反射篇全部完成 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
