# traumareflex_ep09.gd - 创伤反射篇第09话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	traumareflex_ep09_script()

func play_script():
	pass

func traumareflex_ep09_script():
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("—What? The suspect’s dead?","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Our target had renovated his home into a whole fortress. And he’s been firing at the retrieval team like crazy with heavy weapons the moment they arrived.","SID Agent")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("Shouldn’t the retrieval team be equipped with non-lethal weapons only? Why’d the target die?","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("The team didn’t wound the target fatally.","SID Agent")
	await novel_interface.show_dialog("Instead, the target seems to have either died from an overdose of neuropharmaceuticals or blood loss.","SID Agent")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("... I see. You can go now.","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Yes, Boss.","SID Agent")
	await novel_interface.show_text_only("Mariru is flipping through the suspect’s files, looking very much annoyed, when Aya enters the control room.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Is Ren in now?","Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("Yeah. Everything seems pretty stable.","Aya") #文字错误
	await novel_interface.show_dialog("Is this the... autopsy results of the suspect?","Aya")
	await novel_interface.show_dialog("Antonio Jose Urquiza... a mafia warlord that used to be pretty active in South America during the Seven Years War. Right now, he’s no more than a minor gang leader.","Aya")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("Too bad the drugs pretty much fried his brains... or we could have tried to interrogate him with that device.","Aya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Aya murmurs as she flips through her stack of files.")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("South America... so the target really was Fabella, huh?","Aya")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("We can’t be sure yet.","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru shakes her head, face somber, as she studies the target profile displayed on the screen.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("A tiny number of radioactive markers have been detected in the chemical distribution device we found in the church.","Mariru")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("And from that, we easily found another location with the same radioactive markers... right inside New Opulentia.","Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","dizzy",0.25)
	await novel_interface.show_dialog("Oh? So it’s almost like the culprit isn’t even bothering to hide himself.","Aya")
	novel_interface.character_light(0.35,"angry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("That’s why I find this so suspicious...","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("Antonio... does this dude have a motive to hurt Fabella?","Aya")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Yup, and what a motive...","Mariru")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("In the second year of the war, the economy in South America collapsed. What happened next was that gangs took over the political scene with their conflicts and petty fights.","Mariru")
	await novel_interface.show_dialog("Fabella, who lost her parents in the war, was adopted by a colonel, and grew up in a strict military environment.","Mariru")
	await novel_interface.show_dialog("She soon sported animalistic combat instincts and became the youngest national guard in history.","Mariru")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("I heard that she sneaked into enemy territory once, alone, and silently assassinated the commander—who happened to be Antonio’s eldest son.","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wink")
	await novel_interface.show_dialog("Now that’s some motive indeed.","Aya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru calls up the portrait of a man, clad in military attire, and gestures at the screen.")
	novel_interface.show_character("liliu_research","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ai","wink",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("This was the colonel who adopted Fabella: Carlos Branco.","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"think")
	await novel_interface.show_dialog("You mean “Butcher of Churun River” Branco?","Aya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("The Churun River Massacre happened not long after the six Academy Cities formed the United Congress.")
	await novel_interface.show_text_only("46 thousand civilians were executed by the River, their blood dyeing the Salto Ángel Falls downstream red.")
	await novel_interface.show_text_only("It was all over the news those few weeks. Common opinion had it that Carlos Branco, the most powerful warlord then, was behind it all.")
	await novel_interface.show_text_only("The grotesque sights from the incident sparked widespread anti-war sentiments from the general public, and Branco was since then known as the Butcher of Churun River.")
	novel_interface.change_background("res://assets/images/bg/Shot/storyBGPol.png")
	await novel_interface.show_text_only("Soon, the United Congress took military measures against Carlos Branco, condemning him for his anti-humanitarian and racial crimes.")
	await novel_interface.show_text_only("Finally, a Lancer Penetrator blew up the cave Branco was hiding in—and thus bringing an end to the gang-monopolized era in South America.")
	await novel_interface.show_text_only("This put the United Congress in most people’s good books. They were seen by the general public as a symbol of peace and justice. Following their success, the six nations in the Congress had been renamed to Academy Cities.")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("—At least that’s the official version printed on history books.","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru smirks, and Aya nods understandingly.")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("After that, the six remaining warlords in South America simply disappeared all at once, as if they were under some kind of agreement. The United Congress soon took over their territory.","Aya")
	await novel_interface.show_dialog("You know what really happened, don’t you?","Aya")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Aya asks, leaning close to Mariru and nudging her waist with an elbow, like a curious kitty.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Yeah. The massacre really happened—but those who died came from the territories of the six warlords.","Mariru")
	await novel_interface.show_dialog("They agreed to ship those people to the river, and... you know what happened next.","Mariru")
	await novel_interface.show_dialog("Someone had bribed them into doing that.","Mariru")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("The only one who refused to accept the bribe was Carlos Branco.","Mariru")
	await novel_interface.show_dialog("That was how he received the role of the “necessary evil” in our current world.","Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","normal",0.25)
	await novel_interface.show_dialog("So the ones who bribed the warlords...","Aya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Aya stares, eyes wide. The answer is only too clear.")
	novel_interface.show_character("liliu_research","speak")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ai","think",0.25)
	await novel_interface.show_dialog("Those warlords who disappeared must have simply moved somewhere else, changed their names, and enjoyed the rest of their lives spending the money they received.","Aya")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("As for the proof to Branco’s guilt... it must have been forged for the security soldiers by the United Congress themselves.","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("If the United Congress realizes that Antonio’s back for revenge, they’d want to get this over with as soon as possible.","Aya")
	await novel_interface.show_dialog("No wonder this whole situation feels so awkward.","Aya")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Oh? Awkward how?","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"think")
	await novel_interface.show_dialog("The hallucinogens we found in the target’s blood is the same type as what we found on Fabella.","Aya")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("I knew that.","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("And we found a type of stimulant, the kind that the warlords often used to keep their soldiers alert. That was actually the real reason of Antonio’s death.","Aya")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("That’s in the report too.","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"think")
	await novel_interface.show_dialog("The stimulant makes whoever is injected with it hyper-sensitive. They’ll hear more, feel more.","Aya")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("…","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("There’s so much of it in his blood that, if he were hit by a rubber bullet, it’d probably hurt as much as being blasted with a cannon.","Aya")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("But during the twenty minutes or so when the two sides were firing at each other, the target was hit multiple times...","Mariru")
	await novel_interface.show_dialog("The target has been clearly visible since the fifth minute in the footage of the scene. And he never injected anything into himself.","Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("They also didn’t find any lesions in his nervous system during the autopsy.","Aya")
	novel_interface.change_2nd_expression("blush_dizzy")
	await novel_interface.show_dialog("D-does this mean that this guy really really enjoys pain? Wow, the ultimate masochist...","Aya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru swiftly rolls up some paper and smacks Aya on the head, like she’s been doing this all her life.")
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("Aw... anyway, did they find out who brought Skuld to the park yet?","Aya")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Whoever it was stayed away from all surveillance cameras. A textbook example of an excellent kidnapper.","Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("Someone familiar with the locations of surveillance cameras... and could walk around in the city with a girl on their back, without being seen as suspicious...","Aya")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("Yeah. These clues are all we have.","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru scratches her chin, deep in thought.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("If Antonio was actually a scapegoat, carefully chosen to act as the “culprit”...","Mariru")
	await novel_interface.show_dialog("Then whoever is behind it all is likely after Fabella—or, more specifically, her witch powers.","Mariru")
	await novel_interface.show_dialog("I don’t think they got what they wanted.","Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("But she’s quite a valuable specimen, so instead of killing her then and there, they decided to leave her there for the United Congress to capture...","Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("So that was why they used such a precious “scapegoat”?","Aya")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Well, she’s a witch possessed by fire magic, so...\nHmm, wait, “information with a will”...","Mariru")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("Information...?","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru’s shocked eyes meet Aya’s. They’ve come upon the same conclusion.")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("If what those kidnappers actually wanted was to steal the information from inside Fabella’s head...","Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("They might be using the same type of equipment we’re using too. Harima Tech had designed these brain-hacking devices based on some published papers available to the general public.","Aya")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("In that case, they’ve likely come across the same problem we did.","Mariru")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/TheWall.png")
	await novel_interface.show_text_only("The first four agents who attempted to hack into Fabella’s brain were met with the same endless wall.")
	await novel_interface.show_text_only("Like a firewall keeping intruders out.")
	await novel_interface.show_dialog("If it’s an offensive type of firewall—","Aya")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("Aya, get ready to wake Ren up as soon as I give the orders.","Mariru")

	print("=== 创伤反射篇第09话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
