# traumareflex_ep12.gd - 创伤反射篇第12话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放创伤反射篇第12话剧本
	traumareflex_ep12_script()

func play_script():
	pass

# 创伤反射篇第12话 - 正式剧本
func traumareflex_ep12_script():
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_Fighting2.png")
	novel_interface.change_music("res://assets/audio/music/War Drum.mp3")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Bonjour, Mademoiselle Ren.","Skuld")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("On se retrouve !","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","perspire1")
	await novel_interface.show_dialog("Hein ? Sku—","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Je me rattrape juste à temps, ravalant mes mots.")
	await novel_interface.show_text_only("Ces souvenirs datent d'il y a deux ans. Skuld et moi n’aurions pas encore dû nous rencontrer à l’époque.")
	novel_interface.show_character("ren_mercenary","stare")
	await novel_interface.show_dialog("(Pourrait-elle me connaître en raison de ses capacités prophétiques particulières ?)","Ren")
	await novel_interface.show_dialog("(Skuld a dit qu'elle se souvenait de m'avoir vu dans ses souvenirs...)","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Et tu es Fabella, n'est-ce pas ?\nEt Russel, Cassel...","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld se tourne vers les autres membres de l'escouade, le visage brillant et innocent.") #换行问题
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_dialog("Oh, est-ce que quelqu'un vous a appris nos noms ?\nLa fille de notre employeur est en effet une petite fille intelligente.","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","wry_smile")
	await novel_interface.show_dialog("(Haha, peut-être qu'elle n'est pas aussi compliquée que je le pensais.)","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Ravi de vous rencontrer !\nVous êtes beaucoup plus jolie que sur la photo—","Cassel")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Russel donne un coup de coude à Cassel dans les côtes pour le faire taire.")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Oh s'il vous plaît, ne pensez pas que je ne vous ai pas surpris en train de regarder les enchères.","Russel")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld éclate de rire devant le visage rouge de Cassel. L'atmosphère tendue s'allège un peu.")
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("Écoutez, nos troupes de soutien sont toujours retenues en dehors de la zone. Nous devrons trouver un moyen d’atteindre nous-mêmes le point d’évacuation.","Pernard")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_dialog("Nous fusionnons temporairement des équipes. Tout le monde suit les ordres du capitaine Pernard.","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella fait un signe de tête à Pernard, lui tend plusieurs chargeurs de fusil, tandis qu'elle prend elle-même un fusil de chasse.")
	novel_interface.show_character("ren_mercenary","worry")
	await novel_interface.show_dialog("(Ils semblent se faire confiance. Se sont-ils beaucoup battus ensemble ?)","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("Nous pourrions bientôt rencontrer d'autres hostiles. Tout le monde, faites l’inventaire maintenant. Voyez combien d'équipement et de munitions nous avons et faites votre rapport dans cinq minutes.","Pernard")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("J'ai déjà vérifié mon sac à dos. Il contient trois magazines, une petite trousse d’urgence et une bombe d’aérogel.")
	await novel_interface.show_text_only("C’est un peu comme de la laque. La mousse provenant du bidon se dilatera immédiatement et se figera dès qu’elle sera exposée à l’air.")
	await novel_interface.show_text_only("Annie l'a utilisé une fois pour sceller la porte d'une chambre d'amis du Sky Hotel.")
	await novel_interface.show_dialog("(Pourquoi est-ce dans mon sac...?)","Ren")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Street_Fighting2.png")
	await novel_interface.show_text_only("Pendant que tout le monde fait l'inventaire, Fabella entraîne Pernard à travers la rue.") #换行问题
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("Notre ennemi était vraiment préparé.","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("Ouais. Ils semblent avoir tout notre itinéraire tracé. Il a même réussi à évacuer les civils au moment idéal grâce à un faux avertissement.","Pernard")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("Ce qui signifie qu'ils savent quand l'enchère s'est terminée.","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("Combien d'ennemis avez-vous rencontrés après la destruction de la route ?","Pernard")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_dialog("Un tireur d'élite et un Tarin. Toi?","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("Trois tireurs d'élite, quatre drones équipés d'armes automatisées.","Pernard")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("C’est alors que Fabella remarque enfin les éclaboussures de sang sur le coupe-vent de Pernard. Elle demande nerveusement :")
	novel_interface.show_character("fabiola_battle","panic")
	await novel_interface.show_dialog("Il y en a tellement ? Êtes-vous blessé ?","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("Pas sérieusement. Rina est un excellent photographe, elle les a tous éliminés facilement.","Pernard")
	await novel_interface.show_dialog("Ils ont envoyé les tireurs d'élite dans des positions parfaites, même dans une zone avec tant de grands immeubles. Cela signifie qu'ils savent que le « bagage » est avec l'équipe Alpha.","Pernard")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella fronce les sourcils.")
	novel_interface.show_character("fabiola_battle","panic")
	await novel_interface.show_dialog("Mais ce gamin gâté n’a-t-il pas décidé dans quelle voiture monter seulement après la fin de l’enchère ?","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("Cela signifie que... l'un de nous pourrait avoir divulgué l'information.","Pernard")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Pernard et Fabella regardent en silence les quatre autres membres de l'équipe, plaisantant et riant, entourant la jeune fille blonde.")
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("L’ennemi doit la poursuivre, bien sûr, mais ils ne veulent probablement pas la tuer.","Pernard")
	await novel_interface.show_dialog("Ou alors, ils auraient pu le faire facilement une autre fois.","Pernard")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","bored")
	await novel_interface.show_dialog("... Alors ils veulent la kidnapper ?","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("Alors envoyez au moins une escouade terrestre ou un véhicule blindé.","Pernard")
	await novel_interface.show_dialog("Quoi qu'il en soit, évitez les espaces ouverts. Avancez dans l’ombre des bâtiments.","Pernard") #原文多字
	await novel_interface.show_dialog("Prenez soin de vous.","Pernard")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_dialog("Ouais, toi aussi.","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("De l'autre côté de la route, j'écoute Skuld et les trois autres discuter de la vente aux enchères à laquelle ils ont assisté ce soir.")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Ce manuscrit que vous avez acheté ce soir... il vous a coûté 36 millions ?","Cassel")
	await novel_interface.show_dialog("Mais n’est-ce pas juste un vieux parchemin stupide ? Qu’y a-t-il de si précieux là-dedans ? Vous avez tous les futurs numéros du loto dessus ou quelque chose comme ça ?","Cassel")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Oh s'il te plaît. Vous ne connaissez pas la valeur des reliques anciennes.","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","pleased")
	await novel_interface.show_dialog("Moi non plus, je ne connais pas grand-chose aux reliques. D’une manière ou d’une autre, j’avais vraiment le sentiment que je devais l’acheter.","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Ah, c'est ce que je ressens toujours quand je vois les derniers jeux de tir !","Cassel")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Cassel hoche la tête, avec compréhension.")
	novel_interface.show_character("ren_mercenary","wry_smile")
	await novel_interface.show_dialog("(Etes-vous sûr d'avoir vraiment compris ?)\n(Skuld a probablement acheté l'article à cause de quelque chose qu'elle a vu dans ses souvenirs...)","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("leena")
	await novel_interface.show_dialog("À bien y penser, de nombreuses écritures anciennes ont en effet été perdues après la guerre. J’ai entendu dire que quelqu’un avait même acheté le manuscrit d’Archimède il y a quelque temps pour des millions de dollars.","Rina")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Alors, c'est quoi ce parchemin que tu as acheté ?","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Il a déjà des milliers d’années selon la datation au carbone 14. C’est une sorte de recette écrite avec des runes anciennes, je pense. Je n'arrive pas non plus à le lire.","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("dit Skuld en nous montrant le papier décoloré, qu'elle garde dans un dossier exquis dans son sac en peau de crocodile noir.")
	novel_interface.show_character("ren_mercenary","perspire1")
	await novel_interface.show_dialog("(Est-il sécuritaire de nous montrer... juste comme ça ?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La texture du papier semble ressembler à une sorte de tissu. On y trouve d'innombrables runes non identifiables, ainsi que des illustrations ressemblant à des bras de poulpe.")
	novel_interface.show_character("leena")
	await novel_interface.show_dialog("C'est du papyrus ? Mais le papyrus n’aurait pas pu être aussi bien conservé s’il avait existé pendant des milliers d’années.","Rina")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","panic")
	await novel_interface.show_dialog("Ne faut-il pas porter des gants ou autre avant de le toucher ?","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("C'est bon, c'est recouvert d'une couche de spray hermétique.","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Waouh. Je me demande quel plat vous pouvez préparer avec cette recette. Vaut 36 millions...","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Tu ferais mieux d'apprendre à ta mère à le cuisiner la prochaine fois, Russ. La dernière fois que j'ai mangé un plat qu'elle m'a préparé, j'ai failli finir à l'hôpital.","Cassel")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Je ne peux pas blâmer ma mère pour ça. Tu as eu une diarrhée explosive uniquement parce que tu as trop mangé, pas à cause de sa cuisine.","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Alors... ces gars... peut-être qu'ils recherchent ce parchemin ?","Cassel")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Mais un Tarin coûte déjà plus de 20 millions. À moins que ce parchemin ne contienne un message caché très important, cela n’en vaut pas la peine.","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld")
	await novel_interface.show_dialog("Message caché ?","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld tient le manuscrit en l'air, l'étudiant sous les projecteurs du bâtiment d'en face.")
	await novel_interface.show_text_only("Les autres se rassemblent tous et je ne peux m'empêcher de les rejoindre aussi.")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Eh bien…","Cassel")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("D'après ce que je peux voir...","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("leena")
	await novel_interface.show_dialog("Il n’y a rien de suspect là-dedans…","Rina")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("…")
	novel_interface.show_character("ren_mercenary","worry")
	await novel_interface.show_dialog("En fait, ce qui me paraît vraiment suspect, c'est...","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Eh bien, je me le demande depuis que nous sommes arrivés dans cette rue.")
	await novel_interface.show_text_only("Il y a des tonnes de discothèques, de bars et de panneaux publicitaires lumineux par ici.")
	novel_interface.show_character("ren_mercenary","worry")
	await novel_interface.show_dialog("Mais pourquoi ce projecteur est-il braqué sur nous, au lieu d'une publicité ou de l'entrée d'un magasin ?","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("... Hum, c'est vrai...","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("Hé !","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella, qui est de l’autre côté de la rue, nous crie dessus tout à coup.")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("Bougez !","Fabella")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("Boum !")
	await novel_interface.show_text_only("Nous parvenons à peine à nous disperser avant qu'un gigantesque objet noir ne s'écrase du ciel, atterrissant à l'endroit exact vers lequel pointe le projecteur.")
	await novel_interface.show_text_only("Au milieu du nuage de poussière et d'asphalte brisé, nous entendons le bruit inquiétant du frottement du métal et du vrombissement des joints mécaniques.")
	await novel_interface.show_text_only("Une énorme pointe sort de la fumée, brillant dans une lumière métallique bleue et froide.")
	await novel_interface.show_text_only("Attaché à la pointe se trouve un bras mécanique élégant, qui est à son tour attaché à...")
	await novel_interface.show_dialog("Qu'est-ce que c'est que ça ?","Ren")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Big_Spider.png")
	await novel_interface.show_text_only("Fabella nous a avertis que l'ennemi pourrait envoyer une sorte d'armée de robots, mais je ne m'attendais certainement pas à cela.")
	await novel_interface.show_text_only("Il possède huit pattes souples, pointues et pointues, soutenant un corps gigantesque qui ne cesse de faire des bruits mécaniques.")
	await novel_interface.show_text_only("... Une araignée robot en alliage, mesurant près d'un mètre de haut. Équipé de pointes sur chaque jambe qui peuvent facilement percer le corps humain.")
	await novel_interface.show_text_only("Le robot prédateur mortel nous étudie avec des yeux rouges clignotants sur sa « tête ».")
	await novel_interface.show_dialog("Vous vous moquez de moi...","Rina")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_Fighting2.png")
	await novel_interface.show_text_only("Fabella et Pernard lèvent aussitôt leurs armes et ouvrent le feu.")
	await novel_interface.show_text_only("Les balles de plomb pleuvent sur l’armure en alliage, des étincelles jaillissent tandis que les balles ricochent sur le corps de l’araignée.")
	await novel_interface.show_text_only("L’araignée elle-même ne semble pas affectée du tout. Il se tourne vers Fabella et se jette sur elle d'un seul mouvement fluide.")
	await novel_interface.show_text_only("Pernard se penche sur le côté, tandis que Fabella descend et glisse sous le ventre de l'araignée.")
	await novel_interface.show_text_only("Un grand boum vient de derrière moi, me sortant de mon état de stupeur. C’est Rina, qui a commencé à tirer aussi.")
	await novel_interface.show_text_only("Les pattes de l'araignée tremblent, mais même le fusil de sniper anti-matériau de Rina ne laisse qu'une petite entaille sur l'armure en alliage.")
	novel_interface.show_character("ren_mercenary","panic")
	await novel_interface.show_dialog("(Que dois-je faire...?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Utiliser l'aérogel ? Certainement pas. Il me rôtira vivant avant même que je puisse m’approcher pour pulvériser mon aérogel dessus.")
	novel_interface.show_character("ren_mercenary","upset")
	await novel_interface.show_dialog("(Allez, il doit y avoir un moyen...)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("L'arachnide géant s'en prend maintenant à Pernard, qui brise la vitre d'un taxi garé au bord de la route et saute à bord.")
	await novel_interface.show_text_only("Avant même de pouvoir démarrer le moteur, l'araignée a détaché une portière de voiture avec une patte.")
	await novel_interface.show_text_only("Pernard profite de l'occasion pour sortir à nouveau de la voiture, saisissant la portière de la voiture et la jetant sur lui avant que l'araignée ne puisse se jeter sur lui.")
	await novel_interface.show_text_only("L’une des pattes pointues de l’araignée transperce la porte et s’y coince. En dessous se trouve Pernard, qui fait de son mieux pour maintenir la portière de la voiture en place, le visage rougi par l'effort.")
	novel_interface.show_character("ren_mercenary","shout")
	await novel_interface.show_dialog("Pouah, c'est maintenant ou jamais !","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Je prends ma décision et lance toute ma bombe aérosol sur l'araignée.")
	await novel_interface.show_text_only("Ensuite, je passe ma mitraillette KRISS Vector en mode rafale et commence à tirer rapidement en direction de la canette que je viens de lancer en l'air.")

	print("=== 创伤反射篇第12话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
