# traumareflex_ep11.gd - 创伤反射篇第11话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放创伤反射篇第11话剧本
	traumareflex_ep11_script()

func play_script():
	pass

# 创伤反射篇第11话 - 正式剧本
func traumareflex_ep11_script():
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_VTOL.png")
	novel_interface.change_music("res://assets/audio/music/Hand-to-hand combat.mp3")
	await novel_interface.show_text_only("Siskin. An unmanned military helicopter.")
	await novel_interface.show_text_only("A nightmare for all ground units, this heavy-firepower vehicle was developed by Masada Ford in the Third Academy City during the Seven Years War.")
	await novel_interface.show_text_only("It is capable of performing combat actions based on an automated algorithm and can easily acclimate to military environments with radio wave disruptions.")
	await novel_interface.show_text_only("Its less-than-perfect AI recognition technology is its one weak point. It is notorious for misfiring often, leaving lots of civilians dead or injured.")
	await novel_interface.show_text_only("Several countries have signed an agreement to ban machine-operated destructive devices. However, Masada Ford continues to refuse to become part of the agreement.")
	await novel_interface.show_text_only("And now, this yellow-and-black striped nightmare is slowly landing from above the building across us.")
	await novel_interface.show_text_only("The twelve spike missiles on either side of the vehicle can easily blast the whole block into nothing but ashes.")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_Fighting1.png")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("Shh, don’t move.","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella remains kneeling, one knee on the ground. She slowly places her sniper rifle on the ground and raises both arms in a gesture of surrender.")
	await novel_interface.show_text_only("Meanwhile, I’m still sitting there, barely able to breathe from the crushing force of the sniper rifle bullet that had blasted away my cover just now.")
	await novel_interface.show_text_only("In the shadows, I spot a silhouette silently approaching the Siskin from beneath it.")
	novel_interface.show_character("ren_mercenary","serious")
	await novel_interface.show_dialog("(A reconnaissance aircraft... isn’t that one of those that can self-destruct?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("The Siskin, hovering in the air, scans the environment and suddenly sends out dozens of missiles blazing in orange.")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("...!","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","wail")
	await novel_interface.show_dialog("(Oh no!)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("The missiles leave behind several bright arcs in the air, spreading themselves around the Siskin and explodes all at once.")
	await novel_interface.show_text_only("Several rows of glass windows shatter in the building behind. The reconnaissance aircraft, too, is reduced to glistening shards in the air.")
	await novel_interface.show_text_only("The light from the red-and-blue billboard behind the whole scene makes it look like a glorious large-scale fireworks show.")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("(So it fires decoy flares when it’s unable to pinpoint the exact location of a threat...)","Fabella")
	await novel_interface.show_dialog("(What a brilliant war machine indeed. Its AI programming is quite something.)","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("The helicopter then slowly turns, turns, until it is directly facing Fabella and I.")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_VTOL.png")
	await novel_interface.show_text_only("The compound eye lens under its body points its red laser dot of death at the two of us, sitting there exposed right in the middle of the road.")
	await novel_interface.show_text_only("It’s as if time has stopped right there.")
	await novel_interface.show_text_only("The few seconds before death are far more terrifying than death itself.")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("(Just... how much time has passed?)","Ren")
	await novel_interface.show_dialog("(If this is part of Fabella’s memory, it must have actually happened.)","Ren")
	await novel_interface.show_text_only("But something just doesn’t feel right...")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Street_Fighting1.png")
	await novel_interface.show_text_only("Out of nowhere, the Siskin violently shakes, and then—")
	await novel_interface.show_text_only("Following crackling static and several metallic clangs, some parts of the helicopter come loose.")
	novel_interface.show_character("ren_mercenary","solemn")
	await novel_interface.show_dialog("(Did someone... snipe at it?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("The armored helicopter twists to a side and starts falling—but soon manages to maintain altitude.")
	await novel_interface.show_text_only("It attempts to ascend once again. The system must be adjusting the vehicle’s position according to the damage it’s taken.")
	await novel_interface.show_text_only("A sudden female voice comes from my earpiece—which had been quiet for so long I had forgotten it existed.")
	await novel_interface.show_dialog("Sorry for keeping you waiting, my babies!","Female Voice")
	await novel_interface.show_dialog("But remember—the mobile electromagnetic accelerator can be used only once. Normal bullets can’t penetrate it.","Female Voice")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Rina! How’s the Alpha Team doing?","Russel")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Worry about yourself first. You still gotta deal with that helicopter!","Male Voice")
	await novel_interface.show_text_only("A deep, hoarse male voice warns us.")
	novel_interface.show_character("ren_mercenary","panic")
	await novel_interface.show_dialog("Where’s...\nFabella?","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I realize that Fabella, who was crouching at my side, is no longer there. I’m the only one left, sitting in the middle of the street like an idiot.")  #换行问题
	await novel_interface.show_text_only("Seconds later, a dark shadow with a flaming orange tail bursts out from under the toppled armored truck with a sharp screech.")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("Everyone down!","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Boom!")
	await novel_interface.show_text_only("As if torn apart by Fabella’s loud scream, the helicopter bursts into orange and yellow flames on one side.")
	await novel_interface.show_text_only("Soon, the helicopter is swallowed by raging fire. The Siskin spins around and around in the skies, trailing dark smoke, and finally crashes to the ground and meets it demise.")
	await novel_interface.show_text_only("A propeller flap whizzes out from amidst the heavy smoke and lands right between my legs, poking out of the road’s tar surface.")
	novel_interface.show_character("ren_mercenary","wry_smile")
	await novel_interface.show_dialog("?","Ren")
	novel_interface.change_expression("wail")
	await novel_interface.show_dialog("…","Ren")
	await novel_interface.show_dialog("Aaaaaaaah!","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I quickly back up on all fours, feeling like my heart’s about to leap out of my mouth.")
	novel_interface.show_character("fabiola_battle","mock")
	await novel_interface.show_dialog("Haha, poor girl. Can you still stand?","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Fabella appears from behind the armored truck, tossing an empty stinger cartridge aside.")
	await novel_interface.show_text_only("I clamber up, trying to tame my messy hairdo.")
	await novel_interface.show_dialog("Well done!","Male Voice")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("Pernard? How’s it going over there?","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("You’re not going to thank me first?","Female Voice")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Fine. Thanks, O great Mirkin!","Cassel")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Dude. Why did you stay quiet all this time and only get excited when you see a girl?","Russel")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("The “baggage” is fine. We lost Schwartz. Azoulay is down.","Male Voice")
	await novel_interface.show_text_only("The male with the hoarse voice explains the situation with a few simple words. So businesslike, so emotionless.")
	await novel_interface.show_dialog("The police and Ritnalap sent support, but they’re probably stuck outside the area. There’ll probably be another wave of attacks.","Male Voice")
	await novel_interface.show_dialog("This road is barricaded on both sides. Let’s meet at the street to the east side.","Male Voice")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("Roger that.","Fabella")
	await novel_interface.show_dialog("Grab the equipment, get ready to go!","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Yes!","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("What about the guy in the truck?","Cassel")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","bored")
	await novel_interface.show_dialog("Let’s just leave the idiot here.","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Yes!","Cassel")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_Fighting2.png")
	await novel_interface.show_text_only("We set off towards the neighboring street by smashing some windows of a streetside hotel and going through it, carrying the rest of our ammo and supplies.")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("The lights are all on here. Shouldn’t there be someone around?","Fabella")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("russell","",0.25)
	await novel_interface.show_dialog("The Disease Control Center issued a Grade 3 biohazard leakage warning here ninety minutes ago. It’s been cancelled now, though.","Russel")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Russel explains, as he scrolls through the messages on his tablet.")
	novel_interface.show_character("fabiola_battle","thinking")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("russell","",0.25)
	await novel_interface.show_dialog("The war only ended last year and civilians are still paranoid. Who wants to be hit by a faceful of anthrax, right?","Russel")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Fabella asks, scowling:")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("That Siskin... hasn’t it been banned on the market worldwide?","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("Of course. Those guys pride themselves on their top-secret AI control system. They’re certainly not gonna sell it to anyone.","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("Then what if we pick up the control unit from the wreckage? That way we’ll be able to study it, steal the technology—","Cassel")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("The chip self-destructed the second the copter crashed, idiot.","Russel")
	await novel_interface.show_dialog("I heard that its attack and defense modules are actually separate. A couple months ago, an officer from Masada fled his country with a sample of one of those modules.","Russel")
	await novel_interface.show_dialog("When Menorah got wind of it, they went after that poor guy, blasted him and his transport into smithereens. Even collected the ashes and shipped them back to their country, just in case.","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","wail")
	await novel_interface.show_dialog("(Their intelligence agency sounds pretty insane too...)","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("They’re here!","Cassel")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("I follow the sound of footsteps to see several soldiers ambling over from down the street.")
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("You’ve got four here, huh... oh, and a newbie too?","Pernard")
	await novel_interface.show_dialog("I need a map of the area.","Pernard")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("The tall, stocky Team Alpha Captain, one eye covered by a patch, immediately begins studying the map with Fabella.")
	novel_interface.show_character("leena")
	await novel_interface.show_dialog("What a cutie.\nI’m Rina Mirkin. Nice to meet you.","Rina")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_mercenary","gratified",0.25)
	await novel_interface.show_dialog("Nice to meet you. Call me Ren.","Ren")
	await novel_interface.show_dialog("(Wasn’t she the one who fired the shot that saved our asses?)","Ren")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Rina looks like a sophisticated hippie, with her colorful knit bandanna and sniper rifle.")
	novel_interface.show_character("leena")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_mercenary","gratified",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Hm. Your outfit...","Rina")
	await novel_interface.show_dialog("Is it what the youngsters call girly punk?","Rina")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"awkward")
	await novel_interface.show_dialog("Uh, no...","Ren")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("My holed silk stockings do seem... punkish, though.")
	await novel_interface.show_text_only("Well…")
	await novel_interface.show_text_only("Suddenly, from behind the broad shoulders of the Team Alpha leader, a familiar figure pops out.")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("Hi, Miss Ren.","Skuld")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("We meet again!","Skuld")

	print("=== 创伤反射篇第11话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
