# traumareflex_ep03.gd - 创伤反射篇第03话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	traumareflex_ep03_script()

func play_script():
	pass

func traumareflex_ep03_script():
	await novel_interface.show_text_only("Oye, ¿alguna vez has tenido ese tipo de sentimiento?")
	await novel_interface.show_text_only("Recuerdas una escena... pero no tienes idea de cuándo sucedió.")
	await novel_interface.show_text_only("No me refiero al deja vu. Todo el mundo tiene eso en algún momento u otro.")
	await novel_interface.show_text_only("Quiero decir, hay algo que siempre supiste que sucedería algún día, y finalmente sucede.")
	await novel_interface.show_text_only("Siempre has sabido que sucederá. Incluso lo has visto, en forma de flashback. Simplemente no puedes estar seguro de cuándo sucederá.")
	await novel_interface.show_text_only("Lo que llamamos deja vu es simplemente una especie de confirmación de que tus premoniciones se han hecho realidad.")
	await novel_interface.show_text_only("Sabías que sucedería. Siempre lo has sabido.")
	await novel_interface.show_text_only("¿No es así?")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Night_Park.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.show_character("skuld","painful")
	await novel_interface.show_dialog("Mmm…","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La chica rubia abre los ojos atontada, se frota la cara y se encuentra recostada en un banco.")
	novel_interface.show_character("skuld","panic")
	await novel_interface.show_dialog("Fabella... ¿dónde estamos?","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Pero Fabella no responde. Extraño. La criada normalmente aparece en el momento en que se llama su nombre.")
	await novel_interface.show_text_only("La niña mira a su alrededor y ve una calle vacía, bordeada por farolas ordenadas a ambos lados. La calle parece continuar eternamente en un silencio inquietante, como si fuera un universo alternativo.")
	novel_interface.show_character("skuld","panic")
	await novel_interface.show_dialog("¿No estábamos en una iglesia…?","Skuld")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Ahh... ¡Fabella!","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld se pone de pie y una mano masajea su dolorida sien.")
	await novel_interface.show_text_only("Ella recuerda la pesadilla que tuvo. Recuerda las imágenes retorcidas de las ventanas de mosaico. ¿Pero fue realmente sólo una pesadilla?")
	await novel_interface.show_text_only("Ella recuerda a Fabella, echándola de la iglesia, liberándola de la oscuridad que de otro modo la habría reclamado...")
	await novel_interface.show_text_only("Skuld revisa sus pertenencias. Su móvil, su cartera, sus complementos... todo ahí.")
	await novel_interface.show_text_only("Hay treinta y dos llamadas perdidas en su teléfono.")
	await novel_interface.show_text_only("Si Fabella no hubiera instalado un software anti-seguimiento en el teléfono, la Embajada probablemente ya la habría encontrado.")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("Las diez y dieciocho de la noche... ¿ya es tan tarde?","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Cierra los ojos con fuerza, haciendo todo lo posible por regular su respiración, para ordenar el enredo que son sus recuerdos.")
	await novel_interface.show_text_only("Ella debe mantener la calma, eso es lo que el padre y Fabella hubieran querido. Siempre le dijeron que cuanto más peligrosa es la situación, más necesita mantener la cabeza despejada.")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("Esa iglesia... y el texto del Padre Antón... deben ser una trampa.","Skuld")
	await novel_interface.show_dialog("Quienquiera que haya sido debe estar apuntando a mí, a mi padre o a Fabella.","Skuld")
	await novel_interface.show_dialog("Puedo escuchar autos en las carreteras cercanas e incluso artistas callejeros tocando una canción a cierta distancia... y no estoy atado ni nada.","Skuld")
	await novel_interface.show_dialog("Según el GPS de mi teléfono, estoy en Arai Central Park, no muy lejos de la iglesia.","Skuld")
	await novel_interface.show_dialog("Quien me trajo aquí probablemente no quiso hacer ningún daño.","Skuld")
	await novel_interface.show_dialog("No sé si quien puso la trampa y quien me trajo aquí pertenecían a la misma facción... No puedo regresar así.","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Skuld marca el número de Fabella una vez más. Y una vez más, salta el correo de voz. Revisa todos sus registros y parece que Fabella tampoco se había puesto en contacto con ella en absoluto.") #换行问题
	novel_interface.show_character("skuld","painful")
	await novel_interface.show_dialog("Fabella...","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Finalmente, llama a su padre, agarrando con fuerza su teléfono en su pequeña mano.")
	await novel_interface.show_text_only("Responde en el momento en que se realiza la llamada.")
	await novel_interface.show_dialog("¿Skuld? ¿Eres tu?","Padre")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("Padre...","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("¿Dónde diablos estás? Ya son más de las diez de la noche. donde estas. ¡Todos se mueren de preocupación!","Padre")
	await novel_interface.show_dialog("¡Y ni tú ni tu criada contestaron el teléfono! ¿Qué pasa con ustedes dos? ¡El embajador Haggerty ya envió un equipo a buscarte!","Padre")
	await novel_interface.show_text_only("Su padre parece enojado, pero Skuld simplemente se siente aliviado al escuchar su voz.")
	await novel_interface.show_text_only("Al menos nadie intentó amenazarlo con nada, usándola a ella como rehén.")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("Ahora estoy a salvo, no te preocupes, pero escucha—","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("El hombre se calma inmediatamente ante la urgencia en el tono de su hija.")
	await novel_interface.show_dialog("... ¿Estás solo?","Padre")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("Sí. Sólo yo.","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Espera un segundo, te llamaré con otro número.","Padre")
	await novel_interface.show_text_only("Ella cuelga e inmediatamente recibe una llamada de un número desconocido.")
	await novel_interface.show_dialog("Está bien, ya puedes hablar. ¿Qué pasó?","Padre")
	await novel_interface.show_text_only("Skuld respira profundamente. Según lo que sabe actualmente, debería haber dos posibilidades:")
	await novel_interface.show_text_only("Si quienes pusieron la trampa y quienes la trajeron aquí eran del mismo grupo, entonces su objetivo debe ser Fabella, no la propia Skuld.")
	await novel_interface.show_text_only("Si no son del mismo grupo, entonces ella misma podría ser el objetivo: quienquiera que la quisiera fracasó y actualmente mantiene como rehenes a Fabella y al padre Antón.")
	await novel_interface.show_text_only("No importa cuál sea, su persona favorita en el mundo está en peligro.")
	await novel_interface.show_text_only("Aún así, si es lo último, no puede simplemente ir a buscar a Fabella ella misma. Sería caer directamente en una trampa y probablemente ella también terminará como rehén, algo que los secuestradores pueden usar contra su padre y el Comité.")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("¿Puedes hacer algo por mí primero? Necesito que alguien controle al padre Anton de Trinity Church y me diga si está a salvo.","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Claro, enviaré a alguien de inmediato.\nAhora, cuéntame qué está pasando.","Padre")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("Fabella y yo fuimos emboscados cerca de la Embajada no hace mucho. Probablemente utilizaron algún tipo de alucinógeno o drogas elaboradas con Sustancia H.","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("¿Qué?","Padre")
	await novel_interface.show_text_only("Usar armas químicas o aquellas fabricadas con Sustancia H en un territorio internacional equivale prácticamente a declarar la guerra al Congreso Unido.")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("Fabella arriesgó su vida para salvarme. No sé dónde está ahora...","Skuld")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Esos tipos debieron haberme enviado un mensaje de texto haciéndose pasar por el Padre Anton y haberme atraído allí.","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("… Ya veo.","Padre")
	await novel_interface.show_dialog("El Foro de la Paz es el próximo mes... ¿por qué tuviste que ir a Nueva Opulentia en un momento tan delicado...?","Padre")
	await novel_interface.show_dialog("Quien se atreviera a hacer esto definitivamente tendría mucho cuidado con su identidad.","Padre")
	await novel_interface.show_dialog("Aunque el ex-jefe de Fabella en Sudamérica ha fallecido, todavía tiene bastantes enemigos...","Padre")
	await novel_interface.show_dialog("De todos modos, ¿dónde estás ahora?\nArreglaré algo con relaciones exteriores y te traeré de regreso a Newmoridas.","Padre")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("¡Primero tienes que prometerme! ¡Prométeme que salvarás a Fabella!","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("La voz de Skuld tiembla, los ojos llenos de lágrimas.")
	await novel_interface.show_dialog("…","Padre")
	await novel_interface.show_text_only("Al otro lado de la línea, silencio.")
	await novel_interface.show_text_only("Skuld sabe que su padre es extremadamente hábil y siempre está bien informado. Podría analizar la situación fácilmente y decidir el mejor curso de acción.")
	await novel_interface.show_text_only("Su padre es uno de los fundadores de una empresa de fondos de cobertura, que floreció en el mercado financiero durante la guerra debido a sus excelentes habilidades para tomar decisiones. Así se ganó un lugar en el Comité.")
	await novel_interface.show_text_only("Pero así fue también como se ganó innumerables enemigos. Después de todo, hacer caer las acciones es muy diferente a hacer caer un país.")
	await novel_interface.show_text_only("Skuld creció en un ambiente lleno de odio y peligro. Pero su padre fue extrañamente persistente y se negó a cambiar sus costumbres por su hija.")
	await novel_interface.show_text_only("Podría tener algo que ver con su madre, que había muerto cuando ella era muy joven.")
	await novel_interface.show_text_only("De repente, Skuld nota un pequeño marco rojo en la pantalla de su teléfono.\nEsto indica que su ubicación está siendo rastreada durante la llamada.")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("...!","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ella inmediatamente cuelga.")
	novel_interface.show_character("skuld","panic")
	await novel_interface.show_dialog("¡Ya tienen mi ubicación! Tengo que salir de aquí...","Skuld")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Parking_Lot.png")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("Skuld corre hacia las escaleras de un edificio de aparcamiento cercano.")
	await novel_interface.show_text_only("Ella llama al número de una lavandería en sus contactos. Fabella le había dado ese número como último recurso.")
	novel_interface.show_character("skuld","panic")
	await novel_interface.show_dialog("... ¡Supongo que ahora no tengo otra opción!","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Agachada en los escalones, la niña marca el número.")
	await novel_interface.show_text_only("Después de tres tonos, una amable señora habla.")
	await novel_interface.show_text_only("Lavandería Rexhill. Encantado de servirle.")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("... Soy Skuld Axelrod, documento de identidad internacional no. AX1832.","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Entendido. Por favor espera...")
	await novel_interface.show_text_only("Señorita Axelrod, su ropa está lista. ¿Te lo enviamos?")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("Claro. Por cierto, mi amiga de la Iglesia Memorial New Opulentia necesita que le recojan la ropa.","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Entendido.")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("Estoy en—","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Sabemos dónde estás. Por favor tenga paciencia.")
	await novel_interface.show_text_only("La señora cuelga.")
	await novel_interface.show_text_only("Diez minutos más tarde, un todoterreno negro entra en el aparcamiento.")
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("Buenos días, señorita Axelrod.","SID Agent")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("¿Eres de... SID?","Skuld")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("Sí. Ya hemos recuperado a tu amigo.","SID Agent")
	await novel_interface.show_dialog("Por favor entre.","SID Agent")


	print("=== 创伤反射篇第03话结束 ===")
	await novel_interface.end_story_episode(0.5)
