# traumareflex_ep14.gd - 创伤反射篇第14话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放创伤反射篇第14话剧本
	traumareflex_ep14_script()

func play_script():
	pass

# 创伤反射篇第14话 - 正式剧本
func traumareflex_ep14_script():
	novel_interface.change_background("res://assets/images/bg/Fabiola/Brain.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("บางคนอาจคิดว่าความทรงจำก็เหมือนกับไฟล์วิดีโอ")
	await novel_interface.show_text_only("เมื่อเราพยายามเรียกคืน เราก็แค่หาจุดเวลาที่ถูกต้องแล้วกดเล่น")
	await novel_interface.show_text_only("แต่สมองของเราไม่ได้ถูกตั้งโปรแกรมไว้แบบนั้น สมองไม่ใช่กล้องวิดีโอ แทนที่จะเป็นม้วนฟิล์มทั้งหมด สิ่งที่บันทึกกลับเป็นเพียงเศษเสี้ยว")
	await novel_interface.show_text_only("เมื่อเรานึกถึงความทรงจำ สมองจะทิ้งขอบเขตจินตนาการไว้สำหรับเศษความทรงจำเหล่านี้ จากนั้นจึง \"อนุมาน\" ว่าเกิดอะไรขึ้น ณ จุดเวลานั้น")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Memory.png")
	await novel_interface.show_text_only("ดังนั้น อย่างที่พวกเขาพูดในหนัง—")
	await novel_interface.show_text_only("“ความทรงจำคือการตีความ ไม่ใช่บันทึก”")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("ฉันรู้สึกว่าสมองของฉันหยุดนิ่งภายใต้การจ้องมองที่พินิจพิเคราะห์ของ Skuld")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Billboard.png")
	await novel_interface.show_text_only("ดีไซน์บนกล่องขนมนี้...และป้ายโฆษณาที่ฉันเห็นข้างนอกนั้น...")
	await novel_interface.show_text_only("การออกแบบนี้ไม่มีอยู่ในความทรงจำของ Fabella เมื่อสองปีก่อน ตอนนั้นยังไม่ได้ถูกสร้างขึ้นด้วยซ้ำ")
	await novel_interface.show_text_only("เว้นแต่อายะและมาริรุจะใช้มันเป็นเครื่องหมายสำหรับฉันในความทรงจำนี้...แต่ไม่ มันเป็นไปไม่ได้ พวกเขาไม่อินกับตัวละครในเกม")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Factory.png")
	await novel_interface.show_text_only("ใครจงใจวางแบบไว้บนโลกใบนี้ต้องเป็น...")
	novel_interface.show_character("ren_mercenary","normal1")
	await novel_interface.show_dialog("(ฉัน ก็ต้องฉันสิ)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ฉันใส่บางสิ่งที่ไม่ควรมีอยู่ในความทรงจำของฟาเบลลา")
	await novel_interface.show_text_only("แต่เรื่องนั้นเกิดขึ้นเมื่อไหร่?")
	await novel_interface.show_text_only("แล้วทำไมฉันถึงทำอย่างนั้นด้วย?")
	await novel_interface.show_text_only("... ฉันรู้สึกปวดหัวขึ้นมา")
	novel_interface.show_character("ren_mercenary","wry_smile")
	await novel_interface.show_dialog("(ฉันจำไม่ได้เลย)","Ren")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("(นอกเหนือจากการออกแบบนั้น มีอะไรอีกในโลกนี้ที่ไม่ควรมีอยู่?)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("โอ้ สเปรย์แอโรเจล!")
	await novel_interface.show_text_only("กระป๋องที่ฉันมีคือรุ่นใหม่ล่าสุด ซึ่งออกแบบโดย Aya เมื่อสองสัปดาห์ก่อนโดยเฉพาะสำหรับการเดินทางไปแอนตาร์กติกาของเรา")
	await novel_interface.show_text_only("ถ้าไม่มีมัน เราคงถูกทำลายโดยแมงมุมพวกนั้น...")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("(และ... มีอะไรอีกไหม ขอฉันดูหน่อย...)","Ren")
	await novel_interface.show_text_only("มีอะไรอีกบ้างที่ฉัน \"นำ\" เข้ามาในความทรงจำนี้?")
	await novel_interface.show_text_only("โอ้ เสื้อแจ็กเก็ตการต่อสู้ของเหลวที่ไม่ใช่ของนิวตัน")
	await novel_interface.show_dialog("ฉันจำได้ว่าเคยอ่านเรื่องนี้ในคู่มืออุปกรณ์ต่อสู้ของเจ้าหน้าที่ SID","Ren")
	await novel_interface.show_text_only("ถ้าไม่ใช่เพราะแจ็กเก็ตตัวใหญ่ตัวนี้ ฉันคงตายระหว่างที่รถชนกัน")
	await novel_interface.show_text_only("และแว่นตายุทธวิธีไวเปอร์")
	await novel_interface.show_text_only("ฉันสำลักควัน ถ้าไม่มีมันฉันก็คงจะหายใจไม่ออก")
	await novel_interface.show_text_only("และ KRISS Vector ของฉัน ฉันชอบมันมาโดยตลอดในระหว่างการฝึกซ้อมเป้าหมายใน SID เนื่องจากการหดตัวลดลง")
	await novel_interface.show_text_only("ฉันใช้ปืนโจมตีกระป๋องสเปรย์แอโรเจล และรอบสำรองสามรอบก็เพียงพอที่จะป้องกันแมงมุมตัวเล็ก ๆ ได้")
	await novel_interface.show_text_only("และ...")
	novel_interface.show_character("ren_mercenary","shy")
	await novel_interface.show_dialog("(ถุงน่องผ้าไหม...)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("เฉดสีที่สมบูรณ์แบบ ความยืดหยุ่นที่สมบูรณ์แบบ ถ้าไม่มีมัน มือปืนคงจะพาพวกเราออกไปแล้ว")
	novel_interface.show_character("ren_mercenary","uneasy")
	await novel_interface.show_dialog("(ใช่แล้ว เรียกมันว่า... ถุงน่องแทคติคอลสิ!)","Ren")
	await novel_interface.show_dialog("(ถ้าไม่มีสิ่งเหล่านี้ ฉันคงตายไปแล้ว)","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("แต่เดี๋ยวก่อน...")
	await novel_interface.show_text_only("ตายแล้วเหรอ?")
	novel_interface.show_background("res://assets/images/bg/Fabiola/AI.png")
	await novel_interface.show_dialog("ฉันอัพเกรดระบบป้องกันความผิดพลาดด้วยตัวเอง แม้ว่าการบาดเจ็บหรือเสียชีวิตจะเกิดขึ้นภายในศีรษะของเป้าหมาย คุณจะไม่ได้รับอันตรายในชีวิตจริง","Aya")
	await novel_interface.show_text_only("…")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("อืม จริงด้วย...")
	await novel_interface.show_text_only("สิ่งที่ไม่ควรมีอยู่ในความทรงจำนี้จริงๆ...ก็คือฉันเอง")
	await novel_interface.show_text_only("แม้ว่าฉันจะตายในโลกนี้ร่างกายของฉันก็ยังสบายดี...")
	await novel_interface.show_text_only("มันโจมตีฉันเหมือนสายฟ้าฟาด")
	await novel_interface.show_dialog("(ก่อนหน้านี้ฉันตายไปกี่ครั้งแล้ว?)","Ren")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Factory.png")
	await novel_interface.show_text_only("ตัวสั่นไหลลงมาตามกระดูกสันหลังของฉัน ฉันเริ่มตัวสั่นอย่างควบคุมไม่ได้")
	await novel_interface.show_text_only("สิ่งนี้จะอธิบายทุกสิ่ง...")
	await novel_interface.show_text_only("ฉันมองไม่เห็นอนาคต อย่างที่สกัลด์บอกว่าฉันทำได้")
	await novel_interface.show_text_only("เพียงแต่ทุกครั้งที่ฉันตาย ฉันจะพบกลยุทธ์ใหม่เพื่อไม่ให้ตัวเองตาย")
	await novel_interface.show_text_only("สัญชาตญาณของฉัน ป้ายโฆษณา. สถานที่สปอตไลต์สุดแปลก นั่นเป็นเพียงฉันเตือนตัวเองถึงอันตรายที่เข้ามา")
	novel_interface.show_character("ren_mercenary","upset")
	await novel_interface.show_dialog("(ฉันไม่มีความสามารถด้านการทำนายเลย ฉันแค่... ตายไปเยอะมากและได้เรียนรู้จากมัน)","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("คุณเร็น คุณสบายดีไหม\nคุณดูซีดเซียว","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("สคูลด์ตบหลังฉันด้วยท่าทางกังวล")
	novel_interface.show_character("ren_mercenary","upset")
	await novel_interface.show_dialog("ฉันสบายดี ฉันแค่... จำบางสิ่งได้...","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ใช่แล้ว ไม่ว่าจะเกิดอะไรขึ้นกับทีมในตอนนั้น Fabella และ Skuld น่าจะรอด ไม่อย่างนั้นฉันก็คงไม่ได้พบพวกเขาอีก")
	novel_interface.show_character("ren_mercenary","upset")
	await novel_interface.show_dialog("(แล้วทำไมฉันถึงตายหลายครั้ง?)n\\(สายลับที่ฟาเบลล่าพูดถึงทำอะไรบางอย่างกับฉันหรือเปล่า?)","Ren")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("ทันใดนั้น หูฟังของฉันก็ระเบิดด้วยเสียงระเบิดดังกึกก้องตามด้วยเสียงปืนที่ดังลั่น")
	await novel_interface.show_dialog("อ๊ากกก!","เสียงผู้หญิง")
	await novel_interface.show_text_only("ปัง! ปัง ปัง ปัง ปัง")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("เกิดอะไรขึ้น?","Russel")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("รินะเหรอ?","Cassel")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("รินะ รายงานตำแหน่งของคุณ!","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("*ไอ*","เสียงผู้หญิง")
	await novel_interface.show_text_only("หลังจากไอจนปอดแหกหลายครั้ง มีเสียงหอบดังผสมกับเสียงกรน")
	await novel_interface.show_text_only("เสียงผิวปากที่เกิดจากของเหลวภายในปอดที่ได้รับบาดเจ็บ")
	await novel_interface.show_text_only("ในที่สุดของเหลวก็เข้าปกคลุมปอดของผู้บาดเจ็บ ทำให้หายใจไม่ออก จนกว่าพวกเขาจะจมน้ำตายบนพื้นดินแห้ง")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("คุณบาดเจ็บหรือเปล่า?\nคุณอยู่ไหน?","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("ไม่สำคัญ...\n*ไอ*","Rina")
	await novel_interface.show_dialog("พวกมันก็ล้อมโกดังของคุณด้วย...","Rina")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("—!","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("นั่นคือที่มาของเสียงโลหะกระทบผนังและประตู")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("ให้ตายเถอะ... พวกเขากำลังหาทางเข้าไป ฮะ...","Fabella")
	await novel_interface.show_dialog("เรากั้นลิฟต์ได้ไหม","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("เหล่านี้เป็นลิฟต์อุตสาหกรรม เปิดเกินไป","Russel")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("หุ่นยนต์พวกนั้น... พวกเขาใช้เซ็นเซอร์ความร้อน...","Rina")
	await novel_interface.show_dialog("ฉันไม่สามารถ... ติดต่อกับคนของฉันได้... แมลงพวกนั้นมาจากไหน... *ไอ*","Rina")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("... คนของคุณเหรอ?","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("ฮ่า. มิสซี่...เธอยังไม่สำนึกอีกเหรอ?","Rina")
	novel_interface.show_character("ren_mercenary","serious")
	await novel_interface.show_dialog("เป็นไปได้ไหม...","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("นิวโมริดาส... เมืองอะไรเช่นนี้...","Rina")
	await novel_interface.show_dialog("ทุกคนสามารถได้รับโอกาสครั้งที่สองในชีวิตที่นี่...","Rina")
	await novel_interface.show_dialog("แม้กระทั่งชวาร์ตษ์ ฆาตกรคนนั้น... *ไอ*","Rina")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("ชวาร์ตษ์? ผู้ชายในทีมอัลฟ่าที่เสียชีวิต?","Cassel")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("เขา... เคยเป็นสมาชิกของกลุ่มกวาดล้างมาซาดะ... ฉันเฝ้าดูเขา... ฆ่าแม่และน้องสาวที่ไม่มีทางป้องกันของฉัน...","Rina")
	novel_interface.show_character("ren_mercenary","serious")
	await novel_interface.show_dialog("ผู้ชำระล้าง... ดังนั้น ผ้าโพกศีรษะหลากสีสันของริน่าจึงต้องมาจาก...","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("จู่ๆ ฉันก็นึกถึงข่าวเมื่อไม่กี่ปีก่อนขึ้นมา สภาแห่งสหประชาชาติกำลังสอบปากคำมาซาดา ฟอร์ดเกี่ยวกับภัยพิบัติด้านมนุษยธรรมที่เกิดขึ้นในบริเวณใกล้เคียง")
	await novel_interface.show_text_only("ฉันไม่รู้ว่า “ภัยพิบัติด้านมนุษยธรรม” ในตอนนั้นหมายถึงอะไร แต่ฉันจำผ้าโพกศีรษะสีสันสดใสที่ปรากฏในภาพข่าวได้")
	await novel_interface.show_dialog("ตลกใช่ไหม? คนของฉัน... คิดว่ามาซาดา ฟอร์ดเป็นพันธมิตรของเรา...","Rina")
	await novel_interface.show_dialog("แต่หลังจากที่เราร่วมมือกันทำลายศัตรูของเรา ... *ไอ* เราก็กลายเป็นเป้าหมายต่อไปของพวกเขา...","Rina")
	await novel_interface.show_dialog("พวกเขาทำเครื่องหมาย \"พื้นที่อนุรักษ์\"... และผู้ที่ไม่ย้ายไปที่นั่นก่อนกำหนดเวลา... ถูกปฏิบัติเหมือนเป็นผู้ก่อการร้าย...","Rina")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("แล้วคุณและคนของคุณ... คุณอยู่ในกลุ่มต่อต้านเหรอ?","Fabella")
	await novel_interface.show_dialog("หากคุณต้องการกำจัดชวาร์ตษ์ เพียงแค่ส่งทีมนักฆ่าไป ทำไมคุณต้องวางระเบิดนิวโมริดัส และลากพวกเราทุกคนมาที่นี่?","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("*ไอ* เธอไม่รู้อะไรเลยจริงๆนะคุณหนู...","Rina")
	await novel_interface.show_dialog("มาซาดา ฟอร์ดมักจะทำสงครามกับบางคนหรือคนอื่นอยู่เสมอ... และพวกเขาก็คิดค้นอาวุธใหม่ๆ อยู่เสมอ... แต่ใครเป็นคนจัดหาเงินทุนให้พวกเขา?","Rina")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("... ส่วนใหญ่เป็นนิวโมริดาส","Skuld")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("คณะกรรมการควบคุมสินเชื่อ... จัดจำหน่ายหลักทรัพย์... และเงินกู้ที่ตกเป็นของมาซาดะ... ได้รับการบรรจุใหม่เป็นพันธบัตรในเมืองนี้...","Rina")
	await novel_interface.show_dialog("พวกสุภาพบุรุษที่ได้รับค่านายหน้าพวกนั้น... *ไอ* ไม่สนใจหรอก... ระเบิดที่สร้างขึ้นด้วยเงินของพวกเขา... ระเบิดพวกนั้นจะฆ่าใคร? ฮะ?","Rina")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("ดังนั้นคุณจึงเลือกที่จะแสดงในระหว่างการประชุมสันติภาพนานาชาติ...","Russel")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("ผู้ชนะ... คือฮีโร่... เพราะมีเพียงรัฐบาลที่รอด... เท่านั้นที่สามารถชำระคืนเงินกู้ได้... ใช่ไหม?","Rina")
	await novel_interface.show_text_only("สกัลด์ก้มศีรษะลงอย่างเงียบๆ")
	await novel_interface.show_dialog("*ไอ*","Rina")
	await novel_interface.show_text_only("หูฟังเต็มไปด้วยอาการไอที่แสบหูของริน่าอีกครั้ง")
	await novel_interface.show_text_only("มาริรุเคยบอกฉันว่าการทำธุรกรรมด้วยเงินเพียงอย่างเดียวและไม่มีอะไรอื่นบริสุทธิ์ที่สุดในโลก")
	await novel_interface.show_text_only("ไม่เกี่ยวข้องกับภาษา วัฒนธรรม กฎระเบียบ ประวัติศาสตร์ แค่เงิน. สนิทสนมและตรงไปตรงมามาก เลย...ไร้อารมณ์")
	await novel_interface.show_dialog("เราเลือกเด็กผู้หญิงคนนั้นเป็นเป้าหมายเพราะ... พ่อของเธอ... เป็นเพียงคนเดียวในคณะกรรมการ... ที่ไม่สนับสนุนการค้ากับมาซาดา ฟอร์ด","Rina")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("แล้วทำไม-","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("เราอยากให้เขามีเหตุผล... เพื่อสนับสนุนจุดยืนของเขาเมื่อเขาพูดในคณะกรรมการ...","Rina")
	await novel_interface.show_text_only("คำพูดของริน่าพูดไม่ชัด ลมหายใจของเธอแทบไม่ได้ยิน")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("ดังนั้นคุณจึงชน Siskin ในย่านที่พลุกพล่านของเมือง และทำให้ลูกสาวของเขาตกอยู่ในอันตราย...","Russel")
	await novel_interface.show_dialog("และไม่น่าแปลกใจเลยที่คุณจัดการพลซุ่มยิงทั้งหมดที่อยู่เคียงข้างคุณเพียงลำพัง ทั้งหมดเป็นการกระทำของคนของคุณ...","Russel")
	await novel_interface.show_dialog("เดี๋ยวก่อน คุณจึงยิง Siskin เพื่อปกปิดความจริงที่ว่ามันไม่เคยติดตั้งโมดูลการโจมตีตั้งแต่แรกเลยเหรอ?","Russel")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("ฮ่า... รัสเซล... คุณฉลาดใช่ไหม...","Rina")
	await novel_interface.show_dialog("แย่จัง...","Rina")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("เฮ้! รินะ? รินะ?","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ในหูฟัง ความเงียบ")
	novel_interface.show_character("fabiola_battle","sob")
	await novel_interface.show_dialog("ให้ตายเถอะ! ไอ้บ้า! ไอ้บ้า!","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ฟาเบลลาต่อยชั้นวางโลหะ มีเสียงดังกึกก้องดังก้องไปทั่วผนังโกดัง")
	novel_interface.show_character("fabiola_battle","sob")
	await novel_interface.show_dialog("ทั้งหมดก็เพื่อการเมือง สิทธิพิเศษ และเงินใช่ไหม? ต้องมีคนบริสุทธิ์ตายอีกกี่คน?","Fabella")
	novel_interface.change_expression("sob2")
	await novel_interface.show_dialog("เพอร์นาร์ด...","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ฟาเบลล่าร้องไห้สะอึกสะอื้น เลือดสดหยดลงจากปลายนิ้วของเธอ")
	novel_interface.show_character("ren_mercenary","serious")
	await novel_interface.show_dialog("(เดี๋ยวก่อน... รินะพูดว่า... แมงมุมพวกนั้นไม่เกี่ยวอะไรกับคนของเธอเลยเหรอ?)","Ren")
	novel_interface.change_expression("solemn")
	await novel_interface.show_dialog("(ในความทรงจำนี้...อะไรจริง อะไรไม่จริง)","Ren")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…")
	await novel_interface.show_text_only("<ก่อนหน้า>")
	novel_interface.show_background("res://assets/images/bg/Fabiola/BAR2.png")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	await novel_interface.show_text_only("<ศูนย์วิจัยเทคโนโลยีฮาริมะ บาร์เพนต์เฮาส์>")
	await novel_interface.show_text_only("มาริรุนั่งอยู่บนโซฟา พลิกดูกองไฟล์ที่มีคำว่า \"ลับ\" กำกับอยู่")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("คาร์ลอส บรังโก อดีตเจ้านายของสาวใช้ที่เราดึงมาจาก New Opulentia Memorial Church","Mariru")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("อดีตพันเอก สคบ. หนึ่งในทหารจริงจังที่หายากเพียงไม่กี่คนที่เกิดจากระบบที่เสียหายนั้น","Mariru") #换行问题
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("หลังจากที่รัฐสภาถูกยุบโดยเอลรอย เขาได้รับรอยสัก \"Down with the Tyrant\" บนแขนของเขา และนำทหารผ่านศึกในระบบก่อจลาจล","Mariru")
	await novel_interface.show_dialog("เขานำกองกำลังของเขาขยายขอบเขตเทือกเขาแอนดีสในเวลาเพียงหนึ่งวันและสั่งการกองทัพสหต่อต้านเอลรอยในสงครามโปโตซี","Mariru")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("น่าสนใจ นั่นเป็นเหตุผลว่าทำไมเขาถึงได้ชื่อเล่นเดียวกันกับที่ผู้คนตั้งให้ Karl XIV Johan ใช่ไหม?","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("มาริรุพึมพำด้วยความสนใจกับสิ่งที่เธออ่านในไฟล์ นิ้วของเธอหมุนแก้วไวน์ในมือของเธออย่างต่อเนื่อง")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("จากนั้น ระหว่างการต่อสู้ในเอนวิรา เขาก็พบฟาเบลลา เด็กกำพร้าบนเตียงมรณะของเธอ","Mariru")
	await novel_interface.show_dialog("หลังจากการปฏิวัติประสบความสำเร็จ ผู้บัญชาการกองทัพกบฏหลายคนเริ่มต่อสู้เพื่อชิงตำแหน่งที่ไร้ความหมายและอะไรทำนองนั้นอีกครั้ง ดูเหมือนว่าความสงบสุขจะไม่มีวันเกิดขึ้นได้","Mariru")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("น่าเบื่อ","Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("ต่อมาบรังโกก็กลายเป็นหัวหน้าแก๊งที่ใหญ่ที่สุดในอเมริกาใต้ในเวลาต่อมา เขาถูกสงสัยว่าอยู่เบื้องหลังเหตุการณ์สังหารหมู่ที่แม่น้ำชูรัน และได้รับสมญานามว่า “คนขายเนื้อแห่งแม่น้ำชูรัน”","Mariru")
	await novel_interface.show_dialog("แม้ว่าเขาจะไม่ได้ฆ่าใครจริงๆ เพียงแค่ปฏิเสธสินบนของ United Congress","Mariru")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("การผูกขาดสื่อทำให้คุณมีอิสระในการทำสิ่งต่างๆ มากมาย","Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("จากนั้นรัฐสภาคองเกรสแห่งสหประชาชาติได้ประกาศว่าคาร์ลอส บรังโกก่ออาชญากรรมต่อต้านมนุษยธรรมและทางเชื้อชาติ และทิ้งระเบิดใส่ผู้บุกรุกบางคน ตอนจบ.","Mariru")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("ผู้ชายคนนั้นมีอุดมคติของเขา—แต่ไม่รู้อะไรเกี่ยวกับการเมืองเลย","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("มาริรุโยนไฟล์ลงบนโต๊ะ")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("เช่นเดียวกับที่คาร์ลที่ 14 บรรยายถึงนโปเลียน...","Mariru")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Bernadotte.png")
	await novel_interface.show_dialog("“เขาอาศัยสติปัญญาของเขาและไม่มีอะไรอื่น นั่นคือสาเหตุที่พระเจ้าทรงลงโทษเขา”","Mariru")
	await novel_interface.show_dialog("—คาร์ลที่ 14 จอห์น, ฌอง-แบปติสต์ แปร์นาร์ด","Mariru")
	await novel_interface.show_dialog("นักปฏิวัติอเมริกาใต้ทุกคนที่ตามหลังชายคนนั้นชอบสวมหมวกเบเร่ต์ใช่ไหมล่ะ?","Mariru")
	novel_interface.change_background("res://assets/images/bg/Fabiola/BAR2.png")
	await novel_interface.show_text_only("บริกรปรากฏตัวข้างมาริรุ")
	await novel_interface.show_dialog("พวกเขานำสกัลด์มา She’s downstairs now.","พนักงานเสิร์ฟ")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("ก็อตชา เก็บไฟล์เหล่านี้ออกไปแล้วพาเธอขึ้นมา","Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("ครับเจ้านาย","พนักงานเสิร์ฟ")
	novel_interface.change_background("res://assets/images/bg/Fabiola/BAR.png")
	await novel_interface.show_text_only("มาริรุปรบมือของเธอหนึ่งครั้ง หน้าจอสีดำที่ไม่แสดงอะไรเลยนอกจากโลโก้ SID เดียวจะกะพริบทันทีเพื่อแสดงภาพทิวทัศน์ของเมืองในเวลากลางคืนแบบเรียลไทม์")
	await novel_interface.show_text_only("เธอเฝ้าดูป้ายโฆษณาสีแดงน้ำเงินขนาดยักษ์บนอาคารที่สว่างขึ้นลงไวน์ที่เหลือของเธอ")

	print("=== 创伤反射篇第14话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
