# traumareflex_ep08.gd - 创伤反射篇第08话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	traumareflex_ep08_script()

func play_script():
	pass

func traumareflex_ep08_script():
	novel_interface.change_background("res://assets/images/bg/Shot/storyBGWar.png")
	await novel_interface.show_text_only("──この世界は善良ではない。")
	await novel_interface.show_text_only("10年前の戦いは多くのものを奪っていった。")
	await novel_interface.show_text_only("孤児院には俺と同じような子供が沢山いたけど、\n一番不幸なのは自分だと思っていた。")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Mother.png")
	await novel_interface.show_text_only("失ったモノの重さは個々の価値観であって、\n特別大事な存在は、他人の裁量じゃ計れない。")
	await novel_interface.show_text_only("だからこそ、イージスの保護下にある俺には\n想像できていなかった──")
	await novel_interface.show_text_only("親族を失った後も、戦火の中で歯を食いしばり\n生きる人達。\n彼らが毎日どのような生活を送ってきたのかを。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("ス――ハ――")
	await novel_interface.show_text_only("ス――ハ―――")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Street_Fighting1.png")
	novel_interface.change_music("res://assets/audio/music/Hand-to-hand combat.mp3")
	await novel_interface.show_text_only("マスクを装着して、\nなんとか濃煙の中を抜け出だした。\nそのまま道端に止まっている1台の車の裏に\n身を潜める。")
	await novel_interface.show_text_only("周囲を包む叫び声、次々と起こる炸裂音。\n地面には瓦礫が至る所に散らばっている。")
	await novel_interface.show_text_only("遠くにそびえ立つビルのモニターには、\n燃え盛る炎を隔てて、\n今も色鮮やかなCMが流れているのが見える。")
	await novel_interface.show_text_only("実に奇妙で現実離れした感覚が込み上げてくる。")
	novel_interface.show_character("ren_mercenary","solemn")
	await novel_interface.show_dialog("（ファビオラの記憶……だよな？）\n\n（こんな事ばかり経験してきたのだろうか……）","レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("こんな生活、俺とは本当にかけ離れている。")
	await novel_interface.show_text_only("SIDに編入してから様々な訓練を受けたけど、\nその多くが戦術や情報操作に関するものだった。")
	await novel_interface.show_text_only("実弾での演習はおろか射撃訓練場でも、\n反動が一番小さな銃しか使えなくて……\nマリルとアニーに何度笑われた事か……")
	novel_interface.show_character("ren_mercenary","sob")
	await novel_interface.show_dialog("（うぅ、アニーがいたら良かったのに……）","レン")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("ところで今俺が持っているのって……Vector？","レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Vectorは超低反動で有名なサブマシンガンだ。\n\n射出された亜音速弾の発砲音も鼓膜に優しく、\nマリルは「水鉄砲」と呼んでいた。")
	await novel_interface.show_text_only("……皆が皆、マリルみたいに大砲みたいな\nデッカイのが好きというわけじゃないからな！！")
	await novel_interface.hide_background()
	novel_interface.show_character("ren_mercenary","uneasy")
	await novel_interface.show_dialog("こ、この武器なら……","レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("俺は装着されているロングマガジンを見て、\n息を飲んだ。")
	novel_interface.show_character("ren_mercenary","shy")
	await novel_interface.show_dialog("（一旦、セーフティはかけたままにしとこう）\n\n（味方を撃ってしまうとあれだし……）","レン")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Street_Fighting1.png")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("俺は顔を半分覗かせ、外の様子を観察する。")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("キャセール。運転席にいた奴の様子はどうだ？","ラッセル")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("クソったれが、死んじまってるッ！！\n……おい、こっちの方はまだ息があるぞ！！","キャセール")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("そいつにガスマスク着けたら車のトランクに\n放り込んでッ！！\n武器を持ったらさっさとカバーを探しなさいッ！","ファビオラ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ファビオラは黒いハンドバッグを1つ持つと、\n軽やかに俺の近くの遮蔽物に飛び込んだ。")
	novel_interface.show_character("ren_mercenary","perspire1")
	await novel_interface.show_dialog("（というか、みんな動きが早いッ！！）\n\n（め、目が追いつかないぞッ！？）","レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("小隊員達の動きに一切の迷いがない。\n\nラッセルは先ほど爆破した天井の装甲板を\nガレキの脇に立てて死角を作り、\n身を隠しながら道の向かい側へと這って行く。")
	await novel_interface.show_text_only("それを尻目に濃煙の中から大きな\nリュックサックが飛んできた。\nそしてキャセールも大胆に1回転しながら\n姿を見せ、速やかに曲がり角の陰へと潜り込む。")
	await novel_interface.show_text_only("この状況でも、常に激戦区で任務を遂行している\n部隊にとっては、朝飯前という事か……")
	await novel_interface.show_text_only("今回の戦場が第二学園都市の街中と言うだけで、\n後は他と何も変わりないのだろう。")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("機械部隊に気を付けてッ！\nドローンを出して戦場を観察！！\nラッセル、アルファ隊に連絡はできる？","ファビオラ")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("返事がないな……\n彼らと「荷物」はガレキの向こう側だ。","ラッセル")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ラッセルの指差す方向を見ると、\n道路は綺麗に吹き飛ばされていた。\n今の俺達は道路の中央に閉じ込められている。")
	await novel_interface.show_text_only("焼け焦げたアスファルトが、\n大きな塊となって地面に打ち上げられており、\n向こう側の様子は全く見えない。")
	novel_interface.show_character("ren_mercenary","serious")
	await novel_interface.show_dialog("（……あらかじめ爆弾が埋められてたのか？）","レン")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("おい、新入りッ！！\nそれでケツを守ってるつもりッ！？","ファビオラ")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","perspire1")
	await novel_interface.show_dialog("──はいッ！？\n（俺の事っ！？）","レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("俺が呆然としていると、急に首のあたりに\nグイッと力が──\nファビオラが俺のコートを掴んで壊れたATMの\n陰まで引っ張ってくれたみたいだ。")
	novel_interface.show_character("fabiola_battle","perspire")
	await novel_interface.show_dialog("敵の居場所も分からない状態で、明るい場所に\n隠れるなんてね。\n呑気にショッピング中のお嬢さんでも演じている\nつもりなの？","ファビオラ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("俺の返事を待たずに、彼女は街道の向かいで\n身を潜めているラッセルにサインを送った。\n向こうは親指を立てて応じている。")
	await novel_interface.show_text_only("数秒後、彼の隠れている車の後ろから\n灰色のUFOみたいな飛行物体が、\nゆっくりと上昇を始めた。")
	await novel_interface.show_text_only("ファビオラは腰から小型タブレットを取り出し、\n画面に表示された戦域のパノラマを観察する。")
	await novel_interface.show_text_only("先頭2台のSUVは、すでに黒煙を吐く火の玉と\n化していた。")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("あっちのボディーガード連中はお陀仏ね……\n\n幸いアルファ隊と「荷物」を積んでいた車は\n私達の後ろで無事みたいよ。","ファビオラ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("周囲を警戒しながらタブレットを眺め、\n状況を確認するファビオラ。\nそんな最中、突然タブレットの映像が真っ白に\n変わり、次にドカンと爆発が聞こえてくる。")
	await novel_interface.show_text_only("微弱な電気を纏う空気の叫びと共に、\n灰色の飛行物体が空中で砕け散ったのだ。")
	await novel_interface.show_text_only("粉々に砕けたパーツが空から舞い落ちてきた。\n\n付近の車の屋根に当たり、\n金属同士のぶつかり合う音が淡々と響く。")
	novel_interface.show_character("ren_mercenary","serious")
	await novel_interface.show_dialog("──スナイパーッ！？","レン")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("向かいのビルッ！！短距離レールガン仕様の\n対物ライフルよッ！\n遮蔽物の厚さに注意してッ！！","ファビオラ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金属弾頭を加速して打ち出すレールガンは、\n極めて高い貫通力を誇るが、\n設備の移動が難しいという欠点を持っている。")
	await novel_interface.show_text_only("しかし戦時中、ある国の首相が厚さ1メートルの\nコンクリートの壁に隔てながらも、\n500メートル以上離れた距離からの遠距離狙撃で\n暗殺された事件があった。\nゆえに欠点を差し引いても、狙撃装置としての\n評価は高い。")
	await novel_interface.show_text_only("今の知識はSIDの研修に入ってなかったけど……\n\nゲームで販売されていた、この武器の\n限定カラーがどうしても忘れられなくて……")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("『スカイアイ』が敵の攻撃で撃墜された！\n繰り返すッ！ 『スカイアイ』が撃墜されたッ！","ラッセル")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("チッ。相手は少なくとも800メートル以上、\n離れてやがるな……\n残りのドローンは屈折コーティングに\n「プロビデンスの目」を搭載した1機のみか。\nだが、こいつならば見つかる可能性は\n低いと思うぜ……","キャセール")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","panic")
	await novel_interface.show_dialog("──待って。\n\nそれのレンズマウントは直径15センチぐらい\nあったわよね？","ファビオラ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ファビオラは反射鏡を使い、照明が灯っている\n向かいのビルを観察する。")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("たとえ夜間だとしてもレンズが、あの光を\n反射してしまうわ。","ファビオラ")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("まずいぜ……あのビルは一般市民だらけの\n場所じゃねえか。\n正確な位置が分からないと、反撃もできねえ。","キャセール")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("スナイパーにとって最も重要な事は、\n自らの位置を特定されない事。\n特に移動が難しく、弾の交換に手間取る装置を\n使っているなら、なおさらだ。")
	await novel_interface.show_text_only("これは戦術訓練の授業で教わった知識。")
	await novel_interface.show_text_only("でも、情報操作の授業かなんかでこれ関連する\n大事な補足があったような……")
	novel_interface.show_character("ren_mercenary","normal1")
	await novel_interface.show_dialog("（最もバレてはいけないのは……）\n\n（『位置』だけか？）","レン")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("さっきの銃撃で俺達が真っ先に気付いた事は、\nスナイパーが『存在』するって事だ。")
	await novel_interface.show_text_only("この場合に考えられるのは、相手が自分の存在を\n自ら曝け出し、\n敵の裏取りも考えずに待ち続ける、\n初心者ガン待ちスナイパーか……")
	await novel_interface.show_text_only("あるいは2発目で撃つべきターゲットの位置を\n「すでに知っているか」……ッ！")
	await novel_interface.show_text_only("瞬間的に心底から嫌な予感と違和感が\n俺に押し寄せた。")
	await novel_interface.show_text_only("身体が条件反射で跳ね上がり、遮蔽物に寄り添い\n周囲を警戒しているファビオラを押し倒す。")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("な、何するのッ！？　ば──","ファビオラ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("次の瞬間、彼女が頼りにしていた遮蔽物が\n粉々に砕け散った。")
	await novel_interface.show_text_only("弾丸の勢いは衰えず、建物の壁まで貫通し、\n1平方メートル幅の巨大なクレーターを作る。")
	await novel_interface.show_text_only("ATMは押しつぶされ、中から大量の札束が\n花吹雪のように宙に噴出した。\n街灯の白い光の下で、ひらひらと舞い落ちる。")
	await novel_interface.show_text_only("そんな奇妙な光景はフィルム・ノワールの\n一幕のような感じがした。")
	await novel_interface.show_text_only("俺が呆けていると、突然ファビオラが俺の腰を\n太ももで挟んだ。\nそして変な体勢になりながらも、\n新たな遮蔽物へと身をひるがえす。")
	novel_interface.show_character("ren_mercenary","awkward")
	await novel_interface.show_dialog("（あれっ？）\n\n（いつのまにか俺が下になってるけどっ？？）","レン")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("大丈夫か姉御ッ！！","キャセール")
	novel_interface.show_character("fabiola_battle","mock")
	await novel_interface.show_dialog("ええ……平気よっ！\n新入りも中々やるじゃない～～っ！","ファビオラ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ファビオラは俺の上にまたがって、\n話しながら俺の顔を軽く叩いた。")
	novel_interface.show_character("fabiola_battle","wink")
	await novel_interface.show_dialog("さてと、レンズの反射を防止する良い案を\n思い付いたわ。","ファビオラ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("そう言って彼女は、俺の太ももに手を伸ばす──")

	print("=== 创伤反射篇第08话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
