# traumareflex_ep01.gd - 创伤反射篇第01话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放创伤反射篇第01话剧本
	traumareflex_ep01_script()

func play_script():
	pass

# 创伤反射篇第01话 - 正式剧本
func traumareflex_ep01_script():
	novel_interface.show_background("res://assets/images/bg/Fabiola/Brain.png")
	await novel_interface.show_text_only("อะโนโซโนเซีย—")
	await novel_interface.show_text_only("ภาวะที่บุคคลไม่สามารถรับรู้ถึงการสูญเสียหน้าที่ทางอินทรีย์บางอย่างของตนเองได้ในช่วงระยะเวลาหนึ่ง")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Anton's_Blindness.png")
	await novel_interface.show_text_only("ตัวอย่างเช่น คนตาบอดเชื่อว่าพวกเขายังคงมองเห็น และในความเป็นจริงสามารถอธิบายสภาพแวดล้อมในจินตนาการของตนได้อย่างชัดเจน")
	await novel_interface.show_text_only("คนเป็นอัมพาตเชื่อว่าตนเองยังสามารถขยับแขนขาได้ตามปกติ จนถึงจุดที่คิดว่าคนอื่นๆ กำลังขยับแขนขาของตนในลักษณะเดียวกัน")
	await novel_interface.show_text_only("ในทางการแพทย์ ปรากฏการณ์นี้เรียกว่าอาการตาบอดของแอนตัน")
	await novel_interface.show_text_only("สมองในการให้คำอธิบายที่สมเหตุสมผลสำหรับสถานการณ์ที่ไม่อาจหยั่งรู้ได้ จะสร้างชุดภาพเพื่อโน้มน้าวร่างกายว่าทุกอย่างเรียบร้อยดี")
	await novel_interface.show_text_only("บางทีมันอาจเป็นภาพสะท้อนโดยธรรมชาติที่มนุษย์ทุกคนมีอยู่")
	await novel_interface.show_text_only("กลไกการป้องกันโบราณต่อสิ่งแปลกปลอมที่ตั้งโปรแกรมไว้ในยีนของเรา")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("…")
	novel_interface.change_music("res://assets/audio/music/Noise.mp3")
	await novel_interface.show_text_only("ฉันปวดหัว")
	await novel_interface.show_text_only("ปวดหัวอย่างรุนแรงจริงๆ")
	await novel_interface.show_text_only("รู้สึกเหมือนมีคนเทกระสอบซีเมนต์เข้าไปในสมองของฉัน และกำลังกวนมันอยู่")
	await novel_interface.show_text_only("สมองของฉันวูบวาบ หูอื้อ")
	await novel_interface.show_text_only("ฉัน... อยู่ข้างในเหรอ?")
	novel_interface.change_background("res://assets/images/bg/Fabiola/APC_Blur.png")
	await novel_interface.show_text_only("ฉันกระพริบตาและลืมตาขึ้น รูม่านตาค่อยๆ คุ้นเคยกับสภาพแวดล้อมที่สว่างสดใส")
	await novel_interface.show_text_only("หูของฉันดูเหมือนจะยังไม่ปรับเลย รู้สึกเหมือนทุกเสียงอู้อี้มาจากที่ไกลแสนไกล")
	await novel_interface.show_text_only("อากาศมีกลิ่นเหมือนโคโลญผสมกับหนังและกลิ่นสนิมทองแดง")
	await novel_interface.show_text_only("ในพื้นที่แคบที่ห่อหุ้มด้วยแผ่นโลหะหนา มีที่นั่งสองแถวเรียงกันหันหน้าเข้าหากัน ทหารที่นั่งอยู่บนนั้นต่างพากันหัวเราะคิกคัก")
	await novel_interface.show_text_only("พวกเขาไม่มีชุดเครื่องแบบ แต่บอกได้ง่ายว่าพวกเขาอยู่ในยูนิตเดียวกันจากอุปกรณ์ IFF ทรงกลมที่เรืองแสงที่พวกเขาสวมใส่")
	await novel_interface.show_text_only("ลักษณะหน่วยรบพิเศษภายใต้สังกัด ฤทธิ์นลาภ องค์กรข่าวกรองใน Second Academy City")
	await novel_interface.show_text_only("ถ้าฉันพูดถูก ฉันอยู่ในท้องรถบรรทุกหน่วยสวาท F-950...")
	await novel_interface.show_text_only("ไม่กี่ปีที่ผ่านมา มหาเศรษฐีคนหนึ่งซื้อเรือบรรทุกบุคลากรหุ้มเกราะราคาแพงลำหนึ่ง และปรับปรุงใหม่ให้ดูเหมือนไนท์คลับหรูหรามากกว่ายานพาหนะทางทหาร")
	await novel_interface.show_text_only("จากนั้นเขาก็ให้คนอื่นๆ ยิงรถบรรทุกพร้อมอาวุธ ขณะที่เขานั่งจิบแชมเปญอยู่ข้างในกับสาวๆ อีกสองสามคน")
	await novel_interface.show_text_only("วิดีโอดังกล่าวแพร่สะพัดทางออนไลน์ สร้างชื่อเสียงอย่างกว้างขวางให้กับเรือบรรทุกกำลังพลพิเศษที่หุ้มเกราะลำนี้ ซึ่งเสริมด้วยสาร H.")
	novel_interface.change_background("res://assets/images/bg/Fabiola/NewMoridas.png")
	await novel_interface.show_text_only("บนหน้าจอโปรเจ็กเตอร์ในรถยนต์ กำลังเล่นภาพแบบเรียลไทม์ที่กล้องด้านบนของรถบรรทุกบันทึกไว้")
	await novel_interface.show_text_only("แสงไฟในเมืองดูน่าทึ่งภายใต้ท้องฟ้ายามค่ำคืน มีตึกระฟ้าหลายสิบแห่งที่ยังอยู่ระหว่างการก่อสร้าง")
	await novel_interface.show_text_only("แท่งเหล็กดูเหมือนจะขยายออกไปจนสุดท้องฟ้า—เหมือนสัญลักษณ์ที่แสดงถึงความโลภอันเปลือยเปล่าของมนุษย์ที่ไม่มีที่สิ้นสุด")
	await novel_interface.show_text_only("ด้านหลังกลุ่มอาคารสูงเสียดฟ้า ซีกโลกสีดำขนาดมหึมาที่เรียกว่าอาณาจักรแห่งความมืดปรากฏอยู่บนขอบฟ้า")
	await novel_interface.show_text_only("ภายใต้การบริหารของคณะกรรมการ Seventeen Gentlemen เมืองแห่งการศึกษาแห่งนี้ยังคงรักษาตำแหน่งเป็นศูนย์กลางทางเศรษฐกิจและการเงินของโลกแม้หลังสงคราม")
	await novel_interface.show_text_only("ใช่แล้ว—นี่คือที่ที่ฉันอยู่ตอนนี้ เมืองแห่งการศึกษาที่สอง: นิวโมริดาส")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("<ไม่กี่ชั่วโมงที่แล้ว>")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("งั้น... คุณอยากให้ฉันเจาะเข้าไปในสมองของเป้าหมายและเข้าถึงความทรงจำของเธอเหรอ?","Ren")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("พูดง่ายๆ ว่า... ใช่","Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","bored")
	await novel_interface.show_dialog("เดี๋ยวก่อน มันทำได้ด้วยเหรอ?","Ren")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("อุปกรณ์ที่สามารถเชื่อมต่อกับสมองได้...","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ไม่ว่ามันจะดึงความทรงจำไปยังเซิร์ฟเวอร์ หรือว่ามันทำให้เราสามารถเข้าถึงความคิดของใครบางคน...")
	await novel_interface.show_text_only("ดูเหมือนไม่ปลอดภัย! ฉันเคยเห็นอุปกรณ์ประเภทนี้ในอนิเมะและภาพยนตร์มากมาย และมันก็ใช้ไม่ได้ผลดีนัก!")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("เฮ้ อย่าบิดกางเกงในนะ","Aya")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("เป็นอุปกรณ์ทดลองที่จัดทำโดย Harima Tech ออกแบบมาโดยเฉพาะสำหรับการขุดข้อมูล หรือฉันควรจะสอบสวนดี?","Aya")
	novel_interface.change_expression("wink")
	await novel_interface.show_dialog("นอกจากนี้ ฉันยังได้อัพเกรดระบบป้องกันความผิดพลาดด้วยตัวเอง แม้ว่าการบาดเจ็บหรือเสียชีวิตจะเกิดขึ้นภายในศีรษะของเป้าหมาย คุณจะไม่ได้รับอันตรายในชีวิตจริง","Aya")
	await novel_interface.show_dialog("คุณจะตื่นขึ้นโดยอัตโนมัติหลังจากเชื่อมต่อเป็นเวลาหกชั่วโมง มันปลอดภัยอย่างสมบูรณ์","Aya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("เอ่อ โอเค...","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ฉันพยายามโน้มน้าวตัวเองว่าถ้าอายะมั่นใจขนาดนั้นก็คงไม่เป็นไร")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("ฟังนะ เมื่อเชื่อมต่อกับอุปกรณ์ คุณจะไม่มีตัวตนจริงๆ คุณแค่มาสังเกตเหมือน...ผี","Mariru")
	await novel_interface.show_dialog("สิ่งที่คุณต้องทำคือค้นหาข้อมูลสำคัญในความทรงจำของเป้าหมาย อย่าทิ้งก้อนหินไว้โดยไม่เปิด","Mariru")
	await novel_interface.show_dialog("ขณะนี้เป้าหมายอยู่ในระดับสูงในระดับโคม่า เราไม่รู้เกี่ยวกับอดีตของเธอมากนัก ดังนั้นเราจึงไม่แน่ใจว่าเธอติดอยู่ในส่วนไหนของความทรงจำในปัจจุบัน","Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("ซึ่งหมายความว่าคุณต้องใส่ใจทุกรายละเอียด... แม้ว่าเป้าหมายของคุณอยู่ในห้องอาบน้ำก็ตาม!","Aya")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("เฮ้ ฉันไม่อยากเป็นคนถ้ำมอง!","Ren")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("อย่ามองในจุดที่ไม่ควร","Ren")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("อืม…","Ren")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","blush_stare",0.25)
	await novel_interface.show_dialog("เอาล่ะ ฉันเข้าใจแล้ว!","Aya")
	await novel_interface.show_dialog("น่าเสียดายที่อุปกรณ์นี้ไม่กระตุ้นเส้นประสาท ไม่เช่นนั้นคุณจะสามารถโต้ตอบกับสิ่งแวดล้อมได้เช่นกัน...","Aya")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("อายะเริ่มหลงใหลในจินตนาการของเธอแล้ว")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("เฮ้ ไม่ว่าคุณจะคิดอะไรอยู่ ฉันไม่ทำหรอก!","Ren")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("มาริรุม้วนกระดาษแล้วฟาดหลังอายะ")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…")
	await novel_interface.show_text_only("ดูเหมือนว่าฉันจะเข้าไปในความทรงจำของเป้าหมายแล้ว")
	await novel_interface.show_text_only("ฉันคิดว่ามันคงจะเหมือนกับเกมยิงมุมมองบุคคลที่หนึ่ง...")
	await novel_interface.show_text_only("แต่จริงๆ แล้ว มันซับซ้อนกว่ามาก")
	await novel_interface.show_text_only("ทุกอย่างพร่ามัว ฉันต้องเหล่อย่างหนักเพื่อที่จะมีสมาธิ")
	novel_interface.change_music("res://assets/audio/music/Noise.mp3")
	novel_interface.change_background("res://assets/images/bg/Fabiola/APC_Blur2.png")
	await novel_interface.show_text_only("ตอนนี้ ฉันอยู่ในรถบรรทุกหุ้มเกราะพร้อมกับชายผิวสีหลายคน ฉันเงี่ยหูฟังเพื่อฟังบทสนทนาของพวกเขา")
	await novel_interface.show_dialog("รัฐสภาแห่งสหประชาชาติสงบศึกมานานกว่าหนึ่งปีแล้ว แต่ประเทศอื่นๆ ทั่วโลกยังคงต่อสู้อย่างไม่หยุดยั้ง","เสียงชาย ก")
	await novel_interface.show_dialog("ผู้นำของหกชาติในสภาแห่งสหประชาชาติกำลังจัดฟอรัมสันติภาพนานาชาติอยู่ในขณะนี้ ฝูงชนที่ประท้วงกำลังเดินขบวนไปตาม First Avenue ในขณะที่เราพูด","เสียงชาย ก")
	await novel_interface.show_text_only("ฉันได้ยินเสียงผู้ชายห้าวดังมาจากที่นั่งผู้โดยสาร แต่ฉันไม่สามารถบอกได้ว่าเขาหน้าตาเป็นอย่างไรจากมุมมองของฉัน")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("เป็นเวทีแห่งสันติภาพครั้งที่สองแล้วไม่ใช่หรือ? มันไม่มีประโยชน์อย่างชัดเจน","ชาย บี")
	await novel_interface.show_dialog("การระเบิดสองถึงสามครั้งยังคงเกิดขึ้นทุกสัปดาห์ ห่างจาก Third Academy City เพียงสองไมล์","ชาย บี")
	await novel_interface.show_dialog("ป้าของฉันที่อาศัยอยู่ที่นั่นคุ้นเคยกับมันแล้ว แม้แต่เด็กทารกในพื้นที่ก็แทบจะไม่ตอบสนองต่อแรงระเบิดอีกต่อไป","ชาย บี")
	await novel_interface.show_text_only("คนที่พูดต่อไปคือชายผิวสีซีดในวัยสามสิบหรือสี่สิบ มีผมสีน้ำตาลไร้ที่ติ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("อืม หนึ่งปีหลังจากการสงบศึก และเวทีสันติภาพนานาชาติครั้งที่ 2...")
	await novel_interface.show_text_only("ช่วยให้ฉันสามารถระบุความทรงจำนี้เมื่อประมาณสองปีที่แล้วได้")
	await novel_interface.show_text_only("ท้ายที่สุดแล้ว ฟอรัมสันติภาพนานาชาติครั้งที่ 4 จะจัดขึ้นในเดือนหน้าที่เมืองนิวโอปูเลนเทีย")
	await novel_interface.show_text_only("ฉันจำได้ว่ามาริรุบ่นเมื่อสัปดาห์ที่แล้วว่าเขตปลอดทหารที่ตกลงไว้คงจะยุ่งเหยิงเมื่อถึงเวลา")
	await novel_interface.show_dialog("ผู้ก่อการร้ายพวกนั้น... พวกเขาสติแตกไปแล้ว!","เสียงชาย ก")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("ลองดูแผนการป้องกันเมืองใหม่ในมาซาดา รู้สึกเหมือนพวกเขากำลังตั้งเป้าที่จะเปลี่ยนเมืองให้กลายเป็นป้อมปราการหรืออะไรสักอย่าง","ชายซี")
	await novel_interface.show_text_only("ผู้ชายที่นั่งตรงข้ามฉันดูเหมือนอายุยี่สิบ มีผิวสีแทนและผ้าพันคอลายโครงกระดูก")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("เอ๊ะ สงครามเป็นเรื่องธรรมดาเกินไปในมาซาดา ใครจะรู้ บางทีระเบิดนิวเคลียร์อีกลูกอาจจะตกใส่หัวพวกเขาสักวันหนึ่ง","ชาย บี")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("โอ้ ว่าแต่ พวกคุณได้ยินไหม? พวกที่อยู่ในสภา...","เสียงชาย ก")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("คนเหล่านั้นเหรอ? เกิดอะไรขึ้นกับพวกเขาตอนนี้?","ชาย บี")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("พวกเขาอนุญาตให้อาสาสมัครออกสำรวจสู่อาณาจักรแห่งความมืด!","เสียงชาย ก")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("โอ้ คุณหมายถึงสิ่งที่คล้ายโดมสีดำน่าขนลุกใกล้ลองไอส์แลนด์เหรอ?","ชาย บี")
	await novel_interface.show_dialog("ไม่มีสิ่งใดที่เข้าไปในนั้นออกมา แม้แต่โดรนก็ตาม","ชาย บี")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("หากไม่ใช่เพราะสิ่งที่ปรากฏขึ้นมาและกลืนกองเรือบรรทุกเครื่องบินไปสิบสองลำ สภาก็คงไม่ดำรงอยู่อีกต่อไป","เสียงชาย ก")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("ใครจะรู้ บางทีมันอาจจะเกี่ยวข้องกับครัวแม่ของรัสเซลใช่ไหม?","ชายซี")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("ดูสิว่าใครกำลังพูดอยู่ แคสเซล! บางทีมันอาจจะนำไปสู่ดาวดวงอื่น คุณรู้ไหมคนที่คุณมาจาก","Russel")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("หืม. ตอนนี้ผู้คนกำลังเรียกร้องให้เข้าสู่อาณาจักรแห่งความมืดใช่ไหม? กลุ่มคนโง่ที่มีเวลามากเกินไป","เสียงผู้หญิง")
	await novel_interface.show_text_only("เดี๋ยวก่อน นั่นผู้หญิงพูดเหรอ?")
	await novel_interface.show_text_only("ฟังดูไม่เข้ากันเป็นพิเศษท่ามกลางเสียงขรมของเสียงผู้ชายที่หยาบคาย")
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_text_only("ฉันตามเสียงนั้นและเห็นเด็กสาวผมสีชมพูคนหนึ่งซ่อนตัวอยู่หลังไหล่กว้างของแคสเซล สวมหมวกเบเร่ต์และแว่นตากรอบสีแดง")
	await novel_interface.show_text_only("ฉันจำเธอได้ทันทีจากแว่นตา เธอคือเป้าหมายของเรา นั่นคือฟาเบลล่า เด็กผู้หญิงที่ฉันเคยพบเมื่อกลับมาที่โรงแรมสกาย")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ไอจากที่นั่งผู้โดยสารรบกวนความคิดของฉัน")
	await novel_interface.show_dialog("ฟาเบลล่าพูดถูก! อ้อ ยังไงก็ตาม ไม่มีนักวิทยาศาสตร์หน้าใหม่ใน New Opulentia ชื่อ... Marie หรืออะไรสักอย่างเหรอ?","เสียงชาย ก")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("มาริรุ ฉันจำเธอได้!","Cassel")
	await novel_interface.show_dialog("เธอได้ขึ้นปกนิตยสาร Science ฉบับที่แล้ว! สวมถุงน่องสีดำ ยัม! พวกเนิร์ดในแผนกวิจัยต่างก็น้ำลายไหลกันหมด","Cassel")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("คุณอ่านนิตยสารวิทยาศาสตร์แล้วเหรอ? คิดว่าคุณสามารถหาผู้หญิงที่มีควอนตัมฟิสิกส์หรืออะไรสักอย่างได้ไหม?","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("ไม่ใช่ความผิดของฉัน แม็กซ์ซื้อยี่สิบฉบับพร้อมกัน","Cassel")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("เมื่อสองปีก่อนมาริรุดังแล้วเหรอ? ฉันก็อยากเห็นนิตยสารเล่มนั้นเหมือนกัน...")
	await novel_interface.show_dialog("ได้ยินมาว่าเธอมีส่วนโค้งถูกทุกจุด","เสียงชาย ก")
	await novel_interface.show_text_only("คุณกำลังเพ้อฝันเกี่ยวกับร่างกายของนักวิทยาศาสตร์ใช่ไหม? การถูกสร้างเป็นตัวอย่างนั้นเป็นความหงิกงอของคุณหรือไม่?")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("กัปตันกำลังจับตาดูคุณอยู่!","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_dialog("ฮึ. คุณสิ้นหวัง. เห็นสาวสวยแล้วเซลล์สมองหายไปทันที","Fabella")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("คุณควรระวัง ไม่อย่างนั้นสักวันหนึ่งคุณจะถูกทิ้งเปลือยเปล่าในสุสานรถยนต์ เหมือนครั้งนั้นที่คุณลองใช้เว็บไซต์หาคู่","Fabella")
	novel_interface.change_expression("wink")
	await novel_interface.show_dialog("ใครๆ ก็คิดว่าคุณมีเซ็กส์กับรถเชอโรกีปี 1962 ตัวนั้น โตพอที่จะเป็นคุณย่าแล้วใช่ไหม?","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("ฮ่า หัวหน้า หยุดย่างคนจนได้แล้ว สาขาภาคใต้ทั้งหมดรู้เรื่องนี้แล้ว","Cassel")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("บอสเหรอ? เดี๋ยวนะ เด็กสาววัยรุ่นคนนั้นคือหัวหน้าหน่วยรบพิเศษนี้เหรอ?")
	await novel_interface.show_text_only("เธอไม่เหมือนสาวใช้ที่ฉันเห็นครั้งล่าสุด เกิดอะไรขึ้นระหว่างตอนนั้นถึงตอนนี้?")
	await novel_interface.show_text_only("ไม่ เดี๋ยวก่อน นี่คือเมื่อสองปีที่แล้ว ดังนั้นฉันควรจะพูดว่า: เกิดอะไรขึ้นระหว่างนี้ถึงตอนนั้น?")
	await novel_interface.show_text_only("อย่างไรก็ตาม ฉันก็พบเป้าหมายแล้ว การมองเห็นของฉันยังเบลออยู่เล็กน้อย และฉันยังคงปวดหัวอย่างรุนแรง")
	await novel_interface.show_dialog("เอาล่ะ หุบปาก!","เสียงชาย ก")
	await novel_interface.show_dialog("อะแฮ่ม... วันนี้เรามีมือใหม่เข้าร่วมทีมไม่ใช่เหรอ?","เสียงชาย ก")
	await novel_interface.show_dialog("อย่าพูดเล่นนะ First Impression นั้นสำคัญ...","เสียงชาย ก")
	await novel_interface.show_text_only("มือใหม่เหรอ?")
	await novel_interface.show_text_only("สำหรับหน่วยรบเช่นนี้ สมาชิกในทีมจะต้องประสานกันจึงจะทำงานร่วมกันได้ดี ผู้มาใหม่สามารถเขย่าไดนามิกทั้งหมดได้")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("เจ้าหนู คุณกระสับกระส่ายไม่หยุดเลย เกิดอะไรขึ้นกับคุณ?","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("คุณกำลังมองหาหัวของคุณเองหรืออะไร? มันติดอยู่ที่คอของคุณ!","Cassel")
	await novel_interface.show_dialog("ถึงกระนั้น ใครจะรู้ คุณอาจสูญเสียมันไปในภารกิจนี้...","Cassel")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","bored")
	await novel_interface.show_dialog("หยุดหลอกเด็กใหม่ได้แล้ว เขาไม่ใช่เด็กทารก","Fabella")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("หืม? พวกเขากำลังพูดถึงใคร?")
	await novel_interface.show_text_only("ฉันยกมือขึ้นโดยสัญชาตญาณ อยากจะขยี้ตาที่พร่ามัวของฉัน แต่ข้อนิ้วของฉันไปโดนสิ่งกีดขวางที่มองไม่เห็น")
	await novel_interface.show_text_only("—เดี๋ยวนะ ฉันรู้สึกและควบคุมมือตัวเองได้...?")
	await novel_interface.show_text_only("และฉันก็ปวดหัวมาตั้งแต่แรก...")
	await novel_interface.show_text_only("แต่อายะบอกว่าควบคุมหรือรู้สึกอะไรไม่ได้เลย...ใช่ไหม?")
	novel_interface.change_background("res://assets/images/bg/Fabiola/APC.png")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	await novel_interface.show_text_only("ทันใดนั้น แคสเซลก็ยืดแขนออกและถอดหมวกกันน็อคที่ปิดอยู่ของฉันออก การมองเห็นของฉันชัดเจนขึ้นทันที—โอ้ นั่นคือสาเหตุที่ทุกอย่างพร่ามัวและเสียงก็อู้อี้")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("โอ้โฮ","Russel")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","mock")
	await novel_interface.show_dialog("โอ้...","Fabella")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("เป็นเด็กผู้หญิง!","Cassel")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("ผู้หญิงเหรอ? ดี.","เสียงชาย ก")
	await novel_interface.show_text_only("…")
	novel_interface.show_character("ren_mercenary","panic")
	await novel_interface.show_dialog("หะ...?","Ren")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("เกิดอะไรขึ้น...?","Ren")

	print("=== 创伤反射篇第01话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
