# chapter2_ep18.gd - 第二章第18话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep18_script()

func play_script():
	pass

func chapter2_ep18_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_centreSpace1.png")
	await novel_interface.show_text_only("É uma tarde escaldante de verão. Coloco uma pilha de papéis ao lado da mesa redonda no pátio e afundo em uma cadeira à sombra das árvores.")
	await novel_interface.show_text_only("Há algum tempo, vi uma linda garota lutando com sua pilha de livros. Não pensei duas vezes e dei-lhe uma mão.")
	await novel_interface.show_text_only("Então ela simplesmente saiu correndo, embora felizmente. Foi quando percebi que sou um idiota.")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("Ufa... Deixa eu fazer uma pausa aqui... Está tão quente.", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Infelizmente, foi moleza para mim quando eu era menino.")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("E então tem esse SID treinamento chegando... Nossa, posso me esconder em algum lugar?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("Lian, cuidado com seus modos... \\nIsto é uma escola.", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("Ei, Annie! \\nE aí?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("Escute... Eu sei que está quente. \\nMas... é realmente necessário levantar a camisa para enxugar o suor?", "Annie")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("Quero dizer… Tenha cuidado com o mau funcionamento do guarda-roupa…", "Annie")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","wail",0.25)
	await novel_interface.show_dialog("Droga!", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_dialog("Aquela garota Lian é tão rude...", "Aluno A")
	await novel_interface.show_dialog("Pois é, outro dia eu a vi abrindo as pernas, de saia.", "Aluno B")
	await novel_interface.show_dialog("Sério? Eca…", "Aluno A")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("... \\n(Eu não deveria ter usado saias em primeiro lugar, ok?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ei…")
	await novel_interface.show_text_only("Que voz gentil.")
	novel_interface.show_character("nyx_normal","normal1")
	await novel_interface.show_dialog("Use meu lenço se não se importar.", "Garota elegante")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Na minha frente está uma garota linda e elegante. \\nEla tem cabelos longos e sedosos e roxos e olhos lilases.")
	await novel_interface.show_text_only("Ela me entrega um lenço com uma fragrância deliciosa e fresca.")
	novel_interface.show_character("ren_uniform","gratified")
	await novel_interface.show_dialog("Ei?! \\nObrigado… Obrigado.", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("nyx_normal","normal1")
	await novel_interface.show_dialog("Vocês são os alunos transferidos do primeiro ano, certo? \\nMeu nome é Nix Strozzi. Eu sou seu sênior.", "Nix")
	await novel_interface.show_dialog("Eu vi você suando e por acaso estou com meu lenço comigo, então... \\nEspero não estar interrompendo.", "Nix")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Nix acena para mim educadamente, mas eu enlouqueço. Eu me levanto e saúdo de uma forma bem idiota.")
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("Não... de jeito nenhum! \\nÉ uma grande ajuda!", "Lian")
	novel_interface.change_expression("blush")
	await novel_interface.show_dialog("(Ela parece muito amigável.) \\n(Ela é estrangeira? Olhe esses cílios longos...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Eu olho para o rosto delicado de Nix, meu coração dispara.")
	novel_interface.show_character("nyx_normal","normal1")
	await novel_interface.show_dialog("Prazer. \\nEntão... seu nome é...", "Nix")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","happy",0.25)
	await novel_interface.show_dialog("Eu sou Lian. Ela é Annie. \\nAcabamos de ser transferidos para cá recentemente.", "Lian")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("… Annie?", "Nix")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Nix parece confuso e encara Annie, embora brevemente.")
	await novel_interface.show_text_only("Então ela sorri para Annie de uma forma amigável. Eu me pergunto se foi apenas minha ilusão agora.")
	novel_interface.show_character("nyx_normal","normal1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_uniform","happy",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Prazer em conhecê-lo hoje.", "Nix")
	await novel_interface.show_dialog("Mas preciso ir agora. Deixe-me saber se houver algo que eu possa fazer para ajudar.", "Nix")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"smile")
	await novel_interface.show_dialog("Obrigado, Nix!", "Lian")
	novel_interface.character_2nd_move_left(-0.25)
	novel_interface.show_character("anne_uniform","upset",0.25)
	await novel_interface.show_dialog("…", "Annie")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Annie hesita sem qualquer resposta.")
	novel_interface.show_character("ren_uniform","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","upset",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Essa garota, Nix... ela parece muito mais elegante do que qualquer uma dessas garotas de colher de prata.", "Lian")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Annie, você está bem? \\nVocê esteve quieto.", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"unhappy")
	await novel_interface.show_dialog("Ela disse que é uma Strozzi?", "Annie")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Uh-huh, você a conhece?", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Annie pega meu braço e me dá um sorriso inocente.")
	novel_interface.show_character("ren_uniform","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","happy",0.25)
	await novel_interface.show_dialog("Não. \\nSomos novos aqui. Como eu poderia conhecê-la?", "Annie")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"smile")
	await novel_interface.show_dialog("Sim, você está certo.", "Lian")

	print("=== 第二章第18话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
