# chapter2_ep16.gd - 第二章第16话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep16_script()

func play_script():
	pass

func chapter2_ep16_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("愛衣は報告書を両手で持ち、スクリーン上にて\\n躍動するデータと照らし合わせている。\\nそして時折、部屋の中から彼女の啜り笑う声が\\n聞こえる。")
	await novel_interface.show_text_only("マリルは愛衣の背後から書類を抜き取り、\\n内容を確認した。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("愛衣は報告書を両手で持ち、スクリーン上にて\\n躍動するデータと照らし合わせている。\\nそして時折、部屋の中から彼女の啜り笑う声が\\n聞こえる。", "マリル")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","wink",0.25)
	await novel_interface.show_dialog("ああぁーー\\nなんて、なんて素晴らしいっ！！", "愛衣")
	novel_interface.change_2nd_expression("blush_think")
	await novel_interface.show_dialog("健康診断の結果はどうだった？\\nお前がそこまで喜ぶほどの物か。", "愛衣")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("分かっただろう、だからこその秘密厳守だ。\\nで、何か手掛かりは見つかったのか？", "マリル")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("今回、彼女達にテロメア検査を実施してみたの。\\n確かに二人とも年齢は15歳だね。\\nただし、アニーの身体だけど、セシウム‐137の\\n含有量が平均の4分の1にしか満たなかったわ。", "愛衣")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("よくそんな方法を思い付いたな……\\n\\nと言う事は、彼女は『七年戦争』を最大でも\\n半分しか経験していない事になるのか？", "マリル")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("彼女が戦争の後半、ずっと気密室に籠っていた\\n可能性を除けばね。", "愛衣")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("分かった。\\nレンの方は？", "マリル")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"think")
	await novel_interface.show_dialog("彼女が戦争の後半、ずっと気密室に籠っていた\\n可能性を除けばね。", "愛衣")
	novel_interface.character_light(0.35,"serious")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("…つまり、全く新しくできた肉体という事だな？", "マリル")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal")
	await novel_interface.show_dialog("レンちゃんはね……\\n筋肉組織から検出した含有量ですら、\\n一般平均の200分の1にも満たず、通常の\\n新生児が母体から受け継ぐ量よりも低いのよ。", "愛衣")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("…つまり、全く新しくできた肉体という事だな？", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("安心して～～\\n脊髓にウイルスは残っていなかったわ。", "愛衣")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("大まかに調べてみたけど、レンちゃんの免疫系統\\nの軌跡は大体数百年以内のものだけ。\\n中世以前のウイルス抗体はないみたい。", "愛衣")
	await novel_interface.show_dialog("それでも、彼女の白血球を使って、008、217と\\n742号ウイルスを培養してみたいなぁ……", "愛衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("……お前を校医に任命したのは、そんな奇天烈な趣味を満たすためじゃ無いからな。", "マリル")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","think",0.25)
	await novel_interface.show_dialog("はいはい、分かってるわよ～～\\n彼女達の観察はサボらないから。", "愛衣")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("彼女達は『ロス・ゴールド』の消失に、\\n関係している可能性が高い……\\n恐らく、まだ白状していない何かしらの秘密が\\n彼女達にはきっとある。", "マリル")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal")
	await novel_interface.show_dialog("閉じ込めて調べれちゃえばいいじゃない。", "愛衣")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_dialog("私が手伝おうか？\\n\\n今日の健康診断用の装置をちょっと改造すれば、\\nいい尋問道具になりそうだし！ハァ♥ハァ♥", "愛衣")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("愛衣は探求心による興奮を前面に押し出す\\n顔を見せた。\\nマリルは報告書を丸めて彼女を叩く。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("お前は監視をしっかりやってくれ。どんな些細な事であっても、すぐに私に報告するようにな。", "マリル")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("（あいつはすでに気付いていた。\\n　恐らくSIDの内部はとっくに……）", "マリル")
	await novel_interface.show_dialog("（学校に置いておけば、少しは好奇心を別方向へ　向けられるだろう）\\n（ついでに彼の小細工を抑制できれば……）", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_think")
	await novel_interface.show_dialog("お前は監視をしっかりやってくれ。どんな些細な事であっても、すぐに私に報告するようにな。", "愛衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("……お前も少しは自重しろ。", "マリル")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("えへへ、安心して。\\n\\n一回で絞り切っちゃったらもったいないからね。", "愛衣")

	print("=== 第二章第16话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
