# chapter2_ep06.gd - 第二章第6话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep06_script()

func play_script():
	pass

func chapter2_ep06_script():
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/spConferenceRoom.png")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("(Бормочет) Этот мальчишка был намного интереснее...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("На экране по диагонали перед Mariru мерцает приглашение на подключение голосового вызова. Намеренно искаженный электронный голос маскирует первоначальный пол говорящего.")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("(Я проводил этот брифинг много раз, но этот формат одностороннего зашифрованного вмешательства до сих пор бесит.)", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("Итак, что касается исчезновения Ross Goblet, как сейчас продвигается расследование?", "Kirs")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("Сегодня утром в 00:15 система безопасности подтвердила, что Ross Goblet исчез.", "Mariru")
	await novel_interface.show_dialog("В 06:40 система спутникового мониторинга «Истинное зрение» выдала предупреждение после обнаружения серьезных пространственных искажений.", "Mariru")
	await novel_interface.show_dialog("Затем, с 07:00 сегодняшнего утра до настоящего времени, система Aegis обнаружила шесть предупреждений о флуктуациях фазы пространства-времени в пределах New Opulentia.", "Mariru")
	await novel_interface.show_dialog("А если принять за центр НИИ, то одновременно появилось тридцать два подобных оповещения в радиусе полутора тысяч километров...", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("Все это уже есть в документе. Дайте мне заключение.", "Kirs")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru смотрит через правое плечо и улыбается.")
	await novel_interface.show_text_only("Только по тону она может сказать, что это суровый, неулыбчивый руководитель Сенат.")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("— Это не было воровством. Это было пробуждение Substance H вместе с цепной реакцией, которую оно вызвало.", "Mariru")
	await novel_interface.show_dialog("И судя по нынешней частоте и масштабам, мы до сих пор не можем определить, является ли это меметическим типом Substance H.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("В тот момент, когда Mariru заканчивает говорить, испуганный ропот и приглушенные дискуссии разносятся по затемненным экранам вокруг нее.")
	await novel_interface.show_text_only("!!!!!")
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("Что?!", "Kirs")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Слева от Mariru доносится глубокий, ровный голос.")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("Вы имеете в виду экспоненциальную вспышку воздействующего на разум «Божественного прикосновения»?\n Вот это интересно...", "Bright")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("На данный момент, скорее всего, одновременно произойдет несколько инцидентов.\n\"Божественное прикосновение\"... Я не особенно люблю неточную терминологию.", "Mariru")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("(Хотя он является авторитетом в области воздействия на разум Substance H...)", "Mariru")
	await novel_interface.show_dialog("(Я до сих пор не могу избавиться от ощущения, что эта горилла поджарила себе мозг из-за слишком большого количества радиации.)", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("Тогда по вашему мнению...?", "Bright")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("Я пока не могу представить итоговый отчет. У нас просто недостаточно действенной информации.", "Mariru")
	await novel_interface.show_dialog("Учитывая текущую ситуацию, я запрашиваю неограниченное расследование класса S. Надеюсь, вы все понимаете.", "Mariru")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Не обращая внимания на шепот вокруг нее, Mariru снова переключает свое внимание на портативный терминал.")
	novel_interface.character_light(0.35,"normal1")
	await novel_interface.show_dialog("(Эта маленькая девочка отправилась в другую аномальную зону...)", "Mariru")
	await novel_interface.show_dialog("(Как и ожидалось — она исчезла, через некоторое время снова появилась, а затем близлежащее колебание фазы снова прекратилось.)", "Mariru")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("(Кадры с места происшествия... на ней кровь?)", "Mariru")
	await novel_interface.show_dialog("(Эта идиотка... не говорите мне, что она на самом деле—!!)", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("senate_giles","",0.25)
	await novel_interface.show_dialog("Ты выглядишь немного отвлеченным.", "Kirs")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Что?... Совсем нет.", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("На что бы вы ни смотрели, есть ли в нем информация более важная, чем этот брифинг?", "Kirs")
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("...Нет, это просто видео с котенком. Хотите это увидеть?", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("!!!", "Kirs")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("Слева от Mariru раздается резкий электрический вой и жужжание.")
	novel_interface.character_light(0.35,"normal2")
	await novel_interface.show_dialog("Не сердись так. Небольшое отвлечение внимания повышает эффективность работы.", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("...", "Kirs")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,false)
	await novel_interface.show_text_only("Mariru обводит взглядом комнату. Кажется, никто сейчас не заметил мгновенного промаха.")
	novel_interface.character_light()
	await novel_interface.show_dialog("В любом случае, основная информация, которую мы получили на данный момент, полностью соответствует заявленной на брифинге.\nИнцидент все еще находится на стадии дальнейшего расследования.", "Mariru")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Если вопросов нет, отправляюсь на место происшествия.", "Mariru")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Прежде чем Mariru успевает уйти, слева от нее раздается несколько легкомысленный голос.")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("...Я слышал, что ваши подчиненные привезли двух старшеклассников обратно в SID на допрос?", "#C")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("...\n(Опять этот противный ублюдок.)", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("senate_#C","",0.25)
	await novel_interface.show_dialog("Было ли в них что-то особенное, Леди Mariru... нет, Доктор?", "#C")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("...Вообще ничего. Мы уже это подтвердили — это были всего лишь два чересчур любопытных котенка, которые пробрались в запретную зону.", "Mariru")
	await novel_interface.show_dialog("Я организую, чтобы их потом отправили домой.", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Я вижу. Тогда это хорошо.", "#C")
	await novel_interface.show_dialog("В такое непростое время было бы неприятно, если бы другие страны начали относиться к ним как к какому-то странному существованию...", "#C")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("Это замечание вызвало бурю негодования среди остальных.")
	await novel_interface.show_text_only("...Что это значит?")
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Я уверен, что неосторожное замечание может вызвать у некоторых людей дискомфорт.\nМои извинения — просто притворитесь, что вы этого никогда не слышали.", "#C")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"normal1")
	await novel_interface.show_dialog("...\n(Какой совершенно отвратительный человек.)", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("Что ж, несмотря на это, этот инцидент уже привлек внимание других Академгородов.", "Bright")
	await novel_interface.show_dialog("С этого момента мы будем полагаться на вас в проведении секретного расследования и управлении публичной информацией.", "Bright")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("Естественно.", "Mariru")

	print("=== 第二章第6话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
