# chapter2_ep11.gd - 第二章第11话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep11_script()

func play_script():
	pass

func chapter2_ep11_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/hall.png")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("Regardez qui est là ! Qu'est-ce que ça fait de devenir officiellement une fille, Lian ?", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","shy",0.25)
	await novel_interface.show_dialog("... S'il vous plaît, arrêtez de vous moquer de moi !", "Lian")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Très bien, très bien. Au fait, j'ai entendu dire que vous envisagez d'être transféré dans un autre lycée public après les vacances ?", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("Ouais. La nouvelle école est plus proche de chez moi et... les conditions de crédit ne sont pas aussi strictes...", "Lian")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Pour des raisons de sécurité, je vais vous trouver un nouveau logement.\nQuant à l'école...", "Mariru")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("(On dirait que je vais devoir demander une faveur à ce vieux con.)", "Mariru")
	await novel_interface.show_dialog("(Rien que d'y penser, c'est ennuyeux... heureusement que les enregistrements ont déjà été parfaitement corrigés...)", "Mariru")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("Lycée pour filles Gosakuragawa. Il a le niveau de sécurité le plus élevé et n'est pas loin non plus du quartier général de SID", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Pendant qu’elle parlait, Mariru pointait vers le haut.")
	await novel_interface.show_text_only("Gosakuragawa, le quartier commercial animé au-dessus du siège souterrain, abriterait une école prestigieuse aux frais de scolarité terriblement élevés.")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("W-Attends, ce n'est pas l'école des filles riches ?! Celui qu'ils appellent \"un paradis où fleurissent des lys purs et de splendides fleurs de cerisier\"...", "Lian")
	await novel_interface.show_text_only("Il s'agissait d'un texte publicitaire rédigé par des personnes hors sujet sur un certain forum indésirable en perpétuel crash pour se moquer des frais de scolarité scandaleux de Gosakuragawa.")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("Qu'est-ce que c'était ?", "Mariru")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("N-Non, rien du tout !", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak2")
	await novel_interface.show_dialog("Avec à quel point vous êtes stupide, vous pourriez bien finir par devenir un véritable ... truc pour tous ces étudiants des classes supérieures et inférieures.", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru eut un léger rire et ne termina pas la phrase.")
	novel_interface.show_character("ren_battle","awkward")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_dark()
	novel_interface.show_2nd_character("liliu_uniform2","speak2",0.25)
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Devenir quoi exactement ?!", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("Ce n'est pas le moment de laisser libre cours à votre curiosité.\nQuoi qu'il en soit, demain vous irez vous présenter comme il se doit.", "Mariru")
	await novel_interface.show_dialog("Ce ne sera pas aussi laxiste là-bas que dans une école publique.", "Mariru")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("Tu ne peux pas me laisser me détendre un peu... _(:3」∠)_")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("... Oh, c'est vrai. Et Annie ?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("Le parcours de cette fille est plutôt intéressant.", "Mariru")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Elle... qu'est-ce qui ne va pas chez elle ?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak2")
	await novel_interface.show_dialog("Les enregistrements sur Annie Bass dans le système ne remontent qu'à sept ans, alors qu'elle avait quinze ans.", "Mariru")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Il y a sept ans, cela signifie... qu'elle a déjà vingt-deux ans ?!\nElle a à peu près le même âge que moi !", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("C'est vrai. Même aujourd’hui, son âge osseux est toujours de quinze ans.", "Mariru")
	await novel_interface.show_dialog("Mais où elle est allée pendant cette période et pourquoi elle est soudainement réapparue, personne n'a encore compris, y compris Annie elle-même.", "Mariru")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("... Quoi qu'il en soit, je ne pense pas que Annie soit une mauvaise personne.", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("Vous pouvez être tranquille sur cela.\nAprès tout, il y a même des gens dans SID qui étaient ses fans.", "Mariru")
	novel_interface.character_light(0.35,"gratified")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Hein ?! Est-ce que Annie était une sorte d'idole ?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("... Elle entre probablement dans la catégorie des « stars d'il y a des années ».", "Mariru")
	await novel_interface.show_dialog("Mais par rapport à ce qu'elle était, je m'intéresse davantage à ce qu'elle a de spécial maintenant.", "Mariru")
	await novel_interface.show_dialog("Il y a si peu d'informations sur les sorcières au départ... c'était une aubaine inattendue.", "Mariru")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Sorcières... qu'est-ce que c'est ?", "Lian")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"speak2")
	await novel_interface.show_dialog("Mm... en termes simples, vous pouvez les considérer comme des humains qui ont été infectés par un certain type d'informations et ont acquis des traits similaires à \"Substance H\".", "Mariru")
	await novel_interface.show_dialog("Tout comme la façon dont les gens appellent les étranges caractéristiques des « Substance H » – des choses que la science actuelle ne peut expliquer – des « miracles ».", "Mariru")
	novel_interface.change_2nd_expression("normal2")
	await novel_interface.show_dialog("Pour les gens ordinaires, si quelqu’un pouvait manifester ce genre de trait, cela ressemblerait pratiquement à de la « magie ».", "Mariru")
	novel_interface.character_2nd_move_left(-0.25)
	novel_interface.show_character("ren_battle","normal1",0.25)
	await novel_interface.show_dialog("La magie... devrait simplement être une science que nous ne comprenons pas encore...", "Lian")
	novel_interface.character_2nd_light()
	novel_interface.character_dark()
	await novel_interface.show_dialog("C’est une façon parfaitement valable d’y penser.", "Mariru")
	await novel_interface.hide_all_characters()
	novel_interface.change_background("res://assets/images/bg/Shot/burningPunish.png")
	await novel_interface.show_dialog("Il existe de nombreux documents historiques sur les « sorcières », mais ils ont toujours été traités comme une superstition et une légende.", "Mariru")
	await novel_interface.show_dialog("Sur une période de plus de trois cents ans, les Européens ont exécuté près de cent mille femmes au nom de « sorcières ».", "Mariru")
	await novel_interface.show_dialog("Les \"chasses aux sorcières\"... on l'a appris en cours d'histoire...", "Lian")
	await novel_interface.show_dialog("À l'époque, je le considérais seulement comme un matériel d'examen ennuyeux, mais plus j'y pense, plus cela ressemble vraiment à une catastrophe à une échelle anormalement massive....", "Mariru")
	novel_interface.change_background("res://assets/images/bg/SID/hall.png")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("Depuis la découverte de « Substance H », tous les pays ont commencé à réexaminer si ces légendes étaient vraies.", "Mariru")
	await novel_interface.show_dialog("Dernièrement, des rumeurs courent selon lesquelles certaines organisations auraient recréé des sorcières et les utiliseraient à des fins d'espionnage.", "Mariru")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("Heureusement pour nous, Annie a accepté de nous rejoindre sans hésitation.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("Rejoindre quoi ?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("Devenir agent SID.", "Mariru")
	await novel_interface.show_dialog("A partir de demain, elle travaillera pour moi.", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","panic",0.25)
	await novel_interface.show_dialog("Vous ne pouvez pas faire ça ! Les agents SID font évidemment un travail extrêmement dangereux !", "Lian")
	novel_interface.change_2nd_expression("wry_smile")
	await novel_interface.show_dialog("Et elle n'a que quinze ans, tout comme moi. Elle ne peut pas être une sorte d'agent...", "Lian")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Hé. Notre plus jeune agent n’a actuellement que treize ans.", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wail")
	await novel_interface.show_dialog("Treize ?! C'est illégal !!\nCela doit être illégal, non ?!", "Lian")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Si jamais vous avez la chance de la rencontrer, vous ne direz plus ça.\nCe gamin est bien plus intelligent qu'un imbécile comme vous.", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"sprite")
	await novel_interface.show_dialog("... Hmph.", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("En tant que citoyen de New Opulentia, je sais bien sûr que même si les différentes villes universitaires semblent être soumises à un cessez-le-feu, elles se font toujours secrètement concurrence.")
	await novel_interface.show_text_only("Et le bouclier de Aegis est inutile contre les armes biochimiques et les attaques terroristes de type infiltration.")
	await novel_interface.show_text_only("Pour protéger cette ville, Mariru et SID ont dû mener d'innombrables batailles désespérées dans l'ombre.")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("Oh, c'est vrai. L'identité de couverture de Annie sera celle d'un étudiant transféré qui s'inscrit avec vous.", "Mariru")
	await novel_interface.show_dialog("J'ai fait en sorte que vous restiez tous les deux dans la même suite. Les uniformes et autres nécessités quotidiennes\nseront tous livrés dans l'heure.", "Mariru")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("Pas de négociation.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("Je comprends...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Bien sûr, je comprends. Il n'y a rien de mal à cela.\nNon, c'est bien plus confortable que la vie que j'avais avant.")
	await novel_interface.show_text_only("Tant que SID s'occupe de tout.\nTant que je continue à dériver dans ma vie dans une école de filles nobles, en me contentant de crédits.")
	await novel_interface.show_text_only("Et tant que j'essaie de m'habituer à ce nouveau corps..., est-ce que cela suffirait ?")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("... Non.", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("Hein ?", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Même si je ne comprends encore rien, je ne veux pas que Annie affronte seule ce genre de danger.")
	await novel_interface.show_text_only("La Annie qui est apparue devant moi au moment où nous nous sommes rencontrés....\nElle avait l'air calme, mais il y avait encore une trace de peur en elle.")
	await novel_interface.show_text_only("Elle avait... peur aussi, n'est-ce pas ?")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("... Mademoiselle Mariru—si cela ne vous dérange pas que je vous appelle comme ça...\nJe veux aussi vous aider !", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","serious",0.25)
	await novel_interface.show_dialog("Hein ?!", "Mariru")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("... Je veux dire... puisque j'ai pu traverser cet ouragan, peut-être que je peux aider SID avec autre chose aussi !", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("Ce n'était pas un ouragan. Il s'agissait d'une fluctuation de phase spatio-temporelle...", "Mariru")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"shout")
	await novel_interface.show_dialog("Quoi qu'il en soit, je ne peux pas laisser Annie affronter le danger seul.", "Lian")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("Et peut-être... peut-être que j'aurai même une chance de trouver un moyen de redevenir un garçon...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("... Mais avec vos capacités physiques, vous ne pourriez probablement même pas battre l'un des concierges de SID.", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","panic",0.25)
	await novel_interface.show_dialog("Euh...\n(Quel genre de nettoyeurs engagez-vous ?! Les moines Shaolin ?!)", "Lian")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("... Très bien. Je vous laisse essayer la formation des SID cadets. Au moins, si vous courez un danger à l’avenir, cela pourrait augmenter un peu votre taux de survie.", "Mariru")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Quant à votre statut, vous commencerez en tant que candidat agent de niveau 4.", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("D'accord ! Je ferai de mon mieux !", "Lian")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("(Bien. Voyons quel type de données je peux extraire de ce petit.)", "Mariru")

	print("=== 第二章第11话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
