# chapter2_ep03.gd - 第二章第3话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep03_script()

func play_script():
	pass

func chapter2_ep03_script():
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("« Escortés » par les agents, Annie et moi avons sauté dans une berline noir de jais.")
	novel_interface.change_background("res://assets/images/bg/Shot/incarView2.png")
	await novel_interface.show_text_only("L'habitacle est étouffant.")
	await novel_interface.show_text_only("J'enroule mes bras autour de mes genoux, perplexe.")
	await novel_interface.show_text_only("Annie s'appuie doucement sur moi, ce qui me détend quelque peu.")
	await novel_interface.show_dialog("Alors... qu'est-ce que SID ? \\nVous devenez énervé à chaque fois que vous l'entendez.", "Annie")
	await novel_interface.show_dialog("Êtes-vous de l'espace? \\nSID est le département de renseignement relevant du Sénat.", GameConfig.player_name)
	await novel_interface.show_dialog("Certains disent que SID joue un rôle plus important que le système de défense Aegis pour garder New Opulentia neutre.", GameConfig.player_name)
	await novel_interface.show_dialog("Mais il y a d'autres légendes urbaines sur des gens emmenés par SID et qui ne reviennent jamais... C'est tout simplement horrible.", GameConfig.player_name)
	await novel_interface.show_dialog("D'accord... Mais alors, c'est quoi la Cité Académie ?", "Annie")
	await novel_interface.show_dialog("(Attendez... Cette fille n'a-t-elle aucun bon sens ? )", GameConfig.player_name)
	await novel_interface.show_text_only("Annie voit mon regard surpris... et elle me fait juste un sourire détendu.")
	await novel_interface.show_dialog("Détendez-vous, nous n'aurons aucun problème !", "Annie")
	await novel_interface.show_dialog("Parce que... tu es spécial.", "Annie")
	await novel_interface.show_dialog("…", GameConfig.player_name)
	await novel_interface.show_text_only("C'est bizarre que les divagations de Annie aient en quelque sorte calmé mon esprit agité.")
	await novel_interface.show_text_only("Cela ne semble pas si horrible d'être emmené par SID...")
	await novel_interface.show_text_only("(Non. Non. C'est horrible !)")
	novel_interface.change_background("res://assets/images/bg/Shot/incarView1.png")
	await novel_interface.show_text_only("Nous arrivons dans le quartier d'affaires animé de la ville et pénétrons dans un garage ordinaire en sous-sol où nous montons dans un ascenseur pour voiture.")
	await novel_interface.show_text_only("Après le rapport de l'agent, l'ascenseur commence à bouger.")
	await novel_interface.show_text_only("Je peux sentir à quelle vitesse l’ascenseur se déplace. Il descend plusieurs fois sur de longues distances et se déplace même latéralement de temps en temps.")
	await novel_interface.show_dialog("(Il est difficile d'imaginer un tel labyrinthe souterrain sous le quartier des affaires...)", GameConfig.player_name)
	await novel_interface.show_text_only("Les rumeurs sur le quartier général de SID abondent. Certains disent qu'il est situé dans la banlieue sud de New Opulentia, et que toute la structure est recouverte d'un camouflage optique.")
	await novel_interface.show_text_only("Bien sûr, pour un bâtiment qui n’existe pas officiellement dans le système, les médias peuvent inventer n’importe quoi pour peu qu’ils attirent des clics.")
	await novel_interface.show_text_only("Et là où j'interviens, c'est exactement le cœur de ce département « inexistant ».")
	await novel_interface.show_dialog("(J'espère juste que je ne serai pas rendu « inexistant » ici...)", GameConfig.player_name)
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("Nous descendons de la voiture devant un couloir enveloppé de plaques métalliques. Cela donne un sentiment de technologie et d’abstinence.")
	await novel_interface.show_text_only("La porte de l’ascenseur se ferme automatiquement juste après notre descente. Nous l'entendons partir alors que nous continuons le long du couloir sombre. L’air devient raide et morne.")
	await novel_interface.show_text_only("Mon cœur se serre aussi...")
	novel_interface.change_background("res://assets/images/bg/SID/hearingRoom.png")
	await novel_interface.show_text_only("Nous marchons tout droit dans le couloir et arrivons dans une pièce lumineuse mais fermée.")
	await novel_interface.show_text_only("Cela ressemble à une sorte de salle d’interrogatoire, mais il n’y a ni tables ni chaises. Un mur est une immense vitre.")
	await novel_interface.show_text_only("Avant que je puisse me retourner pour vérifier ce mur...")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("Whoooa—!", GameConfig.player_name)
	novel_interface.character_dark()
	await novel_interface.show_text_only("Quelqu’un passe avec force ses bras autour de ma taille.")
	novel_interface.character_light(0.35,"sob")
	await novel_interface.show_dialog("Aïe… Ça fait mal !", GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Alors que je suis sur le point de perdre l'équilibre, je sens ma tête tomber sur quelque chose de familier, doux mais ferme.")
	await novel_interface.show_dialog("Eh bien... À en juger par votre force principale, le métier d'espion n'est pas pour vous.", "Voix féminine")
	await novel_interface.show_dialog("Je pensais que nous avions eu des erreurs de scan corporel, alors je voulais personnellement confirmer.", "Voix féminine")
	await novel_interface.show_dialog("Mais ça fait du bien.", "Voix féminine")
	await novel_interface.show_text_only("La voix féminine derrière moi me semble familière.")
	await novel_interface.show_text_only("Elle desserre les bras. Avec une peur persistante, je me retourne. \\nLa femme en face de moi—")
	novel_interface.show_character("ren_battle","blush")
	await novel_interface.show_dialog("(Hein ?! C'est énorme !!!)", GameConfig.player_name)
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("Mme... Mme Mariru !?", GameConfig.player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","worry")
	await novel_interface.show_dialog("Vous la connaissez ?", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("Ah ? Si rapide à révéler que vous pouvez identifier des agents d’une autre agence de renseignement. \\nOn dirait que vous n'avez jamais prévu de cacher qui vous êtes...", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","sob",0.25)
	await novel_interface.show_dialog("(Mon Dieu ! C'est idiot…)", GameConfig.player_name)
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("C’est difficile à croire, mais cette femme en uniforme devant moi est la femme que j’ai rencontrée dans mon rêve.")
	await novel_interface.show_text_only("La silhouette élancée… les cheveux roux… le look sadique…")
	novel_interface.character_light(0.35,"speak2")
	await novel_interface.show_dialog("Vous devez répondre honnêtement à mes questions maintenant.", "Mariru")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Ne cherchez aucune excuse et ne jouez aucun tour.", "Mariru")
	await novel_interface.show_dialog("Il se trouve que les interrogatoires sont une de mes spécialités. \\nJe ne vais pas y aller doucement avec ton joli petit visage~", "Mariru")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"panic")
	await novel_interface.show_text_only("Cette attitude autoritaire et taquine et ces yeux confiants avec une pointe de moquerie...")
	await novel_interface.show_text_only("Quel est son nom complet, déjà ? \\nBien, c'est...")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("Exactement. Je suis à la tête de SID. Je m'appelle Mariru Von Braun.", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","awkward",0.25)
	await novel_interface.show_text_only("C'est elle !!!")
	novel_interface.change_2nd_expression("perspire1")
	await novel_interface.show_text_only("Attendez... le chef de SID ? \\nN'était-elle pas la scientifique en chef ?!")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_text_only("Mais en regardant de près ses vêtements et ses marques sur ses épaules, c'est probablement une grande patronne...")
	novel_interface.change_2nd_expression("shy")
	await novel_interface.show_text_only("Ses bas et ses talons hauts sont les mêmes qu'hier.")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Hé, ma fille, qu'est-ce que tu regardes, hein ?", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"sob")
	await novel_interface.show_dialog("Ah ! Ouais... c'est vrai ! \\nDésolé, Madame !", GameConfig.player_name)
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Vous avez du courage, laissez votre esprit vagabonder en ce moment.", "Mariru")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("J'ai entendu dire que vous aviez raconté de nombreuses histoires horribles sur SID à ce double-queue bleue.", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"awkward")
	await novel_interface.show_text_only("Mariru tourne son fouet dans ses mains. Je deviens nerveux et j'avale difficilement.")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Devinez... \\nCombien d’entre eux sont vrais ?", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wail")
	await novel_interface.show_dialog("Euh ! Je suis… vraiment désolé !", GameConfig.player_name)
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_battle","perspire")
	await novel_interface.show_dialog("B… double queue bleue…", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak")
	await novel_interface.show_dialog("Maintenant que vous connaissez la peur, commençons par votre identité.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru ouvre son terminal portable et une projection apparaît immédiatement sur le mur de la salle d'interrogatoire.")
	await novel_interface.show_text_only("Il montre des photos de moi prises sous différents angles par des caméras de surveillance, et le résultat de l'analyse faciale se lit comme suit :")
	await novel_interface.show_text_only("[Aucune correspondance trouvée]")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("Aucun enregistrement d'arrivée... Aegis ne parvient pas à s'identifier.", "Mariru")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Si ce n'était pas votre mauvaise forme physique, vous seriez immédiatement traité comme un espion ou un intrus terroriste.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_text_only("Je me sens un peu gêné et me frotte le ventre inconsciemment.")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_battle","frustrate",0.25)
	await novel_interface.show_dialog(GameConfig.player_name+", cette dame semble encore plus effrayante que les ennemis que nous avons rencontrés plus tôt...", "Annie")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("(Ouais… et elle n'aura aucun mal à voir clair dans mes mensonges...)", GameConfig.player_name)
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,false,"sob")
	await novel_interface.show_dialog("(Je l'avoue ! Mon Dieu ! Peu importe !)", GameConfig.player_name)
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog(""+GameConfig.player_name+", par où dois-je commencer... ?", GameConfig.player_name)
	await novel_interface.show_dialog("C'est un peu compliqué, pour être honnête. Je suis également très confus.", GameConfig.player_name)
	await novel_interface.show_dialog("Vous ne croirez probablement pas ce que je dis...", GameConfig.player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak")
	await novel_interface.show_dialog("Arrêtez de divaguer. Je vais juger cela par moi-même !", "Mariru")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("… Eh bien… J'ai fait ce rêve.", GameConfig.player_name)
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Dans le rêve, j'allais au Centre de Recherche pour assister à une conférence pour mon rapport d'enseignement en plein air… Et j'arrivais juste avant l'heure de fermeture.", GameConfig.player_name)
	await novel_interface.show_dialog("Je t'ai rencontré là-bas. Et vous avez dit qu'il avait été capturé…", GameConfig.player_name)
	novel_interface.character_dark()
	await novel_interface.show_text_only("Apparemment, Mariru prend cela comme une blague ou quelque chose du genre.")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("liliu_uniform2","speak2",0.25)
	await novel_interface.show_dialog("Tu veux dire, tu m'as rencontré dans un rêve ?", "Mariru")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Oui, c'était toi. \\nEt tu m'as traîné dans un coin...", GameConfig.player_name)
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Oh, c'est vrai... vous étiez un scientifique de classe SS reconnu par le Sénat... \\nDr. Mariru Von Braun, n'est-ce pas ?", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("... C'est moi.", "Mariru")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("Mais cette information n'est pas secrète : quiconque connaît New Opulentia la connaît.", "Mariru")
	await novel_interface.show_dialog("... Oubliez ça. \\nAlors, que s'est-il passé ensuite ?", "Mariru")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Vous avez renversé l'un des intrus et vous avez récupéré un pistolet. Vous m'avez demandé de rester sur place et d'attendre les secours, et vous êtes allé sur le lieu du détournement.", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Un endroit détourné ? \\nOù exactement ?", "Mariru")
	novel_interface.character_light(0.35,"gratified")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Vous avez dit que c'était la salle de conférence.", GameConfig.player_name)
	await novel_interface.show_dialog("Vous étiez sur le point de donner une conférence là-bas. Vous étiez le conférencier.", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("… Conférence… Conférencier.", "Mariru")
	novel_interface.change_2nd_expression("serious")
	await novel_interface.show_dialog("(Parle-t-elle de la conférence publique sur Ross Goblet organisée par Wolfgang ?)", "Mariru")
	await novel_interface.show_dialog("(Mais cela aurait dû être annulé. Comment pouvait-elle être au courant ?)", "Mariru")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Euh... Mme Mariru ?", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("Ouais… rien. Continue.", "Mariru")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Et des hommes armés masqués sont passés. J'ai couru en bas et je me suis caché à l'ombre d'une ardoise...", GameConfig.player_name)
	await novel_interface.show_dialog("Désolé mais je ne me souviens pas de ce qui s'est passé là-bas…", GameConfig.player_name)
	await novel_interface.show_dialog("Je me suis évanoui et quand je me suis réveillé, j'ai vu…", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("Qu'as-tu vu ?", "Mariru")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"normal1")
	await novel_interface.show_dialog("J'ai vu de la fumée et des flammes tout autour.", GameConfig.player_name)
	await novel_interface.show_dialog("Le Centre de Recherche et les bâtiments environnants étaient tous en ruines...", GameConfig.player_name)
	await novel_interface.show_dialog("Il y avait une odeur âcre partout.", GameConfig.player_name)
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("Il avait un goût fortement salin et amer...", GameConfig.player_name)
	await novel_interface.show_dialog("Tous les gens se sont transformés en figures de pierre.", GameConfig.player_name)
	await novel_interface.show_dialog("Non, pas exactement de la pierre, c'était du sel.", GameConfig.player_name)
	novel_interface.change_expression("solemn")
	await novel_interface.show_dialog("Et j'ai vu quelque chose briller dans l'air.", GameConfig.player_name)
	await novel_interface.show_dialog("C'était comme l'enfer. \\nMais d'une manière ou d'une autre, je peux ressentir une sorte de tranquillité particulière.", GameConfig.player_name)
	await novel_interface.show_dialog("Quelque chose me répond...", GameConfig.player_name)
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Et puis ma mémoire est devenue vague... Il pourrait y avoir une traînée de lumière—", GameConfig.player_name)
	await novel_interface.show_dialog("Et… c'est à peu près la fin du rêve.", GameConfig.player_name)
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Quand je me suis réveillé, je me suis retrouvé sur mon lit dans ma chambre, et c'était déjà le matin.", GameConfig.player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("Était-ce... seulement un rêve... ?", "Mariru")
	await novel_interface.show_dialog("Votre mémoire olfactive était si vive comme si vous y étiez réellement…", "Mariru")
	await novel_interface.show_dialog("(Si cette odeur âcre était du soufre...) \\n(Ce serait comme la façon dont Sodome et Gomorrhe ont été détruites dans la Genèse.)", "Mariru")

	print("=== 第二章第3话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
