# chapter2_ep12.gd - 第二章第12话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep12_script()

func play_script():
	pass

func chapter2_ep12_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("Depois de terminar uma série de procedimentos de registro para treinamento de cadetes SID, recebi uma pilha grossa de \"livros didáticos\".")
	await novel_interface.show_text_only("Então, sob a orientação de um membro da equipe, peguei um elevador pequeno e discreto da SID Sede.")
	novel_interface.change_background("res://assets/images/bg/other/BG_City_street3.png")
	await novel_interface.show_text_only("O elevador subiu rápido o suficiente para que eu pudesse sentir claramente a pressão aumentando em meus ouvidos.\nQuando cheguei à superfície, percebi que já era noite...")
	await novel_interface.show_text_only("O elevador dava para o saguão de um pequeno prédio de escritórios e, do lado de fora, ficava o movimentado distrito comercial.")
	await novel_interface.show_text_only("Ouvi dizer que o elevador só pode descer aos níveis mais profundos quando reconhece que cada passageiro é pessoal autorizado. Caso contrário, apenas se desloca entre o primeiro e o terceiro andares do edifício de escritórios.") #换行问题
	await novel_interface.show_text_only("No segundo andar do prédio havia um café aberto 24 horas por dia, com pessoas entrando e saindo o dia todo – perfeito para se esconder à vista de todos.")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("Suspiro...", "Lian")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("Achei que o treinamento de agente envolveria coisas como combate corpo a corpo e tiro, mas parece mais que eu me inscrevi em um pacote completo de cursinho...", "Lian")
	await novel_interface.show_dialog("Esses livros são muito pesados!\nAinda bem que o lugar que Mariru arranjou para mim não é longe daqui.", "Lian")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Academy District East Road No. 6... Ela disse que era muito discreto—", "Lian")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("...")
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	novel_interface.show_character("ren_battle","wail") 
	await novel_interface.show_dialog("—Como isso é discreto?!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Eu estava dentro de uma residência luxuosa no último andar de um arranha-céu. A luxuosa sala de estar conectada a um terraço gigante com vista noturna do bairro comercial.")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("Essas chamas ao longo da parede são uma lareira de verdade?\nIsso é exagerado...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("No momento em que eu estava olhando ao redor com cautela e me perguntando se havia entrado na sala errada, recebi uma mensagem de Mariru.")
	await novel_interface.show_text_only("Mariru: Escolha o quarto de sua preferência.\nNão há necessidade de ser educado com o orçamento do Senado~") #原文有个♥
	await novel_interface.show_text_only("Aquela mulher... Peça desculpas aos contribuintes de New Opulentia agora mesmo!!")
	await novel_interface.show_dialog("Lian, você está de volta!", "Annie")
	await novel_interface.show_text_only("Annie saiu do banheiro, uma mão prendendo o cabelo enquanto caminhava.")
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("Annie?! Você também está aqui?\nMariru disse que acabou de sair para um treinamento especial...", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","normal1",0.25)
	await novel_interface.show_dialog("Terminei o treinamento antes do previsto. Acabei de tomar banho e experimentar o uniforme escolar.\nParece que seremos colegas de quarto~", "Annie")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("R-Certo...\n(Parece que Mariru mencionou isso...)", "Lian")
	novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,false,"shy_left")
	await novel_interface.show_dialog("(Isso é algum tipo de teste do céu?)\n(Viver sob o mesmo teto que uma garota e tudo mais...)", "Lian")
	novel_interface.change_expression("timid")
	await novel_interface.show_dialog("Esse é o uniforme desta escola? É muito fofo ~", "Lian")
	novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("Mm-hm~ As roupas que eles prepararam para você estão naquela caixa ali. Você deveria experimentá-los também!", "Annie")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","awkward",0.25)
	await novel_interface.show_dialog("E-eu também tenho que usar um...?", "Lian")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Hehe, Lian, você ainda não está acostumado a ser uma garota?", "Annie")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Assim que ela tocou no assunto, não pude deixar de coçar a cabeça e cair no sofá.")
	novel_interface.show_character("anne_uniform","normal2")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ren_battle","shy",0.25)
	await novel_interface.show_dialog("Como alguém poderia se acostumar com algo assim...", "Lian")
	novel_interface.change_2nd_expression("sob")
	await novel_interface.show_dialog("Ugh... Ninguém poderia entender como é isso.", "Lian")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"normal1")
	await novel_interface.show_dialog("Eu entendo.", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Annie de repente sentou-se ao meu lado e roçou levemente minha bochecha com a ponta do dedo, como se para me confortar.")
	novel_interface.show_character("ren_battle","timid")
	await novel_interface.show_dialog("... Annie?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","relieve")
	await novel_interface.show_dialog("Porque somos iguais.", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Havia uma leve amargura em seu sorriso.")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("O-O que—?!\nVocê também era um menino?!", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","smile",0.25)
	await novel_interface.show_dialog("Ahahahahaha! Lian, você é um idiota?", "Annie")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("Eu sempre fui uma garota~", "Annie")
	novel_interface.character_light(0.35,"shy_left")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Agh...\n(Isso é mortificante!!)", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Justamente quando meu constrangimento estava prestes a atingir o auge, Annie parou de rir e olhou para mim gentilmente.")
	novel_interface.show_character("ren_battle","shy_left")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","normal2",0.25)
	await novel_interface.show_dialog("Mas o pânico em seu coração agora... Eu realmente entendo isso completamente.", "Annie")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_left(0,0.3,false)
	await novel_interface.show_dialog("Eu também já estive preso em outro espaço-tempo...\nEsse sentimento provavelmente era um pouco parecido com o que você está passando agora.", "Annie")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("Outro... espaço-tempo?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Annie fez uma pausa, como se estivesse pensando cuidadosamente sobre como formular isso.")
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("A senhorita Mariru não te contou?\nPassei muito tempo vagando em outro espaço-tempo sem realmente entender nada...", "Annie")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("O tempo parecia vago ali. Não pareceu muito tempo, mas quando voltei percebi que sete anos já haviam se passado.", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("Hum, ouvi um pouquinho sobre isso...", "Lian")
	await novel_interface.show_dialog("(Embora isso tenha sido apenas devido a algumas dicas dispersas Mariru descartadas ...)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("O que exatamente aconteceu com ela?\nDevo perguntar diretamente a ela?")
	await novel_interface.show_text_only("Annie não continuou. Ela apenas abaixou a cabeça e brincou distraidamente com os dedos.")
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("Lian... você também já se sentiu assim—", "Annie")
	await novel_interface.show_dialog("Como se tudo isso pudesse ser apenas um sonho, e na próxima vez que você abrir os olhos, você finalmente acordará.", "Annie")
	await novel_interface.show_dialog("Não era assim que as coisas deveriam ser. Você não deveria estar aqui...\nMas não importa o que você faça, você não pode voltar ao caminho normal.", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("(Então Annie chegou até aqui carregando sentimentos como esse sozinha...?)", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Cheguei um pouco mais perto de Annie e dei um tapinha gentil em seu ombro. \nUh, confortar uma garota assim... deveria estar tudo bem, certo?")
	novel_interface.show_character("ren_battle","smile")
	await novel_interface.show_dialog("Não tenha medo. Você está de volta agora, não está?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","worry",0.25)
	await novel_interface.show_dialog("Mm...\nMas tudo ainda parece tão estranho para mim...", "Annie")
	await novel_interface.show_dialog("Não tenho a menor ideia do que todos vocês querem dizer com “cidade acadêmica”.", "Annie")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("(... Certo. A guerra ainda nem tinha terminado quando Annie desapareceu.)", "Lian")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("Então isso significa que você ainda não sabe o que aconteceu nesses últimos anos, certo?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"unhappy")
	await novel_interface.show_dialog("Eu apenas pesquisei as coisas aproximadamente ... Tanta coisa aconteceu ao longo dos anos que eu nem entendo mais o que muitas palavras nas notícias deveriam significar.", "Annie")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Sete anos atrás...\nIsso foi bem no meio da guerra que jogou o mundo inteiro no caos.", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("Hein? A guerra?\nVocê quer dizer a campanha militar que o Forte Masada lançou contra a Europa?", "Annie")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Annie se esforçou para lembrar.")
	novel_interface.show_character("ren_battle","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","worry",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Não, esse não. Não muito depois disso, quase todos os países foram arrastados para isso.", "Lian")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Eu estava no ensino fundamental em um internato naquela época. Todos os dias as notícias estavam repletas de relatórios de guerra e contagens de vítimas. Foi uma época horrível...", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"upset")
	await novel_interface.show_dialog("Lian, você também viveu a guerra?", "Annie")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Não exatamente. Graças à proteção de Aegis, New Opulentia estava concentrando todos os seus esforços na reconstrução ao lado das ruínas naquela época.", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Eu olhei para a próspera paisagem noturna da cidade além da janela... Quando eu era pequeno, a cidade estava cheia de guindastes gigantes e máquinas de construção ocupadas por toda parte.")
	novel_interface.show_character("ren_battle","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","upset",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Então, a maior parte do que sei veio dos livros didáticos.", "Lian")
	await novel_interface.show_dialog("Por causa da guerra, a tecnologia milagrosa avançou rapidamente...\nE por \"milagre\", quero dizer fenômenos causados por Substance H.", "Lian")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Após a guerra, os seis países que dominaram as tecnologias-chave estabeleceram, cada um, uma das seis cidades-academia do mundo.", "Lian")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("(Parece que de repente despertei algum talento oculto para ser professor de história...)", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"unhappy")
	await novel_interface.show_dialog("Então isso realmente aconteceu... nem consigo imaginar.", "Annie")
	novel_interface.character_light(0.35,"gratified")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Bem, quando Annie partiu - uh, desapareceu - o mundo ainda estava relativamente pacífico, certo ...?", "Lian")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal1")
	await novel_interface.show_dialog("Isso mesmo. Naquela época eu ainda podia competir em jogos internacionais de beisebol!", "Annie")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("No momento em que Annie tocou no beisebol, seus olhos começaram a brilhar.")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("Você sabe, Lian, sempre que chegava a minha vez de rebater, todos os olhos dos espectadores focavam apenas em mim!", "Annie")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("Essa mistura de tensão e ter que dar tudo de si faria o sangue do meu corpo inteiro ferver!", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Quando surgiu o beisebol, de repente pensei no monumento de pedra preta do lado de fora do Estádio de Beisebol Lebona, gravado com os nomes de dezenas de milhares de mortos.")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("Na verdade...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","normal2")
	await novel_interface.show_dialog("Hum?", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("Talvez perder os piores anos da guerra tenha sido uma coisa boa para você, afinal.", "Lian")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("Quando penso dessa maneira, talvez se transformar em uma garota e conhecer você\ntambém não tenha sido uma coisa totalmente ruim... em certo sentido?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Annie congelou. Por um momento, ela quase pareceu envergonhada...\nOu eu estava imaginando isso?")
	novel_interface.show_character("anne_uniform","normal1")
	await novel_interface.show_dialog("Lian... Na verdade, estive querendo te agradecer esse tempo todo.\nPorque... foi você quem me salvou de vagar naquele mundo.", "Annie")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","panic",0.25)
	await novel_interface.show_dialog("Hein? Mas eu não fiz nada...", "Lian")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("É exatamente por isso que você deve ser especial~", "Annie")
	await novel_interface.show_dialog("Ainda não sei como você fez isso, mas naquele momento pude sentir sua mão quente me puxando.", "Annie")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Annie gentilmente pegou minha mão e mergulhou em suas memórias.")
	novel_interface.show_character("anne_uniform","normal1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_battle","panic",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Se não fosse por você, não sei quanto tempo mais eu teria ficado preso ali, ou o que poderia ter me tornado no final...", "Annie")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("Torne-se... o quê?", "Lian")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ahaha ~ Não é nada. Isso tudo está no passado agora.\nDe repente, sinto um pouco de sono ~", "Annie")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Annie parecia querer fugir do assunto.\nEla se espreguiçou preguiçosamente, ainda com um sorriso.")
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	await novel_interface.show_dialog("Por quanto tempo vocês dois planejam continuar essa conversa noturna de garotas?", "Mariru")
	await novel_interface.show_text_only("A voz de Mariru de repente saiu do alto-falante no canto da sala.")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("M-Mariru?!\nVocê estava ouvindo agora há pouco?", "Lian")
	novel_interface.character_dark()
	await novel_interface.show_dialog("O quê? Há algo de errado em um responsável ficar de olho na agenda de algumas crianças?", "Mariru")
	novel_interface.character_light(0.35,"wry_smile")
	await novel_interface.show_dialog("Você realmente tem coragem de dizer isso...", "Lian")
	novel_interface.character_dark()
	await novel_interface.show_dialog("Respondendo também?\nParece que terei que treinar você ainda mais amanhã...", "Mariru")
	novel_interface.character_light(0.35,"wail")
	await novel_interface.show_dialog("Sinto muito! Vou tomar banho e vou direto para a cama agora mesmo!\nBoa noite!!", "Lian")

	print("=== 第二章第12话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
