# chapter2_ep02.gd - 第二章第2话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep02_script()

func play_script():
	pass

func chapter2_ep02_script():
	novel_interface.change_music("res://assets/audio/music/Barrier Maze.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/spSoundChannel.png")
	await novel_interface.show_dialog("Attention, toutes les escouades, les fluctuations de phase s'atténuent !", "Agent A")
	await novel_interface.show_dialog("L'ennemi peut émerger à tout moment !\nMaintenez vos positions et préparez-vous à engager !!", "Agent A")
	await novel_interface.show_dialog("... Rapport R !", "Agent B")
	await novel_interface.show_dialog("Deux unités humanoïdes sont apparues à portée visuelle, juste dans la zone centrale de l'anomalie...", "Agent B")
	await novel_interface.show_dialog("Humains...?\nComment est-ce possible ?! Qu'a montré l'analyse mémétique ??", "Agent A")
	await novel_interface.show_dialog("La teinte est...\nVert !!", "Agent B")
	await novel_interface.show_dialog("Il semblerait que ce soient deux jeunes filles....\nNe tirez pas ! Retenez votre feu !", "Agent B")
	await novel_interface.show_dialog("...", "Agent A")
	await novel_interface.show_dialog("Nous venons de recevoir des ordres : la priorité numéro un est de les sécuriser et de les ramener au quartier général.\nEnvoyer un agent supérieur pour négocier...", "Agent A")
	await novel_interface.show_dialog("Tout le monde, restez vigilant. Si les cibles font des mouvements suspects pendant les négociations, éliminez-les immédiatement !", "Agent A")
	await novel_interface.show_dialog("Compris!", "Agent B")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_outside.png")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("Nous nous sommes dirigés prudemment vers la sortie du centre de recherche.")
	await novel_interface.show_text_only("Ce qui nous attendait là-bas, outre la rue familière, c'était une ligne de ruban de barricade et une rangée de personnes armées derrière elle, prêtes à nous accueillir.")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("Pourquoi tant de gens sont-ils soudainement apparus ?!", GameConfig.player_name)
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("Ah—Annie!\nDépêchez-vous et me changez !!", GameConfig.player_name)
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("Ces vêtements sont bien trop embarrassants...\nJe ne veux vraiment pas qu'on me voie comme ça...", GameConfig.player_name)
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_battle","worry",0.25)
	await novel_interface.show_dialog("Est-ce vraiment ce qui vous inquiète en ce moment ?", "Annie")
	novel_interface.change_2nd_expression("uneasy")
	await novel_interface.show_dialog("Vos vêtements sont tous gardés en sécurité avec moi, alors ne vous inquiétez pas...", "Annie")
	await novel_interface.show_dialog("Si vous voulez vraiment changer, enlevez simplement la « tenue de combat » que vous portez actuellement et remettez vos vêtements amples habituels ~", "Annie")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("Mais il y a beaucoup d'hommes devant eux....\nVoulez-vous vraiment changer juste devant eux ?", "Annie")
	novel_interface.character_light(0.35,"shy_right")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ugh...\nMais je suis un gars...", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("À bien y penser,... tu portais des vêtements pour hommes plus tôt !\nEst-ce que ça pourrait être—", "Annie")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Hein ? Vous aussi avez déjà été dans une situation comme celle-ci ??", GameConfig.player_name)
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("(Cela a du sens. ... Annie n'est probablement pas une personne ordinaire non plus, n'est-ce pas ?)", GameConfig.player_name)
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("(Si c'est Annie, peut-être qu'elle peut comprendre ce que je vis...)", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("Mhm, je comprends...", "Annie")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("Vous êtes du genre à emprunter secrètement les vêtements d'un garçon que vous aimez et à les porter vous-même, n'est-ce pas ?", "Annie")
	novel_interface.character_light(0.35,"wail")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ce n'est pas du tout « comprendre » !!!", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("Mhm~ Alors en fait,"+GameConfig.player_name+"C'est le genre de personne qui est captivée par l'odeur du sexe opposé, hein ? Pas besoin d'être gêné...", "Annie") #文本变化important
	novel_interface.character_light(0.35,"sob")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ne faites pas cette grimace du genre : « Tu es peut-être un pervers, mais je t'accepterai quand même » !!!", GameConfig.player_name)
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("Soupir... Je n'ai toujours absolument aucune idée de pourquoi je suis devenu ainsi...", GameConfig.player_name)
	novel_interface.character_dark()
	await novel_interface.show_text_only("...")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("Arrêtez-vous là !\nMettez vos mains là où je peux les voir !", "SID Agent")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Une personne en costume noir s’est avancée et nous a crié dessus.")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("ren_battle","awkward",0.25)
	await novel_interface.show_dialog("Hein...?\nPensent-ils que nous sommes les méchants ?", GameConfig.player_name)
	novel_interface.change_2nd_expression("panic")
	await novel_interface.show_dialog("(Attendez, cet insigne sur la poitrine du chef...)\n(Un bouclier parfaitement rond en forme d'anneau – ne me dites pas que c'est...)", GameConfig.player_name)
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0)
	await novel_interface.show_dialog("Vous deux, je suis un agent SID.\nPour votre propre sécurité, gardez cette pose et ne bougez pas.", "SID Agent")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_text_only("Comme je le pensais, ils sont avec SID !\nOn est foutus maintenant !!!")
	await novel_interface.show_text_only("En un instant, mon esprit s'est rempli d'histoires sur SID envoyant des essaims d'agents pour capturer des espions.")
	novel_interface.change_expression("sob")
	await novel_interface.show_text_only("Et puis il y avait des légendes urbaines sur les « prisons secrètes », les « opérations d'assassinat », etc....")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("Rapport de la zone centrale de quarantaine : les deux cibles n'ont montré aucune intention hostile.\nNiveau de menace provisoirement fixé à D+.", "SID Agent")
	await novel_interface.show_dialog("Commençons par quelques questions simples....\nQui êtes-vous et que faites-vous en vous faufilant ici ?", "SID Agent")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("Je suis un étudiant de cette ville...", GameConfig.player_name)
	novel_interface.change_expression("wail")
	await novel_interface.show_dialog("Nous venons juste de venir ici lors d'une excursion pour visiter l'institut de recherche...", GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("L'agent en noir nous lança un regard dédaigneux.")
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("Est-ce vrai… une tournée ? De l'institut ?", "SID Agent")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_text_only("Oh non...\nJe me suis soudainement souvenu—")
	await novel_interface.show_text_only("En raison de la disparition de la « Roskin Cup », l'institut était placé en confinement d'urgence depuis hier soir.")
	novel_interface.change_expression("sob")
	await novel_interface.show_text_only("S'en sortir effrontément à un moment comme celui-ci et prétendre que nous étions juste en visite..., c'était fondamentalement une confession.")
	await novel_interface.show_text_only("Comme prévu, elle semblait recevoir une sorte d'instruction via son écouteur et me fixa avec un regard sévère.")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("agent","",0.25)
	await novel_interface.show_dialog("J'ai reçu des ordres de mon supérieur. Vous viendrez tous les deux avec nous.", "SID Agent")
	novel_interface.character_move_right(0,0.3,false)
	novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("En l’espace de quelques secondes seulement, nous étions tous les deux complètement encerclés.")
	await novel_interface.show_text_only("Partout où je regardais, il y avait un mur de canons d’armes pointés droit sur nous.")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("anne_battle","worry",0.25)
	await novel_interface.show_dialog(GameConfig.player_name+", ces gens ont l'air d'une très mauvaise nouvelle....\nPourquoi n'attendons-nous pas une opportunité et ne courons-nous pas la chercher ?", "Annie")
	novel_interface.character_move_left(-0.3,0.3,false)
	novel_interface.character_2nd_move_left(0)
	novel_interface.show_3rd_character("agent","",0.3)
	await novel_interface.show_dialog("Soyez assuré que nous ne vous ferons aucun mal.\nTant que vous coopérez à l'enquête, tout cela peut être résolu pacifiquement.", "SID Agent")
	await novel_interface.show_dialog("Vous devez comprendre que la disparition d’un « objet anormal » n’est pas une affaire anodine. Cela pourrait déclencher des événements allant bien au-delà du bon sens, alors veuillez coopérer.", "SID Agent")
	await novel_interface.hide_3rd_character()
	novel_interface.character_move_right(-0.25,0.3,true,"worry")
	novel_interface.character_2nd_move_right(0.25,0.3,false)
	await novel_interface.show_dialog("(Des événements dépassant le bon sens... ?)", GameConfig.player_name)
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("D'accord, je comprends. Je vais avec toi.", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("Hein ?? Pourquoi tu pars avec eux ?!\nHé !"+GameConfig.player_name+"!", "Annie")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Q-arrête de tirer ! Ma stupide jupe va s'enlever !", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("C'est toi l'idiot ! Pourquoi iriez-vous avec des gens aussi suspects ? Et s’ils vous droguent et vous vendent quelque part ?!", "Annie")
	novel_interface.character_light(0.35,"shy_right")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Que voudrait-on d'un homme adulte comme moi ?...", GameConfig.player_name)
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("Attendez, non : qui organiserait une opération de traite d’êtres humains avec autant de personnes faisant une telle scène ?!", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"frustrate")
	await novel_interface.show_dialog(GameConfig.player_name+", vous n'avez visiblement jamais vu les gangs des îles Lebona...", "Annie")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Quoi qu'il en soit... peut-être que nous pourrions enfin apprendre quelque chose.\nAllons avec elle pour l'instant...", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("Très bien. Où que tu ailles, j'irai aussi...", "Annie")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Euh, si possible, pourrais-je d'abord me procurer un manteau ?", GameConfig.player_name) 
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("Cette tenue est vraiment un peu...", GameConfig.player_name)
	novel_interface.character_dark()
	await novel_interface.show_text_only("Être regardée par tout le monde alors que j'étais habillée comme une fille mettait tout mon corps mal à l'aise.")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("Très bien, je vais faire une demande.", "SID Agent")
	await novel_interface.show_dialog("...", "SID Agent")
	await novel_interface.show_dialog("...Désolé, mon supérieur a dit : « Cette tenue est très mignonne » et a catégoriquement rejeté la demande.", "SID Agent")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("Quel genre de supérieur dit quelque chose comme ça ?!", GameConfig.player_name)

	print("=== 第二章第2话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
