# chapter2_ep05.gd - 第二章第5话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep05_script()

func play_script():
	pass

func chapter2_ep05_script():
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/hearingRoom.png")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("今朝から、新豊洲市内のあちこちで『時空位相波動』の警報が同時に発生した。", "マリル")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("まるで一晩のうちに、何かが目を覚ましたみたいにな……", "マリル")
	await novel_interface.show_dialog("監視衛星によれば、お前は異変区域の中で忽然と姿を消し、しばらくして反対側に現れた。その時には隣にもう一人いた。", "マリル")
	novel_interface.character_dark()
	await novel_interface.show_text_only("マリルの視線がアニーへ向く。")
	novel_interface.character_light(0.35,"normal2")
	await novel_interface.show_dialog("そしてお前たちが現れた地点では、この波動が自然に消失した。", "マリル")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","worry",0.25)
	await novel_interface.show_dialog("異変区域？　研究センターのこと？", GameConfig.player_name)
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("そうだ。", "マリル")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wry_smile")
	await novel_interface.show_dialog("それって機械の故障か何かじゃないかな……私はずっと大通りにいたんだけど。", GameConfig.player_name)
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("マリルの表情が険しくなった。")
	novel_interface.character_light(0.35,"serious")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("誰でも好きに『時空位相波動』の区域へ出入りできると思っているのか？", "マリル")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"panic")
	await novel_interface.show_dialog("その波動って……そんなに危ないの？", GameConfig.player_name)
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("本当に何も知らんのだな……", "マリル")
	await novel_interface.show_dialog("時空位相とは物理法則の根幹だ。いわば宇宙の座標系のようなもの。粒子がどう動こうと、座標軸そのものは安定していなければならない。", "マリル")
	await novel_interface.show_dialog("その座標軸に揺らぎが生じれば、たとえ振れ幅がごく僅かでも、空間内の粒子の秩序に壊滅的な影響を与える。", "マリル")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("例えば、高層ビルを構成する粒子の5％がランダムに1ミクロンずれただけで、材質構造は完全に破壊され、一瞬で崩落する。", "マリル")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("だが今のお前は平然としているし、あの区域の建物にも構造破壊は起きていない。", "マリル")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("（それに『神跡』研究の結果では、『GHOST』を持つ人間はあの種の空間へ入れないはずだ……）", "マリル")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("要するに、お前は万物を引き裂く十二級台風の目に踏み込み、無傷で出てきたうえ、その嵐まで鎮めたことになる。", "マリル")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("……", GameConfig.player_name)
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("あの異変って、私を襲ったあいつらの仕業なのかな？\nなんだか正気を失ってるみたいだったけど……", GameConfig.player_name)
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("そこまでだ！　私はこれから元老院へ報告に行かねばならん——", "マリル")
	await novel_interface.show_dialog("あいつらの中には、会議中に映像をリアルタイム解析して嘘を見抜くのが好きな狂人がいる。だから今は、私が知っていることは少ない方がいい。", "マリル")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wry_smile")
	await novel_interface.show_dialog("元老たちへの言い方が、ずいぶん独特だね……", GameConfig.player_name)
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("それに女の子なら、嘘をついていいタイミングくらい覚えておかないとな〜", "マリル")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"awkward")
	await novel_interface.show_dialog("私は女の子じゃない！！", GameConfig.player_name)
	novel_interface.change_2nd_expression("shy")
	await novel_interface.show_dialog("とにかく、誰にも言わなきゃいいんだろ……", GameConfig.player_name)
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("近年、世界中で記録された同種の時空波動は四例だけだ。\nその大半は『異質物』の収容失敗に関係している。", "マリル")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("特性不明の『神跡』が突然励起されれば、破滅的な結果を招きかねん。", "マリル")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire1")
	await novel_interface.show_dialog("……誰かが傷ついたりもするの？", GameConfig.player_name)
	novel_interface.character_light(0.35,"serious")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("最悪のケースでは、死者だけで数万人にのぼった。", "マリル")
	await novel_interface.show_dialog("そのたび各学園都市は示し合わせたように、そうした事件を『通常事故』として報道してきた……", "マリル")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("ガス漏れ、航空事故、テロ攻撃……といった具合にな。", "マリル")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wail")
	await novel_interface.show_dialog("じゃあ、今回は……", GameConfig.player_name)
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("今回はこれまでと違う。こんな大規模な連続発生は、未だかつて例がない……", "マリル")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("偽装用シナリオの上限を超えている。あの時になれば、もう嘘を組み立てることすらできん。", "マリル")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire1")
	await novel_interface.show_dialog("今回の原因って、もしかして私なのかな？\nもし役に立てることがあるなら……", GameConfig.player_name)
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("余計なことを考えるな。確かにお前の身体の変化はこれと無関係ではないだろうが、お前一人でこんな騒ぎを起こせるものではない。", "マリル")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("手がかりを探したいなら、私の部下と一緒に現場へ行ってみるといい。", "マリル")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("（もし本当にそうなら、今のところ彼女だけが唯一の対抗策か……）", "マリル")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("だが、絶対に無理はするな。そして自分のことは誰にも話すな。分かったか？", "マリル")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"panic")
	await novel_interface.show_dialog("誰にも話すなって……つまり……\n最初から女の子だったふりをしろってこと？", GameConfig.player_name)
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("お前も知っているだろう。\n新豊洲市はずっと科学至上主義を掲げてきた。", "マリル")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("お前が自分の体験を公にしたら、『実験対象』として研究機関へ連れて行かれるぞ〜", "マリル")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("その時は科学に一生を捧げたおっさんたちが、列をなしてお前の身体を調べたがるだろうな……", "マリル")
	await novel_interface.show_dialog("こんな可愛い女の子は滅多にいないからな——", "マリル")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wail")
	await novel_interface.show_dialog("……わ、分かりました！！", GameConfig.player_name)
	await novel_interface.show_dialog("わ、私は絶対に変なことは口にしません！！", GameConfig.player_name)

	print("=== 第二章第5话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
