# chapter2_ep24.gd - 第二章第24话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep24_script()

func play_script():
	pass

func chapter2_ep24_script():
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/bedRoom.png")
	await novel_interface.show_text_only("De vuelta en el apartamento, Elluka todavía se aferra a mi ropa incluso mientras duerme.")
	await novel_interface.show_text_only("Annie y Mariru me ordenan darme la vuelta y no mirar, luego forman una pared humana mientras le quitan los guanteletes de metal y el abrigo roto a Elluka y la ponen ropa normal.")
	await novel_interface.show_text_only("Luego me hacen jurar por mi vida que no le haré ningún daño a Elluka, antes de permitirme llevarla a mi habitación.")
	await novel_interface.show_text_only("...Ahora Elluka está dormida en mi cama, todavía agarrando mi ropa, así que todo lo que puedo hacer es sentarme a su lado.")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("¿Por qué eres tan pegajoso, chico? \\nDios, estoy tan cansado...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Después de una noche entera de operación, estoy completamente agotado. Mientras me dejo caer en la cama, siento el papel en mi bolsillo.")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("Annie dijo que estos son… ¿los Fragmentos del Grimorio?", "Lian")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("Elluka parecía querer esto, y me miró como una linda mascota…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Tumbada en la cama, examino las páginas una vez más. Pero el contenido es tan incomprensible como parecía antes.")
	await novel_interface.show_text_only("Mientras paso las páginas, un par de páginas se me escapan de la mano y caen sobre el cuerpo de Elluka.")
	await novel_interface.show_text_only("En el momento en que las páginas tocan su cuerpo, de repente aparece un brillo azulado.")
	await novel_interface.show_text_only("Una ola de símbolos y palabras brota de las páginas, e incluso el aire de mi habitación comienza a temblar.")
	await novel_interface.show_text_only("De repente, las páginas restantes parecen arrastradas por una fuerza invisible hacia el cuerpo de Elluka.")
	await novel_interface.show_text_only("Se produce un estallido de luz deslumbrante y luego todo desaparece.")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("¡¿Q-Qué es esto—?!", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_normal","normal")
	await novel_interface.show_dialog("Búsqueda iniciada. Objetivo identificado:\\nChocolate... ¡hermana mayor!", "Elluka")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("Elluka?! ¡Estás despierto!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elluka de repente me abraza. Al mismo tiempo, la puerta detrás de mí se abre de golpe.")
	novel_interface.show_character("anne_battle","perspire")
	await novel_interface.show_dialog("Oye, ¿qué fue ese temblor?\\n...Espera, ¿finalmente hiciste algo con Elluka?", "Annie")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Annie me mira como si fuera un pervertido.")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("ren_battle","perspire1",0.25)
	await novel_interface.show_dialog("No es lo que piensas. ¡Déjame explicarte!", "Lian")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_left(-0.25)
	novel_interface.show_character("iluka_normal","normal",0.25)
	await novel_interface.show_dialog("Energía, llena.\\nBuscando... destino no encontrado.", "Elluka")
	novel_interface.character_2nd_light(0.35,"worry")
	novel_interface.character_dark()
	await novel_interface.show_dialog("¿Por qué, a quién buscas?", "Lian")
	novel_interface.character_2nd_dark()
	novel_interface.character_light(0.35,"sleepy")
	await novel_interface.show_dialog("… Administrador, del Palacio de Justicia.", "Elluka")
	novel_interface.character_2nd_light(0.35,"perspire1")
	novel_interface.character_dark()
	await novel_interface.show_dialog("¿El Palacio de Justicia...? ¿Qué es eso?\\nDe todos modos, obtengamos Mariru y averigüemos qué hacer.", "Lian")
	await novel_interface.hide_all_characters()
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	novel_interface.show_character("liliu_research","shock")
	await novel_interface.show_dialog("Palacio de Justicia... Ustedes me están metiendo en un gran problema. Tu amigo es miembro de la Congregación.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("¿Eh? ¿Qué es eso?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Mientras investigaba sobre las brujas, conocí estas extrañas organizaciones clandestinas, incluida la Congregación, la más antigua de su tipo.", "Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("Posteriormente, la Congregación se dividió en diferentes facciones, y el Palacio de Justicia es una de ellas.", "Mariru")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Desde que se separó hace cientos de años, el Palacio de Justicia ha estado amenazando con acabar con todas las brujas y ha orquestado la infame Caza de Brujas.", "Mariru")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("Odio tratar con grupos tan supersticiosos.", "Mariru")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("Originalmente estaba planeando colocar a Elluka en una guardería en New Opulentia...\\nPero dadas las circunstancias, no puedo dejarla ir.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("Debes tener otros planes. Será mejor que no realices ninguna investigación extraña sobre ella...", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","happy",0.25)
	await novel_interface.show_dialog("¿Soy tan malo ante tus ojos?", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru me golpea la cabeza. \\nElluka hace pucheros y mira a Mariru enojado.")
	novel_interface.show_character("iluka_normal","unhappy")
	await novel_interface.show_dialog("Objetivo identificado. Índice de amenaza, extremadamente alto.", "Elluka")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","normal",0.25)
	await novel_interface.show_dialog("… Pequeño mocoso.", "Mariru")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("Oh, Elluka, ¿qué tarea te dio Jacob?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elluka frunce el ceño y lentamente recuerda su tarea—")
	novel_interface.show_character("iluka_normal","worry")
	await novel_interface.show_dialog("Primero, acabar con las brujas. Terminado. \\nEn segundo lugar, obtenga el manuscrito. Fallido.", "Elluka")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","worry")
	await novel_interface.show_dialog("¿El manuscrito? ¿No es Lian el que lo tiene?", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_normal","worry")
	await novel_interface.show_dialog("Buscando... Excepción de estado. \\nManuscrito… consumido.", "Elluka")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","perspire1",0.25)
	await novel_interface.show_dialog("¿Consumido? ¿Quieres decir que las páginas están dentro de ti ahora?\\n¿O fueron parte del grimorio de Elluka todo el tiempo?", "Lian")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_dialog("Tu administrador no te dejó absorberlos...\\n¿Tenía miedo de que te volvieras demasiado poderoso para que él pudiera controlarlo?", "Lian")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_battle","smile")
	await novel_interface.show_dialog("Esa es una historia completa con solo un par de sus palabras, Lian. ¡Bien hecho!", "Annie")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Espera, el Grimorio de Elluka. \\nLo que significa...", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("¿Este niño también es una bruja?", "Mariru")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Mariru intenta pellizcarle la mejilla, pero Elluka lo esquiva ágilmente.")
	novel_interface.character_light(0.35,"smile")
	await novel_interface.show_dialog("Hace mucho que escucho que algunos grupos intentan crear y controlar brujas. ¡No faltan arribistas que mueren por tener súper soldados!", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("¿Cómo es que ustedes dos saben tanto sobre las brujas...? Soy el único que está a oscuras aquí. Dime, ¿cómo se convierte una niña en bruja?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","worry")
	await novel_interface.show_dialog("Uh, al principio yo tampoco estaba seguro. Recuerdo haber leído ese libro sin saber qué era.", "Annie")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Comencé a sentirme mareado a medida que el contenido se hacía cada vez más difícil. Luego, en un momento, sentí como si una fuerza desconocida entrara en mi cuerpo.", "Annie")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("Un día, pronuncié un hechizo del libro y fui arrastrado a otro espacio-tiempo...", "Annie")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","smile",0.25)
	await novel_interface.show_dialog("Espacio-tiempo... Según los datos satelitales, el flujo espacio-tiempo ya se había detenido cuando llegaste a la subestación.", "Mariru")
	novel_interface.character_light(0.35,"perspire")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("¡No es de extrañar que no tuviera el mismo sentimiento que tenía en otras Áreas Flux!", "Annie")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("Lo que usted llama un área de flujo se conoce en la literatura de brujas antigua como \"capullo de bruja\".", "Mariru")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,false)
	await novel_interface.show_dialog("Se forma cuando un humano se transforma en bruja. Los extraños no pueden romperlo ni entrar en él. Es de naturaleza muy similar a un espacio generado por Substance H, ¿no crees?", "Mariru")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("Y casi en el momento en que el flujo desapareció, nuestro satélite detectó señales ópticas...", "Mariru")
	novel_interface.change_2nd_expression("speak")
	await novel_interface.show_dialog("Quiero decir, aparecieron los tipos contra los que luchaste.", "Mariru")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("Piénselo: “Capullo de bruja”… En el momento en que el capullo desapareció, estos tipos salieron. Es como si hubieran salido del capullo.", "Mariru")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("iluka_normal","unhappy")
	await novel_interface.show_dialog("¡Bruja, termina!", "Elluka")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("¿¡Entonces las brujas realmente han perdido la cabeza porque no pueden soportar la información del Grimorio!?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_battle","worry",0.25)
	await novel_interface.show_dialog("Eran simplemente chicas normales. No pudieron soportar el poder mágico proveniente de los guiones y resultaron heridos.", "Annie")
	await novel_interface.show_dialog("En el momento en que desencadenaron una violenta distorsión espacial, se convirtieron en...\\nLos seres monstruosos que la gente llama \"Brujas\".", "Annie")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("Se dice en muchos libros antiguos que cuanta más información se conoce sobre el poder mágico, más fácilmente se sufre de locura irreversible.", "Mariru")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Si pierden la cordura, las brujas pueden causar grandes desastres. Si esto es cierto…", "Mariru")
	await novel_interface.show_dialog("Entonces ésta podría ser una de las razones por las que la caza de brujas duró tanto en Europa.", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","perspire1",0.25)
	await novel_interface.show_dialog("Mierda. Suena a pandemia.", "Lian")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"angry")
	await novel_interface.show_dialog("Según lo que sabemos, el Administrador de Elluka dio prioridad a la caza de brujas como una forma de recuperar los Fragmentos del Grimorio.", "Mariru")
	await novel_interface.show_dialog("Pero no permitió que Elluka usara el Grimorio... Tal vez quiera crear más brujas con él.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("Pero leí el Grimorio de Elluka y no reconocí ni una sola palabra. ¿Tiene algo que ver con que yo sea un niño?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("iluka_normal","worry",0.25)
	await novel_interface.show_dialog("… ¿Chico?", "Elluka")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Elluka parece nerviosa y da un paso atrás, con cara de perplejidad.")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("Uh, Elluka, explicaré esto más tarde. \\nNo te preocupes...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","uneasy")
	await novel_interface.show_dialog("Pero pude leerlo. Entonces, ¿tal vez Lian realmente es solo un idiota después de todo?", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("Tengo más curiosidad por saber cómo se puede entrar fácilmente al Capullo de la Bruja.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("¡Yo no lo pedí! Cada vez que entro al área, siempre hay alguien que quiere matarme...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("—Lo que hiciste implica cruzar múltiples dimensiones. La ciencia no puede explicar esto por ahora.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Si la ciencia puede explicar algo aquí, lo primero que quiero saber es ¡por qué me convertí en niña!")
	novel_interface.show_character("anne_battle","smile")
	await novel_interface.show_dialog("Je-je, déjalo a un lado. ¡Cualquier duda se resolverá tarde o temprano!", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("Eso es pensamiento positivo...", "Lian")

	print("=== 第二章第24话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
