# chapter2_ep17.gd - 第二章第17话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep17_script()

func play_script():
	pass

func chapter2_ep17_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_diningRoom.png")
	await novel_interface.show_text_only("Voilà à quoi devrait ressembler une école riche ! \\nRegardez ces plats appétissants à la cantine.")
	novel_interface.show_character("ren_uniform","happy")
	await novel_interface.show_dialog("Salut ! Je voudrais un ensemble de riz au curry et trois ailes de poulet frites.", "Lian")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("Les galettes de crevettes ont l'air bonnes. J'en aurai deux s'il vous plaît.", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Es-tu sûr de pouvoir finir tout ça ?", "Personnel de la cantine")
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("Bien sûr, c'est du gâteau !", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Hé, regarde ! Cette fille mange comme un cheval.", "Étudiant 1")
	await novel_interface.show_dialog("Incroyable… Est-ce qu'elle mange toujours autant ?", "Étudiant 2")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("(… je suis un garçon, d'accord ? C'est normal.)", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","normal1",0.25)
	await novel_interface.show_dialog("Vous savez, les gens vous envient. \\nVous mangez beaucoup sans prendre de poids…", "Annie")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Rien de spécial. \\nHmmmmm ! Les gâteaux aux crevettes sont tellement délicieux !", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("Eh bien, Lian…", "Annie")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Quoi ? (Munches) \\nLe riz au curry est tellement bon ! (Gloires)", "Lian")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("J'adore cette école ! (Barbotines)", "Lian")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal1")
	await novel_interface.show_dialog("Tu manges vraiment comme un cheval, n'est-ce pas ?", "Annie")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("Hein ?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Est-elle la nouvelle étudiante transférée ?", "Étudiant 1")
	await novel_interface.show_dialog("Cela ne ressemble pas du tout à une fille… \\nEww, elle écarte les jambes lorsqu'elle est assise. C'est dégoûtant !", "Étudiant 2")
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("… C'est vraiment nul.", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("Bouh…", "Lian")
	await novel_interface.show_dialog("Eh bien… j'ai fini de manger…", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","panic",0.25)
	await novel_interface.show_dialog("C’est ce qu’une fille mangerait.", "Annie")
	novel_interface.character_light(0.35,"uneasy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Avant, j'étais un gros mangeur ! \\nJe pourrais manger autant que je peux et prendre mon temps pour digérer…", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("Hahaha…! Es-tu vraiment un cheval ? Pourquoi ferais-tu ça ?", "Annie")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"gratified")
	await novel_interface.show_dialog("Probablement parce que... j'avais trop souvent faim quand j'étais enfant.", "Lian")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Shot/cityCrash_ruin.png")
	await novel_interface.show_text_only("Aegis ne peut qu'identifier et protéger les balles. Cela signifie que les soldats armés peuvent facilement pénétrer son champ de force.")
	await novel_interface.show_text_only("Le champ de force a un rayon de 20 milles, ce qui était effectivement le dernier fossé pour des millions de survivants à l’époque.")
	await novel_interface.show_text_only("La guerre a laissé derrière elle de nombreux orphelins. L'organisation de la défense a alourdi les Sénat. Ainsi, les fournitures destinées à chaque école maternelle étaient fortement rationnées.")
	await novel_interface.show_text_only("De nombreux enfants mouraient de faim et devaient chercher de la nourriture dans la zone de guerre proche de la frontière. J'étais l'un d'entre eux…")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_diningRoom.png")
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("… Lian.", "Annie")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Je comprends vos sentiments. Juste… ne mange pas trop maintenant.", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Annie a peut-être aussi vécu cette époque…")
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("Hé, prenons quelques desserts après l'école !", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("… D'accord !", "Lian")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/other/BG_City_coffeeShop.png")
	novel_interface.show_character("anne_uniform","normal1")
	await novel_interface.show_dialog("Nous avons rarement du temps libre pour sortir ainsi, Lian.", "Annie")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","shy",0.25)
	await novel_interface.show_dialog("C'est en fait la première fois que je vais dans ce genre de restaurant… \\n(Je me sens un peu mal à l'aise avec les filles autour…)", "Lian")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Très bien, voyons voir… eh bien, je vais prendre celui-là ! \\nParfait à la crème glacée aux bleuets Super Soda Special Drink DX !", "Annie")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("Le nom à l’air vraiment cool !", "Annie")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"gratified")
	await novel_interface.show_dialog("Tu es vraiment un enfant, Annie.", "Lian")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_dialog("Je vais juste prendre un café…", "Lian")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Lian, tu es une fille maintenant. \\nTu ne veux pas essayer des desserts ? Ils sont très délicieux !", "Annie")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"gratified")
	await novel_interface.show_dialog("D'accord… laisse-moi vérifier. \\nEmm… Muffin au fromage Matcha Napoléon… (Pas mal.)", "Lian")
	novel_interface.change_2nd_expression("shy_left")
	await novel_interface.show_dialog("Gâteau Royal à la Crème d'Orange Confite… (Il a l'air délicieux aussi…)", "Lian")
	novel_interface.change_2nd_expression("shy_right")
	await novel_interface.show_dialog("Coupe glacée aux fruits glacés du festin tropical… \\n(Gulps)", "Lian")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_dialog("Excusez-moi… Avez-vous pris votre décision ?", "Serveur")
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_dialog("Eh bien… Ummm \\npeut-être… juste du café… merci…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Très bien.", "Serveur")
	novel_interface.show_character("ren_uniform","panic")
	await novel_interface.show_dialog("Eh bien…", "Lian")
	novel_interface.change_expression("blush")
	await novel_interface.show_dialog("Euh, attends ! J'ai changé d'avis… \\nUn parfait à la crème glacée à la fraise et à la mousse de myrtille s'il vous plaît…", "Lian")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("Je veux juste y goûter ! \\nJe n'ai vu que des filles en manger avant...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("Aha, pas besoin d'expliquer.", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Désolé de vous faire attendre. Voici votre commande.", "Serveur")
	novel_interface.show_character("ren_uniform","timid")
	await novel_interface.show_dialog("Merci!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("Profitez-en !", "Serveur")
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("Bon, prêt à partir !", "Lian")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("…", "Lian")
	novel_interface.change_expression("blush")
	await novel_interface.show_dialog("Miam… miam..!!", "Lian")
	await novel_interface.show_dialog("La fraise sent si fraîche. La crème est vraiment sucrée. Et la mousse aux myrtilles, un peu acidulée mais vraiment savoureuse…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Je me sens un peu gêné quand je trouve Annie en train de me regarder.")
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("Les filles adorent ces desserts. J'ai toujours voulu savoir \\nquel est leur goût.", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("Bahaha… \\nLian, tu es tellement...", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","normal1")
	await novel_interface.show_dialog("Hum ?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("Tellement adorable !", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("Quoi… de quoi tu parles… !", "Lian")

	print("=== 第二章第17话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
