# chapter2_ep09.gd - 第二章第9话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep09_script()

func play_script():
	pass

func chapter2_ep09_script():
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("ดังนั้น... เพื่อให้คุณปลอดภัย ฉันจะลบทุกร่องรอยและบันทึกเกี่ยวกับชีวิตในอดีตของคุณ และเขียนไฟล์ข้อมูลประจำตัวของคุณใหม่", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","perspire1",0.25)
	await novel_interface.show_dialog("คุณสามารถทำอะไรแบบนั้นได้จริงๆเหรอ?\nดังนั้น SID จึงเป็นตำนานอย่างที่พวกเขาพูดกันจริงๆ...", GameConfig.player_name)
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("แน่นอน. นอกจากนี้ บันทึกพลเมืองทุกรายการใน New Opulentia เป็นส่วนหนึ่งของ Substance H แล้ว", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wry_smile")
	await novel_interface.show_dialog("ฮะ? เธอต้องล้อเล่นแน่เลย...", GameConfig.player_name)
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("พวกเขาไม่ได้สอนคุณเรื่องนี้ในโรงเรียนเหรอ? ระบบการบริหารงานพลเมืองทั้งหมดของ New Opulentia สร้างขึ้นจาก Aegis", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("ขวา... ระบบ Aegis เป็นแบบมีม Substance H...", GameConfig.player_name)
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("เนื่องจากมันถักทออย่างลึกซึ้งในชีวิตประจำวัน ทุกคนจึงคุ้นเคยกับการดำรงอยู่นี้ซึ่งเกินกว่าความเข้าใจของมนุษย์มานานแล้ว")
	novel_interface.show_character("liliu_uniform2","normal2")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_battle","worry",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Aegis คือระบบซอฟต์แวร์ เมื่อเปิดใช้งานแล้วจะสามารถติดตั้งสนามป้องกันได้ในรัศมีสามสิบห้ากิโลเมตร", "Mariru")
	await novel_interface.show_dialog("เชลล์ของฟิลด์นั้นสามารถระบุและบล็อกการโจมตีทุกประเภทได้โดยอัตโนมัติ มันสามารถระงับเอฟเฟกต์ของอาวุธ Divine Touch มากมายได้", "Mariru")
	await novel_interface.show_dialog("ไม่มีใครรู้หลักการเบื้องหลังการรับรู้ภัยคุกคาม แต่มีความชาญฉลาดสูง โดยจะไม่ปิดกั้นการไหลของเรื่องหรือข้อมูลที่ไม่เป็นมิตร", "Mariru")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("เป็นรากฐานอย่างแท้จริงที่ช่วยให้ New Opulentia สามารถฟื้นตัวจากสงครามได้อย่างรวดเร็วและรักษาความเป็นกลางเอาไว้ได้", "Mariru")
	await novel_interface.show_dialog("และเมนเฟรมของ Aegis ก็สามารถระบุและป้องกันการโจมตีทางไซเบอร์ได้เช่นกัน", "Mariru")
	await novel_interface.show_dialog("เนื่องจากการรักษาความปลอดภัยนั้นไร้ที่ติ วุฒิสภา จึงตัดสินใจย้ายระบบการบริหารเมืองทั้งหมดไปยังเมนเฟรม Aegis", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("ตราบใดที่บัตรประจำตัวเชื่อมโยงกับโทรศัพท์ Aegis ก็สามารถสร้างความสัมพันธ์ระหว่างข้อมูลประจำตัว ทะเบียนบ้าน และบันทึกบัญชีของบุคคลได้ แม้แต่เครดิต CAPH ก็สามารถตรวจสอบได้") #鎹㈣闂important
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("เราได้เรียนรู้ทุกอย่างที่โรงเรียนจริงๆ...\nฉันลืมเกือบทุกอย่างทันทีหลังสอบ", GameConfig.player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("แต่สิ่งที่ฉันจะบอกคุณต่อไป—เป็นความลับ", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru จ้องมองมาที่ฉันอย่างจริงจัง ราวกับว่าเธอได้ตัดสินใจแล้ว")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("ระบบ Aegis มีความสามารถอีกอย่างหนึ่งที่ไม่เคยเปิดเผยต่อสาธารณะ", "Mariru")
	await novel_interface.show_dialog("ทันทีที่ใครก็ตามเข้าสู่ระยะของสนามป้องกัน ระบบจะระบุพวกเขาทันที", "Mariru")
	await novel_interface.show_dialog("คุณสามารถพูดได้ว่าการระบุตัวตนนั้นขึ้นอยู่กับจิตวิญญาณ", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("ขึ้นอยู่กับจิตวิญญาณ ...?", GameConfig.player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("Aegis กำหนดรหัสอิเล็กทรอนิกส์ให้กับทุกคนที่อยู่ในช่วงดังกล่าว หลังจากนั้นไม่ว่าบุคคลนั้นจะปลอมตัว เปลี่ยนสีหน้า สูญเสียความทรงจำ หรือถูกล้างสมอง...", "Mariru")
	await novel_interface.show_dialog("...พวกเขาจะยังคงถูกระบุว่าเป็นรหัสต้นฉบับ", "Mariru")
	await novel_interface.show_dialog("แต่ละรหัสมีเพียงสองสถานะที่เป็นไปได้: อยู่ภายในระยะการป้องกันหรือนอกระยะ", "Mariru")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("หากรหัสไม่อยู่ในช่วงอีกต่อไป แสดงว่าบุคคลนั้นออกจากเมืองไปแล้วหรือเสียชีวิตแล้ว", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ความเย็นไหลผ่านหนังศีรษะของฉันขณะที่ฉันฟัง")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("ทุกคน... เป็นเพียงรหัสเหรอ?", GameConfig.player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("ถูกต้องแล้ว ไม่มีสิ่งใดแนบมาด้วย ไม่มีชื่อ ไม่มีรูปถ่าย ไม่มีข้อมูลตำแหน่ง", "Mariru")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("การสร้างไฟล์สำหรับแต่ละโค้ด จับคู่กับบุคคลจริง อัปเดตข้อมูล และติดตามเป้าหมายหลัก นั่นคือหน้าที่ของ SID", "Mariru")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("มันเป็นระบบรักษาความปลอดภัยที่ Academy City ทุกคนอิจฉา", "Mariru")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("มัน... เฝ้าดูทุกคนที่ปกป้อง ทุกรหัส ทุกวินาทีของทุกวัน...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("สีหน้าที่ซับซ้อนปรากฏขึ้นบนใบหน้าของ Mariru มันคงอยู่เพียงชั่วครู่แต่ฉันก็มองเห็นได้ชัดเจน")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("ไม่น่าแปลกใจเลยที่คุณรู้แน่ชัดว่าเมื่อใดที่สายลับจากประเทศอื่นแอบเข้ามาใน New Opulentia", GameConfig.player_name)
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("รอก่อน! แล้ว...ของฉัน", GameConfig.player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("ฉันให้คนของฉันคัดกรองรหัสใหม่ทุกรหัสที่ปรากฏในวันนี้--", "Mariru")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("ฉันไม่เคยพบกรณีเช่นนี้มาก่อน... แต่เท่าที่ Aegis กังวล คุณยังคงลงทะเบียนเป็นผู้ชาย", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("อารมณ์พุ่งผ่านตัวฉันแรงมากจนตาแทบลุกเป็นไฟ\nในที่สุด... ในที่สุด ฉันก็พิสูจน์ได้ว่าฉันยังเป็นเด็กผู้ชาย!")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("ดังนั้นคุณไม่สามารถเป็นเด็กผู้ชายได้อีกต่อไป", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("ฮะ?", GameConfig.player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("ตอนนี้คุณได้เรียนรู้ข้อมูลลับทั้งหมดนี้แล้ว...", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru จู่ๆ ก็ก้าวเข้ามาใกล้มากขึ้น ฉันถอยออกไปโดยสัญชาตญาณ เพียงแต่พบว่าร่างกายของฉันถูกกดทับเข้ากับผนังแล้ว")
	await novel_interface.show_text_only("แต่เธอไม่หยุด เธอวางแขนข้างหนึ่งไว้กับกำแพงและทำให้ฉันจนมุม")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("ก-แล้วนั่นหมายความว่าไง...?", GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("หน้าเธอใกล้เกินไป!\nหัวใจฉันเต้นแรงจนรู้สึกเหมือนจะระเบิด!")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("จากนี้ไปคุณก็เป็นของฉัน~", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","awkward",0.25)
	await novel_interface.show_dialog("ฮะ--??", GameConfig.player_name)
	await novel_interface.show_dialog("มะ-คุณหมายถึงอะไร \"เป็นของคุณ\"?!", GameConfig.player_name)
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog(""+GameConfig.player_name+", ID 2519G1911 อายุ 15 ปี.", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru ในที่สุดก็ปล่อยฉันไป จากนั้นจึงดึงอุปกรณ์มือถือออกมาอย่างเชี่ยวชาญ แล้วเริ่มสะบัดและแตะออกไป")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("คุณจึงกลับไปเรียนโรงเรียนรัฐบาลทั่วไปในโรงเรียนมัธยมต้น...\nก่อนหน้านั้น คุณเป็นเด็กวัยรุ่นที่โดดเดี่ยวที่ใช้ชีวิตอยู่คนเดียว~", "Mariru")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("ส่วนสูง 165... ไม่ ตอนนี้ 161 แล้ว และน้ำหนักคุณก็ลดลงไปบ้างแล้ว ดังนั้นฉันควรอัปเดตเรื่องนี้ดีกว่า", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("ขณะที่ Mariru ทำงาน อุปกรณ์มือถือจะส่งเสียงบี๊บยืนยันที่คมชัด")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("ฮะ? ฉันสั้นลงเหรอ?", GameConfig.player_name)
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("(นั่นก็สมเหตุสมผลดี... ไม่มีเสื้อผ้าเก่าของฉันที่พอดีอีกต่อไปแล้ว...)", GameConfig.player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("คุณยังเป็นสมาชิกแฟนคลับของ Akira Takasaki อยู่ใช่ไหม\nจุ๊จุ๊ ช่างไร้เดียงสาจริงๆ...", "Mariru")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("ประวัติการช้อปปิ้งออนไลน์ของคุณก็ค่อนข้างสนุกสนานเช่นกัน ~ My Little Sister Could Never Be an Idol, Magic Love H...", "Mariru")
	await novel_interface.show_dialog("แล้วคุณยังซื้อหมอนข้าง ... รุ่นพิเศษด้วยเหรอ?", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","awkward",0.25)
	await novel_interface.show_dialog("อร๊ายยยยย!!!\nอย่ามอง! อย่ามองแบบนั้น!!!!", GameConfig.player_name)
	novel_interface.change_2nd_expression("sob")
	await novel_interface.show_dialog("(นี่คือการประหารชีวิตในที่สาธารณะใช่ไหม!\nมะ-ไม่ ถ้าเธอเห็นว่านี่แย่ยิ่งกว่านั้นอีก!!)", GameConfig.player_name)
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"normal2")
	await novel_interface.show_dialog("เอาล่ะ... ฉันคิดว่าฉันแกล้งคุณมามากพอแล้ว~", "Mariru")
	await novel_interface.show_dialog("ฉันผ่านการกวาดล้างระดับ 5 มาหลายปีแล้ว แต่นี่เป็นครั้งแรกที่ฉันได้ทำสิ่งที่สนุกขนาดนี้", "Mariru")
	await novel_interface.show_dialog("มาดู... เริ่มต้นการแก้ไขโปรไฟล์...\nเปลี่ยนเพศเป็น \"หญิง\"!", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("เสียงยืนยันที่ชัดเจนดังขึ้น")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("จุ๊จุ๊ จะทิ้งการประทับเวลาไว้ไหม\nจะไม่เกิดขึ้นหากคนเหล่านั้นสังเกตเห็น...", "Mariru")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("จากนั้น... จัดประเภทประวัติการแก้ไขเป็น \"ความลับ\"\nนั่นควรจะเป็นเช่นนั้น", "Mariru")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("การมีบันทึกของครัวเรือนและการบริหารทั้งหมดถูกแปลงเป็นดิจิทัลอย่างสมบูรณ์นั้นสะดวกจริงๆ", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","panic",0.25)
	await novel_interface.show_dialog("เจ-แค่... ง่ายขนาดนั้น??", GameConfig.player_name)
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("อืม~ ฉันเพิ่งแก้ไขไฟล์ของคุณในบันทึกระบบการดูแลระบบทุกรายการ", "Mariru")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("ตอนนี้คุณเป็นผู้หญิงตามกฎหมายแล้วคุณรู้ไหม", "Mariru")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("ตอนนี้คุณยังสามารถเดินตรงเข้าไปในตู้รถไฟสำหรับผู้หญิงโดยเฉพาะได้เลย~♥", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"sob")
	await novel_interface.show_dialog("เหลือเชื่อ! มันเปลี่ยนง่ายขนาดนั้น...!!", GameConfig.player_name)
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("หัวใจของฉันจม ฉันรับไม่ได้...")
	novel_interface.character_light(0.35,"normal2")
	await novel_interface.show_dialog("นอกจากนี้ ชื่อเก่าของคุณยังผูกพันกับตัวตนผู้ชายของคุณมากเกินไป...", "Mariru")
	await novel_interface.show_dialog("ชื่อใหม่อะไรจะน่ารักพอสำหรับคุณนะ สงสัย...?\nขอคิดดูก่อน...", "Mariru")
	await novel_interface.hide_all_characters()
	novel_interface.change_background("res://assets/images/bg/Shot/girlchar_battleWearingCry.png")
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	await novel_interface.show_text_only("ทันใดนั้นมันก็ทำให้ฉันรู้สึกว่า Mariru มีพลังงานมากแค่ไหน")
	await novel_interface.show_text_only("เธอสามารถเปลี่ยนชีวิตทั้งชีวิตของใครบางคนได้ด้วยการสะบัดนิ้วเพียงไม่กี่ครั้ง...")
	await novel_interface.show_text_only("ฉันรู้ว่าเธอทำเพื่อปกป้องฉัน แต่... มันยังรู้สึกไม่ยุติธรรมเลย!!")
	await novel_interface.show_text_only("ผมเป็นเด็กผู้ชาย!! ฉันยังคง...")
	await novel_interface.show_text_only("แค่คิดก็น้ำตาไหลก่อนจะห้ามไว้...\nสะอื้น สะอื้น...")
	await novel_interface.show_text_only("ให้ตายเถอะ เพราะร่างกายของฉันกลายเป็นผู้หญิงเหรอ?\nทำไมฉันถึงร้องไห้ง่ายขนาดนี้...?")
	await novel_interface.show_text_only("ฉันสัญญากับตัวเองแล้วว่าจะไม่ร้องไห้อีก...\nแต่น้ำตากลับไหลไม่หยุด...")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("โอ้? คุณกำลังร้องไห้จริงๆเหรอ?\nเป็นเพราะเซ็กส์ของคุณเปลี่ยนไปตลอดกาลใช่ไหม~?", "Mariru")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("ฮ่าๆ เอาล่ะ เอาล่ะ...\nจริง ๆ การที่คุณร้องไห้แบบนี้ทำให้คนอื่นอยากทะนุถนอมคุณจริงๆ~", "Mariru")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("อยากทะนุถนอมคุณ... ทะนุถนอม...\nLian...", "Mariru")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("หืม... \"Lian\" ฟังดูค่อนข้างดีจริงๆ~\nมันเหมาะกับรูปลักษณ์ของคุณตอนนี้เช่นกัน", "Mariru")
	await novel_interface.show_dialog("ตัดสินใจแล้ว!\nตั้งแต่วันนี้เป็นต้นไป ชื่อของคุณคือ \"Lian\"!", "Mariru")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("ตั้งค่าสิทธิ์การซิงโครไนซ์ข้อมูลเป็น... ระดับ 5\nนั่นน่าจะเปลี่ยนป้ายชื่อในบันทึกเกมของคุณใช่ไหม!", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("Lian...\nอะ-...? อะไรนะ?!", "Lian")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("(เธอล้อเล่นใช่ไหม! เธอล้อเล่นฉันแน่!)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("เสร็จแล้ว! จากนี้ไปทุกระบบการระบุตัวตนจะจดจำคุณด้วยชื่อนั้น... น้อย Lian~", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","sob",0.25)
	await novel_interface.show_dialog("คุณสามารถเปลี่ยนชื่อแบบสบายๆ แบบนี้ได้จริงหรือ?\nฮึ...", "Lian")
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("นั่นไง หยุดดมได้แล้ว~", "Mariru")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("การ์เดียน... อืม ฉันจะตั้งค่าให้เอง", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("ฉัน-ฉันไม่ต้องการสิ่งนั้น!", "Lian")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("โอ้? คิดจะต่อต้าน--", "Mariru")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("น้ำเสียงของฉันตอนนี้ฟังดูอ่อนโยนมากจนทำให้คุณรู้สึกว่าฉันมีเหตุผลได้ง่ายหรือเปล่า?", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru ก็กลายเป็นเสียงดุดัน\nความกดดันอันท่วมท้นถาโถมใส่ฉัน...")
	novel_interface.show_character("liliu_uniform2","serious")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ren_battle","panic",0.25)
	await novel_interface.show_dialog("ขอโทษที การ์เดี้ยน!!\nฉันผิดไปแล้ว!!", "Lian")
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("ด้วยสถานการณ์ปัจจุบันของคุณ ฉันควรจะขังคุณไว้จริงๆ~", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wail")
	await novel_interface.show_dialog("กรุณาอย่ายิ้มในขณะที่พูดสิ่งที่อันตราย!", "Lian")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("สิ่งที่ฉันเปลี่ยนแปลงเมื่อกี้คือข้อมูลพื้นฐานของคุณ บันทึกทางประวัติศาสตร์ที่เชื่อมโยงกันยังต้องมีการปรับปรุงแก้ไขอีกมาก", "Mariru")
	await novel_interface.show_dialog("หากตัวตนของคุณถูกเปิดเผยก่อนที่จะเสร็จสิ้น คุณจะตกอยู่ในอันตรายได้ทุกเมื่อ ฉันจะล็อคไฟล์ของคุณตอนนี้--", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("อุปกรณ์มือถือส่งเสียงยืนยันที่คมชัดอีกครั้ง")
	novel_interface.show_character("liliu_uniform2","serious")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_battle","wail",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("...!", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"sob")
	await novel_interface.show_dialog("หืม?", "Lian")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("มันเป็นการส่งผ่านข้อมูลลับ ฉันต้องจัดการกับมัน\nไปรอฉันที่ล็อบบี้ก่อน", "Mariru")

	print("=== 绗簩绔犵9璇濈粨鏉?===")

	# 璋冪敤鍓ф儏缁撴潫鍑芥暟
	await novel_interface.end_story_episode(0.5)

