# chapter2_ep02.gd - 第二章第2话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep02_script()

func play_script():
	pass

func chapter2_ep02_script():
	novel_interface.change_music("res://assets/audio/music/Barrier Maze.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/spSoundChannel.png")
	await novel_interface.show_dialog("โปรดทราบ ทุกทีม ความผันผวนของเฟสลดลงแล้ว!", "ตัวแทนเอ")
	await novel_interface.show_dialog("ศัตรูอาจปรากฏตัวออกมาได้ทุกนาที!\nรักษาตำแหน่งของคุณและเตรียมพร้อมที่จะโจมตี!!", "ตัวแทนเอ")
	await novel_interface.show_dialog("... รายงานตัวแล้ว!", "ตัวแทนบี")
	await novel_interface.show_dialog("ยูนิตฮิวแมนนอยด์ 2 ยูนิตปรากฏขึ้นภายในระยะการมองเห็น ตรงโซนแกนกลางที่ผิดปกติ...", "ตัวแทนบี")
	await novel_interface.show_dialog("มนุษย์...?\nเป็นไปได้ยังไง! ผลสแกนมีมแสดงอะไร??", "ตัวแทนเอ")
	await novel_interface.show_dialog("เฉดสีคือ...\nสีเขียว!!", "ตัวแทนบี")
	await novel_interface.show_dialog("ดูเหมือนพวกเขาจะเป็นเด็กสาวสองคน...\nอดทนไว้! ระงับไฟของคุณ!", "ตัวแทนบี")
	await novel_interface.show_dialog("...", "ตัวแทนเอ")
	await novel_interface.show_dialog("เราเพิ่งได้รับคำสั่ง สิ่งสำคัญประการแรกคือการรักษาความปลอดภัยและนำพวกเขากลับไปที่สำนักงานใหญ่\nส่งเจ้าหน้าที่อาวุโสไปเจรจา—", "ตัวแทนเอ")
	await novel_interface.show_dialog("คนอื่นๆ ระวังตัวกันด้วยนะครับ หากเป้าหมายมีการเคลื่อนไหวที่น่าสงสัยในระหว่างการเจรจา ให้กำจัดพวกมันทันที!!", "ตัวแทนเอ")
	await novel_interface.show_dialog("เข้าใจแล้ว!", "ตัวแทนบี")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_outside.png")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("เราเดินอย่างระมัดระวังไปยังทางออกของศูนย์วิจัย")
	await novel_interface.show_text_only("สิ่งที่รอเราอยู่ที่นั่น นอกจากถนนที่คุ้นเคยแล้ว ยังมีเทปกั้นสิ่งกีดขวางและกลุ่มคนติดอาวุธยืนอยู่ด้านหลังพร้อมสำหรับเรา")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("เหตุใดจู่ๆ ก็มีคนจำนวนมากปรากฏตัวขึ้น?!", GameConfig.player_name)
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("อ่า—Annie!\nรีบไปเปลี่ยนเสื้อผ้าคืนเร็ว!!", GameConfig.player_name)
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("เสื้อผ้าพวกนี้น่าอายเกินไปแล้ว...\nฉันไม่ต้องการให้ใครเห็นฉันแบบนี้เลย...", GameConfig.player_name)
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_battle","worry",0.25)
	await novel_interface.show_dialog("นั่นคือสิ่งที่คุณกังวลตอนนี้จริงๆเหรอ?", "Annie")
	novel_interface.change_2nd_expression("uneasy")
	await novel_interface.show_dialog("เสื้อผ้าของคุณถูกเก็บไว้อย่างปลอดภัยกับฉัน ดังนั้นไม่ต้องกังวล...", "Annie")
	await novel_interface.show_dialog("หากคุณต้องการเปลี่ยนจริงๆ เพียงแค่ถอด 'ชุดต่อสู้' ที่คุณใส่อยู่ตอนนี้ออกแล้วใส่เสื้อผ้าที่หลวมๆ ตามปกติกลับคืนมา~", "Annie")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("แต่มีผู้ชายจำนวนมากที่อยู่ข้างหน้า...\nคุณอยากเปลี่ยนแปลงต่อหน้าพวกเขาจริงๆเหรอ?", "Annie")
	novel_interface.character_light(0.35,"shy_right")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("ฮึ...\nแต่ฉันเป็นคนดี...", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("ลองคิดดูสิ... คุณใส่เสื้อผ้าผู้ชายก่อนหน้านี้!\nเป็นไปได้ไหม—", "Annie")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("ฮะ? คุณเคยตกอยู่ในสถานการณ์เช่นนี้มาก่อนเหมือนกัน??", GameConfig.player_name)
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("(นั่นก็สมเหตุสมผลดี... Annie คงไม่ใช่คนธรรมดาเหมือนกันใช่ไหม?)", GameConfig.player_name)
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("(ถ้าเป็น Annie บางทีเธออาจจะเข้าใจสิ่งที่ฉันกำลังเผชิญอยู่...)", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("อืม เข้าใจแล้ว...", "Annie")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("คุณเป็นคนประเภทที่แอบยืมเสื้อผ้าของหนุ่มๆ ที่คุณชอบมาใส่เองใช่ไหมล่ะ?", "Annie")
	novel_interface.character_light(0.35,"wail")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("นั่นก็คือ 'ไม่เข้าใจ' เลย!!!", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("อืม~ จริงๆ แล้ว"+GameConfig.player_name+"เป็นคนประเภทที่หลงใหลในกลิ่นของเพศตรงข้ามใช่ไหมล่ะ? ไม่ต้องอาย...", "Annie") #文本变化important
	novel_interface.character_light(0.35,"sob")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("อย่าทำหน้าแบบนั้นว่า 'ถึงจะนิสัยไม่ดีแต่ยังไงฉันก็ยอม'!!!", GameConfig.player_name)
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("เฮ้อ... ฉันยังไม่รู้เลยว่าทำไมฉันถึงกลายเป็นแบบนี้...", GameConfig.player_name)
	novel_interface.character_dark()
	await novel_interface.show_text_only("...")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("หยุดตรงนั้น!\nวางมือของคุณไว้ในที่ที่ฉันมองเห็น!", "SID ตัวแทน")
	novel_interface.character_dark()
	await novel_interface.show_text_only("คนในชุดสูทสีดำก้าวไปข้างหน้าและตะโกนใส่เรา")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("ren_battle","awkward",0.25)
	await novel_interface.show_dialog("ฮะ...?\nพวกเขาคิดว่าเราเป็นคนเลวเหรอ?", GameConfig.player_name)
	novel_interface.change_2nd_expression("panic")
	await novel_interface.show_dialog("(เดี๋ยวก่อน เครื่องราชอิสริยาภรณ์บนหน้าอกของผู้นำ...)\n(โล่ทรงกลมที่สมบูรณ์แบบ—อย่าบอกนะว่านั่นคือ...)", GameConfig.player_name)
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0)
	await novel_interface.show_dialog("พวกคุณสองคน ฉันเป็น SID เจ้าหน้าที่\nเพื่อความปลอดภัยของคุณเอง ให้คงท่านั้นไว้และอย่าขยับ", "SID ตัวแทน")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_text_only("อย่างที่คิดไว้เลย SID!\nเราแย่แล้ว!!!")
	await novel_interface.show_text_only("ทันใดนั้น จิตใจของฉันก็เต็มไปด้วยข่าวเกี่ยวกับ SID ที่ส่งเจ้าหน้าที่จำนวนมากไปจับสายลับ")
	novel_interface.change_expression("sob")
	await novel_interface.show_text_only("แล้วก็มีตำนานเมืองเกี่ยวกับ 'เรือนจำลับ' 'ปฏิบัติการลอบสังหาร' และอื่นๆที่คล้ายกัน...")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("รายงานจากโซนกักกันหลัก: เป้าหมายทั้งสองไม่ได้แสดงเจตนาร้าย\nระดับภัยคุกคามตั้งค่าไว้ชั่วคราวเป็น D+", "SID ตัวแทน")
	await novel_interface.show_dialog("เรามาเริ่มด้วยคำถามง่ายๆ สองสามข้อ...\nคุณเป็นใคร และมาทำอะไรที่นี่?", "SID ตัวแทน")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("ฉันเป็นนักเรียนจากเมืองนี้...", GameConfig.player_name)
	novel_interface.change_expression("wail")
	await novel_interface.show_dialog("เราเพิ่งมาทัศนศึกษาเยี่ยมชมสถาบันวิจัย...", GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("เจ้าหน้าที่ในชุดดำทำให้เราดูถูกเหยียดหยาม")
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("เป็นเช่นนั้น— ทัวร์เหรอ? ของสถาบัน?", "SID ตัวแทน")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_text_only("ไม่นะ...\nจู่ๆฉันก็จำได้-")
	await novel_interface.show_text_only("เนื่องจากการหายไปของ 'Roskin Cup' สถาบันจึงถูกสั่งปิดฉุกเฉินตั้งแต่เมื่อคืนนี้")
	novel_interface.change_expression("sob")
	await novel_interface.show_text_only("เดินออกมาจากที่นั่นอย่างโจ่งแจ้งในเวลาแบบนี้และอ้างว่าเราเพิ่งมาเยี่ยม... ซึ่งโดยพื้นฐานแล้วถือเป็นคำสารภาพ")
	await novel_interface.show_text_only("ตามที่คาดไว้ ดูเหมือนว่าเธอจะได้รับคำแนะนำบางอย่างผ่านทางหูฟังของเธอ และมองฉันด้วยสายตาที่เข้มงวด")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("agent","",0.25)
	await novel_interface.show_dialog("ฉันได้รับคำสั่งจากหัวหน้าของฉัน คุณสองคนจะมากับเรา", "SID ตัวแทน")
	novel_interface.character_move_right(0,0.3,false)
	novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("ในช่วงเวลาเพียงไม่กี่วินาที เราสองคนก็ถูกล้อมไว้อย่างสมบูรณ์")
	await novel_interface.show_text_only("ทุกที่ที่ฉันมอง ก็มีกำแพงกระบอกปืนชี้มาที่เรา")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("anne_battle","worry",0.25)
	await novel_interface.show_dialog(GameConfig.player_name+"คนพวกนี้ดูเป็นข่าวร้ายจริงๆ...\nทำไมเราไม่รอโอกาสแล้ววิ่งไปหามันล่ะ?", "Annie")
	novel_interface.character_move_left(-0.3,0.3,false)
	novel_interface.character_2nd_move_left(0)
	novel_interface.show_3rd_character("agent","",0.3)
	await novel_interface.show_dialog("โปรดวางใจได้เลย เราจะไม่ทำร้ายคุณ\nตราบใดที่คุณให้ความร่วมมือในการสืบสวน ทั้งหมดนี้ก็จะคลี่คลายได้โดยสันติ", "SID ตัวแทน")
	await novel_interface.show_dialog("คุณควรเข้าใจว่าการหายตัวไปของ 'วัตถุผิดปกติ' นั้นไม่ใช่เรื่องเล็กน้อย มันอาจทำให้เกิดเหตุการณ์ที่เกินกว่าสามัญสำนึกได้ ดังนั้นโปรดให้ความร่วมมือ", "SID ตัวแทน")
	await novel_interface.hide_3rd_character()
	novel_interface.character_move_right(-0.25,0.3,true,"worry")
	novel_interface.character_2nd_move_right(0.25,0.3,false)
	await novel_interface.show_dialog("(เหตุการณ์ที่เกินสามัญสำนึก...?)", GameConfig.player_name)
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("โอเค ฉันเข้าใจแล้ว ฉันจะไปกับคุณ", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("หือ?? ทำไมคุณถึงไปกับพวกเขาล่ะ!\nเฮ้!"+GameConfig.player_name+"!", "Annie")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("คิว-เลิกดึงได้แล้ว! กระโปรงโง่ๆของฉันจะหลุดแล้ว!", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("คุณเป็นคนงี่เง่า! ทำไมคุณถึงไปกับคนที่น่าสงสัยเช่นนี้? จะเกิดอะไรขึ้นถ้าพวกเขาวางยาคุณและขายคุณไปที่ไหนสักแห่ง!", "Annie")
	novel_interface.character_light(0.35,"shy_right")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("จะมีใครอยากได้อะไรจากผู้ชายที่โตอย่างฉัน...", GameConfig.player_name)
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("เดี๋ยวก่อน ใครเล่าจะจัดการปฏิบัติการค้ามนุษย์โดยที่คนจำนวนมากสร้างฉากแบบนี้ขึ้นมา!", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"frustrate")
	await novel_interface.show_dialog(GameConfig.player_name+"เห็นได้ชัดว่าคุณไม่เคยเห็นแก๊งค์บนหมู่เกาะเลโบนามาก่อน...", "Annie")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("ยังไงก็ตาม... บางทีเราอาจจะได้เรียนรู้บางสิ่งบางอย่างในที่สุด\nตอนนี้เราไปกับเธอกันเถอะ...", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("ก็ได้ ไปไหนฉันก็ไปด้วย...", "Annie")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("อืม ถ้าเป็นไปได้ ฉันขอเสื้อโค้ทก่อนได้ไหม?", GameConfig.player_name) 
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("ชุดนี้มันนิดหน่อยจริงๆ...", GameConfig.player_name)
	novel_interface.character_dark()
	await novel_interface.show_text_only("การถูกทุกคนจับตามองขณะแต่งตัวเหมือนเด็กผู้หญิงทำให้ร่างกายของฉันรู้สึกไม่สบายตัว")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("เอาล่ะฉันจะยื่นคำขอ", "SID ตัวแทน")
	await novel_interface.show_dialog("...", "SID ตัวแทน")
	await novel_interface.show_dialog("...ขออภัย หัวหน้าของฉันพูดว่า 'ชุดนั้นน่ารักมาก' และปฏิเสธคำขออย่างเด็ดขาด", "SID ตัวแทน")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("หัวหน้าอะไรจะพูดแบบนั้นด้วย!", GameConfig.player_name)

	print("=== 第二章第2话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
