# chapter2_ep13.gd - 第二章第13话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep13_script()

func play_script():
	pass

func chapter2_ep13_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Trước khi đến trường mới, nhiệm vụ đầu tiên của bạn là rèn luyện kiến thức cơ bản.", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","worry",0.25)
	await novel_interface.show_dialog("Kiến thức cơ bản?\nKhông phải là tôi Annie và bỏ lỡ mọi chuyện xảy ra trong vài năm qua...", "Lian")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Hừ. Bạn đã bỏ lỡ hơn một thập kỷ kiến thức về việc làm con gái phải không?~", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wry_smile")
	await novel_interface.show_dialog("Tôi không cần loại kiến thức đó!", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru hoàn toàn phớt lờ sự phản đối của tôi và sải bước về phía bàn với tinh thần phấn chấn. Sau đó tôi mới nhận ra rằng cô ấy đã chuẩn bị sẵn toàn bộ mặt bàn với mọi loại dụng cụ có thể tưởng tượng được.")
	novel_interface.show_character("liliu_research","speak")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_battle","wry_smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Đầu tiên, bạn cần có khả năng phân biệt 12 màu son tiêu chuẩn và ghi nhớ 20 thương hiệu hàng đầu.", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("Nhiều như vậy...?\nKhông phải về cơ bản các màu đều giống nhau sao?", "Lian")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"smile")
	await novel_interface.show_dialog("Quá ngây thơ! Đó thậm chí không phải là một phần mười của tổng số.", "Mariru")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Và đây tôi đã chuẩn bị đầy đủ các dụng cụ trang điểm cho bạn—kem nền, phấn mắt, son bóng, phấn highlight, tạo khối...", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("Hả? Tôi phải bôi nhiều thứ đó lên mặt sao?!\nKhông phải là tôi đang vẽ tranh... Làm con gái chính xác thì phức tạp đến mức nào...?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","speak",0.25)
	await novel_interface.show_dialog("Đừng lo lắng. Bắt đầu từ hôm nay sẽ có người dạy bạn trang điểm đúng cách.", "Mariru")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Nhưng học sinh trung học thậm chí còn không được phép trang điểm...", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("Bạn thực sự không hiểu thế giới của những nữ sinh trung học...\nNếu bạn cứ hành động bất cẩn như thế này, mọi người sẽ nghi ngờ ngay lập tức.", "Mariru")
	novel_interface.change_2nd_expression("speak")
	await novel_interface.show_dialog("Và ngoài trường học, với tư cách là đặc vụ SID, bạn sẽ cần phải thực hiện tất cả các loại nhiệm vụ. Trang điểm là một trong những kỹ năng cần thiết của một nữ điệp viên.", "Mariru")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("Đặc biệt là với khuôn mặt nhỏ nhắn dễ thương như em—", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru đưa một ngón tay ra và nâng cằm tôi lên.")
	await novel_interface.show_text_only("Tôi lùi lại một bước để tránh bàn tay của cô ấy. Bằng cách nào đó niềm tự hào nam giới của tôi không thể chấp nhận được.")
	novel_interface.show_character("ren_battle","shy_left")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_research","happy",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Chắc chắn là trước đây tôi đã từng làm tình nguyện...\nNhưng tôi chưa bao giờ ngờ rằng mình lại phải học những thứ như thế này...", "Lian")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"smile")
	await novel_interface.show_dialog("Việc đánh giá học viên của SID là cực kỳ nghiêm ngặt. Mỗi vòng loại bỏ một lượng lớn người.", "Mariru")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("Đã nói chuyện lớn như vậy, sao không chứng tỏ bản thân?", "Mariru")
	await novel_interface.show_dialog("Và nếu bạn vượt qua vòng đánh giá cuối cùng, bạn sẽ chính thức được đưa vào danh sách—với mức lương rất kha khá~", "Mariru")
	novel_interface.character_2nd_move_left(-0.25)
	novel_interface.show_character("ren_battle","smile",0.25)
	await novel_interface.show_dialog("Hả? Tôi cũng có thể được trả tiền?!\n(Th-Vậy giỏ hàng Gfat của tôi...)", "Lian")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Được rồi, bây giờ nam nhân có thể ngồi trong góc được rồi.")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"speak")
	await novel_interface.show_dialog("(Hehehe... đúng là một đứa nhóc đơn giản.)", "Mariru")
	novel_interface.change_2nd_expression("angry")
	await novel_interface.show_dialog("Nhưng đổi lại, bạn nên hiểu điều này tốt hơn - với tư cách là sĩ quan chỉ huy của bạn, mệnh lệnh của tôi là tuyệt đối và bạn sẽ tuân theo chúng vô điều kiện!", "Mariru")
	novel_interface.character_2nd_move_left(-0.25)
	novel_interface.show_character("ren_battle","worry",0.25)
	await novel_interface.show_dialog("Tôi đang dấn thân vào điều gì...?", "Lian")
	novel_interface.character_2nd_light(0.35,"speak")
	novel_interface.character_dark()
	await novel_interface.show_dialog("Đầu tiên, hãy để tôi giới thiệu với bạn một người—giáo viên đã tình nguyện dạy bạn trang điểm.", "Mariru")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("Mặc dù trách nhiệm thông thường của cô là thuốc thử nghiệm và phát triển thiết bị đặc biệt...", "Mariru")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("Oh... bạn chắc hẳn là Lian phải không?\nHehe~ Hồ sơ này thú vị thật đấy~", "Cô gái đeo kính")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Xin chào~ Tôi là giám đốc Phòng Nghiên cứu Chiến đấu của SID. Vì cả hai tập tin của chúng ta đều đã bị thay đổi nên bạn chỉ cần gọi cho tôi Ai.", "Cô gái đeo kính")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("Xin chào...\n(Tập tin của cô ấy... cũng bị thay đổi?)", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","blush_wink",0.25)
	await novel_interface.show_dialog("Mariru, Lian đúng là tài liệu nghiên cứu xuất sắc...\nBạn có thể cho tôi mượn cô ấy một lát được không~!?", "Ai")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("(Đối tượng nghiên cứu ư...? Cho mượn tôi...?)", "Lian")
	await novel_interface.show_dialog("(T-Tại sao lưng tôi đột nhiên cảm thấy hơi lạnh...)", "Lian")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("Tôi là người giám hộ của cô ấy, ít nhất là trên giấy tờ, nên cậu không được phép động đến cô ấy~", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","stare",0.25)
	await novel_interface.show_dialog("Hừm, được rồi...", "Ai")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_left(0,0.3,false,"normal")
	await novel_interface.show_dialog("Tôi cũng không thường trang điểm, nhưng việc đó rất đơn giản. Tôi đã ghi nhớ tất cả sau khi nhìn vào nó trong mười phút.", "Ai")
	await novel_interface.show_dialog("Bạn cũng có thể học nó một cách nhanh chóng.", "Ai")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("Nhanh đến vậy?\nĐối với tôi, đó có vẻ là một quá trình thực sự phức tạp...", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","smile",0.25)
	await novel_interface.show_dialog("Ai nhớ mọi thứ rất nhanh. Bạn nên học hỏi từ cô ấy nhiều hơn trong tương lai ~", "Mariru")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Đúng rồi...\n(Làm thế nào chính xác thì tôi phải học thứ gì đó như trí nhớ?!)", "Lian")
	await novel_interface.hide_all_characters()
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("Aghh~~\nĐầu tôi sắp nổ tung sau khi dành cả ngày để Ai ghi nhớ nhãn hiệu và màu sắc trang điểm.", "Lian")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("... Mariru! Tại sao bạn lại ở đây?!", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","speak",0.25)
	await novel_interface.show_dialog("Cái gì? Căn hộ này trước hết là một trong những nơi ở của tôi ở New Opulentia.\nHơn thế nữa, toàn bộ tòa nhà này là tài sản của SID~", "Mariru")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Thảo nào nơi này quá kỳ quặc!\nĐợi đã, đừng nói với tôi là bạn sẽ sống ở đây với Annie và tôi...", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("Tôi chỉ thỉnh thoảng ghé qua nên sẽ không ở đây thường xuyên~\nMặc dù tủ lạnh đã hết bia rồi. Lần sau nhớ mua cho em hai hộp nhé.", "Mariru")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("Nhưng hôm nay tôi ở đây với vai trò là người giám hộ của bạn... hee-hee~♪", "Mariru")
	novel_interface.character_light(0.35,"wail")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("T-tôi có một cảm giác khủng khiếp về chuyện này!!", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("Hãy đến thử những thứ này. Đây là đồng phục học sinh của bạn, Lian, và đây là một chiếc váy~", "Mariru")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Tại sao... váy này ngắn quá...", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("Một chiếc váy thực sự trông đẹp nhất ở độ dài này.", "Mariru")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Chắc chắn bạn đã thay đổi độ dài của chiếc váy này phải không?!", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("Đừng quan tâm đến những chi tiết nhỏ ~", "Mariru")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("Và ở đây chúng tôi có tất ngắn đến mắt cá chân, tất dài, quần đùi, quần tất...\nOho, và cả chiếc thắt lưng nịt tất này nữa!", "Mariru")
	novel_interface.character_light(0.35,"sob")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Làm sao lại có nhiều loại tất như thế này...?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Ngoài ra còn có các loại sọc, chắp vá, hoa văn, chấm bi khác nhau...\nỒ đúng rồi, bạn có muốn thử vớ lưới không?", "Mariru")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Tuyệt đối không!!!", "Lian")
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("Không, chờ đã! Vấn đề không phải ở đó!\nTôi không muốn mặc những thứ như thế này chút nào!!", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Nếu một nhiệm vụ yêu cầu, dù sao thì bạn cũng sẽ không có lựa chọn nào khác, vì vậy tốt nhất bạn nên làm quen với nó sớm...\nMuốn tôi giúp bạn không?", "Mariru")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0)
	await novel_interface.show_dialog("Y-Bạn... bạn...!!", "Lian")

	print("=== 第二章第13话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
