# chapter2_ep19.gd - 第二章第19话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep19_script()

func play_script():
	pass

func chapter2_ep19_script():
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("Según las estadísticas de entrenamiento, la condición física de Lian no es diferente a la del promedio de las adolescentes.", "Ai")
	await novel_interface.show_dialog("Excepto por la coordinación ojo-mano. Podría tener algo que ver con los trofeos de platino en sus cuentas de juego...", "Ai")
	await novel_interface.show_dialog("Annie se desempeña mejor cuando entrena solo. Casi tan buena como los atletas profesionales de su edad.", "Ai")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("Pero lo que detecté la segunda vez que desaparecieron en un área de flujo es totalmente diferente.", "Ai")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("¿Eh? ¿Algo interesante?", "Mariru")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Puede que la gente no pueda sentirlo, pero...", "Ai")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("La sonda Boltzmann en el dron de seguimiento se salió de los gráficos un par de veces. Ya estaba roto cuando lo rescataron.", "Ai")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"serious")
	await novel_interface.show_dialog("Imposible. Si la sonda funcionaba bien... entonces aquellos en el área de flujo... \\nDiría que casi toda el área se habría vaporizado.", "Mariru")
	await novel_interface.show_dialog("Yo diría que casi toda el área habría sido vaporizada.", "Mariru")
	novel_interface.change_2nd_expression("speak")
	await novel_interface.show_dialog("¿Y estabas loco por colocar un dispositivo tan caro en el dron?", "Mariru")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("Mariru enrolla el documento y golpea la cabeza de Ai\\nAi deja escapar un rápido gemido.")
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("Bueno… no me refiero a la energía térmica. Los aumentos abruptos de la entropía de la información también pueden conducir a los mismos resultados.", "Ai")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("Las dos chicas han hecho que este evento extremadamente improbable suceda con un 100% de certeza.", "Ai")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("Annie es una bruja, pero entonces Lian… ¿Es ella un contenedor creado por Substance H?", "Mariru")
	await novel_interface.show_dialog("Es como si Lian hubiera permitido a las brujas y su poder mágico...", "Mariru")
	novel_interface.character_light(0.35,"blush_think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("O, como una batería sobrealimentada puesta en un vibrador…", "Ai")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,false)
	await novel_interface.show_text_only("Un ruido sordo proviene de la Sala de Mando. Aparece un bulto en la cabeza de Ai.")
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("Lo siento mucho por los contribuyentes. Imagínese cuánto dinero de los impuestos se desperdicia en bichos raros como usted.", "Mariru")
	novel_interface.character_2nd_move_left(-0.25)
	novel_interface.show_character("ai","blush_stare",0.25)
	await novel_interface.show_dialog("La ciencia tiene que ver con la curiosidad y la lujuria insaciables, ¿no es así?", "Ai")
	novel_interface.character_2nd_light(0.35,"normal2")
	novel_interface.character_dark()
	await novel_interface.show_dialog("… Realmente no tienes vergüenza de decir eso.", "Mariru")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"stare")
	await novel_interface.show_dialog("¿Mencioné los extraños objetivos de investigación que estableciste para mi SRD?", "Ai")
	novel_interface.change_expression("dizzy")
	await novel_interface.show_dialog("Y tu cara me dice que estás planeando algo astuto. \\nDime, ¿qué tienes en mente?", "Ai")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Ai notó una sonrisa en el rostro de Mariru antes de que se desvaneciera.")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("Ya que han sido entrenados por un tiempo, es hora de ver qué han aprendido.", "Mariru")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("(Substance H, el Ross Goblet, Brujas, Flujo del espacio-tiempo… Todo conectado con Lian…)", "Mariru")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("(Sin ella, Annie no podría atravesar un área de flujo.) \\n(Entonces, durante los siete años en que Annie desapareció…)", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("¿Parece que estás… planeando poner en peligro a los dos adolescentes inocentes?", "Ai")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("De lo que no se puede hablar, hay que guardar silencio.", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","normal",0.25)
	await novel_interface.show_dialog("Humph. Ludwig Wittgenstein. Me gusta más otra cita suya.", "Ai")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"normal2")
	await novel_interface.show_dialog("No es cómo son las cosas en el mundo lo que es místico...", "Mariru")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("Pero que existe.", "Mariru")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("Seguramente me mantendré fiel a mis principios.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("No hay duda de eso.", "Ai")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	await novel_interface.show_text_only("Annie y de repente recibo un pedido de Mariru. Debemos regresar a nuestro apartamento inmediatamente y permanecer de guardia.")
	novel_interface.show_character("ren_uniform","gratified")
	await novel_interface.show_dialog("¿Una misión urgente?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal1",0.25)
	await novel_interface.show_dialog("Yo uh... \\n(Mirando fijamente—)", "Mariru")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"shy_left")
	await novel_interface.show_dialog("Mamá… Mariru?", "Lian")
	await novel_interface.show_dialog("(Creo ver un destello de vacilación en los ojos de Mariru…)", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","speak2",0.25)
	await novel_interface.show_dialog("Entonces, ¿el tiempo vuela cuando no nos encontramos? \\nEstás creciendo rápidamente.", "Mariru")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Sí… Aunque todavía hay cosas a las que no estoy acostumbrado.", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("¿En serio? ¿Por ejemplo?", "Mariru")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Como el aspecto del traje de batalla... \\n¡Qué humillación!", "Lian")
	await novel_interface.hide_2nd_character()
	novel_interface.show_2nd_character("anne_battle","smile",0.25)
	await novel_interface.show_dialog("¡Obviamente es genial!", "Annie")
	await novel_interface.hide_2nd_character()
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("¿La parte superior ya no te queda? \\n¿Le gustaría una nueva medida?", "Mariru")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("¡No, eso no!", "Lian")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_left(0,0.3,true)
	await novel_interface.show_text_only("Mariru se acerca a mí. Me doy cuenta de su intención y rápidamente la esquivo.")
	novel_interface.character_light(0.35,"sob")
	await novel_interface.show_dialog("¡Eh... no, no! \\n¡Encaja perfectamente!", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal1",0.25)
	await novel_interface.show_dialog("Ah.", "Mariru")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"panic")
	await novel_interface.show_dialog("(¿Por qué sientes lástima?)", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","normal")
	await novel_interface.show_dialog("¡Eep! Lian todavía está en desarrollo…", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Annie luce envidioso y triste.")
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("Annie—! \\n¿Cómo pudiste ser como ella...?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","smile")
	await novel_interface.show_dialog("¡Espero poder crecer como tú! \\n—Desafortunadamente, mi tiempo está estancado.", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Su tiempo está estancado… ¿Es porque es una bruja?")
	await novel_interface.show_text_only("Annie intenta lucir optimista, pero no puede ocultar la tristeza en sus ojos. El aire de repente se vuelve pesado.")
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("… Annie", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","happy")
	await novel_interface.show_dialog("Así que déjame sentirlos...\\n¡Ajá!", "Annie")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Annie inesperadamente me abraza por la espalda.")
	novel_interface.show_character("anne_battle","smile")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","awkward",0.25)
	await novel_interface.show_dialog("¡Oye—!", "Lian")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("… Has crecido, niña.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Mariru gira la cabeza y se seca las lágrimas en secreto.")
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("¡Tú! ¡¡Qué tontería!!", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal1",0.25)
	await novel_interface.show_dialog("Ejem, ¡de vuelta al trabajo! \\nTengo una misión urgente para ti ahora mismo.", "Mariru")
	novel_interface.change_2nd_expression("normal2")
	await novel_interface.show_dialog("¿Has oído hablar de la subestación Johnson?", "Mariru")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("¿La enorme subestación de la costa este?", "Lian")
	novel_interface.character_dark()
	await novel_interface.show_text_only("(Es un área coadministrada por las seis Ciudades Academia dentro del campo protector de Aegis. Allí se llevaron a cabo conversaciones de paz de posguerra).")
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Exacto. Acabamos de recibir alarmas de una docena de estaciones repetidoras que muestran fuertes oleadas que ocurrieron en el noreste.", "Mariru")
	await novel_interface.show_dialog("Y nuestro satélite ha detectado un flujo espacio-temporal en la subestación.", "Mariru")
	await novel_interface.hide_2nd_character()
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.character_move_right(0,0.3,true,"solemn")
	await novel_interface.show_dialog("¿Flujo del espacio-tiempo? Podría ser...", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("Si los datos son correctos, la situación sería la misma que las que atravesaste antes.", "Mariru")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("Aún no estás calificado como agente de campo...", "Mariru")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Pero la Subestación está dentro de la “Zona Desmilitarizada Acordada”, lo que significa que SID no tiene autoridad para realizar operaciones allí a pesar de que está en New Opulentia.", "Mariru")
	await novel_interface.show_dialog("Puede verse como un compromiso menor para la \"paz mundial\".", "Mariru")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("Entonces, necesito que sigas adelante para explorar la subestación. SID equipos estarán esperando en el perímetro.", "Mariru")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("Obtendré la aprobación del Congreso Unido lo antes posible.", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","wry_smile",0.25)
	await novel_interface.show_dialog("¿Quieres decir que traspasaremos la jurisdicción de la Alianza de Ciudad Academia? \\n¿Está realmente bien?", "Lian")
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("¡Ajá! Parece que alguien preferiría ver un apagón en el área de la embajada que tomar un atajo.", "Mariru")
	await novel_interface.show_dialog("Si surgen problemas, esos idiotas que se odian pueden simplemente chocar. \\nSi la situación se deteriora hasta convertirse en una guerra...", "Mariru")
	await novel_interface.show_dialog("Si la situación se deteriora hasta convertirse en una guerra...", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"panic")
	await novel_interface.show_dialog("Está bien, está bien. Lo que digas...", "Lian")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Y ustedes son solo adolescentes. Incluso si te atrapan los soldados de seguridad, puedes escapar haciéndote el lindo.", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wry_smile")
	await novel_interface.show_dialog("¡Sí, cuando los cerdos vuelan!", "Lian")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("De todos modos, esto es una orden. \\nEl helicóptero está esperando en el tejado. ¡Prepárate y listo!", "Mariru")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"sprite")
	await novel_interface.show_dialog("Que dictador....", "Lian")

	print("=== 第二章第19话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
