# chapter2_ep13.gd - 第二章第13话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep13_script()

func play_script():
	pass

func chapter2_ep13_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Avant d'aller dans votre nouvelle école, votre première mission est une formation aux connaissances de base.", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","worry",0.25)
	await novel_interface.show_dialog("Connaissances de base ?\nCe n'est pas comme si j'étais Annie et que j'avais raté tout ce qui s'est passé ces dernières années...", "Lian")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Hé. Vous avez manqué plus d'une décennie de connaissances sur le fait d'être une fille, n'est-ce pas ?~", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wry_smile")
	await novel_interface.show_dialog("Je n'ai pas besoin de ce genre de connaissances !", "Lian")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru a complètement ignoré ma protestation et s'est dirigé vers la table de bonne humeur. Ce n’est qu’à ce moment-là que j’ai remarqué qu’elle avait déjà préparé tout le plateau avec toutes sortes d’outils imaginables.")
	novel_interface.show_character("liliu_research","speak")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_battle","wry_smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Tout d’abord, vous devez être capable de distinguer douze nuances de rouge à lèvres standards et de mémoriser les vingt principales marques.", "Mariru")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("Tant de...?\nLes couleurs ne sont-elles pas fondamentalement toutes les mêmes ?", "Lian")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"smile")
	await novel_interface.show_dialog("Trop naïf ! Cela ne représente même pas un dixième du total.", "Mariru")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Et ici, j'ai préparé pour vous un ensemble complet d'outils de maquillage : fond de teint, fard à paupières, brillant à lèvres, surligneur, contouring...", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("Hein ? Je dois mettre autant de trucs sur mon visage ?!\nCe n'est pas comme si je peignais... C'est vraiment compliqué d'être une fille, exactement... ?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","speak",0.25)
	await novel_interface.show_dialog("Ne vous inquiétez pas. À partir d’aujourd’hui, quelqu’un vous apprendra correctement à vous maquiller.", "Mariru")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Mais les lycéens n'ont même pas le droit de se maquiller...", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("Vous ne comprenez vraiment pas le monde des lycéennes....\nSi vous continuez à agir de manière aussi imprudente, les gens deviendront méfiants en un rien de temps.", "Mariru")
	novel_interface.change_2nd_expression("speak")
	await novel_interface.show_dialog("Et en plus de l'école, en tant qu'agent SID, vous devrez accomplir toutes sortes de missions. Le maquillage est l’une des compétences essentielles d’une femme opératrice.", "Mariru")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("Surtout avec un joli petit visage comme le tien...", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru a tendu un doigt et a incliné mon menton vers le haut.")
	await novel_interface.show_text_only("J'ai reculé d'un pas pour éviter sa main. D'une manière ou d'une autre, ma fierté masculine ne pouvait tout simplement pas l'accepter.")
	novel_interface.show_character("ren_battle","shy_left")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_research","happy",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("J'ai déjà fait du bénévolat, bien sûr...\nMais je ne m'attendais pas à devoir apprendre des choses comme ça...", "Lian")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"smile")
	await novel_interface.show_dialog("Les évaluations des cadets de SID sont extrêmement strictes. Chaque tour élimine un énorme groupe de personnes.", "Mariru")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("Puisque vous avez parlé d’un si gros match, pourquoi ne pas faire vos preuves ?", "Mariru")
	await novel_interface.show_dialog("Et si vous réussissez l'évaluation finale, vous serez officiellement inscrit sur la liste, avec en plus un salaire très décent~", "Mariru")
	novel_interface.character_2nd_move_left(-0.25)
	novel_interface.show_character("ren_battle","smile",0.25)
	await novel_interface.show_dialog("Hein ? Je peux aussi être payé ?!\n(Et puis mon panier Gfat...)", "Lian")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Très bien, la fierté masculine peut rester dans un coin pour le moment.")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"speak")
	await novel_interface.show_dialog("(Hehehe... quel simple petit morveux.)", "Mariru")
	novel_interface.change_2nd_expression("angry")
	await novel_interface.show_dialog("Mais en retour, vous feriez mieux de comprendre ceci : en tant que commandant, mes ordres sont absolus, et vous y obéirez sans condition !", "Mariru")
	novel_interface.character_2nd_move_left(-0.25)
	novel_interface.show_character("ren_battle","worry",0.25)
	await novel_interface.show_dialog("Dans quoi est-ce que je m'embarque ?... ?", "Lian")
	novel_interface.character_2nd_light(0.35,"speak")
	novel_interface.character_dark()
	await novel_interface.show_dialog("Tout d’abord, permettez-moi de vous présenter quelqu’un : le professeur qui s’est porté volontaire pour vous apprendre le maquillage.", "Mariru")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("Bien que ses responsabilités habituelles soient le développement de médicaments expérimentaux et d'équipements spéciaux...", "Mariru")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("Oh... tu dois être Lian, non ?\nHehe~ Ce profil est vraiment intéressant~", "Fille avec des lunettes")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Salut ~ Je suis le directeur du département de recherche sur le combat de SID. Puisque nos deux fichiers ont été modifiés, vous pouvez simplement m'appeler Ai.", "Fille avec des lunettes")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("Bonjour...\n(Son fichier... a également été modifié ?)", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","blush_wink",0.25)
	await novel_interface.show_dialog("Mariru, Lian est un excellent matériel de recherche....\nTu ne peux pas me la prêter un petit moment~!?", "Ai")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("(Du matériel de recherche...? Me prêter... ?)", "Lian")
	await novel_interface.show_dialog("(W-Pourquoi mon dos est-il soudainement un peu froid...)", "Lian")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("Je suis son tuteur, du moins sur le papier, donc tu n'as pas le droit de bouger sur elle~", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","stare",0.25)
	await novel_interface.show_dialog("Hmph, bien...", "Ai")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_left(0,0.3,false,"normal")
	await novel_interface.show_dialog("Je ne me maquille pas non plus habituellement, mais c'est simple. J’ai tout mémorisé après l’avoir regardé pendant dix minutes.", "Ai")
	await novel_interface.show_dialog("Vous devriez également pouvoir l’apprendre rapidement.", "Ai")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("Si vite ?\nCela m'a semblé être un processus vraiment compliqué...", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","smile",0.25)
	await novel_interface.show_dialog("Ai se souvient de tout rapidement. Tu devrais apprendre davantage d'elle à l'avenir ~", "Mariru")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Exactement...\n(Comment suis-je censé apprendre quelque chose comme la mémoire ?!)", "Lian")
	await novel_interface.hide_all_characters()
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("Aghh~~\nMa tête est sur le point d'exploser après avoir passé toute la journée à Ai mémoriser des marques et des couleurs de maquillage.", "Lian")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("... Mariru ! Pourquoi es-tu ici ?!", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","speak",0.25)
	await novel_interface.show_dialog("Quoi ? Cet appartement est l'une de mes résidences à New Opulentia pour commencer.\nPlus que cela, tout ce bâtiment est la propriété de SID~", "Mariru")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Pas étonnant que cet endroit soit si scandaleux !\nAttends, ne me dis pas que tu vas vivre ici avec Annie et moi...", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("Je ne passe que de temps en temps, donc je ne resterai pas souvent ici~\nMême si le réfrigérateur n'a déjà plus de bière. La prochaine fois, n'oublie pas de m'acheter deux valises.", "Mariru")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("Mais aujourd'hui, je suis ici spécifiquement dans mon rôle de tuteur... hee-hee~♪", "Mariru")
	novel_interface.character_light(0.35,"wail")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("J'ai un terrible pressentiment à ce sujet !!", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("Venez les essayer. Ceci est votre uniforme scolaire, Lian, et celui-ci est une robe~", "Mariru")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Pourquoi... cette jupe est-elle si courte...", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("Une jupe est vraiment plus belle à cette longueur.", "Mariru")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Vous avez définitivement modifié la longueur de cette jupe, n'est-ce pas ?!", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("Ne vous inquiétez pas des petits détails ~", "Mariru")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("Et ici, nous avons des socquettes, des chaussettes ras du cou, des cuissardes, des collants...\nOho, et ce porte-jarretelles aussi !", "Mariru")
	novel_interface.character_light(0.35,"sob")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Comment existe-t-il aussi autant de types de chaussettes... ?", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Il existe également différents types de rayures, de patchwork, de motifs, de pois...\nOh oui, tu veux essayer les bas résille ?", "Mariru")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Absolument pas !!!", "Lian")
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("Non, attends ! Ce n'est pas le sujet !\nJe ne veux pas du tout porter des trucs comme ça !!", "Lian")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("Si une mission l'exige, vous n'aurez de toute façon pas le choix, alors autant vous y habituer tôt....\nVous voulez que je vous aide ?", "Mariru")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0)
	await novel_interface.show_dialog("V-Vous... vous... !!", "Lian")

	print("=== 第二章第13话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
