# chapter2_ep02.gd - 第二章第2话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep02_script()

func play_script():
	pass

func chapter2_ep02_script():
	novel_interface.change_music("res://assets/audio/music/Barrier Maze.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/spSoundChannel.png")
	await novel_interface.show_dialog("¡Atención a todos los equipos, las fluctuaciones de fase están disminuyendo!", "Agente A")
	await novel_interface.show_dialog("¡¡El enemigo puede emerger en cualquier momento!\n¡¡Mantengan sus posiciones y prepárense para atacar!!", "Agente A")
	await novel_interface.show_dialog("... ¡R-informe!", "Agente B")
	await novel_interface.show_dialog("Dos unidades humanoides han aparecido dentro del alcance visual, justo en la zona central de la anomalía...", "Agente B")
	await novel_interface.show_dialog("Humanos...?\n¿Cómo es eso posible? ¿Qué mostró el escaneo memético?", "Agente A")
	await novel_interface.show_dialog("¡¡El tono es...\nVerde!!", "Agente B")
	await novel_interface.show_dialog("Parecen ser dos chicas jóvenes...\n¡Detén el fuego! ¡Detén el fuego!", "Agente B")
	await novel_interface.show_dialog("...", "Agente A")
	await novel_interface.show_dialog("Acabamos de recibir órdenes: la prioridad uno es asegurarlos y traerlos de regreso a la sede.\nEnvíe un agente superior para negociar—", "Agente A")
	await novel_interface.show_dialog("Todos los demás, manténganse alerta. ¡Si los objetivos hacen algún movimiento sospechoso durante las negociaciones, elimínalos inmediatamente!", "Agente A")
	await novel_interface.show_dialog("¡Entendido!", "Agente B")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_outside.png")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("Nos dirigimos con cuidado hacia la salida del centro de investigación.")
	await novel_interface.show_text_only("Lo que nos esperaba allí, además de la calle familiar, era una línea de cinta de barricada y una fila de personas armadas detrás de ella, listas para recibirnos.")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("¡¿Por qué apareció tanta gente de repente?!", GameConfig.player_name)
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("¡¡Ah—Annie!\n¡¡Date prisa y vuelve a cambiarme de ropa!!", GameConfig.player_name)
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("Esta ropa es demasiado vergonzosa...\nRealmente no quiero que nadie me vea así...", GameConfig.player_name)
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_battle","worry",0.25)
	await novel_interface.show_dialog("¿Es eso realmente lo que te preocupa ahora?", "Annie")
	novel_interface.change_2nd_expression("uneasy")
	await novel_interface.show_dialog("Toda tu ropa estará segura conmigo, así que no te preocupes...", "Annie")
	await novel_interface.show_dialog("Si realmente quieres cambiarte, simplemente quítate ese 'traje de batalla' que estás usando ahora y vuelve a ponerte tu ropa holgada habitual~", "Annie")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("Pero hay muchos hombres más adelante...\n¿De verdad quieres cambiar justo delante de ellos?", "Annie")
	novel_interface.character_light(0.35,"shy_right")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Ugh...\nPero soy un gu...", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("Ahora que lo pienso... ¡antes vestías ropa de hombre!\n¿Podría ser—?", "Annie")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("¿Eh? ¿Tú también has estado en una situación como esta antes?", GameConfig.player_name)
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("(Eso tiene sentido... Annie probablemente tampoco sea una persona común y corriente, ¿verdad?)", GameConfig.player_name)
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("(Si es Annie, tal vez ella pueda entender por lo que estoy pasando...)", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("Mmm, lo entiendo...", "Annie")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("Eres del tipo que en secreto toma prestada la ropa de un chico que te gusta y la usa tú mismo, ¿verdad?", "Annie")
	novel_interface.character_light(0.35,"wail")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("¡¡¡Eso no es \"entenderlo\" en absoluto!!!", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("Mhm~ Entonces, en realidad,"+GameConfig.player_name+"Es el tipo de persona que queda cautivada por el olor del sexo opuesto, ¿eh? No hay necesidad de avergonzarse...", "Annie") #文本变化important
	novel_interface.character_light(0.35,"sob")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("¡¡¡No pongas esa cara de: 'Puede que seas un pervertido, pero te aceptaré de todos modos'!!!", GameConfig.player_name)
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("Suspiro... Todavía no tengo la menor idea de por qué he quedado así...", GameConfig.player_name)
	novel_interface.character_dark()
	await novel_interface.show_text_only("...")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("¡Detente ahí!\n¡Pon tus manos donde pueda verlas!", "SID Agente")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Una persona con traje negro se adelantó y nos gritó.")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("ren_battle","awkward",0.25)
	await novel_interface.show_dialog("¿Eh...?\n¿Creen que somos los malos?", GameConfig.player_name)
	novel_interface.change_2nd_expression("panic")
	await novel_interface.show_dialog("(Espera, esa insignia en el pecho del líder...)\n(Un escudo perfectamente redondo con forma de anillo, no me digas que es...)", GameConfig.player_name)
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0)
	await novel_interface.show_dialog("Ustedes dos, soy un agente SID.\nPor su propia seguridad, mantengan esa postura y no se muevan.", "SID Agente")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_text_only("Tal como pensaba, ¡¡¡están con SID!\n¡¡¡Ya estamos jodidos!!!")
	await novel_interface.show_text_only("En un instante, mi mente se llenó de noticias sobre SID enviando enjambres de agentes para capturar espías.")
	novel_interface.change_expression("sob")
	await novel_interface.show_text_only("Y luego estaban las leyendas urbanas sobre 'prisiones secretas', 'operaciones de asesinato' y cosas por el estilo...")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("Informe de la zona central de cuarentena: los dos objetivos no han mostrado ninguna intención hostil.\nNivel de amenaza fijado provisionalmente en D+.", "SID Agente")
	await novel_interface.show_dialog("Comencemos con algunas preguntas simples...\n¿Quién eres y qué haces escondiéndote por aquí?", "SID Agente")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("Soy estudiante de esta ciudad...", GameConfig.player_name)
	novel_interface.change_expression("wail")
	await novel_interface.show_dialog("Acabamos de venir aquí en una excursión para recorrer el instituto de investigación...", GameConfig.player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("El agente de negro nos miró con desdén.")
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("¿Es así... una gira? ¿Del instituto?", "SID Agente")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_text_only("Oh no...\nDe repente recordé—")
	await novel_interface.show_text_only("Debido a la desaparición de la 'Copa Roskin', el instituto quedó cerrado de emergencia desde anoche.")
	novel_interface.change_expression("sob")
	await novel_interface.show_text_only("Salir de allí descaradamente en un momento como este y afirmar que solo estábamos de visita... eso fue básicamente una confesión.")
	await novel_interface.show_text_only("Como era de esperar, pareció recibir algún tipo de instrucción a través de su auricular y me miró con severidad.")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("agent","",0.25)
	await novel_interface.show_dialog("He recibido órdenes de mi superior. Ustedes dos vendrán con nosotros.", "SID Agente")
	novel_interface.character_move_right(0,0.3,false)
	novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("En el lapso de sólo unos segundos, los dos estábamos completamente rodeados.")
	await novel_interface.show_text_only("Dondequiera que mirara, había una pared de cañones de armas apuntando directamente hacia nosotros.")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("anne_battle","worry",0.25)
	await novel_interface.show_dialog(GameConfig.player_name+", estas personas parecen muy malas noticias...\n¿Por qué no esperamos una oportunidad y la aprovechamos?", "Annie")
	novel_interface.character_move_left(-0.3,0.3,false)
	novel_interface.character_2nd_move_left(0)
	novel_interface.show_3rd_character("agent","",0.3)
	await novel_interface.show_dialog("Tenga la seguridad de que no le haremos daño.\nMientras coopere con la investigación, todo esto se puede resolver pacíficamente.", "SID Agente")
	await novel_interface.show_dialog("Debes entender que la desaparición de un \"objeto anómalo\" no es un asunto baladí. Podría desencadenar eventos que van mucho más allá del sentido común, así que coopere.", "SID Agente")
	await novel_interface.hide_3rd_character()
	novel_interface.character_move_right(-0.25,0.3,true,"worry")
	novel_interface.character_2nd_move_right(0.25,0.3,false)
	await novel_interface.show_dialog("(¿Eventos más allá del sentido común...?)", GameConfig.player_name)
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("Está bien, lo entiendo. Yo iré contigo.", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("¿Eh? ¡¿Por qué simplemente vas con ellos?!\n¡Oye!"+GameConfig.player_name+"!", "Annie")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("¡Q-deja de tirar! ¡Se me va a caer la estúpida falda!", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("¡Tú eres el idiota! ¿Por qué irías con gente tan sospechosa? ¿Qué pasa si te drogan y te venden en alguna parte?", "Annie")
	novel_interface.character_light(0.35,"shy_right")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("¿Qué querría alguien de un chico adulto como yo?...", GameConfig.player_name)
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("Espera, no, ¿quién montaría una operación de trata de personas con tanta gente montando semejante escena?", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"frustrate")
	await novel_interface.show_dialog(GameConfig.player_name+", obviamente nunca has visto las pandillas en las Islas Lebona...", "Annie")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("De todos modos... tal vez finalmente podamos aprender algo.\nVayamos con ella por ahora...", GameConfig.player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("Bien. Donde quiera que vayas, yo también iré...", "Annie")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Um, si es posible, ¿podría conseguir un abrigo primero?", GameConfig.player_name) 
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("Este conjunto es realmente un poco...", GameConfig.player_name)
	novel_interface.character_dark()
	await novel_interface.show_text_only("Ser observada por todos mientras vestía como una niña hizo que todo mi cuerpo se sintiera incómodo.")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("Muy bien, haré una solicitud.", "SID Agente")
	await novel_interface.show_dialog("...", "SID Agente")
	await novel_interface.show_dialog("...Lo siento, mi superior dijo: 'Ese conjunto es muy lindo' y rechazó rotundamente la solicitud.", "SID Agente")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("¡¿Qué clase de superior dice algo así?!", GameConfig.player_name)

	print("=== 第二章第2话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
