# chapter2_ep24.gd - 第二章第24话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep24_script()

func play_script():
	pass

func chapter2_ep24_script():
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/bedRoom.png")
	await novel_interface.show_text_only("De volta ao apartamento, Elluka ainda está agarrada às minhas roupas, mesmo durante o sono.")
	await novel_interface.show_text_only("Annie e Mariru ordenam que eu me vire e não espie, então forme uma parede humana enquanto eles removem as manoplas de metal e o casaco rasgado de Elluka e a trocam por roupas comuns.")
	await novel_interface.show_text_only("Aí eles me fazem jurar pela minha vida que não farei mal a Elluka, antes de me permitirem levá-la para o meu quarto.")
	await novel_interface.show_text_only("...Agora Elluka está dormindo na minha cama, ainda segurando minhas roupas, então tudo que posso fazer é sentar ao lado dela.")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("Por que você é tão pegajoso, garoto? \\nDeus, estou tão cansado...", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Depois de uma noite inteira de operação, estou completamente exausto. Quando caio na cama, sinto o papel no bolso.")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("Annie disse que estes são… os Fragmentos do Grimório?", "Lian")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("Elluka parecia querer isso e olhou para mim como um animal de estimação fofo…", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Deitado na cama, examino as páginas mais uma vez. Mas o conteúdo é tão incompreensível quanto o que apareceu anteriormente.")
	await novel_interface.show_text_only("Conforme viro as páginas, algumas páginas escorregam da minha mão e caem no corpo de Elluka.")
	await novel_interface.show_text_only("No momento em que as páginas tocam seu corpo, um brilho azulado aparece de repente.")
	await novel_interface.show_text_only("Uma onda de símbolos e palavras irrompeu das páginas e até o ar do meu quarto começou a tremer.")
	await novel_interface.show_text_only("De repente, as páginas restantes parecem arrastadas por alguma força invisível em direção ao corpo de Elluka.")
	await novel_interface.show_text_only("Há uma explosão de luz ofuscante e então tudo desaparece.")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("O-O que é isso—?!", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_normal","normal")
	await novel_interface.show_dialog("Pesquisa iniciada. Alvo identificado —\\nChocolate... irmã mais velha!", "Elluka")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("Elluka?! Você está acordado!", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elluka de repente joga os braços em volta de mim. Ao mesmo tempo, a porta atrás de mim é aberta.")
	novel_interface.show_character("anne_battle","perspire")
	await novel_interface.show_dialog("Ei, o que foi aquele tremor?\\n...Espere, você finalmente avançou Elluka?!", "Annie")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Annie olha para mim como se eu fosse um pervertido.")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("ren_battle","perspire1",0.25)
	await novel_interface.show_dialog("Não é o que você pensa. Deixe-me explicar!", "Lian")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_left(-0.25)
	novel_interface.show_character("iluka_normal","normal",0.25)
	await novel_interface.show_dialog("Energia, cheia.\\nPesquisa... alvo não encontrado.", "Elluka")
	novel_interface.character_2nd_light(0.35,"worry")
	novel_interface.character_dark()
	await novel_interface.show_dialog("Por que, quem você está procurando?", "Lian")
	novel_interface.character_2nd_dark()
	novel_interface.character_light(0.35,"sleepy")
	await novel_interface.show_dialog("… Administrador, do Tribunal.", "Elluka")
	novel_interface.character_2nd_light(0.35,"perspire1")
	novel_interface.character_dark()
	await novel_interface.show_dialog("O Tribunal...? O que é isso?\\nDe qualquer forma, vamos pegar Mariru e descobrir o que fazer.", "Lian")
	await novel_interface.hide_all_characters()
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	novel_interface.show_character("liliu_research","shock")
	await novel_interface.show_dialog("Tribunal… Vocês estão me colocando em apuros. Seu amigo é membro da Congregação.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("Hein? O que é isso?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("Enquanto pesquisava sobre bruxas, tomei conhecimento dessas estranhas organizações clandestinas, incluindo a Congregação, a mais antiga do gênero.", "Mariru")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("A Congregação posteriormente se dividiu em diferentes facções, e o Tribunal é uma delas.", "Mariru")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Desde que se separou há centenas de anos, o Tribunal tem ameaçado exterminar todas as bruxas e orquestrou a infame Caça às Bruxas.", "Mariru")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("Detesto lidar com grupos tão supersticiosos.", "Mariru")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("Eu estava planejando originalmente colocar Elluka em uma escola infantil em New Opulentia...\\nMas dadas as circunstâncias, não posso simplesmente deixá-la ir.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("Você deve ter outros planos. É melhor você não realizar nenhuma pesquisa estranha sobre ela…", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","happy",0.25)
	await novel_interface.show_dialog("Eu sou tão ruim assim aos seus olhos?", "Mariru")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Mariru bate minha cabeça. \\nElluka faz beicinho e olha para Mariru com raiva.")
	novel_interface.show_character("iluka_normal","unhappy")
	await novel_interface.show_dialog("Alvo identificado. Classificação de ameaça, extremamente alta.", "Elluka")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","normal",0.25)
	await novel_interface.show_dialog("… Pirralho.", "Mariru")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("Ah, Elluka, que tarefa Jacob lhe deu?", "Lian")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Elluka franze a testa e lentamente se lembra de sua tarefa—")
	novel_interface.show_character("iluka_normal","worry")
	await novel_interface.show_dialog("Primeiro, extermine as bruxas. Concluído. \\nSegundo, obtenha o manuscrito. Fracassado.", "Elluka")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","worry")
	await novel_interface.show_dialog("O manuscrito? Não é Lian quem tem?", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_normal","worry")
	await novel_interface.show_dialog("Procurando… Exceção de status. \\nManuscrito… consumido.", "Elluka")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","perspire1",0.25)
	await novel_interface.show_dialog("Consumido? Você quer dizer que as páginas estão dentro de você agora?\\nOu elas faziam parte do grimório de Elluka o tempo todo?", "Lian")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_dialog("Seu administrador não deixou você absorvê-los...\\nEle estava com medo de que você se tornasse poderoso demais para ele controlar?", "Lian")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_battle","smile")
	await novel_interface.show_dialog("Essa é uma história completa com apenas algumas palavras dela, Lian. Bom trabalho!", "Annie")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("Espere, Grimório de Elluka. \\nO que significa…", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("Essa criança também é uma bruxa?", "Mariru")
	novel_interface.character_dark()
	await novel_interface.show_text_only("Mariru tenta beliscar sua bochecha, mas Elluka se esquiva agilmente.")
	novel_interface.character_light(0.35,"smile")
	await novel_interface.show_dialog("Há muito tempo ouço que alguns grupos tentam criar e controlar bruxas. Não faltam carreiristas morrendo de vontade de ter supersoldados!", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("Como vocês dois sabem tanto sobre bruxas...? Eu sou o único no escuro aqui. Diga-me: como uma garota se torna uma bruxa?", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","worry")
	await novel_interface.show_dialog("Uh, no começo eu também não tinha certeza. Lembro-me de ter lido aquele livro sem saber o que era.", "Annie")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Comecei a sentir tonturas à medida que o conteúdo se tornava cada vez mais difícil. Então, a certa altura, senti como se uma força desconhecida tivesse entrado em meu corpo.", "Annie")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("Um dia, pronunciei um feitiço do livro e fui arrastado para outro espaço-tempo…", "Annie")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","smile",0.25)
	await novel_interface.show_dialog("Espaço-tempo… Segundo dados de satélite, o Fluxo do Espaço-Tempo já havia parado quando você chegou à subestação.", "Mariru")
	novel_interface.character_light(0.35,"perspire")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("Não é à toa que não tive a mesma sensação que tive em outras Áreas de Fluxo!", "Annie")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("O que você chama de Área de Fluxo é referido na antiga literatura de bruxas como “Casulo de Bruxa”.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,false)
	await novel_interface.show_dialog("Ela se forma quando um humano se transforma em uma bruxa. Pessoas de fora não podem quebrá-lo nem entrar nele. É de natureza muito semelhante a um espaço gerado por Substance H, você não acha?", "Mariru")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("E quase no momento em que o fluxo desapareceu, nosso satélite detectou sinais ópticos—", "Mariru")
	novel_interface.change_2nd_expression("speak")
	await novel_interface.show_dialog("Quero dizer, os caras contra quem você lutou apareceram.", "Mariru")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("Pense nisso – “Witch’s Cocoon”… No momento em que o casulo desapareceu, esses caras apareceram. É como se tivessem saído do casulo.", "Mariru")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("iluka_normal","unhappy")
	await novel_interface.show_dialog("Bruxa, termine!", "Elluka")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("Então as bruxas realmente perderam a cabeça porque não conseguem suportar as informações do Grimório!?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_battle","worry",0.25)
	await novel_interface.show_dialog("Elas eram apenas garotas normais. Eles não suportaram o poder mágico vindo dos roteiros e ficaram feridos.", "Annie")
	await novel_interface.show_dialog("No momento em que desencadearam uma violenta distorção espacial, eles se tornaram...\\nOs seres monstruosos que as pessoas chamam de \"Bruxas\".", "Annie")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("É dito em muitos livros antigos que quanto mais informações sobre o poder mágico alguém conhece, mais facilmente ele sofre de loucura irreversível.", "Mariru")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("Se perderem a sanidade, as bruxas poderão causar grandes desastres. Se isso for verdade…", "Mariru")
	await novel_interface.show_dialog("Então esta pode ser a razão pela qual a Caça às Bruxas durou tanto tempo na Europa.", "Mariru")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","perspire1",0.25)
	await novel_interface.show_dialog("Merda. Parece uma pandemia.", "Lian")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"angry")
	await novel_interface.show_dialog("De acordo com o que sabemos, o Administrador de Elluka priorizou a caça às bruxas como forma de recuperar os Fragmentos do Grimório.", "Mariru")
	await novel_interface.show_dialog("Mas ele não permitiu que Elluka usasse o Grimório… Talvez ele queira criar mais bruxas com ele.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("Mas eu li o Grimório de Elluka e não reconheci uma única palavra. Isso tem alguma coisa a ver com o fato de eu ser um menino?", "Lian")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("iluka_normal","worry",0.25)
	await novel_interface.show_dialog("… Rapaz?", "Elluka")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("Elluka parece nervosa e dá um passo para trás, com o rosto confuso.")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("Uh, Elluka, explicarei isso mais tarde. \\nNão se preocupe…", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","uneasy")
	await novel_interface.show_dialog("Mas eu poderia ler. Então talvez Lian seja realmente apenas um idiota, afinal?", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("Estou mais curioso para saber como você poderia entrar facilmente no Casulo da Bruxa.", "Mariru")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("Eu não pedi isso! Cada vez que entro na área sempre tem alguém querendo me matar…", "Lian")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("—O que você fez envolveu cruzar múltiplas dimensões. A ciência não pode explicar isso no momento.", "Mariru")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("Se a ciência pode explicar alguma coisa aqui, a primeira coisa que quero saber é por que me transformei em menina!")
	novel_interface.show_character("anne_battle","smile")
	await novel_interface.show_dialog("Hee-hee, apenas deixe isso de lado. Qualquer dúvida será resolvida mais cedo ou mais tarde!", "Annie")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("Isso é pensamento positivo…", "Lian")

	print("=== 第二章第24话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
